### ISSUE TITLE
Modal changes screen position to top

### ISSUE THREAD

**Issue by jeffwhelpley** [angular-ui/bootstrap#1016]
When I use a modal that slides down from the top and adds an overlay to the screen, the screen underneath the overlay automatically scrolls up the page a little bit (about one screen length). This does not match the Bootstrap modal behavior and is not good UX. Is there a way to ensure the screen stays in the same position?

**Comment by pascaliske** [comment]
@mikesigs Awesome! Your answer helped me a lot!

In our case (bower:angular-bootstrap@^0.12.0) the modal is wrapped in an if-statement (see source below).
I could fix this bug with an simple hidden input including an **autofocus**-attribute in the modal content (again, see source below).
This prevents the modal to manual focus itself which causes a unexpected jump to the top in IE...

###### source code of `angular-ui / modal`:
```js
link: function (scope, element, attrs) {
  element.addClass(attrs.windowClass || '');
  scope.size = attrs.size;

  $timeout(function () {
    // trigger CSS transitions
    scope.animate = true;

    /**
     * Auto-focusing of a freshly-opened modal element causes any child elements
     * with the autofocus attribute to lose focus. This is an issue on touch
     * based devices which will show and then hide the onscreen keyboard.
     * Attempts to refocus the autofocus element via JavaScript will not reopen
     * the onscreen keyboard. Fixed by updated the focusing logic to only autofocus
     * the modal element if the modal does not contain an autofocus element.
     */
    if (!element[0].querySelectorAll('[autofocus]').length) {
      element[0].focus();
    }
  });

[...]
```

###### template source of modal-content:
```html
<input type="hidden" name="fixIEJump" autofocus="" />
```
