### ISSUE TITLE
Add orientation options for tabs

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular-ui/bootstrap#102]
Bootstrap 2.2.x introduced orientation options for tabs (see "Tabbable in any direction" under http://twitter.github.com/bootstrap/components.html#navs).

`Left` and `right` orientations should be trivial to implement. `Bottom` will require a switch in a template (or a separate template).

**Comment by hugsbrugs** [comment]
Hi, I've created a gist for what we need : https://gist.github.com/hugsbrugs/c85a6b1c10d03e8cb0da

is there any chance for angular ui team to have a look at it to get the idea incorporated in next releases because I can't figure out the interest of vertical tabs without content on it's right ?

**Comment by karianna** [comment]
@hugsbrugs Can you try with 0.13.0 and open a new issue if required.

**Comment by gtesslerge** [comment]
hi @karianna @hugsbrugs

I try all of the above and still get the panels BELOW the tabs when they need to be to the right of the panels.  Any advice?
thanks

+--------------+ +-------------------------------------+
|              |      |                                     |
+--------------+ |                                     |

+--------------+ |                                     |
|              | |                                     |
+--------------+ |                                     |
                 |                                     |
                 |                                     |
                 |                                     |
                 |                                     |
                 +-------------------------------------+
                                                        
                                                        
+-------------+                                         
|             |                                         
+-------------+                                         
+-------------+                                         
|             |                                         
+-------------+                                         
+--------------------------------------------+          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
+--------------------------------------------+

**Comment by gtesslerge** [comment]
hi @karianna @hugsbrugs

I try all of the above and still get the panels BELOW the tabs when they need to be to the right of the panels.  Any advice?
thanks

+--------------+ +-------------------------------------+
|              |      |                                     |
+--------------+ |                                     |

+--------------+ |                                     |
|              | |                                     |
+--------------+ |                                     |
                 |                                     |
                 |                                     |
                 |                                     |
                 |                                     |
                 +-------------------------------------+
                                                        
                                                        
+-------------+                                         
|             |                                         
+-------------+                                         
+-------------+                                         
|             |                                         
+-------------+                                         
+--------------------------------------------+          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
+--------------------------------------------+

**Comment by gtesslerge** [comment]
hi @karianna @hugsbrugs

I try all of the above and still get the panels BELOW the tabs when they need to be to the right of the panels.  Any advice?
thanks

**Comment by gtesslerge** [comment]
hi @karianna @hugsbrugs

I try all of the above and still get the panels BELOW the tabs when they need to be to the right of the panels.  Any advice?
thanks
