### ISSUE TITLE
Add add-to-body option for dropdown

### ISSUE THREAD

**Issue by KrisBraun** [angular-ui/bootstrap#1030]
Just as tooltip (and now datepicker via #998) support an add-to-body option, it would be handy to have it for dropdown-toggle.

**Comment by cameronwilby** [comment]
Would be really handy to have, has saved me a number of times with tooltips and popovers so I was expecting this for dropdowns.

**Comment by verbumfeit** [comment]
+1

Just ran into this issue and would love an append-to-body option.

**Comment by amcdnl** [comment]
Open to PRs for this, I don't think this is in the immediate roadmap

**Comment by brafkind** [comment]
+1

**Comment by rysilva** [comment]
I have something working locally, I'll create a PR once I give it a once-over.

**Comment by rysilva** [comment]
@caitp To your concerns, is it against protocol do `element.find('.dropdown-menu').appendTo('body');`? Since we're depending on bootstrap, and this is the way to specify the dropdown menu, it should probably work although less clean.  Alternatively I could specify a directive on the menu.

**Comment by sheymann** [comment]
+1

**Comment by dzwillia** [comment]
This issue plagued me for awhile as well.

The code below is a bit of a kludge, but it works.  It clones the dropdown and marshals the click events back to the items in the original dropdown (in case you've been good about event delegation).  Hook the following code up to `shown.bs.dropdown`.  If you'd prefer, you can take a look at the fix on JsFiddle: http://jsfiddle.net/8rr0xsy8/

        this.onFixedDropdownShown = function(evt)
        {
            // store the dropdown menu for later use
            var $dropdown = $(this),
                $dropdown_menu = $dropdown.find('.dropdown-menu');

            var off = $dropdown_menu.offset();

            // clone this dropdown menu
            var $fixed_dropdown_menu = $dropdown_menu.clone(true);

            // hide this dropdown menu
            $dropdown_menu.addClass('invisible');

            // position the cloned dropdown menu relative to the document body and show it
            $fixed_dropdown_menu.css({
                    'display': 'block',
                    'position': 'fixed',
                    'top': off.top+'px',
                    'left': off.left+'px'
                })
                .appendTo('body');

            // pass-through click events to original dropdown menu
            var i = 0;
            $fixed_dropdown_menu.find('a').each(function() {
                var $related_anchor = $dropdown_menu.find('a').eq(i);

                $(this).on('click', function() {
                    $dropdown_menu.removeClass('invisible');
                    $related_anchor.click();
                });

                i++;
            });

            // remove the cloned dropdown
            $dropdown.on('hidden.bs.dropdown', function() {
                $dropdown_menu.removeClass('invisible');
                $fixed_dropdown_menu.remove();
            });
        }

Again, it works, but It's not really optimized -- if anyone cares to do so, feel free... :-)

**Comment by amcdnl** [comment]
Federnando's solution does not work if you scroll
