### ISSUE TITLE
ng-model values are not available in the controller scope!

### ISSUE THREAD

**Issue by dotansimha** [angular-ui/bootstrap#1052]
Adding this line to the modal view:

```
<input type="text" ng-model="test" />
```

And then is the ModalInstanceCtrl trying to access:

```
console.log($scope.test);
```

and the value is undefined!

Same code works great with 0.5.0 and $dialog

Plunkr is available here:
http://plnkr.co/edit/puTGkLxMb0LA7721Lzrf?p=preview
(Change the input's value inside the modal window, click "Ok" and then look at the log)

**Comment by kkduniya** [comment]
thaks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by kkduniya** [comment]
Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by admakwana** [comment]
Thanks a lot man!!!!!!!!!
