### ISSUE TITLE
How can I close a popover when clicking outside it?

### ISSUE THREAD

**Issue by tschofen** [angular-ui/bootstrap#1055]
I have multiple popovers on a page that are each opened by a link. I'd like a popover to disappear when I click anywhere outside it's space (just like the tooltip-trigger: focus). 

How would I go about this?

**Comment by Radnyeechins** [comment]
hello everyone hope everyone doing fine 
my questions is ...
i want to close popover if it content input field....
here is demo
http://plnkr.co/edit/sIQevsrtTStDvqvG9ot4?p=preview 
add groups and click on the tabs then rename tab but if we click outside then it doesn't close, it closed iff we click on same tab

**Comment by rvanbaalen** [comment]
@Radnyeechins ask questions on StackOverflow and dont hijack closed posts please.

**Comment by pabacham** [comment]
@rvanbaalen no one knows the answer http://stackoverflow.com/questions/29611355/is-there-any-way-to-close-angular-ui-tooltip-by-clicking-outside-it . Please pay attention to the problem.

**Comment by rvanbaalen** [comment]
Same goes for you @pabacham
