### ISSUE TITLE
Datepicker popup: how to customize CSS?

### ISSUE THREAD

**Issue by georgiosd** [angular-ui/bootstrap#1081]
Guys,

I haven't been able to find documentation or examples on two things:

a) How does one replace a built-in NGUI template? Just one, not write all of them.

b) How does one customize the CSS for the datepicker popup? I tried adding a style for the datepicker-popup-wrap but that didn't seem to be copied over by $compile. Never done this before.

**Comment by mg1075** [comment]
I think this ticket should be reopened. In version 0.13.0, there is still no hook for applying css styles based on a css attribute to the datepicker wrapper. I believe this hook should be at the level of the ul.dropdown-menu. Otherwise, as @georgiosd has mentioned, you have to make another wrapping div div with a custom class.

**Comment by cpu999** [comment]
I researched how to change the look and feel of the popup without alteting every other objects on the form. It wasn't evident but there is the plunker I used to make tests on how to change the CSS:

http://plnkr.co/edit/VtrLrmubFFOhELbRXy3J?p=preview

![image](https://cloud.githubusercontent.com/assets/8643543/10249027/14134016-68f1-11e5-8f1e-07da0c6ed329.png)

You can try different colors and see what does what. All I wanted was more contrast between available and unavailable dates. However, you can change many of those dates. Here is a (somewhat ugly) example that shows how things can be changed:

![image](https://cloud.githubusercontent.com/assets/8643543/10249154/be540baa-68f1-11e5-9f1e-c00da4331933.png)

**Comment by mvarshavsky** [comment]
I'm with @mg1075 - it seems like such an overkill to override the pretty involved popup.html template just to add a custom class to the container (and compromise future upgradeability in the process). I can attach through CSS `input[datepicker-popup] + .dropdown-menu`, but again that locks me into never using append-to-body.

**Comment by mvarshavsky** [comment]
I guess you can:
A: add to the wrap directive and add class - you can make it more flexible by reading said class off an attribute
```
angular.module('ui.bootstrap.datepicker')
.directive('datepickerPopupWrap', function() {
    link: function(scope, element, attr, ngModel) {
      return element.addClass('datepicker');
    }
});
```
B: tie the styling through css (which will not work with append-to-body)
`input[datepicker-popup] + .dropdown-menu`

I'm with @mg1075 - seems strange that the recommended solution is to override the whole template. Copy a pretty involved template, threaten upgradability - all just add a custom css class?

**Comment by flons** [comment]
Can't you just use a CSS attribute selector, e.g. ul[uib-datepicker-popup-wrap] ?

**Comment by arajay** [comment]
Styling the datepicker is always a battle because it is built with tables and buttons, so it inherits all the styling for those elements. it would be nice if it included its own scoped stylesheet or config.
