### ISSUE TITLE
PaginationConfig should evaluate its attributes

### ISSUE THREAD

**Issue by frapontillo** [angular-ui/bootstrap#1096]
I am using the `pagination` directive with `angular-translate` and I am having some issues trying to globally localize the `pagination` directive. I am using the following code in `app.run`:

``` javascript
paginationConfig.previousText = $translate('BACK');
paginationConfig.nextText = $translate('NEXT');
paginationConfig.firstText = $translate('FIRST');
paginationConfig.lastText = $translate('LAST');
```

But that doesn't work, as the shown values are simply `BACK`, `NEXT`, `FIRST`, `LAST`. Is there a way to forcefully evaluate those properties when they change?

Thanks.

**Comment by bandara00007** [comment]
@realityking Thanks...Its done the job.

var $translate = $filter('translate');
$rootScope.$on('$translateChangeSuccess' , function(){
            paginationConfig.firstText = $translate('First');
            paginationConfig.lastText = $translate('Last');
            paginationConfig.previousText = $translate('Previous');
            paginationConfig.nextText = $translate('Next');
        });

**Comment by emfrigo** [comment]
I'm really new to AngularJS but i have the same issue, someone can please make an example how you can use this solution??
Thanks

**Comment by railsstudent** [comment]
@bandara00007  try your code but it is not working for me. Do you have sample code?

**Comment by JeanPerriault** [comment]
@bandara00007 @railsstudent listenning at $translateChangeSuccess didn't work for me neither, I ended up using templateUrl, cloning current template in templateCache and replacing getText call with {{ 'label_first' | translate }}
