### ISSUE TITLE
The DropdownToggle hides when you click on content focus

### ISSUE THREAD

**Issue by ivanbreet** [angular-ui/bootstrap#111]
I use the dropdownToggle to display small forms on my site like "Sign up" forms etc. The problem is that as soon as jou focus on one of the forms inputs it closes without allowing you to enter any input.

This is currently something that is supported by the Bootstrap alternative.

**Comment by drothlis** [comment]
It looks like the [auto-close](https://angular-ui.github.io/bootstrap/#/dropdown) attribute added in v0.13.0 solves this.
