### ISSUE TITLE
TimePicker shows current time when model is empty.

### ISSUE THREAD

**Issue by craftyInstigator** [angular-ui/bootstrap#1114]
TimePicker shows current time when the model is null or cleared. On the contrary, DatePicker is blank when model is empty, which is the correct approach. It is impossible to tell when the TimePicker model is not set by looking at the control. TimePicker should be blank when model is not set.

**Comment by NuNn-DaDdY** [comment]
+1

**Comment by iraj-jelo** [comment]
+1

**Comment by constellates** [comment]
+1

**Comment by mciastek** [comment]
+1

**Comment by DefeNder93** [comment]
+1

**Comment by DigitalSmile** [comment]
+1

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by deggesim** [comment]
+1

**Comment by miked1090** [comment]
+1
Why is adding another config option overkill, set an option called default-time or something and everyone will be happy

**Comment by lichtner** [comment]
+1 why you don't merge this?

**Comment by szabyg** [comment]
+1

**Comment by quiz16** [comment]
+1

**Comment by dermoritz** [comment]
+maxInt

**Comment by rvanbaalen** [comment]
**Adding more +1's does not add anything to the discussion**

*Please put your efforts in creating a PR or suggestions for creating this feature instead of posting +1's*

**Comment by szabyg** [comment]
Thank you for the hint! I didn't realize that this is not a discussions point but an open feature request waiting for a PR!
So what can you imagine as a solution? Should an empty timepicker field be shown as empty or should it be an option so that unchanged usage shows the same strange behaviour?
Anyways, is it on purpose that the current time goes into the field?

**Comment by szabyg** [comment]
What I figured out is that this seems to be a feature that noone requested for. Let me explain:

* There's a test [`it('has 'selected' current time when model is initially cleared', ...)`](https://github.com/angular-ui/bootstrap/blob/master/src/timepicker/test/timepicker.spec.js#L108) introduced by b08e993fb472f386c69b713d89c466ca642b1ffe that describes the behaviour as expected. Empty ng-model, not empty input fields.

* The mentioned commit closes #773 and #785 but non of the both require this behaviour. #773 is about the bug that entered data disappears when the user reaches the meridian button and the current time is being inserted. #785 requests the support ng-change and ng-click.

I suggest the following:
* Remove of the mentioned test
* Create a test (if not yet there) describing the usage scenario behind #773 (enter hour, enter minute, click on meridian, expect the time to be whatever was entered)
* Fix the behaviour as follows: After the user enters the hour/minute and ng-model is still empty: set ng-model as `new Date()` and set the hour/minute whatever the user just entered. This way the click on the meridian button won't overwrite the Date object.

WDYT?

**Comment by slavafomin** [comment]
We need this so bad = )
:+1:

Is there a temporary workaround that can be used externally? Thanks!

**Comment by hellfrom** [comment]
I made such a trick

```
function link(scope, elem, attrs) {
	var isolateScope = elem.isolateScope();
	setTimeout(function (){
		isolateScope.minutes = '';
		isolateScope.hours = '';
        isolateScope.meridian = '';
		scope.$apply();
	},0);
}
```

**Comment by szabyg** [comment]
@rvanbaalen I think I contributed to the discussion and in the last month no one responded to the points I made. Does that mean that you all agree? Shall we move on to implementation and a merge request? Who will merge it if no one feels responsible for the issue?

**Comment by fmccown** [comment]
If this would be helpful, here's [my implementation](http://cs.harding.edu/fmccown/temp/timepicker.js) of the timepicker that shows empty inputs when the given model is null.

**Comment by prasad47** [comment]
+1

**Comment by wesleycho** [comment]
@szabyg I will move to implement this feature behind a feature flag, opting for the default behavior to be as requested here to match the datepicker and to allow what is requested in #1589 to be possible as well.

**Comment by wesleycho** [comment]
This is a much more difficult feature to implement than I expected - to properly do this has a lot of side-effects that needs to be accounted for.

I'm not sure it is as easy as people think.

**Comment by fmccown** [comment]
You're right... it is not easy to implement.  Take a look at [this Plunker](http://plnkr.co/edit/YPnukrKzasa1yPugVjch?p=preview) where I've implemented it.  The only thing I'm not real happy about is that $touched is set after moving from the hour field to the minute field, but otherwise it's a pretty good start.

**Comment by wesleycho** [comment]
Mind making those changes and opening a PR? I can review it and help make it good to get in.

**Comment by fmccown** [comment]
Sure thing.

**Comment by helenev** [comment]
Do you know when the fix for this issue will be on bower?

**Comment by icfantv** [comment]
@helenev, I'm on my phone so I can't easily check.  If this is in the 1.0 release, then we don't have a date yet as we have some things we need to finish up for it.  Our goal is to release by the end of the year.  If you want, feel free to pull `master` and run `npm install` followed by `grunt` to build the latest snapshot release.  The generated files will be in the `dist` directory.  Please note that this release has a TON of breaking changes so make sure you look at the changelog.

**Comment by ZackBotkin** [comment]
Was this ever fixed?

**Comment by mkalpana** [comment]
+1

**Comment by mfsi-surajs** [comment]
+1
any workaround to clear that field when model is null ?

**Comment by joaoesantos** [comment]
Im still not able to fix this, any workaround on thsi?

**Comment by spwinner2017** [comment]
+1
 I have set  this.medicineForm.get('startTime').setValue(Date.now()); but its not chaging when i select another time ...
