### ISSUE TITLE
Datepicker popup doesn't respect  "showWeeks: false" with AngularJS git master

### ISSUE THREAD

**Issue by gaydenko** [angular-ui/bootstrap#1132]
With this flag set to false calendar grid still renders weeks column both in Chrome and Firefox (can not say about IE9 as far as #1130 )

**Comment by alaksandarjesus** [comment]
$scope.dateOptions = {
    formatYear: 'yy',
    startingDay: 1,
    showWeeks:false  //Adding this line solve the issue
      
  };
