### ISSUE TITLE
IE 9/10 Issues

### ISSUE THREAD

**Issue by zenwork** [angular-ui/bootstrap#1134]
We have experienced a number of issues with the accordion, tabset, and typeahead directives that all result in the same incorrect behavior in IE9/10. Rather than getting the expected behavior for each directive the user is re-directed to the home page when clicking on accordion link, tab, or in the typeahead drop-down,

we have solved this problem by making sure that the directive templates do not have undefined or empty href properties. Instead we have added href="javascript:" and that seems to do the trick.

Questions:
Is this a valid workaround?
Can anyone think of any reason why we shouldn't do this?
Are there any plans to address IE10 compatibility issues?

cheers,
Florian Hehlen

**Comment by roger2hk** [comment]
A new issue #6262 has been raised with a Plunker scenario.
