### ISSUE TITLE
timepicker: ng-model not undated when set directly without wrapping DIV

### ISSUE THREAD

**Issue by vitalets** [angular-ui/bootstrap#1141]
When `ng-model`set directly in `<timepicker>`:

``` html
<timepicker ng-model="mytime" ng-change="changed()" hour-step="hstep" minute-step="mstep" show-meridian="ismeridian"></timepicker>
```

ng-model not updated when clicking on hours/minutes

**Comment by ShindePrasad** [comment]
I am using timepicker angular ui component in my form, After 1 st form submit, when I am submitting 2 nd form it is blank, it only take value if I manually change timepicker.

**Comment by Srishailam** [comment]
I am facing an issue with timepicker. Form is not resetting when i click on reset button. But the model is setting to null. data is not clearing off from the form.
<timepicker readonly-input="true"  ng-model="issue.closeByTime" show-meridian="false"></timepicker>

In controller
$scope.issue.closeByTime = null;

**Comment by Srishailam** [comment]
I am facing an issue with timepicker. Form is not resetting when i click on reset button. But the model is setting to null. data is not clearing off from the form.

<timepicker readonly-input="true"  ng-model="issue.closeByTime" show-meridian="false"></timepicker>
In controller
$scope.issue.closeByTime = null;

On UI, HH and MM are still showing although model is null. Can you please help me?

**Comment by Srishailam** [comment]
I am facing an issue with timepicker. Form is not resetting when i click on reset button. But the model is setting to null. data is not clearing off from the form.

`<timepicker readonly-input="true"  ng-model="issue.closeByTime" show-meridian="false"></timepicker>`
In controller
`$scope.issue.closeByTime = null;`

On UI, HH and MM are still showing although model is null. Can you please help me
