### ISSUE TITLE
$modal caching

### ISSUE THREAD

**Issue by Siyfion** [angular-ui/bootstrap#1193]
I've been chasing my tail for nearly a day over this; I have updated my AngularJS application on my website, among which I have updated the view used as the template for a `$modal` dialog window. For example given the code:

``` coffeescript
    $scope.showDialog = () ->
      dlg = $modal.open
        templateUrl: '/views/myDialogWindow.html'
        controller: 'DialogWindowCtrl'
        windowClass: 'modal-wide'
      dlg.result.then (result) ->
        if result?
          # Do something meaningful here.
```

I have updated the file `/views/myDialogWindow.html` however, when looking at the new website, I see that `myDialogWindow.html` is being loaded entirely from cache, even though I have used the `Disable Cache (while DevTools is open)` option in Chrome (and have the DevTools window open). None of the "normal" views seem to exhibit this behaviour, only modal windows.

Any ideas?

**Comment by mickeypuri** [comment]
@pkozlowski-opensource I ran into this as well. I tried and proved that the Headers were being set correctly to no caching, however it was still not making a new call and using the cached value. I swopped out the usage of $modal with a simple window.open and then found that it would make new calls, hence suggesting that it was no longer being cached in the browser. Finally to fix the issue I have had to add a randomized cacheBust parameter to the url.

**Comment by marioidival** [comment]
I'm also a caching problem using modal.
When I make any change in the template that is modal, this change is not returned ...

**Comment by hhsadiq** [comment]
Facing the same problem. I am working on localhost with Laravel on backend. The $scope.modal always picks the html file given in templateURL from cache. Is there any solution...?

**Comment by hhsadiq** [comment]
Found a solution for issue. Append a random string after templateURL.

    $scope.showDialog = () ->
      dlg = $modal.open
        templateUrl: '/views/myDialogWindow.html?temp=' + Math.random()
        controller: 'DialogWindowCtrl'
        windowClass: 'modal-wide'
      dlg.result.then (result) ->

**Comment by TurtleShip** [comment]
In case an angular beginner like me stumbles upon here, the below is one way to add a random cacheBust param to modal
```javascript
$modal.open({
                templateUrl: '/app/components/your-modal.html?bust=' + Math.random().toString(36).slice(2),
                controller: 'YourModalController'
            });

```

**Comment by marcrespass** [comment]
@TurtleShip that is a brilliant solution. This problem has been causing so much trouble and your solution fixed it. Much appreciated!

**Comment by dubeytapan12** [comment]
@TurtleShip Thanks for your great solution.. you saved my day. thankyou very much.

**Comment by spacem** [comment]
this still happens even after the issue has been closed for years, I have lots of templates and I can update them and no problem the changes are shown but I changed one to open with modal then now when I update the html the changes are not shown. That math random hack works but ugh

**Comment by aaron-em** [comment]
It's a browser cache issue; the Angular template cache doesn't persist across page loads, so there's nowhere else the browser can get a template from either its own local cache, or the server. If you don't see an HTTP request being made to fetch the template (or you see it coming back with an HTTP 304 or similar response), then it's coming from the browser cache. Configure your dev server to send `Cache-Control: no-cache, no-store` or similar, clear your browser cache for whatever domain you're testing in, and you'll see the problem go away as if by magic.

If that doesn't work for you, you can always try forcibly preloading the template cache with a fresh copy of your modal template when your app finishes bootstrapping:

    // presumably set in a configuration somewhere, or something
    YOUR_ENVIRONMENT = 'development';

    app.run(['$http', '$templateCache', function($http, $templateCache) {
      var targetUrl = '/view/modal/modal.html';
      if (YOUR_ENVIRONMENT !== 'production') {
        $http({
          method: 'GET',
          url: targetUrl
        })
        .then(function(result) {
          console.log(result);
          $templateCache.put(targetUrl, result.data);
        });
      }
    }]);
    
Considering that correct browser cache settings will solve this problem reliably, doing it at the application level is using a shotgun to kill a flea, but if you can't or won't correctly configure your server, this way has the virtue that at least it will work. (And it's a lot easier to compartmentalize than ugly cache-busting URL query params, which in turn means it's easier to ensure this only happens during development, and not in production where it will negatively impact performance.)

**Comment by jagwsing** [comment]
> In case an angular beginner like me stumbles upon here, the below is one way to add a random cacheBust param to modal
> 
> ```js
> $modal.open({
>                 templateUrl: '/app/components/your-modal.html?bust=' + Math.random().toString(36).slice(2),
>                 controller: 'YourModalController'
>             });
> ```

Brilliant solution. Thanks.
