### ISSUE TITLE
ng-show not working in tabs

### ISSUE THREAD

**Issue by konsultaner** [angular-ui/bootstrap#1221]
I have a project where I need to fully hide a tab. This is not possible with ng-show. The tab will not appear if the model allows to show it.

```
...
<tab ng-show='myModel.showTab'>
    ....
</tab>
....
```

**Comment by morfin** [comment]
Why theres no hide attribute ? ng-show/ng-hide only is applied to the tab, not the content.

**Comment by mpojeda84** [comment]
On the Plunkr, If you set to false the showFirst variable, it will hide the tab heading, but it won't hide the static content. I am having the same issue in my project.

**Comment by snimavat** [comment]
Same here this needs a standard way of hiding tab + content
