### ISSUE TITLE
Missing: Affix and Scrollspy, preparing pull request

### ISSUE THREAD

**Issue by oehokie** [angular-ui/bootstrap#1226]
Greetings,
   I've forked the bootstrap repo and am close to submitting a pull request to incorporate Affix and Scrollspy which are currently missing.  This being my first pull request, I'd like to do it right... what are your requirements?

Affix will work one-to-one from the original bootstrap markup.  Right now I'm using a slightly different (but similar/more angular-y) method for the spyscroll bit.  I have not written the tests yet (tsk tsk on me), are they important or should I submit and add the tests later?

Right not I've only modified some files in the src folder, do I need to build and change the templates as well?

Thanks,

Matt

**Comment by RopoMen** [comment]
When these features are ready and added into main build? Project description states clearly "no 3rd party JS dependencies" but that is not true unless these are available.

**Comment by rvanbaalen** [comment]
Feel free to help and submit a PR @RepoMen.

**Comment by wesleycho** [comment]
Closing, as we are looking to mostly stay in maintenance with this project & not add new components.

All components are on the table though for https://github.com/ng-bootstrap/core

**Comment by DDeme** [comment]
well done
