### ISSUE TITLE
Arrow keys don't work in DropdownToggle

### ISSUE THREAD

**Issue by robbertbrak** [angular-ui/bootstrap#1228]
In the dropdown toggle, the arrow keys to navigate through the items in the list don't work.

Reproducable by going to http://angular-ui.github.io/bootstrap/#/dropdownToggle and selecting "Edit in plunker".

**Comment by bleggett** [comment]
Have a PR that add this functionality. Started with yarl's fix but made it an optional flag, added some tests, and removed the apparent dependency on jQuery.
