### ISSUE TITLE
manually entered date not parsed correctly by datepicker

### ISSUE THREAD

**Issue by terebentina** [angular-ui/bootstrap#1235]
When you pick a date with the datepicker, it correctly shows the picked date in the input field, properly formatted as specified by the datepicker-popup format. 

In my case I used datepicker-popup="dd/MM/yyyy" (note the month is the second, day is first)

So if I pick November 1st, 2013 then the input would show 01/11/2013 (correct so far).

However, if I delete the date in the input field and start typing the exact same date, the date picker goes to January 11th, 2013 - it thinks month is first.

By looking at the code I see there's no attempt to parse the value according to the format - the entered value is passed directly to Date().

Plunker for this: http://plnkr.co/edit/uibdoKRTMHLxJJy3KbMS?p=preview but it's basically the default datepicker, nothing special done there.

**Comment by molerat619** [comment]
Any news on this?
