### ISSUE TITLE
popover positioning is wrong for large(r) values of .popover max-width

### ISSUE THREAD

**Issue by facboy** [angular-ui/bootstrap#1236]
it seems that if .popover max-width is set too large (eg over 350px) that the positioning relative to the trigger element is wrong.  i couldn't quite work out what was causing it.  setting a fixed width (rather than max-width) seems to fix the issue.

**Comment by rvanbaalen** [comment]
This is fixed when using the most recent `ui-bootstrap` and `bootstrap css`.

http://plnkr.co/edit/0s6RbB?p=preview
