### ISSUE TITLE
datepicker should allow saving as String instead of Date

### ISSUE THREAD

**Issue by jnizet** [angular-ui/bootstrap#1239]
The datepicker/datepickerpopup component is able to read a string from the model (for example: '2013-11-09'), parse it and display it. But when it saves its value to the model, it saves it as a Date object. 
It would be extremely useful to be able to specify how the date should be stored (i.e. as a Date, or as a String with a given format, different from the format used to display the date)

**Comment by pnowy** [comment]
I will put here example for next generations:

```
angular.module('myApp')
    .directive('datepickerPopup', function (){
        return {
            restrict: 'EAC',
            require: 'ngModel',
            link: function(scope, elem, attrs, ngModel) {
                ngModel.$parsers.push(function toModel(date) {
                    return date.getFullYear() + '-' + (date.getMonth() + 1) + '-' + date.getDate();
                });
            }
        }
    });```

**Comment by aortyl** [comment]
With the 0.14 update of using the uib- prefix, @pnowy's directive would be updated to the following:
```javascript
angular.module('myApp')
    .directive('uibDatepickerPopup', function (){
        return {
            restrict: 'EAC',
            require: 'ngModel',
            link: function(scope, elem, attrs, ngModel) {
                ngModel.$parsers.push(function toModel(date) {
                    return date.getFullYear() + '-' + (date.getMonth() + 1) + '-' + date.getDate();
                });
            }
        }
    });
```

**Comment by victorparmar** [comment]
+1

**Comment by jocelynlecomte** [comment]
Sorry to resurrect this rather old thread, but I can't get it to work:
When I change the value using either the popup or the input, the DOM is correctly updated, but the model value is set to undefined...

**Comment by icfantv** [comment]
@jocelynlecomte. your best bet here is to first search SO for your question and if it's not there, create a new post that shows you've thoroughly tried to solve the issue.  commenting on really old and closed issues is a really good way for your question to be overlooked.

**Comment by alexcrack** [comment]
This solution does not work with version 1.1.0 for me.
It works with v0.14 in my previous project on angular 1.3. But now I use angular 1.4.8.
Any suggestions? I need a string date to put it in the ui-router's query string.

**Comment by icfantv** [comment]
@alexcrack, please read my instructions above for how to ask for help and refrain from asking for help on closed threads as this is a good way for them to be missed or ignored.  Thanks.

**Comment by senyaak** [comment]
May be usefull for someone - just inject uibDateParser and use format and parse to convert Date object to string and backwards
