### ISSUE TITLE
Datepicker selects wrong date when using ISO 8601

### ISSUE THREAD

**Issue by john-ring** [angular-ui/bootstrap#1278]
When entering in a date in ISO 8601 format (yyyy-MM-dd), the calendar selects the entered date minus 1.  So 2000-11-30 actually selects 2000-11-29.  

![screen shot 2013-11-20 at 11 18 02 am](https://f.cloud.github.com/assets/5882209/1583580/58492b2a-51ff-11e3-95cb-4a0ac3db680a.png)

**Comment by admhemed** [comment]
my solution is to use a directive to fix the minus 1 issue, and also to format the view and model values:

app.directive('ngBootstrapFix',['$filter', function($filter) {
  return {
    require: 'ngModel',
    priority: 1,
    link: function($scope, $element, $attrs, ngModelCtrl) {
      ngModelCtrl.$parsers.push(function(viewValue) {
        viewValue = $filter('date')(viewValue, 'yyyy-MM-dd');
        return viewValue;
      });
      ngModelCtrl.$render = function() {
        var val = $filter('date')(ngModelCtrl.$viewValue, 'dd/MM/yyyy');
        $element.val(val);
      };
    }
  };
}]);

**Comment by teracomp** [comment]
Fantastic! Thanks for the directive, this is perfect!
I added one comment to my code:
    Usage: <input ng-bootstrap-fix="currentResource.date_validated" ...

And modified the $render $filter:
    var val = $filter('date')(ngModelCtrl.$viewValue, 'MMM dd, yyyy');
