### ISSUE TITLE
It's very slow when I use the accordion and accordion-group in directive.

### ISSUE THREAD

**Issue by 842454360** [angular-ui/bootstrap#1310]
It's very slow when I use the accordion and accordion-group in directive.
When I enable 'close-others',it will have 2~3 seconds hand in the page during I open another accordion.Not as smooth as the demo. Any idea ? I already follow the code in demo except the css.

code:

<accordion close-others="true">

```
        <accordion-group is-open="!item.isOpen">

            <accordion-heading>
                I can have markup, too!
            </accordion-heading>
        </accordion-group>

        <accordion-group heading="hello,second">
            <div>
                something
            </div>

        </accordion-group>

    </accordion>
```

**Comment by Davy-F** [comment]
@pierregm I'm just wondering if you have a plunker with this example? Trying to achieve the same thing to improve accordion performance.
