### ISSUE TITLE
Carousel strange transition [bootstrap 3]

### ISSUE THREAD

**Issue by djordje** [angular-ui/bootstrap#1350]
I've made video that show behaviour (`angular 1.2.3`).

https://dl.dropboxusercontent.com/u/21598387/AngularUI_Bootstrap3_carousel.mov

**Comment by fnagel** [comment]
Thanks @simonykq for the [workaround](https://github.com/angular-ui/bootstrap/issues/1350#issuecomment-34595075)! 

This really needs to be fixed.

**Comment by dmarcelino** [comment]
Thank you @simonykq, that fixed the issue I was experiencing.

BTW, I'm using:
* angular#1.3.8
* angular-animate#1.3.8

**Comment by timtim-75** [comment]
Hi there,

On safari, the workaround doesn't fix the issue. 

The carousel is loaded, I can only click once on next/prev, then nothing else happen. Something strange, the next/prev slide is shown, but the first is still on the page.

Here is my first slide, before I click next, on the left, 99 is the ID of this picture.
![Uploading Capture d’écran 2015-01-20 à 15.52.14.png . . .]()

And here is the second slide, after I click next, on the left, you can see the ID of this picture, but still the ID of the previous one.
![Uploading Capture d’écran 2015-01-20 à 15.52.39.png . . .]()

Any idea ?

Thanks a lot

**Comment by rubenjimenez** [comment]
I think I'm suffering the same issue. In my case, when i press next or prev arrows sometimes I got the slide to change once, sometimes it doesn't event change. Same behavior in Chrome/Safari. It started to happen when I added ngAnimate to the project.

**Comment by bentleyo** [comment]
Can we add a note about this ngAnimate + ui.bootstrap incompatibility to the FAQ?
I just ran into this issue and it was a *real* pain to figure out. I ended up going with the fix @simonykq provided (thanks Simon!).

**Comment by markleusink** [comment]
@bentleyo Know that feeling. Just went through the same tough process :(

+1 for adding a line to the docs and mentioning the workaround (disabling ng-animate completely or only for the directive).

**Comment by altazar** [comment]
I have a similar, but different problem:
http://kulturfokus.eu/en/projekte/aufsteinernenspuren

**Comment by ivan-abrash** [comment]
@simonykq thanks!

**Comment by gustavobigardi** [comment]
@simonykq thanks!!! I lost almost a day trying to resolve this!

**Comment by daveteply** [comment]
This can also be remedied by specifying a specific prefix when configuring your app.
```javascript
angular.module('fooMod',['ngAnimate']).config(function($animateProvider) {
    $animateProvider.classNameFilter(/prefix-/);
...
```
We had an issue with the carousel after adding another library that required ngAnimate.  This library uses CSS classes that begin with `anim-` so we configured our animate provider with that:

```javascript
    $animateProvider.classNameFilter(/anim-/);
```

This tells ngAnimate to only animate classes that begin with `anim-`.

See https://docs.angularjs.org/api/ngAnimate 'Preventing Collisions With Third Party Libraries' for more details.

**Comment by char0n** [comment]
The work around doesn't seem to work when you are displaying carousel in $modal.
My animate provider is configured like so: 

$animateProvider.classNameFilter(/(app\-repeated\-item)|(modal)/); 
// The modal inside the definition fixes https://github.com/angular-ui/bootstrap/issues/3647

When I remove the class name filter, arrws on carousel seems to work fine.

@simonykq solutions doesn't seem to work in this scenario. It seems absurd that ui-bootstrap which is pure angular implementation of bootstrap components, doesn't work with core angular modules.

I fall-backed using native bootstrap components that works out of the box.

**Comment by Avcajaraville** [comment]
@simonykq Thanks man, save my day :)

**Comment by ikhos** [comment]
Hi, I've used the disableNgAnimate but in my case the carousel directive is only toggling the 'active' class, not adding/removing the others used for animation, this means the slides only toggle but do not animate.

I'm using "angular": "^1.3.0" with "angular-bootstrap": "~0.13.0".

 Any ideas how to fix this?

**Comment by MastroPino** [comment]
@simonykq 
thanks, it worked!

**Comment by sauminkirve** [comment]
@simonykq,

Thanks a lot man... great job. it works.
