### ISSUE TITLE
Popup for Datepicker inside ng-repeat fails to display

### ISSUE THREAD

**Issue by johnmcteague** [angular-ui/bootstrap#1381]
I have two simple examples of a datepicker. One inside a ng-repeat (that only has 1 item in the loop) that does not work and the exact same example but without the ng-repeat.

working - http://plnkr.co/edit/ZDgjFa?p=preview
not working - http://plnkr.co/edit/KIMZt8?p=preview

As soon as I take the ng-repeat away it works. I am using angularjs 1.2.4 with ui-bootstrap 0.7.0.

**Comment by vsthakur78** [comment]
@cgarvis I have created a separate "is open" status related array for ng-repeat and this gives me flexibility even if there are more controls inside ng-repeat. However, please note that I have not changed anything in model still it assigns respective value to control not sure how it reflects on actual model. You may want to have a look at pnkr here: http://plnkr.co/edit/FcuZYsRsTaGEznAabEe8?p=preview
