### ISSUE TITLE
Consider add container option, that solves some bootstrap issues

### ISSUE THREAD

**Issue by marcospassos** [angular-ui/bootstrap#139]
Hello,

The `container` option was introduced to solve some issues of tootip and popover (like style break in btn-group, popover hidden on modal, etc). So,  IMO, it also could be implemented here.

Reference:
https://github.com/twitter/bootstrap/pull/5768

I would be happy in submit a PR if you agree.

Thanks!

**Comment by BrianRT** [comment]
Has this feature been implemented yet?

**Comment by capesean** [comment]
@BrianRT see: http://angular-ui.github.io/bootstrap/#/tooltip - you can configure the $tooltipProvider to append to the body globally.

**Comment by demircancelebi** [comment]
Use it like this

``` js
$uibTooltipProvider.options({ appendToBody: true });
```
