### ISSUE TITLE
Project coding conventions

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#1490]
Hello, as @pkozlowski-opensource knows, I am on a journey of reading every line of code of the repo and one of the goals is to collaborate.

He said that well, the code is awesome but there are some old stuff that could be improved and that is what I am here :)

What I see so far and I only have like 15% done is that in tests (have to check the code also) there are no conventions at all.

I know that is problematic to have conventions in a project with all this contributors but that doesn't mean that we can't change that.

What I suggest is:

Discuss about what conventions should we have and then update [CONTRIBUTORS.md](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md) with all the rules a contributor should follow in order to write tests.

Then update all the unit tests to match this rules.

I see all kind of stuff:

Strings, I saw all kind of combinations:

`"text"`

`'text'`

`'<div id="foo">'`
`"<div id='foo'>"`
`"<div id=\"foo\">"`

I suggest here that we always use single quotes for everything and in the case of html strings, use double quotes for attributes.

Variable names:

I have seen a mix of `$scope` and `scope`.

If my conventions here are not wrong, we should use `scope` for directives and `$scope` for everything else. (That could be problematic in the case we have a test that cover both directives and directives' controller.

More... Injections, somethings injections like `_foo_` and others just `foo`.

We should use underscore only when  we are going to assign that parameter to a variable that we want to have the original name. I mean, this makes no sense:

`scope = _$rootScope_;`

If you're not going to have a `$rootScope` variable, just leave out the underscores.

The biggest problem is that in one test file you can see a lot of mixed conventions.

I wouldn't mind to apply this conventions in my way of reading the code if we agree in what conventions we should follow.

**Comment by wesleycho** [comment]
Closing in favor of #4758.
