### ISSUE TITLE
Tabs - Dynamically created tabs do not respond to "select" or execute it immediately on creation

### ISSUE THREAD

**Issue by epitka** [angular-ui/bootstrap#1496]
If one creates a dynamic tab like this

```javascript
 $scope.tabs = [{ title: "Profile", content: "app/insured/profile/inProfile.html",  select: activateTab(), name: "profile" }, { title: "Coverage", content: "app/insured/profile/inCoverage.html", select: activateTab(), name: "coverage" }]
```
then function specified for "select" will execute right away while tabs are being constructed.  I tried also using just "activateTab" without parenthesis and that does not do anything.  You can try it also just using a plunker supplied with tabs example and try to put select for dynamic tab 1

``` javascript
{ title:"Dynamic Title 1", content:"Dynamic content 1", select:onSelect() },
```

``` javascript
 function onSelect(){
    console.log("onSelectCalled");
    alert("onSelectCalled");
  }
```
and you will see the issue.  Also setting the "active" attribute to true from javascript code does not do anything either.  My markup for the tabs is like this

```html
  <tabset >
            <tab data-ng-repeat="tab in tabs" heading="{{tab.title}}" active="{{tab.active}}"  class="fullwidthtabs">
               <div ng-include="tab.content"></div>
            </tab>        
        </tabset>

**Comment by neekey** [comment]
any progress on this issue?

**Comment by wesleycho** [comment]
Closing, as this looks like a non-issue.

For progress on fixing the API, keep an eye on #4836.
