### ISSUE TITLE
Auto close for alerts

### ISSUE THREAD

**Issue by ghost** [angular-ui/bootstrap#1518]
I would like to set a timeout for alerts, and the alert is not removed when i remove the item from the array inside the controller...

Markup:

``` html
<alert ng-repeat="alert in alerts" type="alert.type"  close="alert.close()">{{alert.msg}}</alert>
```

Inside controller:

``` javascript
$scope.alerts = [];
var alert = {
    msg: 'Please fill all the fields.'
};
alert.close = function(){
    $scope.alerts.splice($scope.alerts.indexOf(this), 1);
}
$scope.alerts.push(alert);
setTimeout(function(){
    $scope.alerts.splice($scope.alerts.indexOf(alert), 1);
}, 3000);
```

In this code the timeout is executed the item is removed, but the view doesn't refresh...

**Comment by VinuOye** [comment]
in controller i have 

    $scope.alerts =  [ ];
    $scope.closeAlert = function (index) {
      $scope.alerts.splice(index, 1);
    };
    $timeout(function(){
      $scope.alerts.splice($scope.alerts.indexOf(alert), 1);
    }, 3000);

while deleting i would like to show this message i.e., 

    $scope.alerts.push({
        type: 'warning',
        msg: 'Task have been deleted!!' +
          '<a ng-click="Undo($index)">Click to undo</a>'
       });

for showing the html content and ng-click purpose i use this directive i.e.,

app.directive('alert', function ($compile, $parse) {
  return {
    restrict: 'E',
      link: function (scope, element, attr) {
        scope.$watch(attr.content, function () {
          element.html($parse(attr.content)(scope));
          $compile(element.contents())(scope);
        }, true);
      }
    }
}); 


my issue is i didn't get the close button on alert after the usage of this directive and also auto close alert is also not working.

**Comment by SuprajaMachavaram** [comment]
In this example the alert is not showing properly i.e., it showing half of the alert message only in XS mode

**Comment by karianna** [comment]
For support, please try SO or the IRC channel

**Comment by twmulloy** [comment]
https://github.com/angular-ui/bootstrap/blob/master/src/alert/alert.js#L22-L31

```
<alert ng-repeat="alert in alerts" type="alert.type" dismiss-on-timeout='3000'  close="alert.close()">{{alert.msg}}</alert>

**Comment by RouR** [comment]
```
.factory("alertService", [
        "$timeout",
        function ($timeout) {
            var alerts = [];
            var service = {
                add: function (type, msg) {
                    var alert = {
                        type: type,
                        msg: msg,
                        close: function() {
                            alerts.splice(alerts.indexOf(this), 1);
                        }
                    };                   
                    if (type === "success") {
                        $timeout(function () {
                            alerts.splice(alerts.indexOf(alert), 1);
                        }, 1000);
                    }
                    return alerts.push(alert);
                },
                closeAlert: function (alert) {
                    return closeAlertIdx(alerts.indexOf(alert));
                },
                closeAlertIdx: function (index) {
                    return alerts.splice(index, 1);
                },
                clear: function () {
                    alerts = [];
                },
                get: function () {
                    return alerts;
                }
            };

            return service;
        }
    ])

**Comment by sarthak-k** [comment]
https://github.com/angular-ui/bootstrap/blob/master/src/alert/alert.js#L22-L31

<alert ng-repeat="alert in alerts" type="alert.type" dismiss-on-timeout='3000' close="alert.close()">

this doesn't work? or it's only me?

**Comment by plattdl** [comment]
@sarthak-k I am having the same issue. Updated to the latest version in bower but still no dice.

**Comment by sarthak-k** [comment]
@plattdl Please use dismiss-on-timeout and not dismissontimeout.

**Comment by gharig** [comment]
//fileName: alert.js

(function (angular) {
    'use strict';
    
   
    angular.module('YourName')
     .factory('alert', ['$rootScope',  function ($rootScope) {
            var alertService;
            $rootScope.alerts = [];
            return alertService = {
                add: function (type, msg, timeout) {
                    return $rootScope.alerts.push({
                        type: type,
                        msg: msg,
                        close: function () {
                            return alertService.closeAlert(this);
                        }
                    });
                },
                closeAlert: function (alert) {
                    return this.closeAlertIdx($rootScope.alerts.indexOf(alert));
                },
                closeAlertIdx: function (index) {
                    return $rootScope.alerts.splice(index, 1);
                },
                clear: function () {
                    $rootScope.alerts = [];
                }
            };
        }
    ]);

})(window.angular);


//fileName: alert.html  ---- use (<div ng-include="'/alert.html'"></div> ) in your index.html
//the dissmissOnTimeout directive from ui-bootstrap needs to have the dashes when reference directives;  dismiss-on-timeout="20000"

<div>
    <alert class="alert" ng-repeat=" alert in alerts" type="alert.type" dismiss-on-timeout="20000" close="alert.close()">{{ alert.msg }}</alert>
</div>



//Your controller that uses the new alert service....

angular.module('????')
        .controller('YourCtrl', ['$scope',  'alert', function ($scope, alert) {

            $scope.submit = function () { 
                alert('success', 'Thanks for coding!');
            };
        }]);


thanks twmulloy and others that shared their code so I could get this working
