### ISSUE TITLE
accordion panels in 0.9.0 open only when you click text on the header

### ISSUE THREAD

**Issue by gae123** [angular-ui/bootstrap#1521]
Steps to reproduce in the angular-ui 0.9.0 web page with the accordion demo:
1. Click on accordion header on top of text
2. The accordion opens as expected
3. Click on the accordion header at a place where there is no text
4. RESULT: Nothing happens
   EXPECTED: accordion opens or closes

This is a regression at least from 0.6.0 that I use

**Comment by paulbhartzog** [comment]
@bekos 
"it's an easy change in the template" is not helpful.  "Easy" for whom?

Regardless of whether you think it is easy or not, you should provide an explanation of how to obtain the desired behavior.  What changes to what template are required to get fully clickable accordion headers?

**Comment by dalvarezr** [comment]
/deep/ .card-header > a{
  display: block;
}
This worked for me
