### ISSUE TITLE
Ideas for UI-Bootstrap's vision/principles

### ISSUE THREAD

**Issue by chrisirhc** [angular-ui/bootstrap#1530]
(Note: This is a discussion, and I thought it's quite different from code conventions so I didn't mention this in #1490)

I was thinking about this the other day, we may need some grounding principles for this repository to guide decisions in adding new features or directives.

I was hoping to start a wiki page that would hold some of these thoughts (open to discussion and I'm happy to add more):

- Simple-first but extensible
  - Support basic use cases easily
  - Allow customizations only if they don't complicate the basic use cases
  - Expose API (through directive controller and/or services) for rare/complex use cases
- Promote and encourage usage of components in the template, the Angular way

As the API stabilizes, I think it becomes more reasonable to ask users to write their custom directives, that extend Bootstrap's directives, to support custom functionality.

Contrast this to asking users to run their own patched/forked version of the repository, I think I much prefer asking them to write and maintain directives that extend Bootstrap's directives.

It may also make sense to keep a library of snippets of these custom directives in the Wiki so that new users can browse through ways to use the API.

Before this can happen, we should migrate into [semantic versioning](http://semver.org/). This helps users to identify which versions will break the API.

**Comment by Foxandxss** [comment]
Closing this. Not an actual issue and we talk about this stuff every day on our slack :)
