### ISSUE TITLE
Progress Bar does not work properly with dynamic max value

### ISSUE THREAD

**Issue by naveensky** [angular-ui/bootstrap#1547]
When we bind max value to a function or property which can update on runtime, the progress bar doesnt work as expected. 

Plunk to get started
http://plnkr.co/edit/goYLZQMnipkMGms45lux?p=preview

**Comment by msnpr567** [comment]
hello guys...
you are all showing data on completed side in progress bar , i want to show data on uncompleted side, In order to show next step title or name of next  form name . can u show me solution.

**Comment by tdhsmith** [comment]
@msnpr567: As @Foxandxss noted, usage questions are better suited and answered more quickly elsewhere, such #angularjs on IRC or StackExchange.

That said, you can accomplish this by using stacked bars, and adding an extra bar for the uncompleted portion. You can style it to be invisible with something like:
```css
.progress-bar-clear {
  background-color: rgba(0,0,0,0);
  color: rgb(51, 51, 51);
}
```
And `<bar type="clear" ... ?>`. Then set the `value` of that bar to be however much remains. I threw an example together here using `$scope.$watch()`, but you can set the value any which way: http://plnkr.co/edit/8rlFN7CtDQrJXroo6Gmf?p=preview

-------------------------------------

On the front of this actual issue, would including this feature be any more complicated than just adding `max: '=?'` to the directives' scope, plus some additional `watch` and default-setting code?

**Comment by msnpr567** [comment]
very nice thanku........... @tdhsmith

**Comment by kedartendolkar** [comment]
Found one solution to the max value problem. Use ng-if like:
````
<progressbar max="max" value="value" ng-if="max"></progressbar>
````
This will wait till max value is obtained.

**Comment by wesleycho** [comment]
As there appears to be a good enough workaround to the issue (thanks to @johnnyaug), I am closing this issue.

**Comment by areindl** [comment]
@johnnyaug You made my day! I was looking for a solution for more than 2 hours. I am building a dynamic progress bar with dynamic max values.

Your normalization idea is simply genius:
```javascript
        $scope.getProgressbarValue = function() {
            var min = $scope.getMin();
            var max = $scope.getMax();
            var val = $scope.points;

            return ( val / max )  * 100;
        }
```

So in my HTML-Markup I simply add this to the progressbar:
```javascript
value="getProgressbarValue()" 
```

Thanks!

**Comment by sicollins** [comment]
Just hit this issue  - using data-ng-if on my progressLength prop solved it for me:

<progressbar data-ng-if="progressLength" class="progress-container" value="currentQuestionIndex" max="progressLength"></progressbar>

**Comment by yuanda** [comment]
Thank you @sicollins  for your solution. 

@johnnyaug's solution doesn't work in stacked progress bar, but @sicollins works.

**Comment by Status420** [comment]
this problem with @kedartendolkar and @sicollins solutions is, it moves down the div around it, as it hides the progress bar, I'd like to keep the bar in place.
The use case for me is showing a progress with loading map tiles (openlayers), we don't the total tiles until half way through the loading process thus the max value needs to be updated.
