### ISSUE TITLE
ng-if and tabs selects second tab

### ISSUE THREAD

**Issue by cmodijk** [angular-ui/bootstrap#1568]
If the first tab has a ng-if that resolves to true the second tab is active instead of the first tab.  I don't know if this is a bug. 

An example of the case: 
http://plnkr.co/edit/Hpif920RrB6nS4AB4Mwj?p=preview

**Comment by psamsotha** [comment]
Yes @cmodijk, how _did_ you fix it?

**Comment by psamsotha** [comment]
Seems to work with `ng-show`. Not sure why it doesn't with `ng-if`
