### ISSUE TITLE
refactor(): add directive prefixes

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/bootstrap#157]
Creating this since only the group thread existed previously.

I was working today and realized the AngularUI version of modal is broken-ish. I want to use the Bootstrap version, but unfortunately everywhere I have a modal class will start having breaking because the bootstrap AND angularUI versions will start doubling up.

This lib really needs to be prefixed, it's sort of frustrating.

https://groups.google.com/forum/?fromgroups=#!searchin/angular-ui/prefix/angular-ui/WPg58BFQDJc/kikQuy5OAcsJ

**Comment by dlwhiteman** [comment]
I understand there are lots of frameworks out there, and it would be impossible not to collide with one of them. That said, ui-bootstrap and angular-strap are two very popular frameworks, so it would seem to be a fairly common issue to have this collision.

**Comment by bzitzow** [comment]
+1

**Comment by ryanhburbank** [comment]
prefixing would be fantastic, **+1

**Comment by caseyhoward** [comment]
+1 for bs

**Comment by julian-iFactory** [comment]
+1  - This issue has been an annoyance for a long time. Prefixing vendor namespace also makes it a lot easier to figure out at a glance who the vendor of a directive is, you can then quickly refer to their docs for help.

**Comment by JetFault** [comment]
+1 for any kind of prefix

**Comment by rvanbaalen** [comment]
Guys. Decide on which prefix to use (`ui`, `bs`, `ngui`, `uibs`, `bsui`..), create a branch where these changes should be implemented and everyone throw PR's at it so we can all chip in and help to get this over with?

It's been more than a year since this issue was recognised. It's time to squash it and move on. And I'm willing to help doing so.

**Comment by Foxandxss** [comment]
Long time issue indeed. We are going to do it for release 1.0 (when we get up to date with angular and bootstrap) since it is when we can change the API. After that we will do semver as well.

**Comment by hugsbrugs** [comment]
Where are we ?

I'm using angularjs 1.3.3, ui-bootstrap-tpls-0.12.1.min.js (and a bunch of other plugins) and still get this error : 

[$compile:multidir] http://errors.angularjs.org/1.3.3/$compile/multidir?p0=match&p1=typeaheadMa…%3D%22match%22%20query%3D%22query%22%20template-url%3D%22templateUrl%22%3E 

Where can I manually change the match directive name to avoid this conflit (If I have correctly read tour potst ! ) ??

**Comment by dmitriz** [comment]
### Proposal
- Add names to the anonymous functions defining directives.
- Add prefixed directives declarations linking to those functions.

### If this is considered a breaking change, follow the same route as in my proposal 
https://github.com/angular-ui/bootstrap/issues/3396#issuecomment-94344993

**Comment by skidvd** [comment]
+1

**Comment by rvanbaalen** [comment]
We're moving all prefix-related discussion to one topic: #3396
