### ISSUE TITLE
Can't have multiple carousels on a single page?

### ISSUE THREAD

**Issue by sroberson** [angular-ui/bootstrap#1582]
I'm using Angular v1.2.6 and have installed angular-ui-bootstrap via bower (not sure what version).  I need to have 3 carousels on a single page, but when I put the three on there, when I advance one, they all move synchronously.   Is this a bug?  If not, how can I separate them?

Thanks,
Scott

**Comment by PhGeek** [comment]
:+1: Thank you for sharing the solution.
