### ISSUE TITLE
Oversize pulled to sides tooltips, incorrect positioning tooltips arrows.

### ISSUE THREAD

**Issue by khusnetdinov** [angular-ui/bootstrap#1606]
The problem appear if you pulled to sides buttons wich trigger tooltips.
Live demo: http://plnkr.co/edit/44iJk3aRU9JjNzIh6ahA?p=preview
![pulled buttons](https://f.cloud.github.com/assets/3524630/1947165/dd627d50-8041-11e3-922a-d459dda58830.png)

Second problem with tooltips  is that arrow can get position incorrect, you can see if there is no oversize, arrow not stand at middle button:
Live demo:  http://plnkr.co/edit/AcjPZxShUW1MzOQw15Gc?p=preview
![1](https://f.cloud.github.com/assets/3524630/1947176/e603913c-8042-11e3-881c-74ddc0e08e1d.png)

**Comment by icfantv** [comment]
Closing in favor of #4762.
