### ISSUE TITLE
clearing a typeahead doesn't work when it's typeahead-editable="false"

### ISSUE THREAD

**Issue by jnizet** [angular-ui/bootstrap#1620]
I think I found a small bug a typeahead. When I try to clear the typeahead (by setting its model to undefined), it works fine if the typeahead is editable, but it doesn't if it's not editable (i.e. its typeahead-editable attribute is false).

The bug is illustrated, with an ugly workaround, in [this plunkr](http://plnkr.co/edit/XLb0vFBZCsvVLnkxrUfT?p=preview)

**Comment by huguangju** [comment]
@futurechan it's doesn‘t work for me
