### ISSUE TITLE
How to fix “App Already Bootstrapped with this Element”?

### ISSUE THREAD

**Issue by Vinoth18** [angular-ui/bootstrap#1626]
I am initializing and opening a model from GWT using $wnd.angular.bootstrap($doc, ['fmEventLogApp']);

After closing the model, when I try to open the model again, it is trying to reinitialize the model and throwing an error as "uncaught exception: com.google.gwt.event.shared.UmbrellaException: One or more exceptions caught, see full set in UmbrellaException#getCauses"

But when I see the actual error message, it says "App Already Bootstrapped with this Element".

How to solve this problem in case of a model window? Please help.

**Comment by danpaulsmith** [comment]
Batarang was the cause for me.

**Comment by jdmagic21** [comment]
I would look and see if there any other dependancies you trying to load in your code. For me my issue was that I was trying to utilize Google API feed and it had a "document.load" type intitialization. I would also check and make sure that you only have one module per website. To prevent having multiple modules and causing unneeded load times you can easily place this inside of your main body tag.
