### ISSUE TITLE
Responsive navbar example with bootstrap 3

### ISSUE THREAD

**Issue by andr3w321** [angular-ui/bootstrap#1628]
I had a hard time finding any docs and figuring out how to get a responsive navbar to work.  Plunker wouldn't accept "!important" in css files either which turned out to be a problem.  I ended up getting a working example here: https://github.com/andr3w321/angularjs-bootstrap3-responsive-navbar-example  It would be great if someone could add this to the docs.

**Comment by carlotes247** [comment]
I just wanted to say that thanks to the github example that @Foxandxss made available I got fixed the same issue with the navbar. Thank you a lot, really :)

**Comment by luckylooke** [comment]
@antoinepairet made [best solution I have found so far](https://github.com/angular-ui/bootstrap/issues/394#issuecomment-69488620).
