### ISSUE TITLE
install via npm

### ISSUE THREAD

**Issue by indeyets** [angular-ui/bootstrap#1636]
Currently, angular-bootstrap is installable via bower and nuget. Would be great to register package in registry at https://npmjs.org/ to let it be installed via `npm install angular-ui-bootstrap`

**Comment by dylanjohnson** [comment]
+1

Two arguments:
  - Blocks usage in enterprise environments using npm integration with Nexus or Artifactory (neither supports Bower).
  - Many developers are already using npm for client-side package management, and the npm team has stated they'll be focusing efforts on this concern.

**Comment by maxkorp** [comment]
I submitted a PR, but it seems the issue is with how angular-ui publishing is handled. See my comments here: https://github.com/angular-ui/bootstrap/pull/3108
I'll file an issue in the publisher repo, and i (or someone else) can hopefully get that up and running asap.

**Comment by maxkorp** [comment]
For reference: https://github.com/angular-ui/angular-ui-publisher/issues/3

**Comment by leon** [comment]
@ProLoser  I took control over angular-bootstrap on npm and added ProLoser and christopherthielen to the owners list, so now we can have the same name in bower as in npm.

**Comment by rnicholus** [comment]
Looks like angular-bootstrap on npm is 0.13.0-SNAPSHOT, even though the package.json lists the version as 0.12.0.

**Comment by chrisirhc** [comment]
Note to self/maintainers refer to https://github.com/angular/angular.js/pull/10732

**Comment by wesleycho** [comment]
We definitely should look to try to tackle this sometime soon.

**Comment by rvanbaalen** [comment]
@wesleycho Added feature for 0.14?

**Comment by wesleycho** [comment]
We might want to think about doing this after 0.13.0 is out, and add support for CommonJS.

**Comment by BobbieBarker** [comment]
I agree with Wesley

**Comment by goldcaddy77** [comment]
All, more than happy to help out tackling this problem if you need more hands.

**Comment by wesleycho** [comment]
This is now published to npm.

**Comment by B3nCr** [comment]
It's not clear which npm package to install. 

angular-ui-bootstrap is out of date and has version 0.13.4
angular-bootstrap is even further behind 0.12.1

Has NPM support been stopped or am I installing the wrong package?

**Comment by B3nCr** [comment]
Okay, it's clear what to install now i've found https://github.com/angular-ui/bootstrap-bower

`npm install angular-ui-bootstrap` has installed the latest version after I deleted the other packages named above.. 

I, perhaps incorrectly, assumed that `npm install angular-ui-bootstrap` would update me to the latest version.

**Comment by icfantv** [comment]
@B3nCr, I believe the instructions you are seeking are [here](https://github.com/angular-ui/bootstrap#installation).
