### ISSUE TITLE
feat(alert) add auto removal after timespan

### ISSUE THREAD

**Issue by jhiemer** [angular-ui/bootstrap#165]
Hi,
the alert directive is a nice piece of code, but regarding usability in a real world application it is lacking of an auto removal after a specific timespan. The code snippet for automatic removal could look like this (I know the jQuery stuff needs to be removed).

``` javascript
var timeout = iAttrs.timeout || 10000;
scope.message = data;

iElement.show();

$timeout(function() {
   iElement.hide();
}, timeout);
```

What do you think, would that represent a good improvement?

**Comment by ErichBSchulz** [comment]
thanks all - good discussion - saved me an hour!
