### ISSUE TITLE
angular-ui 1.10 disabling bootstrap 3 responsive nav.

### ISSUE THREAD

**Issue by ronnross** [angular-ui/bootstrap#1672]
Once angular-ui 1.10 is added to a project the bootstrap nav bar doesn't work in responsive mode. For example when the browser is collapsed and the nav options are replace with a single list button. Clicking on the list button does not display the hidden menu options. Please let me know if you need more detail.

**Comment by jedwards1211** [comment]
Is it really impossible to make dropdowns work with ui-bootstrap-tpls as a drop-in replacement for bootstrap.js?  I mean I'm no expert but I would think something like the following would do it:
```
angular.module(...).directive('dropdown', function() {
    return {
        restrict: 'C'
        ...
    }
});
```

**Comment by schungx** [comment]
@Foxandxss, works perfectly.  Thanks for the tip!
