### ISSUE TITLE
Inline-Datepicker doesn't add ng-(in)?valid

### ISSUE THREAD

**Issue by Crisfole** [angular-ui/bootstrap#1688]
The inline datepicker allows typing in an invalid (disabled) date, and doesn't add the ng-invalid class to the datepicker.

It seems that the dropdown itself is modified to include the ng-invalid but not the actual input...Am I misunderstanding something?

**Comment by antoinepairet** [comment]
@ovaris see the updated README, we are working on angular 1.3 compatibility

**Comment by Crisfole** [comment]
@ovaris: I'm not part of the team.  I have exactly zero say in the `angular-ui`'s compatibility :)

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by kipusoep** [comment]
+1

**Comment by BenjaminCh** [comment]
+1

**Comment by chrisirhc** [comment]
Related work: #3020

Please don't +1, we already know this is a priority.

**Comment by estvmachine** [comment]
How alternative resolve this issue?, if i want a datepicker with validation of min and max. Thanks for the response in advance.

**Comment by avalon12** [comment]
Create a custom directive to do the validation for you, if you really need it.. Until a fix is available.

Here is a blogpost describing such a directive.

https://rashimuddin.wordpress.com/2014/08/24/date-range-custom-validation-in-angular-js/

**Comment by ComeOutToPlay** [comment]
Please refer to http://stackoverflow.com/questions/24359128/bootstrap-angular-datepicker-set-ng-model-invalid-not-change/31595743#31595743 at my response (Aquiles)

**Comment by narangrishab** [comment]
Hello Guys, How to do start date end date validation using Angular JS for bootstrap datepicker?

**Comment by wesleycho** [comment]
I believe this is fixed currently, as the homepage works as expected.

@narangrishab: take a look at the documentation for the datepicker, and read up on how validation in Angular works.

Closing as fixed.

**Comment by dylaninvodo** [comment]
As of September 15th, 2015 the datepicker-popup example at https://angular-ui.github.io/bootstrap/ is not correctly setting the error classes on the input element when a date is manually entered that is before the min-date value.

Screenshot: 
<img width="564" alt="screen shot 2015-09-15 at 2 09 27 pm" src="https://cloud.githubusercontent.com/assets/1335029/9887094/74204544-5bb3-11e5-86d5-c8094633fc08.png">

**Comment by cen1** [comment]
Yep, seems broken to me. Invalid not set on the text input.

**Comment by icfantv** [comment]
@dylaninvodo or @cen1, please open a new issue rather than piling on to an existing and unrelated issue that is already closed.  Doing so is a really good way to not get the issue fixed as we will most likely miss it.

If you so boldly dare to venture where many have gone before and want to file a new issue, please follow the instructions [here](https://github.com/angular-ui/bootstrap#found-a-bug).  Thanks.

**Comment by icfantv** [comment]
Oh for pete's sake.  Nevermind.  I just saw your issue.  I'll shut up now.

**Comment by humam-nameer-10p** [comment]
As an alternative to include range in date entered, I worked with UI.validate and it worked fine!

include dependency => 'ui.validate' 
In html 
` <input type="text" name="dob" show-button-bar="false"
                       class="tw-formControl"  uib-datepicker-popup="MM/dd/yyyy"
                       ng-model="vm.profile.attributes.dob" ui-validate="{outOfBounds : 'vm.checkDateLimits($value)' }" is-open="vm.calanderToggle" placeholder="mm/dd/yyyy"
                       datepicker-options="dateOptions"/>`

validations: 

`   <div class="tw-customValidation" ng-messages="profileForm.dob.$error"
                   ng-if="profileForm.dob.$dirty || profileForm.$submitted">
                <div ng-message="date">Please enter a valid date</div>
                <div ng-message="outOfBounds"> Date selected is out of range. </div>
              </div>`

In Controller:

```
  vm.checkDateLimits = function(selectedDate){
        var currentDate = new Date(selectedDate);
        var upperBounds = new Date();
        var lowerBounds = new Date('01/01/1900');

    return currentDate < upperBounds && currentDate > lowerBounds;

  }
```

documentation for [ui.validate](https://htmlpreview.github.io/?https://github.com/angular-ui/ui-validate/master/demo/index.html)
