### ISSUE TITLE
Adding focus to modal-window in modalWindow directive new in 0.10.0

### ISSUE THREAD

**Issue by dougmcclurg** [angular-ui/bootstrap#1696]
I recently upgraded my modal directive from 0.6.0 to 0.10.0.

My usage involves focusing an input inside the modal on launch which i was previously able to do in 0.6.0.

The addition of the below code in the modal directive in 0.10.0 does not allow me to focus on my input.

// focus a freshly-opened modal
element[0].focus();

The only things i can do to get around this are particularly messy and i was wondering if adding focus to the modal-window could be a configurable option?

If anybody has a clean way of solving i'd love to hear about it.

Thanks for all your killer work.

**Comment by lpsBetty** [comment]
with the latest stable versions `autofocus` does work again!

**Comment by nstuyvesant** [comment]
As of 2.2+, autofocus stopped working. 2.1.4 is working OK.

**Comment by Fernandolcs** [comment]
For me, autofocus only did work for the very first time I opened the modal, all next ones the focus did not work. I ended up implementing [this](https://shekhargulati.com/2017/12/02/adding-autofocus-to-an-input-field-in-an-angular-5-bootstrap-4-application/) and it worked fine.
