### ISSUE TITLE
$position returns wrong results for scaled components

### ISSUE THREAD

**Issue by nebril** [angular-ui/bootstrap#1703]
I am scaling my widget with css:transform because it would be inserted via iframe to other sites.

I am using tooltips in it, but when I started scaling I figured that their positioning was wrong. I dug a little and I think, that the $position service is responsible for the bug.

Here is plunk showing what I am talking about:
http://plnkr.co/edit/LOzAdR64snNulWnatl8b?p=preview

**Comment by BobbieBarker** [comment]
This issue is well over a year old and was against version .10

**Comment by BobbieBarker** [comment]
This issue is well over a year old and was against version .10
