### ISSUE TITLE
investigate tether for positioning improvements

### ISSUE THREAD

**Issue by skivvies** [angular-ui/bootstrap#1715]
I just came across https://github.com/HubSpot/tether and it looked pretty cool. Haven't yet looked at how it works, but wanted to share it here in case it's of interest or of any help with angular-ui's positioning needs. (I think there have been various bugs that have been hard to fix.)

**Comment by wesleycho** [comment]
Closing as we have decided not to support tether due to the size of the library.

We do intend on visiting the positioning issues though, hopefully in the next couple of months.
