### ISSUE TITLE
Display the autocomplete dropdown upwards if it is at the bottom of the browser window

### ISSUE THREAD

**Issue by Victa** [angular-ui/bootstrap#1735]
Hi,

I use the typeahead directive in a popover. If the popover is placed at the bottom of the window, the dropdown should be displayed at the top of the text input.

![](https://i.cloudup.com/tZYwKN7Po4.thumb.png)

**Comment by BobbieBarker** [comment]
Our drop downs have the same behavior as the current bootstrap 3 drop downs. Reopen if you'd like to submit a pull request.
