### ISSUE TITLE
$modal.open fails when including angular-mocks

### ISSUE THREAD

**Issue by jachenry** [angular-ui/bootstrap#1739]
After including angular-mocks to my project I've noticed modals no longer animate open when calling $modal.open. The modal gets stuck and the classes never get removed causing the opacity to stay at zero.

http://plnkr.co/edit/pRhDuKBL6m9nZkhQkWc4

**Comment by wesleycho** [comment]
Modal animations are now using ngAnimate to drive animations, so I believe this is not an issue any more.
