### ISSUE TITLE
Tabs don't play nicely with ng-class

### ISSUE THREAD

**Issue by xaralis** [angular-ui/bootstrap#1741]
Tabs component have issues when you add ng-class on the tab element.

Following chunk:
```
<tab ng-controller="Ctrl" ng-class="{true: 'valid', false: 'invalid'}[isValid()]"></tab>
```

results in:

```
<li ng-class="{true: 'valid', false: 'invalid'}[isValid()] {active: active, disabled: disabled}" ng-controller="Ctrl" class="ng-isolate-scope">
</li>
```

Have a close look to the ng-class which is improperly combined with tab's own ones.

**Comment by NaomiN** [comment]
KamBha, I support this idea. We also want to highlight the tab with invalid class if the form within it is invalid. We're using ui-views to display the form for each tab so I am not sure how to implement the suggested workaround of separate div.

**Comment by Kepro** [comment]
+1

**Comment by uguryilmaz** [comment]
+1

**Comment by ravikiran438** [comment]
https://github.com/angular/angular.js/issues/5695

**Comment by brujo696** [comment]
+1

**Comment by brujo696** [comment]
I had the same problem


```javascript
 <tab ng-class="{'hide-tab':($first && $last)}" >
   //...
</tab>
```

but I solved that with this

``` javascript
 <tab class="{{ ($first && $last) ? 'hide-tab':'' }} " >
   //...
</tab>
```

**Comment by icfantv** [comment]
Hey all, please see the discussion in #4172.  Using `ng-class` on a directive that uses `replace: true` is a very bad idea.  There are numerous issues around `replace: true` and even talk of deprecating/removing it.  But, unfortunately, it's not going anywhere soon and the caveat released by the core Angular team was that use it, but do so at your peril.  I.e., use it knowing that doing so incorrectly can break your DOM.

I suspect this issue will not be addressed.

**Comment by wesleycho** [comment]
Closing as won't support given the resolution in Angular.
