### ISSUE TITLE
docs(modals): $modalProvider.options is undocumented

### ISSUE THREAD

**Issue by nnjpp** [angular-ui/bootstrap#1759]
For a while I thought it was impossible to set global defaults. Even a google search for modalProvider.options is lacking helpful info. I think it would be helpful for others to know how this works. A simple snippet like this would suffice:
```
angular.module('myApp')
  .config(['$modalProvider', function($modalProvider) {
    $modalProvider.options = {
      backdrop: 'static'
    };
  }])
```
I can try to find time to submit a PR for this sometime before the end of the week

**Comment by abobwhite** [comment]
+1 on this. This was very confusing and it a search through the repo issues yielded something with ```modalConfig``` which was supposedly added in v.0.12.0 but it is nowhere to be found.

This method does work - thank you!

**Comment by seiyria** [comment]
+1 -- just needed this, glad I found this issue.
