### ISSUE TITLE
Collapse does not expand if div is hidden

### ISSUE THREAD

**Issue by craftyInstigator** [angular-ui/bootstrap#1774]
If a div is hidden when collapse value is toggled from true to false, the div is not expanded, and is stuck in collapsed state with a class 'collapsing'. This can be easily reproduced by setting collapse to true, setting ng-show to false, then set collapse value to false, then set ng-show to true. The div will remain collapsed even though collapse value is now false.

**Comment by psldevelopers** [comment]
Can this fix to be applied to 0.12? We who are still with Angular 1.2.X need this fix as ewll.
