### ISSUE TITLE
Tooltip show wierdly even if content is whitespaces

### ISSUE THREAD

**Issue by thierryx96** [angular-ui/bootstrap#1780]
Tooltips show, even if text is white spaces. The content (whitespaces) isn't even displayed, which in my opinion is inconsistent behavior ;) . My fix proposal is checking if the text is empty (as it is already), and whitespace(s) to prevent the tooltip rendering.

![tooltip_normal](https://f.cloud.github.com/assets/4757194/2135150/105ab780-92f9-11e3-8a9f-66039972b526.jpg)
![tooltip_whitespaces](https://f.cloud.github.com/assets/4757194/2135151/105eb556-92f9-11e3-9691-750d9496bb24.jpg)

**Comment by wesleycho** [comment]
Re-opened, issue was never resolved.
