### ISSUE TITLE
Tabs with an expression for the 'active' attribute break

### ISSUE THREAD

**Issue by Aklakan** [angular-ui/bootstrap#1791]
With v0.10.0 (via bower) I am trying to obtain a tab's active state from an expression, such as `<tab active="{{foo() == bar}}">...</tab>"`, however it breaks with 'undefined is not a function' 
It seems that a simply wrapping the `setActive` call with an if statement does the trick:

          getActive = $parse(attrs.active);
          setActive = getActive.assign;
        //...
        scope.$watch('active', function(active) {
          // Note this watcher also initializes and assigns scope.active to the
          // attrs.active expression.
          if(setActive) { // <--- Add this
              setActive(scope.$parent, active); // <-- This breaks because an expression's value can't be set
          } // <--- Add this

**Comment by rvanbaalen** [comment]
Continuing in #1496
