### ISSUE TITLE
$digest in progress for modal dialogs

### ISSUE THREAD

**Issue by randymenna** [angular-ui/bootstrap#1798]
version 0.10.0
ui-bootstrap-tpls.js line 1539

currently is just: scope.$apply() and this gives a $digest already in progress error when closing modal dialogs, sometimes.  It should be changed to:

           if(!scope.$$phase) {
                scope.$apply();
            }

**Comment by antoinepairet** [comment]
I will close this for now. Feel free to reopen once you have a clear and clean reproductible scenario  in plunkr. thanks

**Comment by yesnoj** [comment]
Hi,i've the same problem with a modal where there is an input googleplace field.If i start typing a place and exit while the suggestion are still opened, i got this error...
