### ISSUE TITLE
Accordion toggleOpen() assignment throws exception if is-open attribute is set to read only value

### ISSUE THREAD

**Issue by Vinai** [angular-ui/bootstrap#1800]
On the following example the `is-disabled` and `is-open` attributes are set to a model `isStacked`.
```
<accordion-group heading="The Title" class="col-sm-6" is-disabled="!isStacked" is-open="!isStacked">
    <div>The Content</div>
</accordion-group>
```
Whenever the ```isStacked``` model changes value, the accordion group is activated or disabled, and opens or closes as expected.
All great until the new ```toggleOpen()``` method is called.
Then the exception that is thrown is
```
Error: [$compile:nonassign] Expression '!isStacked' used with directive 'accordionGroup' is non-assignable!
```
The assignment in question is
https://github.com/angular-ui/bootstrap/blob/master/src/accordion/accordion.js#L85

**Comment by rvanbaalen** [comment]
We would not consider such a PR unfortunately since it will add unnecessary extra API functions.
