### ISSUE TITLE
ng-click seems not to work in alerts

### ISSUE THREAD

**Issue by johnnywell** [angular-ui/bootstrap#1804]
live demo here http://plnkr.co/wUE0jJHik7sFYgPXVgq8

**Comment by santoshkt** [comment]
I'm using UI Bootstrap 0.11.0 SNAPSHOT. This solution doesn't work on it. I'm not sure what is missing. Appreciate any help if there is anything w.r.t version in this solution.

**Comment by santoshkt** [comment]
Here is the plunkr for the Bootstrap js and css I'm using.

http://plnkr.co/edit/7H1h9LVfboW97pwTFUhS?p=preview

I have placed bootstrap.less but not referenced it in index.html as the less file contains other references. However, I placed it in plunkr just if that can help find any bug.

When I ran this in my application, in console log, I could see the directive being called properly. There seems to be some problem with js/css working together. Appreciate pointers.
