### ISSUE TITLE
Modal + iOS virtual keyboard

### ISSUE THREAD

**Issue by stajs** [angular-ui/bootstrap#1812]
There is a bug with Bootstrap 3 modals when the virtual keyboard in iOS is displayed:

- http://www.abeautifulsite.net/blog/2013/11/bootstrap-3-modals-and-the-ios-virtual-keyboard/
- https://github.com/twbs/bootstrap/issues/9023

iOS/Safari converts elements that are `position: fixed` to something else (`relative` I think) when the virtual keyboard is shown. I have created a plunk to reproduce the downstream effect on Angular UI Bootstrap:

- http://plnkr.co/edit/Qe7QCn

### Bottom of modal is cut off

1. Open the modal from the link at the top of the page.
2. Tap in to the first input field.
3. Use the virtual keyboard "next input field" control (`>`) to tab to the last input.

![photo 1](https://f.cloud.github.com/assets/2253814/2181710/cc7aff08-9761-11e3-8666-0107a396bb67.PNG)

### Overlay does not cover above modal

1. Open the modal from the link at the bottom of the page.
2. Tap in to input 6.
3. Swipe down (to scroll up).

![photo 2](https://f.cloud.github.com/assets/2253814/2181711/d11dc464-9761-11e3-8956-d7c4e17bc973.PNG)

### Overlay does not cover below modal
1. Open the modal from the link at the top of the page.
2. Tap in to input 7.
3. Swipe up (to scroll down).

![photo 3](https://f.cloud.github.com/assets/2253814/2181712/d578be06-9761-11e3-8cac-eb09b93cc1f4.PNG)

The only workaround that seems to actually work so far involves (ugh) user-agent sniffing. As terrible as that sounds, I have implemented a fix locally and would like to submit a PR for review.

**Comment by niftylettuce** [comment]
@gabesumner thanks for your code!

**Comment by niftylettuce** [comment]
@gabesumner Have you seen this <http://www.abeautifulsite.net/bootstrap-3-modals-and-the-ios-virtual-keyboard/>? /cc @gilluminate @talha-asad @cvrebert @stajs

**Comment by stajs** [comment]
@niftylettuce Yeah, I linked to that blog post when I raised the issue (although he has removed the `/blog/2013/11` from the URL). =)

**Comment by wesleycho** [comment]
I believe that this can be fixed through usage of the `windowClass` and `backdropClass` options, with user agent sniffing in the user's codebase.  I do not believe this is something that UI Bootstrap should address.

**Comment by hetAuxo** [comment]
You can add a rule globally:
              if( navigator.userAgent.match(/iPhone|iPad|iPod/i) ) {
                var styleEl = document.createElement('style'), styleSheet;
                document.head.appendChild(styleEl);
                styleSheet = styleEl.sheet;
                styleSheet.insertRule(".modal { position:absolute; bottom:auto; }", 0);
              }

**Comment by stnor** [comment]
That rule fixed my issues! Thanks for sharing!

**Comment by saurabhudaniya200** [comment]
is there an angular way to fix this???

**Comment by raykudo** [comment]
+1

**Comment by swinston1000** [comment]
Also looking for an angular solution!

**Comment by sergkulikovskyi** [comment]
@hetdev thank you!!! But I upgraded your workaround a little bit, so I got something like this:

><input
> 	...
> 	ng-focus="$auth.changeModalPosition('absolute')"
> 	ng-blur="$auth.changeModalPosition('fixed')"
> />

> // this is a fix for ios modal position:fixed input bug
> $auth.changeModalPosition = position => {
> 	if( navigator.userAgent.match(/iPhone|iPad|iPod/i) ) {
> 		var styleEl = document.createElement('style'), styleSheet;
> 		document.head.appendChild(styleEl);
> 		styleSheet = styleEl.sheet;
> 		styleSheet.insertRule(`.modal { position:${position}; bottom:auto; }`, 0);
> 	}
> }
