### ISSUE TITLE
Pagination and SEO

### ISSUE THREAD

**Issue by aromka** [angular-ui/bootstrap#1824]
Right now pagination is using ng-click to switch pages, meaning when rendering pages for SEO purposes, there are no links .. if setting ng-href to switch pages, then pages don't get switched properly .. any suggestions how to do it properly so the links would be crawlable?

**Comment by jbarker4682** [comment]
What we ended up doing was adding both an ng-click and an href to an anchor tag, passing the $event object to the click handler and then calling $event.stopPropagation().

Ex: <a href="/foo/bar/3" ng-click="GoToPage(3, $event)">Page 3</a>

$scope.GoToPage = function(pageNumber, $event)
{
     $event.stopPropogation();

     //... do navigation logic
}

**Comment by v4l3r10** [comment]
+1

**Comment by sangharsh** [comment]
+1

**Comment by icfantv** [comment]
@v4l3r10, @sangharsh, please do not simply add `+1` to issues.  It adds no intrinsic value to the discussion and serves to only clutter up the thread.  If you would like to voice your support for an issue without actually commenting, you may use GH's reaction feature - the smiley icon next to the pencil/edit icon in the upper left corner of a comment.
