### ISSUE TITLE
Two datepickers on the page both open

### ISSUE THREAD

**Issue by jfreal** [angular-ui/bootstrap#1853]
If you have two pop up datepickers on the page, both will open when either of the input buttons are focused.

I set up a plunker where you can see the changes: http://plnkr.co/edit/c28JnZfcuU0Gy5mX0max?p=preview

All I did was duplicate the existing html input field and the error occurs

**Comment by enjareyes** [comment]
Having the same issue as @arook where my datepickers are in ng-repeat so I have many of them and when I click one they all open. They have unique id's but currently share the same model. Is there a way to handle this?

**Comment by icfantv** [comment]
@enjareyes you might try using the latest build or build from `master` as we've decoupled the date picker popup from the actual date picker directive.

**Comment by agravat202** [comment]
i am using **add new** button and each form have from and to .
html : 
`<p class="input-group">
                                <input type="text" class="form-control" uib-datepicker-popup="{{dateFormat}}" ng-model="food.time.date_from" is-open="from.opened[$index]" datepicker-options="dateOptions" close-text="Close" alt-input-formats="altInputFormats" />
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" ng-click="open_from($index)"><i class="glyphicon glyphicon-calendar"></i></button>
                                  </span>
                            </p>

<p class="input-group">
                                <input type="text" class="form-control" uib-datepicker-popup="{{dateFormat}}" ng-model="food.time.date_to" is-open="to.opened[$index]" datepicker-options="dateOptions" close-text="Close" alt-input-formats="altInputFormats" />
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" ng-click="open_to($index)"><i class="glyphicon glyphicon-calendar"></i></button>
                                  </span>
                            </p>
`


IN CONTROLLER : 
`$scope.dateFormat = 'dd-MM-yyyy';

        $scope.from = {
            opened: [false],
        };

        $scope.to = {
            opened: [false],
        };

        $scope.open_from = function (index) {
            for (var i = $scope.foodArray.length - 1; i >= 0; i--) {
                if (i === index) {
                    $scope.from.opened[i] = true;
                } else {
                    $scope.from.opened[i] = false;
                }
            }
        };

        $scope.open_to = function (index) {
            for (var i = $scope.foodArray.length - 1; i >= 0; i--) {
                if (i === index) {
                    $scope.to.opened[i] = true;
                } else {
                    $scope.to.opened[i] = false;
                }
            }
        };`
