### ISSUE TITLE
TZ localization in date picker should be optional

### ISSUE THREAD

**Issue by porschelau** [angular-ui/bootstrap#1891]
We have an application which operates solely on UTC time despite of the fact that we have works in PST as well as EST. We are running into issues where we really just want the date picker to show the date in UTC mode rather than localizing it by default.

I am proposing that we offer this as a bindable configuration at the date picker level and pump the configuration into the ng-date-filter. I have a separate ticket to represent the changes needed at the date filter.

**Comment by ensAlejandro** [comment]
+1

**Comment by przemoli** [comment]
Any update?

**Comment by wesleycho** [comment]
Just noting, I have a current work in progress where the datepicker defaults to the timezone of the date bound to the model initially - I should be able to have this ready by the end of the week.

**Comment by wesleycho** [comment]
Currently, one can set an initial model value of the desired timezone and that timezone will be used throughout the datepicker.

If one wants to dynamically change it, that still needs work, but is also captured in other issues.
