### ISSUE TITLE
problem when data saving in typeahead with ng-blur and typeahead-on-select event

### ISSUE THREAD

**Issue by asithw** [angular-ui/bootstrap#1903]
if typeahead use with ng-blur event(when user need additional word after picking from dropdown ) also have to use  typeahead-on-select event (data picking).if some one need to write additional word have use ng-blur event for data saving.

so when selecting item from drop down both events fire with two DIFFERENT model values.so it is better to dissable ng-blur when data picking

http://plnkr.co/edit/8gu3J8jyDSGqBDTYqfuz?p=preview

check with  console log

**Comment by intensite** [comment]
Has this issue been resolved?  Is there a work around?

The problem appears when the user clicks on an item after partially typing content in the typeahead.  The blur event is fired with only the portion that was typed and not the full item selected, thus causing serious validation issues.

**Comment by ahmedmdmohiuddin** [comment]
Any resolution for this issue ?

**Comment by stefanhuber** [comment]
This is still a problem! Not resolved!

**Comment by Ahmed-Saleh** [comment]
I worked on a workaround. but still this an issue here as well.

**Comment by ceolaflannery** [comment]
Any solution for this/work around that anyone has found?

**Comment by legumanP2T** [comment]
A solution could be to have a callback function on the typeahead close event. But there is not…

**Comment by JulieMarie** [comment]
If this issue is closed and all associated issues are closed as well, how does this get fixed?  This is still unresolved as of 2.0.0.
