### ISSUE TITLE
Tooltip on button doesn't hide if button is disabled on click

### ISSUE THREAD

**Issue by johnsonjake** [angular-ui/bootstrap#1926]
I have a "cancel/reset" button that gets ng-disabled if the form is $pristine.

Clicking the button clears the form and then instantly becomes disabled. the tooltip is not hidden.

here's a [plunk](http://plnkr.co/edit/661Zw8LYKArZV7RHgo19?p=preview)

**Comment by Hypercubed** [comment]
Hmmm....  was this closed because it was fixed or because it will be fixed in the future?  I'm currently using this CSS as a workaround:

```
button[disabled] + .tooltip {
  display: none !important;
}
```

plunker with workaround: http://plnkr.co/edit/jtfr72?p=preview

**Comment by Hypercubed** [comment]
Hmm... has a problem that the tooltip will show again if the button is again re-enabled.

http://plnkr.co/edit/WlwybG?p=preview

Perhaps the tooltip directive should observe the ng-disabled attribute?

**Comment by karianna** [comment]
Can you open a new bug please :-)
