### ISSUE TITLE
Date format dd/MM/yyyy is not handled properly in datepicker

### ISSUE THREAD

**Issue by yukiachen** [angular-ui/bootstrap#1939]
hello there, 

I'm having a problem using the datepicker plugin with the format dd/MM/yyyy ,  I have my datepicker initialized as below. 

<pre>
&lt;input type="text" datepicker-popup="dd/MM/yyyy" ng-model="fromDate" min="mindate" max="maxdate" /&gt;
</pre>

It works fine if I select the date from the calendar popup. but if I type in the date in the input box in the format 'dd/MM/yyyy', it will recognize the 'day' as the 'month'. eg. if type in '16/03/2014', datepicker will treat 16 as the month, and generate an undefined result. 

When reading the code in ui-bootstrap-tpls.js,  I found the following code in the function parseDate of directive 'datepickerPopup',  the viewValue is in the format 'dd/MM/yyyy', but when the Javascript Date object takes it in, it will assume the format to be 'MM/dd/yyyy' , 

<pre>
var date = new Date(viewValue);
</pre>

So I have made my temporary fix to replace the above line with the following,  and it's now working for me, could you please fix this problem in your repo, so we dont keep this custom code in your file.

<pre>
var date = null;
            if(dateFormat === 'dd/MM/yyyy' || dateFormat === 'dd/MM/yy') {
                var dateParts = viewValue.split("/");
                date = new Date(dateParts[2], dateParts[1]-1, dateParts[0]);
            } else if(dateFormat === 'dd-MM-yyyy' || dateFormat === 'dd-MM-yy') {
                var dateParts = viewValue.split("-");
                date = new Date(dateParts[2], dateParts[1]-1, dateParts[0]);
            } else {
                date = new Date(viewValue);
            }
</pre>

**Comment by abdalrahmannada** [comment]
i face this broblem and i dont get solution i have model date type when i pass json date MM/dd/yyyy
it chose the correct date but i make format dd/MM/yyyy on the datpicer html it show correct date with wrong format , if i pass json Date object in the format dd/MM/yyyy then it make month as a day and Day as a Month , how can i solve this Prblem ( correct Date , Correct Format )
