### ISSUE TITLE
use $resolve from angular-ui-router for modal resolver

### ISSUE THREAD

**Issue by boxxxie** [angular-ui/bootstrap#1959]
I ran into some problems where i need one resolve to get a value from a previous resolve, this is something that angular-ui-router $resolve knows how to do, but the resolve function for bootstrap.modal doesn't know how to do.

the resolve component of angular-ui-router is it's own module and shouldn't be too difficult to use in this library.

**Comment by techniq** [comment]
What @alachaum described would be very helpful with resolving modal dependencies.  I ran into this issue today.

**Comment by tmaiaroto** [comment]
I think I had the same need, though I'm looking at it from configuration ```app.config()``` and not a factory. Here's an example of how I was able to pass along a previously resolved provider as a dependencies into an existing controller used by ```$modal```. Basically using ```onEnter``` was the trick and understanding that I needed to add another resolve with the provider object.

This FAQ helped me: https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-open-a-dialogmodal-at-a-certain-state

```
$stateProvider
.state("main", {
  abstract: true,
  template: '<ui-view/>',
  resolve: {
    UserService: 'UserService',
    CurrentUser: function(UserService) { return UserService.me(); }
  }
})
.state("main.documentAdd", {
  url: "/document/add",
  onEnter: ['$stateParams', '$state', '$modal', '$resource', 'CurrentUser', function($stateParams, $state, $modal, $resource, CurrentUser) {
    $modal.open({
      templateUrl: "templates/modals/add-document.html",
      resolve: {
        // NOTE: CurrentUser: 'CurrentUser' will NOT work here
        CurrentUser: CurrentUser
      },
      controller: 'documentCtrl'
    }).result.finally(function() { $state.go('^.main.documents'); })
  }]
})
```

**Comment by dmgr** [comment]
Maybe that implementation would be helpful: http://stackoverflow.com/a/37699891/453581
