### ISSUE TITLE
Pagination with max size does not display correct number of pages when on last page

### ISSUE THREAD

**Issue by lananelson** [angular-ui/bootstrap#1961]
Not sure if this is intended behavior but it seems to me that when `max-size` is set to 5 user should always have 5 pages to choose from.

If we are on the first page we see 5 pages as expected:
![image](https://f.cloud.github.com/assets/2564272/2473917/fbf8ad14-b045-11e3-8287-16e7862fe68e.png)

When we are on the last page we only see 3:
![image](https://f.cloud.github.com/assets/2564272/2473929/0fc521ec-b046-11e3-8104-5ff490e6855e.png)

I looked at the code and tried to change the way first page number is calculated in `getPages` but could not figure it out.

I know though that issue will only occur when

```
totalPages % maxSize !== 0
```

**Comment by maganjo** [comment]
Though it is an old question. am using uib-pagination and i did set max-size="5" and it worked.
