### ISSUE TITLE
Custom css class for tooltip

### ISSUE THREAD

**Issue by dennis-g** [angular-ui/bootstrap#1976]
It would be great to customize the tooltip with a custom css class.

**Comment by cjroth** [comment]
+1

**Comment by NewMediaRoc** [comment]
+1

This is fairly important so that you can create tooltips for different reasons and leave it up to the user to define the style overrides.

**Comment by nick-barth** [comment]
+1

**Comment by mvarrieur** [comment]
+1

**Comment by davidv** [comment]
+1

**Comment by amyhua** [comment]
+1

**Comment by voznik** [comment]
+1

**Comment by nshahpazov** [comment]
+1

**Comment by jengeb** [comment]
+1

**Comment by krishansolanki** [comment]
+1

**Comment by BoeFly** [comment]
+1

**Comment by bkirk1012** [comment]
+1.  I'm currently customizing the inner ui-boostrap popover content by using a `uib-popover-template`. A custom css class would make this much easier.  Additionally, a separate custom class would be useful for customizing the overall popover css on an as-needed basis.

**Comment by iberodev** [comment]
+1. 
still no plans to allow this?

**Comment by icfantv** [comment]
Please refrain from adding only `+1` to issues as it adds no intrinsic value to the discussion and serves to only clutter up the thread.

**Comment by davidv** [comment]
I guess that's is fundamentally debatable. Is there another forum or way to
ask if anyone is working in this or call for attention to this missing
piece?

regards
David Vaassen
Managing Director


E-see International Limited
4 Devon Lane  |  Devonport  | Auckland 0624 | NZ
T:  +64 9 44 66 22 5  |  M: +64 21 648 962  |  E:  david@e-see.com

LinkedIn: nz.linkedin.com/in/davidvaassen | Twitter: davidvaassen  |
 Skype: david.vaassen

*e-see® Brand File Manager > The easiest way to manage and share your brand
and marketing assets > www.e-see.com <http://www.e-see.com>*

..........................................................................................................................................

This message (including any attachments) contains information that may
be confidential and/or privileged. It is intended only for the person(s) to
whom it is addressed.
