### ISSUE TITLE
dropdown-toggle click event.stopPropagation() causes typeahead on same page not to close

### ISSUE THREAD

**Issue by bcronje** [angular-ui/bootstrap#1986]
Typeahead currently relies on a click event registered on document to detect when to close its dropdown. However the standard dropdown-toggle directive registers a click event on its element and then calls `event.stopPropagation()`. This results in a situation where if you have both a typeahead and standard dropdown on the same page, and the typeahead is currently open and you click on the standard dropdown the typeahead is not closed.

I see two ways to fix this:
1. Refactor dropdown-toggle to not stop propagation on click.
2. Refactor typeahead to not use click event on document.

I was unable to find a clean way for (2), but (1) turned out to be rather easy and clean. Will send a PR shortly for this.

**Comment by AnMa12** [comment]
what worked for me:

_file.component.ts_
**stopPropagation(event) {
  event.stopPropagation();
}**
fdiv1() {
  alert("div1 was pressed!");
}
fdiv2() {
  alert("div2 was pressed!")
}

_file.component.html_
<div (click)="fdiv1()" style="background-color: red; width: 150px; height: 150px">
   <div (click)="stopPropagation($event); fdiv2()" style="background-color: yellow; width: 50px; height: 50px">
   </div>
</div>
