### ISSUE TITLE
Typeahead issues

### ISSUE THREAD

**Issue by vitaly-t** [angular-ui/bootstrap#1988]
Just looking at the Typehead demo that's on the library's official website, it doesn't seem to work right.

 - Example 1, for "Asynchronous results"
Type in "Mosc", nothing comes up. Then press "o", suddenly 2 items come up, then "w", for "Moscow", it is found, but strangely, wasn't shown before on the list. That is wrong.

- Example 2, for "Custom templates for results"
Type in something and select any item found. Now hit Backspace to remove the last symbol. The select list appears totally out of place.

Tested in Chrome version 33

**Comment by wesleycho** [comment]
This does not appear to be issues with typeahead itself.

The second one is a demo site issue, and PRs are welcome fixing it.

**Comment by wesleycho** [comment]
Closing, as it appears this has been fixed.
