### ISSUE TITLE
Open modal on top of an other modal

### ISSUE THREAD

**Issue by Timsen88** [angular-ui/bootstrap#1995]
Im refering here to : https://github.com/angular-ui/bootstrap/blob/master/template/modal/backdrop.html

When i open multiple Modals on top of eachother , backdrop is alway 1 modal behinde. here is an example: 
![image](https://cloud.githubusercontent.com/assets/6431888/2540347/3c1857e6-b5d2-11e3-8cbc-520b6637aa24.png)

as you can see on picture i have 3 modals, and backdrops z-index is 1060, while last modal z-index is 1070, which means that backdrop is only applied to second modal. And here is my quiestion, when backdrop is counting z-index, shouldnt it statart from 1050? 

{'z-index': 1050 + (index && 1 || 0) + index_10} instead of {'z-index': 1040 + (index && 1 || 0) + index_10} if i want to have more then 1 modal up at a time? 

Or maybe there are a reason for it to start from 1040? Ive tested it with 1050 and everything worked fine, but i want to be sure im not going to destroy some other part of the application.

**Comment by geri777** [comment]
I am running 2.5.2 and I experience the same problem.

The modal windows have this style: ng-style="{'z-index': 1050 + $$topModalIndex*10, display: 'block'}"
The computed z-index from this in Chrome is 9999 for all modal windows. Even though each new window is placed before the previous one in the html code, it is displayed behind in my gui.
