### ISSUE TITLE
Unable to focus on inputs inside modals on touch devices

### ISSUE THREAD

**Issue by jdhiro** [angular-ui/bootstrap#2017]
There is a related issue opened against angular, but I suspect this is an issue specifically with the modals. https://github.com/angular/angular.js/issues/6432

Plnkr is here: http://embed.plnkr.co/gyNF9BhiaBuMtonPXYKS/preview

This repro requires:
1.  Having an input inside of a UI Bootstrap modal box
2.  Having angular-touch enabled (checked against 1.2 and 1.3)
3.  Being on a touch device or using Chrome's touch emulation

Repro steps:
Click the button to open the modal, and then click on the text input field. On touch devices, the field will momentarily get focus and then lose it. With a normal mouse click, it's fine.

**Comment by psychowood** [comment]
Problem is still present, why the issue is closed?

**Comment by numerized** [comment]
awesome fix ! I'll put a link to it for TextAngular users. Nice editor to use as a edit in place editor.

**Comment by mato75** [comment]
Is a fix present in angular-touch, because with 1.3 version it is not working.

**Comment by Yappli** [comment]
In my point of view, the hack describe below is not a decent solution. We need a real fix. I will work on it.

**Comment by breynolds** [comment]
I agree with Yappli. This needs to be fixed. It's outrageous that something as simple as a modal window doesn't work across all mobile devices and this bug has been sitting here for a year. We shouldn't have to sprinkle directives all around our code and mess around with the event model just to get a simple modal to work.

**Comment by bruteforce** [comment]
The hack suggested works only for input field.

**Comment by Sankluj** [comment]
A fix might be on the way for angular-touch :) https://github.com/angular/angular.js/pull/11212

**Comment by persianturtle** [comment]
jdhiro's fix worked for select, textarea and checkbox fields in my case.  Thank you!

**Comment by Veraprot** [comment]
this fixed the issue on android, however it didn't fix it on ios.

**Comment by salangar** [comment]
Is this the same problem? - 
http://stackoverflow.com/questions/32367621/unable-to-display-right-tick-mark-in-checkbox-in-tablets-and-ipad

But I have already added $event.stopPropagation();


Thanks

**Comment by andycao** [comment]
this fix is working, although it is not best fix.
i can see the main reason of this bug is about touch and events from the fix, is it right?
thank you

**Comment by ericbj** [comment]
thanks jdhiro, works like a charm

**Comment by timum-viw** [comment]
Thanks. Saved me a lot of time and headaches

**Comment by dsiebeck** [comment]
The proposed directive from jdhiro works great for me. Thank you!

**Comment by wesleycho** [comment]
This seems resolved currently - see my comment in https://github.com/angular-ui/bootstrap/issues/4214#issuecomment-152092606, it does not display the prior behavior anymore.

**Comment by marcelkalveram** [comment]
If anyone is struggling with an issue where the modal loses focus when clicking inside a text input field inside the modal, I've been able to resolve it by setting:

```
.modal { position: absolute }
```

It looks like position is fixed by default and this was causing some weird behaviour for me in iOS Safari.

**Comment by icfantv** [comment]
@marcelkalveram, I would argue that modals on a mobile device are quite poor UX.  Same with tooltips and popovers.
