### ISSUE TITLE
scope.$digest() in 0.10.0 causes a $digest infinite loop

### ISSUE THREAD

**Issue by Camusensei** [angular-ui/bootstrap#2024]
Hello.
Using this plunker (http://plnkr.co/edit/1vs7dmwnjx7c65N2KdKS?p=preview), I noticed a bug in the tooltip directive... using an interpolated value in the tooltip, if the value is not trivial to display (a variable is trivial to display, a new Date() is not), if the user hovers in and out of the element the directive has been applied to, an "Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!" with a very long stack trace appears.

How to reproduce:
1. Visit that plunker.
2. open your console (I tested the bug in both firefox and chrome)
3. hover the input with your mouse
4. move your mouse in and out from the input really fast

As soon as an error appears in the console, stop moving your mouse or your browser will freeze from having to display a near infinite amount of errors ^^

Regards,
Camusensei

PS: ui-bootstrap 0.9.0 did NOT have this problem.

**Comment by wesleycho** [comment]
This appears to no longer be an issue with current master at least: http://plnkr.co/edit/Pz7kosxLbhyHyAVEMvwv?p=preview

**Comment by Ir1sh** [comment]
I still get this on 0.13.2 should that release have the fix you mention @wesleycho

**Comment by wesleycho** [comment]
I'm not able to reproduce this at all.
