### ISSUE TITLE
Timepicker does not support has-success and $invalid

### ISSUE THREAD

**Issue by smuellerus** [angular-ui/bootstrap#2030]
Hi,

in contrast to the Datepicker, the Timepicker does not support the error class has-success (it only supports has-error). Also, it does not set $invalid when the input is invalid, e.g. when the hour is "25".

![image](https://cloud.githubusercontent.com/assets/2101681/2649528/98f72622-bf64-11e3-8c12-d046286de533.png)

It would be great if this would be fixed/supported in the next version.

Thanks!

**Comment by wesleycho** [comment]
Looking at the source, I believe the $invalid and `has-error` class issues are resolved. The `has-success` behavior should be opt-in though, and a PR would be welcome for this.

**Comment by wesleycho** [comment]
Considering this further, the datepicker does not currently have `has-success` support, and this is a feature that is easy to implement on the user's side using Angular's validation states for ng-model and ng-class, so I am resolving this as something we won't support.
