### ISSUE TITLE
Modal: Provide default simple modals.

### ISSUE THREAD

**Issue by arg20** [angular-ui/bootstrap#2034]
Sometimes I find myself implementing small modal templates for confirmation windows. For instance if a user whishes to delete a resource and I have to ask for confirmation. Or when somebody clicks an image and I want to display it, I have to create a template just to show the image.

I think there could be some value in providing this functionality out of the box. A modal.confirm function or adding a modal directive to an img tag to simply display it in a sort of "lightbox" fashion.

What do you think?

**Comment by rvanbaalen** [comment]
@gazoakley Any progress on that PR? It's been over a year :wink: I assume this one can be closed. Feel free to re-open if still relevant.
