### ISSUE TITLE
angular UI bootstrap popup datepicker combined with ui.mask

### ISSUE THREAD

**Issue by TomVanHaver** [angular-ui/bootstrap#2036]
Hi,

I am taking my first steps in Angular & hope i am in the correct place to find an answer to my question/issue.
If not, please point me in the right direction.

I am using the angular UI bootstrap popup datepicker like the example here : 
http://angular-ui.github.io/bootstrap/#/datepicker 

When i combine this with the uiMask Directive ( http://angular-ui.github.io/ui-utils/) the values in the input get scrambled when i pick a date.

I suspect because of the difference in type on the angular model : datepicker wants JS Date object/ ui.mask wants (masked) string.

When the picked date gets formatted/parsed by uiMask, it goes wrong :-/

Is what i am trying to do even possible ?

kind regards, Tom.

**Comment by sistemanick** [comment]
Is there any plan to include a masking feature for datepicker? For the life of me I can't get ui-mask to play nice with either ui-bootstrap or angularstrap's datepicker.
