### ISSUE TITLE
typeahead="optionItem.id as optionItem.label for optionItem in collection"

### ISSUE THREAD

**Issue by zerkowsm** [angular-ui/bootstrap#2041]
Hi,

This is a followup to http://stackoverflow.com/questions/17856126/angularjs-bootstrapui-typeahead-with-object-selection-functionality and last Brian Graham comment (http://jsfiddle.net/jLupa/87/).

Why typeahead="optionItem.id as optionItem.label for optionItem in collection" stopped working somewhere after angular 1.0.7 and ui-bootstrap-tpls.min.js somewhere after  0.4.0.

Is there a possibility to make this pair working together using the newest angular (1.2.11 or 1.2.12) and the newest ui-bootstrap 0.10.0?

Thanks,
Maciek

**Comment by BobbieBarker** [comment]
Please test against latest version and reopen if this is still an issue
