### ISSUE TITLE
popover-append-to-body doesn't append to body

### ISSUE THREAD

**Issue by ux-engineer** [angular-ui/bootstrap#2045]
Hi,

popover-append-to-body setting doesn't append the created element to body, but rather it is still nested within the tooltip element... I seem to not be able to get z-indexes right. I have several tooltipped elements on vertical row. If I have set z-index for the tooltipped element and its being lower than tooltip's elements z-index, the tooltip stays behind the tooltipped element.

**Comment by RossRogers** [comment]
Mr. Kozlowski,

[I forked your plnkr to the more recent:](http://plnkr.co/edit/6THyQVEpjOB5ozFTPU20?p=preview)
* angularjs. 1.3.15
* angular-ui 0.13.0
* bootstrap 3.3.4

It appears that `popover-append-to-body` no longer works in your example.  Am I using an incompatible set of versions? Or is this now a bug?  If so, I'll file a new bug.

 - Ross
