### ISSUE TITLE
Prevent the first tab becoming automatically selected on page load

### ISSUE THREAD

**Issue by elduderino87** [angular-ui/bootstrap#2058]
Something that's been driving me nuts recently, why is the first tab's select event always fired on page load? Is it possible to prevent the first tab from becoming selected by itself?

http://plnkr.co/edit/qXekJKNhf0yd0gla2PWq?p=preview

**Comment by jamime** [comment]
I think most people use this to perform the action instead of calling this in their controller constructor. Do you have a specific example where this is not suitable?

**Comment by rvanbaalen** [comment]
Go to StackOverflow to ask about implementation questions. This is not a bug, but a feature.
