### ISSUE TITLE
Tooltip is not closed when related element is disabled

### ISSUE THREAD

**Issue by Myrmex** [angular-ui/bootstrap#2059]
In my Angular app, when I place a tooltip on a button, it shows as expected; but if the button gets disabled (by the underlying controller) after being clicked, and the tooltip was being shown, the tooltip is not hidden and stays there forever. Here's a repro:

http://embed.plnkr.co/numlaAuLOxh3a03Z7O85/preview

Just hover the button to make the tooltip appear, and then click it. The button is disabled, and the tooltip stays there. How can I avoid this behavior and have my tips correctly hidden?

**Comment by rvanbaalen** [comment]
This is fixed in the latest UI Bootstrap 0.13.0

http://plnkr.co/edit/Na1vA4PnRJwU4qMkImnM?p=preview
