### ISSUE TITLE
$modal does not provide proper scope to templates.

### ISSUE THREAD

**Issue by monokrome** [angular-ui/bootstrap#2110]
When using `templateUrl`, the resulting template will not have the same scope as the instance controller. Instead, it is in the scope as passed to the `scope` option on `$modal.open`.

This is an issue, because it means that there is effectively no method by which to get the modal's scope without resolving the modal.

**Comment by spock123** [comment]
Hi guys,
- as I see it, when using controllerAs, there is no $scope injected into the controller.
Any of you know how to inject a scope to a modal service from a controller that doesn't have $scope injected in the first place?

It feels a bit akward having to inject the $scope into a controller JUST to be able to put a scope on the dialog... I'm not feeling it :)

**Comment by MistyShrivastava** [comment]
@joshribakoff thanks a lot... your simple solution solved my issue. 
It literally saved hours of wild goose chase..

**Comment by shailendrarajput** [comment]
2
