### ISSUE TITLE
Datepicker position issue in Chrome/Safari

### ISSUE THREAD

**Issue by cincas** [angular-ui/bootstrap#2113]
Hi guys,

Recently in our project, we had this issue about datepicker popup going out of screen after it opened, especially in mobile screen.

Tested it in FF, Chrome and Safari, FF works fine, just Chrome and Safari are naughty

I'm a slacker, so instead of creating a pull request, I just made a work around to *fix* this. 
Here is the gist link
https://gist.github.com/cincas/11339827

And here is the coffeescript 
```CoffeeScript
@app.directive "datepickerPopupWrap", () ->
  return {
    restrict: "EA"
    link: (scope,ele, attrs) ->
      scope.$watch "position.left", (newValue) ->
        return unless scope.isOpen
        bodyWidth = angular.element('body').width()
        popupWidth = angular.element(ele).outerWidth(true)
        offset = bodyWidth - (popupWidth + scope.position.left)
        if offset < 0
          scope.position.left += offset
  }
```

**Comment by rvanbaalen** [comment]
Please provide a plunkr and confirm this is still an issue with Angular 1.3 and UI Bootstrap 0.13.

**Comment by wesleycho** [comment]
This issue may potentially be stale - please open a new issue with reproduction if this is still a problem.
