### ISSUE TITLE
typeahead, possibility to define own "popup" template/directive

### ISSUE THREAD

**Issue by allan-simon** [angular-ui/bootstrap#2120]
I don't know if it's in the scope of "typeahead" but it seems to me that currently it's not possible to define where we want the results to be displayed. 

I understand it's possible to define the template for one result, but I don't think it cover my use case. My use case would be I got a `<div>` somewhere else in my code, and the results are displayed in there. something like that

```
    <input
        type="text" ng-model="customSelected" 
        placeholder="Custom template" typeahead="state for state in states"
        typeahead-template-url="customTemplate.html"
        typeahead-result-in="#plop"
        class="form-control"
    >
    <div id="plop"></div>

```

with some kind of `typeahead-result-in="#plop"` that would permit to precise where we want the data to be displayed.

As said, if it's not the "goal" of typeahead, feel free to close this ticket. It's just that typeahead was otherwise providing all the stuff i needed , i.e bounce/throttle the results,  different option for the prediction,  custom template for one result etc.

**Comment by ritterpa** [comment]
I am looking at the same use case as @cladera; I have a couple of my own directives that use a typeahead and limit the results returned from the backend, and I'd like to add a "More Results" button to the popup element to get the next 10 results from the backend.
