### ISSUE TITLE
Tooltip does not close on IPhone

### ISSUE THREAD

**Issue by michaelhunziker** [angular-ui/bootstrap#2123]
Dear all!

We are using angular-ui bootstrap in our project. Our application also needs to be responsive.

I just tested angular ui bootstrap tooltips on an IPhone (IPhone 5, IOs 7) and it does not seem to work (just open the following URL on an IPhone: http://angular-ui.github.io/bootstrap/). The tooltip opens correctly on click but I am not able to close it anymore. It all works on Android (e.g. Nexus 5 phone).

Any idea how I could fix this? Is this a known issue?

Cheers
Michael

**Comment by scrivy** [comment]
@m0x72 worked for me! thanks!

**Comment by tdogg137** [comment]
@m0x72 I've been battling with this for days and glad I found this to be the closest to a working solution.  However, It's still doesn't work for my case.  The only difference between mine and the jsfiddle you had was that mine I have this as a config.  Any helps is really appreciated.
```
.config(['$tooltipProvider', function($tooltipProvider) {
    $tooltipProvider.options({
        placement: 'bottom',
        animation: true,
        popupDelay: 0,
        appendToBody: true
    });
}])
```

**Comment by wesleycho** [comment]
I tested this on the iOS simulator, and the tooltips appear to work. However, note that hovering over will be dicey on iOS, so once needs to use a trigger like `click` or `focus`.

Closing as fixed.

**Comment by stereotipo** [comment]
solution http://jsfiddle.net/stereotipo/suhq88b0/17/

test on iOS (ipad and iphone), android and windows

**Comment by mattblang** [comment]
@wesleycho Interestingly, it works on the simulator in Safari but not in a `UIWebView` within an app (e.g. if using Cordova).

**Comment by icfantv** [comment]
@mattblang, we have decided that as a project, tooltips and popovers, in general, are not going to be supported as from a UX perspective it makes almost zero sense.  I can see a use case for `click` enabled popovers for, say, editing an item, but again, from a UX perspective, this behavior/usage just comes across as really bad.

**Comment by johannesjo** [comment]
@icfantv i think there is a legitimate use case for contextual information if you you open them via tap and the tapability is indicated in a good way.

**Comment by sauldeleon** [comment]
We have a similar issue, if I have understand all comments correctly. We tap in iPhone or Android app on a tooltip, it appears, but then the only way to make it dissapear is taping on another tooltip.

If I have understand correctly @icfantv comment, this is not going to be "fixed"?

Thanks in advance for all support!
