### ISSUE TITLE
dropdown doesn't hide after clicking on element

### ISSUE THREAD

**Issue by henrytao-me** [angular-ui/bootstrap#2144]
I have this issue after upgrading to version @0.11.0. I never had this issue on version @0.10.0

Here is my code on @0.10.0

```
<div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle">
        Button dropdown
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><a href="#">Action</a>
        </li>
        <li><a href="#">Another action</a>
        </li>
        <li><a href="#">Something else here</a>
        </li>
        <li class="divider"></li>
        <li><a href="#">Separated link</a>
        </li>
    </ul>
</div>
```

On @0.11.0, I need to define `dropdown` directive and it doesn't hide dropdown menu after I click on `li`. I need to use `is-open` directive to overcome this issue. It's complicated. 

```
<div class="btn-group" dropdown="" is-open="isOpen">
    <button type="button" class="btn btn-primary dropdown-toggle">
        Button dropdown
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li ng-click="isOpen=false"><a href="#">Action</a>
        </li>
        <li ng-click="isOpen=false"><a href="#">Another action</a>
        </li>
        <li ng-click="isOpen=false"><a href="#">Something else here</a>
        </li>
        <li ng-click="isOpen=false" class="divider"></li>
        <li ng-click="isOpen=false"><a href="#">Separated link</a>
        </li>
    </ul>
</div>
```

Please give me some advices. Thanks!

**Comment by anil1712** [comment]
great @fiznool , excellent solution for angularjs

**Comment by krupavarma** [comment]
I have issue in angular 5 when i select <li> item, drop-down couldn't hide.Please solve this issue 


<li class="list-item animated dropdown dropbtn" style="z-index: 10005;" >
                    <a routerLink="/courses" routerLinkActive="active-link" >Courses</a>
                    <div class="dropdown-content hidden-xs hidden-sm" style="padding: 10px;margin-top:0px;" [ngClass]="{'fadesh':hoverEffect}">                        
                        <h3 class="nav_title">
                           <i><img src="../../assets/images/Courses.svg" style="margin:0 5px 0 0;"></i>    
                            Courses</h3> 
                        <div class="col-md-6" *ngFor="let item of list">
                            <ul class="nav_sub">
                                <li>
                                    <a routerLink = "course/{{item.route}}" (click)="navigateToCourse(item.route)" class="captilize-text">{{item.name}}</a>
                                </li>
                            </ul>
                        </div>
                    </div> 
                  
                </li>
