### ISSUE TITLE
datepicker-popup stopped working in UI Bootstrap 0.11.0

### ISSUE THREAD

**Issue by ngtrimble** [angular-ui/bootstrap#2149]
I am having an issue with UI Bootstrap 0.11.0. My datepicker-popup was working fine in 0.10.0. It is a simple <input ng-model="formData.dueDate" type="text" id="dueDate" name="dueDate" class="form-control" datepicker-popup="MM-dd-yyyy" datepicker-append-to-body="true"> that when the user clicks in it the datepicker appears.

In UI Bootstrap 0.11.0 the datepicker just does not popup any more. The problem can be reproduced at http://plnkr.co/edit/3fxVbuTxlTetNvQW4JeZ?p=preview. Just comment the 0.10.0 URL and uncomment the 0.11.0 URL.

Please let me know if I can provide anymore details. Thanks.

**Comment by samsam** [comment]
Could the popup functionality be made as a configurable option similar to showWeeks in a future release?

**Comment by Gajananghuge** [comment]
datepicket-popup functionality not working 
here is my code popup not opening when click on button and not getting any error
<input ng-model="employeeData.employment_attributes.joining_date" uib-datepicker-popup type="text" class="form-control" id="hire_date"  is-open="status.opened" close-text="Close">
           <span class="input-group-btn">
              <button type="button" class="btn btn-primary" ng-click="open($event)"><i class="fa fa-calendar fa-lg"></i></button>
           </span>
