### ISSUE TITLE
Ability to specify backdrop and window template as strings

### ISSUE THREAD

**Issue by follesoe** [angular-ui/bootstrap#2152]
The modal module has options to specify:
- templateUrl (path to template for modal's content)
- template (inline template representing the modal's content)
- windowTemplateUrl (path to a template overriding modal's window template)

The options I feel are missing:
- windowTemplate (inline template overriding modal's window template)
- backdropTemplateUrl (path to a template overriding a modal's backdrop)
- backdropTemplate (inline template overriding a modal's backdrop)

Adding these three options would make the the design more "complete" (i.e. same set of options for all three templates used by the module). 

Also for the particular project I'm working on all templates are inlined during our build process.

I'm happy to implement this feature and send a PR - but adding an issue to have something to register my work against, and to open discussion if this would be useful.

**Comment by Couto** [comment]
Nowadays using a dependency loader like Webpack/Browserify/Require.js is quite common.

These loaders allow developers to import HTML files as strings which can then be fed directly to directives.

According the modal's documentation this option is still impossible in version 2.0.

**Comment by DoctorHowser** [comment]
@Couto @follesoe @pkozlowski-opensource and anyone else who might be running into this--

Just ran into this converting an app using gulp to use webpack. Our workaround for windowTemplate not existing:

import modal from  './modal.partial.html'
import templateWindow from '../select-provider-pref/window.html'
///////

    sessionTimeoutModal.$inject = ['$modal', '$templateCache'];

    /* @ngInject */
    function sessionTimeoutModal($modal, $templateCache) {
        this.open = open;

        ////////////////

        $templateCache.put('templateWindow.html', templateWindow);


        function open() {
            return $modal.open({
                template: modal,
                controller: SelectProviderPreferenceModalController,
                controllerAs: 'vm',
                backdrop: false,
                windowTemplateUrl: 'templateWindow.html'
            });

/////
