### ISSUE TITLE
Dropdown directives conflict with bootstrap's JS

### ISSUE THREAD

**Issue by lijuenc** [angular-ui/bootstrap#2156]
The dropdown directives have a restrict value of `CA`. This means that if you also have bootstrap.js referenced as a script file, the directives conflict with Bootstrap's JavaScript hooks into the `dropdown` and `dropdown-toggle` classes.

See this plunker. Notice that it takes two clicks to open a non-directive dropdown.

http://plnkr.co/edit/AYHYLesd4025dUdfLT7i?p=preview

**Comment by michaeldjeffrey** [comment]
Is there anywhere where the breaking changes are documented between version? This one just tripped me up, and wondering if there are any more I don't know about.

**Comment by karianna** [comment]
@michaeldjeffrey Not that I'm aware of - you can look at all of the issues with a angular1.3 label to get a rough idea.

**Comment by iKronyck** [comment]
thanks @chrisirhc it worked for me in laravel and react js
