### ISSUE TITLE
Accordion: allow automatically open first or selected element

### ISSUE THREAD

**Issue by rewritten** [angular-ui/bootstrap#2171]
When the accordion is built, one of the groups may be initialized as open. Setting
```html
<accordion-group is-open="true">
```
doesn't work, because it can't be closed.

Maybe, as a configuration setting (similarly to `closeOthers`) can help:

```javascript
  // This is called from the accordion-group directive to add itself to the accordion
  this.addGroup = function(groupScope) {
    var that = this;
    var openFirst;
    if (!this.groups.length) {
      openFirst = angular.isDefined($attrs.openFirst) ? $scope.$eval($attrs.openFirst) : accordionConfig.openFirst;
      if ( openFirst ) {
        groupScope.isOpen = true;
      }
    }
    this.groups.push(groupScope);

    groupScope.$on('$destroy', function (event) {
      that.removeGroup(groupScope);
    });
  };
```

or an attribute on a specific group, which will set the `isOpen` value
```html
<accordion-group is-open-at-start="true">
```

**Comment by ameckoni** [comment]
Thanks @CarlosCuevas  I had the same question (first panel to be open by default) and the solution suggested by you worked.

**Comment by pjukalkar** [comment]
thejohnfreeman solution works for my problem!

**Comment by aleksandrj1** [comment]
this finally worked for me :
<accordion-group ng-init="status.open = true" is-open="status.open">

**Comment by aleksandrj1** [comment]
Ahh - But the real problem for me was the ng-controller was spec'd on the accordion. It needs to be on a div that contains the accordion directive. Then: &lt;accordion-group is-open="status.isFirstOpen"&gt; works as expected.

**Comment by kevcoxe** [comment]
if your using ng-repeat this works for me
<accordion-group ng-init="isOpen = $index == 0 ? true : false" is-open="isOpen" ng-repeat="item in list">

**Comment by Backer88** [comment]
What worked for on the first try is to simply add is-open="$first" on the accordion-group element.

**Comment by evfreethy** [comment]
the @thejohnfreeman solution works so long as you properly replace the variables

**Comment by velikodimitrov** [comment]
Thank you

**Comment by virendra656** [comment]
is-open="$first" will do the job

**Comment by chetanbane** [comment]
<accordion-group *ngFor="let product of data.products; let i = index;"  [isOpened]='i == 0'>

For new one I have work with this. 
This code work fine for me in new accordion
