### ISSUE TITLE
modal.open with templateUrl - preventing multiple executions

### ISSUE THREAD

**Issue by lepipele** [angular-ui/bootstrap#2172]
Say that you have following code tied to a button click:

    $modal.open({
        templateUrl: 'pathtofile.html',
        controller: 'MyCtrl as modalCtrl',
        closable: true,
        backdrop: 'static'
    });

If users clicks button multiple times before that pathtofile.html is returned from the server, he will be able to spawn multiple modal windows.

I am just wondering if somebody has easy fix for this in a sense - spawn black overlay immediately, and then spawn modal when HTML file is returned from the server. Obviously this can also be resolved by embedding all html in template variable (vs templateUrl), but I would prefer not to embed html within js files.

**Comment by wesleycho** [comment]
I think the appropriate change with the modal is to perhaps do the `$templateRequest` for the modal `templateUrl` before opening the modal. The multiple modal window problem should be solved on the developer side by creating a lock.

**Comment by wesleycho** [comment]
Closing due to suggestion being a sufficient mechanism
