### ISSUE TITLE
Datepicker min-date does not work.

### ISSUE THREAD

**Issue by piupiupiu** [angular-ui/bootstrap#2189]
Hello, I'm trying to restrict the selection of previous dates but it does not seem to work.
Plunk: http://plnkr.co/edit/h2cJfEl3svnLDuBlylHi

Is this a bug or am I doing smth. wrong?

**Comment by BobbieBarker** [comment]
Closing due to a lack of activity, please test against latest version and reopen if this is still an issue.

**Comment by shamoons** [comment]
Still an issue it seems

**Comment by shamoons** [comment]
See http://stackoverflow.com/questions/30200122/angular-ui-datepicker-max-date-doesnt-work-properly for the code

**Comment by swapnilgaykhe** [comment]
Use attribute min-date on datepicker element.
eg. <input id="datePickerEle" type="text" datepicker-popup="dd/MM/yyyy" ng-model="launchDateForm.date" is-open="opened" min-date="minDate"/>

**Comment by humam-nameer-10p** [comment]
min-date and max-date disables selection from angular bootstrap dropdown datepicker but not when user has access to write date manually in the input field check [this](https://github.com/angular-ui/bootstrap/issues/1688) question for reference, I have also proposed an alternative over there

**Comment by ibbatta** [comment]
@swapnilgaykhe after the last update `min-date` and `max-date` are deprecated.

+ 1 for this issue

**Comment by mpbunch** [comment]
yo. fix this. it is 2016.

**Comment by icfantv** [comment]
@mpbrunch, please read our code of conduct.  Attitudes like that are counterproductive.  You would do well to remember that we are all unpaid volunteers on this project donating time when we can.

Nothing is stopping you or anyone else in the community from putting together a quality PR.

**Comment by mpbunch** [comment]
@icfantv. valid.

**Comment by phildangl** [comment]
+1 
imput text field sitll valid. Have to check the button div, there it works.

**Comment by HectorAnadon** [comment]
@phildangl I can't get it working. Can you post a snippet?

**Comment by joaocmfcm** [comment]
How can we update on the fly a minDate?

**Comment by bogdandrumen** [comment]
Use **datepicker-options="{minDate: yourScopeMinDate}"**

**Comment by robinswaylu** [comment]
Thank you @bogdandrumen. Finally get it to work.

**Comment by GET1NE** [comment]
So I tried the following but I get an error instead. 

datepicker-options="{showWeeks: false, minDate: myScopeDate}"

Error:
angular.js:12314Error: [$parse:syntax] Syntax Error: Token 'Jun' is an unexpected token at column 5 of the expression [Thu Jun 16 2016 18:36:41 GMT-0500 (Central Daylight Time)] starting at [Jun 16 2016 18:36:41 GMT-0500 (Central Daylight Time)].

**Comment by bogdandrumen** [comment]
@GET1NE Your myScopeDate must be a Date object in order to make it work. Try using new Date(myScopeDate) in your controller.

**Comment by icfantv** [comment]
@GET1NE, please be respectful of the community's time by reading the project's API documentation prior to posting your errors.  Additionally, per our issue template and project readme the issues forum is not for support-related requests.  Our demo page shows how to properly use the components.

**Comment by GET1NE** [comment]
@bogdandrumen Thanks for the help. I set this up on my controller side and it worked. I just thought this could be done from the markup side from the examples I had seen.

**Comment by GET1NE** [comment]
@icfantv Thanks I have read the API documentation but was still unclear of using it properly. I'm new to Angular and new to Git. I appreciate the info and sorry for wasting anyones time.

**Comment by ycanales** [comment]
Thanks @swapnilgaykhe, using the `min-date` html attribute was the only thing that worked for me in `angular-bootstrap 0.14.3`

**Comment by Jeelani786** [comment]
Hi there,
I am a new bee to Angularjs and Angularjs-Bootstrap, I am using AngularJS v1.5.8 and angularjs-tpls-2.0.1.min.js with a custom app as I am trying to take control of two date pickers, as if the first date is selected, then second date pickers min-date should be automatically set to first date picker. and if the second date picker's date is selected then the first date pickers max-date should be set to second date picker's selected date.
but its not working.
Help Me please.
[MyApp.txt](https://github.com/angular-ui/bootstrap/files/417955/MyApp.txt)

**Comment by yogi07** [comment]
just add $scope.today = new Date()
 and in html code add 
min-date = "today"
