### ISSUE TITLE
Ability to veto modal close event

### ISSUE THREAD

**Issue by nlwillia** [angular-ui/bootstrap#2191]
If a modal closes (whether due to a close/dismiss call, the Escape key or a click on the background), any work the user was doing in the modal will be lost.  An application should have the opportunity to observe the close event and veto it forcing the modal to remain open.  With the native bootstrap modal, you can preventDefault the "hide.bs.modal" event, but I don't see anything similar in the angular-ui component.  I can turn off the built-in close triggers with options and add are-you-sure checks to any controls inside the modal, but it would be better to have direct support; this is a typical capability of modal widgets.

**Comment by wesleycho** [comment]
Addressed by a5a82d9be7dc0bd1cfd510bacf9aa411c6efe1bc
