### ISSUE TITLE
anchor links are busted for directives on gh-pages

### ISSUE THREAD

**Issue by meandavejustice** [angular-ui/bootstrap#2192]
1. Go to http://angular-ui.github.io/bootstrap/
2. click directives > popover
3. you will be directed to "http://angular-ui.github.io/bootstrap/#/popover"
4. refresh.
5. '/#" is stripped from URL leaving us with "http://angular-ui.github.io/bootstrap/popover" and a 404 :(

**Comment by wesleycho** [comment]
This is now resolved, as can be seen in the demo page.
