### ISSUE TITLE
Minutes should be changed if ngModel is null

### ISSUE THREAD

**Issue by RopoMen** [angular-ui/bootstrap#2193]
Hi,

I have event calendar where I have start and end dates and both have their own datepickers and timepickers (using same date object), now my end time is null as long as user picks date first (because event end time must be greater than starttime -> startime cannot be greater than endtime (validators)). When my end time is null timepicker is showing current hours and minutes. (created new date object?)

I think timepicker is creating new date object, BUT if "minute-step" is EVEN timepicker should set minutes to the "00" or next even minutes count. My timepicker has 5min steps, but if user sees minutes "32" the next minutes is "37" I would like it to be either "05" or "35". If minute-step is 2min. then "32" would be ok.

Or if given ngModel date is null, timepicker could show "00:00"

I hope you can understand what I'm getting :)

**Comment by rvanbaalen** [comment]
Please provide a plunkr and confirm this is still an issue with Angular 1.3 and UI Bootstrap 0.13.

**Comment by wesleycho** [comment]
Closing due to lack of response - it should be noted that support for a null model was added in 8ffdaeb099b3f3858369177056977940107e3d9d
