### ISSUE TITLE
Dropdown button and ngTouch

### ISSUE THREAD

**Issue by stha** [angular-ui/bootstrap#2204]
Hello,

i'm using the dropdown directive to realize a language selection. I'm also using the ngTouch module to get enhanced touch device support. This works fine on the inner `<li><a ...></a>`-Elements but not on the button. The `ng-click-active` css class is not added like documented in the angularjs documentation. See https://docs.angularjs.org/api/ngTouch/directive/ngClick.

What I'm doing wrong?

```html
<div class="push-right cp-btn-dropdown cp-language btn-group" dropdown is-open="language.isopen" ng-controller="Language">
            <button type="button" class="btn btn-default dropdown-toggle">
               <span class="flag_{{currentLang}}"> </span> <span class="caret middle"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="" ng-click="changeLanguage('de_DE')"><span class="flag_de_DE"></span></a></li>
                <li><a href="" ng-click="changeLanguage('en_US')"><span class="flag_en_US"></span></a></li>
            </ul>
</div>
```

Thx for your time!

**Comment by wesleycho** [comment]
Closing, as this is a user error.

**Comment by kotmatpockuh** [comment]
@wesleycho same issue...
