### ISSUE TITLE
datepicker should be easier to be aligned to the right

### ISSUE THREAD

**Issue by jrencz** [angular-ui/bootstrap#2208]
now it calculates `left` and sets it as inline property so I have to use `left: auto !important; right: 0` to make right border of the input and datepicker aligned. And as everyone should I'm trying to avoid `!important` as much as possible.
`left: 0` may be set on class so it's easier to override it.
What's more: simple classes to stick the picker to the left or to the right may be provided.

**Comment by lloiser** [comment]
+

**Comment by chrisirhc** [comment]
Duplicate of #1012
