### ISSUE TITLE
Modal doesn't work with ng-include

### ISSUE THREAD

**Issue by moroshko** [angular-ui/bootstrap#221]
Live example: http://plnkr.co/edit/wWS3UFB3IZ0cAI4u2x04?p=preview

When "Open Modal 1" is clicked, the following error is thrown:

> Error: Dialog.open expected template or templateUrl, neither found. Use options or open method to specify them.

However, Modal 2, which doesn't use `ng-include`, works fine.

Also, if `ui-bootstrap-tpls-0.1.0.js` is included instead of `ui-bootstrap-tpls-0.2.0.js`, all works fine.

**Comment by alanquigley** [comment]
Why is this closed? ng-include does not work inside modals.

**Comment by pkozlowski-opensource** [comment]
@alanquigley it was closed as a duplicate of another issue. If you believe that that it is not a duplicate please open a new issue with a live reproduce scenario: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug
