### ISSUE TITLE
Datepicker popup not respecting show-weeks=false

### ISSUE THREAD

**Issue by ronnieoverby** [angular-ui/bootstrap#2216]
Same as #1132.

I'm on 0.11.0.

**Comment by iyel** [comment]
+1 docs need an update

**Comment by gitnik** [comment]
:+1: this is super confusing

**Comment by yabasha** [comment]
+1 to super confusing, the documentation needs to be more clear

**Comment by prettycode** [comment]
+1

**Comment by holimL** [comment]
Was wondering the exactly same thing. +1

**Comment by wesleycho** [comment]
It should be noted that any attribute without an eye icon is not supported for watching. The documentation makes this clearer in `master` with an explanation in the first few paragraphs.

As a consequence, closing this as resolved.

**Comment by MuhammadTayyeb** [comment]
hi i have issue occur in angular datepicker after edit dateTime. that can't show the datetime. in Html dateTime aleardy exit but i can't show on UI
