### ISSUE TITLE
Make Auto-Close Dropdowns optional

### ISSUE THREAD

**Issue by ulilicht** [angular-ui/bootstrap#2218]
Hi, 

a DropDown always closes when clicked somewhere on the document. It would be great if this would be optional - for example if i put a complex dialog in a dropdown, i want to close it manually. For example: a calendar widget. 

Here you can find a Stackoverflow issue which adresses exactly that: 
http://stackoverflow.com/questions/23698316/how-to-prevent-an-angular-bootstrap-dropdown-from-closing-unbind-event-which-wa/23723686?noredirect=1#23723686

The corresponding lines in code can be found here: 
https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L12

It would be great to apply line12 only if the user whished for example by an option.

**Comment by wesleycho** [comment]
Landed from #3045.  This will be in the next release.
