### ISSUE TITLE
Add support of ng-disabled to timepicker

### ISSUE THREAD

**Issue by idrabenia** [angular-ui/bootstrap#2219]
Hi!

Timepicker is great! 
But will be very cool if timepicker will have support of ng-disabled directive.

Thanks!

**Comment by carlospliego** [comment]
So, we need to set three things to correctly disable the input?

**Comment by Siddeshgad** [comment]
Yes. If you set readonly-input="true", hour-step and minute-step to zero it will work.

**Comment by xiphiaz** [comment]
While this is a feature that definitely should be implemented, there is a workaround - you can wrap the timepicker in a <fieldset ng-disabled="your.param"></fieldset> to disable all fields in the fieldset.

**Comment by theaccordance** [comment]
Having to modify multiple attributes to disable the directive is not ideal, it would be much more preferable to have a single attribute that disables all aspects of this directive from user input.

**Comment by amamut** [comment]
Meridian is still editable after disabling everything.

**Comment by deepu105** [comment]
`<fieldset ng-disabled="your.param"></fieldset>` this is the best workaround disables everything thanks @xiphiaz  but yes ng-disabled directly would be better

**Comment by deepu105** [comment]
PR seems to  have closed with a rollback

**Comment by JoeMatulka** [comment]
Careful of the fieldset, it doesn't work in IE...

**Comment by AliAdravi** [comment]
In our directive we can watch the ngDisabled value and disable the datepicker
scope.$watch(attr.ngDisabled, function (newVal) {
  if(newVal === true)
    $(elm).datepicker("disable");
  else
    $(elm).datepicker("enable");
});
See the complete detail here:
http://www.advancesharp.com/blog/1224/angularjs-jquery-ui-datepicker-for-any-condition
