### ISSUE TITLE
"create your own build" not updated to version 0.11.0

### ISSUE THREAD

**Issue by graphmeter** [angular-ui/bootstrap#2222]
When using the "create your own build" on the website version 0.10.0 files are generated and not 0.11.0, which I guess should be the case? 

Also, when including the ``ui.bootstrap.dropdown`` module in the build and add it as a dependency I get an ``Module 'ui.bootstrap.dropdown' is not available!`` error, it works fine with the other modules.

**Comment by wesleycho** [comment]
This appears to be fixed - the current build on the homepage being generated is 0.13.1
