### ISSUE TITLE
datepickerPopup stop propagation of ESC and by this prevent close of dialog

### ISSUE THREAD

**Issue by luboid** [angular-ui/bootstrap#2228]
May be this need to be occur only when calendar is opened

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.

**Comment by luboid** [comment]
Hi

http://plnkr.co/edit/RNXoQj?p=preview

I think it working, I expect when dialog is open and datepicker-popup is focused, then when I press ESC window to be closed.

**Comment by rvanbaalen** [comment]
Based on your plunkr, I consider this issue fixed.
