### ISSUE TITLE
Carousel not able to set active slide after assining new slides

### ISSUE THREAD

**Issue by kimvanhees** [angular-ui/bootstrap#2235]
I have a simple Carousel example. In this example on Plnkr I change the slides in my application. When I set the active slide after I change slides it goes to that slide and then slides out into oblivion or it goes to the first slide instead.

http://plnkr.co/edit/PJg9U4HZ1k5aSTSvbl3k?p=preview

    angular.module('plunker', ['ui.bootstrap', 'ngTouch']);
    function CarouselDemoCtrl($scope) {
        $scope.genderPerson = "men";
        $scope.myInterval = -1;
        $scope.slides = [];

        $scope.$watch("genderPerson", function( newValue, oldValue ) {
            $scope.MakeSlides();
        });

        $scope.MakeSlides = function() {
            var newSlides = [];
            for ( var i = 0; i < 10; i++ ) {
                newSlides[i] = { image: 'http://api.randomuser.me/portraits/' + $scope.genderPerson + '/' + i + '.jpg' };
             }
             $scope.slides = newSlides;
             if ( $scope.slides[6] ) {
                 $scope.slides[6].active=true;
             }
        }
    }

**Comment by stuartm** [comment]
I'm seeing the same issue with the latest release 0.13.2, if I update the change list used by the carousel then no slides are 'active' and the carousel disappears.

**Comment by shabetya** [comment]
0.13.4 version also has that bug again! if redefine slides, active class is not set

**Comment by dotcom9** [comment]
Is there a workaround for this bug in 0.13.4? Unfortunately, I can't upgrade due to project constraints.

**Comment by icfantv** [comment]
@dotcom9 you could try back porting the fix depending on how invasive it is.  I understand all too well the pain of being forced to remain on an old version.
