### ISSUE TITLE
Update tabset tab orientation dynamically

### ISSUE THREAD

**Issue by EmileSpecs** [angular-ui/bootstrap#2251]
I've bound the tabset vertical attribute to a model in the hopes that the tab orientation would dynamically change based on the model value, that's not happening.

I'm assuming the template would need to recompile when the attribute value changes, could this feature be added/can I add it myself?

**Comment by freewil** [comment]
Running into this issue now, I'm running an old version... 0.12... but looks like this feature still hasn't been added to the latest. 

@wesleycho 
I'd request that this issue gets re-opened, as it should be a fairly common use case to want to dynamically toggle `vertical` for the tabset to make tabs responsive for mobile devices.

**Comment by freewil** [comment]
Slight change to @EmileSpecs code in the `tabset` directive to allow the vertical tabs attribute to be dynamic:

```js
scope.$watch(
  function watchFn () {
    return scope.$parent.$eval(attrs.vertical);
  },
  function watchListener (newValue, oldValue) {
    scope.vertical = newValue;
  }
);
```

Then in your template:

```html
<tabset vertical="shouldBeVertical">
```
