### ISSUE TITLE
Cannot manage to make the modal work

### ISSUE THREAD

**Issue by Maxwell2022** [angular-ui/bootstrap#2252]
I'm trying to setup a route (using ui-router) for the user login. When the client (angular) is detecting that the user session is not valid anymore, I want to display the login modal window to ask the user to authenticate again.

So I tried to setup the route like this:

``` js
define([
    'angular',
    'ui.router',
    'ui.bootstrap',
    '../../config',
    'angular-facebook',
    './services/UserService'
], function (ng) {
    'use strict';

    return ng.module('app.user', [
        'app.constants',
        'ui.router',
        'ui.bootstrap',
        'facebook'
    ]).config(['$stateProvider', '$locationProvider', 'FacebookProvider', 'CONFIG', function ($stateProvider, $locationProvider, FacebookProvider, CONFIG) {

        FacebookProvider.init(CONFIG.facebook_app_id);
        $stateProvider
            .state('main', {
                abstract: true,
                name: '',
                templateUrl: '/js/modules/user/views/index.html',
                controller: 'UserController'
            })
            .state("login", {
                url: "/login",
                onEnter: function($stateParams, $state, $modal) {
                    $modal.open({
                        templateUrl: "/js/modules/user/views/login.html",
                        controller: 'LoginController',
                        backdrop: 'static'
                    });
                }
            })
            ;
    }]);
});
```

And my template looks like this:

``` html
<div class="modal-header">
    <h3 class="modal-title">I'm a modal!</h3>
</div>
<div class="modal-body">
    content...
</div>
<div class="modal-footer">
    <button class="btn btn-primary" ng-click="ok()">OK</button>
    <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
</div>
```

But I get the following errors:

> Error: [$compile:tplrt] Template for directive 'modalBackdrop' must have exactly one root element. template/modal/backdrop.html
> Error: [$compile:tplrt] Template for directive 'modalWindow' must have exactly one root element. template/modal/window.html

I tried to search for this error and some people say that it's because the `modal` template needs to be wrapped in a single `tag` so I did add a simple `<div>...</div>` to wrap the content of my modal but I still get the same error.

I tried to look at the documentation but I cannot find anything really.
Help is welcomed ;)

Maxime

**Comment by eablokker** [comment]
Installation docs should say which files to include
