### ISSUE TITLE
Regression? Datepicker popup does not show in a modal box for 0.11.0

### ISSUE THREAD

**Issue by dcoraboeuf** [angular-ui/bootstrap#2258]
Hi,

If I have the a datepicker popup element field in a popup, it does not show up in a modal box when using UI Bootstrap 0.11.0:

```
<input ng-model="myDate" name="myDate" type="text" class="form-control"
                                   datepicker-popup="EEE dd MMM yyyy"
                                    />
```

Going back to UI Bootstrap 0.10.0, the popup shows correctly.

**Comment by wesleycho** [comment]
Hijacking this issue - a PR with documentation updates about the `is-open` attribute is welcome.

**Comment by wesleycho** [comment]
This opens, as can be seen [here](http://plnkr.co/edit/vXRGY9DtYxFDlqFiFy4t?p=preview) by pressing down on the keyboard - as mentioned, one can access the `is-open` attribute, which is now documented.
