### ISSUE TITLE
dropdown not recognize with  ng-class in 0.11.0

### ISSUE THREAD

**Issue by jojosati** [angular-ui/bootstrap#2264]
plunker
http://plnkr.co/edit/tAjyhc5JdFmHwBaQDT1T?p=preview

in version 0.10.0  I can use ng-class to add 'dropdown'

but with new version 0.11.0, it's not work now.

regards.

**Comment by wesleycho** [comment]
This is likely due to the drop of class support for the dropdown directive.

Closing - let us know if there is something important about this prior behavior.
