### ISSUE TITLE
Datepicker mode is not working

### ISSUE THREAD

**Issue by slavafomin** [angular-ui/bootstrap#2266]
I'm trying to use `datepickerMode` configuration option, but it looks like it's not affecting the widget at all (both provided as an attribute or configuration option for popup).

**Here's the demo:**
http://plnkr.co/edit/33tbOLlb9a085rDK3vXr?p=preview

Please advise! Thanks!

**Comment by liminjun** [comment]
those settings are AngularJS expressions and not constants so you need to quote things if you provide constants. It is very important tips for new beginner using the angular-ui datepicker.
