### ISSUE TITLE
Popover append-to-body is positioned incorrectly in FireFox

### ISSUE THREAD

**Issue by bheithaus** [angular-ui/bootstrap#2268]
Due to an issue in $position factory, specifically the offset function, this line here:

[src/position/position.js:75](https://github.com/angular-ui/bootstrap/blob/master/src/position/position.js#L75)
```
top: boundingClientRect.top + ($window.pageYOffset || $document[0].body.scrollTop || $document[0].documentElement.scrollTop),
```

when I click a popover with append-to-body="true", the top property, which should be around 880px, is coming back as 2211px, and the popover is being placed way down below the rest of the page.

{top: "2211px", left: "813.8499755859375px"}

if I understand correctly, the problem here is that $window.pageYOffset is 0, which should be used, but is skipped over because of the ```||``` operator.

so I made a pull request, I hope it is helpful.

**Comment by BobbieBarker** [comment]
It looks like if #2275 get's merged in that this issue will be fixed. I"m going to close this one for now, no need to keep a duplicate open, we can reopen if if #2275 doesn't resolve this issue.
