### ISSUE TITLE
IE 11 DatePicker year

### ISSUE THREAD

**Issue by leogdion** [angular-ui/bootstrap#2279]
Using the shortDate format, when a user enters a year manually such as "1/1/00" in the  text field the year is rendered as "1900" in IE11 but "2000" in Chrome. I would prefer "2000" or perhaps something which would consider the min-date set.

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.

**Comment by wesleycho** [comment]
I believe this issue has now been resolved with the fallback to the new Date constructor having been removed. Please post with a reproduction if this is not the case anymore.

**Comment by slobdog** [comment]
thanks @wesleycho was using new Date() but changed it to Date.now() and it solved the IE problem
