### ISSUE TITLE
beforeShow in datepicker

### ISSUE THREAD

**Issue by ulrichSchreiner** [angular-ui/bootstrap#2282]
hi,

i need something like http://api.jqueryui.com/1.9/datepicker/#option-beforeShow to have specific css-classes for date's. i want to show the datepicker but need to visualize that some days are reserved or that there is an event on these days. a simple callback where i can return an additional css-class would be fine.

i tried a custom-template for "template/datepicker/day.html" but i don't kow how to call a function in my outer controller. 

any idea's how i can achieve this? 

thanks
</usc>

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
