### ISSUE TITLE
Localised format for datepicker

### ISSUE THREAD

**Issue by Ir1sh** [angular-ui/bootstrap#2287]
I have been browsing through the issues and google and sometimes it seems like what I am looking for is possible and taken care of automatically and sometimes it dosn't.  So I have a question.

Does or can the datepicker format the date displayed automatically depending on region ie in the states it would show mm/dd/yyyy but in the uk it would show dd/mm/yyyy?

**Comment by rvanbaalen** [comment]
Please ask implementation questions on StackOverflow. We'll be happy to answer your questions there. 
https://github.com/angular-ui/bootstrap#need-help
