### ISSUE TITLE
Tabs are deselecting on load

### ISSUE THREAD

**Issue by viniciuspires** [angular-ui/bootstrap#2288]
I don't know if this is a bug or just not the appropiate behavior I was waiting for, but looks like the tab component is triggering one `deselect` for each tab when the template is rendered.

I'm making a huge form separated in tabs, and I expected to use `deselect` to pre-save the form as a draft when the user switch tabs, before the actual submit and validation.

If it's not a bug, maybe the `deselect` event could be a little more semantic, as it gives an idea of manually selecting another tab, and it could be separated in two events, `deselect` to this action, and something like `init` to run the first configuration.

I know there are workarounds for this (and I had to use one), but tell me what you think of breaking this event in two, and if it's positive, I can fork the code and make the proper changes.

Thanks in advance.

**Comment by rvanbaalen** [comment]
Can you confirm this is still an issue with UI Bootstrap 0.13 and Angular 1.3?

**Comment by wesleycho** [comment]
I am not able to reproduce this [here](http://plnkr.co/edit/GHhAbFVf1BaLrgYSXyNX?p=preview).

Feel free to open a new issue with reproduction if it is an issue still.
