### ISSUE TITLE
Angular-ui bootstrap Tab directive accessibility issue.

### ISSUE THREAD

**Issue by justin-john** [angular-ui/bootstrap#2290]
Tab switching doesn't happen through keyboard.

**Comment by geroyche** [comment]
adding a blank href attribute to the links causes tabs to trigger a route reload btw.

at least when angularjs is used in html5 mode, where  <base href='/'></base> is set.
when hovering over the links i can already see that the base is the real link target, clicking a link will then, as expected, load the base route. if i remove the empty href, no re-routing occurs.

**Comment by icfantv** [comment]
@geroyche, this issue has been beaten to death in the forum under several different issues.  We had recently switched to `<div>` elements instead of `<a>` but that breaks Bootstrap's CSS (and custom theming) so we reverted it.  Your best bet here is to use a custom template if you desire different behavior.  See #4533, #5361.

**Comment by geroyche** [comment]
thanks. can't say i found much with regards to forum discussions, so i asked here. maybe my search terms were wrong ;)

**Comment by geethaar09** [comment]
Is this issue about using the tab key to tab through the tabs or using the arrow keys to move to the next/previous tabs? For one of our customer with keyboard only users, they find it hard to tab through each tab before they can get to the tab content, so they want tab key to take them to the tab content and arrow keys to take them to the next tab. I was looking for a solution for this issue and it seems like this is not supported in the tab directive and can be achieved only through JS - https://codepen.io/jeffsmith/pen/YqrzOa

Has anyone resolved this issue?
