### ISSUE TITLE
Losing template scope in component ( Accordion . toggleOpen() ) 

### ISSUE THREAD

**Issue by kosz** [angular-ui/bootstrap#2291]
I am having trouble accessing template methods from within my code. 

I have the need to customize accordion header, to include a set of buttons : 

https://gist.github.com/kosz/7fc8532bed9e68753ff2#file-accordion_buttons-jade

As you can see, in this file, i'm trying to ng-click="toggleOpen()" on a button that will handle expanding and colapsing. This would allow me to have other buttons and attach other events on the accordion header. I've had this working fine with my own code, but trying to standardize and use angular-ui bootstrap. 

I have implemented this template : 

https://gist.github.com/kosz/7fc8532bed9e68753ff2#file-index-jade-snippet

and it works fine, except for the fact that toggleOpen() is not available here . if i add toggleOpen() inside the template, it works just fine, but of course, it prevents me from calling any other methods on click from it's children. 

Am i missing something here ?

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.

**Comment by wesleycho** [comment]
One has access to the `is-open` attribute, which allows one to programmatically toggle opening and closing of the accordion, as can be seen [here](http://angular-ui.github.io/bootstrap/#/accordion).
