### ISSUE TITLE
Dropdown needs two clicks to open

### ISSUE THREAD

**Issue by joshvillbrandt** [angular-ui/bootstrap#2294]
When upgrading from 0.10 to 0.11, drop-down menus started requiring two clicks in order to open (at least for nav-bar drop-down menus.) Removing `data-toggle="dropdown"` from the primary toggle element fixes the problem, but this is no longer the bootstrap-suggested syntax.

I suggest making a clear note of this in the documentation or make the dropdown directive compatible with the standard bootstrap syntax (like it was in 0.10.)

**Comment by kazupooot** [comment]
@Snede 's answer works for me.

**Comment by sime** [comment]
Trying to upgrade from 0.10.0 to 0.11 or 0.12 whilst using Angular 1.3.

Haven't been able to get 0.12 to work at all.

Since 0.11.1 the parent element of `dropdown-toggle` expects a `dropdown` class/attribute. This is documented, but 0.10.0 worked without it.

**Comment by sime** [comment]
Ahh I didn't properly read the breaking changes in the CHANGELOG for dropdowns in 0.12.x. only `dropdown` and `dropdown-toggle` attributes are accepted.

**Comment by theoziran** [comment]
@sayyedi +1

**Comment by icfantv** [comment]
@theoziran, please do not only add `+1` to issues.  It does not add anything to the discussion and only clutters up the thread.  Thanks.

**Comment by FlandersBurger** [comment]
Although it solves the problem of not having to double-click, now the dropdown doesn't close when i select an element.

**Comment by utkapodsousom** [comment]
Confirmed! Adding 'data-disabled="true"' makes menu open on the first click, but in doesn't close

**Comment by vishwapratap007** [comment]
@chrisirhc  thanks it works for me.

**Comment by cristianrennella** [comment]
I solve it.

I had in application.js

//= require rails-ujs
//= require activestorage
//= require turbolinks
//= require jquery3
//= require autonumeric
//= require bootstrap
//= require popper
//= require bootstrap-sprockets
//= require_tree .

I remove require bootstrap leaving only bootstrap-sprockets
