### ISSUE TITLE
Allow datepicker-popup to have number value for ng-model

### ISSUE THREAD

**Issue by craigswatman** [angular-ui/bootstrap#2305]
When passing an epoch time as a number type to the datepicker-popup, the input box displays the correct date, however when launching the popup it is set to todays date.

See: http://plnkr.co/edit/o8dCRgVvckrZvVYZZk2g?p=preview

Would it be possible to have it accept number type?

For example: 
https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L499

Could be changed to:

``` } else if (angular.isString(viewValue) || angular.isNumber(viewValue)) { ```

Thanks.

**Comment by rvanbaalen** [comment]
Datepicker doesnt support epoch time. If you want to implement this, feel free to send us a PR.
