### ISSUE TITLE
datePicker popup not working in modal

### ISSUE THREAD

**Issue by akarelas** [angular-ui/bootstrap#2307]
I took the exact HTML & JS code from the examples and pasted it in an ordinary view of my app, and it worked.

However when I pasted it inside a ui-bootstrap modal, then the datePicker would open when clicked, but could not re-open after it was closed once.

**Comment by SandeepKulkarniag** [comment]
Hi, I'm suffering from the same issue, but with bootstrap datetimepicker. Could either of you all let me know as to what is that I'm missing. I asked this question on SO. Please have a look.
[http://stackoverflow.com/questions/38100111/bootstrap-datetimepicker-showing-inconsistency-while-used-in-bootstrap-modal](url)
