### ISSUE TITLE
typeahead-editable="false" passes ng-required validation when value is not choosen

### ISSUE THREAD

**Issue by prettynatty** [angular-ui/bootstrap#2308]
Here is a plunk: http://plnkr.co/edit/iQM45S?p=preview
Type a value which is not provided in $scope.states and press Enter key.
The form's ng-submit action will be performed but should not because `selected` ngModel is empty.

**Comment by bkirtika** [comment]
+++

**Comment by arjunasuresh3** [comment]
+++

**Comment by lianyi** [comment]
+++

**Comment by ghiaia** [comment]
+++

**Comment by emaish** [comment]
+++

**Comment by sheymann** [comment]
+++

**Comment by chrisirhc** [comment]
You should do a check on the validity of the form before calling submit, like `<form name="myForm" ng-submit="myForm.$valid && submit()">`.

See this Plunker: http://plnkr.co/edit/CK9rUM?p=preview

Just using `require` won't allow Angular to check the form's validity. To the browser, as long as there's a value in the input field, it's valid.

**Comment by karianna** [comment]
@chrisirhc Should we close this as a support issue in that case?

**Comment by chrisirhc** [comment]
Yep closing. If anybody disagrees, they can reopen / post a comment.

**Comment by tommck** [comment]
I disagree with the resolution of this.  The FIELD should be set to $invalid.  How do we do inline validation error messages if we can't tell that the field is not valid?

**Comment by ce-smith** [comment]
I agree with @tommck.

Additionally, there is an issue where the field is set to invalid when selecting the same value from the typeahead as that already set. Watching the model binding, the value is set to undefined when working with the typeahead and ng-invalid is applied to the input field. When the new value is set (which happens to be the same as the previous value), the bound value is assigned but the ng-invalid is never removed. This may be an independent issue from that of the topic but combined, it makes form validation with a typeahead very difficult if not impossible.

**Comment by misugijunz** [comment]
I also disagree. We don't always leverage form submit event. In hybrid app (cordova), the submission button can be from native button for a reason. The behaviour offered by this plugin is somewhat confusing especially in this issue.

**Comment by ziedbg** [comment]
Hello, some one found a solution for this problem? I'm using Angular 1.5 and I have the same issue with typeahead-editable="false" and validity .
