### ISSUE TITLE
Always pad hours and minutes in the timepicker

### ISSUE THREAD

**Issue by mbuttu** [angular-ui/bootstrap#2314]
Right now the timepicker only pads the minutes and hours when the template is first loaded. The hours and minutes are not padded when the model changes.

This makes it difficult to create a custom template for the timepicker that uses ```<select>``` elements to let the user choose the ```hour``` and ```minutes```. The problem is shown in [this plunkr](http://plnkr.co/edit/phKW6WEGgIJQolVWV1xd?p=preview). 

The hours and minutes are initially selected correctly. To see the issue, try changing the values to a number less than 10.

**Comment by wesleycho** [comment]
This should be an opt in feature.

**Comment by wesleycho** [comment]
Closing in favor of #4288.
