### ISSUE TITLE
"Shown" Event in Accordion or Collapse

### ISSUE THREAD

**Issue by KatelynL** [angular-ui/bootstrap#2317]
Is there an event fired when the collapse panel or the accordion finishes opening?  I am trying to render a highchart inside an accordion and I need to refresh the chart after the accordion is done opening.  

I'm looking for something like the "shown.bs.collapse" in bootstrap.  http://getbootstrap.com/javascript/#collapse.

**Comment by tinyfly** [comment]
I'd definitely like this. I run into lots of cases where I need to trigger UI stuff only when the transition is complete. I would think it needs both emit and broadcast. A nested directive might need to know it as well as the parent directive.

**Comment by alecha** [comment]
any news? I have the same issue

**Comment by xBelphegorx** [comment]
In my project I need information when collapse is done to expand other element in the same place, so this feature would be helpful (btw. horizontally collapse is needed too). Please consider adding this feature.

**Comment by KatelynL** [comment]
So this event just became even more necessary for me.  I did have a $watch on the isOpen booleans for my accordions and when the isOpen was true I would re-draw the highcharts inside my accordions.  However, with upgrading to version 0.13.0, the timing does not work out and the $watch beats the accordion opening.  This means that I can't get the desired effect without adding a $timeout to my $watch to wait for the accordion to actually open.

**Comment by RobJacobs** [comment]
@KatelynL You should be using a $timeout in your isOpen watch as that will wait for any DOM manipulation to complete (i.e. ng-if directive).  You can implement the $timeout like so:

    $timeout(function() {
      ...
     }, 0, false)

So it won't trigger another digest cycle.

**Comment by wesleycho** [comment]
One could implement a directive that listened for the `transitionstart` and `transitionend` events and emit an event appropriately depending on the opened value and when `transitionend` is fired - I do not believe we will be supporting this in the library itself though, as this adds complexity & maintenance burden for a relatively easy feature for a user to implement.
