### ISSUE TITLE
Typeahead no option to have all items display.

### ISSUE THREAD

**Issue by HerrPfister** [angular-ui/bootstrap#2324]
There is no clear way to display all items, stored in the typeahead, when there is no text in the input and the typeahead gains focus. Did I overlook something? Is there a way to do this? If so, how?

**Comment by marcusg** [comment]
any updates here? I think this would be a nice feature ;)

**Comment by sharpmachine** [comment]
I want the same thing!  Any updates?

**Comment by dmitrijs** [comment]
+1

**Comment by brunocoelho** [comment]
+1

**Comment by brunocoelho** [comment]
I know that you have to support async load, but it would be a nice and very useful feature if you have a list pre-loaded.

**Comment by flaurian** [comment]
Thanks for adding this

**Comment by flaurian** [comment]
Would actually be even nicer with a scroll when displaying all elements but with a limit of (e.g.) 8 results only so that the user does not believe that the list is displaying all results.

**Comment by icfantv** [comment]
@flaurian, that is beyond the scope of this library, but you can do it yourself quite easily with CSS.

**Comment by flaurian** [comment]
thanks for your comment @icfantv !

Just wondering what you mean by scope... I thought the purpose of such a library is to 1) do things bootstrap isn't doing well (I suppose they also have defined a "scope"), 2) build best-practice versions of basic web functionalities. 

IMHO it seems rather obvious that when you are using a typeahead you should be able to a) show all elements (after all it's an enhanced dropdown), b) manage the use case smoothly if the list of elements is way too long (in my case I am selecting an employee out of ~100).
But indeed as you said I managed it easily like this :

`.dropdown-menu{
   max-height:200px;
   overflow-y:auto;
  }`

Cheers

**Comment by icfantv** [comment]
While we do make certain UX decisions and indeed some CSS ones as well, determining on whether someone wants a scrollbar to appear it not our call.  To be clear, I have CSS in our app so in certain areas the scrollbar always shows on WebKit browsers, but again, this specific use case is not one we should be making.  As soon as we do, someone is going to file a bug asking for a way to turn it off.
