### ISSUE TITLE
Timepicker & seconds

### ISSUE THREAD

**Issue by SkyQuant** [angular-ui/bootstrap#2326]
How can I have a third input box for seconds editing additionaly to hours and minutes?

**Comment by barronj** [comment]
I also vote for seconds. I just had an issue today where it was complaining that the time I entered was not greater than or equal to the minimum time for my field even though it looked identical. Turns out, the seconds were off. And this is for an application where seconds matter.

Thank you.

**Comment by jupake** [comment]
+1. We also now need seconds to be changeable.

**Comment by chrisirhc** [comment]
Maybe fulfilled via resolving #3312 . Will look into time input types as well.

**Comment by Foxandxss** [comment]
Let's continue in #4272
