### ISSUE TITLE
Datepicker options

### ISSUE THREAD

**Issue by monkeymonk** [angular-ui/bootstrap#2338]
Hi there,

I don't understand how we can set options for datepicker and datepicker-popup.
And can't find the match with which options are available...

For now, I have find only one options that actually work :

```
.config(function (datepickerPopupConfig) {
    datepickerPopupConfig.showButtonBar = false;  // working !
    datepickerPopupConfig.dateFormat = 'yyyy-MM-dd'; // not working...
    datepickerPopupConfig.showWeeks = false; // not working...
})
```

Any clue ? Links ? Full example ?

Thank you !

**Comment by stevo-knievo** [comment]
I'm using the current version 1.3.4 and I still have the issue.

http://plnkr.co/edit/ZEeHe7?p=preview
