### ISSUE TITLE
Datepicker date-init attribute

### ISSUE THREAD

**Issue by bixibu** [angular-ui/bootstrap#2348]
Hi It seems that the date-init attribute isn't dual binded/synchronised. it's value is only set the first time the datepicker controller is loaded.. Then binding this attribute after its creation makes no change.. 

Typical example where it is needed is when having a "from date" and "to date" datepicker,When the user select a "from date" from the first picker,  I want the second one to open with an "init date" matching the first one.

**Comment by wesleycho** [comment]
This is now fixed as a result of 98e2bdfc8b4dd108acdf3fac75a795675889bbc7
