### ISSUE TITLE
Open the datepicker popup only on button click not of text field focus 

### ISSUE THREAD

**Issue by vishalgajjar** [angular-ui/bootstrap#2350]
I am working on Angular application. I have 2 Angular Datepickers on the page. Right now I am able to open the datepicker popup when i click the datepicker icon and when I focus the field but my requirement is that datepicker popup should be available only when user clicks on calendar icon. I dont want datepicker popup opened on focus of datepicker field.

**Comment by nshukla75** [comment]
I have version 0.12 but still have the same issue 

HTML
 <div class="col-md-12 form-group">
                        <div class="col-md-1">
                            <label>Start Date<span class="required-field">*</span></label>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="mm/dd/yyyy" size="10" datepicker-popup="MM/dd/yyyy"
                                       name="startDate" min="minStartDate" ng-model="issue.startDate" is-open="datePicker.instances['startDate']"
                                       show-button-bar="false" datepicker-options="datePicker.options" ng-blur="onStartDateBlur()" date-parser required />
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" ng-click="datePicker.open($event, 'startDate')"><i class="glyphicon glyphicon-calendar"></i></button>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-1" style="padding-right: 0;">
                            <label>End Date</label>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group" style="padding-left: 0;">
                                <input type="text" class="form-control" placeholder="mm/dd/yyyy" size="10" datepicker-popup="MM/dd/yyyy"
                                       name="endDate" min="issue.startDate" ng-model="issue.endDate" is-open="datePicker.instances['endDate']" show-button-bar="false"
                                       datepicker-options="datePicker.options" ng-blur="onEndDateBlur()" date-parser/>
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" ng-click="datePicker.open($event, 'endDate')"><i class="glyphicon glyphicon-calendar"></i></button>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <span class="required-field" ng-if="submitted && issueSaveForm.startDate.$error.required">Start Date Required</span>
                            <span class="required-field" ng-if="startdatelostfocus && issueSaveForm.startDate.$error.invalidDateRange">Start date must be before end date.</span>
                            <span class="required-field" ng-if="enddatelostfocus && issueSaveForm.endDate.$error.invalidDateRange">End date must be after start date.</span>
                            <span class="required-field" ng-if="(issueSaveForm.startDate.$error.dateParser)">Invalid Start date</span>
                            <span class="required-field" ng-if="(issueSaveForm.endDate.$error.dateParser)">Invalid End date</span>
                        </div>
                    </div>

JS

$scope.datePicker = (function () {
		    var method = {};
		    method.instances = [];

		    method.open = function ($event, instance) {
		        $event.preventDefault();
		        $event.stopPropagation();
		        method.instances[instance] = true;
		    };

		    method.options = {
		        'show-weeks': false
		    };

		    return method;
		}());
