### ISSUE TITLE
Extra $parse on pagination

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#2353]
I am back on my rewriting and I try to understand all the decision made but there is one I can't realize myself.

@bekos Is there a big reason to $parse on `itemsPerPage` watcher and on the `maxSize` one. It is just extra computing and I don't have any edge case where we would need that. Thoughts?

**Comment by rvanbaalen** [comment]
@Foxandxss I assume this is not relevant anymore and can be closed. Feel free to re-open if you think otherwise.
