### ISSUE TITLE
How can I hide left numbers of Datepicker and open Datepicker after focused input

### ISSUE THREAD

**Issue by mani95lisa** [angular-ui/bootstrap#2356]
Thanks, what I want works fine in 0.10.0. What I want to hide is below:
![image](https://cloud.githubusercontent.com/assets/1968989/3312098/d2d2c118-f6cc-11e3-94c0-376ccf18854a.png)

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
