### ISSUE TITLE
Monthpicker in popup only with global configuration?

### ISSUE THREAD

**Issue by maklemenz** [angular-ui/bootstrap#2358]
I'm trying to use the  datepicker in monthpicker-mode as a popup, but the only working way someone found was to configure this globally.
The problem is that this is not the only picker in my application. I need datepickers and monthpickers in different locations of the app, so I cannot configure the mode globally.

The related stackoverflow question:
http://stackoverflow.com/questions/24180416/angularui-monthpicker-in-popup-shown-as-datepicker

Is this a bug or a missunderstanding on my side?

**Comment by rvanbaalen** [comment]
Closing as an outdated issue. If this is still relevant, @maklemenz please provide a plunkr reproducing your problem and we'll be able to take a look at it. Also, test this in the latest UI Bootstrap 0.13 and AngularJS 1.3.
