### ISSUE TITLE
typeahead with input[email] and array of objects

### ISSUE THREAD

**Issue by BergWerkGIS** [angular-ui/bootstrap#2360]
I would like to use typeahead with `input[email]` to take advantage of the validation that comes with it ([example at the angular docs](https://docs.angularjs.org/api/ng/input/input%5Bemail%5D)).

I have to use an existing API that I have no control of and that outputs the emails as an array of objects. It is also important to keep track of the user ID, if an existing email is used.

Using `input[text]` works, but email validation would have to be custom, e.g. regex, which I would like to avoid.
With `input[email]` the list appears but after selecting an entry the input is not populated.

Is there a way to make typeahead working with `input[email]` and an array of objects?
http://plnkr.co/edit/he9m35OoqXBrCgpfg9zL?p=preview

**Comment by rvanbaalen** [comment]
I know this one is old but it seems to be working just fine when you update to AngularJS 1.3, UI Bootstrap 0.13 and the latest available Bootstrap CSS:

http://plnkr.co/edit/NBXLEUsCWq0y5bNVi76a?p=preview

**Comment by prondzyn** [comment]
Not exactly. It does not work correctly. Please inspect the input and check classes set after email selection. It has 'ng-invalid ng-invalid-email' set. How to force Angular or typeahead to revalidate field after selection?
