### ISSUE TITLE
Typeahead causes memory leak

### ISSUE THREAD

**Issue by mastodon0** [angular-ui/bootstrap#2363]
I noticed a memory leak problem when using the typeahead with the default router.

Setup:
1. Place typeahead in template of route A
2. Navigate from route A to route B
3. GC doesn't collect the scope + dom of route A

I looked into it and found the root of the problem in the combination of $compile and the typeaheadPopup-directive because it uses `replace:true`.
If I remove [line 337 in typeahead.js](https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L337) or assign false the memory leak doesn't occur.

Would this be a problem?

(tested using UI Bootstrap 0.11.0 and Angular 1.2.18)

**Comment by beku8** [comment]
I've a UI where typeahead gets destroyed and created many times. Amazingly increased memory & browser crashes. Is it going to be fixed?

**Comment by wesleycho** [comment]
I am not able to reproduce this [here](http://plnkr.co/edit/k05GkjTqv4sTr0Zs3nTu?p=preview) - please open a new issue with reproducible steps (as well as a reproduction) if this is still an issue.
