### ISSUE TITLE
Pagination: can't override default text attributes to empty string

### ISSUE THREAD

**Issue by mlelkes** [angular-ui/bootstrap#2364]
Until recently, I was using pagination so that I set `previous-text`, `next-text`, `first-text`, `last-text` attributes to empty string and added glyphicons to these buttons with CSS.
Now, after upgrading to 0.11.0, this broke, because of this:
```javascript
$scope.getText = function( key ) {
    return $scope[key + 'Text'] || self.config[key + 'Text'];
};
```
The empty strings evaluate to false so the texts fall back to their respective config setting of "First", "Last", etc.

**Comment by wesleycho** [comment]
One can use custom templates on an instance level now, and in this case, I believe this is the route one should go here.

**Comment by dobre0nony** [comment]
add: 
 $scope.empty = "   ";     in controller


add:
next-text="{{empty}}"
previous-text="{{empty}}">  on directive

its stupid but it works, now previous and next can be empty and replaced with anything inside
