### ISSUE TITLE
Refreshing the demo website can lead to 404 errors

### ISSUE THREAD

**Issue by oliversalzburg** [angular-ui/bootstrap#2368]
If you visit http://angular-ui.github.io/bootstrap/ and click on **Directives** → **Accordion**, you get send to http://angular-ui.github.io/bootstrap/#/accordion.
If you then press F5, you'll get send to http://angular-ui.github.io/bootstrap/accordion and then to a 404 error page.

**Comment by BobbieBarker** [comment]
Thank you for opening this issue, what ever seems to have been causing your problem at the time is no longer reproducible. Feel free to reopen the issue if the problem persists.

**Comment by oliversalzburg** [comment]
Can confirm that it no longer happens :)
