### ISSUE TITLE
Datepicker manual input forced to US format

### ISSUE THREAD

**Issue by natcohen** [angular-ui/bootstrap#2369]
Hello,
I'm using datepicker with input (so the user can insert the date manually). If I select in the datepicker the date, it will show up with format dd.MM.yyyy (which is what I want). But if I manually write inside the input, the datepicker popup won't be set to the correct date and will shoow US format date (MM.dd.yyyy).

you can try there:
http://plnkr.co/edit/t9ERna33YcG8ubDqDPgy?p=preview

**Comment by wesleycho** [comment]
I believe this is currently fixed on `master` with making the model invalid - feel free to open a new issue if this is not the case
