### ISSUE TITLE
Modal - Ability to modify z-index

### ISSUE THREAD

**Issue by Zorkling** [angular-ui/bootstrap#2373]
The modal uses a ng-style to set the z-index, which will overwrite any class styles defined. 
`ng-style="{\'z-index\': 1040 + (index && 1 || 0) + index*10}"`

This is associated with the backdrop and the window.

I would suggest either making the 1040/1050 configurable or adding another property, such as:
`ng-style="{\'z-index\': 1040 + (index && 1 || 0) + index*10 + configurableIndex}"`

I'm working under the assumption the above index property is used to handle multiple modals, and changing it to use classes is not feasible. Is that accurate?

**Comment by distinctdan** [comment]
Personally, I'd rather have the config option, so that I don't have to override the templates.

**Comment by darynmitchell** [comment]
I agree: different types of modals, wishing I could have configurable option.

**Comment by Rosewood99** [comment]
Throwing my vote in for configurable z-index.  Running into an issue right now.

**Comment by steelsojka** [comment]
+1

**Comment by alpemaca** [comment]
+1

**Comment by vlapo** [comment]
+1

**Comment by mizrael** [comment]
+1

**Comment by jrauschenbusch** [comment]
+1

**Comment by rvanbaalen** [comment]
As @pkozlowski-opensource already said months ago, we won't be adding another option to the already extensive config possibilities of the modal. You can easily use a custom template with the correct z-index by using `templateUrl`. That, in combination with the options to overwrite the default template or to add a `windowClass` you should have enough tools to achieve what you want.

Please **don't** add +1's to this issue as it is already closed.
