### ISSUE TITLE
Add directives for standard form controls

### ISSUE THREAD

**Issue by sylvain-hamel** [angular-ui/bootstrap#2375]
Hi,
I'd like ui-bootstrap to offer directives that make it faster (less markup) to create forms.

The idea to replace this:

```html
<div class="form-group">
  <label for="fn4" class="control-label col-sm-2">Notes</label>  
  <div ng-if="horizontalForm" class="ng-scope col-sm-6">
    <input type="text" class="form-control" id="fn4" placeholder="enter comments...">
  </div>
</div>
```

With this:

```html
<abf-text id="fn4" label="Notes" placeholder="enter comments..."></abf-text>
```
And making sure it works well with all form classes (`form`, `form-inline`, `form-horizontal`)

I wrote a prototype of such directive in [this plunkr](http://plnkr.co/edit/ytYSIZUeR8yiWVGBn6Yt?p=preview) just to demonstrate what I'm thinking of.

Is this someting you guys are interested in adding to the project? Otherwise I'll start a separate project.

Thanks

**Comment by rvanbaalen** [comment]
How's the progress going @sylvain-hamel ?

Closing this issue for now but please reference your project if you have something!

**Comment by sylvain-hamel** [comment]
Hi @rvanbaalen, no progress at all on this project. I'll update this issue if I eventually get to it but I don't think it's going to happen.
