### ISSUE TITLE
Timepicker: width of hours/minutes input fields when placed in form-inline

### ISSUE THREAD

**Issue by Magnificus36** [angular-ui/bootstrap#2376]
When you have a timepicker inside a element with class="form-inline" the width of the input fields get set to auto instead of 100% causing display problems.

http://plnkr.co/edit/vqFTtRLN4IE9v3LWKCy4?p=preview

**Comment by rvanbaalen** [comment]
This is not an issue with UI Bootstrap but an implementation issue

https://github.com/angular-ui/bootstrap#need-help
