### ISSUE TITLE
ToggleOpen fires twice thus preventing from opening accordion-group, in Chrome only

### ISSUE THREAD

**Issue by lonormaly** [angular-ui/bootstrap#2378]
For some reason, pressing the accordion groups anchor tag fires the toggleOpen function twice.
This only happens in Chrome. in FF and Safari this doesn't happen...

Any ideas?

Tested even in the main angular-ui website:
http://angular-ui.github.io/bootstrap/

**Comment by rvanbaalen** [comment]
Fixed with 9ca4ec399be0e0e8f6c3fe6fd924a7d94ce669b5
