### ISSUE TITLE
Datepicker not working in ng-repeats

### ISSUE THREAD

**Issue by cgarvis** [angular-ui/bootstrap#2384]
Example plunker: http://plnkr.co/edit/MQzUiooc7mojBH5ivuNC?p=info

Looks like it could be related to other posts: #1381 #2253 #1138

**Comment by wesleycho** [comment]
This appears to not be an issue - we currently only support date objects.

Anyhow, this is not an issue with ng-repeat and the datepicker.

**Comment by RajKharva** [comment]
@andrewdacenko Thanks a lot :+1:
