### ISSUE TITLE
typeahead: ng-change expression is not evaluated when user select item from list

### ISSUE THREAD

**Issue by alexander-konovalov** [angular-ui/bootstrap#2385]
http://plnkr.co/edit/9VWpbHSPlAJ6V5YqyUcf?p=preview
But if I input value manualy then OK

**Comment by rvanbaalen** [comment]
ngChange is just for the input, if you want to listen the model do like this:

```js
$scope.$watch('model.selected', function(value, oldValue) {

});
```
