### ISSUE TITLE
"typeahead-input-formatter" is ignored when the input is the same as the value

### ISSUE THREAD

**Issue by goekhanak** [angular-ui/bootstrap#2390]
In Typeahead  "typeahead-input-formatter" attribute is ignored when the given input is the same as the value with a slightly different input it works.

A Plunker for the issue: http://plnkr.co/edit/uWoI7M?p=preview

**Comment by rvanbaalen** [comment]
I can't seem to understand what is 'not working' here. Looks like your input formatter is working just fine? I'll close this since the issue is pretty old now. Feel free to re-open of you are still experiencing this issue with AngularJS 1.3 and UI Bootstrap 0.13.
