### ISSUE TITLE
Datepicker range support

### ISSUE THREAD

**Issue by WindyWong** [angular-ui/bootstrap#2391]
The current datepicker only allows to select a single date. If would be useful if the datepicker allows to select a date range. Multiple months could be displayed and the dates between the user selected start and the end dates get some class to customize highlighting.

There are plenty of jQuery solutions that do this, but this is the only pure angular solution that I have been able to find https://github.com/monterail/angular-date-range-picker. Unfortunately this library is only a directive and does not provide much flexibility. It would be great to see this functionality in angular-ui.

Can you reply and implement this request?  Thanks in advance!

**Comment by aesnyder** [comment]
@jsdevel did you ever get the range to highlight?

**Comment by vdsabev** [comment]
+1, we need this in our project. It's not critical, but it would look great.

**Comment by ngloom** [comment]
+1, date range picker needed :)
hope some day we can have a  date-range-picker like http://www.daterangepicker.com/
ps, Thanks for your work guys, you're really doing great !

**Comment by jsdevel** [comment]
@aesnyder we were, but not without some hacks :(

**Comment by marcusstockton** [comment]
Is there a way to clear the data? i've been trying and so far, can clear the data in the background, but the dates in the input don't get updated.
I'm resetting the data in a Angular ClearFilters directive?
The following is an extract. The other fields are all cleared on the call except this date picker. I've tried using null as well.

    $scope.clearFilters = function () {
        $scope.DatePickerOptions = {
            startDate: '',
            endDate: ''
        };
}

Any advise would be appreciated.
Thanks,

**Comment by spongessuck** [comment]
My module gives the Datepicker this feature.

https://github.com/spongessuck/gm.datepickerMultiSelect

**Comment by BobbieBarker** [comment]
Closing, I don't see any active problems with uib here. I also don't think we're interested in implementing something like a date range picker.

**Comment by dinebennett** [comment]
+1 - Something like http://www.daterangepicker.com/#examples would be great for me.

Thank you for all the work you guys have done on UI bootstrap, it's really really useful  :)

**Comment by decherneyge** [comment]
It is possible with what exists currently.

Here is a plunker modified from the docs plunker that shows one use case. It could be modified depending on your exact needs.
http://plnkr.co/edit/wHpbTG6E7fTqpGebYZZP?p=preview

**Comment by ZhukV** [comment]
+1, datepicker range needed!

**Comment by shyamal890** [comment]
+1 Datepicker range

**Comment by icfantv** [comment]
@ZhukV @shyamal890, please do not add +1 to issues.  It adds no intrinsic value and only clutters up the thread.  GitHub has added emoji reactions to posts so that you can show your support for an issue without adding meaningless clutter.  It is the smiley icon next to the pencil.

Now, all that said, date range support is something we are not going to support.  There are multiple posts on this, and the reasoning, in our closed issues.

**Comment by mportuga** [comment]
I have come up with a plunker that achieves this with minimal code: https://plnkr.co/edit/VB79RPyXsYQhueZwVd5H?p=preview

I used a watch and the custom class attribute only.
