### ISSUE TITLE
Typeahead behaves differently with http backed data vs hard-coded data

### ISSUE THREAD

**Issue by danielburrell** [angular-ui/bootstrap#2396]
Given the following example scenario:
- A model of dropdown options [{id:"1",name:"bob (1)", {id:"2",name:"roger (2)"}]
- This model is pulled via http request.
- The ability to type bob into the inputbox, and have bob's name appear (while roger remains filtered).
- On pressing enter, bob's name is displayed, BUT, the model is bound to the id value 1.
- If the id is passed in the URL as a query parameter, i should be able to 
 1) wait for the http request which generates the dropdown options
 2) find the id in this dropdown option model, bind the textbox's model to this, set the textbox's display to the associated name.

Snippet of code here:
https://gist.github.com/danielburrell/96e21a011bc8d2fd5f58

"query.defindex" is the ng-model query parameter that it's bound to.

Currently the above requirements seem to only be achievable if the dropdown data is hardcoded as an array (i.e. not fetched via http). Since the formatter executes at the start, finds the http request hasn't completed and then returns no value.

Further to this under an http request, getItems() - is called for every keystroke - when the filter is applied to a hardcoded array, the filtering functions as expected, however when the filter is applied to the array that is returned from an http query, the list is not reduced by the filter. The result is that typing "bob" under an http system results in a dropdown list containing "bob" and "roger", swapping this out for a hard-coded array fixes this.

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
