### ISSUE TITLE
feature suggestion: Notifications

### ISSUE THREAD

**Issue by Sanjo** [angular-ui/bootstrap#2401]
Hi, is there interest in adding a notifications directive and service with the features of http://goodybag.github.io/bootstrap-notify/ to angular-bootstrap?
I built one on top of angular-bootstrap and the alert directive and it is quite lightweight. I thought such a directive would be quite useful because many apps need notifications.

**Comment by Foxandxss** [comment]
I think that for now, we can't maintain more directives.
