### ISSUE TITLE
typeaheadPopup directive not respecting tempateUrl property

### ISSUE THREAD

**Issue by domakas** [angular-ui/bootstrap#2405]
When using typeaheadPopup directive, default template url is used for it's template and templateUrl argument is not respected.

The problem is that code uses 
`scope.templateUrl = attrs.templateUrl;`
in `link` function, however, by the time `link` function is called, request for default template directory is made, and if it's not there - exception occurs.

This can be easily fixed by linking templateUrl to actual element parameter:
```
      templateUrl:function(element, attrs) {
        return attrs.templateUrl || 'template/typeahead/typeahead-popup.html';
      }
```

Can I get a confirmation that this is actual issue and not just a misunderstanding?

**Comment by wesleycho** [comment]
I think this is a misunderstanding - the templateUrl is for the template of each of the matched items.

**Comment by domakas** [comment]
@wesleycho after a second look I have noticed that you are right, ```templateUrl``` is assigned to scope and then used in ```typeahead-popup.html``` template. However in this case it seems that it's impossible to overwrite templateUrl of ```typeaheadPopup``` itself, so you need to be sure you have popup template in ```template/typeahead/typeahead-popup.html``` directory. 

How this could be solved? It seems that a lib forces developer to have such project structure as defined in that lib

**Comment by wesleycho** [comment]
You would need to override the template by updating the template present in templateCache or using your own template.

**Comment by domakas** [comment]
Yup, that's what I meant. For me it seems to be a problem to override it in templateCache because it's seems hacky and separation of concerts might not be followed here, and when using your own template file you need to place it directly at ```template/typeahead/typeahead-popup.html``` because it's hardcoded in the directive.

Is this a problem or it isn't?

**Comment by wesleycho** [comment]
You can use a build tool to compile it into the $templateCache, or manually just define the template in $templateCache yourself (i.e. `$templateCache.put('template/typeahead/typeahead-popup.html', ...)`). It is a pretty standard procedure IMO if a library's template doesn't match your needs.

**Comment by domakas** [comment]
It just seemed strange that it's possible to change item template in this simple way, however popup template needs different approach.

Thanks for you comments, closing this :)
