### ISSUE TITLE
Is there any way to trigger another datepicker by clicking the first datepicker? 

### ISSUE THREAD

**Issue by WindyWong** [angular-ui/bootstrap#2407]
I have created two popup datepickers(two input fields). I am curious if the second datepicker can be triggered to open automatically once I choose a date from the first datepicker for the first input. The scenario will be like below:

1. click the first input box(first datepicker). The first datepicker shows up.
2. choose a date from the first datepicker. This datepicker will close and the date I choose will be filled into the first input box.
3. the second datepicker will open automatically once the first datepicker closes and the date fills into input box. 
4. I can choose date from the second datepicker for the second input box. 

If there is any way and anyone can provide a solution will be much appreciated! A brief example will be awesome! Thanks!

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
