### ISSUE TITLE
Callback function on navigating the suggestion values

### ISSUE THREAD

**Issue by joshijimit** [angular-ui/bootstrap#2408]
Hi,

I am using typeahead in my angular project. I want to implement the functionality like google such that if user navigate to any of the option in suggestion box, a callback function is called and filter the search result. User don't need to select any option in order to filter the search result.

I believe it is not currently achievable (out of the box) with angular ui, however would be great if some one can guide me on how I can achieve it.

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
