### ISSUE TITLE
Docs: List of dynamically-added CSS classes?

### ISSUE THREAD

**Issue by jtibble** [angular-ui/bootstrap#2409]
I'm running the Bootstrap CSS through UnCSS at build-time, and of course it's removing classes like 'open' from the Bootstrap CSS Dropdown because it's added to angular templates dynamically. Is there a published list of classes that these directives add at runtime that I can tell UnCSS to ignore and leave in the original bootstrap CSS file?

Much thanks,
John

**Comment by Foxandxss** [comment]
I am sorry, but I don't think is nothing we should care about. It is a really really "weird" use case and I never saw any projects docs doing that.

You could (if still interested) take a peek on the source and search for all `addClass` methods.
