### ISSUE TITLE
$modal.open().opened with animations

### ISSUE THREAD

**Issue by bblack** [angular-ui/bootstrap#2411]
I would like the `opened` promise of `$modal.open()` to resolve after any animations associated with opening the modal. Or, if the intent of `opened` isn't to fire after the template has been rendered, but merely loaded, I'd like a way to run some code after the template has been rendered, and the show animation has completed.

**Comment by wesleycho** [comment]
One can create a custom directive to set focus on a particular input, and I'd say that would be the recommended approach for any similar DOM manipulation.
