### ISSUE TITLE
datepicker-mode="month" does not work in popup

### ISSUE THREAD

**Issue by creimers** [angular-ui/bootstrap#2417]
I have the impression that datepicker-mode="month" does not work with the pop up version of the datepicker. Trying in the plunker that links from the ui.boostrap page, I can easily implement it for the inline <datepicker>, but not for the popup. Is this an easy fix maybe?

**Comment by rvanbaalen** [comment]
No need to bind it to the scope, you can also use single quotes:

`<input datepicker-popup="" datepicker-mode="'month'">`

This is how AngularJS expressions work.

**Comment by eablokker** [comment]
@rvanbaalen  This worked for me. Thx

**Comment by BaronVonPerko** [comment]
Thank you @rvanbaalen and @dmitryevseev, totally solved my issues :)

**Comment by icfantv** [comment]
@BaronVonPerko, given the age of this, you may want to take a gander at the latest version of the library to see if it's still an issue.

**Comment by BaronVonPerko** [comment]
@icfantv it is an issue in 0.12, which is what we are using.  I do plan on upgrading to the latest soon, but it's not a personal project of mine, so it's not entirely up to me :P

**Comment by icfantv** [comment]
@BaronVonPerko, yea, we're up to 0.14.3 now and 1.0.0-SNAPSHOT has a TON of additional fixes/changes.  If you want to try a plunker to see, that's always an option.  You can build the latest release by pulling the latest code and running `npm install` followed by `grunt`.
