### ISSUE TITLE
firefox 29 $position service unexpected behaviour

### ISSUE THREAD

**Issue by ebuckley** [angular-ui/bootstrap#2418]
The service does not provide the correct position when using a tooltip on buttons in a `.btn-group-justified` element.

I have created a plnkr to show this behaviour http://plnkr.co/edit/6ErC11UZkPWbbt83iAvj?p=preview
To reproduce:
   - Hover over the second or third button.
   - Observe the tooltip position is incorrect.

Firefox 30 does not exhibit this behavior.

**Comment by wesleycho** [comment]
Closing as invalid, as it seems to be fixed in later Firefox versions.
