### ISSUE TITLE
Input with typeahead and with ng-maxlength does not keep value

### ISSUE THREAD

**Issue by RastoStric** [angular-ui/bootstrap#2426]
The value of an input is cleared after user selection from typeahead drop-down when using ng-maxlength (although the maxlength limit is not reached). Attached plunk shows an input **without** `ng-maxlength` keeping the value and an input **with** `ng-maxlength` gets cleared.

http://plnkr.co/edit/yefOFSh85NBWpC6nbHnt?p=preview

**Comment by rvanbaalen** [comment]
Fixed in the latest UI Bootstrap 0.13.0:
http://plnkr.co/edit/pkOJeaV5gzz7HgvbJoG0
