### ISSUE TITLE
Progress directive overrides HTML 5 <progress> element.

### ISSUE THREAD

**Issue by blindworld** [angular-ui/bootstrap#2429]
The HTML 5 progress element (http://www.w3.org/html/wg/drafts/html/CR/forms.html#the-progress-element) gets overridden by the progress directive here (https://github.com/angular-ui/bootstrap/blob/master/src/progressbar/progressbar.js).

I realize we could create our own build and just not include the progress bar, but that would prevent us from using bower to keep up to date as well.

**Comment by bzitzow** [comment]
+1

**Comment by ryanhburbank** [comment]
I agree with @scottopherson, I would really like some better namespacing in the library.

**Comment by LeDeep** [comment]
+1 please. Prefixing would be great

**Comment by JobaDiniz** [comment]
+1

**Comment by chrisirhc** [comment]
Will be fixed via #157 , moving milestone to align with that issue.

**Comment by wesleycho** [comment]
This should now be fixed.

**Comment by wesleycho** [comment]
Sorry, closed prematurely - this is still an issue for stacked bars.

**Comment by grzegorzjudas** [comment]
+1, this is getting ridiculous, especially now, when HTML5 is being so widely used...

**Comment by wesleycho** [comment]
It's not so simple - changing this is a breaking change, and guaranteed to break apps.

In addition there are a lot of feature requests/bug fixes that also need addressing, and short manpower.

If someone were to put together a high quality PR, it would be reviewed and merged in, but nobody has stepped up to the plate to contribute.

**Comment by wesleycho** [comment]
I'm going to close this, as we have already marked the `progress` element directive as deprecated and it is scheduled to be removed in 1.0.0 along with all of the non-prefixed directives.
