### ISSUE TITLE
Modal and date picker not working together after first click

### ISSUE THREAD

**Issue by KevinMann13** [angular-ui/bootstrap#2431]
When a date picker is inside of a modal window, it only works on the first click to select the date. After that the picker doesn't pop up anymore. 

http://plnkr.co/edit/ridTspMBHE1iphrSobQr?p=preview

**Comment by hugotorres** [comment]
doesnt seem to be working now

**Comment by rvanbaalen** [comment]
Not an issue anymore: http://plnkr.co/edit/1bB0JSdpmE1zsHiPUlT2?p=preview
