### ISSUE TITLE
Tests broken under PhantomJS

### ISSUE THREAD

**Issue by alukovenko** [angular-ui/bootstrap#2434]
I've got the following error messages while running tests on trunk under karma/PhantomJS:

PhantomJS 1.9 (Linux): Executed 95 of 656
PhantomJS 1.9 (Linux): Executed 96 of 656
PhantomJS 1.9 (Linux) datepicker directive  renders the week numbers based on ISO 8601 FAILED
        Expected [ '35', '36', '37', '38', '39', '40' ] to equal [ '34', '35', '36', '37', '38', '39' ].
PhantomJS 1.9 (Linux): Executed 97 of 656 (1 FAILED)

...

PhantomJS 1.9 (Linux): Executed 105 of 656 (1 FAILED)
PhantomJS 1.9 (Linux) datepicker directive  moves to the next month & renders correctly when `next` button is clicked FAILED
        Expected [ [ '26', '27', '28', '29', '30', '01', '02' ], [ '03', '04', '05', '06', '07', '08', '09' ], [ '10', '11', '12', '13', '14', '15', '16' ], [ '17', '18', '19', '20', '21', '22', '23' ], [ '24', '25', '26', '27', '28', '29', '30' ], [ '30', '30', '30', '30', '30', '30', '30' ] ] to equal [ [ '26', '27', '28', '29', '30', '01', '02' ], [ '03', '04', '05', '06', '07', '08', '09' ], [ '10', '11', '12', '13', '14', '15', '16' ], [ '17', '18', '19', '20', '21', '22', '23' ], [ '24', '25', '26', '27', '28', '29', '30' ], [ '31', '01', '02', '03', '04', '05', '06' ] ].
PhantomJS 1.9 (Linux): Executed 106 of 656 (2 FAILED)
PhantomJS 1.9 (Linux): Executed 107 of 656 (2 FAILED)
PhantomJS 1.9 (Linux) datepicker directive  updates the calendar when a day of another month is selected FAILED
        Expected [ [ '26', '27', '28', '29', '30', '01', '02' ], [ '03', '04', '05', '06', '07', '08', '09' ], [ '10', '11', '12', '13', '14', '15', '16' ], [ '17', '18', '19', '20', '21', '22', '23' ], [ '24', '25', '26', '27', '28', '29', '30' ], [ '30', '30', '30', '30', '30', '30', '30' ] ] to equal [ [ '26', '27', '28', '29', '30', '01', '02' ], [ '03', '04', '05', '06', '07', '08', '09' ], [ '10', '11', '12', '13', '14', '15', '16' ], [ '17', '18', '19', '20', '21', '22', '23' ], [ '24', '25', '26', '27', '28', '29', '30' ], [ '31', '01', '02', '03', '04', '05', '06' ] ].
PhantomJS 1.9 (Linux): Executed 108 of 656 (3 FAILED)

...

PhantomJS 1.9 (Linux): Executed 165 of 656 (4 FAILED)
PhantomJS 1.9 (Linux) datepicker directive attribute `starting-day` renders the week numbers correctly FAILED
        Expected [ '36', '37', '38', '39', '40', '41' ] to equal [ '35', '36', '37', '38', '39', '40' ].
PhantomJS 1.9 (Linux): Executed 166 of 656 (5 FAILED)

...

PhantomJS 1.9 (Linux): Executed 189 of 656 (5 FAILED)
PhantomJS 1.9 (Linux) datepicker directive formatting changes the title & months format in `month` mode FAILED
        Expected [ [ 'Jan', 'Feb', 'Mar' ], [ 'Apr', 'May', 'Jun' ], [ 'Jul', 'Aug', 'Sep' ], [ 'Oct', 'Oct', 'Dec' ] ] to equal [ [ 'Jan', 'Feb', 'Mar' ], [ 'Apr', 'May', 'Jun' ], [ 'Jul', 'Aug', 'Sep' ], [ 'Oct', 'Nov', 'Dec' ] ].
PhantomJS 1.9 (Linux): Executed 190 of 656 (6 FAILED)

...

Should I provide any additional information?..

**Comment by alanquigley** [comment]
Can you think of any reason why the test won't run in PhantomJS, I've run into problems when using ui.bootstrap and the angular SEO library which uses PhantomJS to render pages.

**Comment by pkozlowski-opensource** [comment]
I didn't use PhantomJS to be honest so can't help here. But I can see several people reporting plenty of problems using it - not sure if those problems are linked to the PhantomJS itself or a particular setup. Regardless - using it in practice seems to be painful and it doesn't bring anything for us (we can use real browsers) so this is why we are staying away from PhantomJS.
