### ISSUE TITLE
Datepicker marks valid content invalid when using custom format

### ISSUE THREAD

**Issue by smuellerus** [angular-ui/bootstrap#2446]
When using a custom format like this:

$scope.format = 'dd.MM.yyyy';

.. it will mark a valid manually inputted date as invalid, for example:

22.07.2014

If you select the same date in Datepicker, it will be accepted. I noticed that if you manually enter

02.01.2014

into the field, it accidentally navigates to Feb 1 2014 even though this date means Jan 2 2014.

I am waiting for a fix - thanks in advance!

**Comment by jmayday** [comment]
I'm just reviewing some datepicker issues as I also have some and found this ticket. To be honest I have to agree that date parsing is somehow broken on datepicker, but I can't get "02.01.2014" parsed as Feb 1 2014 (I entered manually here http://angular-ui.github.io/bootstrap/#/datepicker)
