### ISSUE TITLE
Multiple dropdowns together do not work

### ISSUE THREAD

**Issue by lvegerano** [angular-ui/bootstrap#2448]
Using v.011 adding multiple dropdowns messes up the toggle. To fix it I isolated the scope in the dropdown directive and the dropdownToggle directive.

Here is an example http://plnkr.co/edit/xr8eTgRIcK4XD3pkjDg3?p=preview

**Comment by wesleycho** [comment]
This appears to still be an issue: http://plnkr.co/edit/QeqiU3pOWmzV5apLc7BG?p=preview

**Comment by RobJacobs** [comment]
I think part of the problem is that both dropdowns are binding the is-open attribute to the same variable.

**Comment by karianna** [comment]
Is this really an Angular 1.3 /  0.13.0 issue?

**Comment by RobJacobs** [comment]
This [plunk](http://plnkr.co/edit/u25BuHp5Fg1LChwFR4K5?p=preview) forked from @wesleycho plunk above shows multiple dropdowns working using the internal directive open flag and the is-open attribute.  Both seem to be working fine to me.

**Comment by rvanbaalen** [comment]
As @karianna said; this doesn't seem to be a critical 'Angular 1.3 support' issue, is it?

**Comment by RobJacobs** [comment]
@rvanbaalen I would argue it's not an issue at all, unless I missed something in the plunk I created?

**Comment by karianna** [comment]
Closing as fixed in that case, OP can reopen if they can repeat the issue with master.

**Comment by korya** [comment]
I have the issue when I use `dropdown-append-to-body` functionality for multiple dropdowns sharing the same `is-open`. Check out http://plnkr.co/edit/fl0htOi6k0trMAWwkaoV?p=preview

angular v1.4.9
ui-bootstrap v.1.2.5

**Comment by korya** [comment]
Should I open a new issue?

**Comment by wesleycho** [comment]
Yes, would be easier to triage - I recommend looking at the is-open api though.
