### ISSUE TITLE
Disfunction typeahead on url input type

### ISSUE THREAD

**Issue by max258** [angular-ui/bootstrap#2468]
For input type="url" is not possible use typeahead.
If you click on item, this is ignored.

Plunkr: http://plnkr.co/edit/dgN6reY0N02vgx2FTyAu?p=preview

**Comment by BobbieBarker** [comment]
I'm not sure what the problem is here exactly, I tried the plunker and it seems to be working... Please retest against the latest version of angularJS and this project. If it is still a problem reopen this issue.
