### ISSUE TITLE
 'undefined' is not an object (evaluating 'n.get(a).value') close

### ISSUE THREAD

**Issue by sradu** [angular-ui/bootstrap#2471]
On iOS this error is randomly generated. It's caused by the modal element.

**Comment by antoinepairet** [comment]
@sradu I will close the issue for now as you did not provided a working plunkr showing the problem you want to report. `evaluating 'n.get(a).value'` suggests you are using minified js which is difficult to debug.
Moreover, my guess is you are encountering a bug which was fixed by #1972
