### ISSUE TITLE
dateParser does not fully parse a date string

### ISSUE THREAD

**Issue by gmadden-openet** [angular-ui/bootstrap#2472]
Hello,

I've been working on a bug that relates to the dateParser service and datepickerPopup directive.

I have found a problem in the dateParser directive in that it doesn't build the regular expression to parse the time part of a date (e.g. the date format might be 'medium'). There is also a problem in the isValid function in that it doesn't fully validate the ranges for all the different values in the date. It is currently possible to enter a date like "40 May, 2014".

There is also a problem in datepickerPopup. If dateParser is unable to parse the date string, it uses the Date constructor to parse the date string. This means that the dateParser may find a validation problem (e.g. a day of month is out of range) but the datepickerPopup just uses the Date constructor to parse the date string. This constructor appears to be much more permissive.

I have code that fixes both of these issues so if you're interested in taking a look at them.

**Comment by rvanbaalen** [comment]
Closing as outdated.
