### ISSUE TITLE
Allow switching to Font Awesome

### ISSUE THREAD

**Issue by stramel** [angular-ui/bootstrap#2475]
Could you allow the user to specify to use Font Awesome over Glyphicons?

**Comment by cyberwombat** [comment]
I was not able to use the LESS method from @stramel - I believe from reading the extend docs that it requires the original glyphicon.less file to be present which it is not in my case. However it was easily resolved by adding this anywhere after my Font Awesome imports:

    .glyphicon {
      .fa-icon();
    }
    .glyphicon-chevron-left:before { content: @fa-var-chevron-left; }
    .glyphicon-chevron-right:before { content: @fa-var-chevron-right; }
    .glyphicon-chevron-up:before { content: @fa-var-chevron-up; }
    .glyphicon-chevron-down:before { content: @fa-var-chevron-down; }

**Comment by preston** [comment]
:100: for allowing Font Awesome configuration!

**Comment by pitrackster** [comment]
:+1:  for font-awesome simple configuration support !

**Comment by DaAwesomeP** [comment]
I would much prefer a configuration to a hack. It makes using icons very, very tedious.

**Comment by DaAwesomeP** [comment]
Would using the icon-less version of the Bootstrap CSS work? It' is mentioned [here](http://stackoverflow.com/a/18794451/2852590).

**Comment by Shivraj-Star** [comment]
.glyphicon {
  display: inline-block;
  font-family: FontAwesome !important;
  font-style: normal;
  font-weight: normal;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.glyphicon-chevron-left:before {
  content: "\f053";
}
.glyphicon-chevron-right:before {
  content: "\f054";
}
.glyphicon-chevron-up:before {
  content: "\f077";
}
.glyphicon-chevron-up:before {
  content: "\f077";
}

**Comment by phuyem** [comment]
still hoping core support for font awesome

**Comment by icfantv** [comment]
@phuyem, most, if not all, of our templates can now be overridden.  If you want font awesome, just switch out the templates.

**Comment by cyberwombat** [comment]
@phuyem I thnk you can also switch them out like in this post http://stackoverflow.com/questions/26638215/how-to-replace-glyphicons-with-fontawesome-in-bootstrap-3-without-changing-html#26638216

**Comment by yasar** [comment]
I adapted the less solution for Icomoon, here how it looks like for those who in need:

```
@import (less, reference) 'icomoon.css';
.glyphicon:extend([class^="icon-"] all) {
  &.glyphicon-chevron-right:extend(.icon-chevron-right all) {};
  &.glyphicon-chevron-left:extend(.icon-chevron-left all) {};
  &.glyphicon-chevron-up:extend(.icon-chevron-up all) {};
  &.glyphicon-chevron-down:extend(.icon-chevron-down all) {};
  &.glyphicon-calendar:extend(.icon-calendar52 all) {};
}
```

**Comment by blowsie** [comment]
I made this Gist to map all glyphicon icons to font-awesome.
I'd estimate it has around 95% accuracy and coverage (glyphicon has some useless icons that font-awesome doesn't).

https://gist.github.com/blowsie/15f8fe303383e361958bd53ecb7294f9
