### ISSUE TITLE
Adding attribute for icons to Accordion Group(feature request)

### ISSUE THREAD

**Issue by ozjongwon** [angular-ui/bootstrap#2476]
I found adding icons to accordion directive is impossible.

Supporting "icon" attribute would be great with a template like:

``` HTML
<div class="panel panel-default">
  <div class="panel-heading">
    <a class="accordion-toggle" ng-click="toggleOpen()" accordion-transclude="heading">
      <h4 class="panel-title"><span ng-class="{'text-muted': isDisabled} class={{icon}}"> {{heading}}</span></h4>
    </a>
  </div>
  <div class="panel-collapse" collapse="!isOpen">
    <div class="panel-body" ng-transclude></div>
  </div>
</div>
```

Then usage would be:

``` HTML
...
      <accordion-group heading="{{menu.title}}" icon="{{menu.icon}}">
...
```

Where menu.icon would be things like:

``` HTML
"glyphicon glyphicon-pencil"
```

**Comment by technimadhu** [comment]
Hi, I am not able to get this to work if its in ng-repeat..

http://plnkr.co/edit/8cZXd6w8WQiO5aUr1gQb?p=preview

**Comment by technimadhu** [comment]
should have played with it a bit before posting. If i kept the class in my array and left the <i> tag in html its fine. Thanks

http://plnkr.co/edit/J4jm4cEZRyNfpyDlPB75?p=preview
