### ISSUE TITLE
Passing data into the modal controller

### ISSUE THREAD

**Issue by jhiemer** [angular-ui/bootstrap#248]
Hi,
this is more a question than an issue. How do I provide data from the parent controller into the child controller, when using a modal dialog?

Sadly I was not able to find any information in the docs and also not in the source code. Could anyone give me a hint and help me out?

**Comment by bonthom** [comment]
sasd

**Comment by ghost** [comment]
@jhiemer   The controller in the modal is an angular controller , not a function
