### ISSUE TITLE
typeahead and ng-change

### ISSUE THREAD

**Issue by jon64digital** [angular-ui/bootstrap#2487]
Is it no longer possible to use ng-change on a typeahead to detect when the user is typing?

I just updated to version 0.10.0 and it no longer seems to work.

I use this to empty the model then the user presses backspace to clear the input box. I need to do this because when my search box is cleared I need to reload a grid full of data. typeahead-on-select is no good for this because they haven't selected anything, ng-change doesn't seem to fire and even ng-keypress doesn't seem to fire most of the time. I assume they are being overriden by the typeahead directive.

ng-change used to work though.

**Comment by abrule** [comment]
Thanks jon64digital ! Your typeahead-on-clear attribute saves me a couple of hours to a problem I had.

**Comment by chrisirhc** [comment]
Moving to purgatory as there hasn't been any updates.

**Comment by wesleycho** [comment]
This seems to work to me [here](http://plnkr.co/edit/xHylSVtifI4aDFJWEcDW?p=preview) - I would recommend using ng-keypress to detect user typing though.
