### ISSUE TITLE
feature request - prevent previous and next month dates clickability

### ISSUE THREAD

**Issue by c0debreaker** [angular-ui/bootstrap#2498]
Hi folks,

I'm not sure if DatePicker has this feature. I want the previous month's date and next month's date from not being able to clicked. See my screenshot below

On the screenshot, I'm displaying May month. I would like only May's dates to be clickable and not April 27,28,29,30 nor June 1-7. Is that possible?
 
http://i.imgur.com/n0KMSYQ.png

**Comment by rvanbaalen** [comment]
This can be achieved by using the min and max-date settings.
