### ISSUE TITLE
Tabset: tab's active property does nothing Version: 0.11.0 - 2014-05-01

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [angular-ui/bootstrap#2503]
Hello, I am currently using Version: 0.11.0 - 2014-05-01,  the example for tabset shows a  unusual example of tabs generated dynamically from javascript via Angular  ng-repeat.  It also shows activating and deactivating tabs by setting an object property (active) in the $scope.tabs array.

In my case I have a complex real world usage and so I must declare the tabs in the markup with their contents and can not create them by simply using ng-repeat. 

I am finding that I can not select an active tab by setting the scope variable bound to "active", it simply does nothing,  here's my markup:

```
 <tabset>
        <tab heading="Edit template" active="templateTabActive" select="tabSelected('Template')">
           ...etc etc much more stuff in here....
        </tab>

        <tab heading="View" select="tabSelected('View')" >
            ...etc...more stuff
        </tab>

...etc... more tabs
```

In the script setting $scope.templateTabActive does nothing. 

Here's a plunkr (hopefully, it's my first):
http://plnkr.co/edit/DGlWKgEqEqAkadJNDtVr?p=preview

I also tried the following:

- binding to a property of a 'parent' object (i.e. active="something.templateTabActive") in case it had a problem with a single variable 

- toggling the value of templateTabActive instead of just setting it to true because I saw another bug with disabled that a user reported required that.

Should this work when you have to create the tabs in the markup one by one?

**Comment by wesleycho** [comment]
Closing as resolved by support.
