### ISSUE TITLE
Datepicker displays wrong week numbers

### ISSUE THREAD

**Issue by guenter-wolf** [angular-ui/bootstrap#2506]
The datepicker displays wrong week numbers if the starting-day is 0 (Sunday).
Please compare the week numbers of angularjs-ui bootstrap Inline Datepicker at:
http://angular-ui.github.io/bootstrap/
with the ISO 8601 conform week numbers at:
http://www.epochconverter.com/date-and-time/weeknumbers-by-year.php

The angularjs-ui datepicker displays e.g. for Tue Aug 19 2014 the week number 33,
but the ISO 8601 conform week number is 34.

The problem seems to be that the datepicker uses the first day of the row in the calendar grid to determine the week number of the corresponding row.
This leads to wrong results if the first day of the row is Sunday (which is the datepicker default starting-day).
According to ISO 8601 the week starts on Monday and ends on Sunday.
Consequently the datapicker will display for the week Sun Aug 17 - Sat Aug 23 the number of the week that ended on Sun Aug 17 and not the week that starts on Mon Aug 18.
However, please note that the Popup Datepicker at 
http://angular-ui.github.io/bootstrap/ displays the correct week number, since the startingDay is 1 (Monday).

Suggested Solution:
Use the day in the middle of the row to determine the week number of the corresponding row, i.e. replace in datepicker.js the line:
var weekNumber = getISO8601WeekNumber( scope.rows[0][0].date )
with:
var weekNumber = getISO8601WeekNumber( scope.rows[0][3].date )
This will display the correct week number regardless of whether the week display starts with a Sunday or a Monday.

**Comment by picodealion** [comment]
Since I had no idea of knowing when the adjustments would be made here I made a new PR that covers the issues that were still relevant: https://github.com/angular-ui/bootstrap/pull/3158. Starting day seemed to have already been fixed in the meantime.

**Comment by yuyokk** [comment]
Hey guys,

Do you have any updates on this bug? When do you plan to fix it?
Thank you!

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by picodealion** [comment]
@yuyokk I still have a PR outstanding for this, but as you can read in the comments I'm confused by the conflict in specs (must adhere to ISO standards vs must allow sunday as the week's first day). I don't know how to solve that, it seems more like a business decision to me than something code can easily fix.

https://github.com/angular-ui/bootstrap/pull/3158

**Comment by yuyokk** [comment]
@picodealion I see what you mean. I appreciate your answer. Thanks.

**Comment by LiamK** [comment]
Is there any way to get rid of that last week?  For example, in the last image above, the last row on the January 2016 calendar is not even January, it's February.

**Comment by jkevlorayna** [comment]
Replace this one 
![screenshot_70](https://cloud.githubusercontent.com/assets/16604050/21711171/4f7e7c30-d428-11e6-8855-78b2bd8761ad.png)
with this code 
![screenshot_71](https://cloud.githubusercontent.com/assets/16604050/21711172/4f878c1c-d428-11e6-857f-2d02b9a2540b.png)

on  ui-bootstrap-tpls.js

Think this one will solve your problem!

**Comment by chinchan** [comment]
wow. Thanks for this fix. I just make your code into more elegant looks. I just removed the index since it does not needed. Thanks.
![image](https://cloud.githubusercontent.com/assets/13248437/21712656/f2a7141e-d430-11e6-931d-75020734e5b0.png)

**Comment by jkevlorayna** [comment]
@chinchan  awesome !
