### ISSUE TITLE
Datepicker in Chrome parses in incorrect format

### ISSUE THREAD

**Issue by cdietze** [angular-ui/bootstrap#2508]
I configured the dateFormat for the German style: dd.MM.yyyy
Now when I enter "1.2." it gets parsed as 2nd of January. Expected is 1st of Febuary.

Another example that is pretty confusing for a user:
"1.02.2015" -> February 1st, 2015
"01.02.2015" -> January 2nd, 2015

I already browsed the code a bit and the cause is falling back to [new Date(viewValue)](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L512) which behaves very different across browsers.
Firefox: new Date("1.2.") -> undefined
Chrome: new Date("1.2.") -> Tue Jan 02 2001 00:00:00 GMT+0100 (CET)
Safari: new Date("1.2.") -> undefined

This can be reproduced using the [demo datepicker](http://angular-ui.github.io/bootstrap/).

I suggest to remove the fallback and to only rely on the DateParser that's part of bootstrap. Or at least to make the fallback optional.

**Comment by wesleycho** [comment]
Note, this is also related to #3159.  This should be fixed when #3417 is merged.

**Comment by karianna** [comment]
#3417 and #3159 were merged, so cloing this
