### ISSUE TITLE
interval = false should pause the carousel

### ISSUE THREAD

**Issue by webeau** [angular-ui/bootstrap#2512]
I am trying to implement a playPause toggle on my carousel on ng-click.  I noted that you $watch the interval value and thought that changing it to false would prevent it from cycling.   

The Bootstrap Carousel official documentation states that the interval, "...If false, carousel will not automatically cycle."

There is probably another way to toggle play-pause that I am not thinking of but setting the interval to false and resetting it to a number should work, too.

**Comment by wesleycho** [comment]
Closing as this appears to be fixed.
