### ISSUE TITLE
Bug : Conflict dropdown-toggle with ui-bootstrap.0.11.0.js

### ISSUE THREAD

**Issue by SamiraJafari** [angular-ui/bootstrap#2518]
I have a <a class="dropdown-toggle"> tag. The first time I click on it,it opens and then suddenly closes without allowing me to see its content. Except the first time it works correctly.I think it's because of conflict between dropdown-toggle and ui-bootstrap.0.11.0.js

**Comment by antoinepairet** [comment]
@SamiraJafari I am sorry but your plunkr is cluttered. I will close this issue for now. Feel free to reopen once you come up with a clear and minimal reproducible plunkr.
rgds
