### ISSUE TITLE
Please add controllerAs to modal.open

### ISSUE THREAD

**Issue by SekibOmazic** [angular-ui/bootstrap#2519]
After this line:
ctrlInstance = $controller(modalOptions.controller, ctrlLocals);

you could add something like this:
if (modalOptions.controllerAs) {
  ctrlLocals.$scope[modalOptions.controllerAs] = ctrlInstance;
}

**Comment by eranimo** [comment]
Can we get bindToController as well?

**Comment by antoinepairet** [comment]
@eranimo please create new issue with a reference to this one. thx
