### ISSUE TITLE
Datepicker doesn't open in Angular 1.2.20

### ISSUE THREAD

**Issue by jdscolam** [angular-ui/bootstrap#2522]
Good Afternoon,

I am using 1.2.20, and the date picker dropdown isn't opening when clicking in the text box.  This just started happening after I updated to version 0.11

-Jon

**Comment by JaggyGT** [comment]
Thank you jcarlson for your post! I too was trying to save code and just set the open variable in the html and couldn't figure out why it wouldn't work - that definitely needs to be documented!

**Comment by wesleycho** [comment]
I am closing this PR as we do not support Angular 1.2 anymore (& it is too old).
