### ISSUE TITLE
modal call function inside tab 

### ISSUE THREAD

**Issue by wkjesus** [angular-ui/bootstrap#2526]
hi, i have an issues when i wrap  a ui bootstrap modal with tab inside,

http://plnkr.co/edit/TXBAHvAAnB8xaWoD2dfB?p=preview

when close a modal it fires tabselected automatically.  and i dont know why. and it fires
n times like many tabs are created.

i dont know if some one else have same situation or have a fix to this. what i do is prevent keypress, and make my own close, with ui-keypress call dismiss event.

hope some help thx.

**Comment by BobbieBarker** [comment]
Please test against the latest version and reopen if this is still an issue.
