### ISSUE TITLE
Error: [$compile:ctreq] Controller 'accordionGroup', required by directive 'accordionTransclude', can't be found!

### ISSUE THREAD

**Issue by paulflo150** [angular-ui/bootstrap#2528]
Hello,
Placing the accordion inside a kendo sortable list and dragging it throws several of these exceptions:

here is a codepen demonstrating the issue: http://codepen.io/anon/pen/zsioq

Error: [$compile:ctreq] Controller 'accordionGroup', required by directive 'accordionTransclude', can't be found!
http://errors.angularjs.org/1.2.18/$compile/ctreq?p0=accordionGroup&p1=accordionTransclude

Error: [$compile:ctreq] Controller 'accordionGroup', required by directive 'accordionHeading', can't be found!
http://errors.angularjs.org/1.2.18/$compile/ctreq?p0=accordionGroup&p1=accordionHeading

Any way to get this to work without any exceptions?

Thanks,

**Comment by rvanbaalen** [comment]
Try again with the latest UI Bootstrap 0.13.0. 

This seems like a support question on how to integrate to different libraries. Accordion without third party libraries is working just fine.

**Comment by linslin** [comment]
Accordion HTML markup changed from Version 13.x.x to 14.x.x. I recommend to take a look at versioned docs e.g. http://angular-ui.github.io/bootstrap/versioned-docs/0.13.2/. Cheers

**Comment by icfantv** [comment]
I would recommend upgrading to the latest UIBS version or waiting a little longer until 1.0 is released making sure to go through the CHANGELOG to ensure you address any and all relevant breaking changes.
