### ISSUE TITLE
Dropdown module is missing from "create a build".

### ISSUE THREAD

**Issue by wli** [angular-ui/bootstrap#2529]
Repro:

1. Click on create a build on this page: http://angular-ui.github.io/bootstrap/
2. Select only the "dropdown" module.
3. Observe that the files it generates are pretty much empty. They contain just this:
angular.module("ui.bootstrap", ["ui.bootstrap.tpls", "ui.bootstrap.dropdown"]);
angular.module("ui.bootstrap.tpls", []);

URL it tries to download: http://50.116.42.77:3001/api/bootstrap/download?modules=dropdown&

**Comment by Delapouite** [comment]
This issue seems to be fixed. 

I reproduced the steps described by @wli and the generated custom build contains the dropdown code as expected.

@derzwen do you confirm?

**Comment by karianna** [comment]
Will close for now - can be reopened if one of the OPs comes back.

**Comment by wli** [comment]
Works for me - thanks!
