### ISSUE TITLE
ngModel value change doesn't trigger formatter

### ISSUE THREAD

**Issue by seanmcilvenna** [angular-ui/bootstrap#2537]
I have a typeahead that lists items from an array. I use the formatter to properly format each item for display. I also have an on-select to change the ngModel value appropriately when an item is selected.

The problem I have, is I am allowing the user to dynamically add items to the array. When the user does that, I am trying to auto-select the new item from the array in the typeahead.

AFTER the new item is added to the array, the ngModel is updated with the appropriate value, but the typeahead does not detect the change and call the formatter to update the display within the typeahead.

Can anyone tell me what's wrong here?

**Comment by BobbieBarker** [comment]
Please test against latest version of angularJS and this project and reopen if it is still an issue.
