### ISSUE TITLE
Improve documentation on datepickerConfig's init-date

### ISSUE THREAD

**Issue by nharraud** [angular-ui/bootstrap#2538]
The documentation of DatePicker states "All settings can be provided as attributes in the datepicker or globally configured through the datepickerConfig". It also gives example of overriding options "formatYear" and "startingDay" with simple strings and integers.
I tried doing the same with the initDate option in multiple ways (string, integer, Date, scope attribute name) before digging in the code and seing that it uses "$scope.$parent.$eval(...)" and needs a scope path to the variable. In my case the path is $parent.$parent.initDate because the field is in a form. It's quite difficult to find this solution by accident. Maybe a hint in the documentation could help?

Thank you for your work.

**Comment by wesleycho** [comment]
I think problems with initDate should be fixed as a result of 98e2bdfc8b4dd108acdf3fac75a795675889bbc7 .  Let us know if this is not the case and this issue can be reopened.
