### ISSUE TITLE
Dynamic "max" value of progress bar

### ISSUE THREAD

**Issue by Tomino2112** [angular-ui/bootstrap#2545]
Hi,

After some debugging I noticed that progressbar doesn't support dynamic value for "max" parameter. It creates issue in my application when I create progress bar as follow:

    <progressbar max="page.pull_interval" value="(page.pull_interval-countDown+0.5)"></progressbar>

*Please don't pay much attention to the "value" attribute.

But at the creation time of progressbar the value of page.pull_interval is undefined. The "page" value is loaded from API, so the value is there few ms after. 

Would be great if the "max" attribute could keep binding so it could be changed dynamically.

**Comment by idanb11** [comment]
:+1:

**Comment by chrisirhc** [comment]
Resolved via #3273 (7ccff028ff5ed19af63d9cf1f5e078223924f3a0)
