### ISSUE TITLE
when datepicker opening,it's focused,please do not this,ok?

### ISSUE THREAD

**Issue by bondli** [angular-ui/bootstrap#2546]
var focusElement = function() {
    $timeout(function() {
      //self.element[0].focus();
    }, 0 , false);
  };

**Comment by stephanie-dm** [comment]
+1

**Comment by stephanie-dm** [comment]
Will this issue ever get fixed? The input field losing focus is a major problem for us, users always have to click twice if they want to type a date in the input field. It would be great if this was configurable...

**Comment by wesleycho** [comment]
Nothing is stopping anyone from opening a PR from being opened fixing this if it is desired - there are other much higher priority issues in need of tackling though, which is likely why there hasn't been any movement on this.

**Comment by stephanie-dm** [comment]
Thanks for the fix!
