### ISSUE TITLE
Datepicker is-open issue with ng-focus

### ISSUE THREAD

**Issue by Kevlys** [angular-ui/bootstrap#2548]
Hi,

When I do :

`<input type="text" is-open="date_open" ng-focus="date_open = true" datepicker-popup="MM/dd/yyyy" ng-model="myDate" />`

I have the following error in the console :`$apply already in progress`

see http://plnkr.co/edit/ZEvAW1v033aaEBFfiytF

If I use `ng-click`, it works.

The error seems to be caused by the line 1503 :`element[0].focus();`

PS : An option to (re)enable the automatic opening  would be appreciate :)

**Comment by wesleycho** [comment]
This issue looks fixed in `master`, as can be seen [here](http://plnkr.co/edit/HqWJWNy9rN0T4dfkrOWC?p=preview).
