### ISSUE TITLE
Provide a way to detect opening start and success of a modal

### ISSUE THREAD

**Issue by nanocom** [angular-ui/bootstrap#2549]
Hi,

My app currently displays a spinner when angular is loading templates and stuff (I do it by listening to the '$stateChangeStart'/'$stateChangeSuccess' events).
When I open a modal, it takes a certain time to download the modal template: I would like to track when a modal is starting to be opened and when it is successfully opened, so that I can show and hide the spinner accordingly.
I am aware of the $modal.open({...}).opened promise, but I would like to be able to catch all modal openings in one place.
For instance I would like to be able to do this:

``` javascript
$rootScope.$on('$modalOpenStart', function() { ... });
$rootScope.$on('$modalOpenSuccess', function() { ... });
$rootScope.$on('$modalOpenError', function() { ... });
```

**Comment by rinatio** [comment]
Is it possible to trigger [default bootstrap events](https://github.com/angular-ui/bootstrap/issues/3247)?
