### ISSUE TITLE
Dangling typeahead popup in case of typeahead-append-to-body="true"

### ISSUE THREAD

**Issue by kdekooter** [angular-ui/bootstrap#2551]
As demonstrated here: http://stackoverflow.com/questions/25108068/angular-bootstrap-typeahead-append-to-body-stuck/ the popup does not close when the "parent" input field is gone when moving to a different view.

The quick and dirty fix would be to explicity remove the popup from the DOM on destroy of the scope.

      originalScope.$on('$destroy', function(){
        $document.find('[id^=typeahead]').remove();
        $document.unbind('click', dismissClickHandler);
      });

**Comment by rvanbaalen** [comment]
Can you provide a plunkr with the latest UI Bootstrap 0.13.0 to reproduce this problem?

**Comment by icfantv** [comment]
Closing as this is working correctly with the latest versions of both Angular (1.4.7) and Angular UI Bootstrap (0.14.3).
