### ISSUE TITLE
Tooltip not maintaining placement with fixed position element

### ISSUE THREAD

**Issue by sgarbesi** [angular-ui/bootstrap#2560]
If an element that contains a tooltip has a fixed position, the tooltip doesn't maintain it's placement in correlation to the element when you scroll the page.

**Screenshot:**

![](http://cl.ly/image/0k1P1N1Q0y3W/Image%202014-08-07%20at%204.32.27%20PM.png)

**Comment by dmitriz** [comment]
Is this a bug? Any jsbin reproducing it?

**Comment by rvanbaalen** [comment]
Please check if this is still an issue in UI Bootstrap 0.13.0 and provide a plunkr reproducing the problem.
Not sure if this can be fixed at all since fixed position elements can be a whole different ball game.

**Comment by wesleycho** [comment]
This is likely an old issue that has been fixed with the various refactors that have gone into the tooltip.

If this is still an issue, please open a new one with a reproduction if possible.
