### ISSUE TITLE
feature: save format

### ISSUE THREAD

**Issue by zackarychapple** [angular-ui/bootstrap#2563]
rather than having to parse a date before save, a save format would be a very nice attribute to have.

datepicker-saveFormat="MM/dd/yyyy" would actually bind that format of the date to the model.

**Comment by wesleycho** [comment]
Something like this would be a step in the right direction - currently the datepicker needs to be untangled from its hard dependency on the Date constructor.

**Comment by wesleycho** [comment]
Thinking about this, we would rather this option be on the user's side, as adding an extra configuration value and $watcher adds more complexity and performance pressure on the datepicker. We also would have a difficult time predicting use cases for the dates.

Closing as won't support.
