### ISSUE TITLE
Feature: Typeahead match inside search box

### ISSUE THREAD

**Issue by bjornasm** [angular-ui/bootstrap#2570]
Can we have an option to display the first match (matches[0]) inside the search box, as you'd find in the Typeahead.js demo: http://twitter.github.io/typeahead.js/ (when searching for bower)

**Comment by wesleycho** [comment]
For reference to anyone interested in implementing this - how this works is that a read only input is positioned in the same location as the regular input. This input has its value filled on focus of the typeahead input.

This would be a cool feature, but it may require the user to style it appropriately.
