### ISSUE TITLE
pagination current page is always 1

### ISSUE THREAD

**Issue by yao23** [angular-ui/bootstrap#2571]
I click any of the pages, the parameter currentInvalidProductPage is always 1, welcome for any idea or suggestion, thanks in advance!

Code: 

Jade (a template to generate HTML):

<pre>
block content
    div(ng-controller="CsvProductController", ng-init="init(#{campaignId})")
        h1.pageTitle Csv Products
        strong Invalid Products
        div(ng-if="invalidCsv.length")
            table.table.table-hover
                tr
                    th Name
                    th Product ID
                    th SKU
                tr.product(data-ng-repeat="csvProduct in invalidCsv")
                    td {{ csvProduct.product.name }}
                    td {{ csvProduct.product.partnerId }}
                    td {{ csvProduct.product.sku }}

                pagination(ng-model="currentInvalidProductPage", total-items="totalItems", items-per-               page="numPerPage", ng-change="changeInvalidProductPage()", max-size="pageRange")
</pre>

HTML:

<pre><code>
<ul class="pagination ng-isolate-scope ng-valid ng-dirty" ng-model="currentInvalidProductPage" total-items="totalItems" items-per-page="numPerPage" ng-change="changeInvalidProductPage()" max-size="pageRange">

  
  <li ng-if="directionLinks" ng-class="{disabled: noPrevious()}" class="ng-scope"><a href="" ng-click="selectPage(page - 1)" class="ng-binding">Previous</a></li>

  <li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number)" class="ng-binding">13</a></li>

........

<li ng-repeat="page in pages track by $index" ng-class="{active: page.active}" class="ng-scope"><a href="" ng-click="selectPage(page.number)" class="ng-binding">22</a></li>

  <li ng-if="directionLinks" ng-class="{disabled: noNext()}" class="ng-scope"><a href="" ng-click="selectPage(page + 1)" class="ng-binding">Next</a></li>
  
</ul>
</code></pre>
Controller(Angular):
<pre>
  $scope.currentPage = 1;
  $scope.currentValidProductPage = 1;
  $scope.currentInvalidProductPage = 1;
  $scope.numPerPage = 20;
  $scope.totalItems = 100000;
  $scope.pageRange = 10;

  $scope.changeInvalidProductPage = function() {
    console.log('current invalid product page: ', $scope.currentInvalidProductPage);
  };
</pre>

**Comment by RoyLING** [comment]
I had ran into the same issue with use of either `ng-if` or `ng-include`, the root cause is these directives create new scope, the specified `ng-model` binding is only effective in that scope.

BTW, @yao23 's solution is really good, thanks!

**Comment by deltreey** [comment]
same problem, same solution.  switch wrapper div's ng-if to ng-show.  Not sure I understand why ng-if makes a new scope.

**Comment by DrHelmut** [comment]
got the same issue, it's about time to fix that or specify the limitation in the doc! ;)
thx for the tip, it works with ng-show :dancers:

**Comment by GUSCRAWFORD** [comment]
my paginator is in a modal, I set the model and page counts on the modal scope, what gives why always page 1?

**Comment by GUSCRAWFORD** [comment]
### template.html
Page is always 1
```
<div class="modal-header">
    <h3 class="modal-title">{{$parent.helpName}}</h3>
</div>
<div class="modal-body">
    Page {{currentPage }} of {{totalItems}}
    <pager total-items="totalItems" ng-model="currentPage"></pager>
    <div data-ng-show="page.pageNumber == viewingPage" data-ng-repeat="page in $parent.helpPages">
        <ul tabset typeof="pills">
            <li tab data-ng-repeat="subPage in page.pills" data-heading="{{subPage.tabTitle}}">
                <div class="panel panel-default">
                    <div class="panel-body" style="overflow:auto;" data-ng-bind-html="subPage.pillDiv">
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>
```

### controller.js
Unless I'm missing something basic, this is an issue.

My first level $scope is passed into the controller for a directive.
```
$scope.helpModal = $modal.open({
                            scope:$scope, controller:function ($scope, $sce) {
                                $scope.currentPage = 1;
                                $scope.totalItems = $scope.$parent.helpPages.length;
                                for (var P = 0; $scope.$parent.helpPages[P]; P++) {
                                    $scope.$parent.helpPages[P].pageNumber = P+1;
                                    for(var p = 0; $scope.$parent.helpPages[P].pills[p]; p++) {
                                        if (typeof $scope.$parent.helpPages[P].pills[p].pillDiv == "string") // this string needs to be trusted once
                                            $scope.$parent.helpPages[P].pills[p].pillDiv = $sce.trustAsHtml($scope.$parent.helpPages[P].pills[p].pillDiv);
                                    }
                                }
                            },
                            templateUrl:'app/steps/templates/helpOverlay.html',
                            size:'lg'
                        });
```

**Comment by rvanbaalen** [comment]
@GUSCRAWFORD dont hijack closed issues and ask your questions on StackOverflow please.
