### ISSUE TITLE
datepicker popup size is not adjusted

### ISSUE THREAD

**Issue by agdev** [angular-ui/bootstrap#2572]
Hi,
I am using datepicker inside a tab, when popup is opened it is not adjusted to available space.
See jsfiddle:http://jsfiddle.net/agcsi/dvssnrrv/8/
Click to Settings tab and click on calendar button, you'll see popup is not fully shown.
Is there a way around it or 
can popup's width be the same as input's width or 
or can popup's width be set or
can popup overflow?

Thank you.

**Comment by rvanbaalen** [comment]
Example not working. Please provide a working plunkr.

**Comment by BobbieBarker** [comment]
Closing, no follow up over a long period of time. Will reopen if a plunkr is submitted that demonstrates this is still an issue.
