### ISSUE TITLE
[FR] change popover size (min, max)

### ISSUE THREAD

**Issue by ArdentZeal** [angular-ui/bootstrap#2573]
Hello I am using the jbruni fork of angular-ui-bootstrap to put custom html template into a popover

I want to achieve a Facebook-like notification feed.

![screen shot 2014-08-13 at 14 50 08](https://cloud.githubusercontent.com/assets/5508364/3905536/ec700854-22e8-11e4-8f94-f1d0548b33b4.png)
.

This works pretty well, but the size of the popup seems to be hardcoded somewhere. Can we get the options to change that? Is it already possible and i missed the documentation?

Kind Regards

**Comment by e-cloud** [comment]
i think it can be optionally to add a class to the popover wrapper for user costomization
