### ISSUE TITLE
Date Picker Binding is different between angular-bootstrap 0.10.0 and 0.11.0

### ISSUE THREAD

**Issue by f1ghtingfalcons** [angular-ui/bootstrap#2591]
I am writing a custom date range directive for an app and I noticed that the date picker in version 0.11.0 doesn't bind to the model like it did in 0.10.0.

Here is my code with angular-bootstrap version 0.10.0:

 http://jsfiddle.net/f1ghtingfalcons/3wakgfm1/1/

Here it is again, but the version is now 0.11.0:

http://jsfiddle.net/f1ghtingfalcons/t947zb6c/3/

Notice how the date-picker no longer opens when you click on the text input box. The date picker also no longer defaults to the date displayed in the box. Instead it always defaults to the current date. Is there a new feature that I am missing in the new version? or was this broken between releases?

**Comment by BobbieBarker** [comment]
Please retest against the latest versions of angularJS and ui-bootstrap.

**Comment by f1ghtingfalcons** [comment]
Appears to be fixed in the most recent versions of those code repositories: http://jsfiddle.net/t947zb6c/4/

**Comment by wesleycho** [comment]
It should be noted that there is now a `is-open` attribute that is supposed for programmatically toggling the datepicker, so one can use ng-click.
