### ISSUE TITLE
IE11 : DatePicker sometimes displays date scrolled with an odd margin above it

### ISSUE THREAD

**Issue by DumboJet** [angular-ui/bootstrap#2603]
I am not sure when this happens in general.
In my case, I have made a wrapper directive that creates a field with a pop-up datepicker (I wonder why your lib doesn't provide this out of-the-box).
I change the value of the datepicker, that triggers some data retrival from the server and the result is this (some of the times):

![dp1](https://cloud.githubusercontent.com/assets/8492662/3967621/ea853440-27ae-11e4-8b41-698fce3eafba.PNG)

I have tried searching for changes in the CSS/HTML (if any), but I couldn't locate any yet.
When I hit the 'End' key on the keyboard (inside the input) the caret goes on an empty line above the date.
So, it seems this is probaly an issue with ~~the formatting of the date or sth (it adds newlines for some reason?) or with~~ the content overflow.
I see now that the value of the input has no new-lines in it.

(I am just reporting this in case you have sth on your mind that may help me or others with similar problems or just to make you have this issue on your mind. I don't necessary expect a solution.)

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.

**Comment by wesleycho** [comment]
This can be reproduced on the homepage, even in Edge.

This actually is a Bootstrap CSS issue in IE, as it looks like the MS browsers are not respecting the padding. Removing the padding for the `.form-control` date input fixes this issue.
