### ISSUE TITLE
Alternative to the HTML <select> element

### ISSUE THREAD

**Issue by jrief** [angular-ui/bootstrap#2607]
I would like to contribute an alternative to the built-in HTML ``<select>`` element.
Please check my working  prototype at http://plnkr.co/edit/t1Hq4GruKMBRymIBbd71?p=preview
(it is self documented).

I also believe that it fits into this project:
* the directives are in pure AngularJS, without any dependencies on any external JavaScript library; the only dependency is bootstrap CSS and its markup structure;
* the directives is html-agnostic and its only template can be loaded from an external source
* the directives manipulate DOM structure at a minimum level

I'll add Jasmine based unit tests to the example project.

Moreover, since angular-strap already contains a similar, but less feature rich directive, this repository would be a perfect fit for it.

**Comment by rvanbaalen** [comment]
There are already plenty of alternatives for <select> out there. Even from the Angular UI team see our other repo's.

**Comment by jrief** [comment]
@rvanbaalen Can you please point me on one of those. [angular-multi-select](http://isteven.github.io/angular-multi-select/#/main) is certainly not one of these, considering its code quality.

In the meantime I released my own [package](http://jrief.github.io/angular-bootstrap-plus/) in order to get this up and running. Adding something such as ``ng-option`` is not an option, because I want to be able to style the content. In a current project, I even add other Angular modules as selectable options.

**Comment by rvanbaalen** [comment]
It's not that hard to click on Angular UI above and search for 'select'; you'll end up with this repo:

https://github.com/angular-ui/ui-select

From your new website:
> Apparently the UI Bootstrap team wants to follow the same path as the Angular Strap team.

What do you mean by that?

**Comment by jrief** [comment]
OK, now that I saw the example code, things got clearer.
I wrote my first implementation in July/August 2014 and was not aware of angular-ui/ui-select then.

angular-strap offers a ``<select>`` element, but it was not possible to style the content, when I evaluated it.

**Comment by csakbalint** [comment]
@rvanbaalen It's not that hard to see the numbers of ui-select's pull-request and issues. Ui-select is not uptodate and has a lot of css, js bugs.
