### ISSUE TITLE
Dropdown scroll not working using key up/down

### ISSUE THREAD

**Issue by mehmedju** [angular-ui/bootstrap#2608]
Hi there,

I used angular dropdown in my project with scroll.
This is achieved adding class :.

typeahead-directive-list {
overflow-y: auto;
overflow-x: auto;
}

Html is the following:
   < ul class="dropdown-menu typeahead-directive-list">
            < li data-ng-repeat="item in items" >
     {{item.name}}
            < /li>
        < /ul>

So, how i can move through list of these items using key up/down:

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.

**Comment by javacowboy** [comment]
Here is a plunkr using Angular 1.3 and UI Bootstrap 0.13 that shows the issue.
http://plnkr.co/tSe0ZKzveRoU2xXGS5V9

**Comment by wesleycho** [comment]
Updated the Plunker [here](http://plnkr.co/edit/MlQGXLix6ajD30Om4bb7?p=preview).

PRs are welcome for fixing this.

**Comment by wesleycho** [comment]
Closing, as this appears to already be fixed as can be seen [here](http://plnkr.co/edit/P8ePRQaMGZPRVdfJ49qE?p=preview).

**Comment by roded** [comment]
Any idea on how to get this working with uib-typeahead?

**Comment by javacowboy** [comment]
@roded here was my workaround code before the issue was fixed.  I haven't tried it with uib-typeahead.

/**
	 * A workaround for scrolling a typeahead list using the keyboard arrow keys.
	 * Remove when Angular UI fixes https://github.com/angular-ui/bootstrap/issues/2608
	 */
	.directive('myTypeaheadArrowKeys', [function() {
		//TODO: can we get these pixel heights at runtime?
		var optionStyleHeight = 26;
		var dropdownStyleHeight = 200;
		var padding = 10;
		var addKeyDownHandler = function(scope, element) {
			element.on('keydown keyup', function(event) {
				if(event.which === 38 || event.which === 40) {//up or down key
					element.parent().find('ul.dropdown-menu')[0].scrollTop = (element.parent().find('ul.dropdown-menu li.active').index()) * optionStyleHeight - dropdownStyleHeight + optionStyleHeight + padding;
				}
			});
			scope.$on('$destroy', function() {
				element.off('keydown');
				element.off('keyup');
			});
		}
		return {
			link: function(scope, element, attr) {
				addKeyDownHandler(scope, element);
			}
		}
	}])

**Comment by roded** [comment]
@javacowboy thanks, does what it's supposed to.
Here's an example if the issue with uib-typeahead:
http://plnkr.co/edit/gBiXyN7tOS1qJAQG4m20?p=preview

**Comment by gandaldf** [comment]
+1 for roded
