### ISSUE TITLE
is-disabled doesn't grey out heading when using <accordion-heading>

### ISSUE THREAD

**Issue by jcapalbo** [angular-ui/bootstrap#2612]
When using <accordion-heading> for the header, is-disabled="true" will not grey out the heading when the accordion group is disabled.  Functionally it is disabled but a user wouldn't know.

Plunker: http://plnkr.co/edit/IjFFumF1aVKyWuDTrf6Z?p=preview

**Comment by icfantv** [comment]
This is working as expected with latest version of libraries:  please see [this plunker](http://plnkr.co/edit/IjFFumF1aVKyWuDTrf6Z).  Closing as fixed.
