### ISSUE TITLE
min-mode doesn't work with datepicker popup

### ISSUE THREAD

**Issue by Zacharias3690** [angular-ui/bootstrap#2618]
fix was pushed for datepicker-mode on popup in #2180, but min-mode still doesn't work in 0.12.0.

because 0.12.0 isn't available on plunker, here's my markup for reference

    <input type="text" class="form-control" 
                                datepicker-popup="MMMM yyyy" 
                                datepicker-mode="'month'" 
                                min-mode="'month'" 
                                ng-model="vm.endDate" 
                                is-open="endOpen" 
                                ng-click="endOpen=true" />

**Comment by kannajune** [comment]
thanks suksit 
its working well

**Comment by davidhantson** [comment]
I'm experiencing the same issue as johncronan,
any news on this? I really need to change the minMode on the fly, I have some graphs depending on it.
Thanks for the nice work on the component though, it really saves my day.

**Comment by prettycode** [comment]
+1 `min-mode` isn't respected, whether it's specified as attribute or in `datepicker-options` attribute value object.

**Comment by Slimmmo** [comment]
The min-mode problem is very odd. Would love a fix.
http://plnkr.co/edit/CoqkFvOM7GGNPHzb3iGq?p=preview
Thanks.

**Comment by rvanbaalen** [comment]
Feel free to submit a PR, @Slimmmo

**Comment by Slimmmo** [comment]
I think I've fixed the issues in this thread with my [PR](https://github.com/angular-ui/bootstrap/pull/3843). It fixed my problem at least. Enjoy.

**Comment by urvashi-bhatt** [comment]
It is Possible to set [min-mode="week"](url) ?
