### ISSUE TITLE
No indication that a bower install in not enough

### ISSUE THREAD

**Issue by stephaneeybert** [angular-ui/bootstrap#2622]
It would be nice if there was a note explicitly stating that the css file needs to be added in the index.html file. The bower install does not take care of this. The bower install only inserts the js include statement.

**Comment by stephaneeybert** [comment]
I'm coming back to this, stumbling on the missing css resource, biting me. I can't see anything about it in the doc now.

**Comment by stephaneeybert** [comment]
What was needed was the following command:
bower install bootstrap -s
And adding the following statement in the app/index.html file:
<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css">

**Comment by goldcaddy77** [comment]
@stephaneeybert - You actually need to `bower install angular-bootstrap`.  I've put in a PR for this: #3521.  Then you just need to include a script tag referencing "angular-bootstrap/ui-bootstrap-tpls.js"
