### ISSUE TITLE
the background move a little when opening a modal.

### ISSUE THREAD

**Issue by jixiangcn** [angular-ui/bootstrap#2631]
when I click button to show a "modal", the background move a little then move back, which is not happened in bootstrap and uikit modal.

**Comment by kashesandr** [comment]
Faced with the same issue.

**Comment by TilmannBach** [comment]
issue can be seen even on the bootstrap-ui documentation website

**Comment by Foxandxss** [comment]
I am not able to reproduce it so I am not sure if this is stale or not. Please open an issue with a plunker if you think this is still an issue.

Thank you.

**Comment by j3ffb** [comment]
@Foxandxss This is still an issue, as @TilmannBach says, you can see it on the doco website at https://angular-ui.github.io/bootstrap/#/modal but make sure you are using a browser that consumes a scrollbar width on the page, like FF or Chrome on Windows.

**Comment by Foxandxss** [comment]
Ah, missed the windows part. I am using mac with this annoying scrollbars.

**Comment by NoelKennedy** [comment]
I get the same effect on OS X with Chrome (46.0.2490.80 (64-bit)) & Firefox (41.0.2)

**Comment by j3ffb** [comment]
@NoelKennedy this will depend on your settings in OSX. If scrollbar is visible on page load = you will see the bug

**Comment by TilmannBach** [comment]
Windows 10
* Edge: Ok
* IE 11: Ok
* Chrome 46: Bugged

**Comment by NoelKennedy** [comment]
@j3ffb Confirmed.  The screenshot is OS X settings (under General).  With 'Show scroll bars' set to 'Automatically....' the problem occurs.  If you set it to 'When scrolling' the problem does not occur.  


<img width="604" alt="screen shot 2015-10-23 at 16 47 09" src="https://cloud.githubusercontent.com/assets/545513/10698079/07a167ce-79a7-11e5-83bc-ee2b5da2026f.png">

**Comment by icfantv** [comment]
I'm not sure there's anything we can do here.

**Comment by stefan-dimitrov** [comment]
Maybe this suggestion will help with the problem: http://stackoverflow.com/a/20564773/915372 ?

**Comment by prasadrajandran** [comment]
Hello,

I don't know if this is still an issue for everyone but this should (hopefully) fix it:

CSS:

    html {
      overflow-y: scroll;
    }

That forces the scroll bar to be displayed at all times regardless of whether it's actually needed or not.

**Comment by bboyle** [comment]
@prasadrajandran that does stop the content from shifting, but it means the body can be scrolled while the modal is open, which feels wrong. I think we're all after a solution that's the best of both worlds -- scrolling is disabled, and content does not shift sideways.

**Comment by bboyle** [comment]
here is how bootstrap are measuring scrollbars to handle this issue: https://github.com/twbs/bootstrap/blob/master/js/modal.js#L259

**Comment by prasadrajandran** [comment]
@bboyle, I didn't that doing that would allow the body to be scrolled while the modal is open. Interesting.

I'm probably misunderstanding the actual issue because running this line:
`document.getElementsByTagName('html')[0].style['overflow-y'] = 'scroll';`

on this page https://angular-ui.github.io/bootstrap/#/modal gets rid of the shift for me.

Anyway, that's just my two cents on the issue.

**Comment by RobJacobs** [comment]
Seems this issue is isolated to having the content in an element with the 'container' class.  Using 'fluid-container' class or no container class and the content does not shift.  Container class css ends up looking like:

    .container {
        padding-right: 15px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
    }

With a width set to 750px based on a media query where container fluid does not set a width.  Rather than do a complex scroll measure and body pad, it might be better to go after sibling elements and remove width?

The modal window itself is shifting when the element that the modal is appended to (body) has it's scroll is set to hidden.  

I'm going to dig into this more, here is the [plunk](http://plnkr.co/edit/OxuPsRh54Njm8IUsub8L?p=preview) I'm using for testing.

**Comment by RobJacobs** [comment]
The [plunk](http://plnkr.co/edit/OxuPsRh54Njm8IUsub8L?p=preview) has been updated with a proposed fix.  This works on Chrome and Edge, but now breaks IE-11.  If that's a trade off we are willing to make, let me know and I will create a PR.  Changes are:

New function in $uibPosition service:

      /**
       * Provides the padding required on an element to replace the scrollbar.
       *
       * @returns {object} An object with the following properties:
       *     <li>**widthOverflow**: whether the the width is overflowing</li>
       *     <li>**right**: the amount of right padding on the element needed to replace the scrollbar</li>
       *     <li>**rightOriginal**: the amount of right padding currently on the element</li>
       *     <li>**heightOverflow**: whether the the height is overflowing</li>
       *     <li>**bottom**: the amount of bottom padding on the element needed to replace the scrollbar</li>
       *     <li>**bottomOriginal**: the amount of bottom padding currently on the element</li>
       *   </ul>
       */
      scrollbarPadding: function(elem) {
        elem = this.getRawNode(elem);

        var elemStyle = $window.getComputedStyle(elem);
        var paddingRight = this.parseStyle(elemStyle.paddingRight);
        var paddingBottom = this.parseStyle(elemStyle.paddingBottom);
        var scrollParent = this.scrollParent(elem);
        return {
          widthOverflow: scrollParent.scrollWidth > scrollParent.clientWidth,
          right: paddingRight + this.scrollbarWidth(),
          originalRight: paddingRight,
          heightOverflow: scrollParent.scrollHeight > scrollParent.clientHeight,
          bottom: paddingBottom + this.scrollbarWidth(),
          originalBottom: paddingBottom
         };
      },

Then in the modal - $modalStack.open function:

        if (!modal.scope.$$uibDestructionScheduled) {
          scrollbarPadding = $uibPosition.scrollbarPadding(appendToElement);
          if (scrollbarPadding.heightOverflow) {
            appendToElement.css({paddingRight: scrollbarPadding.right + 'px'});
          }
          $animate.addClass(appendToElement, modalBodyClass);
        }
        $animate.enter($compile(angularDomEl)(modal.scope), appendToElement);

and in the modal - removeModalWindow function:

        removeAfterAnimate(modalWindow.modalDomEl, modalWindow.modalScope, function() {
          var modalBodyClass = modalWindow.openedClass || OPENED_MODAL_CLASS;
          openedClasses.remove(modalBodyClass, modalInstance);
          appendToElement.toggleClass(modalBodyClass, openedClasses.hasKey(modalBodyClass));
          if (scrollbarPadding && scrollbarPadding.heightOverflow) {
            if (scrollbarPadding.originalRight) {
              appendToElement.css({paddingRight: scrollbarPadding.originalRight + 'px'});
            } else {
              appendToElement.css({paddingRight: ''});
            }
            scrollbarPadding = null;
          }
          toggleTopWindowClass(true);
        }, modalWindow.closedDeferred);

**Comment by wesleycho** [comment]
@RobJacobs do you have any idea whether you could come up with a solution for Edge/IE? Is there something wrong with the width calculation in that situation?

**Comment by RobJacobs** [comment]
@wesleycho To summarize:

The difference has to do with browsers whose scrollbars overlay (Edge/IE) vs render inline (Chrome/Firefox). The content shift in Chrome is because the browser is trying to center align elements with a fixed width and left/right margins of auto.  I'm going to do some more digging to see what (or if) is the best way to detect this scenario.

**Comment by deeg** [comment]
@RobJacobs, @wesleycho, where did we leave off with this?

Should we attempt at looking to fix IE/Edge with Rob's solution? Should we be looking for a different solution all together?

**Comment by RobJacobs** [comment]
@deeg Sorry, I got side tracked.  The issue all stems from the .modal-open class that gets added to the body element which just sets overflow: hidden to kill scroll on the body.  If we could live with the scrollbar staying visible and use a scroll event on the modal backdrop element to stopPropagation, it would be a cleaner solution.

**Comment by deeg** [comment]
I guess I'm fine with that approach, but it would be different from how regular bootstrap handles it right?

@wesleycho, thoughts?

**Comment by RobJacobs** [comment]
After some more digging, it seems how TWBS measures the scrollbar width is flawed.  In IE/Edge, the html or body element scrollbars overlay, where in Chrome they render inline.  To get the ture scrollbar width for the html or body element, it needs to be calculated as:

$window.innerWidth - bodyElem[0].offsetWidth

rather than:

scrollElem[0].offsetWidth - scrollElem[0].clientWidth

Which correctly reports 0 for IE and Edge, 17 for chrome.  I added an isBody parameter to the scrollbarWidth function to determine which calc should be done.  I'm wondering if creating a new bodyScrollbarWidth function would be clearer instead?   The [plunk](http://plnkr.co/edit/OxuPsRh54Njm8IUsub8L?p=preview) has been updated with the fix.

**Comment by wesleycho** [comment]
Awesome find - I'm fine with that.

This should also be reported to the Bootstrap guys so they can gain the fruits of these findings.

**Comment by weijyewang** [comment]
Hi, I observe this issue occurs again on Chrome 57.0.2987.133 (64-bit), but it is working fine in IE11. I'm using ui-bootstrap-tpls-2.0.1, which should already contains the fixes above. 

Do you think that the latest chrome update breaks it again?

**Comment by amitdubey8888** [comment]
Use this code, May this can resolve your issue
body.modal-open{
width:100% !important;
padding-right:0 !important;
overflow-y:scroll !important;
position:fixed !important;
}

**Comment by TilmannBach** [comment]
@amitdubey8888 you code works and the background doesnt move now but it generates two scrollbars

see the screenshot

![image](https://user-images.githubusercontent.com/2125941/30032394-f3569bbe-9195-11e7-913a-d77c17fc3e39.png)

**Comment by amitdubey8888** [comment]
You can hide scrollbar also, by using this code

.modal{
           overflow-y: hidden !important;
}

**Comment by OlexandrPopov** [comment]
The issues is back in angular-ui 2.5.0. It can be reproduced on the demo page http://angular-ui.github.io/bootstrap/#!#modal
You can compare it with  angular-ui 1.3.1 where it's fixed http://angular-ui.github.io/bootstrap/versioned-docs/1.3.1/#/modal

**Comment by kuzinmv** [comment]
Moving the container a few pixels down when you open the modal happen if you have a < nav > section of fixed height, but tags contained inside this section a slightly higher. Make the height of internal tags to be less or equal than the height of the < nav > section and container  the shift effect will be lost.

![2017-12-28 10 06 34](https://user-images.githubusercontent.com/6621928/34400231-6d4723d0-ebb9-11e7-8a1a-cbfc7aad50af.png)

![2017-12-28 10 07 24](https://user-images.githubusercontent.com/6621928/34400234-7559ebfc-ebb9-11e7-8b03-e1801059d1b9.png)
