### ISSUE TITLE
Timepicker Input - 00

### ISSUE THREAD

**Issue by Gils14** [angular-ui/bootstrap#2639]
When a user tries to input "00" into the Timepicker minutes field, it only allows one "0" to be typed.  While the 0 does then revert to 00 when the field is no longer in focus, this was frustrating for some of our users. The object we used is below

<code>&lt;timepicker class="time-picker" ng-model="order.appointment.datetime" hour-step="1" minute-step="15"required&gt;&lt;/timepicker&gt;</code>

**Comment by wesleycho** [comment]
A PR for optional support for this would be welcome.

**Comment by chrisirhc** [comment]
Just wondering, after merging #3533, is there still any action needed here for this issue?

**Comment by karianna** [comment]
@Gils14 - Can you please try master and reopen if needed.
