### ISSUE TITLE
embedding a google maps iframe in accordion-group causes weirdness

### ISSUE THREAD

**Issue by sean-stanley** [angular-ui/bootstrap#2643]
Strange issue just came up. I found that adding a googlemaps iframe to an accordion group body resulted in the zoom of the map being set to 0 and center being displaced.

Here is a plunk of the issue: http://plnkr.co/edit/AsyrvTNzmpC86RpRmwob?p=preview

Not entirely sure what would cause this but I hope it's simple to tweak. Maybe there is simply a better way to achieve the desired result?

**Comment by anromerodg** [comment]
Did you finally solve this?

I added a class to the container of the accordion and changed the display none for display block and overflow hidden.

It works!

.myClass .collapse {
    display: block;
    overflow: hidden;
}

**Comment by sean-stanley** [comment]
No actually I just stuck a link to the gmaps page instead. I will try that class though when I get the chance hopefully in the next couple of weeks and post if it works. I don't mind if the issue is closed now or after I reply. Maybe a codepen example or something would help make it an 'Official' solution though and then close the issue?
