### ISSUE TITLE
Accordion: When generating accordion groups via ng-repeat I'm unable to use is-open for the first group

### ISSUE THREAD

**Issue by developer10** [angular-ui/bootstrap#2648]
I'm using ng-repeat to generate all my accordion groups. If I apply is-open="status.isFirstOpen" to the accordion group (the only one, because it's a loop) obviously all my groups will get the same attribute while only the first one is supposed to.

I know there's "$first" property under ng-repeat directive but I'm not sure how to apply it in this case. I also tried using ng-if by duplicating the accordion group declaration - one for generating the $first group and another for "non-first" groups. Didn't work.

Any advice? Thank you!

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
