### ISSUE TITLE
Button dropdown not displaying anything with Bootstrap 3.2.0 and AngularJS 1.2.23

### ISSUE THREAD

**Issue by dcoraboeuf** [angular-ui/bootstrap#2649]
Hi,

With version 0.11.0 of `angular-ui-bootstrap`, when using Bootstrap 3.1.1 and AngularJS 1.2.16, I have dropdown buttons which work fine.

When upgrading to AngularJS 1.2.23 and Bootstrap 3.2.0, those same dropdown buttons do not work any longer (I click on them and nothing happens).

The following Plunker shows the problem:
http://plnkr.co/edit/setHDt61PRCo91OJc8SX

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.

**Comment by wesleycho** [comment]
This seems to work perfectly fine as far as I can tell [here](http://plnkr.co/edit/SM9RJus262XzG5pi2Hv7?p=preview).
