### ISSUE TITLE
typeahead collection changes but it is not reflect to the list

### ISSUE THREAD

**Issue by ali-bugdayci** [angular-ui/bootstrap#2654]
Typeahead shows the results from the previous digest loop, and does not show the current ones:
(Can't use JSON_CALLBACK because of the apple service I am depending on,  so I am triggering typeahead through scope.$apply outside.)

Used within input tag with:
```
ng-change="search(searchStr)" ng-model="searchStr" 
typeahead="suggestion for suggestion in typeAheadResults" 
```

applying outside:
```
 scope.$apply(function() {
    scope.typeAheadResults = _.values(results);
  });
```

$scope.$watch shows that the scope is changing:
```
  $scope.$watch('typeAheadResults', function(neu, old){
    console.error("$watch typeAheadResults changes: " );
    console.error(neu);
  })
```

Check the console, where it writes the $watch results where it logs that collection changes, but it is not reflected into typeahead:
http://plnkr.co/edit/2MQuP2YUwaIZJjEVjdOz?p=preview

**Comment by rvanbaalen** [comment]
Please provide an updated plunkr and verify this is still an issue in Angular 1.3 with UI Bootstrap 0.13.

**Comment by wesleycho** [comment]
Closing due to lack of response & age - if this is still an issue, feel free to open another issue with reproduction based on a current version of UI Bootstrap.
