### ISSUE TITLE
Datepicker dateOptions don't seem to work when datepicker is wrapped inside a directive

### ISSUE THREAD

**Issue by pjfsilva** [angular-ui/bootstrap#2655]
I'm trying to use a datepicker (popup example in my case) inside one directive I made and pass it some dateOptions.
My problem is that it seems that when using the datepicker inside a directive the dateOptions don't work anymore. Using datepicker directly works OK.

Example: http://plnkr.co/edit/W71cz3

You can see on my example that the date picker works OK but with all the default options and ignoring my passed options.

On my debugging I can't really understand much why this doesn't work but it seems that the code from datePicker reading the options (1) runs before my directive link code so the datepickerOptions are empty.

(1)
```
var datepickerEl = angular.element(popupEl.children()[0]);
      if ( attrs.datepickerOptions ) {
        angular.forEach(scope.$parent.$eval(attrs.datepickerOptions), function( value, option ) {
          datepickerEl.attr( cameltoDash(option), value );
        });
      }
```

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by pjfsilva** [comment]
Why closed? this is a bug report not a need for help...

**Comment by rvanbaalen** [comment]
> My problem is that it seems that when using the datepicker inside a directive the dateOptions don't work anymore. **Using datepicker directly works OK.**

Seems like the datepicker is working but not for a specific use case you're following. Therefore, this is an implementation question ("How do I use the datepicker within my own directive") instead of a bug report.

**Comment by pjfsilva** [comment]
ok, I see your point, agreed.
