### ISSUE TITLE
Angular 1.3.0 rc0 causes datepicker to display initial date as unformatted string

### ISSUE THREAD

**Issue by byudaniel** [angular-ui/bootstrap#2659]
The behavior of $viewValue has changed in [this commit.](https://github.com/angular/angular.js/commit/1eda18365a348c9597aafba9d195d345e4f13d1e) Angular 1.3 rc0 sets $viewValue for dates as a string, so date formatting fails.

**Comment by nespapu** [comment]
Many thanks to @DaveWM and @meyerds!

**Comment by jmayday** [comment]
Thanks for this code. 
If someone could just explain me how exactly this works then it would be great. 

So, my question here is why <code>$viewValue</code> gets date like "Feb 17, 2015" and not in specified format? What's a kind of magic for me is that displayed value is in correct format, despite it differs from $viewValue. So, what is the role of $viewValue?

**Comment by slavafomin** [comment]
Hooray! ))

**Comment by rvanbaalen** [comment]
For anyone still using ~0.12 with Angular 1.3, this is a drop-in fix based on @bcronje's comment

```js
.directive('datepickerPopup', ['datepickerPopupConfig', 'dateParser', 'dateFilter', function (datepickerPopupConfig, dateParser, dateFilter) {
            return {
                'restrict': 'A',
                'require': '^ngModel',
                'link': function ($scope, element, attrs, ngModel) {
                    var dateFormat;

                    //*** Temp fix for Angular 1.3 support [#2659](https://github.com/angular-ui/bootstrap/issues/2659)
                    attrs.$observe('datepickerPopup', function(value) {
                        dateFormat = value || datepickerPopupConfig.datepickerPopup;
                        ngModel.$render();
                    });

                    ngModel.$formatters.push(function (value) {
                        return ngModel.$isEmpty(value) ? value : dateFilter(value, dateFormat);
                    });
                }
            };
        }]);
```

**Comment by neonexus** [comment]
Thank you so much for this simple fix @rvanbaalen!

**Comment by rvanbaalen** [comment]
You're welcome @neonexus :+1:

**Comment by harrychenca** [comment]
@rvanbaalen  Thanks! Works perfectly.

**Comment by BalajiTE** [comment]
Hi rvanbaalen,

Thank you for the fix, but for some reason it's not working for me. Here is how I am using it:

I am using AngularJS 1.3.14, ui.bootstrap.min.js 0.12.1 and ui.bootstrap-tps.min.js 0.12.1 versions

in my HTML, I have the datepicker-popup defined as below:

               <input type="text" class="form-control" name="txtDOB" placeholder="Date of Birth"
                          ng-model="dt1" ng-required="true" ng-change="CalculateAge()"
                          datepicker-popup="dd-MMM-yyyy"
                          is-open="opened" close-text="Close" datepicker-options="dateOptions"
                          show-button-bar="false" datepickerpopup readonly required />

I added the same code given by you as Directive. 

When I changed the date on form, ng-model value in ng-change function is still showing the un-formatted long date as string.

Can you tell me what I am doing wrong?

Thanks.

**Comment by rvanbaalen** [comment]
Please ask your question on StackOverflow. We dont have official Angular 1.3 support at the moment so it can basically be anything why its not working for you. Also, reproduce your problem in a plunkr so others can test and debug it. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by BalajiTE** [comment]
Sure Thank you.

**Comment by jmayday** [comment]
@BalajiTE prepare plunker showing the problem. Recently I successfully applied code fixes to get rid of unformatted initial dates problem. In case you want to look at it here's the plunker: http://plnkr.co/edit/HKALJPWWnpyU8nU8iAvX?p=info

**Comment by kodecraft** [comment]
just wanted to feedback that the issue of the datepicker displaying the date unformatted is occurring for angular v1.4 also and davewm's workaround fixes the issue...tks dave+meyerds

**Comment by alexbeletsky** [comment]
I'm having this issue on angular `1.4.3` as @kodecraft also mentioned. Are there any ideas how to workaround it?

**Comment by EdmundMai** [comment]
Here's my workaround using `angular.element`. Kinda hacky but works for me:

View:

        <input type="text"
        class="fromDate"
        datepicker-popup="MM/dd/yyyy"
        ng-model="custom_time_filter_begin"
        ng-focus="showFromCalendar = true"
        is-open="showFromCalendar"
        datepicker-options="datePickerOptions"
        ng-required="true"/>

        <input type="text"
        class="toDate"
        datepicker-popup="MM/dd/yyyy"
        ng-model="custom_time_filter_end"
        ng-focus="showToCalendar = true"
        is-open="showToCalendar"
        ng-required="true"/>
        <input id='custom-duration' class='btn duration-button' type='submit' value='Apply' />


Then in  my controller:

      fromDate = $filter('date')($scope.custom_time_filter_begin, "MM/dd/yyyy")
      toDate = $filter('date')($scope.custom_time_filter_end, "MM/dd/yyyy")
      angular.element(".fromDate").val(fromDate)
      angular.element(".toDate").val(toDate)


Hope it helps

**Comment by biswajit1** [comment]
I faced a related issue with date picker.
If I select a date from date picker, controller is getting date object.
But, I do not change date using date picker and let pre-populated date untouched, the controller is getting a string. And $filter('date') of angular was not working on string version of date.
But, good thing is that if we apply new Date() on both string or date, it returns a date.
And, we can apply the result to $filter('date') easily.
