### ISSUE TITLE
datepicker-mode and scope

### ISSUE THREAD

**Issue by robjames** [angular-ui/bootstrap#2660]
Because datepicker-mode (when being set via an attribute) is set to the scope, not the isolate scope of the datepicker itself, when you have multiple date pickers on the same page they will all change to the last set value.

Worse, when changing modes by selecting dates, they all change simultaneously. 

To combat this i have had to create a separate directive that wraps the datepicker in a new isolate scope.

Note: this doesn't happen when you don't set a datepicker-mode. In this case they work as expected and behave as individual datepickers.

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by robjames** [comment]
@rvanbaalen yeah, that doesn't help. I was highlighting more of a bug, and solution, than asking for help. You will find on SO people with similar issues.

**Comment by rvanbaalen** [comment]
Feel free to re-open and provide a plunkr reproducing this issue if it is still an issue. I'm currently triaging 400+ open issues to see which are outdated, which are invalid and which can be closed and I'm trying to give each individual issue all the attention it deserves. However sometimes issues like this one seem to be a request for help while instead they are actually bugs.

If you think you found a bug, please read [this](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug) and provide as much info as possible for us to reproduce it. That includes a plunkr.

**Comment by robjames** [comment]
Fair enough - thank you.
