### ISSUE TITLE
[popover] Trigger manually ?

### ISSUE THREAD

**Issue by monkeymonk** [angular-ui/bootstrap#2662]
Hi there, I'm trying to trigger a popover manually but I can't find how to do it...

```
<div popover="Lorem ipsum dolor site amet..."
                           popover-placement="top"
                           popover-append-to-body
                           popover-trigger="doPopover">popover here</div>
<span ng-mouseenter="doPopover = 'true'" ng-mouseleave="doPopover = 'false'">trigger here</span>
```

So the purpose is to trigger the popover when the mouse is over the span... but I dont understand what I have to do to succeed.

Thank you!

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
