### ISSUE TITLE
Typeahead Editable = false doesn't reset to field to valid after value is selected

### ISSUE THREAD

**Issue by chrislhardin** [angular-ui/bootstrap#2665]
In Angular 1.3 Beta 18, the Typeahead worked fine, but in rc.0, the typeahead field will not go back to being valid if the user selects a valid value from the list. Only by completely blanking out the value does the state correct itself.

**Comment by rvanbaalen** [comment]
@chrislhardin Can you please verify if this is still an issue with the latest AngularJS 1.3 release?

**Comment by wesleycho** [comment]
This currently looks valid, as can be seen [here](http://plnkr.co/edit/x2lHVztKlQNdYAjZX1CL?p=preview).

Closing as resolved.
