### ISSUE TITLE
Format not supported on datepicker-popup "MM.dd.yy"

### ISSUE THREAD

**Issue by ymitis** [angular-ui/bootstrap#2667]
This: datepicker-popup="MM.dd.yy"  throws the following error: 
TypeError: Cannot read property 'split' of undefined

It failing in the ui-bootstrap.tpls.js file on this line of code:

this.createParser = function(format) {
    var map = [], regex = format.split('');

I'm using the following scripts:
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.0/ui-bootstrap.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.0/ui-bootstrap-tpls.js"></script>

The same code works just fine in version: 0.10.0

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.

**Comment by MaxiSir** [comment]
http://plnkr.co/edit/tY7i7NO3CxGe3NKBVj2O?p=info

it works now with UI Bootstrap 0.13.
To test it, just downgrade the version of UI Bootstrap to 0.11

**Comment by wesleycho** [comment]
As this has been fixed for a while, I am closing this issue as old.
