### ISSUE TITLE
Carousel demo not working - image link broken

### ISSUE THREAD

**Issue by terrapin69** [angular-ui/bootstrap#2673]
This may seem trivial, but it's presumably not what's supposed to happen: the carousel demo at http://angular-ui.github.io/bootstrap/ appears to have a broken link to the first image, so in IE9 it shows a missing image icon, and in FF just a blank image. Slide 2 is showing as Slide 1. On ipad, can't slide away from the missing image.

**Comment by wesleycho** [comment]
This appears to have been fixed - closing as resolved.
