### ISSUE TITLE
Typeahead broken in angular 1.3.0-rc.1 (even worse, than since beta.11)

### ISSUE THREAD

**Issue by EvAlex** [angular-ui/bootstrap#2681]
Example (docs-based): http://plnkr.co/edit/jQSozNWRAbRtrGuOGxb4

Typeahead for states with flags has following bugs (some of them duplicate those reported in other issues, but the last one is new I guess):
* Selecting with mouse doesn't work (this appeared in beta.11 and is already reported in other issues)
* Selecting with arrow keys doesn't work too
* Flags icons not appearing
* Selected object is rendered as '[object Object]'

Just change angular version to 1.3.0-beta.9 and everything gets fine.

**Comment by rwillmer** [comment]
Could the OP confirm whether this is still broken now AngularJS 1.3 is released? (currently at 1.3.11)

**Comment by antoinepairet** [comment]
According to tests I just performed, using angular stable version 1.3.13, it works correctly. Here are the plunkers:
http://plnkr.co/edit/4i5qJYlyCrE4bWkvBV20?p=preview  - working  using 1.3.13
http://plnkr.co/edit/gmOcZlb1KOtQm7D34PZZ?p=preview - broken using 1.3.0-rc.0

**Comment by karianna** [comment]
In that case, closing (it's not unreasonable to expect people to be using an up to date version of Angular).

**Comment by jdforsythe** [comment]
The plunkr by antoinepairet for 1.3.13 is NOT working - at least in Chrome. Selecting with mouse or keyboard does not work. You can press Tab to select the first item in the list and it correctly sets the object to the model. You can select from the dropdown and it sets the object to the model. But mouse and arrow keys don't work (although clicking closes the list, it doesn't set the model). States with flags doesn't work either, and still doesn't work in 1.3.14.

**Comment by RevanProdigalKnight** [comment]
Another problem that I noticed beyond what @jdforsythe mentioned is that once you've selected a value, the model doesn't update when you make further changes to the text.

**Comment by wesleycho** [comment]
Closing this issue, moved keyboard/mouse issues to #3393.
