### ISSUE TITLE
Datepicker better support for mobile

### ISSUE THREAD

**Issue by ChenYongFang** [angular-ui/bootstrap#2682]
Is there a way , that a datepicker could open using code like modal . so we don't need to worry about position and better fit mobile . like this jQplug http://dev.jtsage.com/jQM-DateBox/

thanks.

**Comment by wesleycho** [comment]
This could be useful - PRs welcome!

**Comment by sibeliusseraphini** [comment]
+1

Check - https://github.com/niftylettuce/bootstrap-datepicker-mobile

**Comment by wesleycho** [comment]
I actually encountered having to style the datepicker in mobile today - this can completely be done on the user's side without much trouble, even with custom looks, so I am closing as a usage issue.

There is not too much we can do here from the library side that makes sense.
