### ISSUE TITLE
Time Picker: ISO standard for time-of-day allows value of 24:00

### ISSUE THREAD

**Issue by tfr888** [angular-ui/bootstrap#2685]
With respect to time of day, ISO standards allow both 00:00 and 24:00 values, to distinguish between "midnight earlier today" and "midnight tonight".   Let's say a bartender works the 7pm to midnight shift.  We might want to represent that in a work schedule as StartTime 19:00 and FinishTime 24:00, rather than 19:00 and 00:00.  PostgreSQL database, for example, adheres to the ISO standards in this regard, and allows both values; Microsoft SQL Server, on the other hand, does not follow the ISO standard. Would be convenient if the TimePicker would accept both values, and had an alternate mode that allowed for a 24-hour clock, such that 23:45 + 15 minutes = 24:00,  00:15 minus 15 minutes = 00:00.

**Comment by BobbieBarker** [comment]
As some one who did military service and lives my life by military time for years (To include work schedules that had me working from one day to the next through midnight). We used 00:00, no one uses 24:00. To the best of my knowledge cell phones display it as 00:00. I don't see any value in supporting 24:00.
