### ISSUE TITLE
Accordion: Can we control panel-XXX in accordion?

### ISSUE THREAD

**Issue by Tomino2112** [angular-ui/bootstrap#2686]
Hi,

It would be nice to have the option to control color of the accordion with basic bootstrap classes. As I have seen from template, the accordion is really just a panel and panel has optional classes panel-default, panel-primary etc. Is there away to control those from the directive, or can it be added?

Thanks

**Comment by rvanbaalen** [comment]
Use custom templates to overwrite the default ones with your own classes.

**Comment by Zoomink** [comment]
@rvanbaalen Is it possible to have multiple custom templates for the same directive? Let's say I want to have different classes for different accordion-groups.
