### ISSUE TITLE
appendTo option for modal dialog

### ISSUE THREAD

**Issue by mhaertwig** [angular-ui/bootstrap#2688]
What about a "appendTo" option for the modal dialog? 

In my application I would like to use the modal dialog in an element that can be set to fullscreen mode. However, since the modal dialog is appended to the body by default, the dialog disappears every time application's main container is set to fullscreen. Therefore an option to configure the modal dialog's parent element  (e.g. "appendTo") would be nice.

**Comment by YidingW** [comment]
+1

**Comment by icfantv** [comment]
Linking in #4772 but leaving this open for now.

**Comment by wesleycho** [comment]
This has landed as 16d854ca4c70aefb6b03faeb2a20105ce2bea8ec in `master`.
