### ISSUE TITLE
Progressbar width increase more then page width.

### ISSUE THREAD

**Issue by vinaymavi** [angular-ui/bootstrap#2689]
Progress bar width increase more then page width when values of attributes **max** and **value** are changed dynamically. please check this plunker [http://plnkr.co/edit/usUThO?p=preview](http://plnkr.co/edit/usUThO?p=preview) to reproduce.

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13?
