### ISSUE TITLE
ui.bootstrap.carousel call next()/prev() from $scope

### ISSUE THREAD

**Issue by ghost** [angular-ui/bootstrap#2694]
Is there way how can I get these methods from outside ($scope) ?
The solution what works :

in /master/src/carousel/carousel.js

Change : 

```
.directive('carousel', [function() {
  return {
    restrict: 'EA',
    transclude: true,
    replace: true,
    controller: 'CarouselController',
    require: 'carousel',
    templateUrl: 'template/carousel/carousel.html',
    scope: {
      interval: '=',
      noTransition: '=',
      noPause: '='
    }
  };
}])

To :

    .directive('carousel', [function() {
      return {
        restrict: 'EA',
        transclude: true,
        replace: true,
        controller: 'CarouselController',
        require: 'carousel',
        templateUrl: 'template/carousel/carousel.html',
        scope: {
          interval: '=',
          noTransition: '=',
          noPause: '=',
          control: '='
        },
        link: function (scope, element, attributes, controller) {

          scope.internalControl = scope.control || {};

          scope.internalControl.next = function() {
            scope.next();
          };

          scope.internalControl.prev = function() {
            scope.prev();
          };
        }
      };
    }])
```

Add to your controller :

```
$scope.carouselCtrl = {};
```

In view  :

```
<carousel control="carouselCtrl" >
    <slide ng-repeat="slide in slides" active="slide.active">
        <div class="carousel-caption">
            {{slide.content}}
        </div>
    </slide>
</carousel>

<button ng-click="carouselCtrl.next()">NEXT</button>
```

Is there another solution or is possible to add this to the source ?

Got inspired at : http://stackoverflow.com/questions/16881478/how-to-call-a-method-defined-in-an-angularjs-directive

**Comment by leualemax** [comment]
.directive('carouselNext', function () {
	return {
		restrict: 'A',
		scope: {},
		require: ['^carousel'],
		link: function (scope, element, attrs, controllers) {
			var carousel = controllers[0];
			function howIsNext() {
				if ((carousel.indexOfSlide(carousel.currentSlide) + 1) === carousel.slides.length) {
					return 0;
				} else {
					return carousel.indexOfSlide(carousel.currentSlide) + 1;
				}
			}
			element.bind('click', function () {
				carousel.select(carousel.slides[howIsNext()]);
			});
		}
	};
})

.directive('carouselPrev', function () {
	return {
		restrict: 'A',
		scope: {},
		require: ['^carousel'],
		link: function (scope, element, attrs, controllers) {
			var carousel = controllers[0];
			function howIsPrev() {
				if (carousel.indexOfSlide(carousel.currentSlide) === 0) {
					return carousel.slides.length;
				} else {
					return carousel.indexOfSlide(carousel.currentSlide) - 1;
				}
			}
			element.bind('click', function () {
				carousel.select(carousel.slides[howIsPrev()]);
			});
		}
	};
})

**Comment by Vishal1419** [comment]
@leualemax  How can I use these directives? Can you please show a demo code?
