### ISSUE TITLE
Rating with ng-readonly

### ISSUE THREAD

**Issue by dodophoenix** [angular-ui/bootstrap#2700]
Rating directive doesn't respect ng-readonly. The only way to get it in readonly mode seems to use the readonly directly as attribute. 

As we got hit by the restrictions mentioned here https://docs.angularjs.org/api/ng/directive/ngReadonly we are not able to use readonly as attribute directly.  (version: 0.10.0)

**Comment by zmirc** [comment]
@porjo Thanks a lot :+1:

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.
