### ISSUE TITLE
Timepicker localization

### ISSUE THREAD

**Issue by Aakkosti** [angular-ui/bootstrap#2704]
Currently Timepicker always uses a colon as a time separator. However, some languages, e.g. Finnish, use a period as a time separator. The time separator should be somehow configurable.

**Comment by wesleycho** [comment]
I took at this before, but it looks like we cannot support this - see https://github.com/angular/angular.js/issues/13232 for more information about the work necessary on the Angular side for supporting this feature.

I would recommend homebrewing some hacky logic with $locale in a custom directive with a custom template if you only need to support a limited number of languages.
