### ISSUE TITLE
ui.bootstrap.dropdown missing

### ISSUE THREAD

**Issue by nathanpen** [angular-ui/bootstrap#2708]
Looks like ui.boostrap.dropdown is declared as a module but its not actually in the source.

**Comment by Delapouite** [comment]
if https://github.com/angular-ui/bootstrap/issues/2529 is confirmed to be fixed, so I guess this one can be closed as well.

@nathanpen, @RobJacobs, @rmathis, @hcentelles did you try to do a custom build including the dropdown recently?

**Comment by rmathis** [comment]
@Delapouite I just tested it, seems fixed to me. Thanks!

**Comment by karianna** [comment]
Closing, thanks
