### ISSUE TITLE
Typeahead: preventDefault on enter keypress

### ISSUE THREAD

**Issue by DanielHeath** [angular-ui/bootstrap#2711]
Currently, when a user presses enter after focussing a search result, `select` is called directly.

However, the event has `preventDefault` called on it. This stops the browser from (e.g.) following a link which is focussed when enter is pressed.

This makes sense for up/down keypresses as they cause scrolling which is probably not what you want. However, it hijacks a sensible default behavior for the enter key (since typeahead templates can include links)

**Comment by deeg** [comment]
@wesleycho, I believe this can be closed and is no longer an issue, correct?

**Comment by wesleycho** [comment]
Looks like it, thanks
