### ISSUE TITLE
[$modal]Suggest adding disable body's overflow-y to hidden to prevent scroll when a modal is open.

### ISSUE THREAD

**Issue by xieranmaya** [angular-ui/bootstrap#2722]
Add a option to config that can disable body's vertical scroll when a modal is open.
Using like this:
```
$modal.open({
    disableBodyVerticalScroll:true/false,
    ...
});
```

**Comment by wesleycho** [comment]
I also do not believe any CSS changes like this should be in the core, as it makes it more difficult for users to override if they conditionally need to modify this.

Feel free to create a directive that can handle this for your own projects though!
