### ISSUE TITLE
Typeahead doesn't support two-way data binding fully...

### ISSUE THREAD

**Issue by Siyfion** [angular-ui/bootstrap#274]
See the plunkr here: http://plnkr.co/edit/3ryOYo

If the typeahead is to truly use "the same, flexible syntax as the select directive (http://docs.angularjs.org/api/ng.directive:select)" then it needs to support two-way binding via this method.

**Comment by szaccaria** [comment]
Hello @pkozlowski-opensource I read that this issue is was closed... I've this jfiddle https://jsfiddle.net/qq4gqn6t/12/  but when I change the model the label not change... Can help me?
Thanks

**Comment by icfantv** [comment]
@szaccaria, support-related questions are best suited by posting them to StackOverflow where there's a significantly wider audience to get them answered.

**Comment by szaccaria** [comment]
@icfantv done! thanks for suggest!

**Comment by szaccaria** [comment]
@icfantv I had made a directive... hope that this helps somebody https://jsfiddle.net/qq4gqn6t/91/ and http://stackoverflow.com/questions/35044544/bootstrap-ui-typeahead-doesnt-support-two-way-data-binding?noredirect=1#comment61870083_35044544
