### ISSUE TITLE
Scrolling via a saved url

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular-ui/bootstrap#2741]
Hi guys,

I found a small bug I think, in the gh-pages -> assets/apps.js file. Line 8:

location.replace(el.id);

...should be 

$location.replace(el.id);

Once changed it loads the page and scrolls to the proper place.

AngularJS + Bootstrap is the bomb! Thanks.

**Comment by rvanbaalen** [comment]
Can you verify this is still an issue? Thanks for reporting though :+1:

**Comment by wesleycho** [comment]
I actually think this is intentional. I tried tweaking this, and while this behavior is suboptimal, I'm not sure there is a better way.

**Comment by wesleycho** [comment]
Closing as per prior investigation.
