### ISSUE TITLE
Tabs: control tab visibility

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular-ui/bootstrap#2743]
I know that you can use `ng-show` or `ng-hide` or `ng-if` to set tab's visibility, but that does not cut it because if first tab happens to be set invisible, user still sees contents for the first tab and second tab is not set active.
There should be a separate control similar to `disabled`. For example: `visible`

**Comment by wesleycho** [comment]
Closing in favor of #4836 - keep an eye out for that issue.
