### ISSUE TITLE
Tabs: The binding of "active" does not respect the initial value

### ISSUE THREAD

**Issue by gildorwang** [angular-ui/bootstrap#2745]
With the following code ([plunker here](http://plnkr.co/edit/S8urmT?p=preview)):
````html
<tabset>
  <tab heading="First tab" active="options.firstTabActive">
    <h1>First tab</h1>First tab active={{options.firstTabActive}}
  </tab>
  <tab heading="Second tab" >
    <h1>Second tab</h1>First tab active={{options.firstTabActive}}
  </tab>
</tabset>
````

And in controller:
````javascript
$scope.options = {
  firstTabActive: false
};
````

The second tab is expected to be active. However, the actual behavior is the first tab is active, and `options.firstTabActive` is changed to be `true`.

I took a look at code. During `postLink`, the `tab` directive calls `addTab` of `TabsetController` to add tabs, while in `addTab`, the controller sets the first tab to active blindly regardless of the current value of `active`:
````javascript
ctrl.addTab = function addTab(tab) {
  tabs.push(tab);
  // we can't run the select function on the first tab
  // since that would select it twice
  if (tabs.length === 1) {
    tab.active = true;
  } else if (tab.active) {
    ctrl.select(tab);
  }
};
````

Any idea?

**Comment by rvanbaalen** [comment]
Works in v0.13.0

http://plnkr.co/edit/05e7mw3Ep9x07QkSwQFG?p=preview
