### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/bootstrap#2746]
I was talking to the ui-grid team and kind of touched up our fairly unknown logos a little. I did some touchup with the ui-bootstrap logo too:

![Bootstrap Logo](https://raw.githubusercontent.com/angular-ui/angular-ui.github.com/master/logo/UI_Shield_Bootstrap.png)

**Comment by wesleycho** [comment]
You should open up a PR @ProLoser :) .

**Comment by rvanbaalen** [comment]
No offense or anything but I could also ask one of my designers to take a shot at it if you're interested.

**Comment by ProLoser** [comment]
@rvanbaalan go ahead

**Comment by wesleycho** [comment]
While cool, I don't think we'll be updating the logo - the only place we use it is the favicon afaik, and it is too detailed to notice the changes there.

Thanks for the effort though!
