### ISSUE TITLE
DatePicker behaves erratically when both datepicker-mode and min-mode are set to "month".

### ISSUE THREAD

**Issue by svet007** [angular-ui/bootstrap#2751]
http://plnkr.co/edit/Ihya7ZtFb1fTbCq9y1rZ?p=preview

Or in the DatePicker Plunker http://angular-ui.github.io/bootstrap/ update the HTML:

<datepicker datepicker-mode="dpmode" min-mode="minmode" ...

and JS:

  $scope.dpmode = "month";
  $scope.minmode = "month"

Thanks!

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13?

**Comment by wesleycho** [comment]
There is a similar ticket for when they are both `year` as well - this looks like it may have to do with the conditional where it compares if they are equal.

**Comment by wesleycho** [comment]
This seems to work properly currently, as can be seen [here](http://plnkr.co/edit/KzA8krFjNsi4Z44yp3eR?p=preview).

Closing as resolved.
