### ISSUE TITLE
[Carousel] After hide and show, carousel next/prev buttons don't work

### ISSUE THREAD

**Issue by JobaDiniz** [angular-ui/bootstrap#2752]
**Angularjs**: 1.2.24
**Angular-ui**: 0.11.0
**Plunker**: http://plnkr.co/edit/6wYOvW9MYacJQ6nY9OY6?p=preview
**Steps**:
1. Click **hide** button.
2. Wait a few seconds (**this is important**).
3. Click **show** button.

**Expected result**: *Next* and *Prev* buttons should work. Carousel should show slides automatically.
**Actual result**: *Next* and *Prev* buttons don't do anything. Carousel is stopped; it should show slides automatically.

**Comment by rvanbaalen** [comment]
Fixed in the latest UI Bootstrap 0.13 with Angular 1.3. Don't forget to add ngAnimate manually if you want animated slide transitions.

http://plnkr.co/edit/PcTjVbboIiPNZk4Jr7c2?p=preview
