### ISSUE TITLE
Does Typeahead Support RTL?

### ISSUE THREAD

**Issue by anasqadrei** [angular-ui/bootstrap#2753]
I am typing in an RTL language in an input field with typeahead for suggested texts. The text is aligned to the right correctly but the drop down list is aligned to the left. Is there anyway to align the typeahead drop down list to the right or is it not supported?

For an example, please take a look at my plnkr. Type in `وا` to see suggested text.
http://plnkr.co/edit/QCvLW7Yu86PVcne4nXnu

My plnkr uses angularjs 1.2.10, ui-bootstrap-tpls-0.11.0, and bootstrap 3.1.1.
But I also replicated the problem on angularjs 1.3.9, ui-bootstrap-tpls-0.10.0, and bootstrap 3.2.

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.

**Comment by anasqadrei** [comment]
Problem still persists using Angular 1.4.3 and UI Bootstrap 0.13.3. Check http://plnkr.co/0CZItlMMviBHS9jXJTBX

Copy `وا` and paste it in the text box. You will see the text in the textbox aligned to the right but the dropdown is aligned to the left. They both should be aligning to the right.

**Comment by wesleycho** [comment]
Closing this in favor of #4762 - this is positioning related, which has some hard problems in need of solving.
