### ISSUE TITLE
datepicker does not open

### ISSUE THREAD

**Issue by muneswar** [angular-ui/bootstrap#2767]
Hello,

I do not want all the directives, so I used "create your own build" to download only datepicker Say ui-bootstrap-datepicker-tpls-0.10.0.min.js. Have been using this directive and everything worked fine.

Recently, I wanted to use progress bar also and hence downloaded respective directive, say ui-bootstrap-progressbar-tpls-0.10.0.min.js. When I included this js file also, datepicker is not shown when clicked on a button. But when I remove progress bar js file, I see datepicker working fine.

I don't understand the relation. Can you please help?

**Comment by wesleycho** [comment]
Closing as resolved by support, let us know if this is still an issue.
