### ISSUE TITLE
Modal: Add a way to intercept dismissal and prevent it.

### ISSUE THREAD

**Issue by santialbo** [angular-ui/bootstrap#2768]
I think it would be interesting if there was a way of preventing the user to accidentally dismiss a modal window when clicking on the backdrop by mistake. I'd be happy to think/work on a solution if you guys think it's a good idea.

**Comment by kentor** [comment]
There should be hooks that "clicking outside" and "pressing escape" should both go through so that we can override that hook and prevent closing with logic of our choosing. That would make a good API.

**Comment by eugeneos** [comment]
The backdrop:'static' solution isn't enough when you want dynamic control over when the modal is dismissible. For example, I have a modal with a bunch of data fields and a Save button. Normally, I want the user to be able to dismiss the modal by clicking outside or hitting Escape. However, after Save is pressed and a save request is sent to the server, I don't want the user to be able to dismiss the modal until a reply from the server has been received. It would be great to have a hook where I can intercept modal dismissal and cancel it.
