### ISSUE TITLE
 datepicker $setValidity $error does not follow convention naming

### ISSUE THREAD

**Issue by emouawad** [angular-ui/bootstrap#2773]
In datepicker.js
ngModelCtrl.$setValidity('date-disabled', !date || (this.element && !this.isDisabled(date)));

$setValidity(validationErrorKey, isValid)
validationErrorKey: does not follow convention 

The validationErrorKey should be in camelCase and will get converted into dash-case for class name. Example: myError will result in ng-valid-my-error and ng-invalid-my-error class and can be bound to as {{someForm.someControl.$error.myError}} .

**Comment by rvanbaalen** [comment]
You're right that should be edited. 

https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$setValidity
