### ISSUE TITLE
typeahead set focus causing 'scroll lock' on iOS

### ISSUE THREAD

**Issue by johnwillyn** [angular-ui/bootstrap#2778]
I tracked this down to the code in scope.select() in the typeahead module.

The following line is causing scroll lockup on iOS devices (at the bottom of this function):

        $timeout(function() { element[0].focus(); }, 0, false);

I am using this with the Ionic framework, but I don't think that is required.

When I switch 'tabs' (routes), and the scope containing the typeahead gets destroyed, the scrolling on the IOS device is locked up.

I have tried calling blur() and even canceling the timeout (promise) in the destroy handler, but none of that fixed the issue.  When I comment out this line, scrolling is no longer getting locked.

If anyone can think of something else to try, I would be happy to test it, but for now I am doing without this 'feature' in my typeahead.

**Comment by rvanbaalen** [comment]
We don't officially support mobile yet.
