### ISSUE TITLE
Inputs with tooltip set can't be focused on first click on iOs, it needs 2.

### ISSUE THREAD

**Issue by poupougnac** [angular-ui/bootstrap#2783]
Hi,

When I click on my input that have a tooltip, I can't type directly. It needs a second click to actually focus the input and display the keyboard.
This occurs only on iOs (iPad + iPhone). 
Is this a bug ?
Thanks

**Comment by poupougnac** [comment]
Hi, is there anything new about this issue ? Still waiting for a fix.

**Comment by poupougnac** [comment]
Hello,

I have found that using specifically "click" for the trigger prevent the bug. As tooltip default to "hover" and keep that specification even for touch device, it would be convenient to set "click" per default for touch device. I will check how I can do that.

**Comment by c-johnson** [comment]
+1, thanks for your comment poupougnac, that worked great for me.  Is there a reason why "focus" wouldn't be the default?  I know you all are busy though :)

**Comment by wesleycho** [comment]
This is related to #3687, which has more information.

Closing as a duplicate, although I highly recommend rethinking using a tooltip/popover in iOS due to poor/non-sensical UX.
