### ISSUE TITLE
Sub modules not found

### ISSUE THREAD

**Issue by dbounds** [angular-ui/bootstrap#2787]
I've investigated but have been able to determine any load error on my part so I'm posting an issue.

ui.bootstrap is initializing but during the process I'm getting "Module not found" errors on the sub modules.  

First error was with ui.bootstrap.dateparser, I made a custom build removing it and the became ui.bootstrap.dropdown. See the moduleerr tree below:

https://docs.angularjs.org/error/$injector/modulerr?p0=BaseApp&p1=Error:%20%5B$injector:modulerr%5D%20http:%2F%2Ferrors.angularjs.org%2F1.2.19%2F$injector%2Fmodulerr%3Fp0%3Dui.bootstrap%26p1%3DError%253A%2520%255B%2524injector%253Amodulerr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.2.19%252F%2524injector%252Fmodulerr%253Fp0%253Dui.bootstrap.dropdown%2526p1%253DError%25253A%252520%25255B%252524injector%25253Anomod%25255D%252520http%25253A%25252F%25252Ferrors.angularjs.org%25252F1.2.19%25252F%252524injector%25252Fnomod%25253Fp0%25253Dui.bootstrap.dropdown%25250A%252520%252520%252520%252520at%252520Error%252520(native)%25250A%252520%252520%252520%252520at%252520https%25253A%25252F%25252Fajax.googleapis.com%25252Fajax%25252Flibs%25252Fangularjs%25252F1.2.19%25252Fangular.min.js%25253A6%25253A450%25250A%252520%252520%252520%252520at%252520https%25253A%25252F%25252Fajax.googleapis.com%25252Fajax%25252Flibs%25252Fangularjs%25252F1.2.19%25252Fangular.min.js%25253A20%25253A466%25250A%252520%252520%252520%252520at%252520https%25253A%25252F%25252Fajax.googleapis.com%25252Fajax%25252Flibs%25252Fangularjs%25252F1.2.19%25252Fangular.min.js%25253A21%25253A469%25250A%252520%252520%252520%252520at%252520https%25253A%25252F%25252Fajax.googleapis.com%25252Fajax%25252Flibs%25252Fangularjs%25252F1.2.19%25252Fangular.min.js%25253A33%25253A267%25250A%252520%252520%252520%252520at%252520Array.forEach%252520(native)%25250A%252520%252520%252520%252520at%252520q%252520(https%25253A%25252F%25252Fajax.googleapis.com%25252Fajax%25252Flibs%25252Fangularjs%25252F1.2.19%25252Fangular.min.js%25253A7%25253A280)%25250A%252520%252520%252520%252520at%252520e%252520(https%25253A%25252F%25252Fajax.googleapis.com%25252Fajax%25252Flibs%25252Fangularjs%25252F1.2.19%25252Fangular.min.js%25253A33%25253A207)%25250A%252520%252520%252520%252520at%252520https%25253A%25252F%25252Fajax.googleapis.com%25252Fajax%25252Flibs%25252Fangularjs%25252F1.2.19%25252Fangular.min.js%25253A33%25253A284%25250A%252520%252520%252520%252520at%252520Array.forEach%252520(native)%250A%2520%2520%2520%2520at%2520Error%2520(native)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.19%252Fangular.min.js%253A6%253A450%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.19%252Fangular.min.js%253A34%253A97%250A%2520%2520%2520%2520at%2520Array.forEach%2520(native)%250A%2520%2520%2520%2520at%2520q%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.19%252Fangular.min.js%253A7%253A280)%250A%2520%2520%2520%2520at%2520e%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.19%252Fangular.min.js%253A33%253A207)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.19%252Fangular.min.js%253A33%253A284%250A%2520%2520%2520%2520at%2520Array.forEach%2520(native)%250A%2520%2520%2520%2520at%2520q%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.19%252Fangular.min.js%253A7%253A280)%250A%2520%2520%2520%2520at%2520e%2520(https%253A%252F%252Fajax.googleapis.com%252Fajax%252Flibs%252Fangularjs%252F1.2.19%252Fangular.min.js%253A33%253A207)%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.19%2Fangular.min.js:6:450%0A%20%20%20%20at%20https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.19%2Fangular.min.js:34:97%0A%20%20%20%20at%20Array.forEach%20(native)%0A%20%20%20%20at%20q%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.19%2Fangular.min.js:7:280)%0A%20%20%20%20at%20e%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.19%2Fangular.min.js:33:207)%0A%20%20%20%20at%20https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.19%2Fangular.min.js:33:284%0A%20%20%20%20at%20Array.forEach%20(native)%0A%20%20%20%20at%20q%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.19%2Fangular.min.js:7:280)%0A%20%20%20%20at%20e%20(https:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.19%2Fangular.min.js:33:207

**Comment by wesleycho** [comment]
Closing as there is not enough information.

It should be noted that the custom builder on the homepage has been fixed for a while, so if this is an issue with that tool, it should be functioning fine currently.
