### ISSUE TITLE
datepicker with ng-focus throws $apply error

### ISSUE THREAD

**Issue by martinstein** [angular-ui/bootstrap#2789]
After the changes in issue #1922, the suggested fix for keeping the old "open on focus" behavior is to use `is-open="dt.open"` and `ng-focus = "dt.open = true"`.

However, using `ng-focus` this way causes the datepicker to break with the error:

    $apply already in progress
    [$rootScope:inprog] http://errors.angularjs.org/undefined/$rootScope/inprog?p0=%24apply

This seems to be a problem for multiple people (in the discussion of #2149):
https://github.com/angular-ui/bootstrap/issues/2149#issuecomment-43695213
https://github.com/angular-ui/bootstrap/issues/2149#issuecomment-44204065
https://github.com/angular-ui/bootstrap/issues/2149#issuecomment-54630847
https://github.com/angular-ui/bootstrap/issues/2149#issuecomment-56773007

So, this looks important for many people, especially since it occurs because of the breaking changes of the #1922 fix.

**Comment by alexszilagyi** [comment]
@chrisirhc: could you please tell me if there's any update on this bug? I'm using lastest version and 1.3.11 and seemts to persist.

**Comment by wesleycho** [comment]
Closing this, as we are moving to Angular 1.3 with 0.13.0.
