### ISSUE TITLE
Tabs in combination with ui-router are causing problems

### ISSUE THREAD

**Issue by westor21** [angular-ui/bootstrap#2794]
Tabs in combination with ui-router don't work as expected. Precondition: Drop the tabs in a page with an outer navigation. If you navigate away from the page where your tabset resides, the last active tab is destroyed and the next one is activated. Because of this activation (setting a new route) you are not able to navigate away, except if the last tab is the selected one.
Please see the plunkr:
http://plnkr.co/edit/NBovbrWsiJghtTLY8b1I?p=preview

Steps to reproduce:
- activate page 1, tab 1
- click on page 3, note activation of tab 3 on page 1

Note: I tryed a prior version and that seems to work as expected.

**Comment by wesleycho** [comment]
Closing as fixed, let us know if this is not the case.
