### ISSUE TITLE
Datepicker and Timepicker on single model

### ISSUE THREAD

**Issue by mgibas** [angular-ui/bootstrap#2796]
Hi,

I want to modify date and time with Datepicker and Timepicker on common model (same model for date and time). In the end I'm sending it to my service. I found some problems though-
Every time I change time, my date is coming back to current date :(

```html
<input datepicker is-open="true" ng-model="date" />
<input timepicker ng-model="date"/>
```

http://plnkr.co/edit/SAdQEV0cnw3IPXVf03q9

On provided plunker model is initialized with some date - change time and date will be set to current date (same behavior when You set model value with Datepicker - timepicker will override date)

Maybe this is some kind of misuse and I should use two separated models - if so, please let me know.

**Comment by chrisirhc** [comment]
Most likely due to input type handling changes in Angular 1.3 . Perhaps try adding `type="date"` on the input?

**Comment by BobbieBarker** [comment]
Closing will reopen if a plunker is submitted demonstrating this is still an issue.

**Comment by triarc** [comment]
Still an issue.
(clone of last plunk with updated angular and ui-bootstrap)
http://plnkr.co/edit/k5c7OlH7AK9z3EVCmCPw?p=preview

**Comment by kichooo** [comment]
Also, changing directive to <timepicker> instead of using <input timepicker> does not really change anything afaic.

**Comment by kichooo** [comment]
Oh, that plunk is failed. NVM, I think it can remain closed.
