### ISSUE TITLE
autofocus in modal doesn't work a second time

### ISSUE THREAD

**Issue by wilg** [angular-ui/bootstrap#2802]
1. Open a modal that has an `autofocus` text field
2. Note the field focuses
3. Open the same modal again.
4. Note the field doesn't focus.

This was fixed in #2273 but was not merged.

**Comment by gauravarya83** [comment]
Still not working for me, I have AngularJS 1.2.28 !

**Comment by nosheen-javed** [comment]
Hi,
I am facing the same issue. Did you find any solution for this?
Thanks

**Comment by sanhappyboy** [comment]
Do we have any solution for this?

**Comment by jagdishjadeja** [comment]
i am having this problem in chrome only 
in safari it works fine

**Comment by usmanajmal** [comment]
Seeing same exact issue in Angular 5.2.10

**Comment by usmanajmal** [comment]
Fixed it using following workaround. Hope it helps someone:

```
 <input type="text" #my_input >
            {{ my_input.focus() }}
```

**Comment by usmanajmal** [comment]
Facing same exact issue with Angular 5 and Chrome
