### ISSUE TITLE
NG-animate broke modal in chrome

### ISSUE THREAD

**Issue by johnstonmatt** [angular-ui/bootstrap#2803]
I have a pretty weird bug where my modals won't show up in chrome, but the screen dims and if I tap escape they show for a split second.

Looking at answers to previous issues (december 2013) I think I might have to build with grunt, but I tried that and couldnt seem to get that to work either. I'm running angular 1.2.26 Ui-Bootstrap 0.10.0 and angular-animate 1.2.26

**Comment by wesleycho** [comment]
Closing as fixed by #2724.
