### ISSUE TITLE
Datepicker multidate select support

### ISSUE THREAD

**Issue by piupiupiu** [angular-ui/bootstrap#2806]
Hello, 

Do you have any plans to add multidate select support? I'm talking about one widget, not a date-range.

**Comment by piupiupiu** [comment]
@spongessuck, thank you. Though it's useless in my case as I'd like to use with popup and it does not seem to work altogether.

**Comment by spongessuck** [comment]
@piupiupiu It should work in a popup... if you think there's a problem please open an issue with a demo in my repo and I'll check it out.

**Comment by spongessuck** [comment]
@piupiupiu Oh I see what you mean. That would be a good fork or branch of my repo...

**Comment by spongessuck** [comment]
@piupiupiu Check out this Plunk, it works fine if I take out the requirement for the 'datepicker' controller in my directive: http://plnkr.co/edit/cQXRxM?p=preview

**Comment by piupiupiu** [comment]
@spongessuck, thank you. I mean it does not work as it is supposed to work. Since it binds the selected dates to a new model. (multi-select) it does not reflect the dates in the <input /> field.

**Comment by spongessuck** [comment]
Gotcha.

**Comment by wesleycho** [comment]
I think this would be difficult to support, and I'm not so convinced that it is something that most people would use.

Given these factors, I'm closing this as something we don't want to support, as the complexity vs. the gains aren't worth the tradeoff.

**Comment by karolwebsky** [comment]
+1
