### ISSUE TITLE
'M' and 'd' date formatter too strict

### ISSUE THREAD

**Issue by loicoudot** [angular-ui/bootstrap#2812]
* With 'MM' and 'dd' date formatting, date is valid if and only if we have two digits month or day (ex. 01 or 12) => OK 
* With 'M' and 'd' date formatting, the leading '0' is forbidden to validate a date (ex. 1 is valid, 01 is invalid) => OK

But what if we want to tolerate an input with OR without the leading '0'. I think it can be very handy to tolerate the leading '0' of an input.

see the [plunkr](http://plnkr.co/edit/5e7MfSIid3cPZ6nSys81?p=preview)

One could patch the `dateParser` service like this 
```javascript
    'M': {
      regex: '0?[1-9]|1[0-2]',
      apply: function(value) { this.month = value - 1; }
    },
    'd': {
      regex: '0?[1-2]?[0-9]{1}|3[0-1]{1}',
      apply: function(value) { this.date = +value; }
    },
```

ui-bootstrap 0.11.2
angular 1.3.0-rc5

**Comment by wesleycho** [comment]
I do not believe we will support this, as we are paralleling the Angular dateFilter currently - work needs to be done to abstract the date parsing to allow users to use a library like moment.js, at which point this may be a possibility.
