### ISSUE TITLE
dropdownService close responed to right click incorrectly by closing the dropdown.

### ISSUE THREAD

**Issue by squareplanetdesign** [angular-ui/bootstrap#2813]
It should not close the drop-down with right click. It should just allow the browser defaults to happen meaning the context menu.

A small change would fix this:

```javascript
                var closeDropdown = function( evt ) {
                    var toggleElement = openScope.getToggleElement();
                    if ( evt && event.which === 1 && toggleElement && toggleElement[0].contains(evt.target) ) {
                        return;
                    }

                    openScope.$apply(function() {
                        openScope.isOpen = false;
                    });
                };
```

**Comment by Delapouite** [comment]
2 things to consider regarding `event.which === 1` :
- according to MDN, this property is declared as non standard : https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which
- there seems to be a reverse notation for people configuring their mouse for left-hand use.

**Comment by wesleycho** [comment]
This should now be fixed in `master` for the vast majority of cases - I am not finding a good solution to fix the problem for left-handed mice though.

**Comment by wesleycho** [comment]
Closing due to main issue being fixed, and there being no reliable way to detect the mouse click differences between a left-handed mouse and right-handed mouse.
