### ISSUE TITLE
Collapse inside collapse not working as expected with example

### ISSUE THREAD

**Issue by W1zzard** [angular-ui/bootstrap#2821]
If i use collapse inside other collapse inner collapse not working as expected:
http://plnkr.co/edit/DTY72Zf7dX3QqN6jwtcj?p=preview
toggle collapse, then toggle inner collapse, then close outer and close inner, open outer, inner still open but should be closed.

**Comment by chrisirhc** [comment]
Should be fixed via #1444

**Comment by chrisirhc** [comment]
Possibly duplicate of #1774
