### ISSUE TITLE
Tooltip bug with angular 1.3

### ISSUE THREAD

**Issue by ozdavid3** [angular-ui/bootstrap#2828]
When migrating to angular 1.3 tooltip stops showing.
It seems like the element does show on the DOM but its class attribute does not contain required classes in order to change opacity (so opacity stays 0).

**Comment by cnaccio** [comment]
There seems to be a problem with placement/position of  tooltips, and popovers. It has something to do with the changes to angular.isDefined which works differently in AngularJS 1.2 & 1.3 

Here are a few directives to patch the issues by setting defaults

            // Bootstrap UI fixes after upgrading to Angular 1.3
            .directive('tooltip', function() {
                return {
                    restrict: 'EA',
                    link: function(scope, element, attrs) {
                        attrs.tooltipPlacement = attrs.tooltipPlacement || 'top';
                        attrs.tooltipAnimation = attrs.tooltipAnimation || true;
                        attrs.tooltipPopupDelay = attrs.tooltipPopupDelay || 0;
                        attrs.tooltipTrigger = attrs.tooltipTrigger || 'mouseenter';
                        attrs.tooltipAppendToBody = attrs.tooltipAppendToBody || false;
                    }
                }
            })

            .directive('popover', function() {
                return {
                    restrict: 'EA',
                    link: function(scope, element, attrs) {
                        attrs.popoverPlacement = attrs.popoverPlacement || 'top';
                        attrs.popoverAnimation = attrs.popoverAnimation || true;
                        attrs.popoverPopupDelay = attrs.popoverPopupDelay || 0;
                        attrs.popoverTrigger = attrs.popoverTrigger || 'mouseenter';
                        attrs.popoverAppendToBody = attrs.popoverAppendToBody || false;
                    }
                }
            })

**Comment by guilbep** [comment]
@cnaccio Wow thanks for that.

**Comment by cferejohn** [comment]
I'm still seeing the "jumping" problem (tooltip appears too far to the right and then immediately 'jumps') on angular bootstrap 0.13.3/Angular 1.3.10 (also saw it in 1.4.3). Animation is false and I've set tooltip-trigger and tooltip-placement on the elements in question.
