### ISSUE TITLE
Update to support angular 1.3

### ISSUE THREAD

**Issue by squareplanetdesign** [angular-ui/bootstrap#2830]
The current library supports 1.2. Now that angular 1.3 is out officially, would be great to get it working on angular 1.3.

**Comment by ilanbiala** [comment]
The biggest issue is what @bensquire is referring to about the modal backdrops not having their backdrop.

**Comment by stunaz** [comment]
@bensquire , @ilanbiala it is an issue related to bootstrap 3.3, as mentioned on #2925 here is a quick workaround:

.modal-backdrop{
  bottom: 0
}

**Comment by cnaccio** [comment]
There seems to be a problem with placement/position of  tooltips, and popovers. It has something to do with the changes to angular.isDefined which works differently in AngularJS 1.2 & 1.3 

Here are a few directives to patch the issues by setting defaults

            // Bootstrap UI fixes after upgrading to Angular 1.3
            .directive('tooltip', function() {
                return {
                    restrict: 'EA',
                    link: function(scope, element, attrs) {
                        attrs.tooltipPlacement = attrs.tooltipPlacement || 'top';
                        attrs.tooltipAnimation = attrs.tooltipAnimation || true;
                        attrs.tooltipPopupDelay = attrs.tooltipPopupDelay || 0;
                        attrs.tooltipTrigger = attrs.tooltipTrigger || 'mouseenter';
                        attrs.tooltipAppendToBody = attrs.tooltipAppendToBody || false;
                    }
                }
            })

            .directive('popover', function() {
                return {
                    restrict: 'EA',
                    link: function(scope, element, attrs) {
                        attrs.popoverPlacement = attrs.popoverPlacement || 'top';
                        attrs.popoverAnimation = attrs.popoverAnimation || true;
                        attrs.popoverPopupDelay = attrs.popoverPopupDelay || 0;
                        attrs.popoverTrigger = attrs.popoverTrigger || 'mouseenter';
                        attrs.popoverAppendToBody = attrs.popoverAppendToBody || false;
                    }
                }
            })

**Comment by gotstu** [comment]
+ a billion

**Comment by cm325** [comment]
:+1:

**Comment by kotfilemon** [comment]
+1

**Comment by robbyt** [comment]
@antoinepairet or one of the project maintainers, can you please lock this ticket to prevent the "+1" noise? I'd like to subscribe to this issue to track progress, but the "+1" messages add nothing to the conversation.

**Comment by rvanbaalen** [comment]
Keep an eye out for the 0.13 release @robbyt. We're working around the clock to address all 1.3 related issues. 

We cannot prevent comments in an issue thread.

**Comment by imcotton** [comment]
Just FYI, after upgrade Bootstrap to [v3.3.4](https://github.com/twbs/bootstrap/releases/tag/v3.3.4) for CSS **ONLY**, the modal-backdrop issue goes away automatically, for more: twbs/bootstrap#15881

**Comment by AnirbanKundu** [comment]
The pagination control from angular bootstrap ui does not work with angular 1.3. Any thoughts on this ?

**Comment by karianna** [comment]
@AnirbanKundu - being worked on.

**Comment by AnirbanKundu** [comment]
I solved the issue by taking the templates from ui-bootstrap-tpls and loading all templates  into a templateCache in a separate module. In that way, I had complete control of the html templates and injected few styles wherever required.

**Comment by andrenarchy** [comment]
What do you think about shipping a pre-release for `0.13.0`, e.g., `0.13.0-beta.1`?

I'm currently using the latest release (0.12) with angular 1.3 and the overall experience is quite bad. The current master seems to play nicely with angular 1.3 already. If there are still a few issues/PRs: no worries, it's a pre-release – that's what developers should expect! :smiley:

**Comment by nschloe** [comment]
+1 for @andrenarchy's suggestion.

**Comment by piernik** [comment]
+1

**Comment by rvanbaalen** [comment]
Ill discuss this with the rest if the team and see what we can do.

**Comment by trondeh80** [comment]
+1 for @andrenarchy's suggestion here aswell.

**Comment by andrenarchy** [comment]
@rvanbaalen good! Publishing a pre-release may also decrease the continuous inflow of (duplicate) issues for 0.12. Most of them are probably fixed already in the master branch but it's not easy to use the master branch in a bower/npm-based project (since you have to build it manually).

**Comment by rvanbaalen** [comment]
For future releases we will consider publishing beta's and so on. Right now we're so close to releasing 0.13 (just 8 issues to go) that it doesn't make sense to go through the process of releasing a beta.

**Comment by andrenarchy** [comment]
I can only spot 1 open issue for 0.13 right now: this one! \o/

Good to hear that you plan to publish pre-releases in the future.

**Comment by dcominottim** [comment]
Nice! Can we expect 0.13 before the end of the weekend?

**Comment by rvanbaalen** [comment]
That depends on what we're all doing this weekend ;-) but I suppose it's safe to say you can expect it before the end of next week.

**Comment by dcominottim** [comment]
That is great news -- thank you! One more question: when Angular 2 goes RTM, will ui-bootstrap keep being maintained for Angular 1.x as long as Angular 1 has new releases?

**Comment by rvanbaalen** [comment]
We still have to discuss such plans. It is quite some work to maintain two different repos as you can imagine. But given our huge community I would say there is no way around it :wink:

Note that this is just *my* opinion and not the one of the team. We will publicly discuss this matter when the time comes. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by chrisirhc** [comment]
0.13.0 is now released. Closing. :smile:

**Comment by w3hacker** [comment]
+1

**Comment by andrenarchy** [comment]
Awesome! Is anyone of the core team living in Berlin so I can buy you a beer/coffee/...? :smile:
