### ISSUE TITLE
Typeahead bug when using ng-require and Angular 1.3.0

### ISSUE THREAD

**Issue by joshmackey** [angular-ui/bootstrap#2832]
See http://plnkr.co/edit/ooXX1rvKpur58nTJjcPy?p=preview

Basically, if the model is already set by something, it searches immediately and shows the dropdown. If ````ng-required```` is removed, then there is no issue.

**Comment by JeroMiya** [comment]
I'm also no longer seeing this issue. Recommend closing.

**Comment by antoinepairet** [comment]
Thanks for your feedback @trask and @JeroMiya 
Here is a working plunkr: http://plnkr.co/edit/3Bk3aXpiH5OIee5P4oom?p=preview

Closing the issue
