### ISSUE TITLE
Angular 1.3: date-picker cannot interpret value from `new Date()`

### ISSUE THREAD

**Issue by DerekDomino** [angular-ui/bootstrap#2834]
The break occurred when updating from angularjs-1.3.0-rc.3 to rc.4

When binding a scope property to a ui-date-picker input, the date displayed in the input field is not correct anymore:
````javascript
$scope.theDate = (new Date()).toString();
````

Displayed value depends on angularjs version:
 * with angularjs 1.3.0-rc.3:   '14/10/2014'   <- OK
 * with angularjs 1.3.0-rc.4:   '01/02/2021'   <- KO

**Comment by antoinepairet** [comment]
Should be fixed by https://github.com/angular-ui/bootstrap/commit/23936f9f6ec7170b56c7f13345ae022c74fa3034
rgds

**Comment by Lak1890** [comment]
Dear Sir,
I have created an input tag for my datepicker as follows:
<input type="date" placeholder="" class="ngcalenderwidth" style="width: 80%;height:30px" my-datepicker type="text" ng-model="StartDate" readonly="true"> 
In my controller, I am not able to get the ng-model value : start date. I mean $scope.StartDate gives me Nan-undefined-Nan ., following which i am not able to proceed.
This works fine in chrome, but not in Firefox or IE9 and above.
What can be the reason?
Any help is highly appreciated..!
