### ISSUE TITLE
Collapse fails to update its height when toggling collapse model

### ISSUE THREAD

**Issue by mxth** [angular-ui/bootstrap#2836]
I have a simple collapse.

    <ul collapse="isCollapsed">
      <li ng-repeat="item in items">
        {{item}}
      </li>
    </ul>
    
Here is the controller:

    angular.module('ui.bootstrap.demo').controller('CollapseDemoCtrl', function ($scope) {
      $scope.isCollapsed = true;
      $scope.items = [];
      $scope.add = function() {
        $scope.items.push(Math.random());
      }
    });
    
Plunker: http://plnkr.co/edit/ZYE3A4gt2I3JZgOEXxhf?p=preview

When I toggle the **isCollapsed** from true to false and add more items to the list, the collapse height is not updated.

The problem is when toggling **isCollapsed** from true to false, if the list has no item (height: 0px), the collapse will not set the height attribute to auto. Thus, it will make the collapse fail to update its height.

It does not happen when **isCollapsed** is initialized with false value (still with empty list), since the height attribute is auto in this case.

**Comment by rllola** [comment]
I have the same issue. 
Does the fix has been commited in the master branch ? 
I have Angular 1.2.26 an bootstrap UI 0.12.0

Thank you

**Comment by chrisirhc** [comment]
Will be fixed via #1444
