### ISSUE TITLE
modal ignores early calls to dismiss / close

### ISSUE THREAD

**Issue by josh-compeat** [angular-ui/bootstrap#2838]
If a call to close a modal is made too soon after opening it, the call will be ignored and the modal will never close.
Workaround: before calling modal.close() or modal.dismiss(), set the opened promise to close itself.

Demonstrated here: http://plnkr.co/iCjUvuVumb2Ajfmp2iFv

**Comment by wesleycho** [comment]
Note: this still is an [issue](http://plnkr.co/edit/WDcsHNs8We7SBojj0Be5?p=preview)

I am not sure what the best approach for this would be. Maybe adding built-in support for delaying the close/dismiss calls until the modal loads?

**Comment by nlwillia** [comment]
Unfortunately, the change I submitted last year to add a vetoable `modal.closing` event complicates this somewhat.  The event is dispatched synchronously, so the `close` and `dismiss` methods return a synchronous boolean indicating whether close was permitted.  It's documented and part of the current test suite, so it would be a minor breaking change to defer the attempt and return a promise.  Alternative would be to keep the synchronous dispatch/return and track successfully pre-closed modalInstances in a separate list internally and check that before completing the open.  In that case, a listener would have to allow for the possibility that `modal.closing` could now be broadcast before the resolves finished, which could also be a gotcha in some cases.  If there's a preference for one of the other, I can look at it.

**Comment by wesleycho** [comment]
We have `modal.opened` and `modal.rendered` promises now for hooking into when all of the resolves/template finished loading & when the animation is complete, respectively - this should address this problem sufficiently.
