### ISSUE TITLE
datepickerPopup inside a form (ui-bootstrap v 0.11.2)

### ISSUE THREAD

**Issue by donzauker78** [angular-ui/bootstrap#2839]
I have a custom ngModel directive for mantaining milliseconds timestamp data and format view value as Date type.
<pre>
.directive('dateFormat', function () {
    return {
        restrict: 'A',
        require: 'ngModel',
        link: function (scope, element, attr, ngModel) {
            ngModel.$formatters.unshift(function (timestamp) {
                if (timestamp) {
                    return new Date(timestamp);
                }
                return new Date(0);
            });
            ngModel.$parsers.push(function (date) {
                if (date instanceof Date) {
                    return date.getTime();
                }
                return 0;
            });
        }
    };
})
</pre>
It works very well until I try to validate my field in a form. Unfortunately datepickerPopup has an internal function parseDate(viewValue) that validates only dates, strings and null values and it does not seem to handle milllisecond timestamps. As result form.$error.date is true, even if model contains valid numeric values. It would be useful to make behaviour more flexible replacing this piece of code:
<pre>
if (angular.isDate(viewValue) && !isNaN(viewValue)) {
  ngModel.$setValidity('date', true);
  return viewValue;
}
</pre>

with something like this:
<pre>
if (!isNaN(viewValue)) {
  ngModel.$setValidity('date', true);
  if (angular.isDate(viewValue)) {
    return viewValue;
  }
  return new Date(viewValue);
}
</pre>

**Comment by wesleycho** [comment]
Currently you need to maintain a parallel model to the current model on the datepicker - this is unideal, and we have an issue open to support custom parsers in #4093, which would allow you to bring your own model and hook it into the parsers and formatters directly.

I am going to close this as a duplicate, but this is a well known issue with the datepicker that we want to fix.
