### ISSUE TITLE
datepicker-popup is broken by angular 1.3.0

### ISSUE THREAD

**Issue by hyzhak** [angular-ui/bootstrap#2851]
To reproduce just use new angular 1.3.0 version for example and get:

http://plnkr.co/edit/eaZNCWX9UAk1NuR17qR0?p=preview

date in default date format which doesn't react on any custom format, until you will change date.

![](https://lh4.googleusercontent.com/-4g7bSWtF_jY/VELmkIqJ7pI/AAAAAAAA9nU/cVVfXsBur7A/s0/2014-10-19_00-15-31.png)

**Comment by wesleycho** [comment]
Closing as fixed in master.
