### ISSUE TITLE
AngularJs 1.3.0 - $digest() iterations reached.

### ISSUE THREAD

**Issue by sangallimarco** [angular-ui/bootstrap#2862]
AngularJs breaks and displays error: '...Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! Watchers fired in the last 5 iterations: [] ..' when opening modals . All worked fine till angular#1.3.0-rc.4

**Comment by coryasilva** [comment]
@sangallimarco Have you resolved this issue?

**Comment by pkozlowski-opensource** [comment]
Sounds like @sangallimarco sorted it out, no reason to keep it open any more
