### ISSUE TITLE
Dropdown closing on mouseout parent and child divs

### ISSUE THREAD

**Issue by davidpelayo** [angular-ui/bootstrap#2864]
As an alternative to this opened issue by myself: https://github.com/angular-ui/bootstrap/issues/2863, In case you want to implement a menu using this Dropdown component, is it possible to have the option to declare explicitly to close the "menu" when mouseout on the main element as well as the children list items so that giving the effect of closing after a timer is over?

Thanks in advance.

**Comment by icfantv** [comment]
You can do the following to accomplish what you want.  Note the use of `ng-mouseleave`:
```
<li class="dropdown"
    ng-class="{open: menu.open}"
    ng-mouseleave="menu.open = false">
  <a href class="dropdown-toggle"
     ng-click="menu.open = !menu.open">Sample Menu <span class="caret"></span></a>
  <ul class="dropdown-menu" ng-click="menu.open = false">
    <li><a href="#">A Menu Item</a></li>
    <li><a href="#">Another Menu Item</a></li>
    <li><a href="#">A Third Menu Item</a></li>
  </ul>
</li>
```
Closing as not an issue.
