### ISSUE TITLE
Accordion is-open doesn't work with angular.js 1.3.0

### ISSUE THREAD

**Issue by dmatta** [angular-ui/bootstrap#2871]
I set up two examples in plunker with exactly the same accordion example except this one is using angular.js 1.2.16

http://plnkr.co/edit/4xUgFjQQiXUPYNbMIsI5?p=preview

And the second one is using angular.js 1.3.0 
http://plnkr.co/edit/VpE1343mDkfjZCabXwme?p=preview

Clicking on the link under Static Header, initially expanded for 1.2.16 shows and opens the Dynamic Body Content accordion group.

Clicking on the same link for 1.3.0 shows the Dynamic Body Content accordion group but doesn't open it.

Then you have to click twice on the dynamic body content header to open the accordion group.

Please let me know if you need any more information.

Thanks!

**Comment by JeroMiya** [comment]
FYI: Still seeing this in angular 1.3.8 and ui-bootstrap 0.12.0.

**Comment by Foxandxss** [comment]
Yo!

I can confirm this as well (cleaned [example](http://plnkr.co/edit/RFy1Gm26wF6pDct7OaPt?p=preview)).

I will fix that ASAP.
