### ISSUE TITLE
Datepicker under tab with ng-required not working with angular 1.3.0

### ISSUE THREAD

**Issue by angular-user** [angular-ui/bootstrap#2877]
The datepicker with ng-required seems to be broken with Angular 1.3.0. It is not picking up the model value on load. It works with angular 1.2.16.
http://plnkr.co/edit/NFcm0Bpu0y45LsrzVtpr?p=preview

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13? Also, provide a link to a plunkr reproducing your problem.

**Comment by rvanbaalen** [comment]
Aside from the fact that the current day isn't active, this particular issue is fixed now:

http://plnkr.co/edit/7EZbYD3PBqab8WhzZuS1?p=preview
