### ISSUE TITLE
If initial active tab is not the first one, its select gets called twice

### ISSUE THREAD

**Issue by Dev63** [angular-ui/bootstrap#2883]
If the initial active tab is not the first tab, its select action gets called twice.

You can see this in the slightly modified sample code in this [Plunker](http://plnkr.co/edit/CErAYR11JWvjXgFaiKj5?p=preview).  All I did was add select="alertMe()" to additional tabs, and set active:true to the first Dynamic tab.

**Comment by wesleycho** [comment]
Forked the Plunker with an update [here](http://plnkr.co/edit/dgot8WccoN0OfAqcaAab?p=info) for reference - will be tackling this.
