### ISSUE TITLE
Datepicker only accept text that matches format

### ISSUE THREAD

**Issue by stephendparker** [angular-ui/bootstrap#2886]
If someone is using a datepicker with popup, like here:

http://angular-ui.github.io/bootstrap/#/datepicker

Is it possible to mark the field as invalid until they have formatted the date like provided?  For instance, if I am typed:
10
It treats this as a valid date (october 1, 2001) .  I would rather treat this as invalid, until I completed by typing of my date like:
10/20/2014

**Comment by jmayday** [comment]
Ahh. Seems like I haven't noticed this issue and also created a similar PR for this. https://github.com/angular-ui/bootstrap/pull/3288

**Comment by wesleycho** [comment]
This should now be fixed in `master`.
