### ISSUE TITLE
Typehead always put popup below the input field

### ISSUE THREAD

**Issue by t00f** [angular-ui/bootstrap#2889]
Hi !
When placing the input field at the bottom of the page, the Typeahead should appear on top of the field instead of beeing displayed at the bottom and extending the window size. 

I could not find any option to have this behaviour. Which way would be easier/cleaner to do it ?

Thanks!

**Comment by arg20** [comment]
+1, I need to display the typeahead above the input field. When I have time I'll look into the source code

**Comment by icfantv** [comment]
Closing in favor of #4762.
