### ISSUE TITLE
Incorrect CSS for adding pointer cursor on main page

### ISSUE THREAD

**Issue by leesei** [angular-ui/bootstrap#2891]
http://angular-ui.github.io/bootstrap

Under CSS, a comma is missing before `a` in
```
.nav, .pagination, .carousel, .panel-title a { cursor: pointer; }
```

It should be:
```
.nav, .pagination, .carousel, .panel-title, a { cursor: pointer; }
```

**Comment by wesleycho** [comment]
I am not able to reproduce this currently - feel free to open a new issue with more details if there is a particular problem.
