### ISSUE TITLE
zero-height accordion body never gets opened.

### ISSUE THREAD

**Issue by mattdarveniza** [angular-ui/bootstrap#2893]
When you have an accordion that is empty, it's possible for it's height to get set to 0 instead of auto by the accordion directive, meaning that if it is ever filled with content, that content won't be rendered until you close and re-open the accordion.

By default this doesn't seem to be an issue, since even an empty accordion body has padding and a top-border in bootstrap's default styling, however when overridden to a style with no vertical padding directly on the accordion-body, this issue appears.

Issue can be replicated in [this plunker](http://plnkr.co/edit/YY4PkcJoyYSc8QyHM8TK?p=preview). Open accordion, and then press 'show content' button.

Obviously the above is simplified and not a very good example of *why* you'd want to do this, but I discovered the issue when filtering a group of accordions, where a filter hides all the elements in an accordion, the accordion is opened/closed and then fails to show elements once the filter is cleared.

My temp fix is to just style `.accordion-body` with `min-height: 1px` but that's clearly not great and violates my pixel perfect tendencies.

Keen to provide more info if I haven't made myself clear enough.

**Comment by wesleycho** [comment]
This appears to be fixed now, as can be seen [here](http://plnkr.co/edit/hLh13u4vdm2tlPnD5FRy?p=preview).
