### ISSUE TITLE
ControllerAs with DatePicker binds strings, not Dates

### ISSUE THREAD

**Issue by mbcooper** [angular-ui/bootstrap#2899]
This may be related to another 1.3 issue, but when I use code to assign a date to the DatePicker, I get a date string (and it assigns my binding variable to undefined.)

ALSO: dates are messed up -- added 1 day!

See plunkr at http://plnkr.co/edit/TBClYQ7CHKmPL0H3SbB3?p=info

click on the link .. it will show 3-4 date pickers in a loop .. bad date binding....

**Comment by jancel** [comment]
I'm running into this issue as well.   Have you guys figured out a work around or any particular advice before I pull my ui-datepickers out?

**Comment by karianna** [comment]
What versions of Angular/Bootstrap and Bootstrap UI?

**Comment by jancel** [comment]
1.3.6 I do believe, bootstrap 3.x and 0.12 of ui, whichever bootstrap ui came with it, but will check on Monday. I just removed controllerAs and I was passed the issue for now.

**Comment by wesleycho** [comment]
I'm not seeing this on current master: http://plnkr.co/edit/lm5z2glUX1a3AauKaVLu?p=preview

Has this been potentially fixed?

**Comment by karianna** [comment]
@wesleycho yeah looks like @cleftheris committed it.

**Comment by cleftheris** [comment]
Hi all, I made a PR a while back but was not accepted as the solution. There is an alternative solution in the current master that tackles the problem but is still having a bug. Check the discussion for more info https://github.com/angular-ui/bootstrap/pull/3279.
