### ISSUE TITLE
Enhacement dropdown

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#2904]
I need a dropdown menu with checkbox in it.
I found this site: http://behigh.github.io/bootstrap_dropdowns_enhancement/
Is there angular version of this feature? If not can You make one?

**Comment by hjzheng** [comment]
Yes,  dropdown menu should support sub-menu.

**Comment by hjzheng** [comment]
you can try this implement sub-menu in angular-ui http://plnkr.co/edit/dGg56j?p=preview

**Comment by maxetime** [comment]
You can add an ng-click="$event.stopPropagation()" to the containing element (Ex: the one with the dropdown directive) to prevent it to close when you click inside it.

**Comment by aiguofer** [comment]
I looked for this for a long time, ran into a lot of older closed bugs and tried lots of things until I finally hit this.  This works like a charm, is there any way this could be incorporated into the examples? I think it would help people a lot (I've found lots of similar questions on SO and other places).

Thanks for all the hard work!

**Comment by wesleycho** [comment]
If someone wishes to make a PR updating the docs with these examples, I would be happy to review them and get them in.

**Comment by aiguofer** [comment]
https://github.com/angular-ui/bootstrap/pull/3357 ;-)

**Comment by wesleycho** [comment]
Hm, given that resolution, I am going to close this.
