### ISSUE TITLE
Datepicker value is off by a day when date format is different from the datepicker's date format

### ISSUE THREAD

**Issue by Trish00** [angular-ui/bootstrap#2906]
I have my date picker format set to:  datepicker-popup="MM/dd/yyyy".

If a user types in a date in a different format the date ends as the day before.

i.e.  User types in 2013-10-07  date value is 2013/10/06.  But if the user types in 2013-10-7 the date is correct.
      User types in 2014-08-09 date value is 2014-08-08 but if the user types in 2014-9-09 the date is correct.

Here is an example using your the datepicker example on your website.  It would seem it doesn't like the leading zeros.

![datepicker - 2014-08-10](https://cloud.githubusercontent.com/assets/8975032/4832413/f70cbfc4-5f9b-11e4-94cd-626939a43e74.JPG)

**Comment by cgwyllie** [comment]
+1 for exposing a configuration option to allow 'strict' parsing, we've just encountered this issue with 'relaxed' parsing too on a multi-locale app.

**Comment by wesleycho** [comment]
This should now be fixed in `master`, if not in 0.14.3
