### ISSUE TITLE
Images inside popover

### ISSUE THREAD

**Issue by calbertuk** [angular-ui/bootstrap#2923]
I'm having some issues with my popovers, they contain an image with no fixed height and if the image isn't preloaded in the DOM, it breaks the popover.

The idea is that the popover displays first without the image and once the image is fully loaded, it's added to the tooltip but it makes the tooltip have a higher height than it did when it was first shown and displaces it down:
http://i.stack.imgur.com/1ZPb2.jpg

I tried to load the image on show.bs.popover but that doesn't work

       $('.pop').on('show.bs.popover', function() {
        $('.pop').not(this).popover('hide');
        if ($(this).is('[poster]')) {
            var image = $(this).attr('poster');
            $('#load_hidden').html('<img src="' + image + '" />');
        }
    });

Any idea on how to make the popover fully load its content before displaying?

**Comment by wesleycho** [comment]
I believe this issue is now fixed with dynamic resizing occurring for tooltips/popovers - feel free to open a new issue with a minimal reproduction if you feel this is still an issue.
