### ISSUE TITLE
Accordion Custom "panel-body" class

### ISSUE THREAD

**Issue by sojic** [angular-ui/bootstrap#2948]
I had need to get rid off "panel-body" margins... The template has .no-padding, but I was unable to add it to accordion-group. I have edited my ui-bootstrap-tpls, but have on mind to add "body-class" attribute and append it do     "&lt;div class=\"panel-body {{ bodyclass }}\" ng-transclude&gt;&lt;/div&gt;\n"

**Comment by RobJacobs** [comment]
@sojic This can be accomplished by creating a CSS class that targets the .panel-body class and adding it to the desired accordion-group element.  They class would look like:
    .accordion-panel .panel-body {
       padding: 0px;
     }
and implemented as:
    <accordion-group heading="Item 1" class="accordion-panel" >

**Comment by sojic** [comment]
@RobJacobs you do not get it obviously.

I need 2 types of "panel body", with padding and without padding on same page. Ex: panel body with table inside, without padding, and panel body with normal content, with padding.

**Comment by RobJacobs** [comment]
@sojic I do get it, but I guess I didn't explain it well enough.  This [Plunker](http://plnkr.co/edit/2SDXGKl2y01NxhddOrU5?p=preview) demonstrates using a CSS class to target the .panel-body on just 1 accordion group.  You will notice Item 1 has no padding with a class of custom-accordion defined where Item 2 still has the default padding.

**Comment by sojic** [comment]
@RobJacobs Thanks! That's it!
