### ISSUE TITLE
UTC mode for DatePicker or default timezone option

### ISSUE THREAD

**Issue by slavafomin** [angular-ui/bootstrap#2952]
Hello!

I have a problem with UTC dates in DatePicker component.

When I provide a date to it in UTC format it appears to work normally, however, when I set initial value to `null` and then user selects some date, it returns date in local timezone, but I want it to always return dates in UTC format.

Maybe you can create some configuration option like `utcMode` or provide an option to specify default timezone?

Thanks!

**Comment by Iku-turso** [comment]
+1

**Comment by karianna** [comment]
@chrisirhc Can you add a comment for the Purgatory reasoning?

**Comment by jasontk19** [comment]
+1 for UTC

**Comment by piupiupiu** [comment]
+1

**Comment by MJGrant** [comment]
+1

**Comment by chrisirhc** [comment]
@karianna I did that because we lacked resources to look into this and also, datepicker is pending quite a bit of refactoring. I'm putting it into Backlog. This is clearly a very desirable feature.

**Comment by bguezzie** [comment]
Using 0.13.0 library:
I was able to work around this by adding a directive to my element (the datepicker popup trigger) that basically did the following:

```javascript
ngModelCtrl.$formatters.push(function (value) {
    var date = new Date(value);

    if (isNaN(date)) {
        return value;  // needed for null/empty/undefined values
    }

    date.setMinutes(date.getTimezoneOffset());  // forces the "local" version of the date to match the intended UTC date

    return date;  // yes, this is a Date object being applied to the $viewValue...don't judge, it works!
});
```

Once I did that, the datepicker used the $viewValue (a Date object in this case) as its model, and since a decent offset had been applied the correct date was shown in my input as well as in the graphical day picker.

Caveat:  Some further conversion might be needed when consuming the timestamp provided by the datepicker, but that hasn't proven problematic in our project so far.

**Comment by ttschupp** [comment]
@bguezzie : I did something similar. 

    app.directive('datepickerTimezone', function () {
        return {
            restrict: 'A',
            priority: 1,
            require: 'ngModel',
            link: function (scope, element, attrs, ctrl) {
                ctrl.$formatters.push(function (value) {
                    var date = new Date(Date.parse(value));
                    date = new Date(date.getTime() + (60000 * date.getTimezoneOffset()));
                    //if (!dateFormat || !modelValue) return "";
                    //var retVal = moment(modelValue).format(dateFormat);
                    return date;
                });

                ctrl.$parsers.push(function (value) {
                    var date = new Date(value.getTime() - (60000 * value.getTimezoneOffset()));
                    return date;
                });
            }
        };
    });


This needs to be added to the Date & Time Picker ASAP. Angular 1.3.0 introduced support in date filters and ngModelOptions, but that has yet to carry over to these controls yet, which is very disappointing.

**Comment by elmalto** [comment]
thank you @ttschupp

**Comment by danauerbach** [comment]
I add check for null value coming in, otherwise end up with a date = 1970-01-01. Tjis was not desirable in my case.

```javascript
        ngModelCtrl.$formatters.push(function (value) {
            var date = new Date(value);

            if (isNaN(date) || (value == null)) {
                return value;  // needed for null/empty/undefined values
            }

            date.setMinutes(date.getTimezoneOffset());  // forces the "local" version of the date to match the intended UTC date

            return date;  // yes, this is a Date object being applied to the $viewValue...don't judge, it works!
        });
```

**Comment by lrambert** [comment]
@ttschupp you saved my day, bless you.

**Comment by wesleycho** [comment]
Going to close this in favor of #4113 since they are requesting the same feature.
