### ISSUE TITLE
pagination module initializes ngModel to 1 if total-items starts out undefined

### ISSUE THREAD

**Issue by AlJohri** [angular-ui/bootstrap#2956]
I'm grabbing metadata from an API where I know which page I would like to grab via the url parameters, but the total-items takes a few milliseconds to populate.

Because total-items starts out undefined, ngModel is changed from the correct page number to 1.

The only way I have gotten around this is to initialize total-items to an arbitrary number such as 1000. Then the page number is left alone.

Is there a better solution?

**Comment by brandonarbini** [comment]
+1, just ran into this. Not sure how to fix it or I'd submit a PR.

**Comment by wesleycho** [comment]
I am not sure if we want to change anything in the pagination here - what should `num-pages` return in this instance? How should the UI look?
