### ISSUE TITLE
unable to set href of <a> tag within pagination module

### ISSUE THREAD

**Issue by AlJohri** [angular-ui/bootstrap#2957]
for SEO purposes, I am trying to crawl my angular application to create html snapshots. I am unable to crawl the pages because I cannot easily set the "href" attribute of the ```<a>``` tags.

I am currently changing the URL after navigation via ```ng-change``` as thus:

```javascript
$scope.updateURL = function () { $location.url($scope.filters.buy_or_sell + "/" + $scope.filters.category + "/" + $stateParams.page); }
```

but would much prefer to have the regular href attribute used.

I can submit a PR for this. A simple implementation would just take a base url as a parameter and append the page number:

```
"http://www.nucraigslist.com/#!/sell/furniture/" + page
```

Or simply include a ```:page``` parameter within the provided string:

```
"http://www.nucraigslist.com/#!/sell/furniture/:page"
```

Please let me know!

**Comment by rvanbaalen** [comment]
Please ask implementation questions on StackOverflow. We'll be happy to answer your questions there. 
https://github.com/angular-ui/bootstrap#need-help
