### ISSUE TITLE
Modal backdrop broken with bootstrap 3.3.1

### ISSUE THREAD

**Issue by LeleDev** [angular-ui/bootstrap#2970]
**IMPT** Read bottom message, Bootstrap update has likely fixed this

To be more precise, broken due to this commit:
https://github.com/twbs/bootstrap/pull/14927/files

Temporary workaround: override new css code with older one

https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by GordanBlake** [comment]
+1

**Comment by R0cKET** [comment]
+1

**Comment by staslev** [comment]
@allaire thanks!

**Comment by wcpaez** [comment]
+1, allaire temp fix solves problem

**Comment by sean3z** [comment]
+1

**Comment by gbozee** [comment]
+1

**Comment by bodiddlie** [comment]
+1, allaire temp fix solved issue, but I had to add position: fixed; for .modal-backdrop as well

**Comment by TheWaWaR** [comment]
+1, and thanks for allaire's temp fix!

**Comment by odellcraig** [comment]
+1

**Comment by ClearCloud8** [comment]
+1

**Comment by karianna** [comment]
@allaire Are you able to submit a PR (with a test) with your fix?

**Comment by allaire** [comment]
@karianna I'm swamped at work currently, won't have time to do this this week :/

**Comment by karianna** [comment]
No rush! I'm one of the very new maintainers so I'm looking to do some Cat Herding on the various PR's and workarounds like yours over the coming month.

**Comment by maxisam** [comment]
@karianna @allaire I think using CSS to fix this issue won't work in certain browser. That is why bootstrap team handle it in JS. You can check out their discussion. As far as I know, my implementation is just like what they did with jQuery. However, I agree with @pkozlowski-opensource, my solution isn't pretty. Not so ng.

**Comment by ezzatron** [comment]
@bodiddlie Thanks for the `position: fixed;` comment. Without this, the modal backdrop does not work when opening a modal at the bottom of a long page (one with a vertical scrollbar).

**Comment by IngwiePhoenix** [comment]
When I was testing the `bootstrap3-dialog` plugin with 3.3.1, I had two issues:

- The dialog was behind the backdrop.
- The backdrop only covered a felt 50% of the page. The top and bottom part was not covered at all.

I havent gotten to test the fixes displayed in this issue so far - but it'd be great to have this fixed... I already paniced, that it could have been my own CSS stuff ;)

**Comment by trumbitta** [comment]
:+1:

**Comment by ilanbiala** [comment]
Has any progress been made on this issue?

**Comment by KWyckmans** [comment]
+1

**Comment by henrikhaugboelle** [comment]
+1

**Comment by KautskyLozanoV** [comment]
+1

**Comment by abhidbydx** [comment]
add below line in your css

.modal-backdrop {
  bottom: 0;
}

**Comment by lpsBetty** [comment]
+1

**Comment by lpsBetty** [comment]
I had to add `position: fixed` too, when the page was scrolled the background wasn't the full height

```
.modal-backdrop {
  bottom: 0;
  position: fixed;
}
```

**Comment by souinhua** [comment]
I'm using this fix from the codes posted

.modal-backdrop {
  bottom: 0;
  position: fixed;
}

I can't use the scrollbar in the right most of the page, it closes the modal but I can use mouse scroll to scroll down. Any updates on this? Thank you!

**Comment by souinhua** [comment]
I fixed it with this code:

.modal-backdrop {
    position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 0;
  background-color: #000;
}

Hope it helps :)

**Comment by prettycode** [comment]
+1

Had to add a ui.bootstrap-fixes.css with:

    .modal-backdrop {
        bottom: 0;
    }

**Comment by jpmnteiro** [comment]
@prettycode +1

**Comment by bbougot** [comment]
+1

**Comment by andyperlitch** [comment]
+1

**Comment by impworks** [comment]
+1

**Comment by baverstockc** [comment]
+1

**Comment by rogier21** [comment]
+1

**Comment by bluebilt** [comment]
+1

**Comment by prettycode** [comment]
What's the work that needs to be done around this? We know the fix involves something like:

    .modal-backdrop {
        bottom: 0;
        /* some fixes appear to use this, too: */
        position: fixed;
    }

If I submit a pull request for this, what regressing or side-effects testing do I need to do?

How do we get traction on this? Would love to contribute a pull request but want to make sure adding this CSS doesn't break anything. Any tips?

**Comment by rogier21** [comment]
Why don't we just keep it in sync with the original bootstrap? 
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_modals.scss

**Comment by baverstockc** [comment]
@prettycode I believe theres already been multiple pull requests with regression testing done but as yet the main contributors are too busy/have a multitude of other issues to look at first. Best to add the fix to your own site and keep an eye on the issue for updates.

**Comment by segevofer** [comment]
+1

**Comment by Fonger** [comment]
+1

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by NateRedding** [comment]
+1 (in case there weren't enough already)

**Comment by idoo** [comment]
+1

**Comment by akkez** [comment]
+1

**Comment by albertpeiro** [comment]
+1

**Comment by anthony-stephan** [comment]
+1

**Comment by chuckd** [comment]
Looks like the change has been reverted upstream, so it may be enough to wait for a new Bootstrap release: https://github.com/twbs/bootstrap/pull/15881.

**Comment by mdridley** [comment]
+1

**Comment by brafkind** [comment]
+1

**Comment by Rutix** [comment]
+1 =)

**Comment by lyonsun** [comment]
+1

**Comment by wesleycho** [comment]
This appears to truly be a Bootstrap problem, not UI Bootstrap - I am closing this since the fix appears to be trivial on the user's side by adding `.modal-backdrop { bottom: 0; }`.

**Comment by trumbitta** [comment]
The real fix would be updating UI Bootstrap to Bootstrap 3.3.2 :smile_cat:

**Comment by Foxandxss** [comment]
We hope we can reach bootstrap 3.3.2 on 0.14 after we fix angular 1.3

**Comment by jonkri** [comment]
+1

**Comment by ashep** [comment]
+1

**Comment by jbutko** [comment]
For me to fix the full height issue following addition into CSS fixed the problem:
```
.modal-backdrop {
  width: 100% !important;
  height: 100% !important;
  position: fixed !important;
}

**Comment by kraenhansen** [comment]
+1

**Comment by austinpray** [comment]
+! Upgrading from 3.3.0 to 3.3.4 fixed this with no other changes.
