### ISSUE TITLE
Datepicker - today can be selected even when lower then min-date

### ISSUE THREAD

**Issue by aviram83** [angular-ui/bootstrap#2974]
Not sure if this is the demand but for me it's seems like a bug.

when min-date is higher then today the "Today" button should be disabled.
![image](https://cloud.githubusercontent.com/assets/9781742/5060933/7fc6be44-6d81-11e4-8333-792208b09ca3.png)

**Comment by felixbillon** [comment]
+1

**Comment by karianna** [comment]
@aviram83 Have you tested this with the latest version (0.13.0)?

**Comment by aviram83** [comment]
@karianna sorry but didn't use it eventually so the answer is no

**Comment by mst-avaleo** [comment]
I'm using version 0.13.0 and I've got the same error. Can you reopen the issue?

**Comment by bkirtika** [comment]
+1
