### ISSUE TITLE
Are you interested in end to end testing?

### ISSUE THREAD

**Issue by Droogans** [angular-ui/bootstrap#2988]
I'm volunteering to come in and add in support for end to end component testing for your library, similar to what I've done for the Encore UI project https://github.com/rackerlabs/encore-ui. Here are some of the advantages we've gained from incorporating page objects into our library.

- Relieves end users from testing component functionality
 - focus instead on testing the business logic inside their angular-bootstrap components
- Encourages testers to expose their work in a similar fashion
 - easily consumable, well-encapsulated APIs representing user actions
- Increases the library's code coverage by integrating end to end tests at the component level
 - ensures that the behaviors exposed in the components' functionality are continuously exercised

Encore-UI It has a very similar directory structure to this project. You'll want to look at anything labeled `*.page.js` for an example of what I'm trying to build. An example of it being used can be found [in the demo pages, under the "Protractor" tab](http://rackerlabs.github.io/encore-ui/#/component/rxModalAction).

A major difference is that I'm not looking to bring in an Astrolabe dependency here, which is used in encore-ui.

For now I'll just work in my fork. Please let me know if you're interested in bringing these into the framework later, or if you have any questions about what I'm trying to do.

**Comment by BobbieBarker** [comment]
I wouldn't mind hearing everyone's opinions.

**Comment by wesleycho** [comment]
I think we do not have enough manpower currently for maintaining e2e tests unfortunately, so I am closing this due to our inability to support these. Thankfully, our unit test coverage is very strong, so we see less issues than most projects over the long term.
