### ISSUE TITLE
Tooltip not correctly positioned when host is close to screen edge

### ISSUE THREAD

**Issue by oliversalzburg** [angular-ui/bootstrap#2990]
When the host element of a tooltip is close to a screen edge, this can cause the tooltip to be positioned incorrectly, because the resizing (which is applied to the tooltip once it is moved close to the edge) isn't taken into account when calculating the position of the tooltip.

![](http://i.imgur.com/sVgs5js.png)

**Comment by ronaldjeremy** [comment]
Are you sure #2296 really fixes this?   in http://plnkr.co/edit/GEQKagaZT7oZheK37NnG?p=preview the tooltip on the left still gets cut off even with a ui-bootstrap-tpls.js that includes #2296

**Comment by oliversalzburg** [comment]
I was now finally able to test #2996 with our code. It resolves the issue.

**Comment by oliversalzburg** [comment]
Positioning is still a bit weird though. Compare the vertical positioning of these two tooltip instances in our application:
![](http://i.imgur.com/9YUOuxP.png)
![](http://i.imgur.com/6mVNgki.png)

**Comment by ronaldjeremy** [comment]
@oliversalzburg this does not seem to be fixed?  I forked your plunker and added a ui-bootstrap-tpls-modified-0.12.0.js that includes the #2996 changes.  The left tooltip still gets clipped? here it is:

http://plnkr.co/edit/AK750fE2Pzm78QbXMFYC?p=preview

**Comment by oliversalzburg** [comment]
@ronaldjeremy Left one is clipped, right one is not positioned correctly. I guess #2996 doesn't completely fix the issue, but for our cases it was a big improvement. However, maybe talk about the issue should be concentrated in one thread on #2996 or even #2995.

**Comment by ronaldjeremy** [comment]
@oliversalzburg this thread looks like the best place for this particular issue?  neither #2996 nor #2995 detail the left getting cut off like this thread does.  Should I re-post my plunker to one of those?

**Comment by oliversalzburg** [comment]
@ronaldjeremy There is a general positioning bug in the component. 

But if an element with a tooltip is positioned so extremely close to an edge of the display area, then it's a design problem. With the current sizing and positioning logic, the tooltip on the left edge would have a width:height ration of 1:10, which would be just as useless as clipping it.
In that case, a different `tooltip-placement` probably makes more sense.

Although, I guess, one could argue that no matter how well or bad a tooltip would look, it shouldn't be clipped and should be positioned at the right location. However, if you don't clip the toolip and it gets very high as a result of it, then it could be clipped at the top. What then?

**Comment by Flo-G** [comment]
Reporting that the issue is still there in ui-bootstrap 0.13.3:
http://plnkr.co/edit/FzORHhIMd2oD03BiVeAu?p=preview

Whereas it's not there in bootstrap 3.3.5:
http://plnkr.co/edit/P03333FEPOqzCq9HqzKn?p=preview

**Comment by trane294** [comment]
2.5.0 still there

**Comment by davidmeirlevy** [comment]
This bug still exists, so why is this issue still closed?
Is there another issue about that same bug?
