### ISSUE TITLE
Callback method when drodown menu opens

### ISSUE THREAD

**Issue by abhranilnaha** [angular-ui/bootstrap#2991]
When user clicks on dropdown button (dropdown-toggle), it pulls data from backend with an asynchronous call. I want to set focus on the first dropdown menu item like typeahead (typeahead-focus-first). I need a callback method to do so when the dropdown menu is opened.

**Comment by rvanbaalen** [comment]
Please ask implementation questions on StackOverflow. We'll be happy to answer your questions there. 
https://github.com/angular-ui/bootstrap#need-help
