### ISSUE TITLE
Datepicker - Date Entered in Text Field Does Not Match Selected Date in Calendar

### ISSUE THREAD

**Issue by sagerman4** [angular-ui/bootstrap#2994]
So I have reproduced this on your sample page (http://angular-ui.github.io/bootstrap/).

If I type in the following '2014-10-11', the calendar selects the 10th of October in 2014, not the 11th, as it should.  This is not specific to this date, as I have reproduced it with other dates.

**Comment by kiksebegolovy** [comment]
+1

**Comment by muhammadghazali** [comment]
+1

**Comment by wesleycho** [comment]
This currently seems to work as expected in `master`, as can be seen in this demo [here](http://plnkr.co/edit/3hylCCWwp89FalD06R07?p=preview) that is straight off of the homepage. Note that you have to specify what format you want in order to get it to work.
