### ISSUE TITLE
Drop Down not opening up by adding ui.bootstrap in app.js

### ISSUE THREAD

**Issue by PawandeepKaur** [angular-ui/bootstrap#2998]
I am working on the raw visualization library, which is based on angular, and bootstrap. http://app.raw.densitydesign.org/#%2F

I am adding accordion to make each panel collapsible. Though, it works well but the drop down buttons within the app has stopped working. Even, if I don't use accordion and only add the ui.bootstrap file , still it is the same. Without this file, it works well

Steps I have performed already
1)In my bootstrap folder , I excluded dropdown. js and still the same
2) I could not find any restrict : CA as it was some of the previous suggestions from other posts

Also I am getting the following error on my console for 2 drop downs:

![image](https://cloud.githubusercontent.com/assets/8779073/5106040/1f573816-6ff4-11e4-9be4-c52e4f780b5a.png)

**Comment by cyrus-za** [comment]
After reading here,  and applying the dropdown-toggle attribute to all my dropdown toggle elements, it still didn't work. Then I read the full changelog. You also need to add dropdown attribute to the <li> element where you had the dropdown class.

**Comment by Sampath-Lokuge** [comment]
This one is working for me.

       <li class="dropdown" dropdown >
                   <a href="#" class="dropdown-toggle" dropdown-toggle role="button" aria-expanded="false">More <span class="caret"></span></a>
                                <ul class="dropdown-menu dropdown-menu-left" role="menu">
                                    <li><a href="#">Edit Event</a></li>
                                    <li><a href="#">Withdraw Funds</a></li>
                                </ul>
                            </li>

**Comment by red010182** [comment]
Thanks to @Sampath-Lokuge , it works for me too!

**Comment by rvanbaalen** [comment]
The release notes were slightly unclear indeed. The correct way to implement a dropdown, as mentioned before in this thread is this:

## Before:

```html
<li class="dropdown" ...>
<button class="dropdown-toggle" ...>
```
## After:

```html
<li class="dropdown" dropdown ...>
<button class="dropdown-toggle" dropdown-toggle ...>
```

**Comment by PawandeepKaur** [comment]
thanks, it worked for me as well..

**Comment by rbaarsma** [comment]
With newest boostrap-ui, bootstrap and angularjs, the demo on the bootstrap-ui is not working for me on Chrome Version 43.0.2357.124 (64-bit)

    
    <span class="dropdown" dropdown on-toggle="toggled(open)">
      <a href class="dropdown-toggle" dropdown-toggle>
        Click me for a dropdown, yo!
      </a>
      <ul class="dropdown-menu">
        <li ng-repeat="choice in items">
          <a href>{{choice}}</a>
        </li>
      </ul>
    </span>

Changing

      <a href class="dropdown-toggle" dropdown-toggle>
        Click me for a dropdown, yo!
      </a>

to

      <a href="#" class="dropdown-toggle" dropdown-toggle>
        Click me for a dropdown, yo!
      </a>

solved it for me.

Note: added ="#" to the href attribute.
