### ISSUE TITLE
error on typeahead

### ISSUE THREAD

**Issue by Tallyb** [angular-ui/bootstrap#2999]
in the last line (in getMatchesAsync):
          var onCurrentRequest = (inputValue === modelCtrl.$viewValue);
          if (onCurrentRequest && hasFocus) {
            if (matches.length > 0) {
an error is thrown that matches.length is not defined. 
on the next attempt - it works ok.

**Comment by antoinepairet** [comment]
It does not happen every time. I have the feeling there is a issue of timing. Using your plunkr, if I quickly use the typeahead the error will show up. If I wait long enough, the error will not happen.

That being said, the fix seems obvious and harmless. thanks @unkleara

**Comment by rkriitr** [comment]
if (matches && matches.length > 0)  prevents the undefined error, but first time, the matched dropdown does not show up anyway. Please tell me what needs to be done.

**Comment by rkriitr** [comment]
sorry, in the code
<input ng-model="brandChainName"
			typeahead="name for name in brandChainNames | filter:$viewValue | limitTo:8"
			typeahead-template-url="columnTwo.html" >
brandChainNames  was not intialized. Now it is working. It is not a bug in bootstrap, it is bug on the coder's part.
