### ISSUE TITLE
Issue with multiple supported transition styles

### ISSUE THREAD

**Issue by JoniB** [angular-ui/bootstrap#3001]
Hello,

The selection for the triggered transitionEnd event seems to be wrong if multiple styles (e.g. "WebkitTransition", and "transition") are supported ( as in Chrome 38.0.2125.111 m). 
It uses the first one, but the wrong event is fired. This destroys functionality for e.g. the carousel.

See fiddle with minimal example: [minimal JSFiddle](http://jsfiddle.net/20rvpg51/)

which leads to following log in my setup:
> checking: WebkitTransition  (index):49
> match for:WebkitTransition (index):51
> checking: MozTransition undefined (index):49
> checking: OTransition undefined (index):49
> checking: transition  (index):49
> match for:transition (index):51
> triggered wrong: transitionend

**Comment by chrisirhc** [comment]
We plan to remove `$transition` in favor of `$animate` in the upcoming release.

**Comment by wesleycho** [comment]
Closing, as `$transition` is no longer supported.
