### ISSUE TITLE
In Accordion, having a fixed panel-body is limiting

### ISSUE THREAD

**Issue by cherrydev** [angular-ui/bootstrap#3002]
The contents of a .panel are not always a .panel-body, but sometimes a .list-group instead.  Nesting a .list-group inside of a .panel-body looks terrible.  This is a documented example [here](http://getbootstrap.com/components/#panels-list-group).  Having an option (or default) to omit the default .body-panel would make the accordion much more flexible than it currently is.

**Comment by rvanbaalen** [comment]
You can already do that by implementing your own custom template.
