### ISSUE TITLE
Dropdown's do not work when Toggling with two Buttons

### ISSUE THREAD

**Issue by allentong** [angular-ui/bootstrap#3004]
Since updating to 0.12, some of the functionality on my site stopped working.  

We had set up two buttons as "dropdown-toggle", but now since we updated I cannot have two button(element) toggles under a single "dropdown" directive.

Adding Plunker later on.

**Comment by watsoncj** [comment]
I found this work-around useful to close the menu.

`$scope.$broadcast '$locationChangeSuccess'`

**Comment by wesleycho** [comment]
I am closing this as `wontfix`. The decision was made to not support the class option after the discussion mentioned.
