### ISSUE TITLE
Change regex for dateparser format 'd' and 'M' to allow for leading zeros and fix regex for 'M' format

### ISSUE THREAD

**Issue by dkuerner** [angular-ui/bootstrap#3008]
Allow leading zeros for day and month for format d and M
Use case:
Format d.M.y should allow for entering dates like 02.05.12 and like 2.5.12
This format is very common.

In addition, the regex for 'M' is incorrect. The order of the alternation should be changed.

**Comment by cleftheris** [comment]
This is true I had the same issue. @dkuerner please make a pull request with your commit so that the someone from the team can review/merge. (hope sometime soon :+1: )

**Comment by wesleycho** [comment]
We are not interested in supporting this at this point in time - the dateparser currently aims to support the behavior found in Angular's dateFilter.

**Comment by cleftheris** [comment]
Are you serious. Filters are meant primarily for presenting data not user input. Try putting a date picker on an input type text and explain to the user why is 1/2/2015 is not a valid date. IMHO this is a bug

**Comment by wesleycho** [comment]
Nothing is stopping you from overwriting the `dateparser` factory to implement your own custom parser.

That type of attitude though is unwarranted and unprofessional.

**Comment by cleftheris** [comment]
My sincere apologies for my outburst.

**Comment by wesleycho** [comment]
You'll be happy to know @cleftheris that I figured out a good implementation for this feature, and it will make it shortly to `master` - see #4809 :) .

**Comment by cleftheris** [comment]
@wesleycho thanks much appreciated. Although currently I have overridden the `DateParser` as you suggested and works quite well I will switch back to default in order to get updates as soon as it gets merged.

cheers
