### ISSUE TITLE
Options not getting updated if underlying data changes

### ISSUE THREAD

**Issue by dietergoetelen** [angular-ui/bootstrap#3011]
I'm writing a directive wrapper around a typeahead input. This directive listens for changes on a link and get's new data + options for the typeahead. 

I can simply simulate this behaviour with a $timeout and demonstrated it in [this plnkr.co][1].

**JS**

    app.controller('sample', function($scope, $timeout) {
      
      $scope.options = ['1800', '1900', '2100'];
      
      // Simulate some latency
      $timeout(function () {
        
        $scope.options.push('1850');
        
      }, 4000);
      
    });

**HTML**

    <div>
        <input type="text" ng-model="optionValue" typeahead="opt for opt in options | filter:$viewValue">
    </div>

If you start typing '18' in the input field it shows 1800 as expected. But when 1850 get's added after an amount of time, the selectable options from typeahead are not being updated. 

I've provided a small solution for this, before I do a pull request etc I want to discuss if it's the correct way of doing it:

A custom attribute that'll be used for the $watchCollection

    var customOptions = attrs.typeaheadCustomOptions || '';

In the function where it gets the matches I've added a watch if customOptions is provided:

    if (customOptions) {
         originalScope.$watchCollection(customOptions, function (matches) {
              resetMatches();
              updateMatches(matches);
         });
    }

And that was basically it :-), the updateMatches is just an abstraction of existing code..

    var updateMatches = function(matches) {
           for (var i = 0; i < matches.length; i++) {
               locals[parserResult.itemName] = matches[i];
               scope.matches.push({
                          id: getMatchId(i),
                          label: parserResult.viewMapper(scope, locals),
                          model: matches[i]
               });
           }
    
           scope.query = modelCtrl.$viewValue;
     };

[Updated Plunkr][2]

(uses the updated version of typeahead)

  [1]: http://plnkr.co/edit/TK7Gs7OAit3jRj0p3Kt4?p=preview
  [2]: http://plnkr.co/edit/tm4De8ukfDyu8dXPVwla?p=preview

**Comment by rvanbaalen** [comment]
Please ask implementation questions on StackOverflow. We'll be happy to answer your questions there. 
https://github.com/angular-ui/bootstrap#need-help
