### ISSUE TITLE
Progressbar minsize and flag to show the current percentage

### ISSUE THREAD

**Issue by jlebrech** [angular-ui/bootstrap#3013]
When you show text inside the Progressbar when the percentage is under a certain value then the text doesn't display correctly, there should be a way to set a min percentage that'll fix the 4 characters need to fit that text (i.e '10%')

Also if you want the value and text for the progressbar to be the same there should be an option for that.

Would you accept a pull request for this?

**Comment by rvanbaalen** [comment]
Go for it! Demonstrate it in a seperate repo/plunkr and if it's cool, we can merge it in. You could also make it a standalone extension for UI Bootstrap.

**Comment by wesleycho** [comment]
This sounds like something that can and should be implemented on the user's side - we won't know the font size, or the pixel width, without doing some more intensive calculation.

I am closing this as something we won't support.
