### ISSUE TITLE
Overall size

### ISSUE THREAD

**Issue by fnagel** [angular-ui/bootstrap#3015]
It seems the overall file size has been changed since the descritpion on http://angular-ui.github.io/bootstrap/ was written.

> Whichever method you choose the good news that the overall size of a download is very small: <20kB for all directives (~5kB with gzip compression!)

It seems its more like ~55KB and ~20KB compressed. 

This should be updated. Sorry guys ;-)

**Comment by rvanbaalen** [comment]
Feel free to submit a PR. 

By the way -- there is (quite a big) difference between 'compressed' and 'gzip compressed'.

**Comment by yuyokk** [comment]
Hi guys,
Sorry but I was not able to attach the pull request here.
It is here https://github.com/angular-ui/bootstrap/pull/3837

**Comment by wesleycho** [comment]
This has been updated thanks to @yuyokk.
