### ISSUE TITLE
Bug: Accordion "accordion-toggle" empty href

### ISSUE THREAD

**Issue by pocesar** [angular-ui/bootstrap#3017]
The accordion `a` tag is coming with an empty `href` attribute, that if you right/middle click it, it will reload the current page or open the current page on another window, respectivelly

```html
<a accordion-transclude="heading" ng-click="toggleOpen()" class="accordion-toggle" href="">...</a>
```

plunkr: http://plnkr.co/edit/fdgrUc01JkYlzFrhUoy3

**Comment by rvanbaalen** [comment]
Cant reproduce this with your plunkr.
