### ISSUE TITLE
[$modal] - ability to distinguish modals (by ids) and close a particular modal

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular-ui/bootstrap#3019]
I have a case when a message might come to the website via sockets and based on that message I need to close a particular modal (not all opened modals) if it's open.

For this I propose to add an optional parameter `id` to the modal:
```
var modalInstance = {
	id: modalOptions.id,
	result: modalResultDeferred.promise,
	opened: modalOpenedDeferred.promise,
	close: function (result) {
		$modalStack.close(modalInstance, result);
	},
	dismiss: function (reason) {
		$modalStack.dismiss(modalInstance, reason);
	}
};
```
and add two more methods to `$modalStack`:
```
$modalStack.getAll = function () {
	return openedWindows.keys();
};

$modalStack.closeById = function(id, result) {
	var modalInstance = null;
	var opened = $modalStack.getAll();
	for (var i = 0, l = opened.length; i < l; i++) {
		if (opened[i].id == id) {
			modalInstance = openedWindows.get(opened[i]);
			break;
		} 
	}
	if (modalInstance) {
		$modalStack.close(modalInstance.key, result);
	}
}
```
This way developer will be able to achieve this functionality with ease.

**Comment by rvanbaalen** [comment]
Check the current source code. If I'm not mistaken we have a `$modalStack` these days. Retry in UI Bootstrap 0.13 and Angular 1.3 please. Re-open if this is still an issue.

**Comment by blongstreth** [comment]
This would be very handy,  almost necessary if one wants to close specific modals after a route state change. Unfortunately, the $modalStack doesn't expose the openedWindows variable or the wrapper methods listed above (which is preferred).
