### ISSUE TITLE
Accordion - Always show one content area.

### ISSUE THREAD

**Issue by niemyjski** [angular-ui/bootstrap#3023]
I'm not seeing this in the docs, but is it possible to always show one content area.. It seems kind of crazy that you could have all of the collapsed. It seems like you would always want one open if you don't specify that one shouldn't be open.

**Comment by rvanbaalen** [comment]
Please ask implementation questions on StackOverflow. We'll be happy to answer your questions there. 
https://github.com/angular-ui/bootstrap#need-help
