### ISSUE TITLE
Modal doesn't open when there are already promises running.

### ISSUE THREAD

**Issue by dietergeerts** [angular-ui/bootstrap#3024]
I'm trying to create a busy indicator with the modal dialog. When doing a call that returns a promise, I call the modal and open it, giving the promise in the resolve objects in order to close it by itself. Now the $modal.open is called before the promise ends, that I can say for sure, but the controller is only instantiated when the promise has ended, which should not be happening. I think this is a bug in the modal dialog service.
EDIT: I'm using version 0.8.0

**Comment by epicleptico** [comment]
I have the same issue. In my modals i have dependencies in some data objects that must be attached be AJAX call. 

The problem there is that modal only opens when all dependencies are resolved and this make the UI confusing.

I just forked your Plunkr for modal: [Plunkr](http://plnkr.co/edit/FWH8ww)

**Comment by epicleptico** [comment]
Just saw https://github.com/angular-ui/bootstrap/blob/master/src/modal/test/modal.spec.js#L367-L378 and this is what we don't want.

I was working on a fix that just show loading screen while the resolve of the modal are working. Here is a [Plnkr](http://plnkr.co/edit/NIDUnKtLyBIWQJ82Y0XL?p=preview).

If want take a watch to the fix look at https://github.com/epicleptico/bootstrap/tree/fix3024-waitForController.
 

I am not going to make pull request if this test is against what i need to

**Comment by pkozlowski-opensource** [comment]
@epicleptico if you don't want to wait for the data before opening modal just fetch them from a controller. Not sure why / what change would be needed in this library to accomodate your use-case...

**Comment by epicleptico** [comment]
Just thought that resolve was for dependence resolving. 

Then I need to manage dependencies resolving in all controllers? May not be better to have it managed by modal?

-----Mensaje original-----
De: "Pawel Kozlowski" <notifications@github.com>
Enviado: ‎04/‎02/‎2015 18:04
Para: "angular-ui/bootstrap" <bootstrap@noreply.github.com>
CC: "Vicente manuel aleixos bellido" <alfixos@gmail.com>
Asunto: Re: [bootstrap] Modal doesn't open when there are already promisesrunning. (#3024)

@epicleptico if you don't want to wait for the data before opening modal just fetch them from a controller. Not sure why / what change would be needed in this library to accomodate your use-case...

**Comment by wesleycho** [comment]
@epicleptico that is correct - using resolve may not make sense in that case, and it might make more sense to just make the request from your controller.

I am closing this issue as it appears to be a usage issue.
