### ISSUE TITLE
Datepicker popup's initial format is broken in angular 1.3.X

### ISSUE THREAD

**Issue by rustygreen** [angular-ui/bootstrap#3025]
The datepicker popup's initial display value does not use the passed in format. After you select a value for the first time, it will display it property (using the passed in format).

Here is the angular-ui websites "datepicker" Plunkr with only the version of angular changed to 1.3. All 1.2 versions work great, it's only when using Angular 1.3:
[Plunkr](http://plnkr.co/edit/j0uVkyCTYDFQnNqEHtiJ?p=preview)

**Comment by uberspeck** [comment]
+1

**Comment by antoinepairet** [comment]
Closing as it is a duplicate of #2659 
We will deal with it ASAP

**Comment by luongvanphuc** [comment]
Hi, it seems that the issue is back again in angular 1.5.0 (beta):
http://plnkr.co/edit/cg1Uj5kF8fNAaNuTvxVY?p=preview

**Comment by icfantv** [comment]
@luongvanphuc, would you mind please filing a new issue and referencing this one rather than piggy-backing?  It helps us track it better.  Thanks.

**Comment by luongvanphuc** [comment]
@icfantv, sorry for that :-)
