### ISSUE TITLE
backdrop.html/window.html in different location

### ISSUE THREAD

**Issue by deadpickle** [angular-ui/bootstrap#3026]
On my webserver I prefer to keep scripts separate from my apache server directory. I have bower (with ui-bootstrap) installed at /var/www/bower_components and my webserver at /var/www/deadpickle. When an item is clicked and the modal is to display I get a 404 on the backdrop.html file. It looks like this is hard coded in modal.js at line 64. I am hoping there is a way to set my own path to the template files.

**Comment by RobJacobs** [comment]
@deadpickle The templateUrl defined on the modalBackDrop directive is actually looking to the $templateCache to retrieve the backdrop.html.  The template files are included in the ui-bootstrap-tpls packages and injected into the $templateCache for you.  Closing this for now.

**Comment by pkozlowski-opensource** [comment]
@RobJacobs is right. This is covered in FAQ: https://github.com/angular-ui/bootstrap/wiki/FAQ#im-using-modal-service-but-it-cant-find-its-templates

**Comment by abobwhite** [comment]
I just found this issue myself. I figured out that my actual request was to ```template/modal/backdrop.html?lang=en_US``` and the templateCache only had ```template/modal/backdrop.html```. By hardcoding the ```?lang=en_US```, it worked. I haven't yet figured out how to make this work dynamically since my $httpProvider appends the locale at the end of each request...
