### ISSUE TITLE
no option to set initial date calendar month view upon opening datepicker window?

### ISSUE THREAD

**Issue by git-status** [angular-ui/bootstrap#3027]
minDate seems to prevent selecting dates prior than this value. however the datepicker window will still focus on dates before minDate, I can't seem to find how to do this without setting my datepickers model value.. I want it to function like the start and end date example from bootstrap 2 datepicker where the end  dates selectable and shown are based on the startDate.

**Comment by rvanbaalen** [comment]
Please provide a plunkr reproducing this problem with UI Bootstrap 0.13.0.

**Comment by wesleycho** [comment]
Closing due to lack of response & reproduction.
