### ISSUE TITLE
Directive inside transcluded tab header doesn't have access to outside DOM

### ISSUE THREAD

**Issue by demsey2** [angular-ui/bootstrap#3028]
here is an example http://jsfiddle.net/demsey/kgqsdfo4/2/  , there is an error in console 
> Error: [$compile:ctreq] Controller 'outer', required by directive 'inner', can't be found!

how you can see inner directive can't get access to outer controller
I'm not sure if the problem is with Angular or Angular-UI

I tried to debug it and I found that tab-heading element doesn't have a parent node. here is the function from angular.js and element.parentNode at the bottom
```javascript
function jqLiteInheritedData(element, name, value) {
  // if element is the document object work with the html element instead
  // this makes $(document).scope() possible
  if (element.nodeType == NODE_TYPE_DOCUMENT) {
    element = element.documentElement;
  }
  var names = isArray(name) ? name : [name];

  while (element) {
    for (var i = 0, ii = names.length; i < ii; i++) {
      if ((value = jqLite.data(element, names[i])) !== undefined) return value;
    }

    // If dealing with a document fragment node with a host element, and no parent, use the host
    // element as the parent. This enables directives within a Shadow DOM or polyfilled Shadow DOM
    // to lookup parent controllers.
    element = element.parentNode || (element.nodeType === NODE_TYPE_DOCUMENT_FRAGMENT && element.host);
  }
}
```

**Comment by rvanbaalen** [comment]
Can you please re-test in Angular 1.3 and UI Bootstrap 0.13?

**Comment by demsey2** [comment]
hi, I tried with Angular 1.3 and 1.4 including Bootstrap 0.13. The same issue in both cases.

http://jsfiddle.net/kgqsdfo4/3/

**Comment by wesleycho** [comment]
Should note that this is the exact issue that is causing issues in #4624.

This may not be solvable, but at the least we can investigate what can we do.

**Comment by wesleycho** [comment]
Closing for the same reason as https://github.com/angular-ui/bootstrap/issues/4624#issuecomment-151517752 - notes on investigation there.
