### ISSUE TITLE
data-toggle now working with jquery 1.3.2

### ISSUE THREAD

**Issue by SwalfFzo** [angular-ui/bootstrap#3031]
Hi to All , 

I change the jQuery File from jquery-1.11.1.min to jquery-1.3.2.min because I want to use jquery.blockUI , for my web application header I have 'navbar-btn sidebar-toggle' with data-toggle 'offcanvas' which is not working , until  I will delete the jquery-1.3.2. Please can any one help me to solve this issue

**Comment by BobbieBarker** [comment]
Unfortunately this project no longer supports the use of jquery with our native angularJS directives.
