### ISSUE TITLE
Typeahead: ng-change not trigger when value is selected

### ISSUE THREAD

**Issue by ghoullier** [angular-ui/bootstrap#3036]
Angular 1.3.3
UI-Bootstrap: 0.12.0
[Plunker](http://plnkr.co/edit/JT6LPsFXdJfXEJcnogID?p=preview)

```
<div class="container-fluid" data-ng-controller="TypeaheadCtrl">
  <h4>Static arrays</h4>
  <pre>Model: {{selected | json}}</pre>
  <pre>Value: {{copied | json}}</pre>
  <input type="text" data-ng-change="copied=selected" data-ng-model="selected" data-typeahead="state for state in states | filter:$viewValue | limitTo:8" class="form-control">
</div>
```

ng-change is correctly triggered when user type a value in the input field.

ng-change is NOT triggered when user type several chars and press select a value

**Comment by wesleycho** [comment]
Confirmed [here](http://plnkr.co/edit/TwCEn93DhmoYcpnPxded?p=preview) with up to date UI Bootstrap (as of this comment).

**Comment by RobJacobs** [comment]
Possibly related to PR #3376

**Comment by wattazoum** [comment]
Workaround : use 'ng-change' AND 'ng-selected'

**Comment by ghoullier** [comment]
@wattazoum Plunker?

**Comment by wattazoum** [comment]
here is [the Plunker](http://plnkr.co/edit/q0cthGrC7h90GCoMd8ml) .

**Comment by wesleycho** [comment]
Note that this is still [current behavior](http://plnkr.co/edit/l4mifbqMauJNjOl3lskM?p=preview).

Investigating how `ng-change` works, the Angular documentation notes that it is for [when the input value changes](https://docs.angularjs.org/api/ng/directive/input). This implies that `ng-change` is meant to run when the user modifies the input and the change listeners run in the process of converting the view value to the model value. In light of this, I do not believe that we should work around this, and @wattazoum's workaround is sufficient and preferred.

**Comment by bernhard-hofmann** [comment]
In case it helps someone looking for a solution, I found `ng-selected` fired far too many times for my liking but `typeahead-on-select` worked as expected (invoked once upon selection).

**Comment by Abhith** [comment]
@bernhard-hofmann it helped, thanks.

**Comment by akshaysinghi** [comment]
better use:-
 typeahead-on-select="functionName(arguement)"

**Comment by jbmyid** [comment]
@akshaysinghi 
typeahead-on-select="functionName(argument)" 
it will trigger only if the item is selected but not the model it self. Like  when them match not found.

**Comment by webcore-it** [comment]
Here is a Plunker to show the behavior @jbmyid describes: http://plnkr.co/edit/FcZDMksqFhkVjNo7ZpIC?p=preview

My solution is to call the same function with `ng-change` **and** `typeahead-on-select` like so:

```html
    <input  type="text" 
      ng-model="vm.model" 
      ng-model-options="{ debounce: { default: 500, blur: 100 } }" 
      ng-change="vm.functionName()"
      typeahead-on-select="vm.functionName()"
      uib-typeahead="state for state in vm.states | filter:$viewValue | limitTo:8">
```

**Comment by sabareeshkk** [comment]
great..thanks

**Comment by arunadhumal18** [comment]
IE11 issue : Value is not getting changed when user selects value second time, the value is getting empty string but not the latest selected value.

**Comment by raviook** [comment]
thanks @bernhard-hofmann
