### ISSUE TITLE
Adding styles to Accordion

### ISSUE THREAD

**Issue by nithyanv** [angular-ui/bootstrap#3038]
Hi,

I couldn't find any options to style Accordion. ngClass and ngStyle don't work. Am I missing something?

**Comment by RobJacobs** [comment]
@nithyanv @OliPelz You just need to wrap your accordion heading and content in another element (div) and use the ng-class on that.  Something like so:

    <accordion>
        <accordion-group ng-repeat="phenoGroup in exp.phenotypeGroups">
            <accordion-heading>
                <div ng-class="{phenoListHighlighted : pheno.isHighlighted}">
                    {{phenoGroup.phenoName}} ({{phenoGroup.countPhenos}})
                </div>
            </accordion-heading>
            <div ng-class="{phenoListHighlighted : pheno.isHighlighted}">
                Hello,hidden world
            </div>
        </accordion-group>
    </accordion>

Closing this for now.
