### ISSUE TITLE
Carousel and safari

### ISSUE THREAD

**Issue by BotanMan** [angular-ui/bootstrap#3041]
Carousel stops to slide after some time. So if I open page and wait for 10-15 minutes (use another tabs, some action else) carousel stops and buttons (prev, next) don't work. If I refresh page or go to another route and come back it start to work again.

I use 'disable-animate' directive to remove ngAnimate influence on the carousel.

I can reproduce this only in Safari. So is there any suggestion?

**Comment by lukaszjurys** [comment]
+1

**Comment by karianna** [comment]
Needs more info e.g. plunkr & angular/bootstrap/angular-ui versions

**Comment by lukaszjurys** [comment]
hey, I've got it with
-AngularJS v1.3.0
-AngularUI 0.12 ( only carousel compontent )
-ngAnimate disabled by this hack
`    
angular.module('ui.bootstrap.setNgAnimate', ['ngAnimate']).directive('setNgAnimate', [
    '$animate', function($animate) {
      return {
        link: function($scope, $element, $attrs) {
          $scope.$watch(function() {
            return $scope.$eval($attrs.setNgAnimate, $scope);
          }, function(valnew, valold) {
            $animate.enabled(!!valnew, $element);
            return void 0;
          });
          return void 0;
        }
      };
    }
  ]);
`
I can't use next/prev when I replaced collection of slides (if I use carousel-indicators before click on next/prev they're works again).
if ngAnimate with hack has been removed, everything works fine.

**Comment by BotanMan** [comment]
AngularJS v1.2.16.
When I use ngAnimate - I need to disable it for carousel by using $animate.enabled(false, element);
After these I get frozen carousel in Safari after a while (10-15 minutes)

**Comment by wesleycho** [comment]
Can we have a reproduction of this on [Plunker](http://plnkr.co/)?

**Comment by wesleycho** [comment]
The carousel now fully supports ngAnimate, so reading this ticket more carefully, I think it is now fixed by https://github.com/angular-ui/bootstrap/commit/431b9c76b05f2bab693e05b60d3c50b51a1459ee#diff-30d1e93e1beedfb395ccbc9fb0658f81.

Let us know if this is still an issue.
