### ISSUE TITLE
Clearing/reverting a Typeahead if no value is selected from the dropdown

### ISSUE THREAD

**Issue by rupe120** [angular-ui/bootstrap#3043]
I detailed the issue in this post: http://stackoverflow.com/questions/27253243/angular-ui-bootstrap-clear-model-value-when-a-typeahead-dropdown-value-is-not

The gist of it is this. The Typeahead is selecting an object. If the user just types a few characters and then leaves the field without selecting an item from the dropdown, the model value is set to the string value of the field. This case seems like it should instead revert the field to what ever value was previously displayed. 

Additionally, it seems like there should be an option for an empty string to be converted to undefined.

Alternatively am I just thinking of this incorrectly? Should I instead separate the type ahead from the scope value that is actually being posted to the server?

**Comment by wesleycho** [comment]
This sounds reasonable. PRs are welcome!

**Comment by dmitriz** [comment]
I am using this directive in my app for the location search, and from this perspective, I find the current behaviour most convenient. 

That is, if the user types few characters and leaves without selecting a match, I want my app to know this! So I can write my special logic dedicated to deal with that case, and it is very useful to have that partial typed string in my model. The "job" of the `typeahead` directive was to give me the complete information about the situation - the partial string and the fact that no selection was made. I'd rather have this plain information than any sort of additional magic. That keeps a clean separation of responsibilities.

As user, if I started typing something and lost my attention elsewhere, I would be confused if what I typed would be gone. I'd rather have it exactly as I left. 

This is just my view. Any counter-arguments to challenge it are welcome :)

**Comment by rupe120** [comment]
@dmitriz I do see where your workflow would be desirable in certain situations. For my purposes I ended up creating my own typeahead-advanced control based on the typeahead to behave more like a drop down list. For me it was more logic to handle the dual scenarios of the model value either being an object or a partial unmatched search string. 

With that said, I would absolutely make it configurable in any pull request I would develop.

I would love to be able to create a pull request and I'm planning on it, though I would need to do quite a bit of clean up. There was a lot of trial and error stuff that can be tidied up.

**Comment by mvarshavsky** [comment]
@rupe120, would you be able to share what you have to date? I'm in a similar boat as you, I believe there's absolutely a use case to have typeahead in a "dropdown" mode. This is great for selecting against an enum - I still want the usability of narrowing down options based on user-typed input, but it has to:
1. Show list of options upon focus (there are long discussions of using typeahead-min-length="0" to achieve it, and there's even an accepted PR that shows results if you type 1 char and then backspace, but still doesn't expand the list with empty query on focus - preplexing!)
2. If a user input matches nothing and the field is blurred, roll back to the previous value. It would seem that would be desired behavior with typeahead-editable="false", but it isn't.

I'm also struggling with how little hooks the code leaves for extension. Everything is private. At least for things on the scope, I can attempt to decorate typeahead with my own controller, that then sets up specific watchers. But for things like `getMatchesAsync` I'm at a loss...

**Comment by rupe120** [comment]
I apologize for the delay here. I wanted to create a pull request but I just haven't found the time. So here's what we are currently using. Keep in mind that this was my first foray into Angular, let alone Bootstrap.UI

https://gist.github.com/rupe120/9d095f5d43535e9b2786

The directive is called `typeahead-advanced` and is based on what is now more than likely an older version of the `typeahead` directive. I did try to preserve all of the functionality of the original directive though I think I duplicated some of it as well. 

The properties I added were the require selection, show popup on click, and manage popup height. The manage popup height ensures the popup (dropdown) isn't cut off by the bottom edge of the view port.

    <input type="text"
            id="case-organization-select"
            name="organization"
            typeahead-advanced="organization as organization.name for organization in getOrganizationsByProjectId($viewValue)"
            typeahead-input-formatter="case.organization.name"
            typeahead-require-selection="true"
            typeahead-display-popup-on-click="true"
            typeahead-manage-popup-height="true"
            ng-model="case.organization"
            ng-disabled="!case.project"
            ng-change="organizationChange()" required
            class="form-control" />

Let me know if you have any questions

**Comment by mvarshavsky** [comment]
@rupe120 - thanks for sharing!

**Comment by rupe120** [comment]
You're welcome. 

One other trick that I found useful was the use of the typeahead input formatter property. This gives you control of the display within the the input box after the typeahead selection is made.

**Comment by wesleycho** [comment]
With `typeahead-editable="false"`, this feature should work now in `master` due to 1d9294c8e6b0d888fd77317cb634dd37bb9b5094.
