### ISSUE TITLE
Datepicker (ui.bootstrap.datepicker) -> Display format is broken

### ISSUE THREAD

**Issue by stevo-knievo** [angular-ui/bootstrap#3047]
It works fine until angular 1.2.9. But with latest version (1.3.5) the display format doesn't work.
I know - the website says "tested with 1.2.16". But I thought I will let you guys know. Is it a bug? Or should I develop my app with 1.2.16 if I wanna use ui.bootstrap? Thanks Stefan

example:
http://plnkr.co/edit/6xFDPIodBcNRJjXMZkEm?p=preview

**Comment by antoinepairet** [comment]
This commit should have fixed it: https://github.com/angular-ui/bootstrap/commit/5f9afe5a86af0e207eaacd6a9b1f202fd78d7009

see the working plunkr: http://plnkr.co/edit/0EEK4JpvW7GXqbhAgVwJ?p=preview

regrads
