### ISSUE TITLE
[ui.bootstrap.pagination] Make first page index at 0 rather than 1

### ISSUE THREAD

**Issue by F2X** [angular-ui/bootstrap#3052]
[As documented](http://angular-ui.github.io/bootstrap/#/pagination), pagination settings takes a ng-model with a 1-based index , what's really confusing for a code-based approach. 
I think it will be better to make it 0-based, as when your looking for the first page in a pages[n] Array, your not taking it at pages[1] but pages[0]

**Comment by wesleycho** [comment]
It should be noted that this request is a breaking change, and would depart from the typical use case with paginated api.

I am not sure if I agree that this is desired given that. Thoguhts?

**Comment by stuart-harris** [comment]
I agree with wesleycho.  Pagination typically uses a 1-based approach.  A 1-based approach also matches the view behaviour, which imho is appropriate for view controls.  A 0-based approach may, and in most cases would, match the model, but on balance I would prefer 1-based here.

**Comment by wesleycho** [comment]
Closing as this does not appear to be a change that is desired in this project.

**Comment by xiaolei** [comment]
Is it better to make it configurable? default value is 1 based but can be configured as 0 based
