### ISSUE TITLE
Tab does not advance input field focus in Firefox when Typeahead options are open

### ISSUE THREAD

**Issue by antch** [angular-ui/bootstrap#3053]
Currently, in Firefox if you have the typeahead drop-down open and press Tab, focus does not advance to the next input field on the page.  This appears to work sporadically in Chrome.

Tested with ui-bootstrap 0.11.2 and Angular 1.3.

**Comment by rvanbaalen** [comment]
Bootstrap 0.11 does not support Angular 1.3. Retest with UI Bootstrap 0.13.0 and Angular 1.3 and re-open if this is still an issue.

Also, if this is still an issue, provide a plunkr.
