### ISSUE TITLE
Modal result promise is resolved prior to animations completing when closing the modal

### ISSUE THREAD

**Issue by nauticalcoder** [angular-ui/bootstrap#3057]
Angular version: 1.2.16
Angular Bootstrap version: 0.12.0
Bootstrap version: 3.1.1
http://plnkr.co/edit/xNCeqlj9cXKjTtQOSoiN

I am trying to have a message box display after the modal is closed.  The code for opening the message box is in the result promise handler.  When close is called on the modal instance, the message box is displaying, then once the message box is closed, the modal is closing.  After investigating, the issue appears to be related to the close animation.  I have included a proposed fix for this issue that involves moving the promise resolution so it happens once the animation is complete.
Pull request a proposed solution:
https://github.com/angular-ui/bootstrap/pull/3056

**Comment by chrisirhc** [comment]
Should investigate this only after #2724 is merged.

**Comment by wesleycho** [comment]
I will take a look at implementing this sometime in the next couple of weeks - this requires branching out the logic depending on a configuration value.

**Comment by wesleycho** [comment]
Closing as resolved via e9c4977dc4a326b19694ae4e12784d22a90f1f99
