### ISSUE TITLE
Datepicker Controller cannot be named "DatepickerController"

### ISSUE THREAD

**Issue by ozomer** [angular-ui/bootstrap#3062]
http://plnkr.co/edit/Q7ryAsC5UxnS2FFq3tDy?p=preview
vs
http://plnkr.co/edit/niAUKww0cFH1VehZoP0L?p=preview

**Comment by dmitriz** [comment]
Maybe close and link to:
https://github.com/angular-ui/bootstrap/issues/3396

**Comment by chrisirhc** [comment]
Good point. Closing as duplicate of #3396 .
