### ISSUE TITLE
Pagination : show first and last page number when limiting numbers

### ISSUE THREAD

**Issue by MaitreDede** [angular-ui/bootstrap#3064]
Hi,

Is it possible to add an option to always have first page number and last page number ?

Like this :

    [first][prev][1][...][5][6][7][...][42][next][last]

Replacing "first-text" with "1" and "last-text" with the page count makes pages number dupplication :

    [1][1][2][3][...][42]

Thanks

**Comment by wesleycho** [comment]
I do not believe we want to support this feature, as this adds complication. You are more than welcome to make changes via custom templates and CSS to accomplish your purpose though.

**Comment by matiishyn** [comment]
hm... need the same functionality. @MaitreDede have you implemented it?

**Comment by Thilak8654** [comment]
Thanks for the great pagination. i am appending pagenumbers to work with browser back or forward buttons, if i click 4th page from second page, after click browser back button, url and view is changing but not the active class, can anyone please help me how to set active class, when i use browser back or forward button.

**Comment by bijaykush** [comment]
Hi,
Is it possible to show last and first 3 page numbers as shown below: 

[1][1][2][3][...][40[41][42]
