### ISSUE TITLE
angular ui popover not shown if it is used inside accordian

### ISSUE THREAD

**Issue by raghavareddy** [angular-ui/bootstrap#3069]
I am trying to add a custom directive which contains a input element and if there is a invalid value it shows a angular ui popover message. If the directive is used in side the accordion popover is not shown. It looks there is some problem with child scope but we are not identified the exact problem. Can any one please help?

Link to plnkr is 

http://plnkr.co/edit/TaHaNtfetnCzmlSRmTH3?p=preview

**Comment by rvanbaalen** [comment]
I dont see popovers in your plunkr. Can you update it with Angular 1.3 and UI Bootstrap 0.13 to test of this is still an issue?

**Comment by wesleycho** [comment]
Closing this as invalid - the example is not using the popup correctly.

Please open a new issue with a proper reproduction if this is indeed an issue.
