### ISSUE TITLE
datepicker-options doesn't work inside directives

### ISSUE THREAD

**Issue by vitaly-t** [angular-ui/bootstrap#3070]
Once I wrapped up datepicker-popup inside a directive, its attribute datepicker-options stopped resolving.

The only way I can make it work inside a directive is with in-line values as this:
```
datepicker-options="{startingDay:1,showWeeks:false}"
```

Even if I use {{ }} syntax inside, it still doesn't resolve. In the meantime, outside directives the attribute works as expected.

**Comment by jmca** [comment]
I'm having the same exact issue.

**Comment by karianna** [comment]
Plunkr please.

**Comment by facupedrazzini** [comment]
Hi, here is a plunker:

http://plnkr.co/edit/YyiKrJf2LgIW9nVHM491?p=preview

the datepicker-options attr doesn't work when you use the inline datepicker directive. You have to pass every option as a separate attribute.

**Comment by wesleycho** [comment]
I would recommend putting this in a variable on $scope or your controller in your directive wrapper.

Without a Plunker though, there is not much anyone can do to verify this or tinker with prospective fixes though. Feel free to open a new issue with a suitable reproduction on Plunker if it is still an issue.

**Comment by stijnherreman** [comment]
For anyone reaching this page like I did: you need to set datepicker-options in the pre-link. An example in TypeScript:

```typescript
link = {
    pre: (scope: IDatepickerScope, element: ng.IAugmentedJQuery, attrs: ng.IAttributes, controller: {}, transcludeFn: ng.ITranscludeFunction) =>
    {
        scope.datepickerOptions = {
            startingDay: 1,
            showWeeks: false
        };
    },
    post: (scope: IDatepickerScope, element: ng.IAugmentedJQuery, attrs: ng.IAttributes, controller: {}, transcludeFn: ng.ITranscludeFunction) =>
    {
        scope.isOpen = false;

        scope.open = () =>
        {
            scope.isOpen = true;
        }
    },
}
```

**Comment by pegasuspect** [comment]
This should be in the documentation where people can see, because lots of people who benefit from angular uses directives a lot in order to make their code modular. Thanks a lot @stijnherreman :+1: :100:
