### ISSUE TITLE
Datepicker : Date selection problem

### ISSUE THREAD

**Issue by Lospepes** [angular-ui/bootstrap#3071]
Hello,

When I try to select a day with popup, why the model is one day before my real selection ? You can see it on the "The wrong date is" example.

![error](https://cloud.githubusercontent.com/assets/1099230/5365651/0342e8b4-7fee-11e4-8d7b-63f28f13a9f6.png)

http://plnkr.co/edit/zsKUoYQCfEhJMIHE9A0Z

Thank you for your help.

Los

**Comment by rvanbaalen** [comment]
We do intend to refactor the datepicker to use momentjs indeed @bierdok. Unfortunately, there is still a lot to be done before we reach that moment.

**Comment by wesleycho** [comment]
Closing, as the timezone issue has been fixed in 0.14.3.
