### ISSUE TITLE
Closing the tab changes the ui-router state to default state - 0.12.0

### ISSUE THREAD

**Issue by seenimurugan** [angular-ui/bootstrap#3073]
My application is broken after i upgrade to 0.12.0 from 0.11.0. The issue is, If i close the tab, the state(ui-router) changes to the default state. It is hard to explain the problem, so i created the simple plunker @ 

http://plnkr.co/edit/Yigj4VR10zTAMG9DQo6C?p=preview

If you close any of the tab in the settings page then you are taken to the home page. I expect to stay on the settings page with the first tab being selected after closing the tab. 

If you comment the 0.12.0 version in the plunker and un comment 0.11.0 version, then the application works as expected.

I think the issue is to do with the fix for the following bug - 

https://github.com/angular-ui/bootstrap/pull/2763 (or)
angular-ui/bootstrap/issues/2290. 

There is no error message printed on the console so it is hard to identify the issue.

**Comment by wesleycho** [comment]
I was able to fix this behavior with `$event.preventDefault()` [here](http://plnkr.co/edit/Vs2uWqd1ie5mUQqUH8Vm?p=preview).

**Comment by karianna** [comment]
@wesleycho So should this be closed as a resolved via support?

**Comment by wesleycho** [comment]
I would like more info first before closing.

**Comment by seenimurugan** [comment]
Great. The solution works. Thanks a lot. But i feel this is bit of hack rather than a fix. Anyway thanks.

**Comment by chrisirhc** [comment]
This is a bug with Angular 1.3.5 . 
Plunker is working after upgrading to 1.3.13 : 
http://plnkr.co/edit/EKBQZhz084WRfYPSJuDn?p=preview

**Comment by seenimurugan** [comment]
Yes, it is working after angular upgrade. You are a star.

**Comment by pm98765** [comment]
I am working with AngularJS 1.4.2 and UI-BootStrap 0.13.3 and issue is coming again. With the above solution of $event.preventDefault(), issue goes away. But is it a recommended solution?

**Comment by icfantv** [comment]
I'm on my phone here so I can't easily check for sure.  But if this is the issue I think it is and with the version you are using, yes, it is the recommended solution.  The issue appears to be the use of anchor tags and how browsers are interpreting clicks on them.  We've changed the template in `master` to use `<div>` instead which fixes that issue but does create an accessibility one.  I can't easily find the issue numbers but they are there if you want to look.

**Comment by pm98765** [comment]
Thanks @icfantv
