### ISSUE TITLE
[Datepicker] Repeated months

### ISSUE THREAD

**Issue by ayakovlevgh** [angular-ui/bootstrap#3079]
There is an issue with repeated months in some years in Russian time zones (Moscow UTC +3, Novosibirsk UTC +6). 
The issue occurrs only in Firefox (version 33.0, 34.0). In Google Chrome everything is OK.
Angular bootstrap version: 0.12.0.
Screenshots are attached.

![datepicker2](https://cloud.githubusercontent.com/assets/10140049/5373183/fc5bbf5a-8063-11e4-8e36-715dc98a57b7.png)
![datepicker1](https://cloud.githubusercontent.com/assets/10140049/5373185/ffb833d6-8063-11e4-9a9d-668ef758945d.png)

**Comment by chrisirhc** [comment]
Is this related to https://bugzilla.mozilla.org/show_bug.cgi?id=1079720 ?

**Comment by ayakovlevgh** [comment]
Partially yes.
Actually, I could reproduce three cases of this problem:

1. Win 7; GMT +3 /+6; current date = Dec 10, 2014.

   Problem with `new Date(2014, 0, 1)` and some other dates.

   This case is described in bugzilla's ticket you are referencing to.

2. Win 7; GMT -3; current date doesn't matter.

   Problem with `new Date(2016, 9, 16)` and lots of other dates.

   Also described in a topic on [stackoverflow](http://stackoverflow.com/questions/5859959/dst-problem-storing-date-in-javascript-date-object)

3. Ubuntu / Debian; GMT +3/+6; current date doesn't matter.

   Problem with `new Date(1984, 3, 1)`, `new Date(2040, 3, 1)` and some others.

I suppose there could be more cases. And I think even if Firefox developers fix it, there is no garantee that such problem won't appear again in Firefox or other browsers.
