### ISSUE TITLE
Typeahead - value is not selected when item is clicked (Chrome)

### ISSUE THREAD

**Issue by fracz** [angular-ui/bootstrap#3083]
Google Chrome 39.0.2171.71
Tested on example on project's page: http://angular-ui.github.io/bootstrap/#/typeahead
1. Type "j" in the first field (Static arrays)
2. "New Jersey" pops up
3. Click the "New Jersey" item
4. Typeahead suggestions disappear but the model is not updated; I still see the "j" letter in the field

When in step 3. I hit enter instead of click, model is updated to "New Jersey" as expected.
In Firefox clicking items seems to be working.

**Comment by g00glen00b** [comment]
OMG, I spent 2-3 hours because I didn't understand why I couldn't get it to work properly.... . But indeed, I disabled Batarang and suddenly it works again.
