### ISSUE TITLE
tooltip not working with ngAnimate

### ISSUE THREAD

**Issue by Tim-Erwin** [angular-ui/bootstrap#3084]
As soon as I include ngAnimate in the dependencies of my application, the tooltips don't show up any more. The DOM elements are there and look like that:
```
<div class="tooltip bottom" ng-class="{ in: isOpen(), fade: animation() }">
  ...
</div>
```

The problem here is that although *isOpen()* resolves to *true* (I verified with inserting `{{ isOpen{} }}` into the template) the class *in* is not set. (Without *in* tooltips are invisible.)

I'd provide you with a plnkr, but it seems to be down. Just take any working app with a tooltip and add *ngAnimate* into the mix. e.g.

```
<html>
<head >
    <script src="https://code.angularjs.org/1.3.0/angular.min.js"></script>
    <script src="https://code.angularjs.org/1.3.0/angular-animate.min.js"></script>
    <script src="ui-bootstrap-tpls.min.js"></script>
    <script  language="javascript" type="text/javascript">
        angular.module('test', ['ui.bootstrap', 'ngAnimate']);
    </script>
</head>
<body ng-app="test">
    <a tooltip="asdf" tooltip-trigger="click">bla</a>
</body>
</html>
```

**Comment by chrisirhc** [comment]
Relates to #3375

**Comment by chrisirhc** [comment]
Tooltip should now be fully compatible after #3510 . Closing.
