### ISSUE TITLE
dropdown closes on focus

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#3093]
I want to trigger dropdown open on focus on input field. But it openes and suddenly closes every time I focus. With button toggle everything is ok. Here is example: http://codepen.io/piernik/pen/ByKRwE

**Comment by RobJacobs** [comment]
@piernik What is happening is the dropdown directive - dropdownService open function binds the $document click event to the closeDropdown function.  So when you click on the input box, the ng-focus event fires to open the dropdown, then the document click event is fired to close the dropdown.  If you 'tab' into the input element, you will notice everything works as you expect.  You can over come this by blocking the click event on the input element like so: 
    ng-click="$event.preventDefault(); $event.stopPropagation();" 
or by calling the show($event) function.  Closing this for now.
