### ISSUE TITLE
a feature about edit popup html

### ISSUE THREAD

**Issue by singleseeker** [angular-ui/bootstrap#3097]
Do we have a way to do this?
![image](https://cloud.githubusercontent.com/assets/520698/5426300/f80633f4-8383-11e4-80bd-f46d77cd327e.png)

I mean edit the popup html in order that we could select today, next week and other option.

thank u.

**Comment by RobJacobs** [comment]
@singleseeker The date picker directive does not offer canned time frame selection buttons, that is something you will need to do by overriding the default date picker template.  Closing this issue for now.
