### ISSUE TITLE
support input[multiple] in Typeahead

### ISSUE THREAD

**Issue by xieranmaya** [angular-ui/bootstrap#3100]
html5 supports input[multiple] like this(http://www.w3.org/TR/html5/forms.html#the-multiple-attribute):
```html
<input type="email" multiple list="datalist" />
<datalist id="datalist">...</datalist>
```
when type comma between each email, you'll get hint.
hope Typeahead can support when you type comma and a new hint shows.

**Comment by wesleycho** [comment]
The complexity of such a feature would require a breaking change since a `,` may be a legitimate string. It also would introduce multiple state checking for the view value, which introduces other issues.

Going to reject this as a feature we are not interested in supporting.
