### ISSUE TITLE
tab is duplicated when using ng-if and binded value for condition is refreshed

### ISSUE THREAD

**Issue by seustachi** [angular-ui/bootstrap#3103]
I have a tab with ng-if condition
```javascript
<tab id="..." heading="..." ng-if='orphanInstances' >
```

And a function in the controller
```javascript
$scope.refresh = function () {
...
     $scope.orphanInstances = data;
...
}
```

If I call refresh() twice, I get the tab twice.

If I replace **ng-if='orphanInstances'** by **ng-hide='!orphanInstances'** I have only one tab, as expected.

AngularJS v1.2.0

**Comment by rvanbaalen** [comment]
Is this still an issue for you in the current master branch? Can you create a plunkr reproducing the problem?

**Comment by wesleycho** [comment]
This does not appear to be an issue still, as can be seen [here](http://plnkr.co/edit/QBhQ5xUb8qcdA9kMyHNN?p=preview).

Closing as resolved.
