### ISSUE TITLE
non-dates are being parsed as valid dates

### ISSUE THREAD

**Issue by bolemeus** [angular-ui/bootstrap#3104]
I have a datepicker on my site, using the following format 'dd-MM-yyyy'.
Because it is possible to manually insert a date I want the datepicker to do some validation on it.

However, when I enter the first digit of the date, for example a 1, the datepicker already assumes it's a valid date. It parses it into the date 1 January 2001. The date picker also fills the model with this incorrect date.

Because I use that date in a function that is called with a ng-change function this causes unwanted behaviour.

Is there something I'm missing, or is this a bug?

PS: this bug also happens in the demo.
http://angular-ui.github.io/bootstrap/#/datepicker#datepicker

**Comment by hewstone** [comment]
+1.  I am having the same problem. Adding a $formatter does not help because the $modelValue and the $viewValue are the same

**Comment by jmayday** [comment]
I think I understand your problem @bolemeus. I also find default behaviour of datepicker not only annoying but just incorrect. I'll prepare some code/example at the evening and let you know.

**Comment by jmayday** [comment]
Hi again. I just created a plunker with newest version of angular-ui (0.12.0) - http://plnkr.co/edit/yNuSZPiQYFn0Zy2COPdA
It seems like I'm not able to recreate  your problem @bolemeus (typing just '1' as date doesn't put any valid date in model).

**Comment by jmayday** [comment]
I was hoping it's fixed but I checked once again and unfortunately it's still broken.

I have to admit it works fine under Firefox, but not udner Chrome (couldn't check it under IE). So I'll prepare some code and let you know anyway.

**Comment by jmayday** [comment]
https://github.com/angular-ui/bootstrap/pull/3288

**Comment by karianna** [comment]
@wesleycho - this could be moved to 0.13.x?

**Comment by bartoszbobin** [comment]
Problem is in 2nd condition:
https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L591

new Date('1');
FF 37.02: Date {Invalid Date}
Chrome 42: Mon Jan 01 2001 00:00:00 GMT+0100 (Central European Standard Time)
IE 11: [date] Invalid Date[date] Invalid Date

I expect from user date in provided format.

**Comment by jmayday** [comment]
@bartoszbobin this behaviour was already described. Have a look at plunker (link provided in my previous post)
