### ISSUE TITLE
Support for multiple date picker popups on a page?

### ISSUE THREAD

**Issue by pjfsilva** [angular-ui/bootstrap#3105]
It seems that the usage of multiple date pickers on a single page doesn't work that well or maybe I'm doing something wrong?

Check this out: 
http://plnkr.co/edit/BDL73NrLGGMjt3p4Gi11?p=preview
1) Click the 2nd button to open the date popup
2) Click the 1st button to open the date popup -> both popups are now open. What I was expecting is that only 1 date popup appears at a time...

Is this a bug or am I doing something wrong?

**Comment by RobJacobs** [comment]
@pjfsilva Your managing the date picker is-open attribute to show/hide the date pickers manually, so you will need to accommodate for that in your ng-click event when calling your open and open2 function.  I handle this by using an array to keep track of open date pickers and calling the open function with an index for that particular date picker.  See this plunkr for an example: http://plnkr.co/edit/vezPCi24kxKiLdZKGf2W?p=preview.  Closing this issue for now.

**Comment by zaknuces** [comment]
Another way to solve this problem without relaying on event stopPropagation is either use '$timeout' or $evalApply when you are updating the property associated with the 'is-open' attribute.
