### ISSUE TITLE
Accordion header with anchor and buttons

### ISSUE THREAD

**Issue by JobaDiniz** [angular-ui/bootstrap#3106]
Two questions about **anchor** and **button** on *accordion-heading*:

1.  *Anchor* tag inside the *heading* does not work. 
2. *Button* inside the *heading* will fire event, but the accordion-group will open and I didn't want that. Whenever user click the button in the heading, the accordion should not be opened.

I guess this behavior is because the *heading* is wrapped with an anchor tag itself.
Any ideas of how to address this?

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
