### ISSUE TITLE
Memory-leak in the typeahead-directive

### ISSUE THREAD

**Issue by p4fg** [angular-ui/bootstrap#3111]
There exists a memory-leak in the typeahead-directive when used in conjuction with angular 1.2 and jQuery (2.1.0). This bug is related to #2485 that was closed without any action and #2658 that was closed with a patch.

JSFiddle that reproduce the leak: http://jsfiddle.net/wq74xo2t/4/

JSFiddle with patched typeahead: http://jsfiddle.net/wq74xo2t/6/

**Comment by rvanbaalen** [comment]
Please reproduce with UI Bootstrap 0.13.0 and Angular 1.3 to confirm this is still an issue and re-open if it is.

**Comment by jimmytheneutrino** [comment]
Hi, I have this issue with UI Bootstrap 0.13.4 and Angular 1.4.9. 
While the bootstrap version is old I think the reason is the same: 
the two lines starting at
https://github.com/angular-ui/bootstrap/blob/master/src%2Ftypeahead%2Ftypeahead.js#L280

My problem seemed to be fixed by unbinding the two listeners on originalScope.$on('$destroy', ...).

**Comment by icfantv** [comment]
@jimmytheneutrino, this looks like a good catch.  Would you mind please opening a new issue for this and referencing this issue?  Also, if you're feeling up to it, submitting a well-written PR would be accepted.  Thanks.

**Comment by RobJacobs** [comment]
The handlers are being removed in the originalScope destroy: https://github.com/angular-ui/bootstrap/blob/master/src%2Ftypeahead%2Ftypeahead.js#L472

**Comment by icfantv** [comment]
Whoops, I missed that.  Thanks @RobJacobs - @jimmytheneutrino the listeners are only added and removed when `append-to-body` is `true`.

**Comment by jimmytheneutrino** [comment]
Good! Note that there was no removal of listeners in version 0.13.4: https://github.com/angular-ui/bootstrap/blob/0.13.4/src/typeahead/typeahead.js 

This means that an upgrade will fix my issue. Thanks!
