### ISSUE TITLE
accordion-header with other directives not working

### ISSUE THREAD

**Issue by JobaDiniz** [angular-ui/bootstrap#3113]
Plunker: http://plnkr.co/edit/tbWNQPVcC7h5dJObEPfh?p=preview
I'm trying to show a button only when the mouse is over the header. (using **ng-mouseover** and **ng-mouseleave**)

How to accomplish that? *(ng-mouseover not working)*

**Comment by RobJacobs** [comment]
@JobaDiniz You need to wrap the accordion-heading content in an element (div) and set the ng-mouseover/mouseleave events on that.  This updated [Plunker](http://plnkr.co/edit/kBhaVWeLminnGeKlpN1n?p=preview) demonstrates that.  Closing this issue for now.
