### ISSUE TITLE
Datepicker completly prevents usage of certain keys.

### ISSUE THREAD

**Issue by oleduc** [angular-ui/bootstrap#3115]
Hello,

The application I'm currently working on heavily uses keyboard shortcuts and as such, I cannot have a library that calls event.stopPropagation() and doesn't provide an option to disable it.

In the datepicker controller:
```javascript
  $scope.keydown = function( evt ) {
      console.log('Key downnned!');
    var key = $scope.keys[evt.which];

    if ( !key || evt.shiftKey || evt.altKey ) {
      return;
    }

    evt.preventDefault();
    evt.stopPropagation();

    if (key === 'enter' || key === 'space') {
        console.log('self.isDisabled(self.activeDate)',self.isDisabled(self.activeDate));
      if ( self.isDisabled(self.activeDate)) {
        return; // do nothing
      }
      $scope.select(self.activeDate);
      focusElement();
    } else if (evt.ctrlKey && (key === 'up' || key === 'down')) {
      $scope.toggleMode(key === 'up' ? 1 : -1);
      focusElement();
    } else {
      self.handleKeyDown(key, evt);
      self.refreshView();
    }
  };
```

There should be a way to disable evt.stopPropagation(); and let the application that uses the datepicker decide if it wants to do something the with the key after it has been pressed.

Pull request is on its way.

# To reproduce, press enter without focusing on a datepicker and then press enter while focusing on the datepicker.
Plunker -> http://plnkr.co/edit/aoDoDtkDg7w6dM7JjajQ?p=preview

**Comment by wesleycho** [comment]
This should be addressed now that #3116 is in.
