### ISSUE TITLE
Pagination always starts on 1 even if a different starting point is passed

### ISSUE THREAD

**Issue by bensampaio** [angular-ui/bootstrap#3118]
Hi,

On my application I need to be able to set the current page on the URL. I'm doing something like: `#/path/to/page?currentPage=2`. Then on my controller I use the `$routeParams` service to read the "currentPage" parameter. I'm passing this value to `$scope.currentPage` and on my view file I have the following:

```html
<pagination boundary-links="true" previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;" total-items="totalItemsBig" max-size="maxSize" ng-model="currentPage" ng-change="paginate()"></pagination>
```

If we consider the example URL above, at Controller load the `$scope.currentPage` will be 2. But when the `ngChange` function is executed it is 1. I also tried to set the value of `ngModel` using paginationConfig on my controller but nothing changed.

Am I doing something wrong? Is there any solution for this problem? Do you have any idea what could be causing this? Thank you!

**Comment by bmccarthyhp** [comment]
I'm having a similar issue. I have currentPage set to 2, but after the initial data call, something somewhere resets the currentPage = 1. I tried @bensampaio suggestion of total-items = Infinity, but that just crashed the browser (memory overflow/leak). Where is currentPage being reset to 1 and why?

**Comment by karianna** [comment]
Plunkr please.

**Comment by mthamil** [comment]
I ran into the same problem with my current page always resetting. After seeing the comment about setting the total to Infinity, I got a hunch. I finally fixed this issue by setting the initial value of my total-items bound property to Number.MAX_VALUE in my controller.

**Comment by phamdt** [comment]
i also have this problem. mthamil's solution didn't work for me.

**Comment by vhpoet** [comment]
Resolved this by rendering the pagination only after resolving the total-items number. 

```
<div ng-if="totalItems">
  <pagination ...>
</div>
```

**Comment by glaidler** [comment]
@vhpoet - you are a genius

**Comment by tfKamran** [comment]
@vhpoet Well, that saved the issue, but it stops my model from changing when I click on it... I don't know why but the binding is lost.

**Comment by aquid** [comment]
@tfKamran Try adding $parent in your model object.
`eg: ng-model="$parent.current_page"`
This should solve your problem
