### ISSUE TITLE
Modal Focus Bug on modal sizechanges

### ISSUE THREAD

**Issue by squadwuschel** [angular-ui/bootstrap#3121]
Hi,

when the modal includes a textarea and the size of the Textarea is changed by ng-focus and ng-blur and the textarea has the focus and then you want to click on the "OK" Button only the textarea size changes but the click event is not fired. (Angular 1.3.4 and 0.12.0 bootstrap ui)

You can check this in the plnkr example:

http://plnkr.co/edit/PEVZU1ViPCEFiAHRiP5j?p=preview

**Comment by rvanbaalen** [comment]
This is not a bug but an implementation question. Please ask on StackOverflow

https://github.com/angular-ui/bootstrap#need-help
