### ISSUE TITLE
ui.bootstrap.accordion - doesn't open when we do status.open

### ISSUE THREAD

**Issue by usercommon252** [angular-ui/bootstrap#3122]
ui.bootstrap.accordion at http://angular-ui.github.io/bootstrap/

When I tried to open the last panel of the accordion given in the example at the above address by using the code
angular.element($0).scope().status.open=true

It opens the accordion in the example page

But, the same doesn't work when I tried with angular Version angular.1.3.7.js and ui-bootstrap-tpls-0.12.0.min.js

Please fix this, because I would like to programmatically open the panels of the accordion

Thanks

**Comment by Foxandxss** [comment]
Yo!

Could you please create a plunker showing the issue? I cannot replicate it.

**Comment by chrisirhc** [comment]
@usercommon252 You should use the is-open attribute instead.

**Comment by Foxandxss** [comment]
If there is a nice plunker with a good use case, I will reopen it.
