### ISSUE TITLE
Progressbar - rounding errors

### ISSUE THREAD

**Issue by Busata** [angular-ui/bootstrap#3123]
Is there a particular reason that the width is being rounded for progress bars?
```javascript
bar.percent = +(100 * value / $scope.max).toFixed(2);
```
This bit is causing some values, such as 75.7156 to be rounded to 75.72, causing the total percentage to be 100.1 which overflows the bar & makes it jump to the next line. As far as I know, css doesn't have an issue with longer fractals (since when I remove the toFixed(2), the bar seems to continue working.

**Comment by wesleycho** [comment]
I'm a bit confused here - is this when using stacked bars?

**Comment by wesleycho** [comment]
This is now fixed in `master` from https://github.com/angular-ui/bootstrap/commit/2e9177e5f6408d691f3e33bcd784bd9a74bd7a55#diff-4a5bfdc9cef7e9cd25b9fdcbb6a59774 .
