### ISSUE TITLE
Disable some specific Keyboard Support for DatePicker component

### ISSUE THREAD

**Issue by lesterlpena** [angular-ui/bootstrap#3125]
Hi Team,
I have a simple datepicker, I override the custom day.tpl.html, and I don't want to show the month.html when the ctrl + up key is press after the pop up is open.
So, I will like to disable the ctrl + up keyboard, but I think I don't have option to do that. Do I have a way to do this?
Thanks in advance.

**Comment by lesterlpena** [comment]
I still having this issue, any help will be appreciated.

**Comment by wesleycho** [comment]
Given that this would regress accessibility of the datepicker, so we do not want to support this - if another goal is desired, that should be made clear in a fresh issue.
