### ISSUE TITLE
Feature Request: Allow custom classes to be applied to tooltips

### ISSUE THREAD

**Issue by HighTechnocrat** [angular-ui/bootstrap#3126]
I would like away to apply custom styling to tooltips using CSS classes. Currently the only way to distinguish between different tooltips in CSS is the direction of the tooltip. Styling the tooltip contents using tooltip-html-unsafe="" works fine, but doesn't allow styling of the tooltip itself.

**Comment by nonplus** [comment]
I need this as well.  I'd be happy to implement this.

Presumably we'd want a `tooltip-class="myTooltipClass"` attribute which would be applied to the popup?
