### ISSUE TITLE
default “instant” date value not visible

### ISSUE THREAD

**Issue by sujaychakraborty** [angular-ui/bootstrap#3128]
Hi, 

Objective : Try to display default “instant” date value.
Issue : I am trying to display $scope.instant ("31/03/2014") value but it is not visible but if i comment datepicker span (<span datepicker-popup) it is able to show the instant date value("31/03/2014").
code: controller :
app.controller('DatepickerDemoCtrl', function ($scope) {
    $scope.instant = "31/03/2014";
    $scope.open = function($event) {
        $event.preventDefault();
        $event.stopPropagation();
        $scope.opened = true;
    };
    $scope.save=function(date){
        console.log(date);
    }
}); 
HTML : 
    <div ng-controller="DatepickerDemoCtrl">
        <div>
            <strong>Instant : </strong>{{instant}}
                <span datepicker-popup="yyyy-MM-d" ng-model="instant" is-open="opened" datepicker-options="dateOptions" ng-required="true" close-text="Close"></span>
                <i data-ng-show="false" class="glyphicon glyphicon-calendar" ng-click="open($event)" style="cursor: pointer"></i>
                <button data-ng-click="save(instant)">save</button>
        </div>

    </div>

**Comment by rvanbaalen** [comment]
Please take a look at https://github.com/angular-ui/bootstrap#need-help
