### ISSUE TITLE
Allow scope to windowTemplateUrl

### ISSUE THREAD

**Issue by FDiskas** [angular-ui/bootstrap#3134]
Allow scope to windowTemplateUrl Now its not working. In windowTemplate cant add some buttons to close the modal and pass additional info like title or something.
there is an not working example. http://plnkr.co/edit/mysjPOXA68NiaXcqDKvA?p=preview
By edditing a modalWindow directive its posible to do all the stuf.
#3133

**Comment by tdhsmith** [comment]
Is there a reason you need to put all that in the window template? You could easily put it all in the content template, which is [exactly what the they do in the docs](http://plnkr.co/edit/GBfncNDIk13gL9Rkunx0?p=preview). It seems to me that the window template option was designed specifically to not require any additional user data.

**Comment by FDiskas** [comment]
the name is "window template" so this is what I used for. I got a window
template and other template for content. Window template is reused in all
modals.
2015 saus. 21 19:15 "t d h smith" <notifications@github.com> rašė:

**Comment by tomalex0** [comment]
@FDiskas  were you able to fix the issue? or any workaround?

**Comment by FDiskas** [comment]
here is a pull request https://github.com/angular-ui/bootstrap/pull/3133

**Comment by wesleycho** [comment]
Closing, as we need more information here.

**Comment by FDiskas** [comment]
What? I posted example and did a pull request. What else did you need? :)

**Comment by wesleycho** [comment]
I need information why this couldn't be accomplished with the existing API - the code appears to indicate that this is not a missing capability, but a use issue. Information is needed as pointed out in #3390 .
