### ISSUE TITLE
Add more maintainers

### ISSUE THREAD

**Issue by antoinepairet** [angular-ui/bootstrap#3135]
@karianna makes a good point in:
https://github.com/angular-ui/bootstrap/issues/2830#issuecomment-67939179

What is the position of the angular-ui team regarding adding more maintainers to the project?
Those new people could triage issues, closing duplicates, dealing with simple PR, etc.
For more complex subjects, it would be great to have a kind of mentorship with 'junior' contributors getting help from 'experienced' ones. It would also help to have a clear roadmap towards support of angular 1.3

@chrisirhc @pkozlowski-opensource what is your opinion? 
I would glad to help.

**Comment by Balrog30** [comment]
I agree completely.  It's a shame to see projects that are very widely used become out of date because the original creator doesn't have time to maintain the code base.  Don't get me wrong, I really appreciate that work done to make all this possible, but if you can't keep up, please invite others on board or pass on the torch.  Is anyone else working on an active fork to get caught up with Angular 1.3?

**Comment by chrisirhc** [comment]
I would love to add more maintainers. If anyone interested in helping out, could you add a comment here with some notes on what you would like to help out in?

@Delapouite I'm hoping that issue gets consideration from Github.

**Comment by karianna** [comment]
Hi there, @johnoliver and I could assist with basic maintenance (merging in doc updates, simple fixes etc).  We're primarily Java/JVM folks at heart though, so we wouldn't be comfortable on the more serious changes.

**Comment by RobJacobs** [comment]
I would like to be able to contribute more, I just need some direction on what would be most helpful.  Easy things to start with like maintaining open issues/pull requests (comments and tags), testing and test cases, documentation.

**Comment by antoinepairet** [comment]
@chrisirhc thanks for taking the time to look at this and giving me write access to the repo. I started to triage issues and add labels to it. 
I would like to get in touch in order to setup a workflow and move forward, especially regarding 1.3 support. Would you be available through skype/email/whatever ?
regards

**Comment by chrisirhc** [comment]
Thanks for looking into the issues. :+1:  I've pmed you.

**Comment by assisrafael** [comment]
I would like to help too.

**Comment by antoinepairet** [comment]
@assisrafael here is a Doodle for our next meeting: http://doodle.com/ipux3dv7v6i5uw8s
Hope you can join us

**Comment by assisrafael** [comment]
Excuse me if this is a silly question, but the times are in what time zone?

**Comment by antoinepairet** [comment]
Europe, Brussels GMT+1.
I should update the Doodle. Rgds

**Comment by assisrafael** [comment]
Thanks.

**Comment by rvanbaalen** [comment]
I suppose this can be closed by now since we have a pretty solid team of maintainers for the time being.
