### ISSUE TITLE
Typeahead: Form gets submitted on key press enter although typeahead-editable="true"

### ISSUE THREAD

**Issue by bogacg** [angular-ui/bootstrap#3136]
I'm using typeahead-on-select='onSelect($item, $model, $label)' to get selected item into another $scope array. It works fine for items in typeahead declaration, but if item is not there, a new item, on keypress enter form gets submitted (onSelect doesn't get called at all).

Is this a bug or intentionally have been made this way? I'm on Angular 1.3.4

If it was made this way intentionally, how I can change this behaviour and fetch that custom entry to onSelect method.
Thanks

**Comment by rvanbaalen** [comment]
Did you use `typeahead-editable="false"`? From the docs:

> `typeahead-editable`  (Defaults: true) : Should it restrict model values to the ones selected from the popup only ?

Can you provide a plunker reproducing this problem? And could you verify if the problem still exists in the latest master branch? Re-opening if you can verify this issue still exists.
