### ISSUE TITLE
Fit pagination to available width

### ISSUE THREAD

**Issue by Hyzhak** [angular-ui/bootstrap#3138]
Is there any way to adapt *max-size* to fix pagination to available width? And prevent dangling of tail of pagination that way

![](https://lh4.googleusercontent.com/-EJ2Ibhzfh5A/VJrGNJNJemI/AAAAAAABCRk/ewnsOBp-NUk/w1162-h210-no/Screen%2BShot%2B2014-12-24%2Bat%2B14.55.45.png)

**Comment by RobJacobs** [comment]
@Hyzhak  The pagination directive simply uses the pagination class from the Bootstrap library, there is nothing the in angular-ui-bootstrap directive that is making this happen.  I tested using the pagination example from the Bootstrap site and noticed the pagination elements would wrap if necessary.  This question would get a better response if asked on Stackoverflow.

**Comment by hyzhak** [comment]
@RobJacobs it is not problem in bootstrap class, it will be the same situation with any classes. It is just question about fitting max-size to available width. What can be done only by code by adapting number of visible pages. So it is not a bug - it is feature request
