### ISSUE TITLE
Changing the value of is-open attribute of a hidden accordion causes transition problems

### ISSUE THREAD

**Issue by idanb11** [angular-ui/bootstrap#3141]
Hi @pkozlowski-opensource ,

When I try to change the value of is-open of a hidden accordion is causes the transition of the collapsing to get stuck in 'collapsing' class and not changing to 'collapse' class.
This problem with the transition is causing the accordion to behave strangely where you need to press the heading twice to open accordion group.

I've read this - https://github.com/angular-ui/bootstrap/issues/90
But it looks like it is still an existing bug. (i use the latest version)...

Any help will be much appreciated...
Idanb11

**Comment by chrisirhc** [comment]
#1675 should fix this
