### ISSUE TITLE
Can't click on checkboxes inside Accordion Heading

### ISSUE THREAD

**Issue by CarlosCuevas** [angular-ui/bootstrap#3145]
Accordion headings allow for markup but can't put clickable checkboxes inside the heading (as you would be able to using bootstrap on its own [i.e. not angular-ui]).

```
<accordion-group>
        <accordion-heading>
            I can have markup, too! <input type="checkbox" id="cantTouchThis" class="mcHammer">
        </accordion-heading>
        This is just some content to illustrate fancy headings.
</accordion-group>
```

**Comment by rvanbaalen** [comment]
Can you please provide a plunker reproducing this issue? And could you verify for me that this is still an issue if you use the current master branch? A lot of bugs have been fixed lately.

**Comment by CarlosCuevas** [comment]
Used the plunker link provided on the accordion example page (http://angular-ui.github.io/bootstrap/#/accordion) as a starting point, which seems to be using the latest version:

http://plnkr.co/edit/QEQoS3V5qcrQkdlL4aIb?p=preview

**Comment by RobJacobs** [comment]
You just need to stop the event propagation, adding:

     ng-click="$event.stopPropagation();"

Will fix the problem.

**Comment by CarlosCuevas** [comment]
thanks

**Comment by shilan** [comment]
stopping propagation only solves the problem of clicking the checkbox, but if you bind checkbox to a model and if the checkbox is initially checked then the first two hits won't work properly!
