### ISSUE TITLE
up/down arrow key issue with typeahead control

### ISSUE THREAD

**Issue by ankitdadhich** [angular-ui/bootstrap#3146]
I have implemented typeahead control, By default in type ahead control they are not setting any max-height or height to list, but as per requirement i have to fix height of list to 110px. So, when we have longer list at a time only 4 data will be shown and rest can be seen by scrolling down. 
Scrolling is working while user click on scroll up/down arrows, but it's not working with keyboard up/down keys.

The problem is explained in steps:
1. Type something i.e "a" to get data in typeahead (list will be populated)
2. Press down-arrow key (focus will be on list item)
3. Press down-arrow key 4-5 time to go further down () When we traverse down to list, scroll is not getting moved.
4. It always show top 4 items in list. Ideal behavior is it should shift.
User is able to scroll by clicking on scroll manually but with arrow key it's not scrolling.

Plunker link to to demonstrate problem: http://plnkr.co/edit/grrAxz158PTShzpxz2f0?p=preview

**Comment by serraventura** [comment]
Looks like the same question and the same person. As it had a solution I'll link the answer here for future searchs.

http://stackoverflow.com/questions/27705490/up-down-arrow-key-issue-with-typeahead-control-angular-bootstrap-ui

**Comment by karianna** [comment]
Thanks for the link

**Comment by MohamedHussainSha** [comment]
how can i solve the problem using JQuery Please help me.
