### ISSUE TITLE
Changes between 0.11.0 and 0.12.0

### ISSUE THREAD

**Issue by cconrad** [angular-ui/bootstrap#3150]
Hi,

I recently upgraded from 0.11.0 and 0.12.0 and while this has many nice fixes, it also seems to be not completely backwards compatible - which is fully understandable given the version numbers - but is there some list of changes available (other than comparing the code for changes) ?

Thanks,
Claus

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md
