### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by pvttwt** [angular-ui/bootstrap#3151]
Hi,

There are millions of people who write from right to left, so we wish to support RTL .

The biggest problem in Bootstrap  that it does not support RTL .

Thank you,

**Comment by yassermzh** [comment]
+1

**Comment by pkozlowski-opensource** [comment]
@pvttwt this project doesn't have any CSS associated but works on top of Bootstrap CSS. This request should be directed to the Bootstrap project itself.

**Comment by blowsie** [comment]
The date picker buttons require changes beyond just css
![image](https://cloud.githubusercontent.com/assets/308572/8674677/63886084-2a37-11e5-986e-cd50ee236ed2.png)

**Comment by georgybu** [comment]
the problem is open dropdown (datepicker, whatever) when you work with RTL layout and your dropdown as appended to body.

Instead 'left' should be 'right'.

Something like this (styles in template should bind to "$scope.style"):

```
      scope.$watch('isOpen', function(value) {
        scope.style = {display: (value && 'block') || 'none'};

        if (value) {
          scope.position = appendToBody ? $position.offset(element) : $position.position(element);
          scope.position.right = $(window).outerWidth() - (scope.position.left + scope.position.width);
          scope.position.top = scope.position.top + element.prop('offsetHeight');

          scope.style.top = scope.position.top + 'px';

          switch (scope.popupPosition) {
            case 'left': scope.style.left = scope.position.left + 'px'; break;
            default: scope.style.right = scope.position.right + 'px'; break;
          }

          $rootScope.$broadcast('dropdown-open', {scopeId: scope.$id});
          $document.bind('click', documentClickBind);
        } else {
          $document.unbind('click', documentClickBind);
        }
      });
```

This code don't support RTL
```
var pos = $position.positionElements(self.$element, self.dropdownMenu, 'bottom-left', true);
      self.dropdownMenu.css({
        top: pos.top + 'px',
        left: pos.left + 'px',
        display: isOpen ? 'block' : 'none'
      });
```

https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L166
https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L684
