### ISSUE TITLE
Datepicker's date format

### ISSUE THREAD

**Issue by geminiyellow** [angular-ui/bootstrap#3153]
how can i check the input date format is right?
if i set the format as yyyy/MM/dd,
and i input the date 9999/11/31 or 99999/2/31，
the input box look normal, 
and i could not get the original input text from modal,
how can i prevent input the wrong date?

and maybe you could reformat the date after blue or change?

**Comment by rvanbaalen** [comment]
Please take a look at https://github.com/angular-ui/bootstrap#support if you have any questions regarding usage of the datepicker.

If you actually think you have detected a bug, can you please provide a plunker reproducing this issue?

**Comment by wesleycho** [comment]
Closing as not useful - feel free to open a new issue if there is more information.
