### ISSUE TITLE
Shouldn't we have a directive which encapsulates working with a DatePicker directive as a pop-up to an Input field ?

### ISSUE THREAD

**Issue by kosz** [angular-ui/bootstrap#3157]
Is it possible to have a Date Picker Input directive, that will basically encapsulate what the Date Picker does with the input in the example ? 

In one year of using angular-ui/bootstrap, I have yet to need a date picker without an input and pop up functionality. 

The problem is that the Popup Datepicker example promotes coupling of this directive with your controller. 

For example you need an $scope.open method and $scope.opened parameter for every single date picker you may have associated with that controller. 

Say you have a search form that allows you to enter : startDate and endDate. You are now forced to write something like this in your controller : 

```JavaScript
$scope.openStartDate = function($event) { 
   $event.preventDefault();
   $event.stopPropagation();

  $scope.startDateOpened = true;
}
$scope.openEndDate = function($event) { 
   $event.preventDefault();
   $event.stopPropagation();

  $scope.endDateOpened = true;
}
```

Of course if you have 3 dates, you would now need to write 3 methods and so on and so forth. It gets even worse, as all the boiler plate HTML also has to be copy pasted over and over again. 

Compare this input field with the ngSelect directive. Adding a ngSelect directive to your template, should not require you to write a special method in your controller. 

Does this make any sense ?

**Comment by lapo-luchini** [comment]
I had the same problems in writing the directive, but finally I managed it:
http://plnkr.co/edit/GamW8PuIXfbxwsOiDrnh
(forgetting to stop event propagation had the click also hit document which re-closed it before it was even open)

**Comment by santina** [comment]
@lapo-luchini  thank you for the directive! :+1:

**Comment by wesleycho** [comment]
I do not believe we will support this, as users may want to do custom things with the model, such as hook in custom validators.

This is something one can create for one's own project if it fits the needs though.
