### ISSUE TITLE
TimePicker 2 hours ahead of actual time

### ISSUE THREAD

**Issue by robson-gilli** [angular-ui/bootstrap#3161]
I'm facing a problem where the model used in the timepicker is always 2 hours ahead of the time that appears on the page.

Changing the original Plunker of the documentation, it's possible for me to see it.
Removing the '| date:'shortTime', making the html look like this:
```
<pre class="alert alert-info">Time is: {{mytime}}</pre>
```

I have the following display:
![image](https://cloud.githubusercontent.com/assets/7726846/5634993/0d7f9374-95cc-11e4-98fe-69cab6f7fdf3.png)

It's possible to see there that the times differs, showing 05:48 on the control but "2015-01-06T19:48:11.064Z" on the line bellow.

I've created this plunker to demonstrate: http://plnkr.co/edit/LLfAOrxYDs2aXaVL8TAu?p=preview

Is there anybody else having the same kind of trouble? Could it be something related to the daylight saving time we have right now? (I'm in Brazil).

Thanks and regards
Robson

**Comment by antoinepairet** [comment]
The last part of the string "2015-01-06T19:48:11.064Z" which is "064Z" contains timezone info. It comes from ISO 8601 standard, see: http://en.wikipedia.org/wiki/ISO_8601

If you open a console in your browser and do
````
var myDate = new Date("2015-01-06T19:48:11.064Z");
myDate
````

You will have the same value as the one represented by the date picker. If you need more help, please ask your question on SO.

I will close the issue.

**Comment by robson-gilli** [comment]
Thank you and sorry for the silly question.
