### ISSUE TITLE
Typeahead different usage

### ISSUE THREAD

**Issue by aefox** [angular-ui/bootstrap#3162]
Hello,

I'm trying to make the bootstrap typeahead directive to work like the amazon search box but I'm unable to make it happen. Can anyone provide any ideas?

Amazon search behavior:
- the user clicks something in the search input (like for example 'Javascript bible')
- what amazon search does is to display in the search popup suggested categories: like this 'Javascript bible in All Departaments'  or 'Javascript bible in Kindle ebooks' or 'Javascript bible in Books', etc

In my particular case I always know the categories, they are always the same.

Any suggestion is massively appreciated.

Thanks, fox

**Comment by antoinepairet** [comment]
If I understand your use case correctly, what you want is to have a 'groupBy' for the results of the typeahead directive. Is that correct?
This feature is not supported and there is no plan to support it on the short term. That being said, feel free to send a PR.

Similar issues include #1896 #1691 (see the comment of chrisirhc on why is whas closed)

Additional resources:
another library with full support of group by: https://github.com/angular-ui/ui-select2

workarounds using custom templates:
http://plnkr.co/edit/zujdouvB4bz7tFX8HaNu?p=preview
http://stackoverflow.com/questions/25116635/angularui-bootstrap-typeahead-grouping-results

I will close the issue for now. Regards
