### ISSUE TITLE
Alternative Calendars support (e.g. Julian, Gregorian etc)

### ISSUE THREAD

**Issue by DumboJet** [angular-ui/bootstrap#3163]
Is there any chance that you will include support for different calendars (julian, gregorian, etc)?
Something like this: http://keith-wood.name/calendarspicker.html

As far as I can tell, currently, you do not support this.

Is there any workaround that will add calendar support without changing the whole library?

**Comment by wesleycho** [comment]
This is likely too much work for this library - this could perhaps be something we visit for ng-bootstrap with Angular, but too complex for this given the current implementation.
