### ISSUE TITLE
Custom build datepicker is not working

### ISSUE THREAD

**Issue by vlavellauruit** [angular-ui/bootstrap#3164]
When you download a custom-build containing only the datepicker directive the directive doesn't work. If by the opposite you add all the directives everything works fine....
Im working with a build from the version 0.12.0

Regards

**Comment by karianna** [comment]
Which other directives do you add to make this work, can you list them here?

**Comment by brentmiller** [comment]
Just a week ago I downloaded a custom build with just the datepicker directive. It worked fine for me. I'm using version 0.12.0 with Angular 1.2.19.

**Comment by karianna** [comment]
@vlavellauruit what version of angular are you using?

**Comment by vlavellauruit** [comment]
I was my bad, I was using 2 diferents custom builds in my project, but I didnt knew that
