### ISSUE TITLE
Typeahead bug when selecting a "perfect match" from the dropdown

### ISSUE THREAD

**Issue by andertun** [angular-ui/bootstrap#3166]
See this [plunker](http://plnkr.co/edit/4H8lZyokFOqmEbkYgqS3?p=preview)

If the input value is exactly the same as one of the items in the dropdown, and you select that item. The input gets an incorrect state (`$invalid = true`).

In our case, this prevents the user to submit the form, and it's hard for them to understand why the field is validated as "has error" even though they did nothing wrong.

A "hack" that can be used until this gets fixed would be much appreciated!

**Comment by zv3** [comment]
Seems that we both ran into the same issue, I fixed this by using the "typeahead-on-select" directive and a controller like below:

```javascript
  .controller('TypeaheadCtrl', ['$scope', function ($scope) {
     $scope.onSelect = function ($item, $model, $label, formInput) {
      formInput.$setValidity('parse', true);
    };
  }])
```
and then in the html view, within the typeahead input element i added the following directives:
```
typeahead-on-select="onSelect($item, $model, $label, yourFormName.yourTypeaheadInputName)" ng-controller="TypeaheadCtrl"
```
I believe this is an angular 1.3.x thing, have not tested it yet with angular 1.2.x

**Comment by rpdmiranda** [comment]
I also ran into this issue, it seems that the parser is not called when the selected value is the same as the one in the input field.

**Comment by court-jus** [comment]
@zv3 solution ignores the parser totally. Is there a way to call the parser manually ?

**Comment by acgentry** [comment]
+1

**Comment by dlukez** [comment]
The parser shouldn't need to be called if the view value doesn't change. On the surface I don't see a problem with setting the 'parse' validation key as valid when an item is selected, considering that the same thing is done with the 'editable' validation key also
