### ISSUE TITLE
Modal transclude directive clears out element contents

### ISSUE THREAD

**Issue by ZMan9854** [angular-ui/bootstrap#3170]
I'd like to create a template for the modal directive that has some content inside of the element with the modal-transclude directive on it, but it looks like the modalTransclude directive clears out the contents of the element (see https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L127).

Not sure if this is needed for a certain use case, but removing the call to empty() fixes my use case, so thought I'd file an issue. Thanks!

**Comment by loftyduck** [comment]
Do you have a code snippet?  I had a similar issue but it was due to the scope I was passing in when opening the modal.

**Comment by wesleycho** [comment]
One can use custom templates, as listed in the documentation [here](http://angular-ui.github.io/bootstrap/#/modal).
