### ISSUE TITLE
Popover float right

### ISSUE THREAD

**Issue by jarnovanrhijn** [angular-ui/bootstrap#3172]
When a popover or tooltip is pulled to the right with a lot of content it goes out of position.

Not sure why this is happening. I created a plunker to demonstrate this issue. It doesnt always happen though.

http://plnkr.co/edit/8zSJdv3KgJ2S4Q7huqor?p=preview

**Comment by jarnovanrhijn** [comment]
Thanks for the quick reply.

Angularjs: 1.2.16
Angular UI: 0.12.0
bootstrap: 3.1.1 and also 3.3.1 has this issue

**Comment by fabienvauchelles** [comment]
+1

**Comment by songty** [comment]
0.12.1 should have fixed the issue
