### ISSUE TITLE
Tabset tabs causes exponential watcher increase

### ISSUE THREAD

**Issue by Robinson7D** [angular-ui/bootstrap#3174]
I haven't yet analyzed the code to determine whether this is expected, but I believe there is a watcher issue in tabsets. Below is a plunker to demonstrate this:
http://plnkr.co/edit/bxcsxxYyU8xXNY7fh5dn?p=preview

When adding tabs to the tabset using `ng-repeat`, the watchers grow at a constant rate of 7 watchers per tab, in my example following `7n + 3`, which is expected. However, if the same tabs are entered manually, it increases at a rate of `2n^2 + 5n + 3` where `n` is the number of tabs in the set.

Which is to say, if the controller defines `tabs` at `[1,2,3]`:

```
<tabset>
    <tab ng-repeat="tab in tabs">
        <tab-heading> Tab {{tab}} </tab-heading>
    </tab>
</tabset>
```

Is 24 watchers where the following code, which produces the same number of tabs each with the same content, will create 36 watchers:

```
<tabset>
    <tab>
        <tab-heading> Tab {{tabs[0]}} </tab-heading>
    </tab>
    <tab>
         <tab-heading> Tab {{tabs[1]}} </tab-heading>
    </tab>
    <tab>
        <tab-heading> Tab {{tabs[2]}} </tab-heading>
    </tab>
</tabset>
```

If 10 are coded, then you have 253 watchers, 20 tabs = 903 , and so on.
(Rather than the 143 watchers that 20 tabs that `ng-repeat` would create).

The reason that I believe this could be an issue for some people is that if different tabs use different filters for formatting, having all of their values in an array becomes more complex (and also couples the view to the controller much more).

**Comment by karianna** [comment]
Hi there, what version of angular/bootstrap/angular-ui are you using?

**Comment by Robinson7D** [comment]
I first noticed this on a project that I'm working on that uses:

angular: 1.3.8,
angular-ui-bootstrap: 0.11.2  (though I tried with 0.12.0 as well, with no improvement).

**Comment by chrisirhc** [comment]
There was a mistake in the watcher count calculation where it may double-count the same scope. Here's the corrected Plunker: http://plnkr.co/edit/uKbnoiGXC4grM6Bf7tsQ?p=preview

This is still a lot of watchers and I'm looking into this.

**Comment by chrisirhc** [comment]
Actually, it amounts to about 7 watchers per tab. That's reasonable and it's not longer exponential. I'm marking this issue as invalid. We can look into this further if people find this really severe.
