### ISSUE TITLE
Setting an empty string instead of null or empty object when editable is false

### ISSUE THREAD

**Issue by rpdmiranda** [angular-ui/bootstrap#3176]
When the user clears the input field, the parser returns an empty string instead of null. This may cause problems when the controller expects the ng-model to be an object.

I fixed this changing the line 3719, inside the parser function:
 ```javascript
if (!inputValue) {
            // Reset in case user had typed something previously.
            // An empty string is not always the best value to return
            modelCtrl.$setValidity('editable', true);
            return null;
```

**Comment by antoinepairet** [comment]
Thx. It would be great if you could send a PR with appropriate tests. Rgds

**Comment by rpdmiranda** [comment]
I have just made a plunker to show this issue at http://plnkr.co/edit/dDTdi7

**Comment by mirabilos** [comment]
I’d rather have it the other way, returning an empty string *always* (if not touched, or cleared later)…
