### ISSUE TITLE
Carousel noPause="true" does not work

### ISSUE THREAD

**Issue by MagicN** [angular-ui/bootstrap#3177]
<carousel interval="2700" noPause="true">  does not seem to work. I want to keep the carousel going even if mouse is hovered over images.

My understanding is the default behavior is to stop the rotation when mouse over image, but that noPause="true" is supposed to keep it going no matter what.

Thanks

Mike

**Comment by antoinepairet** [comment]
Please provide a plunkr showing the issue so we can have a look and help you.

**Comment by MagicN** [comment]
See the referenced plunk.  I simply took the angular UI sample code and added the noPause="true" to the carousel tag.

To test this, mouse over the pictures of the kittens. The carousel will stop. My understanding is that the noPause="true" will keep it running, but it does not.

I

**Comment by antoinepairet** [comment]
@MagicN thanks for the plunkr. 
Here is a fixed plunkr: http://plnkr.co/edit/dfG946ib7govfqdosYNb?p=preview
You have to use `no-pause` in markup.

Here is the explanation from ngdoc:
````
Angular normalizes an element's tag and attribute name to determine which elements match which directives. We typically refer to directives by their case-sensitive camelCase normalized name (e.g. ngModel). However, since HTML is case-insensitive, we refer to directives in the DOM by lower-case forms, typically using dash-delimited attributes on DOM elements (e.g. ng-model).
````

closing the issue.
rgds
