### ISSUE TITLE
The datepicker doesn't work correctly inside a ng-if directive

### ISSUE THREAD

**Issue by iranreyes** [angular-ui/bootstrap#3180]
The datepicker shows only one time, and after that it doesn't appear never more, when I change the ng-if by a ng-show this work correctly

**Comment by karianna** [comment]
Hi @iranreyes - Are you able to add some more detailed description or a plunkr to show this behaviour?

**Comment by jackysee** [comment]
I've faced a maybe-related problem. When `datepicker` is inside `ng-if`, when the `ng-if` is set to `false` and then `true` again, the date format is lost, showing the non-formatted date string.

Plunker example: http://plnkr.co/edit/d4L2TBAnfd4wUnxH6ZBp?p=preview

**Comment by newmanw** [comment]
I am also facing the same issue.  I am determining the template to use dynamically.  I have created a very simple plunk to show (I would have more than just a date type), but I think you get the idea.

http://plnkr.co/edit/remf5q4ltkQzM55553tB?p=preview

Looks like the scope is getting messed up somewhere.  I.E. I see isOpen change within the datepicker scope, but does not change in my directives scope.

**Comment by newmanw** [comment]
This is happening due to the way angular handles primitives in child scopes.

Read here for more info:
https://github.com/angular/angular.js/wiki/Understanding-Scopes#angular-scope-inheritance

If the open state is changed to an object rather than a primitive things work as expected.
IE

```javascript
var popupState = {opened: false};
```

```html
<input type="text" class="form-control" ng-model="field.value" is-open="popupState" close-text="Close" />
```

Means the fix is not really backwards compatible.  But I think its the right thing to do.

Thoughts?

**Comment by jamiekemp** [comment]
ng-if creates a new scope. To fix this issue, when inside the ng-if scope, simple prepend $parent. to your is-open value.

```
<input type="text" class="form-control" is-open="$parent.opened" datepicker-popup="MM/dd/yyyy 00:00:00" ng-model="field.value"  close-text="Close" />
```

newmanw, here's a fork of your plunk demonstrating:

http://plnkr.co/edit/n6vgn8d2tByhoHfXyP2w?p=preview

**Comment by MariMax** [comment]
The same problem, may be datepickerPopup could accept an object, which will have isOpen property?
@jamiekemp thanks for solution, but it is really boring to count how many ng-ifs between original $scope and datepicker

**Comment by RobJacobs** [comment]
We have PR #3666 that adds an ng-if implementation directly on the datepicker popup.

**Comment by wesleycho** [comment]
This issue seems to be fixed in `master`, as can be seen [here](http://plnkr.co/edit/Pa60eDUvK2qKuijYZYOj?p=preview).
