### ISSUE TITLE
'type' attribute in alert directive isn't working

### ISSUE THREAD

**Issue by TakLee96** [angular-ui/bootstrap#3181]
I write exactly the same code presented on the official website for alerts, but the type attibute isn't working.

HTML File
```
<div>
  <alert ng-repeat="alert in alerts" close="closeAlert($index)" type="{{alert.type}}">
    {{alert.msg}} {{alert.type}}
  </alert>
</div>
```

JS File
```
// In the appropriate controller
$scope.alerts = [
  { type: 'danger', msg: 'Oh snap! Change a few things up and try submitting again.' },
  { type: 'success', msg: 'Well done! You successfully read this important alert message.' }];
```

The Chrome Developer console tells me that 
```
Error: [$parse:syntax] Syntax Error: Token 'alert.type' is unexpected, expecting [:] at column 3 of the expression [{{alert.type}}] starting at [alert.type}}].
```

Now if I change the type attribute to be a constant string, e.g. type="danger", the alert directive still uses the default "warning" type alert. From the Chrome inspector, I can see that the type attribute is there, but the class only has "alert-warning".

So I suspect if there is some bug with the 'type' attribute for the 'alert' directive.

**Comment by karianna** [comment]
Hi @TakLee96 Are you able to provide a plunkr and the versions of Angular, Bootstrap and UI  you are using?

**Comment by TakLee96** [comment]
I finally find the problem.

If I write type='alert.type', the code would work; but if I write type='{{alert.type}}', angular will complain.

I guess the code for the directive simply uses '=' binding strategy instead of '@'. There is no error or bug. But it's just that the example on the webpage uses it in the wrong way...

P.S. Since I'm currently in China, where a whole lot of websites are firewalled, it would be quite a pain to even go to plunkr... = =

JiaHang (Tak) Li
From my iPhone

**Comment by karianna** [comment]
Thanks for the extra info - that's helpful!

**Comment by pkozlowski-opensource** [comment]
@TakLee96 you must be using some older version of the library since the version from master is using `@` binding (see: https://github.com/angular-ui/bootstrap/blob/82cb637dd12288d9fa0d42783f672fc71b94ffda/src/alert/alert.js#L16) 

A plunker forked from our demo page seems to work without problems: http://plnkr.co/edit/k3Ht33YP8ncrjyuTbds4?p=preview

Closing this one for now, but please do re-open if / when you've got more info.

**Comment by gmarshall56** [comment]
The solution shown in the plnkr uses the <alert> directive which when used, angular states is deprecated:
"...alert is now deprecated. Use uib-alert instead.and to use uib-alert...".  However uib-alert does not work when using ui-bootstrap-tpls-0.14.3.  It keeps throwing:
Syntax Error: Token 'closeable' is unexpected, expecting []] at column 33 of the expression [['alert-' + (type || 'warning] starting at [{4}].
