### ISSUE TITLE
Modal backdrop does not fade out on close

### ISSUE THREAD

**Issue by ezzatron** [angular-ui/bootstrap#3182]
See http://getbootstrap.com/javascript/#modals for expected close animation. Whereas with http://angular-ui.github.io/bootstrap/#/modal, the modal itself animates on close, but the backdrop simply disappears suddenly.

**Comment by karianna** [comment]
Hi @ezzatron - Are you able to provide a plunkr and the version(s) of Angular/Bootstrap and UI you are using?

**Comment by ezzatron** [comment]
I don't have it in front of me right now, but both bootstrap and angular-ui/bootstrap are the latest stable versions available on bower.

I can put together a plunkr tomorrow if it's required, but the two links I pasted exhibit the behaviors I'm referring to.

#### To demonstrate the expected behavior:

- http://getbootstrap.com/javascript/#modals-examples
- Under "Live demo", click "Launch demo modal"
- Close the modal and observe the modal backdrop fade out

#### To demonstrate the actual behavior:

- http://angular-ui.github.io/bootstrap/#/modal
- Click "Open me!"
- Close the modal and observe the modal backdrop **not** fading out

It probably sounds like a minor thing, but since the angular-ui backdrop *does* fade in, it's quite jarring when doesn't fade out.

Does that help, or do you still need a plunkr?

**Comment by karianna** [comment]
That should be enough, thanks!

**Comment by jackrk** [comment]
+1

**Comment by MadFlip** [comment]
add transition.js

**Comment by dyatchenko** [comment]
I found out that the problem is in [0.13.0][1] version. [0.12.0][2] works fine even with AngularJS 1.4.1.

   [1]: http://plnkr.co/edit/kEzRVjvH9P0wrw2oeAuN?p=preview
   [2]: http://plnkr.co/edit/RtjZY9eBDPkotMyn4GsU?p=preview

**Comment by telminov** [comment]
dyatchenko, +1

**Comment by olavocneto** [comment]
dyatchenko, +1

**Comment by vicky-gonsalves** [comment]
dyatchenko, +1

**Comment by SuNiLThAkUr360** [comment]
Modal backdrop does not fade out on close  help me
