### ISSUE TITLE
typeahead-editable="false"  should select first on enter and validate

### ISSUE THREAD

**Issue by MayGo** [angular-ui/bootstrap#3187]
My  configuration:
```javascript
 <input name="type" type="text" class="form-control" 
          ng-model="mytype"   
          typeahead-template-url="typeAutocompleteTemplate.html" 
          typeahead-editable="false" 
          typeahead="b for b in autocompleteService.mytypeQuery($viewValue)"
          typeahead-input-formatter="autocompleteService.mytypeFormatLabel($model)"
       required>
<script type="text/ng-template" id="typeAutocompleteTemplate.html">
    <a><span bind-html-unsafe="match.model.name | typeaheadHighlight:query"></span> </a>
</script>                     
```

When typing value, first value is selected. Hitting enter puts it in input (after formatting with  typeahead-input-formatter). But input does not validate.
When selecting with mouse or keydown, then everything works.
My values are:
Type 1
Type 2, .....
When typing "Type" and hitting enter, it works
When typing "Type 1" then it does not work

One way to fix it is to change parsers:
```javascript
       if (isEditable) {
          return inputValue;
        } else {
          if (!inputValue) {
            // Reset in case user had typed something previously.
            modelCtrl.$setValidity('editable', true);
          } else {
            modelCtrl.$setValidity('editable', false);
          }
          return inputValue;
        }
```
Return value always, because value really is never invalid.

**Comment by antoinepairet** [comment]
@MayGo Could you set up a simple plunkr?
It would be great to send a PR with tests associated to it. rgds

**Comment by arjunasuresh3** [comment]
+++

**Comment by ivschukin** [comment]
guys please fix this bug!

**Comment by antoinepairet** [comment]
@ivschukin Please send us a pull request!

**Comment by parkerhillius** [comment]
What is the status of this? I'm having this issue with a typeahead-editable="false" typeahead. If you type in exactly (case-sensitive) the matching item it selects the value correctly, however it leaves a $error.parse = true property.

**Comment by zhenghao1** [comment]
If I may add.  The documentation is wrong for this attribute.  The default should be false not true.

**Comment by stijnherreman** [comment]
From reading the description, I think I have the same issue. When I type the full value of one of the options and then select the option, the field is invalid with `ng-invalid-parse`. When I type a partial value and select the option, the field is valid.

I don't have a test case to demo, but upgrading from 0.13.0 to 0.13.1 fixes the issue for me.

**Comment by parkerhillius** [comment]
Thank you Stijn! I just upgraded and that resolved my issues, everything is working correctly now.

**Comment by wesleycho** [comment]
Not able to reproduce this issue [here](http://plnkr.co/edit/9FD2KXneXW9bZiSuqdlB?p=preview) - this appears to be fixed.

**Comment by gurpreetrsi** [comment]
@wesleycho You can reproduce it as: 
1) Enter something in the control and check the class of the control as:
"form-control ng-dirty ng-touched ng-invalid ng-invalid-editable ng-invalid-parse"
Till you select some value from dropdown the control remains invalid. It should ideally not be invalid if one enters potential matching values. 
Can we have some resolution for the same please.

**Comment by btalpiga** [comment]
Hey guys! 
Why is this issue closed? I didn't find any solution to the case described by @MayGo . I am using version 1.3.3 of angular-bootstrap.

Thanks!
