### ISSUE TITLE
Typeahead input text sets cursor to the end of line

### ISSUE THREAD

**Issue by javierSF** [angular-ui/bootstrap#3189]
If you have an input with a shorter width that a selected text, the cursor goes to the end of the line and the text is cut off. 

To replicate it see attached link, and select a long option (eg: Massachusetts) and click this option. If you select the option by pressing Enter key it does not happen

http://plnkr.co/edit/n2ZFVOAwCqXr6iZVOc8H?p=preview

Only in IE and Chrome

**Comment by dmitriz** [comment]
However, the text jumps back to the first character as soon as that window loses focus. 
Would there be any better behaviour?

**Comment by rvanbaalen** [comment]
I don't think this is an actual issue. It has nothing to do with UI Bootstrap, this is just default browser behavior for these browsers.
