### ISSUE TITLE
cross origin problem

### ISSUE THREAD

**Issue by rarutu** [angular-ui/bootstrap#3190]
Hi

The script i've build using angular-ui functions as a library that gets loaded on different domains
One of the functionalities that we created involves opening a modal window ... when this happens on a client domain we get this

Error: [$sce:insecurl] http://errors.angularjs.org/1.3.3/$sce/insecurl?p0=template%2Fmodal%2Fbackdrop.html

i tried adding in the config this:
myApp.config(['uiGmapGoogleMapApiProvider', '$sceDelegateProvider', function(uiGmapGoogleMapApiProvider, $sceDelegateProvider) {
                uiGmapGoogleMapApiProvider.configure({
                    key: '',
                    v: '3.17'
                });
                $sceDelegateProvider.resourceUrlWhitelist([
                    'self',
                    'https://*.domain.com/**'
                ]);
            }]);

with little success  though ... i have no idea how to move forward :( i should mention that my modla window uses the inline template attribute not templateUrl

thanks,
Rares

**Comment by rarutu** [comment]
this is the error i get:

https://docs.angularjs.org/error/$sce/insecurl?p0=template%2Fmodal%2Fbackdrop.html

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that would be better asked elsewhere: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
