### ISSUE TITLE
tabs: what's the idea behind tabHeadingTransclude?

### ISSUE THREAD

**Issue by fxck** [angular-ui/bootstrap#3193]
I'm trying to understand the way you've created the tabs and I don't quite get why is tab heading and tab content being transcluded this way? The heading especially, given there's both `tabHeadingTransclude` and `{{ heading }}`..

Could you break down the code a little for me, please?

**Comment by karianna** [comment]
Might get a quicker response asking this Question on SO or in the IRC channel (GitHub is primarily for issue tracking.)

**Comment by chrisirhc** [comment]
Closing as this isn't a description of an issue.
