### ISSUE TITLE
Support for Version Angular 1.3.*

### ISSUE THREAD

**Issue by todeia** [angular-ui/bootstrap#3197]
When I run the command "bower install" a notification appears:
	Unable to find a suitable version for angular, please choose one:
    	1) angular#>=1 <1.3.0 which resolved to 1.2.28 and is required by angular-bootstrap#0.12.0
Can they update the dependency to:
"dependencies": {
         "angular", "~1.3.0" 
     }

Or is there a problem?

**Comment by karianna** [comment]
We have not yet upgraded enough components to be 1.3 compatible.  See the Angular 1.3 Label on many issues in this project.

**Comment by todeia** [comment]
Thanks.
