### ISSUE TITLE
Feature request: Popover to support placement as function, html content, etc.

### ISSUE THREAD

**Issue by AdrianTeng** [angular-ui/bootstrap#3202]
I know you guys are aware of the missing features (as documented in [source code](https://github.com/angular-ui/bootstrap/blob/master/src/popover/popover.js)) but I just want to raise this issue so that it is properly tracked and prioritised.

And yes, I would love to have this feature - you can't really do much with current popover other than just plain text!

**Comment by pkarikh** [comment]
It seems like here is a feature you talking about. https://github.com/angular-ui/bootstrap/pull/1848, isn't it?
