### ISSUE TITLE
Conflict between ui-bootstrap and angular-strap when using modal

### ISSUE THREAD

**Issue by dlwhiteman** [angular-ui/bootstrap#3203]
I am using both this library and AngularStrap (http://mgcrea.github.io/angular-strap) together.  When I use the modal support in UI Bootstrap with angular-strap also loaded, I receive JavaScript errors.  The reason for this is that both libraries provide a $tooltip() function.  When I change the order of the directives, it just changes where the exception is thrown.  When the ui-bootstrap directive appears before angular-strap, I get an exception here in line 2770 of ui-bootstrap-tpls.js when using the modal: ` return $tooltip( 'tooltip', 'tooltip', 'mouseenter' );`, because of the same-named function in AngularStrap.

**Comment by karianna** [comment]
Hi @dlwhiteman - unfortunately I don't think we'll be changing our naming convention here, as you can probably appreciate it's almost impossible to be compatible name space wise with everything out there!.

**Comment by antoinepairet** [comment]
This is a duplicate of https://github.com/angular-ui/bootstrap/issues/157

**Comment by xvitcoder** [comment]
Very bad decision

**Comment by javierfvargas** [comment]
karianna, this kind of decisions can only be taken by people producing no widely used libs.  This lib is widely used and as Angular does not provide a name-collision prevention mechanism you should reconsider.

AngularStrap people are moving to change it as you can see here https://github.com/mgcrea/angular-strap/issues/521

**Comment by RobJacobs** [comment]
@javierfvargas As of version 0.14.0 directives and controllers are prefixed with uib, see latest docs

**Comment by javierfvargas** [comment]
is it the same for providers?  I'm sing 0.14 and $tooltip seems to be still in conflict.  Maybe my bad, will double check.

**Comment by 0917** [comment]
That's really great you've introduced the prefix!

When you are going to remove deprecated code fragments (those without prefix, possibly conflicting ones)?

**Comment by icfantv** [comment]
@0917, we need to let it bake for a while and give people an opportunity to see the warnings and migrate their code.  This will also let us work out any issues introduced by the prefixing (which there were).

**Comment by javierfvargas** [comment]
@RobJacobs Just checked again and it is still in conflict, angular-strap seems to conflict with $tooltip.

TypeError: Cannot read property 'toLowerCase' of undefined
    at TooltipFactory (:9000/webjars/angular-strap/2.3.2/angular-strap.js:256)
    at :9000/webjars/angular-ui-bootstrap/0.14.0/ui-bootstrap-tpls.js:5397
    at Object.invoke (:9000/webjars/angularjs/1.3.16/angular.js:4219)
    at :9000/webjars/angularjs/1.3.16/angular.js:6556
    at forEach (:9000/webjars/angularjs/1.3.16/angular.js:326)
    at Object.<anonymous> (:9000/webjars/angularjs/1.3.16/angular.js:6554)
    at Object.invoke (:9000/webjars/angularjs/1.3.16/angular.js:4219)
    at Object.enforcedReturnValue [as $get] (:9000/webjars/angularjs/1.3.16/angular.js:4072)
    at Object.invoke (:9000/webjars/angularjs/1.3.16/angular.js:4219)
    at :9000/webjars/angularjs/1.3.16/angular.js:4037

**Comment by icfantv** [comment]
@javierfvargas, please create a minimally working plunker that demonstrates the issue.  Also, please try with 0.14.2 and 0.14.3-SNAPSHOT as there were a flurry of bug fixes after the 0.14.0 release to fix corner cases that were missed due to missing functional tests.

**Comment by 0917** [comment]
@icfantv, @javierfvargas, I'm just a user of this library but isn't just the case that code fragments that causes the conflict with angular-strap (not-prefixed ones) still exist but only marked as deprecated (at least with 0.14.2)? 
So the conflict must occur and it's nothing strange as long as the deprecated code is not removed, isn't?

**Comment by icfantv** [comment]
Yea, that sounds logical.  The deprecated code is not going to be removed until we release v1.0 later this year.  We need to give people time before we remove it.

**Comment by javierfvargas** [comment]
@icfantv @0917 Please check the console errors (not warnings) in this plunker.  Any advice is appreciated.
http://plnkr.co/edit/QAA6mxfCV88QQPSUadUt

**Comment by icfantv** [comment]
@javierfvargas, questions of a support nature are best served by posting to StackOverflow.  We've removed all the prefixes in `master` so you may want to try pulling and building the latest code and seeing what happens.

**Comment by javierfvargas** [comment]
@icfantv It is not a support question, it is related to this issue.  U asked for a plunker, there you have it.

**Comment by icfantv** [comment]
@javierfvargas, please update your plunker with the latest build from `master` and let's go from there.  All the prefixes were removed on Friday.

Not to argue symantics, but to be clear, this IS a support issue because you're using two libraries that do nearly identical things and you expect everything to work seamlessly.  Additionally, you posted a plunker and asked us for advice.  That's almost the very definition of support.

**Comment by javierfvargas** [comment]
Thanks @icfantv, yeah I asked for advice, my bad. But the kind of advice I was looking for was about the validity of the test.. Like "please use master build".   BTW how should I include the master build?

**Comment by icfantv** [comment]
@javierfvargas, you can `git clone` our repo, run an `npm install` and then run `grunt`.  This will build the library and place them in the `dist` folder.  You can then copy and paste the contents of the `ui-bootstrap-tpls-1.0.0-SNAPSHOT.js` file into a separate `.js` file in your plunker and then replace the path to the 0.14.3 file.

**Comment by javierfvargas** [comment]
@icfantv, the error is no longer happening and the inclusion order is irrelevant now.  Thanks.  
The plunker is now updated in case you want to check http://plnkr.co/edit/QAA6mxfCV88QQPSUadUt
When do you plan to release it?

**Comment by icfantv** [comment]
good.  thanks for the update.  happy coding.
