### ISSUE TITLE
Issue with dynamic content and modal

### ISSUE THREAD

**Issue by dlwhiteman** [angular-ui/bootstrap#3204]
When I have a modal that provides dynamic content (through use of ng-select and ng-include), how can I make the modal dialog either adjust its height or include a scrollbar on the content?  Currently if the user selects an item from a menu on the left side of the dialog, and a template is loaded on the right side with lengthy content, that content can extend past the height of the modal dialog.  What is the best way to handle this?

**Comment by antoinepairet** [comment]
I am unsure what you issue actually is. Please provide a plunkr showing the issue you encounter.

**Comment by pkozlowski-opensource** [comment]
Closing due to the lack of response
