### ISSUE TITLE
Issue with dialog content appearing in modal footer instead of body

### ISSUE THREAD

**Issue by dlwhiteman** [angular-ui/bootstrap#3205]
I am using the modal support in angular-ui, and for some reason the content is appearing in the modal-footer section of the screen, even though it is defined in modal-body.  Have you seen this issue, and have any ideas why it could be happening?  I am basically following the pattern described in the docs of providing a modal-header, modal-body, and modal-footer inside a script tag, and loading that content using the templateUrl parameter.  I can paste my code if it's helpful.  Thanks!

**Comment by antoinepairet** [comment]
Please provide a plunkr. rgds

**Comment by dlwhiteman** [comment]
I fixed the problem in my case by setting a fixed height for the modal-body section, and also for the two columns within the body

**Comment by pkozlowski-opensource** [comment]
OK, sounds like a support question that was sorted out. Closing.
