### ISSUE TITLE
backspace with modal dialog should be disabled

### ISSUE THREAD

**Issue by runn1ng** [angular-ui/bootstrap#3208]
When modal dialogue is displayed, backspace should be disabled.

Now, the user can still press "backspace" and the page **behind** the modal moves, but the modal itself stays.

**Comment by karianna** [comment]
Version of Angular/Bootstrap/UI used?

**Comment by runn1ng** [comment]
Angular: 1.3.9
Bootstrap: 3.1.1
angular-bootstrap: 0.12.0

**Comment by redab** [comment]
Disabling backspace key is not the right solution. One can still use the browser back button to cause the same effect.

**Comment by runn1ng** [comment]
Well yeah, that's true. Maybe the default backpace/back option should be to just disable the modal and *not* to move the page behind, which makes no sense

**Comment by kernel-io** [comment]
You can add a callback on the scope.$close to close the modal, not that it might solve all use cases.

**Comment by Brovert** [comment]
Seems like this should be a configuration just like the escape key. Any updates on this?

**Comment by chrisirhc** [comment]
This breaks expected behavior from the Bootstrap (Twitter) library's modals. Their modals don't listen to the backspace key. Are we sure we want to go ahead with this?

**Comment by wesleycho** [comment]
I believe we shouldn't deviate from Bootstrap's modal behavior in this case.  If it is desired to have this behavior, one can write a custom directive to accomplish this.

**Comment by wesleycho** [comment]
Closing as I don't see strong justification for this, and there is a way to work around this if one really wants this feature.
