### ISSUE TITLE
Weird select-box rendering issue with ng-model inside a modal

### ISSUE THREAD

**Issue by stlouisweb** [angular-ui/bootstrap#3209]
I'm setting up a modal to contain a form and want to pre-populate the options and selected option of a select box from a scope variable like this
```javascript
          <select ng-model="title" ng-options="Title.name for title in titles track by title.name" id="nameTitle" class="form-control">
          </select>
```
This works fine outside of the modal but in the modal I have a weird issue where the options do exist, and the correct option appears to be selected, but they are invisible (no text appears to render in the browser, even though the value is seen in the console and the correct blank space where the text should be is selected in the browser).

**Comment by karianna** [comment]
Plunkr and versions of angular/bootstrap and ui please :-)

**Comment by stlouisweb** [comment]
http://plnkr.co/edit/lS2Z1RYnQoiyQllMtj23?p=preview

Angular: 1.3.9
Bootstrap: 3.3.0
UI: 0.12.0

In the Plunkr I'm using the latest stable deps for UI (angular 1.2.16, BS 3.1.1).
One closer inspection I'm experiencing the same issue in and out of the modal, so this maybe an an issue with the angular select??
If you inspect the code you will see that the options do have a value attribute and the specified option is selected, but there is no content in the option element. I'm expecting the option content to match the value.
![ngselectplnk](https://cloud.githubusercontent.com/assets/3084858/5840971/e8700b9c-a15e-11e4-8f94-1b301edba60a.png)

**Comment by stlouisweb** [comment]
There's no bug, I just mislabeled my 'title' variable with a capital T..
