### ISSUE TITLE
angular-ui-bootstrap datepicker and masked input issue when working together

### ISSUE THREAD

**Issue by robson-gilli** [angular-ui/bootstrap#3214]
I am using the angular UI bootstrap popup datepicker like the example here : http://angular-ui.github.io/bootstrap/#/datepicker

When i combine this with the uiMask the values in the input get scrambled when i pick a date.

The plunker: http://plnkr.co/edit/Kfzee53GL4T3UGLQRuAe?p=preview

Am I doing something wrong?

Regards
Robson

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by settysreekanth** [comment]
@robson-gilli did you find the solution for this?
