### ISSUE TITLE
When manually typing an item from the popup in a typehead with editable=false the input should be valid.

### ISSUE THREAD

**Issue by dozed** [angular-ui/bootstrap#3219]
Here is a jsfiddle http://jsfiddle.net/av5jyk2L/3/

Reproduce:

  - type "1" in the input
  - loose focus of input by clicking
  - input is marked as invalid, although "1" appears as item in the popup

**Comment by karianna** [comment]
Pretty sure this is a dup - but will confirm later

**Comment by dozed** [comment]
@karianna any news yet?

**Comment by karianna** [comment]
#3187 covers this.

**Comment by dozed** [comment]
Thanks.
