### ISSUE TITLE
ngInclude in modal template

### ISSUE THREAD

**Issue by vanbeast** [angular-ui/bootstrap#3221]
I need 2 modal popups(adding item and editing item). I'd like to use one common template for body(with all item's fields) for both popups but different header and footer. I thought it was possible with using ngInclude but it didn't work on modal popup. The div with ngInclude directive is empty. Should I use something different or maybe there is a possibility to do it with angular-ui bootstrap modal?

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
