### ISSUE TITLE
MeanJS Package Error in UI Bootstrap: 'TypeError: openScope is null 	  var toggleElement = openScope.getToggleElement();'

### ISSUE THREAD

**Issue by corientdev** [angular-ui/bootstrap#3225]
Hi I am getting this error.

`'TypeError: openScope is null 	  var toggleElement = openScope.getToggleElement();'`

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by corientdev** [comment]
Apology! I currently don't have time to create and debug this @ plunkr will do it some other day. I thought i should notify the community so i did it.

**Comment by wesleycho** [comment]
Closing, as there isn't enough information to act on. Feel free to open a new issue with more information if this is a problem in UI Bootstrap itself and not with the MeanJS package.
