### ISSUE TITLE
Blocked loading resource from url not allowed by $sceDelegate policy.  URL: template/datepicker/datepicker.html

### ISSUE THREAD

**Issue by ifaris7** [angular-ui/bootstrap#3227]
I keep getting this error: Blocked loading resource from url not allowed by $sceDelegate policy. URL: template/datepicker/datepicker.html

i have 
"angular": ""1.3.11", 
"angular-bootstrap" : "0.12.0",
"angularAMD" : "0.2.1"

Is it a compatability issue? and if so, is there a way i can fix it without having to downgrade angular?

It is worth noting as well that i use requirejs to load my libraries, and with that said i had to use angularAMD instead of angular.

I also have my own templates for the datepicker loaded as script tags inside my html, so i do not see why the library is even asking to load a template from url.

thanks in advance.

**Comment by karianna** [comment]
Please use StackOverflow or the angularjs IRC channel for support issues, thanks!
