### ISSUE TITLE
Problem with $transition on recent Chrome version

### ISSUE THREAD

**Issue by warpdesign** [angular-ui/bootstrap#3228]
$transition figures out the transitionEnd event name this way:

    var transitionEndEventNames = {
        'WebkitTransition': 'webkitTransitionEnd',
        'MozTransition': 'transitionend',
        'OTransition': 'oTransitionEnd',
        'transition': 'transitionend'
      };

Problem is, with recent Chrome versions (tested with 40.0.2214.93 m (win64), and 42.0.2288.4 canary (64-bit)), $transition uses *webkitTransitionEnd* but Chrome triggers a *transitionend* event instead.

As a result, some Bootstrap directives (eg. carousel) are broken in Chrome versions since end transition is not detected.

For example, you cannot goto next carousel slide more than once since next/prev buttons are disabled until transition end event has been received:

    //Prevent this user-triggered transition from occurring if there is already one in progress
    if (!$scope.$currentTransition) {
      return self.select(slides[newIndex], 'prev');
    }

This may be a bug in Chrome, but meanwhile, replacing above definition with this one fixes the problem:

    var transitionEndEventNames = {
        'transition': 'transitionend',
        'WebkitTransition': 'webkitTransitionEnd',
        'MozTransition': 'transitionend',
        'OTransition': 'oTransitionEnd'
      };

**Comment by knorrus** [comment]
Experiencing same issues. Chrome Version: 40.0.2214.93 m, Win 7 (x64)
Also found bug report: https://code.google.com/p/chromium/issues/detail?id=451756

**Comment by zackiles** [comment]
I'm experiencing the same issues. A few related things are broken in chrome as well which makes me think this is a very recent (within the last few days) bug in chrome. It''s effecting the accordion as well. When clicking the accordion headers some groups with lots of content either fail to display or display after a very long time (15 seconds +). You can find an example at http://liftcannabis.ca/points with the accordion near the bottom of the page in the most recent version of Chrome.

**Comment by zackiles** [comment]
For an update, regarding the accordion issue i mentioned, removing -webkit-transition-duration: .35s; from the ".collapsing" class in bootstraps css fixes the issue with accordions not opening and closing properly for me.

**Comment by warpdesign** [comment]
I have submitted a simple fix: https://github.com/angular-ui/bootstrap/pull/3238

**Comment by wesleycho** [comment]
Is this still an issue in Chrome 41?

**Comment by zackiles** [comment]
@wesleycho from what I've seen, no, this issue seems to have resolved itself now.

**Comment by wesleycho** [comment]
Closing as fixed in Chrome then - if this is still an issue, I will reopen this.

Thanks!
