### ISSUE TITLE
Tooltips mangled in bootstrap grid elements

### ISSUE THREAD

**Issue by RPGillespie6** [angular-ui/bootstrap#3229]
It seems as though tooltips have some very curious behavior when inside bootstrap grid small columns. Take this plunker for example, and stretch the viewport all the way to the left:

http://plnkr.co/edit/gVekao4JCdC5O91RCoiW?p=preview

Is this behavior expected?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support
