### ISSUE TITLE
Modal: deleting DOM element before calling scope.$destroy

### ISSUE THREAD

**Issue by pglotov** [angular-ui/bootstrap#3231]
I'm using ui-slider directive in a modal, and when the modal dismisses it produces an error saying it shouldn't call 'destroy' before initializing slider. I think the reason is that modal destroys DOM before $destroy'ing the scope:

``` javascript 
//remove window DOM element
        removeAfterAnimate(modalWindow.modalDomEl, modalWindow.modalScope, 300, function() {
          modalWindow.modalScope.$destroy();
          body.toggleClass(OPENED_MODAL_CLASS, openedWindows.length() > 0);
          checkRemoveBackdrop();
        });
      }
```

Would it be a good idea to rearrange things so that scope gets $destroy'ed before deleting DOM element?

**Comment by fanzeyi** [comment]
I found this issue from angular-ui/ui-slider#41 . 

I met the same error in my project but I didn't use angular-bootstrap. So I think this issue is irrelevant to this project. Maybe it's relevant to angular-ui/ui-slider or angular/angular .

**Comment by pglotov** [comment]
I can't see what fanzeyis posts in https://github.com/angular-ui/ui-slider/issues/41 show. I still think destroying scope should happen before destroying DOM.
