### ISSUE TITLE
select tab from a controller

### ISSUE THREAD

**Issue by fonzy2013** [angular-ui/bootstrap#3232]
First I want to say a big thanks for this excellent project. Second I want to say sorry if this post is not regarded as an issue, in which case I will gladly redirect my attention to the designated place...

Version: ui-bootstrap-tpls.js (bower installed) 0.12.0 - 2014-11-16

Issue: There is no way to programmatically select a tab. Is there a workaround or are you willing to let be create a patch?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support
