### ISSUE TITLE
Accordion: is-disabled doesn't disable <accordion-heading />

### ISSUE THREAD

**Issue by mikolus** [angular-ui/bootstrap#3233]
Hi,
If you use "is-disabled" attribute on "accordion-group" with header as an attribute, everything works fine, "text-muted" class is added correctly.
But if you use <accordion-heading /> tag, panel is still disabled, but the "text-muted" class is not added to the header.
Here is plunker:
http://plnkr.co/edit/n5LxEAeq5lyS5St6ndYr?p=preview

**Comment by rvanbaalen** [comment]
This looks like a valid bug to me.

**Comment by rvanbaalen** [comment]
I've also implemented a fix in [the plunkr](http://plnkr.co/edit/PjU6pmO1JU3xJlhxwN18?p=preview) I just have to create a PR and write some tests for it now.
