### ISSUE TITLE
Funding Goal?

### ISSUE THREAD

**Issue by coolaj86** [angular-ui/bootstrap#3237]
You mention that someone could potentially sponsor you guys in order to make this effort a higher priority in your long list of todos. I'm not currently in a position to fund you, however, I'd be interested to know what kind of funding you're looking for. (and stating a goal often helps attract attention, y'know?)

* What would be a reasonable goal amount to close major 1.2 and 1.3 bugs?
* What would be a reasonable goal amount to "complete" a solid 1.0 release for ng 1.3?
* Suppose you shed everything that isn't a jquery bootstrap component (and put it into a separate project), what would be a reasonable goal amount to "complete" a solid 1.0 release for just the components listed at http://getbootstrap.com/javascript/?

Throw out some figures, even if they're in a wild range like 10k-50k or 50k-300k.

**Comment by karianna** [comment]
Hi @coolaj86 I'll raise this at the next maintainers meeting - please note we only just met recently for the first time - https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support - so we're not sure the scale of the backlog yet.

**Comment by Foxandxss** [comment]
Money always help a open source project, the biggest issue was a period of no maintainers on the project. We are making a new team and we are starting to do some progress on organization and what to do.

We hope we can start releasing new stuff soon when the new maintainers catch up with what we do here in this project.
