### ISSUE TITLE
Calendar labels Translation

### ISSUE THREAD

**Issue by hersonrodrigues** [angular-ui/bootstrap#3239]
Great product helped me a lot,

But I have to translate the labels for the Brazil portuguese,

is there any simple way to do this, something expected to be implemented?

example:

dateFormat: 'dd / mm / yy'
dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Quinta', 'Friday', 'Saturday'],
dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
dayNamesShort: ['Don', 'Monday', 'Having', 'Wednesday', 'Chi', 'Fri', 'Sat', 'Don'],
monthNames:['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
monthNamesShort: ['Jan', 'Feb', 'Sea', 'Apr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Ten' ]
nextText: 'Next'
prevText: 'Previous'

**Comment by karianna** [comment]
Please see https://github.com/angular-ui/bootstrap#support
