### ISSUE TITLE
Feature status

### ISSUE THREAD

**Issue by avdd** [angular-ui/bootstrap#3243]
Sorry to contribute to the noise, I see you folks are pretty busy.

It would be supremely awesome to have a page somewhere that lists all the bootstrap features and their current status ("caniuse" for ui-bootstrap).

For my part, as a newcomer I don't know whether to use this project or the original jquery components.  I don't know what the current status is overall except the level of activity in the tracker.

I see each component can be tracked individually in the issues, but that doesn't give me a sense of how usable it is now, nor how usable groups of components are together, etc.

Also, as a potential contributor it would be handy to see easily the intersection between the project's needs and my own.

**Comment by karianna** [comment]
I'll attempt to tackle this with the maintainers and have it listed on the README.md file for the project

**Comment by Foxandxss** [comment]
Our components are pretty stable and as close as possible to original bootstrap. The problem is that this project has different needs (because angular) so it would never be a 1:1 match.

To the newbies I recommend them to check the demos, read the doc and see what can be done.
