### ISSUE TITLE
$modal does not trigger default bootstrap events

### ISSUE THREAD

**Issue by rinatio** [angular-ui/bootstrap#3247]
Hello guys,

Seems like [non of the bootstrap modal events](http://getbootstrap.com/javascript/#modals-events) are triggered. Here's a [plunker](http://plnkr.co/edit/yxzsxNY6ACuGmFPg2Vj8?p=preview). 

Is there any workaround?

**Comment by ansonkao** [comment]
Publishing global events in the way you seek goes against the principles of AngularJS. We gotta remember to think in Angular, not jQuery! :)

**Comment by rinatio** [comment]
@ansonkao This is a question of compatibility with bootstrap events, I don't see how it goes against AngularJS if you use those events in directive (plunker is just a simplest example).

**Comment by pkozlowski-opensource** [comment]
@rinatio we believe that there are better APIs as compared to events. For example, in the case of a modal you've got a promise that gets resolved when w modal is opened and closed.

I'm going to close this one as it is a conscious design decision to not support events and offer different (we believe that much better) API instead.

**Comment by rinatio** [comment]
@pkozlowski-opensource What would you suggest to use in case development needs to manually close tooltip in case some modal opens? Right now I use this kind of event and listen for it in the tooltip directive:

```
    $provide.decorator('$modal', ['$delegate', '$rootScope', function($delegate, $rootScope) {
        var open = $delegate.open;
        $delegate.open = function() {
            var r = open.apply(this, arguments);
            r.opened.then(function() {
                $rootScope.$broadcast('modal-opened')
            });
            return r;
        };
        return $delegate;
    }]);
```

Bootstrap built in events seems to be much better approach, no?

**Comment by pkozlowski-opensource** [comment]
There are not enough details here to say what is the best approach - I'm not sure what you mean by "manually close tooltip". Do you have a reference to a tooltip? In this case you can simply close it when opening a modal. Or you could observe modal stack from your tooltip directive. Or you can broadcast events yourself as you are doing.

In short: there are many ways of tackling this problem, but we are not going to add events, unless someone can clearly demonstrate that this is a superior approach. In my experience events give you an illusion of a flexible and loosely-coupled system, while in reality if gives you a very fragile system where hundreds of  events are flying around and you are not sure who is sending and who is handling what. Not to mention that this is string-based API so a small rename or type and the whole thing falls apart....

**Comment by rinatio** [comment]
@pkozlowski-opensource 

1. I don't have a reference to a tooltip from places where I open modals, since tooltip is quite simple html directive similar to (but not the same) bootstrap tooltip while modals are getting opened in controllers
2. I'm trying to keep this code DRY, so I don't `$broadcast('modal-opened')` on every modal I have in the system and use decorator
3. I'm not quite sure how can I observe modal stack from my tooltip directive
4. How is the angularjs `$broadcast` better than jQuery events in terms of "illusion of flexibility" and "string-based API". jQuery events at least have `preventDefault`, `stopPropagation` and namespaces!

I don't have a passion for DOM/jQuery events or something, but using this library I was expecting to have it all the default built-in, documented and so familiar features bootstrap has, including events. I think you might at least have mentioned that you cut that off.

**Comment by vinitsharma87** [comment]
Hi,
I implemented angular-ui modal dialog, and I am also facing a similar kind of problem. When I alert for the JSON.stringify contents of the modal instance, I find **only** two methods inside it as `result()` and `opened()`. Why does it doesn't shows for rendered method ? I am trying to implement something when the whole modal dialog along with the html contents is rendered, but the modal instance doesn't has the rendered method. What could be the reason for this ? Do I need to add for any property while calling the `$modal.open()` method ?

**Comment by vinitsharma87** [comment]
I am using angular-ui bootstrap 0.11.2, and I checked in the `modal.js` file that `rendered` method is not being there. So how would I achieve this for getting `rendered()` event in this existing version of angular-ui bootstrap ? Please help.

**Comment by icfantv** [comment]
@vinitsharma87, please follow the project documentation for how to receive support.  commenting on closed issues, especially ones that are as old as this, is a good way for them to get ignored or missed.

You're using a VERY old version of the library - perhaps upgrading to something more recent would be better?

**Comment by vinitsharma87** [comment]
@icfantv Yes I found it out, in the version which I am using, there is no `rendered()` method support. Perhaps I would be now required to find for some other way for tracking DOM rendered event in some other angular way. Thanks for the info.

**Comment by icfantv** [comment]
The modal fires events as well, but I don't know off the top of my head what initial version of the library contains that functionality and cannot check at this time.  I would suggest going to our demo site and changing the doc drop down to your version to see what's available.

**Comment by vinitsharma87** [comment]
@icfantv I guess regarding demo site, you are talking about [this](http://angular-ui.github.io/bootstrap/#/modal) site itself. And yes I did checked for my currently prevalent version which is 0.11.2. And in the documentation of 0.11.2 version it clearly states that the `open()` method returns a modal instance an object with following properties:

`close(result)`, `dismiss(reason)`, `result` and `opened`. The documentation for `opened` method says _it returns a promise that is resolved when a modal gets opened after downloading content's template and resolving all variables_. But I tried with this `opened` method as well, and this method gets fired before downloading and rendering the DOM contents. For your reference you can check [this](https://github.com/angular-ui/bootstrap/tree/0.11.2/src/modal/docs) out. Don't know how the DOM rendered event would get tracked in this version.

**Comment by icfantv** [comment]
@vinitsharma87, so yes, I am talking about that site, but you'll notice that the docs for 0.11.2 are not present in the dropdown list because that version is so old.  So I'm curious as to what documentation you were looking at.  Did you pull the relevant git version from the `gh-pages` branch?

At this point, there's not a lot we can do for you unless and until you upgrade to a newer version as the version you're using is going on a year and a half old and that's a lifetime in OSS.

**Comment by Stalinko** [comment]
I spent a half-hour pulling my hair out trying to understand why bootstrap events aren't fired, and now you say it was made deliberately. ><
You've just broken compatibility with native bootstrap modals.

And how do you suggest now to define global event handlers? As far as I see now it's impossible. I want to define couple event handlers which will trigger on all modals and I don't want to modify whole my code for that.
