### ISSUE TITLE
Changing the datepicker popup position

### ISSUE THREAD

**Issue by swathi1029** [angular-ui/bootstrap#3249]
I had a small issue in datepicker control. I want to change the popup position of the datepicker control to right as the default position is left.

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support

**Comment by basva5577** [comment]
Hi swathi1029, did you get the solution for your query?

**Comment by basva5577** [comment]
I need answer for the same question, can anyone help? Where to change to show pop on the right side
