### ISSUE TITLE
Changing the datepicker popup position

### ISSUE THREAD

**Issue by swathi1029** [angular-ui/bootstrap#3251]
I am having a “small” issue with the angularjs ui datepicker. I need to indicate somehow, if an input with a datepicker attach, should show the popup in the right side of the textbox

Thanks

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support

**Comment by swathi1029** [comment]
As I am new to github I didn't understand the solution you have specified can you please tell in detail.

Thank you

**Comment by Hypercubed** [comment]
He is suggesting that you look at the #Support section of the readme.  Since your "issue" is not a bug or feature request for this source code you need to look at other channels for getting support.
