### ISSUE TITLE
Typeahead ARIA would need pagination for a number of results

### ISSUE THREAD

**Issue by jmaister** [angular-ui/bootstrap#3253]
I am using the typeahead element and validating it against the WAI-ARIA authoring practices.

On the combo box widget, http://www.w3.org/TR/wai-aria-practices/#combobox shows the next requirement:

* Page Up/Page Down selects the next/previous pages item depending on the lists size.

It be a good point to add to the typeahead element.

**Comment by dmitriz** [comment]
It is my understanding that the `typeahead` completion window should fit into the screen and not be paginated. Page Up/Page Down works and paginates the whole page.

Is this not the correct behaviour?

**Comment by icfantv** [comment]
Closing in favor of #4772.
