### ISSUE TITLE
'bower install angular-bootstrap' fails on OS X

### ISSUE THREAD

**Issue by ckames** [angular-ui/bootstrap#3263]
Charless-MacBook-Pro:orglines charlesames$ bower install angular-bootstrap
bower cached        git://github.com/angular-ui/bootstrap-bower.git#0.12.0
bower validate      0.12.0 against git://github.com/angular-ui/bootstrap-bower.git#*
bower cached        git://github.com/angular/bower-angular.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular.git#>=1 <1.3.0
bower not-cached    git://github.com/angular/bower-angular.git#1.3.36
bower resolve       git://github.com/angular/bower-angular.git#1.3.36
bower cached        git://github.com/angular/bower-angular.git#1.3.12
bower validate      1.3.12 against git://github.com/angular/bower-angular.git#*
bower ENORESTARGET  No tag found that was able to satisfy 1.3.36

Additional error details:
Available versions: 1.4.0-build.3818+sha.030a42e, 1.4.0-build.3817+sha.898714d, 
[snip]

**Comment by pkozlowski-opensource** [comment]
I don't think that there is anything we can do about it on this project side. Please open bower-related issues in the bower repository.
