### ISSUE TITLE
For Tabs generated by ng-repeat, in tab-heading a call to a function that has $location.path(url) causes a weird page reload after redirect.

### ISSUE THREAD

**Issue by ksmirnoff** [angular-ui/bootstrap#3266]
I was using angularjs 1.2 and ui-bootstrap-tpls-0.11.0. Works great!. I am generating tabs dynamically using ng-repeat. 
<tabset>
            <tab ng-repeat="item in items">
                <tab-heading>
                   <div class="rmv-item" ng-click="objMain.removeSelVal(item.id)">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                    </div>
                </tab-heading>
                ...
            </tab>
</tabset>

In MainController.js I have a function
$scope.objMain.removeSelVal = function(id){
    // remove item from items collection based on the passed id and reload the page
    $location.path('/myroute/' + ids of remaining items);
};

When a user clicks on removeSelVal inside of each tab the selected id gets passed to a function in the main controller. This function removes one item and passes the new items collection to 'myroute'. Worked great in version 0.11.0. After the upgrade to 0.12.0 it stopped working. It does the redirect to 'myroute' but then does another redirect to an empty route. I can't use 0.11.0 with angular 1.3 since it breaks typeahead so I had to roll back to angular1.2 Hope the fix for 0.12.0 is coming soon. Thank you

**Comment by karianna** [comment]
@ksmirnoff Can you provide a plunkr?
