### ISSUE TITLE
Single toggle doesn't initialized to the right state

### ISSUE THREAD

**Issue by nicolabortignon** [angular-ui/bootstrap#3268]
Given this scenario

 button type="button" class="btn btn-primary" ng-model="release.isActive" btn-checkbox btn-checkbox-true="1" btn-checkbox-false="0"> Activate </button 

 button type="button" class="btn btn-primary" ng-model="release.isActive" btn-checkbox btn-checkbox-true="0" btn-checkbox-false="1">Deactivate</button 

I would expect that given release.isActive = {0,1}   at least one of the two buttons turn into an active state

**Comment by karianna** [comment]
@nicolabortignon Can you demonstrate with a plunkr?

**Comment by wesleycho** [comment]
You should use `btn-radio` for that purpose if one wants to do something like that.

**Comment by wesleycho** [comment]
This also appears to work in `master`, as demonstrated [here](http://plnkr.co/edit/adBGXxOumEmgKMT9d6HZ?p=preview).
