### ISSUE TITLE
Datepicker min/max-date validation

### ISSUE THREAD

**Issue by mletynski** [angular-ui/bootstrap#3269]
Shouldn't those two attributes make a some kind of validation also ? When they are set i cannot chose wrong date from picker but for e.g i can click Today which can be invalid. Also of course i can set date manually through input. 
I was trying to add separate directive for that but i'm expecting problem with multiple directives.

"Multiple directives [dateRange, datepickerPopup] asking for new on: {3}"

Any hint ?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support
