### ISSUE TITLE
Add an autoclose option in "Alert"

### ISSUE THREAD

**Issue by laac** [angular-ui/bootstrap#3277]
Is there a possibility to add an autoclose option in Alert ?
something like this : 
```
<alert ng-repeat="alert in alerts" type="alert.type"  close="alert.close()" autoclose="10000">{{alert.msg}}</alert>
```
and in the directive, have something like this :
```
if (autoclose) {
$timeout(alert.close, autoclose);
}
```

**Comment by RobJacobs** [comment]
@laac This pull request https://github.com/angular-ui/bootstrap/pull/2854 adds that feature.
