### ISSUE TITLE
Impossible to open a modal inside a div

### ISSUE THREAD

**Issue by natcohen** [angular-ui/bootstrap#3282]
Modals open in body by default but it should be possible to open it in a specific div (by id maybe?)

**Comment by karianna** [comment]
plunkr please

**Comment by thomaspaillot** [comment]
Here's a [plunker](http://plnkr.co/edit/Guuu2kwcbkQWw6XyVLZ2?p=preview) with a modal opened inside a specific div. I can take a look at how to do it if it's a feature your interested in.

**Comment by antoinepairet** [comment]
I am not sure this is a behaviour we want to have.
As the core team is currently focused on angular 1.3 support, I am putting it in the purgatory.
regards

**Comment by natcohen** [comment]
@thomaspaillot how did you do that? AngularUI looks for the body in order to display the modal... how can you change the behavior without modifying angularui tpls file?

**Comment by thomaspaillot** [comment]
It's not possible with AngularUI right now, the plunkr I made is just a demo that use the angularUI template to show how it was supposed to look but It doesn't use the directive.

**Comment by wesleycho** [comment]
This is not something that Bootstrap supports, and so I do not believe this is something we should support either since there is no guarantee that a breaking change won't be made in the CSS.

**Comment by mshefeeqb** [comment]
It's possible in AngularUI. In angularUI, there is an option to append a parent element and add position absolute to the '.modal' class. In that way, i can possible to show modal in a div
