### ISSUE TITLE
unselect seleceted row in nggrid by clicking outside of the grid

### ISSUE THREAD

**Issue by swathi1029** [angular-ui/bootstrap#3283]
Hi,

        I had a problem while using nggrid. I had a requirement in my project that I need to unselect the selected row in the nggrid when I click outside of the grid i.e., I need to loose focus when I click outside of the grid. I want to apply this functionality to all the grids where I have used in my project.  

          As I was new to github I don't know where to post these type of question so please give me a reply.

Thanks,

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support
