### ISSUE TITLE
ng-bind-html with UI Bootstrap directives

### ISSUE THREAD

**Issue by nikolaz111** [angular-ui/bootstrap#3287]
I don't think this is directly an issue but I don't know how to do this. I'm trying to dynamically load content that uses UI Bootstrap directives but when the content is loaded UI Bootsrap components don't work. Being more specific, tooltips don't work. Here is the important code:
```html
<div ng-bind-html="trustSnippet(f.field.contentAfter)"></div>
```
```javascript
$scope.trustSnippet = function(snippet) {
          return $sce.trustAsHtml(snippet);
};
```
The HTML I'm trying to inject is: 
```html
<i class="fa fa-exclamation-circle" tooltip-placement="right" tooltip="On the Right!"></i>
```
Any clues?

TY

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support
