### ISSUE TITLE
Duplicate directives error.

### ISSUE THREAD

**Issue by SgtPooki** [angular-ui/bootstrap#3289]
We just ran into an issue on my current project where the [duplicate directives in your ui.bootstrap.dropdown example](http://angular-ui.github.io/bootstrap/#/dropdown) are breaking when you are using angular-bootstrap v0.11.0. 

Click the plunker link here and then change the ui-bootstrap version to 0.11.0 to see the error: 

> Error: [$compile:multidir] Multiple directives [dropdown, dropdown] asking for 'dropdown' controller on: <span class="dropdown" dropdown="" on-toggle="toggled(open)">
http://errors.angularjs.org/1.2.16/$compile/multidir?p0=dropdown&p1=dropdow…%3D%22dropdown%22%20dropdown%3D%22%22%20on-toggle%3D%22toggled(open)%22%3E

I realize this is an older version and you'll probably close this ticket immediately, but I figured this may help some people who run into a similar situation, and I also think there are a few problems to address regarding this.

Can update the example code to specify that you need 0.12.0 or greater, or that previous versions should use the class directive only? 

Also, maybe I am missing something, but why would you ever want the the same directive on any element twice..? I skimmed through #2156, and it sounds like there was a conflict between [non-angular bootstrap dropdowns](http://getbootstrap.com/components/#dropdowns) and [angular-bootstrap dropdowns](http://angular-ui.github.io/bootstrap/#/dropdown).

**Comment by rvanbaalen** [comment]
For startes, don't use both the Twitter Bootstrap JS and UI Bootstrap in one project side-by-side. UI Bootstrap is designed to *replace* Twitter Bootstrap JS (not the CSS) so you don't need a jQuery dependency in your Angular projects.

This is probably not an issue if you don't include the Twitter Bootstrap JS and use the latest 0.13.0 release.
