### ISSUE TITLE
nav close after routing

### ISSUE THREAD

**Issue by andyf625** [angular-ui/bootstrap#3290]
apologies if this has been asked and answered previous but i couldn't find an exact answer.

is there a way to automatically close the nave bar after routing to a specific link, 

i got it to work but just adding ng-click="isCollapsed = !isCollapsed"
too each link like this
http://jsfiddle.net/945r1zjy/

but the problem im having is that when the nav bar is in desktop its applying the collapse to it and getting a brief collapse (slide up effect on the nav) in-between state changes

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support
