### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by adriangrande** [angular-ui/bootstrap#3295]
$scope.users = all_users;
$scope.itemsPerPage = 5;
$scope.currentPage = 1;

// when using arrays something divides my totalItems by 2, 
// so for this to present proper pagination I have to multiply by 2 like so
$scope.totalItems = $scope.users.length * 2;
 
$scope.$watch('currentPage + itemsPerPage', function() {
  var begin = (($scope.currentPage - 1) * $scope.itemsPerPage),
      end = begin + $scope.itemsPerPage;

  $scope.paginatedUsers = $scope.users.slice(begin, end);
});

When I use angular resource I have zero issues similar to this one.  It is only an issue when I use an array as a "resource".

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
