### ISSUE TITLE
Migration in angularjs 1.3

### ISSUE THREAD

**Issue by mdshohelrana** [angular-ui/bootstrap#3296]
Hi, we are using this plugin, but we want to move our project to angular js 1.3. can you tell me that when will we get the update version of the bootstrap according to 1.3?

**Comment by mgoldsborough** [comment]
https://github.com/angular-ui/bootstrap/issues/2830

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support
