### ISSUE TITLE
Allow for custom classes on tooltips

### ISSUE THREAD

**Issue by mkielar** [angular-ui/bootstrap#3298]
When I define a tooltip on an element like this:

    <td data-tooltip-placement="right" 
        data-tooltip="Tooltip text..." 
        data-tooltip-append-to-body="true">...</td>

there is no way of specifying a custom css class for the tooltip. I have a need of having different tooltips with different colors, and it seems impossible now with ui-bootstrap. Something like `data-tooltip-class` would help a lot.

**Comment by mkielar** [comment]
Ekhem, forgive me asking, but, a duplicate of what? I've reviewed the open and closed issues, and only found these:
- https://github.com/angular-ui/bootstrap/issues/1976 (closed as a duplicate)
- https://github.com/angular-ui/bootstrap/issues/2531 (closed but does not fix the issue)

**Comment by RobJacobs** [comment]
I believe it was closed as a duplicate of this issue: https://github.com/angular-ui/bootstrap/issues/3126  Before opening an issue, it's best to do a search for an existing issue and commenting on that.
