### ISSUE TITLE
Scope Overlap Issue in Bootstrap Components

### ISSUE THREAD

**Issue by swolfand** [angular-ui/bootstrap#3302]
* **Angular Version:** 1.2.16
* **Angular-UI Bootstrap Version:** ui-bootstrap-tpls-0.12.0.
* **Bootstrap Version:** 3.1.1 

--------
#### Problem Description
The issue is that when using the angular-ui bootstrap components there is a scope overlap issue if the user happens to name their controller with the same name as a controller in the underlying angular-ui code. I was able to recreate the example for two different components

#### First Example:
* **Underlying Code File:** https://github.com/angular-ui/bootstrap/blob/master/src/accordion/accordion.js
* **Line:** 7

##### Screenshot
![screen shot 2015-02-16 at 12 28 20 pm]
(https://cloud.githubusercontent.com/assets/3825893/6216353/623c86a8-b5d7-11e4-8c2b-c5990722603a.png)

##### Related Plunks

The first example is with the Accordion demo. In the following plunk, I have named my controller AccordionController and the Accordion demo stops working. Compare this to the Accordion Demo that is straight from the angular-ui documentation that functions correctly.

**Plunk That Demonstrates Error:** 
http://plnkr.co/edit/VDPnaFDxEGf9iLTAFMe6?p=info

**Working Plunk:**
http://plnkr.co/edit/?p=preview

----------------------

#### Second Example:
* **Underlying Code File:** https://github.com/angular-ui/bootstrap/blob/master/src/buttons/buttons.js
* **Line:** 8

##### Screenshot
![screen shot 2015-02-16 at 12 41 52 pm](https://cloud.githubusercontent.com/assets/3825893/6216538/3e217b1e-b5d9-11e4-8a65-5035def2979a.png)

##### Related Plunks

The second example is with the buttons demo. In the following plunk, I have named my controller ButtonsController and the button demo stops working. Compare this to the Button Demo that is straight from the angular-ui documentation that functions correctly.

**Plunk That Demonstrates Error:** 
http://plnkr.co/edit/m19N8VDq7FP1pJco5DNc?p=preview

**Working Plunk:**
http://plnkr.co/edit/j2PbiM3xzofUt1W8SHCy?p=preview

#### Solution:
The easiest solution would be to list the names of the controllers that should be avoided.

**Comment by wesleycho** [comment]
That is fair.

It should be noted that fixing #3396 would also fix this. If you would like to submit a PR that adds a note about the directive controller for each component (it should be added in the `readme.md` file for each component, since they are discrete modules), I would be happy to review it and get it in.

**Comment by swolfand** [comment]
I'd be happy to do that for the current and future controllers. I was
trying to find some isolate scope tool in angular to somehow encapsulate
the ui-bootstrap controllers from the user but this solution is a good
workaround

**Comment by icfantv** [comment]
@swolfand, were you still planning on doing this?

**Comment by wesleycho** [comment]
Closing, as this is going to be tackled as a part of #4373.
