### ISSUE TITLE
Detecting when the user leaves the typeahead

### ISSUE THREAD

**Issue by g00glen00b** [angular-ui/bootstrap#3303]
I'm using the `typeahead-editable="true"` attribute and I would like to show some error messages if the user did not choose a valid object from the typeahead.
I see that the directive sets an `editable` property on the `ngModel` controller (`myForm.element.$error.editable`).

However, I would only like to show these errors when the user finishes with editing that field. Is it possible to detect if the user is still changing the field? I tried using the `ng-change` and `ng-blur` directives, but clicking on an item in the typeahead also counts as blurring the field, and it leads to some very weird situations.

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support-1
