### ISSUE TITLE
Tabs to use ng-if over ng-class to delegate active state

### ISSUE THREAD

**Issue by ajwhite** [angular-ui/bootstrap#3306]
Right now a `.tab-pane` is considered active [by providing the `.active` class](https://github.com/angular-ui/bootstrap/blob/master/template/tabs/tabset.html#L6) to toggle between the visibility of the tab. This means that all the tabs that are out of context to the user still remain in context to the system.

If, instead of `ng-class="{active: tab.active}"` we had `ng-if="tab.active"` then we could have the tab opt-in & opt-out of the digest cycle when it's active or inactive.

A couple issues with the `ng-class` approach, other than leaving inactive tabs wired into context, is that when a directive becomes linked, it has no access to accessing the size of elements because it's currently hidden. 

For example, if we have a directive inside the tab accessing `element.width()`, we'll get an inaccurate value when calling this from the linking phase because it's accessed before the tab's `.active` class has been applied. 

---

The downside is the lack of backward compatibility, since an `ng-if` on the tab content will create an isolate scope. So I'd vote that we could opt-in to using an `ng-if` approach in some way. Something like

```html
<tab use-active-class="false"></tab>
```

---

A simple way to reproduce would be to take a directive like so
```js
function directive () {
  return {
    restrict: 'E',
    link: function (scope, element) {
       console.log(element.closest('.tab-pane').hasClass('active'));
    }
  }
}
```
And toggle between the tabs -- it won't be able to reach a `true` state

**Comment by wesleycho** [comment]
Closing as per comment in https://github.com/angular-ui/bootstrap/issues/2637#issuecomment-141088998
