### ISSUE TITLE
DatePeeker weeks

### ISSUE THREAD

**Issue by Adhara3** [angular-ui/bootstrap#3307]
Dear all,

there are a couple of issues here:
- Week number doeas not reset with January. You can easily see this in the official Plunker. In january 2015 week number reaches 57
- show-weeks does not work in popup. Probably this is not a bug, but a nice to have instead.

Thanks
Andrea

**Comment by chrisirhc** [comment]
#2306 resolves this but hasn't been merged yet. Linking here for reference.

**Comment by wesleycho** [comment]
Closing, as #2306 is now in.

**Comment by Adhara3** [comment]
Thanks!
