### ISSUE TITLE
Modal scope not destroyed

### ISSUE THREAD

**Issue by PaddyMann** [angular-ui/bootstrap#3308]
On closing and reopening a modal, the original scope persists (angular 1.3.13 ; angular-ui-bootstrap v 0.12.0)

Seems to be the same issue as this closed one: https://github.com/angular-ui/bootstrap/issues/1643

Adding the following to modalWindow directive will fix (though there may be a better solution):

```
        element.on('$destroy', function() {
          scope.$destroy();
        });
```

**Comment by johnparn** [comment]
I have the same issue using  AngularJS 1.3.9 and ui-bootstrap 0.12.0. 

@PaddyMann: exactly where did you place this?

**Comment by bimal1331** [comment]
Will it ever get fixed?

**Comment by chrisirhc** [comment]
Please post a Plunker to demonstrate this is broken.

**Comment by bimal1331** [comment]
Apologies, my mistake. It turned out to be inheritance issue for me. The modal scope was getting destroyed. Thanks.
