### ISSUE TITLE
Datepicker - limiting days to selected month

### ISSUE THREAD

**Issue by cssensei** [angular-ui/bootstrap#3309]
By default datepicker lists the days from the previous month and the next month.
Can we add a directive parameter to hide these days?

**Comment by rvanbaalen** [comment]
Directive parameter or `datepicker-options` config parameter?

**Comment by cssensei** [comment]
Ideally it should be a option inside `datepicker-options` that would change the hardcoded `42` from [this line] (https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L242) into the number of days of the selected month.

**Comment by rvanbaalen** [comment]
... or simply hide 'secondary' days in the view?

Name the option something like `onlyShowDaysOfMonth` (too long?)

**Comment by rvanbaalen** [comment]
By the way, I was looking at your plunker and thinking.. the value is actually a `Date` object.
On a `Date` object you can do `.getWeek()` to get the week number from the selected date.

So basically, you already got your solution in your plunker. Just set the date format to `w` or `ww` (for padded value like `09`) and you're done! It now shows the selected week when one of the days is selected. 

Combine it with a `max-mode` of `'day'` and I suppose you're good to go.

**Comment by cssensei** [comment]
@rvanbaalen I don't recall adding and plunker example to this issue...

**Comment by Vortilion** [comment]
You just need to customize the loaded template for that snippet:

[Plunkr](https://plnkr.co/edit/xJ2DQpKdB91JjicPlWUn?p=catalogue)

Basically I just changed the conditions for the button element, which represents the day, to the same as the different text-color:

 ng-hide="dt.secondary"

, because I noticed that the previous and next days have a different styling based on the controller-field dt.secondary.

**Comment by wesleycho** [comment]
After thinking about this, going to close this as something we won't support due to implementing this properly in the library level is difficult - seeing as there are potentially adequate workarounds, is ok IMO that we don't support this.
