### ISSUE TITLE
Something wrong with 'ng-invalid' and 'ng-invalid-parse' classes if 

### ISSUE THREAD

**Issue by dimylik** [angular-ui/bootstrap#3311]
So, imagine you paste 'Arizona' in to input text, and you have drop-down with one 'Arizona' item coming as preloaded items, if you select that one item with mouse or just click Enter on input, value gets selected, but bootstrap classes 'ng-invalid' and 'ng-invalid-parse' stays on input field, so it has red background.
But if you paste 'Arizon' without last letter and do the same, everything is fine and valid

Looks like onChange() function does now occurs if text and selected item are the same.

My workaround, manual removing 'ng-invalid' and 'ng-invalid-parse' with ng-class:

<input class="form-control search-field"
		type="search"
		ng-model="ngModel"
		placeholder='Search terms ...'
		typeahead="term as (term.name) for term in searchTerms($viewValue) | filter:$viewValue"
		typeahead-min-length="2"
		typeahead-wait-ms="300"
		typeahead-editable="false"
		ng-class="{'ng-invalid' : !ngModel, 'ng-invalid-parse' : !ngModel}"
		autocomplete="off">

Please fix !

**Comment by karianna** [comment]
plunkr please.

**Comment by juffee** [comment]
http://plnkr.co/edit/3nkVcTAT89ik9l6s97G0?p=preview
Here's a plunkr but it seems to happen here only if for example you type 'Ohio', backspace/delete 'o', type 'o' again, then 'tab'. It gets stuck with a 'ng-invalid-parse'. But if you type 'Ohio' in one go, its ok.

angular 1.3.3
angular-ui-bootstrap 0.12

**Comment by rvanbaalen** [comment]
@juffee Can you verify that PR #3352 fixes the problem you described?

**Comment by juffee** [comment]
@rvanbaalen Yes it does fix it.
