### ISSUE TITLE
Popover top placement

### ISSUE THREAD

**Issue by viros** [angular-ui/bootstrap#3313]
Use dynamicPopoverTitle and remove/add a title. Popover position doesn't recalculated.
Here is a plunker http://plnkr.co/edit/1ZWOA6Bnt4WlhtoP1HFU?p=preview. 
Try select/unselect checkbox while popover is shown.

**Comment by karianna** [comment]
plunkr please

**Comment by chrisirhc** [comment]
See #1848 . I plan to create a separate PR for repositioning.

**Comment by chrisirhc** [comment]
Will be resolved through #3435

**Comment by wesleycho** [comment]
Closing, #3435 was merged.

Let us know if this is still an issue.
