### ISSUE TITLE
[DOC] Tooltip example on documentation page

### ISSUE THREAD

**Issue by chris-verclytte** [angular-ui/bootstrap#3316]
Hello everyone,

I am currently working on tooltip component and I just  paid attention to the examples provided in the documentation and see this type of example: 
`<a href="#" tooltip="{{dynamicTooltip}}">{{dynamicTooltipText}}</a>`
 
It seems to me that it should be preferable to work with button as `href="#" ` is not a good semantical practice. Thus, should it not be better to replace this example by something like:
`<button tooltip="{{dynamicTooltip}}">{{dynamicTooltipText}}</button>`

**Comment by wesleycho** [comment]
In this case, the anchor tag is inline in the text though - button isn't quite right either, as buttons tend to be discrete elements apart from a sentence.

I am not quite sure there is a better fit than an anchor tag here. In fact, you see Bootstrap itself use anchor tags as well in its [tooltip](http://getbootstrap.com/javascript/#tooltips).

Closing as invalid, feel free to respond with more information.
