### ISSUE TITLE
Dropdown menu is not working with 12.1. Works fine with 11.0

### ISSUE THREAD

**Issue by chachou29** [angular-ui/bootstrap#3324]
Hello,
Dropdown menu is not working with 12.1. 
Works fine with 11.0
http://plnkr.co/edit/GE2R735h6XZvOCdpLFOf?p=preview
Any workaround ?
Thank you !

**Comment by antoinepairet** [comment]
See release notes of 0.12 and the breaking changes:
https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#breaking-changes

Your fixed plunkr: http://plnkr.co/edit/BFw2bsgZEmJwtAfH7Vi1?p=preview
