### ISSUE TITLE
Compile:tplrt error when using tabsets and/or tabs

### ISSUE THREAD

**Issue by 4rlekin** [angular-ui/bootstrap#3325]
Hi, i just started with angular-ui and i noticed weird problem.
When i try to use tabset or tab directives i got this error:
https://docs.angularjs.org/error/$compile/tplrt?p0=tabset&p1=template%2Ftabs%2Ftabset.html

I checked that other directives (i didn't check them all) don't cause such problem.
Im using angular 1.12.6 and ui-bootstrap 0.12.1 with bootstrap css in version 3.3.2

I hope its just something silly, since i didn't find any SO question or anything i hope its just my mistake.

**Comment by antoinepairet** [comment]
We cannot help you without a reproducible scenario, ie plunkr.
Closing for now

**Comment by nult2003** [comment]
i even have error such you. i use bootstrap on .net. It's ok on plunker
