### ISSUE TITLE
How to disable calendar in datepicker control

### ISSUE THREAD

**Issue by swathi1029** [angular-ui/bootstrap#3327]
I have a datepicker which is in datepickerctrl controller and I have a checkboc in some other controller. I have to enable datepicker control when checkbox is checked. I am able to disable the textbox in the datepicker control by using ng-disabled="disabled" but the calender in datepicker control is not disabled. Is there any solution for this.

**Comment by antoinepairet** [comment]
https://github.com/angular-ui/bootstrap#support

If you think you found a bug, provide a reproductible scenario, ie a plunkr
