### ISSUE TITLE
Accordion:  Expand/collapse on ng-click seems broken

### ISSUE THREAD

**Issue by smaye81** [angular-ui/bootstrap#3328]
What I'm trying to accomplish is limiting the expand/collapse of the accordion to a single button click on the heading rather than it happening when *anything* is clicked.  

This plunk with Angular 1.2.x works exactly as intended:

http://plnkr.co/edit/wByMeIM3UwHyxyIAcVWB?p=preview

However, the exact same code with Angular 1.3 does not.  Nothing expands and the button will no longer control expand/collapse of the accordion group:

http://plnkr.co/edit/8Gtu6Xo9JWuPuvnJpkPO?p=preview

Both display console errors that state:

 ```Error: [$compile:nonassign] Expression 'canOpen == true' used with directive 'accordionGroup' is non-assignable!```

However, the Angular 1.3 version seems to completely fail.  Not sure if this is an issue with 1.3 or with the directive itself.

Regardless, here is another plunk that fixes the non-assign error by using paths and not an equals expression for the is-open directive.  However, this seems to completely ignore the ng-click altogether:

http://plnkr.co/edit/eqZKlsVv1qraG761AbET?p=preview

**Comment by smaye81** [comment]
FYI:  I removed the 1.3 portion of the issue name since this issue seems unrelated to 1.3

**Comment by Foxandxss** [comment]
Yo!

The issue in here is that clicking on the header (button or not) will set `isOpen` to `!isOpen`.

So if `isOpen` is false, when you click on the header, it is set to true but if you click on the button, the directive will set it to true and then the button will set it to false so it will never change.

The `isOpen == true` is not a valid syntax for what the directive is expecting (which is not a boolean as you want it to).

**Comment by smaye81** [comment]
So is this actually a bug?  The functionality you describe above doesn't seem to be expected behavior to me.

**Comment by Foxandxss** [comment]
To be honest, it always worked like that and I never questioned it.
