### ISSUE TITLE
Changelog: references to commits are broken

### ISSUE THREAD

**Issue by rvanbaalen** [angular-ui/bootstrap#3332]
The references to commits in the changelog are broken:

https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md

For example, it links to:

```
https://github.com/angular-ui/bootstrap/blob/master/angular-ui/bootstrap/commit/992b23297cd100ab4e236fba469e3a70566a4163
```

instead of

```
https://github.com/angular-ui/bootstrap/commit/992b23297cd100ab4e236fba469e3a70566a4163
```

**Comment by karianna** [comment]
@chrisirhc Are you able to take a look at this?

**Comment by rvanbaalen** [comment]
Perhaps updating `grunt-conventional-changelog` to `v1.1.0` might help instead of sticking to `v0.1.2`

**Comment by chrisirhc** [comment]
Actually, it seems that this issue is due to me mistakenly using `v1.1.0` of `grunt-contentional-changelog`.   `v0.1.2` seems to generate the correct URLs. I haven't looked into why exactly this is happening.

**Comment by chrisirhc** [comment]
Looks like it's because the new version of grunt-conventional-changelog expects a repo url in the package.json .
