### ISSUE TITLE
Use click function in modal's child elements?

### ISSUE THREAD

**Issue by paulinetheitgirl** [angular-ui/bootstrap#3334]
I have a custom modal template, but the button to close doesn't do anything on click and there are no errors in the console.
```
<div tabindex="-1" role="dialog" class="modal fade" ng-class="{in: animate}" ng-style="{'z-index': 1050 + index*10, display: 'block'}" ng-click="close($event)">
    <div class="modal-dialog" ng-class="{'modal-sm': size == 'sm', 'modal-lg': size == 'lg'}">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" ng-click="close($event)"><span aria-hidden="true">Close&times;</span></button>
            </div>
            <div class="custom-modal" modal-transclude></div>
        </div>
    </div>
</div>
```

**Comment by karianna** [comment]
plunkr please - https://github.com/angular-ui/bootstrap#support

**Comment by paulinetheitgirl** [comment]
Plunkr: http://plnkr.co/edit/atEaIWsh6pXeDSFBFBaO?p=preview
Thanks karianna

**Comment by Narretz** [comment]
But in the plnkr, it works ...

**Comment by antoinepairet** [comment]
Here is a working plunkr: http://plnkr.co/edit/AWXNHPEDzhOOe0q7aBwO?p=preview

There are 2 issues with your code:
1. The function "close" is not defined
2. There exists a "$close" function which is defined in the tranclude controller. Therefore, it can not be called within the window template. It can be called from the modal template.

regards,
