### ISSUE TITLE
DatePicker format not applied on init in Angular 1.3

### ISSUE THREAD

**Issue by jdelaune** [angular-ui/bootstrap#3335]
You can see the issue using the plunker from the example all I did was change angular from 1.2 to 1.3:

http://plnkr.co/edit/pWQUvGfCqlN4aBVCLku5?p=preview

Notice the format of the date of the date in the popup date picker field, and then select a date using the date picker and the correct format is applied. But not on init.

**Comment by karianna** [comment]
@antoinepairet Is this fixed on HEAD?

**Comment by antoinepairet** [comment]
Yes, it is fixed in HEAD
