### ISSUE TITLE
Datepicker - year-range seems to be completely ignored

### ISSUE THREAD

**Issue by rvanbaalen** [angular-ui/bootstrap#3338]
When I use the `year-range` attribute on my `datepicker-popup` directive, it seems to be completly ignored.

I set it to value `9` like this:

```html
year-range="9"
```

and also tried this:

```html
year-range="'9'"
```

But both don't work and this is always the result:

![screen shot 2015-02-25 at 14 21 09](https://cloud.githubusercontent.com/assets/220637/6378302/e0dd5c8c-bd00-11e4-85ad-143cc26c908b.png)

I would expect the datepicker to show the years in a 3x3 grid (9 total).

I'm using UI Bootstrap `0.12.1` and Angular JS `1.3.13`

**Comment by karianna** [comment]
@antoinepairet Sorry to keep piling these on you, but thought it was worth checking if fixed on HEAD

**Comment by rvanbaalen** [comment]
It has everything to do with [this](https://github.com/angular-ui/bootstrap/blob/5f9afe5a86af0e207eaacd6a9b1f202fd78d7009/src/datepicker/datepicker.js#L30) fancy line of code (which is very hard to read):

```js
self[key] = angular.isDefined($attrs[key]) ? (index < 8 ? $interpolate($attrs[key])($scope.$parent) : $scope.$parent.$eval($attrs[key])) : datepickerConfig[key];
```

`$attrs.yearRange` is not defined. Therefore, the default `datepickerConfig` option is selected.

**Comment by rvanbaalen** [comment]
I've rewritten that oneliner to a more debuggable block:

```js
if(angular.isDefined($attrs[key])) {
          if (index < 8) {
              var val = $interpolate($attrs[key])($scope.$parent);
              self[key] = val;
          } else {
              var val = $scope.$parent.$eval($attrs[key]);
              self[key] = val;
          }
      } else {
          self[key] = datepickerConfig[key];
      }
```

Now I'm wondering -- why loop through injected `$attrs` service? That service does not seem to be picking up the attributes set on my element (such as `year-range`).

**Comment by rvanbaalen** [comment]
Well for now I've worked around this issue by setting `yearRange` as a property of my `datepicker-options` object. I still think this should be fixed but due to the complexity of the `DatepickerController` I haven't been able to create a solid fix and thus a PR.

**Comment by rvanbaalen** [comment]
@karianna That looks promising.. there won't be a fix any time soon? :wink:

**Comment by karianna** [comment]
@antoinepairet Is our resident datepicker maintainer (at present) - we'll be looking at all of the related PRs over the coming weeks (it's going to take some time) :-)

**Comment by rvanbaalen** [comment]
@karianna @antoinepairet If you're able to shortly explain to what your process is to check these related PRs I might be able to help out. I wouldn't mind being a contributor for the datepicker module. I'm using it a lot in projects are able to debug issues / implement fixes.

For now I'll stick to PRs but you guys already have a lot of these pending.

**Comment by karianna** [comment]
@rvanbaalen If you'd like to become a maintainer then you'd be more than welcome.  Please join the gitter where we discuss merges etc.  We'll have a meeting to triage PRs next week as well IIRC

**Comment by rvanbaalen** [comment]
I would definitely be interested in becoming a contributor @karianna. I did find the gitter indeed. Just need to catch up with everything going on there.

**Comment by karianna** [comment]
Can't see why this is a angular 1.3 support issue - moving to 0.13.x

**Comment by rvanbaalen** [comment]
The 0.13 milestone was added before we had a meeting about the contents of 0.13 :wink:

**Comment by davious** [comment]
Would like to help, but I'm confused about what's wanted here.
Would we like the popup directive to pass through the `year-range` attribute to the datepicker?
