### ISSUE TITLE
Make it possible to customize datepicker icons

### ISSUE THREAD

**Issue by thesamet** [angular-ui/bootstrap#3339]
Currently the icons are hard coded to be glyphicon chevron left/right. It would be nice to customize it (for those who use alternative icon libraries).

Will you take a pull request that makes the icon configurable through the datepicker settings objects?

**Comment by gamebox** [comment]
I'd like to second that notion.  Right now, I am forced to write a hack to hijack the styles to use FontAwesome, so I don't have to use two icon libraries.

**Comment by rvanbaalen** [comment]
:+1:

**Comment by maxfierke** [comment]
I extracted my work from #3478 to an Angular module that you can include which overrides the necessary templates so that you don't need to provide overriden copies yourself.

You may find it useful: [maxfierke/ui-bootstrap-fontawesome](https://github.com/maxfierke/ui-bootstrap-fontawesome)

**Comment by NewMediaRoc** [comment]
+1

**Comment by rvanbaalen** [comment]
For everyone else interested: use @maxfierke's solution. Customize the templates to your needs if you need to change anything like icons etc.
