### ISSUE TITLE
Validation issue e.g. 2015-02-30

### ISSUE THREAD

**Issue by fslembro** [angular-ui/bootstrap#3342]
This issue happen with IE11, not with Chrome 40.

When I manuel insert as date e.g. 2015-02-30. then in chrome it will get ng-invalid, in IE this is accepted.

dates like 2015-02-99 are invalid in both browsers.

Regards

**Comment by wesleycho** [comment]
Have you tested this with the latest from master? Can you create a [Plunker](http://plnkr.co/) illustrating this?

**Comment by gregmuellegger** [comment]
I assume that it's related to this JS behaviour:
![image](https://cloud.githubusercontent.com/assets/88278/6843538/6d096b74-d3a4-11e4-95c5-39fee75417f5.png)

Tested in Chromium Version 41.0.2272.101 (64-bit) on Linux

Firefox does the right thing:
![image](https://cloud.githubusercontent.com/assets/88278/6843569/9fa5a1d8-d3a4-11e4-9460-3d69b3362cb0.png)

**Comment by wesleycho** [comment]
Can you try using this proposed patch from #3759? In particular, try copy/pasting the built version of UI Bootstrap from [this Plunker](http://plnkr.co/edit/k54L20Ux3VkND7yAK2Kh?p=preview) and let me know if this fixes the issue.
