### ISSUE TITLE
Add support for weekpicker

### ISSUE THREAD

**Issue by thuey** [angular-ui/bootstrap#3343]
Often in my projects, I need a weekpicker. There aren't very many good solutions out there, and none for angular. It would be awesome if weekpicker was added as a datepicker mode.

**Comment by rvanbaalen** [comment]
How would you select the week? By number? 

And how would the pagination work out? +/- 20 weeks per page? Or 17 to have 3 pages exactly?

I could create a PR if you give me some more details about the implementation

**Comment by thuey** [comment]
I think the easiest interface to use would be a calendar, similar to the daypicker, except you choose a week at time ([example](http://www.tikalk.com/incubator/week-picker-using-jquery-ui-datepicker/)). 

It's easier to visualize, plus it allows you to choose both a day and week at the same time, if needed. Something like this: [http://plnkr.co/edit/YU4gPG?p=preview](http://plnkr.co/edit/YU4gPG?p=preview).

**Comment by ValentinH** [comment]
:+1: 
I am also looking for a weekpicker and haven't found anything for Angular.
The best example I've found is this one which is an Ember component:
http://rsschermer.github.io/ember-rl-week-picker/

**Comment by rvanbaalen** [comment]
Basically, by taking @thuey's plunkr and adding 'w' and 'ww' date format support to the dateParser, you have yourself a weekpicker. You could just set the format to `yyyy ww` for instance which could result in `2015 12` for week 12 in 2015.

That being said, the dateParser needs some extra love to support a wider variety of date formats.

**Comment by Foxandxss** [comment]
Our datepicker is a monster, all I want is to remove features from it.

I am sorry, I am not considering doing any of this for the time being.
