### ISSUE TITLE
Modal dialogs not modal in IE10 with bootstrap version 3.3.1 and 3.3.2

### ISSUE THREAD

**Issue by lkierstead** [angular-ui/bootstrap#3346]
When using bootstrap version 3.3.1 or 3.3.2 modal dialogs are not modal in IE 10.  They work fine in Chrome and Firefox.

Here is a plunker demonstration (use IE):

http://plnkr.co/edit/16atD4hkk4h4FK1iDd8j?p=preview

Notice you can still click the background buttons when the modal is open.

Now change the version of the bootstrap css to 3.3.0 (in the index.html file) and notice this issue goes away.

**Comment by pkozlowski-opensource** [comment]
@lkierstead when closing as a duplicate we should link to a duplicated issue no, I guess....

**Comment by karianna** [comment]
My bad: https://github.com/angular-ui/bootstrap/issues/2970 & https://github.com/angular-ui/bootstrap/issues/3184
