### ISSUE TITLE
$dialog, modal and location change

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular-ui/bootstrap#335]
Created based on https://github.com/angular-ui/angular-ui/issues/538 from the angular-ui repo:

> I have run into an issue with Modals and Dialogs when a browsers back button is pressed while a modal and glassis visible. (in a multi page app).

The application changes the view and controller while the modal stays activated and visible. As the controller has been swapped out from underneath the modal, strange things start happening.

How do we get around this issue? Is there a way to make sure the modal / dialog is dismissed when the back button is dismissed or the route is changed.

It is an interesting problem, we should consider closing modals on location change. The thing that the modal stays open while controllers can be sapped underneath sounds like a buggy situation.

**Comment by awerlang** [comment]
If using ui-router and the modal itself triggers a state change, the code could be like this:

```js
$state.go('state').then(() => $modalInstance.close())
```

If you use `$state.go()`, then the promise is fulfilled before a `$locationChangeStart` event is raised. By the time the event is handled, there would be no more tracked modals.

Rest of code by @jglinsek above.

**Comment by swapnilchincholkar** [comment]
@jglinsek, thanks a ton !! saved my day.

**Comment by filipesilva** [comment]
@timsly's solution did it for me as well. 

I agree with @pkozlowski-opensource in that something similar should be added to `ui-bootstrap` because of the implications of closing a modal in a state other than the one that opened it.

**Comment by jajourda** [comment]
If the back button is clicked on initial page load, the default behavior happens too fast for the function to be considered so I did the following:

 $rootScope.$on('$locationChangeStart', function (event) {
        event.preventDefault();
        var top = $modalStack.getTop();
        if (top) {
            $modalStack.dismiss(top.key);

        }else{
            event.defaultPrevented = false;
        }
    });

**Comment by henck** [comment]
The issue remains. My workaround for a specific dialog was

    $scope.$on('$routeChangeSuccess', function () {
      $uibModalInstance.dismiss('cancel');
    });

I couldn't see where to access `$modalStack`.

**Comment by icfantv** [comment]
This is still an issue, I'm going to reopen this.

**Comment by wesleycho** [comment]
One can access $uibModalStack through injection.

```js
$scope.$on('$routeChangeSuccess', () => $uibModalStack.dismiss($uibModalInstance, 'cancel'));
```
or
```js
$scope.$on('$routeChangeSuccess', () => $uibModalStack.dismissAll());
```
Closing as we decided we don't want this level of opinionation in the library itself, and there are enough mechanisms around this built into the library itself to allow the user to control to what degree this happens.
