### ISSUE TITLE
Invalid iteration parsing for typehead

### ISSUE THREAD

**Issue by vitaly-t** [angular-ui/bootstrap#3350]
From the library code below, RegEx that's used restricts your data binding to attributes only:

````
/**
 * A helper service that can parse typeahead's syntax (string provided by users)
 * Extracted to a separate service for ease of unit testing
 */
  .factory('typeaheadParser', ['$parse', function ($parse) {

  //                      00000111000000000000022200000000000000003333333333333330000000000044000
  var TYPEAHEAD_REGEXP = /^\s*([\s\S]+?)(?:\s+as\s+([\s\S]+?))?\s+for\s+(?:([\$\w][\$\w\d]*))\s+in\s+([\s\S]+?)$/;

  return {
    parse:function (input) {

      var match = input.match(TYPEAHEAD_REGEXP);
      if (!match) {
        throw new Error(
          'Expected typeahead specification in form of "_modelValue_ (as _label_)? for _item_ in _collection_"' +
            ' but got "' + input + '".');
      }

      return {
        itemName:match[3],
        source:$parse(match[4]),
        viewMapper:$parse(match[2] || match[1]),
        modelMapper:$parse(match[1])
      };
    }
  };
}])
````

I have dictionaries of data to be linked against using the standard angular syntax of:
````
"(key, value) as value in data"
where
data={
  key1: "val1",
  key2: "val2",
  etc...
}
````

The above restriction makes it very akward, so I need to transform dictionary values somehow before I can use it. There is no reason why dictionaries cannot be used for typeheads. We just need to fix the code above, somehow.

Any idea how to make it work?

**Comment by karianna** [comment]
plunkr please

**Comment by VitalyTomilov** [comment]
A plunk is only good to show when something is broken. Binding to a dictionary in a typehead never worked to begin with because the RegEx that's used doesn't allow for the attribute to begin with (key,value). So i'm not sure what example you are expecting to see. Please clarify.

**Comment by karianna** [comment]
My bad, changing labels.

**Comment by dmitriz** [comment]
The string "(key, value) as value in data" indeed is rejected as invalid expression - just added this test and it passes:

      prepareInvalidDir = function () {
        prepareInputEl('<div><input ng-model="result" typeahead="(key, value) as value in data"></div>');
      };
      expect(prepareInvalidDir).toThrow();

**Comment by vitaly-t** [comment]
@dmitriz Shouldn't this be the other way round, the dictionary should work and there should be a positive test?

Your test suggests that the current restriction is supposed to be there. Why? It should be fixed instead.

**Comment by dmitriz** [comment]
As per documentation http://angular-ui.github.io/bootstrap/#/typeahead, supported expressions are

- label for value in sourceArray
- select as label for value in sourceArray

so yes, "(key, value) as value in data" is of not of the type, and is correctly rejected.

**Comment by dmitriz** [comment]
The string "(key, value) as label for value in data" is also rejected, so you can't use parentheses like that inside the expression, as of now.

**Comment by vitaly-t** [comment]
They simply forgot to add `(key, value)`, it is an omission, because there is not reason for not supporting it.

**Comment by dmitriz** [comment]
It it were not rejected, it would become the parsed expression assigned to `modelMapper` here:

https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L26

and then evaluated to `model` here:

https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L259

So how would `(key, value)` evaluate to a single object?

**Comment by dmitriz** [comment]
@vitaly-t Can you give a use case to illustrate the reason why you want object iterators to be added?

**Comment by wesleycho** [comment]
Supporting objects IMO is not a direction we want to go - there have been weird issues reported with ng-repeat supporting so, and it is more awkward in some areas than just using an array, where one has control over the order.

I am closing as something we won't support, as I believe it would be too cumbersome, when one should be using arrays.
