### ISSUE TITLE
Angular 1.3

### ISSUE THREAD

**Issue by sentient** [angular-ui/bootstrap#3353]
Is there an overview which directives work and which one has known issues when I would migrate to angular 1.3.*?

**Comment by karianna** [comment]
Not yet - I'm hoping to put that into the README.md after this week's triaging session

**Comment by sentient** [comment]
I actually did bite the bullet and i am able to use the bootstrap. I don't use too much fancy stuff. Only the bower update gives the issue on   
> "dependencies": {
>       "angular": ">=1 <1.3.0"
>   } 

Would be nice it there is a branch that loosens this restrictions so we can report issues against the 1.3 branch. Or let others know of work arounds.

**Comment by Tavio** [comment]
I have found an issue with angular 1.3 in the datepicker directive, here's the plunker: http://plnkr.co/edit/MYZjqhPSzHU6X4ZQkAlg?p=preview
Basically, the initial date for the popup example does not obey the format defined. I will dive into the code to see what I can find out about fixing this.
