### ISSUE TITLE
Tooltip for disabled input does not disappear

### ISSUE THREAD

**Issue by dimylik** [angular-ui/bootstrap#3354]
Imagine you have input (checkbox or text, or probably any other disabled input)
you show tooltip on mouse over, fine,
than you have some logic to disable input, also fine,
and you can not close tooltip, as mouseleave action does not work on disabled inputs

http://plnkr.co/edit/sgwAvb6fvchYAjeoNhBK?p=preview

Workaround: 
- add ng-click or mouseleave action on tooltip itself to hide tooltip

**Comment by icfantv** [comment]
Closed per #3362.
