### ISSUE TITLE
Glyphicons

### ISSUE THREAD

**Issue by pcnate** [angular-ui/bootstrap#3355]
The example site @ http://angular-ui.github.io/bootstrap/ is attempting to load the glyphicons from the bootstrapcdn which is not loading due to *Cross-Origin Resource policy*

**Error Message in Chrome console**
`Redirect at origin 'http://netdna.bootstrapcdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://angular-ui.github.io' is therefore not allowed access.
`

**Examples**
![image](https://cloud.githubusercontent.com/assets/621940/6467011/1a0b19b0-c191-11e4-9b6e-f9522b23df01.png)

![image](https://cloud.githubusercontent.com/assets/621940/6467024/3ace522a-c191-11e4-9936-b7f5e13ae558.png)

**Browser Infos**
![image](https://cloud.githubusercontent.com/assets/621940/6467080/9bcf81b6-c191-11e4-8ca6-6c87fc4aa349.png)

**Comment by VoltiSubito** [comment]
I have no relationship with this project, but I thought I would jump in here.  This seems like a temporary issue and likely isn't the fault of angular-ui.

@pcnate is this still occurring?  I just tried with my machine and the icons were visible.  I also verified that netdna.bootstrapcdn.com is correctly setting the Access-Control-Allow-Origin header.

This is unlikely a problem with this site.  I suspect either netdna.bootstrapcdn.com wasn't setting the Access-Control-Allow-Origin header correctly, or the beta version of Chrome you are running wasn't interpreting it correctly.  You can check for the header by looking in the network tab in developer tools, finding the line for the glyphicons, and selecting the "Header" tab. In the "Response Headers", you should see a line that says: Access-Control-Allow-Origin:*.

You may also want to try a different browser or a non-beta Chrome.

**Comment by pcnate** [comment]
@VoltiSubito I have had this issue for quite some time. I tried in Firefox 36.0.1 and it does the same thing. Funny thing, IE 11 works. Check this out...

**IE 11 request headers**
![image](https://cloud.githubusercontent.com/assets/621940/6527765/f16e15bc-c3e2-11e4-8e67-7152ab20ccd1.png)

**IE 11 response headers**
![image](https://cloud.githubusercontent.com/assets/621940/6527707/7de36e4e-c3e2-11e4-9d05-0987f9380ff9.png)

**Firefox 36**
http://netdna.bootstrapcdn.com/bootstrap/3.1.1/fonts/glyphicons-halflings-regular.woff
![image](https://cloud.githubusercontent.com/assets/621940/6527834/96460d2e-c3e3-11e4-8da3-22cdff5b91a3.png)

http://netdna.bootstrapcdn.com/bootstrap/3.1.1/fonts/glyphicons-halflings-regular.ttf
![image](https://cloud.githubusercontent.com/assets/621940/6527819/7c01a37e-c3e3-11e4-9a66-cde6b60029d9.png)

Chrome provides a useless output as it is being canceled due to the policy and doesn't provide the headers sent and received (grrr).
![image](https://cloud.githubusercontent.com/assets/621940/6527997/c0654e2a-c3e4-11e4-9088-d6298291ffae.png)

So, it would seem the proxy is dropping the Access-Control-Allow-Origin * header, but only for the ttf and woff files. It is probably misconfigured or not smart enough to cache content for cross domain access.
Unless I am missing something else.

**Comment by wesleycho** [comment]
I'm closing this as resolved, as I am not seeing this issue anymore.

This appears to have been a temporary issue with the Bootstrap CDN.
