### ISSUE TITLE
Widget size limit influencing the Google Map appearance

### ISSUE THREAD

**Issue by audreyaw** [angular-ui/bootstrap#3359]
Hi,

I have an issue with using google map. The background of the map becomes black in the area over the edge of the world map while it should be in its default colour. I've already fiddled with the code and found out that it's caused by limiting the size of the map.

This is my google map code:

```
<article class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
						<div class="jarviswidget jarviswidget-color-white" id="wid-id-1"
							data-widget-editbutton="false" data-widget-deletebutton="false"
							data-widget-fullscreenbutton="false">
							<header>
								<span class="widget-icon"> <i class="fa fa-map-marker"></i>
								</span>
								<h2 th:text="#{global.preview}">Preview</h2>
							</header>
							<div id="map-canvas" class="google_maps"></div>
						</div>
					</article>
```

This is the screenshot:
![map_issue_prtscr](https://cloud.githubusercontent.com/assets/10556371/6481120/464cb78e-c28d-11e4-88ed-402e9141c761.jpg)

I am not sure what I did wrong. If it's something to do with tags, maybe I can send the code file itself and let you have a look. I am really stuck with the issue.

Please kindly help.

Thank you in advance.

**Comment by karianna** [comment]
I'm not even sure that is part of angular-ui/bootstrap?  In any case: https://github.com/angular-ui/bootstrap#support
