### ISSUE TITLE
Angular UI Modal, avoid modal scope change reflects in parent scope

### ISSUE THREAD

**Issue by rahulrulez** [angular-ui/bootstrap#3360]
I am building an Angular app where I want to control which apps in app list I want to show on home page. There is a section called "Manage Apps" where I can manage visible apps..

http://plnkr.co/edit/RPFvv0ZUB2OSctIQM8pQ?p=preview

The plunkr above explains what I want to achieve..

I have passed list of apps in json from parent scope to modal instance. I want to make changes to one field there which is IsPublished.

Now the problem is, whenever I make changes in isPublished field in Modal, it immediately gets reflected in parent scope. You can see apps being filtered in parent scope behind overlay..

I want to avoid it. I want to reflect the changes to parent scope only when I hit save / ok button.

is there any way to do so?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support
