### ISSUE TITLE
How do I change the color of the header?

### ISSUE THREAD

**Issue by crunkyedwards** [angular-ui/bootstrap#3361]
I've looked around on stack-overflow and elsewhere, and can't find a standard way to change the color of the accordion header. 

One insufficient solution is proposed, which is to add a div into accordion-header and change the color of the div, but it doesn't color the margin between the edge of the div and the edge of the header.

**Comment by RobJacobs** [comment]
The accordion markup gets rendered as:
 
    <div class="panel panel-default">
      <div class="panel-heading">
      </div>
    </div>

If you create a class to target the panel heading:

    .my-accordion-heading .panel-heading {
      background-color: blue;
      color: #fff;
    }

You can then add that class to the accordion-group element.  [Example](http://plnkr.co/edit/7IGMir4l3giFiRzo9w7V?p=preview)
