### ISSUE TITLE
Load a HTML inside a div using angularjs

### ISSUE THREAD

**Issue by aksharak** [angular-ui/bootstrap#3363]
Hi,
I have a div inside a HTML page where onclick of few hrefs i want to load html files inside that div. Not hide & Show, want to load them. Like the loading should be only within my div and other contents should be as it is. Is there a good way to do this? Please suggest. Sample would be appreciated.

Thanks in advance.

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support
