### ISSUE TITLE
Tab select method fired during scope destruction if used in Modal Directive

### ISSUE THREAD

**Issue by mu7amed-abdelfata7** [angular-ui/bootstrap#3366]
I used Tabs in Modal ..when modal close or dismiss, then trigger the tabselected, here is the plunkr: 
http://plnkr.co/edit/0pcQYD5ESgQC0COYsObZ?p=preview

The problem is still remaining and did not fix as you discussed in:
https://github.com/angular-ui/bootstrap/issues/2155

 But i made a solution for me to solve the problem:
1- I added this function in TabsetController:

var destroyed = false;
ctrl.destroyTab = function destroyTab(tab) {
console.info("ctrl.destroyTab = function destroyTab(tab) {");
destroyed = true;
ctrl.removeTab(tab);
};

2-I calling destroyTab() rather than removeTab() in $on('$destroy') in tab directive:
scope.$on('$destroy', function() {
tabsetCtrl.destroyTab(scope);
});

here is the plunker of the solution:
http://plnkr.co/edit/weXJbOWP5okQuqd3EVRS?p=preview
see the ui-bootstrap-tpls-0.12.1-updated.js file in the plunker

please see if this solution is proper for the directive or not.

**Comment by chrisirhc** [comment]
Thanks for the reproduction. You're right #2155 isn't fixed.

**Comment by wesleycho** [comment]
Not seeing this anymore [here](http://plnkr.co/edit/MOv0O4flWtEeFa75Du9e?p=preview), I'm assuming this has now been fixed.
