### ISSUE TITLE
Another AngularUI set of components is promoted on G+

### ISSUE THREAD

**Issue by m1rc0** [angular-ui/bootstrap#3367]
Hi everybody,

I'm not sure where to put it, but on G+ some other guy promotes "his project" as AngularUI(see: http://angularui.net/ and https://plus.google.com/u/0/communities/113269892759760815339). When asked about any affiliation to your project the response was:

"No I'am not. The group you refered have generally develope simple or experimental component. But I have tried to develop a compcat solution.﻿"

Maybe some of you like to contact the developer...

**Comment by rvanbaalen** [comment]
Thanks for notifying. We'll take a look at it.
