### ISSUE TITLE
Open another modal from currently opened modal

### ISSUE THREAD

**Issue by dilip-borad** [angular-ui/bootstrap#3369]
Hello,

I can't open second modal when i'm click on button that is inside first already opened modal.

Anyone help me ?
Also i don't know it is possible through this modal plugin, so just suggest me.
Thanks in advance.

**Comment by rvanbaalen** [comment]
Please read the docs and don't post support request as issues.

https://github.com/angular-ui/bootstrap#support

Hope this helps.

**Comment by dilip-borad** [comment]
Ok,
Thanks @rvanbaalen .
