### ISSUE TITLE
Conditionally prevent dismissing modal dialog

### ISSUE THREAD

**Issue by zdila** [angular-ui/bootstrap#3371]
I am missing a feature to implement a custom checking if (edit: modal) dialog can be dismissed and if not then execute custom action. For example to ask user if to really dismiss a dialog containing edited form. This should be handled in dialog's contoller.

Now it is possible to do it only on custom dismiss buttons but not on pressing ESC button or clicking on backdrop.

**Comment by karianna** [comment]
I'm not sure what you mean by a dialog, you mean a modal?

**Comment by zdila** [comment]
Sorry for confusion. Yes, I mean modal.

**Comment by zdila** [comment]
Do you need any other info?

**Comment by rvanbaalen** [comment]
So you basically want to be able to add a custom event for when a user tries to dismiss the modal (with either a (custom) dismiss button, esc key or backdrop click)?

**Comment by zdila** [comment]
@rvanbaalen almost, but also a mean to cancel the action (if some user defined conditions are met).

**Comment by chrisirhc** [comment]
Isn't this the use case of the resulting promise from the $modal? With the promise, you can decide what to do based on whether the promise was rejected or accepted.

**Comment by zdila** [comment]
@chrisirhc, that time the modal has been already closed

**Comment by pkozlowski-opensource** [comment]
Sounds like this is supported in 0.13: a5a82d9be7dc0bd1cfd510bacf9aa411c6efe1bc

**Comment by zdila** [comment]
Works, thanks!
