### ISSUE TITLE
tooltip-trigger is not working with expression

### ISSUE THREAD

**Issue by brunolellis** [angular-ui/bootstrap#3372]
Hi,

I am trying to use tooltip-trigger in an input with an expression to show/hide tooltip, but it is not working as I expect. It looks like expression is not being evaluated.

I've created a plunker to simulate the problem based on ui.tooltip samples: http://plnkr.co/edit/yB7GIKoKnnOWPsKDWrXw

Please, take a look at "Is formexp valid?" section.
Click "Simulate submit" and hover over inputs:
- "tooltip-trigger expression" doesn't show the tooltip message but is contains 'has-error' class;
- "tooltip-enable" works.

Should I use tooltip-enable? It works, but it is not documented, so I am not sure.

Thanks in advance.

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support

**Comment by rvanbaalen** [comment]
First of all -- If `tooltip-enable` works for you, use that.

Take a look at https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L290
You can see that there is no two way binding setup between the directive and the `tooltip-trigger` value. You are programatically changing it's value after the tooltip initialised, which is not supported.

I'm closing this issue now.

**Comment by brunolellis** [comment]
@karianna after some more investigation, I realized that it works until version ui-bootstrap-tpls-0.11.0.js (including this one). Versions 0.12.0 and 0.12.1 are not working.

It may help further investigations.

**Comment by rvanbaalen** [comment]
Good find.  I see that back then, the attributes where all being watched using `attrs.$observe`.
It seems that this was removed in favour of performance.

**Comment by rvanbaalen** [comment]
To be more specific, @chrisirhc removed the observers in this commit:

https://github.com/angular-ui/bootstrap/commit/a65bea95338802b026fd213805b095b5a0b5b393

**Comment by brunolellis** [comment]
@rvanbaalen ok, thanks!
I will use tooltip-enable :)

Are there any guidelines to improve docs?

**Comment by rvanbaalen** [comment]
Just follow the general contribution guidelines.

**Comment by cm325** [comment]
It appears that when the value changes from true to false in tooltip-enable, currently shown tooltip isn't hidden. Is this an oversight?

**Comment by karianna** [comment]
@cm325 Please open a new issue with a plunkr
