### ISSUE TITLE
Date picker inline-form media queries overriding themselves

### ISSUE THREAD

**Issue by stevenmwade** [angular-ui/bootstrap#3374]
For some reason, there seems to be more than one media query overriding another

    @media (min-width: 768px)
    .form-inline .input-group > .form-control {
         width: 100%;
    }

    @media (min-width: 768px)
    .form-inline .input-group .input-group-addon, .form-inline .input-group .input-group-btn, .form-inline .input-group .form-control {
          width: auto;
    }

I don't know if this only the case because of Bootstrap itself, but there is almost no way to get the specificity up enough to override this. The top one is overriding the bottom making the date picker have an extremely narrow width.

**Comment by wesleycho** [comment]
This sounds like a Bootstrap issue, and not with this library - we do not bundle CSS.
