### ISSUE TITLE
ngAnimate breaks fade-in animation of popover

### ISSUE THREAD

**Issue by zdila** [angular-ui/bootstrap#3375]
After including ngAnimate module to my application it breaks fade-in animation of popover.

Demo: http://plnkr.co/edit/3ECNoqBqfUcbwTq3MnVa

**Comment by karianna** [comment]
versions of angular ui / bootstrap?

**Comment by zdila** [comment]
From linked plunk:
angularjs/1.3.9/angular.js
angularjs/1.3.9/angular-animate.js
ui-bootstrap-tpls-0.12.1.js
bootstrap/3.3.2/css/bootstrap.min.css

**Comment by wesleycho** [comment]
To clarify, it looks like it is breaking when the popover is entering - is this accurate?

**Comment by zdila** [comment]
@wesleycho, exactly.

**Comment by wesleycho** [comment]
Can you try based on current master?  The popover now supports ngAnimate

**Comment by wesleycho** [comment]
Closing, as the popover was refactored to support ngAnimate.

Let us know if this is still an issue.

**Comment by zdila** [comment]
Unfortunately it is still broken. Using `ui-bootstrap-tpls-0.13.0-SNAPSHOT.min.js` from today's clone. You can check it out at http://plnkr.co/edit/94yNAYcGjWcndpIH9AbL (`ui-bootstrap-tpls-0.13.0-SNAPSHOT.js` is there loaded from google drive).

**Comment by wesleycho** [comment]
Posting more useful [Plunker](http://plnkr.co/edit/4IFABsZFdDy4zDSdwnW7?p=preview) for reference

**Comment by chrisirhc** [comment]
Reopening as this isn't fixed on master at the moment. Ref: #3506
