### ISSUE TITLE
feat(tabs): add ngAnimate 

### ISSUE THREAD

**Issue by etarce** [angular-ui/bootstrap#338]
I love UI Bootstrap, thanks for all your hard work. I'd like to know if there are any plans to incorporate the new AngularJS animations into some of the directives? For example, I'd like to be able to use ngInclude animations on the tabs directive.

**Comment by wesleycho** [comment]
As far as I can tell, it looks like this can be used today already by hooking into `ng-class`, as can be seen in this crude demo [here](http://plnkr.co/edit/pLbJ4HfiIx7LivwIUzgQ?p=preview).

Closing as resolved.
