### ISSUE TITLE
Datepicker append-to="{selector}" attribute option

### ISSUE THREAD

**Issue by dabedur** [angular-ui/bootstrap#3380]
I was pretty excited to see the `append-to-body="true"` option for positioning the datepicker widget, but got to thinking that it would be even cooler if you could specify which element you would want to append the datepicker to. So that would be `append-to="{selector})"` or a similar syntax.

Is this something that is generally desired by the community? Or am I the only one that would find this useful?

**Comment by aeharding** [comment]
I think the reason you append to the body is so that it will not be affected by containing elements.

What's a use case that you would want this for specifically?

**Comment by dabedur** [comment]
I take my request back. Was able to accomplish what I was going for by having an inline datepicker that I manually show/hide from a separate button. Thanks for the response!
