### ISSUE TITLE
Dynamic datepicker instannces

### ISSUE THREAD

**Issue by Duovili** [angular-ui/bootstrap#3381]
I have a datepicker sitting inside a ng-repeat. So the suer could ad as many rows as they like. All the examples I have seen form multiple datepickers only show if you have two and the solutions dont work when applying them to a dynamic situation.

Please any guidance on this will be much appreciated.

**Comment by RobJacobs** [comment]
This forum is reserved for reporting issues, please use stackoverflow for implementation questions.  See the Support section [here](https://github.com/angular-ui/bootstrap/blob/master/README.md)
