### ISSUE TITLE
Tooltip could use some width options

### ISSUE THREAD

**Issue by DumboJet** [angular-ui/bootstrap#3383]
When using your tooltip with large pieces of text its width remains too small making a column of text.
It would be nice (I think) if you could provide options like a "width" that could affect each tooltip independently.

Related links:
http://stackoverflow.com/questions/14596743/how-do-you-change-the-width-and-height-of-twitter-bootstraps-tooltips

**Comment by rvanbaalen** [comment]
As suggested a lot of times at that StackOverflow post, you can just customize your CSS to ajust the width. I think customizing the style is not part of the intended functionality. The idea is to use native bootstrap styling in combination with the AngularUI directives. If you want to customize, there are plenty of options to do so wothout needing another directive config setting.
