### ISSUE TITLE
Accordion should not transclude content into div.panel-body

### ISSUE THREAD

**Issue by andreialecu** [angular-ui/bootstrap#3387]
There are various use cases when using the accordion where one may not want all contents transcluded into a div with class panel-body.

For example, I want to use a panel footer and a list group as per: http://getbootstrap.com/components/#panels

This is currently not possible, because all content is trapped into a `div.panel-body` as defined in the `accordion-group.html` template.

I'm ready to submit a PR for this, but I'm not sure how to keep it backwards compatible. Perhaps an attribute like `<accordion-group auto-panel-body="false" ...`

**Comment by Foxandxss** [comment]
Yo!

I am gonna check it in a future, we need to bring this back to life and this is not an important issue right now. You can always override the template for that use case. Will leave this open tho :)

**Comment by XmlmXmlmX** [comment]
In case of tables inside panels it is also a problem.
http://getbootstrap.com/components/#panels-tables

**Comment by rvanbaalen** [comment]
I would say creating your own accordion template for that use case is the way to go..

**Comment by wesleycho** [comment]
Creating a custom template may be a bit awkward, but at the least, there is now the ability to use a custom template on a component by component basis for the accordion due to #4084, which should ease the problem a bit.

This may require a bit of investigation.

**Comment by Foxandxss** [comment]
This could be done with a custom template since it is something to be done in userland.

**Comment by ravigithub** [comment]
i think it'll make an custom accordion as it was showed in the bootstrap in it.
