### ISSUE TITLE
Bootstrap Accordion does not render markup correctly when loaded dynamically.

### ISSUE THREAD

**Issue by rkrishnadudyala** [angular-ui/bootstrap#3392]
When Accordion content is loaded from the json with html, it fails to render.

In this link http://plnkr.co/edit/JXIG2bmajA4JdsJHUtpA, one of the accordion content value is 
```javascript
<h2>Try me!</h2><p>textAngular is a super cool WYSIWYG Text Editor directive for AngularJS</p><p><b>Features:</b></p><ol><li>Automatic Seamless Two-Way-Binding</li><li style="color: blue;">Super Easy <b>Theming</b> Options</li><li>Simple Editor Instance Creation</li><li>Safely Parses Html for Custom Toolbar Icons</li><li>Doesn&apos;t Use an iFrame</li><li>Works with Firefox, Chrome, and IE8+</li></ol><p><b>Code at GitHub:</b> <a href="https://github.com/fraywing/textAngular">Here</a> </p> 
```

When we load the Accordion content dynamically, it is not rendering the markup. But when you add the markup content manually, it does render. 

Is this a bug? how can we fix this. 

Much appreciated you help. Thanks in advance.

**Comment by Foxandxss** [comment]
It is not a bug. Angular won't render html from a string if you don't pass it via `$sce` first.

Check this: http://plnkr.co/edit/vppQ2Kx5Drhkgr6AvJPI?p=preview

**Comment by rkrishnadudyala** [comment]
Thanks Foxandxss for your quick reply.
