### ISSUE TITLE
Demo site custom builds / download link don't work with Angular 1.3

### ISSUE THREAD

**Issue by chrisirhc** [angular-ui/bootstrap#3394]
1. Run `grunt` on a checkout of master.
2. Run a http server on the directory. Access `http://localhost:<port>/dist/ `. 
3. Click on Download / Custom Build.

Nothing happens and console says the function is undefined.

Haven't looked into this much but creating the issue in case someone else can look into it.

**Comment by Foxandxss** [comment]
Yeah, demo app is having some issues :P

PD: I invited you to the team slack.
