### ISSUE TITLE
Carousel - Add "wrap"-option

### ISSUE THREAD

**Issue by lippoliv** [angular-ui/bootstrap#3397]
Hey there,
on bootstrap you can stop an carousel from endless cycling by set "wrap" to "false".

Looking into the sources here https://github.com/angular-ui/bootstrap/blob/master/src/carousel/carousel.js#L82 I think this is currently not possible for angular js bootstrap ui, isn't it?

Would be nice to have such an Option.

**Comment by wesleycho** [comment]
To clarify, you mean that it will stop on the last slide instead of going back to the first?

**Comment by lippoliv** [comment]
Yes, sorry for beeing unclear ... :)

**Comment by Digambar14** [comment]
When this feature will be available?
