### ISSUE TITLE
Accordion - toggleOpen event on entire heading

### ISSUE THREAD

**Issue by Aaron-Hartwig** [angular-ui/bootstrap#3399]
Feature request: Clicking the `accordion-heading` fires the `toggleOpen` function, not just what is wrapped by the heading. This would be really nice because currently only the text and/or glyphicon fire the event.

**Comment by RobJacobs** [comment]
This seems to be a trivial change, in the accordion-group template, move the ng-click from the a element to the panel-heading div.  The toggleOpen() in the accordion group directive is handling the disabled state.

**Comment by chrisirhc** [comment]
Moving to Purgatory as this deviates from expected behavior from twbs.

**Comment by chrisirhc** [comment]
Actually, as @RobJacobs mentioned, this is a trivial change on the template, so I'm closing this. The wiki shows you how to customize the templates: https://github.com/angular-ui/bootstrap/wiki/Development#customize-templates

**Comment by savokiss** [comment]
move 'ng-click="toggleOpen()"' works, but copy it may cause some errors.
