### ISSUE TITLE
Angular tooltip from element

### ISSUE THREAD

**Issue by beradrian** [angular-ui/bootstrap#3402]
It will be very helpful to get the tooltip content from a DOM element, instead of passing it as an attribute value.
It can work like 

    <div id="id0" data-tooltip-id="tooltip1">Show the tooltip</div>
    <p id="tooltip1">Just a <em>nice</em> tooltip</p>

or

    <div id="id0">Show the tooltip</div>
    <p id="tooltip1" data-tooltip-for="id0">Just a <em>nice</em> tooltip</p>

**Comment by antoinepairet** [comment]
@beradrian if I understand you use case correctly, you should use a popover.
In the future, templates will be supported, see https://github.com/angular-ui/bootstrap/pull/1848

rgds
