### ISSUE TITLE
Modal - Add bindToController

### ISSUE THREAD

**Issue by eranimo** [angular-ui/bootstrap#3404]
It would be nice to have a bindToController option for the $modal service. This would allow resolves to be bound to the controller instead of the scope much like it does in directives in Angular 1.3.

See the Angular documentation for bindToController:
> When an isolate scope is used for a component (see above), and controllerAs is used, bindToController: true will allow a component to have its properties bound to the controller, rather than to scope. When the controller is instantiated, the initial values of the isolate scope bindings are already available.

https://docs.angularjs.org/api/ng/service/$compile

**Comment by Foxandxss** [comment]
First we need to see if we want to break compatibility with 1.2.x

**Comment by wesleycho** [comment]
I think we've already broken compatibility with 1.2.x with the ngAnimate changes.

**Comment by iyel** [comment]
+1

**Comment by awerlang** [comment]
```
scope - a scope instance to be used for the modal's content 
(actually the $modal service is going to create a child scope of a provided scope). 
Defaults to $rootScope
```

I receive them on controller constructor function. As I use TypeScript, I'm able to prefix them with either `public` or `private` in order to have automatic properties.

Isn't your use case covered by means of constructor function parameters? Or perhaps I'm missing something?

**Comment by ouchxp** [comment]
+1 for this. 
The inconsistency of controller sytay is really important. 
In the mean time. This issue really bothers our new angularjs developers. We have to add exceptions to the coding guideline that explain to our developers that when and why they are allow to break this consistency. That's really painful experience.

**Comment by Quirksmode** [comment]
+1

**Comment by kamarouski** [comment]
+1 

As we have Angular 2.0 coming it's generally recommended not to use $scope anymore and prefer bindToController for directives. 

The absence of bindToController is frustrating and painful.

**Comment by wesleycho** [comment]
I'll take a look at implementing this tomorrow.
