### ISSUE TITLE
Modal Resolution Not Using Locals

### ISSUE THREAD

**Issue by iamchairs** [angular-ui/bootstrap#3405]
If a modal resolution contains another resolution from the same resolve block it will fail. This is not working as expected (like ui-router).

Steps to reproduce:

* Create a Controller called MainCtrl that injects the $modal service with a scope method called openModal()
* Create a view MainCtrl is controller. Create a button that, when clicked, calls openModal()
* In the openModal() method use the $modal service to call $modal.open()
* In the $modal.open call add two resolutions. The second resolution should attempt to use the first resolution.

```
angular.module('app', ['ui.bootstrap'])
  .controller('MainCtrl', function($scope, $modal) {
  
    $scope.openModal = function() {
      $modal.open({
        template: 'hello'
      });
    };
  
    $scope.openModal2 = function() {
      $modal.open({
        template: 'hello',
        resolve: {
          r1: function() {
            return 'hello';
          },
          // Will fail
          r2: function(r1) {
            return r1 + ' world!';
          }
        }
      });
    };
  
  });
```

JSBin: http://jsbin.com/riyijuqolu/1/edit?js,console,output

Please address.

**Comment by BobbieBarker** [comment]
I did a look over on how our resolve block is handled in modals and compared it to how ui-router handles their resolve block. Our resolve in comparison is a very simple implementation where all the promises are pushed into an array and $q.all is used. Which is where I think the break down that this issue high lights begins. For comparison if you look at resolve.js from ui-router
https://github.com/angular-ui/ui-router/blob/master/src/resolve.js
You'll see a dramatically more complex implementation. On thate note, I don't think there is a bug here, I just don't think our modal was written to handle this use case.

**Comment by RobJacobs** [comment]
What exactly is this use case, opening a modal from a modal?

**Comment by rvanbaalen** [comment]
In my opinion there is something wrong with your application/UI design if you're opening modals in modals. As @RobJacobs said; can you provide a solid use case for it?

**Comment by iamchairs** [comment]
@RobJacobs @rvanbaalen 

I'm not opening a modal from a modal...

**Comment by rvanbaalen** [comment]
@iamchairs my bad. I was only looking at @RobJacobs' response and didn't read your issue properly.

**Comment by iamchairs** [comment]
@BobbieBarker Do you think this should be updated? Is the expected behavior to work like ui-router resolve?

**Comment by BobbieBarker** [comment]
Looking at the code I don't think the expected behavior is to have an implementation like ui-routers, but also looking at ui-router's implementation I can see where an enhancement could certainly be made.

**Comment by wesleycho** [comment]
The UI Router implementation is quite complex compared to ours. We could copy/paste that code, but that would be duplicate code - it may end up being the best solution though. UI Router is undergoing a large refactor right now in TypeScript for the 1.0 release and potential abstraction to decouple it from Angular itself (so it can be used in Angular 2, or in any other application).

**Comment by wesleycho** [comment]
An update on this - in order to support this, I am willing to have an interface that is pluggable as config for the modal to use and conforms to UI Router's `$resolve` implementation.

By default, it should use its current implementation when a provided implementation is not present.
