### ISSUE TITLE
transitionEndEvent doesn't fire.

### ISSUE THREAD

**Issue by yao164284351** [angular-ui/bootstrap#3407]
#angular version  : 1.3.15
#angular-ui-bootstrap version : 0.12.1
##when the transition would be end  ,it's never work ,so that the transitionEndHandler  can't call neigher,and the currentTransition can't be null;

**Comment by karianna** [comment]
plunkr please

**Comment by chrisirhc** [comment]
`$transition` is being deprecated. This issue probably isn't valid now since the carousel ngAnimate PRs have been merged.
