### ISSUE TITLE
can't use jquery file upload inside modal window

### ISSUE THREAD

**Issue by vishnu4** [angular-ui/bootstrap#3414]
Here is a plunker example of something that i'm trying to do: http://plnkr.co/edit/dlktEzrBeFshGaZsTmg7?p=preview . Basically i just want to use jquery file upload inside the modal window. as you can see in the plunker though, none of the callbacks are being called.  Even the 'add' callback isn't being called when i add a file. This all works fine if i use angular strap, but i'd rather use angular-ui for several other reasons. I've investigated the modal initialization, and tried to override the windowTemplateURL, starting with the default i found here: https://github.com/angular-ui/bootstrap/blob/master/template/modal/window.html,and it looks like the problem is the 'modal-transclude' attribute. What is this attribute doing that breaks the file upload control, and how do i get past it?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support

**Comment by vishnu4** [comment]
I actually did leave a comment in stackoverflow a week ago: https://stackoverflow.com/questions/29021112/cant-get-file-upload-to-work-in-angular-ui-modal-window , no response.  Not really sure what the next step is.

**Comment by NaturalBornCamper** [comment]
Why was this closed when it's not fixed at all? 0_o
