### ISSUE TITLE
Add full date format support

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#3418]
Currently dateParser only supports a limited number of date formats that [dateFilter](https://docs.angularjs.org/api/ng/filter/date) supports. We should aim to support a larger range of these options, at least supporting all options with the `a` format for AM/PM, which includes `medium`, `short`, `mediumTime`, and `shortTime`.

**Comment by AngularJsChamp** [comment]
You can also create custom date picker using bootstrap date picker code.
