### ISSUE TITLE
typeahead ignore accents

### ISSUE THREAD

**Issue by dariospadoni** [angular-ui/bootstrap#3422]
Hello

Is there a way to ignore the accents on the typeahead in such a way that results such as "Pàte", "Páte" are returned if one types "Pate" ?

**Comment by chrisirhc** [comment]
Interesting. This is a good call for making typeahead more extensible. Users want to be able to customize the query matching logic.

**Comment by dmitriz** [comment]
This sounds like a case for custom filter. 

Just create your own filter doing the matching and add it to the comprehension expression (see examples in http://angular-ui.github.io/bootstrap/#/typeahead).

Would that not do it?

**Comment by pkozlowski-opensource** [comment]
Totally agree with @dmitriz that it can be handled, even today, very elegantly. A user has full control over a collection that goes into the typeahead results and cold write a custom filter or even simply call a function.

**Comment by wesleycho** [comment]
Closing as it appears there is already a great solution for this that can be implemented on the developers' side to support this.
