### ISSUE TITLE
rating directive: ugly border in Chrome

### ISSUE THREAD

**Issue by jgehrcke** [angular-ui/bootstrap#3428]
Have tested this with the directives shown on the website:
https://angular-ui.github.io/bootstrap/

Clicking icons in the rating directive works as expected with Firefox 37. Using Chrome 41, however, an ugly border appears upon click:

![ng-bootstrapui-rating-border-chrome](https://cloud.githubusercontent.com/assets/265630/6800676/044bfac2-d221-11e4-9e2a-98bd56bc3c75.png)

The weird corner in at the top right appears only upon mouse-over (after selecting a value via click).

I have reproduced this locally with a simple `<rating ng-model="foo.rating" max="5"></rating>` where the border with the "weird" corner appears permanently, after click.

**Comment by Foxandxss** [comment]
I can see it, but I am not sure we can change that.

**Comment by jgehrcke** [comment]
Is it as simple as this: "Either this is a Chrome bug or an issue in UI Bootstrap"?

**Comment by Foxandxss** [comment]
To be honest, I don't know, I am not sure if devs can change the border on selection.

**Comment by jgehrcke** [comment]
First of all, this is the outline we see, which makes the element stand out upon focus. It can easily be removed with `outline: none;`, but we do not want to do this by default (http://outlinenone.com/).

There is an "easy" fix for normalizing the focus border among Firefox and Chrome (FF shows the thin dotted border when tabbing through the elements):

```css
:focus {
  outline: thin dotted !important;
}
```

I am not sure why bootstrap does not perform this normalization by default. I think it should, shouldn't it?

What can we do now? From the top of my head there are at least three options:

* add some CSS to UI Bootstrap for performing this normalization
* report this as an issue to Bootstrap
* do nothing

What other options do we have? What is most viable?

**Comment by Foxandxss** [comment]
That sounds better to me, I am not really a CSS person :P.

I don't think we are going to add extra CSS. Maybe we could consider it if there is a real need, but that CSS can be included in the applications themselves (that is my opinion).

About reporting to bootstrap, that is always an option.

**Comment by jgehrcke** [comment]
I have just read http://tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/ which makes a strong point about leaving the default focus outline as is. This probably is why Twitter Bootstrap did not touch it. So, I guess this leaves this to be 

* either a Chrome bug *or* a
* UI Bootstrap bug

I think the latter still is an option. We need to figure out under which circumstances this weird corner effect appears and if these circumstances are triggered by UI Bootstrap alone.

**Comment by Foxandxss** [comment]
Maybe it is, we will check it out

**Comment by RobJacobs** [comment]
The only thing I can see changing in the template is to remove the tabindex="0" from the span tag which would exclude the element from receiving a focus.

**Comment by jgehrcke** [comment]
This fiddle shows a small repro with bootstrap glyphicons and an enumeration within a span only:
https://jsfiddle.net/hakchuot/1/

Indeed, tabindex is "responsible" for making the span reachable. Likewise, removal of  `tabindex="0"` makes the outline disappear. The fiddle shows that 

* the outline border geometry depends on the order of spans
* IE 11 shows the same outline geometry as Chrome

Play with the tab key in the fiddle using different browsers and see for yourself. In fact, Drupal just recently closed a related issue: https://www.drupal.org/node/2086641

We can conclude that the ugly geometry of the outline in IE and Chrome stems from the fact that a number of items is placed within a span. I guess this we do not want to change. I also guess that reporting this weird geometry to both, MS and Google will not really help.

So, the question is what we can do about the `tabindex` setting. Can the rating be set with the keyboard only? Or can it only be set with the mouse? In the latter case: can we then consider removing `tabindex`? I do not have enough knowledge about how people with visual impairment may need this. Do we have an expert for this? :)

**Comment by RobJacobs** [comment]
I think the tab index is there to support ARIA, the span has a role of [slider](http://www.w3.org/TR/wai-aria/roles#slider) with the appropriate ARIA attributes.

**Comment by rvanbaalen** [comment]
In my opinion this is not an issue but just native behavior. UI Bootstrap does not add custom CSS rules since the only CSS we depend on comes straight from Twitter Bootstrap.

So @jgehrcke regarding this:

> * either a Chrome bug or a
> * UI Bootstrap bug

It's none. It's expected browser behavior (browser adds outline on focussed elements).

If you don't want this to happen, you can just use the snippet you mentioned earlier in your own CSS to customize things. Getting rid of the `tabindex` will break ARIA support which is less wanted than a focus outline style.

**Comment by jgehrcke** [comment]
@rvanbaalen: the existence of the outline is expected, clearly. That is not questioned in this issue (does it appear like that?).

It is the distorted geometry which is not expected.

**Comment by rvanbaalen** [comment]
Aah allright I misunderstood you on that point. I'm affraid we must close this issue though. This is clearly a browser and/or styling issue which we both aren't able or willing to influence.

**Comment by ismtah** [comment]
in angular project you can put css globally in styles.css file : 

rating{
           span{
               outline: none;
           }
 }
hope this help solve your issues

**Comment by walheredia** [comment]
> in angular project you can put css globally in styles.css file :
> 
> rating{
> span{
> outline: none;
> }
> }
> hope this help solve your issues

that worked for me
