### ISSUE TITLE
Update Readme to reflect file inclusion

### ISSUE THREAD

**Issue by tommymcdonald** [angular-ui/bootstrap#3430]
I feel like there should be some indication in the README that you must include both the tpls file and the main file for this to work, I had to find the solution via stackoverflow. Otherwise, you get an error similar to `404 Not Found - localhost/angular/template/message.html`

**Comment by RobJacobs** [comment]
In the README under the installation section it states:

All the files and their purposes are described here: https://github.com/angular-ui/bootstrap/tree/gh-pages#build-files Don't worry, if you are not sure which file to take, opt for  ui-bootstrap-tpls-[version].min.js .

The link has a pretty good explanation on what the differences are.  You do not want to include both files.

**Comment by tommymcdonald** [comment]
@RobJacobs My apologies, you are absolutely correct. Thanks for pointing it out!
