### ISSUE TITLE
When an input name is specified, the "date-disabled" validation is not applied to the named input control

### ISSUE THREAD

**Issue by Asvarduil** [angular-ui/bootstrap#3438]
Reproduction Plunker can be found [here](http://plnkr.co/edit/XdUTSlx9koKFHctohdlg?p=preview)

**Steps to Reproduce:**

 # Open the reproduction plunker linked above.
 # Observe that there are two 'text-danger' labels set to appear if an error object exists for the `testText` field on the `testForm` form.
 # In the plunker, manually enter a value less than the min-date, or greater than the max-date (test values used: 01/01/1900, 01/01/2100)
 # Observe that the validation label for the field with message, "Date is outside of the valid range" does not appear.
 # Observe that the validation label for the form with message, "Should not see this error." does appear.
 # Observe in the paragraph "Form Error Dicitionary Blob", that a `date-disabled` validation error exists, but the `$name` property of the single error object consists of an empty string.

**Observed Results:**

 # The form-level validation message in the reproduction plunker is shown
 # The control-level validation message is not visible
 # The Form Error dictionary blob has a single instance of the `date-disabled` error, with an empty string as the name of the throwing control.

**Expected Results:**

 # In the reproduction plunker, the form-level validation message should be hidden.
 # The control-level validation message should be visible.
 # If a `name` attribute exists for the input on which the datepicker is set, then if a model value is outside of the given date range, the corresponding `date-disabled` validation error should have `$name` being the name of that control.

**Comment by wesleycho** [comment]
Noting that this is still an issue [here](http://plnkr.co/edit/341iRoiMwjJw2qxQZpZ5?p=preview).

It looks like we don't have a mechanism to bubble up the validation error from the model in the datepicker directive to the popup's input.

This is a completely missing feature.

**Comment by wesleycho** [comment]
I did some research on this in the past couple of weeks - I believe we cannot do anything about this, as the input's validation is for the user to control.

Going to close this as won't support.

On a side note, love your gravatar, although X is better IMO :P .
