### ISSUE TITLE
Documentation - The datepicker documentation does not inform programmers about the date-disabled validation error produced if a manually-entered date is outside of the min/max-date range.

### ISSUE THREAD

**Issue by Asvarduil** [angular-ui/bootstrap#3440]
Functional reproduction Plunker can be found [here](http://plnkr.co/edit/XdUTSlx9koKFHctohdlg?p=preview)  

Additionally, refer to your public-facing [documentation](https://angular-ui.github.io/bootstrap/), in the Datepicker section.

The `min-date` and `max-date` property entries do not note that if a given date is outside of their date range, that the `date-disabled` validation error will be added to the form (refer to Bug #3438 and Bug #3439 for additional problems posed due to the current implementation.)  This is critical information for a UI programmer to have in order to raise hint messages to the user to help them enter valid information.

**Steps to Reproduce:**
 # Open the Angular UI Documentation link given above
 # Navigate to the Datepicker section
 # Find the entries for the `min-date` and `max-date` attributes
 # Observe that the information does not denote that `date-disabled` is raised on the form if the calendar's date lies outside of this range.

**Observed Behavior:**
 # Documentation does not denote the consequences of a user entering a date outside the min-/max-date range.

**Expected Behavior:**
 # Documentation should denote the consequences of a user entering a date outside the min-/max- date range.

**Comment by wesleycho** [comment]
Feel free to file a pull request fixing this.

**Comment by Asvarduil** [comment]
Will do gladly, when the time comes.  There are two other issues that came to my attention on the project that I am working on (the two tickets linked in the OP) that might affect the final shape of what gets pushed.  For the time being I was wanting to wait on those other issues, before making any hasty pull requests.

**Comment by wesleycho** [comment]
Understood, I will try to triage your other ticket in the next few days and see what would be the best courage of action on UI Bootstrap is (hopefully tonight, but I am tired today).

**Comment by karianna** [comment]
@wesleycho Can this be pushed back to 0.13.x?

**Comment by aarosil** [comment]
I am using v. `0.13.0` and still facing this.  I believe it's amply documented what the problem is in the 2 issues above.  Is there anything I can help with?  @Asvarduil are there any work arounds you can share?

**Comment by wesleycho** [comment]
As the label mentions, PRs are welcome.

**Comment by aarosil** [comment]
I'm willing to take a crack at it.  Do you know why ngModelController is set to null here?  I think this maybe why the $validation error doesn't appear under the control's "name" property 

angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L23

**Comment by Asvarduil** [comment]
@aarosil There is no built-in workaround to this issue; what I wound up doing instead for my team was writing a separate date range validation directive.
