### ISSUE TITLE
Visual Studio - bower install angular-bootstrap can't use a correct dependency of angularjs

### ISSUE THREAD

**Issue by NicoJuicy** [angular-ui/bootstrap#3449]
bower install angular-bootstrap

Tried with both angular 1.2.16 and angular 1.2.28

Command + results
PM> bower install angular-bootstrap
bower angular-bootstrap#*       cached git://github.com/angular-ui/bootstrap-bower.git#0.12.1
bower angular-bootstrap#*     validate 0.12.1 against git://github.com/angular-ui/bootstrap-bower.git#*
bower angular#>=1 <1.3.0        cached git://github.com/angular/bower-angular.git#1.2.28
bower angular#>=1 <1.3.0      validate 1.2.28 against git://github.com/angular/bower-angular.git#>=1 <1.3.0
bower : bower                        ECONFLICT Unable to find suitable version for angular

These are my dependencies:

"dependencies": {
		"angular": "1.2.28",
		"bootstrap": "3.3.4",
		"angular-boostrap-ui": "0.12.1",
		"jquery": "1.10.2",
		"jquery-validation": "1.11.1",
		"jquery-validation-unobtrusive": "3.2.2",
		"hammer.js": "2.0.4",
		"bootstrap-touch-carousel": "0.8.0"
	},

Did i do something wrong? I executed this on Visual Studio 2015 ( Asp.Net 5 -- vNext) and it's the only package where i have trouble with...

When i run bower install angular-bootstrap in "cmd.exe", everything works fine.. I think the issue is related to Asp.Net 5 or Visual Studio (integrated tools). Both use node v 0.10.33.

If this is a no fix because of Visual Studio dependency, i have cross posted this on : https://github.com/aspnet/Home/issues/414

So please leave this open untill fix for others?

**Comment by BobbieBarker** [comment]
The fact that you said it works fine if you use your regular command line tool indicates the problem isn't with bower or the angular-bootstrap project. Will re-open if additional information is provided that suggests otherwise.

**Comment by wesleycho** [comment]
There is a label for more info - in general give the benefit of the doubt.

@NicoJuicy please provide more info, there should not have been a conflict there from the bower CLI as far as I understand.

**Comment by NicoJuicy** [comment]
I think the same (Visual Studio bower = cmd.exe bower) but i haven't found anything that suggests there a difference... But there is one

NodeJS at version 0.10.33 (both)
Bower at version 1.3.12 (both)

It goes wrong here : validate 1.2.28 against git://github.com/angular/bower-angular.git#>=1 <1.3.0, for some reason. It thinks that 1.2.28 is not valid, so it can't find another version.

When i use cmd.exe and navigate to the folder and run "bower install angular-bootstrap" --> All OK
When i use "Package Manager Console" and run "bower install angular-bootstrap" --> ERROR 

NOTE:
I used "bower uninstall angular-bootstrap" in both cmd.exe and "Package Manager Console" in the root folder of my project. Suddenly the package has been installed without problems.

So the problem seems to be fixed (suddenly)
