### ISSUE TITLE
Auto open for tooltip

### ISSUE THREAD

**Issue by cdroulers** [angular-ui/bootstrap#3452]
As seen here : https://github.com/imcnally/bootstrap/blob/master/src/tooltip/tooltip.js#L163

The tooltip can't be opened automatically right now. I really don't know where to start but I'd love to contribute. If someone can point me in the right direction to get the tooltip open, I'll be more than happy to create a pull request!

**Comment by RobJacobs** [comment]
See PR #2148

**Comment by cdroulers** [comment]
I'll check it out, thanks.
