### ISSUE TITLE
Consider dropping ngDocs

### ISSUE THREAD

**Issue by chrisirhc** [angular-ui/bootstrap#3457]
Looks like this isn't used, and it's sort of broken. Doing `grunt ngdocs` creates a documentation page that doesn't seem to work properly. Not sure whether to remove it entirely or fix it later.

**Comment by wesleycho** [comment]
We should probably remove it completely if it is broken - the demo page serves as our documentation page currently, as the library generally is pretty simple to use.

I know the Angular team created dgeni, we can probably try migrating to that as a docs solution.

**Comment by Foxandxss** [comment]
Yes, deleting it completely, then in a future consider other kind of doc.
