### ISSUE TITLE
Bad format  DatePicker in Angular 1.3.14 on init from Date JavaScript

### ISSUE THREAD

**Issue by bagnos** [angular-ui/bootstrap#3471]
when we initialize DatePicker from Date Javascript Object bind by ng-model we have this string:

Mon Mar 30 2015 15:22:54 GMT+0200 (ora legale Europa occidentale)

instead of

30/03/2015

es:

<input type="text" class="form-control"
	datepicker-popup="dd/MM/yyyy" ng-model="evento.dt" is-open="opened"
	min-date="minDate" max-date="'2015-06-22'"
	datepicker-options="dateOptions"
	date-disabled="disabled(date, mode)" ng-required="true"
	close-text="Close" /> 
         <span class="input-group-btn">
	<button type="button" class="btn btn-default"
	ng-click="open($event)">
	<i class="glyphicon glyphicon-calendar"></i>
	</button>
	</span>

**Comment by karianna** [comment]
Issue is fixed on master.
