### ISSUE TITLE
Split Datepicker component off to its own repository

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#3472]
The datepicker has been a big pain - the UI Bootstrap team has floated the idea of splitting it off to its own repository so it could get the maintenance that it deserves without bogging down the release cycle.

Thoughts?

### Possible challenges
- [ ] dependency on tooltip / position service
- [ ] dependency on dateparser service

**Comment by rvanbaalen** [comment]
Like discussed in [last meeting](https://github.com/angular-ui/bootstrap/wiki/Meeting-minutes#meeting-thursday-march-26th) I agree with splitting it out to it's own repo. That way we can channel efforts to the right components and keep a clear issue tracker for instance. 

We also mentioned porting a full featured jQuery datepicker like the one from eterniecode to Angular without the jQuery dependency. I'm just tossing that in here as well.

**Comment by BobbieBarker** [comment]
I also agree with what was said during the meeting obviously the datepicker
has become a noose around this projects neck

**Comment by tdhsmith** [comment]
Interesting. I can definitely see even as a casual observer how this would be helpful. Almost half of the issues on the front page are datepicker-related.

datepicker also seems to draw more help/support tickets than its companions, so perhaps this would be an opportunity to address that (expanded docs, easier to browse issues, single meeting area for people knowledgeable in it). And smaller repos are less intimidating for people to begin contributing to.

That said there are the obvious issues of user confusion and module proliferation, and the possibility that datepicker won't stay as active as the parent project.

**Comment by BobbieBarker** [comment]
I'm actually waiting for the pickers to be spun off into their own modules so I can tackle them.

**Comment by RobJacobs** [comment]
I agree, but would this new project take a dependency on ui-bootstrap?  I would hate to see a separate implementation to support what the tooltip and position service in ui-bootstrap are doing of the datepicker..

**Comment by rvanbaalen** [comment]
Good point @RobJacobs that is indeed one of the many issues we have to tackle before deciding what to do with it.

@wesleycho I took the liberty to add a checklist to your original post to keep track of possible issues involved with splitting off the datepicker project. Feel free to do as you please with it.

**Comment by realityking** [comment]
Dateparser shouldn't be a problem, since it's only used in the datepicker. Thus is should just follow the datepicker into it's own repository.

**Comment by Foxandxss** [comment]
For the time being, we are not doing any split.
