### ISSUE TITLE
popover-placement not respected when using popover-template

### ISSUE THREAD

**Issue by trendzetter** [angular-ui/bootstrap#3473]
When using the new popover template the placement is always default.
I am using this branch: 
https://github.com/chrisirhc/angular-ui-bootstrap/tree/feature/popover-template

**Comment by chrisirhc** [comment]
Please create a Plunker to demonstrate your issue.

**Comment by trendzetter** [comment]
My mistake. It works with popover-template-placement. I was trying with popover-placement.

**Comment by chrisirhc** [comment]
Actually, this is my mistake, heh. It shouldn't be reading from `popover-template-placement`. It should be set as `popover-placement`. I'll fix that.
