### ISSUE TITLE
Datepicker within a ngGrid, where the Grid is inside a modal

### ISSUE THREAD

**Issue by HasithaGunasinghe** [angular-ui/bootstrap#3475]
date-picker is not working when the control is inside the ngGrid, where the grid is inside of a modal. It acts as an input text controls as the calendar popup does not popup on focus.

Plunkr:
http://plnkr.co/edit/CpzmNwwlXDDD0ZP6jgLf?p=preview

**Comment by wesleycho** [comment]
This is a old version of UI Bootstrap and Angular - ng-grid also was deprecated in favor of the newer UI Grid.

If this is an issue with the recent libraries for all involved, then we would be more than happy to investigate, but this is unsupported otherwise.
