### ISSUE TITLE
typeahead with bloodhound

### ISSUE THREAD

**Issue by Repalogic** [angular-ui/bootstrap#3480]
I have a very large set of objects which I currently use as dataset for typeahead:

  item as item.name for item in items | filter:{name:$viewValue}

This filter is very slow due to the data size. It is currently not usable at all. Therefore I am thinking to use a search optimized data structure. With bloodhound, twitter has already realized such an engine. However, I have not found any possibility to use bloodhound in angular-ui's version of typehead. 

Adding support for bloodhound also makes it possible to use the search in multiple typeaheads without requiring to create search optimized data structures for each typeahead.

Is there any way to support bloodhound?

Mathias

**Comment by chrisirhc** [comment]
Are you referring to https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md ?

**Comment by Repalogic** [comment]
yes

**Comment by chrisirhc** [comment]
I'm open to this if it can be opt-in and typeahead can be *extended* to use bloodhound.

**Comment by Repalogic** [comment]
Currently, I have succeeded to use bloodhound using the internal get function:

```
var engine = new Bloodhound({
   name: 'products',
   local: items,
   datumTokenizer: ,
   queryTokenizer: 
});

engine.initialize();
```
Then you can use bloodhound directly:
```
<input type="text" ng-model="product" typeahead="product as product.name for product in engine.index.get($viewValue)>
```

However, the internal get method is synchronous which causes a small delay when typing. The non-internal get method (engine.get) is asynchronous which prohibits this delay. In Chrome, the delay is nearly not measurable, however in firefox, it is absolutely anoying (not tested IE so far).

So far I was not able to use the asynchronous method as this would require to have a callback for the suggestions.

**Comment by dmitriz** [comment]
@Repalogic Can you provide a plunkr showing the delay?

**Comment by sajanojha** [comment]
@Repalogic 
Hi,
What shall I do to add multiple bloodhound. I am stuck and still unable to figure it out.
Please let me know if you have a demo plunkr for this.

My Bloodhound is there below but I am stuck using them in my view

var NameBH = new Bloodhound(
  {
    name: "Entity",
    datumTokenizer: function (d) {
      return Bloodhound.tokenizers.whitespace(d.name);
    },
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: 'http://localhost:5000/ep/'+'freesearch?typequery=1&query=%QUERY',
      filter: function (data) {
        return $.map(data.results, function (result) {
          return {
            name: result[2],
            id:result[0],
            class:result[1],
            source: "Entity Name"
          };
        });
      },
      ajax: {
        beforeSend: function (jqXhr, settings) {
          settings.urlName += "&east=" + map.getBounds().getEast() + "&west=" + map.getBounds().getWest() + "&north=" + map.getBounds().getNorth() + "&south=" + map.getBounds().getSouth();
          $("#searchicon").removeClass("fa-search").addClass("fa-refresh fa-spin");
        },
        complete: function (jqXHR, status) {
          $('#searchicon').removeClass("fa-refresh fa-spin").addClass("fa-search");
        }
      }
    },
    limit:270
  });
NameBH.initialize();
AddressBH.initialize();

**Comment by wesleycho** [comment]
Going to note that it does not seem Bloodhound is not being maintained.

Closing this feature request as a result.
