### ISSUE TITLE
Add a Show/Hide Method to Bootstrap Modal

### ISSUE THREAD

**Issue by aug-riedinger** [angular-ui/bootstrap#3483]
In my situation, the modal contains some pretty heavy to load information. Instead of appending it to the DOM on open, I'd rather append it on load, and call a `show`/`hide` method on it. Instead, I'll have to do that manually, which is going to be dirty ...

**Comment by RobJacobs** [comment]
@aug-riedinger I think the scenario you are describing is you make a service call to load information in the modal controller and don't want to show the modal till those service calls are complete?  I typically just make my service calls in the parent controller before I call the modal.open and pass the results in to the modal controller via the resolve property or use $cachefactory to hold the results.

**Comment by BobbieBarker** [comment]
If you want something to not be included into the HTML for the modal on load until the data has been resolved, then I would use ng-if and not a show/hide.

**Comment by aug-riedinger** [comment]
I'm not sure I was clear here.

I have a modal, containing a video. And in the typical user-flow, the modal will be opened and closed several times.

So instead of calling `$modal.open({template: "<video></video>"})` several times, I'd rather do something like

```
var modal = $modal.load({template: "<video></video>"});

// then when needed
modal.open()
// and also
modal.close()
```

I don't think I can achieve that at the moment without doing hacky things (either hiding the modal with another strategy like css, or moving the content to a hidden node in the DOM and moving it back after.

What do you think?

**Comment by RevanProdigalKnight** [comment]
It would certainly be a handy feature to have in some cases. It would probably be best to leave the current `modal.open()` and `modal.close()` methods for the majority of modals, though, and maybe just introduce a `modal.show()` and `modal.hide()` to the `$modalStack` factory.

**Comment by icfantv** [comment]
I'm not sure there's anything to do here.  Loading HTML templates is pretty fast and as mentioned previously, you inject your required content into the modal controller using normal resolve-like syntax.

The overhead you speak of, is primarily centered around the loading of a video, the performance of which is really beyond the control of this framework and and Angular.

I'm closing this for now.  If you would like to reopen, please create either a PR or plunker that demonstrates a clear performance benefit using a potentially new show/hide functionality as opposed to the current functionality.  Don't forget that doing a show/hide has other ramifications like memory usage and the fact that it's still physically present in the DOM.

**Comment by aug-riedinger** [comment]
Got it.
For now, I can afford living without it. If I need to go further, I'll work on it and PR.
