### ISSUE TITLE
Don't know what scripts and CSS to load

### ISSUE THREAD

**Issue by blakemcbride** [angular-ui/bootstrap#3485]
Your page at:  https://angular-ui.github.io/bootstrap

Tells you how to download and build.  Wouldn't most people use bower?  A bower example would be much more useful.

You state:  "As soon as you've got all the files downloaded and included in your page you just need to declare a dependency..." but you never tell what scripts or CSS files to include.  I am lost.

On your github README.md you show the bower command but still do not show what scripts or CSS to include/load.  Really, I am lost.

**Comment by pkozlowski-opensource** [comment]
> Wouldn't most people use bower?

I hope not... it is broken in several ways and the JS community seems to be shifting to npm...

**Comment by rvanbaalen** [comment]
@blakemcbride thanks for the feedback. Will update the README.

**Comment by blakemcbride** [comment]
Thanks!  As soon as I figure out what scripts and CSS files to load, I'd like to start using it.

**Comment by rvanbaalen** [comment]
For now, there's some useful stuff in the Wiki pages for you

**Comment by icfantv** [comment]
At the most very basic level, downloading and adding the Bootstrap CSS file and the full Angular UI Bootstrap JS file to your `<head>` section will be sufficient to get started.  Please see the [`Manual` section](https://github.com/angular-ui/bootstrap#manual-download) for more info.
