### ISSUE TITLE
Three DatePickers. onwatch or ng-change work only once.

### ISSUE THREAD

**Issue by hmendezm** [angular-ui/bootstrap#3487]
I have three datepickers in my page. My problem is that I can select days but I can validate them because the ng-model is not updated and onwatch or ng-change is not trigged. I really need your help!!

VIEW HTML DATEPICKERS

<div class="form-group col-xs-6"  ng-hide="rule.fRecurrence">
							<label>Start Date</label>
							   <p class="input-group">
						              <input type="text" id="eventDate" class="form-control" datepicker-popup="{{format}}" ng-model="rule.tmpEventDate" is-open="datepickers.eventDate" min-date="minDate" 
						              date-Validator  valid-range="{{IsDatesValid()}}" required maxlength="10"
						              		 datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text="Close" show-weeks='false' ng-disabled="{{isDisabled}}" name="tmpEventDate" />
						              <span class="input-group-btn">
						                <button type="button" class="btn btn-default" ng-click="openCalendar($event,'eventDate')" ng-disabled="{{isDisabled}}"><i class="glyphicon glyphicon-calendar"></i></button>
						              </span>
						             <p ng-show="!userForm.tmpEventDate.$valid" style="color: red;">Date is invalid. (MM/DD/YYYY)!</p>
 	
					            </p>
						</div>
						<div class="form-group col-xs-6" style="padding-top:4px" ng-hide="rule.fAllDayEvent">
							<label ng-hide="!rule.fRecurrence">Start Time</label>
							<timepicker id="tEventTime" ng-model="rule.tmpEventTime" style="width: 50%;" hour-step="hstep" minute-step="mstep" show-meridian="ismeridian" ng-disabled="{{isDisabled}}"></timepicker>
			
						</div>
					</div>
				
					<div class="col-xs-6 column box">
						<div class="form-group col-xs-6"  ng-hide="rule.fRecurrence">
							<label>End Date</label>
							   <p class="input-group">
					              <input type="text" id="endDate" class="form-control" datepicker-popup="{{format}}" ng-model="rule.tmpEndDate" is-open="datepickers.endDate" min-date="minDate" 
					              date-Validator valid-range="{{IsDatesValid()}}"  required maxlength="10" 
					              		 datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text="Close" show-weeks='false' ng-disabled="{{isDisabled}}" name="tmpEndDate" />
					              <span class="input-group-btn">
					                <button type="button" class="btn btn-default" ng-click="openCalendar($event,'endDate')" ng-disabled="{{isDisabled}}"><i class="glyphicon glyphicon-calendar"></i></button>
					              </span>
					               <p ng-show="!userForm.tmpEndDate.$valid" ng-if="IsDatesValid()" style="color: red;">Date is invalid. (MM/DD/YYYY)!</p>
									<p ng-show="!IsDatesValid()" style="color: red;">End date\time must be greater than start date\time!</p>
					            </p>
						</div>

CONTROLLER CODE

		/*DatePicker*/
			
		 $scope.clear = function () {
		 
		    $scope.rule.EventDate = null;
		  };
		  
		  $scope.toggleMin = function() {
		    $scope.minDate = $scope.minDate ? null : new Date();
		  };
		  $scope.toggleMin();
		  
		  
		// Disable weekend selection
		  $scope.disabled = function(date, mode) {
		    return ( mode === 'day' && ( date.getDay() === 0 || date.getDay() === 6 ) );
		  };

	// Calendars open flags
		$scope.datepickers = {
	        eventDate: false,
	        endDate: false,
	        endbyDate:false,
	        RecurrenceStartDate:false
	      }

 		$scope.openCalendar = function($event, which) {
	        $event.preventDefault();
	        $event.stopPropagation();

	        $scope.datepickers[which]= true;
      	};      

		  $scope.dateOptions = {
		    formatYear: 'yy',
		    startingDay: 1
		  };
		
		  $scope.format = 'MM/dd/yyyy';
		  
		/*TimePicker*/
		  $scope.hstep = 1;
		  $scope.mstep = 5;
		
		  $scope.options = {
		    hstep: [1, 2, 3],
		    mstep: [1, 5, 10, 15, 25, 30]
		  };
		
		  $scope.ismeridian = true;
		  $scope.toggleMode = function() {
		    $scope.ismeridian = ! $scope.ismeridian;
		  };
		
		  $scope.update = function() {
		    var d = new Date();
		    d.setHours( 14 );
		    d.setMinutes( 0 );
		    $scope.mytime = d;
		  };

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support

**Comment by hmendezm** [comment]
There is nothing in the link that can help me with my problem. What was the intention of the link and why did you close my question?

Thx

**Comment by realityking** [comment]
He closed the issue, because this is not the appropriate venue for support questions. Please read the *Need help?* section of the above link.
