### ISSUE TITLE
Too many errors when trying to include in my project

### ISSUE THREAD

**Issue by marvoh** [angular-ui/bootstrap#3489]
I am using angular.js version 1.3.0 and have the included the js files in the index.html as below:

    <script src="lib/onsen/js/angular/angular.js"></script>
    <script src="https://code.angularjs.org/1.3.1/i18n/angular-locale_en-gb.js"></script>
    <script src="lib/onsen/js/onsenui.js"></script> 
    <script src="js/ui-bootstrap-0.12.1.min.js"></script>
    <script src="js/ui-bootstrap-tpls-0.12.1.min.js"></script>
    <script src="js/app.js"></script>

When I serve my app through gulp, I get the following error messages:

    www\js\ui-bootstrap-tpls-0.12.1.min.js
    line 8  col 1617  Expected '{' and instead saw 'if'.
    line 8  col 1640  Expected '{' and instead saw 'return'.
    line 8  col 1651  Missing semicolon.
    line 8  col 1823  Missing semicolon.
    line 8  col 1825  Missing semicolon.
    line 8  col 1968  Missing semicolon.
    line 8  col 2048  Missing semicolon.
    line 8  col 2059  Missing semicolon.
    line 8  col 2416  Missing semicolon.
    line 8  col 2608  Missing semicolon.
    line 8  col 2614  'e' is already defined.
    line 8  col 2660  Missing semicolon.
    line 8  col 2780  Missing semicolon.
    .....
    .....
    line 8  col 9980  Too many errors. (80% scanned).

    × 101 problems

What am I doing wrong?

**Comment by realityking** [comment]
First of all, you're loading UI Bootstrap twice. The file with "tpls" in the name contains the first file.

The issue you're seeing is that you're running JSHint over the minefield source for UI Bootstrap. You should change your build environment to only check your own files with JSHint, not 3rd party libraries.

Lastly, be aware that UI Bootstrap 0.12 is not fully compatible with AngularJS 1.3.

**Comment by marvoh** [comment]
I corrected that but still had errors. I resolved this by using the uncompressed version.
