### ISSUE TITLE
Toggle Buttons ng-click fires before scope / model data is updated. 

### ISSUE THREAD

**Issue by markalanevans** [angular-ui/bootstrap#349]
I have created a plunker for you.

http://plnkr.co/edit/oUIyUW9b9KUn6zR8ZK9L?p=preview

Click any of the buttons in the toggle.
You will notice that the click fires and the data available via scope is still the old data. 
Perhaps this is by design and there is some way to detect when the scope data has updated?

PS. 
Your example here:
http://angular-ui.github.io/bootstrap/#/buttons   for the radio option says 
`data-toggle="buttons-checkbox"`

I think you meant data-toggle="buttons-radio".

**Comment by jeonghwan-kim** [comment]
Nice.

**Comment by cnaccio** [comment]
ng-change worked perfectly; duh!
