### ISSUE TITLE
Pagination Improvement

### ISSUE THREAD

**Issue by leoncc** [angular-ui/bootstrap#3490]
Hi,

I suggest the following change for the two watches for the PaginationController in ui-bootstrap-tpls.js.

<pre>
  $scope.$watch('totalItems', function() {
    $scope.totalPages = self.calculateTotalPages();
    ngModelCtrl.$render();
  });

  $scope.$watch('totalPages', function(value) {
    setNumPages($scope.$parent, value); // Readonly variable
  });
</pre>

as opposed to what you currently have. The reason being that if totalItems changes, for instance in the case where you fetch only a page of data from the server and the server also provides an updated count of totalItems then both watches gets triggered and the $scope.selectPage(value) resets to the first page.

<pre>
  $scope.$watch('totalItems', function() {
    $scope.totalPages = self.calculateTotalPages();
  });

  $scope.$watch('totalPages', function(value) {
    setNumPages($scope.$parent, value); // Readonly variable

    if ( $scope.page > value ) {
      $scope.selectPage(value);
    } else {
      ngModelCtrl.$render();
    }
  });
</pre>

**Comment by wesleycho** [comment]
We welcome a PR for this - this looks like it would be a nice optimization.

**Comment by warmhug** [comment]
In addition, when `totalItems` is very big, for example `totalItems = 600000`, it would cause the page to suspend!

**Comment by wesleycho** [comment]
I took a look at this, making the suggested changes looks like it breaks other functionality - perhaps this needs to be revisited as to how to optimize, but this appears to be an invalid optimization unfortunately.
