### ISSUE TITLE
Missing class from css overrides.

### ISSUE THREAD

**Issue by topless** [angular-ui/bootstrap#3492]
.nav, `.navbar-brand`, .pagination, .carousel, .panel-title a { cursor: pointer; }

**Comment by wesleycho** [comment]
I am confused about this issue - can you explain in more detail, and perhaps a reproduction?

**Comment by chrisirhc** [comment]
This looks like an issue for Twitter Bootstrap https://github.com/twbs/bootstrap . There aren't CSS overrides in this repository except for animations.

**Comment by wesleycho** [comment]
Closing as invalid unless there is more information - we do not bundle CSS for UI Bootstrap.
