### ISSUE TITLE
Collapsing bootstrap navbar menu - menu items shortened during collapsing

### ISSUE THREAD

**Issue by Lucasus** [angular-ui/bootstrap#3493]
Here is [plnkr reproduce scenario](http://plnkr.co/edit/cNiLd3rvKe1Ne3nwcZ8J?p=preview)

To reproduce: make the view narrow (so the toggle button appears) and expand a toggle menu. Now collapse the menu. Notice that menu items are shortened when menu is collapsing (a white "right margin" temporarily appears on the plnkr).

Possible cause and fix:

The height set in collapse directive's `collapse()` function is too low (`1px` too low in the example):
`element.css({ height: element[0].scrollHeight + 'px' });`

This causes a vertical scroll bar to be temporarily shown for menu items (the scroll bar is visible when debugging, you won't notice it in the plnkr).

I've changed `scrollHeight` to `offsetHeight` and the problem disappears (in the example, `offsetHeight` is `1px` longer than `scrollHeight`, probably because it includes also the border height). I'm not a DOM master, so I'm not sure this fix won't break anything.

**Comment by wesleycho** [comment]
This should currently be fixed via 6d1cd0f
