### ISSUE TITLE
Modal Dialog templateUrl requests application/json instead of text/html

### ISSUE THREAD

**Issue by madhavabhyankar** [angular-ui/bootstrap#3495]
Here is a request from one of my modal calls
GET /app/views/wishDetails/wishDetailsModal.html HTTP/1.1
Host: localhost:51615
Connection: keep-alive
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
Referer: http://localhost:51615/Index.html
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
If-None-Match: "03738af1770d01:0"
If-Modified-Since: Mon, 06 Apr 2015 03:13:42 GMT

The "Accept" part of the header s/b 'text/html'

**Comment by chrisirhc** [comment]
These are the default headers in AngularJS as [stated here](https://github.com/angular/angular.js/blob/master/src/ng/http.js#L233). AngularJS makes the requests for the templateUrl. Please file a bug at https://github.com/angular/angular.js/ instead.

**Comment by madhavabhyankar** [comment]
The default headers are correct, when I try to call the modal dialog - with template url pointing to the html page, I get '406 - not acceptable'.  How do you recommend doing the pop up without embedding the html in one of the pages with the <script type="text/ng-template" id="itemBoughtModal.html"> tag.  The 406 error goes away if in the function - 'getTemplatePromise', I add the header  { Accept: 'text/html' }
