### ISSUE TITLE
0.13 release in Bower

### ISSUE THREAD

**Issue by pankas87** [angular-ui/bootstrap#3501]
Hi,

thanks for all your hard work, this module is amazing, it has helped me a lot in a big project I'm doing.

Is there any release date for v0.13 via Bower? 

I really need to use a template for the contents of a popover and got really excited when I read this would be released soon.

Thank you!

**Comment by karianna** [comment]
Not concrete ETA, https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by realityking** [comment]
@karianna That section was removed a week ago (https://github.com/angular-ui/bootstrap/commit/6355d8adc7d051e18739e617cba158f5d29c15d4)

**Comment by karianna** [comment]
Heh - so it was, you can look for 0.13.0 milestone issues to get a guesstimate of how close we are to a release.
