### ISSUE TITLE
Carousel controller can't be found

### ISSUE THREAD

**Issue by thebucknerlife** [angular-ui/bootstrap#3502]
Whenever I try to use the carousel directive, I get this error in my js console:

```
Error: [$compile:ctreq] Controller 'carousel', required by directive 'slide', can't be found!
```

I created a custom build with carousel and collapse. Requiring like this: `<script src="assets/js/vendor/ui-bootstrap-custom-tpls-0.12.1.min.js"></script>`

I've included 'ui.bootstrap' as a dependency when creating my app. 

Entire error:
```
Error: [$compile:ctreq] Controller 'carousel', required by directive 'slide', can't be found!
http://errors.angularjs.org/1.2.19/$compile/ctreq?p0=carousel&p1=slide
    at https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:1:675
    at $ (https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:1:25062)
    at m (https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:1:26831)
    at https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:1:30240
    at https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:2:4311
    at a.promise.then.l (https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:2:19985)
    at a.promise.then.l (https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:2:19985)
    at https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:2:20662
    at l.$get.l.$eval (https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:2:25869)
    at l.$get.l.$digest (https://cdn.jsdelivr.net/angular.all/1.2.19/angular-all.min.js:2:24394) <div ng-class="{
    'active': leaving || (active &amp;&amp; !entering),
    'prev': (next || active) &amp;&amp; direction=='prev',
    'next': (next || active) &amp;&amp; direction=='next',
    'right': direction=='prev',
    'left': direction=='next'
  }" class="left carousel-control item text-center ng-isolate-scope" ng-transclude="" href="#preview-image-carousel" data-slide="prev">
```

Relevant part of the template:

```
... 
<h1>Angular-UI Carousel</h1>
  <carousel interval="5000">
    <slide ng-repeat="slide in vm.slides" active="slide.active">
      <img ng-src="{{ slide.image }}" style="margin:auto;">
    </slide>
  </carousel>
...
```

and controller:

```
.controller('CreateThingController', ['$state', function($state) {
    var vm = this;

    vm.slides = [
      {image: 'http://veggiesetgo.com/wp-content/uploads/2012/05/Bottega-Louie_2.jpg'},
      {image: 'http://shubinanddonaldson.com/wp-content/uploads/2012/05/LB02_Bar-C1.jpg'}
    ];
...
```

Thanks for the help.

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#support

**Comment by qz2rg4** [comment]
Have you found a fix to this problem?

**Comment by thebucknerlife** [comment]
@qz2rg4 no :( I ended up ripping out ui-bootstrap and figured out how to use a vanilla bootstrap Carousel. Let me know if you want to see how I did it and I cal post that.

**Comment by qz2rg4** [comment]
Thanks. Did you  use it in conjunction with angular or did you use the bootstrap.js ?

**Comment by thebucknerlife** [comment]
Pure bootstrap JS.

**Comment by cboden** [comment]
Same issue. Can you post how you resolved this @thebucknerlife please?

**Comment by thebucknerlife** [comment]
Totally @cboden 

Here is the relevant part of my layout file:
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
...
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
```

So I'm using css for Bootstrap 3.0.0 and the JS from bootstrap 3.3.2. Haha sorry I know that is totally wacky but this is an existing project I inherited. I would anticipate you can use both JS and CSS from 3.3.2 and this will still work. If not, let me know! That will be f***ing interesting.

Here is a partial I'm using for the carousel. I'm `ng-includes`'ing it, in case that has any bearing. But I don't anticipate it mattering:

```
<div id="preview-carousel" class="carousel slide" data-ride="carousel" data-interval="false">
  <!-- Slides -->
  <div class="carousel-inner">
    <div class="item" ng-repeat="slide in vm.images" ng-class="{'active': slide.active}">
      <img ng-src="{{ slide.url }}">
    </div>
  </div>
  <!-- end Slides -->

  <!-- Controls -->
  <a class="left carousel-control" ng-class="{'hide': vm.images.length == 0}" role="button" data-target="#preview-carousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" ng-class="{'hide': vm.images.length == 0}" role="button" data-target="#preview-carousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <ol class="carousel-indicators">
    <li ng-repeat="slide in vm.images" ng-class="{'active': slide.active}" data-target="#preview-carousel" data-slide-to="{{ $index }}" ></li>
  </ol>
  <!-- end Controls -->
</div>
```

Some notes:

* I'm using Controller As syntax, so vm is the name of my controller. vm.images is an array of image objects, each represented as a JS object (aka hash, dictionary, whatever vernacular you prefer). You have to keep track of which slide is active, hence the `ng-class`. When loading images into the carousel, make sure to initialize the first object in your array as "active". You could do this in your controller. Just make sure one of them has a class active (and only one!) otherwise the carousel wigs out.

Cool? Let me know if I can provide any more details.

G

**Comment by raza2022** [comment]
http://stackoverflow.com/questions/26332202/using-ui-bootstrap-causing-issues-with-carousel

**Comment by vikrampaygude** [comment]
In the below link fix is given
http://stackoverflow.com/questions/26332202/using-ui-bootstrap-causing-issues-with-carousel

Workaround/Fix 
Add ng-non-bindable and change href for data-target

```
<a class="left carousel-control" data-target="#myCarousel" role="button" data-slide="prev" ng-non-bindable><</a>
<a class="right carousel-control" data-target="#myCarousel" role="button" data-slide="next" ng-non-bindable>></a>
```

**Comment by ruisilva450** [comment]
Hi, the ng-non-bindable is doing the right job on "prev" and "next" parts but I have this same issue on the indicators. My code is like this:
```
<ol class="carousel-indicators visible-xs">
    <li data-target="#carousel-example-generic" ng-non-bindable data-slide-to="{{$index}}" ng-class="{'active': $index == 0 }" ng-repeat="image in images">
    </li>
</ol>
```
And this code doesn't fix this issue because the rendered html is:
```
<ol class="carousel-indicators visible-xs">
    <li data-target="#carousel-example-generic" data-slide-to="0" ng-class="{'active': $index == 0 }" ng-repeat="image in images" class="ng-scope"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1" ng-class="{'active': $index == 0 }" ng-repeat="image in images" class="ng-scope"></li>
    ...
</ol>
```

Causing the error again...

**Comment by raza2022** [comment]
@ruisilva450 did you tried http://stackoverflow.com/a/26612052/4441764

**Comment by ruisilva450** [comment]
@raza2022 Can you explain how do I add that linked piece of code in my app?
In app.js?

**Comment by aamin3189** [comment]
The page is getting reloaded if we add ng-non-bindable
