### ISSUE TITLE
Datepicker - Inconsistent validation behavior between IE11 and Chrome

### ISSUE THREAD

**Issue by Asvarduil** [angular-ui/bootstrap#3503]
*Note: No Plunkers needed; simply use the datepicker control on the [https://angular-ui.github.io/bootstrap/](UI Bootstrap Documentation) to observe this issue.*

**Steps to Reproduce:**
1. Open an instance of Internet Explorer 11 and Chrome
2. In each instance, open the [https://angular-ui.github.io/bootstrap/](UI Bootstrap Documentation)
3. Navigate down to the Datepicker
4. In the text field, manually enter an invalid date (I used "4/", without quotes)
Observe that in Internet Explorer 11, the field gains a red outline, denoting a validation error.  In Chrome, however, the Calendar gains a red outline, but the input field that the invalid value was entered in retains a valid style.
5. Right-click the element in both browsers, and navigate to element
6. Observe that in IE, the text field has the `ng-invalid`, `ng-invalid-required`, and `ng-invalid-date` classes.
7. Observe that in Chrome, the text field has the `ng-valid`, `ng-valid-required`, and `ng-valid-date` classes.

**Expected Results:**
When an invalid date is given to the Datepicker text field, the control should generate the same validation errors between different browsers.

**Observed Results:**
When an invalid date is given to the Datepicker text field, IE correctly recognizes the validation error, but for some reason the error does not register for Chrome.

**Comment by RobJacobs** [comment]
I'll do some testing on this and post results.  Latest master branch build is not behaving this way.  Documentation page has 2 datepickers (inline and popup) bound to the same date so that may be impacting the results as well.

**Comment by RobJacobs** [comment]
I think this is just a difference between how the 2 browsers handle dates.  You will notice entering 4/90 causes Chrome to display the invalid states correctly, where 4/ could possibly be a valid date.  Closing for now.

**Comment by karianna** [comment]
Moving the datepicker to moment.js in 1.0 will resolve this long term, there are dup issues open for that.

**Comment by chrisirhc** [comment]
This will also be fixed once we merge in #3294, by completely disallowing dates that don't parse through the dateParser.
