### ISSUE TITLE
Calling dismiss causing ng-submit handler to fire.

### ISSUE THREAD

**Issue by mdsauer** [angular-ui/bootstrap#3504]
If a form with the ng-submit directive is included in a modal window, the submit handler is called when $modalInstance.dismiss is called.  My intent was to call dismiss on a cancel button but I am finding that the ng-submit method is being called as well as my ng-click handler on the cancel button.
Changing the code to not use ng-submit and instead use ng-click on the submit button works as expected.
This is happening with version 0.12.1 and angular 1.3.15.

**Comment by chrisirhc** [comment]
Could you please post a Plunker demonstrating this issue?

**Comment by mdsauer** [comment]
I posted the following at plunker:
http://plnkr.co/edit/dEYpnULoBFjQn3YLGesj?p=preview

Open a console.
If you press 'Open modal with ng-submit' and then cancel the modal, you should see two entries in the log, one from the cancel action and another from the submit action.

If you plress 'Open modal without ng-submit' and then cancel, only the cancel entry appears in the log.

**Comment by RobJacobs** [comment]
@mdsauer You need to stop the cancel click event from bubbling by using preventDefault() and stopPropagatiion().  This [plunker](http://plnkr.co/edit/zRIKqzw4GWW4wHilA3F9?p=preview) demonstrates that.

**Comment by mdsauer** [comment]
Thanks Rob.  I should have seen that this was an issue with the way I did the form regardless of whether I was using a modal.  For those interested, another fix is to make sure that the cancel button has type="button".  Without this the button defaults to type submit and hence both the ng-click and the submit action both fire.

**Comment by freshfelicio** [comment]
Thank you so much @mdsauer!!! Had the exact same issue. Adding type="button" fixed it.
