### ISSUE TITLE
tooltip - Issues with PR #3126

### ISSUE THREAD

**Issue by RobJacobs** [angular-ui/bootstrap#3506]
PR #3126 introduced the ability to support defining a class for the tooltip as an attribute.  This is causing issues with how the popover adds the placement and animation classes, this [plunker](http://plnkr.co/edit/hp2hIKSiZXP0iRU6lhkM?p=preview) demonstrates the issue.  You will notice the popover does not display the arrow correctly and the animation doesn't run when it opens and closes.  I've narrowed down the problem to the following line in the tooltip provider where the template variable is declared:

    'class="'+startSym+'class'+endSym+'" '+

The classes on the outer popover div are not getting added correctly.  The outer popover div should have:

    class="popover right fade in"

but instead have:

    class="popover popover in"

We should also reconsider using 'class' as a variable as that is a reserved word in ECMA 6.

**Comment by chrisirhc** [comment]
Thanks! Looks like my fix (https://github.com/angular-ui/bootstrap/commit/461087b5ff360e1d06d6724375ab29169a89fcf2) was incomplete. I'll look into this very soon.
