### ISSUE TITLE
dropdown is-open attribute only closes dropdown, won't open it

### ISSUE THREAD

**Issue by twler** [angular-ui/bootstrap#3514]
The dropdown `is-open` will only close the dropdown (i.e. will only set the `is-open` variable to false)

Here's an example with the JS unchanged from the official docs:
http://plnkr.co/edit/3pzUhAklYFcCl04mXaI9?p=preview

**Comment by karianna** [comment]
This has been fixed in master, hoping to get 0.13.0 out soon!

**Comment by snehatulsi** [comment]
In the button ng-click, 
     ng-click="toggleDropdown()"
u missed out passing $event to the function. This will solve the issue.  
     ng-click="toggleDropdown($event)"
