### ISSUE TITLE
Collapse event 

### ISSUE THREAD

**Issue by artem-galas** [angular-ui/bootstrap#3523]
Hi everyone!

I've recently got stuck with such a problem.
I use `angular-ui bootstrap` and I want to call `show.bs.collapse` callback for collapse, but nothing happens. Here's my [plank] (http://plnkr.co/edit/rD1w7lqdBgJjAuGGEfQE?p=preview) .

Pls, help.

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by artem-galas** [comment]
Sorry...
This is [question on stackoverflow] (http://stackoverflow.com/questions/29558672/collapse-event-doesnt-work-in-angular-js)
