### ISSUE TITLE
Discussion - Adding Aria compatibility & improving accessibility

### ISSUE THREAD

**Issue by rvanbaalen** [angular-ui/bootstrap#3526]
Opening this tread to discuss Aria compatibility / accessibility in general with @angular-ui/bootstrap and it's community. I'll also reference all Aria related PR's and issues in here.

Related issues:  #494, #2249, #2303, #2688, #3095, #3199, #3253, #3264, #3474 

Related PR's: #1714, #2174, #3329, #2316, #2515, #3329

### Resources (curated list)

- http://www.w3.org/TR/wai-aria-practices
- https://developer.mozilla.org/en-US/docs/Accessibility/ARIA
- https://docs.angularjs.org/guide/accessibility
- http://a11yproject.com/checklist.html
- http://oaa-accessibility.org
- https://medium.com/@cironunesdev/angularjs-cares-about-accessibility-607785648c58
- [Fully accessible datepicker](http://oaa-accessibility.org/example/15/)
- https://www.marcozehe.de/2015/02/05/advanced-aria-tip-2-accessible-modal-dialogs/
- https://egghead.io/lessons/angularjs-using-ng-aria-to-automatically-improve-your-angularjs-accessibility

- http://www.webdesignerdepot.com/2015/04/8-reasons-to-embrace-website-accessibility/

### Tools

- [Automated Accessibility testing](https://github.com/nature/pa11y)

### Milestone 1.1

Everything accessibility and ARIA related will be covered in milestone `v1.1.0`.

**Comment by rvanbaalen** [comment]
Related: 

#494
#2249
#2249
#2303
#2688
#3095
#3199
#3253
#3264
#3474

**Comment by Tobino** [comment]
Is it possible to get a label "accessibility"?
Like [twbs/bootstrap](https://github.com/twbs/bootstrap/labels/accessibility)

**Comment by rvanbaalen** [comment]
@Tobino your prayers are heard :wink: `type: accessibility` tag is created

**Comment by icfantv** [comment]
Closing in favor of #4772.

**Comment by icfantv** [comment]
Closing in favor of #4772.
