### ISSUE TITLE
$touched not set to TimePicker

### ISSUE THREAD

**Issue by mesuttalebi** [angular-ui/bootstrap#3527]
when hour control or minute control touched and value changed, we must could be able to get 
form.[TimePicker control's name].$touched == true

but it not set. mean ng-touched must be added to control's classes.

**Comment by karianna** [comment]
plunkr please.

**Comment by mesuttalebi** [comment]
http://plnkr.co/edit/zYXJ9GU0LU6ReEDqO2EU?p=preview

change $touched to $dirty to see what I mean.

**Comment by wesleycho** [comment]
I think this might be fixed in master - check out this [Plunker](http://plnkr.co/edit/PK8xTh2IZB3AUv87OqLt?p=preview).

**Comment by wesleycho** [comment]
This is not actually fixed - this should be a simple fix if someone wants to open a PR.

**Comment by icfantv** [comment]
I can take a look at this tonight.

**Comment by icfantv** [comment]
we're going to push this to 0.14.0 as we're releasing 0.13.4 late tonight or first thing in the AM.
