### ISSUE TITLE
How to reset main body size of datepicker?

### ISSUE THREAD

**Issue by TigerSoaring** [angular-ui/bootstrap#3530]
I'm try to reset the body size of datepicker followed the example,but the main body size of datepicker is not changed?
<div style="display:inline-block; min-height:400px; min-width:400px">
        <datepicker ng-model="dt" min-date="minDate" show-weeks="true" class="well well-sm">  </datepicker>
</div>
I wonder how to reset it?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by hsbilgen** [comment]
I would like to resize of my datepicker its too large. How can i set the width and height? I was using it and i need to make it smaller size of datepicker options. 

Any idea?  here is my plunk : http://plnkr.co/edit/PrhDJPjXrskZcIYMx2do?p=preview

**Comment by icfantv** [comment]
@hsbilgen, please do not comment on closed issues.  Doing so is a good way for them to get missed/ignored.  Per our project documentation, questions of this nature are best suited for SO so that they may be addressed and solved by the community at large.
