### ISSUE TITLE
windowClass not correctyle set on modal

### ISSUE THREAD

**Issue by EdwinRikkers** [angular-ui/bootstrap#3538]
from bootstrap-ui 0.11+ the windowClass property on the modal is not properly set in the html anymore. In bootstrap-ui 0.10.0 everything is working fine. Also the size option is not working.

**Comment by karianna** [comment]
plunkr please

**Comment by rvanbaalen** [comment]
As you can see in the demo's plunkr, the size option is working just fine:

http://plnkr.co/edit/HNmnv5yegRdRHBAhhLwj?p=preview

And there's nothing wrong with the `windowClass` either as demonstrated in this plunkr:

http://plnkr.co/edit/w46FTequFL0LHtsuJGMp

Closing until more information is provided.
