### ISSUE TITLE
Use tooltip combined with other elements cause collision of $digest.

### ISSUE THREAD

**Issue by TomerAvni** [angular-ui/bootstrap#3539]
Using the tooltip directive alongside another directive might cause collision in $digest having both directives $applying their phase.
Specifically in line 2589 on the hideTooltipBind function, a better approach might be 
scope.$evalAsync(hide);
instead of:
 scope.$apply(function () {
                hide();
              });
To avoid collision in $digesting.

P.S.
There other ways to solve this problem (such as validating $digest is not in progress).

**Comment by Gamemaniak** [comment]
Isn't this a duplicate of #516?

**Comment by TomerAvni** [comment]
It is... Sorry for this.

**Comment by chrisirhc** [comment]
Actually, @TomerAvni , could you post a reproduction? I want to figure out which use cases are missing. Perhaps you can add a reproduction on #516 .
