### ISSUE TITLE
Tabset content ng-model is not working

### ISSUE THREAD

**Issue by dosapati** [angular-ui/bootstrap#3543]
Facing a weird issue, where a simple text field value is not getting getting printed when using tabset. Wrote a sample to demo the same. Please check it below link

http://plnkr.co/edit/JczXnsFj9MZR9kpyBVn5?p=preview

Do suggest, what would have been missed out.

Thanks in advance.

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#need-help
