### ISSUE TITLE
Tooltip > Mobile orientation change

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [angular-ui/bootstrap#3552]
Not sure if this is already known, but when you specify the `tooltip-placement` while using tooltip, then the tooltip repositions itself incorrectly on orientation change in mobile. It seems that the tooltip repositions itself perfectly on orientation change when `tooltip-placement` is not indicated. You can see the issue [here](http://plnkr.co/edit/xchLBGlFks7LfvLOkRUt?p=preview) (which is shamelessly taken from from the angular ui bootstrap site).

**Comment by wesleycho** [comment]
This now appears to be fixed in `master`, as can be seen [here](http://embed.plnkr.co/JLVOdDczRhnDcWBIj1go/)
