### ISSUE TITLE
injecting html in a popover doesn't work/popover templates do not work

### ISSUE THREAD

**Issue by jpetraws** [angular-ui/bootstrap#3553]
Not sure if I am doing this wrong or what...

    <div class="col-lg-12">
      <legend>Android Industries
        <i class="fa fa-truck"
           popover-placement="bottom"
           popover-template="{{templateUrl}}"
           popover-title="Requests for shipments">
          <span class="badge">2</span>
        </i>
      </legend>
    </div>

##js 
        
    $scope.templateUrl = 'app/views/android-industries-popover-template.html';

I get the following error message...

GET http://localhost:63342/MOCK_UPS__2/MOCK_UPS_2/app/template/popover/popover-template.html 404 (Not Found)
angular.js:11594 Error: [$compile:tpload] Failed to load template: template/popover/popover-template.html
http://errors.angularjs.org/1.3.9/$compile/tpload?p0=template%2Fpopover%2Fpopover-template.html

It is not even trying to look for my template... and even if I do bring that template in, then it will just make the string 'app/views/android-industries-popover-template.html' the content in the popover.
I have tried it with and without the {{}}.

**Comment by rvanbaalen** [comment]
This feature has not landed in a stable release yet. Unless you're using a manual build from the current master branch, this feature does not exist.

What version of Angular and UI Bootstrap are you using and if it's one of the officially release versions, please provide a plunkr reproducing your problem.

**Comment by jpetraws** [comment]
I am using a manual build by copying the new popover.js into the latest release.

    AngularJS v1.3.9, Bootstrap v3.3.1

Here is a quick plunker of my problem

http://plnkr.co/edit/bBAeHhFF6oE7XvCfUibc?p=preview

**Comment by RobJacobs** [comment]
@jpetraws A problem I see right off is that you are using the bootstrap javascript library and the angular-ui-bootstrap library.  The plunker provided does not have the latest angular-ui-bootstrap library or a manual build, it's pulling from http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.12.1.min.js.  Here is a [plunk](http://plnkr.co/edit/nbbfpG2TjB3uvSORsSAJ?p=preview) with the latest build from master using a popover with the new template feature.  If you can reproduce the problem using that plunk I'll reopen the issue, thanks.
