### ISSUE TITLE
Issue with typehead not working in modal dialog called from modal dialog

### ISSUE THREAD

**Issue by Skypus** [angular-ui/bootstrap#3560]
Env: IE 11.0.xx

Issue description: typehead not fire keydown event and typehead not working as a result.

Fix:
Changes to angularjs.js 1.3.14

Method: function $SnifferProvider() 
                           hasEvent  
Line:            
Before        if (event === 'input' && msie <= 11) return false;
After:
                          if (event === 'input' && msie <= 10) return false;

This is fixing issue with reaching keydown event typehead element(s).

Please let me know if this possible to fix in other way etc.

Thanks,

Pavel

**Comment by karianna** [comment]
Can you provide a plunkr please

**Comment by Skypus** [comment]
Here it is:

This is how it works 

http://plnkr.co/edit/roCvxWQkxIGIo9Qui6Fx?p=preview

To replicate issue change angular version to 1.3.15

This will kill keydown event to reaching typehead element.

**Comment by rvanbaalen** [comment]
Can you explain the use case where you need to open a modal in a modal?

**Comment by Skypus** [comment]
Not sure what you mean. But when I have typehead in the second modal dialog its failing to work in angularjs 1.3.x.
This all need to be tested in IE, I would say IE 11.x
Thanks,

**Comment by rvanbaalen** [comment]
Well I can reproduce this in Chrome as well. But what I meant with 'what is the use case' is please explain why you would trigger a modal from another modal. It smells like there is something wrong with your UI design rather than the library having to support such edge cases.

From what I can see, this seems to be a z-index issue since the modals just keep stacking up but the typeahead dropdown has a lower z-index than the second modal.

**Comment by Skypus** [comment]
Well, UI is fine. Main, first level modal dialog looks much bigger and second is just to provide user input etc.
There is nothing to do with z-index. 

This is just and example how it works on production system.

If you would dig deeper you will see that typehead not getting 'keydown' event. 

So I did provided you with the quick fix above and would like to have more appropriate solution etc.

Thank you,

**Comment by wesleycho** [comment]
This looks like this has to do something with mixing Bootstrap's JS and UI Bootstrap.

I am rejecting this as won't support.
