### ISSUE TITLE
Cleanup Demo Inconsistency and Readability

### ISSUE THREAD

**Issue by dmitriz** [angular-ui/bootstrap#3562]
There is some inconsistency and lack of clear explanation for a few components on

http://angular-ui.github.io/bootstrap/

- The descriptions for **Button** and **Collapse** do not say what the actual directives are.

- Some directives are used as Elements and some as Attributes. It would be good to state the actual rules rather than guess them from demo examples.

- Typeahead description does not document the API `match.label` and `typeaheadHighlight:query` used inside examples' templates.

- Is there Controller namespace clashing issues? None is mentioned on the page.

Also in the Demo the UIB-components get blended among other "noise" created by the bootstrap markup, so it is hard to tell which one is which.

I would suggest an easy solution to this problem - highlight all new markup related to UIB-components.
This would **really** help the readability.

If there is agreement, I could make the corrections (once I find how to view demo pages locally, that is :)

**Comment by karianna** [comment]
@dmitriz PR welcome!

**Comment by dmitriz** [comment]
Ok  :)

Any easy way to build and view the doc locally?

Couldn't find in Grunt but I'm no Grunt (I'm Gulp :-)

**Comment by chrisirhc** [comment]
When you run `grunt` it builds the documentation in the `dist` folder. You can run a http server (such as `http-server` on npm) and point your browser to `dist/index.html` .

**Comment by dmitriz** [comment]
Thanks! 
Didn't expect the demo pages "hidden" inside `dist`. :)

PR submitted!

**Comment by dmitriz** [comment]
Unfortunately, I could not find an easy way to <mark>highlight</mark> the demo code as I previously proposed. Too bad as that would really improve the readability. 

The main problem seems to be that the same files are used as actual code and again to show the markup. Which is a good precaution against putting messy code on the Demo. But this makes it very hard to add markup without affecting the functionality.

If anyone has a solution - please let me know.

**Comment by rvanbaalen** [comment]
I think it will be too much to highlight the demo code where actual UI Bootstrap code is used. It's expected from users that they have some sort of experience with using Twitter Bootstrap and by having that, I think it's fairly clear to read the code examples and know what's 'new' (e.g. from UI Bootstrap).

**Comment by wesleycho** [comment]
Assigned to @Foxandxss and moved the milestone back - he has been slowly doing some work in this area
