### ISSUE TITLE
Datepicker min-date Ignores Format

### ISSUE THREAD

**Issue by matt-major** [angular-ui/bootstrap#3570]
**Angular**: 1.3.2
**Angular UI**: 0.12.1

I'm formatting my dates to the format ```dd/MM/yyyy``` (UK-style) and trying to use these for the ```min-date``` attribute on the DatePicker directive.

This directive is reading the date in the format of ```MM/dd/yyyy```, which causes (for example) April 5th to be read as May 4th.

I believe the directive should use the format provided in the ```datepicker-popup``` attribute for both ```min-date``` and ```max-date``` and default to the US style only when a custom format isn't provided.

**Comment by karianna** [comment]
Pretty sure this is a duplicate - have you tried against master?

**Comment by rvanbaalen** [comment]
@matt-major Please add a plunkr demonstrating your issue.

**Comment by matt-major** [comment]
@rafbgarcia sure, http://plnkr.co/edit/hxEiaVDvGyRheOV6VzCA?p=preview

As you can see with this demo, I'm passing in the min-date of 05/04/2015, and the data-datepicker-popup format as "dd/MM/yyyy" as this date is in UK format.

The directive however just creates a new Date from 05/04/2015 with no localization/formatting which results in May 4th rather than April 5th.

**Comment by stevecavanagh** [comment]
My PR #3606 will cover this one.  It considers the format when parsing the min-date and max-date.
https://github.com/stevecavanagh/bootstrap/blob/fix(datepicker)MinMaxInputValidation/src/datepicker/datepicker.js#L601

**Comment by wesleycho** [comment]
With the enforcement of min-date/max-date using date objects, we will not be supporting string formats, so closing.
