### ISSUE TITLE
Add strict date parse mode to datepicker

### ISSUE THREAD

**Issue by egaga** [angular-ui/bootstrap#3571]
Inside parseDate(viewValue):
          var date = dateParser.parse(viewValue, dateFormat) || new Date(viewValue);

There should be a configuration option that if dateParser.parse returns undefined, then the value is invalid. 
One reason for strict parsing is that if the dateFormat is 'dd.MM.yyyy', then "1.12.2015" is interpreted as 12.1.2015! (month and day are otherway around). This results in subtly changed data or incorrect user input.

**Comment by cgwyllie** [comment]
+1
