### ISSUE TITLE
Detached elements on $modal close

### ISSUE THREAD

**Issue by viveleroi** [angular-ui/bootstrap#3575]
Using angular 1.3.15, also reproduced with 1.2.28, and angular-bootstrap 0.12.1 - 2015-02-20

When closing a modal, DOM elements are left detached and in our case the issue impacts rendering next time the modal is opened. I have a `ui-grid` inside the modal and if someone opens the modal a second time, the ui-grid code doesn't have the proper sizing information and does not render correctly.

Looking at the heap snapshot I see a ton of detached DOM elements which all belong to the $modal previously opened:

http://puu.sh/hm3Bo/305956b7c3.png

This issue was partly discussed in #1491 but I'm not clear on what was fixed.

Reloading the entire page clears the memory and everything works as expected. Using an auto-resizing method from `ui-grid` also works but that requires resize event listeners and that's a performance issue all on its own.

**Comment by icfantv** [comment]
Can you please create a bare bones plunker that reproduces the issue and link here?  Thanks.

**Comment by wesleycho** [comment]
I believe this is now fixed in `master` with some of the work that has been done with fixing stranded DOM elements.

Feel free to open a new issue with a reproduction if it is not.
