### ISSUE TITLE
popover with popupDelay is first visible to right then hops to bottom

### ISSUE THREAD

**Issue by majgis** [angular-ui/bootstrap#3577]
I'm seeing this issue in chrome but not in firefox.

Setting a popupDelay with a placement of top or bottom results in a visible hop for a popover.

Here is the [plunk](http://plnkr.co/edit/6J1f6z?p=preview).

**Comment by rvanbaalen** [comment]
You should be using the latest UI Bootstrap:

http://plnkr.co/edit/FkHhsf?p=preview

**Comment by majgis** [comment]
The latest on npm is v0.12.0.  Can you publish v0.12.1 to npm?

**Comment by rvanbaalen** [comment]
We currently don't officially support the npm channel release. However once we get back in touch with the owner about it, we'll publish npm installation instructions in the readme.

As for now, you can either manually build the latest version, get it from a cdn or use bower to install `0.12.1`
