### ISSUE TITLE
Nested accordion issue

### ISSUE THREAD

**Issue by Digambar14** [angular-ui/bootstrap#3579]
I want to create accordion with nested levels. The levels are created properly, but the last level contains list of subcategories which should get listed one by one on new line. But what happens in my case all sub categories gets listed in one line. I seen in console that all sub categories getting listed in one panel body, they should get separate class for each of the sub categories. I have created [plunker] (http://plnkr.co/edit/yWQxQN4Vh0XmLSQ8hV2P?p=preview) for same.

Please help, its very urgent.

Thanks in advance.

**Comment by Digambar14** [comment]
I need to repeat this div
```
 <div class="panel-body" ng-transclude>
 </div>
```

Please help...

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
