### ISSUE TITLE
Dynamically setting height for carousel (for enforcing a certain aspect ratio)

### ISSUE THREAD

**Issue by canebat** [angular-ui/bootstrap#3584]
Is there a way to force the carousel to use a certain aspect ratio? At the moment, the carousel adjusts its height to the height of the active image, so if i have images with varying heights, the carousel will cause the entire webpage to shrink/expand depending on what image is being rendered.

I've seen css solutions where people would add a fixed height, but this is a problem when viewing the images on varying screen sizes. For instance, setting `height: 500px` would show a lot of empty space on a smart phone screen, but may display fine for desktop browsers.

The only way I can think of to enforce a 16:9 aspect ratio is to do the height calculation myself. In jQuery it might be something like:

```
$(window).resize(function() {
  var new_height = (current_width * 9)/16;
  $(".carousel").height(new_height);
});
```

Is there an equivalent way of dynamically setting the height for an `angular-ui` carousel on a window resize event?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#need-help
