### ISSUE TITLE
How to use this with bower

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/bootstrap#3585]
There is no bower.json file. How can I get the latest version using bower?

**Comment by kavika-1** [comment]
Not in the main project, but there are instructions there, which also point you then to the separate repository for bower.  For convenience, here's the link to the instructions.

https://github.com/angular-ui/bootstrap#install-with-bower

**Comment by salarmehr** [comment]
Therere are three similar repository in bower:`angular-ui-bootstrap`, `ui-bootstrap` and `angular-bootstrap` . They are really confusing. What is the point in maintaining them?

**Comment by wesleycho** [comment]
There were two main ones, each pointing to different repositories - they are maintained automatically once a new version has been tagged.

I suspect that `angular-ui-bootstrap` was registered by someone else, although I'm not finding it on bower anymore.

Anyhow, the instructions for usage is [here](https://github.com/angular-ui/bootstrap#install-with-bower).
