### ISSUE TITLE
The alert scope issue in FAQ seems to be resolved -- no need to mention it anymore

### ISSUE THREAD

**Issue by dmitriz** [angular-ui/bootstrap#3586]
It seems now `alert` works with `ng-hide/ng-show`:

http://plnkr.co/edit/PTF3fli73qNVT82AzT7r?p=preview

So no need to [mention it in the FAQ](https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input-elements-stop-working-when-i-place-a-tooltip--popover-on-it)

**Comment by wesleycho** [comment]
I removed it from the wiki, which should resolve this: https://github.com/angular-ui/bootstrap/wiki/FAQ

Thanks for the catch!
