### ISSUE TITLE
inject $modalInstance into a directive controller

### ISSUE THREAD

**Issue by blackotruck** [angular-ui/bootstrap#3592]
hello, i'm using a lot of modals on a project and for each type of modal i have to add a $scope.cancel() function, to close said modal, this is thedious an repetitive, so im trying to implement a directive that takes care of this, this is the code 

```
angular
  .module('close-modal',[
  	'ui.bootstrap'
	])
  .directive('closeModal', closeModal)

  function closeModal() {
	  var directive = {
	    restrict: 'EA',
	    replace:true,
	    template: '<button class="close-modal-btn"><i class="fa fa-remove"></i></button>',
	    controller: closeModalController
	  };
	  return directive;
	};

	closeModalController.$inject = ['$element', '$modalInstance'];
	function closeModalController ($element, $modalInstance) {
		$element.bind('click', close);
		function close(){
			$modalInstance.dismiss('cancel');
		};
	};
```

The issue here is that i'm getting a ``` Error: [$injector:unpr] Unknown provider: $modalInstanceProvider <- $modalInstance``` when i open the modal, what could be the cause of this and how could i fix it?

**Comment by NicolasKovalsky** [comment]
From modal's documentation: 

In addition the scope associated with modal's content is augmented with 2 methods:
$close(result)
$dismiss(reason)

**Comment by blackotruck** [comment]
Thanks for the answer, but even when that works is not what i want, as im using controllerAs so i still need to add ``` vm.cancel = $scope.$dismiss; ``` on the controller and ```<button class="close-modal-btn" ng-click="vm.cancel()"><i class="fa fa-remove"></i></button>"``` inside each modal tremplate, when i want to be able to use a directive like ```<close-modal></close-modal>``` that takes care of this

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap/blob/master/README.md#need-help
