### ISSUE TITLE
Horizontally collapse support

### ISSUE THREAD

**Issue by merlosy** [angular-ui/bootstrap#3593]
I noticed Bootstrap added horizontal collapse support by adding the class `width` to the existing `collapse`, starting with v3.0.
Is there a way to do the same with Angular UI Bootstrap?

I found a post on stackoverflow: http://stackoverflow.com/questions/22654933/angularjs-bootstrap-collapse-horizontaly
The idea was to copy-paste the directive to make a custom one, and changing the direction...
Also found this one that suggest to upgrade the css : http://stackoverflow.com/questions/12498476/twitter-bootstrap-collapse-plugin-direction

It could be great to have this `width`class working!

Thanks,

**Comment by plong0** [comment]
I have modified the collapse directive and submitted PR #3995 

I am also going to see about implementing a new ng-collapse directive that would give more options for collapse animations (ex. collapse from a specific corner)
