### ISSUE TITLE
Need bootstrap tab focus code

### ISSUE THREAD

**Issue by soundar84** [angular-ui/bootstrap#3598]
HI,
        I have created three bootstrap tabs in my application. This three tabs i have checked required field validations. when i click save button if i missed out any value means that particular tab want to focus.
Please send the sample code for this.

Thanks,

**Comment by rvanbaalen** [comment]
You can ask questions on StackOverflow

https://github.com/angular-ui/bootstrap/blob/master/README.md#need-help
