### ISSUE TITLE
AngularJS Git Commit Message Conventions

### ISSUE THREAD

**Issue by dmitriz** [angular-ui/bootstrap#3602]
Just found this great Guide of Angular team (sorry to spam those in the know ;-),
would really add to the contributing Guide in my view:

https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.4a9jrkze4u4a

**Comment by pkozlowski-opensource** [comment]
Right, we should add it to https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md

But I would rather link to https://github.com/ajoslin/conventional-changelog/blob/master/CONVENTIONS.md
