### ISSUE TITLE
Boostrap ui carousel empty

### ISSUE THREAD

**Issue by NoiZeR355** [angular-ui/bootstrap#3603]
Hello,

I have some strange issue. I use an carousel from bootstrap ui in a modal box from bootstrap. At the beginning is init the images for the carousel. Then i click on a button to show the modal box. This time they appear correctly. But then i reinit the carouseldata (Switch to other data) and open the carousel again and then he is empty. Is there an possible solution for this?

Here you can a example of it: http://plnkr.co/edit/YASfl9nF0cxqlytFjjI0?p=preview

Click first on click me and then you see the modal box. Close the modal box and switch from data and open it again.

**Comment by rvanbaalen** [comment]
This sounds like a perfect question for StackOverflow:

https://github.com/angular-ui/bootstrap#need-help

**Comment by NoiZeR355** [comment]
I did it but there doesn't know the solution

**Comment by rvanbaalen** [comment]
Sorry but that doesnt turn the issue tracker into a Q&A.
