### ISSUE TITLE
[typeahead] Do not respond to pressing the space bar

### ISSUE THREAD

**Issue by ivaaaan** [angular-ui/bootstrap#3605]
When I press the space bar - the list is not updated, and is only updated when you press the other keys. how can I fix it? I could not find this point in the source code

**Comment by rvanbaalen** [comment]
What do you mean by 'the list is not updated'? You mean it doesn't open when you have only a spacebar as an input?

**Comment by ivaaaan** [comment]
Yes, I mean it

**Comment by rvanbaalen** [comment]
Please provide a plunkr demonstrating this issue.

**Comment by ivaaaan** [comment]
@rvanbaalen please go to royaltyfreemusic.com and open console. Start typing a 'Music' and press space. when you press space typeahead not updated

**Comment by karianna** [comment]
@ivaaaan We really need a plunkr which is a short and sharp code sample.

**Comment by pkozlowski-opensource** [comment]
I think it is just default behaviour of Angular's ngModel that trims inputs by default: https://docs.angularjs.org/api/ng/input/input%5Btext%5D

From the doc on ngTrim:

> If set to false Angular will not automatically trim the input. This parameter is ignored for input[type=password] controls, which will never trim the input.
>
> (default: true)

But hard to tell for sure without a plunk. @ivaaaan I'm afraid that no one has free cycles to debug entire apps. If you need help please take some time to isolate the issue.

**Comment by rvanbaalen** [comment]
Just like @karianna said; we ask for a plunk for a reason. Provide a plunkr that reproduces your problem and I'll be glad to take a look.

But even before that, this smells like basic AngularJS model logic. Spaces get trimmed from the model.

**Comment by wesleycho** [comment]
As far as I can see based on what is said, it looks like @pkozlowski-opensource provided a workaround for this issue provided by Angular itself - if this is still an issue, please provide a reproduction via [Plunker](http://plnkr.co/) in a new issue.
