### ISSUE TITLE
$watch class event not working properly with collapse directive

### ISSUE THREAD

**Issue by je3f0o** [angular-ui/bootstrap#3608]
$watch('class') event not working properly with collapse directive. I need to rerender my custom scrollbar after collapsed or opened. But my $watch('class') event didn't work properly after I updated ui-bootstrap 0.13. I think I found a bug inside collapse directive. I added a line before closing bracket in expandDone(), collapseDone() functions.
```
scope.$digest()
```
It fixed my problem.

**Comment by rvanbaalen** [comment]
Please provide a plunkr and we'll be able to take a look at your problem.

**Comment by je3f0o** [comment]
I provided 
[Plunker](http://plnkr.co/edit/lDpcPjsKCLXLQ3EsbanB?p=preview)

**Comment by wesleycho** [comment]
The class changing is due to ngAnimate - is there any reason why you are trying to observe the class changes instead of using the `is-open` attribute binding?

**Comment by wesleycho** [comment]
Closing due to lack of response.
