### ISSUE TITLE
Carousel dont work when opened 2nd time

### ISSUE THREAD

**Issue by sniegoman** [angular-ui/bootstrap#3610]
I'm using angular-ui bootstrap carousel in my application. I have list of comments, each might contain 1 or more photos. What I want to achive is when user clicks at photo new modal opens with carousel of all pictures.

At first I have encountered simillar issue as: https://github.com/angular-ui/bootstrap/issues/1350 and directive provided by whitehat101 solved that.

But now I'm struggling with issue where re-opening another set of images causes carousel to stop working - first photo appears but user cannot use navigate buttons since it has wrong classes set (item ng-isolate-scope prev right). Using bullets to change photo works fine and after that carousel starts working normally until another reopening.

I have tried manually setting active flag: 

    if ( $scope.slides[0] ) {
             $scope.slides[0].active=true;
    }

But it seems like there is a problem with directive that turns off animations and my classes look like:
item ng-isolate-scope prev right active, there is no photo at all - it is on the right of active panel.

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#need-help
