### ISSUE TITLE
Issue #3167 still present if using `tooltip-popup-delay`

### ISSUE THREAD

**Issue by ntrifunovic** [angular-ui/bootstrap#3611]
Issue #3167, fixed in 87a3607632cae03ead57b377bb91ca27610e7730, is still present if using  `tooltip-popup-delay` with the tooltip.

**Explanation:** The tooltip is opened after the check is made to see if the tooltip is opened, when the button becomes disabled. This will lead to the same issue as described in #3167 .

**Comment by rvanbaalen** [comment]
Updated plunkr: http://plnkr.co/edit/AUKz0kVzwMwlzZJDiHsr

**Comment by rvanbaalen** [comment]
@ntrifunovic Can you confirm your issue is fixed in my plunkr?

http://plnkr.co/edit/AUKz0kVzwMwlzZJDiHsr?p=preview

I'll submit a PR for this if you confirm it's fixed.

**Comment by ntrifunovic** [comment]
Yes.

              if (popupTimeout && val) {
                  $timeout.cancel(popupTimeout);
              }

That seams to do the trick :smiley:

**Comment by rvanbaalen** [comment]
Allright ill squeeze it in soon. Ill close this automatically when the PR lands.
