### ISSUE TITLE
Dropdown doesn't work with anchor tags inside ul>li elements

### ISSUE THREAD

**Issue by SiddharthMantri** [angular-ui/bootstrap#3613]
I have the following code snippet

    <a class="dropdown" dropdown>
    <button type="button" class="navbar-toggle settings-btn dropdown-toggle" dropdown-toggle>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <ul class="dropdown-menu setting-dropdown">
        <li>
            <a ui-sref="profile">
					    				My Profile
					    			</a>
        </li>
        <li ng-click="logout()">
            Logout
        </li>
    </ul>
    </a>

Doing this doesn't open the dropdown. However, if I remove the anchor tags, the dropdown works perfectly. How do I fix this?

**Comment by rvanbaalen** [comment]
Please add a plunkr reproducing this problem.

**Comment by SiddharthMantri** [comment]
@rvanbaalen Hey, I've added the plnkr here with the same behavior:

http://plnkr.co/edit/gd1WcXezs3Vld0v6vPYS

**Comment by wesleycho** [comment]
Is there any reason you are wrapping the button in an anchor tag? This seems like an unnecessary element and a poor choice - you should use one or the other.

**Comment by pkozlowski-opensource** [comment]
Having `<button>` inside `<a>` isn't valid HTML5: http://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5

**Comment by pkozlowski-opensource** [comment]
IMO we should close this one, as we are clearly dealing with invalid HTML here and browsers are free to change / ignore this markup as pleased.

**Comment by robeverett** [comment]
Could anyone help. I can't post on uib-dropdown as it appears that this component is no longer supported.

I cannot get the html select element to play nicely with uibdropdown.

`<div class="btn-group" uib-dropdown>
                    <button class="btn btn-default" aria-haspopup="true" aria-expanded="false" uib-dropdown-toggle>
                        <span class="caret"></span>
                    </button>
                    <select ng-options="e for e in vm.plannedEmployees track by e" multiple="multiple" ng-model="selectedEmployee" ng-change="vm.employeeSelectClick(selectedEmployee)">
                    </select>               
                </div>`

All that happens is my list of items is displayed in an already open state and the button displays but does nothing.
I'm using AngularJS version 1.4.9, nodejs and express.
