### ISSUE TITLE
allow for more control of heading text in tabs

### ISSUE THREAD

**Issue by phamdt** [angular-ui/bootstrap#3616]
for example, i need bootstrap badges as part of the tabs which requires that i'm able to add scope variables and html into the heading property.

**Comment by rvanbaalen** [comment]
You can easily replace the templates with your own templates to extend functionality and/or change layout. 

If that's not enough, you an always submit a PR that contains this new feature and we'll be happy to review it.

**Comment by phamdt** [comment]
i'm not sure i know what you mean when you mention replacing templates. could you please elaborate?

**Comment by rvanbaalen** [comment]
Google search result: http://stackoverflow.com/questions/17660947/can-you-override-specific-templates-in-angularui-bootstrap
