### ISSUE TITLE
0.13.0 modal dialog not closing in angular 1.3.15

### ISSUE THREAD

**Issue by blkeagl** [angular-ui/bootstrap#3624]
This is a bug in using the combination of angular 1.3.15 and ui-bootstrap 0.13.0. 

The modal dialog does not actually close even though the triggered code executes with apparent error messages. While I can work around this by using $modalInstance in my own code instead of the local instance variable returned by $modal.open(), some of the libraries I am using via bower are using this local variable handle which used to work in prior releases.

See the attached plunkr for an example: http://plnkr.co/edit/bQbbkuustf0H4iBOGrG6?p=preview

**Comment by rvanbaalen** [comment]
Seems to be going wrong with your `var testScope = $scope.new();` implementation which you're passing to the modal options.

When I use the methods provided by the modal itself, everything seems to be working OK, or am I missing something?

http://plnkr.co/edit/1cFGn4SnPw1wt89acQyP?p=preview

**Comment by blkeagl** [comment]
This seems to be related to manually calling $new and $destroy for creating and cleaning up scopes in the code. If these are deferred until later, this issue seems to not occur. I fixed the 3rd party library to do this a different way (using $dismiss()) and sent them a bug as well, so I am not blocked, but in terms of behavior, it looks like this is some type of animate bug because the dialog does not get removed.

Tarik

**Comment by rvanbaalen** [comment]
Also, take a look a t this:

https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L422

The modal already creates a scope of its own. So basically it will create a new scope ON your new scope which probably causes the modal not to fire the methods you're calling on your new scope.

Take a look at the documentation page on how to use the scope option.

**Comment by blkeagl** [comment]
Makes sense, thank you. I will update the bug report on the library I’m using to change this there.

Tarik

**Comment by wawyed** [comment]
Hmm, I've just upgraded to 0.13.0 and noticed that my modals don't seem to be closing anymore. I've also create my own scopes since I have a service to extend $modal functionality and allow the consumers of my service to pass custom properties to the newly created $scope.

How do you suggest that I get around this issue without having to change the implementation to use resolve blocks only?

**Comment by karianna** [comment]
@wawyed separate issue which we're looking at

**Comment by 311chaos** [comment]
@karianna  - Is there a separate issue # for this? I am not sure which issue I am seeing. Basically, I upgraded to 0.13.0 and to Angular 1.3 and my modals no longer close. From this thread it seems to be related to passing in a scope?

```javascript    
openChangeAssignmentModal = function () {
      $modal.open({
        templateUrl: 'template.html',
        controller: ChangeAssignmentModalInstanceCtrl,
        backdrop: 'static',
        scope: $scope
      });```

**Comment by RobJacobs** [comment]
@311chaos Just want to make sure you realize, with backdrop set to 'static': backdrop is present but modal window is not closed when clicking outside of the modal window.

**Comment by 311chaos** [comment]
@RobJacobs - Thanks, this is an application that I have only recently started working on. I am guessing that was the intended behavior. My issue is that the close functions do not close the modal.

```javascript
$modalInstance.dismiss('cancel');
```

or

```javascript
$modalInstance.close();
```

**Comment by adamdva** [comment]
We are using ui-bootstrap 0.13.0 and using $modal also. Just tried upgrading to angular 1.4.0 and now see this issue. The modal appears to close, but the element is still there. We are using backdrop static, so the page is then unresponsive, and the divs are still found when using the developer element explorer.

**Comment by tomtwo** [comment]
Also seeing this issue on ui-bootstrap 0.13.0 & angular 1.4.0

**Comment by jberk** [comment]
+1 
same issue here.  If I set ```animation: false``` the modal does disappear.  If I use animations though, once the modal-header clears, the animation stops and it just sort of "hangs" there
angular 1.4.1 and ui 0.13.0

**Comment by jehoshua02** [comment]
For anyone still experiencing this issue: Are you overriding the modal template?

@311chaos and I discovered we were. We compared the default angular-bootstrap modal template with our own template.

__Our Template__

```javascript
    $templateCache.put('template/modal/window.html',
        '<div tabindex="-1" class="modal {{ windowClass }}" ng-class="{in: animate}" ng-style="{\'z-index\': 1050 + index*10, display: \'block\'}" ng-click="close($event)">\n' +
        '    <div class="modal-dialog {{ $parent.$parent.customClasses }}"><div class="modal-content" data-ng-transclude></div></div>\n' +
        '</div>');
```

__Angular Bootstrap Default Template__
```javascript
  $templateCache.put("template/modal/window.html",
    "<div modal-render=\"{{$isRendered}}\" tabindex=\"-1\" role=\"dialog\" class=\"modal\"\n" +
    "    modal-animation-class=\"fade\"\n" +
    "	ng-class=\"{in: animate}\" ng-style=\"{'z-index': 1050 + index*10, display: 'block'}\" ng-click=\"close($event)\">\n" +
    "    <div class=\"modal-dialog\" ng-class=\"size ? 'modal-' + size : ''\"><div class=\"modal-content\" modal-transclude></div></div>\n" +
    "</div>\n" +
    "");
```

I know it looks mucky, but we started moving one attribute over to our template one at a time. It so happens the first attribute we moved over fixed it: `modal-render=\"{{$isRendered}}\"`.

So if you are overriding the modal template, perhaps you need to update it to match the default.

BTW: does anyone in the Angular community know what [semver](http://semver.org/) is?

**Comment by jberk** [comment]
Semantic versioning

**Comment by jehoshua02** [comment]
@jberk It's a beautiful thing, but it doesn't seem like Google and Twitter follow it perfectly.

**Comment by moich4no** [comment]
I'm experiencing the same problem, the modals were working as supposed to, but after a "bower update" (angular went from 1.3.16 to 1.4.1 and angular-bootstrap from 0.12.1 to 0.13.0) modals doesn't "close" anymore. 

Quotes on close because when I click on the close button (or outside a non "static" modal for that matter) the modal disappears from the view (but not from the DOM) and the backdrop stills showing, so it is impossible to interact with the page.

Any thoughts?

**Comment by 311chaos** [comment]
@moich4no - Angular 1.4.x is not supported yet.

**Comment by moich4no** [comment]
@311chaos Sure... My mistake...
