### ISSUE TITLE
Force a re-render of a datepicker?

### ISSUE THREAD

**Issue by xingped** [angular-ui/bootstrap#3626]
So, I'm trying to sew together a date range picker of sorts from two datepickers and it's pretty close. I'm trying to disable dates on the start calendar based on the date selected on the end calendar and vice versa. The problem is that the start calendar only refreshes or re-renders when a selection is made on that calendar. So if I select a date on the end calendar, the start calendar will not re-run the disable-date function and re-render until I pick a date on the start calendar again.

Does anyone know a way to force a re-render of a calendar or make a direct call to the supplied disable-date or custom-class functions?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by xingped** [comment]
No one wants to answer the question there and I'm ignored/lost in the sea of comments on IRC (surprise surprise!): http://stackoverflow.com/questions/30080708/ui-bootstrap-datepicker-force-a-re-render-of-a-datepicker

**Comment by rvanbaalen** [comment]
Its not about 'not wanting to answer'. Its about using the issue tracker for issues instead of implementation questions. 

Thanks for referencing the SO here for future visitors of this issue.
