### ISSUE TITLE
tooltip-html, $sce and ng-repeat

### ISSUE THREAD

**Issue by starf** [angular-ui/bootstrap#3628]
trying to switch from tooltip-html-unsafe to tooltip-html

in the example, the tooltip-html content is provided in the controller as 
```
$scope.htmlTooltip = $sce.trustAsHtml('I\'ve been made <b>bold</b>!')
```
is there a proper solution for when the content is inside an ng-repeat?
simply switching to tooltip-html produces a $parse error

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by starf** [comment]
https://stackoverflow.com/questions/30072924/ui-bootstrap-0-13-how-to-use-tooltip-html-inside-an-ng-repeat

I had put it here because it's directly related to the new version.
