### ISSUE TITLE
v0.13: TypeError: Cannot read property 'initDate' of undefined

### ISSUE THREAD

**Issue by johntmyers** [angular-ui/bootstrap#3631]
This error shows up in the console even if ng-model and init-date are both present and given date objects. 

Has anyone else had this problem?

**Comment by johntmyers** [comment]
This is because init-date is expected to be a member of datepickerOptions, so if you pass something in via datepicker-options and init-date is not set as a member of that object, you'll get this error.

The docs do not explain this.

**Comment by rvanbaalen** [comment]
Thanks for letting know. Feel free to submit a PR to fix this.

**Comment by hmillet** [comment]
Same error in my console.
But I don't agree with the analyse.
In my app, it's seems to depends of the context. On my "big" page, I've got about 10 datepicker, all with the same html, attributes and options. Some works, some does not.

My option's variable is OK (```attrs.datepickerOptions``` return the correct value) , but the eval return sometimes "undefined" (line 1522).
```js
      if ( attrs.datepickerOptions ) {
        var options = scope.$parent.$eval(attrs.datepickerOptions);
```

I can see that the datepickers that does not works are inside an ngRepeat directive. Maybe a start for investigation...

**Comment by hmillet** [comment]
As for me, this error message was meaning that my ```attrs.datepickerOptions``` object was undefined.

In fact, it was not still setted when the datepicker directive was running. 

The Bug was mine, the error message not very clear ...

**Comment by bridges23** [comment]
Hi there,

I am not sure that I understand - so maybe someone is able to comment whether there is a workaround for the issue? I'd like to use the datepicker but JS always crashes with that type error.... 

Thank you so much for any hint.
Steffen

**Comment by hmillet** [comment]
@bridges23 : as far as I am concerned, there is no issue. I've got this message when my var `datepicker.birthdate.options` was undefined when the following input render :

```html
<input type="text" name="birthdate" datepicker-popup="{{datepicker.birthdate.format}}" is-open="datepicker.birthdate.opened" datepicker-options="datepicker.birthdate.options" ng-model="birthdate" class="form-control" />
```

When I finally set correctly this variable, all was fine

**Comment by bridges23** [comment]
@hmillet : Thanks for this. I think the question is rather how to set initDate as this is not working for me: 

My piece of code:

  $scope.dateOptions = {
            formatYear: 'yy',
            startingDay: 1,
            initDate: new Date('01-01-1900')
        };

Your help is really appreciated

**Comment by bridges23** [comment]
Or the right question would be: why does it return 'undefined' The $scope.dateOptions is declared in my controller and I cannot guess why the problem turns up...

**Comment by hmillet** [comment]
In a simple case, there is no reason for the variable to be undefined. My case was not simple, yours seems to be.

My options var is :

```js
         this.options     = {
           formatYear: 'yy',
           startingDay: 1,
           showWeeks: false
           initDate: null
         };
```

I can't see any problem on yours...

Maybe can you make a plunkr or equivalent that demonstrate your problem?

**Comment by bridges23** [comment]
@hmillet: Thank you so much for your reply. In fact, it was a very silly mistake and it works now. have a great day!!!

**Comment by basco-johnkevin** [comment]
We're getting the same error after we upgraded to version 0.13.

**Comment by basco-johnkevin** [comment]
What's the workaround for this issue?

**Comment by hmillet** [comment]
@basco-johnkevin : as far as I am concerned, this error message appear only when your options attribute `datepicker-options`is not set with a correct value. For me, this attribute was set with an undefined variable, because this variable was not still initialized

**Comment by punknroll** [comment]
I had the same issue using datepicker inside another directive as my options variable was not interpreted as a variable. This fixed it for me:
datepicker-options="{{dateOptions}}"

**Comment by basco-johnkevin** [comment]
Using the controllerAs syntax doesn't work: `vm.dateOptions` 

using `$scope.dateOptions` works though.

**Comment by tpoljones79** [comment]
Getting the same as basco-johnkevin.

**Comment by kristw** [comment]
punknroll's solution works for me

**Comment by nekcih** [comment]
Not sure if it's related but I'm getting this in Chrome...
`Cannot set property 'date' of undefined`

**Comment by nekcih** [comment]
My bad. I needed to upgrade angular from 1.2.x to 1.4.2. It's working now.

**Comment by randykittinger** [comment]
punknroll's solution works for me as well!

**Comment by wesleycho** [comment]
This should now be fixed in `master`.
