### ISSUE TITLE
Update NPM registry to 0.13.0

### ISSUE THREAD

**Issue by mchlbrnd** [angular-ui/bootstrap#3632]
0.12.0 => 0.13.0 :)

**Comment by rvanbaalen** [comment]
@Foxandxss ?

**Comment by hiebj** [comment]
+1

**Comment by rvanbaalen** [comment]
No need to +1 this. We are on it. It's just not an automated process and thus it takes some (spare) time to update.

**Comment by scottohara** [comment]
Just out of curiosity, what is the relationship between the npm packages:

  - `angular-ui-bootstrap` (points to the `angular-ui/bootstrap-bower` repo); and
  - `angular-bootstrap` (points to *this* repo)

Clearly the former repo (`angular-ui/bootstrap-bower`) is for bower's `angular-bootstrap` and `angular-ui-bootstrap-bower` packages (why there are two **identical** bower packages with different names, I'm not sure....but that's beside the point).

Specifically:

  1. what purpose does the `angular-ui-bootstrap` *npm* package serve?
  2. why is the latest `angular-bootstrap` npm package version **0.12.0**; while the latest `angular-ui-bootstrap` npm package is **0.12.1**?  Why wasn't `angular-bootstrap` ever bumped 0.12.1?

Its all just a bit confusing for anyone wanting to install via npm, especially given that `package.json` file in this repo specifies a package name of `angular-ui-bootstrap`.  Shouldn't it be `angular-bootstrap` to match the npm registry?

I'm sure there valid reasons for all of this. Its just not clear to me what those reasons are  (perhaps some details in the README, regarding the npm install/publish process, might be useful here?)

**Comment by Foxandxss** [comment]
@scottohara Neither of those two packages are made by us. Both packages were done by third party users.

I got handle into the `angular-boostrap` one which points to this repo, but we were thinking about creating a new repository to hold the `npm` files to match `bootstrap-bower` but that is still under discussion.

So the **TL;DR** here is that none of those is from us and there is no official way to install via npm yet.

**Comment by scottohara** [comment]
Ah, I see...thanks for the explanation.

**Comment by rnicholus** [comment]
It doesn't seem like a new repo is necessary for publishing to npm, unless I'm missing something. To ensure only relevant binaries/source are published, you should be able to construct a build task that creates a dist directory with a copy of the package.json. Then change to the dist directory and `npm publish`.

**Comment by kevintechie** [comment]
Until the angular-bootstrap npm package gets updated you can use the angular-bootstrap-npm package.

**Comment by whroman** [comment]
Thanks @kevintechie

**Comment by alexey-shaposhnikov** [comment]
![2015-06-30 18 55 08](https://cloud.githubusercontent.com/assets/2097562/8431185/31239604-1f51-11e5-8342-a6fabdd10896.png)
![facepalm5](https://cloud.githubusercontent.com/assets/2097562/8431020/c9764d72-1f4f-11e5-9423-d814e2d6313c.jpg)
https://www.npmjs.com/package/angular-bootstrap

**Comment by madeleneallvin** [comment]
npm is still not updated to 0.13.0. Could you please speed up this process. It has been two months since you said "We are on it"

**Comment by Foxandxss** [comment]
@madeleneallvin We know, but we lack the manpower. This is a gigantic project with hundred of issues and we do it for free, so sometimes it is hard to find time for it.

On the other hand, there are other issues we have to fix as well.

**Comment by Foxandxss** [comment]
Done.

**Comment by madeleneallvin** [comment]
@Foxandxss  Thank you. Much appreciated

**Comment by rnicholus** [comment]
Not sure why this is closed. npm for angular-bootstrap is still at 0.12.0. Nothing was updated.

**Comment by Foxandxss** [comment]
@rnicholus wrong package. It is `angular-ui-bootstrap`.

**Comment by rnicholus** [comment]
Oops. Perhaps @leon could remove angular-bootstrap then, to avoid confusion?

**Comment by Foxandxss** [comment]
That sounds like an idea.

**Comment by Foxandxss** [comment]
And... done :)
