### ISSUE TITLE
Documentation update request

### ISSUE THREAD

**Issue by icfantv** [angular-ui/bootstrap#3634]
Hey, just a low priority nit.  I'm getting a CSS warning saying tooltip-html-unsafe is deprecated - we should probably update the docs to indicate this and that we shouldn't use it.

**Comment by rvanbaalen** [comment]
Will take a look at it.

**Comment by icfantv** [comment]
Thanks.  No rush, clearly.

**Comment by icfantv** [comment]
While we're at it, we should update the documentation to include that the value of the tooltip-template needs to be quoted if it's just a string since the directive uses an = instead of an @ for the parameter values.  I just spent an hour trying to figure this one out.

**Comment by starf** [comment]
Thanks for the quote tip, was struggling with this.

**Comment by icfantv** [comment]
@karianna sorry, just saw your label.  can you please provide PR instructions?  i've never done one before and the contributing article doesn't seem to give steps.

**Comment by rvanbaalen** [comment]
Well we don't provide such information since there are plenty of resources out there that do. 1 simple google search let me do this page for you:

https://help.github.com/articles/creating-a-pull-request/

**Comment by rvanbaalen** [comment]
Nevermind the PR, I'll fix this now.

**Comment by rvanbaalen** [comment]
Next release, this will be fixed in the docs.
