### ISSUE TITLE
Jumpy scroll to input fields within a modal window in IOS

### ISSUE THREAD

**Issue by bkanuck** [angular-ui/bootstrap#3635]
I haven't been able to nail down the cause of this problem, but I believe it may be a bug. It's not new to 0.13, but I can say that this does not occur in a Bootstrap jQuery based modal window, only Angular-UI Bootstrap modals.  I created a Plunker to illustrate the problem by adding a simple form with input fields to the Plunker example for modals on the Angular-UI Bootstrap page.  The problem only occurs on IOS devices, so to recreate the problem, go to this Plunk on an iPhone or iPad, preview it and open the modal and click through the input fields.
http://plnkr.co/edit/1z7lk5

I would call it an IOS Safari bug, but in my testing it's specific to Angular-UI modals.

**Comment by rvanbaalen** [comment]
I can confirm the bug. But im not sure if its ours to fix. Will take a look at it. Any help is appreciated.

**Comment by HarrisRobin** [comment]
+1

**Comment by wesleycho** [comment]
I took a look based on current `master` [here](http://plnkr.co/edit/8YLaUt?p=info), but I don't think there is anything we can do about this - I believe this is likely a browser issue, and Chrome does not seem to behave much differently here on my laptop when tabbing through.

I am going to close this as something we cannot fix.

**Comment by yinanchuan** [comment]
Here is my fix:

`//$uibModal open for fixed IOS scroll bug after modal-open
        var userAgent = navigator.userAgent.toLowerCase();
        var isIOS = (userAgent.indexOf('iphone') != -1) || (userAgent.indexOf('ipad') != -1);
        var scrollTopPosition = 0;

        $rootScope.openModal = function(options){
            var modalInstance = $uibModal.open(options);

            if(isIOS){
                scrollTopPosition = $(document).scrollTop();
                $('body').addClass('modal-open-ios');

                modalInstance.result.then(function () {
                    $('body').removeClass('modal-open-ios');
                    $(document).scrollTop(scrollTopPosition);
                }, function(){
                    $('body').removeClass('modal-open-ios');
                    $(document).scrollTop(scrollTopPosition);
                });
            }

            return modalInstance;
        };`


`body.modal-open-ios{
        overflow: hidden;
        position: fixed;
        width: 100%;
    }`


child Controller open modal
`var modalInstance = $rootScope.openModal(modalOptions);

            modalInstance.result.then(function () {

            });`
