### ISSUE TITLE
[tooltip] tooltipService / event-based trigger

### ISSUE THREAD

**Issue by SoundLogic** [angular-ui/bootstrap#3638]
I know there's a similar issue [Issue 590: popover/tooltip | Support Programmatic Triggers](https://github.com/angular-ui/bootstrap/issues/590), but I think this scenario is a bit different as it is a bit more involved.

I have a case that requires functionality similar to the `$modal` dialog. I created a `tooltipService` that works much like the modal dialog, but uses the `$event.target`           
 
        $scope.toggleTooltip = function ($event, item) {
        
            var tooltipInstance = tooltipService.open({
                templateUrl: 'app/templates/foo-bar-tooltip.html',
                controller: 'fooBarCtrl',
                targetElement: $event.target,
                placement: 'left', // defaults to left if none provided, but prefer to be explicit
                resolve: {
                    fooText: function() {
                        return item.foo;
                    },
                    barText: function() {
                        return item.bar;
                    },
                    itemId: function() {
                        return item.id;
                    }
                }
            });

            tooltipInstance.result.then(
                function (result) {
                    var targetItem = _.first(_.filter($scope.vm.items, { id: result.itemId }));
                    targetItem.foo = result.foo;
                    targetItem.bar = result.bar;
                },
                function () {
                    $log.info('tooltip dismissed at: ' + new Date());
                });
                
        };
        
In the tooltipService code, I use the target like so (where `tooltipDomEl` is the compiled tooltip)

	var targetElement = angular.element(tooltip.targetElement);
	targetElement.after(tooltipDomEl);

I've created a fork and am working to integrate this into `0.13.1` (current code is based on `0.12.1`), but I want to check before I did this work if this would be useful to others and if anyone has any suggestions as to how I can improve this approach and/or if there's a better way of going about it?

**Comment by ermalmino** [comment]
+1

**Comment by SoundLogic** [comment]
80% of the way there on this one - had to set this aside for a bit, but picking it back up today. I was originally thinking of making this an extension of the tooltip, but given its nature is more like that of the modal dialog and the architecture of the tooltip is not very compatible with this approach, I've decided to create it as a separate control called the `tooltipDialog`.

**Comment by SoundLogic** [comment]
I've completed an initial pass on this - I decided to create a new control called `$popupDialog`. It is very similar to the `$modal` code. It's working great, but I found there can be an issue with an edge case (or maybe this is more common than an edge case?). One of my use cases is to show a preview of the popup dialog when the user mouses over a data point. If they don't click on that point, the dialog will close on mouse-out. Once they click on the point, we'll assume they want to edit the data and they have to explicitly dismiss the dialog or save their changes. The problem is that because of the asynchronous manner in which the dialog is created, the mouse-out event may occur before the `popoverDialogInstance` has been created. I've thought of a few ways I can resolve this issue, but was curious if there's already a pattern laid out for this somewhere in the ui-bootstrap library? I should have the code checked into my fork hopefully this week - working through some red tape ATM.

**Comment by shreedharshetty** [comment]
+1

**Comment by wesleycho** [comment]
I think this sounds reasonable, perhaps it's worthwhile opening a PR when you're ready so we can review the API signature and maybe identify some rough edges.

**Comment by wesleycho** [comment]
Thinking about this again, I am not sure we want to support this in the library proper - this would require a lot of tests, and we are trying to move towards an extendable over configuration philosophy in general, which this feature would do the reverse of.

**Comment by SoundLogic** [comment]
Yeah... Got held up anyways... Gave it my best shot :/
