### ISSUE TITLE
Dropdown on float:left appears on right instead of underneath

### ISSUE THREAD

**Issue by bgold0** [angular-ui/bootstrap#3641]
If i'm floating an element left that I want to be the toggle to be the toggle of the dropdown, the dropdown appears on the left side. I'm trying to get it to go to the bottom. Anyone have any suggestions?

    <span class="dropdown" dropdown on-toggle="toggled(open)">
		<a style="float:left" class="dropdown-toggle" dropdown-toggle>text</a>

		<ul class="dropdown-menu">
			<li ng-repeat="choice in items">
				<a href>{{choice}}</a>
			</li>
		</ul>
	</span>

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by bgold0** [comment]
I'm pretty sure this is an issue rather than me needing help. Twitter's bootstrap doesn't do this.

**Comment by RobJacobs** [comment]
@bgold0 It's hard to help you without a plunk to work with, but I would try using the pull-left and clear-fix classes instead of float: left inline.

**Comment by bgold0** [comment]
My apologies, here is a working plnkr. I tried to do the pull-left and the clearfix but it just moves to another line.

http://plnkr.co/edit/7naI9Eq9a5XaBv26BVnr
