### ISSUE TITLE
Popover popover-template doesn't work with template url string

### ISSUE THREAD

**Issue by metanav** [angular-ui/bootstrap#3642]
If I provide scope variable as a value to popover-template it works but if I provide a templateUrl string it does not work. Is this behaviour intended? If yes, why? Otherwise, it is a bug.

$scope.templateUrl = 'js/controllers/templates/profile.html';

```
<a popover-template="templateUrl">  (works)
<a popover-template="js/controllers/templates/profile.html"> (doesn't work)
```

I am using latest ui-bootstrap 0.13.0.

**Comment by chrisirhc** [comment]
Similar to ng-include:
```
<a popover-template="'js/controllers/templates/profile.html'"> (works)
```

**Comment by pkozlowski-opensource** [comment]
Yep, this is an expression, works as designed.

**Comment by umair-khanzada** [comment]
doesn't work in  my site

**Comment by navid-dada** [comment]
+1

**Comment by davidpiber** [comment]
This doesn't work fro me ui-grid 3.2.9, I get 404 from the server as it cannot locate the template, I have the template in a separate folder.

**Comment by sirisha96** [comment]
@davidpiber  I hv the same issue, did u find a solution?

**Comment by davidpiber** [comment]
We were having several issues with ui grid , so we changed to ag-grid.
