### ISSUE TITLE
datepicker 0.13.0 does not allow model updates after a parse error for certain dates when ng-model-options updateOn: blur is used

### ISSUE THREAD

**Issue by jongunnip** [angular-ui/bootstrap#3643]
Using 0.13.0 of datepicker with ng-model-options="{updateOn: 'blur'}"

When entering a date that causes a parse error (e.g. 'abc'), subsequently entering a 10-character 'mm/dd/yyyy' date (e.g. 01/01/2014) will not update the $modelValue.  

Entering an 8-character date (e.g. 1/1/2014) or selecting the datepicker in the calendar does update $modelValue.

[Plunkr](http://plnkr.co/edit/zY1DiPfEskLmNONddPJF?p=preview)

This seems related to [https://github.com/angular-ui/bootstrap/issues/3609], but I wasn't sure if it was the same issue.  As an aside, the $invalid flag isn't being set on parse errors.

Would be interested if anyone is aware of a workaround.

**Comment by wesleycho** [comment]
I believe this is now fixed in `master` since #3759 is merged - feel free to open a new issue if this is not the case.
