### ISSUE TITLE
Datepicker has trouble with some dates

### ISSUE THREAD

**Issue by realityking** [angular-ui/bootstrap#3644]
This might be related to #3617 and/or #3643.

JSBin: http://output.jsbin.com/pasiweruhe/2/

I have a date field set up with the German date format (`dd.MM.yyyy`). After clearing the field and entering a date where the day part is larger than 12, it will fail and the date will be `undefined`.

The issue seems to be, that the date parser has trouble creating a valid date input when the input is an invalid date input.

**Comment by karianna** [comment]
@realityking Is this with the latest 0.13.0 and can you provide a plunkr?

**Comment by realityking** [comment]
@karianna Yes, this is with 0.13.0. I've got a JSBin (http://output.jsbin.com/pasiweruhe/2/) or do you specifically need a plunkr?

**Comment by karianna** [comment]
@realityking That's fine, thanks!

**Comment by nethulap** [comment]
I have the same issue..any work around??

**Comment by natcohen** [comment]
Here is a plunker... http://plnkr.co/edit/Dd6FKcboWGlIKh6Dy9cv?p=preview

**Comment by realityking** [comment]
Cause is the following commit: 1a9e88fe9e6a078943273012429788e742f8ebbd

After reverting that one I still have the issue described in #3617

CC: @chrisirhc

**Comment by hmillet** [comment]
In fact, no need for a plunker, the same issue can be seen on the official example page of this project :-(
