### ISSUE TITLE
Dropdown auto-close outsideClick not working when used with append-to-body

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [angular-ui/bootstrap#3645]
Simple, when `append-to-body` is set, and `auto-close` is set to `outsideClick`, closing behaves like if it has the default value (`always'), I believe it's somewhat related to catching the "onclick" event attached to the wrong element.

Plunkr: http://embed.plnkr.co/WpARFC/preview

**Comment by rvanbaalen** [comment]
Can you please provide a plunkr so we can reproduce this issue and see what library versions you've used?

**Comment by Fire-Dragon-DoL** [comment]
@rvanbaalen Yes, give me a bit. I used the latest (I believe) version, 0.13.0, downloaded from the website (custom build) with templates integrated 5 minutes ago

**Comment by Fire-Dragon-DoL** [comment]
@rvanbaalen Here is the plunkr: http://embed.plnkr.co/WpARFC/preview

**Comment by Fire-Dragon-DoL** [comment]
I temporary solved this using a simple `ng-click` on the `dropdown-menu` item and the function has this code inside

```javascript
          $event.preventDefault()
          $event.stopPropagation()
          return false;
```
