### ISSUE TITLE
Carousel (ui.bootstrap.carousel) - No Slide Animation on Plunker

### ISSUE THREAD

**Issue by MishaTornes** [angular-ui/bootstrap#3648]
There is no slide animation in the Plunker for the  ui.bootstrap.carousel.

I was unable to figure it out in my own site.
Is it just missing a reference to a library ?

Does it means the demo code on ui.bootstrap is missing a config argument?

**Comment by sagidayan** [comment]
If you include ngAnimate as a dependency the animations will work.

note that ngAnimate is not included in the angular.js file. you need to include the angular-animate.js to your html.

**Comment by MishaTornes** [comment]
Adding the ngAnimate dependency resolved the issue.
It will be nice if the examples for each component (or plunker) included it's dependencies :) (if any)
My first assumption was ui.bootstrap element where self sufficient. 
Thanks for the quick follow up!

**Comment by sdhintGIT** [comment]
This is still not resolved, adding the ngAnimate to the plunkr, and adding the injection to the module, allows for one transition, then it freezes on the slide. I am getting the same behavior on my app after upgrading to resolve other issues in 12.1

http://plnkr.co/edit/PaJXc8n7HJ5XvtTh9c0T?p=preview

**Comment by abrahamgodoy** [comment]
I have the same problem but i wasnt able to fix it, can you put the example in plunker to see the order of dependencies and check my error. @MishaTornes

**Comment by MishaTornes** [comment]
I just did what @sagidayan sugested.
Note I'm using Angular 1.3.13 instead of .14 (since @sdhintGIT sugested prtoblems in 12.1)

Here, I modified the Plunker from the UI website : 
http://plnkr.co/edit/4MluOvr5AVc0qBKkyVpM?p=preview

**Comment by federicosintucci** [comment]
Hi guys,

seems like this issue is back in angular 1.4.x.
See attached Plunker http://plnkr.co/edit/zv1tcFJ0N6n1TT5PeTTo?p=info
