### ISSUE TITLE
Typeahead matches don't show cursor pointer

### ISSUE THREAD

**Issue by OzzieOrca** [angular-ui/bootstrap#3649]
When hovering over the typeahead matches, they work fine but the cursor is not a pointer (hand) but instead alternates between an arrow and a text select cursor (when hovering over text).

This could be fixed by changing `template/typeahead/typeahead-match.html` from
```
<a tabindex="-1" bind-html-unsafe="match.label | typeaheadHighlight:query"></a>
```
to
```
<a tabindex="-1" bind-html-unsafe="match.label | typeaheadHighlight:query" style="cursor: pointer"></a>
```

We could also add a CSS file to apply that style. Or add a blank href but that might cause other issues.

Do any of these seem like good approaches? I can submit a PR adding this if it seems like a good change.

**Comment by karianna** [comment]
@OzzieOrca I'd say the CSS approach is best, PR welcome!

**Comment by RobJacobs** [comment]
In the accordion-group template, heading element, the href attribute on the anchor tag is:

    href=\"javascript:void(0)\"

**Comment by pkozlowski-opensource** [comment]
> I'd say the CSS approach is best

Currently we don't have any CSS deliverable in this project and IMO we should keep it like this.

**Comment by karianna** [comment]
@pkozlowski-opensource & @OzzieOrca - I stand corrected!

**Comment by OzzieOrca** [comment]
So javascript:void(0) is the best option? I can submit a PR soon.
