### ISSUE TITLE
Datepicker reset question

### ISSUE THREAD

**Issue by JordanSinko** [angular-ui/bootstrap#3652]
Anywhere to default a certain date if the model is blank? For example, when I use the popup, I choose May 30, 2015. If I clear that date, it still shows that the selected date is May 30, 2015 in the popup. Anywhere to get it to show a certain date by default if a model is blank, for example today's date? I tried init-date and it doesnt seem to work the way I would like. Thanks!

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
