### ISSUE TITLE
Translate issue on modals

### ISSUE THREAD

**Issue by mndeveci** [angular-ui/bootstrap#3656]
Hi,

When i try to open a modal window, its template contains angular-translate, the translation texts are not translated, modal shows the translation keys only.

I think, wiring the translation text to a function in controller will fix the issue but why it is not working on a normal usage, any ideas?

Thanks a lot.

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
