### ISSUE TITLE
datepicker max-date does not work

### ISSUE THREAD

**Issue by shamoons** [angular-ui/bootstrap#3658]
My HTML
```
                            <div class="input-group input-group-sm input-group-date">
                                <input id="dob" name="dob" class="form-control required" required ng-model="model.patient.dob" placeholder="Required" datepicker-popup="MM/dd/yyyy" is-open="model.birthDateOpened" datepicker-options="dpOptions" />
                                <span class="input-group-btn">
                                    <button class="btn btn-default" data-ng-click="openBirthDate($event)"><i class="glyphicon glyphicon-calendar"></i></button>
                                </span>
                            </div>
```

My JavaScript
```
            $scope.dpOptions = {
                formatDay: 'd',
                showWeeks: false,
                maxDate: '05/01/2015', //moment().format('MM/DD/YYYY'),
                minDate: '01/01/1875',
                datepickerMode: 'year'
            },
```

This breaks both the min and the max. If I remove the max, then the min works fine. If I remove just the min, then the max is ignored.

This is with version 0.13

**Comment by rvanbaalen** [comment]
Provide a plunkr.

**Comment by CharlJKruger** [comment]
Im also having the same problem, the docs read 'min-date' but the directive reads, 'minDate'

Both dont work - plunker: http://plnkr.co/edit/tzPIcr3kdizlWr94pVDI?p=preview

**Comment by wesleycho** [comment]
This appears to be fixed in `master`, as can be seen [here](http://plnkr.co/edit/yUBOsAMtgkbEdlBNHuuM?p=preview).

Note that the first example will not work because browsers interpret `minDate` as `mindate` unless it is one of the special SVG attributes inside an SVG element.

**Comment by mkoutroupis** [comment]
Min Max Date still does n't work please check the example here:
http://plnkr.co/edit/y1DvReVwFxFTk1UVR1yJ
