### ISSUE TITLE
Modal-Footer too tall

### ISSUE THREAD

**Issue by Leon-O** [angular-ui/bootstrap#3660]
Hi, I'm using modal windows as a create/edit form, but for some reason the modal-footer gets taller than the modal-body.
http://plnkr.co/YCbGISumK555RCsw6BE3
![20150512-3](https://cloud.githubusercontent.com/assets/4379316/7602187/3d40d60a-f8ef-11e4-9dba-22ef7ce200d7.PNG)

I hope someone can give me nice solution to this.

**Comment by KillaBee1985** [comment]
@Leon-O Hello. .col- classes use float:left, so for expected behavior you should add .clearfix class to your <form> tag. It is not a bug of angular-ui.
