### ISSUE TITLE
"$animate:close" event is not triggering on modal close

### ISSUE THREAD

**Issue by salemdar** [angular-ui/bootstrap#3662]
On modal close, modal window fades, backdrop stays visible, but both of them stays in the body. I tracked down the issue till the 'domEl.one("$animate:close".....' line. I think the problem is with "$animate:close" event.

**Comment by maximumduncan** [comment]
I've just had the same issue - started happening when I upgraded from Angular 1.3 to 1.4-rc2. What version of angularjs are you using?

**Comment by salemdar** [comment]
I use 1.4.0-rc2, didn't try with 1.3.15. I downgraded ui-bootstrap instead of angular.

**Comment by RobJacobs** [comment]
This issue is been reported under #3633
