### ISSUE TITLE
How to get $element in modal's controller

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#3663]
How I can get `$element` in modal's controller?
This is modal's controller's func. I always get `Unknown provider: $elementProvider <- $element`
```
function mailPodgladCtrl($scope, $modalInstance, $element) {
        var vm = this;
});
```
I need modal element to get tag from a modal.

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
