### ISSUE TITLE
Typeahead inside a ui.grid (3.0)'s cell

### ISSUE THREAD

**Issue by AWRyder** [angular-ui/bootstrap#3664]
I've noticed that when I wrote a custom template for ui.grid's cellEdit in order to add typeahead, everything would show up as expected but when one of the typeahead suggestions was chosen, it wouldn't auto-complete. This only seems to happen if the edited template is the cell editing one. If instead we put the exact same template in the regular cell's (it becomes an <input> all the time instead of only when a cell edit is triggered), it works just fine. 

I've started making a plunkr for this, but could only make it work for the regular cell's template as the ui.grid.edit module doesn't seem to be loading (or I'm forgetting something trivial).

http://plnkr.co/edit/arTtfJ2DU52xTURf39W0

After debugging typeahead's onSelect code, it seems that due to some sort of weird scope used by ui.grid's cell edit, onSelect isn't even called. 

Edit: Note that in order to access the data in the controller's scope, I had to use the following in the typeahead directive as shown in the plunkr: "grid.appScope.". Which is why I think there might be a scope conflict as well when it comes to acessing the onSelect method.

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help
