### ISSUE TITLE
0.13.0 does not work with async loading

### ISSUE THREAD

**Issue by lapo-luchini** [angular-ui/bootstrap#3665]
I recently updated from 0.12.x to 0.13.0 and I have a few errors, the first I found is in the last line of both `ui-bootstrap.js` and `ui-bootstrap-tpls.js`: the function `angular.$$csp()` is called possibly before Angular itself is loaded. I fixed this wrapping it in a module `run` (and adding it to the dependencies in the first line):

    angular.module('ui.bootstrap.csp', []).run(function () {
      !angular.$$csp() && angular.element(document).find('head').prepend('<style type="text/css">.ng-animate.item:not(.left):not(.right){-webkit-transition:0s ease-in-out left;transition:0s ease-in-out left}</style>');
    });

I'd gladly produce a PR but I don't understand from which source code is that line built. I also noticed it's also present in `angular.js` so maybe it could be avoided altogether?

**Comment by rvanbaalen** [comment]
Please provide a plunkr reproducing this problem.

**Comment by lapo-luchini** [comment]
[Here goes the plunkr.](http://plnkr.co/edit/nP6i7JxJYaKVscn06oGE)

**Comment by rvanbaalen** [comment]
This seems like something @chrisirhc was involved with. Perhaps he can take a look.

**Comment by rvanbaalen** [comment]
Looking into it, this seems like a question suitable for StackOverflow. It's not actually a bug with this library, it's an issue you have when using this library in a certain manner that we don't support out of the box.

Indeed, one could expect UI Bootstrap to work in this situation and it would help if we implement a fix for it but basically this is an enhancement request instead of a bug.

**Comment by lapo-luchini** [comment]
AngularJS module system supports out-of-order loading by default (using the official async loader), this only happens because `angular.$$csp` is currently used in the global namespace instead of inside a module, wrapping it with a `module.run` should solve the problem as far as I can see. (of course, the code would be executed as soon as the module and all his dependencies is loaded, not as soon as it's singularly loaded, but I guess that's ok)
