### ISSUE TITLE
Breaking change in $tooltip service from 0.11.2 to 0.13.0?

### ISSUE THREAD

**Issue by icfantv** [angular-ui/bootstrap#3669]
I have the following tooltip directive that no longer works in 0.13.0 because the object returned by the $tooltip service function no longer has a compile function.  Am I missing something?  Is there a breaking change from 0.11.2 to 0.13.0?

The issue appears on the line `var parentLinkFn = compile(element, attrs);` because `compile` is undefined.
```javascript
.directive('myTooltip', [
  '$tooltip',
  '$timeout',
  function($tooltip, $timeout) {
    // Create a popover directive with the ui-bootstrap $tooltip service
    // Arg1: name of this directive
    // Arg2: prefix of configuration directives (tooltip-popup-delay, tooltip-placement)
    // Arg3: The DOM pseudo-event that triggers show/hide
    var tooltipDirective = $tooltip('myTooltip', 'myTooltip', 'showTrigger');
    var compile = angular.copy(tooltipDirective.compile);

    // register a custom compile function on our directive which decorates the stock compile fn
    tooltipDirective.compile = function customCompile(element, attrs) {
      // Invoke the parent compile function to receive the parent linkFn
      var parentLinkFn = compile(element, attrs);

      return function popLinkFn(scope, element, attrs) {

        function showHideTooltip(showHide) {
          $timeout(function() {
            element.triggerHandler(showHide ? 'showTrigger' : 'hideTrigger');
          });
        }

        // typeaheadPopup directive exposes the active index on the scope
        // Since the $tooltip directive uses isolate scope, we have to reference $parent
        scope.$watch(attrs.myTooltipShow, function(newval) {
          showHideTooltip(!!newval);
        });

        // Our logic is all set up.  Now invoke the parent link fn
        parentLinkFn(scope, element, attrs);
      };
    };

    return tooltipDirective;
  }])
```

**Comment by benjaminsuch** [comment]
It also says that tooltip-html-unsafe is depreciated, but there is no documentation how to use tooltip-html (you can't just use tooltip-html like tooltip-html-unsafe; it throws an error).

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by icfantv** [comment]
@rvanbaalen i'm a little confused, if this is not a breaking change or bug, can you please indicate thus rather than just posting a link that says how to get help?  otherwise, it comes off as a little flippant.  thanks.

**Comment by rvanbaalen** [comment]
The link I was referring to explains where you can ask questions regarding the library. As mich as Id want to help you out, this is an issue tracker to keep track of bugs. Not a forum to ask questions about all sorts of implementations. 

I would suggest asking your question on the IRC channel as some of the UI Bootstrap crew likes to hang around there and to be sure Ill tag @chrisirhc since I believe he worked on the part you mention.

**Comment by icfantv** [comment]
Cool, thanks.

**Comment by inkxe-karma** [comment]
tooltip="{{color}} <br>  {{checkCMYKData(side.cmykValue[$index])}} " not working please help

**Comment by icfantv** [comment]
@inkxe-karma, commenging on old/closed issues is a really good way for them to be missed or ignored.  Since nobody wants that (least of all you) I would strongly encourage you (per our project documentation) to post any support requests on StackOverflow or the like.

If you think you've found a bug, please feel free to follow our issue template when opening a new one making sure to search both open and closed existing issues to see if it's already been addressed.
