### ISSUE TITLE
documentation versioning - hard to tell what version features apply to

### ISSUE THREAD

**Issue by ktiedt** [angular-ui/bootstrap#3670]
Just spent way more time than was necessary trying to resolve why tooltip-class did not work in our application only to find out (via commit history here) that it was a brand new feature only in the latest release... 

After going back to the documentation I looked for indications of what version I might have been looking at and the only reference to the actual project version # was in the Download button at the top of the page. I know other projects have done it in the past  and it may not be the simplest thing, but being able to specify what version of documentation you are looking at would have been a huge boon to solving this in a more timely fashion. 

As per @Foxandxss here is a ticket to help track this issue

**Comment by rvanbaalen** [comment]
I feel your pain and understand the issue. However, a huge refactor session is required to do this the right way if I'm right.

**Comment by ktiedt** [comment]
It could be as simple as when publishing the docs, moving the existing to /docs/vXXX and letting the latest publication take /docs (granted I have not looked how how the docs generation currently works)

I am aware that projects that do this, typically start with that goal in mind.

A simple solution would just to tag features with their "added in" version number so no changes are really necessary code wise, just an extra property in comments

**Comment by piotrd** [comment]
Yesterday I had exactly the same problem (with `tooltip-class` not working in version older than 0.13.0 and not being able to quickly tell that by looking at the docs).

:+1: for creating "added in v. ..." badges.

Also, docs for Tooltips need updating: `tooltip-html-unsafe` is now deprecated and `tooltip-html` is a new, but undocumented option!

**Comment by Pickra** [comment]
Just had the same problem. Bootstrap has versioned docs, it would be great if they were supported here.

**Comment by wesleycho** [comment]
I think we are going to want to revamp our homepage - the UX could use some work to make it easier to get to the component of interest.

This would be a large amount of work though, so I cannot give an estimate when this can be done, especially with the large amount of issues/PRs being tackled with - more maintainers is a necessity for some of this work, as requested in #3997.
