### ISSUE TITLE
Popover template doesn't work with custom distribution

### ISSUE THREAD

**Issue by natcohen** [angular-ui/bootstrap#3671]
I tried to use popover-template with a custom build (everything except the modal) and I get the error (/template/popover/popover-template.html not found).

The full distribution works well... I guess it's just a problem in the way the build is downloaded.

PS I'm using the last release of course...

**Comment by rvanbaalen** [comment]
Please provide a plunkr with the exact custom build you made. Seems like you missed something.

**Comment by natcohen** [comment]
You're right! My bad...
