### ISSUE TITLE
<Alert> Colour Type ignored

### ISSUE THREAD

**Issue by seamuspc** [angular-ui/bootstrap#3672]
Do you know why when I specify the Alert tag with  type="success" 

the type is ignored and messages are always displayed in the warning colour?

**Comment by RobJacobs** [comment]
https://github.com/angular-ui/bootstrap/blob/master/README.md#need-help

https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

Closing pending more info.
