### ISSUE TITLE
Datepicker: after navigating within calendar, active day loses "active" class

### ISSUE THREAD

**Issue by Zion-ICS** [angular-ui/bootstrap#3673]
Minor bug, but annoying if you're trying to override datepicker styles.

Look at a datepicker in month view. I chose a month where the active date was today. Open the Chrome or Firefox inspector and note how the the current day on the calendar has a class called "active".
`<button type="button" style="width:100%;" class="btn btn-default btn-sm btn-info active"`

Navigate to a previous month, then navigate back.

If you look at the Firefox or Chrome inspector again and look at the day that's active, you'll see that it doesn't have the class "active" anymore.
`<button type="button" style="width:100%;" class="btn btn-default btn-sm btn-info"`

If you aren't overriding datepicker styles, you won't see a difference.
We're trying to customize the datepicker a bit, and we want to rely on the "active" style. This bug is causing us issues.

**Comment by rvanbaalen** [comment]
Please provide a plunkr so we can see what you're seeing. Can be the default plunkr as well if that reproduces your problem.

**Comment by Zion-ICS** [comment]
My apologies on not providing code!
Here's a plunkr
http://plnkr.co/edit/jWjlsmUjheKk84aD7TKJ?p=preview
You'll see that when you get to the page, the datepicker's current day has a blue background and white letters.
If you navigate to another month and then navigate back, the current day now has a gray background and navy blue letters.

The inspector seems to show that this is due to the class "active" not being re-added.

Also please forgive me for having an icon for the previous month going in the wrong direction. Our code uses images, and I felt that characters were easier to handle here.

Thanks for all your work on this component!!

**Comment by chrisirhc** [comment]
This is intended behavior. The active class is only on the element when the mouse is down during a click. When the mouse button is released, the `btn-info` class is applied (`dt.selected == true`). To style it, you should restyle the `btn-info` class instead of `active`.

**Comment by Zion-ICS** [comment]
My apologies on the very, very late response....
Thank you very much for the advice! That worked awesomely.
