### ISSUE TITLE
External tooltip template?

### ISSUE THREAD

**Issue by sime** [angular-ui/bootstrap#3674]
Hello,

Is it possible to use a external file as a tooltip template?

Note `tooltip-template.html` in the plunker.

http://plnkr.co/edit/iUPTDlOXtQRX2OT4M5lM?p=preview

**Comment by RobJacobs** [comment]
Per the docs [here](http://angular-ui.github.io/bootstrap/#/tooltip):

tooltip-template attribute takes text that specifies the location of a template to use for the tooltip.  In the plunkr if you do:

    tooltip-template="'myTooltipTemplate.html'"

It works.  FYI:

https://github.com/angular-ui/bootstrap/blob/master/README.md#need-help

**Comment by sime** [comment]
Yes, though `myTooltipTemplate.html` is not an external file, but an inline `text/ng-template`
```html
<script type="text/ng-template" id="myTooltipTemplate.html">
  <span>Special Tooltip with <strong>markup</strong> and {{ dynamicTooltipText }}</span>
</script>
```

**Comment by sime** [comment]
I should note that hovering the tooltip in the plunker throws this error:
```
Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite! See: http://docs.angularjs.org/api/angular.element
http://errors.angularjs.org/1.3.13/jqLite/nosel
```

**Comment by RobJacobs** [comment]
Your template is just plain text, I don't think Angular considers that as a valid template.

**Comment by sime** [comment]
Got it! Template needs to be wrapped by a single element.

Cheers.

**Comment by tcrite** [comment]
Hi, I know this is kind of old, but is it also possible to pass variables to the template from the parent view?
