### ISSUE TITLE
DatePicker gives validation error if date is cleared

### ISSUE THREAD

**Issue by joelbhansen** [angular-ui/bootstrap#3675]
This is a problem in a form I'm making, in which the date doesn't have to be set. The form will then not validate, due to this date error.

**Comment by RobJacobs** [comment]
https://github.com/angular-ui/bootstrap/blob/master/README.md#need-help

https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

Closing pending more info.
