### ISSUE TITLE
Modal cannot be closed by clicking on the backdrop.

### ISSUE THREAD

**Issue by nullstatement** [angular-ui/bootstrap#3677]
The commit 444c488d62e1b653a1b6c98f0bbeed4040835131 removed the ability to close the modal by clicking on backdrop. However the documentation still refers to the option backdrop having the 'static' option. With the current code it is always the static.

We should either make it clear in the documentation that the backdrop option is only true or false (with no ability to close the modal by clicking on the backdrop), or add the functionality back in.

**Comment by rvanbaalen** [comment]
Please try the demo page. You can still close a modal by clicking on the backdrop. http://angular-ui.github.io/bootstrap/#/modal

You're referencing a commit from 2 years ago..

**Comment by nullstatement** [comment]
Ahh I see what what happened. I upgraded from 0.6.0 to 0.13.0, but forgot to upgrade the css. So I had to modify the backdrop template so it would close again and found this commit where it was removed.

**Comment by rvanbaalen** [comment]
Aah thats quite a big step haha. Glad it worked out for you.

**Comment by Jeevanandanj** [comment]
I want to restrict the user if he clicks on backdrop, the modal pop up should not close

**Comment by icfantv** [comment]
@Jeevanandanj if you want support, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) rather than commenting on a month's old issue, otherwise, no one may see it.
