### ISSUE TITLE
Datepicker in a Dropdown ignores auto-close definition if a date picked is outside of the current month.

### ISSUE THREAD

**Issue by xingped** [angular-ui/bootstrap#3678]
See my plnkr for an example: http://plnkr.co/edit/cDD3nuL9SvMnTKXzSPLV?p=preview

Select any date within the current month and notice that it behaves as expected. Select a date outside of the current month (i.e. the 28th of the month before or the 3rd of the month after) and you'll see the dropdown close. It will also close if you click on the month to zoom out to a month-level view.

**Comment by rvanbaalen** [comment]
Seems like a valid bug. However I'm not sure if this behaviour is intended or not. Doesn't make much sense to allow selecting these greyed out dates in the first place.

**Comment by xingped** [comment]
It's not just the grayed out dates, but also clicking the "Month" button that zooms out to month level.

The way I've gotten around this problem for now (for anyone else that comes along) is to use a CSS rule to set pointer-events: none on the "Month" button and use the disable-date function to detect whether or not the current day is within the current month and if not, disable the date.

**Comment by wesleycho** [comment]
[Here](http://plnkr.co/edit/vGA11mwWhY5QKruVdhFY?p=preview) is a current Plunker.

This is a weird bug - a current workaround is to stop propagation on the dropdown menu element and to programmatically close the datepicker.

**Comment by drewbeck** [comment]
I'm having the same issue.

[This 'contains' line](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L701) in the datepicker is returning false when it should be returning true.

Looks like the same code is working fine on the [demo page](https://angular-ui.github.io/bootstrap/#/datepicker), though!

#mystery

**Comment by wesleycho** [comment]
I am going to recommend adding `ng-click="$event.stopPropagation()"` on the datepicker directive in this case - this seems to be the best fix for this use case.

[Here](http://plnkr.co/edit/a9F0cgdEEm9Tw8c7G9td?p=preview) is this fix in action.

@drewbeck: the demo page is using the `uib-datepicker-popup` directive.

**Comment by xingped** [comment]
@wesleycho Just wanted to say thank you for that fix/workaround. Finally came back around and had to fix it.

**Comment by jaczkog** [comment]
@wesleycho May I ask why this was closed? It's still not fixed in v2.5.0.
