### ISSUE TITLE
Angular UI tabs don't respect the Bootstrap CSS definitions. 

### ISSUE THREAD

**Issue by victorbstan** [angular-ui/bootstrap#3679]
Tabs are supposed to have a margin bellow them, to separate the bottom of the tabs from the content. You can check this in the Twitter Bootstrap documentation http://getbootstrap.com/javascript/#tabs. 

This is not the case for the implementation of angular-ui, you can check the faulty implementation on the example page for tabs: http://angular-ui.github.io/bootstrap/ go see `Tabs (ui.bootstrap.tabs)` section

**Comment by KillaBee1985** [comment]
@victorbstan Hello. You are not right. In original bootstrap.css is no margin. Margin which you can see on bootstrap website appears because custom styles have been used (docs.min.css)

**Comment by victorbstan** [comment]
Hmm, yes you are quite right! My bad.
