### ISSUE TITLE
Integrate angular ui-mask and datepicker - non US dates format

### ISSUE THREAD

**Issue by eladh** [angular-ui/bootstrap#3680]
Hi.

after a long research i found that using the ui bootstrap datepicker with ui-mask using non US date format like : dd/mm/yyyy cause the ui-mask to display invalid date representation.

please see the following plunker: http://plnkr.co/edit/88ax7pkiEhsD5b74q3Bf?p=preview 

also this stackoverflow :  http://stackoverflow.com/questions/28559033/ui-mask-and-datepicker-in-angular

the solution there is to write custom decorator that use jquery ui mask .

I saw closed issue with the same scenario and its been closed and the rresponse was to contact support or stacktrace.

so - this issue is invalid ? or its a bug ? 

thanks in advance,
elad.

**Comment by rvanbaalen** [comment]
If you saw the same issue somewhere else stating that it was an invalid issue, why would re-posting that issue make it valid?

This is clearly an implementation question on how to use two libraries together. Questions are asked on StackOverflow.

**Comment by eladh** [comment]
Thanks for the Polite answer.

in the other issue it wasn't clear if its implementation issue in ui-mask or the datepicker.

next time i will be more careful not wasting your time.

10x
