### ISSUE TITLE
Apply one-time binding to typehead list items

### ISSUE THREAD

**Issue by Serginho** [angular-ui/bootstrap#3681]
The ng-repeat of the dropdown div that appears when you write something should have an options to apply on-time binding for improving its performance.

**Comment by rvanbaalen** [comment]
Feel free to submit a PR implementing this improvement. Seems to make sense -- any performance improvement is welcome.

**Comment by wesleycho** [comment]
A one time binding is not something that can really be implemented optionally easily (or at least that I know of) - this would involve using parse and potentially managing a slew of options for each binding, as there is a decent chance that there will be lots of feature requests against each binding everywhere if we go down this route.

I'm not sure whether it is something that should be implemented for this particular feature, but this is lower on the priority level IMO, unless someone files a PR implementing this well with tests.

**Comment by wesleycho** [comment]
Closing, as this appears to be a dangerous breaking change.
