### ISSUE TITLE
modal does not show up when on fullscreen mode on an element

### ISSUE THREAD

**Issue by nozer** [angular-ui/bootstrap#3686]
If I go full screen on a div element and then if I click on a button on this div to show a modal, that modal will not show up. 

Here is a plnkr demo (it is a modified version of what you have on the bootstrap modal template page). 
1 - Please click on "launch the preview in a separate window" icon of plnkr and then 
2 - Click on "Go Full Screen" button. 
3 - Then, when in full screen mode, click on any of the buttons to try to show a modal. 

http://plnkr.co/edit/oKZHZZebyNMwpG114Jyy?p=preview

I think that if I could specify in modal options what the parent element of the modal window is, then this could solve the issue.

**Comment by rvanbaalen** [comment]
This has nothing to do with modal, it's an issue in your 'screenfull' implementation. Please ask questions on StackOverflow and report bugs on GitHub.

https://github.com/angular-ui/bootstrap#need-help

**Comment by nozer** [comment]
Thank you. I will do as you suggested.

**Comment by nozer** [comment]
Hi
Instead of using the `screenfull` library, I used `BigScreen` library to test this issue. I still have the same problem. This is not related to screenful implementation or BigScreen implementation. 

When browsers go on fullscreen on an **element**, for ui bootstrap's modal to appear in front, i think that, it must be a child of the element that is on fullscreen (I verified this by editing the html source of ui  modal from developer tools and pasting it inside the element that has gone full screen and the problem was fixed). 

You may test this again via this plnkr

To test it: 
1 - Click on this link  http://plnkr.co/edit/oKZHZZebyNMwpG114Jyy?p=preview
2 - Click on the  "launch the preview in separate window" icon (image shown below)
3 - Click on Go Full Screen Button (you will then be in full screen on the element with id `fullable`)
4 - Then click on any of the buttons to try to show a modal. 

Here is how to "launch  the preview in separate window" on plnkr: 

![screen shot 2015-05-19 at 09 54 23](https://cloud.githubusercontent.com/assets/6604091/7723127/f189860c-feee-11e4-9870-b4ea5c51c356.png)

**Comment by nozer** [comment]
I solved this issue by editing the modal source. 

It involved modal window to be appended to the element of my choice (in this case, element that goes full screen).

Options object we pass to the `$modal.open()` function now accepts an `appendTo` property which is a css selector that will be used by `document.querySelector`.

In modal code, I changed from these:
```
var body = $document.find('body').eq(0),
    currBackdropIndex = backdropIndex();
```
to these:
```
var appendTo = modal.appendTo || 'body';
var body = angular.element(document.querySelector(appendTo)),
            currBackdropIndex = backdropIndex();
```

It would be great if a fix similar to this would be added to the code.

**Comment by nozer** [comment]
I solved this issue by editing the modal source. 

It involved modal window to be appended to the element of my choice (in this case, element that goes full screen).

Options object we pass to the `$modal.open()` function now accepts an `appendTo` property which is a css selector that will be used by `document.querySelector`.

In modal code, I changed from these:
```
var body = $document.find('body').eq(0),
    currBackdropIndex = backdropIndex();
...

$modalStack.open(modalInstance, {
            scope: modalScope,
            deferred: modalResultDeferred,
            content: tplAndVars[0],
            backdrop: modalOptions.backdrop,
            keyboard: modalOptions.keyboard,
            backdropClass: modalOptions.backdropClass,
            windowClass: modalOptions.windowClass,
            windowTemplateUrl: modalOptions.windowTemplateUrl,
            size: modalOptions.size
          });
```
to these:
```
var body = angular.element(document.querySelector(modal.appendTo)),
            currBackdropIndex = backdropIndex();
...

$modalStack.open(modalInstance, {
            scope: modalScope,
            deferred: modalResultDeferred,
            content: tplAndVars[0],
            backdrop: modalOptions.backdrop,
            keyboard: modalOptions.keyboard,
            backdropClass: modalOptions.backdropClass,
            windowClass: modalOptions.windowClass,
            windowTemplateUrl: modalOptions.windowTemplateUrl,
            size: modalOptions.size,
            appendTo: modalOptions.appendTo || 'body'
          });
```

It would be great if a fix similar to this would be added to the code.

**Comment by PanfilovDenis** [comment]
This fix work for me! Maybe merge this little fix to master?

**Comment by numbata** [comment]
@nozer thx for solution. Vote for reopen this issue and fix it.

**Comment by vdv73rus** [comment]
Whoa! Let's merge to master!

**Comment by nozer** [comment]
Thank you @PanfilovDenis  @numbata  and @vdv73rus. I created a pull request here https://github.com/angular-ui/bootstrap/pull/4194

**Comment by nozer** [comment]
It says all checks failed, it would be nice if someone else tried.

**Comment by bryan-gislason** [comment]
Awesome! Literally came looking for this ability right now as it's much needed.

**Comment by nozer** [comment]
I just created a pull request for this and it says "all checks failed". I am not sure what i am doing wrong (this is my first attempt to contribute to a public repo). 
https://github.com/angular-ui/bootstrap/pull/4200

**Comment by nozer** [comment]
Test is failing because in the tests, `body > ...` selectors are failing. Any help to update tests would be appreciated

**Comment by TurkiWalid** [comment]
For the ones who uses Angular2+
this solved my problem:
[https://stackoverflow.com/questions/47966814/angular-ngbmodal-how-to-make-specific-modal-be-topmost-all-other-modals](url)
