### ISSUE TITLE
[typeahead] use as auto-complete?

### ISSUE THREAD

**Issue by fiznool** [angular-ui/bootstrap#3695]
I know that we aren't supposed to use GitHub for support questions, and we should use SO instead, but I've had [this question](http://stackoverflow.com/questions/30118967/can-the-angular-ui-bootstrap-typeahead-be-used-as-an-auto-complete) posted for a while and there has been no answer, so I'm hoping somebody here can help me. Even if its a simple 'no, that can't be done'.

I'm looking to add an 'auto-complete' feature to text fields and textareas in my Angular app. I'm looking for something similar to GitHub's @-mentions, i.e. when the user types a specific key (e.g. `@`) a dropdown box appears so that the user can select the text to insert. Something like this:

![ygjax](https://cloud.githubusercontent.com/assets/820863/7726855/cf0fd6f4-fefc-11e4-835c-1a5240f3d7b8.png)

It looks like the typeahead directive almost does what I need, however the typeahead is revealed after any character is pressed. I only want it to be revealed when the specific key is pressed, e.g. @.

Is there any way to get this typeahead to do what I want, or should I use a different approach?

**Comment by rvanbaalen** [comment]
> I know that we aren't supposed to use GitHub for support questions, and we should use SO instead

Sorry pal that simple rule stil applies even when your question doesn't get answered quick enough.
I'll take a look at your SO question though.
