### ISSUE TITLE
How can I switch active tabs based on window width?

### ISSUE THREAD

**Issue by canebat** [angular-ui/bootstrap#3697]
I can't quite grasp how to switch from one tab to another based on window width.

ie,
```
<tabset>
    <tab>
        <tab-heading>One</tab-heading>
        <span>ONE</span>
    </tab>
    <tab>
        <tab-heading>TWO</tab-heading>
        <span>TWO</span>
    </tab>
</tabset>
```

When the window width is at least 900px, it should auto-switch to the first tab. 
When the window width is less than 900px, it should auto-switch to the second tab.
But once the switch happens, the user should still be able to access the other tab (it should not lock a user into a particular tab).

I tried wrapping the `<tabset>` in a directive, and then manipulating the `active` class on the elements but angular-ui does not register this change, so it ends up having tabs with multiple active classes.

**Comment by rvanbaalen** [comment]
The issue tracker is for bugs and issues, not implementation questions. Those can be asked on StackOverflow.
