### ISSUE TITLE
Accordion animations not working in Plunkr example

### ISSUE THREAD

**Issue by apandichi** [angular-ui/bootstrap#3700]
The accordion elements shown in the http://angular-ui.github.io/bootstrap/#/accordion page have animations. The ones shown in the associated Plunkr do not. If I replace the script version ui-bootstrap-tpls-0.13.0.js with ui-bootstrap-tpls-0.12.0.js, animations work. Is this some kind of a bug or regression? Or am I missing something here?

**Comment by rvanbaalen** [comment]
Unfortunately, you are right. This is indeed a bug.

**Comment by C00per** [comment]
Hi, Is it correct that the accordion animation is not working in ui-bootstrap-tpls-0.13.0.js?  Or the problem only with demo site and there is a way to turn it on for ui-bootstrap-tpls-0.13.0.js?

**Comment by rvanbaalen** [comment]
Please use the search function. This has been asked before. 

Add ngAnimate to your project for animations support.

**Comment by Hrafnkellos** [comment]
There is nothing in the documentation implementing that you have to have a ngAnimate dependency for animation to work in your project.

**Comment by icfantv** [comment]
@Hrafnkellos neither does the core Angular project.  Our project, like Angular, will use it if it's there, otherwise it won't.  I believe it's a reasonable deduction for developers to make on their own that animation doesn't just happen auto-magically.
