### ISSUE TITLE
Datepicker clicking clear button on popup gives "ng-model" value must be a Date object

### ISSUE THREAD

**Issue by gjmoyer** [angular-ui/bootstrap#3701]
If you have a Datepicker directive as a popup, and choose a valid date, then popup again and click the clear button, you get the following exception:
Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.

This then leaves the form.$invalid property as true, which is not correct, if this is not a required field.

Open the console window on the demo page, and follow the above 2 steps, and you will see the error emitted to console window.

**Comment by rvanbaalen** [comment]
Plunkr please.

**Comment by dkavun** [comment]
Looks like the problem is either in $viewChangeListener or in the dateParser: 'clear' passes an empty string as a selected value and the dateParser parses it to 'Invalid date'. It seems to me, that null should be returned in this case.

**Comment by gjmoyer** [comment]
In datepicker.js line 652, I changed the code to this, and it appears to fix the issue.
      ngModel.$viewChangeListeners.push(function () {
          if (ngModel.$viewValue) scope.date = dateParser.parse(ngModel.$viewValue, dateFormat, scope.date) || new Date(ngModel.$viewValue);
          else scope.date = null;
      });

**Comment by slavafomin** [comment]
This is a very annoying bug indeed. Is there a temporary workaround for this that we can use externally?

Thanks!

**Comment by ruionwriting** [comment]
Reverted back to 0.12.0 for now.

**Comment by DeWet-vanRooyen** [comment]
I still get this error when I use the format of 'dd/MM/yyyy'

when manually typing in the date and starting with a number greater than 12 it wont work.
Any ideas ? Thanks !

**Comment by kenthamilton** [comment]
I am guessing this is happening because there is no date present on the page when it loads. What I ended up doing was setting the value to undefined instead of null if there is no value for that field. If there is a value then I convert it to a new Date object. I hope this code helps. I believe that the value cannot be null but it can be undefined. In my case I was setting the value as it was returned from the JSON object in my service like this:
_.each(_estimate.EstimateLineItems, function(li){
                        if(li.IssueDate == null) {
                            li.IssueDate = undefined;
                        } else {
                            li.IssueDate = new Date(li.IssueDate);
                        }
                    });
