### ISSUE TITLE
Implementation details too sparse

### ISSUE THREAD

**Issue by Jaff** [angular-ui/bootstrap#3702]
After a lot of manual downloading and dependency setup, I attempted to load a page with some example code. However, Safari java console shows:

[Error] ReferenceError: Can't find variable: angular
	(anonymous function) (ui-bootstrap-0.13.0.min.js, line 8)

Has anyone provided a self-contained demo instead of assuming everyone knows how to make these things work? Looking at demo examples, it does not even show what needs to be put in html to satisfy dependencies.

**Comment by rvanbaalen** [comment]
@Jaff Sorry to hear that you weren't able to figure out UI Bootstrap to get it up and running. Did you check out http://angular-ui.github.io/bootstrap/#/getting_started ? That's a pretty extensive description on how to get started.

You can also checkout some of the plunkr demos on that same page.
