### ISSUE TITLE
Open modal is shifting body content to the left

### ISSUE THREAD

**Issue by alexndlm** [angular-ui/bootstrap#3707]

**Comment by rvanbaalen** [comment]
Possibly the worst reported issue so far. Since this is so poorly formatted, I'm going to close this until you add all required info and reopen. 

Read this before posting issues
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md

**Comment by alexndlm** [comment]
Sorry.
http://plnkr.co/edit/ynWJUbnryVkSHdEjFRMw?p=preview
