### ISSUE TITLE
Typeahead dropdown list position

### ISSUE THREAD

**Issue by albv** [angular-ui/bootstrap#371]
For now if input margin-bottom is specified it affects dropdown list position, so it's appear with some undesirable offset. Actually you can see this at http://angular-ui.github.io/bootstrap/ example page (compare with http://twitter.github.io/bootstrap/javascript.html#typeahead).

**Comment by shilan** [comment]
but I still have this problem, if you put a typeahead inside and accordion, then the positions it gets after scrolling will be wrong especially in Internet Explorer.
I try to provide a plunker tomorrow.

**Comment by shilan** [comment]
I applied 
typeahead-append-to-body="true"	
and now it works :)
