### ISSUE TITLE
Can't require tab in custom directives

### ISSUE THREAD

**Issue by Septh** [angular-ui/bootstrap#3710]
I'm trying to write a directive that would require tab as its parent :

    .directive('needTabAsParent', [ function()
    {
    	return {
		restrict: 'AE',
		require: '^tab',
		template: '<h2>I am a child of tab</h2>',
		link: function(scope, element, attrs, tab)
		{
			console.log(tab);
		}
	}
    }])

But this doesn't work. All I get is the Missing Required Controller error : https://docs.angularjs.org/error/$compile/ctreq?p0=tab&p1=needTabAsParent

Note that I have no problems requiring tabset rather than tab.

**Comment by rvanbaalen** [comment]
https://github.com/angular-ui/bootstrap#need-help

**Comment by Septh** [comment]
Sorry if I didn't make myself clear : I was not asking for help but describing a situation that, unless I'm mistaken, seems to me like an issue. I'm editing my original post to clarify.

I've made a plunker to illustrate : http://plnkr.co/edit/GQh9svSMfXcRzkHJlCt1?p=preview

Note that if the tab requirement is made optional (ie. :require : '^?tab') then null is output to the console.

**Comment by Septh** [comment]
Hmmm... ok, sorry if I didn't make myself clear: I'm not looking for some help here but just describing a situation that, if I'm not mistaken, looks like an issue. I edited my post to clarify.

I also created a Plunk to illustrate : http://plnkr.co/edit/GQh9svSMfXcRzkHJlCt1?p=preview

**Comment by rvanbaalen** [comment]
I get that but its still an implementation question and not a bug in the library

**Comment by smithscripts** [comment]
This is still and issue. Creating custom directives is an essential part of angular development. If tabs does not support this process I would place this in the bug bucket
