### ISSUE TITLE
select strange behaviour in $modal

### ISSUE THREAD

**Issue by sgibberd** [angular-ui/bootstrap#3711]
http://plnkr.co/edit/ZqzCnMEIjR72nXh1Yd22?p=preview shows when I include a \<select\> in a $modal template, the first \<option\> is not selectable, and following  \<option\>s choose the \<option\> above. This behaviour occurs whether I bind to an angular controller \<select ng-model="obj.val"\> (ie a binding with a dot '.'), or not as in the example.

When I use \<select size="3"\> or \<select multiple="true"\> it works well

**Comment by rvanbaalen** [comment]
Your plunkr doesn't reproduce the problem -- the first item is selectable.

**Comment by sgibberd** [comment]
Ok - I checked on several browsers. It seems to be specific to iceweasel (firefox) version 31.6.0 running on debian . Firefox running on ubuntu and chrome don't have this problem. Thanks for your help.
