### ISSUE TITLE
typeahead on Chrome/Android: Can't select options occluded by pop-up keyboard

### ISSUE THREAD

**Issue by GregS2** [angular-ui/bootstrap#3712]
I initially posted this over on the Chrome forum here: http://bit.ly/1AuZ6AU , but I probably ought to have reported it here, so here it is:
Using the AngularJS ui-typeahead control, if the list of items is long enough to be occluded by the on-screen keyboard, and one scrolls down to select an item that is occluded, the chosen item is not actually selected. I have created a Plunk which demonstrates the problem: http://plnkr.co/edit/KdEbBwoHmzo724xLdMFi?p=info  (type any  part of the name of a number from one to two-hundred)

It works on in the Dolphin browser.

Environment: 
Chrome 42.0.2311.111 
Android 4.4.2

**Comment by rvanbaalen** [comment]
Not sure yet what our course is regarding mobile support. I'll label it accordingly but don't hold your breath for a fix.

**Comment by GregS2** [comment]
Thanks. I'm a bit surprised about what appears to be a lower priority for mobile than desktop. I'm a beginner, and I got the impression that generally, mobile support is considered to be as important, if not more important, than desktop. (I keep seeing "mobile first" design mentioned everywhere, for example). Indeed, the app I am working on will be used more often on mobile devices.  Can you help me understand why mobile support is not seen as being as important as desktop, for angular-ui? (I am absolutely not complaining - this is an honest question. I am very grateful to be able to develop apps with Angular for no cost whatsoever)

**Comment by rvanbaalen** [comment]
Its not that we dont want to. Its just that this project has been around for quite some years now and back then, mobile first wasnt really a thing. And right now with 400+ open issues, weve got other priorities than to refactor the whole library to mobile first. 

That being said, on the mobile Angular market are other players that do a great job as well such as Ionic Framework etc.

**Comment by GregS2** [comment]
Thanks for the explanation - very much appreciated. Regarding Ionic, I started looking at that, but it seemed to me that in order to support Apple devices, I'd a) have to buy a Mac so I could do the build and b) either release my apps through the Apple app-store, or jump through hoops to get my app to my users some other way. (and I could not find a very simple way to do that).  I found a commercial product similar to Ionic that does not require a Mac, but problem b) still applies.   

That's why I decided to just write a plain web app. Have I misunderstood the capabilities of Ionic?

**Comment by rvanbaalen** [comment]
You have not. That is indeed what Ionic does. And if you're serious about app development, youshould get yourself either a mac or a developer account indeed. Preferably both. 

Anyway I like the conversation but I suppose Ill be closing it now. Our focus is on stable desktop support. If we start supporting mobile devices, we're playing a whole different ball game.

**Comment by azhu2** [comment]
Ran into the same issue, which I solved by replacing the default ngClick with https://docs.angularjs.org/api/ngTouch/directive/ngClick.
Basically, there's a ~300ms delay between the tap and release events, during which I believe the on-screen keyboard closes, thus messing with selection. The ngTouch version doesn't have this delay.
