### ISSUE TITLE
Issue with Tabs control in versions 12+ (worked in version 11)

### ISSUE THREAD

**Issue by ksmirnoff** [angular-ui/bootstrap#3718]
First of all you guys are doing an amazing job maintaining this library. Thank you.
The tab control that I am using gets populated dynamically from an array of objects. Each tab has a [x] remove link that removes a corresponding object from the array. When using ui-bootstrap 11.0 that action resulted in a tab disappearing from the view. When I tried upgrading to 12.0 or 13.0 this action results in the whole tabs set disappearing from the screen. 
Below are two plunks. Click on [x] in the tab to see the issue. Hope you can look into it asap. I have the tabbed control running in prod so a fix will be greatly appreciated.  
Here is a plank that works (11.0) - http://plnkr.co/7DdAcGw1eBJqZKTZGuvN
Here is the one that doesn't (13.0) - http://plnkr.co/ruQnm4eR0SU4UcheAIm8

**Comment by rvanbaalen** [comment]
The plunks dont seem to be working -- I get a blank screen.

Also, use the proper dependencies: no jquery, Angular 1.3 and UI Bootstrap 0.13.
For UI Bootstrap 0.11, use Angular 1.2

**Comment by ksmirnoff** [comment]
Thanks for a quick response. You don't see a blue 'Run Report' button showing up in the upper left corner? I tested the plunker links in in IE, Firefox and Chrome and they are working for me.
Can you give it another try. Thank you

**Comment by ksmirnoff** [comment]
I tested the plunkers from multiple locations. They work. Can you please give it another try.

**Comment by rvanbaalen** [comment]
1 message asking to give it another try was sufficient. I simply don't have all the time to respond super fast to requests. Looking into it now.

**Comment by rvanbaalen** [comment]
Seems like you have a funky implementation error. The way you're removing tabs (using jQuery?!) is really odd. Look into Angular / vanilla javascript array manipulation and ask your question on StackOverflow if you can't figure it out.

Here's a demo plunkr that demonstrates the possibility of removing a dynamically generated tab:

http://plnkr.co/edit/U0rBkUaSDjWT28fi0jAH?p=preview
