### ISSUE TITLE
0.13 Release?

### ISSUE THREAD

**Issue by varmint09** [angular-ui/bootstrap#3722]
Hi,

I want to use this https://github.com/terranisu/angular-emoji-picker and it requires 0.13, so I wondered what timeframe for 0.13 release as the popover historically sounds like it was either buggy, or a bit weak.

Or, if there was a way to get callbacks from a popover so I could tell which item they clicked, that would work too, any ideas? or does 0.13 add that?

Thanks

**Comment by rvanbaalen** [comment]
Take a look at the releases. Its been out there for a while now.

**Comment by varmint09** [comment]
Taking a close look at npmjs says otherwise;

https://www.npmjs.com/package/angular-ui-bootstrap

When I want to take the latest version, I get 0.12, not 0.13.

**Comment by rvanbaalen** [comment]
Who said nom was the official resource to check for UI Bootstrap releases? Last time I checked, you check in the github repo for new releases or other official channels like bower. 

The npm release is not maintained by the current team.
