### ISSUE TITLE
Regarding server side pagination

### ISSUE THREAD

**Issue by vaishali-saxena** [angular-ui/bootstrap#3724]
Hi,
I am using the pagination feature in my project using angular and it works fine but the issue is i am using the API which get the data like json using http. and total data will not load only the limited data will load which i will pass using the page-per-item attribute.
here is my controller, what i want to do here, limit is the page-per-item(currently i'm using static value) and the offset is the items if 0 then API will send first 5 items then on offset 1 next 5 items API will send and so on till the totalItem.
now i want to show the pagination in this scenario.
pagination works fine but on click next/ any page click no data show only 5 items show on first page other than no data show.
Note: now i have to change the offset value as per pages click and send the http request to the server then the data show as per the http request.
so please tell me how i'll solve it.

app.controller('pendingOrdrController', function ($scope, $http) {
    var dataObj = {
          offset : 0,
          limit : 5
      };  
    function call(){$http.post('/order/pending-order', dataObj)
      .success(function(response, status) {
        $scope.POData = response;
      })}
      call();
});//end

here is the HTML of pagination

<pagination ng-model="currentPage" max-size="10" class="pagination-sm" boundary-links="true" rotate="false" previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;" items-per-page="itemsPerPage"  total-items="POData.total_order"></pagination>

**Comment by pkozlowski-opensource** [comment]
I'm sorry, but we can't handle support questions as part of GitHub issues, please see: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
