### ISSUE TITLE
Dropdown broken from 0.11.2 onwards

### ISSUE THREAD

**Issue by jkelleher** [angular-ui/bootstrap#3725]
I'm using mean.js stack and when I bump the bower packages to latest, the dropdowns fail to display on click. I worked back through the angular-bootstrap versions until it worked - 0.11.2 is the last time it worked (at least in my build).

**Comment by Gamemaniak** [comment]
This is because 0.12.0 has [breaking changes](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#breaking-changes), always check the changelog when you want to upgrade.

**Comment by jkelleher** [comment]
Thanks for reminder, still finding my feet.
