### ISSUE TITLE
ngAnimate 1.4 Breaks Modal Animations

### ISSUE THREAD

**Issue by danielpquinn** [angular-ui/bootstrap#3730]
I'm not sure what exactly has changed in ngAnimate 1.4, but I will investigate and try to provide more information. Notice that after the modal is dismissed the background overlay remains in the dom. I've created a plunkr that reproduces the issue here: http://plnkr.co/edit/l63yXaNe3lwZtPuZKrzS?p=preview

**Comment by Gamemaniak** [comment]
Angular 1.4 isn't supported yet. Check #3633 for more information.

**Comment by danielpquinn** [comment]
Duplicates [#3633](https://github.com/angular-ui/bootstrap/issues/3633)
