### ISSUE TITLE
Dropdown menu issues with Angular 1.4

### ISSUE THREAD

**Issue by mohsen1** [angular-ui/bootstrap#3733]
I'm using `ui.bootstrap` in [Swagger Editor](https://github.com/swagger-api/swagger-editor). After updating to `angular@1.4` and `angular-bootstrap@0.13` (from `0.11`) via [this commit](https://github.com/swagger-api/swagger-editor/commit/d461094634adbfc9c88c52a42cc08f849a7d0a85) Dropdown menus [stopped working (failed tests)](https://travis-ci.org/swagger-api/swagger-editor/builds/64491889). I had to [roll back](https://github.com/swagger-api/swagger-editor/commit/86b66eb2910b76b4e4ef18ed52ac55af38e6ef32) since I couldn't find any fix for the issue.

Here is [my markup](https://github.com/swagger-api/swagger-editor/blob/master/app/views/header/header.html#L7-L127):

```html
<div class="help dropdown">
      <button class="dropdown-icon btn btn-default dropdown-toggle" id="helpMenu" data-toggle="dropdown">
        <span>Help</span>
        <span class="caret"></span>
      </button>

      <ul class="dropdown-menu">
        <li>
          <a tabindex="-1" href="https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md" target="_blank">Swagger 2.0 Specs</a>
        </li>
        <li>
          <a tabindex="-1" href="http://swagger.io/" target="_blank">Swagger Website</a>
        </li>
        <li>
          <a dropdown-toggle tabindex="-1" ng-click="openAbout()">About Swagger Editor</a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="https://github.com/swagger-api/swagger-editor/issues/new?labels=From%20Editor" target="_blank">Report A Bug</a>
        </li>
        <li class="divider"></li>
        <li>
          <a dropdown-toggle ng-click="toggleAboutEditor(true)" tabindex="-1">Show Introduction Help</a>
        </li>
      </ul>
</div>
```

Is my markup not compatible with `0.13` or it's a bug?

**Comment by RobJacobs** [comment]
Angular 1.4 is not supported yet.
