### ISSUE TITLE
Want latest ajs ui bs tabs on tabs-left to work with panel data to right side

### ISSUE THREAD

**Issue by gtesslerge** [angular-ui/bootstrap#3735]
We cant get out tab panel data to appear to the right of the tabs-left.  they in error appear below.
see attached file

**Comment by gtesslerge** [comment]
+--------------+ +-------------------------------------+
|              | |                                     |
+--------------+ |                                     |
+--------------+ |                                     |
|              | |                                     |
+--------------+ |                                     |
                 |                                     |
                 |                                     |
                 |                                     |
                 |                                     |
                 +-------------------------------------+
                                                        
                                                        
+-------------+                                         
|             |                                         
+-------------+                                         
+-------------+                                         
|             |                                         
+-------------+                                         
+--------------------------------------------+          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
|                                            |          
+--------------------------------------------+

**Comment by rvanbaalen** [comment]
This is complete rubbish. Come back when you are able to produce a solid issue description complete with plunkr.
