### ISSUE TITLE
DatePicker: No events like "on-select" supported

### ISSUE THREAD

**Issue by NCC1701M** [angular-ui/bootstrap#3738]
The DatePicker doesn't support events like onSelect. You can only use ng-model to change one date, but what's when you need to select multiple dates or you like to add dates to an array? You have no possibility to do so.

**Comment by rvanbaalen** [comment]
For support questions, please read:

https://github.com/angular-ui/bootstrap#need-help

**Comment by NCC1701M** [comment]
This is no seek for help. It's a feature request!

**Comment by rvanbaalen** [comment]
> That's a big lack in my opinion.

Technically, you we're just venting your opinion. I'll re-open as a feature request :+1:

**Comment by NCC1701M** [comment]
Unvented ;-)

**Comment by wesleycho** [comment]
So this is really a feature request to add support for multiple selection of dates if I'm reading this correctly?

**Comment by NCC1701M** [comment]
Correct

**Comment by wesleycho** [comment]
Going to close this as a duplicate of #2806
