### ISSUE TITLE
Calendar popup squished in Firefox 39 Beta

### ISSUE THREAD

**Issue by codewzrd** [angular-ui/bootstrap#3740]
Check out the plunker http://plnkr.co/edit/XVUQfP

All I did was set the width on the second p.input-group to be 150px. The calendar popup is squished.

It's OK in Chrome and IE 11.

![datepicker](https://cloud.githubusercontent.com/assets/23690/7916827/4aa8b33e-0854-11e5-9c4f-a5fca4afd1ef.PNG)

**Comment by rvanbaalen** [comment]
Please check again when the stable Firefox 39 is out. We can't support beta releases.

**Comment by shaunbowe** [comment]
This is an issue with the stable Firefox 39 which was released on June 30, 2015
