### ISSUE TITLE
Modal close method keypress

### ISSUE THREAD

**Issue by ryanburnett** [angular-ui/bootstrap#3741]
When you use the modal and press the Escape key it calls the `dismiss` method.

Is there a way to use the Enter (or Spacebar) key to call the `close` method?

https://angular-ui.github.io/bootstrap/#/modal

**Comment by rvanbaalen** [comment]
First of all; questions are asked on StackOverflow:
https://github.com/angular-ui/bootstrap#need-help

Second: your suggestion would be highly unintuitive if you ask me. A user won't expect to close a modal when they press space or enter.
