### ISSUE TITLE
improvement: add id's to tabs in tabset

### ISSUE THREAD

**Issue by bolemeus** [angular-ui/bootstrap#3743]
I have a tabset in my application and I'd like to add an id to the different tabs in a tabset, because of testing reasons.

I was able to do this by adding a tab-id to the tabs like so...

```
<tabset>
	<tab active="..." disabled="..." tab-id="tab-id">
		<tab-heading><i class="fa fa-info-circle"></i> Basisgegevens</tab-heading>
		<ng-include src="'...'"></ng-include>
	</tab>

	...
</tabset>
```

I changed the template for the tabs to the following

```
angular.module("template/tabs/tab.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("template/tabs/tab.html",
    "<li ng-class=\"{active: active, disabled: disabled}\">\n" +
    "  <a ng-click=\"select()\" tab-heading-transclude id=\"{{tabId}}\">{{heading}}</a>\n" +
    "</li>\n" +
    "");
}]);
```

Offcourse I've added the tabId to the scope of the directive as well.

Can this be implemented in this library?

**Comment by rvanbaalen** [comment]
Well the way you're implemented it, is exactly the way we suggest how to customise UI Bootstrap: overwrite default templates with your own custom templates. There's no need to actually add this to the library for two reasons:

- You're able to do this by overwriting the custom template with your own, just the way it's supposed to
- Adding ID's to tabs is perhaps useful for your specific use case, but we can't implement everyone's specific use cases in a generic library.
