### ISSUE TITLE
Scope issue with modals

### ISSUE THREAD

**Issue by yourrock** [angular-ui/bootstrap#3744]
Hi,

First, I'm new to GitHub so let me apologize beforehand for any mistakes.

I wanted to define a custom scope for the modal (I don't want to use dependency injection for reasons) I am using in my project, but I'm getting an error whenever I define a scope in `$modal.open`. Here is the plunk: http://plnkr.co/edit/rbtbpyqG7L39q1qYdHns 

I tried debugging and saw that `(modalOptions.scope || $rootScope)` returns `true` with a custom scope and since `true` (obviously) doesn't have a `$new()` function defined, an exception is thrown.

Any thoughts?

**Comment by rvanbaalen** [comment]
No need to apologize. But let me give you this advise: all open source project have a certain way of handling issues and questions. The issue tracker on GitHub is **not** a forum for questions. You can read about each project's individual do's and don't mostly in the [README.md](https://github.com/angular-ui/bootstrap) or the [Wiki](https://github.com/angular-ui/bootstrap/wiki).

In our case, please read this:

https://github.com/angular-ui/bootstrap#need-help

It states that questions like this one should be asked on StackOverflow.
