### ISSUE TITLE
Toggle Collapse is not working

### ISSUE THREAD

**Issue by satheeshsanthosh** [angular-ui/bootstrap#3745]
Toggle collapse is not working in the current version. It works good in older version in ui-bootstrap-0.12.0.js

**Comment by rvanbaalen** [comment]
Add a plunkr and a scenario for us to reproduce this problem (browser used, AngularJS version, UI Bootstrap version, etc.)

**Comment by satheeshsanthosh** [comment]
Here the plunker link. 
http://plnkr.co/edit/JiM9mRXaAUmY3H8mU9RO?p=preview
The smooth toggle effects is not working in current version.

**Comment by rvanbaalen** [comment]
Hmmpff.. Even with `angular-animate` included, it doesn't work. This issue is reproducible even in the demo plunkr. Thanks for spotting that bug! I'll tag Chief Animations @chrisirhc here so he can take a look when he's got time.

**Comment by leobudima** [comment]
Could be related to https://github.com/angular-ui/bootstrap/issues/3694

**Comment by deeg** [comment]
@leobudima, were you able to create a plunker showing the issue? When I tried the issue wasn't happening, which means there might be something else in my code which causes the issue.

**Comment by rvanbaalen** [comment]
@leobudima how is a collapse bug related to a modal bug?

**Comment by satheeshsanthosh** [comment]
Thanks. But even after included angular-animate also not working. Check my plunkr again.

**Comment by wesleycho** [comment]
You must specify `ngAnimate` as a dependency - you can see it working [here](http://plnkr.co/edit/NCqGLmgHVrfNKjA0mZjA?p=preview).

**Comment by satheeshsanthosh** [comment]
sorry, i forgot that.

**Comment by meganathan-powerofn** [comment]
Same issue in angular 5, How can i fix it ?
