### ISSUE TITLE
modal close event

### ISSUE THREAD

**Issue by mario56** [angular-ui/bootstrap#3747]
how can i use $on to get modal close or dismiss event.

not use the result.then promise

**Comment by pkozlowski-opensource** [comment]
There is no such event and we are not planning on adding one, ad the thinking is that promises provide much nicer API. Unless you can provide a valid use case where event based api is much better.

**Comment by rvanbaalen** [comment]
In addition to the above, https://github.com/angular-ui/bootstrap#need-help
