### ISSUE TITLE
[date-picker] Is it possible to get hook for current selected date when using the keyboard navigation

### ISSUE THREAD

**Issue by sushantdhiman** [angular-ui/bootstrap#3748]
Date-picker has good aria support, it allow navigation through keyboard. But date is changed only when user hits enter / space.

Are there any possible hooks which give the `current selected date` when navigating via keyboard.

**Comment by rvanbaalen** [comment]
I think you mean current focussed date, based on the fact that you're talking about keyboard navigation?

**Comment by sushantdhiman** [comment]
I have noticed that there is already something like that [activeDate]( https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L59) available. But its not exposed to public API.

May be if we can expose `activeDate`. Then code should be able to `watch` it safely without any performance issues.

**Comment by sushantdhiman** [comment]
I have created an addon which can work independently from Datepicker API.

[Here](https://gist.github.com/sushantdhiman/0b1957bfb096c1addccf) is the GIST if anyone need this feature without waiting for "Purgatory" updates.

It works by watching the [activeDate](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L59).

**Comment by wesleycho** [comment]
This sounds like a reasonable feature, although this should be opt-in if it were implemented.

**Comment by icfantv** [comment]
Closing in favor of #4772.
