### ISSUE TITLE
Modal backdrop isn't fading out

### ISSUE THREAD

**Issue by Kenvdb** [angular-ui/bootstrap#3754]
Hi guys,

Hope you can help me out. I have the following setup:
    "angular-bootstrap": "~0.13.0",
    "jquery": "~2.1.4",
    "bootstrap-sass-official": "~3.3.1",
    "ui-router": "~0.2.15",
    "underscore": "~1.8.3",
    "angular-animate": "~1.4.0",
    "angular": "~1.4.0"

Everything is working fine, except for the Modal, it's showing properly, but when I close the modal, the backdrop isn't fading out. The classes 'fade in' are still on the backdrop element, the Modal itself works ok... Any ideas how to fix this, tried several things, like switching to other versions of angular-animate and angular-bootstrap?

Thanks in advance!

Ken

**Comment by Kenvdb** [comment]
Fixed by downgrading setup to:
    "jquery": "~2.1.4",
    "bootstrap-sass-official": "~3.3.1",
    "underscore": "~1.8.3",
    "angular": "=1.3.13",
    "angular-bootstrap": "=0.12.1",
    "angular-animate": "=1.2.16",
    "ui-router": "~0.2.15"

**Comment by rvanbaalen** [comment]
Please use the search function. This is a duplicate.

**Comment by hirshy** [comment]
This isn't a duplicate. #3633 is about the dialog not fading out. This issue is about the backdrop not fading out.

[Plunker here](http://plnkr.co/edit/xQOL58HDXTuvSDsHRbra?p=preview).

The issue is only present when using Angular 1.4.x.
