### ISSUE TITLE
[Carousel] TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by bondneverdies** [angular-ui/bootstrap#3755]
In [carousel.js#L76](https://github.com/angular-ui/bootstrap/blob/master/src/carousel/carousel.js#L76), if *slides.length == 0*, **newIndex** will be **NaN**.
This will cause **function getSlideByIndex(index)** to throw an error on [L52](https://github.com/angular-ui/bootstrap/blob/master/src/carousel/carousel.js#L52) :
```
TypeError: Cannot read property 'index' of undefined
    at getSlideByIndex (ui-bootstrap-tpls.js?body=1:363)
    at Scope.$scope.next (ui-bootstrap-tpls.js?body=1:391)
    at timerFn (ui-bootstrap-tpls.js?body=1:429)
    at angular.js?body=1:13331
    at Scope.$eval (angular.js?body=1:14467)
    at Scope.$digest (angular.js?body=1:14283)
    at Scope.$apply (angular.js?body=1:14572)
    at tick (angular.js?body=1:10429)
```

**Comment by rvanbaalen** [comment]
Plunkr please.

**Comment by wesleycho** [comment]
Here is a reproduction in [Plunker](http://plnkr.co/edit/zrHVBdiQhteJ6Wxps39I).

**Comment by wesleycho** [comment]
What is happening is that the carousel uses $interval to time sliding to the next slide, but if the slides disappear in the interim, then the callback fired ends up with a false assumption about the existence of an index in the slides array.

**Comment by Gericho91** [comment]
currentIndex = slides.length == currentIndex ? 0 : currentIndex;
    add to the 566 line in ui-bootstrap-tpls.js

function goNext(slide, index, direction) {
    if (destroyed) {
      return;
    }
    currentIndex = slides.length == currentIndex ? 0 : currentIndex;
    angular.extend(slide, {direction: direction});
    angular.extend(slides[currentIndex].slide || {}, {direction: direction});
