### ISSUE TITLE
Button row with popovers squish together after popovers activated on Chrome

### ISSUE THREAD

**Issue by dlwhiteman** [angular-ui/bootstrap#3756]
I found an issue on Chrome & Safari that does not occur on IE11 or Firefox.  If you have a row of buttons, all with popovers defined, if you activate all the popovers simultaneously, the buttons move together with no gap between them.  This is evident in the demo found in the popover section of this site.  We are using these popups in our application and are having the same issue reported by our testers.  Please see the two attached images, one with the popovers inactive and the buttons with horizontal spacing, and one with the popovers active and the buttons having moved together.

![croppercapture-149](https://cloud.githubusercontent.com/assets/4522490/7984251/aec81d6c-0a95-11e5-84fd-4c241a4f69b2.png)

![croppercapture-150](https://cloud.githubusercontent.com/assets/4522490/7984250/aec3e94a-0a95-11e5-9cba-09bad0a83bbc.png)

**Comment by RobJacobs** [comment]
What your seeing is whitespace between elements with the 'display: inline-block' style being rendered prior to the popover being injected into the DOM.  Once the popover element is injected between the inline-block elements, it seems to replace the whitespace.  See [this](https://css-tricks.com/fighting-the-space-between-inline-block-elements/) article for more info on dealing with that quirk.
