### ISSUE TITLE
Epoch time validation error

### ISSUE THREAD

**Issue by ccadieux** [angular-ui/bootstrap#3760]
When using epoch time (new Date.getTime()) as the model for the date picker. The date is displayed correctly but the field is marked as invalid. 

Here is a demo:
http://plnkr.co/edit/Y0cw379HBTjqn7gIyqmG?p=preview

**Comment by chrisirhc** [comment]
I was considering removing support for epoch time as the model. Is there a particular use case you're fulfilling with this? As I commented on https://github.com/angular-ui/bootstrap/issues/3403#issuecomment-109617617 , this usage of the datepicker is quite confusing.

**Comment by ccadieux** [comment]
This has fixed in 0.13.

http://plnkr.co/edit/Uu1xfS7patfrZO48A9Tf?p=preview
