### ISSUE TITLE
Preventing dismissal of typeahed when certain items in the list are clicked

### ISSUE THREAD

**Issue by atinsood** [angular-ui/bootstrap#3763]
I am trying to implement a functionality where the type ahead list contains a list of suggestions and a View More at the bottom. Clicking on View More should bring down more suggestions and append the list with these new suggestions without dismissing the suggestion list. Clicking on any other item in the list should select the item and dismiss the list. Also I am fetching the items for this list asynchronously. 

Any suggestions on how to implement it. I have a feeling that I will have to introduce another attribute directive inside the type ahead to achieve this.

**Comment by rvanbaalen** [comment]
Please ask questions on StackOverflow. 

https://github.com/angular-ui/bootstrap#need-help

**Comment by atinsood** [comment]
Sorry, saw some old questions in github and assumed that you were handling questions via this approach. I did go ahead and open up the question on SO . Here is the link in case someone ends up on this link looking for the same information http://stackoverflow.com/questions/30658739/preventing-dismissal-of-angular-ui-typeahed-when-certain-items-in-the-list-are-c

**Comment by rvanbaalen** [comment]
No harm done. Thanks for posting the link.
