### ISSUE TITLE
Carousel slides in wrong order

### ISSUE THREAD

**Issue by SvenJunga** [angular-ui/bootstrap#3764]
Hi,

there's a bug in the carousel when the number of slides increases. (ui-bootstrap 0.13.0)
Check this plunker example: http://plnkr.co/SDAVaJIULWhWFS3fWZHu
The indicator selected after page load is wrong. And proceeding through the slides lets the indicator jump rather arbitrary.

Regards
Sven

**Comment by rvanbaalen** [comment]
Seems like a legit bug. The question is however, do we support dynamic carousel items using ng-repeat?

I think we should, however the answer to the question defines if this is a bug or an enhancement request.

**Comment by SvenJunga** [comment]
Hey Robin,

maybe I didn't make myself clear enough. There's no dynamic adding/removing of slides involved in this. By "increase" I meant there's a certain number of static slides in the carousel and exceeding this certain number unveils the described bug.

Regards
Sven 

Am 08. Juni 2015 um 04:20 schrieb Robin van Baalen <notifications@github.com>:

Seems like a legit bug. The question is however, do we support dynamic carousel items using ng-repeat?
I think we should, however the answer to the question defines if this is a bug or an enhancement request.

**Comment by intellix** [comment]
I believe this is caused by `orderBy:'index'` within the carousel.html template. That seems to be what has changed and removing it fixes this

**Comment by wesleycho** [comment]
[This](http://plnkr.co/edit/0o1D5fRURUGPYMSRKefc?p=preview) is indeed a strange bug.

I have a fix I am about to open a PR for.

**Comment by kirandas82** [comment]
#5652
