### ISSUE TITLE
No true "[top|bottom]-left" available in $position

### ISSUE THREAD

**Issue by WydD** [angular-ui/bootstrap#3766]
Currently, "top-left" refers to the target element and the host element aligned on left due to:
left: function () {
    return hostElPos.left;
},

But there is no way to align, target's element to the left side of the host element like:
farleft: function () {
    return hostElPos.left - targetElWidth;
},

"top-right" does this (left side aligned with the right side of the host).

**Comment by rvanbaalen** [comment]
Please provide a plunkr

**Comment by wesleycho** [comment]
We want to support something like this, but this is unscheduled currently since this is complex work.

**Comment by icfantv** [comment]
Closing in favor of #4762.
