### ISSUE TITLE
popover-template works in 0.13.0-SNAPSHOT but not in 0.13.0

### ISSUE THREAD

**Issue by dozed** [angular-ui/bootstrap#3767]
See http://plnkr.co/edit/rvkSvgdInhrsBNP4WXdy?p=preview

It could be related to `useContentExpr` which has been introduced after the SNAPSHOT.

Also `popover-class` does not work in SNAPSHOT, but it works in the 0.13.0 release.

**Comment by rvanbaalen** [comment]
I'm confused what you are trying to say here. The GitHub issue tracker is for reporting issues on official releases of UI Bootstrap. We're not accepting issue reports for custom builds or unofficial releases.

**Comment by rvanbaalen** [comment]
Regarding your 'issue', you should just define the `popover-template` within single quotes:

http://plnkr.co/edit/5r1mJmBBAX8ucNHhjYW8?p=preview

**Comment by dozed** [comment]
You might want to improve the docs then a bit: 

    popover-template takes text that specifies the location of a template to use for the popover body.

Also I surely did not want support for an "unofficial release", it was merely to help finding a possible issue.

But thanks for helping!
