### ISSUE TITLE
collapse CSS transitions do not work with a Bootstrap navbar in ui-bootstrap 0.13

### ISSUE THREAD

**Issue by dtrebbien** [angular-ui/bootstrap#3769]
Test case:

```html
<!DOCTYPE html>
<html ng-app="myApp">
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.0/ui-bootstrap.min.js"></script>
  <script>
    angular.module("myApp", ["ui.bootstrap"])
      .controller("HeaderNavController", function ($scope) {
        $scope.isCollapsed = true;
      });
  </script>
</head>
<body>

<nav ng-controller="HeaderNavController as headerNav" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" ng-click="isCollapsed = !isCollapsed">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" collapse="isCollapsed">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

</body>
</html>
```

This was derived by:

 1. Copy the example Navbar code from http://getbootstrap.com/components/#navbar
 2. Add ` ng-controller="HeaderNavController as headerNav"` to the &lt;nav&gt; element.
 3. Add ` ng-click="isCollapsed = !isCollapsed"` to the menu toggle button.
 4. Add ` collapse="isCollapsed"` to the \#bs-example-navbar-collapse-1 element.

Run this example in a browser.  Decrease the width of the browser window until only the "Brand" title and menu toggle button are visible.  Click the menu toggle button - the menu will appear immediately and there is no CSS transition.

If you instead use ui-bootstrap 0.12, then the CSS transitions will work.

**Comment by dtrebbien** [comment]
Here is the test case as a Plunker:
http://plnkr.co/edit/PTlBoyemqbClajzyV1vj?p=preview

**Comment by rvanbaalen** [comment]
Since 0.13, you should add Angular Animate (ngAnimate) as a dependency in order for transitions to work.

See forked plunkr:
http://plnkr.co/edit/B9suaOG8YeCvAvnZ3BA4?p=preview

**Comment by pmcgeebcit** [comment]
Actually the drop down still does not work in this latest version shown in plunker.  
http://plnkr.co/edit/B9suaOG8YeCvAvnZ3BA4?p=preview

You can see the problem if you try to click the drop down menu item - nothing appears.  Clearly there are sub-items that are not displaying. I reproduced this issue in both Chrome and IE.

As far as I can see, you correctly identified the issue where this drop down broke after 0.12 but I am still not sure how to fix the drop down.  Thanks for your excellent work and for the discussion on this.

**Comment by Jordan-McMillan101** [comment]
@pmcgeebcit @rvanbaalen 

To fix this dropdown issue change the <li> and <a> tags to the following: 


`
 <li dropdown>
          <a href="#" dropdown-toggle data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

`

**Comment by icfantv** [comment]
If you aren't already, you guys should be trying this against the latest versions of the code.  If there's a bug, or something you believe to be a bug, please file a new issue.  Thanks.
