### ISSUE TITLE
Expand / Collapse animation within table issue regression

### ISSUE THREAD

**Issue by SafiX** [angular-ui/bootstrap#3772]
Hi,
I found that upgrading from version 0.12.0 to version 0.13.0 affected the way expand / collapse animation within a table works.

Here's an example of an expected behavior with a nice animation (version 12) - 
http://codepen.io/SafiX/pen/jPmZEx

Here's the exact same example but with version 13. The animation isn't working - 
http://codepen.io/SafiX/pen/vOmdOX

Thanks,
Asaf

**Comment by rvanbaalen** [comment]
Please use the search function. Plenty of people reported this and it all comes back to including ngAnimate in your project. 

If you add ngAnimate, do the animations work for you?

**Comment by pkozlowski-opensource** [comment]
Doesn't look like including ngAnimate is the only problem: http://codepen.io/anon/pen/wadyEx
@SafiX BTW, you do _not_ need to include Bootstrap's JS

**Comment by SafiX** [comment]
Hi,
Thanks for the responses.
As pkozlowski-opensource mentioned, it doesn't work with ng-animate included.

Expand / collapse does work outside of a table in version 13.

**Comment by wesleycho** [comment]
I converted it to a [Plunker](http://plnkr.co/edit/2ucBEyMnoFlOdn6FecHY?p=preview) since it would make it easier to inspect the DOM.

I'll see if I can take a stab at figuring this out tomorrow.

**Comment by wesleycho** [comment]
Looking into this a bit more, this may be an $animate bug.

**Comment by SafiX** [comment]
Hi guys. Any update on this? Is it a bug?

**Comment by wesleycho** [comment]
This appears to be fixed with the latest release now, as can be seen [here](http://plnkr.co/edit/Vmy4WeS8tEmzILkd4LIj?p=preview).
