### ISSUE TITLE
Customize typeahead popup template

### ISSUE THREAD

**Issue by bhavnaberi** [angular-ui/bootstrap#3774]
I have three typeaheads on my html page. Each of these use AngularJs Bootstrap Typeahead. I can modify the template of the match by using the following: 
<script type="text/ng-template" id="template/typeahead/typeahead-match.html">
    <a class="abc" tabindex="-1" bind-html-unsafe="match.label | typeaheadHighlight:query"></a>
</script>

However I want to modify the outer template for the typeahead i.e. typeahead-popup.html and customize it differently for each of the three different typeaheads on the page. I searched for this but with no success. Any help would be very thankful.

**Comment by rvanbaalen** [comment]
Provide a plunkr reproducing your scenario please.

**Comment by wesleycho** [comment]
This appears to be a feature request, one that I actually have been in the process of implementing for each component with support of `templateUrl` modification on an instance by instance level.

I am all for this, and am aiming to be fully complete with this before the 0.13.4 release.

**Comment by kikar** [comment]
Looking for this feature as well. When is 0.13.4 release planned?

**Comment by wesleycho** [comment]
At yet, no particular plans - I'd anticipate in ~1 month or so.
