### ISSUE TITLE
error with modalProvider

### ISSUE THREAD

**Issue by jcocana** [angular-ui/bootstrap#3779]
I have an error with dependency injector $modal, this is my code:

var crudAngular = angular.module('crudAngular', ['ngRoute', 'ngAnimate','ngGrid', 'ng-store','ui.bootstrap']);

crudAngular.controller('listarCtrl', ['$scope', '$location', '$modal', '$http', 'store', function ($scope, $location, $modal, $http, store) {
       .........
}]);

I'm using 1.3.13 angular version and 0.13.0 ui-bootstrap version

**Comment by pkozlowski-opensource** [comment]
Impossible to help with just this info, see https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing for now, happy to re-open when we've got a minimal reproduce scenario.
