### ISSUE TITLE
Inverse Pagination

### ISSUE THREAD

**Issue by varmint09** [angular-ui/bootstrap#3781]
Hi,

I want to keep the links of paginated items static, so the oldest content is always on page 1, and the newer content comes in page 2, 3 etc.

What I need the pagination to do, is to show me the highest number page, and then the pagination to go 

5, 4, 3, 2, 1... this would show the newest first and page 1 will always have the same content in (unless i delete items).

not 1,2,3,4,5 as that will show oldest first

Does that make sense? I want a solution that plays well with angular/bootstrap, it doesn't need to be this module, but I would hope someone else has had this request before as its common for content sites to do this...

Many thanks!

**Comment by icfantv** [comment]
This is such a specialized use case it's not one we are going to be able to support.  Note that the page "buttons" aren't really links (yes, they're anchor tags under the hood), they're just an object on which a click handler is registered.
