### ISSUE TITLE
Unable to use library when installing with bower

### ISSUE THREAD

**Issue by tno2007** [angular-ui/bootstrap#3783]
when i use bower install ui-bootstrap... there is no ui-bootstrap-custom-tpls javascript so i am unable to use when installing with bower

**Comment by pkozlowski-opensource** [comment]
There is no such thing as ui-bootstrap-custom-tpls - if you are unsure which file to use, stick with https://github.com/angular-ui/bootstrap-bower/blob/master/ui-bootstrap-tpls.min.js

And be sure to check installation instructions: https://github.com/angular-ui/bootstrap#installation
