### ISSUE TITLE
Why datetimepicker popup is loaded in DOM whereas user doesn't opened it yet ?

### ISSUE THREAD

**Issue by cyrilgandon** [angular-ui/bootstrap#3784]
The visibility of the popup is toggled via the display style attribute block or none.
https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/popup.html
`ng-style="{display: (isOpen && 'block') || 'none'`

This is problematic with a page with many datetimepicker available, the page loads terribly slow, 10 seconds for 50 datetimepicker. Every datetimepicker load in the DOM (and so Angular and his thousand of watchers) a lot of elements.

Can we load it in DOM only on demand via ng-if instead, or is there consequences I didn't see ?

Proposition :

`ng-if="isOpen"`

**Comment by pkozlowski-opensource** [comment]
Duplicate of #2613 and #3451 - there are PR(s) in the works that address this pb.

**Comment by vgallur** [comment]
I'm using this workaround while the issue is totally resolved. It works in my use case, but perhaps breaks in other situations. In the next line:

`<li ng-if="isOpen" ng-transclude></li>`

**Comment by cyrilgandon** [comment]
I've implemented that PR:

https://github.com/angular-ui/bootstrap/pull/3666

It works nicely.
