### ISSUE TITLE
Dropdown toggling not working with ngTouch (angular 1.3.16)

### ISSUE THREAD

**Issue by Sankluj** [angular-ui/bootstrap#3793]
> Angular: 1.3.16
> ui-bootstrap version: 0.13.0

Hi,

The ```dropdown``` directive with the additional ```dropdown-toggle``` directive doesn't seem to be working on touch device when ```ngTouch``` is loaded as a dependency.

plunkr demonstrating the issue:  http://plnkr.co/edit/WlLwSCymbf6Xbbr4H280
It can also be reproduced by using the chrome developer tools and selecting a touch capable device.

Many thanks for your work on this awesome library :)

**Comment by rvanbaalen** [comment]
Please provide a simple plunkr so we can easily test this.

**Comment by Sankluj** [comment]
I've linked one in my first post. Isn't that alright?
Thanks for your reply.

**Comment by rvanbaalen** [comment]
My bad. I'll remove these comments.

**Comment by avaragado** [comment]
I'm seeing the same problem. I believe ngTouch's ngClick prevents the click event that normally closes the menu from propagating. See https://docs.angularjs.org/api/ngTouch/directive/ngClick

The workaround in @Sankluj's plunkr works fine for me.

**Comment by kamilbrk** [comment]
+1

**Comment by wesleycho** [comment]
I am not sure there is anything we can do about the ngTouch problem in this case. I think a documentation update couldn't hurt though to note that this is something that one would have to work around.

**Comment by wesleycho** [comment]
Interestingly, this looks fixed on `master` with UI Bootstrap and with angular 1.4.

Closing as fixed.

**Comment by sime** [comment]
@wesleycho I was about to log this same issue, please re-open this issue.

I have updated @Sankluj plunkr with Angular 1.4.8 and UI Bootstrap 0.14.3.

http://plnkr.co/edit/4WN0L0O1XzQUYaqvVDam?p=preview

Note: If testing on desktop, please switch to 'device mode' to simulate touch events.

**Comment by kotmatpockuh** [comment]
@sime
same to me...

**Comment by avaragado** [comment]
Still a problem with UI Bootstrap 1.0.3.

**Comment by wesleycho** [comment]
I took a look at this issue again within the past few weeks - there is nothing we can do here due to how ngTouch decorates ng-click to call `event.stopPropagation` on click events.

See the the Known issues section in the documentation of the dropdown component: https://angular-ui.github.io/bootstrap/#/dropdown
