### ISSUE TITLE
tab activation and visibility watches

### ISSUE THREAD

**Issue by vitaly-t** [angular-ui/bootstrap#3796]
I have a directive that represents a UI element that needs to update its size once the containing tab is activated.

Typically, it is achieved by using the following approach within the directive `link` function:
```javascript
            scope.getInfo = function () {
                return {
                    visible: elem.is(':visible'),
                    width: elem.width(),
                    height: elem.height()
                };
            };
            scope.$watch(scope.getInfo, function (val)  {
                // do the update here;
            }, true);
```
So, any change in `width` / `height` or `visibility` would trigger the required update.

However, when a tab is activated, somehow all elements on that tab are failing to detect any change.

Any idea as to what is the reason for that?

To put it otherwise... why the following directive fails to detect activation of the tab it resides on?

```javascript
app.directive('test-active', [function () {
    return {
        restrict: 'EA',
        scope: {},
        template: '<div>Hello!</div>',
        link: function (scope, elem) {
            scope.getInfo = function () {
                return {
                    visible: elem.is(':visible'),
                    width: elem.width(),
                    height: elem.height()
                };
            };
            scope.$watch(scope.getInfo, function (val) {
                console.log("Active", val); // doesn't trigger on tab activation;
            }, true);
        }
    };
}]);
```

**Comment by rvanbaalen** [comment]
Please reproduce this scenario in a plunkr for us to investigate.

**Comment by wesleycho** [comment]
Why not just watch for when `tab.active` is `true`?

**Comment by vitaly-t** [comment]
@wesleycho imagine a generic/reusable directive that needs to change its size and/or dimension when it becomes visible. A directive as such can only do so in Angular by watching for `elem.is(':visible')` flag.

So, first of all, such a directive knows nothing about tabs, and it can be placed anywhere.

Second, your tab event `tab.active` happens before its content has become visible.

I've been using such directive in various places, and it worked, till I tried placing it into a tab, and suddenly, it no longer works, watch for elem.is(':visible')` doesn't trigger when the tab is activated. I wonder why....

To prove that something is wrong there, I used a timer as a hack, which does pick up a change in the flag, just not the watch.

I can't say for sure if the issue is within the tab directive or angular itself. I'm using version `1.3.16`

**Comment by pkozlowski-opensource** [comment]
IMO observing visibility property of a DOM element is a terrible idea, as it will touch DOM element properties (and potentially call reflow) on each $digest cycle - actually 2 times per $digest cycle on average. This means a slow, slow application. This would be equivalent of pooling DOM for visibility changes, I can see people doing such hacks, ex.: https://github.com/shaunbowe/jquery.visibilityChanged/blob/master/visibilityChanged.js

I don't think we want to make it any easier for people to apply such hacks. Feel free to investigate this further and if you narrow down the pb you can send a PR to the relevant repo. But this doesn't sound like sth we want to support / investigate. I would advise to see if you can't structure your UI differently, for example by subscribing to events that cause size / position change.

Closing this one as this is not sth in the scope of this project.

**Comment by snimavat** [comment]
We have exactly same problem, when tab is activated, and digest cycle runs, and watch expression function is called, the element :visible is still false. so watch listener does not execute. the element :visible becomes true only few milli seconds after the tab is activated, and hence the watcher function doesnt pick the flag and listener is not called untill next digest cycle (at this point element.is(":visible")) would have turned true)
