### ISSUE TITLE
Bump up on npmjs.org

### ISSUE THREAD

**Issue by piotrd** [angular-ui/bootstrap#3798]
Could you please bump up the version on npmjs.org to 0.13.x? Thanks.

**Comment by mathpere** [comment]
+1

**Comment by rvanbaalen** [comment]
We're currently working on officially supporting the npm package. We haven't released the current npm package.

Stay tuned for an update soon.

**Comment by pho3nixf1re** [comment]
I believe this is a duplicate of #3632.

**Comment by piotrd** [comment]
Indeed, it is. I don't know how I missed that. Sorry. Closing this one then.
