### ISSUE TITLE
Anchors empty href under angular 1.4 and NewRouter components redirects to root /

### ISSUE THREAD

**Issue by alexrada** [angular-ui/bootstrap#3799]
I had to change templates for tabset directive because clicking on tabs would redirect me to root.
Because of the empty "href". I had used this before and href wasn't added

![image](https://cloud.githubusercontent.com/assets/1150584/8103859/895e0c2c-1034-11e5-8883-4ad05ea5bdba.png)

**Comment by rvanbaalen** [comment]
Please provide a plunkr so we can reproduce this scenario.

**Comment by wesleycho** [comment]
Keep in mind that we are currently not supporting Angular 1.4, but it is certainly on our todo list after we roll out bug fixes and performance improvements with our next release.

**Comment by realityking** [comment]
This should probably be reported as a bug against Angular. There are many apps relying on it. And there's no great alternative way to achieve the same thing.
