### ISSUE TITLE
CORS request for templates fails

### ISSUE THREAD

**Issue by kmccargar** [angular-ui/bootstrap#3802]
I have an angular app that can switch to other instances of the same app. 

To reduce load on the first instance, I wrote a header interceptor that changed the request url to the second instance to load REST data and templates. 

Angular fails to find bootstrap resource in $templateCache. All other resources are found.

For example,

`GET http://localhost:9001/template/pagination/pagination.html 404 (Not Found)
angular.js:10072 Error: [$compile:tpload] Failed to load template: http://localhost:9001/template/pagination/pagination.html
http://errors.angularjs.org/1.2.26/$compile/tpload?p0=http%3A%2F%2Flocalhost%3A9001%2Ftemplate%2Fpagination%2Fpagination.html
    at VALIDITY_STATE_PROPERTY (angular.js:78)
    at angular.js:6919
    at angular.js:8120
    at deferred.promise.then.wrappedErrback (angular.js:11582)
    at deferred.promise.then.wrappedErrback (angular.js:11582)
    at angular.js:11715
    at Scope.$get.Scope.$eval (angular.js:12702)
    at Scope.$get.Scope.$digest (angular.js:12514)
    at Scope.$get.Scope.$apply (angular.js:12806)
    at done (angular.js:8379)(anonymous function) @ angular.js:10072$get @ angular.js:7364deferred.promise.then.wrappedErrback @ angular.js:11585deferred.promise.then.wrappedErrback @ angular.js:11582(anonymous function) @ angular.js:11715$get.Scope.$eval @ angular.js:12702$get.Scope.$digest @ angular.js:12514$get.Scope.$apply @ angular.js:12806done @ angular.js:8379completeRequest @ angular.js:8593xhr.onreadystatechange @ angular.js:8532
angular.js:10072 Count: 0`

**Comment by wesleycho** [comment]
The intention is to bundle the templates into $templateCache when deploying the application. If you switch to use https://github.com/angular-ui/bootstrap-bower/blob/master/ui-bootstrap-tpls.js instead (or the minified form), this should resolve this issue.

**Comment by kmccargar** [comment]
We are using that file.

In index.html:
`<script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>`

In app.js:
`angular.module('webApp', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngRoute',
    'ngSanitize',
    'ngTouch',
    'pascalprecht.translate',
    'ui.bootstrap',
    'ngStorage',
    'angular-underscore',
    'zeroclipboard',
    'ui.select',
    'rt.debounce'
  ])`

Is there a restriction on the bundled templates that would stop them being served to another instance? Other templates in  $templateCache are being served correctly.

**Comment by pkozlowski-opensource** [comment]
There must be something wrong going with your env or you've got broken downloaded file. Try to isolate the pb in plunker - otherwise there is next to zero chance that we will be able to help you...

Other idea: maybe some part of your code is removing things from $templateCache?

**Comment by RobJacobs** [comment]
@kmccargar I notice in your first post the url listed is http://localhost:9001.  Do you still have these problems when the files are being served from a url with a fully qualified domain name?  I assume with an address of http://localhost:9001 you are running from a dev server.

**Comment by wesleycho** [comment]
Closing as a support issue - we can try to help if more information is provided, including a reproduction, but otherwise this is not an issue with UI Bootstrap itself.
