### ISSUE TITLE
Tooltips: tooltip-enabled seems to be broken

### ISSUE THREAD

**Issue by jfizz** [angular-ui/bootstrap#3813]
I tried using tooltip-enabled in a project of mine so that I could display a tooltip conditionally. I couldn't get it to work so I headed to the docs. I tried the example in the docs and it isn't working either:

![screen shot 2015-06-12 at 5 22 56 pm](https://cloud.githubusercontent.com/assets/6319548/8142120/01616414-1128-11e5-94f8-7c445ceab1a6.png)

**Comment by wesleycho** [comment]
It appears to be working as far as I can tell in [this Plunker](http://plnkr.co/edit/vtwHzVnXWsawOkBQLkVV?p=preview). Can you reproduce this in Plunker or give instructions on how to reproduce it exactly?

**Comment by jfizz** [comment]
sorry, I wasn't aware that you had to re-activate the trigger for it to become hidden. I just kept hovering over the input while typing and I figured it should disappear when it only disappears after triggering another 'mouseenter' event after typing. seems that the functionality I want has yet to be implemented: https://github.com/angular-ui/bootstrap/issues/590. sorry for the confusion!
