### ISSUE TITLE
Tabs: tab disable not working on production

### ISSUE THREAD

**Issue by krayevidi** [angular-ui/bootstrap#3814]
On development everything works well. But after run `$ grunt build` the tab that should be disabled turns enabled.

This bug not reproduces on plnkr. So I created simple repo that show my problem. 

steps to reproduce:

1. clone my repo
`$ git clone https://github.com/krayevidi/angular-bootstrap-ui-tabs-bug`

2. install dependencies
`$ npm install` 
`$ bower install`

3. build project
`$ grunt build`

4. run 'production' server
`$ node server.js`

Now open in browser "localhost:5000" and you'll see two tabs. Second tab should be disabled but it's not. Also if you run development server `$ grunt serve` and open in browser "localhost:5000" you'll see second tab is disabled.
Tested on angular: 1.3.0, angular-bootstrap: 0.13.0 and angular: 1.2.24 angular-bootstrap: 0.12.0

Can anyone help me?
Thanks in advance)

**Comment by wesleycho** [comment]
Use `ng-disabled`, not `disabled` - `disabled` is an HTML5 attribute, it does not make sense to set a value on it, since the only valid use of it is `disabled` or the absence of the attribute.

**Comment by krayevidi** [comment]
@wesleycho I missed up the line in docs "Note that this was previously the disabled attribute, which is now deprecated." But it's still not work with angular: 1.2.24 and angular-bootstrap: 0.13.0. Thank you. I'll update angular.

**Comment by wesleycho** [comment]
0.13.0 supports only 1.3.x - is this still an issue you say?

**Comment by krayevidi** [comment]
No. Could you close it please. I'm sorry. Thanks.

**Comment by rvanbaalen** [comment]
@krayevidi you can also close it yourself :wink: But I did it for you now :+1:

**Comment by krayevidi** [comment]
@rvanbaalen thanks))
