### ISSUE TITLE
"$modalInstance" not is working

### ISSUE THREAD

**Issue by donnes** [angular-ui/bootstrap#3815]
##### Function to open modal
```
$scope.open = function () {
	var addMember = $modal.open({
		templateUrl: 'templates/modal/add-team-member.html',
		controller: 'AddMemberCtrl'
	});
}
```

##### Modal controller
```
app.controller('AddMemberCtrl', function($scope, $modalInstance) {
	$scope.title = "Modal";
	$scope.content = "Teste";

	$scope.ok = function() {
		$modalInstance.dismiss('cancel');
	}

	$scope.cancel = function() {
		$modalInstance.dismiss('cancel');
	}

});
```

#### Error
![screenshot_3](https://cloud.githubusercontent.com/assets/9506146/8143884/11be64e4-1199-11e5-8888-739bbcb243bd.png)

**Comment by wesleycho** [comment]
This needs a Plunker.

However, I notice that the error is coming from Angular 1.4 - we are not currently yet supporting 1.4.

**Comment by pkozlowski-opensource** [comment]
I would suspect that a controller is referenced in the modal's template through ngController... but as @wesleycho noted - impossible to confirm without a minimal reproduce scenario. Please provide one or it isn't actionable....

**Comment by donnes** [comment]
Sorry @wesleycho and @pkozlowski-opensource , I forgot to reproduce the error.
See: http://plnkr.co/edit/puYm0zkETcLweX80zkfk

**Comment by wesleycho** [comment]
As @pkozlowski-opensource suspected, you are using ng-controller in the template - this is unnecessary, and the source of your error.

[Here](http://plnkr.co/edit/fZigjUysPetiziLDbGUX?p=preview) is a working Plunker for you.

**Comment by donnes** [comment]
I understood now.
I really didn't realize the "ng-controller" I think it's the lack of sleep.

Well, thank you very much guys!
