### ISSUE TITLE
Displaying the No Items Found Message

### ISSUE THREAD

**Issue by ErBahuguna** [angular-ui/bootstrap#3816]
Hello,

I would like to thanks first for such pagination directive.
I have one question
1.  I want to display the message No Items Foundi if the user search is not available or say data.length==0.

![image](https://cloud.githubusercontent.com/assets/9461432/8147394/b57f7dde-1284-11e5-89dc-6cf5d4f53307.png)

Thank You.

**Comment by wesleycho** [comment]
Why not use ng-show/ng-hide?

**Comment by pkozlowski-opensource** [comment]
Or `ngIf` (would probably require a wrapper element). I don't think that any special message should be part of the standard directive - but you can modify the existing one to suit your needs of course.

**Comment by ErBahuguna** [comment]
Okay Thank You so much. now its working for me.


On Sun, Jun 14, 2015 at 6:50 PM, Pawel Kozlowski <notifications@github.com>
wrote:

> Or ngIf (would probably require a wrapper element). I don't think that
> any special message should be part of the standard directive - but you can
> modify the existing one to suit your needs of course.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/bootstrap/issues/3816#issuecomment-111826881>
> .
>



-- 
@Bahuguna Goyal
