### ISSUE TITLE
dropdown-append-to-body doesn't work with .dropdown-menu-right

### ISSUE THREAD

**Issue by bytasv** [angular-ui/bootstrap#3820]
Hello,

When adding `dropdown-append-to-body` to `dropdown` component and inner menu has `.dropdown-menu-right` class (for right side alignment) the dropdown menu position is set incorrectly. I've checked source code and noticed that when calculating position for `dropdown-append-to-body` option only `left` property is used, hence not positioning correctly the menu... It should be using `right` instead of left..

**Comment by cpitt** [comment]
Should be able to fix it by checking if element has class dropdown-menu-right and subtracting el width from left offset on line 126ish of src/dropdown/dropdown.js . I'm unfortunately not in a position to try it right now if someone wants to take a crack at it in the mean time.

**Comment by rvanbaalen** [comment]
Please demonstrate your issue in a plunkr.

**Comment by rysilva** [comment]
Does this really need a plunkr?  It's really straightforward.

I wrote the append-to-body feature of dropdown, and I actually just came across this issue myself.

Here's the plunkr so we can get that out of the way: http://plnkr.co/edit/21xjDthnZsbC2StDy2VY?p=preview

**Comment by schmuli** [comment]
I tried out a fix, by looking for the dropdown-menu-right class, and changing the calculation for the CSS positions, so in [dropdown.js](https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L165) instead of:

```
  if ( appendToBody && self.dropdownMenu ) {
      var pos = $position.positionElements(self.$element, self.dropdownMenu, 'bottom-left', true);
      self.dropdownMenu.css({
        top: pos.top + 'px',
        left: pos.left + 'px',
        display: isOpen ? 'block' : 'none'
      });
    }
```

I used:

```
        if (appendToBody && self.dropdownMenu) {
            var rightalign = self.dropdownMenu.hasClass('dropdown-menu-right');
            var pos = $position.positionElements(self.$element, self.dropdownMenu, 'bottom-left', true);
            var css = {
                top: pos.top + 'px',
                display: isOpen ? 'block' : 'none'
            };
            if (!rightalign) {
                css.left = pos.left + 'px';
                css.right = 'auto';
            } else {
                css.left = 'auto';
                css.right = (window.innerWidth - (pos.left + self.$element.prop('offsetWidth'))) + 'px';
            }
            
            self.dropdownMenu.css(css);
        }
```

I didn't change the <code>$position</code> service, as I am setting the <code>right</code> property, and that is not always relevant.

**Comment by mariocasciaro** [comment]
I'm having the same issue.@schmuli it would be nice if you could send a PR for your fix so everybody can take advantage of it.

**Comment by schmuli** [comment]
I wanted to first check that this is a valid fix, I'll try to get a PR ready in the next couple of days.

**Comment by mariocasciaro** [comment]
:+1: 
BTW, I tried it as well and it seems working perfectly

**Comment by schmuli** [comment]
I added a PR #3913, with this fix, thanks for the update.
