### ISSUE TITLE
Bootstrap 3.3.4 tootlip-html-unsave deprecated

### ISSUE THREAD

**Issue by emasch** [angular-ui/bootstrap#3821]
After an CSS-Update to bootstrap 3.3.4. I got a warning, that the use of tooltip-html-unsafe is deprecated and that I should use tooltip-html instead.

Then I tried to use tootlip-html but nothing happens. 

I use Bootstrap CSS 3.3.4 and angular-ui/bootstrap v0.13.0

**Comment by rvanbaalen** [comment]
`tooltip-html` takes an Angular expression as it's value.

And upgrading your Twitter Bootstrap CSS dependency couldn't have produced that deprecated warning.  Even though this seems to be a support request, provide a plunkr and I'll take a look.

**Comment by wesleycho** [comment]
The warning is new as of UI Bootstrap 0.13.0 - this is because its usage is now deprecated, and it is recommended to use the `tooltip-html` or `tooltip-template` directives instead.

**Comment by wesleycho** [comment]
Closing as a support issue, feel free to provide more information if you'd like to have help seeing any problems & the fixes for them.
