### ISSUE TITLE
Typeahead does not support ng-model-options="{getterSetter: true}"

### ISSUE THREAD

**Issue by pkarikh** [angular-ui/bootstrap#3823]
AngularJS: v1.3.
ui-bootstrap: v 0.13.

Looks like when I set `ng-model-options="{getterSetter: true}" ` typeahead for some reasons replaces getter/setter method with selected value.

Here the plankr: http://plnkr.co/edit/a3Ld9eVmysrt8RsyzbhX?p=preview
Steps:
0) Note from the sources that `suggestions.value` is a getter/setter. 
1) Type "one" or "two"
2) Note that `suggestions.value` is not a function any more. It is a choosen value from typeahead suggestion.

**Comment by pkarikh** [comment]
Looks like this fix works.

If we replace this line: `var $setModelValue = $parse(attrs.ngModel).assign;`
with this code:

     var $setModelValue = (function() {
        var options = $parse(attrs.ngModelOptions)(),
          parsedNgModel = $parse(attrs.ngModel),
          parsedNgModelAssign = $parse(attrs.ngModel).assign,
          ngModelSet;
          if (options && options.getterSetter) {
          var invokeModelGetter = $parse(attrs.ngModel + '()'),
            invokeModelSetter = $parse(attrs.ngModel + '($$$p)');

          ngModelSet = function($scope, newValue) {
            if (angular.isFunction(parsedNgModel($scope))) {
              invokeModelSetter($scope, {
                $$$p: newValue
              });
            } else {
              parsedNgModelAssign($scope, modelCtrl.$modelValue);
            }
          };
        }

        return ngModelSet || parsedNgModelAssign;
      })();
everything works fine, all tests pass and now typeahead knows how to work with `ngModelOptions={getterSetter: true}`.
Here the commit: https://github.com/pkarikh/bootstrap/commit/6baf354f4683c8ca1ba5b74eadd10ff6d9a68da3
And here the plnkr: http://plnkr.co/edit/j3ZQS0gAraVxwmMOWL0l?p=preview

**Comment by wesleycho** [comment]
@pkarikh: I believe I have a better fix in #3865, take a look at it and let me know if it satisfies your needs whenever you get the chance.

**Comment by pkarikh** [comment]
@wesleycho works for me. Thank you! Your approach is much more clearer.
