### ISSUE TITLE
Timepicker: Invalid value in the field is removed when focus lost

### ISSUE THREAD

**Issue by lauribenno** [angular-ui/bootstrap#3825]
Timepicker shows behaviour that is inconsistent with datepicker (and other input fields as well) when handling invalid input.

Steps to reproduce:
* Enter 25 in first field
* Tab to second field
* Enter 6 => first field is changed to 2 => should stay 25 and marked as invalid

Expected behaviour: Invalid fields are marked but invalid input is still displayed in the field.
Same problem in the other direction as well.

**Comment by rvanbaalen** [comment]
First step to reproduce: provide us with a plunkr.

**Comment by wesleycho** [comment]
This is easily reproduced on the basic Plunker, as seen [here](http://plnkr.co/edit/lypWdSoX8uXCTHgyFo4L?p=preview).

This is certainly unexpected behavior.
