### ISSUE TITLE
Tab select/deselect methods should pass reference to tab

### ISSUE THREAD

**Issue by viveleroi** [angular-ui/bootstrap#3826]
Currently, the `tabset` directive allows us to define select/deselect callbacks `select="tabChange()`. However, there's nothing on the scope that can be easily passed as an argument which references the  tab.

What I'd like to see is something along the lines of:

    select="tabChange($tab)"

Where `$tab` is the tab object with `active`, `heading`, and other properties. This is especially useful for those not using an ng-repeat to generate tabs.

**Comment by wesleycho** [comment]
Closing in favor of #4836 - keep an eye on that issue

**Comment by asgh** [comment]
I don't know if there is a better way, but this worked for me:

    ....deselect="func($event, $selectedIndex, this)">

And the javascript:

    ....function($event, $selectedIndex, caller) {
      caller.$parent.tabset.active = $selectedIndex;
    }

You can get a reference to the tabset, not the tab. But you can look at `active` to find the tab, and $selectedIndex to find the new tab.
