### ISSUE TITLE
"Unknown provider" error when using typeahead

### ISSUE THREAD

**Issue by fplgusmao** [angular-ui/bootstrap#3832]
Hello,

My app is using `ngRoute` and has two views. On the first view, it has a `datepicker` and everything works fine. On the second view, it has a `typeahead`, and when that view loads, it gives me the following error:

`Unknown provider: $templateRequestProvider <- $templateRequest <- typeaheadMatchDirective`

Now, I know that it's supposed to be related to not having declared the correct dependencies on the respective module, but it may be more complex than that, apparently.

Each of these views has a module for their directives, and in each one I declare the `ui.bootstrap` dependency, as shown:

    var mmQuestionnaireDirectives = angular.module('mmQuestionnaireDirectives', ['ui.bootstrap']);

    var mmMapsDirectives = angular.module('mmMapsDirectives', ['ui.bootstrap']);

I've tried to declare the dependency right away on the app module, which contains the routing configuration, but it does nothing. And yes, I am adding the dependency to the file on my `index.html`.

    <script src="lib/ui-bootstrap/ui-bootstrap-tpls-0.13.0.min.js"></script>

Am I doing something wrong?

**Comment by wesleycho** [comment]
Note, UI Bootstrap requires Angular 1.3 currently.

**Comment by fplgusmao** [comment]
Ups, you may be right. I now see that I'm still using 1.2. I'll be changing it soon and I'll get right back with the result

**Comment by fplgusmao** [comment]
Ok, so that was problem... Feeling a little bit stupid now.

Thanks a lot!
