### ISSUE TITLE
Dismissible popover

### ISSUE THREAD

**Issue by sime** [angular-ui/bootstrap#3846]
Feature request.

Use the focus trigger to dismiss popovers on the next click that the user makes.

http://getbootstrap.com/javascript/#dismiss-on-next-click

**Comment by rvanbaalen** [comment]
To be more specific: dismiss popover when the focussed popover trigger element loses it's focus.

**Comment by sime** [comment]
Thanks!

Looking at the tooltip focus behavior I wasn't able to reproduce it outside of a input element and I believed that is where the confusion came. A quick plunkr with a `popover-trigger="focus"` proves otherwise.

Thanks for the tip.

**Comment by rvanbaalen** [comment]
You're welcome :+1:
