### ISSUE TITLE
Today button should reflect Min / max dates

### ISSUE THREAD

**Issue by AndersMalmgren** [angular-ui/bootstrap#3847]
Today button is active even if min or max dates says otherwise (Today is not a valid date)

**Comment by rvanbaalen** [comment]
Please provide more information and a plunkr. This is very hard to understand or debug.

**Comment by AndersMalmgren** [comment]
http://plnkr.co/edit/ooN4ICQ3QCIW8UQaQsfQ?p=preview

Today button is not disabled even if today is invalid

**Comment by DavidePastore** [comment]
:+1:

**Comment by wesleycho** [comment]
This looks implemented in `master` currently, as can be seen in https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L130 and https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/popup.html#L5
