### ISSUE TITLE
Carousel - no animation when edit in plunker.

### ISSUE THREAD

**Issue by limonte** [angular-ui/bootstrap#3850]
There's the nice animated example of carousel on plugin homepage:

![recorded](https://cloud.githubusercontent.com/assets/6059356/8333995/decf3eb8-1a95-11e5-9fef-347d430d21fa.gif)

But when I click 'Edit in plunker' button there's no animaton in plunker example:

![recorded](https://cloud.githubusercontent.com/assets/6059356/8334011/f807094c-1a95-11e5-834c-f61fc90b38e5.gif)

Same issue I have in my project. Tested with Angular 1.3.* and angular 1.4.*.

**Comment by rvanbaalen** [comment]
That's because since 0.13, you need to include `angular-animate` in your project if you want animations:

http://plnkr.co/edit/0k1HyBcT87MXSRZ8pQXD?p=preview
