### ISSUE TITLE
New popover-template not working with Angular 1.3.8

### ISSUE THREAD

**Issue by jadarnel27** [angular-ui/bootstrap#3852]
Here is a plunkr for the issue: http://plnkr.co/edit/spe6hpCHzGhjxUFVJIHl?p=preview

Clicking the button (to produce the popover) does nothing (no errors, but also no popover).  Compare to [this plunkr](http://plnkr.co/edit/nbbfpG2TjB3uvSORsSAJ?p=preview) where the popover-template is working.  The only difference I can see is that it's using Angular 1.3.15.

The GitHub site for UI Bootstrap says "*requires AngularJS 1.3.x, tested with 1.3.13*," so I suppose there was some kind of breaking change between Angular 1.3.13 and 1.3.8.

**Comment by dovy** [comment]
So I found a workaround.

If you declare the exact template in your view, be it popOverTemplate.html, and declare it within the HTML, it fails. However, if you declare a scope variable inside your controller, and call that as your template, the popover works...

**Comment by jadarnel27** [comment]
I definitely don't understand everything that's going on here, but maybe this will help point things in the right direction.  The reason the popover isn't displaying is here (in the `show()` method):

    // Don't show empty tooltips.
    if ( !(options.useContentExp ? ttScope.contentExp() : ttScope.content) ) {
      return angular.noop;
    }

In the case of using a popoverTemplate, `useContentExp` is true; so the result of `contentExp()` is used to determine if the popover (tooltip) is "empty."  Here's that function:

    ttScope.contentExp = function () {
      return scope.$eval(attrs[type]);
    };

The value of `type` is "popoverTemplate" and the value of the `popoverTemplate` property of the `attrs` object is the name of / path to the template ("*app/template/my-popover-template.html*" in my example).  

Calling `$eval` on that returns `NaN`, which is falsey - thus the popup doesn't display.

**Comment by jadarnel27** [comment]
Actually, I think this fixes the problem:

    ttScope.contentExp = function () {
      return scope.$eval(attrs[type]) ? scope.$eval(attrs[type]) : attrs[type];
    };

If popover-template was set to a valid expression, then evaluate that expression (maybe a scope function that generates the template link) and return it.  Otherwise, it *is* the template link, so just return that value.

**Comment by jadarnel27** [comment]
I will go ahead and submit a pull request to that effect with some unit tests that expose the issue.

**Comment by jadarnel27** [comment]
I submitted a pull request based on this report (although the solution wind up being slightly more complex than what I mentioned above).  I also updated my original plunkr repeating the problem, as it was busted: http://plnkr.co/edit/OxpB4cyjJpZGWzTBGqJA?p=preview

I'm really grateful for all the work you folks have done on this library - I use it frequently at work, and it is excellent.  Also, the unit testing is great too; that really helped me understand the impact of the change I was trying to make.

**Comment by RobJacobs** [comment]
If you wrap the template string in single quotes it works, updated [plunkr](http://plnkr.co/edit/6cLx53flWOxWiDRytTKl?p=preview)

**Comment by jadarnel27** [comment]
Oh, wow - that's a pretty simple workaround, @RobJacobs.  Thanks!

**Comment by dovy** [comment]
Should of guessed that what was going on. I was setting the variable in my controller to pass as a string.

Should we fix it long-term though, or is this the solution?

**Comment by pkozlowski-opensource** [comment]
I don't think there is anything to fix here - this attribute accepts an expression so if anyone wants to pass a string literal it needs to get quoted. This is exactly how `ngInclude` behaves.

**Comment by 360disrupt** [comment]
None of the examples I found do work for me. I use `"angular-ui-router": "~0.2.13",` `"angular-bootstrap": "0.12.x",` &  `"angular": "~1.3.4",`

Same problem no error msg nothing happens. All other popup types besides the one with template works.

## ui-view/HTML
```
<button popover-template="dynamicPopover.templateUrl" popover-title="{{dynamicPopover.title}}" class="btn btn-default">Popover With Template</button>

<script type="text/ng-template" id="myPopoverTemplate.html">
    <div>{{dynamicPopover.content}}</div>
    <div class="form-group">
      <label>Popup Title:</label>
      <input type="text" ng-model="dynamicPopover.title" class="form-control">
    </div>
</script>

<button class="btn btn-default" popover-template="'app/template/my-popover-template.html'" popover-placement="right">Popover</button>
<script type="text/ng-template" id="app/template/my-popover-template.html">
  <div>
    Popover content
  </div>
</script>

<button class="btn btn-default" popover-template="'manage-users/xy.html'" popover-placement="right">Popover</button>
```

## templatecache.js
`$templateCache.put("manage-users/xy.html","<h1>BAAAAM</h1> ...);`

## controller
```
angular.module "register"
  .controller "ManageUsersCtrl", ($scope, $rootScope, $http, manageUsersService) ->
    $scope.dynamicPopover = {
      content: 'Hello, World!',
      templateUrl: 'myPopoverTemplate.html',
      title: 'Title'
    }
```
