### ISSUE TITLE
Dropdown auto-close outsideClick issue when menu items change

### ISSUE THREAD

**Issue by ajrind** [angular-ui/bootstrap#3854]
Hello,

I'm working on creating a dropdown menu that uses an input box to search through that menu. 
I'm trying to make it so that as the user clicks on options in the menu, they are removed from that menu. I need to make the menu stay open during this process (i.e. be able to remove multiple items from the menu without it closing).  Using auto-click="outsideClick" does not work when items are removed from the menu using splice().

I created a minimal reproduce scenario plunkr here: http://plnkr.co/edit/OCNhSxesFd9H0hbN76WH?p=preview

This seems to be a bug; though, perhaps there is another preferred way of doing this.

Thanks,
Andrew

**Comment by wesleycho** [comment]
You should pass `$event` to your callback in your `ng-click` and call `$event.stopPropagation()` in the callback.

[Here](http://plnkr.co/edit/jUUSIwCFeX26duCbjPZh?p=preview) is an example with this in action.

**Comment by ajrind** [comment]
Awesome.  Thanks for your help!

**Comment by kaige11** [comment]
you solved my problem, thanks a lot

**Comment by kaige11** [comment]
but why? 难死宝宝了!

**Comment by kaige11** [comment]
you solved my problem, thanks a lot, but why? 难死宝宝了!
