### ISSUE TITLE
Popover with custom template doesn't auto close when clicking outside

### ISSUE THREAD

**Issue by yaring** [angular-ui/bootstrap#3855]
https://angular-ui.github.io/bootstrap/#/popover

There is option `popover-trigger="focus"` which closes the popover on any click inside or outside the popover, this behaviour seems to be wrong when using custom template with inputs for example.

Please look on angular-strap example, and the third (red one):
http://mgcrea.github.io/angular-strap/#/popovers
Over there after open the popover when click inside the popover nothing happens as it should be, but when you clicking outside it disappears.
Maybe related: https://github.com/mgcrea/angular-strap/pull/1076

I can't find and similar behaviour on ui-select popover.

Plnkr:
http://plnkr.co/edit/iJJ3LCpWR675dUU0Rl5R?p=preview

**Comment by yaring** [comment]
Never mind, It seems supported already :)
popover-trigger="focus"
:+1: :+1: :+1:

**Comment by austinpray** [comment]
Yep seeing this as well.

**Comment by yaring** [comment]
I've added plnkr which demonstrates focus trigger, try clicking on the input after opening the custom template popover.

**Comment by icfantv** [comment]
@yaring @austinpray, the trigger is not on the popover, but on the element on which the popover directive is placed.  Thus, when you click on the popover template, the popover element is losing focus and the popover closes.

The default trigger for popovers is `click` (as you can see via the [UI Bootstrap Example](https://angular-ui.github.io/bootstrap/#/popover) - Look at the `Popover With Template` button example.  You will see that the popover will not close unless the `Popover With Template` button is clicked again.

@wesleycho, I think we can close this.

**Comment by wesleycho** [comment]
As pointed out, one has to set the popover trigger to be `focus`, so that on `blur` it will close.

**Comment by yaring** [comment]
@icfantv @wesleycho , the problem with the `click` trigger is that it's not closes the popover when clicking outside but only clicking on the `Popover With Template` button.

As I showed on angular-strap it's closing it when clicking outside of the popover.

**Comment by wesleycho** [comment]
One could potentially customize the `click` trigger, but automatically changing the click trigger to close on outside click would be a poor breaking change since it changes expectations in behavior.

This perhaps requires some more thought on how best to support this.

**Comment by kikar** [comment]
I have the same problem, I need a popover with an input field, but that it closed when clicking outside of the popover and not again on the button that activates it.
Is there any progress on this? Any suggestion on how could I make it?

**Comment by LeleDev** [comment]
Same here

**Comment by icfantv** [comment]
With the fix for #590 in place, you guys can now programmatically control when the tooltip is open and closed via the `tooltip-is-open` option.  Note that this change is in 0.13.4-SNAPSHOT and not in 0.13.3.  We should be releasing 0.13.4 shortly.

**Comment by pr-dev-repo** [comment]
@kikar @LeleDev Can you please share if you found? i am having trouble with this. thanks
