### ISSUE TITLE
PopUp Datepicker not working on Demopage

### ISSUE THREAD

**Issue by elpeyotl** [angular-ui/bootstrap#3856]
Hi Guys

Something little. On https://angular-ui.github.io/bootstrap/#/datepicker the popup datepicker is not working. The  max-date is set to "'2015-06-22'". So the user cannot choose a date. I used the code snipped in a project and it was not working anymore. Probably it makes sense to remove the max-date on the demo as it confusing people. 

Cheers
Chris

**Comment by rvanbaalen** [comment]
So, to be clear, the datepicker was working in the demo but wasn't working in your project once you copy/pasted it? Or you just didn't notice the max-date setting and expected that it wasn't there when you copied the code?

**Comment by elpeyotl** [comment]
Yes. The datepicker was working in January. But i Did not notice the max-date setting. It was set at 6/22. So this date passed and now it is not possible to choose a date. I fixed it in my installation, but I think it would be nice to make the selection of the date working on the demo datepicker popup again. Just my 5 cents.

**Comment by wesleycho** [comment]
This should be fixed in `master`, and will reflect live this weekend when 0.13.2 is released.
