### ISSUE TITLE
'modal.closing' never triggered on passed in scope

### ISSUE THREAD

**Issue by olore** [angular-ui/bootstrap#3857]
I am trying to open a modal, passing a scope such that I can listen for 'modal.closing'. However, $on('modal.closing') never triggers. I believe this is because :

1. https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L321 is using $broadcast instead of $emit
2. https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L427 is creating a new child scope 

http://plnkr.co/edit/oL0HojeQzqNBZowzj5WN?p=preview

**Comment by wesleycho** [comment]
What happens is the modal uses the passed in $scope and creates a new one that inherits from it.

Can you explain your use case?

If you need access to it, what you can do is put an `init` function on the controller and use `ng-init` in the modal template to run the initialization function to bind the listener on the appropriate $scope.

**Comment by olore** [comment]
I guess I am really looking for an example that uses 'modal.closing'. I expected to be able to call $modal.open with a scope, then setup a listener on that scope for when the modal closes.

Because the scope passed in gets used to create a new child scope, shouldn't the event use $emit so the event dispatches **up** the scope hierarchy, instead of down? Thus letting me listen for it from the parent scope that I passed in.

**Comment by pkozlowski-opensource** [comment]
Why not using a promise that gets resolved when a modal is closed?

**Comment by olore** [comment]
@pkozlowski-opensource I don't have access to the promise in that part of the code.

I thought the purpose of the event was to be able to know when modals are closed outside of the scope that has access to the promise. Maybe I am reading too much into it. If that's not the purpose, maybe you can help describe to be a scenario where listening for modal.closing would be useful.

Thanks

**Comment by wesleycho** [comment]
Using the promise API is much cleaner in general - the purpose of the broadcasted event is for potential child components to hook into it to potentially be able to abort the the close action, say in the event of a failed exit condition.

I would recommend exposing the promise itself via callback (or whatever more appropriate mechanism in the codebase) into the relevant area of the code to close it. One can also potentially inject the `$modalStack` service and close the modal programmatically through that.

**Comment by olore** [comment]
@wesleycho using 'modal.closing' to "hook in to abort the close action" makes sense. I was trying to wedge it into solve my use case, which, I agree, would be better served via the promise pattern.

Thanks for the explanation.
