### ISSUE TITLE
Progress bars inside modal animates back from 100% in 0.13

### ISSUE THREAD

**Issue by neballer** [angular-ui/bootstrap#3858]
In version 0.13, when opening a modal with a progress bar inside it, the progress bar animates from the end of the bar, to its set value.

http://plnkr.co/edit/McgZm5o4DDJfSedjAfvh?p=preview
Switch the version in the plunk to .12 and you'll see this behavior does not occur.

**Comment by wesleycho** [comment]
This is currently fixed in `master` - here is a [Plunker](http://plnkr.co/edit/vLf8HnhRCZtzMa7F5Xx2?p=preview) using the build off of the current `master` branch.
