### ISSUE TITLE
Datepicker - Date is Always Required?

### ISSUE THREAD

**Issue by hancock808** [angular-ui/bootstrap#3862]
See my Plunkr > http://plnkr.co/edit/1iGDEnnpEOtBPymPPiLS?p=preview

Dates are not required on my form, however when a date is entered then cleared out the form is marked invalid and the user cannot submit.

**Comment by wesleycho** [comment]
This looks like a legitimate bug - this needs to be rewritten to use `ngModel.$validators`

**Comment by onenive** [comment]
@wesleycho , I have a fix to this bug in my forked repo: https://github.com/blendlabs/bootstrap. Should I add tests and submit a PR for this issue?

**Comment by wesleycho** [comment]
I am assuming that [this](https://github.com/blendlabs/bootstrap/commit/55334fb22ba263374508ca08ae5162158d7e2f4b) is the commit?

Feel free to open a PR - I think this is not quite the correct way to fix this though. The proper fix would change the setting of validity to be in `ngModelCtrl.$validators.date` and not manually checking `$attrs.ngRequired`.

**Comment by onenive** [comment]
Would that be to:
1) log the error: "Datepicker directive: "ng-model" value must be a Date object..." regardless of what ng-required is set as
2) remove ngModelCtrl.$setValidity('date', ...) from this.render() and move all the validation logic to ngModelCtrl.$validators.date

**Comment by pavlovt** [comment]
the bug still exists in version 1.3.2 (date is always required for uib-datepicker-popup component)

**Comment by brunosantosnasajon** [comment]
Bug still exists in version 2.0.1. Is this project still maintained?

**Comment by MatheusArleson** [comment]
Bug still happens on version 2.5.6.

I have an optional datepicker field initialized with null value.
When the datepicker is initialized, angular has a $error.date

An null date is an invalid date, but a null value for the model maybe not.
