### ISSUE TITLE
'restrict' for dropdown and dropdownToggle

### ISSUE THREAD

**Issue by djvs** [angular-ui/bootstrap#3868]
Why was this removed?  Broke my code during upgrade.  Manually went in the minified code and added `restrict:'AC'` for both, so that I didn't have to edit every instance of popover in my app.   Using  0.13.0 stable.

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#breaking-changes

It was removed based on the discussion in #2156

**Comment by pkozlowski-opensource** [comment]
BTW: having directives matching CSS classes (`C`) is discouraged in AngularJS, generally speaking.

**Comment by djvs** [comment]
I could go wrong, but I don't thnk this is mentioned on the changelog either.

**Comment by pkozlowski-opensource** [comment]
@djvs I've linked to an entry to a CHANGELOG.....

**Comment by djvs** [comment]
Ah sorry, still waking up.
