### ISSUE TITLE
Easy event hook on "blur" or being done with TimePicker

### ISSUE THREAD

**Issue by hryanjones** [angular-ui/bootstrap#3872]
I have a validation step which I want to run when a person is "done" using the timepicker. If it runs on ng-change it will show annoying messages at an interim state while they're editing.

My goal is to find an easy way to hook into an event when someone is "done editing the time" or put another way, "leaves" the timepicker. As the timepicker is a collection of elements focused towards editing one value ng-blur made sense to me, but [my PR to fix it this way](https://github.com/angular-ui/bootstrap/pull/3833) was not the appropriate approach as it doesn't follow the the correct browser API by allowing blur to bubble up.

**Comment by wesleycho** [comment]
Just to clarify, do you need granular control over firing a callback for when a particular input is blurred (i.e. hour input vs. minute input), or would you like to fire a callback in both situations?

**Comment by hryanjones** [comment]
I have a couple warnings (if the time range is in the past, etc.) that shouldn't bother the user while they're trying to set a time, but would be good to warn them with after they're done modifying it. Firing on a blur of either element would work well, a little better would be to fire when focus changes outside of the timepicker element (to treat it kind like a single element).

**Comment by wesleycho** [comment]
Hm, I think I get what you desire here - detecting whether each element does not have focus would be a tricky thing to implement properly I believe, since one would have to detect whether each element has focus (i.e. the arrow controls).

Supporting firing a callback for when an input blurs would be amenable though with some attribute such as `input-blur`.

I will think on this again tomorrow after some sleep, but at the least, a new api for passing a callback to be bound to ng-blur on the inputs would definitely be acceptable.

**Comment by wesleycho** [comment]
Sorry for not responding earlier - I think the ability to bind an optional listener for the blur event (via optional directive attribute binding) that binds listeners to the inputs that checks for whether the other inputs have focus to determine whether the user is done with the timepicker would be a good feature.

**Comment by pkozlowski-opensource** [comment]
I'm not sure "blur" event is a good indicator of a user being "done" with a timepicker. There are many things to consider here: shell we listen to blur on a particular input of a timepicker? All of them? Or maybe the time-picker element itself?

IMO a better solution would be to bind a timepicker to a separate (temp) model value and ask users explicitly to "commit" value.

This issue didn't receive much attention in over a year and proposes fishy semantics so I'm going to close it for now. I understand a use-case, though, so if anyone has a precise need and a good idea of a solution we can consider PRs.
