### ISSUE TITLE
Using alternative formatting breaks validation

### ISSUE THREAD

**Issue by robbaman** [angular-ui/bootstrap#3875]
When using an alternative formatting (in my case dd-MM-yyyy) the validation breaks when typing in the textbox.

http://plnkr.co/edit/ZdyqcUpFW6dxcqZsS8CE?p=preview

This appears to be due to an issue where the baseDate passed to the parse function of the parse may be an invalid date. If this is the case, the parser will always keep spitting out invalid dates.

I'll try to issue a PM with a fix for the issue.

**Comment by wesleycho** [comment]
This appears to be a duplicate that should be fixed by #3759.
