### ISSUE TITLE
Datepicker options for datepicker directive (no popup)

### ISSUE THREAD

**Issue by facupedrazzini** [angular-ui/bootstrap#3880]
Hi, is there a way to give an object with all the options in the datepicker element directive?

http://plnkr.co/edit/YyiKrJf2LgIW9nVHM491?p=preview

the datepicker-options attr doesn't work when you use the inline datepicker directive. You have to give every option as a separate attribute.

**Comment by wesleycho** [comment]
Looks like this is correct - a PR for this feature request is welcome, and should be fairly simple to implement. Mimicking the behavior in `datepickerPopup` to take options from the attribute `datepicker-options` would be good.

**Comment by alexey-sh** [comment]
so sadly..

**Comment by wesleycho** [comment]
Closing, as this has been implemented in the datepicker since 1.2.0.
