### ISSUE TITLE
Angular UI bootstrap pagination not working inside ui.bootstrap.tabs

### ISSUE THREAD

**Issue by athimannil** [angular-ui/bootstrap#3881]
Angular UI bootstrap gives awesome solutions. Very unfortunately Pagination (ui.bootstrap.pagination) does not working inside Tabs (ui.bootstrap.tabs)

DEMO http://plnkr.co/edit/mLBkDwEVY6SIh5oCyy0K?p=preview

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive

**Comment by athimannil** [comment]
Finally I have found solution with `filter()` and no concern about `$scope`

    app.filter('pagination', function () {
        return function (input, currentPage, pageSize) {
            if (angular.isArray(input)) {
                var start = (currentPage - 1) * pageSize;
                var end = currentPage * pageSize;
                return input.slice(start, end);
            }
        };
    });

Demo http://plnkr.co/edit/hgpko1aed2Fg15gcBOvZ?p=preview
