### ISSUE TITLE
can popover-template pass html script?

### ISSUE THREAD

**Issue by devmark** [angular-ui/bootstrap#3884]
~~~~
var title = 'Angular-ui bootstrap';
...
    'popover-template': "<div>title</div>'",
...
~~~~
for some reason , i wanna pass html only.

**Comment by wesleycho** [comment]
You can insert your html via `$templateCache` and set a path to the template, or put it in a partial.

I do not believe that this feature should be supported though, as it pollutes HTML templates with HTML templates for other features, which is a mix of concerns, and confusing to boot.
