### ISSUE TITLE
UI collapse animation is not smooth on spans

### ISSUE THREAD

**Issue by lilnate22** [angular-ui/bootstrap#3886]
Simple plunkr to show what i mean:http://plnkr.co/edit/jeMjGiMbABPdZKYRbe7J?p=preview

on div, the animation is pretty smooth,
but on <span> animation does not seem to work correctly

the description for collapse says all elements

**Comment by warrendodsworth** [comment]
I'm using collapse and it dosent have any animation on any element. Some are saying its a bug with angular UI 0.13 and it works in 0.12

**Comment by wesleycho** [comment]
Confirmed, this is a bug - even putting `display: block` on the span does not fix this.

**Comment by chrisirhc** [comment]
Actually, putting `style="display: block"` or `style="display: inline-block"` does fix this.
See http://plnkr.co/edit/ViLy7cEmNFSGyDEvbmlK?p=preview

The root cause is that sizing inline elements doesn't work.

**Comment by wesleycho** [comment]
Hm, I had put it in CSS and it didn't work.

But seeing as there is a workaround, this does not appear to be an issue. In addition, semantically it is incorrect, for the reason what @chrisirhc said.
