### ISSUE TITLE
Pagination Minor Improvement

### ISSUE THREAD

**Issue by warrendodsworth** [angular-ui/bootstrap#3889]
Works great, could use an autoHide default: true like in (https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination)
else need to add ng-show everywhere.

auto-hide (optional, default = true) Specify whether the pagination control should be hidden when there's not enough elements to paginate over.

<pagination ng-model="currentPage" items-per-page="itemsPerPage" total-items="totalItems" ng-change="get()" ng-show="totalItems > itemsPerPage"></pagination>

I tried with some success, but not a proper solution.

**Comment by wesleycho** [comment]
One can simply use ng-show/ng-hide for that. I'm not sure I see a compelling reason for the logic to be duplicated in the directive itself - can you give more info as to why ng-show/ng-hide is not optimal?

**Comment by warrendodsworth** [comment]
Its optimal, it would just mean less code.
As I think hiding the pager when there arent any elements by default would be the case with most UIs.

**Comment by wesleycho** [comment]
It adds more net code though since logic would need to be added to the directive itself, including a watcher to each pagination directive instance.

**Comment by warrendodsworth** [comment]
Ah hah.. cool, gotcha.  ty :+1:
