### ISSUE TITLE
body scrollable when modal is open on mobile

### ISSUE THREAD

**Issue by gazman99** [angular-ui/bootstrap#3891]
Is there a fix to prevent body content from being scrollable once a modal is opened (on mobiles). e.g: the modal-backdrop should catch all mouse/touch events and prevent anything underneath from being touched or scrolled. This happens from http://angular-ui.github.io/bootstrap/#/modal, if you open modal on iphone... the body behind can still be scrolled through the backdrop.

any ideas?

apologises if this has been addressed previously but I could find the correct thread.

**Comment by wesleycho** [comment]
One can likely create a custom directive and make use of it in the template to catch the desired events & stop them from bubbling up.

Handling mobile events would be difficult though, and I am not sure how desirable it would be to handle it in this library itself - if someone is able to come up with a lightweight solution, I would be happy to evaluate it though.

**Comment by chrisirhc** [comment]
I think you're referring to the mobile zoom behavior. The current behavior on a desktop already prevents the body from scrolling.

The mobile scrolling behavior can be tweaked via the viewport meta tag. There's also other relevant techniques:
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag
https://github.com/phonegap/phonegap/wiki/Prevent-Scrolling

**Comment by wesleycho** [comment]
I'm not sure why it didn't occur to me to not ask about whether that meta tag was set.

**Comment by gazman99** [comment]
Thanks for your input guys, I had already tried the scrolling fix but it blocked all touch scrolling. I had also added the metatag previously.

The solution thats works for me was to add/remove a class to the body when modals opens and close.       
    body.isopn{
        postion:fixed, 
        overflow:hidden
    }

may not be the only or best way to solve this.....but works for my cause.

**Comment by wesleycho** [comment]
Doing a bit of research on this problem, it looks like your solution is the best approach to handle this use case - the only other solution is binding an event listener to $document for the touchstart event, which is horribly inefficient.

This does sound like a UX problem though - would it make sense for the modal to handle adding and removing these styles on the body tag? My only concern there is that it may potentially break someone's CSS.

**Comment by wesleycho** [comment]
Closing due to solution found for mobile problem - I have found that `overflow: hidden` and `position: relative` worked best to fix this on the `.modal-open` class.

**Comment by rdillmanCN** [comment]
Here are some thoughts for starters,  Not sure what I should be looking at.
- I am able to scroll the page while modal is open. Some brands use a modal as an advertising roadblock. This would defeat that. Also from a UX standpoint it seems odd.
- Between 760px and 768px desktop and below 418px desktop the modal content window is wider than the browser window.  Need to account for those scroll bars.
- modal on mobile is just bizarre. And overflows a lot in landscape.
- When a modal shows up it should steal the focus.  If not text readers will continue reading content beneath. It should return that focus when dismissed.
- There is a scroll bar within the modal content window.
- The version with the close button delay is offset to the right and overflows the browser.
