### ISSUE TITLE
modal.js contains illegal character -> script error

### ISSUE THREAD

**Issue by jvanbouchaute** [angular-ui/bootstrap#3892]
In modal.js from the current master, there's an illegal character resulting in a script error.

![image](https://cloud.githubusercontent.com/assets/2338344/8499619/05079d40-2195-11e5-8cb6-ecda4882cfec.png)

![image](https://cloud.githubusercontent.com/assets/2338344/8499623/0c2266fa-2195-11e5-81b9-16eedd882c3c.png)

**Comment by wesleycho** [comment]
Interesting, I don't see this character - can you give steps to view?

**Comment by jvanbouchaute** [comment]
Just cloned the project source via bower as we need to have the fix for Issue #3639 ..  and added the module registration from a custom build. that's it ...

**Comment by jvanbouchaute** [comment]
Maybe a build process filters it out ?

**Comment by wesleycho** [comment]
I mean is there a particular editor that shows that character?

**Comment by jvanbouchaute** [comment]
Ultra edit in hex mode ...
Op 3-jul.-2015 18:54 schreef "Wesley Cho" <notifications@github.com>:

**Comment by wesleycho** [comment]
Not seeing it in Vim when opening it in xxd, but I did see the diff when editing it to add a space. I will look at merging shortly.
