### ISSUE TITLE
Feature Request - Last Known Tab

### ISSUE THREAD

**Issue by warrendodsworth** [angular-ui/bootstrap#3894]
Saving the last known tab using local storage. So that when the user returns to the page that tab is selected. I was able to do this as an add on for jQuery Boostrap, this would be a really nice if it could be included in the 'tab' directive

for example - <tabset tabgroup-id="terminalTabs" save="true">
or autogenerate a random id for local storage

```html
 <tabset type="pills" vertical="true">
        <tab active="tabs[0]">
            <tab-heading>Events</tab-heading>
            Events {{tabs}}
        </tab>
        <tab active="tabs[1]">
            <tab-heading>Users</tab-heading>
            Users {{tabs}}
        </tab>
    </tabset>
```

```javascript
        ( function () {
            'use-strict';
            angular.module( 'app' )
                   .controller( 'TerminalController', TerminalController );

            TerminalController.$inject = ['$scope', 'localStorageService'];

            function TerminalController( $scope, localStorageService ) {
                $scope.tabs = localStorageService.get( 'terminalTabs' ) || [true, false];

                $scope.$watchCollection( 'tabs', function ( value ) {
                    localStorageService.set( 'terminalTabs', $scope.tabs );
                } )
            }
        } )();
```

**Comment by wesleycho** [comment]
This would be easy to implement on the developer's side through setting the initial active tab on load of a particular view after checking if the value is present in a local caching solution.

This feature is out of scope for this library though, as it would require adding a potential dependency on a localStorage abstraction (or IndexedDB/WebSQL), and that is a level of opinionation & potential duplication that is not desirable.
