### ISSUE TITLE
Modal Backdrop not being Removed from Page Upon Modal Close

### ISSUE THREAD

**Issue by tuckerjt07** [angular-ui/bootstrap#3896]
I'm opening a new issue based off of the following two threads <a href="https://github.com/angular-ui/bootstrap/issues/3620">3620</a> and <a href="https://github.com/angular-ui/bootstrap/issues/3633">3633</a>. Both threads discuss this issue in depth but apparently it needs its own dedicated space. The issue is with ngAnimate and the updates that have changed the way its functions interact with Angular Bootstrap's. The opening functions are still wired up and fire but the close events do not cause ngAnimate to fire. There are several work arounds provided in <a href="https://github.com/angular-ui/bootstrap/issues/3633">3633</a>.

**Comment by chrisirhc** [comment]
I think @esion 's description in https://github.com/angular-ui/bootstrap/pull/3895#issuecomment-118589077 mentions this.

**Comment by diwu1989** [comment]
can you make a 0.13.1 release with this?

**Comment by lawlessbg** [comment]
+1 @diwu1989 If the bower repository is also update will be very nice too.

**Comment by pkeuter** [comment]
Yes, a 0.13.1 release would be very nice :-)

**Comment by simison** [comment]
+1 for 0.13.1

**Comment by sagar-ranglani** [comment]
+1

**Comment by simison** [comment]
Thanks! https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#0131-2015-07-23
