### ISSUE TITLE
Relocate $position to angular-ui/ui-position

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/bootstrap#3902]
In continuation of my long-standing intentions in #1049 we finally split apart ui-utils into multiple projects and simply include them all together in `ui-utils` as dependencies.

I feel now would be an appropriate opportunity to revisit moving the position code outside of `ui-bootstrap` since so many projects have used it as a boilerplate (foundation, semantic, tooltips, datepickers, etc) that it would be really nice if we could share this underlying complexity and make it easier/faster for those trying to build angular suites.

Placeholder repo is here: https://github.com/angular-ui/ui-position/issues/1

**Comment by icfantv** [comment]
This is great in theory, but in practice, we're not sure it's practical.  People have a hard enough time using the template version of the library as it is.  Sadly I'm going to close this as wishful thinking for a perfect world.
