### ISSUE TITLE
Feature request on tabs

### ISSUE THREAD

**Issue by xforceco** [angular-ui/bootstrap#3903]
![pr3](https://cloud.githubusercontent.com/assets/12808889/8537375/af0736b8-2490-11e5-844e-00a04d45638f.png)

I would like the tabs to behave like firefox's tabs, when the width is not enough for showing the tabs, arrows will be provided to switch from one to the other instead.

**Comment by wesleycho** [comment]
This sounds like something you can create via HTML/CSS using media queries in conjunction with the existing tab components - I don't think this is prudent to be supported in UI Bootstrap itself, as it remains relatively unopinionated on this type of functionality.
