### ISSUE TITLE
Accordion does not animate

### ISSUE THREAD

**Issue by FlavorScape** [angular-ui/bootstrap#3912]
I'm looking at the example plnkr and it does not animate or apply the collapsing class. How do I use the animations like on the main docs page?

**Comment by RicardoRFaria** [comment]
You've added the ngAnimate library and imported in your module?
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.2/angular-animate.min.js"></script>
```
```javascript
angular.module("yourModuleName", ['ui.bootstrap', 'ngAnimate']);
```

**Comment by FlavorScape** [comment]
Ah, that did the trick. I see you updated the readme to include that info. Thanks!

**Comment by FlavorScape** [comment]
p.s. plnkr might want to update, too.

**Comment by crestwoodCoder** [comment]
I added ngAnimate (included in script and injected into module), and the transition just seems to go slower, but not collapsing right. It seems to open first and then close the other one slowly. I'm using 0.13.1.  Version 0.12.x works perfectly.

**Comment by VoltiSubito** [comment]
@crestwoodCoder I think you'll have better luck if you create a plnkr illustrating the problem and open a new issue instead of tailing on this one that has already been closed.
