### ISSUE TITLE
Dateparser can't handle constants in format

### ISSUE THREAD

**Issue by ivarm1984** [angular-ui/bootstrap#3914]
Version 0.13.0 datepicker doesn't work when format has constants. Spanish: 'd 'de' MMMM 'de' y'

This works with version 0.11.0

[Plunker](http://plnkr.co/edit/dxLYdZT3JyaSXO47CzMX?p=preview) Comment in 0.11.0 to make it work.

**Comment by bike2live** [comment]
Version 0.12.1 works because it doesn't get to the regex parsing. The parser in 0.12.1 doesn't get created correctly either.
