### ISSUE TITLE
Bootstrap UI Tabs causes $parse:isecdom error for csp "expensiveChecks" set true

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular-ui/bootstrap#3917]
The Bootstrap UI v0.13.0 Tabs widget causes a $parse:isecdom error, when the csp "expensiveChecks" option is set true. This seems to be the offending code:

            scope.$watch('headingElement', function updateHeadingElement(heading) {
                if (heading) {
                    elm.html('');
                    elm.append(heading);
                }
            });

...at line 252 of the current "tabs.js" (4bfae2238d08d7edea8e6dfe99051192a16d6587)

I'm still new to AngularJS, but this seems to work as a fix:

            scope.$watch(function() {
                return tabCtrl[attrs.tabHeadingTransclude];
            }, function updateHeadingElement(heading) {
                if (heading) {
                    element.html('');
                    element.append(heading);
                }
            });

**Comment by wesleycho** [comment]
Hm, so is the problem that Angular enforces no DOM elements being watched in a string, but not a function?

**Comment by wesleycho** [comment]
If you can reproduce this in a [Plunker](http://plnkr.co/), this would massively be helpful to us as well.

**Comment by wesleycho** [comment]
I am not able to reproduce this [here](http://plnkr.co/edit/3Lvh2t7HkZmJmuSChSI6?p=info) - nothing can be done without a reproduction to work off of for this issue.

**Comment by wesleycho** [comment]
Closing due to lack of response.

**Comment by OpenSiteMobile** [comment]
Hi, I looked at the Plunker you created and didn't see "expensive checks"
enabled. To tell you the truth, I don't remember how you guys enable it, as
I use it as the default in my version of Angular. So yeah, it all works
otherwise. I'm probably the only person in the universe using "expensive
checks", so it really isn't a problem...just an FYI.

**Comment by wesleycho** [comment]
Can you reproduce it off of a fresh Plunker? I'm willing to take a look if it is an issue
