### ISSUE TITLE
Bootstrap tooltip not showing complete text of a very long word(without space) 

### ISSUE THREAD

**Issue by balutalkin** [angular-ui/bootstrap#3918]
For the below line of code

//</ a href="#" tooltip="thisisaverylongwordwhichneedstobeshownastooltiptext" tooltip-placement="bottom">Check me out!</a>

the tool tip only shows "thisisaverylongwordwhichneedstob" when we hover over the link.

please check this plnkr link

http://plnkr.co/edit/FmcxznrivN60Dva5ocxR?p=preview
![issue](https://cloud.githubusercontent.com/assets/13224976/8575263/b04e2600-2560-11e5-954e-3ff87cb1d315.png)

**Comment by pkozlowski-opensource** [comment]
This is due to Boostrap's CSS, nothing to do with this project:

```
.tooltip-inner {
  max-width: 200px;
```
