### ISSUE TITLE
ngModel and modal window strange behaviour before first blur of field

### ISSUE THREAD

**Issue by matyee** [angular-ui/bootstrap#3923]
Hi,

I know the subject sounds strange, but also the problem what I found. I tried to figure this out but I failed. Seems angular's ngModel does something different before and after the first blur of the field that is binded. 

Here is the example. http://jsfiddle.net/oLdnooh2/2/

Click in the field, type anything and hit ENTER. This will trigger a modal window and you are going to get an angular error in the console saying a digest cycle is already running (Tested in Chrome). Close the modal, hit ENTER, the same error occurs as many time as you want.

OK, now click outside the field, it looses it focus, then click back, and hit enter again. Everything seems the same, but the error disappeared. And you are never going to get again. You also never will get the error if you click in the field click out and click back again before you first hit ENTER. If the field lost its focus at least once this error never occurs.

What do you think what is this and how can it be avoided?

Thanks,
Matyee

**Comment by matyee** [comment]
The opposite works as well. If I put a field on a modal and bind it with ngModel, click in it to gain focus and hit ESC that makes the modal to close, the same digest error comes up. If I click on the field click elsewhere and click on it again and hit ESC after, then the modal closes but the error is not there.

**Comment by matyee** [comment]
The same issue comes up in FF.

**Comment by wesleycho** [comment]
I am not actually seeing the error in Chrome in the fiddle, but I do see this in Firefox.

Also your fiddle had a slight error with the submit button type, so I updated it [here](http://jsfiddle.net/oLdnooh2/3/).

**Comment by wesleycho** [comment]
I updated the fiddle again [here](http://jsfiddle.net/oLdnooh2/4/) with the unminified version of UI Bootstrap.

It looks like the error is being thrown [here](https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L148).

Can you recreate this in [Plunker](http://plnkr.co/)? This would make it easier to debug & modify the source itself to test bug fixes, which jsfiddle seems to be bad at allowing in an easy to work with way.

**Comment by icfantv** [comment]
I created a plunker [here](http://plnkr.co/edit/j9pC1ujvPnmGLU6OS6UN) but the issue was fixed in [Angular 1.3.4] (https://github.com/angular/angular.js/blob/master/CHANGELOG.md#134-highfalutin-petroglyph-2014-11-24) - most likely via the bullet titled `call $setTouched in blur asynchronously if necessary`.

I did confirm that the issue goes away when using Angular 1.3.4.  @wesleycho, I think this issue can be closed.
