### ISSUE TITLE
Only allow valid integers for dismiss-on-timeout

### ISSUE THREAD

**Issue by steven10172** [angular-ui/bootstrap#3928]
Currently if you have dismiss-on-timeout="" or an invalid integer `parseInt(attrs.dismissOnTimeout, 10)` evaluates to `NaN` which causes `$timeout` to run instantly. To prevent this from happening the `dismissOnTimeout` directive should check to make sure  `parseInt(attrs.dismissOnTimeout, 10)`  evaluates to a proper integer.

**Comment by steven10172** [comment]
Implemented a Fix in #3927

**Comment by icfantv** [comment]
@wesleycho, per the comments in #3927, this can be closed.
