### ISSUE TITLE
Dropdown is-open not work with combined expression

### ISSUE THREAD

**Issue by btpka3** [angular-ui/bootstrap#3930]
[dropdown.js#L85](https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L85)

```
    if ( $attrs.isOpen ) {
      getIsOpen = $parse($attrs.isOpen);
      setIsOpen = getIsOpen.assign;    // undefined when using combined expression
```

example

* OK :   `<div dropdown is-open="searchResult">`
* ERROR :  `<div dropdown is-open="searchResult  && searchResult.length != 0">`

**Comment by wesleycho** [comment]
Can you reproduce this in a [Plunker](http://plnkr.co/) - this is not enough information to go by.

**Comment by btpka3** [comment]
My fault, I am trying to open a dropdown, I should  update the `is-open` model's value, but not assign it to an complex expression.
The directive will update the `is-open` model's value, so it could not be an complex expression.
Here is the [misused demo](http://plnkr.co/edit/EBC4HkQveny8zpn5UvvI?p=preview).
