### ISSUE TITLE
Carousel Animation Broken

### ISSUE THREAD

**Issue by maneesht18** [angular-ui/bootstrap#3932]
Latest version of Angular UI Bootstrap (0.13.0) does not have smooth transitioning with the carousel. This is broken because the transitioning works on 0.12.0

**Comment by mchlbrnd** [comment]
Are you using Angular 1.4? Probably related to #3811. 0.13 does not support Angular 1.4 yet.

**Comment by gytisgreitai** [comment]
It's also broken with 1.3.13
See plunker  http://plnkr.co/edit/KixcEb1uDNNgdXEzTDCe?p=preview

**Comment by jrief** [comment]
@gytisgreitai The demo Plunk is broken. You have to add ``ngAnimate`` to your angular module initialization. Please check this modified Plunk: 
http://plnkr.co/edit/OyihVYocklUSMboUpENL?p=preview

**Comment by wesleycho** [comment]
@jrief is correct - animations are now optional, so you have to specify the `ngAnimate` dependency manually.
