### ISSUE TITLE
modal should be draggable

### ISSUE THREAD

**Issue by ezraroi** [angular-ui/bootstrap#3935]
It will be good to be able to make the modal draggable as in other frameworks such as Kendo

**Comment by madhums** [comment]
You can make it moveable using decorators. I have the right thing for you here  https://gist.github.com/madhums/7d8377498b34933ebb18

**Comment by wesleycho** [comment]
This is not a feature we are interested in supporting in the library itself. I think something like @madhums's solution makes a lot of sense in a local codebase if one desires such a feature.
