### ISSUE TITLE
ui-select doesn't show list of choices in modal dialog (pop-up)  angular 1.4

### ISSUE THREAD

**Issue by C00per** [angular-ui/bootstrap#3936]
It works fine in angular 1.3.17 with angular-bootstrap 0.13.0 and older versions.
In angular 1.4.2 and angular-bootstrap 0.13.0 \ 0.12.1 , I have to enter 'sss' letters in the search field and remove them for list of choices to be shown.

ui-select works fine in angular 1.4.2 without modal dialog (pop-up).

Could someone help with fixing this issue?

Thanks

**Comment by pkozlowski-opensource** [comment]
@C00per ui-select is not part of this repo. The only thing that comes to my mind is a scoping and / or timing issues. I'm afraid that you will have to dig into it on your end as we don't have free cycles left to handle such support requests:   https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
