### ISSUE TITLE
days out of month to not show

### ISSUE THREAD

**Issue by dougeff** [angular-ui/bootstrap#3938]
Hi:

When the popup opens, it not only shows the full month, but also the days of the previous and next months to fill out the rest of the grid with a class of "text-muted" for the inner spans.  Is there any way to have those "outer" days not show at all so the display looks more like a calendar?  Just having a CSS rule for not displaying the text-muted class doesn't work because the buttons that contain the spans that contain the numbers are still visible.  

Thanks for your time.

**Comment by mecapetr** [comment]
I think only way to do that is change some code in bootstrap.js. Try to find this line
angular.module("template/datepicker/day.html", []).run(["$templateCache", function($templateCache)

and then find the current span and copy 'text-muted': dt.secondary from span ng-class to parent button ng-class.

**Comment by dougeff** [comment]
Thanks for responding mecapetr, that's actually what I ended up doing.  I just wanted to see if there was some setting I was missing that would accomplish the same thing.  Thanks again.
