### ISSUE TITLE
datepicker - is-open - No Documentation

### ISSUE THREAD

**Issue by stephen-cernota** [angular-ui/bootstrap#3939]
As a total bootstrap/jquery/angular/web noob, it was not apparent to me how to open and close the datepicker.

The documentation does not say anything about "is-open"

- https://angular-ui.github.io/bootstrap/
- https://github.com/angular-ui/bootstrap/tree/master/src/datepicker/docs

Please save other noobs!

The is-open="opened" attribute puts the variable opened on the scope and you can pop the datepicker open by using scope.opened = true;

**Comment by holimL** [comment]
EXACTLY what I was wondering. I was looking into source code to figure out that I need it declared.

**Comment by wesleycho** [comment]
This was a complete oversight - feel free to file a PR.
