### ISSUE TITLE
responsive navbar

### ISSUE THREAD

**Issue by acornejo** [angular-ui/bootstrap#394]
The documentation doesn't show how to use the responsive navbar feature in bootstrap.

This feature allows the links in the navbar to be "collapsed" in small screens, and the click of a button allows these links to be displayed again (below the navbar).

I thought the "collapse" part of bootstrap-ui would work, but it doesn't work (at least not out of the box). Googling I found several other people with the same problem, but there seems to be no good answer.

For reference see this question on stackoverflow (not mine):

http://stackoverflow.com/questions/16268606/responsive-dropdown-navbar-with-angular-ui-bootstrap-done-in-the-correct-angula

Also, someone suggested a solution in a blog post:

http://frankapi.wordpress.com/2012/12/04/responsive-bootstrap-and-angularjs-routing/

However, that requires jquery + bootstrap.js, so its not for ui-bootstrap.

**Comment by davisford** [comment]
Broken with angular-ui 12.0 -- here's a fork of the plunk above that just changes angular-ui to release 12.  While the collapse directive still works, the dropdown no longer does (try and expand the submenus).

Looking for a solution.

**Comment by antoinepairet** [comment]
@davisford Please read the release note of 0.12 and the list of breaking changes: https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#breaking-changes
The dropdown directives are no longer class directive. They need to be set as attribute.

Here is a working plunker: http://plnkr.co/edit/by9bV5jBA4Qn8VASfw08?p=preview

**Comment by luckylooke** [comment]
Thank you @antoinepairet! Best solution I have found ;)

**Comment by pgnaveen** [comment]
@antoinepairet The entire menu should fully collapse upon the selection of an item similar to this plunkr and it uses very old versions of angular and ui-boostrap.  http://plnkr.co/edit/OlCCnbGlYWeO7Nxwfj5G?p=preview

However, this code snippet doesnt work with latest angular js and ui-bootstrap versions. Help pls!!

**Comment by krnlde** [comment]
This issue is really annoying and tbh `ng-class="!navCollapsed && 'in'"` is a hack, not a solution.
