### ISSUE TITLE
Datepicker: Popout day of month width squishes day view in firefox

### ISSUE THREAD

**Issue by atentis** [angular-ui/bootstrap#3941]
If you have a limited column size your day view for your popout date picker will be squished in firefox. This is not an issue with chrome as it keeps its static size. Resize the screen to see the difference if necessary. 

http://plnkr.co/edit/kV8ICxL8Jiwmttzyt13G?p=preview

![capture](https://cloud.githubusercontent.com/assets/8903400/8662007/8fbeee22-2981-11e5-9062-a674fdf4bd47.JPG)

**Comment by wesleycho** [comment]
Perhaps modifying the templates for the `day`, `month`, and `year` components with an appropriate min-width would work to fix this - feel free to file a PR for this.

**Comment by atentis** [comment]
@wesleycho That worked. I will try to file a pr soon
