### ISSUE TITLE
Using "max" in a progressbar may create unwanted objects in my scope

### ISSUE THREAD

**Issue by marcoliceti** [angular-ui/bootstrap#3944]
**EDITED** to use non-embeded plunker site.

The issue is clearly described and demonstrated in [this plunker](http://plnkr.co/edit/KDMn05Y2P94bUJL4KJ6V).

**Comment by icfantv** [comment]
@marcoliceti, the value attribute is required on the directive for a good reason:  a progress bar has a value of 0 to max and it does not make sense to have "no value" - that's the same as zero.

If you do not want your progress bar to show until a scoped variable is set, then you can either wrap it in a `<div>` and use the same scoped object as your progressbar, or use a different scope variable and set the `ng-show` on the `<progressbar></progressbar>`.
