### ISSUE TITLE
First tab is not active if it its generated from data (ng-repeat) and followed by static tabs

### ISSUE THREAD

**Issue by franciscoruiz** [angular-ui/bootstrap#3945]
### Scenario
- The first N tabs are generated from data, using `ng-repeat`.
- Extra tabs are statically defined.

### Expected behaviour
- The first tab is active.

### Actual behaviour
- The first static tab is active.

http://plnkr.co/edit/Wf6ubHOhOQhcSHa9pk7I?p=preview

**Comment by wesleycho** [comment]
Just to confirm, this looks like a current issue in `master`, as illustrated in [this updated Plunker](http://plnkr.co/edit/JOw1pHvNwATsINVyNHiI?p=preview).

**Comment by wesleycho** [comment]
This looks like a potentially difficult bug to fix - the tabs call `tabsetCtrl.addTab(scope)` on each tab directive compilation, and the tabs created with ng-repeat get created after the static version.

I will need to think on this.

**Comment by wesleycho** [comment]
Closing in favor of #4836 - keep an eye out for that issue.
