### ISSUE TITLE
Possibility to show/hide indicators

### ISSUE THREAD

**Issue by demiro** [angular-ui/bootstrap#3947]
component: carousel
For some reason, there is no way to turn off the indicators, they are added automatically
Would be nice to have an option to hide them or better, not include them at all!

**Comment by RicardoRFaria** [comment]
I think this would be a nice feature.

**Comment by wesleycho** [comment]
This can be accomplished via CSS with ng-class on the carousel element.

I do not believe this is something UI Bootstrap should support, as the ng-class solution would be more performant than adding watchers for each potential toggle.
