### ISSUE TITLE
text-center class added automatically to slides

### ISSUE THREAD

**Issue by demiro** [angular-ui/bootstrap#3948]
component: carousel
I don't like the idea, that class text-center is automatically attached to the carousel slides with no possibility to override this - OK, to be fair, I could do style="text-align: left" on the slides... but this feels so dirty :)

**Comment by wesleycho** [comment]
You could also override it in CSS as well for just the `slide` element.

**Comment by wesleycho** [comment]
Closing as not an issue, as this has easy CSS solutions by putting custom classes on the carousel and slide elements & overriding with user CSS.
