### ISSUE TITLE
hi,where can i get the offeline demo for ui-bootstrap

### ISSUE THREAD

**Issue by coojee2012** [angular-ui/bootstrap#3955]
hi,where can i get the offeline demo for ui-bootstrap?
thank you very much!

**Comment by pkozlowski-opensource** [comment]
Not sure what you mean by "offline" exactly, but you can build docs on your machine after clonning this repository: https://github.com/angular-ui/bootstrap/wiki/Development

**Comment by coojee2012** [comment]
@pkozlowski-opensource  

thanks
