### ISSUE TITLE
When 13.1 ?

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#3958]
I don't want to complain, but 0.13.0 was released more than two months ago, and it was said than 'shortly' after releasing, version with performance issues would be released.
Also angular 1.4 is in perspective :)

**Comment by pkozlowski-opensource** [comment]
@piernik in open-source things are ready when done. If you want to contribute in a meaningful way pick up some issues or review existing PRs. We are a community of developers here, not a free development shop, sorry.
