### ISSUE TITLE
tooltip-html does not work if a function instead of a variable is used

### ISSUE THREAD

**Issue by koryhopkins** [angular-ui/bootstrap#3959]
I was having trouble getting tooltip-html to work with a function. 

I found this previous thread:
https://github.com/angular-ui/bootstrap/issues/3790
and got it to work with a variable.  But, I need it to work with a function.

tooltip works fine with a function or variable.
tooltip-html only seems to work with a variable.

The following plunker demonstrates this issue:
http://plnkr.co/edit/RnA1KF4DfpYLxd0lWKUd?p=preview

The same function is used for the Nay and Maybe buttons but it only works with the Maybe (tooltip) button and not the Nay (tooltip-html) button.

**Comment by fushnisoft** [comment]
I believe the issue is that you have not included ngSanitize.
See if this does what you want: http://plnkr.co/edit/4LU5KyXmjKKZYJTH7RjQ?p=preview

**Comment by koryhopkins** [comment]
Thanks for the tip!  If I add ngSanitize and remove the {{}} brackets around the function that returns the tooltip it all works.

**Comment by wesleycho** [comment]
Looks like this has been resolved.

Feel free to comment further if there is an issue.
