### ISSUE TITLE
Dropdown more than one dropdown-toggle not work

### ISSUE THREAD

**Issue by btpka3** [angular-ui/bootstrap#3962]
If a `dropdown` contains more than one `dropdown-toggle`, only one work. Can this be improved? Here is the [plunker](http://plnkr.co/edit/NlbecC3Pe7xg4pgVcq8n?p=preview)

**Comment by RobJacobs** [comment]
Questions of this nature belong on Stackoverflow, see the FAQ section [here](https://github.com/angular-ui/bootstrap#need-help). You will need to prevent the click handler from bubbling up, see this forked plunk [here](http://plnkr.co/edit/snLpiCBbec93LvQDdutv?p=preview).
