### ISSUE TITLE
ngAnimate breaks ability to close modal

### ISSUE THREAD

**Issue by entrity** [angular-ui/bootstrap#3967]
See Plunker: http://plnkr.co/edit/OT36XUFNtbHe8IM5VTnP?p=preview

You can open a modal (click 'Open Me!'), but when you click outside the modal to close it, the modal blackdrop remains. Likewise, the `modal-open` class remains on the body tag.

**Comment by wesleycho** [comment]
This looks like this is fixed on `master` - check [here](http://plnkr.co/edit/sND0OTnpfQEoZZQS6eSx?p=preview).
