### ISSUE TITLE
Allow different accordion-group classes

### ISSUE THREAD

**Issue by hejmsdz** [angular-ui/bootstrap#3968]
The class of panels (aka accordion groups) at https://github.com/angular-ui/bootstrap/blob/master/template/accordion/accordion-group.html are hard-coded to `panel-default`. I would like to be able to use a different one. Currently, even if I use `ng-class` to assign another class to the panel, the `panel-default` class is still there.

**Comment by wesleycho** [comment]
This sounds reasonable - feel free to open a PR.

**Comment by RicardoRFaria** [comment]
One question. The behavior of this feature is:
- if I place attribute ```ng-class``` he will override ```panel-default ``` and ```panel``` too, maybe.
or 
- if I place attribute ```panelClass``` (or something like this) he will override all classes of panel.

**Comment by wesleycho** [comment]
Another solution is `class="foo {{bar}}"`

**Comment by RicardoRFaria** [comment]
And when I place ```class="foo {{bar}}"``` will override all default classes? (```panel panel-default```)

**Comment by wesleycho** [comment]
it could be `class="foo {{bar || 'panel-default'}}"`

**Comment by RicardoRFaria** [comment]
ok, thx

**Comment by RobJacobs** [comment]
Just a suggestion, rather than go through all the work involved with removing/adding classes, would it be better to offer the ability to override the templates with an attribute?  I.E., changing this:

    templateUrl: 'template/accordion/accordion.html'

To this:

    templateUrl: function(element, attrs) {
       return attrs.template || 'template/accordion/accordion.html';
    }

**Comment by wesleycho** [comment]
That is also a valid option/feature - may be even better for performance reasons & simplified api.

**Comment by RobJacobs** [comment]
It got me thinking, it would be a nice (and easy) feature to add to all the simple (mostly markup) directives and would relieve the burden of having to do customization on the default templates.

**Comment by RicardoRFaria** [comment]
I think that give option to change the default template is good, in other way, when you change the template "only to customize the css" you loose features like accessibility (that isn't implemented in collapse yet).

**Comment by wesleycho** [comment]
Hm? I merged your PR with accessibility enhancements to collapse in 92551342cc36c0f655a4b47bda4c46d196736d83 .

**Comment by RicardoRFaria** [comment]
@wesleycho sorry, I talked collapse, but is accordion.

**Comment by icfantv** [comment]
Just an update here.  We now have support for @RobJacobs solution in `master` so the only question remaining is do we allow a custom panel class option ala the suggestion by @wesleycho above?  While this seems like a pretty easy change to make and test, we're kind of pulling the thread on the proverbial sweater, ala:

If we allow customization here, don't we also need to also add it for the `panel-heading`, `panel-title`, and `panel-collapse` classes?  And what about `panel-group` in the `accordion` directive template?  And if we allow this, are we really still Bootstrap?

It sounds like using the custom template solution is the right way to go here and I think we can close this.

**Comment by wesleycho** [comment]
In this case, there are other supported panel classes, such as `panel-success` - see https://github.com/twbs/bootstrap/blob/master/less/panels.less

**Comment by icfantv** [comment]
Ah crud, I'd forgotten about those.  So we probably only want to support replacing just the `panel-default` as you describe above.
