### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by johneakin** [angular-ui/bootstrap#3976]
Hi,
If I manually (via the textbox) set the date back a year 
i.e. change 2015 to 2014
then the control shows as invalid (i.e. a red border)

Is there a fix for this?

**Comment by wesleycho** [comment]
Can you create a reproduction on [Plunker](http://plnkr.co/) - this is not enough to go by or be sure what is happening.

**Comment by ChristophT** [comment]
I came across the same problem today. Seems to me, that the baseDate used in dateparser.js, line 130, is supposed to be a date object. If you enter the date manually however it is a string, so the call 
```javascript
year: baseDate.getFullYear(),
```
fails.

**Comment by ChristophT** [comment]
Created a [plunkr](http://embed.plnkr.co/T65uYsHxO3bY3j7z8gf2/).
The date is initially set as string. A manual edit in the input box triggers the error. If you select a date via the picker or initialize `mydate` with `new Date()` everything works fine.

**Comment by RobJacobs** [comment]
@ChristophT, @wesleycho  The datepicker has these open PRs: #3759, #3691, #3682, #3344, #2513, #2369, #2142 that are related to how the date is parsed.  I updated the [plunk](http://plnkr.co/edit/1EnxEHjRK0129bruG7jB?p=preview) with the latest build from the master branch so we can test against that.

**Comment by wesleycho** [comment]
#3759 fixes this.

**Comment by johneakin** [comment]
If you go down to the Datepicker here

https://angular-ui.github.io/bootstrap/

and change 2015 in the textbox to 2014 you'll see the red error border around the calendar.
Are we saying this is now fixed?
