### ISSUE TITLE
Any way we could get npm publishing part of the normal release process?

### ISSUE THREAD

**Issue by kentcdodds** [angular-ui/bootstrap#3977]
npm is becoming a very popular method of distributing frontend code. Could we please get an official release of the latest version and keep that going for future versions?

**Comment by wesleycho** [comment]
@chrisirhc what is the release process currently on the `bootstrap-bower` repository? @Foxandxss and I both have access to `angular-ui-bootstrap` on npm as of today, so we can start using that for releases to npm.

We would need package.json to be start being bundled in the repository at least. I did not see an automated task for pushing up to this repository.

**Comment by chrisirhc** [comment]
The release process on bootstrap-bower is currently manual. Files are copied from the https://github.com/angular-ui/bootstrap/tree/gh-pages branch once a release is done.

This is one of the todos for #3450

**Comment by wesleycho** [comment]
We can add anyone as needbe to the npm collaborator list also if it helps speed it up - if you like, register your handle on npm and we can add you.

**Comment by Foxandxss** [comment]
0.13.0 is now in npm. Manual process but it works

**Comment by kentcdodds** [comment]
Thanks for doing that @Foxandxss :-)
