### ISSUE TITLE
Backdrop is not removed after modal is dismissed (0.13.0)

### ISSUE THREAD

**Issue by james-hart** [angular-ui/bootstrap#3979]
With Angular 1.4.2 (using ngAnimate) and bootstrap-ui 0.13.0, the backdrop is not removed when the modal is dismissed or closed with any command, when animation is true.
This event appears to be not be firing:

    domEl.one('$animate:close', function closeFn() {
      $rootScope.$evalAsync(afterAnimating);
    });

If you turn off animation (```animation: false```), it does work correctly, since it is bypassing this event. This could be due to an Angular change.

Looking at the master branch, it appears this may have been fixed by a promise change (however, I'm unable to test this). I wanted to at least save anybody time that's been banging their head on a table for why their backdrop may not be closing when using the modal.

**Comment by wesleycho** [comment]
This is fixed in `master` already - see #3899.
