### ISSUE TITLE
Modal backdrop not closing on angular 1.4.3

### ISSUE THREAD

**Issue by orzilca** [angular-ui/bootstrap#3981]
Modals works fine except when trying to close the modal using ```$dismiss``` or ```$modalInstance.close()```.

The modal then closes (as expected) but the backdrop remains visible blocking any clicks on the page behind.

using ui-bootstrap latest version with angular 1.4.3

**Comment by jakobholmelund** [comment]
It's fixed in the master branch, and will be in 0.13.1 for which we still haven't got a release date :)
https://github.com/angular-ui/bootstrap/issues/3633

**Comment by RobJacobs** [comment]
Closing as fixed in PR #3895
