### ISSUE TITLE
Modal close cannot be cancelled

### ISSUE THREAD

**Issue by mathlarocque** [angular-ui/bootstrap#3983]
Hi, I'm currently trying to induce some logic to the way the modal close itself. when I lunch the backdrop event, there is no way to cancel it. What I would like to do is something like a beforeClose function that would let me prevent the modal from closing if it return false for example...

The reason is : 
I got an object that get dragged in the modal. when the user accidentally drag it out, the modal close itself. 
But I still want the user to be able to close the modal by clicking outside. If I could simply declare the function beforeClose in my modal controller so that it return whether or not the modal can be close my problem would be solve.

Is there a way to achieve what i'm trying to do?
Thank in advance

**Comment by RobJacobs** [comment]
These forums are for reporting issues, read [here](https://github.com/angular-ui/bootstrap#need-help).  Please post questions of this nature on Stackoverflow, thanks.
