### ISSUE TITLE
ng-controller on tab

### ISSUE THREAD

**Issue by rkurbatov** [angular-ui/bootstrap#3985]
I used to place ng-controllers on tabs in multi-tab apps. But in angular 1.4.1 they 'fixed' something and now it's impossible. I have a multidir error. I have quite independent controllers and need to use select handler. So ng-controller can't be placed inside of tab. And also it can't be placed outside of tab - only outside of tabset. I don't like that idea, really.

**Comment by wesleycho** [comment]
Can you explain more clearly and (preferably) come up with a reproduction on [Plunker](http://plnkr.co/)?

`ng-controller` is generally considered a bad practice - if you need a controller, you should write custom directives.

**Comment by rkurbatov** [comment]
http://plnkr.co/edit/YnatxPc4eHmqMqoRwfXn?p=preview - here is my example. It stop working when switched to 1.4.2+

**Comment by wesleycho** [comment]
This does not appear to be a valid use case - in this case, Angular is enforcing that you cannot use a directive that creates new $scope (`ng-controller`) with a directive that has an isolate $scope (`tab`). In this case, `tab` also creates a new `$scope` that inherits via transclusion.

One can work around this by creating namespaces on $scope for each tab.
