### ISSUE TITLE
Tooltips erratic/off-by-one when supporting both mouseenter and focus

### ISSUE THREAD

**Issue by bkardell** [angular-ui/bootstrap#3987]
Test case demonstrated here 
http://plnkr.co/edit/xj8TFBBc5NyJoRUp4Ypx?p=preview - if you use both keyboard and mouse to move back and forth you will see incorrect behavior where it doesn't show or shows when it shouldn't.

**Comment by wesleycho** [comment]
Note that this occurs because more than one is being used - the component is only currently designed to support one option right now.

**Comment by wesleycho** [comment]
Just adding, this appears to work fine if one used `focus`, as can be seen [here](http://plnkr.co/edit/CFLqGAsvn3VF89XqZrWQ?p=preview).

**Comment by bkardell** [comment]
@wesleycho yeah, but this is of course just a simple demonstration of a failure case.  Either way, it looks like it got added now, so great.
