### ISSUE TITLE
Datepicker today option is enabled if today's date is outside of max-date/min-date range

### ISSUE THREAD

**Issue by JamesM123** [angular-ui/bootstrap#3988]
The button to select Today in the datepicker is enabled and works even if today's date is outside of the valid max-date/min-date range.

I would imagine that if today's date falls outside the valid range of dates, then the today button should be hidden or disabled.

![screen shot 2015-07-22 at 11 34 43](https://cloud.githubusercontent.com/assets/3850209/8817426/c0acca3c-3065-11e5-8226-eac1fb1a6af6.png)

**Comment by wesleycho** [comment]
Given that the min-date and max-date are observable, this should likely use either ng-show/ng-hide or ng-if. I would imagine that the max-date and min-date would change relatively infrequently, so I think an ng-if would be ok.

**Comment by wesleycho** [comment]
Hmm, thinking about this more, I think a disabled would be more appropriate, perhaps with `ng-disabled` - this shouldn't be a difficult feature to implement if you want to open a PR.

**Comment by bkirtika** [comment]
+1

**Comment by wesleycho** [comment]
Please do not do a +1, it does not offer any useful signal.
