### ISSUE TITLE
Datepicker watchers problem is solved?

### ISSUE THREAD

**Issue by khusnetdinov** [angular-ui/bootstrap#3990]
Hi! 

There are several issuies and PR witch releate to datpicker problem with plenty watchers.

https://github.com/angular-ui/bootstrap/pull/1915
https://github.com/angular-ui/bootstrap/pull/1922
https://github.com/angular-ui/bootstrap/pull/3666
https://github.com/angular-ui/bootstrap/issues/3705

I just want to clear is this problem fixed? With version can i use for avoid bug?

**Comment by RobJacobs** [comment]
Those datepicker watches issue has been addressed by the following commits:

https://github.com/angular-ui/bootstrap/commit/b72efed56f68e9e5dbed934df7f47e0b5c94242c
https://github.com/angular-ui/bootstrap/commit/2a2e5de7d89a7a2b55268ec415ee60ba4315972e

There is 1 outstanding PR: #3770 which hopefully will be included in the 0.13.1 release.
