### ISSUE TITLE
alert displays close button even when no close attribute with angular 1.4.1, 1.4.2 and 1.4.3

### ISSUE THREAD

**Issue by jnizet** [angular-ui/bootstrap#3993]
A close button is displayed on the alert even when no close attribute is set on the alert, since angular 1.4.1. 

Plunkr: http://plnkr.co/edit/FXsxgH0eBpWGZevKwcLo?p=preview

I haven't been able to find, in the changelog, an explanation for this change of behavior.

**Comment by Foxandxss** [comment]
I can see that. Will check it.

**Comment by Foxandxss** [comment]
Oh, that is fixed on master.
