### ISSUE TITLE
ui-bootstrap needs more maintainers

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#3997]
Hello,

This project is really stuck and we really really need more people to collaborate with it.

We need people to do some triaging, review some pull request and if possible, to contribute with code.

**Comment by wesleycho** [comment]
Yes please! We would like to move to faster releases so features & fixes aren't so far and between.

**Comment by icfantv** [comment]
Closing as we're in a really good place and we're always happy to have more contributors.
