### ISSUE TITLE
Which npm package to use?

### ISSUE THREAD

**Issue by royaldark** [angular-ui/bootstrap#3998]
There appear to be two NPM packages for this project:
- `angular-boostrap` on 0.13.0
- `angular-ui-bootstrap` (the package listed in the readme) on 0.12.2.

Which should be used? If it is `angular-ui-bootstrap`, that package should be updated to 0.13.0. Otherwise, the readme should be updated.

**Comment by Foxandxss** [comment]
Are you sure you don't have them reversed?

`angular-bootstrap` is an old third party package which I decided to f* up and I put back (my total mistake).

People should use `angular-ui-bootstrap` which points to 0.13.0.

**Comment by royaldark** [comment]
Sorry, you're right. My brain is obviously tired :)
