### ISSUE TITLE
Relax peerDependency version of angular-ui-bootstrap

### ISSUE THREAD

**Issue by jasonrose** [angular-ui/bootstrap#4001]
https://github.com/angular-ui/bootstrap/issues/3992#issuecomment-123817297

`angular-ui-bootstrap@0.13.0` dictates `bootstrap@3.1` and `angular@~1.3.17`.  These are very restrictive.

I personally don't think that bootstrap should be a peerDependency at all, but it doesn't hurt to have it at a more relaxed version, such as `^3.1`.

For angular, I understand that angular-ui only officially supports 1.3 at this time, but parts currently work in 1.4, and I at least use 1.4 with angular-ui and have no problems.  I suggest using the version string `^1.3`, which should catch 1.3 and 1.4.

**Comment by wesleycho** [comment]
We agree - this will be fixed in 0.13.1 which we are looking at releasing possibly tomorrow (all unfixed issues and unmerged PRs will be pushed to 0.13.2).

**Comment by wesleycho** [comment]
This should now be fixed - we did a release of 0.13.1 an hour ago with the relaxed peerDependency.
