### ISSUE TITLE
Set triggers for popovers

### ISSUE THREAD

**Issue by LeleDev** [angular-ui/bootstrap#4007]
How can I set default triggers for popovers?

With tooltips, I use:
```
$tooltipProvider.setTriggers({'mouseenter':'mouseleave click'});
```

Wouldn't be useful to have a $popoverProvider.setTrigger() too?

Thank you in advance

**Comment by icfantv** [comment]
@LeleDev, per the docs https://angular-ui.github.io/bootstrap/#/tooltip, the `$tooltipProvider` controls both tooltips and popovers.  Was there a specific reason you had to have popovers configured separately?

**Comment by wesleycho** [comment]
To set default triggers, one can set
```
$tooltipProvider.setTriggers({
  mouseenter: 'mouseleave'
});
```
Only a one-to-one mapping is supported.

**Comment by LeleDev** [comment]
I've set ```$tooltipProvider.setTriggers({'mouseenter':'mouseleave click'});```, but it doesn't work with my popovers, for example with the following popover with template:
```html
<button type="button" popover-template="'popover.template.html'" popover-placement="bottom" popover-title="sampleTitle" class="btn btn-no-min-width btn-default btn-sm btn-raised ripple-effect pull-right" id="search"><i class="fa fa-search"></i></button>
```

**Comment by wesleycho** [comment]
One has to specify `popover-trigger`.

**Comment by icfantv** [comment]
@LeleDev, in order for us to assist you, please create a working plunker that demonstrates the issue you are having.  It sounds like there are two:  1) that you want to have multiple "deactivate" triggers and 2) that your trigger configuration is not being recognized.

For 1), that syntax is correct, but be aware that you are redefining the default behavior for your entire application when you do this.  For 2), again, please create a working plunker that shows the issue.
