### ISSUE TITLE
Doesn't work minMode for datepicker popup

### ISSUE THREAD

**Issue by eugenelabonarsky** [angular-ui/bootstrap#4009]
Found in versions 0.13.0, 0.13.1

# Observed behaviour: 
minMode='year' allow us to switch between other modes and after selecting year goes to month selection.

# Expected behaviour:

minMode='year' doesn't allow us to switch between other modes and after selecting year should prepopulate value

# Plunker link

http://plnkr.co/edit/wKjuZTk2xB5jtZfvO5No?p=preview

**Comment by wesleycho** [comment]
Can you recreate this in Plunker?

**Comment by eugenelabonarsky** [comment]
http://plnkr.co/edit/wKjuZTk2xB5jtZfvO5No?p=preview

**Comment by eugenelabonarsky** [comment]
datepicker-mode="'year'" min-mode="year"

**Comment by wesleycho** [comment]
Confirmed to still be an issue even with recent change [here](http://plnkr.co/edit/hiQ4EFFNd6J7BnpLoBva?p=preview).

**Comment by lucienbertin** [comment]
is there any progress made on the issue ? will it be fixed in the next release (0.13.4) ?

**Comment by kaeyonbaker** [comment]
I also got stuck to this problem,but I found a workaround by using dateOptions to define minMode but not adding attrs min-mode="month"
html:
```
<input id="dt" type="text" datepicker-popup="yyyy-MM" ng-model="search.fbdate" is-open="opened" datepicker-options="dateOptions" min-mode="'month'" datepicker-mode="'month'"/>
```
js: (in your controller)
```javascript
    $scope.dateOptions = {
      formatYear: 'yy',
      startingDay: 1,
      minMode:'month',
      class: 'datepicker'
    };
```


this part can't get minMode if we add attrs min-mode="month" to datepickerPopup
```javascript
  angular.forEach(['formatDay', 'formatMonth', 'formatYear', 'formatDayHeader', 'formatDayTitle', 'formatMonthTitle',
                   'minMode', 'maxMode', 'showWeeks', 'startingDay', 'yearRange'], function( key, index ) {
    self[key] = angular.isDefined($attrs[key]) ? (index < 8 ? $interpolate($attrs[key])($scope.$parent) : $scope.$parent.$eval($attrs[key])) : datepickerConfig[key];
  });
```

**Comment by wesleycho** [comment]
This actually appears to be a usage issue - check [this Plunker](http://plnkr.co/edit/tnwFZDC92f4deGCZmRPW?p=preview) for a working example.

The documentation does need to be clearer, but that is on the plate for our upcoming 1.0 release, so it will be clearer then.
