### ISSUE TITLE
disabled and ng-disabled ineffective on radio and checkbox buttons with Bootstrap CSS 3.3.5

### ISSUE THREAD

**Issue by jljouannic** [angular-ui/bootstrap#4013]
With Bootstrap CSS 3.3.4, `ng-disabled` and `disabled` applied to `label` associated with the `btn-radio` or `btn-checkbox` directives work has expected (See this [plunk](http://plnkr.co/edit/m5sHzwsIPPQTQpAgJsNJ?p=preview))

After upgrading to Bootstrap CSS 3.3.5, it does not work anymore (See this [plunk](http://plnkr.co/edit/O2kghWBeYszJWwXpdC8X?p=preview)).

To be more precise, styling is good (even better than with 3.3.4) but behaviour is not what it should be.

I guest solving issue [#16092](https://github.com/twbs/bootstrap/pull/16092) on Bootstrap CSS had a harmful effect on `radio` and `checkbox` `buttons` behaviour.

**Comment by jljouannic** [comment]
As a temporary workaround, the following CSS rule set can be used:

```less
label.btn[disabled] {
    pointer-events: none;
}
```
Styling of the cursor is not as good as it is with Bootstrap 3.3.5, but behaviour is restored.

**Comment by wesleycho** [comment]
Take a look at the fix I have in #4026 @jljouannic - this should do the trick :) .
