### ISSUE TITLE
Carousel docs have no mention of pause, next, previous

### ISSUE THREAD

**Issue by smlombardi** [angular-ui/bootstrap#4015]
Perhaps instead of having an example which is rarely used (adding slides on the fly) we could get more documentation on basic carousel actions, or at least how to access the ones on Bootstrap itself?

**Comment by wesleycho** [comment]
Can you explain what you would like to see in the docs?

**Comment by smlombardi** [comment]
How to create custom controls for navigation, mostly. Replace the standard
UI with one of my own.

For example, I needed a carousel with no dots or arrows, but instead a set
of buttons for next etc.

**Comment by wesleycho** [comment]
The intention is for any hiding to be done in CSS. If you would like to file a PR with a note in the docs about that, I would be glad to review & merge it.

Otherwise, this is still a bit vague as to what is desired.

**Comment by smlombardi** [comment]
Yeah, sorry for being so vague.

I guess I was looking for a way to add my own button for "next". No matter
what I did no success. I finally realized I had to put button inside
carousel div (seems obvious now, but docs would have helped)

Of course once I got that in there, my next button would only send the
carousel backward. Using auto plus was fine but next went backwards. I cand
example code when back at work.

Thanks!

**Comment by wesleycho** [comment]
Closing, as we do not want to necessarily document these APIs, as they are exposed to the templates and not normally accessible unless one overrides the template. For this type of case, it is always on the developer to read the code to see what is doable since the developer is overriding typical behavior.
