### ISSUE TITLE
Issue in animations with the latest angularjs and angular-ui-bootstrap

### ISSUE THREAD

**Issue by salalaslam** [angular-ui/bootstrap#4017]
I have created this [pen](http://codepen.io/salalaslam/pen/zGmLVq) to illustrate the problem

**Comment by wesleycho** [comment]
Here is a working version - http://codepen.io/wesleycho/pen/VLVLVZ

Note the inclusion of ngAnimate as a module dependency.

**Comment by salalaslam** [comment]
works for collapse but not working for modal, [see here](http://codepen.io/salalaslam/pen/YXRXbX)

**Comment by wesleycho** [comment]
[Not true](http://plnkr.co/edit/cLENui6xgn348uLxz92C?p=preview). Not sure what is wrong with CodePen, but it's clearly not a UI Bootstrap problem.

**Comment by salalaslam** [comment]
apparently the problem is in adding the ng-app attribute, if its on the html it works and if its in body it wont work!

**Comment by salalaslam** [comment]
apparently the problem is in adding the ng-app attribute, if its on the html it works and if its in body it wont work!
[this](http://codepen.io/salalaslam/pen/YXRXbX) works
[this](http://codepen.io/salalaslam/pen/doQYMY) dont
doesn't look like codePen issue is it?

**Comment by RobJacobs** [comment]
@salalaslam  The issue seems to be Chrome only (both work in IE11) with having the ng-app and ng-controller declaration on the same element.  I have to agree with @wesleycho.

**Comment by salalaslam** [comment]
but the app i am building will only be used in the chrome and its still a problem, so any fix/patch for it?

**Comment by wesleycho** [comment]
Just move your ng-app to a higher element then.
