### ISSUE TITLE
NuGet Package for 0.13.1

### ISSUE THREAD

**Issue by pascalberger** [angular-ui/bootstrap#4022]
Please update the NuGet Package also to version 0.13.1

**Comment by kukac7** [comment]
@pascalberger https://github.com/angular-ui/bootstrap-bower

**Comment by xt0rted** [comment]
The NuGet package has been updated to [v0.13.1](https://www.nuget.org/packages/Angular.UI.Bootstrap/0.13.1)

**Comment by pascalberger** [comment]
Thanks!
