### ISSUE TITLE
gh-pages: 0.13.1 still marked as SNAPSHOT

### ISSUE THREAD

**Issue by royaldark** [angular-ui/bootstrap#4025]
This is related to the `gh-pages` branch.

https://github.com/angular-ui/bootstrap/commit/ea1c2a04849c88713f4ad05b21461a5b5d7d60d9 removed `-SNAPSHOT` from the filenames for 0.13.1, but the version headers in the actual files still have it (e.g. `Version: 0.13.1-SNAPSHOT - 2015-07-23`).

**Comment by wesleycho** [comment]
Fixed via 7af3115b0aec348b0871425cd137b90aacd38ca7

**Comment by royaldark** [comment]
Looks like https://github.com/angular-ui/bootstrap/blob/gh-pages/ui-bootstrap-0.13.1.js and https://github.com/angular-ui/bootstrap/blob/gh-pages/ui-bootstrap-0.13.1.min.js still have `-SNAPSHOT` in them.

**Comment by wesleycho** [comment]
Hm weird - just removed them via b1218f73f1399410bbddd1ee383a6feb634c336b

**Comment by royaldark** [comment]
Looks good now. Thanks!
