### ISSUE TITLE
panel-title > a(href='# ') in 0.13.1

### ISSUE THREAD

**Issue by suresh-mits** [angular-ui/bootstrap#4029]
In new Patch of 0.13.1 the anchor tag href has been changed from javascript:void(0) to '#'  which is causing problem like redirecting to # when clicking any text field inside accordion-heading.

**Comment by RobJacobs** [comment]
That was done under this PR: https://github.com/angular-ui/bootstrap/commit/fb302c6086543420b3561be3ed5c49ac3974c243 for CSP compliance.  Notice $event.preventDefault() was added to the anchors ng-click attribute to prevent that.  Can you please create a plunkr that reproduces the issue?

**Comment by wesleycho** [comment]
I think this is safe to close, as we have changed it back to an empty href as mentioned in #4104.
