### ISSUE TITLE
ng-click on progress bar?

### ISSUE THREAD

**Issue by rbosneag** [angular-ui/bootstrap#4031]
More of a question than an issue here:

I am trying to use the progress bar to show the elapsed/buffered time of an audio player and it seems to be going well. 

I am wondering if there is a way to bind the progress bar to user actions like ng-click and returning the new value where the click was "clicked". This should help me for implementing a seek function for the audio player. 

Any suggestions would be greatly appreciated.

**Comment by icfantv** [comment]
Are you asking if there's a way to add a click handler to the progress bar to update the value?  If so, will this work:  http://plnkr.co/edit/djihXbK7dOXqwHeZa7Z2.

**Comment by pkozlowski-opensource** [comment]
@rbosneag such support question would be better asked a dedicated support channel: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
