### ISSUE TITLE
Modal close animation: .modal-dialog and .modal-backdrop duration stack (instead of firing simultaneously)

### ISSUE THREAD

**Issue by mpiasta-ca** [angular-ui/bootstrap#4036]
I'm wondering if this is a feature, or unintended behavior...?

When modal is closing, first the `.modal-dialog` will animate-out; and only when that is complete, then the `.modal-backdrop` will begin animate-out. So if `.modal-dialog` animation duration is 300ms, and .modal-backdrop animation is 300ms, it takes 600ms for the modal to close [before the page becomes clickable again].

In contrast, when modal is opening, `.modal-dialog` and `.modal-backdrop` animate simultaneously. So if each requires duration of 300ms, the modal only requires 300ms to open.

As someone who does not like waiting, I find this to be irksome. However, if I reduce the animation-out duration to be 150ms for each, for a total of 300ms, the animation feels choppy.

**Comment by wesleycho** [comment]
Can you reproduce this in a Plunker? It would make it much easier to debug.

**Comment by mpiasta-ca** [comment]
[Created a plunkr](http://plnkr.co/edit/x0TuQRla0SiGB4sZa4bk?p=preview). When you click the button, it takes 3 seconds to load the modal-dialog and modal-backdrop. When you click close, first the modal-dialog takes 3 seconds to close, then the modal-backdrop takes another 3 seconds to close, for a total of 6 seconds.

**Comment by wesleycho** [comment]
Thanks for this clear reproduction - I will take a look at this possibly this weekend.

If I have this right, you would like the animation of the backdrop and the modal to happen simultaneously when the modal first appears? If so, that sounds like a reasonable request.

**Comment by mpiasta-ca** [comment]
I would like the close event for `.modal-dialog` and `.modal-backdrop` to trigger at the same time, so that if each has a close animation duration of 250ms, both will be hidden/removed after 250ms (instead of the current 500ms).

ie. while `.modal-dialog` is fading-out (or sliding-up), that the `.modal-backdrop` is simultaneously fading from opacity 0.5 to 0.0, such that both close/hide animation events end at the same time (instead of the current, where one begins only after the other ends).

**Comment by mpiasta-ca** [comment]
@wesleycho works great, thanks for fixing that so quickly!
