### ISSUE TITLE
Pagination does not seem to work when ng-if is used

### ISSUE THREAD

**Issue by vorillaz** [angular-ui/bootstrap#4045]
```
 <pagination ng-if="flag" total-items="bigTotalItems" ng-model="bigCurrentPage" max-size="maxSize" class="pagination-sm" boundary-links="true" rotate="false" num-pages="numPages"></pagination>
```
http://plnkr.co/edit/EaGwrL1i47LFJU7QQ0lh?p=preview

**Comment by pkozlowski-opensource** [comment]
it is scoping issue: http://plnkr.co/edit/RSnfknFAvrO4hrXFHqDQ?p=preview

See: https://github.com/angular/angular.js/wiki/Understanding-Scopes

**Comment by fmalk** [comment]
I also encountered this bug. My workaround was to use `ng-show` instead.
