### ISSUE TITLE
Missing `.in` class in modal with custom template

### ISSUE THREAD

**Issue by edouard-lopez** [angular-ui/bootstrap#4046]
I'm using `ui.bootstrap` v`0.13.x` with custom template, while the modal is enable it is invisible due to the missing `in` class. This also happen with the [example markup/js from the doc](https://angular-ui.github.io/bootstrap/#/modal)

### `pacakge.json`

My project got the following `pacakge.json` :

    {
      "name": "project",
      "dependencies": {
        "bootstrap": "3.3.x",
        "angular": "1.3.x",
        "font-awesome": "4.3.x",
        "ui.bootstrap": "0.13.x",
        "angular-animate": "1.3.x"
      }
    }

### Scripts
Here are the scripts I concat/minify into `vendor.js`: 

    vendor_scripts: [
        'bower_components/angular/angular.min.js',
        'bower_components/angular-sanitize/angular-sanitize.min.js',
        'bower_components/angular-animate/angular-animate.min.js',

        'bower_components/ui.bootstrap/src/dropdown/dropdown.js',
        'bower_components/ui.bootstrap/src/alert/alert.js',
        'bower_components/ui.bootstrap/src/bindHtml/bindHtml.js',
        'bower_components/ui.bootstrap/src/modal/modal.js',
        'bower_components/ui.bootstrap/src/position/position.js',
        'bower_components/ui.bootstrap/src/progressbar/progressbar.js',
        'bower_components/ui.bootstrap/src/tooltip/tooltip.js',
        'bower_components/ui.bootstrap/src/transition/transition.js'
    ],

### modalInstance

    var modalInstance = $modal.open({
        templateUrl: '/static/html/inventory/change-quantity-modal.html',
        controller: 'ChangeQuantityCtrl',
        resolve: {
            …
        }
    });

#### `backdrop.html`

    <script type="text/ng-template" id="template/modal/backdrop.html">
      <div class="modal-backdrop fade {{ backdropClass }}"
           ng-class="{in: animate}"
           ng-style="{'z-index': 1040 + (index && 1 || 0) + index*10}"
      ></div>
    </script>

#### `window.html`
    <script type="text/ng-template" id="template/modal/window.html">
      <div tabindex="-1" role="dialog" class="modal fade" ng-class="{in: animate}" ng-style="{'z-index': 1050 + index*10, display: 'block'}" ng-click="close($event)">
          <div class="modal-dialog" ng-class="{'modal-sm': size == 'sm', 'modal-lg': size == 'lg'}"><div class="modal-content" modal-transclude></div></div>
      </div>
    </script>

##### Default template
I tried to use the template from the package but then get `Error: $transclude is not a function`. 

I reckon it's a different issue than #3559 as I'm using angular `1.3.x`.

**Comment by pkozlowski-opensource** [comment]
I think that are mixing JS version with a template version (are you taking released js and a template from master?).

**Comment by edouard-lopez** [comment]
1. I'm copying template from `bower_components/ui.bootstrap/template/modal` ;
2. and minifying JS from `bower_components/ui.bootstrap/src/modal/modal.js`

**Comment by pkozlowski-opensource** [comment]
@edouard-lopez something else must be going on then, since it works correctly on the demo page. Please provide a plunker with a minimal reproduce or it is not actionable, really

**Comment by edouard-lopez** [comment]
I got the window to miss not the backdrop as I don't know how to override the template:

http://plnkr.co/edit/eFwBU5YANspmZFCRf5Zm?p=preview

**Comment by RobJacobs** [comment]
The modal has changed how it implements the animation classes due to the animation changes in 1.4, the updated templates now have the following attributes:

    modal-animation-class="fade"
    modal-in-class="in"

instead of ng-class.  You will need to update your custom modal template accordingly.

**Comment by edouard-lopez** [comment]
Problem solved by:
* updating the templates (without the wrapping `<script type="text/ng-template" id="template/modal/backdrop.html">` tag)
* removing `<ng-include src="'template/modal/backdrop.html'"></ng-include>`
