### ISSUE TITLE
What's the official word on Angular 1.4 compatibility?

### ISSUE THREAD

**Issue by openface** [angular-ui/bootstrap#4050]
It seems people are having good success using this with Angular 1.4.    I'm about to start a new project soon, and am curious what the official status here is.   The roadmap does not seem to cover this.

**Comment by wesleycho** [comment]
`master` is currently 1.4 compatible as of 1 minute ago, and we will be releasing this weekend :)

**Comment by openface** [comment]
:+1:

**Comment by openface** [comment]
Excellent, thanks.  I hope this release makes into the NPM repository soon.   I only see 0.12.1 there now.
