### ISSUE TITLE
Accordion Animation Missing on Expand and Collapse

### ISSUE THREAD

**Issue by brencon** [angular-ui/bootstrap#4053]
The sample code provided for the Accordion control no longer animates when expanding or collapsing elements within the accordion.

http://plnkr.co/edit/da8QO4EEqIJHqQYEHHRW?p=preview

Also: when using Chrome, an outline appears when clicking on the panel title. The following style (added to the Plunkr) corrects the issue:

`accordion * {outline: 0 !important;}`

**Comment by wesleycho** [comment]
You forgot ngAnimate - that is an optional dependency.

You can see it working [here](http://plnkr.co/edit/XmhAYNPHnpLtgYSSAdDL?p=preview).

**Comment by brencon** [comment]
Thank you. The Plunkr sample for Accordion on https://angular-ui.github.io/bootstrap/ is still missing the ngAnimate dependency. Although it's optional, I think most people expect to see the smooth animation applied to the control.
