### ISSUE TITLE
How do I show a tooltip on focus of something other than an <input>

### ISSUE THREAD

**Issue by mjhamm75** [angular-ui/bootstrap#4058]
I need to have a tooltip show when I focus on a `div`, `p`, or some other kind of block element.  I originally used `click` as the trigger, but when I do this, I have to click on the `div` to hide the tooltip.  I want the tooltip to disappear when I click anywhere on the page.  Here is a plunkr to show what I am talking about.

http://plnkr.co/edit/IWHPFfpei5UzUza8icac?p=preview

**Comment by RobJacobs** [comment]
@mjhamm75 Questions of this nature will get a better response on Stackoverflow, please see the [Need help](https://github.com/angular-ui/bootstrap#need-help) section here.  This issue has nothing to do with the tooltip directives, some elements (like a div, p) will not accept a focus event without a tabindex attribute.  In your plunk, I added tabindex="-1" to the p element and the tooltip showed up.
