### ISSUE TITLE
Tooltip is not closed when exiting enclosing <div> containing disabled checkbox

### ISSUE THREAD

**Issue by ijprest** [angular-ui/bootstrap#4060]
Angular 1.4.3, Angular-UI-Bootstrap 0.13.1, Chrome 44.

* Put a tooltip on a `div`
* Within that `div`, put a disabled checkbox:
  * `<label><input type="checkbox" ng-disabled="true"><span>Label</span></label>`
* Run the app.
* Hover over the checkbox/label `div`... tooltip appears.
* Exit the `div` by moving the mouse to the *left*... tooltip doesn't close.

Note: this is using the standard Bootstrap styling.  You can make the problem less likely to appear by putting a margin (say, 5px) on the left side of the checkbox, but the problem can still occur if you move your mouse fast enough.

Here's a plnkr:  http://plnkr.co/edit/CZpwOw1NXcoI8LQAbnDV

**Comment by ijprest** [comment]
See also related issue #2059.

**Comment by wesleycho** [comment]
Forked Plunker to a more useful one [here](http://plnkr.co/edit/HPdSmQONRQJSOHp2m0EN?p=preview) for reference.

**Comment by wesleycho** [comment]
This looks like a fundamental issue in jqLite - opened an issue https://github.com/angular/angular.js/issues/12703
