### ISSUE TITLE
`disabled` support for Accordion

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#4067]
The accordion supports not going to a disabled panel, but it does not appropriately reflect it in the UI. This should support ngDisabled properly.

**Comment by wesleycho** [comment]
This also needs to work properly with accessibility, not allowing the user to tab a disabled panel.

**Comment by icfantv** [comment]
Linking in #4772 to this issue, but not closing this since it's not just ARIA related.
