### ISSUE TITLE
Datepicker popup '$digest already in progress' on route change

### ISSUE THREAD

**Issue by artaommahe** [angular-ui/bootstrap#4076]
'$digest already in progress' fires if datepicker popup is opened and we change current state

ui.bootstrap version 0.13.1, angular 1.4.3, last angular-route or ui-router

http://plnkr.co/edit/FFEGvrbDrzX1pt2u9rYL?p=preview
Steps:
- click go to state 2
- click go to state 1
- click on input for popup showing
- click go to step2
- see error in console

**Comment by wesleycho** [comment]
Looks like this is still an issue, as can be seen [here](http://plnkr.co/edit/3tlbi5U101bavwEsS9sI?p=preview)

This should be an easy fix.

**Comment by realityking** [comment]
I know it's not very common, but could you cut a releae for this? We've just go off our own fork because of the date bugs and now this bit us.

**Comment by wesleycho** [comment]
@realityking I am considering a midweek release to get out this fix and a few others out there.

**Comment by realityking** [comment]
@wesleycho That'd be awesome. Thank you.

**Comment by wesleycho** [comment]
Sorry for not deploying yet - trying to make sure some other major issues are addressed. It may not be until early next week, the only issue left that we need addressed properly is #4090
