### ISSUE TITLE
Accordion- collapsible panels not working with new ui-bootstrap

### ISSUE THREAD

**Issue by bharos** [angular-ui/bootstrap#4085]
This feature used to work with an older code of ui-bootstrap. Now,it is opening and collapsing but the transition is not happening, it is suddenly opening and closing.. I can also see some changes in new code in collapse functions. Can I get to know if anything needs to be changed in my accordion to make it work

**Comment by bharos** [comment]
This is the working version 0.12.1 - 2015-02-20.. But when 0.13 + is used it does not transition during collapse and expand

**Comment by wesleycho** [comment]
@bharos have you added ngAnimate?

**Comment by bharos** [comment]
Yes, I had added ngAnimate also, but seems like its missing something else.
Is there a minimum required version for angular also for this to work ??

**Comment by RobJacobs** [comment]
@bharos 0.13.2 is tested on Angular 1.4.  Please provide a plunk so we can look into this further.

**Comment by bharos** [comment]
Okay. It is now workign fine. Seems like some issue was there for ngAnimate.
Now when everything is included properly,it is working.Thanks for the help
