### ISSUE TITLE
set ng-model value on <tabset> <tab> when active

### ISSUE THREAD

**Issue by donmyhl** [angular-ui/bootstrap#4086]
Hi. 

Is it possible to set a $scope value on a tab when its  active? 

Example: 3 tabs with ng-model="tabID" on each. Then {{tabID}} would be either 1,2,3,4 depending on what tab is active. 

Hope you understand

**Comment by wesleycho** [comment]
You can programmatically set what tab is active by watching for your model change and using the value to appropriately determine which tab should be active and set `tab.active = true` for that tab.

Otherwise, this is not clear at all.

**Comment by RobJacobs** [comment]
@donmyhl Questions of this nature will get a better response on Stackoverflow, please see the [Need help](https://github.com/angular-ui/bootstrap#need-help) section.
