### ISSUE TITLE
carousel contents collide when going left for the first time

### ISSUE THREAD

**Issue by nschloe** [angular-ui/bootstrap#4087]
When clicking the right arrow on the carousel, the current content exists to the left and the next content enters from the right, just as expected.

When clicking the left arrow on a carousel, the next content correctly enters from the left. However, the current content also exists to the left, instead of to the right. For all subsequent left-arrow clicks, it works as expected.

The same wrong behavior is also observed when clicking the right arrow *after* having clicked the left arrow at least once.

**Comment by wesleycho** [comment]
The fix should be merged in shortly and will be released in 0.13.3 likely around Wednesday.
