### ISSUE TITLE
0.13.2 - When a button-checkbox's ng-disabled is false, model doesn't change when clicking

### ISSUE THREAD

**Issue by starf** [angular-ui/bootstrap#4088]
when (checkbox/radio) button's ng-disabled has a false value, clicking it does not change the model

problem occured after switching to 0.13.2 (worked OK in 0.13.1)

see plunkr: http://plnkr.co/edit/hjcmk0fNvRVjD0rFJjAG?p=preview

**Comment by wesleycho** [comment]
Good catch - @RobJacobs looks like your observation about `'disabled' in attrs` was on point. Changing to `!attrs.disabled` there fixes it, as can be seen [here](http://plnkr.co/edit/Nn9Z2Icfhj1q21l52hay?p=preview).

**Comment by wesleycho** [comment]
Just a note, I may do a mid-week release in order to get this fix and another out there.
