### ISSUE TITLE
Rating directive HTML does not meet Bootstrap standards

### ISSUE THREAD

**Issue by Blackbaud-MatthewBell** [angular-ui/bootstrap#4089]
Elements with the `.glyphicon` class should not contain any content.  The rating directive includes an `.sr-only` element inside the `.glyphicon` element.  Rather than nesting the elements, it should use markup such as:

     <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     <span class="sr-only">star</span>

Here's an example directly pulled from the documentation:

     <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          Enter a valid email address
    </div>

The current HTML triggers errors from BootLint indicating that it does not comply with Bootstrap standards. See issue below from BootLint confirming this.

https://github.com/twbs/bootlint/issues/298

**Comment by wesleycho** [comment]
This is already fixed in `master`, as can be seen by https://github.com/angular-ui/bootstrap/commit/cf65a6357cf70808e07658af8cf9fe142c5dcf42
