### ISSUE TITLE
Dropdown Key Navigation doesn't work when "dropdownAppendToBody" is enabled

### ISSUE THREAD

**Issue by robertaistleitner** [angular-ui/bootstrap#4091]
When pressing up/down arrow buttons it causes an exception in the "keyboardNav" directive in this line:
```javascript
var elems = angular.element(element).find('a');
```

I think this line fixes this issue (accessing the dropdownMenu jQuery element from a reference):
```javascript
var elems = dropdownCtrl.dropdownMenu.find('a');
```

**Comment by icfantv** [comment]
@robertaistleitner, please create a working plunker that demonstrates this issue and link it here.  Thanks.

**Comment by wesleycho** [comment]
Definitely a [bug](http://plnkr.co/edit/MAzW2nscc5F8y5OCOSP2?p=preview).

**Comment by wesleycho** [comment]
Want to tackle it @icfantv? Should be an easy fix - otherwise I can tackle it.

**Comment by icfantv** [comment]
Yea, I can take a look.

**Comment by robertaistleitner** [comment]
Thanks guys, I was in a hurry yesterday.. ;)

**Comment by icfantv** [comment]
Looks like that plunker is horked.  With the fix in place, you can't navigate past the first list item and the keyboard navigation no longer responds.  [Here's](http://plnkr.co/edit/YZ2woGMgABThe7CgGYBC) an updated one with the proposed fix in place.

**Comment by GregePorter** [comment]
I am seeing the commit, 0b37f08, and I am running the most current build and I'm still seeing this error.
@robertaistleitner, plunkr is still working and it demonstrates the error. His solution works too (I tried it locally)
