### ISSUE TITLE
ng-disabled directive does not seem to work with btn-radio directive, if ng-disabled evaluates to false

### ISSUE THREAD

**Issue by ravenscar** [angular-ui/bootstrap#4094]
In ui-bootstrap-tpls-0.13.1.js, having an ng-disabled directive in conjunction with a btn-radio directive worked as expected: http://plnkr.co/edit/JAhGr0MkKN88Nk1WQ8HD?p=preview

In version ui-bootstrap-tpls-0.13.2.js simply having the ng-disabled directive (even if it evaluates to false) seems to prevent the buttons in the radio group to be selected. Note that it does not disable the buttons, they seem to be functional but the click event seems to be lost somewhere: http://plnkr.co/edit/yyAGH2auvVOJRHwBJPcc?p=preview

**Comment by wesleycho** [comment]
Thanks for reporting this, but you were beaten to it by under a day in #4088 :) . In addition, I was able to fix this up in https://github.com/angular-ui/bootstrap/commit/707fbf55c04db115d97d785bec292212e410a1ee in that time, which should be in a new release 0.13.3 this Wednesday (along with a few other important fixes).

**Comment by qoshi** [comment]
Thank you very much for this
