### ISSUE TITLE
add additional functional test coverage for dropdown

### ISSUE THREAD

**Issue by icfantv** [angular-ui/bootstrap#4099]
Currently, all the functional tests for dropdown assume the `dropdown` directive is being placed on an `<li>` and none of our examples [here](http://angular-ui.github.io/bootstrap/#/dropdown) actually even show that as an option.  This, combined with `dropdown-append-to-body`, resulted in #4091.  The similar applies to `dropdown-toggle`.

The functional tests should be augmented to reflect realistic, accurate, and documented uses of the `dropdown` and `dropdown-directive`.

**Comment by wesleycho** [comment]
Closing, as I think in this case, the template should not affect the tests since `li` is functionally not too different from `div` or `span`, minus CSS differences, and doesn't have special semantics such as anchor tags.
