### ISSUE TITLE
Carousel custom indicator(arrow) by using ng-class [Carousel]

### ISSUE THREAD

**Issue by KimCrab** [angular-ui/bootstrap#4100]
I've seen many qeustions about remove indicator or customize indicator and all the answers are "Using ng-class" But, I just don't understand how it works..so, would you please show me an example? 
I think many people are searching this example.

**Comment by wesleycho** [comment]
One can just override the carousel template in $templateCache.

**Comment by RobJacobs** [comment]
Questions of this nature will get a better response on Stackoverflow.  The [carousel](https://github.com/angular-ui/bootstrap/blob/master/template/carousel/carousel.html) template uses to anchor elements with the glyphicon-chevron-right/left classes to create the indicator arrows.  You will need to create your own template using the content you desire.
