### ISSUE TITLE
Click in accordion-heading clears $location

### ISSUE THREAD

**Issue by snajberk** [angular-ui/bootstrap#4104]
Hi,

I noticed a bug in a new version 0.13.2 (it is OK in 0.13.0). 

I am using buttons inside of "accordion-heading" section, which worked fine in previous version, but latest release negatively affects location - it clears it completely. In other words: $location.path() is cleared after every single click on one of these buttons.

I created a plunker, so you should be able to easily check it. All you have to do is to open a preview window to see the URL.

Example usage:
```javascript
    <accordion close-others="false">
      <accordion-group is-open="true">
        <accordion-heading>
          <div>
            Accordion heading
            <input type="button" ng-click="changeLocation($event)" value="Change location (broken)" />
          </div>
        </accordion-heading>
```

Plunker: http://plnkr.co/edit/Ub43PHtVxnPbmRzU0mAJ?p=preview

**Comment by wesleycho** [comment]
Reproduction with latest from `master` [here](http://plnkr.co/edit/4tCyQlRRkP8k01Dtj6Tx?p=preview).

This looks like a problem for some reason with the anchor tag having `href="#" ng-click="$event.preventDefault(); ..."` - however, removing that creates accessibility problems.

**Comment by wesleycho** [comment]
To expand on this, Bootstrap uses the anchor tag in accordions to hook into the `cursor: pointer` style, so removing the `href` completely does not seem to be a good option as that breaks CSS.

`href="javascript:void(0)"` is CSP non-compliant.

Any other `href` value, even an empty one, seems to require `event.preventDefault()` paired with it.

I'm a bit stumped as to the best approach here.

**Comment by pkozlowski-opensource** [comment]
@wesleycho I remember this being a pb for quite some time and we've kept adding / removing this href back and forth. I wonder if `<a href>`  instead of `<a href="#">` would do the trick here? AngularJS should prevent default on empty hrefs, no?

**Comment by wesleycho** [comment]
Aha, I found where I saw the issue with the empty href - #3799 . Perhaps that is more appropriately filed against the router though, if it hasn't been already.

I will change all usage to empty `href`s then.

**Comment by pkozlowski-opensource** [comment]
Right. I think that there are some corner cases with empty `href` as well (I remember people reporting reload pbs with it), but I agree that we should track those pbs instead. In any case `href="#"` is not the best idea IMO.

**Comment by icfantv** [comment]
Linking issues, #5361, #4777, #4533, and #3199.  For the relevant conversation in Bootstrap, see [this thread](https://github.com/twbs/bootstrap/issues/18975).

**Comment by roger2hk** [comment]
It seems using the empty href would cause issue #6262.
