### ISSUE TITLE
btn-radio/btn-check directives not working on 0.13.2  if combined with ng-disabled directive

### ISSUE THREAD

**Issue by terryt2000** [angular-ui/bootstrap#4105]
commit 42e1af5c provided a fix to ensure the *btn-radio* and *btn-check* directives respected the 'disabled" attribute.  Unfortunately the implementation doesn't seem to be compatible with using the ng-disabled directive on the element as well.

If ng-disabled is present, the buttons will not respond to clicks: see plunk using angularjs 1.13.17 with ui-bootstrap 0.13.2 -> http://plnkr.co/edit/VGBoML5oh4VvEP9kwT3g?p=preview

Instead of:

`if ('disabled' in attrs) {`

on lines 27 and 71 of buttons.js, it works if you change to 

`if(attrs.disabled) {`

**Comment by wesleycho** [comment]
This already is fixed on `master` & will be going out in a fix likely tomorrow.
