### ISSUE TITLE
Push last version to Meteor package angularui:angular-ui-bootstrap

### ISSUE THREAD

**Issue by EvilJohnny** [angular-ui/bootstrap#4112]
Hi,

if I am not wrong, the latest version available for Meteor is 0.13.0. I wonder if it's posible to push the latest version, so we can update it from the official resource :)

Thanks!

**Comment by wesleycho** [comment]
I don't think we maintain that.

**Comment by pkozlowski-opensource** [comment]
Nope, we don't maintain any Meteor-related artifacts, and IMO we should not (we do already distribute this package using variety of channels).  

@EvilJohnny you should contact people who published things in the first place (not sure who it might be as not familiar with the meteor ecosystem).

**Comment by EvilJohnny** [comment]
Ops! Sorry about that then! The atmosphere package explorer it was pointing here, so I thought this was the correct place to report it.

Thanks guys!

**Comment by cmddavid** [comment]
Just for everyone in need of the latest version, i added it to Atmosphere. I did this since we have no way of contacting the author of the angular-ui account. Check it out here: https://atmospherejs.com/enforcer/angular-ui-bootstrap

**Comment by markleusink** [comment]
@cmddavid Thanks! 

It sucks that someone created an (official sounding) account named 'angularui' on atmospherejs.com that points to this repo, but apparently doesn't have any relation with the people here and isn't maintained.

**Comment by psychoph** [comment]
@cmddavid Is there a repo i can fork to create a new atmosphere package that uses the latest angualr-ui-bootrap? You updated the package to 0.13.3 but it doesn't look like there has been an update since.

**Comment by cmddavid** [comment]
@psychoph Sorry for my late response, i updated the package now. I don't have anything automated so its basically a 4 step plan: download the latest version of ui-bootstrap, change the package.js, change the readme.md and then running meteor publish. If you want i can put the code in a repo but it would require you to push another package to Atmosphere unless we share the same Atmosphere account.
