### ISSUE TITLE
If I use method in popover (popover="{{hello()}}") it is getting called multiple times. 

### ISSUE THREAD

**Issue by rajputvai** [angular-ui/bootstrap#4114]
Can you please tell me why 'hello()' method is getting called multiple times in this plnkr (see it in console)? You can also observe this on any popup show/hide.

http://plnkr.co/edit/Wt2fwMu9cIxSajDH1k43?p=preview

Is it bug?

I have a code where I am doing this way. I can't put everything together in popover attribute as it has many data to iterate and evaluate. Is there any better way to do this?

**Comment by wesleycho** [comment]
That is how angular works.

If you do not need to evaluate it so many times, you may consider using a ES5 getter instead.

**Comment by rajputvai** [comment]
Yes correct, It is angular behaviour and I am newbie in angular. Can you please help me to understand this, Why it is calling multiple times even though popover for that element is not triggered?

**Comment by wesleycho** [comment]
This requires understanding how $scopes and the $digest cycle works in angular - I recommend reading [this](https://github.com/angular/angular.js/wiki/Understanding-Scopes).

Essentially in the watch expression for the component, which is watching for changes in the expression, it evaluates the expression for changes. If it has to run a watch listener, it then runs it, and then executes another $digest cycle, which evaluates all watch expressions again for changes.

In the future, this type of problem is better asked & solved using StackOverflow, or #angularjs on FreeNode.
