### ISSUE TITLE
Button Groups Not Triggering When disabled

### ISSUE THREAD

**Issue by bensquire** [angular-ui/bootstrap#4116]
*EDITED* for clarity and to fix link.

In 13.2 when you use ng-disabled on a button group (either with btn-checkbox or otherwise) regardless of the ng-disabled state the click event never triggers.

Using [this plunker](http://plnkr.co/edit/fmLzkvLwzYeaeURdYasH), try changing the ui-bootstrap version between .2 and .1 and you'll see what I mean.

**Comment by icfantv** [comment]
Hey @wesleycho, we just talked about the ability to uncheck a radio button.  I don't remember if there was an issue backing this or not though I want to say yes.

@bensquire is there a particular reason you want to be able to uncheck a radio button?  I was looking for a valid use case.  This sounds like you might want a checkbox group instead.  I would argue that people, in general, understand and expect radio buttons to not be unclickable - especially after 15-20 years of that behavior on the web (and then previously from desktop apps).

**Comment by RobJacobs** [comment]
I believe this issue is fixed under this commit: https://github.com/angular-ui/bootstrap/commit/c9b0d0b05f18257b6e58cb732dbd0421321fc7de

**Comment by wesleycho** [comment]
This should be fixed in `master`.
