### ISSUE TITLE
Remove the `angular.version.minor > 4` checks

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#4122]
These checks should be removed once we hit 0.14.0 & claim angular 1.4+ support.

- [ ] Carousel
- [x] Modal

**Comment by icfantv** [comment]
This is referencing PR #4121 which fixes issue #4119.

**Comment by Foxandxss** [comment]
Got lost. Don't we have 1.4 support at the moment? I can see changing this line for $injector.has, but I am confused.

**Comment by wesleycho** [comment]
We do, but we still also support 1.3 - there is one check left for the $animate listener, which might be able to be checked by checking
```javascript
if ($animate.one) {
...
else {
...
}
```

**Comment by wesleycho** [comment]
Hmm the carousel one is not as easy to remove since the `one` listener is on the element itself - perhaps I'll hold off on this until 0.14.0.

**Comment by wesleycho** [comment]
Rescheduling this - this is unnecessary at this time, and I don't think it's a good idea to force 1.3 uncompatibility here. Maybe we can revisit for 1.0.
