### ISSUE TITLE
How to programatically open elements of the accordion?

### ISSUE THREAD

**Issue by rc9000** [angular-ui/bootstrap#413]
Hi

Can somebody please tell me how I can tell the accordion that certain elements are open from the beginning, and how I can set this from the angular controller (e.g. I get URL parameters which tell me what elements to open on load of the page).

Thanks!

**Comment by Bhavyasujay** [comment]
Hi somebody help me...
we need to make sure we enable that particular accordian and also we need check the checkbox for sub category please help me...and i need example 
using angularjs
