### ISSUE TITLE
Pagination 'direction-links' to support glyphicons

### ISSUE THREAD

**Issue by Frondor** [angular-ui/bootstrap#4130]
just by providing a string like `glyphicon-chevron-right` the directive should render a `<span class="glyphicon glyphicon-chevron-right"></span>` instead of a simple character or string.

**Comment by wesleycho** [comment]
Any reason why you wouldn't just use `&gt;` or `&lt;` for that?

**Comment by Frondor** [comment]
In a small pagination they are really small, and not good looking at all.
In bootstrap you can place whatever you want inside the list items

**Comment by wesleycho** [comment]
The problem is, your suggestion is tied too heavily to one particular implementation. What if someone wants to use Font Awesome icons for example?

The best solution is to allow `templateUrl` overriding at the directive level IMO.

**Comment by RobJacobs** [comment]
We could potentially add unique classes to the pagination first, last, next, previous elements that would allow people to use the css content property to set the icon, so the pagination button would look like so:

    <li ng-if="::boundaryLinks" ng-class="{disabled: noPrevious()||ngDisabled}"><a href class="pagination-first" ng-click="selectPage(1, $event)">{{::getText('first')}}</a></li>

and the class would look something like:

    .pagination-first: after {
         font-family: 'Glyphicons Halflings';
         content: '\fe079'; //glyphicon-chevron-left
    }

**Comment by wesleycho** [comment]
That is also a good idea - I was thinking about that too, it would make it more flexible to style.

**Comment by wesleycho** [comment]
I opened a PR with classes added to each of the `li` elements.
