### ISSUE TITLE
modal-dialog after size change event

### ISSUE THREAD

**Issue by f0def** [angular-ui/bootstrap#4134]
Hello
I show modal form by calling `$modal.open()` with `size = "sm"` or `size = "lg"`. 
Whether there is an event or workaround that will be triggered after the class `modal-sm` has been added to the modal-dialog?
I need to get the width of a `modal-dialog` to fit the size of the embedded component, but sometimes the width of the back before the class has been applied.
I create a [plnk](http://plnkr.co/edit/quAe8PSziGgh9a21rTYk?p=preview) described this issue
```
firstWidth = 568
secondWidth = 268
```
First attempt (before applied `modal-sm` class) sometimes return `568px`, second attempt using $timeout (after applied `modal-sm`) return `268px`.
I use angular 1.4.3, angular-bootstrap 0.13.2

**Comment by wesleycho** [comment]
Using $timeout is your best bet I believe - eventing would be a rabbit hole we do not want to go down, as then there might be feature requests to do so with a lot of other things to make the api symmetric, and use then becomes very clunky.
