### ISSUE TITLE
Template loading fails when http interceptors adds params to url

### ISSUE THREAD

**Issue by Serginho** [angular-ui/bootstrap#4135]
If I add time=2342342 param to prevent cache on IE11, angular-bootstrap doen't load any template.html. I don't know the way templates are implemented but all fails.

**Comment by pkozlowski-opensource** [comment]
@Serginho this project doesn't do anything special with template loading, so I would say it is a general support question about using interceptors that might interfere with template loading. As such it should be discussed elsewhere: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

If you still believe that this is a bug in this library, please report a bug with all the necessery context and steps to reproduce, see: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug
