### ISSUE TITLE
datepicked popup has inline styles

### ISSUE THREAD

**Issue by spooky** [angular-ui/bootstrap#4136]
The template for datepicker popup has a [hardcoded style attr](https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/popup.html#L3) (padding)

**Comment by wesleycho** [comment]
A short term workaround is to override the template and add a class - we will also be adding `datepicker-popup-template-url` support shortly for allowing to override this on an instance by instance basis.

This is obviously not ideal though, and we will want to move this out.

**Comment by wesleycho** [comment]
I am closing this, as overriding the template will be your best option here.
