### ISSUE TITLE
btn-radio directive is called after ng-click, displaying wrong value

### ISSUE THREAD

**Issue by shlomis** [angular-ui/bootstrap#414]
when using btn-radio directive it often required to use an ng-click directive to send data to the server.

Since ng-click is called first the data being sent does not reflect the ui

**Comment by kimardenmiller** [comment]
Not sure when ngChange was introduced into Angular, but pretty sure I've been using ui.bootstrap radio before it was there. Surprised more is not sited about this issue.  So ... this does not work:

```slim
label type='button' ng-click="setFilter('active')" class='btn btn-default' ng-model='sessionSettings.routeParams.filter' btn-radio="'active'" 

... but his does:

label type='button' ng-change="setFilter('active')" class='btn btn-default' ng-model='sessionSettings.routeParams.filter' btn-radio="'active'"

**Comment by bmallen1** [comment]
Here's a plnkr demonstrating that this issue still exists:

https://plnkr.co/edit/bJ6LSR7fAY9mlvqBzDUw?p=preview
