### ISSUE TITLE
Typeahead not working when using async loading method

### ISSUE THREAD

**Issue by usernamehoax** [angular-ui/bootstrap#4156]
Hi,

I tired using multiple approaches to make it work but it is impossible. I enter into my input the values which I have them in the database but no result dropdown is being shown. Here is the example code:

```javascript
$scope.getUserNames = function (input) {
  return $http.get(ApplicationConstants.apiUrl + 'api/Users/UserNames', {
    headers: { 'ContentType': 'application/json' },
    params: {
      input: input
    }
  }).then(function (response) {
    $log.debug('GetUserNames:', response.data);
    return response.data;
  }, function (error) {
    $log.debug(error);
  });
};
```

In markdown:
<input type="text" ng-model="userNameSelected" placeholder="Type the username" typeahead="username for username in getUserNames($viewValue)" class="form-control" />

The model is being updated and no results are being included. As you can see I tried using $log.debug and the response is returned properly each new input to the typeahead's input , it is the array of strings.

**Comment by usernamehoax** [comment]
Forgot to add , angularJS - 1.4.3 , ui-bootstrap - latest

**Comment by wesleycho** [comment]
Can you reproduce this on Plunker? This appears to work for me [here](http://plnkr.co/edit/ol8FE2RmHZL4Grvfq6e7?p=preview).

**Comment by usernamehoax** [comment]
I tried getting code from your Plunkr - getLocation and markdown and incorporating it to my code and it doesn't help. I cannot reproduce that easily my code since I'm using grunt/bower/requirejs setup and use various libraries. What I can tell you more is that I was using my typeahead inside and outside tabset directive and everithing resides inside ngView

**Comment by wesleycho** [comment]
Problem is, without a reproduction, we can only guess - we can't test out potential fixes either, which makes it difficult to determine whether it is a problem in the library or in the usage.

**Comment by usernamehoax** [comment]
Ok I'll try reproducing

**Comment by usernamehoax** [comment]
I managed to make it working - stripped out my application to bare bones and now it works , I guess some other library is causing the conflict - don't know yet which. I'll post when I'll find out

**Comment by wesleycho** [comment]
Good to hear - I suspected it was something specific to your setup. This also helps you debug exactly what's wrong by properly evaluating all possibilities :) .

**Comment by usernamehoax** [comment]
Ok, found the guilty party - angular-block-ui - when I enable it on the module list in my main app then the dropdown doesn't show. I understand this is unrelated to the issues regarding bootstrap-ui but I'll try to find the fix in the guilty library. Should we close this thread ?

**Comment by wesleycho** [comment]
Sure, looks like it's not an issue here - thanks for taking the time trying to get more information to see if we could help!

**Comment by usernamehoax** [comment]
Thanks for your time. Just for information if anyone else runs into this problem: you can configure blockUI to autoBlock=false - it won't block all $http service requests only those which are defined explicitly. I posted an issue on the blockUI's github page also.

**Comment by kira510** [comment]
Hello,
I am not using block-ui but still I face this issue. The drop down doesn't load the first time but it works fine after ng-change in my input is triggered. Please get back to me soon. Don't know why I face this issue
