### ISSUE TITLE
Support for systemjs

### ISSUE THREAD

**Issue by richburdon** [angular-ui/bootstrap#4158]
Does angular-ui support loading via systemjs?
Also, if bootstrap is a dependency (for the CSS file) then how can systemjs (or bower for that matter) include bootstrap without bringing in the jquery dependency?

**Comment by wesleycho** [comment]
We do support `npm`, so you can use System.js via jspm - that said, you won't get any particular benefit of doing so currently, as UI Bootstrap is not currently written in TS/ES6.

**Comment by wesleycho** [comment]
As far as Bootstrap CSS goes, you could choose to not compile it in if you use jspm. You could also just use npm as well.

**Comment by wesleycho** [comment]
Closing, as I believe this is already currently supported as an option. Feel free to post questions in more traditional help venues as listed in https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem .
