### ISSUE TITLE
Does Modal support using this instead of $scope

### ISSUE THREAD

**Issue by justechn** [angular-ui/bootstrap#4159]
I was playing around with the modal and tried using this instead of $scope, but it broke the items list and the ok and cancel buttons. Am I doing something wrong, or is this not supported?

http://plnkr.co/edit/wnDk17aEMkYJrTsh4BpB?p=preview

In the console I am seeting errors about 
 Unknown provider: $modalInstanceProvider

**Comment by wesleycho** [comment]
You actually want to pass the controller information via the options object passed into the `$modal` service - [here](http://plnkr.co/edit/pPyBmyW8eIldmZy2GB3u?p=preview) is a working example of your Plunker.
