### ISSUE TITLE
Datepicker: Highlight multiple days

### ISSUE THREAD

**Issue by waqas-syed** [angular-ui/bootstrap#4169]
I want to be able to highlight a number of days in a month when the calendar gets rendered on screen. This will probably require that the highlighted days have a different color (e.g., green) and the selected day has another color (e.g., blue).

Is this possible? I will be glad if i can even get some guidelines on tweaking it up myself to get this desired functionality.

**Comment by wesleycho** [comment]
Currently, you can use a custom template on an instance by instance basis - I am not sure that is enough to get to where you want though.

**Comment by waqas-syed** [comment]
I have used the custom-class attribute to render the color on specific dates!
