### ISSUE TITLE
Alerts: support for fade

### ISSUE THREAD

**Issue by hlship** [angular-ui/bootstrap#417]
I would to have my alert fade out when clicked, rather than just be removed immediately from the DOM.  Ideally, I need a notification after the alert is invisible so that I can choose to remove it then (or at least, remove the directive containing the alert).

Right now, I'm kludging something together using a <div> with class "fade in", and I remove the "in" when closing. I then guess how long until it is invisible before removing from the DOM.

**Comment by msgilligan** [comment]
Has this been implemented? Should this issue be re-opened or is there some other place to track this feature?

**Comment by deeg** [comment]
I think this would be a good feature, which does not look like its been implemented yet.

@wesleycho, was there a decision not to add this feature in? I can look into opening a PR for this in the next few days.

**Comment by icfantv** [comment]
@deeg, I did a [really quick and dirty plunker](http://plnkr.co/edit/3AhRgUS1EUFA4Sbi8jPX) to demo how we might do this.  Fading in is easy, you just add the `in` class to the element with the `fade` class.  Fading out stinks and basically involves incrementally decreasing the element's `opacity` until it's effectively invisible before removing it from the scope.

**Comment by icfantv** [comment]
[Here's a MUCH better plunker](http://plnkr.co/edit/vrf5ka3Pbzr4hR4FFFFg) using the `$animateCss` service.

**Comment by msgilligan** [comment]
I'm going to move ahead with integrating alerts and migrating to latest release (1.0.3) and once that's done, I'll take look at the above suggestions. Thanks!

**Comment by msgilligan** [comment]
Should this issue be re-opened or should I create a new issue?
