### ISSUE TITLE
datepicker-popup does not heed min-date when manually inputting date (0.13.3)

### ISSUE THREAD

**Issue by hoxu** [angular-ui/bootstrap#4170]
When `min-date` is set, the user can still manually input a date before `min-date`, and it gets succesfully bound to the model. I would expect that the model would not get bound when a date outside the allowed range is inputted manually, and the field would be set `$invalid`.

See [plunker demonstration](http://plnkr.co/edit/IzN5tI3pRJvxCDoTFkjP?p=preview).

**Comment by wesleycho** [comment]
I believe this was always an issue - the datepicker does not clear the model like the timepicker.

The validation should definitely occur though, so that is a missing functionality.

**Comment by wesleycho** [comment]
This appears to be a usage issue: http://plnkr.co/edit/U60gYOY0jRHQHAQZbp3Z?p=preview - one should not be able to manually input a prior date to the min date.

The documentation needs updating to be clearer, but this is planned for the 1.0 release.
