### ISSUE TITLE
openedClass not removed when close/dismiss (0.13.3)

### ISSUE THREAD

**Issue by povilass** [angular-ui/bootstrap#4171]
Adding your own class to openedClass after close/dismiss will not be removed. (angular-ui-bootstrap Version: 0.13.3 - 2015-08-09)

![class-passed](https://cloud.githubusercontent.com/assets/8037810/9167474/6612a66c-3f5d-11e5-93cf-6e5609e700fe.png)
![error](https://cloud.githubusercontent.com/assets/8037810/9167475/66199238-3f5d-11e5-8944-f174d7d87b66.png)

**Comment by wesleycho** [comment]
Good catch - that is completely overlooked, and I should have written a test case for this.

**Comment by povilass** [comment]
Stuff happens. :dancers:

**Comment by wesleycho** [comment]
I just opened a fix for this issue in the referenced PR above, should land sometime today.

**Comment by povilass** [comment]
Thanks.

**Comment by povilass** [comment]
I have problem, one case like you have 2 opened pop-ups and i got 2 body classes "class="modal-scrollable modal-open"" when I close pop-up with modal-open class, class is not toggled body.toggleClass(modalWindow.openedClass || OPENED_MODAL_CLASS, openedWindows.length() > 0).

**Comment by wesleycho** [comment]
Hmm, that will be a very tricky situation to fix...really feel that the library should have never supported multiple modals.

That part may require some more thought.

**Comment by wesleycho** [comment]
Actually, can you open a new issue on that?
