### ISSUE TITLE
UK Date Format Issue on Model Change

### ISSUE THREAD

**Issue by ChrisMurphy** [angular-ui/bootstrap#4173]
AngularJS: 1.3.2
UI BootStrap: 0.13.3
Use Case: [Code Pen Example] (http://codepen.io/anon/pen/KpEyLZ)

When manually setting the value of a model that is attached to a datepicker that has 'dd/MM/yyyy' specified as the date format, then the calendar is subsequently opened, the interpreted date is the inverse of what it should be (i.e. set the model value to 11th of August, the calendar displays the date as the 8th of November).

In the use case, if the cdn version of angular ui bootstrap is changed to version 0.12.1 then the issue does not materialise.

**Comment by wesleycho** [comment]
[Ported to Plunker](http://plnkr.co/edit/mbMMrSJR6Y4WPr3LUddt?p=preview) for ease of debugging.

Certainly looks like a bug.

**Comment by k0nG** [comment]
Experiencing this issue as well with UI BootStrap: 0.13.3.

Setting `datepicker-popup="dd/MM/yyyy` with a valid JS Date object as the `ng-model` seems to cause it.

**Comment by k0nG** [comment]
On further investigation I've managed to partially fix it by changing the `render` function within the Date Picker: https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L94

The issue is the function parses a date without specifying a format using native JS `Date` which when given a UK format assumes it's an American format. I've fixed this by using the DateParse service to parse the date to a given format. Unfortunately I've not found a way of passing the format in so I've had to hard code it in this example.

```javascript
this.render = function() {
    if ( ngModelCtrl.$viewValue ) {
      var date = dateParser.parse(ngModelCtrl.$viewValue, 'dd/MM/yyyy'),
          isValid = !isNaN(date);

      if ( isValid ) {
        this.activeDate = date;
      } else if ( !$datepickerSuppressError ) {
        $log.error('Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.');
      }
    }
    this.refreshView();
  };
```

I've tried adding a failing test to datepicker.spec.js but I can't get it to fail:

```
describe('initially opened with specified format', function () {
          var wrapElement;

          beforeEach(inject(function(_$document_, _$sniffer_, _$timeout_) {
            $document = _$document_;
            $sniffer = _$sniffer_;
            $timeout = _$timeout_;
            $rootScope.isopen = true;
            $rootScope.date = new Date("2015-08-10T00:00:00");
            wrapElement = $compile('<div><input type="text" ng-model="date" datepicker-popup="dd/MM/yyyy" date-input-format="dd/MM/yyyy" is-open="isopen"><div>')($rootScope);
            $rootScope.$digest();
            assignElements(wrapElement);
          }));

          it('has `selected` only the correct day', function() {
            expect(getTitle()).toBe('August 2015');
          });
        });
```

Can anyone help me? I'd love to complete a fix and PR in.

**Comment by wesleycho** [comment]
The fix is going to be a little tricky - there are two situations one has to consider here. The first is where the format is set in the popup, and the other is for the plain datepicker.

**Comment by wesleycho** [comment]
Discovered that this issue is because the date is being set to a string and not a date object - it actually works properly when set to a date, like in [this Plunker](http://plnkr.co/edit/mbMMrSJR6Y4WPr3LUddt?p=preview).
