### ISSUE TITLE
Disabled UTCtimezone in timepicker

### ISSUE THREAD

**Issue by harsh5400** [angular-ui/bootstrap#4177]
Can I disabled ISO 8601 format ans pass the value to model as well database server as it is. 

For example : 
Present : I am selecting 5:30, but in the database it is saving 12:00 due to ISO standard. 

Requirement : If I will select 5:30 it should save as it is in the database ie 5:30

Please help..

**Comment by wesleycho** [comment]
You would have to do some manual conversion when sending the value to the server to make sure the correct time is sent currently.

There are multiple tickets open regarding timezones, so any request for offsetting will be tracked through those.

**Comment by harsh5400** [comment]
Actually I m making an angular dynamic form framework. It will automatically read the form fields from database and draw form at run time. 

Right now I converted the time to local time zone in the bootstrap.js directly

But if we make the setting of disable timezone, it will be great.

Do you have any example. Please send link if possible.

**Comment by wesleycho** [comment]
That functionality is not currently in the framework - if the request is for disabling timezone, then that request is already encoded in another issue that we are tracking.

Otherwise, manual work cannot be avoided at this time currently.

**Comment by harsh5400** [comment]
Ok we are waiting for this functionality 

Thanks and regards 
Harsh
