### ISSUE TITLE
Wrong tooltip size with html content

### ISSUE THREAD

**Issue by Izhaki** [angular-ui/bootstrap#4186]
From the demo:

![image](https://cloud.githubusercontent.com/assets/880132/9201254/ea0f317e-4043-11e5-82b8-12b6db698905.png)

The tooltip size is smaller than the string provided.

**Comment by pkozlowski-opensource** [comment]
AFAIK this size limitation comes from Bootstrap CSS. @Izhaki did you check this?
IMO this has nothing to do with the lib here....

**Comment by icfantv** [comment]
@Izhaki and @pkozlowski-opensource - This limitation is set by Bootstrap CSS and you can easily override it in your Bootstrap Theme file or in your site's CSS file:
```
.tooltip-inner {
  max-width: 200px;
  padding: 3px 8px;
  color: #fff;
  text-align: center;
  background-color: #000;
  border-radius: 4px;
}
```
Just a note that popover also has a max-width.
