### ISSUE TITLE
Allow tab content to be in a different part of the DOM

### ISSUE THREAD

**Issue by richburdon** [angular-ui/bootstrap#4187]
The current implementation requires tabs to be inline within the tabset. The jquery implementation is much less restrictive, allowing the tab-content to be placed anywhere within the DOM.

In general, is there any way to extend the behavior of the angular bootstrap directives rather than rewriting them when there's a similar restriction?

**Comment by icfantv** [comment]
@richburdon - If I understand your question correctly, there's no restriction on where the content (template) for your tabs is defined.  I've defined them in completely separate files and done something like this:
```
<data-tabset class="tabset" data-justified="true">
  <data-tab data-ng-repeat="tab in tabs"
             data-active="tab.active">
    <data-tab-heading>
      {{ ::tab.heading }}
    </data-tab-heading>
    <div data-ng-include="tab.template"></div>
  </data-tab>
</data-tabset>
```

**Comment by wesleycho** [comment]
I think he means that he would like the tab content to be completely decoupled from the directive.

I do not believe we will support this, as it would require stateful knowledge of where it is in the DOM, and the best way to do so is with a parent element, hence the existence of `tabset`.

**Comment by icfantv** [comment]
That makes sense.  @richburdon don't forget that jQuery, and thus jQuery UI, is a DOM manipulation framework.  Most of what jQuery does is via selectors.  Whereas with Angular, the items are right there (directives or otherwise).

**Comment by icfantv** [comment]
@richburdon, do you require further assistance here?  If not, I'm going to close this.  Thanks.

**Comment by wesleycho** [comment]
Closing as won't support as per discussion.
