### ISSUE TITLE
Datepicker after init have $error state on form.

### ISSUE THREAD

**Issue by khusnetdinov** [angular-ui/bootstrap#4191]
At the loading view My datepicker have error in Form, instead the model have right format date string. After I change date error is gone. As I can see the problem with initialization of date picker, I spend a lot of time but can't see problem.

What is wrong?

I have markup:

<div class="form-group grid-flex__column--2">
    <label class="form-group__label">Start date</label>
    <input type="text"
         class="input-icon--date-picker"
           id="encounterStartDate"
           name="encounterStartDate"
           ng-model="ctrl.model.startDate"
           datepicker-popup
           is-open="startDate"
           ng-click="startDate = !startDate"
           ng-change="ctrl.updateStartDate()" // Just copy date to another object
           ng-disabled="!ctrl.model.isEditable"/>
</div>

To ctrl I pass model with dates. In $scope I have $error on alod and init:
$error: Object
date: Array[1]
0: Object
$$debounceViewValueCommit: (t)
$$lastCommittedViewValue: "8/8/2003"
$$parseAndValidate: ()
$$parserName: "date"
$$rawModelValue: "2003-08-08T00:00:00"
$$runValidators: (e,t,r)
$$setOptions: (e)
$$success: Object
$$writeModelToScope: ()
$asyncValidators: Object
$commitViewValue: ()
$dirty: false
$error: Object
$formatters: Array[1]
$invalid: true
$isEmpty: (e)
$modelValue: "2003-08-08T00:00:00"
$name: "encounterStartDate"
$options: null
$parsers: Array[1]
$pending: undefined
$pristine: true
$render: ()
$rollbackViewValue: ()
$setDirty: ()
$setPristine: ()
$setTouched: ()
$setUntouched: ()
$setValidity: t(e,t,l)
$setViewValue: (e,t)
$touched: true
$untouched: false
$valid: false
$validate: ()
$validators: Object
$viewChangeListeners: Array[2]
$viewValue: "8/8/2003"
__proto__: Qa
length: 1
__proto__: Array[0]

**Comment by aarosil** [comment]
@khusnetdinov what resolution did you find, I see this happening for me with 0.13.3 but with 0.13.1 it doesn't happen.
