### ISSUE TITLE
Cant use ng-class on accordion group since 1.33.3

### ISSUE THREAD

**Issue by blowsie** [angular-ui/bootstrap#4193]
You can no longer use `ng-class` on an accordion group since this commit.
https://github.com/angular-ui/bootstrap/commit/ead15e37
---
https://github.com/angular-ui/bootstrap/pull/4152
https://github.com/angular-ui/bootstrap/issues/3419

**Comment by blowsie** [comment]
Saldy, I'm closing this due to the responses on here 
https://github.com/angular-ui/bootstrap/issues/4172 

---

Sadface.

**Comment by icfantv** [comment]
Don't be sad.  We're actually looking out for you and your app's best interests here.  Did you read the comments in [this link](https://github.com/angular/angular.js/issues/5695)?  Merging classes can yield very unpredictable behavior - this is one of the reasons `replace: true` can be so evil.

**Comment by LeleDev** [comment]
Temporary workaround:

Put your ng-classes in your plain "class" attribute:

Before:
```
ng-class="{'expanded': status.open}"
```

After:
```
class="{{status.open ? 'expanded':' '}}"
```

**Comment by icfantv** [comment]
@leledev, this is not a workaround, temporary or otherwise.  CSS classes are not applied in the order they appear in your DOM element's class attribute, but rather, where they are defined in your CSS file(s), and thus, the order in which they are loaded.

**Comment by LeleDev** [comment]
@icfantv 
Sorry, I wanted to post the 'workaround' in / for this issue: https://github.com/angular-ui/bootstrap/issues/4172 , but I pasted it here by mistake

**Comment by LeleDev** [comment]
It's a workaround for who wants to make things works without using ng-class, and it should work in most of the cases
