### ISSUE TITLE
Rating and typeahead behave differently in different environment

### ISSUE THREAD

**Issue by Vaelyr** [angular-ui/bootstrap#4196]
When using Rating or Typeahead directives locally they both work fine.

1) I use Rating with readonly mode in one of my detail page, however when I deploy my application to a server (Amazon), the readonly feature for some reason doesn't work as it supposed to, I am still able to mouseover the stars and click them (without changing the model value though).

2) Typeahead does not work at all when being deployed, locally it works, but spams the unsafe html bind warning to console, maybe that breaks it?

Any thoughts what is happening?

**Comment by icfantv** [comment]
@Vaelyr can you please try recreating this in a plunker?  Should be sufficient since it's also a remote server.

**Comment by Vaelyr** [comment]
Found here that just readonly attribute may not function properly in all cases. Have to use data-readonly. Typeahead was my issue with json data not being loaded.
