### ISSUE TITLE
Customization of the carousel

### ISSUE THREAD

**Issue by nirus** [angular-ui/bootstrap#4201]
Cannot access $scope.slides object inside carousel controller to customize the carousel template. The answer in the stackoverflow explains the scenario and possible work around. 
Link: http://stackoverflow.com/a/31989387/1848109

> Keep up the good work. Your library is awesome.

**Comment by wesleycho** [comment]
It actually is exposed, via `controllerAs` - couldn't you use `carousel.slides` in the template, or does that not work?

**Comment by wesleycho** [comment]
A Plunker would also be very helpful - a demonstration of the failure to access [here](http://plnkr.co/edit/JEHq0Y0IjYljXwHoqIvP?p=preview) would be a good starting point.

**Comment by nirus** [comment]
Issue : http://plnkr.co/edit/qwkJ84m6SB6slDxpe88s?p=preview 

Workarround: http://plnkr.co/edit/npMsqiGwM3eBrvAdB2oU?p=preview

For explanation please take a look at the stackoverflow question : http://stackoverflow.com/questions/31981553/how-to-use-controller-scope-in-directive-template/31989387#31989387

**Comment by wesleycho** [comment]
I think I see now - the slides array is an array of the slide element $scope in the carousel controller.

Would allowing an optional binding to the slide directive accomplish what you want then?

**Comment by nirus** [comment]
Yes. Correct.This would allow the customization of the <li> elements as illustrated in the plunkr and also loop animation on the <li> tags when the slides changes.

**Comment by wesleycho** [comment]
Alright, I'll have it implemented in the next couple of days.
