### ISSUE TITLE
Typeahead does not allow blur on select

### ISSUE THREAD

**Issue by ZMan9854** [angular-ui/bootstrap#4206]
I'm trying to configure my UI so that if a typeahead suggestion is selected, the UI automatically focuses the next field in the form. The behavior I'm seeing is that the next field is focused correctly, but then the typeahead field takes the focus back. It looks like the code that is causing this is:

    $timeout(function() { element[0].focus(); }, 0, false);

It seems like this behavior should be optional. Thanks!

**Comment by wesleycho** [comment]
Just to verify, you don't want it to focus on the `input` element after blur with `typeahead-select-on-blur="true"`? The Plunker [here](http://plnkr.co/edit/6eTFVKMljx2Ms7iBsd5T?p=preview) displays this behavior currently.

**Comment by ZMan9854** [comment]
I think my issue is not that the field is refocused on select, but that the refocus happens after the `onSelectCallback()` callback is called, so the refocus can't be prevented.

Maybe the `onSelectCallback()` callback could be called inside the $timeout callback just after the call to `element[0].focus()`?

**Comment by wesleycho** [comment]
In reality, it sounds like you want a way to cancel the focus - let me think on this a bit, not sure what the best way to approach this would be.

**Comment by chriso86** [comment]
Hi guys,

Was this ever resolved? I'm losing a part of my soul trying to get this to work.
