### ISSUE TITLE
Popover and tooltips inside a modal still has broken positioning.

### ISSUE THREAD

**Issue by amcpanaligan** [angular-ui/bootstrap#4209]
I've been using 0.13.3 version of all this time.

**Comment by wesleycho** [comment]
Can you give a simple reproduction?

**Comment by amcpanaligan** [comment]
Hi, just figured I was using an image with image maps with a mouseenter trigger for a popover for every maps. Sorry for that. I think it was just natural for the positioning to broken as it doesn't treat my map an element (?)

**Comment by wesleycho** [comment]
Please give a reproduction - guessing at what is wrong is not productive, or something we can work with.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have reproduce scenario.
