### ISSUE TITLE
missing weeks 'ww' in the dateParser

### ISSUE THREAD

**Issue by marcelboelen** [angular-ui/bootstrap#4213]
When using weeks in the datepicker format there will be no change in the angular ngModel. (undefined). I debugged the code and found out that the dateParser can't parse a week 'ww'.

Currently i added my own week parser to the dateParser using the following

OLD
<pre>
<code>
    'ww': {
      regex: '\\d{2}',
      apply: function(week) {
        // http://stackoverflow.com/a/16591175/1668675
        var year = (new Date()).getFullYear();
        if (typeof this.year !== 'undefined') {
          year = this.year;
        }
        var simple = new Date(year, 0, 1 + (week - 1) * 7);
        var dow = simple.getDay();
        var ISOweekStart = simple;
        if (dow <= 4) {
          ISOweekStart.setDate(simple.getDate() - simple.getDay() + 1);
        } else {
          ISOweekStart.setDate(simple.getDate() + 8 - simple.getDay());
        }
        this.date = ISOweekStart.getMilliseconds();
      }
    }
</code>
</pre>

NEWEST
- updated Regex to the regex @wesleycho suggested
- updated date value setters
<pre>
<code>
    'ww': {
      regex: '[0-4][0-9]|5[0-3]',
      apply: function(week) {
        // http://stackoverflow.com/a/16591175/1668675
        var year = (new Date()).getFullYear();
        if (typeof this.year !== 'undefined') {
          year = this.year;
        }
        var simple = new Date(year, 0, 1 + (week - 1) * 7);
        var dayOfWeek= simple.getDay();
        var ISOweekStart = simple;
        if (dayOfWeek<= 4) {
          ISOweekStart.setDate(simple.getDate() - simple.getDay() + 1);
        } else {
          ISOweekStart.setDate(simple.getDate() + 8 - simple.getDay());
        }
        // Set the values individually based on the current week date
        this.year = ISOweekStart.getFullYear();
        this.month = ISOweekStart.getMonth();
        this.date = ISOweekStart.getDate();
        this.hours = ISOweekStart.getHours();
        this.minutes = ISOweekStart.getMinutes();
        this.seconds = ISOweekStart.getSeconds();
        this.milliseconds = ISOweekStart.getMilliseconds();
      }
    }
</code>
</pre>

I used an solution already available on stackoverflow
http://stackoverflow.com/a/16591175/1668675
http://stackoverflow.com/questions/16590500/javascript-calculate-date-from-week-number

**Comment by wesleycho** [comment]
That regex is not a good idea - it is too broad.

If you want to add support, you want `'[0-4][0-9]|5[0-3]'` as your regex string.

I took a look at this feature just now for the `w` and `ww` flags, and this might take some work to implement.

**Comment by marcelboelen** [comment]
I totally agree with the <code>'[0-4][0-9]|5[0-3]'</code> as a better regex. The code above was just a quick fix for me. 

It definitely requires some work to implement. The problem with the <code>ww</code> and <code>w</code> flag is that it's hard to use in combination with the other flags.

I'm looking forward to this feature.

**Comment by wesleycho** [comment]
I am going to close this issue in favor of #3418 in order to decrease the issue clutter.
