### ISSUE TITLE
From where i can download custom ui-bootstrap-0.12.0?

### ISSUE THREAD

**Issue by arjundas** [angular-ui/bootstrap#4216]
I am using Angular v1.2.23, for that i want ui-bootstrap v0.12.0
but i dont want full bootstrap plugins, i want specific modules only.
I didn't found any link for that, please help me.

**Comment by wesleycho** [comment]
The tags on this repository will let you handselect what code you want to use: https://github.com/angular-ui/bootstrap/tree/0.12.0 .

In the future, this is a question better suited for StackOverflow or IRC.
