### ISSUE TITLE
Bookmark pages - Pagination

### ISSUE THREAD

**Issue by bighoax** [angular-ui/bootstrap#4219]
Is it possible to bookmark pages? For example if you are on page 10, and you want your user to bookmark and be back to page 10.

Can the page links include get param page or something, is that possible now? How would one go about doing that?

**Comment by wesleycho** [comment]
You could cache the last visited page the user is on before leaving the view (through usage of a service to store it either in memory, locally via localStorage/IndexedDB/WebSQL, or persist it to a backend), and load it again in the controller on page load.

**Comment by bighoax** [comment]
Hi @wesleycho,

I can probably do that but that doesn't answer the question, what if a person is browsing trough a catalog of items, and is interested in 2 items from page 6 and item from page 11, in that case user would  get only stuff from page 11.

Can I do something with the pagination itself, to alter the links, i.e appending get param onto url or something.

Thanks

**Comment by wesleycho** [comment]
In that case, the responsibility would be on the developer to manage the model & the selected items - the pagination component simply is a component for keeping track of a page number model. with a nice UI for navigating around it, but doesn't trigger the actual navigation.

**Comment by wesleycho** [comment]
Closing as support ticket - this is not something that is an issue with the library.

**Comment by bighoax** [comment]
:+1:
