### ISSUE TITLE
carouselCtrl.addSlide is not a function when using ui.router

### ISSUE THREAD

**Issue by deryl27** [angular-ui/bootstrap#4223]
I am using ui.bootstrap.carousel with ui.router having nested views. 

Error : carouselCtrl.addSlide is not a function

**Comment by wesleycho** [comment]
Can you reproduce this on [Plunker](http://plnkr.co/)? This is not enough to go by.

**Comment by Blackbaud-BobbyEarl** [comment]
@deryl27 Are you using "CarouselController as carouselCtrl"?  Using the same controller name as ui.bootstrap causes problems.  I was seeing the exact same error, switched the name of my controller, and the problem went away.

**Comment by wesleycho** [comment]
Should be noted that we are in the process of implementing namespaces for each controller using `uibFoo` for controller names, which should eliminate this problem by the time we hit 1.0 - this is being tracked by #4373.

If this is not the issue, what is posted here is not enough information to go by - closing under the assumption that the former is the case, feel free to post a reproduction via Plunker if it is not the case and there is more information to allow us to assist.

**Comment by TowerC** [comment]
@Blackbaud-BobbyEarl Thank you! Problem solved!
