### ISSUE TITLE
Invoke a function when popover is clicked ?

### ISSUE THREAD

**Issue by ramprakash-ravi** [angular-ui/bootstrap#4224]
```
<div class="caption caption-md">
    <i class="icon-bar-chart theme-font hide"></i>
    <div class="caption-subject bold" popover-template="dynamicPopover.template" popover-trigger="click" popover-placement="bottom" popover-title= "{{dynamicPopover.title}}" ng-click="openMachineDetailsPopover(device.deviceId,device.deviceName)">
           {{device.deviceName}}
     </div>
</div>
```

In the above code i'm trying to invoke a functtion in my angular controller js file, but i'm using ng-click.

The logic works fine, but the problem is :
1. I'm not able to close already opened popover when new popover is opened.
2. ng-click works only on second click.

**Comment by icfantv** [comment]
@ramprakash-ravi questions like this are best for Stackoverflow.  Please see [this link](https://github.com/angular-ui/bootstrap#need-help) for how to get support.

That said, see if the solution for #4007 will work for you.
