### ISSUE TITLE
Datepicker popup doesn't allow all date formats

### ISSUE THREAD

**Issue by mattlewis92** [angular-ui/bootstrap#4229]
This broke between 0.13.1 and 0.13.2, the docs say all dates are formatted using the date filter, however `medium` doesn't seem to be a valid format anymore and silently breaks the datepicker popup which wipes the ng-model value.

Example plunkr:
http://plnkr.co/edit/aOGQ1BY4SJBeuwP9MRzp?p=preview

If you try and change the date then you'll see the model value gets wiped.

**Comment by wesleycho** [comment]
Closing as a duplicate ticket - there are several tickets relating to this issue.
