### ISSUE TITLE
Rewriting in TypeScript/ES6

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#4235]
We need to investigate which option makes sense to support for the project - the ecosystem is moving towards TypeScript, so that is a strong contender, but ES6 via Babel is another option, and one that has simpler build tooling.

I'm open to either option.

This needs to

- [ ] Provide abstract accordion classes
- [ ] Provide abstract alert class
- [ ] Provide abstract button checkbox class
- [ ] Provide abstract button radio class
- [ ] Provide abstract carousel & slide classes
- [ ] Provide abstract collapse class
- [ ] Provide abstract datepicker classes
- [ ] Provide abstract dropdown class
- [ ] Provide abstract pagination class
- [ ] Provide abstract progressbar classes
- [ ] Provide abstract rating classes
- [ ] Provide abstract tab classes
- [ ] Provide abstract timepicker class
- [ ] Provide abstract typeahead classes
- [ ] Build to pure ES6 consumable script
- [ ] Build to UMD ES5 consumable script

This is to give the greatest flexibility to users consuming the library on release, as well as allowing them to implement the components in more flexible ways. This also paves the way for Bootstrap 4 support due to logic being abstracted.

This work needs to start soon I believe, since Angular 2 also looms on the horizon, so interop with Angular 2 needs to be investigated.

**Comment by icfantv** [comment]
I don't have a strong opinion either way either.  If core angular is moving forward using TS, does it make sense to do that as well?

**Comment by pkozlowski-opensource** [comment]
Yeh, I'm not sure rewriting buys us much here... While I'm really excited about TypeScript the whole tooling is still a moving target which makes it kind of pain in a neck for daily, practical workflow. Also changes needed for ng2 are so substantial that TS itself is not a big deal.

BTW, I would love to chat with you guys about ng2 support one day, maybe we should organize a hangout or something?

**Comment by wesleycho** [comment]
Hm, would be interesting to gather thoughts - I would be down for a hangout sometime.

I'd be happy not doing a rewrite too if it's not worthwhile to do - that's a lot of work.

**Comment by RobJacobs** [comment]
Id love to be part of that discussion, keep us posted, thanks.

**Comment by Foxandxss** [comment]
I like both opinions. Rewrite is cool because you can use more modern solutions, it allows us to clean the codebase a bit...

But this is also a pretty big library so it is a daunting task (not that I mind really tbh).

I would like that hangout for sure, we are starting to brainstorm ideas but we have our own ideas in mind.

**Comment by wesleycho** [comment]
Changed to Backlog for now until we decide on whether this is worthwhile.

Someone want to start an email chain for organizing a hangout? My email is in my profile

**Comment by eduardoinnorway** [comment]
I would go for TypeScript for the simple reason of Angular 2.0, what ever you choose, looking forward to that release with Bootstrap 4 I imagine :)

**Comment by pkozlowski-opensource** [comment]
@eduardoinnorway "Angular 2.0" reason kind of makes sense if we migrate this project to use ng2. Just rewriting in TS and staying in ng1 is a nice (but time-consuming!) exercise but doesn't buy us anything....

Just my $0.03....

**Comment by eduardoinnorway** [comment]
Totally agree on that, it would have to be on the ng2 version. If you need more people for that one, just ping me.

**Comment by Foxandxss** [comment]
Let's close that and reopen if for some reason we find that we have time for this.
