### ISSUE TITLE
Grid is not rendered in tabs under collapsible divs that is not visible on initial page load.

### ISSUE THREAD

**Issue by yjw9012** [angular-ui/bootstrap#4237]
I placed a grid in tabs under divs with collapse. On initial page load, those divs are collapsed by default so you can't see tabs and grid unless you manually click on collapsible divs to expand them. The problem is that when I click on the collapsible divs and expand them, I can see tabs but grid. Grid seems to have zero height. If I do not collapse the collapsible divs by default, on initial page load, grid is rendered properly.

I found this article talking about the problem I am facing: http://ui-grid.info/docs/#/tutorial/108_hidden_grids

I tried the first two solutions in the webpage: 1) setting width and height of grid and 2) using ng-if
but neither worked. Any idea how to solve this or workaround?

**Comment by wesleycho** [comment]
This appears to be a question more appropriate for StackOverflow or IRC: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem .

Closing, as this is not likely a bug in this library.

**Comment by ProLoser** [comment]
or slack
