### ISSUE TITLE
if dropdown has typeahead directive, typeahead-template-url is working wrong.

### ISSUE THREAD

**Issue by kim-jeongki** [angular-ui/bootstrap#4239]
I was found that if dropdown directive has typeahead directive, typeahead-template-url is working wrong.
so demo is here
http://plnkr.co/edit/8dvPHYP98YHulObIxdXd?p=preview

I was digging it. The problem is that typeahead popup template has ui.dropdown-menu element and dropDownMenu directive applied template-url instead of typeaheadMatch directive.

To solve the problem is, default 'template/typeahead/typeahead-popup.html' has wrapping dummy div 
and I hope to support typeahead-popup-template-url like datepickerPopupConfig constants

here is PR
https://github.com/angular-ui/bootstrap/pull/4238

**Comment by wesleycho** [comment]
This should no longer be an issue in 1.0 with the non-prefixed directives removed.
