### ISSUE TITLE
[DatePicker] Unable to handle lower case month names

### ISSUE THREAD

**Issue by jeffyates123** [angular-ui/bootstrap#4241]
Hi,

I've been trying for over a day to get the date picker to work and it's just not happening.

If I type in a date say "01-aug-2015" in a date picker field, the parser does not recognise this as a valid date. The regex is case sensitive it would seem on investigation of the code in version 0.13.3. So it doesn't recognise "aug" as being "Aug".

It's very frustrating! Any fixed, workaround or anything else for this. I notice even on the demo page when you type in a date without the upper case first character it also appears to find this invalid. Perhaps it's something straight forward?

Please help!

**Comment by wesleycho** [comment]
This uses the formats in `SHORTMONTH`, as found [here](https://github.com/angular/angular.js/blob/master/src/ngLocale/angular-locale_en-us.js#L69-L82) in Angular.

**Comment by wesleycho** [comment]
I do not believe this is a bug, as this mirrors the behavior in Angular itself, and I am not sure this is something worth changing.

Note that the `dateParser` service can be overridden by the user to support any desired formatting rules, so one can override this on an app level basis.

**Comment by henne001** [comment]
+1

I am having the same issue, but in uppercase manual input format: 23NOV15. Date input is not validated.

It is strange that this is not configurable through the date-format="ddMMMyy". It's not that it's a 'bug', but rather a missing feature imho. Angular is too restrictive not supporting uppercase/lowercase date formats.

If overriding the dateParser does the trick, any suggestion on how to approach this?

**Comment by brettjacobson** [comment]
:+1: 

@wesleycho I do not think this should have been closed.  This seems like a valid use case.  People when typing into a datepicker are NOT going to type in proper capitalization the way the Angular developers typed in the Month short names (with a capital first letter and lower rest).  They're GOING to type in all lowercase (or uppercase if their caps lock is on).

The problem does *NOT* lie in Angular itself; the *problem* is the simple way in which dateParser builds its regex text for short month names (and also full names, too).  It simply takes the names from and joins them with pipes `$locale.DATETIME_FORMATS.MONTH.join('|')`.  What it *SHOULD* do is act on each of those month texts and "massage" them into supporting case insensitivity.

I hacked in some extremely ugly code, just to prove it is possible:
in the formatCodeToRegex section for 'MMM' i made it call my function to massage the month names:
`regex: makeArrayTextCaseInsensitiveForRegex($locale.DATETIME_FORMATS.SHORTMONTH).join('|'),`
then here is that function 
```javascript
function makeArrayTextCaseInsensitiveForRegex(textArray) {
	var letters,
		letter,
		newArray = [];

	textArray.forEach(function (textArrayItem) {
		letters = '';
		for (var i = 0; i < textArrayItem.length; i++) {
			letter = textArrayItem.charAt(i);
			letters += '[' + letter.toLocaleUpperCase() + letter.toLocaleLowerCase() + ']';
		}
		newArray.push(letters);
	});

	return newArray;
}
```

**Comment by mebibou** [comment]
For those who have the same problem, I managed to override the parser of `uibDateParser` to handle non-case sensitive month matching:
````
angular.module('app').run(['uibDateParser', function(uibDateParser) {
  var format = 'dd-MMM-yyyy';
  // Triggers creation of the parser
  uibDateParser.parse('01-Jan-2000', format);

  // Override parser
  var parser = uibDateParser.parsers[format],
      regex = '(' + [
        parser.map[0].matcher,
        parser.map[1].matcher + '|' + parser.map[1].matcher.toLowerCase(),
        parser.map[2].matcher
      ].join(')-(') + ')',
      apply = parser.map[1].apply;

  parser.map[1].apply = function(value) {
    value = value[0].toUpperCase() + value.substring(1);
    apply.call(this, value);
  };
  parser.regex = new RegExp('^' + regex + '$');
}]);
````
