### ISSUE TITLE
how to disable previous dates in UI- datepicker[Question]???

### ISSUE THREAD

**Issue by SupriyaVenkatesh** [angular-ui/bootstrap#4245]
Hi ,

I am using UI-Datepicker in angular formly i have two date fields validfrom and validto on the selection of the first date field i need to disable the dates in second date field(i.e previous date of validfrom dates to be disabled)???

here is the code http://jsbin.com/yivelamiha/edit?html,js,output

can anyone please give the solution...for this

**Comment by wesleycho** [comment]
In the future, please read the CONTRIBUTING.md file before opening an issue on a repository: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem . Opening support issues in a repository is generally frowned upon, and slows project progress.
