### ISSUE TITLE
$modal controllerAs does not work properly

### ISSUE THREAD

**Issue by tqtran7** [angular-ui/bootstrap#4256]
I have created a plunker example: http://plnkr.co/edit/x4uuQjxfdGkdAMTXNqYv?p=preview
When controller: 'modalController as modal' it works
When controllerAs syntax is use instead, it breaks

**Comment by wesleycho** [comment]
Your example is against an old version of UI Bootstrap and Angular - it does work, as shown [here](http://plnkr.co/edit/sS7bQtVbEUBjPaPo4pDc?p=preview).

**Comment by tqtran7** [comment]
Ah ok, sorry about that, I did not check the version when testing. Looks
like we'll need to update our version of bootstrap too, thanks!
