### ISSUE TITLE
Include templates with npm package

### ISSUE THREAD

**Issue by olsonpm** [angular-ui/bootstrap#4260]
Currently the npm package `angular-ui-bootstrap` doesn't contain the template files.  These would be helpful in my situation where I only want to customize a few of them.  That way I can update the library, get the updated default templates (if any), and still point to my unchanged custom templates.

**Comment by wesleycho** [comment]
They are included in the *-tpls scripts - one can easily override them by overriding the $templateCache with the newer template.

**Comment by olsonpm** [comment]
Ah - that is reasonable.  Thanks
