### ISSUE TITLE
Modal fade in down animation degradation?

### ISSUE THREAD

**Issue by levin81** [angular-ui/bootstrap#4263]
With 0.13.1, modal fade-in-down and fade-out-up was working fine with Angular 1.4.3.

After changing to 0.13.3 the fade-in-down animation doesn't work when the modal is displayed - it just fades-in, not down (no animation). The fade-out-up works fine when closing the modal, though.

**Comment by wesleycho** [comment]
I am confused - are you using a custom animation via classes?

Can you create a reproduction in [Plunker](http://plnkr.co/edit/Rl97kK2Z6lNTxiWhFG0m?p=preview) so it is more clear?

**Comment by levin81** [comment]
http://plnkr.co/edit/6IQrImCFRZCpt0MKulYp?p=preview

**Comment by levin81** [comment]
Just adding an update, this also reproduces on your examples page now (after 0.13.4). "Open me!" button works fine. "Large modal" and "Small modal" exhibit the problem.

**Comment by wesleycho** [comment]
Linking [here](http://plnkr.co/edit/FZ98E8m9StEczBJ1WXpj?p=preview) that it still is an issue - not sure what is causing this.

**Comment by bboyle** [comment]
It seems to specifically happen when size is specified. Couldn't figure out why.

**Comment by lance-burton** [comment]
More specifically, it happens when the ng-class attribute associated with size evaluates to any value other than ''.

In the template is this div (line 8295 in 0.14.3):

```<div class=\"modal-dialog \" ng-class=\"size ? 'modal-' + size : ''\">```

I tweaked it to add other classes, like so:

```<div class=\"modal-dialog otherclass\" ng-class=\"size ? 'modal-' + size : 'anyclass'\">```

If 'otherclass' is added by itself, the modal drops in as expected. When 'anyclass' is thrown in, causing the ng-class to always evaluate to something, the modal does not drop in. And if 'anyclass' is already in the class directive, causing ng-class to effectively be a no-op, the modal again behaves properly.

**Comment by QuipHop** [comment]
Same issue, AngularJS v1.3.12, Angular-ui-bootstrap v0.14.3.
Animation doesn't work on modal appear

**Comment by lance-burton** [comment]
Update: when the size class is applied via ng-class, it ends up calling ```$animate.addClass(element, className)```. I haven't tracked down what the exact consequence of this i yet, but commenting out that call to ```addClass()``` revives the drop-in animation.

**Comment by wesleycho** [comment]
Strangely, not seeing it in `master` anymore, as can be seen [here](http://plnkr.co/edit/fKxXFFLOgYU5bR9YB9lF?p=preview).

**Comment by bboyle** [comment]
Looks good @wesleycho! Will this be in v0.14.4 and is there an ETA for that?

**Comment by wesleycho** [comment]
This will be in the upcoming 1.0 release - we are hoping to have it out by the end of the year.

Closing as hopefully resolved
