### ISSUE TITLE
Clear typeahead input when value not from popup entered

### ISSUE THREAD

**Issue by im1dermike** [angular-ui/bootstrap#4265]
When using `typeahead-editable="false"`, the model bound to the typeahead is undefined on blur when a value is not selected from the popup.  Unfortunately, the input still contains the value entered.  The expected/desired behavior for me is to clear the input in such a situation.

**Comment by wesleycho** [comment]
Can you put together a quick [Plunker](http://plnkr.co/edit/OnwFTu9tB4htYpSGvu2e?p=preview) illustrating this? It would save some time mentally processing this & make desired behavior clear.

**Comment by im1dermike** [comment]
Sure.  My apologies.  I thought I was missing something. :P

http://plnkr.co/edit/TAhtbdQH5C3DarGQjdyP?p=preview

**Comment by wesleycho** [comment]
No worries, it was more of a convenience favor :) .

**Comment by im1dermike** [comment]
Any timeline on this?

**Comment by wesleycho** [comment]
Not currently, this month is a pretty busy month for me, although maybe someone else is able to step up to the plate - if you're willing, feel free to file a PR with the fix for this with accompanying unit test, as that would be the fastest way to get the fix in.
