### ISSUE TITLE
alert dismiss on timeout

### ISSUE THREAD

**Issue by MrOutput** [angular-ui/bootstrap#4268]
The alert does not close after timeout...is this broken?

##### Jade
```jade
alert(type='info' dismiss-on-timeout=500)
```

**Comment by icfantv** [comment]
@MrOutput, it works.  Not sure what syntax you're using above (you may be missing quotes around your number) you want it as an attribute on the `<alert>` element.  Try editing the plunker from [the docs](https://angular-ui.github.io/bootstrap/#/alert) by adding this attribute and you will see it works.

**Comment by MrOutput** [comment]
its HTML5 syntax, it's valid and it's not working.

**Comment by icfantv** [comment]
I would first see what type of HTML is being generated by your browser as it's the browser's responsibility to handle HTML5 syntax.  As you can see from [this plunker](http://plnkr.co/edit/jbFEbNtHppsIeV6BIuCd), it is working.

**Comment by MrOutput** [comment]
```html
<div class="alert ng-isolate-scope alert-info" ng-class="['alert-' + (type || 'warning'), closeable ? 'alert-dismissible' : null]" role="alert" type="info" dismiss-on-timeout="10000">
    <button ng-show="closeable" type="button" class="close ng-hide" ng-click="close($event)">
        <span aria-hidden="true">×</span>
        <span class="sr-only">Close</span>
    </button>
    <div ng-transclude=""><span class="ng-scope">{{message}}</span></div>
</div>
```

**Comment by icfantv** [comment]
No.  That's only for when you want to provide functionality for the user to be able to dismiss it manually.  It doesn't always make sense to use it - it just depends on your use case and what you want your UX to be.

**Comment by MrOutput** [comment]
Remove the close attr, it stops working.

**Comment by icfantv** [comment]
Sorry, what `close` attribute?  I was referring to the close button (and thus `ng-click` handler).

**Comment by MrOutput** [comment]
The alert `close` attribute in the Plunker it is: `close="closeAlert($index)"`

**Comment by icfantv** [comment]
I thought you meant in your example above.

Yes, you need that because that's what's called after the timeout specified by `dismiss-on-timeout`.

**Comment by MrOutput** [comment]
Okay, thank you sir. Please append to the docs. 'The presence of the `close` attribute determines if a close button is displayed.' This is misleading.

**Comment by icfantv** [comment]
You're welcome, however your statement is not correct.  The presence of the `closeable` attribute is what determines whether or not the close button is correct.

The reason we require you to specify a close function is because we cannot presume to know what the user wants to do on an alert close.

**Comment by icfantv** [comment]
I think updating the docs is a fair request.  I will make the change.  Thanks.
