### ISSUE TITLE
typeahead-match.html uses deprecated directive bind-html-unsafe, Angular 1.4.x

### ISSUE THREAD

**Issue by glebv** [angular-ui/bootstrap#4270]
Angular.UI 0.13.3
Angular 1.4.3

You can see the issue in console if you try to use basic example which is provided to typeahead directive.
e.g. http://plnkr.co/edit/SYMYGyAPZ0vLE1Gee5Co?p=preview
there are a lot of warnings.
`bindHtmlUnsafe is now deprecated. Use ngBindHtml instead` 

I guess there are should be used ngBindHtml with custom sanitization filter.

**Comment by wesleycho** [comment]
This is already fixed in `master` due to bb9fa1a2a554b44b9532eb0195e2e66432ecb2d3 :) .
