### ISSUE TITLE
Datepicker: preverse bound date's time

### ISSUE THREAD

**Issue by matthewjh** [angular-ui/bootstrap#4271]
Hi all,

I have both a datepicker and a timepicker which are both bound to the same `Date` object, but when changing the date I don't want the time to reset to 12:00 as seems to happen by default. Ideally the datepicker could be used to change the date component (day, month, year) without touching the time component.

Is there an option for this or should I go ahead and cook up a PR?

**Comment by wesleycho** [comment]
Can you come up with a reproduction? There are tests against this behavior in the datepicker, so this shouldn't happen.

**Comment by matthewjh** [comment]
@wesleycho You're right. I was unable to reproduce this in a plunkr, but it's definitely occuring in a project I'm working on even in an isolated scenario. I'll keep trying to repro.

**Comment by BobbieBarker** [comment]
Closing as there hasn't been a reproduction of the issue after a period of some time.

**Comment by dben** [comment]
I've been able to reproduce this issue witth the datepicker popup - entering a date into the input field (instead of clicking a date) will reset the time. You can reproduce in this plunkr: http://plnkr.co/edit/6z5jMDrT3XGla7UyKzFM?p=preview
