### ISSUE TITLE
Modal focus should wait after animation.

### ISSUE THREAD

**Issue by wawyed** [angular-ui/bootstrap#4274]
When a modal is opened focus to either the modal or the autofocus element is applied after waiting a $digest cycle using modalRender property. That is not enough as the focus happens before/during the animation in class. This could be avoided by using the promise returned from $animateCss or $animate.

I could submit a PR if you thing that is the right approach.

**Comment by wesleycho** [comment]
This sounds reasonable - feel free to file a PR for this.
