### ISSUE TITLE
Timepicker - expose template url

### ISSUE THREAD

**Issue by waratah** [angular-ui/bootstrap#4275]
I have a need to override the formatting of the time picker and note the documentation does not include the ability to use a template url attribute which would be consistent with other components.

This would allow me to move the spinners around to best fit the screens.

**Comment by wesleycho** [comment]
Currently that feature is not implemented - I believe the two components that do not have it fully available is the timepicker and typeahead. I have been bogged down on a major refactor of the datepicker to optionally support moment.js usage.

If you'd like to take a stab at it, feel free to file a PR implementing this - it should be pretty easy to follow the existing feature and tests on some of the other components for adding this to the timepicker.

**Comment by icfantv** [comment]
@waratah please let us know if you want to do the PR for this.  Otherwise, I can knock this out in an hour or so.  Thanks.

**Comment by waratah** [comment]
Sorry I am a git newbie.   @icfantv can you please.

**Comment by icfantv** [comment]
I'll see if I can get to it tonight.  I have some work work to do.
