### ISSUE TITLE
How can I destroy a tooltip dynamically on an element?

### ISSUE THREAD

**Issue by cmehta82** [angular-ui/bootstrap#4283]
I have a custom directive to check validation of an input typeahead and I am adding errors as tooltip on change event inside directive. 

element.attr("tooltip", errorMessage);
$compile(element)(scope);

Now I want to remove this tooltip, when the input is valid. I tried, but that's not working.

element.removeAttr("tooltip");
$compile(element)(scope);

**Comment by icfantv** [comment]
@cmehta82, please do not use the issues as a support forum.  You may seek help by following the instructions [here](https://github.com/angular-ui/bootstrap#support).

You would be better off only having one tooltip and setting the message dynamically as you see fit.  Starting with 0.13.4 and available in the master branch currently is a new feature for programmatically being able to show tooltips and popovers.  This new feature combined with dynamic error messages is probably the right way to go.

Modifying the DOM as you are doing currently is very heavy-handed and a poor implementation.
