### ISSUE TITLE
Timezone issue with Datepicker and inconsistency

### ISSUE THREAD

**Issue by esditm** [angular-ui/bootstrap#4287]
UI Bootstrap: 0.13.3
AngularJS: 1.4.4

**Starting out**
1. Open this Plunker http://plnkr.co/edit/vcOgtMr0XSS3Mewj0KTK?p=preview
2. Observe that the input matches the model.

![start](https://cloud.githubusercontent.com/assets/7996710/9519444/0bec8e54-4cbf-11e5-9741-93ff412bae26.png)

**Problem 1**
1. Pick 30-01-2015 (dd-mm-yyyy) in the popup in both of the inputs. 
2. Observe that the input without a starting value (top field ) has an incorrect date in the model. While this might be caused by a timezone issue, then why doesn't the input with a starting value also do this?

![image](https://cloud.githubusercontent.com/assets/7996710/9519466/3e4a84a0-4cbf-11e5-9fed-d2e5e7ceca1a.png)

**Problem 2**
1. Reload the page, so we start from fresh.
2. Pick 20-05-2015 (dd-mm-yyyy) in the popup in both of the inputs. 
3. Observe that now both fields have the wrong date in the model. It's not even the same incorrect value. This extra offset might be due by summer time. 

![image](https://cloud.githubusercontent.com/assets/7996710/9519660/d769255a-4cc0-11e5-9370-9a7b17a5a8a5.png)

**Problem 3**
1. Reload the page, so we start from fresh.
2. Click the Today button (for me that's 27-08-2015 (dd-mm-yyyy)) in the popup in both of the inputs.
3. Observe that the value in the model is now the same incorrect value, unlike previous.

![image](https://cloud.githubusercontent.com/assets/7996710/9519796/327e3e0c-4cc2-11e5-83ab-f3a17ff26e19.png)

**Problem 4**
1. Reload the page, so we start from fresh.
2. Pick any date in the popup in both of the inputs.
3. Click the Today button (for me that's 27-08-2015 (dd-mm-yyyy)) in the popup in both of the inputs.
4. Observe that problem 3 isn't consistent as it now appears to behave like problem 2.

![image](https://cloud.githubusercontent.com/assets/7996710/9520182/1d46919e-4cc5-11e5-9f71-688efb8237f2.png)

---------------------------------

While I understand where the problem is coming from. Some sort of configuration for handling timezone/summer time is needed so the correct value can be set in the model.

Happy to hear about workarounds :)

**Comment by wesleycho** [comment]
Thanks for the details - this is indeed a bug that has been reported multiple times (there are other open issues on this).

**Comment by juanpujol** [comment]
Waiting for this fix like crazy! Thanks :+1:

**Comment by nipec** [comment]
+1

**Comment by juanpujol** [comment]
This is a bigger issue than I thought. Without the ability to use dates as strings since 13.2 I cannot find a way at all to keep the dates consistent between the model and the calendar.

Did anybody found a hack or something for that while we wait for an update? Thanks.

**Comment by yaronmiz** [comment]
+1

**Comment by icfantv** [comment]
Please do not +1 issues.  It doesn't add anything to the discussion and clutters the thread.  Thank you.

**Comment by raftalks** [comment]
any idea on when this bug will get fixed?

**Comment by wesleycho** [comment]
Just noting:

1 & 3) This turns out to not be a bug - one must be careful when parsing dates since `date.toJSON()` will munge the timezone information into the date string itself, which can cause the date representation to shift by a day. There is nothing we can do here, and this is a usage issue

2 looks like it might be a legitimate issue though, and should be investigated.

**Comment by wesleycho** [comment]
It should be noted that we no longer support date strings in the model.

2 & 4 no longer appear to be issues anymore, as can be seen in [this Plunker](http://plnkr.co/edit/B7GOO2iYhL254jrHof8V?p=preview)
