### ISSUE TITLE
TimePicker problem with hour column ( the first zero is hidden when you write on this column)

### ISSUE THREAD

**Issue by kevincaradant** [angular-ui/bootstrap#4288]
Hi

I need your help to fix that :).

When i wrote in the input "01" in the hour column , only "1" appears and when i leave the input the "0" appear. But i want keep the "0" in all case in the hours column . How can i do that ?

Thank you very much  :)

Kévin

**Comment by wesleycho** [comment]
For UX, it has been preferred that the 0 be omitted - we could perhaps implement this behind a feature flag though.

If you would like to take a stab at it, feel free to open a PR.

**Comment by kevincaradant** [comment]
oki and have you any idea, how i can show again the 0 even in the librairy if i have to change something ? 

otherwise i will wait a new feature ;)

Thank you

**Comment by BobbieBarker** [comment]
"PRs plz," means "Pull Request Please," it is an invitation to users of this library to submit a pull request to fix the issue. This is an open source library and anyone an contribute to it. Including you, to fix your very own problem and help other people who use this library! Details on how to contribute to this library can be found [here](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md).
