### ISSUE TITLE
Event name documented incorrectly

### ISSUE THREAD

**Issue by scottseeker** [angular-ui/bootstrap#4291]
On the main angular-bootstrap site you claim for the modal directive that "a modal.closing event is broadcast to the modal scope before the modal closes".

I did not see this event anywhere in the code, but I did see a "modal.stack.now-closing" event being broadcasted.

**Comment by icfantv** [comment]
you mean [this one](https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L490)?

**Comment by scottseeker** [comment]
Ah, okay.  For some reason I could not seem to catch this event.

**Comment by icfantv** [comment]
Per the docs, note that the event is broadcast **to the modal scope**.  [Here's a working plunker](http://plnkr.co/edit/G6V5rhSTzu9myu1QpCWg) as an example.

**Comment by bbodenmiller** [comment]
@icfantv seems your plunker link isn't working. Can you provide another example?

**Comment by icfantv** [comment]
Wow.  I lost all my plunkers.  Gone.  Poof.  I'm at the airport currently but will try to get to tonight or in the morning.  Please feel free to ping me again if I forget.  Cheers.

**Comment by bbodenmiller** [comment]
No worries. Found another example at https://github.com/angular-ui/bootstrap/pull/2256#issuecomment-44116315.
