### ISSUE TITLE
ng-Class assignments on accordion panel - 0.13.3

### ISSUE THREAD

**Issue by aghreed** [angular-ui/bootstrap#4294]
The way that accordion panel's are now assigning an `ng-class="{'panel-open': isOpen}" ` to each panel makes it impossible to place your own `ng-class` assignment on an <accordion-group>, as angular vomits because of a syntax error.

This is pretty uncool, guys. :(

Do you really need a classname to cue off here? I know that it wasn't the case in 0.13.0.

**Comment by icfantv** [comment]
In the future, please do not use the issues form for support and follow the instructions [here](https://github.com/angular-ui/bootstrap#support).

Additionally, this has been addressed in #4172, #3419
