### ISSUE TITLE
Carousel randomly flickering on iPad when switching images

### ISSUE THREAD

**Issue by blake-nouribekian** [angular-ui/bootstrap#4296]
I don't know if this issue exists but I noticed something on my iPad where the carousel does this random flickering when switching from one image to another. What seems to be happening is that the height of the image container is collapsing and all of my content on my site shifts up and then back down really quickly.

Angular 1.4.3
Bootstrap CSS 3.1.1
Bootstrap UI 0.13.3

**Comment by wesleycho** [comment]
Does this happen on the demo site? Do you have a reproduction that can be used to verify this behavior?

**Comment by blake-nouribekian** [comment]
I just tested the carousel on http://angular-ui.github.io/bootstrap on my iPad and it does have a blank image when you go from the last image to the first image or vise versa.  This one can be replicated every time unlike mine where it seems to be random. Anyways, it would be awesome if someone can take a look at this.  I am going to be launching my site soon and would like as few bugs as possible for my startup :)

**Comment by wesleycho** [comment]
Best person to take a look is usually the reporter of the issue :) - I'm going on vacation soon, and have been on a pretty tight schedule these days. I'll try to take a look at it, but I cannot guarantee the time in the near future, as there are other major issues on my plate too.

**Comment by blake-nouribekian** [comment]
Alright sounds good. I know what you mean man. I don't have time either with my day job plus 2 freelance jobs and my own site I am trying to launch.  If you can take a look then great, if someone else sees this and wants to take a shot that would be much appreciated.

**Comment by blake-nouribekian** [comment]
I dont think I see this issue anymore. We can close this.

**Comment by wesleycho** [comment]
There was a major set of carousel bugfixes in 1.x, I think it fixed the issues there
