### ISSUE TITLE
support modal draggable and resizable 

### ISSUE THREAD

**Issue by sargin48** [angular-ui/bootstrap#4307]
please support modal draggable and resizable

**Comment by icfantv** [comment]
I don't know how useful this would be given the isle case of modals in general.  I think what might be a much better enhancement would be to allow dragging and resizing of panels.

That said, this is probably not going to be a huge priority for us since people haven't been clamoring for this feature.  Please feel free to submit a PR.

**Comment by wesleycho** [comment]
I think this is outside the scope of this library - it should be noted that by creating custom directives and using custom modal templates, one can implement this oneself. This would require too much code for an edge case that can be implemented on the user side.

**Comment by peterrobinson** [comment]
I'd like to see this reopened.  Yes, it is very easy to do this with jqueryUI.  But there are many clashes/problems with use of jqueryUI with bootstrap. A pure bootstrap solution wd be excellent

**Comment by Lenndev** [comment]
I agree with @peterrobinson. using jqueryUI next to bootstrap doesn't do any good. would be a great improvement. so...please please please :D

**Comment by icfantv** [comment]
@peterrobinson, @Lenndev - per @wesleycho's comments, this is not a feature we are going to support and as mentioned you can do this yourself by using custom directives and templates.

Every feature added has to be balanced with what is the purpose/scope of this library and what is maintainable.  Recall that we are all unpaid volunteers.

**Comment by peterrobinson** [comment]
Indeed, I have implemented this, as a custom directive in Angular 2, so it is not an issue for me now. I guess the query is more relevant to people who are NOT working in Angular. -- but that is outside the scope of this list
