### ISSUE TITLE
[Question] Using less/sass with angular-bootstrap

### ISSUE THREAD

**Issue by jd-carroll** [angular-ui/bootstrap#4308]
I'm a bit of a newb here so please pardon this question, I did try searching for an answer but was unable to come up with anything.

Is it possible to use less/sass with angular-bootstrap?  The obvious answer is no given the dependency on bootstrap css.  But has anyone attempted to use less/sass (bootstrap-less) instead of the css directly?

**Comment by jd-carroll** [comment]
Actually, I think I am going to answer my own question here...

Since there is no listed dependency on bootstrap (package.json), there is nothing preventing the use of less/sass.  It would be completely transparent to angular-bootstrap, you just need to tie in the preprocessing.  (Correct?)

**Comment by icfantv** [comment]
In the future, please do not use the issues section for support issues, rather, follow the instructions listed on our site.

If you look at the distribution code, you'll see that there is no CSS distributed with UI Bootstrap (there is, but it's only a few lines and is a VERY specific use case), it's just an angular wrapper around the Bootstrap CSS which does support LESS/SASS.
