### ISSUE TITLE
Modal: custom z-index styling

### ISSUE THREAD

**Issue by bobmulder** [angular-ui/bootstrap#4313]
Hey all,

I need to customize the z-index value of my model. How am I able to pass custom styling or z-index to my modal?

Thanks

**Comment by icfantv** [comment]
Please do not use the issues forum for support requests and follow the instructions [here](https://github.com/angular-ui/bootstrap#support).

You have several options here as the modal service allows you to add additional classes (via `windowClass`) to the modal window and also to completely override the window template (via `windowTemplateUrl`).  You might first render a normal modal and decide where you need your `z-index` to determine which of these options will work for you.

**Comment by bobmulder** [comment]
Thanks for your suggestions. I know issue-report isn't for questions, but I tried to open it to make it customizable for the tool. However, these suggestions are enough ;)

**Comment by phazei** [comment]
Adding the z-index to the class doesn't have any way to account for multiple modals though.  Currently the calculation takes into account the index.  I don't believe it's currently possible for the default (1040/1050) z-index to be increased, but have it handle the multiple modals at the same time incrementing one just above the other.
