### ISSUE TITLE
Datepicker Popups closing when selecting a month

### ISSUE THREAD

**Issue by dwelch2344** [angular-ui/bootstrap#4314]
I've got a strange scenario where clicking any of the buttons on the datepicker will close, which really isn't a problem unless you're trying to scroll through the months (or pick one explicitly). When this happens, the date picker doesn't actually trigger [the cleanup method](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L779-L782) 

I'm fairly confident it's something to do with my app / libraries, as I can't seem to replicate it on a clean project. However, I've been trying to debug _why_ it's happening and am totally up a creek without a paddle. 

One potential issue I came across while stepping through the events is that the [documentClickBind](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L717-L723) function is being triggered and toggling the state, even if the event is inside the popup. It looks like line 718 is checking to see if the clicked element is inside the datepicker target, but in a popup's case it should probably also be a searching for a child of `popupEl` instead, correct? 

Adjusting that line locally to the following fixes our issues, but I'm curious how this isn't also occurring in vanilla apps. Does the following make more sense as it's possible to click a custom element the popup that doesn't close the popup? 

``` 
var documentClickBind = function(event) {
        if (scope.isOpen && !(element[0].contains(event.target) || popupEl[0].contains(event.target))) {
          scope.$apply(function() {
            scope.isOpen = false;
          });
        }
      };
```

An example of one of our datepickers: 

```
<input type="text" class="form-control"
                               datepicker-popup="{{dp.format}}"
                               show-weeks="false"
                               show-button-bar="false"
                               is-open="__dp.reportStart"
                               ng-click="dpOpen($event,'reportStart')"
                               ng-model="report.startDate"
                               required/>
```

**Comment by wesleycho** [comment]
If the event is inside the popup, it should not be bubbling up, due to the `$event.stopPropagation` call https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/popup.html#L1 .

I am not quite sure the reason for this call.

That said, the proposed change doesn't seem to break anything, and passes all of the tests - it seems reasonable enough.
