### ISSUE TITLE
Tooltip hangs off page

### ISSUE THREAD

**Issue by montlebalm** [angular-ui/bootstrap#432]
Wide tooltips are extending past the edge of the window. It looks like there needs to be some kind of boundary detection put in place.

Here's an example: http://plnkr.co/edit/uGI8m3

**Comment by JasonMongue** [comment]
Why is this closed? The problem has not been fixed.

**Comment by karianna** [comment]
@JasonMongue see comments further above.

**Comment by jkjustjoshing** [comment]
@karianna I'm still confused - why is this closed?

**Comment by BobbieBarker** [comment]
It was closed because we're dealing with this conversation in #375.
