### ISSUE TITLE
Tooltip running digest when it trigger mouseleave even tooltip-enable attribute is false.

### ISSUE THREAD

**Issue by lg314** [angular-ui/bootstrap#4321]
Mouseenter event should not run digest when tooltip-enable is false. I found the code triggered by mouseleave.

            function hideTooltipBind () {
              hide();
              if (!$rootScope.$$phase) {
                $rootScope.$digest();
              }
            }
I wonder whether it is necessary to run digest when the tooltip has never been opened.
http://plnkr.co/edit/7dUsCKFr6ZNtnZslHJW8?p=preview

**Comment by lg314** [comment]
I tried to change the code like this. And it works good in my case. But it should be tested in other cases.

            function hideTooltipBind() {
                if (ttScope.isOpen) {
                    hide();
                    if (!$rootScope.$$phase) {
                        $rootScope.$digest();
                    }
                }
                else if (ttScope.popupDelay && popupTimeout) {
                    $timeout.cancel(popupTimeout);
                    popupTimeout = null;
                }
            }

**Comment by wesleycho** [comment]
Can you please explain things more clearly here? Your comment seems to be talking about something completely separate from the original post.
