### ISSUE TITLE
Directives as class in bootstrap ui modal do not compile

### ISSUE THREAD

**Issue by nicolasroger17** [angular-ui/bootstrap#4326]
I'm trying to pass a directive as a class in the windowClass field but it doesn't seem to be compiled and therefore the directive is not called.

Please see the detail on [SO](http://stackoverflow.com/questions/30177840/directives-as-class-in-bootstrap-ui-modal-do-not-compile/32317051#32317051).

**Comment by icfantv** [comment]
Cool.  Thanks.

**Comment by wesleycho** [comment]
I am not sure we should support this particular case - it should be noted though that one can provide a custom template for the window and attach a standard directive there.

**Comment by icfantv** [comment]
@wesleycho, this was the one we spoke about and you wanted an issue entered because it was an interesting idea.

**Comment by wesleycho** [comment]
I know, but I think I misunderstood - in would highly recommend a custom template if one wants to apply a custom directive.

**Comment by icfantv** [comment]
ok.  closing as won't fix.
