### ISSUE TITLE
there is no date range selection functionality

### ISSUE THREAD

**Issue by shailendra9** [angular-ui/bootstrap#4329]
Hello , i need to use date range functionality ...so the function should select two dates from calender popoups...(like 12-2-2015  to 15-5-2015)

**Comment by decherneyge** [comment]
This is technically possible currently. Here is an example of one way to tackle the date range.

http://plnkr.co/edit/wHpbTG6E7fTqpGebYZZP?p=preview

**Comment by RopoMen** [comment]
Hi,

I have used ui-bootstrap in many customer projects and I have build this range selection at least three times and now it seems that in my latest project there is again need for this and I was thinking of implementing it on ui bootstrap project if possible. I'm not 100% sure when this would happen but I would guess that in 2-4 months from now.

My question is, 
What is the look of the range selection directive?
I was looking current implementation "angular + bootstrap" and most of them relay on jQuery + moment.js. This project had pretty good looking UI https://github.com/fragaria/angular-daterangepicker

What do you think about this?

Directive interface could be roughly something like
```js
.directive('uibDateRangePicker', function() {
  return {
    restrict: 'EA',
    scope: {
      rangeStart: '=',
      rangeEnd: '=',
      showTime: '@' //Boolean, should we show time selection as well
    }
  };
})
```

This implementation would also require tests and demo page update. Also I think that rangePicker and rangePickerPopup should be separate directives. Although this implementation uses mostly current date/time picker implementations. 

Also how ngModelController validation should be taken care of?

**Comment by RopoMen** [comment]
In my previous implementation I have only used two datePicker fields, start/end and I have had a ng-change attached to those which is triggering the validation for the range and settings formController validity over there. 

If end <= start -> invalid
If showTime is not used then time parts needs to be set to 0 in both date models. In some cases start could have 00:00:00 time part and end 23:59:59.

**Comment by wesleycho** [comment]
I have done a date range sort of functionality in the past at work using two inputs tied to different datepicker instances (wrapped in a modal instead of using the datepicker popup), one for a min date and the other for a max date for search functionality.

I am going to close this as likely out of scope for this library - most of our active efforts are going towards ng-bootstrap, and this likely would be too complex due to the complexity of the datepicker & needing to do research as to what sort of UX makes sense.
