### ISSUE TITLE
Notification on Selection for Typeahead

### ISSUE THREAD

**Issue by nwpappas** [angular-ui/bootstrap#433]
Implement event notification for user selection of typeahead, so developer can capture selection and perform additional additional actions.

The [AngularStrap project's typeahead](https://github.com/mgcrea/angular-strap/blob/master/src/directives/typeahead.js), a wrapper for Bootstrap (vs. native AngularJS), fires a common event for all typeahead fields.

Example:
1. User enters an Employee ID.
   - Typeahead information gathered from `$http` request as field is filled.
2. User selects Employee ID from typeahead list, either by click or key stroke.
3. **updater** makes `$http` request for complete employee record and fills in remaining form elements.
4. User reviews fields and can update (e.g., update "Richard" to "Bob" in name field - or - job title is incorrect).

Additionally, typeahead is hooked up to name field so user can type in name instead of Employee ID.  Same process as above follows.

As a result, it would be very beneficial if each typeahead had its _own_ `updater` callback instead of a single common event fired when any typeahead is updated.  Multiple typeaheads could exist on the same page.

Below is a jQuery implementation of the concept:

HTML:

``` html
<input type="text" pattern="[0-9]*" class="span6" id="textbox_EMPID" data-provide="typeahead" placeholder="8675309">
```

JavaScript:

``` javascript
$('#textbox_EMPID').typeahead({
  minLength: 3,
  source: function (query, process) 
  {
    $.get(
      '/visitorLog/search',
      { b : query },
      function(data)
      {
        process(data);
      },
      "json"
    );
  },
  updater: function (item)
  {
    $.get(
      '/visitorLog/search',
      { b : item, emp : true },
      function(data) 
      {
        jQuery.parseJSON(data).forEach(function(element, index, array) 
        {
          // fills out the remaining form fields based on employee id search
          autoFieldComplete(element);
        });
      },
      "json"
    );

    return item;
  },
/*
  matcher: function (item) {
  },
  sorter: function (item) {
  },
  highlighter: function (item) {
  },
*/
});
```

Typeahead selection event could return the selected value or the selection _object_.  If selected _object_ can be returned it opens up ability to query database only once, pulling a complete record with a single typeahead selection.

Basic extension of use case:
- Manufacturing Parts Search.  On selection of part number from typeahead, the complete part record is queried and displayed.
- Subcategory Selection.  The selection made in a "category" field determines what typeahead options are available in "subcategory" section, which would have to be retrieved after the initial selection (similar to an "editable combobox", allowing user to select existing or enter new value).

The notion is simply that an value from a typeahead field could one piece of a larger record, which could by queried on if the developer has access to the **updater** (to use Twitter Bootstrap terminology) event.

**Comment by murraybauer** [comment]
typeahead-on-select does work @hectormateosoblanca.  This worked for me.
http://stackoverflow.com/questions/16109364/angular-ui-bootstrap-typeahead-callback-on-selectmatch/17994624#17994624

@JobaDiniz $viewValue does not exist in the spec.  See:
https://github.com/angular-ui/bootstrap/blob/91ac17c9ed691a99647b66b3f464e3585398be19/src/typeahead/test/typeahead.spec.js#L372
