### ISSUE TITLE
Add track by support to typeahead

### ISSUE THREAD

**Issue by NTag** [angular-ui/bootstrap#4331]
Hello,

We can't add "track by" in a typeahead expression, which is limited to
```html
typeahead="value as label for element in collection"
```

I think angular-ui uses after ng-repeat with "track by $index". But if you use bind-once in your template, it does not work very well...

The user should be able to specify his own track by expression.

**Comment by icfantv** [comment]
just a note that the angular docs state you are not supposed to use `select as` and `track by` together.

**Comment by wesleycho** [comment]
It should also be noted that `track by` and `select as` are not something built into the Angular parser - the directives themselves parse it manually with regexes and do actions appropriately.

In this case, `track by` is already used interally by the typeahead, although in a naive fashion, as can be seen [here](https://github.com/angular-ui/bootstrap/blob/master/template/typeahead/typeahead-popup.html#L2). We could perhaps allow an optional function binding that lets users return the id given an item to help optimize the `track by` portion.

**Comment by wesleycho** [comment]
Considering this further, I think we should leave it for users to override the template - `track by` is something that needs to be baked into the template, but we have no knowledge of what keys a user might want.

Closing as something we can't really support.
