### ISSUE TITLE
Custom CSS class in typeahead and dropdown when append-to-body is true

### ISSUE THREAD

**Issue by ehteshamkafeel** [angular-ui/bootstrap#4332]
Sometimes you want to style the drop down according to some particular styles matching to your look and feel or to achieve some very specific functionality. If the `typeahead-append-to-body="true"` you can't style the drop down by being more specific. e.g. you can't do `.my-component .dropdown {}` sure you can do `.dropdown {}` but that would globally apply style to every dropdown in your app. 

It would be really nice if we could specify another attribute like `dropdown-custom-class` to the directive and the class would be added to the main container i.e. `<div class="dropdown my-custom-class">`

**Comment by wesleycho** [comment]
This makes a lot of sense - PRs welcome!

**Comment by wesleycho** [comment]
As per discussion in fa1cdfc, this feature will not be supported. In order to accomplish custom classes currently, the solution espoused is to use a custom typeahead popup template.

**Comment by datazen** [comment]
This actually makes more sense than you would think.   It would be NICE to simply have a class we can change in the ngb-typeahead-window div.   I mean how freaking hard would that be to do?   It seems a lot of users are having the same issues.
