### ISSUE TITLE
Using is-open with popovers will display the popover by default

### ISSUE THREAD

**Issue by kawazoe** [angular-ui/bootstrap#4335]
Hi guys,

I was just playing with the new popover-is-open parameter that got added in v0.13.4 and I noticed that if I use the following code...

    <button popover="test content" popover-is-open="testIsOpen" type="button" class="btn btn-default">test popover</button>

...with `testIsOpen` left undefined, the popover will be visible by default. You can test it yourself by copying this code inside the popover sample plunkr.

**Comment by wesleycho** [comment]
Verified [here](http://plnkr.co/edit/7xic1OZqTMLhfhD1Nfkh?p=preview).

Also reproducible for the tooltip [here](http://plnkr.co/edit/HbJtuIPWjesNnG5Zc6hQ?p=preview) (first link)
