### ISSUE TITLE
Add support for tab fade effect

### ISSUE THREAD

**Issue by davide-quix** [angular-ui/bootstrap#4339]
As the title suggest, it would be nice to add a configuration in tab directive to activate fade effect like that on bootstrap demo.
http://getbootstrap.com/javascript/#tabs

**Comment by wesleycho** [comment]
We won't be able to add that animation itself, but we can add support for it using ngAnimate for when the pane enters in the view, which lets the user add their own animations.

**Comment by sevdog** [comment]
+1

**Comment by wesleycho** [comment]
Please do not +1 issues, it adds no useful signal & adds noise

**Comment by wesleycho** [comment]
Going to push this back to 0.14.x, lots of issues on the plate currently and we're overdue for releasing.

**Comment by wesleycho** [comment]
Question - is it not possible to take advantage of ngAnimate currently through ng-class's `ng-active-add`/`ng-active-add-active` and `ng-active-remove`/`ng-active-remove-active` classes?

**Comment by wesleycho** [comment]
Closing in favor of #4836, keep an eye on that issue.
