### ISSUE TITLE
How to  support the Accessibility & G11N

### ISSUE THREAD

**Issue by zoyun** [angular-ui/bootstrap#4352]
How to  support the Accessibility & G11N?

**Comment by icfantv** [comment]
This is not very much information to go on here so there's not much we can do to answer your question without more specifics.

Additionally, for support related issues please follow the instructions [here](https://github.com/angular-ui/bootstrap#support).  I would encourage you to use StackOverflow.

**Comment by zoyun** [comment]
I want to know angular-ui/bootstrap whether to support the Accessibility & G11N?

**Comment by icfantv** [comment]
If you asking whether or not UI Bootstrap supports accessibility with respect to the ARIA specification, it does to some degree, but is not complete.

As far as internationalization goes, there is nothing language specific in either Bootstrap CSS or UI Bootstrap (save for the API, which is in English).

If you have further questions, please direct them to StackOverflow as the issues forum is strictly for bugs.  Thanks.
