### ISSUE TITLE
Opening modal backdrop without modal

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#4353]
When opening modal there is nice black backdrop.
Is there a way to show/hide this backdrop - modal is not needed.

I have widgets and I can maximize them. And I want to use this backdrop - only backdrop - not modal.
Is there a servcie to control backdrop iteslf?

**Comment by icfantv** [comment]
Questions of this nature are best served by posting them on StackOverflow.  Additionally, please follow the instructions [here](https://github.com/angular-ui/bootstrap#support) and do not use the issues forum for support requests.

As UI Bootstrap is an Angular veneer on top of Bootstrap CSS and essentially contains no CSS, the class you want is `modal-backdrop` and resides in the core Bootstrap CSS
