### ISSUE TITLE
Collapse with Table Row not animating correctly

### ISSUE THREAD

**Issue by trajano** [angular-ui/bootstrap#4358]
When applying the collapse transition on a table row, the animation does not work, but does take its time.

        <tr ng-click="row1Open = !row1Open">
          <td>Acrylic (Transparent)</td>
          <td>{{row1Open}}</td>
          <td>foo</td>
        </tr>
        <tr collapse="!row1Open">
          <td>Detail Row</td>
          <td>abc</td>
          <td>$2.90</td>
        </tr>

The following http://plnkr.co/edit/bZIpFvIPjMxVaFh19Ln0?p=preview shows it in full.

**Comment by Foxandxss** [comment]
I can see it failing on master. We will research it.

**Comment by wesleycho** [comment]
Here is the Plunker using `master` - it should be noted that this also fails in 1.3.

I wonder if this is an Angular issue and not UI Bootstrap.

**Comment by Foxandxss** [comment]
@wesleycho You forgot the link.

**Comment by wesleycho** [comment]
Doing some further investigation, this appears to be a longstanding pre-existing issue with animating `tr` elements - my recommendation is to not do it. It seems that even when using vanilla Bootstrap JS, one has to hack around it too.

[Here](http://plnkr.co/edit/GV9Euz5AJFllik7VhHM5?p=preview) is a workaround that works - I am going to close this issue as not a fixable bug unfortunately. Thankfully, one can work around this, as my Plunker shows.
