### ISSUE TITLE
Drop-down menu doesn't work on focus

### ISSUE THREAD

**Issue by Tachii** [angular-ui/bootstrap#4359]
Gist example, try to focus input with tab and trigger drop down menu:
http://plnkr.co/edit/lW0hNYXzyibLujgSxAzi?p=preview

As you see it only triggers on actual click, not when focusing with TAB and then pressing enter.

**Comment by icfantv** [comment]
Can you please explain your use case as to why you need a left-click drop-down menu on a text field?  I would argue that this is not a very common use case.

Secondly, I *could* see a potential use case for open dropdown on focus via TAB, but I'd want to look at the ARIA docs more closely.  I can say that our dropdowns are missing some ARIA compliance.  But either way, this is probably not going to be a very high priority feature.

**Comment by Tachii** [comment]
I need it for something like search.

You click on a field - dropdown with a huge scrollable list appears.
Then you enter some string and this dropdown list becomes shorter and more precise.

Now I can force a click on a focus, so I can actually navigate only with my KB, but it will also trigger the click when I actually click, so I will have double-click effect in the end if I'll actually click on the field.

**Comment by Tachii** [comment]
I actually have to do this, to make it work:

```.directive('myClickable', ['$document', function($document) {
        return {
            link: function(scope, element, attr) {
                element.on('mousedown', function(event) {
                    element.data('mousedown', true);
                });
                element.on('focusin', function(event) {
                    if (element.data('mousedown')) {
                        element.data('mousedown', false);
                    } else {
                        element.click();
                    }
                });
            }
        };
    }]);```

**Comment by icfantv** [comment]
Closing in favor of #4772.
