### ISSUE TITLE
No animation of progressbar with ng-show directive

### ISSUE THREAD

**Issue by FabrizioA** [angular-ui/bootstrap#4360]
Hi, I've a problem with the progressbar component generated by a ng-repeat loop.
If i remove the ng-show directive of the parent container if tr (ng-repeat directive), the progressbar's animation works fine. If I leave ng-show, the progressbar works ok, but without animation.
I'm using angular-bootstrap 0.13.4 with anguarjs 1.3.16 (with ngAnimate).
Any suggestions?
Thanks in advance.

```html
<div class="custom classes" ng-show="myList.hasItems">
    ...
    <tr ng-repeat="item in ::myList.items track by item.name">
        <td>
            {{ item.name }}
        </td>
        <td>
           <progressbar value="item.valuePerc" animate="true" class="progress progress-striped">
            {{ item.valuePerc | number:2 }} %
        </progressbar>
    ...
```

**Comment by Foxandxss** [comment]
Can we have a plunker with a reproduction please?

**Comment by FabrizioA** [comment]
I hope to post a plunker soon.

**Comment by FabrizioA** [comment]
Hi @Foxandxss , sorry for my delay.
I'm using ui.bootstrap's progressbar with "angular-gage" component... I've realized that if I change $scope.myGageValue in the same function of $scope.progressBar.value, the progress bar value is animated from 0 to my $scope.progressBar.value.... If I not set the angular-gage value... my progress bar is not animated at the first load... it is animated only from current value from a new value.
Anyway.... I've read that default behavior of progress bar is: not animated at the first time; animated when the value change.

How can I animate the progressbar from 0 to currentValue at the first time (on load of it)?
this Plunk http://embed.plnkr.co/T2plU3/preview simulate my current application code flow.
Thanks in advance. (sorry for my English :) )

**Comment by FabrizioA** [comment]
I realized that this is not a progressbar bug so I close this issue. Sorry for my misunderstanding.
Thanks anyway. 
F.

**Comment by MilesYM** [comment]
@FabrizioA I’m interested to know this answer to this one as I’m having the same issue.

How did you achieve to animate you progress bar? 
Could you update your plnkr? 
Thx
