### ISSUE TITLE
carousel breaks on dynamic slide add and scroll

### ISSUE THREAD

**Issue by totano** [angular-ui/bootstrap#4361]
as seen in this plunker, if you add a slide and force scrolling right or left, rendering up.
http://plnkr.co/edit/HnfgQMHXNE2QQdOMFeZl

You can see that also in the demo page (https://angular-ui.github.io/bootstrap/#/carousel),
move on last slide and then quickly click the Add Slide button and then the carousel next control arrow,
the UI will flicker and then the carousel will become unresponsive.

As a temporary fix I'm using $timeout after setting the active property

**Comment by wesleycho** [comment]
This appears to be a bug when on the last slide - is this correct?

**Comment by totano** [comment]
this happens when on the edge slide (both last and first) after adding a new slide and advancing the carousel, both manually (setting active to false on the current slide, and true on the following) or clicking carousel prev/next controls.

**Comment by wesleycho** [comment]
This will be fixed by #4984, as can be seen [here](http://plnkr.co/edit/8fvkMmJ2kM8cpQ1fAckF?p=preview)
