### ISSUE TITLE
Typeahead tab and mouse click outside have different behaviour

### ISSUE THREAD

**Issue by AndersMalmgren** [angular-ui/bootstrap#4369]
Given: typeahead-editable="false"

If you type something in a typeahead and tab out it will select current item (Correct behavior). If you mouse click outside it will not. When  typeahead-editable is false I guess this could be considered a bug? We never want none auto completed content in the box after we leave box when typeahead-editable = false?

**Comment by wesleycho** [comment]
This should be fixed via 1d9294c8e6b0d888fd77317cb634dd37bb9b5094
