### ISSUE TITLE
$tooltipProvider.setTriggers with multiple events broken with v. 0.13.4

### ISSUE THREAD

**Issue by LeleDev** [angular-ui/bootstrap#4371]
I have the following code in my app:
```
$tooltipProvider.setTriggers({'mouseenter':'mouseleave click'});
```
to make my tooltip close either clicking OR leaving the elements.
Since the last update, none of these two events does trigger a tooltip hide action. If instead I keep just one of the two events ('mouseleave' or 'click'), the tooltip behaves has expected. So I guess that something is broken regarding multiple events triggers support.

Thank you in advance

**Comment by wesleycho** [comment]
Can you whip up a quick Plunker demonstrating this?

**Comment by LeleDev** [comment]
Here you go:
http://plnkr.co/edit/TYDF58LwMhypuc7AgZ7J?p=preview

**Comment by wesleycho** [comment]
Thanks - I was able to fix this quickly thanks to that reproduction

**Comment by LeleDev** [comment]
Great job! Thank you!

**Comment by wesleycho** [comment]
Don't close this just yet, we'll close it when the PR is merged in :)
