### ISSUE TITLE
Tooltip error on already destroyed scope

### ISSUE THREAD

**Issue by levin81** [angular-ui/bootstrap#4372]
After a tooltip's scope is destroyed asynchronously, it will try to hide() it and throw this error: 

Uncaught TypeError: Cannot set property 'isOpen' of null

http://plnkr.co/edit/67MVP62ZxbPMduA5usGt?p=preview

1. Click 'Show'
2. Click 'Click me' (see error in console)

**Comment by wesleycho** [comment]
This is already fixed in `master`, as can be seen [here](http://plnkr.co/edit/g7J80Kjq2Dg7BUTJviQi?p=preview).

**Comment by KopiSusu** [comment]
Awesome! Also having this issue. Is there a workaround before the release?

**Comment by icfantv** [comment]
@KopiSusu, yes.  You can checkout master and do a snapshot build.  This should be as simple as doing a `node install` and then `grunt`.  The SNAPSHOT build files will be in the `dist` directory.

**Comment by ozziest** [comment]
I have got same error but I have to wait the new release. :) I think you might have a bug branch for the last release in order to publish updates which has got bug fixes.

**Comment by AhsanAyaz** [comment]
We encountered the issue too while developing an app :) waiting for the release.. thanks

**Comment by icfantv** [comment]
Hey guys, 0.14.0 is not going to be released for some time based on the amount of work we want to get into the release.  If you're really hot for this fix, you basically have two options:  either backport the fix into your existing 0.14.0 version of UI Bootstrap, or fork and build the latest SNAPSHOT from `master`.

The first is the least risky as `master` includes a bunch of other fixes as well as our current work on adding directive prefixes to components.  In theory, `master` shouldn't contain NEW bugs, but you never know...it is a SNAPSHOT.

**Comment by petervojtek** [comment]
hi all,

I currently use `"angular-bootstrap": "0.14.0"` and I still experience the issue:
```
TypeError: Cannot set property 'isOpen' of null      angular.js:12783
    at ui-bootstrap-tpls.js:4710
    at Scope.$eval (angular.js:16359)
    at Scope.$digest (angular.js:16175)
    at angular.js:16398
    at completeOutstandingRequest (angular.js:5754)
    at angular.js:6031(anonymous function) @ angular.js:12783(anonymous function) @ angular.js:9535Scope.$digest @ angular.js:16177(anonymous function) @ angular.js:16398completeOutstandingRequest @ angular.js:5754(anonymous function) @ angular.js:6031
```

**Comment by icfantv** [comment]
@petervojtek based on how old this issue is and that we are currently on version 1.3.2 - the right solution here is to upgrade your library versions.  we do not issue patches for back versions.

**Comment by petervojtek** [comment]
@icfantv, thanks for response.

Actually I messed things up - I overlooked how old your discussion is and I thought that when you refer e.g. to `0.14.0`, you actually mean `1.4.0` (some software teams do this different external and internal version numbering).

Now I updated to `1.3.2` and all works well.

**Comment by mak7iliano** [comment]
> you actually mean `1.4.0`

I think no. cause for angularJS max version is 0.14.3
