### ISSUE TITLE
Component prefixing

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#4373]
So this is the proposal for the prefixing.

Steps for a `foo` component:

* Create a comment at the bottom of `foo.js`, copy all the content of the file below that comment (removing modules dependencies in here so it is a `get` module instead of `create`).
* Prefix the directive (and controllers) and make the needed changes if any (for example check if there is any `$watch` using the old directive name)
* Fix the tests, normally just change the elements to compile.
* Add a `value` service in the module after the comment to suppress the deprecation warnings.
* add an `if` inside the deprecated directives to log the deprecation.
* Add a comment at the bottom of `foo.spec.js` and below that, a new describe to check that the suppression works.
* Update the demo and docs to show the prefix.

For the commit title, it is more a feature than a bug fix (It features a prefix now).

Here is the list in strict order (some component depend on other components). If you want to tackle one, edit this to add yourself.

- [x] Collapse (@Foxandxss)
- [x] Accordion (@Foxandxss)
- [x] Alert (@Foxandxss)
- [x] Buttons (@Foxandxss)
- [x] Carousel (@BobbieBarker)
- [x] Dateparser (@wesleycho)
- [x] Position (@wesleycho)
- [x] Datepicker (@wesleycho)
- [x] Dropdown (@BobbieBarker)
- [x] Modal (@Foxandxss)
- [x] Pagination (@BobbieBarker)
- [x] Tooltip (@wesleycho)
- [x] Popover (@wesleycho)
- [x] Progressbar (put it like the others) (@wesleycho)
- [x] Rating (@wesleycho)
- [x] Tabs (@icfantv)
- [x] Timepicker (@wesleycho)
- [x] Typeahead (@BobbieBarker)

**Important**: If there is any $ in a service / controller / directive, remove it.

**Comment by Foxandxss** [comment]
About the `$` thing, Angular guidelines states that `$` is only for angular use.

**Comment by wesleycho** [comment]
I don't think we should remove the `$` - pretty much any third party library still uses it, such as UI Router. In truth, I doubt Angular will remove support of this in service names.

**Comment by Foxandxss** [comment]
@wesleycho check this https://google-styleguide.googlecode.com/svn/trunk/angularjs-google-style.html#dollarsign

**Comment by wesleycho** [comment]
I have seen that before, but I'm speaking of the reality of the ecosystem. It can be found in third party libraries all over the place.

**Comment by Foxandxss** [comment]
That doesn't mean it is done correctly.

Personally I don't like them, adds nothing. But I don't mind leaving them anyway.

**Comment by RobJacobs** [comment]
@BobbieBarker @wesleycho My schedule is getting back to normal, I can tackle Datepicker and Typeahead if you haven't started these yet.

**Comment by Foxandxss** [comment]
@RobJacobs There is a PR for datepicker but @wesleycho tried to do a bit too much with it and well, it is more stuck. Typeahead is almost done I think.

**Comment by wesleycho** [comment]
If you want to fix the tests in my attempt at the datepicker one, you're more than welcome to :) .
