### ISSUE TITLE
ng-controller on tab element throws error while using AngularJS version greater than 1.4.1

### ISSUE THREAD

**Issue by bkmagnetron** [angular-ui/bootstrap#4381]
Here is the Plunker for AngularJS 1.4.5 with ui bootstrap 0.13.4
http://plnkr.co/edit/sGT7l5qUWkY627SMJzMC

**Comment by wesleycho** [comment]
You should avoid using `ng-controller` in general - it is considered a bad practice in serious apps. You should especially avoid using it on a directive that uses an isolate scope such as `tab`.

[Here](http://plnkr.co/edit/epqJujRldXBrdZs2Czt2?p=preview) is a suitable workaround.

**Comment by bkmagnetron** [comment]
But, I want the scope of the controller to cover the entire tab element. Because I have some dynamic value on tab-heading.

**Comment by wesleycho** [comment]
One can accomplish that by handling the controller/service logic at a higher level - it is a bad practice to mix that logic within a component in an in-between state though.
