### ISSUE TITLE
Popover shows before positioning is complete

### ISSUE THREAD

**Issue by Ardenexal** [angular-ui/bootstrap#4382]
When using hover (had the same issue with others but hover was the most noticeable) on a popover sometimes the popover becomes visible before the positioning has completed. i wrote a plnkr to show the bug.

if you quickly pass your mouse over the button you will see sometimes that the popover will be visible at left:0, top:0 instead of only showing once the position has been set, this could be caused by a slow computer but it should be hidden while processing the popover position

http://plnkr.co/edit/ElCZD5iOonVLL6f5fVbe?p=preview

**Comment by Ardenexal** [comment]
Just found this bug doesn't exist in 0.13.3 only in 0.13.4

**Comment by wesleycho** [comment]
This is now fixed in `master`, as can be seen [here](http://plnkr.co/edit/nJVzOm0k8FnQjgdioS7w?p=preview).
