### ISSUE TITLE
Tooltip initial position bounce / flicker

### ISSUE THREAD

**Issue by razvanbalosin** [angular-ui/bootstrap#4391]
The position of tooltips flickers sometimes in other places of the document before going to it's right position.

Here is a demo [plunker](http://plnkr.co/edit/bpBNM7UFSWyuxkBK3jDP) replicating the issue. Just hover over the tooltips multiple times, you'll notice it.

**Comment by wesleycho** [comment]
This is currently fixed in `master`, as can be seen [here](http://plnkr.co/edit/1AqGnQzyPd2khi6V0VjH?p=preview)
