### ISSUE TITLE
Error "$apply already in progress" shows when dismissing modal by press "Esc" button

### ISSUE THREAD

**Issue by hungyc** [angular-ui/bootstrap#4396]
There's no problem if I press the cancel button, but when press "Esc" button on keyboard, it shows "$apply already in progress", any solutions?

**Comment by Foxandxss** [comment]
Our demos are working fine. That has to be something in your end. Reproduce it on a plunker.

**Comment by hungyc** [comment]
I've double checked my code, it's my problem, thx a lot!

**Comment by normanjaeckel** [comment]
Sorry for spamming here: @hungyc Do you still know what the problem was? I have exactly the same problem and I have no idea why.
