### ISSUE TITLE
Typeahead and $parsers not working well together

### ISSUE THREAD

**Issue by emasch** [angular-ui/bootstrap#4398]
Hi there,
i've a problem using your Typeahead directive togeher with a $parser which updates the viewValue.

When I updated the viewValue to format a String with spaces, than the typeahead-window won't open.
Do you have any idea?

Here's a plunker: http://plnkr.co/edit/9qitEudseluyXeBHAyEo?p=preview

Used Libraries:
angular Version: 1.4.5
bootstrap-ui Version: 0.13.4
angular-animate Version: 1.4.5

**Comment by wesleycho** [comment]
This is a user issue - your parser results in a mutated $viewValue, so the filter when applied isn't matching any results.
