### ISSUE TITLE
Angular-UI-Bootstrap website custom build not working on Chrome Version 45.0.2454.85 m

### ISSUE THREAD

**Issue by byronalfonso** [angular-ui/bootstrap#4403]
Hi Everyone,

I'm building an app and I want to use one of Angular-UI-Bootstrap modules so I used the custom build found here - https://angular-ui.github.io/bootstrap/. The problem is that it doesn't work on chrome. I tried using firefox to download the build and was successful... This perhaps is not a big issue but I'm reporting it anyways so the author can fix the issue. That's all thanks!

**Comment by icfantv** [comment]
Are you saying the custom build doesn't work on chrome?  What version of chrome?  What platform and OS?  Thanks.

**Comment by wesleycho** [comment]
I was not able to reproduce this on Chrome 45.0.2454.85 on OSX

**Comment by byronalfonso** [comment]
Hi Everyone,

First of all I apologize for the late reply.. I'm usually out every weekend. Anyways.. as soon as I was available I tried recording the error but the error wasn't there anymore. Now I am able to create a custom build and download it. I'm suspecting that it could possibly be a memory leak on Chrome (windows) on my pc and not actually an error of the website. I apologize if it bothered anyone, the purpose was to notify anyone that might be experiencing the same. Apparently it was an isolated case on my part. I am closing this ticket now. Thanks!

**Comment by wesleycho** [comment]
Not a problem, it was worth investigating and wasn't difficult to try to verify :) .
