### ISSUE TITLE
tooltip and popover flicker before correctly positioned 

### ISSUE THREAD

**Issue by fotofinder** [angular-ui/bootstrap#4407]
since 457f10c tooltips and popovers appear shortly after trigger at 0, 0 , disappear and eventually reappear at their correct position. This can best be seen when they are body-appended.
I'd  happily add a plunker here, but for some reason I can't save :-( 

I created an gist: https://gist.github.com/fotofinder/540f05ef77ef10bd2673

**Comment by edcarroll** [comment]
This has already been fixed in `master`, see [here](http://plnkr.co/edit/1AqGnQzyPd2khi6V0VjH?p=preview)

**Comment by fotofinder** [comment]
Ah, good. Thanks

**Comment by jitendersandhu** [comment]
I also faced the same issue, fixed by upgrading. Thanks!
