### ISSUE TITLE
I have a page where same ui is shown for 10 or more tabs how do i validate each tab?

### ISSUE THREAD

**Issue by saroj990** [angular-ui/bootstrap#4413]
I have page where i have 10 to 15 tabs for a particular injury and I added a custom directive for validation  it works fine when i have a single tab.
But when i have more tabs then it fails neither the validation message is shown in a particular tab .Since the element/field name is same for all the tab i think it doesn't work.
Please if any one has done this  please give me some idea
Thanks
Saroj

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by saroj990** [comment]
Finally got the solutions, We need to use ng-form inside the main form to get this functionality
<form name="anyForm">
  <div class="row marginTop">
                                    <tabset class="container-fluid marginTop">
                                        <tab ng-repeat="otherInjury in otherInjuries" heading="{{otherInjury.other_injury?otherInjury.other_injury:'injury'}}" active=otherInjury.active>
                                            <ng-form name="otherExamInnerForm">
                                                <div ng-controller="tabController" class="marginTop">
                                                    <div class="row">
                                                        <div class="col-lg-2"></div>
                                                        <div class="col-lg-10">
                                                            <input type="text" class="form-control" ng-model="otherInjury.other_injury" readonly>
                                                        </div>
                                                    </div>
                                                    <div class="row marginTop">
                                                        <div class="col-lg-2">Examination</div>
                                                        <div class="col-lg-10">
                                                            <select class="form-control" ng-options=" otherExam.item|separator disable when otherExam.item == '-' for otherExam in otherExamInfo" ng-model="otherInjury.selectedOtherExamInfo" ng-change="selectOtherInjuryExamInfo($index,otherInjury.selectedOtherExamInfo)"></select>
                                                        </div>
                                                    </div>
                                                    <div class="row marginTop">
                                                        <div class="col-lg-2"></div>
                                                        <div class="col-lg-10">
                                                            <textarea class="form-control" rows="5" ng-model="otherInjury.other_examination" name="otherExamination" complete-info-validator></textarea>
                                                            <button class="btn btn-primary btn-xs pull-right" ng-click="clearOtherInfo($index)">Clear</button>
                                                            <span ng-show="otherExamInnerForm.otherExamination.$error.completeInfoValidation">Incomplete info</span>
                                                            <div ng-show="otherExamInnerForm.otherExamination.$error.completeInfoValidator" class="error">Incomplete Information</div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </ng-form>
                                        </tab>
                                    </tabset>
</form>

Hope this may help .
