### ISSUE TITLE
$modal takes command outside of popup

### ISSUE THREAD

**Issue by atul221282** [angular-ui/bootstrap#4417]
When popup is open and nothing is focused and selected pressing backspace triggers the route change 
event. Currently i am using the directive to disable any navigation but I was hoping for something built in with modal object?

my directive code is
var app = angular.module("ControlDirectives", []);
app.directive('disableNavigation', ["$document", function ($document) {
    return {
        restrict: 'AE',
        scope: {//create isolate scope so that locationChangeStart get destroyed for this modal
            //otherwise we will end up same event getting fired twice on two different location
        },
        link: function (scope, element, attr) {
            scope.currentUrl = $document[0].URL;
            scope.$on("$locationChangeStart", locationChange);
            function locationChange(event, next, current) {
                if (next !== scope.currentUrl) {
                    event.preventDefault();
                }
            }
        }
    };
}]);

And within pop html i got form tag decorated with that directive
<ng-form name="formHierarchyItem" class="form-inline" novalidate data-disable-navigation="">
<b>my popup html</b>
</ng-form>

**Comment by ehteshamkafeel** [comment]
Theres nothing built in to `$modal` service as browser's back button or backspace cannot events can not be prevented. you have two options here, one is to use stateful modals, you can find more about this approach going to the link below if you are using `ui router` for the routing.

https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-open-a-dialogmodal-at-a-certain-state

Second approach is to automatically dismiss all modals on state transition. you can accomplish this by adding `$stateChangeStart` event in your app run function.

```javascript
App.run([
  '$rootScope', '$modalStack', 
  function($rootScope, $modalStack) {
    $rootScope.$on('$stateChangeStart', function() {
      var top = $modalStack.getTop();
      if (top) {
        $modalStack.dismiss(top.key);
      }
    });
  }
]);
```

**Comment by atul221282** [comment]
Thanks for you reply and it is really appreciated but that still doesn't solve my problem as I have mentioned that I don't want to close the modal and I am also not using ui router.

**Comment by wesleycho** [comment]
The modal is a standalone component with no knowledge of routing - this is a feature that is ideally in a custom component or service for your application to keep concerns separate.

**Comment by atul221282** [comment]
I agree
