### ISSUE TITLE
Popover in 0.13.4 shows flash of unstyled content

### ISSUE THREAD

**Issue by bikegriffith** [angular-ui/bootstrap#4427]
Regression in 0.13.4 from 0.13.3 generates a FOUC on the popover directive.  It's very apparent on any page that has a slow digest cycle.  Making sure to hide element before the `$timeout` then promptly show works around the issue.

See plunkr to reproduce problem: http://plnkr.co/edit/XKtxNa67aaT2TsS7YcNV?p=preview

angular version: 1.4.5
angular-ui bootstrap version: 0.13.4
browser: latest stable Chrome

Workaround at https://github.com/bikegriffith/bootstrap/commit/af9d18df666a66a7c40c5409f89e7bdab073ef19 (I can pull request it if desired)

**Comment by icfantv** [comment]
I *think* this is fixed in `master`, can you please check?

**Comment by wesleycho** [comment]
This should be fixed in `master` currently, as it was also present with tooltips as well.
