### ISSUE TITLE
AngularJS creating additional scopes on opening modal dialog multiple times

### ISSUE THREAD

**Issue by kwehrle** [angular-ui/bootstrap#443]
I've a simple problem. I'm using a ng-include directive inside a modal.
It's because a want to dynamically change the src for the include (the example however is with fixed src attribute).

 &lt;div class="modal" modal="theModal" close="closeModal()">
    &lt;div ng-include src="'form1.html'"></div>
  &lt;/div>

Every time I open the modal, a new scope is created (I can see it with batarang).
After opening the modal a dozen times, I've many scopes and the application is getting slow.

Is this a bug?

More Information is here:
http://stackoverflow.com/questions/16528634/angularjs-creating-additional-scopes-on-opening-modal-dialog-multiple-times

http://plnkr.co/Mbo9OaKA8MFJptwmI3PN

**Comment by ShindePrasad** [comment]
Hi, I can not able to view solution for this. @pkozlowski-opensource  could you please update the correct answer for topic?
