### ISSUE TITLE
Remove bootstrap from peerDependencies

### ISSUE THREAD

**Issue by alberto** [angular-ui/bootstrap#4430]
`angular-ui-bootstrap`doesn't really depend on `bootstrap` so it shouldn't require it.

In our case, we are using `bootstrap-sass` instead of `bootstrap`.

**Comment by wesleycho** [comment]
This won't take into effect until the next release.

https://github.com/angular-ui/bootstrap-bower/commit/febda42fce40e6692c5186937c5701a2322c083a
