### ISSUE TITLE
accordion-group and ng-show not working in 0.13.4?

### ISSUE THREAD

**Issue by kentor** [angular-ui/bootstrap#4436]
A regression? Seems to have worked in 0.13.3.

http://plnkr.co/edit/zn0nVPrbqWG9tOeZGIA5?p=preview

```html
  <accordion>
    <accordion-group ng-show="false">
      <accordion-heading>
        I can have markup, too! <i class="pull-right glyphicon" ng-class="{'glyphicon-chevron-down': status.open, 'glyphicon-chevron-right': !status.open}"></i>
      </accordion-heading>
      This is just some content to illustrate fancy headings.
    </accordion-group>
  </accordion>
```

The `ng-show` is not applying the `ng-hide` css class.

**Comment by kentor** [comment]
Hmm.. seems to work as expected if ng-animate is removed. But yeah, this worked in 0.13.3 but not 0.13.4.

**Comment by wesleycho** [comment]
This seems to be an Angular issue, not UI Bootstrap: http://plnkr.co/edit/QL4plbOpkaWu9ZAilBao?p=preview - please file it there.

**Comment by kentor** [comment]
You had a syntax error (a missing `'`) in `script.js`, seems to work when it's fixed.
```
template: '<div>' +
      <div ng-transclude></div>' +
    '</div>'
```

**Comment by wesleycho** [comment]
Ah you're right, whoops.

**Comment by ersimont** [comment]
I'm having the same issue.  My workaround is to use `ng-if` for now.

**Comment by karentrevino** [comment]
I'm having the same problem.

**Comment by icfantv** [comment]
@karentrevino, we're aware of the issue and it looks like there's a workaround, albeit a temporary one.  Typically, when there is a non-intrusive workaround like this, issues take a lower priority.  But know that we haven't abandoned this and the issue is still open.  Thanks.

**Comment by poorva29** [comment]
+1

**Comment by icfantv** [comment]
@poorva29, please do not just add `+1` to issues.  It adds no intrinsic value and only clutters up the thread.

**Comment by wesleycho** [comment]
This appears to be a side effect of how transclusion works I think - see [here](http://plnkr.co/edit/FNsxYIhwwyI2VuwJ4keL?p=preview) for a working example with workaround.

I do not believe we can fix this in the library itself - I would generally recommend against using directives that modify the DOM (i.e. ng-class, ng-show, etc.) on directives that use `replace`

**Comment by DurgpalSingh** [comment]
ng-show="false" is not working in uib-heading. how can I fix this
