### ISSUE TITLE
Modal promises clarification

### ISSUE THREAD

**Issue by feus4177** [angular-ui/bootstrap#4441]
It's a little unclear in the documentation when the `rendered` promise gets resolved. Is it after the `open` promise gets resolved? Is it supposed to be after the HTML has been added to the DOM? I'm looking for a promise that resolves once `angular.element('.modal.in')` returns a non-empty array. I thought that was what the rendered promise was for but it doesn't seem to be working that way.

**Comment by BobbieBarker** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md
