### ISSUE TITLE
DropdownMenu directive doesn't when it's evaluated as argument restriction

### ISSUE THREAD

**Issue by ka8725** [angular-ui/bootstrap#4442]
See the [plunker](http://plnkr.co/edit/3AM107KptafYK8oUR7Ww?p=preview).

Pay attention on line 18 in `index.html`. If change the `dropdown-menu` directive to the class the picker is working correctly. But accordingly to the [code](https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L254) it should work for the argument case either.

**Comment by wesleycho** [comment]
This appears to be a bug and needs investigation.

**Comment by wesleycho** [comment]
This should be an easy fix - the reason this occurs is because the `dropdown-menu` class is missing. Once #4514 makes it in, I'll fix this up.
