### ISSUE TITLE
tooltip flashes on top right of window before appearing at intended position

### ISSUE THREAD

**Issue by dmvianna** [angular-ui/bootstrap#4443]
I'm actually working with the popover directive. When I display it, more often than not it flashes on the top left of the screen. Then it appears in the intended position. You might need to click and close repeatedly to notice it in the example below.

It seems like more people noticed that issue (see @cferejohn's comment at #2828 and @pads at #375). However, nobody filed a bug. I can reproduce it in both [Plunker](http://embed.plnkr.co/EQPsTxTegtGR5hu8b7Eg/preview) and [Codepen](http://codepen.io/dmvianna/pen/PPzpPY). My actual code appends a much bigger body to the popover, so the issue is very noticeable.

**Comment by RobJacobs** [comment]
PR #4363 should fix your issue.

**Comment by icfantv** [comment]
Also, if you search the closed issues forum, you'll find at least a half dozen items that refer to this issue.

**Comment by wesleycho** [comment]
This is already fixed and has been reported several times already :) .
