### ISSUE TITLE
dropdown "outsideClick" does not work without dropdown-menu

### ISSUE THREAD

**Issue by virtuacoplenny** [angular-ui/bootstrap#4444]
[Plnkr] (http://plnkr.co/edit/qi2VATdQlqZyxMP0nebG?p=preview)

Since 0.13.1, "outstideClick" is not being respected when using just the dropdown directive. I think the change in behavior was introduced with [this commit] (https://github.com/angular-ui/bootstrap/commit/cc66a0687208b2cf41eecf92a922a6e0f92f2708). To get "outsideClick" to work, I now have to use dropdown with dropdown-menu. Is this intentional?

**Comment by wesleycho** [comment]
This was intentional due to a bug where `outsideClick` would cause the dropdown menu to close incorrectly in some situations.

**Comment by wesleycho** [comment]
One solution could be to create a custom directive that requires the dropdown directive controller and to register the element you wish to target as the dropdownMenu element.

Closing as a support issue for now, unless given information that requires moving in a particular direction in the library.
