### ISSUE TITLE
ui.bootstrap.modal gives ng-model undefined on HTML5 validation

### ISSUE THREAD

**Issue by rajputvai** [angular-ui/bootstrap#4447]
**Plunker**
http://plnkr.co/edit/Jt4VTCMNL2UBsGGnvfeb?p=preview

Please follow below steps to produce this error.
1. Click on 'Open Me!' button. (This will open modal.)
2. Click on 'Ok' button. (this will alert '$scope.data.name is : ')
3. Follow Step 1. and give some input to input text box
4. Click on 'Ok' button. (this will alert '$scope.data.name is : <inputed_string>')
5. Follow Step 1. and give some input to input text box, and remove the string from input text box. empty input text box.
6. Click on 'Ok' button. (this will alert '$scope.data.name is : undefined') (instead of giving empty string)

**Modal html**
```HTML
<script type="text/ng-template" id="myModalContent.html">
    <div class="modal-header">
        <h3 class="modal-title">I'm a modal!</h3>
    </div>
    <div class="modal-body">
      <input type="text" ng-model="data.name" required maxlength="6" minlength="6">
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" type="button" ng-click="ok()">OK</button>
        <button class="btn btn-warning" type="button" ng-click="cancel()">Cancel</button>
    </div>
</script>
``` 
ng-model with input type as text and html5 validation.

**Demo controller**
```Javascript
angular.module('ui.bootstrap.demo', ['ngAnimate', 'ui.bootstrap']);
angular.module('ui.bootstrap.demo').controller('ModalDemoCtrl', function ($scope, $modal, $log) {
  $scope.open = function () {
    var modalInstance = $modal.open({
      templateUrl: 'myModalContent.html',
      controller: 'ModalInstanceCtrl',
    });
  };

});
```
Hope nothing to explain.

**ui.bootstrap.modal controller**
```Javascript
angular.module('ui.bootstrap.demo').controller('ModalInstanceCtrl', function ($scope, $modalInstance) {

  $scope.data = { "name" : "" };

  $scope.ok = function () {
    alert("$scope.data.name is : "+ $scope.data.name);
    $modalInstance.close();
  };

  $scope.cancel = function () {
    $modalInstance.dismiss('cancel');
  };
});
```
define $scope.data.name as blank string.

**Comment by pkozlowski-opensource** [comment]
It has nothing to do with modal. The way validation works in AngularJS is that model value is undefined till it passes validation. You'e got rather strict validation rules. Try to put `123456` in the input and see that it "works".

**Comment by rajputvai** [comment]
Yes, Thanks for correcting me.
