### ISSUE TITLE
Error with multiple classes in datepicker

### ISSUE THREAD

**Issue by brujo696** [angular-ui/bootstrap#4450]
I have this code
http://plnkr.co/edit/oyzleZeoWfdGLeIzLepq?p=preview
and I want to show the actual week and the week of the selected day, the console log return correct data about the selected week, but the calendar don't change the classes of these days.

**Comment by brujo696** [comment]
is related with #4227 but still without a great solution

**Comment by wesleycho** [comment]
Closing as a duplicate issue
