### ISSUE TITLE
Modal should not close on backdrop click

### ISSUE THREAD

**Issue by Jeevanandanj** [angular-ui/bootstrap#4453]
Now the modal is closing automatically when click on backdrop. Can we restrict like modal should not close on backdrop click?

**Comment by pkozlowski-opensource** [comment]
From http://angular-ui.github.io/bootstrap/#/modal:

> backdrop - controls presence of a backdrop. Allowed values: true (default), false (no backdrop), 'static' - backdrop is present but modal window is not closed when clicking outside of the modal window.

https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by Jeevanandanj** [comment]
But when I use backdrop:false, then backdrop will be removed from the body. I don't want the backdrop to be removed. But I want the backdrop, but when click on the backdrop, modal should not be closed

**Comment by pkozlowski-opensource** [comment]
> 'static' - backdrop is present but modal window is not closed when clicking outside of the modal window

I wonder what is not clear in this doc....

**Comment by Jeevanandanj** [comment]
Oh sorry. I've seen.

**Comment by Jeevanandanj** [comment]
Thanks
