### ISSUE TITLE
Tooltip not fading in

### ISSUE THREAD

**Issue by ValerioBulla** [angular-ui/bootstrap#4454]
Tooltip doesn't seem to fade in. Fade out animation works just fine.
Just compiled from `master`, using AngularJS 1.4.x and Bootstrap 3.3.1

[Plunker with the issue](http://plnkr.co/edit/G09Evg?p=preview)

**Comment by wesleycho** [comment]
This works, you need to add ngAnimate though - see [here](http://plnkr.co/edit/JVMX21?p=preview)
