### ISSUE TITLE
Datepicker with asynchronous call.

### ISSUE THREAD

**Issue by CrackerakiUA** [angular-ui/bootstrap#4456]
I have option in datepicker which is in the database. When i put $scope.options inside that asynchronous call, datepicker just ignore those options and use old one or default if i don't add any option before. I can share code if that help's

**Comment by wesleycho** [comment]
Can you explain more clearly? Is the wish to fetch the datepicker option config remotely from the server and populate the datepicker? If this is the case, one simple way you can accomplish this now is to use ng-if to hide the template until the options come from the server, then toggle the ng-if condition to truthy.

**Comment by CrackerakiUA** [comment]
hmmm, yes, ng-if should work. Thanks
