### ISSUE TITLE
Tooltip in 13.4 bouncing positions, fine in 13.3

### ISSUE THREAD

**Issue by jfarago** [angular-ui/bootstrap#4457]
[Plunk](http://plnkr.co/edit/UiTfhk?p=preview)

Tooltip gets displayed at the very left and quickly adjusts. On my app(not the plunker) this is causing the scroll bar to briefly show.

**Comment by wesleycho** [comment]
This is actually currently fixed in `master`, as can be seen [here](http://plnkr.co/edit/Wzi3Zj?p=preview)
