### ISSUE TITLE
How to Render as HTML in popover title ?

### ISSUE THREAD

**Issue by ramprakash-ravi** [angular-ui/bootstrap#4462]
The content added to renders  popover-title is displayed as it is in the web page.
Eg: popover-title="This is title <span>X</span>"
is displaying as This is title <span>X</span>.

Is there a way to render as HTML in title ?

**Comment by icfantv** [comment]
In the future, please do not use the issues forum for support related requests.  See [this](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem) for instructions on how to get help.

The answer is yes, it is possible.  You need to use a template.  You can do this via a directive.
