### ISSUE TITLE
popover keeps on flashing in Safari

### ISSUE THREAD

**Issue by rhitesh** [angular-ui/bootstrap#4468]
If the window size is small or the popover text is big, the popover seems to flash in its own place instead of displaying where it actually should. It goes to the right place if we click. I have uploaded a video for reference. I tried the same thing with tooltip and it works well but popover doesn't.

Video Url: http://www.screencast.com/t/fcKuKgDrS2

OS: OS X Yosemite
Version 10.10.4

Browser: Safari Version 8.0.7 (10600.7.12)
Works well for chrome

Works almost as expected for firefox but there is some lag.
Version 33.1

**Comment by wesleycho** [comment]
This should be addressed in `master` - let us know with a proper reproduction in Plunker if this is not the case.
