### ISSUE TITLE
Problem with Datepicker in IE

### ISSUE THREAD

**Issue by sgrady** [angular-ui/bootstrap#4469]
On your example , open the datepicker popup (http://angular-ui.github.io/bootstrap/), then click anywhere else outside of the popup - javascript errors start flying and the picker does not automatically close. (SCRIPT438: Object doesn't support property or method 'contains'
File: ui-bootstrap-tpls-0.13.4.min.js, Line: 8, Column: 27435) - FYI - this is NOT present in bootstrap 0.12.1

**Comment by wesleycho** [comment]
This has actually been fixed in `master`

**Comment by sgrady** [comment]
When do you anticipate a release of that fix?

**Comment by icfantv** [comment]
Given the changes we want to put (and are putting) into 0.14.0 it could be a while.  If you're comfortable doing so, you could always check out `master` and do a snapshot build.

**Comment by Craig1f** [comment]
Can you give us a short-term fix on this? If I delete " || popupEl[0].contains(event.target)" from the dev version and "||y[0].contains(a.target)" from the min.js, will this break other things, or is that a safe change?

**Comment by wesleycho** [comment]
That is essentially the fix in `master`.

We are likely going to release 0.14.0 tomorrow FWIW.
