### ISSUE TITLE
Clicking space on a checkbox button

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#4474]
There is code to toggle a checkbutton with space. If you go to the demo and do it, it will toggle twice. I haven't checked it yet so I open this issue to not forget.

**Comment by wesleycho** [comment]
I implemented it for accessibility reasons originally.

**Comment by Foxandxss** [comment]
Yes, but I don't think it should trigger the toggling twice, right?

**Comment by wesleycho** [comment]
No, that's a bug then. I just mentioned it for context.

**Comment by Foxandxss** [comment]
Wes, I checked and basically the PR you made to add accessibility is not needed. It works without it. I am not completely sure if it works nice with screenreaders and stuff, but a button is always clickable with space.

The thing is, I would like to leave the test, but the keypress event won't work. I am not sure if under the hood the space counts as a click instead of keypress.

Thoughts?

**Comment by wesleycho** [comment]
Hm, maybe I was mistaken in my attempt to fix it.

That sounds good - as long as we have a test around it and this is fixed, I'm all for it.

**Comment by Foxandxss** [comment]
Yeah, but test how. I have no idea because I don't know how does this work behind the scenes. Is the space on a button considered a click? If so, how to test that?

**Comment by wesleycho** [comment]
It just needs to behave like a click and toggle the button model

**Comment by Foxandxss** [comment]
And it does my friend and it does, but no idea how to test that in a special way.

**Comment by wesleycho** [comment]
The pre-existing test may be fine
