### ISSUE TITLE
Popover flashing issue on version 0.13.4

### ISSUE THREAD

**Issue by MarkoCen** [angular-ui/bootstrap#4477]
Hi,

Please check the plunker for the issue:

http://plnkr.co/edit/YgyaSyrAbvUzIEGhoAtd?p=preview

There a flash effect before popover showed on correct position, I guess it appended to body before setting its position?

UPDATE: this issue may not happened each time, but in most time, you can see a flash on top-left corner of document body

**Comment by icfantv** [comment]
This issue has been fixed in `master`.  In the future, please make an effort to search existing issues, both open and closed, before creating a new issue as this bug in particular has been reported literally dozens of times.
