### ISSUE TITLE
Pagination component text bindings are not updated

### ISSUE THREAD

**Issue by maximnaidenov** [angular-ui/bootstrap#4481]
Hi,

I am using pagination component and I want to i18n my app with angular-translate. So I want to set 
the values of previous-text and next-text attributes with interpolation that uses the 'translate' filter like this: previous-text="{{'message.key.previous'|translate}}" 
This will work fine if I provide the translated texts synchronously with the application start. But in practice my translated text are stored in json's and loaded on demand. So due to the usage of one-time expression for binding them in the default template the expressions are not updated and the message keys are shown.
Please have a look of the problem here:
http://plnkr.co/aDjreaFoRN2CZh39vVkd

**Comment by wesleycho** [comment]
This sounds like a potentially risky use IMO - if it is fetched asynchronously, you have a possibility that the text will change dynamically or with sudden text population.

One way to avoid this on user side would be to use a custom template that removes the one-time binding, but know that you will suffer a performance hit on your app. I am not sure there is anything else we can do on the library's side given the situation.

**Comment by maximnaidenov** [comment]
Hi,

Text changing asynchronously is actually a (common) feature with localization - user could change the language after the page is loaded and rendered. 
The resolution is quite simple - just remove one-time "::" prefix in the bindings in the default templates.
Of course, I could supply custom template but in my opinion this is an important feature to have a fully functional localization support in pagination component.

**Comment by pkozlowski-opensource** [comment]
> but in my opinion this is an important feature to have a fully functional localization support in pagination component

It is not about i18n per see but rather about ability to dynamically swap a locale without a reloading a page. While I understand that it is an attractive feature it comes with the performance penalty. So we need to make a decision for this project: either we support dynamic locale swapping and penalize all users that don't need it. 

IMO dynamic locale swapping sounds great but comes with so many practical complications / perf hits that we shouldn't change impls in the repo. Especially that users can supply their own templates so it is not like we are preventing this use-case.

Unfortunately we can't have both super-dynamic and super-performant components so we need to draw a line somewhere.

**Comment by wesleycho** [comment]
Closing, as one can work around this through custom templates & is a legitimate case to use a custom template instead as the default behavior should be performance minded with the ability to swap with custom templates.

**Comment by leocaseiro** [comment]
Here there's a solution using a custom template:
http://plnkr.co/edit/kuoehp0W8jSKMklgNXzE?p=preview
