### ISSUE TITLE
Datepicker clears date when locale have been changed

### ISSUE THREAD

**Issue by andertun** [angular-ui/bootstrap#4485]
In my application the user can change language and locale at runtime. If locale is changed, the datepicker-popup clears the date when the user changes it.

Is this a bug, or am I doing this wrong?

See this plunker: http://plnkr.co/edit/e02zpQC5ROlQsW8pSAZZ?p=preview

**Comment by andertun** [comment]
I found [this issue](https://github.com/angular-ui/bootstrap/pull/4425) after I submitted. Maybe the same problem - which has been fixed?

**Comment by wesleycho** [comment]
I believe that should fix this issue - I am not seeing it [here](http://plnkr.co/edit/vi6EVvJkeXJPXbf4hIB5?p=preview) anymore.
