### ISSUE TITLE
Tooltip is not closing on updating "tooltip-is-open" to false 

### ISSUE THREAD

**Issue by akhare22sandeep** [angular-ui/bootstrap#4486]
Hi, 
I am not able to close the tooltip is there something i am doing wrong ? i don't see any example/documentation for using the attribute tooltip-is-open. Below is my html 
```
                <a id="comp-info" tooltip-template="'{{compResult.DynamicContent}}.html'"  
ng-click="showTooltip1()"  tooltip-trigger="none" tooltip-is-open="showCompTooltip"  
tooltip-placement="right" tooltip-class="customClass">
                  <image src="/images/info_icon.png"></image>
                </a>
```	
below is Tooltip content and it has close button to close it 
```
 <a id="crossCheck" class="btn-cross2"><span ng-click="cancel()">x</span></a>
  <div class="heading">
    DyamicContent
  </div>
 
```	
My controller has below 	methods

```
 $scope.showTooltip1 = function()
 {
   if($scope.showCompTooltip === true)
   {
     $scope.showCompTooltip = false;
   }
   else {
     $scope.showCompTooltip = true;
   }
 },

$scope.cancel = function()
{
    setTimeout(function() {
    $scope.showCompTooltip = false;

}, 100);



}

```

Its been long time i am scratching my head now. Please advise

**Comment by RobJacobs** [comment]
We need a plunk to help diagnose he problem further.

**Comment by icfantv** [comment]
Please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

[Here](http://plnkr.co/edit/7X5mjm0Gbf7nN8zMpUbU) is a working example for you.  I would check the following:
* variable name spelling
* proper tooltip template injection
* the chrome console to make sure you don't have errors

Finally, this may be just your example code, but there is almost __NEVER__ a reason to do `if (foo === true)`.  You can replace your entire `showTooltip()` function with just `ng-click="showCompTooltip = !showCompTooltip"` but know that this means you're polluting your tests with `ng-click` behavior - and you __ARE__ functional testing your code, right? :-)

**Comment by VenkatRamReddyK** [comment]
Easiest way of working with uib-popover with mouse event on the pop-over

https://plnkr.co/edit/9oMYadXPNJcRPrig71iF?p=preview
