### ISSUE TITLE
modal result.rendered function doesn't appear to exist

### ISSUE THREAD

**Issue by mikecantor** [angular-ui/bootstrap#4490]
I am using ui-bootstrap modal for angular.  When I can $modal.open(...) the resulting object does not have a "rendered" property where I can provide a callback as advertised in the docs.  The properties, opened, result, closed and dismissed are all their and working properly, but no "rendered".

Am I missing something or are the docs incorrect?

**Comment by mikecantor** [comment]
should mention I am using ui-bootstrap-tpls-0.13.4.min

**Comment by icfantv** [comment]
@mikecantor please do not use the issues forum for support requests.  Rather, please follow the instructions outlined [here](https://github.com/angular-ui/bootstrap#need-help).

There is a bug in your code.  This feature works just fine as per the demo [here](https://angular-ui.github.io/bootstrap/#/modal).  Add the following to the `$scope.open` function:

```
    modalInstance.rendered.then(function() {
      $log.info('calling rendered promise');
    });
```

**Comment by vinitsharma87** [comment]
Hi,
I implemented angular-ui modal dialog, and I am also facing a similar kind of problem. When I alert for the JSON.stringify contents of the modal instance, I find only two methods inside it as `result()` and `opened()`. Why does it doesn't shows for rendered method ? I am trying to implement something when the whole modal dialog along with the html contents is rendered, but the modal instance doesn't has the rendered method. What could be the reason for this ? Do I need to add for any property while calling the $modal.open() method ?

**Comment by brayann** [comment]
Same thing happens for me.

**Comment by brayann** [comment]
It might be because of the version we are using, which is `"angular-bootstrap": "~0.11.0",`
On which version was the rendered function added? Will I get any incompatibilites I should know of? Thanks!

**Comment by brayann** [comment]
Nevermind found it, for future reference it's ~~~0.13.0~~~. Works now :)

**Comment by icfantv** [comment]
@brayann, the docs for older versions are available via the dropdown in the header on our demo site.  Thanks.

**Comment by brayann** [comment]
@icfantv thanks, didn't see that :+1:
