### ISSUE TITLE
min attribute of timepicker does not work.

### ISSUE THREAD

**Issue by prasadh13** [angular-ui/bootstrap#4491]
I want past time to be disabled. What I mean is, I can only select current time or future time. The min attribute of timepicker doesn't seem to work

**Comment by wesleycho** [comment]
Can you post a [Plunker](http://plnkr.co/edit/1C3OPzJv5d8pkXlnpO4E?p=preview) with a reproduction?

**Comment by robertppn** [comment]
Plunker: http://plnkr.co/edit/7DDDPTIhnuXK9XGMFDiF?p=preview

**Comment by turakvlad** [comment]
The same issue. How can I set min time in timepicker?

**Comment by BobbieBarker** [comment]
@robertppn I deleted your comment your plunker links do a demo of the datepicker. Original issue opened was for timepicker. If you have an issue you would like to raise with the datepicker regarding your plunkr you're more than welcome to do so. 

@turakvlad This isn't the appropriate place to ask questions regarding how to use the library. I'd refer you to [this](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug)
[this plunk](http://plnkr.co/edit/oZQWsY1R0tjVDDqx1eb3?p=preview)
Demonstrates the min attribute being set and used propperly. I'm closing this issue and would gladly reopen it if OP produces a plunkr demonstrating a deficiency.
