### ISSUE TITLE
Using `popover-is-open` to close popovers

### ISSUE THREAD

**Issue by MattDionis** [angular-ui/bootstrap#4494]
I am attempting to close my popovers when clicking anywhere outside of them by using the new `popover-is-open` attribute. My current HTML and relevant controller code looks like so:

```
<div
  ng-click="level.openTogglePopover()"
  popover-template="level.changeLevelTemplate"
  popover-trigger="none"
  popover-placement="right"
  popover-is-open="level.togglePopover">
  <button class="btn btn-default btn-xs" type="button">
    <span class="glyphicon glyphicon-sort"></span>
  </button>
</div>
```

```
vm.togglePopover = false;

vm.openTogglePopover = function() {
  vm.togglePopover = !vm.togglePopover;
};
```

This works great for toggling popovers on/off by clicking on them. How is the `popover-is-open` attribute used to close popovers by clicking outside of them?

**Comment by icfantv** [comment]
Please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

The answer to #4486 may be of some help.

**Comment by chrisjlee** [comment]
Is there documentation regarding this new attribute yet? Seems like this is a common issue. I would happily provide a PR if needed.

**Comment by icfantv** [comment]
@chrisjlee, doesn't look like we have a working example in our docs yet for either tooltips or popovers.  Please feel free to get with @Foxandxss to discuss the docs (and how to create a good example) as he's currently in the process of a doc sweep for the 1.0 release.  I think there may also be an issue tracking the doc sweep...

**Comment by Foxandxss** [comment]
Let me add this issue on my list of things to update with the doc.

**Comment by chrisjlee** [comment]
Thank you so much, @icfantv

**Comment by VenkatRamReddyK** [comment]
Look at the plunker for the easiest solution using uib-popover and mouse events. 

https://plnkr.co/edit/9oMYadXPNJcRPrig71iF?p=preview
