### ISSUE TITLE
unable to format the input field when using ui.bootstrap.typeahead

### ISSUE THREAD

**Issue by manichandra** [angular-ui/bootstrap#4499]
I tried to format the phone number we typed ($modal) in the input field after selection or after typing certain characters in case of unmatched items(adding new phone number ) . but i cound't find a way . can anyone help me with this . 
basically i am trying to select a phone number if match is found or add a new one if no match is found . 
I am able to format the matching items in drop-down but not the input field itself . i trind to format the input field after "onblur" event . 

      <h4>Phone numbers</h4>
       <pre>Model: {{selectedPhone | json}}</pre>
      <input   type="text" ng-model="selectedPhone" typeahead="phone as phone.number for phone in  phoneList | filter:{number:$viewValue} | limitTo:10" class="form-control"
           typeahead-template-url="customTemplatePhone.html" 
         typeahead-input-formatter = ""
         typeahead-on-select= "onSelect($item, $model, $label)">
     
plunker :
http://plnkr.co/edit/BJxauIKMYmIqM8cpWqol?p=preview

one more thing how can i show the drop-down on focus of the input field , without typing anything

**Comment by icfantv** [comment]
Please do not use the issues forum for support requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

**Comment by manichandra** [comment]
Thanks @icfantv .
