### ISSUE TITLE
Issues with min-mode and datepicker mode in angularui bootrstrap datepicker-popup when made custom

### ISSUE THREAD

**Issue by jigyasup** [angular-ui/bootstrap#4506]
I made a custom datepicker using angularui bootstrap datepicker-popup directive . There were some issues with min-modes and datepicker mode in custom directive . The problem is that if i provide min-mode through datepicker-options parameter in index.html it works but the same scenario in directive template isn't working . If somebody has idea regarding min-mode in custom directive using angularui bootstrap please help . here is my plunkr http://plnkr.co/edit/FDigEjyMYm5SVYnQyZGp. Here i the same scenario in index.html

<input datepicker-popup="MM/yyyy" ng-model="dt" datepicker-mode="'month'" datepicker-options='options' is-open="opened" ng-click="open()"/

and datepicker-template.html

  <input  class="form-control" id="{{id}}" datepicker-popup={{calendarProperties.format}} datepicker-mode='modes' datepicker-options='options' ng-dblclick="open($event)" ng-model="ngModel" n is-open="calendarProperties.opened"  />

The default directive in index.html is working fine but in custom directive min-mode isn't working . Have a look and suggest some idea. I kind of stuck there.

**Comment by icfantv** [comment]
Please do not use the issues forum for support requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) for how to receive assistance.

**Comment by jigyasup** [comment]
sorry for this .
