### ISSUE TITLE
typeahead does not work on IE 11 browser.

### ISSUE THREAD

**Issue by prakashagarwallabrocade** [angular-ui/bootstrap#4513]
i am having issues with executing the bootstrap typeahead samples on IE 11. works fine in chrome.

**Comment by wesleycho** [comment]
Can you explain what issues? I did not see anything out of the ordinary on IE11, so this needs a reproduction & more info.

**Comment by prakashagarwallabrocade** [comment]
dont know yesterday i was getting no result found in IE, today its working.


- Prakash

**Comment by pkozlowski-opensource** [comment]
OK, I'm going to close this one then. @prakashagarwallabrocade feel free to re-open when you've got a reproduce scenario.

**Comment by BhuvaneshwaranK** [comment]
I'm getting same issue today. Bootstrap 3 Typeahead is working fine in chrome. But not working in IE 11. My dropdown list has 1000's of values. Can anyone help me in this ?
