### ISSUE TITLE
Fix heavy dependence on the DOM for carousel transition information

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#4516]
See discussion in #4325 - this exposes a heavy dependence on the DOM structure, which defies the custom template possibilities.

This needs to be untangled in a clean way to avoid the heavy dependence and part of the limitations of `.animation` - might need to store all the slides for a carousel in a model using `$$multiMap`.

**Comment by chrisirhc** [comment]
The NO_TRANSITION hack was there because there was no way to use $animate.enabled as a getter (the getter was added in Angular 1.4). Now that that's no longer true, we can remove the usage of .data . It can instead use $animate.enabled on itself, as $animate.enabled gets inherited by children.

**Comment by wesleycho** [comment]
Thanks for that - that is exactly the info I needed!
