### ISSUE TITLE
Popover-html result in an unsafe content error

### ISSUE THREAD

**Issue by c00** [angular-ui/bootstrap#4522]
Using `popover-html` on the popover directive results in an error: Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context. 
Example in this [Plunkr] (http://plnkr.co/edit/hBqNnviLRHIKTWaaUTSa?p=preview). Watch the console.

**Comment by pkozlowski-opensource** [comment]
@c00 if you go to http://angular-ui.github.io/bootstrap/#/popover and check the docs you will see:
> The user is responsible for ensuring the content is safe to put into the DOM!

You need to $sanitize the HTML string before passing it to the popover.
