### ISSUE TITLE
$tooltip deprecation notice still firing

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#4537]
Hey @wesleycho, check this plunker: http://plnkr.co/edit/d03g3YRgEq40oKvCTXKC?p=preview

Somehow it is still using the old `$tooltip` service and I don't know why. Because that, you get a deprecation message.

**Comment by wesleycho** [comment]
It looks like the culprit is the `tooltip` directive - somehow the $tooltip service is being run there, even if the directive is not being used. Not quite sure how to stop this though.

**Comment by Foxandxss** [comment]
Don't worry. Will check again later.

**Comment by wesleycho** [comment]
Closing as fixed.
