### ISSUE TITLE
Popover with template url not working with angularjs 1.2.23, ui-bootstrap-tpls-0.12.1.js and bootstrap 3.2.0

### ISSUE THREAD

**Issue by sivaecekrr** [angular-ui/bootstrap#4539]
Popover with template url not working with angularjs 1.2.23, ui-bootstrap-tpls-0.12.1.js and bootstrap 3.2.0.

Can anyone please suggest. Thanks in advance

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by sivaecekrr** [comment]
Please find the sample plunker.
http://plnkr.co/edit/1rO7m6GMAAdYAAlktaIe?p=preview

**Comment by pkozlowski-opensource** [comment]
@sivaecekrr support for `popover-template` was only added in 0.13.0 - check the changelog: https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#0130-2015-05-02
