### ISSUE TITLE
tooltip customer trigger not working.

### ISSUE THREAD

**Issue by piupiupiu** [angular-ui/bootstrap#4540]
Hello.

I'm trying to show/hide the tooltip dynamically. 
In order to do that I set up custom trigger 

    $tooltipProvider.setTriggers({
        'show':'hide'
    });

And created a custom directive which triggers 'show' event.

```javascript
app.directive('dynamicTooltip', ['$timeout', function($timeout) {
  return {
    restrict: 'A',
    link: function($scope, $element, $attrs) {
      $timeout(function() {
        $element.trigger('show');
      },1000);
    }
  };
}]);
```
However, nothing happens. No errors or something.

Here is a [plunk](http://plnkr.co/edit/zmza9NeqHcE9apsPxSGi?p=preview)

I read the documentation and lots of SO posts thoroughly, but cannot figure it out.
Am I doing something wrong or is it a bug? 

Note: I have already tried `tooltip-is-open` attribute and it did not work for me. I have the latest 0.13.4 version.

**Comment by icfantv** [comment]
@piupiupiu, please do not use the issues forum for support requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

There are a ridiculous number of things wrong with your plunker:
* You are including both the minified and non-minified version of the Bootstrap CSS file.
* You are including both the minified and non-minified version of Bootstrap's JS file.
* Bootstrap's JS file **REQUIRES** jQuery - had you looked at the error console in your browser you would have seen this.
* Angular UI Bootstrap's only dependencies are Angular and Bootstrap CSS, thus you don't even need (and should not be including) Bootstrap's JS file.
* You are using Angular 1.2.28 and Angular UI Bootstrap **REQUIRES** 1.3.x or higher.
* You are using Angular UI Bootstrap 0.13.3 and not 0.13.4 as you state above.
* `tooltip-is-open` was added in the 0.13.4 release and is not available in 0.13.3 so your statement above is also incorrect.
