### ISSUE TITLE
Tooltip positionning is completly broken

### ISSUE THREAD

**Issue by Masadow** [angular-ui/bootstrap#4543]
Hi guys, the tooltip has been broken by recent changes as you can see here

http://plnkr.co/edit/EV69LOIbqJQ87RxAgLqW?p=preview

It appears for a few time at a wrong position and then position itself correctly.

I assume it has relation with some refactor made on positionTooltip recently. @RobJacobs and @dabos-GFI might be interested in this issue since I think it is directly related to #4311.

I don't have the time to investigate but if someone can show a workaround, I would be glad !

**Comment by RobJacobs** [comment]
This [commit](https://github.com/angular-ui/bootstrap/commit/81a38d72613d82bb4d8b5ab44e3bde704a59b056) should address the positioning issue.

**Comment by Masadow** [comment]
Thanks @RobJacobs any date in mind for the next release which will include that fix ?

I guess the only workaround I have so far is building from the source to get it working ?

**Comment by icfantv** [comment]
@Masadow, yes, that's the current way to get the latest.  We're talking about trying to get a release out this week, but it may get pushed to next week.

Also, in the future, please do a search of both open and closed issues to prevent duplicates.  This issue has been reported literally dozens of times.

**Comment by Masadow** [comment]
Sure, I'm sorry Adam, I only checked opened issues. Thanks for letting me
know about the next release. Good luck guys



Jimmy Delas
Twitter <https://twitter.com/masadowbdx>
Linkedin <http://www.linkedin.com/profile/view?id=154981683>
GitHub <https://github.com/Masadow>
