### ISSUE TITLE
How to install the typings of this package

### ISSUE THREAD

**Issue by talor1981** [angular-ui/bootstrap#4544]
tsd install angular-bootstrap --save
return zero results

Thanks

**Comment by icfantv** [comment]
@talor1981, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

I believe what you're looking for is [this](https://github.com/borisyankov/DefinitelyTyped/tree/master/angular-ui-bootstrap).  Please note that that is not our repository nor do we manage/maintain it.
