### ISSUE TITLE
Why doesn't dismiss-on-timeout work for the alert directive after an ngClick?

### ISSUE THREAD

**Issue by adamzerner** [angular-ui/bootstrap#4545]
http://stackoverflow.com/questions/32982806/why-doesnt-dismiss-on-timeout-work-for-ui-bootstraps-alert-directive-after-an

**Comment by icfantv** [comment]
@adamzerner, please do not use the issues forum for support related requests.  You followed the getting help instructions, mostly.  Now you need to wait patiently for someone to have time to help.  Most of us OSS developers have full-time jobs outside our OSS project(s) and do the OSS part in their free time.

**Comment by adamzerner** [comment]
I thought there was a decent chance that it was a bug in the source code, but sorry if I violated the conventions.
