### ISSUE TITLE
custom-class not geting applied for Datepicker in year mode.

### ISSUE THREAD

**Issue by Sheeryada** [angular-ui/bootstrap#4546]
I tried to pass custom class for datepicker. I tried to pass custom class when datepicker is in year mode and it is not applying it. However the same works fine when datepicker is in day and month mode.

Please confirm me if it is a bug?

**Comment by icfantv** [comment]
@Sheeryada, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

**Comment by Sheeryada** [comment]
Hi @icfantv thanks for your reply. I feel this is a bug, 

Here is the plunker http://plnkr.co/edit/qvWGqcyS5GYpOuffOs7k?p=preview

Please see no class getting added when datepicker is in year mode. I inspected the element and see no custom-classes getting added when in year mode.

Do you agree if this is a bug? or please let me know if I am missing anything?

here is the screenshot it appears as ,
![image](https://cloud.githubusercontent.com/assets/13951485/10380822/7a286cf0-6dd3-11e5-96a0-09296245104b.png)
![image](https://cloud.githubusercontent.com/assets/13951485/10380815/72aa9048-6dd3-11e5-8d4f-205a4ebb3991.png)
![image](https://cloud.githubusercontent.com/assets/13951485/10380799/5f6109e0-6dd3-11e5-958f-d35f39cd10ed.png)

**Comment by icfantv** [comment]
Yep.  It's a bug.  The template for `year.html` is missing `ng-class="::dt.customClass"` on the `<td>` wrapping the `<button>`.

**Comment by Sheeryada** [comment]
@icfantv thanks for your confirmation and for reopening this issue.

**Comment by icfantv** [comment]
You're welcome.  And thanks for following the instructions for how to properly submit a bug report.  As most of us have day jobs, it's quite difficult for us to also do that and create working plunkers that reproduce the issue so we rely heavily on you end-users to prove it's an actual issue before we can act.  I should have posted the link to the bug reporting instructions so that's on me.  My bad.

**Comment by Sheeryada** [comment]
No worries.. Thanks...

**Comment by icfantv** [comment]
@Sheeryada, we released 0.14.0 last night and this fix is contained in that release so if you upgrade to the latest you will have this fix.  Please be sure to look at the `CHANGELOG.md` to go through the changes.

**Comment by Sheeryada** [comment]
@icfantv Thank you for the update.
