### ISSUE TITLE
ng-click in <tab> do not work

### ISSUE THREAD

**Issue by przemoli** [angular-ui/bootstrap#4548]
Can't understand why ng-click do not work when put in <tab> tag.

```html
<tabset class="nav-tabs-custom">
        <tab ng-repeat="tab in tabs" active="tab.active" disable="tab.disabled" heading="[[ tab.name ]]" ng-click="alert('hi');">
            <div cms-controller="tab.controller" ng-include="tab.templateUrl"></div>
        </tab>
 </tabset>
```

Changing that *alert* to *$emit* would give me cheap way to notify controller that tab was selected. However ng-click do not work. No alert is shown.

Above code will be translated to:
```html
<li class="ng-isolate-scope active" ng-repeat="tab in tabs" active="tab.active" disable="tab.disabled" heading="TabName" ng-click="alert('hi');" ng-class="{active: active, disabled: disabled}">
  <a class="ng-binding" href="" ng-click="select()" tab-heading-transclude="">TabName</a>
</li>
```

**Comment by icfantv** [comment]
@przemoli, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

I suspect you are running into [this issue](https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive).  But I can't be certain without seeing more of your code.

**Comment by przemoli** [comment]
Why is it related request? Why would "selected" not work when its given pure js? Is angular-bootstrap expecting there only functions from scope or something?

**Comment by icfantv** [comment]
You should be using the `select` attribute on the `tab` element and not `ng-click`.  See [the documentation](http://angular-ui.github.io/bootstrap/#/tabs) for proper use and examples.
