### ISSUE TITLE
Modal backdrop doesn't appear

### ISSUE THREAD

**Issue by moriarais** [angular-ui/bootstrap#4549]
When I am trying to open multiple modals, one on the another, the backdrop doesn't appear after the last one is open. The situation as it seems is that the backdrop is appearing before the first modal that was opened. What could be the cause for this issue?

**Comment by icfantv** [comment]
@moriarais, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

**Comment by moriarais** [comment]
Sorry!!! I haven't notice that.

2015-10-08 21:16 GMT+03:00 Adam Gordon <notifications@github.com>:
