### ISSUE TITLE
Datepicker - show two consecutive month side by side

### ISSUE THREAD

**Issue by dahlbergsi** [angular-ui/bootstrap#4551]
I want to show two consecutive months side by side. I want to have one input box, when clicking on the input box two calendars of two different months should popup. Like the datepicker for jquery numberOfMonths option.

**Comment by icfantv** [comment]
@dahlbergsi, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).
