### ISSUE TITLE
Carousel with multiple item with indicators 

### ISSUE THREAD

**Issue by rajeesab** [angular-ui/bootstrap#4553]
Could you please help me on this.
I am trying to create carousel with multiple items display in single slide. I am struck in displaying multiple active indicators.
For example :loading 50 images and I'm displaying 4 images in one slide  with four gray color indicator and 46 some other color. But I can click any of them..

**Comment by icfantv** [comment]
@rajeesab, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).
