### ISSUE TITLE
on tooltip hover it re-creates items in ng-repeat loop

### ISSUE THREAD

**Issue by jschuler** [angular-ui/bootstrap#4562]
It's causing a performance hit. Is it mean to happen?
http://plnkr.co/edit/LHC16dJUeMn33XKBoOXC?p=preview

Thanks

**Comment by icfantv** [comment]
@jschuler, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, your plunker and limited comments make it quite difficult to understand exactly what you're experiencing.

**Comment by wesleycho** [comment]
Well, if it is a performance regression, it is a problem - however, more detailed information would be much appreciated.

**Comment by jschuler** [comment]
Sorry, here's more info:

When you open the debugging console, you can see that every time you hover over a link to display its tooltip that it loops through the ng-repeat items. This is not scalable and seems like a bug.
I have edited the plunker to add many items and the performance hit is obvious.

Thanks

**Comment by jschuler** [comment]
Although it's not that bad when i comment out the logging statement. So maybe it's not a real issue.

**Comment by RobJacobs** [comment]
I think what's happening here is your logging digest cycles, not necessarily the tooltip being created.  Here is an updated [plunk](http://plnkr.co/edit/SvOR0KicFfk9reHdzzNS?p=preview) that demonstrates the same behavior when the tooltip is used outside of an ng-repeat.  You will also notice the messages are logged when the app first runs even though no tooltip has been activated.

**Comment by jschuler** [comment]
Thanks, I'll close this issue then. Seems like this is standard behavior.
