### ISSUE TITLE
$uibModal: unknown service

### ISSUE THREAD

**Issue by bitliner** [angular-ui/bootstrap#4563]
* the script ui.bootstrap is included in html file
* the deps (in app.js, when declaring the app module) of the app include `'ui.bootstrap'`, `'ui.bootstrap.modal'`
* my Ctrl just use $uibModal, but $uibModal results as unknown

What am I missing?

I am using ui.bootstrap 0.12.0 and angular 1.2.6

**Comment by wesleycho** [comment]
Hi @bitliner, can you reproduce this? I am not seeing this [here](http://plnkr.co/edit/iAJHkA7Y1HuCHDoK0P4h?p=preview).

**Comment by bitliner** [comment]
just change the version from 0.14 to 0.12 and I think you are done.

**Comment by wesleycho** [comment]
That is new to 0.14 - for 0.12, use $modal

**Comment by icfantv** [comment]
@bitliner, you may want to take a gander at the [changelog](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md) as there have been quite few updates since 0.12.0.

**Comment by bitliner** [comment]
I see, thanks.

I was looking for in the github page documentation, I did not find a way to see the docs about the older version, that is why  posted here.

I did not thinkg on the changelog there were such details.

Thanks anyway. If you could make the docs of older versions accessible, that would be great :-)

**Comment by icfantv** [comment]
Unfortunately, that's not going to be possible.  You will need to download the 0.12.0 version of the source code and build it yourself - then you will have the docs.  [Here's the release commit](https://github.com/angular-ui/bootstrap/commit/1cebcbc3879a75ee5eae53d7c818745d4f2d4580) so you just need to check out that version and build.

**Comment by bitliner** [comment]
How to serve the docs after building it?

**Comment by bitliner** [comment]
Any guide to build and serve the documentation/gthub page ?
