### ISSUE TITLE
v0.14.0 removed datepickerConfig. Docs still has reference to it.

### ISSUE THREAD

**Issue by brenovieira** [angular-ui/bootstrap#4572]
The [angular bootstrap docs](http://angular-ui.github.io/bootstrap/#/datepicker) says:

> Datepicker Settings
All settings can be provided as attributes in the datepicker or globally configured through the **datepickerConfig**.

Although in version 0.14.0 ```datepickerConfig``` is not available anymore.
Please see the error on devTools [in this plunker](http://plnkr.co/edit/y28XOTlZhbSKf03lWe2x?p=preview):
> Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:unpr] Unknown provider: datepickerConfig

I noticed ```<datepicker>``` still works, but it logs a warning "it's deprecated".

Do you intend to maintain backward compatibility with ```datepickerConfig``` also,
or the documentation is wrong and I must use the new ```uibDatepickerConfig``` ?

**Comment by wesleycho** [comment]
In this case, the documentation is wrong - we are using the `uib` prefix for all constants

**Comment by brenovieira** [comment]
@wesleycho, great! It's what I thought.

**Comment by wesleycho** [comment]
Just updated the live docs, should be fixed there.

**Comment by brenovieira** [comment]
Please see https://github.com/angular-ui/bootstrap/pull/4575#issuecomment-147211519
