### ISSUE TITLE
Prevent Modal Close when Clicking Outside the Modal

### ISSUE THREAD

**Issue by snotice7** [angular-ui/bootstrap#4589]
Hi,
I still pretty new to UI-Bootstrap so this may be a simple one.
I am trying to configure the modal to:

1.User is required to make a selection from the Modal options
2. If the user clicks outside the Modal, it does not close

Any help would be great!

**Comment by wesleycho** [comment]
See the `backdrop: 'static'` option, as listed in the documentation [here](http://angular-ui.github.io/bootstrap/#/modal) - this should do the trick

**Comment by enfingit** [comment]
Refer 
https://stackoverflow.com/questions/22207377/disable-click-outside-of-bootstrap-modal-area-to-close-modal
