### ISSUE TITLE
Using Bower to install custom build.

### ISSUE THREAD

**Issue by vorillaz** [angular-ui/bootstrap#4590]
Hello there I am using Bower to fetch my dependencies. Is it somehow possible to generate a custom build without grabbing all the components?

Cheers.

**Comment by wesleycho** [comment]
One can consume this repository directly with bower and load the scripts you like that way.

**Comment by vorillaz** [comment]
Hello there , thanks for the instant reply.
Using bower I am getting the compiled and concatenated JavaScript files , not the whole repo

**Comment by wesleycho** [comment]
You can specify
```json
"angular-ui-bootstrap": "https://github.com/angular-ui/bootstrap"
```
in your bower.json file.

**Comment by vorillaz** [comment]
Thanks a lot. Cheers.
