### ISSUE TITLE
typeahead-editable attribute does not update as per documentation

### ISSUE THREAD

**Issue by damonf** [angular-ui/bootstrap#4592]
Changing the value of typeahead-editable attribute should update the behaviour of the directive, but this is not implemented.
The documentation for this attribute has an eyeball icon next to it, and the doc says... "The eye means that the setting has an Angular $watch listener applied to it."

plunker here http://plnkr.co/edit/W2vneQGgiMDHMGC3uDGS?p=preview

**Comment by wesleycho** [comment]
This looks like it was never supported - probably better to just remove the eye from the docs.

This would be an easy PR if you'd like to tackle it.
