### ISSUE TITLE
A way to view older docs

### ISSUE THREAD

**Issue by chaddjohnson** [angular-ui/bootstrap#4593]
Guys,

Thanks for the library. It's great.

I built my site using 0.13.0. I'm launching next week. There's no way I can change everything now to use the new namespacing in 0.14.0 (among any other changes), so it would be great if I could somehow still view the docs for 0.13.0. I (and surely others) really need to be able to reference the old docs.

Is there a way to do this? Even if there's a way I can download them locally and run them on a local web server -- that's great too.

**Comment by chaddjohnson** [comment]
Okay, I found a way:

1. Clone the repository: git@github.com:angular-ui/bootstrap.git
2. Switch to the "gh-pages" branch.
3. View the git log to find the branch version corresponding to 0.13.0 (which happens to be 5495d6b1d04888692b10121a8acb565c69a865b2).
4. Checkout that commit.
5. Run servedir (or whatever server).

So that works. But I do recommend you all implement a way to view docs for previous version of this library.

**Comment by Foxandxss** [comment]
Let's continue in #4565. We are lacking the manpower to do every possible chore. This is a good thing to have, but we have other priorities for the time being.

**Comment by chaddjohnson** [comment]
Looks like this is in place on the site now via a navbar option -- thank you!
