### ISSUE TITLE
Timepicker fails validation if you change the "min" dynamically

### ISSUE THREAD

**Issue by changus** [angular-ui/bootstrap#4598]
Hi,  asked this on stackoverflow on well (let me know if not allowed), but I am trying to change the minimum date on a timepicker control dynamically based on a different timepicker.  The reason that it sets the validity to false is because it runs the render function (that still has the old "min" value) before it fires the watch to the "min" attribute to update that value.  If you try to update the start time or end time on the next digest cycle, then it sets it back to valid.  Is there anyway to add something to check if there is a new min/max value before it checks the validity?

Link to stackoverflow question:
http://stackoverflow.com/questions/33089488/angularjs-angularui-timepicker-validation-error-when-minimum-date-is-changed

Link to plnkr:
http://plnkr.co/edit/HdKmbvBsSdtUBnf9ZuZd?p=preview

**Comment by icfantv** [comment]
Hi @changus, you were correct to post the question to StackOverflow.  The official instructions for receiving support are [here](https://github.com/angular-ui/bootstrap#need-help).

However, if you think you've found a bug, the instructions are [here](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

But at first glance, this sounds either like a bug or a feature request so I'm going to mark this as needs more investigation so we don't lose it.

**Comment by icfantv** [comment]
Additionally, if you're feeling awesome, please feel free to submit a PR.

**Comment by icfantv** [comment]
Closing in favor of #5957 as this will result in a complete rewrite of the widget, addressing all the outstanding issues.
