### ISSUE TITLE
datepicker docs

### ISSUE THREAD

**Issue by isometriq** [angular-ui/bootstrap#4600]
I was unable to use the docs sample HTML code here:
https://angular-ui.github.io/bootstrap/#/datepicker
<uib-datepicker /> did not work...
I had to use <datepicker />

**Comment by isometriq** [comment]
Same for the directive "uib-datepicker-popup"
Had to use "datepicker-popup"

**Comment by isometriq** [comment]
Updated to 0.14.1 since i was on 0.13.4
What was explained above is the same

**Comment by wesleycho** [comment]
Can you post a reproduction? This is not helpful information, especially given that the [demo Plunker](http://plnkr.co/edit/OTRH81oDPsorzovP62t3?p=preview) works.

Otherwise, this is a question better suited to support channels such as StackOverflow.

**Comment by isometriq** [comment]
ok, I've just found the problem was on my side, i confirm it works now
