### ISSUE TITLE
Custom tooltip event in Accoridon panel

### ISSUE THREAD

**Issue by Jebedo** [angular-ui/bootstrap#4602]
When I am outside accordion custom event in tooltip fires like it should, but when I am inside accordion problem emerge.

Plunker:

http://plnkr.co/edit/dtYO32GM2fc9WKy46fka?p=preview

Outside tooltip hides when mouse leave area, but it doesn't in accordion. 

Is this bug, or am I doing something wrong?

**Comment by icfantv** [comment]
@Jebedo, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

There were a lot of issues with your plunker.  [Here's the working one](http://plnkr.co/edit/uVhVmiVbvGj6m8rVeHXj):
* You're including two different versions of the Bootstrap CSS
* You're including Font Awesome
* You're including two different versions of the Angular UI Bootstrap library and neither are the latest (0.14.1 is the latest).
* You're including jQuery after you include core Angular

In the future, for us to be able to help you, you need to create a MINIMAL plunker that shows the problem.  Adding extra stuff just makes our job that much harder and you're left wondering why no one is helping you.

**Comment by Jebedo** [comment]
You are right, my Plunker was terrible, I am new with Plunker :)

But the "bug" is still there even with your, repaired, code and new ui-bootstrap 0.14 version:

http://plnkr.co/edit/dtYO32GM2fc9WKy46fka?p=preview

**Comment by RobJacobs** [comment]
This is a result of the prototypal inheritance gotcha as described [here](https://github.com/angular/angular.js/wiki/Understanding-Scopes) and in the [FAQ](https://github.com/angular-ui/bootstrap/wiki/FAQ) section under 'My input / select element doesn't work as expected inside the tab / accordion directive'.  Updated working plunk [here](http://plnkr.co/edit/5NK3f2UwPISNw7Euvdvr?p=preview)

**Comment by Jebedo** [comment]
Nice! It worked. Thank you very much @icfantv  and @RobJacobs.

Now to go back to study on scope and inheritance ;)
