### ISSUE TITLE
$uibTooltip creates massive memory leak

### ISSUE THREAD

**Issue by maxklenk** [angular-ui/bootstrap#4604]
Each usage of `<span uib-tooltip="Hey"></span>` creates a memory leak on each state change with `ui-router`.

When profiling the heap allocation of this [plnkr](http://plnkr.co/edit/Sq5KAfMcTzmCt2MfJlUa) memory leaks can be seen with tooltips:
![screen shot 2015-10-13 at 2 32 46 pm](https://cloud.githubusercontent.com/assets/3898310/10454805/b4054f82-71b7-11e5-8c24-51e316d416a9.png)
and less when there are no tooltips
![screen shot 2015-10-13 at 2 33 00 pm](https://cloud.githubusercontent.com/assets/3898310/10454814/c157eed8-71b7-11e5-8390-675103f0fb96.png)

**Comment by Foxandxss** [comment]
@maxklenk Could you please check if that happens with the old non-prefixed version? And if possible with 0.13.4?

Thank you.

**Comment by maxklenk** [comment]
Sure:

0.14.1  `uib-tooltip`  => memory leak
0.14.1  `tooltip`  => memory leak
0.13.4  `tooltip`  => **no** memory leak

**Comment by Foxandxss** [comment]
Interesting, really interesting. I wonder if we introduced it with the prefix work. It is too much ask for 0.14.0 test?

**Comment by Foxandxss** [comment]
We did lot of tooltip changes in 0.14.0 so one of them is.

Thoughts @wesleycho ?

**Comment by maxklenk** [comment]
The memory leak was already introduces in the 0.14.0 release.

**Comment by Foxandxss** [comment]
Thanks, it is time to check out why and fix it :+1:

**Comment by wesleycho** [comment]
I suspect this might be the cause: https://github.com/angular-ui/bootstrap/commit/c08509a

**Comment by wesleycho** [comment]
If that is indeed the cause, the fix should be simple - on the $scope `$destroy` event, just clear out the tooltip from the stackedMap.

**Comment by RobJacobs** [comment]
@wesleycho Verified that does in fact fix the problem.  I can fix this as part of PR #4597 if you would like?

**Comment by wesleycho** [comment]
Separate PR if possible

**Comment by Foxandxss** [comment]
Yeah, separate always.

**Comment by RobJacobs** [comment]
I can do that, will create A PR shortly.

**Comment by maxklenk** [comment]
Thank you for fixing this that fast!
