### ISSUE TITLE
Typeahead open on focus

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#4605]
I see that min-length must be greater or equal 1
How to force typeahead open on focus without typing anything?

**Comment by Foxandxss** [comment]
Please, use stackoverflow (http://stackoverflow.com/questions/tagged/angular-ui-bootstrap) for questions. We prefer to keep this issue tracker for bugs only.

Thank you.

**Comment by piernik** [comment]
I think angular bootstrap misses that feature so it's rather feature request

**Comment by Foxandxss** [comment]
I reopen this, but I don't think it is a good idea.

**Comment by piernik** [comment]
Why  ? I could be new directive `typeahead-open-on-focus`

**Comment by wesleycho** [comment]
We want to decrease the number of configuration options - if we implemented every request, the library would bloat up massively. It is already more complicated than it should be.

We are currently weighing feature requests carefully.

**Comment by piernik** [comment]
`min-length=0` and thats all ;)

**Comment by Foxandxss** [comment]
I am closing this in favor of #764 which has lots of more information

**Comment by shyamal890** [comment]
@Foxandxss I wonder why both the issues (#764) are closed. This is one of the most sought after feature request!!  @wesleycho

**Comment by Foxandxss** [comment]
I don't follow. What you mean with closed? This issue is just a duplication of #764 and the other one has more information (and that issue is open).
