### ISSUE TITLE
Slide on uib-carousel changed listener

### ISSUE THREAD

**Issue by renatosierra** [angular-ui/bootstrap#4608]
is there anyway that the uib-carousel directive have a callback or a service to let you have the current slide on a function of your scope to get the current slide on a specific carousel?

**Comment by icfantv** [comment]
@renatosierra, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

The `UibCarouselController` is exposed as `controller` via `controllerAs` syntax and thus, the `currentSlide` field is accessible.
