### ISSUE TITLE
Doesn`t work. No errors

### ISSUE THREAD

**Issue by Valonix** [angular-ui/bootstrap#4611]
Hello, i try to use ur directive.
Include script in my index.html
after inject him in my module

 var app = angular.module('app', ['ngRoute', 'ngResource', 'ui.bootstrap']).run(function($rootScope) {
      
    });

and nothing. no errors. but no any style by bootstrap . My version of Angular is 1.4.7

**Comment by pkozlowski-opensource** [comment]
This project doesn't provide CSS, you need to use Bootstrap's one. Check the demo page (http://angular-ui.github.io/bootstrap/) and fork on of the plunkers to see what is needed for a minimal setup.
