### ISSUE TITLE
Feature: add 'typeahead-matches' option to bind to matches array for an 'Add All' button

### ISSUE THREAD

**Issue by bc-jasond** [angular-ui/bootstrap#4612]
would be awesome to expose the scope.matches array in the API to make operations on the whole list like 'add all' and 'remove all'

**Comment by wesleycho** [comment]
This is an internal - I don't see any particular value with exposing this beyond how it is already exposed. You can already calculate the current matches.

Can you give a strong argument why we should expose it?

**Comment by bc-jasond** [comment]
How is the scope.matches array already exposed, can you point me to docs/code?  It seems like only one item at a time is available via 'typeahead-on-select' or 'ng-model'

here's the use case:
user types a few letters, the list appears with some items
user clicks a button and all list items are returned not just one

**Comment by wesleycho** [comment]
Right, but why would this be a feature hugely needed? One already has access to the larger array that the matches is a subset of...so this confuses me.

**Comment by bc-jasond** [comment]
so you're proposed workaround is to cut and paste the code that does the matching?

**Comment by bc-jasond** [comment]
agreed, just use $filter() and the ng-model value.  Thanks
