### ISSUE TITLE
Cannot set property 'isOpen' of null

### ISSUE THREAD

**Issue by oliversalzburg** [angular-ui/bootstrap#4614]
I occasionally see the following error in the browser console in our application.
```
Uncaught TypeError: Cannot set property 'isOpen' of null
hide @ ui-bootstrap-tpls.js:3496
hideTooltipBind @ ui-bootstrap-tpls.js:3454
```

I can't definitively say what causes it, but I suspect that it happens when I have a tooltip on a link which, when clicked, causes a route change and, thus, destroys the current scope.

**Comment by RobJacobs** [comment]
This should be fixed under PR #4455 which fixed issue #3347.  When reporting issues, please search closed issues and PRs first and provide a plunkr that reproduces the problem.
