### ISSUE TITLE
Tooltip not closing

### ISSUE THREAD

**Issue by bogdanalexe90** [angular-ui/bootstrap#4618]
Hi since last update (1.4.2) All my tooltips are not closing.
This is reproducible when you have 2 or more tooltips one near each other and you hover over them.

```html
<span uib-tooltip="Some tooltip" tooltip-popup-delay="300" tooltip-popup-close-delay="300">Some text</span>
```

**Comment by Foxandxss** [comment]
Can we have a plunker please?

**Comment by RobJacobs** [comment]
Here is a [plunk](http://plnkr.co/edit/Z6xzaMBxKlnvm6xf2eQs?p=preview) that reproduces the issue.

**Comment by RobJacobs** [comment]
In looking at the test associated with the tooltip for this scenario and I'm trying to figure out why this [test](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/test/tooltip.spec.js#L278) is not failing.  I've tried adding timeout flush and using a count of elements, but still haven't gotten the test to fail?

**Comment by bogdanalexe90** [comment]
Thanks guys for your quick reaction.
 Any idea when this fix would be released?

**Comment by icfantv** [comment]
@bogdanalexe90, we don't have a time frame for 0.14.3 yet, but please feel free to clone the repo, run an `npm install` and then `grunt` to build the SNAPSHOT release (which will appear in the `dist` folder.
