### ISSUE TITLE
Documentation for previous versions

### ISSUE THREAD

**Issue by wkjesus** [angular-ui/bootstrap#4625]
Where can i found the documentation for previous versions. e.g. version 0.13.0 because i only see on main page the brand new version 0.14.0

**Comment by icfantv** [comment]
@wkjesus, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

You can clone the repo for that release and perform a local build.  We currently do not have a mechanism in place for viewing older docs.

**Comment by xt0rted** [comment]
The steps to view the documentation locally are described in https://github.com/angular-ui/bootstrap/issues/4593#issuecomment-147303084

**Comment by chaddjohnson** [comment]
Looks like this is in place on the site now via a navbar option -- thanks guys!
