### ISSUE TITLE
Typeahead event listeners never removed

### ISSUE THREAD

**Issue by oliversalzburg** [angular-ui/bootstrap#4632]
http://plnkr.co/edit/7KezbXxCsmx79oyDpux9?p=preview

When using `typeahead-append-to-body='true'`, event listeners will be bound to `window` and `body`, these listeners are never unbound.

To showcase:
1. In the plunker, click the **Open me!** button.
2. Close the modal, by clicking **Cancel**.
3. Change the preview window body size by moving the splitter.
4. `fireRecalculating` will be called.

**Comment by icfantv** [comment]
Yep.  Looks like a bug.  Good catch.  Please feel free to submit a PR.  Thanks.
