### ISSUE TITLE
Popover not working with Angular 1.4.6 and above

### ISSUE THREAD

**Issue by bhushanvaidya3** [angular-ui/bootstrap#4633]
http://plnkr.co/edit/Amk67tRwf1VWs3jbwmhY?p=preview

Update: Tooltip also not working. May be the root cause since Popover is dependent on Tooltip

Thanks,
Bhushan

**Comment by Foxandxss** [comment]
I don't we have 1.4.x support for that old ui-bootstrap version. Please update it to the latest 0.14.0 (at least a 0.13.x for 1.4.x support).

**Comment by bhushanvaidya3** [comment]
Thanks for the update. In my app, I'm using  0.13.4. Will update and check the same. Thanks again.

**Comment by bhushanvaidya3** [comment]
@Foxandxss I tested it on 0.14.2 and it's working fine. Also with that I updated my app to the latest version. Thanks for your help!

**Comment by shubham094** [comment]
I am using 0.14.2 and 1.4.2 but its not working if i apply it on a span element.
<span popover="{{endorsement.desc}}" popover-trigger="'mouseenter'" popover-placement="top" popover-class="fg-blue" popover-title="{{endorsement.title}}" ng-model="endorsement.title">{{endorsement.title}}</span>
