### ISSUE TITLE
Cleanup needed for deprecation removal

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#4637]
List of tasks to do for when we decide to remove the deprecated stuff.

All the components have some things in common that needs be deleted, so I will put all of that under the same checkbox. Those things are:

* Remove everything from the deprecation comment to the bottom (source file)
* Remove everything from the deprecation comment to the bottom (test file/s)

Components:

- [x] Collapse
- [x] Accordion
- [x] Alert
- [x] Buttons
- [x] Carousel
- [x] Dateparser
- [x] Position
- [x] Datepicker
- [x] Dropdown
- [x] Modal
- [x] Pagination
- [x] Tooltip
- [x] Popover
- [x] Progressbar
- [x] Rating
- [x] Tabs
- [x] Timepicker
- [x] Typeahead

Extra quirks:

- [x] On UibDatepickerPopup controller, remove the reference to `attrs.datepickerPopup`
- [x] Tooltip re-add the `tooltip` class to templates and remove the code that adds it.
- [x] Popover re-add the `popover` class to templates and remove the code that adds it.
- [x] uibAccordionTransclude has a hack to support deprecated heading.
- [x] uibTabHeadingTransclude has a hack to support deprecated heading.
- [x] uibTabContentTransclude has a hack to support deprecated content.
- [x] $uibModal has special logic for handling the `$modalInstance` controller local that needs to be stripped out

**Comment by Foxandxss** [comment]
Please, if you remember any extra quirk that you had to do for the deprecation sake, add it there.

**Comment by wesleycho** [comment]
This is now addressed in `master`!

**Comment by crisbeto** [comment]
What's the plan regarding having the deprecated code together with the current one? Also is there a way to do a custom build without the deprecated stuff?

**Comment by wesleycho** [comment]
Currently we removed the deprecated code in `master` - in the upcoming 1.0 release, it will not be released.

We may have an interim 0.14.4 release soon with a tooltip fix though, but deprecated code present.

**Comment by icfantv** [comment]
@crisbeto, if you really want to live on the edge, you can close `master` and do an 'npm install' followed by 'grunt' to build the latest 1.0 SNAPSHOT build.

**Comment by crisbeto** [comment]
I don't really mind that, but I'd still need to remove the modules, that I'm not using, manually.
