### ISSUE TITLE
Change $modalInstance to $uibModalInstance

### ISSUE THREAD

**Issue by ravishivt** [angular-ui/bootstrap#4638]
Shouldn't this provider's name be updated to conform?

**Comment by pkozlowski-opensource** [comment]
Yeh, we could do this for consistency.

**Comment by wesleycho** [comment]
It should be noted that this is a breaking change - I'm fine with this breaking change. This could affect the regular modal service users since the code is not duplicated.

**Comment by wesleycho** [comment]
Scheduling this for 1.0 since this will be a breaking change with a bit of potential pain.

**Comment by wesleycho** [comment]
Figured out a way to get this to work in 0.14.x and play nicely - will have PR up shortly.

**Comment by ravishivt** [comment]
Great, thanks!  I opened another similar request.  https://github.com/angular-ui/bootstrap/issues/4670
