### ISSUE TITLE
Popover with template flickers on first open

### ISSUE THREAD

**Issue by mihaibogdan10** [angular-ui/bootstrap#4639]
I'm using 0.14.2, but I've tested it and I have the same issue with master.

I find that simplest way to explain this is to show it. For a split second, the popover is positioned at the top-right corner of the element that shows/hides it. This only happens the first time I open it, however.

<img width="149" alt="screen shot 2015-10-16 at 12 01 14 am" src="https://cloud.githubusercontent.com/assets/2984085/10527492/603664d4-7399-11e5-8a37-e5e9b13f20bb.png">
(I was only able to get a picture of the above by recording and playing in slow-motion)

All subsequent opens are correctly positioned.

<img width="187" alt="screen shot 2015-10-16 at 12 01 24 am" src="https://cloud.githubusercontent.com/assets/2984085/10527491/6034d772-7399-11e5-86cc-4b82a0140f03.png">

I was able to showcase it in a plnkr, you can clearly observe the initial flickr, although the behavior is different: http://plnkr.co/hRJNKJGo6gaDFBmoPEMa

**Comment by wesleycho** [comment]
@RobJacobs know of what might cause this? Sounds related to the tooltip positioning

**Comment by RobJacobs** [comment]
Here is a [plunk](http://plnkr.co/edit/5sIQBeKhKeaQI3oT6zgb?p=info) with the latest build from master that includes PR #4623 which behaves better.  What you are seeing is the delay for the template to be loaded into cache then the popover sizing to fit that content.  I added an example of an inline (local) template and you will notice there is no 'flash'.

**Comment by mihaibogdan10** [comment]
I'm afraid my use case prevents me from using inline templates, as I need to use the same one across a lot of different views.
Is it possible to wait for the template to be loaded before displaying anything the first time it is opened?

**Comment by icfantv** [comment]
@mihaibogdan10 you can register your template in the `$templateCache` at Angular boot time if you don't want to specify it on EVERY directive.

**Comment by wesleycho** [comment]
Closing this issue as a support issue.

You should always bundle your templates in $templateCache before it potentially loads. Never load a template via xhr if you want to avoid weird flashes such as this.
