### ISSUE TITLE
Creating a hoverable popover

### ISSUE THREAD

**Issue by httpete** [angular-ui/bootstrap#4640]
Hi,

Is there a way to do a templated popover on mouseover that stays open if your mouse is on it? Seems a common need, to have a link in the popover that when you mouseover the target and then into the popover you can click a link.

http://stackoverflow.com/questions/20267967/create-hoverable-popover-using-angular-ui-bootstrap?lq=1

We are having to use another library which is a PITA..

http://nohros.com/nsPopover/

**Comment by icfantv** [comment]
@httpete, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

**Comment by icfantv** [comment]
I've updated the SO article with the right solution:  http://stackoverflow.com/questions/20267967/create-hoverable-popover-using-angular-ui-bootstrap/33159724#33159724.  You want to disable the triggers and use the `popover-is-open` property to manually control when it open vs. closed.
