### ISSUE TITLE
Accordion and dynamic content

### ISSUE THREAD

**Issue by renatotkr** [angular-ui/bootstrap#4645]
I have an accordion on my page and the body content is rendered dynamically via ajax when the user clicks on the accordion heading. The problem is that the height gets fixed when I first click on the heading. After the content loads, accordion does not resize properly . Is there a way to set the height to auto?

![image](https://cloud.githubusercontent.com/assets/1720409/10552270/228d0198-7429-11e5-8d83-12b536a52b55.png)

**Comment by AWolf81** [comment]
Please have a look at this [SO question](http://stackoverflow.com/questions/33178479/dynamic-content-hidden-in-angular-bootstrap-accordion/33179216#33179216) where I added an answer to the same issue a minute ago.

I don't know how to fix that with the latest version of ui.bootstrap, at the moment.

**Comment by AWolf81** [comment]
I think I've found the point why it is not working. `ngAnmiate` is required as dependency of your app as `collapse` directive needs it to work.

This [commit](https://github.com/angular-ui/bootstrap/commit/36e6363765dbae2872ef86b4cba890c9b197d74b) has changed the animations and dynamic content behavior. 

That point is not mentioned in the docs and should be added.

**Comment by Foxandxss** [comment]
No. `ngAnimate` was added lot ago (for a 0.13.x version).

You can use this library without `ngAnimate`, you just will lose the animation.

Do you have any plunker with the latest version where I Can see that problem you say? Thank you.

**Comment by AWolf81** [comment]
[here](http://plnkr.co/edit/y81e62ZXRnCeFRSrazzS?p=preview) is the plunkr from the mentioned SO question (it uses the latest version).

**Comment by Foxandxss** [comment]
I can see that. Thanks.

**Comment by icfantv** [comment]
I'm pretty sure this is related to #4561.

**Comment by Foxandxss** [comment]
100% related. Closing this.
