### ISSUE TITLE
Accordion body incorrect height calculation

### ISSUE THREAD

**Issue by Skakruk** [angular-ui/bootstrap#4647]
Accordion body height is calculated incorrectly when it has hidden content. Please check [plnkr](http://plnkr.co/edit/ZhPtRFB11zq3EXsClsmF?p=preview)

Initially it has height that exceed visible content. After toggling body is shown correctly, but when I'm toggling hidden content it shows cutted.

**Comment by Foxandxss** [comment]
It is more of an collapse issue probably and similar to #4561 (will probably be the same issue).

**Comment by Foxandxss** [comment]
When the PR get merged, you will ned to update to 1.4.5 because there is a related bug fixed in that version.
