### ISSUE TITLE
Wrong placement of uib-tooltip in 0.14.x

### ISSUE THREAD

**Issue by sunabozu** [angular-ui/bootstrap#4649]
Hi.

I've been using 0.13.4 version before, and everything was fine, but with migrating to 0.14.x version I got slightly broken tooltips. In some cases they display correctly, but in some they don't. I noticed it right after migrating. You can see how it looked before and now:

![Image of tooltip](http://s10.postimg.org/p1g361mn9/Screen_Shot_2015_10_18_at_11_56_21.png)

![Image of tooltip](http://s24.postimg.org/95uy0sk8h/Screen_Shot_2015_10_18_at_11_56_33.png)

I use AngularJS 1.4.7. and Bootstrap 3.3.5.

**Comment by Foxandxss** [comment]
Could you please put a plunker of a tooltip that gets misplaced?

@RobJacobs You have any idea? :)

**Comment by sunabozu** [comment]
Sure, here is plunker http://plnkr.co/edit/dUEyFn0kPkDnxJGac1Ai?p=preview

**Comment by wesleycho** [comment]
It looks like the float is destroying the positioning logic - certainly a bug, but I'd recommend against using floats if you can.

**Comment by Foxandxss** [comment]
I agree with my friend idea because I tried a 0.13.x version and even when it is not as weird as with 0.14.x, it looks a bit brokish in my opinion.

**Comment by icfantv** [comment]
Let's leave this open until we get the position issue entered, please.

**Comment by wesleycho** [comment]
So what is happening here is that the div needs `position: relative` - see [here](http://plnkr.co/edit/K7AYDOhYZwAa2Z0IPTcz?p=preview) for a working Plunker.

**Comment by marbug** [comment]
It's more a workaround. Tooltip's text is shown in several lines but not in one.

**Comment by marbug** [comment]
P.S. Fix to show tooltip in one line:
tooltip-class="nowrap"

and in css:
.nowrap {
    white-space: nowrap;
}

May be this could help...

**Comment by divisble** [comment]
I know it's very old topic but also can help this post: https://github.com/angular-ui/bootstrap/issues/4195#issuecomment-148049343
