### ISSUE TITLE
uib-popover-template unclear

### ISSUE THREAD

**Issue by adamzerner** [angular-ui/bootstrap#4654]
The docs [say](https://angular-ui.github.io/bootstrap/#/popover):
> takes text that specifies the location of a template to use for the popover body. Note that this needs to be wrapped in a tag.

Questions:
1. What is meant by "wrapped in a tag"?
2. Is it the case that it evaluates the value of this attribute as an expression? That seems to be the case.
3. Can this be a link to an external file, or does it just work for inline templates? I tried to use it to point to an external template and it wasn't working. A demo of how to do that would be useful.

**Comment by icfantv** [comment]
I agree this is worded a little weird.  Think of it as a URL to a template file.  The contents of the template file __MUST__ be wrapped in a tag, e.g., `<div>...</div>`.

If, as you say, a URL is not working, please follow the instructions [here](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

**Comment by adamzerner** [comment]
I see, thanks for the help. I got the external link working. I was just confused about what it treats as the root directory. You're right that I should have thought to make a Plunker, thanks for pointing that out.

**Comment by icfantv** [comment]
You're welcome.  I'll update the docs.  The external link is relative to your webroot.  It also serves as the key in `$templateCache`.
