### ISSUE TITLE
auto-close = "outsideClick" do not work with new uib-dropdown directive

### ISSUE THREAD

**Issue by maded2** [angular-ui/bootstrap#4655]
Just switched to 0.14.2,  the new directive uib-dropdown ignores the auto-close="outsideClick".  It works if I keeps the old dropdown directive, but don't if I update as per the warning message in the console.

Console warnings:
dropdown-toggle is now deprecated. Use uib-dropdown-toggle instead.
dropdown-menu is now deprecated. Use uib-dropdown-menu instead.

thanks,
eddie

**Comment by icfantv** [comment]
Can you please quickly create a plunker that demonstrates this?  Thanks.

**Comment by maded2** [comment]
http://plnkr.co/edit/f6NV20pHZE7lcBBwTCcS?p=preview

**Comment by wesleycho** [comment]
Thanks for the reproduction - this is actually a usage issue, as one can see it working [here](http://plnkr.co/edit/OvBTC8PBLJmEDNRlwOel?p=preview). What was missing was the `uib-dropdown-menu` attribute (or class, if one wants) on the element with the dropdown menu.

**Comment by maded2** [comment]
thanks that works.  Looks like the documentation on the web site only mentioned:  dropdown-menu , not uib-dropdown-menu.

**Comment by trisys3** [comment]
I know this is about 2 years too late, as the library is deprecated, but this only works with the attribute `uib-dropdown-menu`. It doesn't work with the element `uib-dropdown-menu` or `dropdown-menu`, nor with the class `dropdown-menu`.
