### ISSUE TITLE
uib-accordion: is-open is not linked to the outer scope as expected

### ISSUE THREAD

**Issue by ssc-hrep3** [angular-ui/bootstrap#4656]
I used the ``is-open`` attribute of the uib-accordion directive. I expected that the variable, I pass in there, will be updated by uib-accordion. That is not the case. Is this the correct behavior?

Story around: I wanted to use the variable of is-open and manipulate it from external. Inside the accordion is a search mask, which should be closed after a successful search. If I change the variable in is-open, after the successful search, the uib-accordion reacts as expected. The problem occurs, if the user clicks on the accordion header. The variable is not updated anymore and can therefore not correctly directed from outside anymore.

I added a plunkr, where you see, that the variable is not updated on a click on the header of the accordion (opening/closing accordion).
http://plnkr.co/edit/YTX7LTdiFlqn5yIn9t1x?p=preview

**Comment by icfantv** [comment]
Yea, this is a bug.  We should be toggling the `is-open` attribute when the user clicks the header.  Good catch.  Please feel free to submit a clean PR with appropriate functional test(s).

**Comment by Foxandxss** [comment]
This is not an issue.

The rule is always always always have a dot in your expressions. That way, you avoid the issues with inner scopes.

Check this: http://plnkr.co/edit/ITVUu4oLTiLZRUMvdeF1?p=preview

**Comment by ssc-hrep3** [comment]
Thank you. That info solved my bug.
