### ISSUE TITLE
Datepicker gives form error when time is a string?

### ISSUE THREAD

**Issue by nozshand** [angular-ui/bootstrap#4662]
Recently updated to version 0.14.2, Datepicker always gives form error 'Date' if the model is a string

For example:
obj.time = '2015-10-09T00:00:00Z';
this would produce a form error 'Date', but this would not
obj.time = new Date('2015-10-09T00:00:00Z')

Is this working as intended that datepicker only accepts model as Date object?

I'm using angular 1.4.7

**Comment by icfantv** [comment]
@nozshand, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

Yes.  If you look at [the docs](https://angular-ui.github.io/bootstrap/#/datepicker) you will see that `ng-model` must be a JS `Date` object.
