### ISSUE TITLE
Datepicker input not validated for min and max when manually inserting date

### ISSUE THREAD

**Issue by cen1** [angular-ui/bootstrap#4664]
Reproducible on demo page: https://angular-ui.github.io/bootstrap/

Simply apply the min rule and change day to yesterday. Calendar UI is properly invalid but input box is not.

See: https://github.com/angular-ui/bootstrap/issues/1688#issuecomment-140504899

**Comment by icfantv** [comment]
Thank you for entering this, we'll take a look.

**Comment by wesleycho** [comment]
Doing a deep investigation into this issue, this is not a bug. The input is separate from the datepicker, so one should create a custom directive to hook into the validation state of the datepicker, and use that to modify the validation state of the input to match.

**Comment by dgsmith2** [comment]
@wesleycho I'm struggling to see that there is no bug.  

In the case of an input that uses the pop-up functionality, one could reason that the picker is an extension of the input.  It would not be available if it weren't for the input being present (much like the picker you get in Chrome for a plain HTML 5 input with ```type="date"```).  Thus the two, if not seen as a whole, are, at the very least, coupled.

Now, an argument could/should be made that if it is an input that is tied to the model then validators should be defined on the input.  Where I get hung up one this thought is shouldn't only validators specified on the input affect the form's validity?  If an invalid date is manually entered when the pop-up is open it will invalidate the form and the revalidate it when closed.

I don't understand why it's okay for the pop-up to care enough to update the validity of the form, as a whole, but not to update the validity of the individual input.  I think some sort of change is necessary.  Either update the input's validity in addition to the form's, or stop updating the form's validity.

**Comment by daric81** [comment]
@dgsmith2  I have to agree with you. This is also behaviour that used to work and now doesnt as ive noticed the validation issue after migrating to 0.14.3 from 0.12.1.

This used to work in 0.12.1. see [Plunk](http://plnkr.co/edit/Mbz8EWbx5RUUDeXf5L2z?p=preview)

**Comment by cen1** [comment]
I too understand that these two components are technically separate, but I do not see a use case when the text input is valid and popup is invalid. You always want them to be of the same validity because it is the same component for the end user, just different ways of selecting the date (writing it or clicking on it).
Sure, I can write a wrapper but I don't want to. I just want to use the library in the cleanest way possible.

**Comment by SlippySken** [comment]
I stumble across the same bug now.
But I can not understand the reasons mentioned from wesleycho. I'm using the uib-datepicker-popup directive with an input. So I want this input to behave like a datepicker. 
When I enter something, which can't be parsed to an date, the input gets red and the form is marked as invalid. But if I enter something which can be parsed to an date but is before the min date, then for the input everything is fine. In my eyes that's not how it's supposed to be :(

**Comment by antch** [comment]
@wesleycho How exactly would we go about "hooking into the validation state of the datepicker"? The only behavior that I can see is that when you click to open the popup a `dateDisabled` error key is added. Is there even a way to manually fire the datepicker validation from your form?

I have to agree with the other commenters, this seems like an obvious bug.

**Comment by spirau** [comment]
This is still not working in 2.5.0

**Comment by alexnoise79** [comment]
this is not a bug, is a Feature! :-1:

**Comment by arielkuzminski** [comment]
@alexnoise79 
Hi, I think I've found even prettier way to deal with this bug (yes, it's obviously a bug), however it's still just a workaround.
`<input type="text" uib-datepicker-popup="..." readonly="readonly"/>`
