### ISSUE TITLE
Alert is created and dissappears when dismiss-on-timeout contains a variable

### ISSUE THREAD

**Issue by bartrail** [angular-ui/bootstrap#4665]
I recently updated from version 0.13.3 to 0.14.1 and recognized that using a variable as timeout immediately hides the alert after showing. When you put a breakpoint to dom modification in chrome, you see that it appears and then gets removed immeditely after.

I made a little demo here http://plnkr.co/edit/6dEUew1athBdkrGDXFt8?p=preview

**Comment by Foxandxss** [comment]
Oh, I am going to fix it.
