### ISSUE TITLE
Setting active slide for carousel doesn't work with ngAnimate

### ISSUE THREAD

**Issue by jholt1** [angular-ui/bootstrap#4667]
Angular, animate - v1.4.7
Bootstrap - v0.14.2

Not a new issue see: https://github.com/angular-ui/bootstrap/issues/2235

**Comment by jholt1** [comment]
http://plnkr.co/edit/OjmPa0FukOfqJ8JYlqo9?p=preview

You can see that when changing slides (first two buttons) that the carousel doesn't work. With active the slide shows up but you cannot change slides and without active everything disappears.  Changing active on its own does work.

However if you remove ngAnimate in my plnkr everything works.

**Comment by wesleycho** [comment]
There's one thing being done very wrong here - breaking the reference to the slides array is bad.

Forked the Plunker with those fixes [here](http://plnkr.co/edit/PnX2ErjeF4kF3kvSGojx?p=preview), but this needs a little looking into.

**Comment by wesleycho** [comment]
This should now be fixed in `master`, as can be seen [here](http://plnkr.co/edit/TXxHHerTIZQggM3nE7ta?p=preview).
