### ISSUE TITLE
uibDropdownToggle should add class "uib-dropdown-toggle", not "dropdown-toggle"

### ISSUE THREAD

**Issue by ravishivt** [angular-ui/bootstrap#4670]
For the sake of consistency.

**Comment by BobbieBarker** [comment]
Your pretty passionate about this, you know there is nothing stopping you from making some pr's

**Comment by wesleycho** [comment]
In this case, no, this is not what is desired. The reason for the `dropdown-toggle` class addition is because Bootstrap uses `dropdown-toggle`.

Closing as invalid.

**Comment by raman15071991** [comment]
i used it but it still not working properly
