### ISSUE TITLE
popover: allow specifying default popoverTrigger via $tooltipProvider

### ISSUE THREAD

**Issue by hoxu** [angular-ui/bootstrap#4671]
To support both devices with and without touch, something like `popover-trigger="mouseenter click"` has to be used.

It would be really nice to provide this as a default via `$tooltipProvider`.

**Comment by icfantv** [comment]
Per [the docs](http://angular-ui.github.io/bootstrap/#/tooltip), you can already configure the triggers globally.

If you are asking about supporting dual triggers, we do not support that as documented in #4007.

**Comment by hoxu** [comment]
I have read the doc on `$uibTooltipProvider`, but as far as I understand, it's not possible to provide default value for `popover-trigger` via `options`. Can you elaborate a bit on what you mean?

Basically, I want to be able to configure `$uibTooltipProvider` so that every popover works like it had `popover-trigger="mouseenter click"` attribute.

**Comment by icfantv** [comment]
@hoxu, there's no bookmark link that I can explicitly point you to, but if you read the docs for popover, you will see:

```
The popover directive also supports various default configurations
through the $tooltipProvider. See the tooltip section for
more information.
```

I'm not really sure how to make it more clear than that.

**Comment by hoxu** [comment]
Yes, and `$uibTooltipProvider` section says:

```
options(obj): Provide a set of defaults for certain tooltip and popover attributes.
Currently supports 'placement', 'animation', 'popupDelay', and appendToBody.
```

`popoverTrigger` is not one of the supported properties (yet), right?

**Comment by icfantv** [comment]
@hoxu, popover is build on top of tooltip so as a matter of fact, [it is](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L457-L460).

**Comment by ayush** [comment]
```
    $uibTooltipProvider.options({
        'trigger': "mouseenter click"
    });
```
