### ISSUE TITLE
Print Modal style for Google Chrome has issue with long overflow contents

### ISSUE THREAD

**Issue by shenlong** [angular-ui/bootstrap#4673]
If the contents of the modal is a long list or table when you print, the contents will get truncated or cut off. Tested with the latest Google Chrome and angular-bootstrap version 0.14.2.

This only happens with Modal and having added the @media print styles does not resolve the issue.

I created a Stackoverflow question http://stackoverflow.com/questions/33254940/printing-a-bootstrap-modal-page-with-contents-larger-than-1-page-results-in-cut

Plunker as follows:
http://plnkr.co/edit/TV0ttEAw4LWJ6sGLjSTR?p=preview

**Comment by icfantv** [comment]
@shenlong, please do not cross post your SO requests here.  The issues forum is for bugs and not support requests.  There are additional avenues via which you can request support as documented [here](https://github.com/angular-ui/bootstrap#need-help).

Having very tall modals, in general, is poor UX - you should ensure your contents fit and if they don't adding `overflow-y: scroll` is an option.  Note that you will need to set the container height for this to work.

**Comment by shenlong** [comment]
Hi Guys, I have the fix for printing issues:
http://stackoverflow.com/questions/33254940/printing-a-bootstrap-modal-page-with-contents-larger-than-1-page-results-in-cut/33298074#33298074

Basically, we need to see the CSS for the @media print and set visibility: visible; and overflow: visible !important;
   
    @media print {
      .modal {
        position: absolute;
        left: 0;
        top: 0;
        margin: 0;
        padding: 0;
        visibility: visible;
        /**Remove scrollbar for printing.**/
        overflow: visible !important;
      }
      .modal-dialog {
        visibility: visible !important;
        /**Remove scrollbar for printing.**/
        overflow: visible !important;
      }
    }

I will put these down for documentation purposes. Modal is useful to serve as Print Preview for IE and firefox and so I think it is crucial for long contents (though users may not scroll all the contents before printing).

I am working for education sector so we need to print the list for students, so a good overview for Teachers are great! (save paper as well).

Anyways, this CSS will be a nice to have addition for people who needs to support printing.
