### ISSUE TITLE
$sce with Alerts still shows html

### ISSUE THREAD

**Issue by ProdigyView** [angular-ui/bootstrap#4675]
Basically I am getting a response back from the server and implementing the response into the alerts array, but it shows the html that is passed back from the server.

    Messages.save({}, data, function(response) {
			window.location = '/accounts/read/' + response._id.$id;
		}, function(response) {
			
	 	$scope.alerts.push({ type: 'danger', msg: $sce.trustAsHtml(response.data) });
			
		});

How do I ensure that the divs passed back get rendered as html?

**Comment by icfantv** [comment]
@ProdigyView, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.
