### ISSUE TITLE
Custom Format for datepicker combined with ngRequired causing issues with binding

### ISSUE THREAD

**Issue by codenewa** [angular-ui/bootstrap#4678]
Libraries:
Angular JS: v1.4.7
Angular JS animate: v1.4.7
Angualr ui: 0.14.2

Here's the [plnkr](http://plnkr.co/edit/OlVM23mm7rn89lBJhA9a?p=preview)

So far, I have seen this issue only when format is provided with `uib-datepicker-popup` and it also includes a `ngRequired` expression. As you can see in the plnkr, the date field disappears from the model.

So, the snippet will work properly if you remove
`ng-required="data.config.dob.isRequired"`
or, change
`uib-datepicker-popup="MM/dd/yyyy"` to `uib-datepicker-popup`

One more observation was that this affects all other datepickers on the page whether or not they have the format and `ngRequired` combination.

This might be related to: #4607

**Comment by icfantv** [comment]
Currently evaluating options here, but as noted, the demo is working fine.  The issue appears to be setting  a hard-coded string in `uib-datepicker-popup` vs. setting via a scope variable.  For now, you can use that as a work around.

**Comment by icfantv** [comment]
@codenewa, this was fixed in #4635.  To get all the fixed goodness, you can do a snapshot build of `master` by running the `npm install` and `grunt` commands.

**Comment by icfantv** [comment]
Duplicate  of #4616 and #4607.
