### ISSUE TITLE
Tab disabled issue, new feature sugestion

### ISSUE THREAD

**Issue by beeseenmedia** [angular-ui/bootstrap#4680]
lets say we have tabs [x, y, z, settings]
if there is any issue with the settings then settings should be pre-selected. you can set active=true or bind it to a true variable, this works ok.

but what if you want to at the same time disable the rest of the tabs.  in this case, with the available methods you would do [x,y,z] disabled on error true and [settings] active on error true.  this binds error to settings. if there is an account with no error and you click on settings, because it is binded active (error) becomes true and disables the rest of the tab.
 
a pre-selected feature would work better in this case.  you would set [x,y,z] to disabled on error, and pre-selected on error. this eliminates the previous issue as pre-selected would not bind the variable.

**Comment by icfantv** [comment]
There is no restriction on how tabs are created, in fact, using a scoped array of JSON objects to define your tab behavior is how our demo works.  One could easily add a `disabled` field and use `$watchCollection` to monitor for changes.  Then you can set the field value as you wish.

This is such a specialized use case, this is not something we will be able to support.
