### ISSUE TITLE
tooltip increases the length of the page

### ISSUE THREAD

**Issue by StennikovDmitriy** [angular-ui/bootstrap#4682]
I have found that when the tooltip disappears for a moment the page length is increased by the tooltip element height.
Tooltip configured with appendToBody: true
```javascript
$uibTooltipProvider.options({
            placement: 'top',
            animation: false,
            popupDelay: 0,
            appendToBody: true
        });
```
Markup is trivial
```html
<a href="#" class="btn blue" uib-tooltip="Edit">
    <i class="fa fa-edit"></i>
</a>
```
Tooltip element at this moment (when it disappears) looks like:
![screenshot_12](https://cloud.githubusercontent.com/assets/15243363/10658626/187be6fa-78b2-11e5-8de2-2385cac14aef.png)

Normally, the the element has a style: `style="visibility: visible; display: block; top: 513px; left: 1688.25px;"`
`visibility:hidden` in fact, it does not hide the the element and it appears at the end of the page. The page length increases, for a moment appears a scroll bar.

I think should be `display:none` instead of `visibility:hidden` or just don't remove `top` & `left` position.

**Comment by StennikovDmitriy** [comment]
ui-bootstrap: 0.14.2
Bootstrap: 3.3.4
angular: 1.3.16

The obvious hotfix:
```css
.tooltip { top: 0; }
```

**Comment by RobJacobs** [comment]
The tooltip service is used for both popovers and tooltips which have different css implementations.  Using display: none causes issues with measuring the popover height and width for top and left calculations.  Recent PRs #4621 and #4623 attempt to put this issue to rest once and for all.
