### ISSUE TITLE
Tabs - vm is undefined in tabset 

### ISSUE THREAD

**Issue by talor1981** [angular-ui/bootstrap#4686]
Hi,
I created angularjs directive with 2 buttons (ok, cancel).
When i put the directive in tabs and click on ng-click button event i recived:
"vm is undefined". The ng-click event fired angularjs controller method
If i put the directive not in tabs - it works well.
Why?

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive and https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
