### ISSUE TITLE
Getting date picker to recognize YYYYMMDD format?

### ISSUE THREAD

**Issue by uberspeck** [angular-ui/bootstrap#4691]
We have legacy birth date data in the format of YYYYMMDD (20151022). Angular and the ui-bootstrap date picker obviously don't like this format. Also, our new UI requirements are to display the format as MMM, d YYYY (Oct, 22 2015). I'm not seeing a way to enforce a non-standard date format (for data, not for display) in the documentation. Is this not supported or am I just overlooking it?

**Comment by icfantv** [comment]
@uberspeck, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.
