### ISSUE TITLE
Is there a way to disable one-time binding for day labels?

### ISSUE THREAD

**Issue by Badabum** [angular-ui/bootstrap#4692]
I tried to dynamicaly change locale in datepicker following this approach: 
```javascript
 angular.module('ui.bootstrap.datepicker')
.config(function ($provide) {
    $provide.decorator('datepickerDirective', function ($delegate) {
        angular.forEach($delegate, function (directive) {
            var originalCompile = directive.compile;
            var originalLink = directive.link;
            console.log($delegate);
            if (originalCompile) {
                directive.compile = function () {
                    return function (scope, element, attrs, ctrls) {
                        var datepickerCtrl = ctrls[0];
                        scope.$on('$localeChangeSuccess', function () {
                            scope.move(0);
                            datepickerCtrl.refreshView();

                        });
                        originalLink.apply(this, arguments);
                    };
                }
            }
        });
        return $delegate;
    });
});
```
But I found that this is not working because of one-time binding for day labels. So is there a way to disable one-time binding without the need of modifying template? I use 0.13.2 version.

**Comment by wesleycho** [comment]
I would recommend modifying the template for now - this is a valid feature request for adding support for i18n updating of the view, so I am tagging this with the fresh i18n label.

**Comment by sandeepthomas** [comment]
Can someone please explain what modification needs to be done in the template to translate datepicker?

**Comment by icfantv** [comment]
@sandeepthomas, please don't hijack the thread and change the topic.  Questions like yours are best served (and answered) when posted to StackOverflow.  Please see our instructions [here](https://github.com/angular-ui/bootstrap#need-help).  Thanks.

**Comment by Badabum** [comment]
@sandeepthomas , just delete one time bindings ('::') for day labels. Also you need to reload datepicker when locale changed if you use angular-translate lib.

**Comment by Badabum** [comment]
@sandeepthomas , just delete one time bindings ('::') for day labels. Also you need to reload datepicker when locale changed if you use angular-translate lib.

**Comment by wesleycho** [comment]
Closing this in favor of #4626, I have figured out a solution to this issue that will be implemented as detailed there.

**Comment by zsitro** [comment]
Just `$scope.$watch` for  value changes and broadcast a calendar redraw with help of this guide: https://gist.github.com/cgmartin/3daa01f910601ced9cd3
