### ISSUE TITLE
Date picker field does not prepopulate if format is supplied

### ISSUE THREAD

**Issue by riankruger** [angular-ui/bootstrap#4696]
I am using:

angular v1.4.7
with bootstrap templates 0.14.2

I am prepopulating the model in my controller with the following:

```$scope.dt = new Date();```

The date field is not prepopulated, it only shows a value once I have opened the picker and selected a date.

Here is the markup that is not working:

```<input type="text" class="form-control" uib-datepicker-popup="yyyyMMdd" ng-model="dt" is-open="showCalendar" ng-required="true" close-text="Close" />```

If I remove the format it does prepopulate:

```<input type="text" class="form-control" uib-datepicker-popup ng-model="dt" is-open="showCalendar" ng-required="true" close-text="Close" />```

**Comment by Foxandxss** [comment]
That got fixed with 7c3c6. We will release soon.

**Comment by icfantv** [comment]
@riankruger, please search both open and closed issues before entering new ones as this one has been reported about a half-dozen times.
