### ISSUE TITLE
Datepicker: uib-datepicker-popover format works only via $scope

### ISSUE THREAD

**Issue by zauker** [angular-ui/bootstrap#4699]
It seems format works only with a variable on $scope, if i set a String or quoted String it doesn't work.

__works__

    <input type="text" class="form-control" uib-datepicker-popup="{{format}}" />

__doesn't works__

    <input type="text" class="form-control" uib-datepicker-popup="dd-MMMM-yyyy">

    <input type="text" class="form-control" uib-datepicker-popup="'dd-MMMM-yyyy'">

i made a plunker to test this issue
http://plnkr.co/edit/2pKx9jHjCDm7DjI91oqf?p=preview

**Comment by icfantv** [comment]
@zauker, in the future please do a search on open and closed issues before entering an issue.  This has been fixed in `master`.
