### ISSUE TITLE
I have a suggestion.

### ISSUE THREAD

**Issue by Ansrala** [angular-ui/bootstrap#4705]
This might not be the best place for this but not sure where else to put it.
https://angular-ui.github.io/bootstrap/

on this page could you list what version each property or option was created in?

**Comment by icfantv** [comment]
@Ansrala, we here on the Angular UI Bootstrap team like to think of ourselves as pretty brilliant individuals but sadly, we are not omniscient, nor can we read minds.  Thus, we must ask you to tell us your suggestion.

**Comment by icfantv** [comment]
@Ansrala, not on that page, no.  But, you can look at [the CHANGELOG](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md) to see that information.

In fact, it's a really good idea to view the CHANGELOG when upgrading - taking an especially good look at the **Breaking Changes** section.
