### ISSUE TITLE
uib prefix for all constants isn't listed as a breaking change

### ISSUE THREAD

**Issue by esditm** [angular-ui/bootstrap#4724]
Prefixing constants with uib is a breaking change and somehow it's absent from the CHANGELOG.md file.

I'm not sure what version made this change. Else could make a PR.
All I know is that it happened between 0.13.3 and 0.14.3

**Comment by wesleycho** [comment]
It is not a breaking change - the old prefixes still work.

The breaking change will be in 1.0 when the unprefixed directives/services are removed.

If the unprefixed directives/services are not working, please post a Plunker.

**Comment by esditm** [comment]
Odd, the non-prefixed names didn't work for me. Angular couldn't find the provider datepickerConfig.

Updated angular from 1.4.4 to 1.4.7 and ui-bootstrap from 0.13.3 to 0.14.3 and the following broke:

`app.config(['datepickerConfig', func...`

When I changed it to 

`app.config(['uibDatepickerConfig', func...` everything was fine.

I created a plunker.

http://plnkr.co/edit/XiYKQFKvPt1t7jcEogth?p=preview running ui-bootstrap 0.13.3 with non prefixed names. Works.

http://plnkr.co/edit/ZuCCsSKGwgi83EJgeOj1?p=preview running ui-bootstrap 0.14.3 with non prefixed names. Broken.

http://plnkr.co/edit/stTmopB2QzYfwRNaWoVO?p=preview running ui-bootstrap 0.14.3 with prefixed names. Works.

**Comment by esditm** [comment]
@wesleycho see my previous post

**Comment by wesleycho** [comment]
The constants are prefixed, and I guess technically a breaking change, but a minor one - it only is breaking if one is overriding the constant through $provide, which is a bit of a hack.

**Comment by icfantv** [comment]
@esditm, we've removed all the deprecated code in `master` in preparation for the 1.0 release - I would strongly encourage you to test again with a build off of that and we can go from there.

**Comment by esditm** [comment]
I already changed my code to use the prefixed constants. I merely made this issue so others would be aware of it when going through the changelog to see if anything would break when upgrading :)

Also be able to find this issue when googling why their `datepickerConfig` couldn't get injected anymore
