### ISSUE TITLE
Datepicker modal is broken in a table-responsive column when wrap in an input-group

### ISSUE THREAD

**Issue by cyrilgandon** [angular-ui/bootstrap#4732]
Conditions:
 - wrap a table into a responsive table
 - create a cell with a DatePicker
 - wrap the input of the DatePicker into a div input-group

Problem:
 - open the modal then triggered the responsivness of the table and the modal is wrap inside the table

What can fix the problem: 
 - remove input-group classes seems to resolve the problem
 - use attribute 'datepicker-append-to-body' (use only if you don't plan to use DatePicker in a Modal, which is not my case)

http://plnkr.co/edit/udn0qTc8CMjg6zrP1LkJ?p=preview

**Comment by RobJacobs** [comment]
Use:

    datepicker-append-to-body="true"

**Comment by cyrilgandon** [comment]
@RobJacobs : as I've said, this is not an option.
I'm using the DatePicker in a Modal, so if the DatePicker modal is appened to the body, when it is open, the DatePicker modal is behind the main Modal.
I don't know if this is a supported use case, because multiple modal is not supported, but the DatePicker is more a popover, not a 'real' modal.

**Comment by RobJacobs** [comment]
I apologize, I didn't see that comment about using the append-to-body feature.

**Comment by icfantv** [comment]
@RobJacobs, is there anything we need to do here or can we close this?

**Comment by RobJacobs** [comment]
@icfantv I don't think so, but I already prematurely closed this so I was giving @cyrilgandon a chance to respond.

**Comment by icfantv** [comment]
Ok, sounds good.  Thanks.

**Comment by cyrilgandon** [comment]
The fix works fine, ty!
