### ISSUE TITLE
Cannot globally configure datepicker

### ISSUE THREAD

**Issue by chaaya** [angular-ui/bootstrap#4733]
The global configurations that are set are not used when opening the datepicker popup.
When debugging the code the configuration object do change the property values but then in datepicker init it still has the constant values from the injected datepickerconfig object.

Plunker example: http://plnkr.co/edit/P4cMQqtFpHJAjx6k8FPI?p=preview

**Comment by icfantv** [comment]
@chaaya, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

Per [the documentation](http://angular-ui.github.io/bootstrap/#/datepicker), `close-text` and `clear-text` are properties on `uibDatepickerPopupConfig` and not `uibDatepickerConfig` as you have in your plunker.

**Comment by chaaya** [comment]
Oh my bad, but I honestly thought it was a bug. Thanks anyways!

**Comment by icfantv** [comment]
No worries.  This is why [we ask you](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug) to submit a plunker that demonstrates the problem because 95% of the time, it's user error and a plunker (usually) easily shows that.
