### ISSUE TITLE
Buttons: Radio: uib-btn-radio vs btn-radio: documentation out-dated!

### ISSUE THREAD

**Issue by janppires** [angular-ui/bootstrap#4735]
Hi!

I have just wasted 2 hours of work trying to figure out why the radio button wasn't working! I am using the version 0.13.3 and trying to use the uib-btn-radio directive. Your 'migration guide' stands for 0.14.0 > versions. And your example is using 'uib-btn-radio'. There is a big confusion here. Please highlight a comment near the example, for the people to be aware of the changes.

Thanks!

**Comment by icfantv** [comment]
@janppires, I'm sorry you're frustrated and wound up wasting time.  The latest version is displayed at the top of the demo page [here](http://angular-ui.github.io/bootstrap).  Additionally, you'll notice we've added a new menu item to view the docs to the previous version.

As a developer, the onus is on you to ensure the docs you are reading match the version of whatever library you happen to be using.

As far as a migration guide goes, which one are you looking at?  [Ours](https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes) documents the version number at the top.  Another good resource you might be interested in is [our changelog](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md) which documents everything that goes into a release.  You should pay particular attention to the BREAKING CHANGES sections.

**Comment by janppires** [comment]
Thank you for the quick answer!

The thing is that the version 0.13.3 downloaded using bower only works with the 'btn-radio' directive. And according with the breaking changes you pointed this only should happen in the 0.14.0! And the example http://angular-ui.github.io/bootstrap/#/buttons stills uses a very old version 'uib-btn-radio'. Does this make sense?

**Comment by icfantv** [comment]
Actually, it doesn't make sense.  What bower package are you using?

**Comment by janppires** [comment]
Cool! It doesnt make sense to me as well! =) 

"angular-bootstrap": "0.13.3"

**Comment by icfantv** [comment]
I meant that what _you_ typed doesn't make sense.  The `uib-` prefix was _added_ to our directives in 0.14.0, not removed - there's nothing "very old" about it - it's not even 20 days old at this point.

My understanding of what you wrote was that you were using 0.13.3 but using the latest version of the on-line documentation rather than the release-specific version and were frustrated why your code wasn't working.

**Comment by janppires** [comment]
Ok! Now I understand everything. My apologies for making you waste 2 hours on this thread! =) In my head I was expecting the uib prefix to be removed in recent changes. Dont ask me why =). 
Everything matches. The documentation is correct and the breaking changes too.
