### ISSUE TITLE
DatePicker - Internet Explorer switching month display issue

### ISSUE THREAD

**Issue by RobWright** [angular-ui/bootstrap#4741]
When using IE, if we change month by clicking on a visible day of the next/previous month (as opposed to using the month picker) then we temporarily see two calendars - one for each month before the previous month is hidden.

This is reproducible on the main angular material website:
https://angular-ui.github.io/bootstrap/#/datepicker

You can see this in the image below, captured at the exact moment of changing from one month to the next (by clicking on a day visible from the next month)

<img width="382" alt="datepickerdoublemonth" src="https://cloud.githubusercontent.com/assets/10189629/10751431/373a19b0-7cbb-11e5-804d-2a6edf5ca0cf.png">

**Comment by Foxandxss** [comment]
What IE version is that?

**Comment by RobJacobs** [comment]
Reproduced with IE11, only happens on first transition.

**Comment by wesleycho** [comment]
Strange...could this be an ng-animate bug with ng-repeat? I don't see anything that raises a flag on our end.

**Comment by RobWright** [comment]
Just to confirm, I am seeing this in IE11.  This doesn't occur on every transition, but I do see it more often than just the first transition.

**Comment by wesleycho** [comment]
Going to close this as a duplicate and continue tracking in #5446 - Angular seems to potentially be the culprit though.
