### ISSUE TITLE
Why doesn't cursor change to pointer/hand on Tabs, Pagination, Dropdown Toggle etc in angular-ui-bootstrap?

### ISSUE THREAD

**Issue by sgon00** [angular-ui/bootstrap#475]
I have to add the following code:

```
<style type="text/css">a {cursor:pointer;}</style>
```

to make cursor change to pointer/hand on links for Tabs, Pagination, Dropdown Toggle etc.. in angular-ui-bootstrap.

Why doesn't it change to pointer by default? Is this done intentionally? this is not the normal case in pure bootstrap. 

Thanks a lot.

**Comment by innatewonderer** [comment]
Found this useful:
https://docs.angularjs.org/api/ng/directive/ngHref

By adding `href: ""` to my `a` tag, I was able to get `cursor: pointer` to show up.
