### ISSUE TITLE
urgent urgent urgent urgent urgent urgent urgent urgent urgent urgent urgent

### ISSUE THREAD

**Issue by allendongyx** [angular-ui/bootstrap#4750]
http://plnkr.co/edit/WXGMkC5mUvC03NrQSk06?p=preview

don't work

**Comment by wesleycho** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem - please add more of a description & a descriptive title, a title like this without detailed information is not helpful.

This repository is for legitimate verified bugs and feature requests, not support.
