### ISSUE TITLE
carousel don't work

### ISSUE THREAD

**Issue by allendongyx** [angular-ui/bootstrap#4751]
http://plnkr.co/edit/WXGMkC5mUvC03NrQSk06?p=preview
angular 1.4.7

**Comment by allendongyx** [comment]
This version is right
https://github.com/angular-ui/bootstrap/blob/8899fc8e850d227a8dd384d61f7a092bf7471ef6/src/carousel/carousel.js

**Comment by RobJacobs** [comment]
Dude, do you even open source?

**Comment by icfantv** [comment]
@allendongyx, I'm not really sure what you're attempting to accomplish.  [Our demo](http://angular-ui.github.io/bootstrap/#/carousel) is working fine.

Perhaps if you gave us more information we can point you in the right direction.  Until then, I'm closing this issue.  Thanks.
