### ISSUE TITLE
Do something with uib-dropdown-menu

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#4753]
I don't like it being a class directive, people gets confused on the consistency of having to prefix that one class or not.

I propose to change it for 1.0.0

**Comment by Nieralyte** [comment]
I got confused when came across that prefixed class name. I didn't realize it's a directive, and thought it's just some custom override, and didn't know if i should be prefixing all classes in ui-bootstrap or not.

**Comment by wesleycho** [comment]
I'm fine with changing it - I think class directives make less sense with the prefixing.
