### ISSUE TITLE
uib-accordion is not working #4726

### ISSUE THREAD

**Issue by tempx** [angular-ui/bootstrap#4754]
Since I cannot re-open a closed issue, I had to open a new issue. Please refer to #4726, whihc is closed but not-solved! Here is my response to @icfantv. Please respond accordingly. Regards,

Hi @icfantv, thank you very much for your answer. Unfortunately I can not give the punker link since it is not provided in the website. However, I can describe how to get the files: when you go the "Accordion (ui.bootstrap.accordion)" section click on the "Edit on plunker" button and then download to files to your locale and try to run the index.html. You will see that the supplied accordion code is not working.

I am not using the of mine, rather the code supplied in the website. There may be a problem with the files you have uploaded or there may be a bug in the accordion. Can you please recheck the code and the files you have provided in the website?

Regards,

**Comment by Foxandxss** [comment]
Please, you don't need to create a new issue when you want to add an answer to a closed one. We can read your comments on the closed one.
