### ISSUE TITLE
Pagination changes current page to 1 when rendered

### ISSUE THREAD

**Issue by grubyrychu** [angular-ui/bootstrap#4755]
I update URL page parameter when pager is clicked
to something like this: http://localhost/#?q=security&limit=10&page=2 

When this URL is opened in a new page I am reading the page parameter from query and update $scope.currentPage so the page is switched to 2. This is working but after a while currentPage changes back to 1. It is not my code so I suspect pagination scripts.

here is [plunker](http://plnkr.co/edit/4tVZCuCIkqPzhvoa7ffN?p=preview) however I cannot add URL hash params in pluker and refresh page

**Comment by grubyrychu** [comment]
This is related to #2173

**Comment by wesleycho** [comment]
I don't see any pagination use - please put it in your Plunker if you have a reproduction.

It should be noted that there is a known issue previously reported in #2956 that may be related to your problem.

**Comment by wesleycho** [comment]
Assuming that the aforementioned issue is the problem, this is now fixed via 30099a0cd080936b22027d37c52b3b32f1fb3ad7
