### ISSUE TITLE
Not able to select date from ui-bootstrap Datepicker

### ISSUE THREAD

**Issue by rajendra3** [angular-ui/bootstrap#4756]
Hello,

I am not able to select date from ui-bootstrap Datepicker. Always shows 2015-12-31 irrespective of any date selection .(Not showing any error on console)
I have used  below dependencies for it  - /bootstrap-3.3.4/bootstrap.min.css
/bootstrap-3.3.4/bootstrap.min.js

Please find below implementation of code -

HTML Code - 
 <div class="row">

				<!-- <div class=" col-2 text-right">
					<label translate="FromDate"></label>
				</div>
				<div class="col-3">		
					<p class="input-group">
						<input type="text" id="searchStartDate"
							datepicker-popup="{{'dateToFormat' | translate}}" ng-model="search.date.start.value"							
							is-open="search.date.start.opened"
							close-text="Close"
							placeholder="{{ 'FromDate' | translate }}" /> <span
							class="input-group-btn">
							<button type="button" class="btn btn-default"
								ng-click="open($event, 'start')">
								<i class="glyphicon glyphicon-calendar"></i>
							</button>
						</span>
					</p>
					</div>	
			</div> 

controller js code - 

				    	 /* UI-DatePicker configuration */
				    	$scope.reset = function () {
					    	$scope.search = {
					    			fields: {},
					    			date: {
					    				start: {
					    					opened: false
					    				},
					    				end: {
					    					opened: false
					    				}
					    			}
					    	};
				    		
				    	};
				    	$scope.reset();
						
						// Disable weekend selection
						$scope.disabled = function(date, mode) {
							return ( mode === 'day' && ( date.getDay() === 0 || date.getDay() === 6 ) );
						};
						
						$scope.open = function($event, opened) {
							$event.preventDefault();
							$event.stopPropagation();
							$scope.search.date[opened].opened = true;
						};
						
						$scope.dateOptions = {
								startingDay: 1
						};

Kindly provide solution for it ASAP.

Thanks!!

**Comment by Foxandxss** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by icfantv** [comment]
@rajendra3, I feel compelled to also point out that asking us to help you debug your code ASAP is not a good way to ask for help.
