### ISSUE TITLE
Typeahead : attribute "typeahead-is-toggled" to know if dropdown is toggled

### ISSUE THREAD

**Issue by NicolasVargas** [angular-ui/bootstrap#4760]
Hi, 

I would like to know if the dropdown is open in order to change others elements behaviour during this time.
I didn't find any clean method to succeed.
The only solution I found was to check the dropdown attribute "aria-hidden" :
```
angular.element('.dropdown-menu').first().attr('aria-hidden')
```
but I don't really like it and the attribute change is not fired by angular when we click outside the dropdown.

What do you think about adding a new attribute to typeahead in order to bind a boolean to the ```isOpen()``` intern typeahead function.

Thank you,
Nicolas VARGAS

**Comment by wesleycho** [comment]
This seems like a reasonable request.
