### ISSUE TITLE
Datepicker shows curly braces on load

### ISSUE THREAD

**Issue by geoguide** [angular-ui/bootstrap#4769]
I'm not sure if it's because our application is running too slow but we get a lot of stuff like this:

http://new.tinygrab.com/5d87ec975c8022159ae9908dc57fa2011353e3b49c.png

When the date picker is loaded, any chance it could at least use ng-bind so that this doesn't happen? Am I missing a setting? I would hope it would be pre-loaded.

**Comment by icfantv** [comment]
Try putting `ng-cloak` on the element with the datepicker directive and see what that does.  Note that you will also need the `ng-cloak` CSS as [documented here](https://docs.angularjs.org/api/ng/directive/ngCloak).  Please let us know what that does.

**Comment by wesleycho** [comment]
It likely is performance related - the datepicker does have performance issues. We could switch to ng-bind, but I want opinions here, as we likely should do so for all of the templates then if we do, so this decision has ramifications.

**Comment by geoguide** [comment]
ng-cloak does not work because the datepicker directive loads and removes the ng-cloak, it's the generated datepicker that has the issue.

**Comment by geoguide** [comment]
I'm noticing this on other components also, I didn't notice it on my app, but I'm helping with another app that is slower and it's obvious in many places. Would my best bet to be to fork and change all the templates to ng-bind?

**Comment by icfantv** [comment]
@geoguide, ok.  that was just a stab in the dark anyway.

here's something else to try.  create a new directive whose template wraps the datepicker directive but adds a `$timeout` (in the `link` function) combined with a one-time binding of an `ng-if` block-level element wrapping theso there's no watch.  the $timeout will execute when the $digest cycle has finished - namely, when the datepicker directive has done building.  i.e., a template that looks like:

```
<my-directive ng-if="doneRendering">
  <uib-datepicker ...></uib-datepicker>
</my-directive>
```

Note that you will most likely NOT want this to be an isolate scope directive as doing so will have ramifications when used inside components like tabs and accordions.

**Comment by wesleycho** [comment]
Closing, as I don't think there's much more we can do here.

We could switch to ng-bind, but I think we've done a lot of work to improve the perf. If we see any more issues on it, we can always go that route down the road.
