### ISSUE TITLE
Typeahead docs don't use the "uib" prefix

### ISSUE THREAD

**Issue by philBrown** [angular-ui/bootstrap#4771]
The docs still refer to the non-prefixed `typeahead` attribute ~ https://angular-ui.github.io/bootstrap/#/typeahead

**Comment by icfantv** [comment]
Thanks for this.  We're currently scrubbing the docs in preparation for the 1.0 release.

**Comment by wesleycho** [comment]
Good catch indeed - will fix momentarily.

**Comment by wesleycho** [comment]
Addressed by 468d68ac6b89ad15b408cadd8b2934c51309db5e
