### ISSUE TITLE
$watch form inside a uib-tab

### ISSUE THREAD

**Issue by AndreasHo** [angular-ui/bootstrap#4787]
Hello,

i have following problem...

i have an uib-tabset with ng-include templates inside my uib-tab. In my Controller for this side i want to watch over angular on my <form> inside the template. But this doesn't work with tabs..

My Form get undefined in $scope...

This is my $watch method:
$scope.$watch('anmeldungDetailsForm.$valid', function() {
        console.log($scope.anmeldungDetailsForm.$valid);
    });

Following is a short example of my HTML code, which is my problem...
`<uib-tabset>`
    `<uib-tab active="true" heading="Maske">`
        `<div ng-include src="'mask.html'"></div>`
    `</uib-tab>`
`</uib-tabset>`

I hope you can help me :)

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive
