### ISSUE TITLE
Carousel support for event emittion

### ISSUE THREAD

**Issue by Forusim** [angular-ui/bootstrap#4788]
Using the carousel for more complex elements than just images, i need events for Slide and SlideAnimationEnd.
As a far as I understood, the current (0.14.3) version does not support them.
So I modified the goNext function to get them on my own.

```javascript
    $scope.$emit('uibCarousel:onSlide');
    angular.extend(slide, {direction: direction, active: true});
    angular.extend(self.currentSlide || {}, {direction: direction, active: false});
    if ($animate.enabled() && !$scope.noTransition && !$scope.$currentTransition &&
      slide.$element && self.slides.length > 1) {
      slide.$element.data(SLIDE_DIRECTION, slide.direction);
      if (self.currentSlide && self.currentSlide.$element) {
        self.currentSlide.$element.data(SLIDE_DIRECTION, slide.direction);
      }

      $scope.$currentTransition = true;
      if (NEW_ANIMATE) {
        $animate.on('addClass', slide.$element, function(element, phase) {
          if (phase === 'close') {
            $scope.$currentTransition = null;
            $animate.off('addClass', element);
            $scope.$emit('uibCarousel:onSlideAnimationEnd');
          }
        });
      } else {
        slide.$element.one('$animate:close', function closeFn() {
            $scope.$currentTransition = null;
            $scope.$emit('uibCarousel:onSlideAnimationEnd');
        });
      }
    }
```

Would like to know, if this implementation is right. 
Are there any plans to add more event emitters to the libraries components?

**Comment by wesleycho** [comment]
This is better implemented via a custom directive with negative priority using `$animate.on('addClass', ...)` there.

This is not a feature we want, since it is easily pluggable on the user's side & it has performance implications to all consumers.

**Comment by Forusim** [comment]
Thank you for the feedback.
I need these events in a parent directive, which creates the markup for the carousel.
I would appreciate, if you could point to me a good example for your proposal.
Thanks in advance!

**Comment by wesleycho** [comment]
Something like [this](http://plnkr.co/edit/MCp2Tl85kqswl4sKadW4?p=preview)
