### ISSUE TITLE
Docs and demos revamp

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#4798]
For 1.0.0 I am revamping all the documentation to put it up to date with more examples and all the possible settings explained properly.

- [x] Accordion
- [x] Alert
- [x] Buttons
- [x] Carousel
- [x] Collapse
- [x] Dateparser
- [x] Datepicker
 - [x] `starting-day` needs to be in config object per #3970.
 - [x] `datepicker-mode` needs improved wording & example #2301
- [x] Dropdown
- [x] Modal
- [x] Pager
- [x] Pagination
- [x] Popover
 - [x] `popover-is-open` needs an example
- [x] Position
- [x] Progressbar
- [x] Rating
- [x] Tabs
- [x] Timepicker
- [x] Tooltip
 - [x] `tooltip-is-open` needs an example
- [x] Typeahead
  - [x] Min-length 0 needs an example

Revise https://github.com/angular-ui/bootstrap/issues/4494

**Comment by wesleycho** [comment]
Linking #3687 for reference as needing to be done for the tooltip/popover.

**Comment by wesleycho** [comment]
We should document the dateparser as well - a text block is ok, this does not need a demo.

**Comment by Foxandxss** [comment]
Mixed feelings since it is an internal component. If I do docs, I do demo as well. There is a test.html inside dateparser (that I thought about deleting) that has some demos. I could do something, I don't know.

**Comment by wesleycho** [comment]
I just thought about it, but I understand - the problem is that we don't have anything documenting its functionality, so it may be trickier for developers to figure out what date formats we support and how they should behave without source code diving.

**Comment by Foxandxss** [comment]
Oh, nevermind what I said mate. I was thinking about position for some reason which could use love as well.

**Comment by drKnoxy** [comment]
@Foxandxss any update on this? I just went through `dropdown` with some pain searching through the repo to understand what each directive did. I'd be glad to lend a hand. Is there a feature branch going? Any specific requests / styles to adhere to for the doc, or just follow the contrib.md

**Comment by Foxandxss** [comment]
This is in master so the doc you see in the main page is not updated at all.

If you want to help, you can revise the ones I already did (dropdown and the previous ones alphabetically) to see if I missed something or the explanations could be better. I prefer to revamp them by myself because I have all the ideas in mind.

Thanks.

**Comment by sumeetsonawane11** [comment]
Facing Multiple popup  [issue:](`url`)

I am facing uib-popover issue in which I am not able to hide the popup on mouseleave of an element.

I have multiple fields  in a page and for the ui-select dropdown when i select any value and moveout of the element, then the popup is still there.

![dropdown buttons](https://user-images.githubusercontent.com/22935051/38767409-08c00f46-3ffe-11e8-9446-82addc3f8637.png)

I want current popup to hide when moving to another element
Attached the screenshot for reference
