### ISSUE TITLE
uibDatepickerPopup could not format as desired

### ISSUE THREAD

**Issue by sereysopheak** [angular-ui/bootstrap#4799]
I would like to change format of uibDatepickerPopup when using {{dateValue}}.

In version 0.12.1 I can archive it by creating a filter as bellow but no luck for new version.
angular.module('app')
.directive('datepickerPopup', function(dateFilter) {
  return {
    restrict:'A',
    require: 'ngModel',
    link: function(scope, element, attrs, ngModel) {
      ngModel.$parsers.push(function(value) {
        return dateFilter(value, "yyyy-MM-dd'T'HH:mm:ssZ");
      });
    }
  }
});

Could you kindly help this out? I'm stuck with this and I do really want to use new UI available in new version.

**Comment by Foxandxss** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
