### ISSUE TITLE
The demo page isn't openable when in Chinese region.

### ISSUE THREAD

**Issue by AdaJass** [angular-ui/bootstrap#4801]
I quite like this framework, but I'm a Chinese, some manual sites such as https://github.com/angular-ui/bootstrap#demo  are rejected by GFW.  Coz these sites quote resource from tweeter and google, we can't  reach neither of them, can you help me?

**Comment by Foxandxss** [comment]
Sure mate.

Clone this repository, install the dependencies:

```
$ npm install -g grunt-cli http-server
$ npm install
```

`http-server` is optional but helps you launching a server to read the docs.

Once you have your deps installed:

```
$ grunt html2js && grunt after-test
$ cd dist
$ http-server
```

Now just go to localhost:8080 and you can view your doc in there.

Hope that helps, but we cannot do anything else I am afraid.

**Comment by AdaJass** [comment]
thanks

**Comment by icfantv** [comment]
Man, that stinks.
