### ISSUE TITLE
The mismatch between GitHub version of file and version in Nuget package.

### ISSUE THREAD

**Issue by romka-04** [angular-ui/bootstrap#4815]
Dear comunity,

I found strange problem. 
The version in GitHub repository contains property appendTo of the modal options object
https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L685
in the same time in the version delivered by NuGet package this property is absent.
https://www.nuget.org/packages/Angular.UI.Bootstrap/
files ui-bootstrap.js and ui-bootstrap-tpls.js.
I used last version (at this moment) 0.14.3 - 2015-10-23 and nuget 0.14.3.

Do you have ideas why this versions are different?

Thanks in regards!

**Comment by pkozlowski-opensource** [comment]
While browsing code in this repo you've been looking at the master branch that has un-released code. Nuget has a released version - you can see source code for it at https://github.com/angular-ui/bootstrap/tree/0.14.3

**Comment by romka-04** [comment]
Thank you for fast response (I even didn't expect that it will be so fast)!
Looks like i found this commit: https://github.com/angular-ui/bootstrap/commit/16d854ca4c70aefb6b03faeb2a20105ce2bea8ec
Will wait for a new version!
