### ISSUE TITLE
after update angular-ui:$modal is now deprecated. Use $uibModal instead.

### ISSUE THREAD

**Issue by yuyongyu08** [angular-ui/bootstrap#4816]
update angular-ui to 0.14.3,there is a warning:$modal is now deprecated. Use $uibModal instead. How can i fix it?

**Comment by pkozlowski-opensource** [comment]
> How can i fix it?

Rename references from `$modal` to `$uibModal`?

**Comment by SenHeng** [comment]
I'm having similar issues.
The below errors appear when clicking on the `select element` tool in chrome dev tools. I've already gone through my entire codebase and can't find any instance of deprecated code in use.

```
dateParser is now deprecated. Use uibDateParser instead.
$position is now deprecated. Use $uibPosition instead.
dropdownService is now deprecated. Use uibDropdownService instead.
$modalStack is now deprecated. Use $uibModalStack instead.
$modal is now deprecated. Use $uibModal instead.
$tooltip is now deprecated. Use $uibTooltip instead.
typeaheadParser is now deprecated. Use uibTypeaheadParser instead.
```

**Comment by joh-klein** [comment]
I have the same issue. Did a `grep` of my complete project folder. I don't use $modal anywhere anymore. Yet it still warns me about using it.

**Comment by icfantv** [comment]
Hey guys, can you please do a build off of `master` and see what happens?

If the error goes away and your code works perfectly, then it sounds like we may have missed something.  But I strongly suspect your code will stop working and you may get errors in your console.  If that happens, then you've missed some directives.

Please let us know.

You can build master by pulling the repo and running `npm install` followed by `grunt`.

**Comment by SenHeng** [comment]
I'm not getting this issue on a separate machine, I'll check again when I get back to the office. I was quite sure I cleaned out both the npm_modules and bower_component folders though.

**Comment by icfantv** [comment]
Browser cache?  What are your Expires and Cache-Control headers set to for `.js` files?

**Comment by joh-klein** [comment]
To be clear, I made a custom build from your website with only the two modules I need (typeahead and modal). And if I do that right now again, the errors persist. (Btw. I get the same warnings in the console when I browse http://angular-ui.github.io/bootstrap/)

**Comment by joh-klein** [comment]
I am starting to get the feeling this is browser related (Chromium 45.0.2454.101 in my case) because there are times when I can not reproduce it.

**Comment by SenHeng** [comment]
It may have been the browser cache. I'm not getting the errors anymore.

If it matters, I'm using Chrome 46.0.2490.80 (64-bit) on the machine with the errors.

**Comment by icfantv** [comment]
Just a helpful tip that I use:  when doing development I leave my chrome debugger window open and leave the disable cache checkbox checked.  This counteracts the Expires and Cache-Control headers we set and allows newly built/deployed files to be picked up on a page reload.

**Comment by daric81** [comment]
I had this issue, turns out I was using angular-aside v 1.12 which refs $modal if this helps anyone.
