### ISSUE TITLE
typeahead options show 'undefined' 

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [angular-ui/bootstrap#4817]
I have a project with angular 1.3.15 and I just added angular-bootstrap 0.13.4

did a simple use of typehead and saw that all options show 'undefined'

debugging it a bit, it seems that template `typeahead-match.html` expects object with `label` field, but instead gets `model` which has `label` inside. 

what am I doing wrong?

**Comment by pkozlowski-opensource** [comment]
> what am I doing wrong?

No idea. Send a plunk so we can try to help you: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

You can fork one of our demo page.

**Comment by guy-mograbi-at-gigaspaces** [comment]
sure thing

http://plnkr.co/edit/PNLruPFH1ruFNtI1IECg?p=preview

**Comment by Foxandxss** [comment]
Please, use stackoverflow for questions. This is not an issue, you're just using the typeahead wrong. Try with `apps for apps in yourFunction()`. That should work.

**Comment by guy-mograbi-at-gigaspaces** [comment]
now I see it, thanks. drove me nuts. SO next time.. sure thing.
