### ISSUE TITLE
Carousel corrupted if render slides with ng-repeat and cnahge slide set.

### ISSUE THREAD

**Issue by sergik** [angular-ui/bootstrap#4823]
Carusel corrupted if render slides with ng-repeat and cnahge slides collsection. Slides animations throttled with internal flag $scope.$currentTransition. This flag prevents moving to next slide if carusel is in slide change process. When changing slides collection this flag leaves in true state and carusel is corrupted. See the example. http://plnkr.co/edit/FNijUvcOjsXocqmtP3bh?p=preview.
Press "kill me" and wait for a second. This example emulates fast 2 time change of an active slide.

**Comment by sergik** [comment]
could potentialy relate to https://github.com/angular-ui/bootstrap/issues/4667. Submitted a pull request for this: https://github.com/angular-ui/bootstrap/pull/4824

**Comment by mchurichi** [comment]
Here is another example of the same issue happening when you add a bunch of slides after the carousel has been fully loaded: http://plnkr.co/edit/NyG9yX?p=preview. This pull request doesn't solve the issue in this case.
