### ISSUE TITLE
Failed animation for uib-collapse when using a http request

### ISSUE THREAD

**Issue by declanelcocks** [angular-ui/bootstrap#4825]
I'm using a uib-collapse where the variable which toggles the state is set after receiving a http request. So I make a http request, and on success I set $scope.show to true, but the animation doesn't happen. Instead there will be a short lag, and the collapse instantly changes to open. If I move the show value to outside the http request (just after it) it will successfully animate the opening of the collapse, but I don't feel that's a good way to do it as I only want to open it if the http request was successful.

Is this an issue you've seen before with the collapse component?

**Comment by wesleycho** [comment]
Can you create a reproduction on Plunker? This is not enough information to go by, and it would be a. tremendous waste to go on a wild goose chase

**Comment by declanelcocks** [comment]
@wesleycho Of course, I will try to get a plunker up and running. It's a bit difficult to get one running exactly the same as my environment so I just wanted to check if you'd experienced this before.

**Comment by declanelcocks** [comment]
After investivating
