### ISSUE TITLE
Multiple slides in carousel

### ISSUE THREAD

**Issue by jsdevel** [angular-ui/bootstrap#4827]
I've been looking for a port of jcarousel in angular, but haven't found anything.  Ideally I'd like to use ui's carousel but it's fairly limited.  Is there any appetite for a PR that adds support for multiple slides?

**Comment by icfantv** [comment]
@jsdevel, what do you mean by multiple slides?  Can you please provide an example?  Thanks.

**Comment by jsdevel** [comment]
![carousel](https://cloud.githubusercontent.com/assets/2605980/10977389/fc8b544c-83ad-11e5-8606-56eb0d0f2ab3.png)

This can be viewed at http://www.republicservices.com/businesses on the top of the page.  Note that if you resize your window, the carousel shows fewer items.

**Comment by wesleycho** [comment]
This sounds much more like a pagination element than a carousel - you can probably just use the pagination directive with custom templates to accomplish this.

**Comment by jsdevel** [comment]
The issue with `pagination` is that the number of visible items must change based on screen width.  `jcarousel` implemented this nicely, but so far I haven't found a good angular solution.

**Comment by jsdevel** [comment]
> This sounds much more like a pagination element than a carousel - you can probably just use the pagination directive with custom templates to accomplish this.

Actually, in looking at the current implementation on my site, there are a fixed number of items!  Thank you so much for letting me know about `pagination`!

**Comment by jsdevel** [comment]
Have you guys considered `gitter` over issues?

**Comment by wesleycho** [comment]
Gitter runs too slow, but I recommend checking out the [Angular Buddies](https://angularbuddies.com/) Slack - there's a nice help channel for general support issues

**Comment by franbueno** [comment]
hi @jsdevel! Did you resolve it?

**Comment by jsdevel** [comment]
I ended up having to watch for window resize events and shuffle the items between the slides to make the correct width.  Not ideal, but it worked for our use case.
