### ISSUE TITLE
Pagination next & previous button function.

### ISSUE THREAD

**Issue by gopimr2** [angular-ui/bootstrap#4828]
I need to call a function in pagination pager directive, when i click next & previous button. how can i put the function for next & previous buttons, like ng-click (<pager next-button = "somefunction()" previous-button="fn()" ></pager>).

Or any other option available for this please suggest me.

**Comment by icfantv** [comment]
@gopimr2, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.
