### ISSUE TITLE
uib-typeahead static array ui-bootstrap-tpls-0.14.3.js Angular 1.4.7 match.label= undefined

### ISSUE THREAD

**Issue by choupa** [angular-ui/bootstrap#4829]
hello,

> It's not easy to reproduce this issue in plunker I'm trying ...

## 1. My issue
All "matches.label" are undefined.
![bug-uib-typeahead](https://cloud.githubusercontent.com/assets/11082253/10993622/610eca94-8470-11e5-8244-0fcbea62a445.png)

### The context:
Angular, angular-route , angular-animate: 1.4.7
uib-bootstrap-tpls-0.14.3

#### Template (ng-View) classifiedForm.html in main.html:

```html

<input id="marque" placeholder="Marque du produit" type="text" ng-model="classified.brand" uib-typeahead="brand for brands in brands | filter:$viewValue | limitTo:8" class="form-control">
..
 <pre>
        brands = {{brands }}
        Classified = {{ classified | json}}
    </pre>
```
#### client.js (module)
```javascript
'use strict'
var clientApp = angular.module('clientApp',['slugifier','ngResource','ngRoute','angularLoad','ngAnimate','ui.bootstrap']);
```

#### JS controller
```javascript
clientApp.controller ('Form_ctrlController', ['$scope','SCategories','SBrands',function ($scope,SCategories,SBrands){
     $scope.categories = SCategories;
     $scope.brands = ['ALibaba','ala','arli','test']; //SBrands;
}]);
```

#### route.js
```javascript
'use strict'
clientApp.config(['$routeProvider', '$locationProvider', function($routeProvider,$locationProvider){
    $routeProvider
        .when('/index.html',{templateUrl:'/template/index.html',controller:'Index_ctrlController'})
        .when('/formulaire.html',{templateUrl:'/template/classifiedForm.html',controller:'Form_ctrlController'})
        .when('/annonces',{templateUrl:'/template/search.html',controller:'Search_ctrlController'})
        .when('/annonces-:departmentId',{templateUrl:'/template/search.html',controller:'Search_ctrlController'})
        .when('/:keywordsId-annonces',{templateUrl:'/template/search.html',controller:'Search_ctrlController'})
        .when('/:keywordsId-annonces-:departmentId',{templateUrl:'/template/search.html',controller:'Search_ctrlController'})
        .otherwise({redirectTo:'/index.html'});
    $locationProvider.html5Mode(true); // remove # in url with <base href="/"> in main.html
}]);
```

#### server nodejs:
```javascript
var express = require('express');
var app = express();
app.get(/^(?!(?:\/api.*))/, function (req, res) { //TMP use regexp : all route define in angular but no /api/.*
       res.sendFile(__dirname + '/clientAPP/view/main.html');
});
```
## 3. My debug:
I think it's a scope issue in parserResult.viewMapper(scope,locals);
the var "brands" is in the scope.$id=8 and not scope.$id9 ...
Could  be fix it  with transclude in the directive? but in which directive? ... i'm trying ..
```javascript
 transclude(scope.$parent, function(clone, scope) {
        element.append(clone);
});
```
3.1. First: parserResult = OK
![bug-uib-typeahead1](https://cloud.githubusercontent.com/assets/11082253/10995578/2697dd84-847e-11e5-9eb6-ad7c894056df.png)

3.2.  "Transform Label" Scope Issue could be resolved with transclude method?
![bug-uib-typeahead2](https://cloud.githubusercontent.com/assets/11082253/10995747/65a4f3d0-847f-11e5-96a5-784cde17bbae.png)

> thanks

**Comment by choupa** [comment]
i have got it in Plunker !
[bug uib-typeahead](http://embed.plnkr.co/f3uKja8RVFxGhQOilRF9/preview)

**Comment by wesleycho** [comment]
Interesting - thanks for getting it in a Plunker. I don't think I would be able to investigate otherwise.

This certainly looks like a bug.

**Comment by wesleycho** [comment]
Linking with current `master` for convenience [here](http://plnkr.co/edit/RON73IwPKvI8WIvtSNAA?p=preview) - need to see what's happening here.

**Comment by RobJacobs** [comment]
The issue in the plunk is a result of a typo in how the typeahead options are declared:

    uib-typeahead="bug for bugs in bugs...

Should be

    uib-typeahead="bug for bug in bugs

Updated working [plunk](http://plnkr.co/edit/kbdkG2zXtKZrggwZUyi0?p=preview)

**Comment by choupa** [comment]
Pfff, i 'm so sorry ... Just for a "s" ...
Thank you very much ...
