### ISSUE TITLE
Naming of popover directives

### ISSUE THREAD

**Issue by ojosdegris** [angular-ui/bootstrap#4830]
Is there a particular reason why html-safe popover directive is `uib-popover` while html unsafe (one where you can actually use html in content) is `popover-html` ? 

There is also `popover-html-popup` which warns that it is depricated and I should use `uib-popover-html-popup` but I wasn't able to get any of these two working the same way `popover-html` works.

Should we rename `popover-html` and add alias with a warning similar to `popover-html-popup` ?

**Comment by icfantv** [comment]
@ojosdegris, Ok.  You got us.  Sometimes we just like to mess with our users.

But seriously, you should only be using one of the three main directives:  `uib-popover`, `uib-popover-html`, or `uib-popover-template`.  If you look at the [`tooltip.js` code](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L115-L128) you'll see we assemble a template using those `*-popup` directives internally.

Hope that makes more sense.

**Comment by ojosdegris** [comment]
Right, and because of the missing `uib-` prefix on `popover-html` it was not obvious how to use it.
I am sure I am not the only one with that issue , so what Is better for me to do? pull request docs to say use `uib-popover`, `popover-html`, or `uib-popover-template`
or pull request tooltip.js to rename `popover-html` to 'uib-popover-html` ?

**Comment by icfantv** [comment]
@ojosdegris, it's not at all clear what you're looking at.  there is no `popover-html` without the `uib` prefix either in the docs or the code.

**Comment by RobJacobs** [comment]
The only thing I can see is in the readme.md:

     uib-tooltip-html-unsafe  -- deprecated in favour of  tooltip-html

**Comment by icfantv** [comment]
Well, we should definitely fix that.

**Comment by icfantv** [comment]
I'll do the PR - I haven't done one in a while.  Getting rusty.
