### ISSUE TITLE
Cannot download 0.12.1 Unminified from website

### ISSUE THREAD

**Issue by lty83** [angular-ui/bootstrap#4832]
Does anyone have a link to the 0.12.1 unminified? The download on the website fails.

http://angular-ui.github.io/bootstrap/versioned-docs/0.12.1/

click download -> choose uncompressed -> click download -> failed - no such file

**Comment by icfantv** [comment]
So, I could be wrong, but I'm fairly certain that we never intended people to be able to download specific versions via the versions docs which is an oops on our part.

Your best bet is to check out the version tied to the 0.12.1 release and build it yourself.

**Comment by lty83** [comment]
Ahh yes... found it.. thanks much..

**Comment by wesleycho** [comment]
One can download the full version of the scripts through the gh-pages branch, but we otherwise dio not support actively a version that old.
