### ISSUE TITLE
Investigate fixing the tab api

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#4836]
We need to make a breaking change to fix how the tab API is handled. It is a much more awkward component to use than the accordion, which allows for more use cases.

In particular, we have bugs against the select callback api, and the active state should be kept at a higher level since we can only have one tab active at any given time.

API needs to
- [x] Expose active state separate from the tab object and into a single two-way bound value
- [x] Select in a more flexible manner
- [x] Allow passing in of `event` into select callback
- [x] Handle dynamically generated tabs gracefully with selection of first tab
- [x] Handle ng-if, ng-show, ng-hide gracefully
- [ ] Allow animate support with showing/hiding new tab (investigate content transcluding re: #4339)

**Comment by chenyuzhcy** [comment]
I have fix for one of the issue, should I just creat a pr and refer to the item or should I try to fix all of them and creat one pr for all?

**Comment by icfantv** [comment]
Using one PR for each and referencing this issue is fine - we won't close the issue until all the checkboxes are addressed.

We use the checkboxes in the description allow us to track progress separately and we've done this for other issues - adding the `uib-` prefix was one such issue.

**Comment by daniel-jann** [comment]
I guess "Allow passing in of event into select callback" was meant to address #2715 (A way to intercept tab change), but #2715 also mentions being able to prevent tab selection (I believe that's not been addressed yet, has it ?)

**Comment by icfantv** [comment]
@daniel-jann, #5720 was entered for this feature.

**Comment by wesleycho** [comment]
[Here](http://plnkr.co/edit/EAlCBsdE6fJLizNBA5NO?p=preview) is a demonstration of being able to animate using the current api.

Closing this as resolved.
