### ISSUE TITLE
Collapse animation stopped working when upgrading from 0.14.2 to 0.14.3.

### ISSUE THREAD

**Issue by LuizGsa21** [angular-ui/bootstrap#4846]
Collapse animation stopped working when upgrading from 0.14.2 to 0.14.3.
[demo 0.14.2](http://plnkr.co/edit/3adrgL0mDLUpxP8EZ6UR?p=preview)
[demo 0.14.3](http://plnkr.co/edit/CUnvqquRQWX5avkEV0x5?p=preview)
	
Undoing commit ([3144633][1]) fixes the issue.

[1]: https://github.com/angular-ui/bootstrap/commit/3144633

**Comment by wesleycho** [comment]
One has to use ngAnimate to get animation - see [here](http://plnkr.co/edit/fs1uTSd3i2EO6XSQjkid?p=preview)
