### ISSUE TITLE
Allow dynamic panel-class on accordion

### ISSUE THREAD

**Issue by Fidel90** [angular-ui/bootstrap#4847]
Hi,

I'd like to update my angular-UI from 0.12.0 to 0.14.3 and just stumbled accross the new panel-class introduced in 0.13.4. I have accordion groups with a dynamic changing class name and wanted to use the new panel-class instead of ng-class like before. But it turns that panel-class will only be evaluated once. I need to use it with angular bindings {{}}. I don't see why there's a need for this attribute anyway as we had ng-class for such things...

Btw: I've tried ng-class instead but that shows some buggy behaviour (at leat in 0.13.4). Being on the site where my accordion is everything works fine at first. But then, changing route to another page and then changing back to my accordion, the ng-class wont be applied again.

**Comment by wesleycho** [comment]
`ng-class` is not supported by angular on directives that use `replace: true`, and thus we do not support this usage.

If one really must bind this way, I recommend using `class="{{classBinding}}"` instead.
