### ISSUE TITLE
Accordion shows expanding animation when navigating to page

### ISSUE THREAD

**Issue by Fidel90** [angular-ui/bootstrap#4848]
Hello,

when my accordion group is initially opened with is-open attribute, navigating to the page shows the group expanding. I know this occurs since 0.13.4 or even earlier (I'm on 0.12.0 at the moment). I think this is is bad behaviour as something that is already opened, should not animate an opening animation when navigating to it.

**Comment by wesleycho** [comment]
Please reproduce with a Plunker.

**Comment by Fidel90** [comment]
Yes, ofcourse: http://plnkr.co/edit/BVsBM7XFWAhGDpj6xghz?p=preview

**Comment by wesleycho** [comment]
Closing, as this appears to be a duplicate of #4849

**Comment by wesleycho** [comment]
Reopening, as this actually turns out to be separate
