### ISSUE TITLE
Nested Modal Closing Parent

### ISSUE THREAD

**Issue by necrogami** [angular-ui/bootstrap#4852]
I've got a modal window which sometimes needs to open a child modal but when i cancel or submit the child it closest the parent as though i submitted it. How can i stop this from happening?

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by necrogami** [comment]
This should SERIOUSLY be under the support section as i searched for about 20 minutes before posting an issue. Currently the support section lists the FAQ and nothing else.

**Comment by icfantv** [comment]
@necrogami, which support section are you talking about?  It's listed in [this support section](https://github.com/angular-ui/bootstrap#support) and, more specifically, [here](https://github.com/angular-ui/bootstrap#need-help).

I'm not sure where you were searching for 20 minutes, but those above links are on our project's GitHub landing page (aka, `README.md`).

**Comment by necrogami** [comment]
This is where i was talking about the support section of the README on the github page https://github.com/angular-ui/bootstrap
