### ISSUE TITLE
$modal not being destroyed if state changes [ui-router]

### ISSUE THREAD

**Issue by jaybloke** [angular-ui/bootstrap#4854]
My modal attempts to retrieve json data via a resolve on the modal. If I get back a 401 response (unauthorised) via a response interceptor my app automatically presents a login modal - at least that's what it used to do before I moved to 0.14.3. With the latest version it appears that the first modal is never destroyed, and subsequent attempts to open *any* modal fail. Reverted back to the old version I was using before (0.13.3)... and all works good again.

Working nicely on 0.13.3: http://plnkr.co/edit/Vqx6XUeugyPtUfDmHYMh?p=preview

Naughty 0.14.3: http://plnkr.co/edit/nYRGPzgzK7btWERUDf8g?p=preview

Any clues?

**Comment by wesleycho** [comment]
This seems to be a user error - there is something bad happening when `return false` in the error interceptor is executed. One can see [here](http://plnkr.co/edit/vIqi7kl63eCGFhInCxhi?p=preview) non-breaking behavior by returning a rejected promise.

However, this seems to be user error with incorrect usage of UI Router. One should use the onEnter method to open the modal based on the example code, as shown [here](http://plnkr.co/edit/lkUKxl3TAPnuFZ1dv7Of?p=preview). If one does not want to route to a state, then there should never be any $state.go usage, as this is abuse of a $state transition.

In the future, please take the time to read the documentation for all libraries being used and explore the thought that the application design may have been incorrect. This is precisely a general support question. Understanding the apis being used is important, and it is an expected courtesy in general to do the research beforehand before attempting to escalate to an issue.
