### ISSUE TITLE
Popover directive does not raise events before and after open/close

### ISSUE THREAD

**Issue by akhilesh84** [angular-ui/bootstrap#4855]
Similar to the events available in bootstrap js, the tooltip and popover directive should expose events to be hooked on to in order to be able to execute custom code.

**Comment by pkozlowski-opensource** [comment]
-1 from me, I don't think we to expose event-based APIs. People can hook into whatever changed popover opening / closing.

**Comment by wesleycho** [comment]
I'm in agreement with @pkozlowski-opensource. Eventing offers an awkward API, and would take us down a rabbit hole of doing so everywhere in the library.
