### ISSUE TITLE
Dropdown outsideClick should close only when the whole click is made outside

### ISSUE THREAD

**Issue by ValentinH** [angular-ui/bootstrap#4856]
When using a dropdown with the `outsideClick` option, I think that it should only be closed when the whole click (mouseDown + mouseUp) is made outside the dropdown.

For instance, if I display a slider inside a dropdown, when the user drags the slider and releases it outside the dropdown, it is not cool to close the dropdown. In this case, the mouseDown event is inside the dropdown and then the mouseUp is outside.

What do you think of this idea?

**Comment by wesleycho** [comment]
This is jqLite/jQuery that is normalizing the click event. IMO, we should not mess with this. I would also avoid using a control like a slider inside of a dropdown, but that is an aside.

One could create a custom directive that requires programmatic opening & closing though to accomplish what you want though.

**Comment by ValentinH** [comment]
OK for the jQuery part.

_About the aside:_
I'm using dropdowns to make a toolbar in a photoshop like. When clicking a tool, a dropdown with a control appears and this control can be a text input, checkboxes or a slider. Why is it wrong to use a dropdown for this use case?
