### ISSUE TITLE
Datepicker doesn't validate value on the input where datepicker is applied

### ISSUE THREAD

**Issue by mikahakkarainen** [angular-ui/bootstrap#4858]
It is possible to type invalid date to the input where datepicker is applied. This causes error "Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.".

It would be nice if datepicker could validate the date typed directly to the input. This would make possible to let user give date by typing it to the input. Datepicker would prevent invalid date to be given to the input.

**Comment by wesleycho** [comment]
I don't think this is what we want - this would prevent users from typing the date from scratch.

For example, suppose the date was not preset. The user could type the date from an empty input - we do not want to prevent that.

If this is not what you mean, please explain clearly.

**Comment by mikahakkarainen** [comment]
I mean that user could type date to the input and datepicker would validate that given date. If date is not valid giving date is prevented (ie. input is reset for early value after focus moves out from the input or something else).

We have situation where we have datepicker applied to the input and input is disabled because otherwise it would be possible to type invalid date to the input which would cause errors. We would like to enable input so user would be able to type date to the input (addition to select it from the datepicker) and this is the point where validation should be done. It would be nice if datepicker itself could make validation and confirm that valid date is given to the input.

I am sorry because my English is not very good and clear but I hope you can understand me. :)

**Comment by wesleycho** [comment]
So the problem is that the validation on the input is completely user controlled - the input mechanism may not even be a text input, but it could be a more complicated control feasibly.

The datepicker does set validity. Is the problem that the validity is not propagating from the datepicker to the popup?

**Comment by wesleycho** [comment]
Closing due to lack of response.
