### ISSUE TITLE
debounce implementation doesn't pass arguments to debounced function

### ISSUE THREAD

**Issue by dfsq** [angular-ui/bootstrap#4859]
The current implementation incorrectly converts `arguments` collection into `args` array. As the result original function is invoked without arguments even if debounced function is called with some.

Here is the demo with the debounce code from original [commit](https://github.com/angular-ui/bootstrap/commit/73efc782e98123b6def5df85ec2875ab583cade2).
http://plnkr.co/edit/f1kCAlHOcVznlv3Yh5IG?p=preview 

Only the little thing is missing `Array.prototype.slice.call(arguments)` instead of `Array.prototype.slice(arguments)`. Try adding `call` in the demo above to see how it should work.

**Comment by dfsq** [comment]
By the way, this is still not fixed, after the fix was reverted in https://github.com/angular-ui/bootstrap/commit/1e19292b6b2d1953807d0c9b57292a8a4a8cedd2 commit.

**Comment by wesleycho** [comment]
Based on what I was told, it was by accident - undid the revert in dd6ddc8
