### ISSUE TITLE
Pagination buttons are not refreshed after Ajax data pull

### ISSUE THREAD

**Issue by hemantvikram** [angular-ui/bootstrap#4862]
Hi Friends,

From the below code, I 'm expecting that there should be 2 pagination buttons displayed for page 1 and page 2 respectively. But seems like the pagination control is not listening for the updates that I 'm doing. Can you please look at the code below and help me understand if I'm missing anything.

The following is my pagination control which is defined within my Controller "AngularPersonController"

<pagination boundary-links="true" max-size="3" items-per-page="itemsPerPage" total-items="persons.length" ng-model="currentPage" ng-change="pageChanged()"></pagination>

Below is the javascript code that I 'm using to pull the data and refresh the pagination control:

<script type="text/javascript" language="javascript">
    var angularPersonModule = angular.module("angularPersonModule", ['ngRoute', 'ui.bootstrap']);
    angularPersonModule.config(['$routeProvider',
        function ($routeProvider) {
            $routeProvider.
                when('/angularperson', {
                    templateUrl: '/angularperson/list',
                    controller: 'AngularPersonController'
                }).
                when('/angularperson/:id', {
                    templateUrl: '/angularperson/edit',
                    controller: 'AngularPersonController'
                }).
                otherwise({
                    redirectTo: '/angularperson'
                });
        } ]);

        angularPersonModule.controller("AngularPersonController", ['$scope', 'AngularPersonService',
        function ($scope, AngularPersonService) {
            $scope.persons = [];
            $scope.totalItems = $scope.persons.length;
            $scope.maxSize = 3; //Number of pager buttons to show
            $scope.currentPage = 1;
            $scope.itemsPerPage = 2;
            $scope.setPage = function (pageNo) {
                if ($scope.currentPage === pageNo) {
                    return;
                }

                $scope.currentPage = pageNo;
                alert("call from setPage");
            };

            $scope.pageChanged = function () {
                var i = 0;
            };

            $scope.getAll = function () {

                var promise = AngularPersonService.search({ PageSize: $scope.itemsPerPage, PageNumber: $scope.currentPage });
                promise.then(
                    function (payload) {
                        $scope.persons = payload.data.Data;
                        $scope.totalItems = payload.data.TotalRecords;
                    },
                    function (error) {
                        alert("load error" + error);
                    }
                );
            }

            $scope.getAll();

        } ]);

    angularPersonModule.factory("AngularPersonService", function ($http) {
        return {
            search: function (params) {
                return $http({ method: 'GET', url: '/AngularPerson/Search', params: params });
            }
        }
    });
</script>

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by hemantvikram** [comment]
Hi pkozlowski,
I have created plunkr showing the issue: http://plnkr.co/edit/t2oRxGLoHXwrP3rPx9lD?p=preview
From this plunkr, remove line 35: total-items="persons.length" and you will see that paging does not work.
