### ISSUE TITLE
"typeahead-on-select"    selection was by "Enter key" or "Mouse click"..

### ISSUE THREAD

**Issue by adnansaleemsse** [angular-ui/bootstrap#4867]
I have used type a head i have scenario where i want to differentiate selection by "Enter Key" or "Mouse click".
is there any way that i can know that selection was made my by enter or click..?

**Comment by icfantv** [comment]
@adnansaleemsse, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

**Comment by adnansaleemsse** [comment]
@icfantv can you please guide me on this if there is any way...?

**Comment by icfantv** [comment]
@adnansaleemsse, I'm getting all kinds of red flags here when you say you need to discern between how the user selects something from a typeahead.  What is your use case where you think you need to discern between events?

**Comment by adnansaleemsse** [comment]
i have my own Enter key event bind to text-box (on which i send text as message) i want to know if the Enter is on type a head selection then i can ignore my event binding.
i only want to ignore in case of Enter.
