### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by regisnew** [angular-ui/bootstrap#4869]
We should add an option to define the language of components.

**Comment by icfantv** [comment]
@regisnew, aside from the one-time binding of certain labels in the datepicker (see #4692), what component are you thinking needs i18n support?

**Comment by regisnew** [comment]
Datepicker

**Comment by icfantv** [comment]
Ok, I'm going to close this as a duplicate of #4692 then.  Maybe we decide to use this one over that one, but we don't want multiple issues tracking i18n of the datepicker.  Thanks.
