### ISSUE TITLE
Datepicker custom class on other modes

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#4873]
Custom classes are technically meant to be applied in all 3 modes (or that is what tests says) but it is only applied to `day` mode.

So it needs to be applied in the other two modes too.

Also tests to make sure that it is applied in popup mode too.

**Comment by wesleycho** [comment]
I'm not able to reproduce this as an issue - see [here](http://plnkr.co/edit/7gpZd0EGmlTgbo6tGRRJ?p=preview). There are also tests against all 3 modes.

**Comment by Foxandxss** [comment]
Seems like the other two (month and year) were fixed in separated PRs and I never saw them. My bad.
