### ISSUE TITLE
Datepicker initDate

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#4882]
This seems to not be doing anything.

Technically is to set an initial date, but you already do that with the `ng-model`.

In fact, if you add some init-date, it will get overrode immediately by ng-model.

So, send it to the drain?

**Comment by wesleycho** [comment]
It sets the initial active date I think, which differs from the model

**Comment by gimzani** [comment]
On datepicker popup, I can set a date and it will go through just fine.  But when I load it with a date from the model, it will load and even show the correct date when the popup is open, but when the form is submitted it says "invalid".

Now, if I select some other date and then go back to the original date, it will work.

So - for some reason, the validators are not validating the initial input.  They only validate IF you actively select a new date.

Hope that helps - the datepicker is AWESOME - but this bug sucks!

Thanks,

Gim

**Comment by Foxandxss** [comment]
Please, create an issue if you have a bug, with a reproduction plunker, but don't use this one. Thanks.

**Comment by deeg** [comment]
@wesleycho, @Foxandxss, what is the resolution on this one?

The docs currently reads
>The initial date view when no model value is specified.

Is this going to be removed, or are any other changes wanted?

**Comment by Foxandxss** [comment]
I opened it to investigate what it really does, but I personally didn't dig too much. So for me, it is still due for investigation.

**Comment by icfantv** [comment]
@Foxandxss, @wesleycho - looks like this is being used now based on Wes' recent changes.  Can this be closed?

**Comment by wesleycho** [comment]
I took a look - init-date actually does something, as can be seen [here](http://plnkr.co/edit/2CrK8U3yUCySj10RmSK0?p=preview).

Going to close as it is indeed being used.
