### ISSUE TITLE
Prevent modal from scrolling to top after modal dismiss / close

### ISSUE THREAD

**Issue by LeleDev** [angular-ui/bootstrap#4883]
How to prevent modals from scrolling to the top of the page after each modal dismiss / close action?

**Comment by icfantv** [comment]
@LeleDev, please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

**Comment by abobwhite** [comment]
@LeleDev @icfantv I am having this probably now, but only in IE. Is this truly a support question or an actual bug that should in fact be listed here? I'm not yet sure what's causing it.

**Comment by icfantv** [comment]
@abobwhite i am not seeing this behavior on our demo page.  can you please create a working plunker that demonstrates the issue using the latest version of our code?  you can easily create a plunker from our button links in on the demo page.

**Comment by LeleDev** [comment]
I'm not experiencing this problem too, with the current version
