### ISSUE TITLE
Collapse show property is wrong

### ISSUE THREAD

**Issue by Nosthertus** [angular-ui/bootstrap#4884]
The collapse shows when the property expression is false

**Comment by wesleycho** [comment]
Please post a link to a reproduction in Plunker.

**Comment by Nosthertus** [comment]
you can see it in Plunker preview used for collapse, the original value of the property is false, which is making the collapse to show on false, this could make some confusions when creating expressions for collapse

**Comment by Foxandxss** [comment]
So, let's say what the dictionary says about collapse:

>Fold or be foldable into a small space

So to collapse something, means that you fold it, in bootstrap terms, you make it disappear.

![](http://puu.sh/liEWF/e4027989ad.png)

So in this case, is this folded? **False**, it is not collapsed.

Then you click it:

![](http://puu.sh/liF0W/43eb369db8.png)

Is this now folded? **True**, it is collapsed.

So TL;DR this works as intended, a false expression means that the content is shown and true means that it is collapsed. Think about this like `ng-hide`. If true it hides, if false it shows.

**Comment by RobJacobs** [comment]
This is also consistent with the TWBS collapse plugin, the presence of the collapse class hides content.
