### ISSUE TITLE
Strange behaviour of uib-collapse inside ng-repeat

### ISSUE THREAD

**Issue by BParnikel** [angular-ui/bootstrap#4885]
Faced with strange behaviour of uib-collapse inside ng-repeat with changing collection: animations calls with each collection update, despite the fact that uib-collapse is set to false;

See plunkr: http://plnkr.co/edit/rP1AlbLsi1qXuJOJL0D6?p=preview

**Comment by Fidel90** [comment]
Maybe related? https://github.com/angular-ui/bootstrap/issues/4848

**Comment by RobJacobs** [comment]
Closing as support question answered on SO, [link](http://stackoverflow.com/questions/33666761/strange-behaviour-of-angular-bootstrap-collapse)

**Comment by BParnikel** [comment]
I got only a partial answer on SO about transition between primitives.
But what about first opening of uib-collapse="false" with animation? I suppose it shouldn't be happened, but it does...

**Comment by RobJacobs** [comment]
This is a result of the expand animation being run immediately in the link function.  Adding the following code:

    if (!scope.$eval(attrs.uibCollapse)) {
      element.addClass('in')
        .addClass('collapse')
        .css({height: 'auto'});
    } 

at the top of the linking function seems to solve the problem.  Updated [plunk](http://plnkr.co/edit/qzHb2sNHBhb0vXKndNpK?p=preview) with code changes.

**Comment by BParnikel** [comment]
Thank you! Is there a chance that this fix will be included in next releases? I think changing of vendor sources is a bad practice :)

**Comment by wesleycho** [comment]
I wonder if this is related to all of our ngAnimate modal + collapse issues - can you check on whether the fix fixes those issues to @RobJacobs?

**Comment by RobJacobs** [comment]
@wesleycho Will do, wanted to get the positioning PR in first.

**Comment by wesleycho** [comment]
This is not related to the modal issues - that one turns out to be a gotcha with ng-app needing to be present on the `body` element or higher.

**Comment by wesleycho** [comment]
Actually...nevermind, I could be mistaken.

**Comment by wesleycho** [comment]
So to clarify why the collapse class is removed - Bootstrap uses the `collapsing` class to set the transition, and the `in` class to animate.

**Comment by BParnikel** [comment]
Great job, @wesleycho , thank you!
