### ISSUE TITLE
Changing month or day in text input from two digits to only one yields undefined on bound scope property

### ISSUE THREAD

**Issue by mzabani** [angular-ui/bootstrap#4887]
I'm facing an issue where after editing a datepicker text field with `ng-model="someDateObject"`,  someDateObject` becomes undefined. This happens specifically when I change a date such as *12/07/2016* to *12/7/2016* or from *01/07/2016* to *1/07/2016*, i.e. when I remove one zero from the month or from the day.

Don't know if it's relevant, but I'm on a pt-BR locale, which is DD/MM/YYYY, on version 0.14.3.

**Comment by wesleycho** [comment]
Removing a 0 will cause it to be an invalid date given that format.

If you are looking for a looser format, there is currently support for `d!` and `M!` flags for optional leading zeroes. If you are looking for invalid dates still being set, keep an eye out for #4837.
