### ISSUE TITLE
Date Picker validation not functioning correctly

### ISSUE THREAD

**Issue by gimzani** [angular-ui/bootstrap#4888]
On datepicker popup: the first time through a pristine form, I can set a date and it will go through just fine. 

But when I load the form with a date from the model, it will load and even show the correct date when the popup is open - even if the format differs. But when the form is submitted it says "invalid".

Now - here's the funny part. If I select some other date and then go back to the original date, submit the form, it will validate and the submit will work.

So - for some reason, the validators are not validating the initial input. They only validate if you ACTIVELY select a new date.

Hope that helps - the datepicker is AWESOME - but this bug sucks!

Thanks,

Gim

**Comment by icfantv** [comment]
If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you've found a bug and do not follow the above instructions when opening a new issue, we will close the issue due to lack of activity after a reasonable amount of time.

**Comment by gimzani** [comment]
You can delete this - I figured it out.  BUT - you might want to put in the documentation that the model going in MUST be of type date - mine was going in as a string - which LOOKED fine to me but was obviously not.

Thanks

**Comment by icfantv** [comment]
It's been corrected in `master`.  Yours would not be the first time this this issue has come up.  Apologies for the vague docs.

Assuming you're upgrading from an older version, it's listed as a breaking change [in the CHANGELOG](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#bug-fixes-6) for the 0.13.2 release.  I would argue that the onus is on the developer to read that prior to upgrading any library.
