### ISSUE TITLE
Pagination with a limit of maximum visible buttons that shows first and last items all the time.

### ISSUE THREAD

**Issue by hyzhak** [angular-ui/bootstrap#4890]
Is there any way to be able to have such view of pagination?
```
<< < 1 2 3 4 5 6 7.......13 14 > >>
```

**Comment by icfantv** [comment]
@hyzhak, please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

**Comment by hyzhak** [comment]
@icfantv just asked. Are you sure that this issue is not feature request? As I know there no way to archive such result. And if I'm right it is not support request.
