### ISSUE TITLE
uib-tooltip size

### ISSUE THREAD

**Issue by tylerdmace** [angular-ui/bootstrap#4900]
I would like to force my tooltips to be 500px in width but I cannot seem to figure out how to do that. Does anyone have some suggestions here?

**Comment by icfantv** [comment]
@tylerdmace, please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

**Comment by icfantv** [comment]
you need to override the `max-width` css property on either the `.popover` or `.tooltip-inner` class defined in Bootstrap's CSS.
