### ISSUE TITLE
Using uib-popover-template with popover-trigger="focus" - can't stop close on click

### ISSUE THREAD

**Issue by terrydw** [angular-ui/bootstrap#4901]
My popover template includes a series of checkboxes.  Without the popover-trigger="focus" the way to close the popover is to click on the link that opened it in the first place.  I would prefer to close the popover by clicking away which "focus" does.  However, if the user clicks any of the checkboxes inside the popover, it closes the popover.  Ideally, I'd like the popover to stay open in case multiple checkboxes are necessary and only close when clicking "away".

I have played a number of different ways with the event stopPropagation() on click and just can't seem to get the behavior to change.

Any help?

**Comment by icfantv** [comment]
@terrydw, please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

You want to use the `popover-is-open` attribute so you can programmatically control whether or not it's open.

As an aside, this issue has been discussed numerous times via various issues.  Please do us the courtesy of searching both open and closed issues (and reading the project docs) prior to opening new issues.

**Comment by terrydw** [comment]
I apologize.  The fact that stopPropagation() doesn't appear to be working "felt" like a bug to me.

Also, for clarification (it appears you misunderstood), I'm not trying to control when the popover opens.  I'm trying to stop the popover from closing (it is closing because of clicking a checkbox INSIDE the popover and I only want it to close when clicking OUTSIDE the popover). 

The stopPropagation not working is what I think really think is the issue though.  I had already searched high and low for an answer to why stopPropagation() was not working before I posted.

Thanks.

**Comment by icfantv** [comment]
I'm looking at `master` and it looks like we've added a new trigger called `outsideClick`.  You may want to give that a go.  You can build the latest SNAPSHOT code by executing `npm install` and `grunt` after getting the latest.

In the future, if you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).
