### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by georgi-kovachev** [angular-ui/bootstrap#4902]
In Angular UI Bootstrap Carousel I would like to remove arrows of 'next' & 'prev' and move to the specific page   from code.
What code snippet should I use to set the current index of the carousel?

**Comment by Foxandxss** [comment]
Use a custom template without arrows and use `active` to select.

Anyway: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
