### ISSUE TITLE
Popover html content

### ISSUE THREAD

**Issue by chilimix** [angular-ui/bootstrap#4906]
Hi Guys,

First, thank you for a great framework :)
I can't get the popover control to work with html input: http://plnkr.co/edit/5DkntpzcDRAzKpj8oWRZ?p=preview

Can anyone please tell what I'm doing wrong or have I found a bug?

**Comment by icfantv** [comment]
@chilimix, please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.  Thanks.
