### ISSUE TITLE
typeahead with headers

### ISSUE THREAD

**Issue by kefengdeng-ibboost** [angular-ui/bootstrap#4907]
There's any option available to create Headers on typeahead like in Multiple Sections with Headers example [here](http://twitter.github.io/typeahead.js/examples/).

Cheers

**Comment by icfantv** [comment]
@kefengdeng-ibboost, please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.  Thanks.

**Comment by rognstad** [comment]
You can get something like this working now by using a custom template and sorting the results. See this [question](http://stackoverflow.com/questions/25116635/angularui-bootstrap-typeahead-grouping-results) on stackoverflow.

**Comment by kefengdeng-ibboost** [comment]
That's really good to know. Thanks a lot.

**Comment by wesleycho** [comment]
Closing this as support - looks like it's doable with custom templates.
