### ISSUE TITLE
bootstrap 4 issue - ignore progress tag

### ISSUE THREAD

**Issue by iBasit** [angular-ui/bootstrap#4911]
I'm using bootstrap 4 and it has following progress tag

```html
<progress  class="progress progress-striped progress-animated" value="{{ file.percentage }}" max="100">{{ file.percentage }}%</progress>
```

How can I tell ui-bootstrap to ignore progress tag from parsing template?

**Comment by icfantv** [comment]
@iBasit, please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.  Thanks.

Angular UI Bootstrap doesn't officially support Bootstrap 4 yet (and I should point out it's still in Alpha state).

Finally, please give us the courtesy of performing a search of both open and closed issues has the conflict with the `progress` tag is well known and has been addressed starting with the last few versions of Angular UI Bootstrap with the introduction of the `uib-` prefix on all our components.

**Comment by icfantv** [comment]
Depending on your version of Angular UI Bootstrap, you will see deprecation warnings in your console.

**Comment by iBasit** [comment]
Version: 0.14.3 - 2015-10-23

and I see this warning: (don't see any deprecation warnings)

![image](https://cloud.githubusercontent.com/assets/34341/11190022/5971572a-8c8b-11e5-8424-d953d9edb8b0.png)


Sorry for opening the issue, next time I will take the issue on stackoverflow.

**Comment by icfantv** [comment]
Make sure you're using the `-tpls-<version>.js` version of the library.

**Comment by iBasit** [comment]
Yes, but question was how to tell ui-bootstrap **not to parse** the progress tag

**Comment by icfantv** [comment]
The deprecated code was removed from `master`.  If you don't want the progress element getting parsed, you will need to use a build off of that until we release 1.0.

You can build `master` by pulling down the latest code and running `npm install` followed by `grunt`.  The latest SNAPSHOT build will be in the `dist` directory.
