### ISSUE TITLE
popover can't work well inside a modal

### ISSUE THREAD

**Issue by zhangningdlut** [angular-ui/bootstrap#4912]
I want to use popover in a modal, but the layout of popover is disorder。

div.modal-header
    script(type='text/ng-template' id='datepickerTemplate.html')
        .form-group()
            label date
            input.form-control

div.modal-body
    .form-group
           label.col-xs-3.control-label start
           button.btn.btn-default(uib-popover-template='datepicker.template',popover-placement='{{datepicker.placement}}')

$scope.datepicker = {
        template:'datepickerTemplate.html',
        placement:'right',
}

anyone can help me ? thank you

**Comment by wesleycho** [comment]
Please post a Plunker with reproduction.

**Comment by zhangningdlut** [comment]
Thanks, I have solved it.
1. Use popover-append-to-body=true to let popover append to body, then the layout is well, but the popover is behind the modal.
2. Then , change  z-index in .popover bigger than the z-index in .modal, I change the value from 1010 to 1100.

Then it work well.
