### ISSUE TITLE
Min attribute in timepicker doesn't work with 0 value.

### ISSUE THREAD

**Issue by turakvlad** [angular-ui/bootstrap#4918]
"Min" attribute with 00:00 time doesn't work - [plunkr](http://plnkr.co/edit/q6IlxftsS71QN3yIfC8Y?p=preview).

If we set its to 01:00 or 02:00 time or whatever else except for 00:00 everything is OK - [plunkr](http://plnkr.co/edit/ktWo3eETGjDN1ooUnWax?p=preview).

My [previous issue](https://github.com/angular-ui/bootstrap/issues/4606) was closed. @BobbieBarker told, that it was working as intented, but I and my team don't agree with his statement. 

For example, I need to use these timepickers for creating range timepickers. In my project user can choose some daily interwal.

It can be:
* 09:00 - 18:00
* 14:00 - 15:30

But can't be:
* 23:30 - 14:00 (because these are different days)

So, I need to set min attribute for "start" timepicker to 00:00 and max attribute for "end" timepicker to 23:59, but can't.

To my mind, it isn't working as intended. But if I haven't convinced you and you don't want to fix this, maybe you can tell me how can I fix this in bootstrap code?

**Comment by wesleycho** [comment]
This looks like a bug to me - need to investigate further.

**Comment by icfantv** [comment]
Closing in favor of #5957 as this will result in a complete rewrite of the widget, addressing all the outstanding issues.
