### ISSUE TITLE
Datepicker popup does not validate input correctly

### ISSUE THREAD

**Issue by xcintas** [angular-ui/bootstrap#4922]
Angular version: 1.4.7
BootstrapUI version: 0.14.3

I try to init datepicker popup with my date, which is  in ISO_8601 format, but it is not valid

bug is reproduced in: http://jsfiddle.net/aoLxrvtu/

**Comment by cyrilgandon** [comment]
The date you give doesn't correspond to the format. If you set the format to ISO_8601, it works as expected:

http://jsfiddle.net/27c177a9/

**Comment by icfantv** [comment]
@xcintas, , please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.  Thanks.

We've clarified the docs for the 1.0 release, but it is listed in the [CHANGELOG.md](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md), the datepicker expects a Javascript `Date` object and not a string.

Please do us the courtesy of performing a search of both open and closed issues before entering a new one as this one has been addressed many times.

@cyrilgandon, see my comment above about the proper use of datepicker.  Thanks.
