### ISSUE TITLE
[Popover] Html is not compiled when using the attributes uib-popover-html

### ISSUE THREAD

**Issue by cyrilgandon** [angular-ui/bootstrap#4923]
Maybe it is the expected beahviour, but it is not in the docs.
I expected to have the same result if I use `uib-popover-template` or `uib-popover-html`.
It appears that the latest doesn't compile the angular code.

 - With uib-popover-html : http://plnkr.co/edit/mL4EJ2POh7hnEPWtKf82?p=preview :-1: 
 - With uib-popover-template : http://plnkr.co/edit/C3WZP55OQuIx1KbXyFBG?p=preview :+1: 

Could we have a compiled result when using `uib-popover-html`?

**Comment by icfantv** [comment]
@cyrilgandon, I'm not sure what your issues is, both of those plunkers are working correctly.

`uib-popover-html` assumes the attribute value is HTML and treats it as such (note that the onus is on the developer to determine that the HTML is safe to render), whereas the `uib-popover-template` attribute takes the path of an HTML template.

**Comment by icfantv** [comment]
Ahhhh, hang on.  I see.

**Comment by cyrilgandon** [comment]
Quick test with modal, inline templating work as expected:

http://plnkr.co/edit/8z1pnlPCeoSsFQf85yJN?p=preview

**Comment by icfantv** [comment]
Yea, this is starting to smell like a bug.  @wesleycho, what do you want to do here?  Basically, the user supplied HTML for the `popover-html` attribute is not getting $compiled when inserted into the DOM.

There is a relatively simple workaround in using an external template so it's probably not high priority.

**Comment by RobJacobs** [comment]
I would argue that the uib-popover-html is designed to support static markup only.

**Comment by icfantv** [comment]
I don't have a strong opinion here one way or another.  If we stick with the static HTML option, we should update the docs to indicate that for both popovers and tooltips.  I'm happy to do that if that's what we decide.

Is there anything you want to do to handle the inconsistency then between modal and tooltips/popovers?  Is it just something we live with then?

**Comment by cyrilgandon** [comment]
A use case we might have at my company is giving customer Wysiwyg textarea to enter html stuff, and propose them custom angular element so they can build views more business oriented. That's the kind of stuff we might want to show in a popover.

Be able to use the `popover-html` would be great in this case.

**Comment by icfantv** [comment]
But you could use a generic HTML template that takes the HTML from your database and THAT would get compiled.

**Comment by icfantv** [comment]
[Here's a super quick and dirty example](http://plnkr.co/edit/o6LNqh6TgbE1y9N6sw4M) of how you could do that.

**Comment by icfantv** [comment]
Look at the freeform input example at the bottom.

**Comment by cyrilgandon** [comment]
I agree that there is a workaround. What I'm saying is that there is use case where using a file is not a possibility, and the html string is the only possibility.

In this case, it would be nice if popover support angular syntax in the popover-html attribute.

**Comment by icfantv** [comment]
@cyrilgandon, my example gives you a way to do what you want.  Instead of a text field, you could use your WYSIWYG editor.

I wanted to get other devs' feedback on this which is why it hasn't been closed yet.

**Comment by wesleycho** [comment]
I don't think we want to support this - the problem we need to be careful about here is XSS injection. `uib-*-html` forces explicit whitelisting of HTML via $sce, and `uib-*-template` forces the template to be present in $templateCache, the two main mechanisms angular is designed around for consuming HTML content. Anything else overlaps concerns.

I would recommend explicitly caching the template in $templateCache at runtime and using popover-template for this case.

**Comment by wesleycho** [comment]
Going to close this, as we aren't going to support this. Currently, we have a task to update the docs for every component, so this should improve when we do the 1.0 release.

**Comment by readme42** [comment]
A short note in the docs mentioning *... we aren't going to support this ...*  would be great!

**Comment by icfantv** [comment]
@readme42, I just missed getting this in for the 1.0 release - we'll patch our gh-pages to reflect this.  Thanks.

**Comment by sumeetsonawane11** [comment]
The popover is not getting compiled on <option> tag like

```
<select>
        <option uib-popover="I appeared on mouse enter!" popover-trigger="mouseenter" type="button" class="btn btn-default">Mouseenter</option>
</select>
```

Is there a way to show the popover in <option> tag

**Comment by williansmartins** [comment]
I'm having a situation like you are talking, inclusive I opened a stackoverflow about this: https://stackoverflow.com/questions/47775068/angular-ui-bootstrap-popover-is-not-changing-scope-model

Popover have no two way bind?
https://plnkr.co/edit/ebYWI8hP0xtOboY2v37Z?p=preview

**Comment by williansmartins** [comment]
I'm looking here that is two way but not for all elements
Look: http://plnkr.co/edit/nJhEl21LsLcAB8pmvmfy?p=preview

**Comment by williansmartins** [comment]
Resolved, was necessary to use $parent scope to access my variable
