### ISSUE TITLE
Why would you change ui- prefix to uib- ?

### ISSUE THREAD

**Issue by dadoadk** [angular-ui/bootstrap#4924]
When doing update on angular-ui do I need to change all of my markup from ui- to uib-?

**Comment by pkozlowski-opensource** [comment]
No. Previously we haven't had prefixes for this library at all. So you don't have to _change_ any prefixes, only _add_ prefixes for directives from this library.

**Comment by dadoadk** [comment]
So you're saying if i was using ui-tooltip, that I can continue using ui-tooltip when I update to current version? 
"ui-" is a prefix to the name of the directive. 
I don't have to change it to "uib-tooltip" ?

**Comment by pkozlowski-opensource** [comment]
> So you're saying if i was using ui-tooltip, that I can continue using ui-tooltip when I update to current version? 

We never had `ui-tolltip` in this library so you must be confusing libraries / repositories.

**Comment by icfantv** [comment]
@dadoadk, are you sure you're using the right library?  I did a cursory Google search and I can't find any directive named `ui-tooltip`.

**Comment by dadoadk** [comment]
Sorry, I was looking into examples on https://angular-ui.github.io/bootstrap/#/tooltip
this is what it shows: <a href="#" tooltip-placement="left" uib-tooltip="On the Left!">left</a>

**Comment by icfantv** [comment]
So you're good then?  The example is correct, use `uib-tooltip`.  The prefixes were introduced recently in 0.14.0 at the beginning of October.  If you are using a version prior, the prefixes won't work because they are not present.  If you are using a 0.14.x version, then you will see deprecation messages in the console when you use the old style of directive names.  The deprecated directives are removed completely in `master` and so you **must* use the `uib-` prefix if you want any of our components to work.

**Comment by dadoadk** [comment]
I think I'm good as long as I don't update to 0.14.x version. But if I do update then I have extra work to do because it is not backwards compatible. I'll have to change all the directives from **tooltip** to **uib-tooltip**, etc. I'm not sure if other people are aware of this.

**Comment by icfantv** [comment]
@dadoadk, 0.14.x IS backwards compatible w/r/t the directive names but you will see console warning messages that they are deprecated.  we have completely removed the deprecated prefixes in `master` for the 1.0 release.  That said, before you upgrade to 0.14.x, be sure to read through [the CHANGELOG](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md) and note any BREAKING CHANGES from each release between the one you're currently using and the one to which you're upgrading.

I would encourage you to upgrade as there have been TONS of bug fixes.

**Comment by dadoadk** [comment]
Thanks @icfantv , looking forward to use 1.0 release.
Any updates on accessibility features in 1.0?

**Comment by icfantv** [comment]
@dadoadk, accessibility is targeted for 1.1.  Follow #4772 for progress.
