### ISSUE TITLE
datepicker format is not work 

### ISSUE THREAD

**Issue by rafaoli** [angular-ui/bootstrap#4926]
hi, when use uib-datepicker-popup="{{format}}" or uib-datepicker-popup="dd/MM/yyyy"
is not work.

```javascript
<input type="date" class="form-control" uib-datepicker-popup="{{format}}" ng-model="item.dt" is-open="item.opened" min-date="minDate" max-date="maxDate" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text="Close" />
              <span class="input-group-btn">
                <button type="button" class="btn btn-default" ng-click="open($index)"><i class="glyphicon glyphicon-calendar"></i></button>
              </span>
```

**Comment by icfantv** [comment]
@rafaoli, please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.  Thanks.

**Comment by icfantv** [comment]
@rafaoli, also, when you post your question on SO, if you want help, you will need to also post the relevant portions of your controller as just posting the HTML isn't sufficient.  Better yet, post a link to a working plunker so people can see the actual problem.

You are asking for help, thus it is important to provide as much information as possible to those who would help you or your request will be ignored.  And you will be sad.  And we don't want you to be sad.

**Comment by rafaoli** [comment]
thank you, sorry...
