### ISSUE TITLE
ui.bootstrap.carousel url-template attribute ignored

### ISSUE THREAD

**Issue by GarrettVD** [angular-ui/bootstrap#4928]
Not quite sure what I am doing incorrectly here; I've been trying to use the ui.bootstrap.carousel module with a customized template.  My actual use-case is preloading the template cache with the template, but to simplify the matter I've included the template inline.  But even that doesn't appear to be working for me.  Any ideas?

Have a look at this Plunker: http://plnkr.co/edit/Ne6zDBpuIFDMfOhjqNvV?p=preview

Thanks,

**Comment by wesleycho** [comment]
It is `template-url`, as can be seen in practice [here](http://plnkr.co/edit/x7RYgtdEmDvsdN4c2npV?p=preview).

In the future, please post this sort of question in a more appropriate venue such as IRC or StackOverflow - issues are generally for verified issues.
