### ISSUE TITLE
how to access typeahead-min-length for validation

### ISSUE THREAD

**Issue by pjlasl** [angular-ui/bootstrap#4933]
I have a button I would like to be enabled ONLY when the value in the input box matches the typeahead-min-length. What is the $scope variable name I can access to check this?

for example:

pseudo code:
if (textbox.length == typeahead-min-length) {
    button.enabled = true;
}

**Comment by icfantv** [comment]
@pjlasl, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.  Thanks.
