### ISSUE TITLE
uib-rating onChange even

### ISSUE THREAD

**Issue by kgignatyev** [angular-ui/bootstrap#4934]
It would be awesome if uib-rating had onChange callback available. $watch does not work that well in case there is long array of ratings, and only few are editable (time based), so when rating changes for that review I would like to show 'changed' view and show "save" button.

**Comment by pkozlowski-opensource** [comment]
You can use ngModel + ngChange

**Comment by kgignatyev** [comment]
Indeed!
Thank you!

**Comment by ananyaojha** [comment]
code please...
