### ISSUE TITLE
Inconsistent use of uib- prefix

### ISSUE THREAD

**Issue by rowanmoul** [angular-ui/bootstrap#4937]
I have noticed this specifically when using Typeahead, though it could be a problem in other components.
**typeahead-no-results** does not use the **uib-** prefix, nor does **typeahead-loading**, **typeahead-template-url**, or **typeahead-popup-template-url**.
There may be others, but these ones are used in the example on the demo page. When **uib-** is added it fails silently.
To reproduce:
1. head over to the demo page https://angular-ui.github.io/bootstrap/#/typeahead
2. open the typeahead plunker
3. add **uib-** to the above mentioned attributes/directives

**Comment by wesleycho** [comment]
The importance of the namespacing is to avoid clobbering common directive/controller/service names, i.e. CarouselController, or taking over the `progress` element completely. We are not likely to prefix all attributes used.

**Comment by rowanmoul** [comment]
In that case there is not a real issue here except perhaps with this not being made clear on the demo page. I will close this issue.
