### ISSUE TITLE
Collapse is too slow?

### ISSUE THREAD

**Issue by Misaka42** [angular-ui/bootstrap#4939]
I'm using latest ui-bootstrap, and if I have a lot of elements inside my collapse, it takes ages for it to open and close (with animations-enabled). Is there a way to controll collapse animation speed?

**Comment by wesleycho** [comment]
You can change it by setting the collapse transition in CSS.

**Comment by soulfresh** [comment]
Can you give some more information on this? The docs are not very verbose with regards to this. I tried the following but it does not seem to preserve the transition-timing-function:

```html
<div id="thisOne" uib-collapse="myValue" style="transition: all 300ms cubic-bezier(1, 0, 0, 1);">
...
</div>
```

Thanks

**Comment by soulfresh** [comment]
I was eventually able to get this working by adding `!important` to the end of my style. However I'm not sure if that's the best approach.
