### ISSUE TITLE
Typeahead ng-mouseover not working

### ISSUE THREAD

**Issue by gbranco** [angular-ui/bootstrap#4941]
What I want to do is: Bind the object listed inside dropdown to another element when the user pass the mouse over the list item

See the folowing code:

li ng-repeat="match in matches track by $index" ng-class="{active: isActive($index)}"ng-click="selectMatch($index)" role="option" id="{{::match.id}}"  ng-mouseover="ccx()">
                    <div uib-typeahead-match index="$index" match="match" query="query" template-url="templateUrl"></div>
</li

and in my controller:

$scope.ccx = function(){
console.log('update on mouse over')
};

but the method inside my controller is never being called... Any ideas?

**Comment by icfantv** [comment]
@gbranco, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.  Thanks.
