### ISSUE TITLE
Typeahead data with alternate names (or nicknames)

### ISSUE THREAD

**Issue by DaAwesomeP** [angular-ui/bootstrap#4942]
To some up the details of what I am trying to do below, I want to have "nicknames" to data points. For example, `Alaska` or be matched by both `AK` and `Alaska`. I'm currently searching an array of objects that point to the data to do this, but this method returns duplicates.

----
I'm trying to implement a simple search feature with Typeahead. Originally, I had typeahead simply search an array of the data. This is fine, but humans don't like typing things exactly as they should be quickly. The search is more robust if similar terms can bring up the same result. For example, if I had a search of states and countries, I would want `United States of America` to come up when searching `USA`, `U.S.A.`, and `United States of America` (this includes simply `U.S.` and other shortened terms because of the autocomplete) and both `AK` and `Alaska` to bring up `Alaska`.

Right now, I am searching an array and then matching a field from it to an object to get more information like so:
```js
var altNames = [            // The array that Typeahead looks in
  {
    altname: 'ak',
    to: 'alaska'
  },
  {
    altname: 'alaska',
    to: 'alaska'
  },
  {
    altname: 'u.s.a',
    to: 'unitedstatesofamerica'
  },
  {
    altname: 'usa',
    to: 'unitedstatesofamerica'
  },
  {
    altname: 'united states of america',
    to: 'unitedstatesofamerica'
  }
];
var dict = {     // The object that the 'to' field is then matched to to get more data and the "proper" name
  unitedstatesofamerica: {
    name: 'United States of America',
    altNames: [ 'U.S.A.', 'USA', 'United States of America' ]
  },
  alaska: {
    name: 'Alaska',
    altNames: [ 'Alaska', 'AK' ]
  }
};
```
```html
<input type="text" class="form-control" ng-model="searchbox" typeahead="term as search.dict[term.to] for term in search.altNames | filter:$viewValue | limitTo:8" typeahead-template-url="searchTemplate.html" placeholder="Find something..." />
<!-- where 'search.altNames' is the array above and 'search.dict' is the object above -->
```

However, there are flaws with this implementation. First of all, there are duplicates. Because sometimes similar terms can have the same beginning and different endings (imagine having `node`, `nodejs`, and `node.js` and only typing `node`), there are sometimes multiple terms going to the same thing listed (duplicates). Also, I have to structure my data oddly. The lookup causes the search to return `[object Object]` upon pressing enter.

I would rather structure my data like so:
```js
var dict = { // I want to keep it an object (instead of an array of objects) to make the function of my site a little easier (URL safe terms as the key), if possible
  alaska: {
    name: 'Alaska',
    altNames: [ 'Alaska', 'AK' ],
    thisObject: 'will eventually have a lot more data in it'
  },
  unitedstatesofamerica: {
    name: 'United States of America',
    altNames: [ 'U.S.A.', 'USA', 'United States of America' ]
  }
};
```
I would be fine using the current implementation if it is absolutely necessary where I search in one array and then look it up in an object (assuming that the object and duplicate issue is resolved), but having that extra array is a lot to process (it will grow a lot) and seems redundant when there is already another object with the same data in it. I plan to auto-generate that array from the object.

Is there any hope?

**Comment by DaAwesomeP** [comment]
I just solved my own question! I can have Typeahead search an entire array of objects! Cool! Then I just use `match.model` to get more information in my template.

**Comment by icfantv** [comment]
@DaAwesomeP, glad to hear you were able to solve your own question.  In the future, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.
