### ISSUE TITLE
 using single controller with tab & datepicker, $scope.dt is not working

### ISSUE THREAD

**Issue by gopiece04** [angular-ui/bootstrap#4944]
Hi

I have using latest version of angular ui bootstrap.

I created single controller with tab & datepicker, onload the datepicker is working fine. 

I get issue, when clicking/ changing the date, the $scope.dt is not change dynamically.

Can u give me solution.

Please find the plunker : http://plnkr.co/edit/w9WV2kXTd5jgetY62fnw?p=preview

Regards
Gopinath BS

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive and https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by gopiece04** [comment]
Hi pkoz,

I cannot get it idea from link very soon.
Please find the plunker: http://plnkr.co/edit/w9WV2kXTd5jgetY62fnw?p=preview
and change the date by click the date in datepicker. I have binded the $scope.dt in here not working & here working. give me the solution why not working in "here not working"

Regards 
Gopinath BS

**Comment by pkozlowski-opensource** [comment]
> I cannot get it idea from link very soon.

Sorry to hear this... But GH issues are not support forum so you might either go over provided links once again or ask your question using an appropriate support channel. We are _not_ going to answer support questions here.

**Comment by gopiece04** [comment]
Feeling bad!!!
