### ISSUE TITLE
How to add popover in a direcitve of div?

### ISSUE THREAD

**Issue by shlomogoldstein** [angular-ui/bootstrap#4946]
I am using ``` "angular-bootstrap": "0.11.0"```. I have a div where I want to show a popover. I want the popover attributes/directives to be added in a custom directive:

```<div trim-to-tooltip="">
            {{transaction.devicehash}}
          </div>```

directive  trim-to-tooltip, it will trim the value and show the long value in a popover

```
function ($compile, $timeout, $filter, $translate) {

    return {
      link: link,
      restrict: 'AE'
    };

    function link($scope, $element, $attrs) {

      // c75454e71293c47d987819f3ab3f4e31

      var maxLength = 16;
      var originalValue, v;

      function _init() {
        // after rendering
        $timeout(function () {
          originalValue = $element.text().trim();

          if (originalValue.length > maxLength - 3) {
            v = originalValue.substring(0, maxLength) + '...';
            
// #1 approach does not work
           $element.attr("popover", originalValue);
            $element.attr("popover-placement", "top");
            $element.attr("popover-trigger", "mouseenter");

// #2 approach does not work
            $element.html('' +
                    '<div popover-placement="top" ' +
                    'popover="'+ originalValue + '"' +
                    'popover-trigger="mouseenter"'  +
                    '>' +
                    v +
                    '</div>'
                    );
            
          }
        });
      }

      _init();
    }
  }
```

**Comment by wesleycho** [comment]
You have to $compile the HTML if you are creating it dynamically in a directive.

Generally this sort of question should be posted in a venue such as StackOverflow or IRC than here.
