### ISSUE TITLE
typeahead-editable binding

### ISSUE THREAD

**Issue by DavidBanksNZ** [angular-ui/bootstrap#4947]
When trying to replace old directive names with the `uib-` prefixed versions, I run into `$parse` errors with `uib-typeahead`. Previously, with the un-prefixed directive, I could use `typeahead-editable="{{editable}}"`  where editable is defined on the controller scope, but now this causes a `$parse` error. See http://plnkr.co/edit/vmF98QeXxj5E5pDRYOSQ?p=preview

**Comment by icfantv** [comment]
This is still a bug in `master`.

**Comment by icfantv** [comment]
@DavidBanksNZ, thanks for catching this.

**Comment by wesleycho** [comment]
In this case, this is easy to fix by not using {{ }}, as seen [here](http://plnkr.co/edit/IpRIWAQBAIVuc6GiB4GX?p=preview)

**Comment by wesleycho** [comment]
Going to close this as not a bug - did some git history tracing, it doesn't look like this was officially supported with interpolation for quite a long time, if ever.

**Comment by DavidBanksNZ** [comment]
Yes it's an easy workaround thanks. Perhaps it used to be 'unintentionally supported'
