### ISSUE TITLE
[Regression] Dynamically open popover broken

### ISSUE THREAD

**Issue by jd-carroll** [angular-ui/bootstrap#4949]
Previously you were able to dynamically open popovers / tooltips because the listeners were installed on the jqlite / jquery object.  However 7556beda486f26b40fb860448316e8a32457e9e9 moved the listeners to the raw DOM element which broke the ability to open popovers / tooltips dynamically.

Is there any plan to move these back to jqlite / jquery?  If the underlying jquery issues cannot be resolved, what other workaround could be implemented to still support dynamically opening these popovers.

**Comment by wesleycho** [comment]
Explain - this functionality is not broken, so this sounds like a usage issue.

**Comment by jd-carroll** [comment]
**Original Plunkr:** (working)
http://plnkr.co/edit/HqKTgmci4lJQtc50WNIj?p=preview
UIB Version: 0.13.0

**Updated Plunkr:** (not working)
http://plnkr.co/edit/xCrXj6jLxAZD6cnRHxXE?p=preview
UIB Version: 0.13.4 (the first release after 7556beda486f26b40fb860448316e8a32457e9e9 was merged)

Note: The only difference between the two Plnkr's is `index.html:6` where I updated the version.

**Comment by wesleycho** [comment]
Here is a working example: http://plnkr.co/edit/1RSIeYxRngMuBp8rOpjp?p=preview

**Comment by jd-carroll** [comment]
Awesome! Thanks and sorry for the noise.

**Comment by zaiiiPan** [comment]
我就只是注册了一个帐号，你们一群鬼人就给我发邮箱，还装13用英文，不知道我英文不好么，讨厌！

**Comment by wesleycho** [comment]
Not a problem - we may revert that breaking change that happened, it seems to be causing some usage pain to get around an edge issue with disabled elements.
