### ISSUE TITLE
Datepicker ignores time edits in the input box

### ISSUE THREAD

**Issue by bgrohman** [angular-ui/bootstrap#4950]
If you have a datepicker using a date format that displays a time as well as a date, and you change the time in the input box, the underlying date model does not get updated with the new time. 

http://plnkr.co/edit/9kkn32QwRILAiUaBp0Yo

The Plunker above shows the issue. If you highlight a single digit in the time portion of the input box and change it to a different but valid value (e.g. change "9:00 AM" to "8:00 AM" by highlighting the "9" and pressing "8" on your keyboard), then the model is not updated. 

Interestingly, if you edit the time portion in the input box in such a way as to cause an intermediate invalid date, then the model does get updated once the input box value is a valid date again (e.g. use backspace to change "9:00 AM" to "8:00 AM").

It works correctly when you edit the date portion - if you highlight a single digit in the date portion of the input box and change it, then the model is updated accordingly.

**Comment by wesleycho** [comment]
Is there a particular reason why the model should get updated? This sounds like this would add negative performance.

**Comment by bgrohman** [comment]
Re: "Is there a particular reason why the model should get updated?" - Two-way data binding. If the user manually types in a date, I would expect that date to be selected if they then open the date picker.

**Comment by wesleycho** [comment]
Have you tried `ng-model-options="{allowInvalid: true}"`?

**Comment by bgrohman** [comment]
I updated the plunker above (http://plnkr.co/edit/9kkn32QwRILAiUaBp0Yo) to use ng-model-options like you suggested, but I still get the same issue.

**Comment by wesleycho** [comment]
Going to close this as resolved in `master` via 2460e423224492a35a354ee6f3dc0dd4352d00d6 - that should do the trick.

**Comment by bgrohman** [comment]
@wesleycho will this change allow a change from "2015-01-01 1:00 PM" to "2015-01-01 2:00 PM" to actually update the model? Both of those view value strings represent valid dates.

**Comment by bgrohman** [comment]
@wesleycho I created a pull request that contains an additional test that should pass for the scenario I'm describing in this issue. I think the test might make it clearer than my description of the problem.

**Comment by wesleycho** [comment]
So it appears that your test passes even without ng-options being used. It could very well be that this is resolved.

**Comment by bgrohman** [comment]
@wesleycho I'm looking at the Milestones page on the wiki (https://github.com/angular-ui/bootstrap/wiki/Milestones), but it isn't clear when to expect the 1.0.0 release. Is there a likely time frame for 1.0.0 yet?

**Comment by wesleycho** [comment]
We are shooting for by the end of the year for 1.0

**Comment by bgrohman** [comment]
@wesleycho Thanks!

By the way, I just checked out the 0.14.x branch and added my test above, and the test is failing there. So it does appear to be fixed since then on master. Thanks again for your help!

**Comment by wesleycho** [comment]
Not a problem, glad to be of service :)
