### ISSUE TITLE
Datepicker popup: Support Multiple Input Formats

### ISSUE THREAD

**Issue by davious** [angular-ui/bootstrap#4951]
I'm using a fancy `MMMM dd yyyy` format on my datepicker popup. I like the fancy, but I'd also like my users to be able to type in a date using the `M!/d!/yyyy` format which, to them, is the go-to date format. Would angular bootstrap add a way to make this a reality? Maybe a list of acceptable date format inputs?

**Comment by wesleycho** [comment]
I'm amenable to this feature for UX reasons, although it seems like it could also add to user confusion.

**Comment by icfantv** [comment]
We could accept an array of input formats and then test that the date matches one of the formats?  This has not been a oft-requested feature, however, so it's not a huge priority.  @davious, if you want to take a stab at a PR, we'd welcome a well-thought/well-designed one.
