### ISSUE TITLE
datepicker should support new angular $locale.DATETIME_FORMATS.FIRSTDAYOFWEEK parameter

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/bootstrap#4954]
Angular's $locale service now supports FIRSTDAYOFWEEK parameter that is supposed to control which week of day appears first in the calendar (daypicker template in Angular UI). Currently, Sunday is always the first one even though most of the locales use Monday as the first day of the week. Please work this into your next release.

**Comment by pkozlowski-opensource** [comment]
>  Please work this into your next release.

Sure, feel free to send us a PR
