### ISSUE TITLE
timePicker should support 'seconds' as well

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/bootstrap#4955]
Currently, timePicker only shows hours and minutes. Please add support for the seconds.

**Comment by icfantv** [comment]
@yurigenin, this is already in `master` under #4768.  As I'm sure you can imagine, it takes a tremendous amount of effort to maintain a very popular OSS repository.  As such, please extend us the courtesy of searching both open and closed issues before opening a new one - especially for feature requests.

If you would like to partake of the sheer awesomeness of timepicker seconds, please feel free to pull down `master` and run `npm install` followed by `grunt`.  The built files (including the new docs) will be in the `dist` folder.
