### ISSUE TITLE
timePicker should use input type="number" for hours, minutes, and seconds

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/bootstrap#4956]
Currently, to display and edit hours and minutes (seconds unfortunately missing) timePicker uses input type="text" and display increment arrows on top and bottom. Would be much more intuitive to use type="number" so that browser's native up/down controls would be used instead and real estate would be saved. Currently, placing date and time pickers side by side is an issue because of it.

**Comment by Foxandxss** [comment]
If I have to name one HTML5 that works like crap that is `type="number"`. Not supported in IE nor safari (surprise).

**Comment by wesleycho** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input , there looks like some number input support.

I'm not necessarily against this, but this has UX tradeoffs as well, including the really ugly number spinner.

**Comment by icfantv** [comment]
That built-in number spinner IS awful.

**Comment by wesleycho** [comment]
I think we should not support this officially due to UX questions & it being supported by IE10 and up (we officially support IE9 and up) - if one wants to use it, one can override the template to use a version with the desired input.
