### ISSUE TITLE
date and time pickers should be combined

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/bootstrap#4957]
I should be able to specify Date as a model and see both the date and time components in the same control. Currently, breaking it into two components is really messy where I have to first split Date into its date and time components and then recombine. And option to show both or either should also be provided.

**Comment by wesleycho** [comment]
I do not believe we want to do this in the library itself due to the amount of code this would require - however, you are more than welcome to write a directive that does this for your own needs.
