### ISSUE TITLE
Tooltip / Popover Custom Templates Not Working

### ISSUE THREAD

**Issue by jd-carroll** [angular-ui/bootstrap#4963]
Specifying a custom template (url or html) does not seem to be working.  In the Popover directive, the template is sourced by:
```
    templateUrl: 'template/popover/popover-template.html',
```
Shouldn't this be something like:
```
    templateUrl: function(element, attrs) {
      return attrs.templateUrl || 'template/popover/popover-template.html';
    },
```

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have live reproduction.
