### ISSUE TITLE
open $uibModal A from already open $uibModal B

### ISSUE THREAD

**Issue by Zivrn** [angular-ui/bootstrap#4964]
Hi, 
While everything working well when opening $uibModal A from main view (ng-repeat, ng-model they are all updated) open the same $uibModal A from already open $uibModal B the ng- do not update the relevant $uibModal A  controls although in same case the $scope initialized the same.

Does anyone experience such behavior?

Thanks!!!

**Comment by wesleycho** [comment]
Please post a Plunker.

**Comment by pkozlowski-opensource** [comment]
Closing as we don't have any live reproduction scenario.
