### ISSUE TITLE
Dropdown styling IE 10/11

### ISSUE THREAD

**Issue by Duskfall** [angular-ui/bootstrap#4966]
Steps to reproduce.
1) Open http://angular-ui.github.io/bootstrap
2) Scroll to dropdown
3) Open the button dropdown

![bug](https://cloud.githubusercontent.com/assets/2528125/11439567/f0ca968c-9504-11e5-910e-856ace8b7367.png)

Tested on IE10/IE11 With bootstrap.css 3.3.4 and 3.3.6

Solution for me was to change the ul and li elements to divs

**Comment by wesleycho** [comment]
@Foxandxss this sounds like it's something that's next on your plate

**Comment by Foxandxss** [comment]
I don't have any IE at hand to try the solution, you could create a PR, but I don't have a way to try it anyway...

**Comment by wesleycho** [comment]
I could try tackling this after you revamp the docs.

**Comment by Foxandxss** [comment]
Dropdown is ready for business. I perhaps need to do some tweak, but I revamped it already.

**Comment by wesleycho** [comment]
Going to close as this appears to be a Bootstrap/CSS problem - this is easily fixed on the user side, and I'm not sure if there's much utility doing on in the demo app.
