### ISSUE TITLE
On manually changing active slide, image is displayed twice (one below the other) in the carousel

### ISSUE THREAD

**Issue by Nishanthi** [angular-ui/bootstrap#4969]
On manually changing(selecting from the list of images) the active slide during the slideshow(carousel), the newly active slide is displayed twice.

On disabling ng-animate this issue is not seen, but ng-animate is required to animate(smooth transition from one slide to another) the slideshow instead of just displaying slides one after the other.

Please can anyone help me in fixing this issue, without disabling ng-animate

**Comment by pkozlowski-opensource** [comment]
Please send a plunker with a reprduction scenario, see: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by Nishanthi** [comment]
Please find the plunkr here: http://plnkr.co/edit/EiB76Hqzl3QMuVbaONIX?p=preview

version of AngularJS used: 1.4.7
version of ui-bootstrap used: 0.14.3
version of angular-animate: 1.4.7

* Also please note this issue is intermittent and doesn't occur for every attempt.
Screenshot provided for reference
![screenshot from 2015-11-30 12 45 07](https://cloud.githubusercontent.com/assets/3086730/11465642/810369a6-9760-11e5-98c5-63eafc18196b.png)
