### ISSUE TITLE
why the directive(uibModalWindow) close event stopPropagation?

### ISSUE THREAD

**Issue by why520crazy** [angular-ui/bootstrap#4973]
When I open a modal, it may be bind a click event to the document, but when click the modal backdrop to close the modal, it not trigger my custom event binding, can not stop propagation?

**Comment by wesleycho** [comment]
Please post a reproduction in Plunker.

**Comment by pkozlowski-opensource** [comment]
Closing as the issue is not clear and we don't have live reproduction scenario.
