### ISSUE TITLE
Add Select Box For Number of Rows Per Page

### ISSUE THREAD

**Issue by opticyclic** [angular-ui/bootstrap#4978]
Please add an option to display a select box to choose the number of rows/records per page.
E.g. Add I could set an array of 5, 10, 25, 50, 100

I should then be able to set the selected value programmatically too (or via a binding)

**Comment by wesleycho** [comment]
Please be more specific clear what you are asking for.

**Comment by opticyclic** [comment]
I am paging data in a grid. I want to give the user the option of selecting the number of rows that are displayed at a time.

See this example with datatables https://datatables.net/examples/advanced_init/length_menu.html however, I would like the drop down to be next to the pagination.

See this example with UI-Grid http://ui-grid.info/docs/#/tutorial/214_pagination

See also this question on stackoverflow http://stackoverflow.com/questions/33990460/add-control-to-bootstrap-pagination-for-rows-per-page

**Comment by wesleycho** [comment]
In this case, the pagination is just a simple standalone component - it is up to the user to wire it up with a select box for modifying the number of items displayed per page, and that is by design since the pagination should be agnostic to however the user decides to implement such a select box.
