### ISSUE TITLE
Remove usage of replace

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#4985]
Given https://github.com/angular/angular.js/issues/13215 and knowing that replace is deprecated, we should investigate removal of `replace` usage. This will cause us some pain since a one-to-one removal is not possible in an optimal way due to how Bootstrap's CSS works in some areas, using direct child selectors.

We likely will have to have a mechanism to generate a stylesheet with the project and distribute it with the library.

**Comment by icfantv** [comment]
I'm assuming we're looking at an `$element.append` type solution?  Having our own CSS is going to suck unless there's a way to use Bootstrap's LESS version.  And even then, we can only make it work w/ the built-in Bootstrap classes.

If someone uses custom Bootstrap-like classes, they're going to be upset.  And not only that, some of our templates that allow for custom classes will be totally broken until they make new CSS.

I'm not going to lie, this one is going to suck.

**Comment by wesleycho** [comment]
Going to close this as something we won't do - we are unfortunately hamstrung by Bootstrap's CSS in this case.
