### ISSUE TITLE
Opening a modal gives html like : ng-class="size ? 'modal-' + size : ''". Is this correct?

### ISSUE THREAD

**Issue by ericvb** [angular-ui/bootstrap#4986]
Hi,
I was playing with the Modal demo (https://angular-ui.github.io/bootstrap/)
I saw as result of clicking on a button to launch a modal dialog following html code:
```
 <div ng-class="size ? 'modal-' + size : ''" class="modal-dialog modal-sm" style=""><div uib-modal-transclude="" class="modal-content">
        <div class="modal-header ng-scope">
            <h3 class="modal-title">I'm a modal!</h3>
        </div>
        <div class="modal-body ng-scope">
            <ul>
                <!-- ngRepeat: item in items --><li ng-repeat="item in items" class="ng-scope" style="">
                    <a ng-click="$event.preventDefault(); selected.item = item" href="#" class="ng-binding">item1</a>
                </li><!-- end ngRepeat: item in items --><li ng-repeat="item in items" class="ng-scope">
                    <a ng-click="$event.preventDefault(); selected.item = item" href="#" class="ng-binding">item2</a>
                </li><!-- end ngRepeat: item in items --><li ng-repeat="item in items" class="ng-scope">
                    <a ng-click="$event.preventDefault(); selected.item = item" href="#" class="ng-binding">item3</a>
                </li><!-- end ngRepeat: item in items -->
            </ul>
            Selected: <b class="ng-binding">item1</b>
        </div>
        <div class="modal-footer ng-scope">
            <button ng-click="ok()" type="button" class="btn btn-primary">OK</button>
            <button ng-click="cancel()" type="button" class="btn btn-warning">Cancel</button>
        </div>
    </div></div>
```
Forgotten to include the code in {{ }}?

**Comment by pkozlowski-opensource** [comment]
> Forgotten to include the code in {{ }}?

Why do you say so? @ericvb is there any particular problem that you are seeing? Could you clarify what is the issue here?

**Comment by ericvb** [comment]
It seems not to be a problem to use the modal.
I was just curious about this piece of code. What's the meaning of it?
```
<div ng-class="size ? 'modal-' + size : ''" class="modal-dialog modal-sm" style="">
```

**Comment by pkozlowski-opensource** [comment]
> I was just curious about this piece of code. What's the meaning of it?

It is an expression evaluated by the [ngClass](https://docs.angularjs.org/api/ng/directive/ngClass) directive:

> Expression to eval. The result of the evaluation can be a string representing space delimited class names, an array, or a map of class names to boolean values. In the case of a map, the names of the properties whose values are truthy will be added as css classes to the element.

We are in the "a string representing space delimited class names" case here.

**Comment by ericvb** [comment]
Thanks to clarify this.
We don't stop to learn ;-)
