### ISSUE TITLE
ng attributes added to accordion-header needs to move to panel-heading

### ISSUE THREAD

**Issue by gomezruo** [angular-ui/bootstrap#4987]
any ng attribute added to accordion-header: <accordion-header ng-click="doStuff()"></accordion-header>

Needs to move to the panel-heading when the cotent is moved

**Comment by wesleycho** [comment]
Explain why this needs to happen - what is your use case?

**Comment by gomezruo** [comment]
So i can use ng-click to trigger an angular function when the accordion
item's header is clicked on. We just need a function to run when an item is
expanded / collapsed

**Comment by wesleycho** [comment]
Why not watch for the value of the `is-open` property on the group?

**Comment by gomezruo** [comment]
Yes, could do. It still would be handy to have this functionality for other
use cases.

**Comment by RobJacobs** [comment]
This can be accomplished by creating your own accordion heading template, e.g:

    <uib-accordion-heading>
      <div ng-click="headingClick()">
          I can have markup, too! <i class="pull-right glyphicon" ng-class="{'glyphicon-chevron-down': status.open, 'glyphicon-chevron-right': !status.open}"></i>
      </div>
    </uib-accordion-heading>

**Comment by gomezruo** [comment]
why should you have to create your own? This is such a simple thing to add
to the default template

**Comment by wesleycho** [comment]
Adding support for features that can be extended by the user is probably the largest cause of bloat in libraries, which is problematic if not all users want a particular feature.

**Comment by gomezruo** [comment]
okay fair point. Thanks for your help guys anyway
