### ISSUE TITLE
angular-bootstrap CLI builder

### ISSUE THREAD

**Issue by redhead** [angular-ui/bootstrap#4988]
Just as there is manual web-based builder to chose angular-bootstrap components to download. I would like to have it automated in our gulp build process. Is there a simple CLI tool that takes arguments like `modal`, `typehead` and builds the source and minified file with only those components?

**Comment by pkozlowski-opensource** [comment]
Nope, there is no specific CLI and we don't plan to have one (at least not now). To automate things you can still clone this repo and run the build on your end.
