### ISSUE TITLE
tool-tip-is-open throw an error

### ISSUE THREAD

**Issue by NetanelBasal** [angular-ui/bootstrap#4989]
I am using Version: 0.13.4 and when i am trying to set this attr:

```html

<div class="outer-progress"
       tooltip-is-open="{{expression}}"
       tooltip="msg">
</div>

```
I get this error:
```js
Uncaught TypeError: isOpenExp.assign is not a function

//In this section in the code:
if (isOpenExp) {
  isOpenExp.assign(ttScope.origScope, ttScope.isOpen);
}
```

**Comment by pkozlowski-opensource** [comment]
Try `tooltip-is-open="expression"` and direct general support questions like this one to an appropriate support channel in the future: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
