### ISSUE TITLE
uib-modal Trap focus doesn't work when keyboard: false option is provided

### ISSUE THREAD

**Issue by wawyed** [angular-ui/bootstrap#4990]
This is caused by this line https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L357

Most likely that check (`modal.value.keyboard`) should be inside the `case 27:` (escape key) and not surrounding the whole switch that also handles trap focus.

**Comment by wesleycho** [comment]
You mean the check should be inside case 27 - that is the escape key, 9 is the tab key.

Would you like to file a PR for this?

**Comment by wawyed** [comment]
Derp, sorry I mean case 27 escape key yes. I might to submit a PR for it but I'm quite busy at the moment. I might get some time next week.

**Comment by wesleycho** [comment]
Just let me know - this should be easy to fix and I can fix it, but I think it'd be a nice contribution if you'd like.
