### ISSUE TITLE
close-on-timeout ?

### ISSUE THREAD

**Issue by synthecypher** [angular-ui/bootstrap#4991]
Say I'm creating a copy to clipboard button, and I want to show a *"Copied"* tooltip on the button once they've clicked it.

However now the tooltip won't disappear until it's clicked again, I've tried using triggers `click mouseleave` but then it triggers whenever they mouse over and out and not just when it's clicked. 

Can we have to close similar to the `dismiss-on-timeout` directive found on the alert component?

**Comment by wesleycho** [comment]
You can use custom events with the tooltip to close it when desired - please refer to the [triggers section](http://angular-ui.github.io/bootstrap/#/tooltip) of the tooltip documentation.

Given that workaround, I do not believe we want to support this in the library itself since it is possible to accomplish with the given features.

**Comment by pkozlowski-opensource** [comment]
@wesleycho note for ng2 version - the basic pb here is that we don't expose a tooltip controller that people could hook into. With a controller exposed people could write their own directive, subscribe to whatever crazy events and just call a `close()` method on a tooltip controller. With such design we would just say: "hay, write your own directive".

**Comment by synthecypher** [comment]
@wesleycho So how would you implement close on timeout?
After tooltip is triggered, trigger a timeout which when it times out fires a custom event that then triggers the tooltip again?

So the triggers would be `click timeout`, but if they click and trigger the tooltip, then click it again to close it. Then timeout will trigger and open the tooltip again. Just doesn't seem like a sensible solution to have only the ability to trigger (toggle) the tooltip.

**Comment by wesleycho** [comment]
So one can set triggers for opening & the triggers for closing the tooltip via $uibTooltipProvider, like
```js
$uibTooltipProvider.setTriggers({
  click: 'timeout'
});
```
and then create a custom directive for use on the element with the tooltip like
```js
module.directive('tooltipDismissOnTimeout', function($timeout) {
  return {
    link: function(scope, element) {
      if (attrs.uibTooltip) {
        element.on('click', function() {
          if (!scope.tooltipIsOpen) {
            return;
          }

          $timeout(function() {
            element[0].dispatchEvent(new Event('timeout'));
          });
        });
      }
    }
  };
});
```
