### ISSUE TITLE
Hide Buttons in Carousel

### ISSUE THREAD

**Issue by AndreasHo** [angular-ui/bootstrap#4992]
Hello,

is there any chance to hide the prev/next button when i am on the first/last slide?

I use the uib-carousel with no-wrap.. and then i think the buttons are not very good :)

Bye Andreas

**Comment by wesleycho** [comment]
This can be accomplished via CSS & ng-class - this is best done on the user side.

**Comment by AndreasHo** [comment]
i don´t use ng-repeat so i can use my css instant as class, on the first slide which i define i can disablePrevButton and on the last slide i can disableNextButton.

But how is the correct css, because the buttons are not defined in carousel-inner (like slides) they are on the same level like carousel-inner :/

**Comment by wesleycho** [comment]
The ng-class would be on your component consuming the carousel, where one can easily determine whether the slide active is the first or last or not, and from there it becomes easy to write the appropriate CSS to hide the buttons of interest when the particular class is on your component.

**Comment by AndreasHo** [comment]
At this moment i find the solution of my problem :) now it works!
But thanks anyway.
