### ISSUE TITLE
template-url on uib-carousel approximately 1s load time

### ISSUE THREAD

**Issue by danielsomekh** [angular-ui/bootstrap#5004]
The load time for the uib-carousel templateUrl is approximately 1 second with an identical template. The network request time for the template is quick. I solved this issue by injecting the template I wanted into my application's template cache.

**Comment by pkozlowski-opensource** [comment]
You shouldn't be loading templates for directive via network - always use $templateCache. And we do distribute builds with $templateCache pre-populated - see https://github.com/angular-ui/bootstrap/blob/gh-pages/README.md and https://github.com/angular-ui/bootstrap/wiki/FAQ#im-using-modal-service-but-it-cant-find-its-templates

I don't think we can do much more - we don't have control over your environment not network setup and pre-populating $templateCache is what you should be doing anyway.
