### ISSUE TITLE
Include separate modules in custom builds

### ISSUE THREAD

**Issue by drKnoxy** [angular-ui/bootstrap#5006]
I thought it would be a cool feature if the 'Custom Builds' separated out each module. That way if i download and use the code for the datepicker, and then later download the code for dropdown I don't have two copies of position in  my lib.

For example I make a custom build of the datepicker module and receive the following files:

1. ui-bootstrap-dateparser-0.14.3.js and .min.js
    
    ```js
    angular.module('ui.bootstrap.dateparser', [])
    ```

1. ui-bootstrap-position-0.14.3.js and .min.js
    
    ```js
    angular.module('ui.bootstrap.position', [])
    ```

1. ui-bootstrap-datepicker-0.14.3.js and .min.js

    ```js
    angular.module('ui.bootstrap.datepicker', [
        'ui.bootstrap.dateparser',
        'ui.bootstrap.position'
    ])
    ```

1. ui-bootstrap-datepicker-tpls-0.14.3.js and .min.js 
    Also I wanted to point out that templates use double quotes instead of singles, and it irks me to see them mixed when i view `-tpl.js` file

    ```js
    angular.module('ui.bootstrap.datepicker.tpls', [
        'template/datepicker/datepicker.html',
        'template/datepicker/day.html',
        'template/datepicker/month.html',
        'template/datepicker/popup.html',
        'template/datepicker/year.html'
    ]);
    ```

1. And concatenated copies where `ui.bootstrap` is the only module you need to import
    
    ui-bootstrap-custom-0.14.3.js
    ui-bootstrap-custom-0.14.3.min.js
    ui-bootstrap-custom-tpls-0.14.3.js
    ui-bootstrap-custom-tpls-0.14.3.min.js

    ```js
    angular.module('ui.bootstrap', [
        'ui.bootstrap.datepicker',
        'ui.bootstrap.datepicker.tpls', // conditionally included
        'ui.bootstrap.dateparser',
        'ui.bootstrap.position'
    ]);
    // and then all of the modules concatenated below
    ```

This might be an interesting update for the docs revamp ticket https://github.com/angular-ui/bootstrap/issues/4798

**Comment by wesleycho** [comment]
We probably won't support this specifically, but keep an eye out for #4739 - with CommonJS via Browserify or Webpack, one will then be able to require only what one needs.
