### ISSUE TITLE
Ability to disable browser autocomplete for typeahead

### ISSUE THREAD

**Issue by chrisjlee** [angular-ui/bootstrap#5007]
So i ran into a UI problem when trying to use typeahead. Not sure if this has already been covered; if not i'll happily provide a pull request.

Problem:
I use typeahead and enter in a state. If i've previously entered in a value the browser autocomplete covers up my typeahead. This is problematic.

Solution:
1. By default autocomplete should be turned off for typeahead.  I think there should be an option to be able to turn this back on if needed. This could be simply accomplished by adding the `autocomplete="off"` attribute when the `uib-typeahead` directive is added.
2. Add documentation that ensures that people know about this option to turn autocomplete

**Comment by wesleycho** [comment]
One can override the template to do this locally - I'm hesitant about making this change because there is a way to override this simply and there's a decent chance someone will complain about this breaking change that I am not 100% convinced we should make.

**Comment by chrisjlee** [comment]
Respectfully, why would anyone want autocomplete on? It covers up the options as you typeahead?

**Comment by wesleycho** [comment]
Not necessarily forever, especially when we implement robust positioning support for typeahead.

In addition, there are two problems with removing it - users expect the UX of autocomplete, and `autocomplete="off"` is not respected by Chrome. As soon as we take a position on autocomplete, there is bound to be complaints.

Given those two points, it is better to let the user choose how to implement it.

**Comment by chrisjlee** [comment]
Alright. Fair points.
