### ISSUE TITLE
Invalid deprecation warnings

### ISSUE THREAD

**Issue by Cyricx** [angular-ui/bootstrap#5009]
The only thing I am using is the accordion, tab and dropdown, however, I still see the following warings:

$modalStack is now deprecated. Use $uibModalStack instead.
$tooltip is now deprecated. Use $uibTooltip instead.
typeaheadParser is now deprecated. Use uibTypeaheadParser instead.

I'm not even using the html tooltip anywhere in the entire solution. Can you please either add a quick option to disable the warnings, or just remove the warnings and create a breaking change version.

If you really want to keep a version that supports both, that might I suggest a stronger error check for when to display the warnings.

**Comment by icfantv** [comment]
@Cyricx, while some components require, and use, others, I suspect this may be a non-issue.  Please try using a build from master where we've removed all the deprecated code (and thus, warnings) to see if your app still behaves.

Please note that there are a bunch of other breaking changes in `master` so you probably don't want to upgrade just yet - just test to see if those warnings go away (which they will) and your app still works.

**Comment by wesleycho** [comment]
One can override the warnings via $provide.value.

I suspect something else going on in your code though, and that they are likely valid warnings.
