### ISSUE TITLE
tooltip-append-to-body not working on disabled elements

### ISSUE THREAD

**Issue by pjlasl** [angular-ui/bootstrap#5012]
Is there a way to display a tooltip on an element that has been disabled?

For example, I have a button that is disabled, but I would still like the tooltip to be shown when I hover over the button...

**Comment by pkozlowski-opensource** [comment]
This is a browser limitation where events are not fired on disabled element. See discussion in http://stackoverflow.com/questions/3100319/event-on-a-disabled-input as an example.

Sorry, we can't do much about this one

**Comment by icfantv** [comment]
@pjlasl, one final note.  Maintaining a popular OSS project requires a lot of hard work by many people.  We ask that you please be respectful of our time by searching existing issues (both open and closed) prior to entering anything.  This issue has been addressed several times already.  Thank you.

**Comment by pjlasl** [comment]
Thank you for replying so quickly :). I am looking into the workaround now.

On Fri, Dec 4, 2015 at 2:29 PM, Adam Gordon <notifications@github.com>
wrote:

> @pjlasl <https://github.com/pjlasl>, one final note. Maintaining a
> popular OSS project requires a lot of hard work by many people. We ask that
> you please be respectful of our time by searching existing issues (both
> open and closed) prior to entering anything. This issue has been addressed
> several times already. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/bootstrap/issues/5012#issuecomment-162073514>
> .
>



-- 
Thanks,

Peter Leaf
