### ISSUE TITLE
I found a bug at uibPopover directive  about popover-popup-close-delay

### ISSUE THREAD

**Issue by seeyou19992006** [angular-ui/bootstrap#5015]
It seems that the popover control where hide  delayed when I set popover-popup-close-delay="xxx" , but actually it hides directly
When I looked at the source code,I found  some code may cause problem at line 4709 in function hide
    
    ttScope.isOpen = false;
it makes the code at line 4727 doesn't work1

    transitionTimeout = $timeout(removeTooltip, ttScope.popupCloseDelay);

**Comment by seeyou19992006** [comment]
I'm Chinese, please ignore my poor English

**Comment by wesleycho** [comment]
These line numbers do not help at all - can you please post a simple reproduction on [Plunker](http://plnkr.co/edit/vs9R30f7BRP4R2PoBUHW?p=preview) .

**Comment by seeyou19992006** [comment]
I'm sorry for my careless, this bug has already been fixed before  v0.14.3
