### ISSUE TITLE
Custom template location and custom methods

### ISSUE THREAD

**Issue by dashawk** [angular-ui/bootstrap#5021]
Hi all,

I've read most of the template issues here and found the solution for the custom template locations by just adding this attribute `template-url="{{ templateLocation }}"` to the element.

But one problem that I've encountered is when I am using a custom method for that template, it gives me an error.

Here is an example for the timepicker directive:
![timepicker layout](https://cloud.githubusercontent.com/assets/1437205/11616641/4f02d8a0-9cbb-11e5-97fe-f83e3445f623.jpg)
![timepicker dropdown layout](https://cloud.githubusercontent.com/assets/1437205/11616642/5ba4dbc6-9cbb-11e5-833c-aa6c89c4ec02.jpg)

This is my custom layout for the timepicker. I manage to get this working.

The only BUT here is that the methods I use in the template like the click event, $watch, etc, I coded it directly in the tpls.min file which is not a good idea.

How can we add custom methods that can be used in the custom templates?

**Comment by wesleycho** [comment]
Perhaps making your own custom directives that are used in the template - this request is somewhat too vague for me to recommend a better course of action. This is a question not quite suited for GitHub issues though.
