### ISSUE TITLE
Help!How to set custom size of modal-dialog?

### ISSUE THREAD

**Issue by ibufu** [angular-ui/bootstrap#5025]
i want to set width of modal-dialog to 1130px.

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by ibufu** [comment]
sorry

**Comment by icfantv** [comment]
@ibufu, i didn't see you post this to SO yet, so here's probably the easiest way to do this:

1.  Set the `windowClass` option on your modal, to say, `my-modal`.
2.  Create a CSS class like the following:
```
div.my-modal > div.modal-dialog {
  width: 1000px !important;
}
```

You will almost certainly need the `!important`.

**Comment by ibufu** [comment]
@icfantv, thanks,
I tried your way, but windowClass was added to uib-modal-transclude.it canot set its width.
So I set the size option to w1130, and Create a CSS class like that .modal-w1130 {
    width: 1130px;
}
it works.

**Comment by icfantv** [comment]
That's odd.  I'm using that in our production application at work and it works fine.  What version of the library are you using?  We're using 0.14.3.

I suspect you're doing something incorrect.  Please create a SO question and link it here and I'll help you out there so others can benefit as this is a common question.

**Comment by mahit777** [comment]
@ibufu are you saying you did this 
`this.modalService.open(component, { size: 'w1130', backdrop: 'static',windowClass:'custom-modal animated slideInUp'});`

**Comment by msmani9891** [comment]
can we set the size after the modal Opened? 
Say for Example: The modal should have two size toggle button inside the modal.
1) Full Screen
2) modal-lg

I might able to toggle these two once the modal is opened.
