### ISSUE TITLE
Can't use variables inside of uib-typeahead

### ISSUE THREAD

**Issue by iamfrontender** [angular-ui/bootstrap#5026]
Hi, guys, please consider following markup:

```html
<input ... uib-typeahead="item['{{searchModel.key}}'] for item in searchModel.items | filter:$viewValue">
```
It tries to implement an abstract configurable wrapper over the typeahead (long-live higher level components). Though it'll never work as expected cause it'll never be interpolated (unlike in the older typeahead).

The problem is pretty much similar to #5000, though it looks like a regression taking into account, older typeahead handles this.

**Comment by iamfrontender** [comment]
Closed as this is not an expression and shouldn't support {{}}, it's possible to refer the value directly.

**Comment by markbucknellcc** [comment]
I wish to reopen this as my problem is pretty much the same as above but the variable represents the expression.

`<input ng-if="advanced != true"ng-model="search" type="text" class="form-control" ui-keypress="{13:'cancelEnter($event)'}" name="inputUser" id="inputUser" placeholder="{{placeholder}}" uib-typeahead="{{display}} in source | filter:$viewValue | excludeFilteredItem:filtered | limitTo:8"
                    typeahead-on-select="addFilterItem($item, $model, $label)"
                    typeahead-editable="false"
                    >`

**Implementation**

`<typeahead-filter
            source="clients"
            display="client as (client.name) for client"
            ng-model="filters.client"
            placeholder="Start typing to find client"
            title="Filter by Client"
        ></typeahead-filter>`
