### ISSUE TITLE
Frequently changed active slide in carousel crashes a carousel.

### ISSUE THREAD

**Issue by mazavr** [angular-ui/bootstrap#5031]
uibSlide derective has "active" property. I can use this to change current slide in a carousel.
And when I use the property during an animation, it crashes the carousel.
Use http://plnkr.co/edit/8GRoO3?p=preview and try to click different links below a carousel frequently.
Actually I don't know if I use undocumented approach or not.

**Comment by wesleycho** [comment]
This is actually fixed in `master` currently
