### ISSUE TITLE
Inconsistent time with datepicker

### ISSUE THREAD

**Issue by natcohen** [angular-ui/bootstrap#5033]
http://plnkr.co/edit/iBjdxpt0onsD6OdIQMDH?p=preview is an example of the inconsistency. If you look on top, you'll see that the time is 'now'. Each time you'll select a date, it will keep the time.

But when you clear and reselect a date, you'll get 00:00:00

The same behavior when you click on the date next to 'Today'.

PS I think that the time should always be 00:00:00. There is no point of keeping the time for a datepicker!

**Comment by wesleycho** [comment]
Actually, there is a reason for keeping track of time - people are using the same date model in both the datepicker and timepicker.

I'm not sure we want to support modifying this behavior as a result.

**Comment by natcohen** [comment]
@wesleycho I see but it's very confusing... Not sure what would be the best solution but the current one seems very inconsistent

**Comment by wesleycho** [comment]
Problem is, if someone removes the model, we would have no knowledge as to what the time should be, nor should we assume knowledge.

Unfortunately, this is not a problem that is really solvable until we properly support timezones.

Going to close this given this situation - this should behave better when timezones are properly handled.
