### ISSUE TITLE
Version selector for documentation and other improvements

### ISSUE THREAD

**Issue by anilnatha** [angular-ui/bootstrap#5035]
Yesterday, I was reading the documentation for the Accordion component and when trying to implement it in my application, it didn't work. While investigating my issue, I found the [0.14.x migration guide](https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes), which while helpful, annoyed me a bit because had a link, or even just a mention of these changes been provided on the [documentation page](https://angular-ui.github.io/bootstrap/), it could have saved me some time since my app is currently running v0.13.4. While I have no reservations about upgrading to the latest version of Angular UI Bootstrap, others may. So providing documentation for older versions, in addition to new versions, would be most helpful, along with important details, like info about the migration guide.

So if I had to sum up what I would have liked to see on the documentation page:

1. A version selector so that developers could see documentation for older versions of Angular UI Bootstrap in addition to the latest version.
2. Improve the amount of detailed information included in the [documentation](https://angular-ui.github.io/bootstrap/) that directly impact usage of the component(s) since this is typically the first place I feel many developers go for reference.

In some ways, this request may be related to Issue https://github.com/angular-ui/bootstrap/issues/4798

Thank you for your time.

**Comment by Foxandxss** [comment]
I am sorry but I am not following you at all.

What is the issue with the migration guide? Or perhaps you got confused because you were running 0.13.4?

Also, there is versioned docs, there is a dropdown in the docs page where you can change to other versions.

**Comment by wesleycho** [comment]
FWIW, the migration guide is linked in the README [here](https://github.com/angular-ui/bootstrap/blob/master/README.md).

**Comment by anilnatha** [comment]
Sorry for the confusion @Foxandxss. There is no issue with the migration guide. The issue I had is that no where on [this documentation page](https://angular-ui.github.io/bootstrap/) was it stated that the prefixes were added. So a person running an older version that comes to the [documentation page](https://angular-ui.github.io/bootstrap/), isn't made aware that based on the documentation shown, you _must_ be using the version 0.14.x; otherwise, the sample code won't work.

Now if there was a version selector shown on the documentation page, that when set, displayed the documentation specific to that version, it would have saved me the trouble because for version 0.13.4, the accordion tag is simply `accordion`; whereas, for version 0.14.x, the tag is `uib-accordion`, and there are probably differences that developers should be made aware of between various releases.  We can't all upgrade to the latest and greatest. And for devs running legacy apps built on older versions, where do they find the documentation for older releases of the library? I didn't see anything on the documentation page regarding information specific to 0.13.4, or any older version for that matter.

@wesleycho, thank for that bit of info, but again, as far as reference goes, why should developers look at the wiki, readme, and [documentation](https://angular-ui.github.io/bootstrap/), and other sources to piece together information about how to use the library. It can be challenging, but if the most important aspects of a release can be located in one place, it can make the developers job of researching information about the library and how to use it, easier to hunt down.


The best example of what I am trying to convey is shown here: https://docs.angularjs.org/api

Notice at the top left, there is a dropdown where a dev can select what version of angular js they are running, and when this is set the documentation displayed is specific to that selected angular js version.
![screen shot 2015-12-08 at 11 43 49 am](https://cloud.githubusercontent.com/assets/931107/11666388/1cf6f1c0-9da1-11e5-8922-caad411c0124.png)

**Comment by Foxandxss** [comment]
we have a dropdown to select versions and you can see what is the actual version (in the download button).

what I agree on is having docs in the homepage + migration guide only in the wiki (wiki only have that interesting tbh).

So the point would be having something in the homepage that links to migration guide. The whole homepage needs a new face to be honest.

I hear your issues and I agree with them. Do you want to help fixing that? We all give our free time to this project so we could use more help on that.

**Comment by Foxandxss** [comment]
I created a PR to put the migration guide link on the homepage. About the version. I have mixed feelings, you can see it like:

![](http://puu.sh/lOisN/29622f466d.png)

That always worked for me. That doesn't mean that it should work for everyone else.

**Comment by anilnatha** [comment]
@fassetar Thank you for making the changes and creating the PR. I appreciate it.

I understand that many of the projects on GitHub are community driven and it takes a lot of effort to keep them going. I would be happy to help as best I can. I will read up on the contribution guidelines and read through some of the issues in hopes that I can find something that I can work on.

**Comment by wesleycho** [comment]
I think you meant @Foxandxss :P . The only thing left is for him to retrofit the existing docs so it has this improvement.

**Comment by Foxandxss** [comment]
Ah, I knew I had to do something. I will retrofit to add the migration guide to 0.14.0+ and about making visible the current version, I don't know, I like the button.

**Comment by anilnatha** [comment]
Whoops! Fixed mention. ;)

**Comment by Foxandxss** [comment]
I retrofitted the migration thing to all 0.14.x versions.

I am not going to make any change to put the doc version in another place. I don't find a good idea for that.
