### ISSUE TITLE
span.badge.pull-right in div.dropdown-menu line-breaks

### ISSUE THREAD

**Issue by PassionatePro** [angular-ui/bootstrap#5038]
![image](https://cloud.githubusercontent.com/assets/7323026/11682276/b68ffdb6-9e89-11e5-9a3f-8b6c2d0f54cf.png)

JSBin Demo: http://jsbin.com/tabenizono/edit?html,js,output

Could you look into this issue?

**Comment by pkozlowski-opensource** [comment]
There is no line break here, this is bootstrap CSS at play here, see: http://stackoverflow.com/questions/198153/why-does-the-css-min-width-attribute-not-force-a-div-to-have-the-specified-minim

Closing as this is not a problem with this library but rather how bootstrap CSS works. Feel free to report in Bootstrap's repo if you believe that this is a bug.
