### ISSUE TITLE
angular ng-options is not working in modal 

### ISSUE THREAD

**Issue by hemnysingh** [angular-ui/bootstrap#5041]
ng-options is not working in modal for chrome-v47.0.2526.80 (64-bit) in Linux and windows. It is working in Mac with the same version. I am not able to select the value from the dropdown. If it's working fine if it is not in the modal. In older version of chrome(v46.0.2490.85), It was working. 
[Here] (http://jsfiddle.net/hemny/tdu4x2m0/6/) is JSFiddle demo.

**Comment by wesleycho** [comment]
I'm confused - it appears to be working [here](http://jsfiddle.net/1jxk4ghv/).

**Comment by hemnysingh** [comment]
Did you check your chrome version? Which OS are you using? As I wrote above, this issue appears in Windows/Linux ChromeV47.0.2526.80.

**Comment by metimus** [comment]
Had the same problem with metioned Chrome version and AngularJS v1.2.14, after changing to AngularJS v1.2.24 problem was solved.

**Comment by hemnysingh** [comment]
@metimus Thank you. It works for me.
