### ISSUE TITLE
Modal open when press enter

### ISSUE THREAD

**Issue by rodrigomvf** [angular-ui/bootstrap#5042]
After opening and closing the modal, every time you press enter the modal will open.
This behavior happens on the sample page.

**Comment by icfantv** [comment]
@rodrigomvf, that's because the button still has focus and is active.  if you change the focus by clicking elsewhere on the page, it works as designed.

**Comment by rodrigomvf** [comment]
I built a system that has this problem.
Even without opening and closing the modal and focus on any input, pressing the enter opens a modal.

**Comment by icfantv** [comment]
If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).
