### ISSUE TITLE
Opening modal on focus causes infinite loop

### ISSUE THREAD

**Issue by GrosBibi** [angular-ui/bootstrap#5043]
When opening a modal from an input text on focus, it causes an infinite loop since the opener get the focus back when the modal is closed or dismissed.

Plunker here : http://plnkr.co/edit/3bCv0M9eJL3TT4aByhYz?p=preview

Thanks guys !

**Comment by GrosBibi** [comment]
My users needs to translate what they are typing, so what I want to do is : 
- Input text with default language 
- On focus, modal open with an input for each language available

**Comment by GrosBibi** [comment]
I think I could have work around this by using the closed promise added in this commit : https://github.com/angular-ui/bootstrap/commit/e9c4977dc4a326b19694ae4e12784d22a90f1f99
Something like disable focus before opening, and enable it after the modal is closed.

**Comment by wesleycho** [comment]
We should have 1.0 released by the end of the year - would that feature work for you as far as addressing this infinite loop goes?

Temporarily, one could also try creating a directive to focus something else when the modal closes.

**Comment by GrosBibi** [comment]
I think it would. But anyway, I worked my way around by not using an input to open the modal.

**Comment by wesleycho** [comment]
Going to close this as resolved - let us know if there is still an issue.
