### ISSUE TITLE
Is it possible to send the longitude/latitude in the results from Typeahead into a hidden textfield?

### ISSUE THREAD

**Issue by sterichards** [angular-ui/bootstrap#5045]
I want the potential addresses to to be listed and upon clicking one, the longitude/latitude from the Google Maps API to be sent somewhere hidden on the page.  I can send it to the address input text box but it's not something I want the user to see

**Comment by wesleycho** [comment]
Sounds like something you can do on the user side by doing an ng-repeat over the results with inputs of type hidden.

**Comment by wesleycho** [comment]
Oh correction, by doing maybe
```html
<div uib-typeahead="..." ng-model="my.model"></div>
  <input type="hidden" ng-if="my.model" value="{{appropriateValueFromModel()}}">
</div>
```

**Comment by sterichards** [comment]
Cool. thank you. I will make the attempt later

**Comment by wesleycho** [comment]
Going to close this as a usage issue - feel free to add to this if your use case is more complex & not captured by available API.

**Comment by sterichards** [comment]
I've added the following to my view:

`<div class='container-fluid typeahead-demo' id="address">
            <label for="address">Address</label>
            <input type="text" ng-model="asyncSelected" placeholder="Locations loaded via $http"
                   uib-typeahead="address for address in getLocation($viewValue)" typeahead-loading="loadingLocations"
                   typeahead-no-results="noResults" class="form-control">
            <i ng-show="loadingLocations" class="glyphicon glyphicon-refresh"></i>

            <div ng-show="noResults">
                <i class="glyphicon glyphicon-remove"></i> No Results Found
            </div>
        </div>`

        `<div uib-typeahead="address for address in getLocation($viewValue)" ng-model="test">
            <input type="hidden" ng-if="test" value="moose">
        </div>
        Model: {{test}}`

The first code block is what's used to display the address and that works (it's a copy and paste from the Typeahead example documentation.
The second code block is what i've added to test sending something to the hidden value but there is no output after 'Model:'

**Comment by sterichards** [comment]
There is a slightly less good way to do this. I could add an ng-change to the textbox which displays the address. When the address is added to the textbox, the lat/long could be added inside of some characters, IE '10 Downing Street, London, UK **Lat: x, Long: x** and the ng-change could fire an Angular function which strips the '**Lat: x, Long: x**' from the textbox and adds it to a variable.

That is a fallback approach though and will be used as last resort

**Comment by sterichards** [comment]
I've also just noticed this in the documentation for Typeahead:

'typeahead-on-select($item, $model, $label) (Defaults: null) : A callback executed when a match is selected'

That should help me to accomplish my task, I believe?

**Comment by sterichards** [comment]
I have solved this with the following not so good code:

```<div class='container-fluid typeahead-demo' id="address">
            <label for="address">Address</label>
            <input type="text" ng-model="asyncSelected" placeholder="Locations loaded via $http"
                   uib-typeahead="address for address in getLocation($viewValue)" typeahead-loading="loadingLocations"
                   typeahead-no-results="noResults" typeahead-on-select="updateAddress($item, $model, $label)" class="form-control">
            <i ng-show="loadingLocations" class="glyphicon glyphicon-refresh"></i>

            <div ng-show="noResults">
                <i class="glyphicon glyphicon-remove"></i> No Results Found
            </div>
        </div>```

```$scope.updateAddress = function ($item, $model, $label) {
            var selectedAddress = $item;
            var addressDisplay = selectedAddress.substr(0, selectedAddress.indexOf('**'));
            var latLong = selectedAddress.substr(selectedAddress.indexOf('**'));
            latLong = latLong.replace('**', '');
            latLong = latLong.replace('**', '');

            $scope.asyncSelected = addressDisplay;
            $scope.latLong = latLong;
        };```
