### ISSUE TITLE
Setting tab Active with $scope disables other tabs

### ISSUE THREAD

**Issue by DevQueen** [angular-ui/bootstrap#5047]
I am using Angular 1.4.6 and ui-bootstrap 0.13.4.  I have a tab that is disabled.  When the user clicks a button, I want to enable the tab and make it active (I am using $scope.noView = true/false and active = noView).  This works fine, accept that once it becomes Active all other tabs are non-clickable.  The don't show as being disabled, but clicking on them does nothing.  Am I missing something?

**Comment by RobJacobs** [comment]
https://github.com/angular-ui/bootstrap#found-a-bug
