### ISSUE TITLE
Datepicker Font's Not Loading

### ISSUE THREAD

**Issue by joelcdoyle** [angular-ui/bootstrap#5049]
Using with bootstrap-sass 3.3.5, and trying to use Datepicker. Fonts are available in fonts/bootstrap, and the rest of the website works with glyphicons and bootstrap fonts. For some reason only fonts in datepicker are not working.

This warning is shown in Chrome debugger. No error shows up in safari, but the fonts are not displaying. No 404's all files are successfully retreived.
```
Failed to decode downloaded font: http://localhost:5000/fonts/bootstrap/glyphicons-halflings-regular.woff2
(index):1 OTS parsing error: invalid version tag
(index):1 Failed to decode downloaded font: http://localhost:5000/fonts/bootstrap/glyphicons-halflings-regular.woff
(index):1 OTS parsing error: invalid version tag
(index):1 Failed to decode downloaded font: http://localhost:5000/fonts/bootstrap/glyphicons-halflings-regular.ttf
(index):1 OTS parsing error: invalid version tag
```

**Comment by wesleycho** [comment]
I don't think that is a UI Bootstrap error - we need more information here, as we do not see this issue on the docs page [here](http://angular-ui.github.io/bootstrap).

**Comment by joelcdoyle** [comment]
Issue was not with ui-bootstrap. Removing *.woff2 file from the dist folder of my app solved the problem.

**Comment by wesleycho** [comment]
Glad to hear it :)
