### ISSUE TITLE
Getting data based on the ENTER hit by the user -TypeAhead.js 

### ISSUE THREAD

**Issue by azhagulakshman** [angular-ui/bootstrap#5054]
I have not used TypeAhead before and I have a requirement where i need to populate the result set from an external REST service in the following scenarios:
1. When user selects a particular data from suggestion (Achieved by selected event).
2. When user hits enter, I need to pull all the records which are matching to the "text" entered by user. It can be any text like aaaa, bbb, abver etc. 

I am facing a problem in achieving the requirement No.2 . I dont want to select the first suggested result set, which can be fetched by autoselect option.

Is there any way to fetch the records and display it on console, based on any input from user. 

I believe, we need to have a custom event but it would be great if any one of you people already achieved the solution.

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
