### ISSUE TITLE
datepicker-popup remains on screen when launched from modal that goes away 

### ISSUE THREAD

**Issue by bhelzer** [angular-ui/bootstrap#5058]
Open a datepicker-popup from a modal, with datepicker-append-to-body set to true. Click outside the modal to close it. The datepicker stays around even though its scope was destroyed.

See http://plnkr.co/edit/YdWmqYPFBNbv4vhQZc4t?p=preview

**Comment by wesleycho** [comment]
This looks like a bug to me, but need further investigation. What appears to be happening is that the popup is binding to an incorrect template when appendToBody is used, causing a comment tag to be removed instead of the right element.

**Comment by deeg** [comment]
I am also having this issue, it does seem to be a bug.

Destroying the scope keeps the datepicker visible on the screen. The modal does not have anything to do with it, the issue happens with any $destroy event.

**Comment by wesleycho** [comment]
Yeah, the incorrect DOM node is being used to remove - this is a bug in our tracking of the popup DOM element.

**Comment by deeg** [comment]
Sounds good, will try to get out a PR for this in the next few days.
