### ISSUE TITLE
Popover events not working

### ISSUE THREAD

**Issue by epnikolop** [angular-ui/bootstrap#5060]
Are the popover event's supported

I want to set a custom position relative to the last css calculation and I cannot achieve that as .on('shown.bs.popover' ....) doesn't work

**Comment by epnikolop** [comment]
An example http://plnkr.co/edit/QMTxCXMkmKJuIYUCk6dK?p=preview

**Comment by icfantv** [comment]
If I understand what you are trying to do here, I would argue that what you're trying to do is well outside the scope of this library.  Can you please explain what you are trying to accomplish and why?

You might be interested in the new feature we have slated for 1.0 (currently in `master`) where we allow positional placement similar to Bootstrap core.

At this point, please explain what you want to do (from a high level) and we'll proceed from there.   Thanks.

**Comment by wesleycho** [comment]
We do not support event APIs from Bootstrap, and do not intend to.

We do need more detail though, as your use case is not clear as to why it must be done this way.

**Comment by epnikolop** [comment]
I'm trying to align the start of the popover in x-axis with the start of the button and move the popover arrow in the right side and not in the middle, and because the button that triggers popover change places i cannot put this inside CSS but must do this dynamically.

**Comment by icfantv** [comment]
@epnikolop, I'm still not sure what you're trying to do.  It sounds like you are trying to do custom popover placement via CSS via a wrapping directive?  If that's the case, I'm not sure there's much we can do here since you're doing something outside of the functionality the API provides.

As I mentioned, please pull the latest from `master` and see if the new, positional placement, is something that will work for you.  Please let us know.

**Comment by epnikolop** [comment]
You could close it thanks

**Comment by icfantv** [comment]
Closing as requested.

**Comment by VaibhavP17** [comment]
@icfantv @epnikolop : I know this is an old thread but I could not find any other place to ask the question. I have a requirement, "whenever popover is opened, put the focus on first input field, if available". 
For this, I would require an event **.on('shown.bs.popover' ....)** . So, that I can put the focus on the input field (for e.g.: [as show in this answer](http://stackoverflow.com/questions/31510756/focus-on-input-field-when-popup-shownbootstrap-popover))

Kindly let me know if it is possible now, or is there a better way to achieve the objective.

Thanks in advance.
