### ISSUE TITLE
tooltip-html does not work properly

### ISSUE THREAD

**Issue by yovin99** [angular-ui/bootstrap#5068]
Hi,

I have edited the plunker that i found in a previous example [https://github.com/angular-ui/bootstrap/issues/3821] according to what i actually needed, this works fine for me when i am using tooltip-html-unsafe. this is just a sample that i have added here but i wanted to do something like this.

http://plnkr.co/edit/16U6Nvdfx1fsnkJF8gLQ?p=preview

**Comment by frfancha** [comment]
You must give to tooltip-html the result of applying $sce.trustAsHtml to your expression and then it works perfectly (exactly as when you want to use html in angular expression by the way).
There is no problem.

**Comment by wesleycho** [comment]
@frfancha is correct - [here](http://plnkr.co/edit/9hGDLWhJ1Vd3VJKJx5M9?p=preview) is an example of using tooltip-html, and using tooltip-template, which is what you really want in this case.

**Comment by yovin99** [comment]
@wesleycho Thankyou but isn't is possible to use as inline expression rather using a different html template???

**Comment by wesleycho** [comment]
`tooltip-html` is for static content, while a template is for what you desire - one can manually insert that inline expression into $templateCache, but be sure to be careful about the HTML you insert to avoid XSS issues.
