### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by guilhermecvmnsj** [angular-ui/bootstrap#5070]
When is 0.14.4 is going to be released?

**Comment by icfantv** [comment]
@guilhermecvmnsj, at this point we are not planning on a 0.14.4 release.  Rather, we are focusing on getting 1.0 out the door and currently are targeting doing so by the end of the year.  If you are anxious for  this release, you may pull `master` and build the latest SNAPSHOT version for you to do development against.

**Comment by icfantv** [comment]
@guilhermecvmnsj, also, maintaining a popular OSS repository requires a lot of time and effort by many people who do this in addition to their day jobs.  As such, we ask that you please extend us the courtesy of searching both open and closed issues prior to opening a new one.  This question has been asked several times in the past few weeks, including within the past 24 hours.  Thanks.
