### ISSUE TITLE
autofocus: $digest already in progress

### ISSUE THREAD

**Issue by dizel3d** [angular-ui/bootstrap#5077]
`Error: [$rootScope:inprog] $digest already in progress` for modal containing `<input autofocus>`.
Demo http://jsfiddle.net/dizel3d/dayapLwo/. ui-bootstrap 0.14.3, angular 1.4.7. I reproduced the bug in Chrome 47.0.2526.80 m, Edge and Firefox.
The problem is that $uibModal triggers focus event in $digest cycle.
```javascript
$q.when(animationPromise).then(function() {
  var inputWithAutofocus = element[0].querySelector('[autofocus]');
  /**
   * Auto-focusing of a freshly-opened modal element causes any child elements
   * with the autofocus attribute to lose focus. This is an issue on touch
   * based devices which will show and then hide the onscreen keyboard.
   * Attempts to refocus the autofocus element via JavaScript will not reopen
   * the onscreen keyboard. Fixed by updated the focusing logic to only autofocus
   * the modal element if the modal does not contain an autofocus element.
   */
  if (inputWithAutofocus) {
    // THE PROBLEM IS HERE
    inputWithAutofocus.focus();
  } else {
    element[0].focus();
  }
});
```

**Comment by wesleycho** [comment]
In this case, the problem seems to be in your directive - in your listener for your directive, you should do a check for $rootScope.$$phase first.
```js
scope.value = 'focus';
if (!$rootScope.$$phase) {
  $rootScope.$digest();
}
```

**Comment by dizel3d** [comment]
Thank you! But, seems, `$$phase` is not documented opportunity. So, I think, `$evalAsync` is better in my case.
```
scope.$evalAsync(function() {
  scope.value = 'focus';
});
```

**Comment by wesleycho** [comment]
While $$phase is undocumented, it is a very well known work around, and even used in under the hood vastly, as seen in https://github.com/angular/angular.js/blob/master/src/ng/rootScope.js#L990-L999, https://github.com/angular/angular.js/blob/e57cf13d5da204a3324e8b083718c0dcfbb58207/src/ng/http.js#L1276, and many other places ($rootScope, $animate, ngModel, etc.) - it is much preferred over forcing async unnecessarily.

**Comment by dizel3d** [comment]
@wesleycho, thank you for your help again!
