### ISSUE TITLE
Datepicker popup's initial format is broken in angular 1.5.0

### ISSUE THREAD

**Issue by luongvanphuc** [angular-ui/bootstrap#5081]
Please refer to https://github.com/angular-ui/bootstrap/issues/3025
Commented by rustygreen: "The datepicker popup's initial display value does not use the passed in format. After you select a value for the first time, it will display it property (using the passed in format)."

Angular 1.4.8 works fine but 1.5.0:
http://plnkr.co/edit/cg1Uj5kF8fNAaNuTvxVY?p=preview

**Comment by wesleycho** [comment]
This appears to be an issue with current `master` as well, as can be seen [here](http://plnkr.co/edit/jzLMdCLvgb91FoRhVAoh?p=preview).

**Comment by wesleycho** [comment]
Looks like a workaround for now is to use `init-date` as the same value as your model, as shown [here](http://plnkr.co/edit/GB6YLgykzX5HxKBnPsdi?p=preview) - need to investigate further though.
