### ISSUE TITLE
Remove src & template from .npmignore

### ISSUE THREAD

**Issue by sashless** [angular-ui/bootstrap#5084]
Previously it was possible to load just modules i need but in the recent version `0.14.3` https://github.com/angular-ui/bootstrap/commit/27f7ca26d28f7bd05cd77c3380fd52e357230ed8

`src` and `template` among others were added to the `.npmignore` file.
As result only the build files are present in the npm package.

But i need the module files in `src` and `template` to avoid using the build result file.

Please remove `src` & `template` from `.npmignore` :)

**Comment by Foxandxss** [comment]
The package we have as today is not based on this repository but `boostrap-bower` who doesn't have the src nor template.

I think there are plans to move npm package back to this repo so for 1.0.0 you will have access to src and template.

I am closing this one :)

**Comment by sashless** [comment]
Honestly I don't know what you are talking about. 

There is https://www.npmjs.com/package/angular-ui-bootstrap which points to this repository? 

In addition I can use the git repo as installation source as well even when there is no package on npm available. 

@Foxandxss

**Comment by Foxandxss** [comment]
The URL in there can point where you want to, that is just a field on package.json.

The home of the package is: https://github.com/angular-ui/bootstrap-bower

And there is no src or template folder.

That will change for 1.0.0

**Comment by sashless** [comment]
Well thanks for pointing that out. I assumed the field is pointing to the actual repository which would make more sense :)

Back to topic..

I am installing angular ui bootstrap from git like

`"angular-ui-bootstrap": "git+ssh://git@github.com:angular-ui/bootstrap.git#0.14.3"`

Given i use node `4.2.1` all i get is the bloated build results ( hard to believe that everyone is using the bloated build results ) instead of single modules.

Given i use `0.10.37` i get `src` & `template` files as well which is what i want to load just modules i need

But i dont want to use such an old version of node. I want to go back to `4.2.1` + updating angular ui bootstrap to `0.14.3`

I dont want to wait for `1.0.0` to get that possibility back because its a two line PR to change that so what ? =)

**Comment by sashless** [comment]
Honestly, I am just guessing it is because of `.npmignore` is handled differently in both node versions. Maybe you know what the real problem is ?

**Comment by wesleycho** [comment]
This sounds like there is something different being handled in npm.

One thing I should note is that we may be making a breaking change to publish from this repository for npm which will allow users to consume individual scripts or use the distribution version.

**Comment by sashless** [comment]
Yea indeed. I was a bit wrong above. 

When i install it like `"angular-ui-bootstrap": "git+ssh://git@github.com:angular-ui/bootstrap.git#0.14.3"` i dont get anything useful on node `4.2.1`

```
node_modules/angular-ui-bootstrap/
├── CHANGELOG.md
├── CODE_OF_CONDUCT.md
├── LICENSE
├── package.json
└── README.md
```
 
I removed `src` & `template` from `.npmignore`.  https://github.com/easybiblabs/angular-ui-bootstrap/commit/6a6772b1f4899b93a04256322fd27872ff2f3316

As result i get

```
node_modules/angular-ui-bootstrap/
├── CHANGELOG.md
├── CODE_OF_CONDUCT.md
├── LICENSE
├── package.json
├── README.md
├── src
└── template
```

That means our assumptions from above are correct.

Can you fix that please so people are able to actually install it from git correctly ?

**Comment by wesleycho** [comment]
So funnily enough, I already removed those in `master` - that will change in the 1.0 release, as seen from 384fdfc83de66b26de5a5ef4c70f51ea197b29ce

**Comment by sashless** [comment]
Nice but that means I need wait for the next release or use master because
ideally I would like to avoid forking?

Wesley Cho <notifications@github.com> schrieb am Do., 17. Dez. 2015 17:57:

**Comment by wesleycho** [comment]
I think you can actually specify a specific commit to use from npm. `master` is stable currently, so you would be just fine consuming from the latest in `master`.

**Comment by sashless** [comment]
yea true my friend but i would like to use a tag because its easier to look up :) That means its a `no` RE new release just for the npmignore changes :/ ?

**Comment by wesleycho** [comment]
Unfortunately no, that is largely because we are very close to being ready to release 1.0 formally.

**Comment by sashless** [comment]
At least one good news :) Thanks for removing that in 1.0 !
