### ISSUE TITLE
How to test content change after tab.click()?

### ISSUE THREAD

**Issue by basharov** [angular-ui/bootstrap#5086]
I have tabs created with this library.
When I run Protractor tests, how do I make sure that the content of the tab is updated, rendered and available after a tab click?

In my case, when I run this:

```javascript
element(by.cssContainingText('a[ng-click="select()"]', 'Visual')).click()
expect(element.all(by.repeater('row in data.tableData')).count()).toEqual(8);
```

The latter command doesn't seem to execute and hangs the testing completely. Then after some timeout I see this:

```
 Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

Do I need to wait somehow while the content loads into the tab content area?
Please share a piece of code as an example.

**Comment by wesleycho** [comment]
I believe you need to insert `ptor.waitForAngular();`, where `var ptor = require('protractor');`

**Comment by basharov** [comment]
It doesn't do any difference.
More than that, as written in docs `Note that Protractor automatically applies this command before every WebDriver action.`

**Comment by wesleycho** [comment]
This seems to not be a UI Bootstrap issue at all, which is why I closed this - keep a note that this issue tracker is for legitimate issues with UI Bootstrap itself, and feature requests.

This is a better question suited for a venue like StackOverflow.

**Comment by basharov** [comment]
I am asking here because when I comment out line with the `.click()`, test
tries to run and doesn't hang, though it fails as no required element is on
the page.
Can it be something in the `select()` function of the Bootstrap Tab
functionality?

**Comment by wesleycho** [comment]
Under the hood, what is happening is click -> active set -> ng-class toggles active on appropriate tabs from $watchers during $digest -> correct pane shows due to CSS.

There is no $timeout involved or anything async.

**Comment by bhoomi65** [comment]
I m getting the same issue as @basharov.My test case is just hanging up
