### ISSUE TITLE
Add ability to set templateUrl with uibTimepickerConfig

### ISSUE THREAD

**Issue by 40in** [angular-ui/bootstrap#5087]
new timepicker has uibTimepickerConfig but it doesn't support templateUrl option
It's still possible to set it via attributes, but it would be useful to configure it with standard config

you may check here: http://plnkr.co/edit/Uvw1ECUNK4S6mviz3Qak?p=preview

**Comment by wesleycho** [comment]
This would be an easy fix if you'd like to file a pull request for this feature - it would need one test to demonstrate that it is possible to override the config and it will use it to fetch a new template. One can use the tests for template-url in any component as a guide to how one would write it.

**Comment by deeg** [comment]
@wesleycho, are you saying you want the attribute set on the element to override the config if both are set?

I can work on getting a PR out for this.
