### ISSUE TITLE
support form validation classes for uib-dropdown

### ISSUE THREAD

**Issue by eliasre** [angular-ui/bootstrap#5088]
It would be nice if classes such as ng-untouched ng-valid ng-dirty etc was supported for uib-dropdown.
This would make it more similar to a select and easier to combine with form validation.

The classes are allready added to uib-btn-checkbox and uib-btn-radio.

**Comment by wesleycho** [comment]
This is just a simple dropdown - it does not even use ng-model. What use case do you have requiring validation on a dropdown?

**Comment by eliasre** [comment]
I need something to replace <select> and <option> in my forms. 
I can use uib-btn-checkbox and use my own styling to benefit from angular validation, but select is a problem.
If there is something I have missed and ui-bootstrap contains another styleable replacement for <select>, then I apologize for not finding this, However: I dont think my usecase (styling select/option while benefiting from validation inside forms) is uncommon.

**Comment by wesleycho** [comment]
Couldn't one use ng-class on the approach element and then use ng-click to set your model? This is a fairly unorthodox use of the UI Bootstrap dropdown component, but I don't see why this couldn't be solved simply on your side.

**Comment by wesleycho** [comment]
Going to close as something we don't want to support - for this use case, this should be simple to create your own mobile and manage the model & validation. This is custom logic that we do not want to bloat up the library with & support due to many users not needing such a feature.
