### ISSUE TITLE
Uncheckable is not working

### ISSUE THREAD

**Issue by tsmith-sdm** [angular-ui/bootstrap#5092]
The 3rd option on https://angular-ui.github.io/bootstrap/#/buttons using uncheckable does not disable the radio buttons.

**Comment by wesleycho** [comment]
Uncheckable is not about disabling the radio buttons (the name is a bit unfortunate) - it is about whether to allow unchecking by toggling the button while it is already selected.

To disable, one would obviously use ng-disabled.
