### ISSUE TITLE
Expression used with directive 'uibTab' is non-assignable!

### ISSUE THREAD

**Issue by manofearth** [angular-ui/bootstrap#5108]
With uib-tab directive:
```html
<uib-tab ng-repeat="source in page.getSources()"
             ng-click="pageController.setCurrentSourcePage($index)"
             active="pageController.isSourcePageCurrent($index)">
```

We have an error
```
Error: [$compile:nonassign] Expression 'pageController.isSourcePageCurrent($index)' used with directive 'uibTab' is non-assignable!
http://errors.angularjs.org/1.4.8/$compile/nonassign?p0=pageController.isSourcePageCurrent(%24index)&p1=uibTab
    at angular.js:68
    at parentSet (angular.js:8894)
    at parentValueWatch (angular.js:8907)
    at Object.regularInterceptedExpression (angular.js:14447)
    at Scope.$digest (angular.js:15888)
    at Scope.$apply (angular.js:16160)
    at HTMLAnchorElement.<anonymous> (angular.js:23618)
    at HTMLAnchorElement.jQuery.event.dispatch (jquery.js:4435)
    at HTMLAnchorElement.elemData.handle (jquery.js:4121)
```

**Comment by wesleycho** [comment]
Because it is a two way binding, one can only assign `active` to a variable, not a function invocation.

**Comment by manofearth** [comment]
It is possible to bind getterSetter to model with ngModelOptions (ngInput directive). May be it worth implementing something like that with "active" attribute?

**Comment by AmaarHassan** [comment]
Hi guys, i am very new to angular and i am getting this error
[$compile:nonassign] 
http://errors.angularjs.org/1.5.8/$compile/nonassign?p0=undefined&p1=active&p2=uibCarousel

i am using 
           <div uib-slide index="0">
                <img src="images/slider/1.jpg" active="active" style="margin:auto;" class="img-responsive">
........

and the error is recursive, it keeps popping up the console.
i will really appreciate your help
