### ISSUE TITLE
No validation can be added when user is trying to put date manually also having time zone  issue how to specify timezone on date field 

### ISSUE THREAD

**Issue by tkssharma** [angular-ui/bootstrap#5109]

**Comment by wesleycho** [comment]
Please explain this clearly - as written, it is difficult to parse what the problem is, as well as this conflating two different user issues.

For timezone, in `master` we are supporting ng-model-options' `timezone` option.

If input validation is the problem, it should be noted that one should create a custom directive to handle the validation as desired.

**Comment by tkssharma** [comment]
I have developed the application for my client and using angular UI-Date picker but now am facing issue when i am handling validation for manual user input , there is no way of masking the input to a specified pattern i am using JQuery masking which has issue with IE-11 .

My major concern is with date picker modal value and view values :+1: 
example when i enter 01 in date field its updating modal value to 01/01/2001 or any default value totally strange ...
Modal value is getting initialized with default values even when i have not specified complete date field.

I can handle the date format and masking issue but in manual input validation will always fails as modal value getting initialized with default values 
even if i enter 01 for MM/dd/yyyy format its valid date as  modal value has complete date object
  
http://plnkr.co/edit/fTFNu9Mp2kX5X1D6AJOx?p=preview
if you can suggest masking of date field same type  which is mentioned in this punker that will be helpful these mask library has issue with IE 11 .
Time Zone is another issue here i always getting date i day behind the mentioned date ..

**Comment by wesleycho** [comment]
For timezone, those issues are fixed in 0.14.3, through setting of the initial model value with the desired date object.
