### ISSUE TITLE
Modal backdrop not showing when multiple modals are opened

### ISSUE THREAD

**Issue by SMarijic** [angular-ui/bootstrap#5111]
I have modal in which you can open new modal on top of the existing one. The problem is when I open new modal, the backdrop does not switch in front of the first modal.

It should be like this:

--------------------------------------> 
| View | Modal 1 | Backdrop | Modal 2 |

Instead it's like this:

-------------------------------------->
 | View | Backdrop | Modal 1 | Modal 2 |

**Comment by icfantv** [comment]
@SMarijic, I answered your post on StackOverflow where this type of question is better suited.  Please do not use the issues forum for support requests as it is reserved for bugs.  In the future, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

Finally, when asking for help, and this applies to both your SO post and this one, it is nearly always impossible to debug something without any code.  Please be respectful of both our time and the SO community by putting forth an effort to show that you you have attempted to both debug the problem on your own and to give us the information needed to assist you.
