### ISSUE TITLE
Bug - Using mouse scroll button on an overflowed modal

### ISSUE THREAD

**Issue by msosa** [angular-ui/bootstrap#5112]
When we have an overflow scroll inside a modal and use the middle mouse click to scroll it seems to break all usage of the mouse.  I can't click anywhere in the tab and even after I close the modal and I have to close the tab and open a new one to fix the clicking problem.

This is only a problem on Chrome

**Comment by icfantv** [comment]
@msosa, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

**Comment by msosa** [comment]
Updated with a plunker.
