### ISSUE TITLE
0.14.3 accordion is-open state renders after page renders

### ISSUE THREAD

**Issue by greglbd** [angular-ui/bootstrap#5113]
I'm running into an issue that the accordion is-open state doesn't render until after the page finishes loading.  If you look at the [0.14.2 accordion](http://angular-ui.github.io/bootstrap/versioned-docs/0.14.2/#/accordion) the first item is open when the page loads, where as [0.14.3 accordion](http://angular-ui.github.io/bootstrap/versioned-docs/0.14.3/#/accordion) opens the accordion after the page load.  this causes an undesirable effect if you're using ng-animate.

**Comment by greglbd** [comment]
I see that this a duplicate of https://github.com/angular-ui/bootstrap/issues/4849

**Comment by icfantv** [comment]
@greglbd, many, many thanks for doing due diligence and closing this after you found it was a duplicate.  Being proactive like this helps us immensely and is greatly appreciated.

**Comment by greglbd** [comment]
No problem.  However, I still haven't solved the issue.  Hopefully I will once i've fully investigated all solutions out there
