### ISSUE TITLE
uibDateParser not parsing times

### ISSUE THREAD

**Issue by Gillardo** [angular-ui/bootstrap#5114]
The uibDateParser has this code near the end of it

```
      if (isValid(fields.year, fields.month, fields.date)) {
        if (angular.isDate(baseDate) && !isNaN(baseDate.getTime())) {
          dt = new Date(baseDate);

          // this is the cause of the error setFullYear only accepts year, month and day...
          dt.setFullYear(fields.year, fields.month, fields.date,
            fields.hours, fields.minutes, fields.seconds,
            fields.milliseconds || 0);
        } else {
          dt = new Date(fields.year, fields.month, fields.date,
            fields.hours, fields.minutes, fields.seconds,
            fields.milliseconds || 0);
        }
      }
```

This is wrong.  setFullYear only accepts year, month and date, so why pass in hours, minutes, seconds and milliseconds?

Also the uibDateParser works out the hours, minutes, seconds and milliseconds as shown here

```
    if (angular.isDate(baseDate) && !isNaN(baseDate.getTime())) {
        fields = {
          year: baseDate.getFullYear(),
          month: baseDate.getMonth(),
          date: baseDate.getDate(),
          hours: baseDate.getHours(),
          minutes: baseDate.getMinutes(),
          seconds: baseDate.getSeconds(),
          milliseconds: baseDate.getMilliseconds()
        };
      } else {
        if (baseDate) {
          $log.warn('dateparser:', 'baseDate is not a valid date');
        }
        fields = { year: 1900, month: 0, date: 1, hours: 0, minutes: 0, seconds: 0, milliseconds: 0 };
      }
```

So i believe the last part of this function (posted first), is invalid, and should just be

```
      if (isValid(fields.year, fields.month, fields.date)) {
          dt = new Date(fields.year, fields.month, fields.date,
            fields.hours, fields.minutes, fields.seconds,
            fields.milliseconds || 0);
      }
```

This seems to work then when typing into an input, and works out the date correctly.  I have this issue as i have the developer for the angular-ui-datetime-picker and this is an issue when trying to set the time, when typing into the input field.  All other fields work fine.

I have added a plunkr here, where you can see the error.  You will notice i have copied the uibDateParser service into the script.js.  If you run through the demo, you will notice the error.  I have commented out what the code should be, if you do this, and try the demo again it works.

http://plnkr.co/edit/ClGwTsNIHsXKS9SfHVs6?p=info

**Comment by Gillardo** [comment]
I am quite happy to create a PR if someone can confirm its a bug

**Comment by icfantv** [comment]
@Gillardo, it sure smells like it. @Foxandxss or @wesleycho, are either of you able to peek at this and confirm?

**Comment by Foxandxss** [comment]
Yes, I saw that in the past when discussing timezone stuff with @wesleycho. We changed that code, so it is completely different in master now.

**Comment by wesleycho** [comment]
Sorry about this - we did indeed see this mistake in the past (I think I was the one who made it). This should already be fixed in `master`, which we're hoping to release in 1.0 by the end of the year. If you want, you could consume current `master`, or overwrite the dateparser service locally if you want a quick fix to this issue in the meantime.

For reference, here is the current version in `master`: https://github.com/angular-ui/bootstrap/blob/09098f891f8c319df47b25cdd06c980e51816ab6/src/dateparser/dateparser.js#L289-L306 - note that it splits out updating the year/month/day and hours/minutes/seconds/milliseconds, so it explicitly avoids that problem.
