### ISSUE TITLE
Documentation error with datepicker examples on bootstrap directives page

### ISSUE THREAD

**Issue by lonerzzz** [angular-ui/bootstrap#5115]
On the angular bootstrap directives page, https://angular-ui.github.io/bootstrap/,  there is an error in the examples for the datepicker that involves the use of <input type="date" class="form-control" uib-datepicker-popup... instead of <input type="text" class="form-control" uib-datepicker-popup... with the result being that a different datepicker implementation is embedded within the bootstrap datepicker input.

The result of this can be seen by hovering over the associated datepicker input on the directives page, https://angular-ui.github.io/bootstrap/,  and the internal date picker control becoming visible and clickable.

**Comment by icfantv** [comment]
This is a really good catch.  Thanks.  Some quick googling [found this](http://stackoverflow.com/questions/11320615/disable-native-datepicker-in-google-chrome) which allows the user to override it on their end.  I will point out that using `<input type="date"/>` is not incorrect and not supporting it may have accessibility issues <-- I'm looking at this now.

@Foxandxss, we should update the datepicker docs to reflect this.  Thanks.

**Comment by icfantv** [comment]
Here's what it looks like in Chrome:

![screen shot 2015-12-22 at 16 22 45](https://cloud.githubusercontent.com/assets/370054/11968375/f6a1b068-a8c8-11e5-897d-c4efe2277cb5.png)

**Comment by deeg** [comment]
Is the fix to just change the demo to use type=text, or do we want a fix where even if type is date, both don't show up? If it is just docs the change should be trivial and I can open a PR
