### ISSUE TITLE
Scrollbar showing inside uib-collapse

### ISSUE THREAD

**Issue by mattwcole** [angular-ui/bootstrap#5116]
Plunk [here](http://plnkr.co/edit/EKjHRred9YksLQSXJKUs?p=preview), just make the preview panel smaller and click the menu button. Issue disappears when using `collapse="vm.isCollapsed"` instead of `uib-collapse="vm.isCollapsed"` on  the collapse div (line 28).

**Comment by wesleycho** [comment]
This is actually currently fixed in `master`, as seen [here](http://plnkr.co/edit/ZLjnDRh45UGTBuYjD4ZK?p=preview).

https://github.com/angular-ui/bootstrap/commit/82cd2d41d1237cc412e10b8351e587aba8fb350b#diff-0234c538cd31e09e1b5b48c2383a8427 is the commit for reference.

**Comment by mlardy** [comment]
It seems that the code of this commit have been reverted and is no longer available in master.
Perhaps someone failed a merge.

I've tried to patch tag 1.2.4 with this commit and it seems to do the job in my case, 
can someone reopen this issue.
