### ISSUE TITLE
Feature Request for  typeahead

### ISSUE THREAD

**Issue by Kuroky360** [angular-ui/bootstrap#5122]
We wanted to use the typeahead with a something(e.g. button)  which can display all dropdown info , when user clicked it.
This was due to the user may forget the name which he gonna search.

**Comment by wesleycho** [comment]
One would be able to accomplish this with a custom template I believe.

**Comment by Kuroky360** [comment]
Awesome, thanks for the quick feedback. okay. 
and which version would be released for this feature?

**Comment by wesleycho** [comment]
There already is support for it released

**Comment by Kuroky360** [comment]
This is related to #4789 I found. that's  a similar feature that we needed.
and when is the new Version( this feature included) is going to be released?

**Comment by frfancha** [comment]
Small tip: in our typeaheads we ignore "special characters" (meaning not letter or digits) in the filtering.
We have "trained" our users to type any special charcater ('-', '+', ...) to force opening the typeahead.

**Comment by Kuroky360** [comment]
@frfancha  When will  the version 1.0.0 be released ?

**Comment by frfancha** [comment]
@Kuroky360 I've no idea, I'm just a simple humble user of ui-bootstrap ;-)

**Comment by icfantv** [comment]
We're aiming for this week.

**Comment by Kuroky360** [comment]
@icfantv  wonderful!
