### ISSUE TITLE
ui having two datepickers click on one open both pickers

### ISSUE THREAD

**Issue by chamincs** [angular-ui/bootstrap#5123]
as the demo , here how to use if we have two date pickers ,clicking on one datepicker cause to open both datepickers

**Comment by wesleycho** [comment]
This is actually fixed in `master` - that will be changed in our next release in the docs.

**Comment by chamincs** [comment]
![image](https://cloud.githubusercontent.com/assets/5775518/11996369/3fe3e7e0-aa87-11e5-8789-ed62c4663d3d.png)

i used to resolve giving two different  name for each datepickers   is-open and ng-click  same name
