### ISSUE TITLE
Size exceeding bootstrap + jquery. Does it make sense to use ui-bootstrap now?

### ISSUE THREAD

**Issue by otabekgb** [angular-ui/bootstrap#5137]
ui-bootstrap has gone far away from initial 5kb gzipped size, even now 20 kb gzipped size is wrong on the top of github page.
ui-bootstrap.tpls.min.js is 130 kb

bootstrap.min.js is  37kb
jquery-2.1.4.min.js  is 83kb
bootstrap + jquery makes 120 kb
No intention to confuse people, but out of curiosity:
What is the point now? Though, I appreciate the modal service.

**Comment by Foxandxss** [comment]
The reasoning behind ui-bootstrap is not to eliminate jquery weight. It is about offering native directives to use bootstrap. If you decide not to use ui-bootstrap, you will need to create (and maintain) a lot of directives that you need to create to wrap those jquery plugins.

Say you want to use bootstrap accordion, you need to create an accordion directive and inside there, instantiate the accordion component. Also if it has some input / output, you need to wrap that as well.

That being said, all the 0.14.x versions of ui-bootstrap is a bit bigger than the other (all the deprecated directives). ui-bootstrap 1.0.0 will have considerable less weight.

**Comment by otabekgb** [comment]
@Foxandxss Why do I need to create directives? I think I just need to add some bootstrap tags in class  attribute. I couldn't find accordion from bootstrap components page. 
bootstap does not need any jquery plugins. Additional components are out of topic.

**Comment by Foxandxss** [comment]
You need to use javascript for any of this ones: http://getbootstrap.com/javascript/

For that you would need a directive to wrap them.

**Comment by otabekgb** [comment]
I think bootstrap is mainly about markup. Personally I didn't know bootstrap can be used with javascript until you pointed. For those corner case javascript(events and programmatic changes), who stops using bootstrap api directly from angular app?

**Comment by Foxandxss** [comment]
No one is stopping anyone. This library is just a port of that javascript part.

You can use bootstrap.js in Angular perfectly, but you will need to do a lot of work to transform that code into something that angular can execute (kind of).

We do the heavy lifting in here and we recreated that bootstrap.js from zero to use native Angular stuff. That way you don't need to do any extra stuff.

That being said, if you don't need any of the javascript parts, this library offers you no benefit (apart from the modal).

For ui-bootstrap 1.0.0, you will be able to cherry pick the features you need, so if you only need the modal, you can use that part only and never load the rest.

**Comment by otabekgb** [comment]
Honestly, all my point to use ui-bootstrap till now was the "small footprint".
I still appreciate ui-bootstrap's team, for their open source contribution.
You should remove misleading message in the title:
Smaller footprint (20kB gzipped)

**Comment by Foxandxss** [comment]
Yeah, don't worry mate. The small footprint will come back in the next version :)

**Comment by Foxandxss** [comment]
Now tpls one is 108kb and gzipped it is 28kb.

**Comment by wesleycho** [comment]
One thing that should be mentioned is that the vanilla Bootstrap JS is probably less performant due to reliance on jQuery for behavior. In addition, this library contains components and functionality that is different in some ways from the vanilla Bootstrap JS.

Anyhow, what is needed really depends on your use cases and what demands there are on them. The 0.14.x versions are bloated due to the deprecated directives, as mentioned prior. Current `master` does not have this issue, and we are getting close to being ready to cut the 1.0 release.

Closing this issue due to lack of anything further actionable for us that we are not already committing to.
