### ISSUE TITLE
uibModal from build master@33b7a37 causes unknown provider $animateCssProvider

### ISSUE THREAD

**Issue by cwkwong** [angular-ui/bootstrap#5139]
Hello, firstly this started with trying to solve tooltip positioning(tooltip appears over item itself, preventing interaction) by following https://github.com/angular-ui/bootstrap/issues/4999

I then encountered the similar issue at the comment: https://github.com/angular-ui/bootstrap/issues/4999#issuecomment-161788279

- we are using angular `1.3.16`
- I believe for our current version, we don't have `$animateCss`. Only angular `1.4.x`
- For modals, we don't use `ngAnimate` currently.
- Error in console is: `Uncaught Error: [$injector:unpr] Unknown provider: $animateCssProvider <- $animateCss <- $uibModalStack <- $uibModal <- LoginService`

Any alternatives towards not using `ngAnimate` and not having `$animateCss`?

**Comment by wesleycho** [comment]
Can you post a reproduction? It is working just fine in 1.3 as far as I can tell, as seen [here](http://plnkr.co/edit/lVqeLDxYdrhOBYLpvdla?p=preview).

**Comment by wesleycho** [comment]
Ah wait, I see - in `master`, we are only supporting 1.4+.

**Comment by icfantv** [comment]
@foxandxss, on my phone at the moment so I can't check.  We should put this in the docs in some prominent location, if we're not already, or we're going to get issues filed.

**Comment by Foxandxss** [comment]
The homepage, on the description, it says "This library support angular 1.4+" or something like that.

If you have a better idea, file a PR. Perhaps on the readme as well.

**Comment by icfantv** [comment]
Nope, that works for me.

**Comment by frfancha** [comment]
For info: Same problem with angular 1.4.3, but runs fine with angular 1.4.8

**Comment by Foxandxss** [comment]
Thanks for the info, I will check what is the real minimum and update accordingly.

**Comment by wesleycho** [comment]
I think it might be 1.4.5 at this point

**Comment by icfantv** [comment]
@wesleycho, I think you're right. I think that's when angular-animate changed.

**Comment by Foxandxss** [comment]
Out of curiosity, works for me even in 1.4.1.

**Comment by wesleycho** [comment]
The problem only manifests if one is not using ngAnimate I believe - I injected $animateCss directly since the older versions of 1.4 are a bit busted and Matias added a generic $animateCss service around 1.4.4 or 1.4.5 (I forget the version number). I think 1.4.5+ is where the ngAnimate bugs are fleshed out though.

**Comment by Foxandxss** [comment]
Will recheck then.
