### ISSUE TITLE
Binding ngModel to an object not to text when using typeahead

### ISSUE THREAD

**Issue by Alcruz** [angular-ui/bootstrap#5140]
I have this in my html:

```html
<div class="col-lg-5">
	<div class="input-group">
		<input type="text" 
			   ng-model="pharmacyVm.selectedMedicine" 
			   typeahead-editable=false
			   placeholder="Escribe el nombre de algún medicamento" 
			   uib-typeahead="medicine for medicine in pharmacyVm.getMedicines($viewValue)"
			   class="form-control">
			   
		<span class="input-group-btn">
			<button type="button" ng-click="pharmacyVm.addMedicine()" class="btn btn-primary"><i class="fa fa-plus"></i></button>
		</span>
</div>
```

Then i want to add that value in a table
```javascript
		function addMedicine() {
			vm.selectedMedicine.price = 0;
			vm.tableParams.data.unshift({
				id: vm.selectedMedicine.id,
				name: vm.selectedMedicine.name,
				description: vm.selectedMedicine.description,
				price: 0
			});
		}
```

**Comment by wesleycho** [comment]
The default behavior is to allow binding to objects, as can be seen [here](http://plnkr.co/edit/nE8xQL4f9XmqqmZvFgAS?p=preview). Please post a reproduction of the issue.

**Comment by Alcruz** [comment]
Here a plunkr which depicts the issue:
http://plnkr.co/edit/ZX33SHDTHVViJqV21m8S?p=preview

 I'm trying to bind the input to an object In the uib-typeahead attribute, son when I'm typing, the typeahead shows '' [Object object]".

I'm doing that, because I want to select the whole reference of the returned object, not only the name for example.
```html
    <input type="text" ng-model="customPopupSelected" placeholder="Custom popup template" uib-typeahead="state for state in statesWithFlags | filter:{name:$viewValue}" typeahead-popup-template-url="customPopupTemplate.html" class="form-control">
```

**Comment by wesleycho** [comment]
There is the `select as label for value in sourceArray` syntax for this exact purpose - see [here](http://plnkr.co/edit/rBDoXTXCymiFn3iyXLuD?p=preview).

**Comment by marcusjwhelan** [comment]
How would you save in the model the exact word selected and not the whole object. I have this code exactly the same and it does not save anything to the model I just get undefined for the value.

**Comment by fernandodof** [comment]
@wesleycho About In the example you showed, how could I show the flag name on the input but bind the flag image (only the flag image) to the model ?

If I change to:
```html
uib-typeahead="state.flag as state.name for state in statesWithFlags | filter:{name:$viewValue}"
```
attention to **state.flag** 
the image is bound but when the user chooses the input also shows the flag image and not the name as I want.

Thanks.

**Comment by fernandodof** [comment]
@wesleycho I got it to work by using two variables a dummy one just to bind the value a another one that is the one that will actually be send to the back end, and this one I change it with a function on **typeahead-on-select.** I not sure if there a better way but that's the workaround I found.
