### ISSUE TITLE
Pagination generated to more than it should be.

### ISSUE THREAD

**Issue by herpiko** [angular-ui/bootstrap#5142]
Current configuration :

- Total item : 443
- Current page : 1
- Per page : 50

It should generate 8 page, but the result is more than 45 pages.

http://plnkr.co/edit/T8E3nqYBoNdCcpwYM8ky?p=preview

**Comment by pkozlowski-opensource** [comment]
You had a typo in the directive usage: `item-per-page` => `items-per-page`: http://plnkr.co/edit/DSf9VUlBrX9ohGD2oR63?p=preview
