### ISSUE TITLE
Clicking on a typeahead option that is inside of a dropdown closes the dropdown.

### ISSUE THREAD

**Issue by spiffy2man** [angular-ui/bootstrap#5145]
If I have a typeahead inside of a dropdown (using a dropdown because it closes when a user clicks outside of it and we don't want the arrow to show up), and a user clicks on a typeahead option using a mouse, the dropdown closes. Using tab or the enter key to select an option works fine. Only using the mouse causes an issue.

I am not aware of any setup options that would keep the dropdown from closing. Currently, as a workaround, I am re-opening the dropdown when a user clicks on the typeahead option, but it causes the dropdown to close and then re-open, which is not a desired behavior.

**Comment by icfantv** [comment]
@spiffy2man, sorry it took so long to get back to you on this.  Take a look at the `autoClose` attribute option for `uib-dropdown`.  I was able to get your desired behavior by setting to `disabled`.  [Here's an example plunker](http://plnkr.co/edit/GZqmYoA1vCWIovHJGVen)
