### ISSUE TITLE
Is there a good documentation on how to customize the carousel? 

### ISSUE THREAD

**Issue by gfouvry** [angular-ui/bootstrap#5153]
Hi, 
I had the same issue as deftleftPeters with the new carousel, now I have to do the carousel all over again it seems. Is there something usable on how to parameter the div properly with the same flexibility as the old bootstrap carousel.
Thanks in advance,
Geoffrey.

**Comment by wesleycho** [comment]
Can you explain what you wish to do in more detail? I'm not sure what you are asking for.

**Comment by icfantv** [comment]
@gfouvry, I'm going to close this due to a lack of activity or a response from you.  If you wish to elaborate further, we can discuss reopening.  Thanks.
