### ISSUE TITLE
tooltip is 'null' by the time $timeout fires

### ISSUE THREAD

**Issue by cthielen** [angular-ui/bootstrap#5155]
We are using angular-bootstrap in production and log our JS exceptions.

We a null pointer exception on the following .css() line fairly regularly in this piece of code:

            var positionTooltip = function() {
              // check if tooltip exists and is not empty
              if (!tooltip || !tooltip.html()) { return; }

              if (!positionTimeout) {
                positionTimeout = $timeout(function() {
                  // Reset the positioning.
                  tooltip.css({ top: 0, left: 0 });

My guess is by the time $timeout fires, 'tooltip' is null. If that sounds right to you guys, I'd be happy to submit a PR.

**Comment by icfantv** [comment]
@cthielen, do you see this in a minimal plunker?  I'm looking at the code and we set `tooltip = null` after we call `cancelShow(); cancelHide(); unregisterObservers();` - the first of which is the function that cancels the `positionTimeout`.

**Comment by RobJacobs** [comment]
This issue has been addressed in master under this [commit](https://github.com/angular-ui/bootstrap/commit/429ddc12b6b5c2d9a4637cd6bd94e3927247d00f)

**Comment by icfantv** [comment]
Cool, thanks @RobJacobs.  That would be why I wasn't seeing how that could happen in our code.  Closing.
