### ISSUE TITLE
Modal does not slide if size: lg or sm is applied

### ISSUE THREAD

**Issue by turneye** [angular-ui/bootstrap#5156]
If you use the option size: 'lg' or size: 'sm' the modal does not perform the sliding down animation.  

Don't think it's anything unique I'm doing as you can see this behaviour on the samples page -- http://angular-ui.github.io/bootstrap/#/modal

The slide up animation does occur when you close the small/large modals.  

Not sure if this is a bug in these controls that can be fixed or something to do with what the ng-class does when being applied...

**Comment by icfantv** [comment]
This is fixed in `master`.  Thanks.
