### ISSUE TITLE
Create build creates empty minified JavaScript file

### ISSUE THREAD

**Issue by belchugov** [angular-ui/bootstrap#5158]
1. Open https://angular-ui.github.io/bootstrap/
2. Press create 'Create build' button
3. Select 'Carousel' module
4. Download the module
5. Extract the zip
6. Open `ui-bootstrap-custom-0.14.3.min.js`
7. Notice the file is **empy**

Expected: should contain the minified version of `ui-bootstrap-custom-0.14.3.js`

![image](https://cloud.githubusercontent.com/assets/886326/12168041/78700240-b538-11e5-8bdd-32bf740b614a.png)

**Comment by wesleycho** [comment]
I'm not able to reproduce this - is this possibly related to #4977?

**Comment by belchugov** [comment]
I'm using Chrome Version 47.0.2526.106 m on Windows 10

**Comment by wesleycho** [comment]
Do any error messages happen in the console when downloading the build?

**Comment by belchugov** [comment]
No error, nothing in the console.

**Comment by wesleycho** [comment]
Not able to reproduce this, on exactly the same version of Chrome and on Windows 10.

**Comment by pkozlowski-opensource** [comment]
@belchugov could you try it on the incognito mode / with all the extensions disabled? Maybe one of your installed Chrome extensions is interfering here?

**Comment by belchugov** [comment]
Strange, not it works, it might be a one time thing, thanks for the help.
