### ISSUE TITLE
bug(tooltip): $apply already in progress

### ISSUE THREAD

**Issue by blabno** [angular-ui/bootstrap#516]
Tooltip throws exceptions if bound to button and ngClick takes long.
HTML:
```html
<button ng-click="exitEdit()" tooltip="Exit edit mode">exit</button>
```
JavaScript:
```javascript
    $scope.exitEdit = function ()
    {
        if (this.isModified()) {
            if (!window.confirm("There are changes. Do you want to quit without saving?")) {
                return false;
            }
            ...
    }
```

The window.confirm pauses execution, which happens in $apply phase so the tooltip hits the same phase as it's triggered by jQuery (outside of Angular):

> Error: $apply already in progress
> beginPhase@http://localhost:8000/libs/angular.js:8288
> Scope.$apply@http://localhost:8000/libs/angular.js:8090
> hideTooltipBind@http://localhost:8000/libs/angular-ui-bootstrap.js:3451 
> jQuery.event.special[orig].handle@http://localhost:8000/libs/jquery.js:3431 
> jQuery.event.dispatch@http://localhost:8000/libs/jquery.js:3074 
> jQuery.event.add/elemData.handle@http://localhost:8000/libs/jquery.js:2750
> (?)() angular.js (line 5704)
> anonymous() angular.js (line 4800)
> $apply(expr=undefined) angular.js (line 8093)
> hideTooltipBind () angula...trap.js (line 3451)
> handle(event=Object { originalEvent=Event mouseout, type="mouseout", timeStamp=0, more...}) jquery.js (line 3431)
dispatch(event=Object { originalEvent=Event mouseout, type="mouseout", timeStamp=0, more...}) jquery.js (line 3074)
handle(e=mouseout clientX=1132, clientY=104) jquery.js (line 2750)

**Comment by TroelsL** [comment]
I ran into this issue on IE11 (11.0.9600.16428), but was able to monkey patch my way around it with:

    function hideTooltipBind() {
      //PATCH for MNSTD-31925
      if(scope.$$phase === "$digest" || scope.$$phase === "$apply") {
        return;
      }
      scope.$apply(function () {
        hide();
      });
    }

**Comment by gufigueiredo** [comment]
Another scenario:

If i use tooltip with "tooltip-trigger=focus" and ui-datepicker, same error occurs:

```
<div class="form-group">
                        <label for="DateField" class="required">Date Field</label>
                            <div class="input-group date">
                              <input name="DateField" type="text" class="form-control" 
                                     tooltip="Choose a date"
                                     tooltip-trigger="focus"
                                     datepicker-popup="dd/MM/yyyy" 
                                     ng-model="vm.DateField" 
                                     is-open="vm.opened" 
                                     show-button-bar="false" />
                              <span class="input-group-btn">
                                <button type="button" class="btn btn-default" ng-click="vm.open($event)"><i class="glyphicon glyphicon-calendar"></i></button>
                              </span>
                            </div>
                        </div>

```

**Comment by RobJacobs** [comment]
@gufigueiredo That is not a valid use case, see the Wiki faq section [here](https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input-elements-stop-working-when-i-place-a-tooltip--popover-on-it) for an explanation.

**Comment by chrisirhc** [comment]
@gufigueiredo , that might be a possible use case to support after we release 0.13 . I've opened another issue for that.
