### ISSUE TITLE
Errors in console when interacting with demo for typeahead

### ISSUE THREAD

**Issue by deeg** [angular-ui/bootstrap#5167]
With the latest master code, the last demo on the typeahead causes errors in the console:

```
ui-bootstrap.js:6267 Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined
(anonymous function)	@	ui-bootstrap.js:6267
eventHandler
```

https://plnkr.co/edit/myFVFqnO2fHNo0aEednm?p=preview

Type some text in the last example, and then hit the arrow down key to scroll through results. This causes the error.

Might just be an issue with the demo and not the code itself, didn't have the time to look into it yet.

**Comment by wesleycho** [comment]
Thanks for this - I see what is happening, the children need to select specifically for the `li` elements. I'll have a fix for this shortly.
