### ISSUE TITLE
calendar navigation button disabled beyond valid date

### ISSUE THREAD

**Issue by technimadhu** [angular-ui/bootstrap#5169]
is there a way, to disable browsing next month when the max date which can be chosen is Today?
similarly disallow navigating backwards beyond min-date?

**Comment by icfantv** [comment]
@technimadhu, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

**Comment by icfantv** [comment]
You can accomplish this by overriding the datepicker template for month (month.html) and adding an `ng-disabled` attribute with the appropriate condition.
