### ISSUE TITLE
automatically close one datepicker popup when opening another datepicker instance

### ISSUE THREAD

**Issue by JackGommeren** [angular-ui/bootstrap#5172]
When i have two or more directives of a datepicker on a page and when i have openend one, I want it to automatically close the other. This is not the case in the current version as it leaves the other one open as it opens yet another datepicker popup.

Perhaps it would be best to have this option as a global (and local) setting on each directive for the instances that you do want to have multiple opened datepickers on one page.

The screenshot below illustrates the issue, I want only one instance of a datepicker to be openend at a time, not multiple:
![51420426-b555-11e5-88b9-2a63624cfc32](https://cloud.githubusercontent.com/assets/14069393/12200489/5b58148a-b61f-11e5-9316-b9a5b05845a6.JPG)

I could attempt to close the datepicker by using the ng-click, but i feel like tis functionality should be provided from within the datepicker directive itself.

**Comment by icfantv** [comment]
@JackGommeren, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

You can accomplish your request on your own by simply watching the datepicker popup's `is-open` property.
