### ISSUE TITLE
Update prefix migration guide

### ISSUE THREAD

**Issue by deeg** [angular-ui/bootstrap#5177]
[The migration guide](https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes) states

> Dropdown
Change: The class dropdown-menu for uib-dropdown-menu.

This seemed to work for 0.14.3, but not for version 1.0.0. Changing all classes back to dropdown-menu seems to be working.

Also there seem to be some missing from the guide:
* typeaheadHighlight -> uibTypeaheadHighlight

**Comment by wesleycho** [comment]
typeaheadHighlight is a directive, so the prefix rule applies.

As for the dropdown menu, not sure why that was missed in the changelog

**Comment by deeg** [comment]
@wesleycho, understood that the prefix rule applies, but for all directives they were listed on the migration guide, this one was not. I would have put out a PR, but the wiki is not backed by files in the repo is it?

**Comment by wesleycho** [comment]
Ah, so it needs a wiki update - understood, we'll fix that quick.

**Comment by wesleycho** [comment]
Updated the wiki - thanks for the catches!

**Comment by deeg** [comment]
@wesleycho, that page on the wiki still states:

> Dropdown
Change: The class dropdown-menu for uib-dropdown-menu.

That does not seem to work with 1.0.0, like it did with 0.14.3. After changing the classes back to dropdown-menu it worked. Should that not be updated also?

**Comment by wesleycho** [comment]
Just updated it - does the wording look right now?

**Comment by deeg** [comment]
Looks good, thanks!
