### ISSUE TITLE
uib-tab

### ISSUE THREAD

**Issue by Rouche** [angular-ui/bootstrap#5181]
Hi,

Any reason why tabs are now `<div>` instead of `<a>` ?

We have to reskin everything but it seems to create a strange behavior that im unable to reproduce in plunkr.
Tabs appear only after a user interaction, like its missing an apply() or something.

Ill try to plnk it the best i can.

**Comment by deeg** [comment]
Are you missing some text in the message?

____ instead of _____, what goes in the blanks?

**Comment by Rouche** [comment]
its ok now :)

**Comment by icfantv** [comment]
Yes.  We ran into issues with Firefox (and maybe Webkit browsers) reloading the page when the tab was clicked.  And this was happening before angular was processing the `href` attribute so this was the "fix."  We don't love it and it has accessibility ramifications.

I'll check the docs and breaking changes section to make sure this gets documented if it's not.

**Comment by wesleycho** [comment]
@Rouche the reason is because of some use cases where routing issues would happen if you try to use certain elements within the anchor tags, such as buttons. Nesting a button inside an anchor tag actually is a case of bad HTML, but UI Bootstrap shouldn't be interfering with use cases such as this, which is why the breaking change is listed.

The demo documentation has the necessary CSS necessary in order to fix this on the user side.

**Comment by icfantv** [comment]
Cool, thanks @wesleycho.

**Comment by Rouche** [comment]
OK il follow this to my colleague.

Thanks.
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


[image: ResoluTech]
*Jean-Francois Larouche*
Architecture de Solutions TI
[image: Cell] 514-965-9224 | [image: Email] contact@resolutech.com[image:
Web] http://www.resolutech.com
<http://ca.linkedin.com/pub/jean-francois-larouche/1/b84/530>

**Comment by icfantv** [comment]
@Rouche, I've edited your comment to remove all your personal information.  In general, it's not a good idea to reply to GitHub notification emails from your work email account because corporations like to add on stuff that's outside of your control.

**Comment by Rouche** [comment]
Thanks, my bad.
