### ISSUE TITLE
timepicker - Value can be changed via the text input fields even if ng-disabled evaluates to true

### ISSUE THREAD

**Issue by bisswanger** [angular-ui/bootstrap#5182]
Thanks for adding the ng-disabled feature for the timepicker.
It works fine in disabling value changes via the up and down buttons.

Though even when setting it to true, the text input fields are not disabled and the value still can be changed (Tested in Firefox & IE)

**Comment by deeg** [comment]
It would help to be able to resolve the issue if you could post a plunker demonstrating the issue.

**Comment by deeg** [comment]
[Plunker for good measure.](http://plnkr.co/edit/zFpfOJlqd2tU2ncbKIsN?p=preview)

**Comment by deeg** [comment]
Working on fix, should have PR up shortly.
