### ISSUE TITLE
After 1.0, Bootstrap menus don't really work

### ISSUE THREAD

**Issue by nickdnk** [angular-ui/bootstrap#5186]
Hello

I just tried upgrading to 1.0.0, but now my Bootstrap-built menus don't work properly. Please see attached screenshot. This issue goes away if I go back to 0.14.3
![screen shot 2016-01-09 at 03 03 40](https://cloud.githubusercontent.com/assets/8411314/12213707/a3729ca0-b67d-11e5-9b93-aba20290fd34.png)
The menu should be collapsed and selectable by clicking the (in this case) "Management" button.

Angular version is 1.4.8. Depicted menu built like such:
`<div class="collapse navbar-collapse" data-ng-class="{'in':!navCollapsed}">
<li uib-dropdown>
                            <a href="#" uib-dropdown-toggle>Management <span class="caret"></span></a>
                            <ul class="uib-dropdown-menu" role="menu">
                                    <li class="dropdown-header">PRICES & PRODUCTS</li>
                                    <li><a href="">Products</a></li>
                                    <li><a href="">Prices &amp; Categories</a</li>
                                    <li><a href="">Menu Cards</a></li>
                            </ul>
                        </li>
</div>`
No errors logged to console.

**Comment by nickdnk** [comment]
Seems I was using class="uib-dropdown-menu" where I should have used just uib-dropdown-menu. Now it works.

**Comment by readme42** [comment]
Sorry for using a closed issue, but i can confirm:

`class="uib-dropdown-menu"`is working in 0.14.3 but not in 1.1.0

Could you add this to the Breaking Changes section in the Changelog? Using it as attribute works fine.

**Comment by icfantv** [comment]
Sorry about this.  We've had issues with the CHANGELOG generator in the past missing stuff, but I just noticed #4753 was missing the `Breaking Change` tag even though the PR #4975 had it.  I will update the changelog to show this.

**Comment by readme42** [comment]
Never mind, thanks for the update!
