### ISSUE TITLE
[Date picker] Calendar not rendering when initDate is undefined

### ISSUE THREAD

**Issue by bogdanalexe90** [angular-ui/bootstrap#5190]
Calendar is not rendering when `initDate` and model are `undefined`.

http://plnkr.co/edit/Dy9UvDb5z8vRt8phYypD?p=preview

**Comment by wesleycho** [comment]
Looks like a bug (fixed the Plunker [here](http://plnkr.co/edit/1BsP29JRcaR15pKllUQd?p=preview)), but should be simple to fix by setting an initial model value of the current date.

**Comment by wesleycho** [comment]
Linking this investigation with the inline datepicker [here](http://plnkr.co/edit/fSRjIy0cVDorWlT6Wwdp?p=preview) to note that this is only an issue with the popup version, so something in between is being set incorrectly.
