### ISSUE TITLE
[Date picker] Calendar is not rendering when model is a timestamp

### ISSUE THREAD

**Issue by bogdanalexe90** [angular-ui/bootstrap#5191]
Calendar is not rendering when model is a timestamp. This issue happens only with angular 1.5 and only when the popup is opened first time.

http://plnkr.co/edit/i2y5RqCzvyro8O7NVryg?p=preview

**Comment by wesleycho** [comment]
There was a breaking change made a couple of releases ago where we decided we only want to support usage of a Date instance due to various issues & complexity supporting multiple formats.

This Plunker works fine if it is a date object, as seen [here](http://plnkr.co/edit/Rk3CLqjoCVelb2vr6mYw?p=preview).

**Comment by bogdanalexe90** [comment]
Strange... It was working fine before `1.0.0`. if it's not supported anymore you can update the error message from:

```js
this.render = function() {
    if (ngModelCtrl.$viewValue) {
      var date = new Date(ngModelCtrl.$viewValue),
          isValid = !isNaN(date);

      if (isValid) {
        this.activeDate = dateParser.fromTimezone(date, ngModelOptions.timezone);
      } else if (!$datepickerSuppressError) {
        $log.error('Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.');
      }
    }
    this.refreshView();
  };
```

**Comment by wesleycho** [comment]
There were a lot of changes made in the datepicker from 0.14.3 to 1.0.0, namely to support user-specified timezones of relevance here.

I'll update the error string, sorry about the misreported message there.

**Comment by bogdanalexe90** [comment]
The error highlighted is in `UibDatepickerController`.

But... The example in my plnkr was working fine with angular `1.4.18`. 
The problem appears only with `1.5.0`.

**Comment by wesleycho** [comment]
Ah, I thought it was in the dateparser - I'll open a PR for this shortly.

**Comment by bogdanalexe90** [comment]
Still. Have a look on the last plnkr. Timestaps are working wit angular 1.4.8

**Comment by wesleycho** [comment]
We declared in release 0.13.2 that we are only supporting date objects, as seen [here](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#bug-fixes-7). Our documentation also declares only support for date objects - this is not going to change.

**Comment by bogdanalexe90** [comment]
Not pushing for a change. It seems a little bit weird that the error with angular 1.5 is more an uncatched error than an error throwed by the library.
