### ISSUE TITLE
[Collapse] First animation is still ran

### ISSUE THREAD

**Issue by bogdanalexe90** [angular-ui/bootstrap#5192]
Collapse has a strange flickering when is opened by default at first rendering and some delayed content is loaded. I took a look in the collapse directive and the `expand()` logic is still ran.

```js
// This should add `collapse in` class
if (!scope.$eval(attrs.uibCollapse)) {
          element.addClass('in')
            .addClass('collapse')
            .css({height: 'auto'});
}

function expand() {
    ...
          if ($animateCss) {
            $animateCss(element, {
              addClass: 'in',
              easing: 'ease',

              // if the async content is loaded after this
              // it will cause an animation towards the new scrollHeight

              to: { height: element[0].scrollHeight + 'px' }
            }).start()['finally'](expandDone);
          } else {
            ...
          }
        }

// Still the watcher will trigger expand logic
scope.$watch(attrs.uibCollapse, function(shouldCollapse) {
          if (shouldCollapse) {
            collapse();
          } else {
            expand();
          }
        });
```

Because we need to skip `expand()` only for the first rendering we can add a simple check inside the watcher:
```js
scope.$watch(attrs.uibCollapse, function(shouldCollapse) {
          if (shouldCollapse) {
            collapse();
          } else {
            if(arguments[0] !== arguments[1]){
                expand();
            }
          }
        });
```

**Comment by icfantv** [comment]
@bogdanalexe90, per [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug), can you please post a plunker that reproduces the issues?  Doing this for bugs usually greatly reduces the time it takes for us to diagnose and fix issues.  Thanks.

**Comment by bogdanalexe90** [comment]
Please have a look on https://github.com/angular-ui/bootstrap/issues/4414 it's the same issue. Also you can have a look on my pull request https://github.com/angular-ui/bootstrap/pull/5199

**Comment by icfantv** [comment]
Awesome, thanks.
