### ISSUE TITLE
Collapse: Support for pre/post collapse/expand callbacks

### ISSUE THREAD

**Issue by nonplus** [angular-ui/bootstrap#5194]
In my application, before expanding a collapsed section, I need to populate the contents.  Similarly, after collapsing an expanded section, I'd like to do some cleanup.

It would be great if the `uib-collapse` supported additional attributes that would be evaluated before and after the collapse animation, e.g. `expanding`, `expanded`, `collapsing`, `collapsed`.  If the "before" attribute (`collapsing`/`expanding`) returns a promise, the directive should wait for it to resolve before beginning the collapse/expand animation.

Specifically, I'd like to be able to do something like this:
```html
<div uib-collapse="isOpen" expanding="setupContent()" collapsed="cleanupContent()">
    <!-- complex & expensive content goes here -->
</div>
```

FWIW, I have an implementation and can create a PR if there is general interest in this...

**Comment by wesleycho** [comment]
I think this is a simple enough feature & should be simple enough to implement - I'm open to this.

**Comment by deeg** [comment]
@nonplus, do you have a PR you are going to put up, or should someone else look into implementing this?

**Comment by nonplus** [comment]
I need to write the unit test before providing a PR.  Hopefully I can do that tonight.
