### ISSUE TITLE
Encapsulate build files in IIFE

### ISSUE THREAD

**Issue by bogdanalexe90** [angular-ui/bootstrap#5196]
When using `ui-bootstrap-tpls.js` with `gulp-useref` into a build process resulting code is not working. This is due to a missing `;` at the end of the file. Adding the `;` or encapsulating into an IIFE solves the issue.

I suggest better to encapsulate all the lib into an IIFE.

**Comment by bogdanalexe90** [comment]
The actual error is:
`Uncaught TypeError: angular.module(...).run(...) is not a function`

Because in my file the next thing is an IIFE, so concatenated code looks like:

```js
angulat.module.run(...)(function(){...}());
```
So the js engine tries to evaluate it as a function.

**Comment by wesleycho** [comment]
Not sure why it is like that - this should be fixed on next release after #5197 gets in.

There is no benefit of wrapping everything in an IIFE here - all of the innards are encapsulated in angular modules, and there is no global being set by UI Bootstrap.

**Comment by philBrown** [comment]
This should **never** have made it in to any release, let alone 1.0

**Comment by wesleycho** [comment]
@philBrown please read the [Code of Conduct](https://github.com/angular-ui/bootstrap/blob/master/CODE_OF_CONDUCT.md) - if you do not change the tone/attitude in your comments (as this is not the first issue where this is exhibited), you will be blocked from commenting, and the Angular team will be notified of this violation.

**Comment by philBrown** [comment]
@wesleycho my apologies, it's been a long day (previous comment removed).

I am able to work around this by using the pre-minified version of `ui-bootstrap-tpls.min.js` instead of the main file for now.

Do you have a rough timeframe on a 1.0.1 release?

**Comment by wesleycho** [comment]
@philBrown not a problem, we all have them - hope you get some rest!

We're likely to release a 1.0.1 on Monday evening PST or Tuesday morning PST if I have agreement from the others.

**Comment by Anjmao** [comment]
I general it is best practice to wrap library to IIFE and also use strict mode
```javascrtip
(function() {
    'use strict';
    //your library code here
})();
```
I don't get it why angular bootstrap don't do it?
