### ISSUE TITLE
Missing Semicolon in ui-bootstrap.js

### ISSUE THREAD

**Issue by kirkone** [angular-ui/bootstrap#5204]
Hello,

I installed this package with bower and noticed the following:
in the last line of ui-bootstrap.js and ui-bootstrap-tpls.js the last semicolon is missing.

I use bundling to combine all js files to one file an so I get a syntax error in the next line of code if there is anything after this line of code.

in both .min.js files the semicolon is present.

Greetings,
Kirsten

**Comment by Foxandxss** [comment]
That was fixed at 9d0269e

**Comment by kirkone** [comment]
thank you, I did not see this is allready fixed.
