### ISSUE TITLE
Some shaking in bootstrap modal when open with animation

### ISSUE THREAD

**Issue by Jeevanandanj** [angular-ui/bootstrap#5207]
http://plnkr.co/edit/7c2YCo28JAiR3U5QKGWE?p=preview

Please check the plnkr. When open the modal with animation and backdrop false, there is some shaking in the page.

**Comment by icfantv** [comment]
@Jeevanandanj, this is a duplicate of #5183.  Please extend us the courtesy of searching open and closed issues before entering a new one.  Thanks.
