### ISSUE TITLE
add ability in typeahead to handle when the enter key is entered and the popup is not open

### ISSUE THREAD

**Issue by tzejohn** [angular-ui/bootstrap#5213]
There are cases where the typeahead field might have the focus, but the typeahead popup is not open because there was no click event or change in the value of the model. I would like to be able to handle when the user hits the enter key.  Currently, when the enter key is hit and the matches length is 0, the event handler just returns.  If I add another key event handler, like with ng-keyup, on the text field, then they both get called, and I cannot tell if the typeahead handled it or not.  So essentially, I would like the key event to be propagated to another handler if the typeahead is not going to do anything and just return.

**Comment by deeg** [comment]
You could do something like with the first typeahead example on [this plunker|http://plnkr.co/edit/6yn9LAqk1oyIe9LSiIAX?p=preview]

If you put the keydown event on a parent element of the input, you can then stop the propagation if a selection happens only catching the keydown event if there is no selection.

**Comment by tzejohn** [comment]
Thanks @deeg. That worked for me.  I stop the propagation in my callback handler and that way I know that the event was handled.  Thanks for pointing the example out.
