### ISSUE TITLE
Calendar is displaying improperly model value that is date string and in custom format

### ISSUE THREAD

**Issue by ninjaprox** [angular-ui/bootstrap#5217]
Calendar is displaying improperly model value that is date string and in format `MMM-yy`.
The month is correct but the year is not. In day mode, year displays as day. In month mode, year displays in `2001`.
http://plnkr.co/edit/Bdh6aVdgMjdqDAn42fde?p=preview

**Comment by Foxandxss** [comment]
The ng-model needs to be a Date object not a string.

http://plnkr.co/edit/fbIWtvTHlTrXel4HCPlH?p=preview

**Comment by icfantv** [comment]
@ninjaprox, please extend us the courtesy of reading the documentation first and then searching both open and closed issues before opening a new issue.  Managing a large/popular OSS repository requires a lot of work by many people and each issue takes time to research.  Thanks.

**Comment by ninjaprox** [comment]
Thanks, noted that. Sorry for my hastiness.
