### ISSUE TITLE
dateMin does not work on DatePicker if the value is not a Date object and is a string

### ISSUE THREAD

**Issue by gmodrogan** [angular-ui/bootstrap#5223]
Hello,

Please have a look at the following plnkr: http://plnkr.co/edit/weqkakdClFB3ZBI7SKtr?p=preview

From the controller I set 
$scope.minDate = new Date("2016-01-15T17:17:07.670Z");
$scope.minDateString = "2016-01-15T17:17:07.670Z"; -> this is how the json is parsed from any API

First datePicker has dateMin as value for min-date and second datePicker has minDateString.

[BUG]
- second date picker doesn't have disabled the dates before 15th Jan 2016.

Any idea? From my API I get the data as in the second string. I don't want to loop over my API entities and create Date objects after the call.....

Thanks,
George

**Comment by icfantv** [comment]
@gmodrogan, please extend us the courtesy of reading the project documentation and both open and closed issues prior to entering anything in the issues section.  This change was made quite a while ago and has been dealt with many times via the issues forum.  Thanks.

The datepicker requires a `Date` object only and does not support strings.

**Comment by gmodrogan** [comment]
ng-model $  - The date object. Needs to be a Javascript Date object.

**Comment by gmodrogan** [comment]
Please be so kind and modify that plnkr to use version 0.14.3
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.14.3/ui-bootstrap-tpls.min.js"></script>

You will see that is working fine. I consider this to be a regression. Why would you restrict that?

**Comment by gmodrogan** [comment]
Now you constrain me to loop over the json received from API call and make date objects for the fields that I know that represent dates? !ok

**Comment by icfantv** [comment]
Ok, let me check.

**Comment by gmodrogan** [comment]
any news on this one? please reopen the ticket if this is a regression. Cheers

**Comment by icfantv** [comment]
There's more issues at play here.  Somehow we are accepting strings again as a value for `ng-model` which is a much larger issue.
