### ISSUE TITLE
How to resize AngularUI datetime-picker bootstrap component?

### ISSUE THREAD

**Issue by hsbilgen** [angular-ui/bootstrap#5231]
"Bootstrap components written in pure AngularJS by the AngularUI Team"
"https://angular-ui.github.io/bootstrap/#/timepicker"

I would like to resize my datetime-picker which is smaller size. I don't know how to resize existing datetime-picker. Any ideas? or any help on this?

![image](https://cloud.githubusercontent.com/assets/10603702/12301769/7300cae6-ba2a-11e5-812c-04020f9ae133.png)

Here is my plunk : http://plnkr.co/edit/6hAptiAZQz5tVsM93cLp?p=preview 

thanks a lot

**Comment by icfantv** [comment]
@hsbilgen, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.
