### ISSUE TITLE
Datepicker has a rather large delay on click (even on example page)

### ISSUE THREAD

**Issue by stephengardner** [angular-ui/bootstrap#5232]
I couldn't find this being brought up before and it's hugely significant.  I just scaffolded a brand new app using Yeoman angular and placed a `<uib-datepicker>` directive on the page and clicking a date causes about a half second (or more) delay.  Even the example page has a long delay when clicking a date.  Has this been discussed?

**Comment by icfantv** [comment]
@stephengardner, if you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

**Comment by icfantv** [comment]
As this is not an issue on our demo page, I'm going to close this until we hear back from you.  Thanks.

**Comment by stephengardner** [comment]
That's wild.  I checked from Chrome, Firefox, and IE and they're both showing a large delay.  I checked from my phone (Galaxy s6 edge) and it's showing the same delay.  When I click a date, the time between when it I clicked it and when it becomes highlighted is about half a second or more.  I'll see if I can set a plunkr up, but if you're not seeing this and I'm seeing it on two different devices I'm stumped too.

**Comment by icfantv** [comment]
@stephengardner, are you seeing this on our demo page from all those browsers/devices or are you testing your web application from those devices?

**Comment by stephengardner** [comment]
On your demo page from all those browsers/devices.  I just did a reboot, same issue.

**Comment by icfantv** [comment]
I don't know what to say - without a reproduction there's not really anything we can do.

**Comment by richirm** [comment]
I have the same problem, I tested with version 1.3.1 and still gives the same problem
