### ISSUE TITLE
Please add a directive for Scrollspy like in bootstrap

### ISSUE THREAD

**Issue by anubhav7495** [angular-ui/bootstrap#5234]
Normally bootstrap has this Scrollspy feature which keeps track of the current page hash on the navbar. A scrollspy directive would be a welcome addition.

url: http://getbootstrap.com/javascript/#scrollspy

**Comment by anubhav7495** [comment]
Closing issue becuase i solved my problem using ui-router.

**Comment by andyperlitch** [comment]
@anubhav7495 may I ask how you solved this with ui-router?

**Comment by anubhav7495** [comment]
```
<a ui-sref-active="active" ui-sref="/home" ng-click="null"></a>
```

when route would match `/home`, `active` class would be applied to the `<a>`.

Hope this helps.
