### ISSUE TITLE
Datepicker doesn't take date

### ISSUE THREAD

**Issue by stefanhuber** [angular-ui/bootstrap#5236]
The new datepicker-popup doesn't take the date after clicking on the date on the calendar or rather clicking on Done. I have to use the ~0.14 version.

Tried on chrome and firefox

```html
   <input on-open-focus="false" datepicker-options="{\'starting-day\':1}" datepicker-append-to-body="true" uib-datepicker-popup="dd.MM.yyyy" type="text" ng-model="cell.value" close-on-date-selection="true" ng-model-options="{ updateOn:\'blur\' }" ng-change="detail.updateRow(rowIndex)" is-open="true">
```

**Comment by icfantv** [comment]
@stefanhuber, this is working in the demo.  Please extend us the courtesy of reading our project documentation for how to enter what you think is a bug.  You may find [these instructions here](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

I will consider reopening if you are able to recreate the issue in a minimally working plunker and there is no issue with your code.  Thanks.
