### ISSUE TITLE
Datepicker doesn't update view value when the date object changes elsewhere

### ISSUE THREAD

**Issue by reneolivo** [angular-ui/bootstrap#5237]
Plunker: http://plnkr.co/edit/hu3xJKGoqvTROxCiNyqA?p=preview

**Issue:** when you manipulate the date object from the controller, the input's view value and the widget don' t update themselves. The only way to make them work is to destroy the date object and create a new one.

**Comment by wesleycho** [comment]
That is correct - we have no way of knowing that the date object is changed from a user manipulation of the object itself when the reference is the same, nor should we I argue, as that would involve wasteful dirty checks of converting the date to its value.

**Comment by reneolivo** [comment]
Then why use a Date object when a string works great?

**Comment by icfantv** [comment]
@reneolivo, two reasons:

1. Trying to interpret a user's string resulted in a myriad of issues.  see [this commit](https://github.com/angular-ui/bootstrap/commit/ab4580fd) for the entire list of bugs - there's far too many to get into here.
2. Somehow supporting strings snuck back in and that was a regression.
