### ISSUE TITLE
Datepicker - max-date

### ISSUE THREAD

**Issue by BartoGabriel** [angular-ui/bootstrap#5238]
When I put the max-date to null is not expected behaves.

Example: http://plnkr.co/edit/4hJWbKjKvD5NGIlDoZvJ?p=preview
The example shows that when the calendar is opened, the date that lets you select is the 31/12/1969 (1969-12-31)

The expectation is that it has no maximum limit. Since max-date is null.

**Comment by dungvu-qe** [comment]
this my case, please check it, now we must set max-date year=2050

**Comment by Foxandxss** [comment]
I can see that. I will discuss it with my team and fix it for the next version.
