### ISSUE TITLE
Unregister watches on the parent scope

### ISSUE THREAD

**Issue by pedroclayman** [angular-ui/bootstrap#5242]
Several watches are registered on the parent scope in the datepicker.js. Those watches are going to be unregistered the moment the parent scope will be destroyed. Wouldn't it be wiser to unregister them when the directive's scope is being destroyed?

```javascript
  angular.forEach(['minDate', 'maxDate'], function(key) {
    if ($attrs[key]) {
      $scope.$parent.$watch($attrs[key], function(value) {
        self[key] = value ? angular.isDate(value) ? dateParser.fromTimezone(new Date(value), ngModelOptions.timezone) : new Date(dateFilter(value, 'medium')) : null;
        self.refreshView();
      });
    } else {
      self[key] = datepickerConfig[key] ? dateParser.fromTimezone(new Date(datepickerConfig[key]), ngModelOptions.timezone) : null;
    }
  });
```

**Comment by wesleycho** [comment]
I was wondering about watchers on the parent throughout several components - they probably should be garbage collected on $destroy.

Should be an easy PR (or few PRs for the other components where this is happening) if you'd like to try your hand at it.

**Comment by deeg** [comment]
I will try to get to this tonight or tomorrow.

**Comment by pedroclayman** [comment]
thanks!
