### ISSUE TITLE
Missing bottom border on uib-tabset inactive tabs with justified=true

### ISSUE THREAD

**Issue by SamuelPadou** [angular-ui/bootstrap#5243]
When the uib-tabset is configured with justified=true, the bottom border of the inactives tabs is not visible. This is reproductible on the demo page.

For justified tabs, Bootstrap display the bottom border on each individual tabs but this CSS is missing as div are used for tabs instead of a.

**Comment by wesleycho** [comment]
Missed this, but this should be addressed by #5262.
