### ISSUE TITLE
Cannot use controller at uib-tab level with Angular.js 1.4.0 and above

### ISSUE THREAD

**Issue by elgs** [angular-ui/bootstrap#5248]
Previously I was using Angular.js 1.3.x. For each tab, I had a separate controller. After upgrading to Angular.js 1.4.x. I got this error:

https://docs.angularjs.org/error/$compile/multidir?p0=ngController&p1=&p2=uibTab&p3=&p4=new%2Fisolated%20scope&p5=%3Cli%20ng-class%3D%22%7Bactive:%20active,%20disabled:%20disabled%7D%22%20class%3D%22uib-tab%22%20data-ng-controller%3D%22TableCtrl%22%20select%3D%22tablesSelectMe()%22%20active%3D%22staticTabs.tableActive%22%3E

The logic for each of my tabs is very different so that I don't want to put all tabs in a single controller. Is there any way for this problem? Thanks.

**Comment by icfantv** [comment]
@elgs, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

**Comment by elgs** [comment]
@icfantv is this not a bug?

**Comment by icfantv** [comment]
I suspect it's a combination of your code and what the API does internally.  Without seeing your code, I can't be certain.  This is why we have procedures and documentation in place for how to properly ask for help and how to properly report bugs.  Please extend us the courtesy of reading that documentation before entering an issue and asking for help.  Thanks.

For reference, the instructions on how to ask for help may be found [here](https://github.com/angular-ui/bootstrap#need-help) and instructions for how to properly enter a bug may be found [here](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Maintaining a very popular library requires a lot of hard work by many people who do it _in their spare time_.  Making our jobs as easy as possible is imperative for when you require assistance.

**Comment by elgs** [comment]
Here is the code in problem: http://plnkr.co/edit/x9DDLWIrqLuRFRM01mli?p=preview which uses Angular.js 1.4.8.

And Here is the code that works: http://plnkr.co/edit/sIGIMDr6dnvr0jWvmD49?p=preview which uses Angular.js 1.3.18.

The only difference is the Angular.js version numbers.

**Comment by elgs** [comment]
@icfantv please don't close this issue. I believe this is an incompatible upgrade, if it is not a bug.

**Comment by icfantv** [comment]
Angular UI Bootstrap 1.x _requires_ Angular 1.4+ and was tested with 1.4.8.  There is a dichotomy between our demo page, which says this, and our project readme which was not updated - this is our fault and I am correcting now.

**Comment by elgs** [comment]
@icfantv the thing is that a controller could be use at the `uib-tab` level in Angular 1.3.x, but it doesn't work with Angular 1.4.x. Would you confirm that it's by design that a controller should not be used at the `uib-tab` level? Or is there any remedy?

**Comment by elgs** [comment]
@icfantv would you please take a look at the two links I posted. This is a major problem in my way to upgrade to Angular.js 1.4.x. Thanks.

**Comment by elgs** [comment]
@icfantv would it be possible to reopen this case? If you rejected to reopen this case, I would open another issue addressing this problem. If it were still closed without being taken a look at, I would have to find a new tab solution, otherwise I had to staying at Angular.js 1.3.x.

**Comment by icfantv** [comment]
@elgs, Ok, let's both settle down here.

I said you needed to be patient.  This means you need to temper this expectation of someone getting back to you immediately.  Everyone on this project is a volunteer and no one does this as their full-time job.  It is not uncommon to have to wait 3-5 days for lower priority items.

I will reopen this if you promise to follow our project guidelines in the future.

**Comment by elgs** [comment]
Thanks @icfantv I appreciate your reopening it. As I said, I have no problem waiting. I'd be glad to do research on the problem. My only problem is closing an issue before it's resolved or rejected.

@icfantv I apologize if I offended you. I appreciate your time reviewing my issues.

**Comment by wesleycho** [comment]
It should be noted that one should avoid using ng-controller at all costs. It is better for performance if one created custom directive wrappers for each controller and used it as part of the content inside the uib-tab element. This also would be cleaner for your HTML if you have more complex tabs.

[Here](http://plnkr.co/edit/XbmATEwMLfZIF5yR9BGR?p=preview) is an example in action.

**Comment by elgs** [comment]
@wesleycho thanks for the reply. 

The heading text for my tabs are dynamic and I put them in the same scope as the tab controller previously. Now if I create a directive for the content inside the tab, looks like I have to separate the heading text from the content of the tab? Previously I need to read the heading text from the tab content area. Now it seems it's not easy to do so.

Performance is actually not a problem for my app. I guess the origin of this problem is that Angular 1.4 made some changes that do not allow multiple controllers/directives to access the same scope. Since `rib-tab` has already created a scope there, it prevents my controller from accessing that scope there.

**Comment by wesleycho** [comment]
I'm going to close this as something we can't really handle in the library.

I would recommend that perhaps you handle the logic above the tabs somehow since the heading text needs to depend on certain state with the content - this implies that it should be handled at a higher level so that updates can flow down without running into this issue.
