### ISSUE TITLE
Cannot use controller at uib-tab level with Angular.js 1.4.x

### ISSUE THREAD

**Issue by elgs** [angular-ui/bootstrap#5253]
Previously I was using Angular.js 1.3.x. For each tab, I had a separate controller. After upgrading to Angular.js 1.4.x. I got this error:

https://docs.angularjs.org/error/$compile/multidir?p0=ngController&p1=&p2=uibTab&p3=&p4=new%2Fisolated%20scope&p5=%3Cli%20ng-class%3D%22%7Bactive:%20active,%20disabled:%20disabled%7D%22%20class%3D%22uib-tab%22%20data-ng-controller%3D%22TableCtrl%22%20select%3D%22tablesSelectMe()%22%20active%3D%22staticTabs.tableActive%22%3E

The logic for each of my tabs is very different so that I don't want to put all tabs in a single controller. Is there any way for this problem? Thanks.

Here is the code in problem: http://plnkr.co/edit/x9DDLWIrqLuRFRM01mli?p=preview which uses Angular.js 1.4.8.

And Here is the code that works: http://plnkr.co/edit/sIGIMDr6dnvr0jWvmD49?p=preview which uses Angular.js 1.3.18.

The only difference is the Angular.js version numbers.

**Comment by icfantv** [comment]
@elgs please do not open duplicate issues.  you need to be patient.  if you cannot be patient then I encourage you to dig into the API and see what's causing the problem rather than making us debug your code.

**Comment by elgs** [comment]
Wonderful! Issues closed without a result.

**Comment by icfantv** [comment]
@elgs if you don't stop i'm going to block you and report you to the angular team.  this sense of entitlement you have with respect to us addressing your issues ASAP is greatly misplaced.  there are 80+ issues in the queue ahead of you.  why do you think your issue deserves the most attention?  especially when you absolutely refuse to take any ownership of doing any research into why your issue is occurring?

**Comment by elgs** [comment]
@icfantv go ahead and block me and report me to where ever you like please. I brought the issue to the most appropriate place. I have no problem waiting. I never refuse to take any ownership of doing any research. The interesting thing is my issues were closed without any result. To me it's obviously an open issue. Leaving it open at least leaves a chance for people to take a look at it. If an issue is closed, it's either resolved or rejected, in my opinion. Closing an issue without getting it resolved or rejected to me is totally senseless. I would not open another issue here. I would not waste my time using things like this at all.
