### ISSUE TITLE
element.addClass('dropdown-toggle'); line breaks dropdown focus

### ISSUE THREAD

**Issue by Codermar** [angular-ui/bootstrap#5259]
Line 311 on dropdown.js breaks accessibility dropdown focus in button.

element.addClass('dropdown-toggle');

Removing it resolves it.

Please attach to #4772

**Comment by wesleycho** [comment]
Why would this break focus? Can you explain in more detail/post a reproduction in [Plunker](http://plnkr.co/edit/qG9z6HWntfKn01LVrzzN?p=preview)?

**Comment by Codermar** [comment]
Not a bug, my apologies, the cause of this is the override in the bootstrap css:
.dropdown-toggle:focus {
  outline: 0;
}
I am not sure why they decided to remove the outline. My accessibility QA raised this issue so I've restored the outline: 
.dropdown-toggle:focus {
outline: auto 5px -webkit-focus-ring-color;
}
