### ISSUE TITLE
Typeahead selection by mouse click doesn't work

### ISSUE THREAD

**Issue by ashigl** [angular-ui/bootstrap#5272]
Using Bootstrap 0.11.0 and angular js v1.4.8, the Typeahead selection by mouse click doesn't work. It works when keyboard enter is used.
There was a similar problem discussed for v1.3.0, which was fixed but problem seems to be there in v1.4 -> https://github.com/angular-ui/bootstrap/issues/2293

**Comment by icfantv** [comment]
@ashigl, If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

**Comment by wesleycho** [comment]
Keep in mind, UI Bootstrap is now on 1.0.3 - 0.11.0 is almost 2 years old, so we can't really help with any issues on a version that old.

**Comment by any-hn** [comment]
Related Plunkr link below:
http://plnkr.co/edit/TokpsC12d8rhzBPQojvc?p=preview

**Comment by icfantv** [comment]
@any-hn, to reiterate what @wesleycho said, given the age of the library being used, I'm pretty certain it doesn't make any sense for us to spend time on this.  We are not going to release a patch to the 0.11 version.  As an aside, I check that plunker with 0.12.0 and the issue goes away so if you're absolutely stuck on an old version, perhaps upgrading to 0.12.0 will work for you.

**Comment by any-hn** [comment]
cool. thanks @icfantv
