### ISSUE TITLE
update to angular-bootstrap 1.0

### ISSUE THREAD

**Issue by trendzetter** [angular-ui/bootstrap#5273]
Angular-bootstrap 1.0 is out. Would it be desirable for you to update? I created a patch see gist:
https://gist.github.com/trendzetter/c1e7be8bd3e41404fd49

**Comment by trendzetter** [comment]
https://gist.github.com/trendzetter/c1e7be8bd3e41404fd49

**Comment by Foxandxss** [comment]
I am sorry, I don't understand.

**Comment by trendzetter** [comment]
angular-bootstrap in meanjs is stuck on 0.13.
The 1.0 release has many improvements.

**Comment by Foxandxss** [comment]
I get you now. But you are on the wrong repository. You need to open an issue / PR in their repo, not here :P

**Comment by trendzetter** [comment]
oops!!!
