### ISSUE TITLE
Swapping day/mont/year templates of the datepicker

### ISSUE THREAD

**Issue by Foxandxss** [angular-ui/bootstrap#5279]
I have seen that we have the same attr `templateUrl` for all of our xxxpicker. How is someone supposed to swap a concrete template? If we need to override `datepicker.html` I think that it loses its purpose a bit.

WDYT?

**Comment by wesleycho** [comment]
Currently, by being able to swap out datepicker.html, one can then do this in the datepicker template:
`<uib-daypicker template-url="myNewTemplate.html">` - I think this is sufficient.

**Comment by Foxandxss** [comment]
I haven't thought about that possibility. I guess it is fine.
