### ISSUE TITLE
Popover animation broken when jquery-ui is included

### ISSUE THREAD

**Issue by devguydavid** [angular-ui/bootstrap#5282]
http://plnkr.co/edit/XeCPqw10y2Ln8rGQD9V0?p=preview

ui-bootstrap worked fine in this case in 0.14.3. Since 1.0.0 (and tested in 1.0.3) it no longer animates properly when jquery-ui is included. The fade still applies, but the popover itself translates into position (the margin value) and the arrow instantly appears once the translation is done. In some cases I've even seen it re-translate from 0 to the adjusted margin on events such as click or typing (in the case where a form element is inside the popover).

I wouldn't normally include jquery-ui except I'm using https://github.com/angular-ui/ui-sortable which requires it.

**Comment by wesleycho** [comment]
This is fixed by #5235, will be in the next release on Monday.
