### ISSUE TITLE
Modal flashing full width when toggled

### ISSUE THREAD

**Issue by hphu** [angular-ui/bootstrap#5286]
When toggling the modal, the user can see the modal at full width for a tiny moment before it resizes. This is happening on the official guide's plunker: http://plnkr.co/edit/EtBemPzKe1YRnHvE4Ooi?p=preview 

gif of what i see:
![angularmodalbug](https://cloud.githubusercontent.com/assets/5354683/12378257/57d80ef8-bd06-11e5-84f2-16072827826a.gif)

I am using Google Chrome Version 47.0.2526.106 (64-bit).

**Comment by philBrown** [comment]
It's probably related to https://github.com/angular-ui/bootstrap/issues/5183. My guess would be the modal size CSS class is being applied whilst the fade / slide animation runs.

**Comment by Foxandxss** [comment]
Totally. It is fixed in master.
