### ISSUE TITLE
Radio is not working as it should with ng-repeat

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#5288]
I've made plknr to show the case:
http://plnkr.co/edit/38GrcvcFlGcxGp6Yq8cq?p=preview

ngModel is not changed.

**Comment by AndriIushchuk** [comment]
@piernik it's working as it should. Please look at [binding ng-model inside ng-repeat loop in AngularJS](http://stackoverflow.com/a/14411131/5337516)

**Comment by piernik** [comment]
ok You're right. Thanks
