### ISSUE TITLE
Modal's contents flashes on top of body before it's rendered

### ISSUE THREAD

**Issue by atte-backman** [angular-ui/bootstrap#5291]
As the title says. The same behavior can be seen on demo-page as well.

**Comment by cynrichuysAE** [comment]
Duplicate of #5183?

**Comment by maxm450** [comment]
:+1:

**Comment by icfantv** [comment]
@cynrichuysAE, indeed it is a duplicate.  @atte-backman, please extend us the courtesy of searching both open and closed issues before entering a new one.  Processing user-entered issues is usually a time-consuming and cumbersome process (albeit, not in this case, as this was a quick resolution) so we ask that you please respect our time by doing some sort of due diligence first.  Thanks.
