### ISSUE TITLE
Can't clear timepicker without adding extra button 

### ISSUE THREAD

**Issue by asurinov** [angular-ui/bootstrap#5293]
There is no ability to reset timepicker's model using keyboard, without adding extra button. Input value sets to '00' on blur.

**Comment by icfantv** [comment]
@asurinov, I'm not exactly sure what you're asking for here.  Even our demo has an external button.  Can you please elaborate?  Thanks.

**Comment by asurinov** [comment]
![example](https://cloud.githubusercontent.com/assets/5726950/12397774/5d56a64e-be20-11e5-9aa3-57df26e7fcd5.gif)

**Comment by asurinov** [comment]
I attach an example. Timepicker fields can't be cleared. For example, datepicker control supports such usecase.

**Comment by icfantv** [comment]
Got it.  I would revise the reproducibility steps to include delete the contents of the field and then click off to force it to lose focus.  Feel free to submit a PR for this if you want to take a gander.  Until I am overruled, I think this is something we could/should fix.

**Comment by icfantv** [comment]
Another note.  This can be seen in our demo page as well.

**Comment by icfantv** [comment]
@asurinov, reading the code, it looks like this may be intentional behavior to prevent the user from having invalid data entered:  https://github.com/angular-ui/bootstrap/blob/master/src/timepicker/timepicker.js#L353-L362.

I'm going to wait to see what the devs decide here before promising anything.

**Comment by wesleycho** [comment]
I'd argue this is by design - this doesn't have any buttons except to increment or decrement. However the user wants a clear button, we leave it up to the user to implement and choose where to locate it to take minimal opinion.

**Comment by Foxandxss** [comment]
I think that the enduser can add a button to do that if they want to.
