### ISSUE TITLE
pagination - make labels accept html

### ISSUE THREAD

**Issue by thiagodp** [angular-ui/bootstrap#5303]
One recurring problem many developers face is using HTML instead of plain text for attributes such as previous-text and next-text.

For instance, instead of using something like:
```html
previous-text="&lsaquo;"
next-text="&rsaquo;"
```
we would like to define an icon:

```html
previous-text="<i class='previous-icon' ></i>"
next-text="<i class='next-icon' ></i>"
```
I know we can edit the template file, but this may not scale for using with different projects or pages that apply different pagination styles.

**Comment by thiagodp** [comment]
Maybe a good option is creating `previous-html` and `next-html` and using `ngSanitize`.

**Comment by wesleycho** [comment]
One could just override the template - for your purposes, this might even be better.

**Comment by thiagodp** [comment]
As I said before:
> I know we can edit the template file, but this may not scale for using with different projects or pages that apply different pagination styles.

**Comment by wesleycho** [comment]
My problem here is that this seems simple to override for a template, and perhaps even desired for a particular company since you generally want to keep the theme the same. In addition, this likely has negative performance ramifications since it deals with DOM creation/destruction & sanitization.

**Comment by thiagodp** [comment]
Is there any attribute to indicate the template file? Is it possible to create additional template files and choosing them using the directive? (If yes, problem solved. If no, I think my suggestion is a good option).

**Comment by wesleycho** [comment]
One can override on the instance level using the `template-url` attribute - see the [pagination docs](http://angular-ui.github.io/bootstrap/#/pagination) for more detail on usage.

If one wants to override the global, one can simply just override the $templateCache of `uib/template/pagination/pagination.html`.

**Comment by thiagodp** [comment]
So problem solved! ;)

**Comment by wesleycho** [comment]
Not a problem!

Going to close as resolved then.
