### ISSUE TITLE
If using modal-transclude in your template, migrating from $modal to $uibModal requires "uib-modal-transclude"

### ISSUE THREAD

**Issue by csojka** [angular-ui/bootstrap#5304]
The only way to know that this change happened was to look at:

https://github.com/angular-ui/bootstrap/blob/master/template/modal/window.html

```
<div modal-render="{{$isRendered}}" tabindex="-1" role="dialog" class="modal"
    uib-modal-animation-class="fade"
    modal-in-class="in"
    ng-style="{'z-index': 1050 + index*10, display: 'block'}">
    <div class="modal-dialog {{size ? 'modal-' + size : ''}}"><div class="modal-content" uib-modal-transclude></div></div>
</div>
```

This should likely be mentioned in the migration guide as well.

**Comment by wesleycho** [comment]
Done - thanks for catching this

**Comment by csojka** [comment]
thanks for the fast update! Great work on this set of tools.

**Comment by nmccready** [comment]
Where was this done? It needs to standout on the main websites documentation for `modal`. This was an  hours of headache.
