### ISSUE TITLE
Datapicker in popover

### ISSUE THREAD

**Issue by BartoGabriel** [angular-ui/bootstrap#5305]
When a datapicker is placed within a popover and popover is set `popover-trigger="outsideClick"`, the datapicker not work correctly.

See the following example:
http://plnkr.co/edit/yQ20ODyzkcDABuij4g5R?p=preview

Steps to follow:
1. Press "date"
2. Press the button that opens the "From" calendar
3. Press out the calendar but within the popover. Such as on the word "from".
4. Then try to open the "From" calendar again. And he notes that can not be opened until it closes and open the popover.

**Comment by wesleycho** [comment]
This appears to be a bug - what appears to be happening is that when the datepicker is closed, the state of `is-open` is not updated properly.

**Comment by BartoGabriel** [comment]
Yeah, but the strange thing is that this only happens when it is in a popover.
I think the popover-trigger are affecting proper operation.

**Comment by wesleycho** [comment]
I see what is happening - this is not a bug, but a usage issue from the fact that primitives are used instead of objects on $scope.

See [here](http://plnkr.co/edit/dMWd7KRHjaoOZWXyYvE5?p=preview) for how to correctly accomplish what is desired

**Comment by BartoGabriel** [comment]
You are right, sorry... I didn't check my code accordingly.

**Comment by BartoGabriel** [comment]
@wesleycho I found two problems in the example.
1. When I click on "today" the popover closes unexpectedly.
2. When I select a date the calendar closes, again I select a new date in the same calendar and closes unexpectedly the popover. This happens when I select twice dates in the same calendar.
