### ISSUE TITLE
How to prepare an npm package?

### ISSUE THREAD

**Issue by kayhadrin** [angular-ui/bootstrap#5309]
Hi there,

I've done some code customizations for my project and I'd like to publish them on my local npm repo (Nexus server).

How would you recommend to do this?

Currently, if I run `grunt shell:release-prepare`, I can see the creation of the `dist` folder but I don't see any `index.js` file in it. So I'm not sure that it's sufficient to make it usable in npm when using require().

Any help would be greatly appreciated!

Regards,

David

**Comment by wesleycho** [comment]
Unfortunately, it is a manual process currently - I clear out `dist`, make sure package.json has the desired version, run `grunt`, then copy the files to the needed locations (the `gh-pages` branch, the `bootstrap-bower` repository). To release, I rename the `dist/ui-bootstrap-` files by stripping out the version numbers, then run `npm publish`.

**Comment by kayhadrin** [comment]
Oh ok ok. Should I assume that the index.js file at the root of the npm
package is created by the npm publish action automatically then?

**Comment by wesleycho** [comment]
The index.js is already in the repository - see https://github.com/angular-ui/bootstrap/blob/master/index.js

I'm going to close this as a support issue, but feel free to ask more questions if you have any.

**Comment by kayhadrin** [comment]
Thanks for the info!
