### ISSUE TITLE
'format-day-title' can not work

### ISSUE THREAD

**Issue by smallg** [angular-ui/bootstrap#5310]
I added format-day-title="yyyy MMMM" into datepicker input element.
but it can not work, the title still show 
![image](https://cloud.githubusercontent.com/assets/225962/12440807/bad97a34-bf7a-11e5-88e5-0d2cf588f63e.png)

When I modify ui-bootstrap-tpls.js and change
![image](https://cloud.githubusercontent.com/assets/225962/12440823/da735e50-bf7a-11e5-9f5c-26bd5724a5f5.png)
it's works.

I think this issue need to fix.

**Comment by icfantv** [comment]
@smallg, I'm not exactly sure I follow.  What do you mean by 'title?'

**Comment by smallg** [comment]
@icfantv I want format this title
![image](https://cloud.githubusercontent.com/assets/225962/12442213/0bfa441c-bf89-11e5-8c00-851f2cc8bafc.png)

but this way can not work format-day-title="yyyy MMMM"

**Comment by wesleycho** [comment]
That is not supported as far as I can see from the documentation. You have to use the `datepicker-options` attribute to bind the desired datepicker options.

**Comment by smallg** [comment]
![image](https://cloud.githubusercontent.com/assets/225962/12471213/6bb89540-c036-11e5-975c-2e114d8d4301.png)
![image](https://cloud.githubusercontent.com/assets/225962/12471217/73efafaa-c036-11e5-84e8-e6fa35ab134c.png)

it works, thanks
