### ISSUE TITLE
Is there language option?

### ISSUE THREAD

**Issue by qidaneix** [angular-ui/bootstrap#5312]
What can I do to change it to zh-CN? thank you!

**Comment by Foxandxss** [comment]
We don't offer internationalization as today (we will study it for the future).

The best thing you can do is to translate all the templates and use them instead of the originals.

**Comment by qidaneix** [comment]
@Foxandxss I can't find where you define month and week in datepicker, could you please tell me where is it? Thx

**Comment by Foxandxss** [comment]
All templates are structured under `/template` in the same way as `src` so `/template/datepicker`. Check for `daypicker` for the "week one" and `monthpicker` for the month one.
