### ISSUE TITLE
if state changes $modal has to disable how to close modal

### ISSUE THREAD

**Issue by naveencasp** [angular-ui/bootstrap#5313]
factory('myHttpInterceptor', function ($location) {
        var timestampMarker = {
            response: function(response) {
               /* console.debug('factory response checking..',response);*/
                if(response.data=='wrong'){
                    $location.path('/login');
                }
                return response;
            }
        };
        return timestampMarker;
    })

in the above code i'm not able to close modeInstance 
How to disable $model

**Comment by Foxandxss** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
