### ISSUE TITLE
Cannot close datepicker popup

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#5320]
I have app with routes.
When I open datepicker popup and then press `backspace` browser moves back in history and form with date field is no more and popup cannot be closed - even with `done` button.

Done button should always close popup

**Comment by icfantv** [comment]
If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

**Comment by piernik** [comment]
I see it's fixed in 1.1.0 - was broken in 1.0.3
Thanks
