### ISSUE TITLE
issue/bug with minDate and display days?

### ISSUE THREAD

**Issue by yanivlllev** [angular-ui/bootstrap#5323]
i'm having problems with using minDate and i have no clue why,
when i use it - the days in the row of the current day get messed up

this is my input in my html: 

      <input type="text" class="form-control cursor-pointer" size="16"
           placeholder="E.g. 01-01-2017"
           ng-model="deadline"
           required="required" input-validation-icon
           is-open="isDatePickerOpen" uib-datepicker-popup="{{'MM-dd-yyyy'}}"
           min-date="minDate"
           show-weeks="false"
           show-button-bar="false"
           ng-click="isDatePickerOpen=!isDatePickerOpen"/>

this is my minDate variable in controller:

        $scope.minDate = new Date();

here is in img to show it... :
![img](https://cloud.githubusercontent.com/assets/12447235/12484846/cc807e6e-c064-11e5-98e5-9e104ec2d8d1.jpg)

**Comment by Foxandxss** [comment]
Can you make a plunker please? That `uib-datepicker-popup="{{'MM-dd-yyyy'}}"` is freaking me out.

**Comment by yanivlllev** [comment]
hey, i'm closing it... 
i have NO idea what happened and what fixed it, but now it works fine with the minDate... 
sorry, thanks.
