### ISSUE TITLE
Datepicker default value timestamp

### ISSUE THREAD

**Issue by isimonov** [angular-ui/bootstrap#5328]
If the default value of the timestamp, then the DatePicker is not working. The problem started to happen in version 1.1.0, in earlier versions it worked.

Console error: *TypeError: this.activeDate.getFullYear is not a function*

http://plnkr.co/edit/soJGCM48U0ifrcN17P0y

![default](https://cloud.githubusercontent.com/assets/2580203/12503946/06fa6e30-c0ea-11e5-86f8-b5c979797c0e.png)

**Comment by dawciobiel** [comment]
Same problem. In example code try this:
...
this.testDate = new Date(1452470400000);

**Comment by isimonov** [comment]
Yes, it works. But I would like the return of behavior that once was. Don't want to think every time about casting timestamp to a Date type.

**Comment by migajek** [comment]
yeah it should handle string value as well, as it used to.
please note JSON apis return date as string (ISO-8601 for example)

**Comment by wesleycho** [comment]
@migajek we removed string support due to unfixable cross-browser bugs. Please do not derail issues.

This is sort of related to #5190, may even be a duplicate.

**Comment by icfantv** [comment]
I'm not sure this is an issue.  If you use a `Date` object instead of a `long` the code works properly.  @wesleycho, I think we can close this.

**Comment by migajek** [comment]
@wesleycho sorry, just can't find it in the release notes, neither in the issues. should I fill the new one? I believe this is a major/breaking change ...

**Comment by wesleycho** [comment]
Closing, as per comment by @icfantv - convert to use a date instance if desired.
