### ISSUE TITLE
Angular ui Bootstrap touch event is not working in Nokia lumia 720 and other window devices which have ie 10

### ISSUE THREAD

**Issue by gopiece04** [angular-ui/bootstrap#5329]
Hi 

I am using Angular ui Bootstrap in my web application,  touch/ click event is not working/triggering in Nokia lumia 720 and other window devices which have ie 10. so modal, dropdown and other directives is not working.

Give me the solution to resolve

Regards
Gopinath BS

**Comment by wesleycho** [comment]
@gopiece04 typically users will use a solution such as fastclick, ngTouch, or hammer.js for mobile.

This is also a question better suited for StackOverflow or other places - in general, please read [contributing.md](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem) before filing issues in a repository.
