### ISSUE TITLE
Middle clicking on tabs has different behaviour in Firefox

### ISSUE THREAD

**Issue by d-lane** [angular-ui/bootstrap#5332]
Clicking a ui.bootstrap.tabs with the mouse wheel in Chrome or IE is the same as clicking normally, however in Firefox it opens a new browser tab of the same page. For instance, middle clicking the tabs on the [demo page](http://angular-ui.github.io/bootstrap/#/tabs) in Firefox will open the demo page again (and not select the clicked tab).

**Comment by icfantv** [comment]
As we don't have any browser specific logic in there for click handling, I'm not sure there's anything we are going to be able to do here.  Especially since this can be overridden at the OS level.

**Comment by wesleycho** [comment]
We could do a `event.stopPropagation()` if `event.which === 2` I guess and adapt the select function.

**Comment by wesleycho** [comment]
As per https://github.com/angular-ui/bootstrap/pull/5636#issuecomment-197932542, closing as won't fix.
