### ISSUE TITLE
MathJax in tooltip HTML

### ISSUE THREAD

**Issue by stephenHartzell** [angular-ui/bootstrap#5333]
I'm trying to use MathJax inside of a tooltip. For some reason it doesn't render when put inside of tooltip HTML template using the uib-tooltip-template. Any ideas as to why that is?

**Comment by wesleycho** [comment]
Closing as a support question: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
