### ISSUE TITLE
ES6 Question: How to import angular bootstrap using JSPM

### ISSUE THREAD

**Issue by bhushanvaidya3** [angular-ui/bootstrap#5339]
I was able to install "angular bootstrap" using JSPM but don't know which class to import.

I tried this but it doesn't work:

import ui.bootstrap from "angular-bootstrap";

Thanks!

**Comment by wesleycho** [comment]
Closing as a support issue - we do not have the repository registered on JSPM I believe (unless someone else registered it), but one can reference the npm install as mentioned https://github.com/angular-ui/bootstrap#install-with-npm and use JSPM to `import 'angular-ui-bootstrap'`

**Comment by bhushanvaidya3** [comment]
Thanks for the update @wesleycho! JSPM registry already has a hook to pull angular bootstrap from bower but the import is failing. I tried importing "ui.bootstrap" as well as "angular-ui-bootstrap" but get error while executing it.

**Comment by bhushanvaidya3** [comment]
Found a work around. Instead of using specific class to import, I just used $ instead. Works fine.

e.g., import $ from 'angular-bootstrap';

**Comment by icfantv** [comment]
@bhushanvaidya3, don't use `$` as that's usually reserved for jquery.  A better solution would be to use `import uiBootstrap from 'angular-ui-bootstrap';` and then `angular.module(...,[..., uiBootstrap, ...])`.  This is what we do at work.

**Comment by bhushanvaidya3** [comment]
@icfantv thanks, that worked fine :+1:
