### ISSUE TITLE
When transitioning, carousel changes link style on other parts of the page (Chrome)

### ISSUE THREAD

**Issue by anyandallart** [angular-ui/bootstrap#5342]
I've been using the Angular UI Bootstrap carousel, and when I do, it causes a change in the link style on links inside of a div with class="col-md-12". The style reverts back after the transition. I'm on Windows 10, I've also tested it on a friend's Mac. Chrome version: 47.0.2526.111

This is a link demonstrating the issue. The bottom 3 links change style on transition:
http://www.flippingscripts.com/dev/carousel.php

I managed to fix this by wrapping the carousel in a relatively positioned div with a z-index, 
i.e. style="position:relative; z-index:1"

Example of appliex fix: http://www.flippingscripts.com/dev/carousel-fixed.php

This still seems odd.

Any thoughts?

P.S. This issue does not occur in Safari, Internet Explorer, or Firefox. It does not occur on Chrome for Android. It does occur in Chrome on Macs and Windows.

**Comment by wesleycho** [comment]
This looks like potentially a browser bug. This also occurs on Chrome on OS X as well.

I don't think there is anything we can do here though.
