### ISSUE TITLE
Resolves, controller and deferred template loading for the accordion component.

### ISSUE THREAD

**Issue by crisbeto** [angular-ui/bootstrap#5344]
While porting some functionality from the modal directive to the accordion, I found out that the `accordionGroup` directive loads and renders all of the custom templates, even if the accordion group is closed. I wrote a patch that allows for loading the template only if that group gets opened, in addition to allowing for resolving data and adding controllers in a similar way to the modal directive. Are you interested in a PR to add this functionality to UI-Bootstrap?

**Comment by wesleycho** [comment]
In general, this is against recommended practices - it is generally recommended that the template be bundled as a part of $templateCache.

I do not think we should support this.

**Comment by crisbeto** [comment]
Makes sense, it was more appropriate for my case since I had a lot of data that should be available only when a group is open.
