### ISSUE TITLE
missing ui-bootstrap-tpls in version 1.1.1

### ISSUE THREAD

**Issue by blackat** [angular-ui/bootstrap#5346]
Hello,
I have installed the package via bower and I do not have any `dist/` folder and there are not files `ui-bootstrap-tpls.js` and `ui-bootstrap-tpls.min.js`.

The installation via `npm` is correct but not the one via bower, am I missing something?

Thanks a lot for the attention :wink:

**Comment by pkozlowski-opensource** [comment]
> am I missing something?

Probably, since it seems like all the files are well present in bower distribution repository: https://github.com/angular-ui/bootstrap-bower

Are you sure that you are properly following installation instructions? https://github.com/angular-ui/bootstrap-bower#install-with-bower

**Comment by blackat** [comment]
Ah! You are right Pawel, `bower install angular-bootstrap` while I have run `bower install angular-ui-bootstrap`, it works but with different result.

Thanks a lot for your help :wink:
