### ISSUE TITLE
feat(uib-carousel): expose current index and update it after a slide gets changed

### ISSUE THREAD

**Issue by sryzycki** [angular-ui/bootstrap#5353]
Is it possible to get current index from outside of the uib-carousel component? I read the source code and cannot find an option.

I thought that we could have an uib-carousel attr that would call provided function and inject the whole object that has the component has been fed with. That function could be called after instantiation and a slide change. Is my thinking okay here or it can be done much better?

**Comment by wesleycho** [comment]
Currently, one needs to iterate over all of the slides and find the slide with `active: true`.

We eventually want to make a breaking change where one can access the active slide through a simple two-way binding, and setting active would be as simple as setting the active slide on the carousel directive.

**Comment by sryzycki** [comment]
@wesleycho Thanks for the rapid response!

Just to clarify, currently one needs to inject `$scope`, save the `slides` object to `$scope.slides` (which are used to populate the `uib-slide` elements with the `active="slide"` attribute) and then create a `$scope.watch` on that object - is that the only way?

Also, could you elaborate a bit on that breaking change you think about (or maybe do you have it written down somewhere) just in case someone would like to submit a PR?

**Comment by wesleycho** [comment]
The carousel API is sort of not great currently - compare how one has to provide the data structure and interact with it compared to the accordion. The slide model is too coupled to UI Bootstrap, as opposed to being an independent object.

**Comment by wesleycho** [comment]
Took a quick look, the only way unfortunately is to watch the slide objects - we need to make a major breaking change to expose this in a more proper way.
