### ISSUE TITLE
uib-pagination doesn't work with ES6 (system/jspm)

### ISSUE THREAD

**Issue by bhushanvaidya3** [angular-ui/bootstrap#5356]
While migrating my angularjs application to ES6, I figured out uib-pagination stopped working. I replaced it with other directive and it worked fine. Just wanted to let you know...

**Comment by Foxandxss** [comment]
We need more information than that.

Error given, some reproduction...

Thanks.

**Comment by icfantv** [comment]
@bhushanvaidya3, we're also in the process of converting our application to ES6 and have not yet run into any issues.  As @Foxandxss, until and unless you give us a working example that shows the error, it's impossible for us to do anything about this.  Also, the statement "I replaced it with the other directive..." is meaningless without any context.  E.g., what other directive?

**Comment by bhushanvaidya3** [comment]
@Foxandxss @icfantv  Thanks for replying guys. It doesn't give any errors. At least no errors in console. The control just doesn't render on screen. The values it needs are all generated.

 I'm using "angular-utils-pagination" directive for the time being.  It worked fine with my current implementation.

**Comment by icfantv** [comment]
@bhushanvaidya3, so.....that's not one of our directives.  what project are you using?

**Comment by icfantv** [comment]
I'm going to go ahead and close this.  We will consider reopening if we determine that it's actually our code and there's a reproducible issue.
