### ISSUE TITLE
[typeahead]when I use 'template-url' with 'typeahead-show-hint' makes conflict.

### ISSUE THREAD

**Issue by coolwine** [angular-ui/bootstrap#5357]
Here is [plnkr](http://plnkr.co/edit/Iz4yxKJRxMwnKQfhVeM2?p=preview).

when i click to try to use typeahead.

makes a some error.

`Cannot read property 'length' of undefined , ui-bootstrap-tpls-1.1.1.js:6049`

I think the error because of  'template-url' not load yet. but show-hint option going to show some data before load finishing. 

so i fix my code.

`  if (showHint) {var firstLabel = scope.matches[0].label;
  if(!inputValue)return;......}`

**Comment by wesleycho** [comment]
Did a little looking into, this is only a problem when min-length="0" is combined with show-hint="true". This should be easy to fix if I had to guess.
