### ISSUE TITLE
Alert support for closing without handler function

### ISSUE THREAD

**Issue by lobodpav** [angular-ui/bootstrap#536]
Currently, one can create alerts by something like:
&lt;alert ng-repeat="alert in alerts" type="alert.type" close="closeAlert($index)">{{alert.msg}}&lt;/alert>

However, if I need a single simple alert, I am targeting to write this snippet:
&lt;alert type="'error'" close>OMG, alert!!!&lt;/alert>

This works well except the close button. I do not want to call any javascript, but instead just to allow to user to get rid of the message.

It would be great if the code uses some default close action when no value is specified in the close attribute. Actually, the same way bootstrap works when I add close button.

**Comment by azachar** [comment]
Anyway I think this is not elegant at all
```
<alert type="'error'" ng-show="$parent.loginError" close="loginError = false">Alert msg</alert>
```

and it should be encapsulated for such a simple case.

**Comment by sbolofsson** [comment]
You could also do this. It even works without a controller as it uses the directive's scope.

```html
<alert type="success" role="alert" close="close = true;" ng-show="!close">
	Happy alert
</alert>
```
