### ISSUE TITLE
Uib-carousel cannot slide after setting a slide to active

### ISSUE THREAD

**Issue by junduanvibesmg** [angular-ui/bootstrap#5362]
Here's a fork of the [plunker](http://plnkr.co/edit/YNYRFpPTtae2VnrhenZf?p=preview) of uib-carousel on [ui.bootstrap]( https://angular-ui.github.io/bootstrap/#/carousel).

I added a line in the controller after the for loop for populating $scope.slides:
$scope.slides[1].active = true;

I want to pre-select a certain slide, however, after adding this line, the uib-carousel stopped sliding. It seem to have been fixed in place.

This is the intended behaviour? Or am I going about setting the active slide the wrong way?

**Comment by icfantv** [comment]
@junduanvibesmg, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

We expose the carousel controller via `controllerAs` and you want to use the `select` method.  Or, you can set the `active` attribute on the `uib-slide` for the slide you want active in your HTML.
