### ISSUE TITLE
Add missing info to Migration Guide

### ISSUE THREAD

**Issue by adamweeks** [angular-ui/bootstrap#5364]
In the migration guide, there is no mention of the change from `$modalInstance` to `$uibModalInstance` under the **Modal** heading.

Change: `$modalInstance` for `$uibModalInstance`.

In the migration guide, there is no mention of the change from `tab-heading` to `uib-tab-heading` under the ** Tabs** heading.

Change: `tab-heading` for `uib-tab-heading`.

**Comment by icfantv** [comment]
@adamweeks, cool.  Good catch.

**Comment by adamweeks** [comment]
Looks like `tab-heading` got changed to `uib-tab-heading` as well. Should I open another ticket for it?

**Comment by icfantv** [comment]
nah.  we can combine them.  thanks.

**Comment by adamweeks** [comment]
Perfect, thanks. I'm in the process of doing a migration and will update this ticket if I find more.

**Comment by icfantv** [comment]
Sounds good.  I've fixed those two.  I'm going to close this but feel free to comment if you find others and I'll reopen.

**Comment by surry** [comment]
@icfantv - The change from `paginationConfig` to `uibPaginationConfig` is not documented in the migration guide under **Pagination**. I ran into an issue injecting that after upgrading. After looking at pagination.js, I changed to uibPaginationConfig and I'm not seeing the injection issue any more.

**Comment by icfantv** [comment]
@surry cool, thanks.  Do you mind opening a new issue for this and linking this one in?  I don't want it to get lost.  Thanks.

**Comment by surry** [comment]
@icfantv - Created #5717. Let me know if you need anything else.
