### ISSUE TITLE
-tpls version vs. 'regular' version

### ISSUE THREAD

**Issue by comountainclimber** [angular-ui/bootstrap#5366]
Why does this team have two different versions of the ui-bootstrap script, is there a reason other than to give people a headache? If one wanted to create custom directives to overwrite the ones provided with UIB why would they be using it in the first place?

**Comment by icfantv** [comment]
@comountainclimber - it's not the overriding the custom directives, it's overriding the directive's templates.  If you're overriding the templates, you don't want the ones included in the application because all they would do then is add bloat.

**Comment by icfantv** [comment]
Oh, and I can assure you, it's not to give people a headache.  :-)
