### ISSUE TITLE
datepicker ng-model doesn't support a string anymore

### ISSUE THREAD

**Issue by tribicito** [angular-ui/bootstrap#5367]
I'm using moment to format dates, as a result, the dates become strings. This seem to work just fine when I upgraded from 0.14 to 1.0.0. I kept upgrading the library and I noticed that with 1.1.1 the calendar doesn't work anymore. I did some digging and the calendar works up to 1.0.3 with the ng-model being a string. I'm using AngularJS 1.4.9, bootstrap UI 1.1.0 and moment 2.11.1. I reviewed the changelog and I don't see any change that would have caused this behavior. Attached is the plunkr so you can check the results. The calendar works correctly if you just assign a ng-model with the value of new Date() instead of using the string.

https://plnkr.co/edit/pqBK0omSm2Mdt86ov4WS?p=preview

**Comment by icfantv** [comment]
@tribicito, please extend us the courtesy of reading the project documentation (including CHANGELOG - paying particular attention to the breaking changes sections within each version) as well as searching both open and closed issues before opening a new one.  Thanks.  People have reported this issue numerous times.

The ability to support strings was removed in 0.13.2 and was erroneously added back in recently due a rogue PR and was correctly re-removed in 1.1.0.  Either way, the API docs for datepicker state that a Javascript `Date` object must be used.
