### ISSUE TITLE
Support conditional update on panel-class

### ISSUE THREAD

**Issue by rohdef** [angular-ui/bootstrap#5368]
I have a set of options that I group in the accordion, I'd like to do something like this:

<uib-accordion-group ng-repeat="setting in mySettings" is-open="setting.isVisible"
                         panel-class="{{setting.isValid ? 'panel-danger' : ''}}">

thing is this works on load, but does not update when the isValid setting is changed :(

**Comment by Foxandxss** [comment]
There is no support for that at this moment. `panel-class` is set once.

Not hard to do, but every watch is a performance hit on the app and we need to consider if that feature is worthwhile or not for that.

**Comment by wesleycho** [comment]
We could support an optional @ binding. I think I would be fine with that, seems reasonable - the workaround is to do something like `class="{{foo ? 'panel-danger'}}"`, which potentially adds likely two watchers anyway. (1 interpolation * 2, 2 for the original element and for the element replacing it)

**Comment by rohdef** [comment]
@Foxandxss that makes sense, I guess for the majority of the uses cases you're quite right. The suggestion by @wesleychy seemss quite reasonable to me :)
