### ISSUE TITLE
How to get Carousel slide transition events

### ISSUE THREAD

**Issue by VinaykumarNM** [angular-ui/bootstrap#5369]
Hi,
In base bootstrap carousel component there are two events available (slide.bs.carousel and slid.bs.carousel), I wonder how these two events can be handled in angular-ui carousel directive.

Thanks
Vinay

**Comment by Foxandxss** [comment]
It is true that they both exist. Let's see what the other thinks about it.

**Comment by wesleycho** [comment]
We don't support them.

I sort of lean against this request, as it would add quite a bit of complexity. If we do tackle this, it won't be until after a breaking change to fix up the carousel api.

**Comment by wesleycho** [comment]
Thinking about this, going to close as won't support - if one wants to listen to the transition events, one should create a custom directive and bind to the events directly. This has performance ramifications and is an anti-pattern with angular.
