### ISSUE TITLE
Pagination ng-model doesn't change

### ISSUE THREAD

**Issue by mustafashujaie** [angular-ui/bootstrap#5370]
Hello, This is how I use pagination on my page:

    <uib-pagination total-items="bigTotalItems"
        ng-model="bigCurrentPage"
        max-size="maxSize"
        class="pagination-sm"
        boundary-link-numbers="true"
        ng-change="pageChanged()"
        items-per-page="itemsPerPage"
        rotate="false"></uib-pagination>

And javascript is:

    $scope.pageChanged = function() {
	   alert('Page changed to: ' + $scope.bigCurrentPage);
    };

    $scope.maxSize = 5;
    $scope.bigTotalItems = 6;
    $scope.bigCurrentPage = 1;
    $scope.itemsPerPage = 5;

But the page doesn't change and it is always `1`.  BTW I am using the latest version `1.1.1`. I have this problem with previous versions too.

**Comment by icfantv** [comment]
@mustafashujaie, please read and follow the project documentation for how to either receive help or report an issue.  If you think you've found a bug, we will need a minimally working plunked that shows the issue.  I'm on mobile at the moment so I can't look more closely.

**Comment by mustafashujaie** [comment]
It looks like a bug to me. Maybe something is missing in the documentation, since I read every bit of information about pagination component in the documentation. I om on the mobile too. I will creat a plunkr for it as soon as I reach to a computer. Thank you for your response

**Comment by RobJacobs** [comment]
Please see the 2nd section in the [FAQ](https://github.com/angular-ui/bootstrap/wiki/FAQ) wiki.  I suspect this is a prototypal inheritance issue.

**Comment by wesleycho** [comment]
The documentation and unit tests make clear that this works - this is highly likely a prototypal inheritance of $scopes issue. I recommend reading [Understanding Scopes](https://github.com/angular/angular.js/wiki/Understanding-Scopes) from the Angular.js wiki.

**Comment by icfantv** [comment]
@mustafashujaie, @RobJacobs point is a very good one.  You should never store primitives on $scope directly, rather store them in a "data" object.  Primitive values are copied (as opposed to being a live reference) to descendant scopes.  This means, if a value is changed on one scope, the other scopes won't see the change.

I'm going to close until you can get back to us.

**Comment by mustafashujaie** [comment]
@icfantv @RobJacobs @wesleycho Thank you all for your help. Yes It solved my problem. I changed it to this:

    $scope.pagination = {
         maxSize : 5,
         bigTotalItems: 6,
         bigCurrentPage: 1,
         itemsPerPage : 5
    };

I think this should be noted in the documentation. 
Thank you all.

**Comment by icfantv** [comment]
Excellent!  Glad it worked.  Btw, it is in the documentation in the FAQs.
