### ISSUE TITLE
No support for timezone in ng-model-options for timepicker

### ISSUE THREAD

**Issue by slepkaviba** [angular-ui/bootstrap#5372]
Hi,

I have tried to define the timezone for the timepicker and I see that unfortunatelly it doesn't work. As docs say it works for datepicker - would be very useful if timepickers could support it too.

Is there any plan to include it in the incoming versions?

Best regards,
S

**Comment by wesleycho** [comment]
I would strongly advise against using such a feature - this could create a very bad UX for the user where the user sees a time that is different than expected, especially closer to midnight.

What are your thoughts @Foxandxss ?

**Comment by slepkaviba** [comment]
But that's the main goal of that... Assume that user has wrong timezone in his computer and you ask him "when do you want your package to arrive in this totally different city?" he should be able to put the time and date from the other city. Knowing that if he puts 00:00 Dec 1st in destination, it will be this time. 

And btw. If you have this feature for dstepicker and not for timepicker that's the UX killer around midnight. So it seems like a consistent feature with what we have so far. 

S

**Comment by icfantv** [comment]
@slepkaviba, are you suggesting we have/provide a dropdown for the time zone?

**Comment by wesleycho** [comment]
Something like that can have major side-effects though if you use ng-model-options with the timezone for one and not the other, or if you use it for both and they have different values.

I am very wary of this, I can see this exploding into lots of bugs, and we're left with the maintenance burden.

The better route is to separate your datepicker and timepicker models and use a serializer/deserializer to wrap/unwrap a higher level model for such an edge case.

**Comment by Foxandxss** [comment]
I think that we shouldn't do timezone work in here. Timepicker is just to pick a time. We have two set of time related components:

* Datepicker: Select a date, for example 22 march 2016
* Timepicker: From the previous selected date, pick the concrete hour.

I believe that adjusting the timezone of that date should be done in userland.

**Comment by slepkaviba** [comment]
@wesleycho but now you can bind a timepicker to the same model as datepicker. Then if timezone is defined for datepicker it will be some kind of a woohoo for the time changes. 

And for the moment if I need I do all conversion manually on model updates to be in control of both date and time picking controllers and their timezones. But that requires as you say two models and work in userland. 

Just find allowing us to set timezone in one only element out of two can more complicate the life. As in this case I can select a date in any timezone and time on that date in my local (or rather currently set). So basically it's useless to have it in datepicker if I still must do manual work. That sounds totally not like predictable but I respect your opinion of finding this desired. Thank you for all responses.
