### ISSUE TITLE
Popover elements flickers in Firefox

### ISSUE THREAD

**Issue by shyamal890** [angular-ui/bootstrap#5377]
Elements in popover flickers in Firefox (only visible in large angular app). 

Here is an example [PLUNKER](http://plnkr.co/edit/hsGkwMF9fPE04SsdSB7p?p=preview) Try clicking on "Click me" in firefox and you will see the dom jumping.

**Note**: 
-  $interval function is there to stimulate a large application.
-  Tested with latest version of Angular, Angular UI Bootstrap and Bootstrap.
-  Problem visible in browser: Firefox (Tested only with Chrome and Firefox)
-  This does not happen with Angular UI dropdown.

**Comment by RobJacobs** [comment]
When using a templated popover, every time a digest cycle occurs, the position method is called at this [line](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L420).  This is to ensure the popover will position itself correctly when the content changes.

**Comment by shyamal890** [comment]
Ok, but lets say the content doesn't change is there a way to stop popover from re-positioning itself?

**Comment by icfantv** [comment]
@shyamal890 this smells like a design problem to me in that the size of the angular app is irrelevant.  rather, how skilled a developer is at managing watches and digest cycles within their application.  Angular recommends no more than 3 digest cycles occur for any trigger.

Also, I was unable to see the issue using your plunker.  In Firefox or otherwise.

**Comment by shyamal890** [comment]
@icfantv Try clicking on the select menu and let it stay open. It will start flickering.

**Comment by icfantv** [comment]
Got it.  Thanks.

@RobJacobs, do we know why the $watch being triggered when the select is opened?

**Comment by RobJacobs** [comment]
It was originally introduced under this [PR](https://github.com/angular-ui/bootstrap/pull/3435/files) by @chrisirhc.  @wesleycho and I tried to optimize it by only calling it at the end of the digest cycle under another PR (can't find it) but this is still a performance concern of mine.

**Comment by shyamal890** [comment]
Any updates on this issue?

**Comment by wesleycho** [comment]
If there are no additional comments, there is no update at this time. Please do not spam our notifications/inboxes with comments that add no value.

**Comment by wesleycho** [comment]
Closing as tracked by #5918.
