### ISSUE TITLE
Trigger typeahead even if a value is selected

### ISSUE THREAD

**Issue by shyamal890** [angular-ui/bootstrap#5380]
Is there a way to show typeahead even if ngModel is bound to a value?

Here is a [PLUNKER](http://plnkr.co/edit/FP8frHEfwm4vAq9gc2W0?p=preview) example

**Comment by icfantv** [comment]
@shyamal890, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

**Comment by shyamal890** [comment]
@icfantv I posted this question on [stackoverflow](http://stackoverflow.com/questions/35145914/angular-ui-how-to-trigger-typeahead-even-if-a-value-is-selected) haven't received any replies yet, would appreciate if you could help.
