### ISSUE TITLE
Navigation Bar for Fixed Top, when window is resized the content goes under the navigation bar 

### ISSUE THREAD

**Issue by SanjayGautam** [angular-ui/bootstrap#5381]
I am using navigation bar and I am using a TOP fixed class , when i resize my window the content goes under the navigation bar. 

example can be found here. 
http://plnkr.co/edit/jdvvkRRThUJQczLKYNmb?p=preview
![image](https://cloud.githubusercontent.com/assets/1543475/12733353/1eceb626-c8ef-11e5-9600-e6f56e7f3ada.png)

Thanks
Sanjay Gautam

**Comment by SanjayGautam** [comment]
when not using the fixed-top 

![image](https://cloud.githubusercontent.com/assets/1543475/12733430/aee2d918-c8ef-11e5-8eff-864088cf32f4.png)

**Comment by icfantv** [comment]
@SanjayGautam, please explain how this is an Angular UI Bootstrap issue.

Also, our demo page uses a fixed navbar up top with dropdowns - you might take a look at that to see what you are doing incorrectly.

**Comment by SanjayGautam** [comment]
See my assumption is that when i use element <nav></nav> and then I user a <div>  immediately after that like below 

<nav>
<div .... nav...header...>
</div
<div>
links goes here.  
<div>
</nav>
<div>XXX  My content XXXX<div>

my assumption is that the div with my content will always and should be visible and should not go under the navigation header, see I can add extra breaks but I dont want to do that , probably thats where i was wondering if automatically div after nav or anything after </nav is taken as content and bootstrap  should be able to position the content div appropriately 

Thanks
Sanjay Gautam

**Comment by SanjayGautam** [comment]
I did do the comparison between the how i am using I think I am not doing any mistake in terms of the usage. the plucker example is the best one to to prove that there is some issue. 

thanks
Sanjay Gautam

**Comment by icfantv** [comment]
@SanjayGautam, I'm sorry, but we are not going to debug your code for you unless you can show that this is an Angular UI Bootstrap issue.  Using a Bootstrap navbar with UIBS dropdowns is unbelievably common and the web is littered with examples (again, not to mention the one on our demo page).

If you require support, we ask that you please follow the instructions in our documentation for how to get help.  For your reference, [here are those instructions](https://github.com/angular-ui/bootstrap/blob/master/README.md#need-help).

As the issues forum is reserved for bugs, I'm going to close this until you follow the above instructions and can show that this is an Angular UI Bootstrap issue.

**Comment by SanjayGautam** [comment]
Surely Understand your perspective on that , I think i understood what you are trying to say, Let me do some more investigation into it to find out and make sure that it is Angular UI Bootstrap, I am totally new to Angular and hence I assumption might be wrong as well. Appreciate your time in looking into it though.  Sorry for any inconvenience. I like the community and the promptness of response though.
