### ISSUE TITLE
Carousel custom sliding buttons

### ISSUE THREAD

**Issue by vladab** [angular-ui/bootstrap#5386]
How can I add custom sliding buttons for carousel?

Example: http://plnkr.co/edit/kPNyTQcNRaBG6WaP15xt?p=preview

**Comment by wesleycho** [comment]
One can override the template with a custom provided template.

For more details, please ask in a more appropriate venue, as issues are not for help - please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md before filing an issue.
