### ISSUE TITLE
Accordion Collapse Issue

### ISSUE THREAD

**Issue by dlennon0** [angular-ui/bootstrap#5389]
Hi,
The accordion element is not collapsing after it is first collapsed.
I have a search form that I want to collapse after I click the search button, this works only on the first search. The is-open attribute appears to no longer works after the first collapse.
Anyone have an idea what the cause might be?

Plunker below.
http://plnkr.co/edit/xNBSSNSs1xv34FkpuZGf?p=preview

Thanks,
Dáire

**Comment by Foxandxss** [comment]
To avoid scope inheritance issues, use controllerAs.

http://plnkr.co/edit/kNkYdmEFdKNLGUlv0h1e?p=preview

Your behavior is flawed tho.

**Comment by dlennon0** [comment]
Sorry, could you clarify what you mean by "Your behavior is flawed tho"? 
Is my approach wrong or is it a bug?
Thanks,
Dáire

**Comment by Foxandxss** [comment]
It is wrong because it is closing the form with any kind of click so it is hard to use it.

**Comment by dlennon0** [comment]
Would you have any suggestions on the best way to implement it? I need to collapse an accordion by clicking a search button.
