### ISSUE TITLE
extra space next to the month selector

### ISSUE THREAD

**Issue by kevinlbatchelor** [angular-ui/bootstrap#5392]
In chrome, there is extra space on the left side of the right arrow, next to the month selector.

**Comment by icfantv** [comment]
I'm not seeing this on [our demo page](http://angular-ui.github.io/bootstrap/#/datepicker).  Can you post a screenshot along with your code snippet?

**Comment by kevinlbatchelor** [comment]
I'm just looking at your demo page, not my own code.

![space](https://cloud.githubusercontent.com/assets/5952444/12756291/60821062-c990-11e5-8f11-bcc785e41eb6.PNG)

**Comment by icfantv** [comment]
Oh.  On the left side of the right arrow _button_.  Thanks.

**Comment by icfantv** [comment]
@wesleycho, I think this is a browser bug.  Chrome is allocating an extra 2px to the `<th>` cell.  We have no styling here and there's nothing I can see that we can do.

**Comment by RobJacobs** [comment]
It's the pull-right class on the template [here](https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/month.html#L6)  Year, Month, and Day templates all have the pull-right class on the right button.

**Comment by wesleycho** [comment]
I think the fix for this should be
```css
.uib-datepicker .uib-right {
  width: 100%;
}
```

Would need to test across browsers though.

**Comment by icfantv** [comment]
That removes all the space entirely.  Is that what we want?

**Comment by agrahamlincoln** [comment]
```
table.uib-daypicker button.uib-right {
    width: 100%;
}
```
seems to fix it for all of the ocurrences

**Comment by icfantv** [comment]
It needs to be
```
.uib-datepicker .uib-right, .uib-datepicker .uib-left {
  width: 100%;
}
```

or the spacing on the left won't match.

**Comment by agrahamlincoln** [comment]
in that case, why not 
```css
.uib-left, .uib-right {
  width: 100%
}
```

Both CSS classes are only used in the template, I see no reason to complicate it

**Comment by wesleycho** [comment]
I think the concern is if we ever use those classes for another component. I'm not hugely opinionated on which in this case.
