### ISSUE TITLE
Unable to horizonatally center pagination

### ISSUE THREAD

**Issue by jsdevel** [angular-ui/bootstrap#5398]
Is there a way to center the pagination?  I'm currently unable to do so because of these hidden list items.

![unable-to-center](https://cloud.githubusercontent.com/assets/2605980/12767404/34baf300-c9c6-11e5-866d-83a87c1db686.png)

**Comment by icfantv** [comment]
This requires further investigation.  Just looking at just your screenshot, it looks like that's margin?

**Comment by jsdevel** [comment]
It's actually an `<li>` with width set to `0`.  UI Bootstrap has a lot of these that aren't completely removed from the DOM.

**Comment by jsdevel** [comment]
Sorry to bother you.  Turns out I actually had margin being set on them globally.  I hate global CSS for no reason!
