### ISSUE TITLE
uibModal is broken when using Angular 1.4.0 with Angular UI 1.1.1

### ISSUE THREAD

**Issue by davidfit** [angular-ui/bootstrap#5402]
When using Angular 1.4.0 with Angular UI 1.1.1, the uibModal is broken.
Angular 1.4.1 added feature $q: $q.resolve as an alias for $q.when and Angular UI use it in the new $uibResolve.
example: [https://plnkr.co/edit/Ibm6ahXiNaC5R1810YPl?p=preview](https://plnkr.co/edit/Ibm6ahXiNaC5R1810YPl?p=preview)

**Comment by wesleycho** [comment]
In truth, you should be using this library with 1.4.5 or higher (preferably 1.4.9) - this is due to ngAnimate bugs that were not resolved until that version.
