### ISSUE TITLE
Required modal.opening event

### ISSUE THREAD

**Issue by Shailu4u** [angular-ui/bootstrap#5403]
I want to execute some common functionality for all modals in an application when any modal opens.
We have model.closing event which is helpful when any model closes. Similar to model.closing, there should be model.opening event which will get triggered when any model opens.

**Comment by wesleycho** [comment]
There is the `modalInstance.opened` promise - is there a particular reason why this does not work?

**Comment by Shailu4u** [comment]
modalInstance.opened is working correctly. But my scenario is: Lets say i have 5 modalInstances, and i want to execute some common functionality for each of these 5 modals when modal opens. So writing modalInstance.opened promise for each of these five modals separately will duplicate the code. Its better to have one global promise which resolves when any modal opens in an application of 1000 modals.

**Comment by wesleycho** [comment]
At the cost of an extremely awkward API for a rarer use case, which encourages general anti-patterns.

I'm very much against an eventing pattern here without a strong reason, and I believe maintainers in the past also believe the same - modal events present in other modal/dialog libraries are extremely awkward to use and results in poor garbage collection techniques to compensate for their poor form.

**Comment by wesleycho** [comment]
Going to close this as something we won't support - having duplicate API for the same hook is not good, and encouraging a pattern that generally is no good is not what we want to do. In addition, this adds confusion, as well as negative performance implications due to how eventing on $scope works.
