### ISSUE TITLE
appendTo option not working for modal

### ISSUE THREAD

**Issue by dpkshrma** [angular-ui/bootstrap#5404]
Tried the following example from [docs](https://angular-ui.github.io/bootstrap/):

```javascript
$scope.items = ['item1', 'item2', 'item3'];

$scope.animationsEnabled = true;

$scope.open_modal = function (size) {
console.log(angular.element(document).find('aside').eq(0));
var modalInstance = $uibModal.open({
    animation: $scope.animationsEnabled,
    templateUrl: 'newSetModal.html',
    appendTo: angular.element(document).find('aside').eq(0),
    backdrop: false,
    controller: ['$scope', '$uibModalInstance', 'items', function($scope, $uibModalInstance, items) {
        $scope.items = items;
        $scope.selected = {
            item: $scope.items[0]
        };

        $scope.ok = function () {
            $uibModalInstance.close($scope.selected.item);
        };

        $scope.cancel = function () {
            $uibModalInstance.dismiss('cancel');
        };
    }],
    size: size,
    resolve: {
        items: function () {
            return $scope.items;
        }
    }
});

modalInstance.result.then(
    function (selectedItem) {
        $scope.selected = selectedItem;
    },
    function () {
        console.log('Modal dismissed at: ' + new Date());
    }
);
};
```
First, I tried it using with angular directive, it didn't work, so I thought maybe it works only with html elements. But, it isn't working with them either. Modal always appends to the body.

Everything else works perfectly fine. I have installed the latest version that was available **using bower(1.1.2)**

**Comment by wesleycho** [comment]
This works, as seen [here](http://plnkr.co/edit/RrkzJ2R1J5aZH5x6V3X9?p=preview) - this appears to be a usage issue.

**Comment by dpkshrma** [comment]
@wesleycho Thanks for quick reply. You're correct, indeed, modal html does get appended to the element. But, should the modal not be contained inside the `aside` element? The backdrop covers the entire body, and modal shows just the same way, had it not been appended to `aside`. This looks like a design issue to me.
