### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by ilcheivanovski** [angular-ui/bootstrap#5408]
Sorry,

**Comment by wesleycho** [comment]
Closing as not informative/actionable :)

**Comment by christopherthielen** [comment]
sorry

**Comment by HoltMansfield** [comment]
The comma is the best part

**Comment by icfantv** [comment]
@ilcheivanovski, might I suggest you get your thoughts down on paper or in a text editor first before attempting to tackle it on GitHub.  In the interim, please refrain from utilizing the issues forum on GitHub, and in particular OUR issues forum, until you feel you have a better grasp of the question you are attempting to ask and/or issue you may have.
