### ISSUE TITLE
Bug: uib-uncheckable not working on radio button directive

### ISSUE THREAD

**Issue by JAnderson1122** [angular-ui/bootstrap#5412]
I found this using your demo page: https://angular-ui.github.io/bootstrap/#/buttons

The right button in the right group is never rendered uncheckable.  

Examining/tracing through the code, I think I can explain why it is not working and suggest a solution.
Lines 45-49 of buttons.js are intended to remove the `uncheckable` attribute from the element if `uib-uncheckable` evaluates to false.  However, removing an attribute using `attrs.$set(uncheckable, null) does not seem to work.  It looks like the angular function `$set()` leaves the attribute key/value of `uncheckable="uncheckable"` on the `attrs` object.  In line 37, a check is made to see if `uncheckable` is present using `angular.isDefined(attrs.uncheckable)`.  This seems to always returns true because `uncheckable="uncheckable"` evaluates to `uncheckable=null`.

You might need to remove the attribute from the element directly using `removeAttribute()` instead of using the angular function `$set()`.

Let me know how I can help.

**Comment by wesleycho** [comment]
This does look like a bug - if you want to file a PR fixing this, it'd be welcome. Just let me know if you want to work on a fix - if not, I can take a deeper dive into it.

**Comment by JAnderson1122** [comment]
I can work on a fix over the weekend.  I will update by Monday AM.

**Comment by rasenplanscher** [comment]
Ran into this today, see my pull request for a fix ;)
