### ISSUE TITLE
Release 1.1.2 - Problem when passing date

### ISSUE THREAD

**Issue by immortalcy** [angular-ui/bootstrap#5416]
I tried to see the commits and figure out what is wrong with the latest commit that brakes the datepicker control when we load the date from the database.

Here is a [JSBin](https://jsbin.com/qucuzo/edit?html,js,console,output) showing the problem in angular-formly. If you got to the HTML tap and change the version to 1.1.1 you will notice that the problem does NOT appear - even though a warning is shown the control is working properly.

**Comment by icfantv** [comment]
@immortalcy, please extend us the courtesy of searching both open and closed issues as well as reading the documentation before entering issues.  The model must be a JavaScript `Date` object.

There were several regressions that accidentally allowed strings, but this restriction was originally made way back in 0.13.4 or thereabouts.

**Comment by immortalcy** [comment]
Thanks for the headsup and sorry for not searching the closed issues. Justi n case someone else comes up with this here is the working formly tempalte code:

`formlyConfig.setType({
      name: 'datepicker',
      templateUrl: 'datepicker.html',
      wrapper: ['bootstrapLabel', 'bootstrapHasError'],
      defaultOptions: {
        ngModelAttrs: ngModelAttrs,
        templateOptions: {
          datePickerOptions: {

          }
        }
      },
      link: function(scope){
        var model = scope.model[scope.options.key];
        if (model === void 0) return;
        var isDate = (model instanceof Date);
        if(!isDate)
          scope.model[scope.options.key] = new Date(model);
      },
      controller: ['$scope', function ($scope) {
        $scope.datepicker = {};

        $scope.datepicker.opened = false;

        $scope.datepicker.open = function ($event) {
          $scope.datepicker.opened = true;
        };
      }]
    });`
