### ISSUE TITLE
init datepicker without model value bug

### ISSUE THREAD

**Issue by trickpattyFH20** [angular-ui/bootstrap#5417]
If a popup datepicker is initialized without a model value, everything functions as expected.

If an inline datepicker is initialzed without a model value, the datepicker does not display anything (only the arrows are shown)

http://plnkr.co/edit/13h4rpa2b3xUbSXxnuMO?p=preview
comment on line 4 of example.js in the UIB datepicker example plunkr reproduces the bug

**Comment by wesleycho** [comment]
This is already fixed in `master` via 4b2ee0fa85e309437a137d7f9e2ab90fbd186ecf

**Comment by trickpattyFH20** [comment]
@wesleycho  I don't think it is actually, this seems like a different issue.

I built the latest version from the master branch and updated it in the plunkr.
http://plnkr.co/edit/13h4rpa2b3xUbSXxnuMO?p=preview

This seems to be a different issue and actually is a regression and now affects both inline AND popup datepickers in the current master branch.

**Comment by wesleycho** [comment]
The fix is unreleased, and will be in 1.2.0

**Comment by trickpattyFH20** [comment]
@wesleycho .... I downloaded the master zip and built it myself and included that file as the UIB source in that plunkr...

**Comment by icfantv** [comment]
@trickpattyFH20, sure looks like you're including 1.1.2 in your `<head>` rather than the SNAPSHOT build as a separate file.

**Comment by trickpattyFH20** [comment]
ui-bootstrap-tpls-1.2.0-SNAPSHOT.min.js was the name of the file that was build... I can rename it to that in the plunkr if you'd like @wesleycho

**Comment by icfantv** [comment]
the plunker you had before was not correct, hence my comment.  it had only the HTML file and the example.js file.  you must have forgotten to save it.

**Comment by trickpattyFH20** [comment]
ah... yes probably didn't save the plunkr. @icfantv 
unless I am mistaken in some other aspect, I still see the bug I mentioned earlier.

**Comment by icfantv** [comment]
Agreed.  Even if you set `$scope.dt = null` or `$scope.dt = undefined` the error is present.  Could you please replace the SNAPSHOT contents with the uncompressed version?  It helps us debug and test potential fixes.  Thanks.

**Comment by icfantv** [comment]
@wesleycho, unless I'm missing something obvious, it sure looks like this is still an issue.

**Comment by icfantv** [comment]
Wait a second.  You're getting errors in your console.  This is not an issue.

**Comment by icfantv** [comment]
Check/fix the errors and we'll go from there.

**Comment by trickpattyFH20** [comment]
@icfantv 
- switched to unminified SNAPSHOT
- the console errors come from line 2187 of ui-bootstrap-tpls-1.2.0-SNAPSHOT.js
looks like we still see the bug when the datepicker is not initialized with a date

**Comment by trickpattyFH20** [comment]
@icfantv 
builld process + karma unit tests are failing for my local build and for the travis build on this pr because of an error form another component...

looks like the same error happened in @wesleycho 's latest build as well https://travis-ci.org/angular-ui/bootstrap/builds/107235596

any idea what the error is and how to resolve/merge the fix into this pr?
