### ISSUE TITLE
error when requiring individual components

### ISSUE THREAD

**Issue by httpete-ire** [angular-ui/bootstrap#5420]
I'm using webpack and following the README guidelines when I require an individual component (see below),  webpack throws this error `Module not found: Error: Cannot resolve module 'angular-ui-bootstrap/src/COMPONENT_NAME'` for every component I require.

```
var app = angular.module('dochub', [
  'ui.router',
  'ui.codemirror',
  'relativeDate',
  'ngMessages',
  'as.sortable',
  require('angular-ui-bootstrap/src/modal'),
  require('angular-ui-bootstrap/src/debounce'),
  require('angular-ui-bootstrap/src/alert'),
  require('angular-ui-bootstrap/src/dropdown')
])
```

Any idea whats going on?

**Comment by wesleycho** [comment]
Are you consuming directly from `master`? The recent changes are for the upcoming 1.2 release.

**Comment by httpete-ire** [comment]
That would explain it. I used NPM to install the library (v1.1.2)

The Webpack section in the readme is a little misleading as it suggests requiring individual components is available in the current version (no mention of v1.2)

**Comment by wesleycho** [comment]
Sorry about that, we're trying to get ahead for the 1.2 release - we're likely to release in the next week or two, but once that is ready, consuming individual modules using CommonJS & npm will be nice and easy as demonstrated.

**Comment by Rahees148** [comment]
I m having same issue, can you please suggest the workaround.
