### ISSUE TITLE
FEATURE REQUEST: Anchoring Modal to Element

### ISSUE THREAD

**Issue by SwagUX** [angular-ui/bootstrap#5422]
It would be really awesome to have the feature where when the modal is invoked the origin of the click is captured in coordinates, and then passed to the modal with a 1ms timer and erased so that we can animate the modal into its final resting place from where it was invoked; like how Angular Material Dialogs are done.

**Example**
https://material.angularjs.org/latest/demo/dialog

Controlling the flow of animations is a huge thing.

**Example to Modal Instance:**
`anchorElement: $event ? angular.element($event.target) : undefined,`

**Comment by wesleycho** [comment]
One can create custom animations using module.animation and ngAnimate. Other than that, that is the maximum support we would offer.

**Comment by welcomeToGotham** [comment]
This doesn't really do the same thing using animations. You can't anchor an animation. He is referring to having the modal generate from the source of where it was initialized; a lot like how Materialize and Angular Material dialogs work.
