### ISSUE TITLE
Delay can't handle quick is-open change

### ISSUE THREAD

**Issue by jamesclark92** [angular-ui/bootstrap#5431]
When using popover-delay if there is a is-open change in the delay time the popover will stay open, even if the is-open attribute evaluates to false. 

See this working plunker: http://plnkr.co/edit/3Y27cDT8eUXLX24RydRp?p=preview

**Comment by wesleycho** [comment]
I don't even see a popover working here, even if I change it to popover-is-open="true" - please slim down the Plunker to a minimal state.

**Comment by jamesclark92** [comment]
Sorry, I had placed the popover to the right and was being shown outside on the page. I have now moved the popover to the bottom and this should work.

**Comment by wesleycho** [comment]
Problem here looks like your delay - see [here](http://plnkr.co/edit/SinX8XbrTXltCuTWRpjv?p=preview)
