### ISSUE TITLE
Support Angular 1.5

### ISSUE THREAD

**Issue by alippai** [angular-ui/bootstrap#5436]
Angular 1.5 is now stable, we should test against it. If it already works, we should indicate it in the readme.

**Comment by icfantv** [comment]
Please exercise some patience.  There were some issues in the library exposed by the 1.5 release and some of them have been fixed `master`.  Additionally, we took the opportunity to address some API design issues and it needs to bake a little longer before we either issue a release or make such a statement.

**Comment by alippai** [comment]
Sure. The linked issue is perfect, thank you!

**Comment by bartvanderwal** [comment]
I just installed angular-ui via Bower:
> bower install angular-bootstrap

And I had Angular 1.5 installed in `bower_components`. Since I wanted to build a component directive I was glad. But reading this issue I'm a bit confused, and hope that everything works.

Ah wait, I see it WAS updated to 1.5 per #5437.
