### ISSUE TITLE
'Join' error on datepicker

### ISSUE THREAD

**Issue by natcohen** [angular-ui/bootstrap#5439]
I just upgraded from 0.14 to 1.1.2. I get the following error "Cannot read property 'join' of undefined".

In fact when I go to line 910 of the complete tpls (non minified) file, I see the following:

`regex: $locale.DATETIME_FORMATS.ERANAMES.join('|').replace(/\s/g, '\\s'),`

But when I print `$locale.DATETIME_FORMATS`, there is no ERANAMES or ERAS in this object.

Where am I supposed to get ERANAMES and ERAS from?

BTW I'm using bootstrap 3.3.6 and angularjs 1.4.9

**Comment by icfantv** [comment]
@natcohen, please be advised that the issues forum is reserved for bugs and if you believe you've found one we ask that you please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

That said, please create a minimally working plunker that reproduces the issue and we will see what we can do.  Thanks.

**Comment by RobJacobs** [comment]
Those constants are part of the core angular library, $locale service.

**Comment by natcohen** [comment]
@RobJacobs Thanks! I thought it was a bug but I had an old version of $local... might be useful to mention with which version it was tested!

**Comment by Neustren** [comment]
In my case, i was using angular-locale en-us, same name module , I uninstalled it and downloaded the angular-i18n and everything worked

**Comment by primehero** [comment]
So guys you just have to add a reference or do you need to inject it as a dependency too?

**Comment by Sergevia** [comment]
So, I don't really understood, what to do if we have that error? should we update AngularJs or what?
