### ISSUE TITLE
Datpicker Popup next month prematurely updates date model value

### ISSUE THREAD

**Issue by mosleywm** [angular-ui/bootstrap#5441]
This repros on the demo site http://angular-ui.github.io/bootstrap/#/datepicker v1.1.0 and higher.

Opening the datepicker popup and browsing the months without actually selecting a date updates the date model (see "Selected Date is:" change) .  Click outside of the popup to close it and notice the Date model has been updated but the input still reflects the initial value.

After a date has been selected through the popup, browsing the months does not update the Date model (expected behavior).

**Comment by ian505c5** [comment]
I am seeing this as well, is this by design?

**Comment by icfantv** [comment]
At first glance, this looks like a bug.

**Comment by wesleycho** [comment]
This is definitely a bug, we need to fix this.

**Comment by ribizli** [comment]
Any workaround until the fix? I have a $watcher on the date, which is triggered (due to this bug) even if the user hasn't selected a date.

**Comment by wesleycho** [comment]
The culprit is 2cb3bc2e762ef0f2dbc2a4152ecccc2f9937618d - this commit must have exposed a bug that was hidden by the gc issue.
