### ISSUE TITLE
Tooltips not clearing hover state Safari (OSX)

### ISSUE THREAD

**Issue by red2678** [angular-ui/bootstrap#5445]
- Angular version 1.4.9
- UIBS version 1.1.2

The issue is when you hover over an element with a tooltip and then move your mouse to hover over another element, that is positioned closely above the first, that also has a tooltip; the directive does not clear the hover state from the originally hovered element. 

Plunker: http://plnkr.co/edit/BPWlKzeuessskaMJTf3s?p=preview

At the time of writing this, **it is only happening in Safari. 9.x (OSX 10.11.2)**

_Repo Steps:_
Starting from the bottom of the lists in the plunker, move your mouse up and down them, over the "action" links. Notice that the background sometimes does not change to the correct color.

**Comment by wesleycho** [comment]
I'm not seeing this on 9.0.3...what version is your Safari? My OS X is 10.11.3.

**Comment by deeg** [comment]
I see this with Safari 8.0.0 (I should probably update!) and OSX 10.10.5 (again I should update).

Just wanted to post the info.

![screen shot 2016-02-24 at 2 03 31 pm](https://cloud.githubusercontent.com/assets/2857769/13302600/9169dd6a-daff-11e5-9ecb-ce7026439978.png)

**Comment by red2678** [comment]
I am using 9.0.3 on OS 10.11.3. I can make a screencast if needed.

**Comment by RobJacobs** [comment]
Can you try this with a tooltip-popup-delay="250"?  The default is 0 and can be overridden $uibTooltipProvider.  We may want to consider setting the default to something higher than 0.

**Comment by wesleycho** [comment]
I think I misunderstood the original issue when I first looked at this - this is certainly a bug, but a very strange one.

**Comment by wesleycho** [comment]
I'm not sure how much we can do about this - this looks like a bug in Safari itself.

**Comment by red2678** [comment]
@wesleycho yeah. I did try changing the tooltip-popup-delay to no avail. I am sorry, I forgot to post the results here (that was quite some time ago).

**Comment by wesleycho** [comment]
Not a problem - unfortunately, I don't think there is anything we can do, as this looks like it is browser specific in a way that has no easy resolution.

I think the best we can do is to add a note in the `Known Issues` section of the documentation for the tooltip.
