### ISSUE TITLE
pagination control accessibility, skip disabled buttons

### ISSUE THREAD

**Issue by hbostic** [angular-ui/bootstrap#5448]
When tabbing through the pagination controls, first page for instance, the previous and go to first buttons are correctly disabled, however, their tabindex is not set and thus allowing them to be tabbed in their disabled state.  Is this by design?

**Comment by icfantv** [comment]
Closing as duplicate of #5151.

**Comment by chvenkat668** [comment]
Hi. I am also facing same kind of issue, can you help me, how you resolved this accessibility issue in ui-bootstrap1.1.1
