### ISSUE TITLE
ng-class no longer works with uib-accordion

### ISSUE THREAD

**Issue by jgogstad** [angular-ui/bootstrap#5449]
Before `panel-class` was introduced we could use `ng-class` to dynamically assign classes to accordions. That's no longer possible.

    <uib-accordion>
        <uib-accordion-group ng-class="{my_class: expression > 0}">

gets compiled to

    <uib-accordion><div class="panel-group" ng-transclude="">
        <div class="panel ng-isolate-scope" ng-class="{my_class: expression > 0} panelClass || 'panel-default'">

which is not valid syntax for `ng-class`

**Comment by jgogstad** [comment]
Puttin a binding inside `panel-class` doesn't work either. I.e. `<uib-accordion-group panel-class="{{ expression > 0 ? 'my_class' : '' }} panel-default">`. Once `my_class` is added, it will not be removed again.

**Comment by wesleycho** [comment]
Please read the Known Issues section on the accordion documentation: https://angular-ui.github.io/bootstrap/#/accordion
