### ISSUE TITLE
Datepicker (ui.bootstrap.datepicker) with ng-model-options updateOn blur

### ISSUE THREAD

**Issue by ph6** [angular-ui/bootstrap#5452]
(ui-bootstrap-tpls-1.1.2) The date from the popup won't be set if there is a updateOn blur option on the input field.
See the second datepicker under "Popup":
http://plnkr.co/edit/T04GySThXnW6TdQbH6oV

**Comment by wesleycho** [comment]
Closing as duplicate of #4837
