### ISSUE TITLE
.bower.json is missing main attribute

### ISSUE THREAD

**Issue by Chrisbright10** [angular-ui/bootstrap#5454]
upon installing this with bower the .bower.json file is missing the "main" attribute. I have included the attibute in the text below. This needs to be added for wiredep to pick up the dependency correctly.
 ```
{
  "name": "ui.bootstrap",
  "homepage": "https://github.com/angular-ui/bootstrap",
  "main": [
    "index.js"
  ],
  "version": "1.1.2",
  "_release": "1.1.2",
  "_resolution": {
    "type": "version",
    "tag": "1.1.2",
    "commit": "d4a68e57b266abadd97a13eb1c420cc80e562ba0"
  },
  "_source": "git://github.com/angular-ui/bootstrap.git",
  "_target": "^1.1.2",
  "_originalSource": "ui.bootstrap"
}
```

**Comment by icfantv** [comment]
Good catch.  I've caught this on other projects.  Can you confirm this is the only necessary change?  I vaguely recall having to make two mods to another project to get it working, but don't recall if it was a bower file.

If it works, please feel free to open a PR and reference this issue in the commit message.

**Comment by wesleycho** [comment]
`index.js` is for when one is using CommonJS/ES6/TS - for bower, it should probably point to `ui-bootstrap-tpls.js`...although one should probably be using npm.

**Comment by wesleycho** [comment]
Wait, it is [present](https://github.com/angular-ui/bootstrap-bower/blob/master/bower.json) - sounds like something else is going on here.

**Comment by icfantv** [comment]
@wesleycho, where is our bower.json file?

**Comment by wesleycho** [comment]
I just linked it

**Comment by icfantv** [comment]
Ahhhh, different project.  Thanks.

**Comment by Foxandxss** [comment]
FWIW I would remove bower support :P

**Comment by wesleycho** [comment]
I think this is referring to the wrong bower package - the one we maintain is `angular-bootstrap`
