### ISSUE TITLE
uib-tab + ng-repeat + fn || defer == very nasty results

### ISSUE THREAD

**Issue by vltr** [angular-ui/bootstrap#5455]
Hi! Sorry, I couldn't find a better way of giving this problem a title. Well, since I use `'SomeCtrl as ctrl'` to my definitions and almost everything (in the system I'm currently working) comes from an asynchronous backend, I tend to use functions to return promises that can be later used. So, I ended up using `uib-tabset` with the `uib-tab` element using `ng-repeat` for a given **function**. If returning a promise, everything goes dark and I have to kill the tab (or the browser). If I return an array from the function, it calls `$digest` 10 times and breaks (at least it doesn't kill my tab). If I create a simple array, everything works as expected.

* Angular versions 1.4.8 and 1.5.0 (plunkr using 1.4.8);
* UI Bootstrap 1.1.2;
* Plnkr: http://plnkr.co/edit/f7dVCScn6DZWnKpyrnu6

**NOTE:** In this plunker, I have commented out (in the HTML and JS) the bug, so no one will get its browser dead (in the worst scenario). Just, feel free to modify and call a function inside ng-repeat.

### Resuming:

* `<uib-tab ng-repeat="tab in ctrl.getTabs()" heading="{{tab.title}}" active="tab.active" disabled="tab.disabled">` breaks if my controller returns an array;
* `<uib-tab ng-repeat="tab in ctrl.getTabs()" heading="{{tab.title}}" active="tab.active" disabled="tab.disabled">` goes nuts if my controller returns a promise; and
* ` <uib-tab ng-repeat="tab in ctrl.myTabs" heading="{{tab.title}}" active="tab.active" disabled="tab.disabled">` works great.

Thanks a lot! :)

**Comment by wesleycho** [comment]
It should be noted that the tab component has changed significantly in `master` for the upcoming 1.2.0 release, so I'm not sure if this is necessarily an issue.

**Comment by wesleycho** [comment]
Also one should never use a function with ng-repeat. That is a big nono.

**Comment by vltr** [comment]
Hmm, I just made a workaround. But OK, I didn't knew that functions and ng-repeat are not a good couple. Can you just tell me why, so I can make things "right" ?

**Comment by icfantv** [comment]
@vltr, I fully respect the asynchronous nature of your application, but I'm afraid this just isn't a use-case that we are going to be able to support.  Adding the support of promises to the API would be a huge undertaking and open a massive can of worms for us maintenance-wise, e.g., where would we stop with the support in the rest of the API?  Remember that we're all volunteers doing this in our spare time.

**Comment by wesleycho** [comment]
Take a look at the [ngRepeat documentation](https://docs.angularjs.org/api/ng/directive/ngRepeat) - note the section talking about $watchCollection.

Going to close this as a usage issue.

**Comment by vltr** [comment]
@icfantv thanks for your feedback. I fully respect your work and mean no trouble. I was just trying to help :)

@wesleycho thanks also! I just read the mentioned section, it does makes sense. I'll go with what's working ;)

Best regards!
