### ISSUE TITLE
One time bindings in pagination template prevents switching language on the fly

### ISSUE THREAD

**Issue by Ludevik** [angular-ui/bootstrap#5460]
Hello,

this problem is similar to #4692. In this case the pagination template contains one time bindings for displayed texts and that prevents to change language for this component.

**Comment by GEETAMAMUNI** [comment]
Me too

**Comment by wesleycho** [comment]
One can use a custom template to get around that.

**Comment by Ludevik** [comment]
Yes, we are currently doing that, but it's pitty that one has to use custom template only to disable one time bindings.

**Comment by wesleycho** [comment]
IMO this is a better situation than the other way around, causing the default behavior to be unperformant for little reason.

Going to close this as a support ticket.
