### ISSUE TITLE
Patches to 0.12.x?

### ISSUE THREAD

**Issue by danielneri** [angular-ui/bootstrap#5465]
Any chance we can submit PRs to older versions like 0.12? We're stuck on 0.12 now, and really need a feature that was submitted into master recently: 
https://github.com/angular-ui/bootstrap/issues/4954

I've completed the backport and would like to submit a PR: https://github.com/accesso/bootstrap/commit/0367b68d7e0c24f56b06850697cbf812adeab386

**Comment by icfantv** [comment]
@danielneri, hello there!  while we do appreciate (and love) community involvement, we don't intend on issuing patch releases for old versions - especially one so old as 0.12.  please accept our apologies and we do hope you're able to upgrade to 1.1.2 soon.

**Comment by icfantv** [comment]
I should say, that barring your ability to upgrade, forking our repo is probably your next, best bet.
