### ISSUE TITLE
TimePicker and Iphone 6 not updating Time

### ISSUE THREAD

**Issue by Senske** [angular-ui/bootstrap#5466]
Hi, I've been using TimePicker for about a year now and it works fine on Android. I use momentjs to update the format properly. However, when I try to use it on the Iphone, it does not update and shows the current time. I even try to pull the time from the database to try and update it and I can see that the timestamps were recorded, it just won't update the TimePicker with those times from the model. Here's what I have.

TimePicker 
`<div class="row nopadding">
                <div class="col-xs-6 roundcorners bdivblue">
                    <div class="row nopadding">
                        <pre class="alert alert-info text-center"><strong>IN</strong></pre>
                    </div>        
                    <div class="row nopadding">
                        <div><timepicker class="timepick-input" data-ng-model="vm.TimeIn" hour-step="vm.hstep" minute-step="vm.mstep" show-meridian="false"></timepicker></div>                    
                    </div>                                
                </div>
                <div class="col-xs-6 roundcorners bdivblue">
                    <div class="row nopadding">
                        <pre class="alert alert-info text-center"><strong>OUT</strong></pre>                        
                    </div>
                    <div class="row nopadding">
                        <div class="col-xs-6"><timepicker class="timepick-input" data-ng-model="vm.TimeOut" hour-step="vm.hstep2" minute-step="vm.mstep2" show-meridian="false"></timepicker></div>
                    </div>
                </div>`

controller
`function getCompletedJobDisplay() {
            //Grab Data from database	to display    
            return datacontext.getCompletedJobDisplay(vm.employeelogin, $routeParams.ServiceID).then(function (result) {
                // I see datetimes being returned same as android in this alert
		alert('TimeIn:' + result.TimeIn + 'TimeOut:' + result.TimeOut);
        if (result.TimeOut && result.TimeIn)
		{ 
			vm.actualTimeOut = result.TimeOut;
			vm.Servicenum = result.Servicenum;
			vm.AccountKey = result.AccountKey;
			vm.Measurement = result.Measurement;
			vm.MeasurementUnit = result.MeasurementUnit;
			vm.SaleAmount = result.SaleAmount;
			vm.ServiceDesc = result.ServiceDesc;
			vm.TimeIn = result.TimeIn;
			vm.TimeOut = result.TimeOut;
						
			if (($rootScope.WeatherZip == result.ServiceZip)) {			    
			    vm.WindVelocity = $rootScope.WeatherWindSpeed|0;
			    vm.WindDirection = $rootScope.WeatherWindDir;
			    vm.Temperature = $rootScope.WeatherTemp|0;
			} else {
			    //set new WeatherData
			    setWeather(result.ServiceZip);
			}
		    }		
                return;
            },
               function (reject) {
                    return alert(reject);
        });
        }`

`        function getCurrentTimeStamp() {                       
	    var datetimestamp = moment().format("YYYY-MM-DD HH:mm:ss");
 	    $('#date').append(datetimestamp);
        }`

**Comment by icfantv** [comment]
@Senske, this smells an awful lot like a support issue and we ask that you please follow our project documentation on how to receive help.  Said documentation also contains instructions on how to properly submit a bug.  Until then, I'm going to close this but will happily reopen if appropriate instructions are followed and we deem it to be a bug.  Thanks.

**Comment by Senske** [comment]
I’m confused. I went to the docs page and clicked on issue. Then New issue. I don’t see any other “proper way”

Thanks and God Bless,

J Zarate | Software Developer
Senske Services | 400 North Quay | Kennewick, WA | 99336
Direct:  509-374-5013 | Fax:  509-374-5002

“Mark 11:23<https://www.biblegateway.com/passage/?search=Mark+11%3A23&version=ESV> Truly, I say to you, whoever says to this mountain, ‘Be taken up and thrown into the sea,’ and does not doubt in his heart, but believes that what he says will come to pass, it will be done for him.”

Senske Lawn & Tree Care | Senske Pest Control | Christmas Decor by Senske
www.senske.com<http://www.senske.com/>

Refer a Friend and receive $25 OFF your next service!   Learn More...<http://www.senske.com/about/referral-program/>
þ Please consider the environment before printing this e-mail.  This email was sent using recycled electrons. `
"CONFIDENTIALITY NOTICE: This e-mail message, including all attachments, contains information from Senske Services, Senske Lawn & Tree Care, Senske Pest Control, and Christmas Decor by Senske and  is for the sole use of the intended recipient's and may contain confidential and privileged information. If you are not the intended recipient, you may not use, disclose, copy, or disseminate this information. Please contact the sender by e-mail immediately and destroy all copies of the original message including all attachments. Your cooperation is greatly appreciated."

**Comment by icfantv** [comment]
@Senske, in general, it's not a good idea to reply to GitHub emails, especially from a work account -  any information you have in your signature (and anything your company may add via it's email servers) gets appended.  I've removed it from your past post.

[Here are the instructions](https://github.com/angular-ui/bootstrap#need-help) for getting help and [here are the instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug) on how to file a bug.

Additionally, it's a good idea to read a project's README and CONTRIBUTING guide prior to contacting the OSS team.  The OSS developers will greatly appreciate it.
