### ISSUE TITLE
$onInit hook from Angular 1.5.0 will not fire for ModalInstance controller

### ISSUE THREAD

**Issue by radek-anuszewski** [angular-ui/bootstrap#5472]
Of course I have in mind that, at this moment, Angular 1.5.0 is not officially supported:
> AngularJS (requires AngularJS 1.4.x, tested with 1.4.9)

But have I decided anyway to submit an issue about new `$onInit` hook problem. The problem is that it will not fire for modal instance controller (specified with `controller` and `controllerAs` options for `open` method). Here is plunker forked from your demo pego which shows an issue: [$onInit will not fire for modal instance controller](http://plnkr.co/edit/0kccyc2Qh6OLXHxfiJQl?p=preview). Some content has been removed, Angular CDN have been updated to use 1.5.0 version and controllerAs syntax has been used.

Update:
Of course problem does not exists with current supported Angular version (1.4.9), because hook is available in 1.5.0 version

**Comment by icfantv** [comment]
@radek-anuszewski are you saying that it IS working for 1.4.9?  Thanks.

**Comment by Foxandxss** [comment]
No

**Comment by Foxandxss** [comment]
I didn't know about this feature so we will take a peek

**Comment by radek-anuszewski** [comment]
@icfantv No, it's not working for 1.4.9

**Comment by wesleycho** [comment]
Looks like we have to implement this manually since we copied over the API for bindToController.

This would be an easy PR if you want to try tackling it quickly. Otherwise, one of us could probably implement it.
