### ISSUE TITLE
How to change uibTooltip to appendToBody by default?

### ISSUE THREAD

**Issue by pgrm** [angular-ui/bootstrap#5473]
I'm in the process of updating from angular-bootstrap 0.14.3 to the latest version, 1.1.2. So far my code looked like this:

 ````
myModule.config(['$tooltipProvider', function ($tooltipProvider) { 
    $tooltipProvider.options({ appendToBody: true }); 
}]); 
````

now, `$tooltipProvider` was replaced with `$uibTooltip` so I tried the pragmatic approach and just replaced them, resulting in:

 ````
myModule.config(['$uibTooltip', function ($uibTooltip) { 
    $uibTooltip.options({ appendToBody: true }); 
}]); 
````

However, that resulted in the following error:

> Uncaught Error: [$injector:modulerr] Failed to instantiate module myModule due to:
Error: [$injector:unpr] Unknown provider: $uibTooltip

I tried setting a breakpoint into [tooltip.js#L14](https://github.com/angular-ui/bootstrap/blob/48c9cd8f5183239219ccda7e4f7fbadde24bc57b/src/tooltip/tooltip.js#L14) and it got hit as expected, yet I was still seeing the same error message. Changing `myModule.config` to `myModule.run` would work, however I can't set the options anymore.

I ran the following code in the developer tools console, while a breakpoint washit in a different config method:

````
JSON.stringify(
    angular.module('ui.bootstrap.tooltip')._invokeQueue.filter(function(params) { 
        return params[2][0] === '$uibTooltip'; }));
````

and got the expected response:

    "[["$provide","provider",{"0":"$uibTooltip"}]]"

Am I missing something, or why am I getting that error?

thx

**Comment by pgrm** [comment]
ok, again something new learned - for anyone finding this later - the correct name is not `$uibTooltip` but `$uibTooltipProvider`

**Comment by icfantv** [comment]
@pgrm not only is this in [our documentation](http://angular-ui.github.io/bootstrap/#/tooltip), but it is in the CHANGELOG.  We appreciate you closing your issue but ask that in the future, you please extend us the courtesy of going over both before entering an issue.  Additionally, the issues forum is reserved for bugs and not support.  This is also documented in our project info.

**Comment by iwllyu** [comment]
I had the same issue. There's no mention of "$uibTooltipProvider" in the changelog, btw.
