### ISSUE TITLE
Question: extend link function

### ISSUE THREAD

**Issue by havenchyk** [angular-ui/bootstrap#5479]
Hi, I'm sorry for asking this here. I'm looking for a way to extend a little bit the `uib-tooltip` directive, in details I'd like to show it only for items with ellipsis.

It's pretty much simple to implement with patching the link function in the `$uibTooltip`, but I'd like not to modify it and just to extend.

So, there are ways:
- `provider.decorator -> $delegate` - i think it's not an option, I need to modify the link and haven't idea how to do it with decorate.
- wrapper for `uib-tooltip`, but I can't find the way to get options in the link of my wrapper.

Is there any ideas? I've checked a lot of answers on SO and issues and haven't found the answer.
Thanks in advance!

**Comment by icfantv** [comment]
@havenchyk, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

**Comment by havenchyk** [comment]
Sure, I have already apologized, but thanks anyway.
