### ISSUE TITLE
Setting show-hint on a required uibTypeAhead will show trigger a constraint message

### ISSUE THREAD

**Issue by Tom-V** [angular-ui/bootstrap#5481]
Setting both the `required `and the `show-hint`  attribute on a uibTypeAhead element will trigger the required constraint message on the "hidden" hint input element

Tested with google chrome and the latest version of angular-ui-bootstrap
[Plunkr](http://plnkr.co/edit/fybny55hcgeWmdBAjY70?p=preview)

**Comment by wesleycho** [comment]
Not sure what we can do about this - to work around this, I recommend using the `novalidate` attribute, as demonstrated [here](http://plnkr.co/edit/ejLSDOmsxW06uHVXqYi7?p=preview). In general, it is recommended to disable HTML5 form validation in favor of Angular's.
