### ISSUE TITLE
Modal rendered promise is not working

### ISSUE THREAD

**Issue by k-zakhariy** [angular-ui/bootstrap#5482]
If i pass to modal next settings, especialy 'windowTemplateUrl' and then when i try to use promise 'rendered' from modal instance , promise always has state 'pending' ,
But if i remove windowTemplateUrl - all works perfectly, It's a bug or feature ?
``var modalSettings = {
                            scope: $scope,
                            windowClass: 'feed-modal',
                            windowTemplateUrl: 'templates/modal_template.html',
                            templateUrl: 'templates/modal.html',
                            size: 'lg',
                        };
var modal = $modal.open(modalSettings);
modal.rendered.then(function(){
// Here not working, always pending
});
``

**Comment by k-zakhariy** [comment]
So i found next:

Don't works:
`<div tabindex="-1" role="dialog" class="modal" ng-style="{'z-index': 1050 + index*10}" ng-click="close($event)"  uib-modal-transclude></div>`
Works fine:
`<div tabindex="-1" role="dialog" class="modal" ng-style="{'z-index': 1050 + index*10}" ng-click="close($event)"  modal-transclude></div>`

**Comment by wesleycho** [comment]
This is fixed in 42fb48673581a4a533de4c0b392fda3873b3dfcf, will be in 1.2

**Comment by k-zakhariy** [comment]
Thanks!
