### ISSUE TITLE
tooltip-is-open is not working if it's parent has ng-if directive

### ISSUE THREAD

**Issue by feng-xiao** [angular-ui/bootstrap#5484]
tooltip-is-open is not working if it's parent has ng-if directive

**Comment by wesleycho** [comment]
This needs a reproduction on Plunker.

**Comment by wesleycho** [comment]
I suspect this issue is due to not binding the value to a reference on $scope - see [Understanding Scopes](https://github.com/angular/angular.js/wiki/Understanding-Scopes) on the AngularJS wiki

**Comment by feng-xiao** [comment]
it works if I change to use ng-show/ng-hide. would that be timing issues?

**Comment by RobJacobs** [comment]
@feng-xiao Here is a [plunk](http://plnkr.co/edit/fmkIDm7n0dCb2nXmdFGG?p=preview) generated from the demo page that proves the tooltip-is-open is working as expected with ngIf.  I'm going to close this issue for now, if you can reproduce the problem, I will re-open it.

**Comment by chandlerkent** [comment]
@RobJacobs here is a [plunk](http://plnkr.co/edit/ATixYRIv9A3PC76wc57x) based on your working plunk that demonstrates the issue.

There are two directives created with exactly the same logic. The only difference is one has an ng-if and one does not.

**Comment by Vaaceph** [comment]
I agree with one who asked this question. If you use ng-if , tooltip-is-open does not work, but it works fine when you use ng-show.

**Comment by keithics** [comment]
same problem here..
