### ISSUE TITLE
Timepicker: DST issue

### ISSUE THREAD

**Issue by joh-klein** [angular-ui/bootstrap#5485]
On the fall day of DST the time picker can't go forward past 2 AM

http://plnkr.co/edit/f1kiq5J89eOhBLgtstRT?p=preview

**Comment by wesleycho** [comment]
I'm not seeing this - can you give me the exact steps you are taking to see the issue?

**Comment by joh-klein** [comment]
Ah, I think this might happen, if the day to switch back from DST in your time zone differs from mine (2016-10-30). Please change `$scope.mytime` accordingly.

**Comment by wesleycho** [comment]
Got it, finally was able to reproduce in the Pacific timezone: http://plnkr.co/edit/aJSWySs4N458sERn7yum?p=preview

This is an interesting bug. We likely need to add a check in the increment method in the timepicker & special timezone handling - the decrement one seems to work properly.

**Comment by sokla** [comment]
I really want to know hot to use arrowkeys in Timepicker.

**Comment by icfantv** [comment]
Closing in favor of #5957 as this will result in a complete rewrite of the widget, addressing all the outstanding issues.
