### ISSUE TITLE
Tab: active state

### ISSUE THREAD

**Issue by RobJacobs** [angular-ui/bootstrap#5486]
@wesleycho I'm seeing a behavior I was not expecting as a result of change #5425 and wanted to check if it was intended.  The tab content no longer works if not implementing the 'active' state on the uib-tabset and 'index' on the uib-tab directives.   Previously, tracking the active tab was not required.  Here is a [plunk](http://plnkr.co/edit/lPwmPpFK0sLVGjsJsUge) demoing the issue.

**Comment by wesleycho** [comment]
The API changed as a result of 5ec19b643b2271c81e83a7032ccb0ab97ddc6612
