### ISSUE TITLE
typeahead-loading is still true for short time after promise has finished

### ISSUE THREAD

**Issue by naokha** [angular-ui/bootstrap#5487]
Hello,
Thanks for this nice project.
I'm using typeahead to autocomplete an input with data from a server.
I want to display a spinner while it is retrieving data, the problem is that the spinner continues to be shown (it is to say the variable in the typeahead-loading attribute is still true) even when the data are displayed, for a short time (let's say 1 or 2 seconds) which is weird.

Am I the only one having this ? 
I wanted to get the data retrieved as workaround, meaning if the length of my array of data is not empty, that means I retrieved stuff and I have to hide the spinner, but I don't know how to do this since I use it like this :
`uib-typeahead="data for data in myFunctionToRetrieveData($viewValue)"`

Any clue ?
Thanks

**Comment by icfantv** [comment]
@naokha, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.
