### ISSUE TITLE
Typeahead with hint gets invalid input

### ISSUE THREAD

**Issue by deeg** [angular-ui/bootstrap#5493]
[See this plunker for issue](http://plnkr.co/edit/FQWvIyRKMTGozoE7KKUY?p=preview)

Steps to reproduce:
* Go to second input on the plunker and type the letter "r"
* With results showing, hit shift + tab
* Notice the input has the word route in it

*Note:* Depending on the first letter typed, the input after tabbing out will be different.

**Comment by wesleycho** [comment]
This must be tab completion happening - this is an accessibility bug, and probably a case that wasn't anticipated.

**Comment by deeg** [comment]
Tab completion from where? Where do you think the value is coming from?

**Comment by wesleycho** [comment]
There is a listener for the keypress event, and it checks whether the key pressed is a tab, but we need to be screening out for if shift is pressed.
