### ISSUE TITLE
Mobile menu not working?

### ISSUE THREAD

**Issue by a11smiles** [angular-ui/bootstrap#5495]
I'm sure I'm doing this incorrectly, but here's the issue:

1) I typed the following commands
    `bower install angular-bootstrap`
    `bower install angular`
    `bower install bootstrap`
2) I then added the following to my html file
```
    <link href="styles/bootstrap.min.css" rel="stylesheet">
```
and
```
    <script src="scripts/angular.js"></script>
    <script src="scripts/ui-bootstrap-tpls.min.js"></script>
    <script src="scripts/app.js"></script>
```

3) Finally, I added `ui.bootstrap` as a dependency to my module.

The problem is, when I decrease my browser's width to show the mobile, collapsed menu, clicking on the menu does nothing - it doesn't display the menu.

What am I missing?

**Comment by icfantv** [comment]
@a11smiles, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.


There is absolutely nothing you've given us to assist you in debugging this issue.
