### ISSUE TITLE
Doc : tooltip-append-to-body not indicated as being configurable globally

### ISSUE THREAD

**Issue by JulReb** [angular-ui/bootstrap#5501]
In the [documentation](http://angular-ui.github.io/bootstrap/#/tooltip), tooltip-append-to-body is annotated with "$" (angular expression) only, whereas I discovered in some issues' comments that it can also be configured globally using "appendToBody", so I think it should be annotated with "C" also?

It is marked as being configurable only for the datepicker element whereas it also exists in dropdown, popover and typeahead, I don't know if it's configurable for all of these.

**Comment by icfantv** [comment]
Yep, this looks like a good catch.  Thanks.  @Foxandxss, I looked at the code and this looks to be correct.  Can you just double-check please?  Thanks.

**Comment by Foxandxss** [comment]
That is actually true. I missed it because it is not well "documented" on the code. I will fix that and the docs tomorrow.

**Comment by JulReb** [comment]
Thank you  @icfantv and @Foxandxss !!
