### ISSUE TITLE
Tooltip top offset isn't working for wrapped content.

### ISSUE THREAD

**Issue by jsdevel** [angular-ui/bootstrap#5504]
![white-space](https://cloud.githubusercontent.com/assets/2605980/13130273/1666eb12-d5a0-11e5-897f-6bb9aaecc031.png)
![white-space-one-line](https://cloud.githubusercontent.com/assets/2605980/13130272/166601c0-d5a0-11e5-87a6-af6483726435.png)

**Comment by icfantv** [comment]
Hi there!  Per our project documentation, please create a minimally working plunker that shows this issue.

**Comment by RobJacobs** [comment]
Our demo page seems to be working correctly

![image](https://cloud.githubusercontent.com/assets/4559806/13143628/380d2376-d613-11e5-9139-8a5e9483ed29.png)

**Comment by jsdevel** [comment]
I'll have to check it out then.  Must be something CSS related.

**Comment by icfantv** [comment]
@jsdevel that was going to be my guess as well - you're clearly not using our built in templates or any Bootstrap classes.
