### ISSUE TITLE
Can't display value with angular ui datepicker and open datepicker popup for multiple datepicker

### ISSUE THREAD

**Issue by thovo** [angular-ui/bootstrap#5505]
I am loading the data into several `uib-datepicker-popup` through `ng-repeat` and allow the user to edit these data. Now I met some problems here:

1. To display the value for the date inside `uib-datepicker-popup`, currently only the placeholder show the value
2. Can't open the calendar popup to choose a new date

The plunker for my example is [here](http://plnkr.co/edit/bRDkV1L6iH0aKPyAPW2f?p=preview)

**Comment by icfantv** [comment]
@thovo, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.
