### ISSUE TITLE
Opening $uibModal with keyboard:true but disabling it while the modal is open?  

### ISSUE THREAD

**Issue by mareksoans** [angular-ui/bootstrap#5506]
Hello!

In my modal, I have a simple web form. If user opens the form to read some data then it is safe (and intuitive) to close it with [**esc**] key.

However, when the user changes something on the form and has not yet saved it, then, ideally - I'd want to prevent the accidental closings of the modal with [**esc**] key.

**Q:** Is it possible to change the properties (**keyboard** and/or **backdrop**) of a modal - once it is already opened?

Thanks,

**Comment by icfantv** [comment]
@mareksoans, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

Ok.  So there's UX to consider here - does it make sense to still allow the user to hit the ESC key when you have a form in your modal and there's a risk of them losing their entered data?  IMO, no, there's not, but I could go both ways on this as it's a soft "No."

Finally, there is a way to intercept and prevent the window from closing.  You need to listen for the `modal.closing` event and if you prevent the default event from continuing, you will prevent the modal from closing on escape.  This is in our [documentation for modal](http://angular-ui.github.io/bootstrap/#/modal) - scroll down to the _Events Fired_ section.

I'm going to close this as a support issue.

**Comment by sayoojvv** [comment]
**put 	keyboard  : false**


var modalInstance = $uibModal.open({
				animation: true
				, templateUrl: page
				, backdrop: 'static'
				, keyboard  : false
				, scope: $scope
				, size: size
				, resolve: {
					items: function () {
						return 1;
					}
				}
			});
