### ISSUE TITLE
incorrect z position modal

### ISSUE THREAD

**Issue by paradoxm** [angular-ui/bootstrap#5510]
If you open a modal and then from it to open a second modal it comes back first. In version 0.14.3 was all excellent

example [http://joxi.ru/v29WkXWFGOWQ3r.jpg](url)

**Comment by icfantv** [comment]
@paradoxm, please read our documentation on how to properly file a bug report.  Also, the link you pasted is not formatted correctly in MD.  I'm going go close until you fix both issues and will then reopen.  Thanks.

**Comment by paradoxm** [comment]
I said that there is an error, and then decide for yourself

**Comment by icfantv** [comment]
@paradoxm, perhaps this response is better:

Managing a very popular OSS repository requires a lot of work by many people all of whom _do it in their spare, unpaid time_.  We ask that you please be respectful of that time by adhering to our project documentation - which I should point out has a link in a bright, yellow box just above the issue input field where you created this issue.

If you are unwilling to put forth even a basic level of effort to follow our project documentation and create an issue with a working hyperlink (yours currently directs to https://github.com/angular-ui/bootstrap/issues/url even though the text of the URL points to an image), then should you realistically expect us to bend over backwards disproportionately to help you?

**Comment by paradoxm** [comment]
I do not need help. I tried your directives, and it failed. I refused it. I thought you might be interested.

**Comment by icfantv** [comment]
Worked just fine for me two months ago when I [created this plunker](http://plnkr.co/edit/spsOOBXFKG5N8Ygzw3Uz) using 0.14.3.  I even upgraded to the latest library versions and it still works correctly.

I'm sorry you're having trouble, perhaps posting your problem in a more widely read forum, like StackOverflow, will help you solve your issue.  Incidentally, this is also in our documentation.
