### ISSUE TITLE
Star rating wraps over then pushed narrow

### ISSUE THREAD

**Issue by mcd-php** [angular-ui/bootstrap#5514]
### Bug description:

Star rating wraps over then pushed narrow
Expected to be unbendable block

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/1ImqAPFyjWVurqmm3yPy

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.9
UIBS: 1.1.2
Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
This is a CSS problem that is easily fixed on the user side - see [here](http://plnkr.co/edit/SREW2B9F6xZTeVF8i8Qg?p=preview) for an example.

**Comment by mcd-php** [comment]
@wesleycho Plunker is down for many hours as of `2016-02-24 09:20:52+00:00`. What if it ever go out of business at all ? Please put the solution here.

**Comment by wesleycho** [comment]
Plunker is working. Your question was not a library issue, and should not have been posted here, but on StackOverflow - this is the type of issue that slows open source progress.

**Comment by mcd-php** [comment]
@wesleycho No, this is a conceptual problem and not a usage peculiarity - star rating is supposed to be stiff bar, not something bendable. 

Yes, my usage is somewhat special, but what if someone will miscalculate width of his regular layout, making star rating pushed from sides ?

Then I search for 'start rating' at Google and show pictures - it's only straight or special art forms, but not flowing like text.
