### ISSUE TITLE
Datepicker - Tweak monthpicker to allow custom # months per row

### ISSUE THREAD

**Issue by Mrman** [angular-ui/bootstrap#5515]
This is a feature request to allow more flexibility in the monthpicker. Currently its set to always be 3x4. In my custom template I'd like to have this as 4x3. The monthpicker is currently hardcoded to split by 3:

`scope.rows = this.split(months, 3);`

This is similar to this request for yearpicker: #4970 #3348 but different in that we can only have 12 months so I propose just providing a monthsPerRow option which defaults to the current 3 if not provided.

Happy to submit a PR for this if you are happy to take this in.

**Comment by wesleycho** [comment]
This sounds reasonable, similar to how the yearpicker works - feel free to file a PR. Be aware that current `master` has some major changes in the datepicker config definition (deprecating most attribute bindings).
