### ISSUE TITLE
 Datepicker: Support Week Input Format

### ISSUE THREAD

**Issue by schasoli** [angular-ui/bootstrap#5516]
### Feature requests:
using UI Bootstrap 1.1.2 and the current  'ui.bootstrap.datepicker' plunker example:
 $scope.format = 'yyyy KW ww';
gives a week result "2016 KW 07" in the Popup.
But it is not possible to change the week/date through
$scope.altInputFormats = 'yyyy KW ww';

This makes sense, as a week is not a certain date. But it would be good, if it would return a day in this week. 
Or better, being able to redirect the input for 'altInputFormats' to a different variable. So it could be adapted to whatever may be wanted.

**Comment by wesleycho** [comment]
Changing the week though has a lot of complications - can you explain why would changing the week be desired?

**Comment by schasoli** [comment]
I want to use the picker to select a calender  week. The incomming date is 2016W02 or 2016-W-02 ISO Format.
(Maybe 2016W02P1 would be more correct.)
However, moment() transformes it into the monday of the week.
In the picker input field it is showen as 2016 W 02. Opening the Calender shows the monday. Choosing a day of the next week shows 2016 W 03 in the input field.

I would like to change the week directly in the input field, too.

What would be perfekt?
Date picker could interpret 2016W02P1 as a Periode of one week. 
In Calender all the days of the week were preselected.
The week numbers could be selected and return 2016W02P1 (or 2016-01-11P7)
Changing the week numbers in the input field would reflect in the date Periode.

Am 22. Februar 2016 16:33:50 MEZ, schrieb Wesley Cho <notifications@github.com>:
>Changing the week though has a lot of complications - can you explain
>why would changing the week be desired?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/angular-ui/bootstrap/issues/5516#issuecomment-187231520

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by wesleycho** [comment]
This seems like a strange feature request, and I think it would be too difficult to integrate with the existing datepicker.

From a UX standpoint, it also introduces an additional step for the user.

I'm going to reject this as a feature we are not interested in supporting unfortunately - the overhead risk is too large.
