### ISSUE TITLE
Hitting "enter" to accept the modal dialog

### ISSUE THREAD

**Issue by huyph** [angular-ui/bootstrap#5517]
### Bug description:
I'd expect if the modal is wrapped inside a form, hitting "enter" should click `button type="submit"`.
But that doesn't seem to be the case?. I know I can apply solution similar to the one mentioned here: http://stackoverflow.com/questions/21633422/angularjs-accept-a-ui-bootstrap-modal-with-enter-key

But would be great if there is any easier way out of the UIBS?

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/PD7Fq8xYVdaH3mnHX28B?p=preview

### Version of Angular, UIBS, and Bootstrap
Angular: 1.4.9
UIBS: 1.1.2
Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
This seems very dirty - why are you wrapping all of the modal HTML in a form element?

**Comment by sylouuu** [comment]
Hi @huyph,

First add `ng-submit` attribute in your form.

Then don't forget to add `type="button"` on your cancel button as all `<button>` are `submit` by default.

Hit enter after focusing in the input then check the console. http://plnkr.co/edit/PKpIi5cDsIYbHcyUjnVJ?p=preview

Bests

**Comment by icfantv** [comment]
@sylouuu, all buttons are _not_ `submit` by default - an `<input type="submit">` is a submit by default, but a `<button>` simply does what its `ng-click` handler says to do.

IMO, the right behavior here is to have a `<form>` element wrap _only the form controls_ and the `ng-click` event handler for a dialog's "Save" button is where you do either the persistence, or the sending of the data back to the calling code that opened the modal.  If you want to control button state based on form validation, you can still easily do this by storing the form on the modal controller and then using the standard `ng-disabled="form.$invalid || !form.$dirty"` on the "Save" button.

**Comment by huyph** [comment]
@wesleycho: I want to be able to accept the modal (or confirm action) by hitting 'Enter', instead of clicking on the button using my mouse
@sylouuu : uhm.. That works. But i don't want the extra input field. And looks like if I have `type='hidden'`, then `focus()` won't work.
@icfantv: i don't think that will make "enter" to accept the form works?

**Comment by icfantv** [comment]
@huyph, adding a `$timeout` function handler that gives your `submit` button focus does make the Enter key work as you wish.  Here's a directive we use (ust add `auto-focus` to your submit button):

```
.directive('autoFocus', function AutoFocus($timeout) {
  return {
    restrict: 'A',
    link: function ($scope, $element) {
      $timeout(function () {
        $element[0].focus();
      }, 0);
    }
  };
})
```

I'm going to close this as a support issue rectified by the user on their end.
