### ISSUE TITLE
Carousel suddenly stopped working

### ISSUE THREAD

**Issue by thangnguyendt** [angular-ui/bootstrap#5519]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Hello

I used carousel with angular 1.5.0 -> it suddenly stopped working. I thought -> ha, this might be an issue -> I changed the whole library (angular, animate) to 1.4.9 -> the issue is still here.

Please help

### Link to minimally-working plunker that reproduces the issue:
I don't have plunker :  I copied from https://angular-ui.github.io/bootstrap/#/carousel

### Version of Angular, UIBS, and Bootstrap

Angular:
1.4.9 and 1.5.0
UIBS:
1.1.2 (latest)

Bootstrap:
3.3.6

**Comment by wesleycho** [comment]
This is a known/duplicate issue - see #5471.
