### ISSUE TITLE
Days Field after hours or a way to go Beyond pass 23:59 like 139 hr: 59 min..... 

### ISSUE THREAD

**Issue by harshpuidev** [angular-ui/bootstrap#5521]
### Feature request
I am using angular timepicker for duration selection and i know that i can use date picker and time picker together to do that i want to do it in following ways.

Is there way to select a unlimited hours instead of limiting it to 23:59 or can you add a day input field that increments when the counter reaches 23:59..

Or is there any way i can do these on my side..

 
http://keith-wood.name/timeentry.html -> format -> Unlimited Hours. some thing like these
Thank you

**Comment by icfantv** [comment]
What you're talking about is effectively a duration field, and not a time field.  Our time picker was not designed to be used for duration.  I'm not suggesting that this wouldn't be a useful feature, but it IS one that has not been requested before (to my knowledge) - certainly not requested enough for me to remember.

This is not going to be a very high priority for us and you'd probably be better off, taking our timepicker code and tweaking it as you see fit.  If you do that, you might consider open-sourcing that component in your own repo.

I'm going to close this for now until/unless one of the other devs would like to reopen.
