### ISSUE TITLE
Cursor blinks outside the textbox in IE 11

### ISSUE THREAD

**Issue by curiousPup** [angular-ui/bootstrap#5523]
This issue had been raised quite a times but I still cannot find a fix for it.
The cursor blinks somewhere outside the input box in modal specifically in IE11, and comes in right position as soon as you start typing.
Please respond if anybody knows a work around for this.

**Comment by icfantv** [comment]
Any particular reason you ignored our issue template?

**Comment by wesleycho** [comment]
Closing due to insufficient information & likely nothing to do with UI Bootstrap
