### ISSUE TITLE
pagination doesn't work

### ISSUE THREAD

**Issue by taugustyniak** [angular-ui/bootstrap#5524]
Hi, I try to use the pagination directive and on the official [plnkr demo](http://plnkr.co/edit/LuiXN4sxqQ8jS877vgD5?p=preview) we can see that directive seems not to be working at all. Why ?

**Comment by wesleycho** [comment]
The [official demo](http://plnkr.co/edit/z39tSz7tpM0yc4bd3Laq?p=preview) works fine. It doesn't have the current page listed there - @Foxandxss have any ideas how we should spruce this up so it's more obvious what is happening? Should we add something like `The current page is: {{currentPage}}`?

**Comment by Foxandxss** [comment]
That is the type of thing I never noticed. Yeah, that plunker and demo is horrible. Let me thing about that.

**Comment by taugustyniak** [comment]
hmm ok, but why the page number buttons are not generated ?

**Comment by Foxandxss** [comment]
There is a **pagination** control and a **pager** control. You are looking at the pager and I guess you want the pagination.

**Comment by taugustyniak** [comment]
you're right, I didn't notice that. Now it's fine, thanks !

**Comment by wesleycho** [comment]
Keeping this issue open since we do need to update the pager docs

**Comment by agrahamlincoln** [comment]
here's a quick crack at it:
http://plnkr.co/edit/mZbFVPI6DFDy4NdWlG1m?p=preview

I can create a PR if it looks good to you guys
