### ISSUE TITLE
dropdown - separate auto-close options

### ISSUE THREAD

**Issue by charlierudolph** [angular-ui/bootstrap#5525]
I would like to have something that is a combination of the two auto-close options - 'outsideClick' and 'disabled'.

I have a dropdown that I want to stay open when the user clicks inside it or the url changes, but closes when the user clicks outside the element.

Giving a new option for this combination or separating the option into three booleans (`auto-close-inside-click`, `auto-close-outside-click`, `auto-close-location-change`) would be great.

I'm happy to help with the implementation if this would be accepted.

**Comment by icfantv** [comment]
This is a pretty specific use case and one I'm not sure we're going to be keen on supporting.  @wesleycho/@Foxandxss, thoughts?

**Comment by RobJacobs** [comment]
This is what the is-open attribute is for, you can support more exotic uses cases with that.

**Comment by icfantv** [comment]
Works for me.  Closing as a support issue.  @charlierudolph, we'll consider reopening if you can give us a more compelling reason.  Thanks.

**Comment by charlierudolph** [comment]
My workaround ended up being using `auto-close='disabled'`, using `is-open`, and using another library to get the `outsideClick` effect. I was hoping for this just so I that other library wouldn't be necessary.

**Comment by charlierudolph** [comment]
I agree, this is an edge case, but you really do have 3 different auto close functionalities and I don't think this will make the code any more complex. The three different options may be a bit much and instead you could allow the user to enter in all the different types of auto-close they way.

```
auto-close='always' // same as current
auto-close='insideClick' // only on inside click
auto-close='outsideClick' // only on outside click, not on location change
auto-close='outsideClick locationChange' // on outsideClick and locationChange
auto-close='disabled' // same as current

**Comment by icfantv** [comment]
@charlierudolph, with all due respect, anytime you add an API feature and tests you make the code (and testing) more complex.  :-)

Remember that we are all volunteers doing this in our spare time, for free.  So any additional maintenance on us has a direct impact on you guys as library users.
