### ISSUE TITLE
tab is active but on click still tab being activated

### ISSUE THREAD

**Issue by GGeorgi** [angular-ui/bootstrap#5534]
I have got a problem using tabs in nested views.

I have a two level tab bars:

| tab 1 || tab 2 || tab3 ||
| ||___________
| tab1.1|| tab1.2 ||

tab1 state is "user({id:45})" tab1.1 state is "user.details"
I'm passing parameter to tab1 and loading that user data and stores in service before changing state to "user.detail". So it works good so far. But when I clicks on tab1 state has being changed to "user({id:45})" and from sub tabs no one is selected. But I wonders why it changes state in case of it is already selected.
so I wonder to know is where any way to prevent tab select if is it already selected ?
Here is how I creating tab: passing state url by ui-sref

`<tab ng-repeat="tab in tabs" heading="{{tab.title}}" active="tab.active" disabled="tab.disabled" ui-sref="{{tab.url}}" ui-sref-active="active">`

**Comment by icfantv** [comment]
@GGeorgi, is there any particular reason you ignored our issue template?  I'm going to close this until our instructions are followed.  Sorry, and thanks.
