### ISSUE TITLE
Angular bootstrap not passing official W3C HTML5 validation

### ISSUE THREAD

**Issue by roshancsc** [angular-ui/bootstrap#5545]
Hi 

I have a project where I'm using AngularJS and bootstrap, but one of the requirements is that my app must pass official HTML5 validation. Is there any way by which I can meet this requirement or do I need to do it from scratch.

Thanks

**Comment by icfantv** [comment]
@roshancsc, per the issue text you deleted to enter your message, the issues forum is not for support requests.  Please respect our time by following our project's instructions.  Thanks.

Additionally, your question is FAR better suited to a venue like StackOverflow.
