### ISSUE TITLE
Focus should not place on input field after closing the modal

### ISSUE THREAD

**Issue by hollykarthi** [angular-ui/bootstrap#5546]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
In internet explorer 10, the focus is automatically placed on input field after I close the modal. This should not be happen when I close the modal.
### Version of Angular, UIBS, and Bootstrap
angularjs 1.4
angular-ui-bootstrap, Version: 0.12.1 - 2015-02-20
bootstrap 2.2.2
Angular:

UIBS:

Bootstrap:

**Comment by wesleycho** [comment]
Any reproduction?

**Comment by wesleycho** [comment]
Closing due to lack of actionable information.
