### ISSUE TITLE
Popover with template in 1.2.0 version

### ISSUE THREAD

**Issue by egortsaryk9** [angular-ui/bootstrap#5549]
It seems that _ui.bootstrap.popover_ with a Template is broken in new 1.2.0 version. It even doesn't work on official example at https://angular-ui.github.io/bootstrap/   (click 'Popover With Template' button)

**Comment by icfantv** [comment]
Good catch on this.  Thanks.

**Comment by wesleycho** [comment]
This is an interesting defect - the tooltip class has `display: block`, but the popover class has `display: none`. Looking into this, we will probably release 1.2.1 asap after this is fixed.

**Comment by wesleycho** [comment]
A quick fix is to define `.popover { display: block; }` in your CSS

**Comment by jibap** [comment]
And what about [uib-popover-html-popover] ? also missing, no ?
