### ISSUE TITLE
uib-datepicker flicker

### ISSUE THREAD

**Issue by kyrylkov** [angular-ui/bootstrap#5550]
### Bug description:
Flicker of uib-datepicker when date is first selected
![flicker](https://cloud.githubusercontent.com/assets/6225870/13373638/3c0615e4-dd6d-11e5-9393-12db3c38fe71.gif)
### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 1.2.0

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
Without further information, this appears to be a duplicate of #5446.

@kyrylkov, please be respectful of our time by following the project documentation (and the issue template you deleted to enter your text).  If you can show that this is a different issue that #5446, we will reopen.  Thanks.
