### ISSUE TITLE
Tooltip: ng-if container delays tooltip HTML compilation and fails `positionTooltip`

### ISSUE THREAD

**Issue by skmasq** [angular-ui/bootstrap#5553]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
If bootstrap tooltip is compiled within `ng-if`, the `positionTooltip` function @ Line: 5028, cannot find `html()` of that tooltip because nothing has been compiled yet. Whereas, if the tooltip is compiled outside `ng-if` everything is working properly.

If you look at the plnkr and put a break point @ Line: 5028, you'll see that one tooltip is already compiled where the other one is still pending the compilation.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/3Mv6UWPjDNiuw6NKemSN?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.3.20

UIBS: 1.4.3

Bootstrap: 3.1.1

**Comment by RobJacobs** [comment]
Try wrapping your compile in a timeout:

        $timeout(function() {
          $compile(targetElement)(scope);
        }, 0, false);

**Comment by skmasq** [comment]
Thanks @RobJacobs  it solves the issue. Is there any reference to why this works?
