### ISSUE TITLE
tooltop

### ISSUE THREAD

**Issue by amurtola** [angular-ui/bootstrap#5559]
I have bootstraps tooltip in element with hidden overflow. When i hover button with tooltip, part of tooltip is hidden by parent div.
```

<div class="hiddenoverflow">
<span class="btn" tooltip="Part of this tooltip is hidden by parent div"></span>
</div>
```

Tooltiptip component defined in ui-bootstap-tpls.js

What can i try?

**Comment by Foxandxss** [comment]
You haven't read the issue template, am I right?
