### ISSUE TITLE
ModalWindow $animateCss event bug

### ISSUE THREAD

**Issue by je3f0o** [angular-ui/bootstrap#5562]
I think I found a bug with Modal window.
I was trying to add custom animation on modal window.
But there was a problem with `.ng-leave` class.
So I go to read modal's source code.
I think forget to add
`structural : true`
after this line
https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L365

**Comment by icfantv** [comment]
@je3f0o, thank you for this report.  In the future, please follow our issue template to ensure your issues receive the proper attention.

**Comment by wesleycho** [comment]
This should be fixed in 299f751
