### ISSUE TITLE
uib-datepicker-popup attribute will be deprecated, using datepickerConfig in datepicker-options instead doesn't work

### ISSUE THREAD

**Issue by bolemeus** [angular-ui/bootstrap#5563]
### Bug description:
I'm migrating from 0.14 something to the latest version and I get the message that the attribute uib-datepicker-popup will be deprecated, so I'm trying to refactor it so it's set in the datepicker-options object instead. Sofar I've got the following...

```
this.dateOptions = {
    maxDate: new Date(),
    datepickerConfig: 'dd-MM-yyyy'
};
```

But now the popup is not opening anymore. The documentation isn't clear on this either, since it still uses the soon to be deprecated attribute uib-datepicker-popup. I think the documentation might be outdated on this.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.7

UIBS: 1.2.1

Bootstrap: 3.3.1

**Comment by icfantv** [comment]
you can pull the latest code and build it locally.  this will build the updated version of the library and the docs and place them in the `dist` folder.  you will need grunt to build the project.

**Comment by moderndegree** [comment]
@bolemeus Not sure you were seeing the same issue I was but for me, it turned out to be an issue with our CSS. It was working, just not visible. After including `ui-bootstrap-csp.css` the problem went away.
