### ISSUE TITLE
docs(popover): wrong default trigger

### ISSUE THREAD

**Issue by CecilCable** [angular-ui/bootstrap#5564]
### Bug description:
The docs say the default behavior trigger is "mouseenter", but it is "click":
See source code:
https://github.com/angular-ui/bootstrap/blob/master/src/popover/popover.js#L18

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/s0kEawEU6KqCSXMva593

### Version of Angular, UIBS, and Bootstrap

Angular:1.5.0

UIBS:1.1.1

Bootstrap:3.3.5

I can add a do a PR

**Comment by wesleycho** [comment]
This sounds like you're correct - feel free to open a PR.
