### ISSUE TITLE
colon notation for the uib prefix isn't supported for tab headings

### ISSUE THREAD

**Issue by ivassiliev** [angular-ui/bootstrap#5568]
### Bug description:
Hi, I found this while fixing some inconsistencies in our code:

The colon notation for the uib prefix isn't supported for tab headings, but is for other elements such as alert, angularjs also currently still supports both formats so there's some inconsistency here between what angularjs is supporting and what ui boostrap is supporting.

Thanks for looking.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/7SARpm4f3a0TSBTjaDhg

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 1.2.1

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
Can't say I like seeing anyone use `:` in their element names (seems foreign to anyone working in HTML, and rare), but I guess this is a bug.
