### ISSUE TITLE
first-text on Pagination cant cant render  HTML

### ISSUE THREAD

**Issue by jasminmif** [angular-ui/bootstrap#5570]
**Bug Description:**
I want to render the first-text ( First page on the Pagination) as <u>First</u> but it renders it as a text, and not as a html, i tryed to use $compile but no success yet.

Tryed fixing using this code: 
`var firstComp = $compile(scope.firstText)(scope);
				scope.firstText = firstComp;`
on line: 4343

Version: angular 1.5, uib: 1.2.1

p.s: i know we can edit the templates directly, but i dont think its a good way to do it, so maybe we could fix this by compiling the text into a html

**Comment by icfantv** [comment]
@jasminmif, any particular reaso you ignored our template and didn't add a reproduction?

**Comment by jasminmif** [comment]
I think it would be better if its avilable just to put a HTML in the first-text attribute, and compile it, cause for some reasons i might want to add a Glyphicon or a Bold or Underline on the keyword and it would not work.
Otherwise good job you made my life easier :)

**Comment by wesleycho** [comment]
If one wants HTML instead of just text, one needs to override via a custom template and usage of something like the `template-url` option.

Closing as a support issue.
