### ISSUE TITLE
Datepicket: format not conserved when converted to json

### ISSUE THREAD

**Issue by shanavas786** [angular-ui/bootstrap#5572]
Datepicker model gets converted to  date time format when converted to json object.

uib-datepicker-popup="dd MMMM yyyy" with date selected 10 March 2016 gets converted to 2016-03-09T21:00:00.000Z when converted to json.

This creates unexpected results in CRUD operations.

http://plnkr.co/edit/Syu4rynw0lMdYfTXl6KC?p=preview

**Comment by icfantv** [comment]
@shanavas786, in the future, please be respectful of our time by adhering to our issue template rather than summarily deleting it.

My gut says this is intended behavior but will let @wesleycho or @Foxandxss clarify for sure.

**Comment by wesleycho** [comment]
The model is a date object - if you are saving it to a DB, it is up to you to serialize it. This is not a bug.

**Comment by icfantv** [comment]
Thanks @wesleycho.

**Comment by shanavas786** [comment]
@icfantv sure.

@wesleycho then, what is the use of format parameter ?

**Comment by wesleycho** [comment]
For display in the UI - that is clearly illustrated in the documentation.
