### ISSUE TITLE
Split off datepicker popup into separate component

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#5574]
Currently the datepicker popup is bundled with the inline datepicker - it would be beneficial to split it off to increase modularity.

**Comment by RobJacobs** [comment]
I was thinking it would be nice to have a generic popup directive that would just handle the open state, positioning and trigger events.  Then allow for template content which we could then use for a datepicker, popover, template tooltips, typeahead, etc...  Tooltip could be scaled back to serve just basic tooltips.

**Comment by icfantv** [comment]
I like that idea @RobJacobs.

**Comment by wesleycho** [comment]
That could separated into a different module - maybe this one can be renamed to `uib-datepicker-dropdown`

**Comment by wesleycho** [comment]
Or...this one can still be `uib-datepicker-popup`, and the new one could be `uib-datepicker-popover`.

**Comment by wesleycho** [comment]
This task is complete, looks like I forgot to mark it for closure - closing now.
