### ISSUE TITLE
XSS attack is possible through typeahead component

### ISSUE THREAD

**Issue by vpishuk** [angular-ui/bootstrap#5578]
### Bug description:
Try to return HTML in the displaying response.

Actual result: HTML is displayed as renderd
Expected result: HTML is displayed as simple text

Angular: on your site (https://angular-ui.github.io/bootstrap/)

It happens because you use $parse instead of $sce

**Comment by wesleycho** [comment]
Please post a specific Plunker in the future - this would make it much faster to respond & reduces problems chasing issues.

[Here](http://plnkr.co/edit/pppmzZyCa2pWh6XW2oji?p=preview) is the Plunker for reference here.

**Comment by wesleycho** [comment]
Updated the Plunker - it doesn't look like injection is possible here. Can you elaborate/fork the Plunker with a clear illustration?
