### ISSUE TITLE
Typeahead is-open does not update when typeahead closes from escape keydown

### ISSUE THREAD

**Issue by ryanyuyu** [angular-ui/bootstrap#5579]
### Bug description: 
`typeahead-is-open` does not update when typeahead closes from escape keydown.  To reproduce this, simply type some text and the hit the escape key.  The typeahead menu will close itself, but the variable bound to `typeahead-is-open` does not update.  It updates twice after being reopened with new inputs.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.7, 1.5.0

UIBS: 1.2.1 (with templates)

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
Modified the Plunker to show open state too [here](http://plnkr.co/edit/xmwcGq0dC944z0pJeByc?p=preview) for quicker validation for whoever works on this - this indeed looks like a bug.
