### ISSUE TITLE
Using min/max with datepickerOptions don't bind

### ISSUE THREAD

**Issue by jibap** [angular-ui/bootstrap#5581]
Hi !

I upgrade in 1.2.2, and i get this console log : 
<code>
uib-datepicker settings via uib-datepicker-popup attributes are deprecated and will be removed in UI Bootstrap 1.3, use datepicker-options attribute instead
</code>

So i removed min-date & max-date from HTML and added it into datepickerOptions.
The issue is they don't bind, it works only first time but : 
i have a start and end datePicker and i want :
- max of start be the end value
- min of end be the start value

For now, when start or end change, i change min & max values and it works.

Thanks

**Comment by icfantv** [comment]
@jibap, per the text you deleted you enter this, the issues forum is NOT for support-related requests.  You didn't even follow the requisite instructions for if you found a bug.  In the future please be respectful of our time by adhering to or project documentation (and our issues template).

If you believe you've found a bug, you will need to replace your above information with the information requested in the issue template.  Until you do so, I am going to close this issue.
