### ISSUE TITLE
Support ng-model-options for timepicker

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#5594]
We should support [ng-model-options](https://docs.angularjs.org/api/ng/directive/ngModelOptions) in the timepicker.

- [ ] updateOn
- [ ] debounce
- [ ] allowInvalid
- [ ] getterSetter
- [ ] timezone

**Comment by WindSaber** [comment]
While they're working on this feature, probably it would be a good idea to review this workaround used when you're working at the same time with datepicker and time picker.

[http://www.ericluwj.com/2015/11/06/angularui-ui-bootstrap-datepicker-and-timepicker-neutral-timezone.html](url)

Hope someone helps...

**Comment by wesleycho** [comment]
@WindSaber we have full timezone support in the datepicker.

Support in the timepicker is of dubious value though.

**Comment by icfantv** [comment]
Closing in favor of #5957 as this will result in a complete rewrite of the widget, addressing all the outstanding issues.

**Comment by WindSaber** [comment]
Not completely sure about this decision....I think maybe timezone support would be necessary....especially when working when multiple and different timezones at the same time

**Comment by icfantv** [comment]
@WindSaber, we specifically do NOT want timezone support for this component as we fully intend on not even using a date object anymore.  as @wesleycho pointed out, if you want time zone support it's available via the date picker.

**Comment by vallabhvrao** [comment]
@WindSaber 
https://github.com/Gillardo/bootstrap-ui-datetime-picker

use this repo with, enable-date="false" if you need timezone support.
