### ISSUE TITLE
uib-dropdown-menu broken in IE 11 and Edge

### ISSUE THREAD

**Issue by RopoMen** [angular-ui/bootstrap#5595]
Hi,
IE 11 / Edge is not applying "list-style: none;" when class "dropdown-menu" is added dynamically.  
![uib-dropdown-menu](https://cloud.githubusercontent.com/assets/7492812/13575465/be974e6c-e491-11e5-9a2c-c9dc11ab8d3a.png)

I encountered this issue today when testing my site today with Windows 10 and Edge. I was able to verify this issue with Windows 7 and IE 11 in your [Dropdown demo](https://angular-ui.github.io/bootstrap/#/dropdown)

I solved issue by just adding 'dropdown-menu' class for `ul` element and not letting 'uib-dropdown-menu' set it dynamically.

Angular: 1.4.9

UIBS: 1.2.2

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
That sounds really weird - will have to look at this when I get home, unless someone beats me to it.

Not much we can do here if that's the case except recommend to people to use `dropdown-menu` in the HTML, demonstrate it in the documentation, and add a known issue note.

**Comment by RobJacobs** [comment]
@wesleycho This seems to be isolated to the demo page.  If you create a plunk from the demo, I don't see the issue.

**Comment by wesleycho** [comment]
This only seems applicable on the `Dropdown with keyboard navigation` button, and is more of a docs problem than anything else.

**Comment by RopoMen** [comment]
@RobJacobs Agree, I tried to create also jsfiddle but the bug didn't show up. I also checked the dropdowns in my page where I initially saw this issue, but even if I copied 1:1 that DOM structure + js logic it didn't show up anymore in fiddle.

 I did some research and it seems that it is most likely this kind of [issue with IE](http://stackoverflow.com/questions/20356311/internet-explorer-11-ignores-list-stylenone-on-the-first-load)
