### ISSUE TITLE
datepicker ngblur issue

### ISSUE THREAD

**Issue by bittu42** [angular-ui/bootstrap#5599]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
This issue doesn't follow the prescribed template for issues and as such it is not actionable and will be closed. Happy to re-open if you can provide all the relevant and requested info - most importantly a live reproduce scenario using plunker or similar.
