### ISSUE TITLE
Highlight a Date or DateRange which is not current-value.

### ISSUE THREAD

**Issue by vsthakur78** [angular-ui/bootstrap#5600]
Highlight a Date or DateRange which is not current-value.

### Bug description:
Irrespective of what is current date value assigned to a uib-datetimepicker, I am interested in highlighting a specific date or a range of dates. I couldn't make this out from documentation page and since I am new to angular/javascript world not aware if there are alternate ways.

Appreciate getting solution to this issue. Please point me to appropriate resources if there is an existing solution/thread or any other link on internet.

### Something similar to what is described in this post:
http://www.spiceforms.com/blog/highlight-particular-dates-jquery-ui-datepicker/

### Version of Angular, UIBS, and Bootstrap
This is the plunker I referred and using given versions of js/css etc which are used in this plnkr
http://plnkr.co/edit/?p=preview

Angular:
src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js"
src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular-animate.js"

UIBS:
following this page
https://angular-ui.github.io/bootstrap/#/datepicker

Bootstrap:
src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-1.2.4.js"
link  "//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"

**Comment by icfantv** [comment]
@vsthakur78, we do not have a component called `uib-datetimepicker` - the `uib-datepicker` is for picking dates, and the `uib-timepicker` is for picking times.

We do not support date ranges and this issue has been addressed previously in the issues forums.  Please be respectful of our time by extending us the courtesy of reading the issue template and the link to the docs therein as the issues forum is NOT for support requests.  If you have a feature request you need to indicate it as thus but you must first search both open and closed issues to see if your request has already been addressed.

I'm sorry but we will not be supporting date ranges.  You can accomplish this by using two date pickers side by side (perhaps encapsulated within a directive) and overriding the template.

I'm closing this as not an issue and won't support.
