### ISSUE TITLE
Datepicker: Weird behavior if maxDate and initDate refer to the same object

### ISSUE THREAD

**Issue by czosel** [angular-ui/bootstrap#5604]
### Bug description:
I found a weird bug, which occurs when `maxDate` and `initDate` refer to the same object (see fiddle below). 
Steps to reproduce:

1. Open datepicker
2. Go one month in the past
3. Select a date
4. Open datepicker again

Now all the dates displayed are disabled, except the first day of the month - as if `maxDate` changed.

I know that the easy fix is to create a copy of the `Date` object to avoid this, but you can probably imagine how long it took me to figure that out. Maybe it would be possible to create a copy of the dates within UIBS or make it in some other way less likely for someone else to make this mistake?

### Link to fiddle
http://jsfiddle.net/8n6vjzvm/2/

### Version of Angular, UIBS, and Bootstrap
Angular: 1.4.8
UIBS: 0.14.3

**Comment by wesleycho** [comment]
Attribute use has been deprecated - also 0.14.3 is an older version of UI Bootstrap.

Looking at the code in the datepicker, this should already be fixed in the latest release.
