### ISSUE TITLE
$uibModal's open function should take scope as an object even if it is not an instance of $scope

### ISSUE THREAD

**Issue by ranjith19** [angular-ui/bootstrap#5605]
This would make it consistent with the angular JS patterns. The convention is not to use $scope in controllers. However, to open a $uibModal, it looks like one must instantiate a scope even when not using using the $scope.

Have a  look at http://plnkr.co/edit/NWTnxnuL5GLXOdxk0lH3?p=preview

I have defined two controllers. In the first controller, I have $scope and in the second one I do not. There are 2 functions each in the controllers. And I am doing bindToController in both.

Only functions ModalDemoCtrl.first and ModalDemoCtrl2.fourth work correctly. But since I am using bindToController with controllerAs, I would expect all 4 buttons to work correctly.

In the second controller, I am having to invoke the $rootScope even when I do not want to.

**Comment by wesleycho** [comment]
This only would serve to create confusion & have negative perf implications as the default, as well as overly complicate the internals for what appears to be a minor benefit. The modal is not for creating bindings - the only interaction it has with wherever launches it is with the resolution of the modal instance result promise, and with an appropriate structured response object, one can easily get any desired behavior.

Closing as encouraging anti-patterns we do not want to support.
