### ISSUE TITLE
NPM WARN fsevents

### ISSUE THREAD

**Issue by mbruggenwirth** [angular-ui/bootstrap#5606]
### Bug description: NPM WARN fsevents
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8

On npm installing angular-ui-bootstrap i get the following error messages

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.8
Bootstrap: 3.2.0
Node: 4.3.1
NPM: 3.7.5

**Comment by wesleycho** [comment]
I ran a fresh install as a test and do not get this warning - I did not expect to see it because this library has no declared npm dependencies.

You likely have a dependency that depends on fsevents.

Closing as not a UI Bootstrap bug.
