### ISSUE TITLE
Popover placement bottom-right arrow doesn't align when using a template

### ISSUE THREAD

**Issue by midori0507** [angular-ui/bootstrap#5610]
### Bug description:

Popover placement bottom-right arrow doesn't align when using a template

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/rCZjwlwnACkyY8BUFsBY?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0
UIBS: 1.2.4

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
This looks correct in the Plunker to me - it is aligned with the bottom and right, although perhaps @RobJacobs might have more to add here.

**Comment by midori0507** [comment]
Just double check, doesn't work on mine and others machine.

**Comment by wesleycho** [comment]
What OS & browser?

**Comment by midori0507** [comment]
Window 10, Chrome 49
OSX 10.11.3, Chrome 48
OSX 10.11.3, Chrome 49
screenshot attached if you need it 
![bikwxu1](https://cloud.githubusercontent.com/assets/9389531/13639731/c15d9bbc-e61a-11e5-9497-1c73b0627244.png)

**Comment by RobJacobs** [comment]
@wesleycho The css selector for the arrow in the tooltip.css needs to be adjusted to include all the tooltip/popover flavors.  I'll create a PR shortly...
