### ISSUE TITLE
 Stop the carousel bootstrap when video html5 play automatically

### ISSUE THREAD

**Issue by fabdelgado** [angular-ui/bootstrap#5612]
I need to stop the carousel bootstrap when webm (Video HTML5) video play automatically. After finishing video, play the slider should continue.
The documentation does not specify.

Angular: 1.5.0

UIBS: 0.11.0

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@fabdelgado, please be respectful of our time by reading the project documentation and utilizing the issue template that you deleted to enter your support request.  As was stated in that text, the issues forum is not for support requests.

I suspect your issue may be related to #5471.
