### ISSUE TITLE
upgrade from 0.14.0 to latest stable version.

### ISSUE THREAD

**Issue by pgangwani** [angular-ui/bootstrap#5614]
Hello Team,
I am using UIB version 0.14.0 , it seems there are some huge number of changes in components based on issues. 
I am also facing some issues , so would like to upgrdae uib 0.14.0 to latest stable.
Could you please suggest which version I should be using and what functionality might be breaking after this upgrade ?

Please inform me so that I can proceed ahead.

Thanks in advance

**Comment by pkozlowski-opensource** [comment]
Check BREAKING CHANGES sections in https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md

**Comment by icfantv** [comment]
@pgangwani and be sure to read EVERY breaking changes section between your current version and the one to which you are upgrading.
