### ISSUE TITLE
Document popover-enable

### ISSUE THREAD

**Issue by twwwt** [angular-ui/bootstrap#5615]
After realizing that the tooltip an popover have much in common in their implementation, I checked whether `popover-enable` works the same way as `tooltip-enable`. Yes, it does. Now, the former is not documented on the Web site while the latter is. So, please document it.

Version used: 1.2.4; Angular 1.5.0.

**Comment by icfantv** [comment]
@twwwt, yes, popovers are essentially tooltips with some extra sugar.  The underlying code is shared.

Looks like we are missing the documentation for `popover-enable` and there's a typo in the popover documentation text:  `There are three versions of the popover: uib-popover and uib-popover-template, and uib-tooltip-html:` - that last one should be `uib-popover-html`.
