### ISSUE TITLE
UIB-Timepicker not updating first-row readonly in ng-repeat

### ISSUE THREAD

**Issue by Donny5300** [angular-ui/bootstrap#5616]
Using the uib-timepicker in a ng-repeat and add a readonly input, doesnt update the first datepicker row.

`<tr ng-repeat="row in rows">
	<td>
		<uib-timepicker ng-model="row.start_time" ng-change="validateTime($index)" readonly-input="rows.length > 1"></uib-timepicker>
	</td>
</tr>`

### Version of Angular, UIBS, and Bootstrap

"angular": "angularjs#^1.5.0",
"angular-bootstrap": "^1.2.1",

UIBS: Timepicker

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
Please post reproduction in Plunker.
