### ISSUE TITLE
redundant left property in arrow when using uib-popover-template

### ISSUE THREAD

**Issue by pgangwani** [angular-ui/bootstrap#5619]
Hello Team,
I found a bug when I used **uib-popover-template** in popover , left:50% was added for arrow , which was redundant. when i removed it arrow was perfectly fine. 

**markup with popover template:**
`<span search-pop-over popover-placement="bottom-right" popover-append-to-body="true"  uib-popover-template="searchPopover.templateUrl" popover-class="search-popover" popover-trigger="outsideClick" popover-is-open="searchPopover.isOpen" class="icon icon-page_magnifyer"></span>
`
![image](https://cloud.githubusercontent.com/assets/14316332/13679628/c2b20510-e71a-11e5-910a-b7b984fbea7b.png)

**markup with popover text : **
`
<span search-pop-over uib-popover="I am popover test" popover-placement="bottom-right" popover-append-to-body="true" popover-class="search-popover" popover-trigger="outsideClick" popover-is-open="searchPopover.isOpen" class="icon icon-page_magnifyer"></span>
`
![image](https://cloud.githubusercontent.com/assets/14316332/13679965/75b30212-e71c-11e5-8f3c-0f525012c3b4.png)

Popover template  position issue , I resolved using css  
`.arrow{left:auto}`

**One more issue: **
After solving this, 
When I scroll up and down the top position also distracts , please check this screen shot below:
top position changes on scroll
![image](https://cloud.githubusercontent.com/assets/14316332/13680392/62e5d20c-e71e-11e5-88d3-fc09b397bfc3.png)

Please revert if you are able to reproduce this issue.

**Comment by pgangwani** [comment]
<img width="737" alt="screen shot 2016-03-10 at 11 46 09 pm" src="https://cloud.githubusercontent.com/assets/14316332/13680455/9cc012a8-e71e-11e5-978b-ef7f7898263d.png">


<img width="738" alt="screen shot 2016-03-10 at 11 51 59 pm" src="https://cloud.githubusercontent.com/assets/14316332/13680471/aad19f2e-e71e-11e5-89b9-005ee0f5594d.png">

<img width="686" alt="screen shot 2016-03-11 at 12 14 57 am" src="https://cloud.githubusercontent.com/assets/14316332/13680477/b0184a14-e71e-11e5-8a93-64bd98edc502.png">

**Comment by icfantv** [comment]
Please clean this up dramatically and create a working plunker per our issue template.  I'm going to close this as it's incredibly difficult to follow and it's difficult for us to invest the time and resources to investigate in this current format.  I will reopen when this is rectified.

**Comment by RobJacobs** [comment]
This was addressed under PR #5611

**Comment by pgangwani** [comment]
Thanks both of you ... @Adam Will take care..
