### ISSUE TITLE
Setting minDate to future still allow to select today using button 'Today'

### ISSUE THREAD

**Issue by alephx** [angular-ui/bootstrap#5622]
On grid with days today is grayed. But pressing 'Today' closes popup and select today, breaking validation.

Tested with : 1.2.4

Example : 
[https://plnkr.co/edit/1WVFHHbktqEgHsWtepjK?p=preview](https://plnkr.co/edit/1WVFHHbktqEgHsWtepjK?p=preview)

**Comment by wesleycho** [comment]
Looking at the pre-existing code, this is a bug - I will have this fixed shortly.
