### ISSUE TITLE
uib-dropdown seems to be broken in some cases

### ISSUE THREAD

**Issue by mmonshausen** [angular-ui/bootstrap#5623]
Hi all,
I have a problem after upgrading my project to angular-ui-bootstrap 1.2.4:
The uib-dropdown-menu/menuitem are visible in closed state and clicks to toggle button seems to have no effect.

See following screenshot:
![bug-closed](https://cloud.githubusercontent.com/assets/2780316/13706760/bf36a0da-e7a6-11e5-8cf2-036bcac0688b.png)

sourceCode: 
`<div class="row">
                <div class="col-xs-6">
                    <div class="btn-group" uib-dropdown is-open="status.isopen">
                        <button type="button" class="btn btn-default" uib-dropdown-toggle>
                            Add Field<i class="fa fa-caret-down btn-icon-right"></i>
                        </button>
                        <ul class="uib-dropdown-menu" style="max-height: 115px;" role="menu">
                            <li role="menuitem" ng-repeat="tag in tags" ng-click="addTag(tag);status.isopen=false"><a>{{tag.value}}</a></li>
                        </ul>
                    </div>
                </div>
            </div>`

If I switch back to angular-ui-bootstrap 0.14.3 (same sourceCode). Everything is okay:
![working](https://cloud.githubusercontent.com/assets/2780316/13707140/90449816-e7a8-11e5-980e-a83713814670.png)
 
I am using angular-ui-bootstrap in Cordova.
Screenshots are taken on MacOSX Firefox (same issue when running on android).

Would you please mind to check was is wrong?

Kind regards and thanks alot,

Martin

**Comment by icfantv** [comment]
@mmonshausen, per the issue template you summarily deleted to enter this, please be respectful of our time by 1) reading the project documentation for prerequisites of entering issues, 2) following our issue template, and 3) understanding that the issues forum is not for support requests.

I'm closing this until you follow the template and can show that this is a bug in the library.  We simply do not have the time to investigate poorly written issues.
