### ISSUE TITLE
uib-datepicker-popup: Field is marked as invalid (ng-invalid-date) when you quickly change value in field back and forth

### ISSUE THREAD

**Issue by fullstackcreatives** [angular-ui/bootstrap#5625]
Starting with a valid value: If you delete a number and put in the same or a new one (for example: change the year from 2013 to 201 and then back to 2013 again) and you do it very fast then the text field sometimes stays in invalid state (red border). You can reproduce this even on the angular-ui website.

I use Firefox.

**Comment by icfantv** [comment]
@fullstackcreatives, please be respectful of our time by following our issue template and project documentation.  Managing a popular OSS repository requires a lot of work by many people - all of whom are unpaid volunteers.  We simply do not have the time to investigate issues that are not written per our instructions.

I'm sorry, but I'm going to close this until this is rectified.
