### ISSUE TITLE
[Datepicker] on [Popover] automatically closes [Popover] by second date-selection 

### ISSUE THREAD

**Issue by kcfinished** [angular-ui/bootstrap#5628]
Just test Popover with Template button in the example.

Example :
[(http://plnkr.co/edit/CSZqF1eeEyFoqfpe7CU7?p=preview)]

Bootstrap 1.2.4
Angular 1.5

**Comment by wesleycho** [comment]
You have to manually stop the click event propagation - see [here](http://plnkr.co/edit/ML8Uxdsl6ByX87bGZxie?p=preview) for an example.

**Comment by kcfinished** [comment]
thanks so much :+1:

**Comment by 845ben** [comment]
Works but sounds like a workaround to me

**Comment by icfantv** [comment]
@845ben, how would you propose we address this then?  Please keep in mind that it needs to not impact any other datepicker use case.  Additionally, it should not add any other API endpoints as the current API is already bloated.

**Comment by httpete** [comment]
Really bit me after upgrading to the latest, where popovers would suddenly come down when elements were removed or clicked.  ng-click="$event.stopPropagation()" around it or on it fixes it.
