### ISSUE TITLE
datepicker - doesn't trigger ngChanges callback on first manually typed invalid date

### ISSUE THREAD

**Issue by Hotell** [angular-ui/bootstrap#5629]
### Bug description:
datepicker doesn't triggers ngChange callbacka on inital invalid user input. When user deletes the invalid view value, ngChange is triggered, also when I start typing again, it will trigger correctly.

Open devTools console and start typing manually the input ( invalid date )

This is unexpected behaviour as ngChange should be triggered always as per ngModel lifecycle standard

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/oQHCw6zInopS30ifVkFt?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.9

UIBS: >=0.14.3

Bootstrap: latest/whatever
![uib-datepicker-bug](https://cloud.githubusercontent.com/assets/1223799/13751869/73ced67c-ea0c-11e5-8960-b5310f842618.gif)

**Comment by wesleycho** [comment]
This is how Angular behaves with regards to failed validation. If one wants ng-change to fire, one needs `ng-model-options="{allowInvalid: true}"`
