### ISSUE TITLE
Carousel wrong ordering

### ISSUE THREAD

**Issue by antonybudianto** [angular-ui/bootstrap#5638]
### Bug description:
Carousel wrong ordering, same as [this](https://github.com/angular-ui/bootstrap/issues/3764)

Try to click next slide, and the slide will jump from "slide 0" straight to "slide 6"
Also try to change UIBS version to `1.1.0` and it worked.
The slides work properly within 11 slides, it's broken on the 12th one

### Link to minimally-working plunker that reproduces the issue:
[Plunker](http://plnkr.co/edit/VI0xRHqPNuQ61Ty1Helg?p=preview)

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5

UIBS:
1.2.4

Bootstrap:
3.3.6

**Comment by icfantv** [comment]
_may_ be related to #5601.

**Comment by charlierudolph** [comment]
I believe the bug is here. https://github.com/angular-ui/bootstrap/blob/48f62a6dadaee110a4d6777088a20681878dd407/src/carousel/carousel.js#L18

For sort, the comparison function needs to return -1, 0, or 1. Returning a boolean doesn't work as false is 0 which means the two are considered equal.

**Comment by kirandas82** [comment]
Good catch.. Thank you
