### ISSUE TITLE
typeahead's(with append-to-body) menu doesn't get positioned.

### ISSUE THREAD

**Issue by akhlesh** [angular-ui/bootstrap#5639]
### Bug description:
It happens only when typeahead is in a container inside body which has its own scrollbar so when we scroll this inner container it doesn't invoke scroll event for typeahead as it is attached to body.

##### Plunker link that reproduces the issue:
[http://plnkr.co/edit/yOmhoLMbWN6SR0ycmr1M?p=preview](http://plnkr.co/edit/yOmhoLMbWN6SR0ycmr1M?p=preview).

To reproduce this issue scroll inner container when typeahead menu is visible.

**Comment by icfantv** [comment]
@akhlesh, we have the issue template for a reason.  It helps us save time when investigating issues.  In the future, please be respectful of that time by adhere to both it and our project documentation.  Thanks.

**Comment by icfantv** [comment]
@RobJacobs, can you please confirm whether or not this is a positioning bug?  Thanks.

**Comment by deeg** [comment]
This is something we deal with in our app too. I have seen this exact same issue in software like Jira.

Since it is being appended to the body in an absolute position the scroll does not effect it. One thing you could do to fix is bind to the scroll event and reposition on scroll, but even that can get difficult if there are multiple scrolls etc.

So while I consider this a bug, I consider it a far off edge case which is acceptable in our software. Interested to hear other people's thoughts.

**Comment by akhlesh** [comment]
@deeg yes its an edge case which is difficult to fix.

One solution that i can think of is to attach event on mousedown which will start interval that reset Position as we scroll and on mouseup event, interval can be canceled. it seems like non efficient way but we can make sure that event will be attached only when typeahead menu is visible and position will be reset only if position is changed.

Apart from this we need to handle mousewheel event also.

**Comment by wesleycho** [comment]
Perhaps we could bind a listener to the scroll event on the container and debounce a reposition. We do have a reference to the element, so it presumably wouldn't be difficult to do this.

I'm not against this if someone wants to implement this in a PR.

**Comment by akhlesh** [comment]
@wesleycho  we can get parent container with scroll bar and bind a listener to scroll event on this but it won't work as there may be any number of container which could change the position typeahead. 

We do have element reference but we don't know the container which can cause position reset.

**Comment by wesleycho** [comment]
Would it make more sense then to wrap your container within the scrollable container and then append to that?

**Comment by akhlesh** [comment]
Does it even matter where typeahead menu is appended as it is absolutely positioned?

**Comment by wesleycho** [comment]
If it is absolutely positioned inside a position: relative container that is inside the scrollable container, I believe that should work (haven't tried it yet though).

**Comment by wesleycho** [comment]
I took a look at this, I don't think this is a positioning bug. This is a usage problem where the container being appended to isn't a part of the scrollable container, so closing as a consequence.

**Comment by alejandroiglesias** [comment]
@wesleycho right, but if you use `dropdown-append-to-body` because the container has an `overflow: hidden or `overflow: auto` for scroll, then you have no solution for this issue. What do you suggest in those cases?
