### ISSUE TITLE
uib-popover-html does not appear

### ISSUE THREAD

**Issue by facboy** [angular-ui/bootstrap#5640]
### Bug description:

uib-popover-html does not work, the elements appear in the dom but have display: none.  this appears to be because the embedded CSS does not include it:

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/E8LbFEYHgxxFsVjge3NE?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 1.2.4

Bootstrap: 3.3.6

**Comment by facboy** [comment]
I have a feeling that the arrow positioning for uib-popover-template and uib-popover-html (and possibly uib-tooltip-template and uib-tooltip-html) is missing too.

**Comment by icfantv** [comment]
This is fixed in `master`.  Please be respectful of our time by searching existing issues (both open and closed - per our project documentation) before opening a new issue.

**Comment by facboy** [comment]
sorry about that, I forgot to remove the 'open' filter from the search...or look at master...novice mistakes.

**Comment by icfantv** [comment]
No worries.  Thanks.  It happens more often that you might think.
