### ISSUE TITLE
The date is set to 1st of month when user naivgated left or right in popup datepicker

### ISSUE THREAD

**Issue by jesselty** [angular-ui/bootstrap#5642]
When the user navigates left or right , the class used to identify the selected date ".btn-info" is set on 1st of month instead of date selected because of which the selected date becomes dis-highlighted.Please help me with this issue because its on the live uib datepicker example aswell so I am sure I am not making any mistake

**Comment by icfantv** [comment]
@jesselty, i'm going to close this until you are able to follow instructions.  We have the issue template for a reason - having it greatly reduces the time it takes to investigate issues.  Please be respectful of that time by using it and reading our project documentation.
