### ISSUE TITLE
IE10 datepicker missing saturday column + quickfix

### ISSUE THREAD

**Issue by szada92** [angular-ui/bootstrap#5645]
### Bug description:
In IE 10, the Saturday column is missing in the datepicker

Angular 1.4.9
UI Bootstrap 1.2.4

### Quick-fix

I have made a quickfix in the code, in [datepicker.js](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js) on line: 459-467
`
  this.getDates = function(startDate, n) {
    var dates = new Array(n), current = new Date(startDate), i = 0, date;

    // IE10 fix
    current = current.getTime();
    var dayInMillis = 24 * 3600 * 1000;

    while (i < n) {
      date = new Date(current);
      dates[i++] = date;
      current += dayInMillis;
    }
    return dates;
  };
`

As IE10 returned invalid dates via the setDate method, it gave null for every Saturday, by this, it returns at least a valid date object.

**Comment by wesleycho** [comment]
Can you explain why it gave null? A fix is no good in open source without a good explanation of what exactly is happening, and it appears that more research is needed before adding a potentially flawed fix.

**Comment by szada92** [comment]
Probably the IE10's JS engine makes things wrong, as while incrementing the date, when t

**Comment by szada92** [comment]
Probably IE10's JS engine produces the problem, as when the day of a JS Date object should be Saturday, it shows it as 'undefined'. So when the current date variable reaches Saturday, and we trying to create a new Date object of it, as (i think) it cannot parse the undefined string, where a valid day should be, and returns an 'Invalid Date'.

P.S.: I did a little overkill with this 'quickfix' - I did a little research, and if I've changed 
the following: `date = new Date(current);`
to this: `date = new Date(current.getTime());`
should do the trick.
![screenshot 2016-03-17 17 34 53](https://cloud.githubusercontent.com/assets/9250493/13853557/836f917c-ec67-11e5-9a2c-587e35450dae.png)

**Comment by wesleycho** [comment]
This sounds like an IE10 bug, and we shouldn't hack around.

In addition, IE10 is not supported by Microsoft except in a rare case. This hack also destroys date reference information, which comes with its own problems when it comes to timezones.

Closing this as something we won't fix.
