### ISSUE TITLE
IE 11 Scrollbar come in transparent behind the html, but in chrome fine

### ISSUE THREAD

**Issue by gopiece04** [angular-ui/bootstrap#5646]
### Bug description: The Scrollbar in IE come in transparent which is behind the html view.
Please give me the solution for scrollbar should not come behind the html view.

### Version of Angular:, UIBS, and Bootstrap
Angular:1.5.0

UIBS:1.2.4

Bootstrap:3.3.6

PFA for screenshot in IE, Chrome

![inchrome](https://cloud.githubusercontent.com/assets/4813050/13845948/84b5732e-ec69-11e5-8d89-4eebc4245e5f.png)
![in ie](https://cloud.githubusercontent.com/assets/4813050/13845949/84bb29ea-ec69-11e5-9f31-3ce927466464.png)

Regards
Gopinath BS

**Comment by icfantv** [comment]
@gopiece04, per the issue template you deleted, the issues forum is not for support requests.  Might I first suggest creating a simple, standalone angular app with some bootstrap CSS and HTML components tall enough to make the page scroll to see if this is even a UIBS issue?  I'm going to close until you do this but will reopen if you can show this is specifically a UIBS bug.

**Comment by RobJacobs** [comment]
This has nothing to do with the angular-ui-bootstrap library, it's the browser implementation.  You will notice the same behavior if you view the [TWBS](http://getbootstrap.com/) site.
