### ISSUE TITLE
uib-datepicker-popup: input is marked as invalid when you quickly change value in it

### ISSUE THREAD

**Issue by SlippySken** [angular-ui/bootstrap#5647]
I have the same problem as stated in #5625 .
The problem occurs on the sample page https://angular-ui.github.io/bootstrap/#/datepicker and in my application. When you change the date really fast from '17-March-2016' to '17-March-2015' by pressing backspace and then 5, the input is marked as invalid. I tried to reproduce this behaviour with my code and with the code on the sample page (by pressing "edit in plunkr") in a plunkr, but there it won't occur. I think the timing in plunkr is not the same as in a real application, because on your sample page the problem occurs.

### Version of Angular, UIBS, and Bootstrap
Angular: 1.5.0
UIBS:  1.2.4
Bootstrap: 3.3.6
Browser: Firefox 44.0.2

**Comment by wesleycho** [comment]
One can use the `debounce` option in `ng-model-options` for this - see [here](http://plnkr.co/edit/PMqsVgb4dvghKEeMta7H?p=preview) for an example.

**Comment by SlippySken** [comment]
ah, thanks :). Now it works :).
