### ISSUE TITLE
Bootstrap Modal Box scroll issues on print

### ISSUE THREAD

**Issue by niviaqua** [angular-ui/bootstrap#5657]
I am trying to have a print functionality on Modal box opened on top of a long parent webpage. The modal box has a scrollable div which I was able to get it printed by doing this:
 
<style>
 @media print {
   
 body * {
        visibility: hidden !important;
    }

    #container * {
     visibility: hidden !important;
    }

    #print-content * {
       
          visibility: visible !important;
            /**Remove scrollbar for printing.**/
            overflow: visible !important;
    }
    .modal {
        position: absolute;
        left: 0;
        top: 0;
        margin: 0;
        padding: 0;
        min-height:550px
         visibility: visible;
            /**Remove scrollbar for printing.**/
            overflow: visible !important;
    }
    .modal-body {
    max-height: calc(100vh - 210px);
    overflow-y: auto;
    }
}
</style>

 I can still see EMPTY PAGES from the parent webpage on which the modal was opened. I am trying to get this solved. If anyone is facing the same issue, pls chip in by forking this:
[https://jsfiddle.net/niviaqua/3zu008ch/83/](https://jsfiddle.net/niviaqua/3zu008ch/83/)

**Comment by icfantv** [comment]
@niviaqua, per the issue template you summarily dismissed, apparently without even reading, the issues forum is NOT for support requests.  please be respectful of our time and our project by adhering to the project documentation, which, had you read, you would have realized that there's a far better audience for support than the issues form, namely StackOverflow.  As such, I'm going to close this.
