### ISSUE TITLE
Typeahead. Invalid regular expression: /^*/: Nothing to repeat

### ISSUE THREAD

**Issue by Kamilius** [angular-ui/bootstrap#5662]
Upon trying to enter a `*` (Star) symbol into typeahead's input, I'm getting next error:
```js
Invalid regular expression: /^*/: Nothing to repeat.
```

Previously I've found that similar issue was already fixed in 2013: https://github.com/angular-ui/bootstrap/issues/316 . But now it doesn't seem to be fixed for me.

My version of `angular-ui-bootstrap` is `0.14.3`. I've also tried latest - `1.2.5` but it also didn't worked for me.

**Comment by wesleycho** [comment]
Not seeing this according to the demo, as can be seen [here](http://plnkr.co/edit/npqnrrJNQu2xPHJjNHbR?p=preview).

In the future, please do not ignore the issue template - it is there to save everyone time.

Closing due to invalid issue with no issue template usage.
