### ISSUE TITLE
Memory leak on inject uibModal

### ISSUE THREAD

**Issue by marcosdemelo** [angular-ui/bootstrap#5668]
When I inject the uibModal in my test, it generates memory leaks. The browser's memory goes there on high.

```javascript
describe("MyController", function() {
  "use strict";

  beforeEach(function() {
    module("ngAnimate");
    module("ui.bootstrap");

    inject(["$uibModal", function($uibModal) {
    }]);
  });

  for(var i = 0; i < 10000; i++) {
    it("Test", function() {
      expect(1).toEqual(1);
    });
  }
});
```

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.3

UIBS: 1.2.5

Bootstrap: bootstrap-sass-official: 3.3.1

I'm using chrome and karma-runner.

**Comment by wesleycho** [comment]
Can you reproduce this on Plunker using the Jasmine browser test runner?

**Comment by marcosdemelo** [comment]
Hi, the plunker link: https://plnkr.co/edit/TZkj9g2PJY8d1RYo7kE2

Monitor the memory consumption in scheduler browser task.

Thanks,
Marcos

**Comment by goliney** [comment]
Hi guys. I didn't read the actual spec, but this great article may help you with troubleshooting: [link](http://blog.thecodecampus.de/avoid-memory-leaks-angularjs-unit-tests/).

**Comment by olso** [comment]
+1

**Comment by fabioelizandro** [comment]
+1

**Comment by icfantv** [comment]
@olso, @fabioelizandro, please do not simply add `+1` to issues.  It adds no intrinsic value to the discussion and serves to only clutter up the thread.  Thanks.

**Comment by costafacchini** [comment]
Any news on this?

**Comment by wesleycho** [comment]
We will comment if there is news - please don't add unhelpful/content-less comments, as all it does is try to put pressure, which increases stress and decreases likelihood of overall library progression (as well as progress on this specific issue).

**Comment by wesleycho** [comment]
I did an investigation on this, and found that Plunker to be invalid. It contained two lines that appear to be the cause of the leakage, lines 8 and 12.
```html
<script>var c=new AudioContext,o=c.createOscillator();o.frequency.value=0,o.connect(c.destination),o.start(c.currentTime),window.addEventListener("mousemove",function(){setTimeout(function(){o.frequency.value=4e3*Math.pow(Math.random(),10),setTimeout(function(){o.frequency.value=0},100)},1e3+5e3*Math.random())});</script>
```

[This Plunker](https://plnkr.co/edit/WpDk1WSKRce108q2FEMd) demonstrates no leakage, as profiled on Chrome.
