### ISSUE TITLE
DatePicker Min/Max Date and NgModelOptions Timezone

### ISSUE THREAD

**Issue by loren138** [angular-ui/bootstrap#5679]
### Bug description:
If you use NgModelOptions to set a timezone, the min/max dates are still processed according to the local users timezone rather than that timezone creating improper select options.

In my example, if March 25th is select for start date, then March 25th should be the smallest date available in End Date.  If end date is then selected as March 26th, then March 26th should be the last date available in Start Date.  Depending on your timezone, your options will vary, but unless your timezone is GMT-0200, the options will show incorrectly.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/1fTFcwr68shkXHVT5GjS

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 1.2.5

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
This Plunker is invalid.

There was an issue before I found with regards to timezones and min-date/max-date that should be fixed in `master` & will be in the 1.3.0 release though.
