### ISSUE TITLE
Localization for russian

### ISSUE THREAD

**Issue by Lekmaby** [angular-ui/bootstrap#5684]
There are two sections for month in angular-locale_ru.js: MONTH and STANDALONEMONTH.

We should use STANDALONEMONTH when selecting month in Datepicker (январ**ь** - january), and MONTH when use it with date (21 январ**я** 2016 - 21 January 2016).

In English we write "January". But in Russian (and some other languages) we have different word endings in different cases (Январ**ь**, Январ**я**)

**Comment by icfantv** [comment]
@Lekmaby, please be respectful of our time by following the issue template.  it's there to ensure we can resolve issues in a timely manner.  I'm going to close this until the template is followed.
