### ISSUE TITLE
Popover arrow not positioned in the center of link element.

### ISSUE THREAD

**Issue by Rouche** [angular-ui/bootstrap#5685]
Hi,

We a problem when forcing "auto bottom" close to the edge of the screen.

The arrow is not positioned in the center of the parent, is there any way to fix this manually for us?

You can see when clicking the X : http://plnkr.co/edit/Ej1NfYa3Oj75ZUv0vFVB?p=preview

Not sure if its a good idea to provide some sort of callback for positionning?

Angular: 1.5.2
UIBS: 1.2.5
Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@RobJacobs, i vaguely recall a discussion around this.  Something having to do w/ margins maybe?  Can you please confirm if @Rouche's use case is correct?  Thanks.

**Comment by RobJacobs** [comment]
@icfantv, @Rouche  This is part of the reason we moved the tooltip inline styles to css classes.  See issue #5464 for reasons why this is happening and suggested fixes.

**Comment by Rouche** [comment]
Definatelly same bug. Not because i did not searched!

Closing, thanks for the link.

**Comment by icfantv** [comment]
@robjacobs, thanks.  I *thought* we discussed it before.

**Comment by Rouche** [comment]
Not same thing, it was to make a popover "optional" when "popover-visible" is always true.

Good memory sir!
