### ISSUE TITLE
ui-tab didn't displayed correctly when use string index

### ISSUE THREAD

**Issue by brutalcrozt** [angular-ui/bootstrap#5687]
### Bug description:
I am refering the doc:
>`index` - Tab index. Must be unique

it's clearly work when use tab without index attribute, so i made the reproduction both.
Here the [reproduction](http://run.plnkr.co/plunks/cCUWgu/)
### Version of Angular, UIBS, and Bootstrap

angular version `1.5.0`
uib `1.2.5`
bootstrap `3.3.6`
ngAnimate `1.4.2`

**Comment by wesleycho** [comment]
There is already a pull request (#5577) for implementing this.

I thought it's generally assumed one uses a number with an index, but I guess some people disagree...

**Comment by icfantv** [comment]
I don't think that guy is going to get around to finishing that, we may need to enter a new PR.

**Comment by wesleycho** [comment]
Closing, as this is already addressed in a release.
