### ISSUE TITLE
Canvas content disappears with a delay on tooltip on Chrome 49 on Mac

### ISSUE THREAD

**Issue by wolf-daniel** [angular-ui/bootstrap#5688]
### Bug description:

The content of an HTTP canvas disappears, when I have a tooltip with a delay, on a button that opens a new tab.

This is a very specific symptom, so I'd try to walk you through it:

1. It is reproduced only on Chrome 49 on a Mac.

1. To reproduce: click on the button (before the tooltip appears!), a new tab would be opened. Wait a few secs. Perhaps open another new tab. Then close all tabs and go back to the original tab. The shape of the canvas should disappear.

1. Upgrading the angular-ui-bootstrap version does not help.

1. It is not reproduced on other browsers, or on other OSs.

I also published the issue on stackoverflow:
http://stackoverflow.com/questions/36198813/canvas-content-disappears-on-chrome-49-on-mac-with-an-angularjs-tooltip

### Code to reproduce:

Unfortunately, I'm only able to reproduce it with the following HTML, and not in a plunker or jsfiddle:

    <html>
    <head>
        <style>
            .container {
                height: 300px;
                width: 300px;
            }
            canvas {
                border: 1px solid black
            }
            button {
                margin-top: 15px;
            }
        </style>
    </head>
    <body ng-app="CanvasTooltipApp">
        <div ng-controller="CanvasTooltipCtrl" class="container">
            <canvas id="myCanvas" height="300"></canvas>
            <button type="button" ng-click="clickMe()" tooltip="The Tooltip Text">Click Me</button>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.14.3/ui-bootstrap-tpls.js"></script>
        <script>
            angular.module('CanvasTooltipApp', ['ui.bootstrap']);
            angular.module('CanvasTooltipApp').config(function($tooltipProvider) {
                $tooltipProvider.options({popupDelay: 1500});
            });
            angular.module('CanvasTooltipApp').controller('CanvasTooltipCtrl', function($scope) {
                var canvas = document.getElementById('myCanvas');
                var ctx = canvas.getContext('2d');
                ctx.beginPath();
                ctx.arc(95, 50, 40, 0, 2 * Math.PI);
                ctx.stroke();
                $scope.clickMe = function() {
                    window.open('http://www.google.com', '_blank');
                };
            });
        </script>
    </body>
    </html>

### Version of Angular, UIBS, and Bootstrap

Angular: 1.3.15

UIBS: 0.14.3

Bootstrap: -

**Comment by wesleycho** [comment]
This sounds like a browser bug - I've seen similar issues happen with the Chrome developer tools.

I'm not sure I would consider this a library bug.

**Comment by wesleycho** [comment]
Going to close as a browser specific bug we cannot do anything about.

If there is a specific reproduction we can work off of, we can take a look, but I suspect there is nothing we can do about this.
