### ISSUE TITLE
Example of datepicker is using depreciated syntax

### ISSUE THREAD

**Issue by richfergus** [angular-ui/bootstrap#5691]
The example located: [https://angular-ui.github.io/bootstrap/#/datepicker
](https://angular-ui.github.io/bootstrap/#/datepicker
) has the depreciated `uib-datepicker-popup` syntax which issues this warning in chrome console:

> uib-datepicker settings via uib-datepicker-popup attributes are deprecated and will be removed in UI Bootstrap 1.3, use datepicker-options attribute instead

**Comment by wesleycho** [comment]
Not seeing this at all.

**Comment by richfergus** [comment]
Nope you're correct. I had a an extra attribute in my markup that I though came from the example....
