### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by darkylmnx** [angular-ui/bootstrap#5699]
Hi,

is there a built-in way to synchronise two datepickers ? like datepickers for booking hotels or flights etc

A Start datepicker & an End datepicker where both dates are linked together etc ?

Angular: 1.4

UIBS: last version

Bootstrap: 3

**Comment by darkylmnx** [comment]
apparently there's no built-in way. Watchers seems to be the only solution here

**Comment by icfantv** [comment]
You can write a wrapper directive that encapsulates two date pickers.  This issue has been discussed ad nauseum and there are multiple, closed issues addressing this.

**Comment by darkylmnx** [comment]
thansk, could you give some links of the relevant ones

**Comment by icfantv** [comment]
#2806, #2391, #1749, not to mention the PRs that people have opened.
