### ISSUE TITLE
Issue with alerts

### ISSUE THREAD

**Issue by ctjhoa** [angular-ui/bootstrap#570]
Hi guys,

I make an angular app with yeoman. All my modules are installed by bower.

```
`--> bower list
├── angular#1.0.7
├─┬ angular-bootstrap#0.4.0
├─┬ angular-cookies#1.0.7
├── angular-grid#2.0.6
├─┬ angular-mocks#1.0.7
├─┬ angular-resource#1.0.7
├─┬ angular-sanitize#1.0.7
├─┬ angular-scenario#1.0.7
├─┬ bootstrap#2.3.2
├── es5-shim#2.1.0
├─┬ jquery-ui#1.10.3
├── js-base64#2.1.2
├── json3#3.2.5
├── lodash#1.3.1
├── plupload#1.5.7
├── requirejs#2.1.6
└─┬ restangular#1.0.2
```

Others components (modals, collapse etc ..) are ok but I've got an issue with alerts and I don't understand why:

```
Error: Failed to load template: template/alert/alert.html
```

This is the associate code:

``` html
<alert type="error">foobar</alert>
```

Do you know if I missed something? or if it's a bug?

Thanks

**Comment by kwisatz** [comment]
:+1:  for an explicit note of this in the docs

**Comment by rvanbaalen** [comment]
Its already there @kwisatz. See demo / docs first paragraphs. And the wiki for that matter.
