### ISSUE TITLE
startingDay will be NaN when using an older version of angular-i18n

### ISSUE THREAD

**Issue by MacDschie** [angular-ui/bootstrap#5700]
### Bug description:

Until now, I used v1.3 of angular-i18n, which has no FIRSTDAYOFWEEK value on the $locale service. When you use the uib-datepicker-popup without datepicker-options, then the startingDay gets initialized to NaN (line 2018 of ui-bootstrap-tpls.js) and opening the datepicker throws some errors on the console when rendering the week numbers. The numbers are just missing in the display, everything else seems to run fine.

I resolved the problem by updating angular-i18n, but maybe you guys want to implement a check here and use some hard-coded default when FIRSTDAYOFWEEK isn't available.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.3

UIBS: 1.2.5

Bootstrap: 3.3.4

**Comment by wesleycho** [comment]
We support only Angular 1.4+, and so any other first party libraries by the Angular team should always match the version of Angular being used.

Closing as a usage issue.

**Comment by MacDschie** [comment]
Then you could write that down in the dependencies section of the "Getting started" documentation. angula-i18n is not mentioned there. There, you could also tell your users what happens, when angular-i18n is not installed at all - or if it's mandatory. In the code, it looks like it is.

**Comment by wesleycho** [comment]
This is something pretty standard when using Angular, and not unique to this library - Angular.js itself bundles the us-en version from i18n by default, and all of the angular first-party libraries such as ngRoute, ngAnimate, etc. are all meant to have the same version used as Angular.

This is very clearly a user error here.

**Comment by MacDschie** [comment]
I see. I didn't know about the bundling. Then you are on the safe side when someone uses no i18n.
