### ISSUE TITLE
On carousel hide prev when index is 0 and next when index is slides.length - 1

### ISSUE THREAD

**Issue by plondon** [angular-ui/bootstrap#5704]
It's unnecessary to have next and prev arrows if you can't go forward or back respectively and the carousel is not infinite.

**Comment by deeg** [comment]
Not sure if they should be hidden or maybe a class should be added to the arrow for the user to add disabled state or hide themselves through CSS.

@wesleycho, thoughts? Maybe this has come up before, and a decision was already made?

**Comment by icfantv** [comment]
One can easily override this in the template directly.  I'm ambivalent here on whether or not to do something in our library.  @wesleycho, thoughts?  I could go either way.

**Comment by wesleycho** [comment]
Would be an easy feature to integrate I think - I'm ok with this.

**Comment by icfantv** [comment]
Coolness, @plondon, pelase feel free to submit a PR w/ tests.

**Comment by deeg** [comment]
Just to be clear, would you guys rather a class be added where the user can decide what happens, or have it be in a disabled state, or remove it all together in this case?

**Comment by wesleycho** [comment]
ng-show/ng-hide usage - a user can override the template if he/she wants otherwise.

**Comment by plondon** [comment]
#5708
