### ISSUE TITLE
Timepicker on <input /> tag: model is undefined

### ISSUE THREAD

**Issue by jekser** [angular-ui/bootstrap#5705]
### Bug description:
Model is undefined after UI-change. Spinners works well, but after direct input the model is undefined.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/UzER1XUzfMYkHTnkjo8Z?p=preview

### Version of Angular, UIBS, and Bootstrap
Angular: 1.5
UIBS: 1.2.5
Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
You actually want to use this control with a `div` - see [here](http://plnkr.co/edit/n7HEPGXBse731fQd0BHO?p=preview).

Going to close as a simple usage issue.

**Comment by jekser** [comment]
This workaround is known. The problem is, if I add angular functionality to my page, I MUST change my working code... It's not very good. Apart from then, an <input>-tag is semantically correct. Can You fix it?

**Comment by wesleycho** [comment]
This is probably not something we can support - the input directive modifies the ng-model flow.

It would be better for you to change to use another element.

**Comment by jekser** [comment]
Should I do it for all input- and select- tags?

**Comment by wesleycho** [comment]
Yes.
