### ISSUE TITLE
datepicker doesn't work inside ng-if or ng-switch with new style datepicker-options

### ISSUE THREAD

**Issue by petttro** [angular-ui/bootstrap#5710]
If change datepicker options from element attributes to datepicker-options atribute inside ng-if it's stop working correctly.

this works:
```
<ng-if/ng-switch ...>
... 
<uib-datepicker ng-model="selectedDate"
		          show-weeks="false"
			  format-day-title = "MMM yyyy"
			starting-day ="1">
</uib-datepicker>
```
and this doesn't:
```
<ng-if/ng-switch ...>
... 
<uib-datepicker ng-model="selectedDate"
		          datepicker-options="options">
</uib-datepicker>
```

**Comment by RobJacobs** [comment]
Seems to be working for me.  Here is a [plunk](http://plnkr.co/edit/R5o0uWeJ6QwQvM9Qlecl?p=info) with the latest build from master.  Closing until the problem can be demonstrated.

**Comment by icfantv** [comment]
@petttro, in the future, please be respectful of our time by adhering to the issue template.  Using it allows us to serve you more quickly.  Ignoring it will simply result in the issue being closed.  Thanks.
