### ISSUE TITLE
Document migration steps for paginationConfig on wiki

### ISSUE THREAD

**Issue by surry** [angular-ui/bootstrap#5717]
The change from `paginationConfig` to `uibPaginationConfig` is not documented in the migration guide on the wiki under **Pagination**. I ran into an issue injecting that after upgrading ui-bootstrap from 0.13.0 to 1.2.5. After looking at pagination.js in 1.2.5, I changed to `uibPaginationConfig` and I'm not seeing the injection issue any more.

Created a new issue per the discussion on #5364.

**Comment by wesleycho** [comment]
Looking at the wiki [here](https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes), it looks like all of the service/injectable mention is encapsulated in the last two lines.
```
There are also prefixes on controllers, directives and services that were meant to be private. Check the source if you still get some warnings.
```
What are your thoughts on more detailed mentions here @Foxandxss and @icfantv ?

**Comment by Foxandxss** [comment]
We can add that too, why not.

**Comment by wesleycho** [comment]
Updated the wiki - closing this issue, should be addressed now @surry
