### ISSUE TITLE
uib-accordion-group directive removing <form> tag from template 

### ISSUE THREAD

**Issue by nithishj** [angular-ui/bootstrap#5718]
My Template:
```
<uib-accordion close-others="true">
<uib-accordion-group is-open="guest.isopen" ng-init="guest.isopen=true">
    <uib-accordion-heading>
	   <span>Checkout as a guest</span>
    </uib-accordion-heading>
	<form class="form-horizontal"  ng-submit="onUserRegister(guestuser)" >
			<!-- Text input-->
			<div class="form-group">
				<label class="col-md-4 control-label" for="Emailaddress">Email Address</label>  
				<div class="col-md-5">
				<input id="Emailaddress" name="Emailaddress" placeholder="Email Address" class="form-control input-md" required="" type="email" ng-model="guestuser.email">

				</div>
			</div>

			<!-- Button -->
			<div class="form-group">
				<label class="col-md-4 control-label" for="continue"></label>
				<div class="col-md-4" style="padding-top:20px">
				<button id="continue" name="continue" class="button" type="submit">Continue</button>
				</div>
			</div>
	</form>
</uib-accordion-group>
</uib-accordion>
```

clicking button "continue" of type=submit never triggers ng-submit event.
I checked the rendered html in console and it doesn't show the form tag.
Attached Image:
![capture](https://cloud.githubusercontent.com/assets/7048218/14176763/4d7bafba-f770-11e5-87d6-72d9c90995b4.JPG)

**version:**
    _"angular-bootstrap": "~1.1.2",
    "angular": "~1.5.0",
   "bootstrap": "~3.1.1",_

**Comment by icfantv** [comment]
@nithishj please be respectful of our time by adhering to the issue template.  In this case, we require a minimally working plunker to show the issue.  You may use the link in our demo page to get you must of the way there - you would just need to add your form.  Thanks.

**Comment by nithishj** [comment]
It is working fine in plunkr.
http://plnkr.co/edit/KmW69Y4cdaoOsanVfqul
Someother  plugin might having messing up with my template.

**Comment by icfantv** [comment]
Thank you.
