### ISSUE TITLE
Update tab directive's select method to allow for event.stopPropagation()

### ISSUE THREAD

**Issue by icfantv** [angular-ui/bootstrap#5720]
The current `select` method on the `uibTab` directive does not allow the user to stop the selection process via `event.stopPropagation`.  We need to add an `if` block to check for this and not change tabs if the user's stopped the propagation.

Here's the relevant code:  https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js#L161-L173

We need to update the documentation as well.

This addresses comments/concerns in #2715, #4836, and #5716.

**Comment by icfantv** [comment]
So this turns out to be not as easy as we'd like.  From a logic flow perspective, it is not right that the `select` method on the NEW tab be called to determine whether or not it's ok to leave the OLD tab.

A better solution, at the expense of API bloat, would be to add a `beforeChange` function to the tab (that defaults to noop) that would be called before the switching of the tabs is allowed.  In that function we'd check the `event.defaultPrevented` property.

**Comment by icfantv** [comment]
Currently looking at leveraging the `deselect($event)` method.

**Comment by icfantv** [comment]
Using `deselect($event)` provides an acceptable solution.  See [this plunker](http://plnkr.co/edit/N8ingGJbRASW76oW7ctK) for the demo - the "Static title" tab is not unselectable.

**Comment by daniel-jann** [comment]
The fix doesn't work for me: evt.defaultPrevented is undefined. I figured it's because I included the full jQuery library which redefines events with a isDefaultPrevented() instead of the standard defaultPrevented. I'm not sure where the fix should take place. On one hand I think it would be nice that jQuery follows standards but on the other hand I thought angular was supposed to work fine with the full jQuery library as is...

**Comment by icfantv** [comment]
@daniel-jann, actually, you're sort of right.  Angular found this issue as well and augmented their event object with the same method from jQuery (and even included a comment as to why):

```
function createEventHandler(element, events) {
  var eventHandler = function(event, type) {
    // jQuery specific api
    event.isDefaultPrevented = function() {
      return event.defaultPrevented;
    };
...
```

I'm going to reopen and fix.
