### ISSUE TITLE
timepicker variable date, hard to compare.

### ISSUE THREAD

**Issue by lmcmgig** [angular-ui/bootstrap#5722]
### Bug description:
timepicker create a new Date with the current time.  Result if you try to compare the output without processing the date itself, the same time (i.e. 16h00) can be different.  Using always the same time reference ease the comparaison.

Proposed code modification:
.controller('UibTimepickerController', ...
  var selected = new Date(0),  //or 86400000 if you don't like negative number when offsetting for the timezone and using getTime().

### Version of Angular, UIBS, and Bootstrap
Angular 1.5.0
UIBS 1.2.4
Boostrap 3.3.6

**Comment by icfantv** [comment]
@lmcmgig, please be respectful of our time by creating a minimally working plunker with the issue and proposed fix.  You can use the plunker link in our demo page to get you 19% of the way there.

**Comment by lmcmgig** [comment]
Hi,

     I wish, but the result will be the same visually speaking.  The 
back-end code using it will be simplier.  Plunker doesn't help in that case.

Mathieu Giguere

**Comment by icfantv** [comment]
This is a breaking change because instead of defaulting to now(), it's now defaulting to 01JAN1970...

Can you please elaborate further in order to provide some justification....?

**Comment by icfantv** [comment]
Ok, maybe I'm just not following...

**Comment by lmcmgig** [comment]
For example, I'm using the date in a JSON.  In the application I need to 
identify changes to allow some behaviour.  But 16h00 of any day is 16h00 
in a timepicker.  So if you use the timepicker on 2 different day the 
date in the back will not be the same even if the time (16h00) is the same.

We can process at an higher layer, but verybody using the library will 
need to code the same thing (more or less).

Regards,
Mathieu Giguere

**Comment by icfantv** [comment]
Ahhhh.  I got it.  Thanks.  @wesleycho, @Foxandxss thoughts?

**Comment by wesleycho** [comment]
Closing as won't support, or extremely vague/poorly worded - parsing the sentences hurts my head.

We have decided that due to the special issue in #5485, we are recommending that the date object used in the timepicker is separate from any other date usage, and we will be requiring that users process the two models appropriately.
