### ISSUE TITLE
carousel sequence problem

### ISSUE THREAD

**Issue by carlosMoncada** [angular-ui/bootstrap#5724]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I have a problem with sequence transition, when I load more than 10 slides. sequences becomes crazy skip sequence order and didn't follow index order.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/DUtA2cHnZkM2ZVp91fAE?p=preview
### Version of Angular, UIBS, and Bootstrap

Angular:
angular 1.5.0
animate 1.5.0
UIBS:
angular-ui-bootstrap 1.2.5
Bootstrap:
Bootstrap 3.3.6

**Comment by icfantv** [comment]
@carlosMoncada, this is fixed in `master`.  In the future, please be more respectful of our time by searching both open and closed issues before entering anything.  Thanks.
