### ISSUE TITLE
uib-tab won't toggle active class if uib-tab index is set to dynamic key

### ISSUE THREAD

**Issue by rajputvai** [angular-ui/bootstrap#5725]
**Bug description:**

When I assign dynamic key to index uib-tab and try to change it on button click, only tab content will change but tab won't change. It will not add active class to the changed tab (ul li).

__EDIT :__
It will add active class if you click on the tab.

**Link to minimally-working plunker that reproduces the issue:**

http://plnkr.co/edit/nCpLE1DVwhME6doXAOha?p=preview

**Version of Angular, UIBS, and Bootstrap**

Angular: 1.5.0

UIBS: 1.2.5

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@rajputvai, this has already been (quite recently) reported and rejected as a feature we are not going to support.  In the future, please be more respectful of our time by searching both open and closed issues before entering anything.

**Comment by icfantv** [comment]
See #5654 for details.

**Comment by rajputvai** [comment]
I searched in both open and closed issues didn't get it so reported it. #5654 content looks not so relevant might be the reason of not appearing. 

@lunhat79: The document say the index is UNIQUE. So i think we could solve the problem by determine the index is unique and the model (scope) is change following the Index.
^ Even I too thought the same. Anyways it is the limitation.

**Comment by icfantv** [comment]
@rajputvai - apologies for not looking at the plunker - i was on my mobile and couldn't as plunker's site does not lend itself to mobile viewing.  The `index` property does not accept a string value yet.  We are working on a PR #5713 and issue #5687 to add this feature.  Please follow this PR for status.  Thanks.

**Comment by rajputvai** [comment]
Will follow that PR. Thanks.
