### ISSUE TITLE
issue with popover control

### ISSUE THREAD

**Issue by Pradeepsh8** [angular-ui/bootstrap#5726]
I could find a problem with popover where I am setting popover-trigger="outsideClick". But nothing happens.

If I keep popover-trigger="focus" , my popup is shown but when I click in the popup's scroll bar which was opened, the popup div disappears. Is it a known problem  or is there any way this could be solved,

This problem is faced when using IE 11. forgot to point out

**Comment by icfantv** [comment]
@Pradeepsh8, please be respectful of our time by adhering to the issue template.  It is there for a reason, namely, to assist us in helping you and determining if this is a bug or user error.  I'm going to close this until you can follow instructions and will reopen when you do.  Thanks.
