### ISSUE TITLE
Close dropdown menus when document's contextmenu event fires

### ISSUE THREAD

**Issue by viveleroi** [angular-ui/bootstrap#5727]
### Bug description:

Dropdown menus close automatically when the document `click` event is fired outside of the menu. We need these menus to close when a `contextmenu` event is fired.

### Link to minimally-working plunker that reproduces the issue:

In lieu of a plunkr (this is a feature request) - you can see that the only events currently used to close these menus are `close` and `keydown` (partially):

https://github.com/angular-ui/bootstrap/blob/c534cb4a945284247c067698cc949a2576efb10b/src/dropdown/dropdown.js#L13 

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.2.5

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
One can easily create a wrapper directive to do this with the dropdown `is-open` binding.

The important question here is why should this be in the library itself?

**Comment by viveleroi** [comment]
Because that's more consistent with how other UIs work. Windows, Mac, most applications, etc only allow a single menu open at a time.

**Comment by wesleycho** [comment]
Reason I ask is because this would be a breaking change that some people don't want as a default behavior, and would result in the library having to have config to disable it - the whole point of the `is-open` binding is to allow users to implement the conditions that make the most sense for them.

**Comment by piyush-dholariya** [comment]
Hi All,
I want to use Typeahead functionality to get ajax call on time interval but I do not want to show list of items's pop up. How can I prevent to show that popup?

**Comment by wesleycho** [comment]
Closing this as something that isn't to be supported in the library itself.
