### ISSUE TITLE
Documentation site has errors

### ISSUE THREAD

**Issue by genu** [angular-ui/bootstrap#5728]
Maybe its just me, but the documentation site has js errors and it doesn't seem to load. 

Browsing to https://angular-ui.github.io/bootstrap/ loads a blank page.

**Comment by wesleycho** [comment]
I see it working just fine - closing as not an issue.

Do you have JavaScript disabled?

**Comment by christopherthielen** [comment]
works for me too.

**Comment by Cellery72** [comment]
I tried a few different browsers, was your issue with Chrome? Try disabling extensions, I did and it loaded fine. I'm pretty sure it's uBlock Origin causing the issue.

**Comment by icfantv** [comment]
this is now fixed - even with an adblocker installed.
