### ISSUE TITLE
Missing Folder in Tree

### ISSUE THREAD

**Issue by alejandroPenafiel** [angular-ui/bootstrap#5730]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
All the "templateUrl" in the library point to a folder "template" that is suppose to be under "uib/" 
the quick fix was to make that folder and move the "template" folder over there

### Version of Angular, UIBS, and Bootstrap

"dependencies": {
    "angular": "^1.5.3",
    "angular-animate": "^1.5.3",
    "angular-gridster": "^0.13.3",
    "angular-route": "^1.5.3",
    "angular-ui-bootstrap": "^1.2.5",
    "bootstrap": "^3.3.6",
    "jquery": "^2.2.2"
  }

**Comment by icfantv** [comment]
@alejandroPenafiel, it's not at all clear what you are saying.  The value of the `templateUrl` firstly refers to the key in the `$templateCache` and if there is not an entry in cache for that string, angular requests it from the server.  The actual path is totally superfluous and can be anything.  It does not have to refer to a physical directory structure.

Also, when indicating library versions in issues, it is important to only list the minimally necessary libraries.  In our case, this is core angular, bootstrap CSS, our library version, and maybe angular-animate (which should be the same version as angular).

I'm going to close this until you can elaborate further what it exactly is that you mean.
