### ISSUE TITLE
ui.bootstrap.tabs errors with ngCsp (DOM manipulation)

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular-ui/bootstrap#5736]
This is a suggestion for the ui.bootstrap.tabs module. The module stops on the "ensureSafeObject" function when processing the uibTabHeadingTransclude directive, due to the scope.$watch( 'headingElement', function updateHeadingElement(heading) { ...} trying to access/manipulate the DOM. This only happens for ngCsp, (which hardly anyone appears to actually use), but the work-around/fix is easy.

I changed this line in the uibTabContentTransclude directive:

            //Let tabHeadingTransclude know.
            tab.headingElement = node;

to this:

            //Let tabHeadingTransclude know.
            tab.headingElement = angular.element(node).html();

I can't say this is the best way to fix it, but it does seem to work.

### Version of Angular, UIBS, and Bootstrap

Angular: v1.5.2 (or any recent)

UIBS: v1.2.5

Bootstrap:

**Comment by deeg** [comment]
It would help us investigate this issue if you add a plunker which demonstrates the problem.

Please try to adhere to the issue template, which calls for a plunker, in the future.

**Comment by OpenSiteMobile** [comment]
Thanks for the reply. With more investigation, it seems more an issue with Angular than Angular-UI-Bootstrap. I only came across the problem due to the fact my version of Angular uses the function ensureSafeObject (not the self.ensureSafeObject version) for everything. I only use the ASTInterpreter, not the ASTCompiler one (I removed that code). I thought this was the norm for the ng-csp directive, but that doesn't seem to be the strictly the case. To tell you the truth, I can't figure out what the ng-csp directive does of much value, or how to engage expensive checks, and don't have the time to bother figuring it out.

Anyway,  it isn't a real problem for anyone else since I couldn't get the current versions of Angular and Angular-UI-Bootstrap to cause the error by engaging ng-csp. By the way, ng-csp only seems to work when applied to the html element in my version of Linux Chrome (I've seen examples use the body tag). Please just close this issue out. At least the info is here if others happen to run into the same problem.

**Comment by icfantv** [comment]
Closing per comments.
