### ISSUE TITLE
Form $dirty and $valid broken with fields inside tabs

### ISSUE THREAD

**Issue by rosslavery** [angular-ui/bootstrap#574]
I'm not sure if this is an implementation issue on my end, or a bug with the tabs directive, but I've asked around and most responses I've gotten seem to indicate it might be the latter.

When form fields are inside tabs, and that tabset is nested inside a `<form>`, the form's $dirty and $valid properties are not affected by the field(s) inside the tabset.

Plunkr here: http://plunker.co/edit/dCSE1jyLYIWY342mQfAl?p=preview

**Comment by amirensit** [comment]
Is this fixed with angular 2 because I face this problem.
