### ISSUE TITLE
demo page error.

### ISSUE THREAD

**Issue by vazh** [angular-ui/bootstrap#5740]
i get empty pages in ui.bootstrap demo page.

console says ::

angular.js:38 
Uncaught Error: [$injector:modulerr]
http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=ui.bootstrap.demo&p1=ReferenceError%3A%20FastClick%20is%20not%20defined%0A%20%20%20%20at%20http%3A%2F%2Fangular-ui.github.io%2Fbootstrap%2Fassets%2Fapp.js%3A3%3A3%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0%2Fangular.min.js%3A41%3A295)%0A%20%20%20%20at%20d%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0%2Fangular.min.js%3A39%3A234)%0A%20%20%20%20at%20http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0%2Fangular.min.js%3A39%3A358%0A%20%20%20%20at%20n%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0%2Fangular.min.js%3A7%3A355)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0%2Fangular.min.js%3A39%3A135)%0A%20%20%20%20at%20fb%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0%2Fangular.min.js%3A43%3A164)%0A%20%20%20%20at%20Ac.c%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0%2Fangular.min.js%3A20%3A449)%0A%20%20%20%20at%20Ac%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0%2Fangular.min.js%3A21%3A259)%0A%20%20%20%20at%20fe%20(http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.0%2Fangular.min.js%3A20%3A69

**Comment by icfantv** [comment]
@vazh, our demo page is working fine.  please check your browser plugins and whatnot.

**Comment by icfantv** [comment]
@vazh another thing to try is restarting your browser.  we had another issue filed for the same reason #5729 and it was that guy's extensions - but he neglected to mention which one.

**Comment by vazh** [comment]
yeah, thanks.
trying with firefox. it loads fast.
i disable my abp then it works. but it loads super slow.
havent try restarting my browser.

probably because of proxy too.

**Comment by icfantv** [comment]
oh geez.  do you have some sneakernet in there as well - for good measure?  ;-)
glad it's working now.  not sure why it would load slow - the only thing we do is GA and that _should_ be async.

**Comment by vazh** [comment]
eh sorry, i dont understand sneakernet even after googling it. haha.
after i enabled abp again. the error returns. its blocking fastclick. and then angular error came out.
both mozilla and chrome got abp extension. both have the same filter.
and yet the one in chrome block it.
not because of proxy. both browser set to connect to proxy.

**Comment by icfantv** [comment]
this is now fixed - even with an adblocker installed.
