### ISSUE TITLE
The 1.3.0 release broke the docs page

### ISSUE THREAD

**Issue by jpmckearin** [angular-ui/bootstrap#5741]
Looks like there was a step missed in the build process. The minified ui-bootstrap-tpls file was not generated.

![image](https://cloud.githubusercontent.com/assets/6679168/14271652/8eeca3c0-fac0-11e5-89c6-d0b870eb1f7b.png)

**Comment by storkme** [comment]
why was this closed? Issue is still present I think?

**Comment by icfantv** [comment]
@storkme, did you try forcing a refresh of the page and/or restarting your browser?

**Comment by storkme** [comment]
My apologies, think it got cached by something in my network! All good now.

**Comment by icfantv** [comment]
@storkme no worries - we've seen some issues for those behind a proxy.  thanks.

**Comment by icfantv** [comment]
this is now fixed - even with an adblocker installed.

**Comment by jpmckearin** [comment]
Sorry for closing without an explanation. Minutes after I opened the issue it was resolved, so I just chalked it up to someone still in the process of building, etc. I can verify that my problem was not because of caching.
