### ISSUE TITLE
Carousel broken after upgrade to 1.2.x

### ISSUE THREAD

**Issue by liamkennedy89** [angular-ui/bootstrap#5742]
The plunker on the bootstrap homepage: http://plnkr.co/edit/jvN4YPPQZbFnOi4KdvM4?p=preview

**Comment by wesleycho** [comment]
Looks like lorempixel broke @Foxandxss

**Comment by deeg** [comment]
Looks like there service is fixed. Should we close this, or were you thinking about getting off their service in favor of local files or something?

**Comment by wesleycho** [comment]
I'm fine with this being closed if this is resolved (on my phone at the moment)
