### ISSUE TITLE
Typescript: Documentation and Source Code Mismatch For Resolve in Modal Options

### ISSUE THREAD

**Issue by pixelshaded** [angular-ui/bootstrap#5748]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8853/files

I've created a pull request to update the typescript definition for the IModalSettings interface so that it matches the documentation. The desire to make this change originated in our own project when we tried to resolve an array of objects and started getting exceptions. When we looked at the docs, they mention that resolve is modeled after resolve in ui-router.

https://github.com/angular-ui/ui-router/wiki

This states that the value is a string or a function. So we started refactoring everything so the values were functions that returned the object we wanted.

However, when I started to look at the source code for angular-ui-bootstrap, I see this on line 79 of https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js (invocables is the resolve object):

```javascript
angular.forEach(invocables, function(value) {
            if (angular.isFunction(value) || angular.isArray(value)) {
              promises.push($q.resolve($injector.invoke(value)));
            } else if (angular.isString(value)) {
              promises.push($q.resolve($injector.get(value)));
            } else {
              promises.push($q.resolve(value));
            }
});
```

We can see that the code is using the $injector service and that it accepts just about anything (if it is not a function, array, or string, the code resolves the promise with the value itself). If we look at the docs for invoke, we can see why we were having trouble with our object array:

https://docs.angularjs.org/api/auto/service/$injector

Invoke takes either a function or an injection array (i.e. a collection of strings representing dependencies followed by a factory method). Since our last item in the array was an object rather than a function, we get our error.

So here is the struggle. Do I model the typescript definition off the documentation provided (aka what you see in the pull request) or off the source code (deny pull request - change nothing)? The documentation is fairly strict on what the values of the resolve keys can be, but the reality is that you can pass just about anything unless it is an array. 

What this means is that the more explicit definition will fail to compile in situations where the code would actually work, where as the less explicit definition will compile in situations where the code would fail at run time.

**Comment by wesleycho** [comment]
Going to close this as the DefinitelyTyped PR got merged.
