### ISSUE TITLE
Text input: text getting deleted upon pressing del/esc when cursor is at beginning of word

### ISSUE THREAD

**Issue by arijit550** [angular-ui/bootstrap#5753]
### Bug description:

Start typing in any of the input boxes http://angular-ui.github.io/ui-select/demo-multiple-selection.html
Place your cursor before the first character i.e. 0 position. Press delete or backspace, whole text gets cleared. Issue is not reproducible for other position of cursor. For all other positions of the cursor.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 0.16.1

Bootstrap: 3.3.6

**Comment by RobJacobs** [comment]
This is the wrong repo, you need to post your issue [here](https://github.com/angular-ui/ui-select)
