### ISSUE TITLE
datepicker, documentation update : customClass / dateDisabled

### ISSUE THREAD

**Issue by Rouche** [angular-ui/bootstrap#5757]
Hi,

customClass / dateDisabled function calls now (dont know since when) uses an object parameter,
{date: date, mode: $scope.datepickerMode}

Just a little update in the doc page.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3
UIBS: 1.3.1
Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
Feel free to file a PR :) .

**Comment by Rouche** [comment]
Ok, night take some days tough :P

**Comment by felixruponen** [comment]
+1
