### ISSUE TITLE
Typeahead : hover on select runs digest on view ?

### ISSUE THREAD

**Issue by iwarner** [angular-ui/bootstrap#5758]
### Bug description:

Hiya when a typeahead is invoked, hovering over the select list with my mouse seems to invoke a digest/apply

Using the keys to traverse up and down the list does not

Basically need to investigate the event being called on hover of the select and how to disable a page apply

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.0

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@iwarner though most of this is clear, please be respectful of our time and adhere to the issue template and create a plunker.  doing so allows us to address issues faster.  please remember that we are all unpaid volunteers.  thanks.

**Comment by iwarner** [comment]
I will try - its a bit of a bizaree one so to aid you I have been debugging all day to find the simple root cause - I threw this up to help.. not to hinder !

**Comment by icfantv** [comment]
@iwarner not harping here - it was a good description.  far better than many we get (including those with plunkers).  in this case, the plunker would immediately show us the issue - it also allows us to swap out the `<script>` include for the web-hosted version of the library for one we build locally allowing us to make tweaks to get a better understanding of what's happening and to also try out fixes.

**Comment by wesleycho** [comment]
Actually, this does not need a Plunker - if you look in the typeahead popup template, we are using ng-mouseenter.

**Comment by wesleycho** [comment]
I am not sure this is a bug though - this is how the active selection is determined.

**Comment by iwarner** [comment]
Yes indeed you are calling selectActive - but this in term probably fires a digest or apply. ( quite new to angular so excuse my ignorance ) as it fires a check I am doing on the view, was console logging this at the time when I noticed this, it does not stop things working but for performance I would rather not have these triggering all the time.

Let me know

**Comment by wesleycho** [comment]
This would be a micro-optimization if anything - if it is a problem, it is highly likely there is something wrong going on in your end, and not the typeahead component if anything. I am 100% certain that there are a lot more significant optimizations you can make on your end before this even approaches being an issue.

Going to close this as a breaking change request, and something we are not interested in supporting.
