### ISSUE TITLE
Size difference in views of datepicker popup

### ISSUE THREAD

**Issue by mrudu** [angular-ui/bootstrap#5760]
### Bug description:

The month view, the year view and the date view of the date picker popup are of different sizes. Is it possible to bring it to display it with the same height and width for consistency purposes?

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/ySow6cM4tvPlUhIkFCoB?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:1.5.3

UIBS:1.3.1

Bootstrap:

**Comment by icfantv** [comment]
@mrudu, you can do this by overriding the built in templates.  they're all just `<button>`s after all.

The three templates you want to look at overriding are [day](https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/day.html), [month](https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/month.html), and [year](https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/year.html).
