### ISSUE TITLE
Datepicker warning when datepicker-options is not supplied

### ISSUE THREAD

**Issue by georules** [angular-ui/bootstrap#5762]
### Bug description:

When datepicker-options is not supplied, you get the warning "Literal date support has been deprecated, please switch to date object usage."
from here: https://github.com/angular-ui/bootstrap/blob/fc02fd1e307bcf2716eff56c058b003eef4a27db/src/datepickerPopup/popup.js#L209

This was committed recently:
https://github.com/angular-ui/bootstrap/pull/5732

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/rk6oFGmgURnzloSmGNLm?p=preview

Click the first popup datepicker and view the console.  This problem does not arise if you include datepicker-options with min and max date.  This is strange, because it seems that this is checked for here:
https://github.com/angular-ui/bootstrap/blob/98eb8f1a77ca8d266d7b32b2d9fdf8dc96841c15/src/datepickerPopup/popup.js#L203
### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.3
UIBS:
1.3.1
Bootstrap:
3.3.6

**Comment by deeg** [comment]
This has already been fixed as part of 98eb8f1a77ca8d266d7b32b2d9fdf8dc96841c15
