### ISSUE TITLE
ui-sref not working in accordion in touch devices

### ISSUE THREAD

**Issue by priyavyasamor** [angular-ui/bootstrap#5763]
### Bug description:
I am using angular bootstrap accordion in my project. The accordions have several ui-sref attached to anchor tags or divs. They all are working fine in desktop but they are not working in touch devices. I have to use ng-click in place of ui-sref for touch devices. This is only happening if ui-sref is inside accordion. Otherwise it is working fine in all devices outside accordions.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.3.20

UIBS :  0.14.3

Bootstrap: 3.3.2

**Comment by icfantv** [comment]
@priyavyasamor several things:  plase be respectful of our time by adhering to the issue template.  In this case, please create a working plunker that shows the problem.  And secondly, please use the latest versions of the library and angular in that plunker.  0.14.3 is incredibly old by OSS standards and we do not release patches for old versions.

**Comment by priyavyasamor** [comment]
@icfantv  sorry for the trouble, I cannot use latest versions of angular or UIBS as for now in my project. I am temporarily using ng-click instead of ui-sref. This has solved my issue for now.  Thanks
