### ISSUE TITLE
Popover - Wrongly positioned when parent has transform properties

### ISSUE THREAD

**Issue by ValentinH** [angular-ui/bootstrap#5766]
### Bug description:
When `transform: translateX(0);` is added on the parent, the popover is incorrectly positioned because its coordinates are computed based on the top-left corner of the window while it should be based on the parent one.

This behavior is pretty close from setting `position: relative` on the parent, but this case is already handled.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/hWJ5aeZjffmeulQldeqR?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.1

Bootstrap: 3.3.2

**Comment by wesleycho** [comment]
Not sure if there's much we can do about this specific case... @RobJacobs what do you think? This could open a whole can of worms when it comes to stuff like skew or other transforms, and calculating could get impossibly hard.

**Comment by ValentinH** [comment]
For now, I've found a workaround: just add `position: relative` to the parent. 

Maybe a check that test if a parent use a transform property can be added like for non-static parents:
https://github.com/angular-ui/bootstrap/blob/master/src/position/position.js#L71

**Comment by ValentinH** [comment]
Once `relative` is added the parent, popover position is correct even if the transform translate is above 0: http://plnkr.co/edit/pG0kTAUtR0Yfvej8XWJo?p=preview

**Comment by wesleycho** [comment]
A check isn't enough to handle all of the transform cases - this is a rabbit hole I want to say we don't want to support because the different transform options have differing calculations necessary, and this will be very easy to miss edge cases & easily cause the library to balloon, but I'll wait for @RobJacobs' opinion here.

**Comment by RobJacobs** [comment]
I don't think we should try and get that exotic with how the placement calculates, especially since the work around is as simple as adding position: relative to the class or parent element.
