### ISSUE TITLE
Modal: body padding-right not removed after switching between modals

### ISSUE THREAD

**Issue by karensg** [angular-ui/bootstrap#5768]
When I close the modal through javascript with $close() or $dismiss() the padding-right is not removed. 
Version 1.3.1. 
I will try to add Plunker later.

**Comment by RobJacobs** [comment]
I'm not seeing the problem in this [plunk](http://plnkr.co/edit/vIbMlp7hqjaunjag92Zf?p=preview)

**Comment by karensg** [comment]
The problem starts when you switch between modals.
See this plunk: http://plnkr.co/edit/AbxMqD3LVs907Z3CJHdv

**Comment by RobJacobs** [comment]
The problem I'm seeing is that the modal close animations have not completed before the modal open method is called.  This is causing other race conditions in how the backdrop is getting built/destroyed.  I've update the [plunk](http://plnkr.co/edit/bYCBhHFOASqCsVQ6Vmik?p=preview) with some console.log messages that illustrate the sequence of events.  I'd like to get an opinion from @wesleycho on the best way to deal with this.

**Comment by wesleycho** [comment]
That sounds like a usage issue to me - there are promises for when the animation is finished for a reason.

**Comment by karensg** [comment]
Thanks for advice. I agree, for this scenario callbacks should be used. I fixed my problem. Thanks for advice.
