### ISSUE TITLE
ui.bootstrap.typeahead fails with ng-csp directive

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular-ui/bootstrap#5770]
As best I understand, the ng-csp should be called at the html element (or can be?), but doing so causes the ui.bootstrap.typeahead module to fail in some/most cases. And as best I can tell, when applied to the body element instead, it doesn't (but I'm not convinced ng-csp actually is doing anything anyway).

So the problem in my opinion is more probably the ng-csp stuff in Angular, but I can't verify that (can't isolate a plnkr for ng-csp without hours and hours of work). And as stated before, it doesn't seem like anyone uses ns-csp anyway, so maybe the answer is to dump it.

Here is the plnkr which demonstrates this in my browser:

http://plnkr.co/edit/02c0Cf3Tmu4ckUs4QGBV?p=preview
Version 43.0.2357.130 Built on Ubuntu 14.10, running on Ubuntu 15.04

I noticed the problem when using these versions:
Angular: v1.5.3  ...but see version in plnkr also
UIBS: v1.2.5
Bootstrap: v3.3.6

Now oddly enough the test plnkr fails for all cases except the last one (Custom popup templates for typeahead's dropdown), This still works. But when I use my version of Angular (derived from v1.5.3) which uses ng-csp code as the default, the only case that fails is the last one (the Custom popup). And it fails for the right reason I think. It disallows the inline style: style="display: block;" in the custom popup template, so the html is there but not viewable (which is probably correct for what the ng-csp code is intended to do as best I understand). My testing also used ngSanitize. When adding ngSanitize to the required modules in the plnkr, the last case (Custom popup) stops working too.

**Comment by wesleycho** [comment]
When using ng-csp, one needs to include the stylesheet part - see [here](http://plnkr.co/edit/yxI5usIjWX9icnFu43oB?p=preview).

Closing as a usage issue.

**Comment by OpenSiteMobile** [comment]
Yeah, I found that out too...too late. Sorry about that. My version worked because I had included it earlier, and forgot.

Here is the css that makes the plunker work correctly, for anyone else missing this important detail:

[uib-typeahead-popup].dropdown-menu {
  display: block;
}

**Comment by HugCoder** [comment]
The problem with the csp css "solution" is that when the object has been selected or is empty/null, there's a small white box showing up with no content, under the input. It's the ul .dropdown-menu, but empty. It's visible in the plunker that @wesleycho posted: http://plnkr.co/edit/yxI5usIjWX9icnFu43oB?p=preview
Is there a workaround for this? 
It looks pretty bad. I think it would go away if the ul used ng-if instead of ng-show, but not sure if that would cause some other problems or is a valid solution.

**Comment by wesleycho** [comment]
@HugCoder can you open a separate issue with that - it looks like a bug, but I need to spend some time thinking about it as to what a good solution is.

**Comment by HugCoder** [comment]
OK, thanks, new issue here #6220.
