### ISSUE TITLE
Tab Active Index fails when dynamic

### ISSUE THREAD

**Issue by SergeyCherman** [angular-ui/bootstrap#5771]
When setting the active tab index via {{}} tabset fails to load and gives console error.
Error:
angular.js:13236 Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{tab}}] starting at [{tab}}].

[Plunker](https://plnkr.co/edit/by40cmwvw2cCa0nbjlYK?p=preview
)
Reproduced with: ng 1.5/1.5.3 ngBootstrap: 1.3.1/1.30

**Comment by deeg** [comment]
Remove the braces and it works as expected.

[See the updated working plunk](https://plnkr.co/edit/Ry4It1wr09Eoo1PntoHF?p=preview)
