### ISSUE TITLE
formatDayHeader option for single character Day titles.

### ISSUE THREAD

**Issue by Marcmurray92** [angular-ui/bootstrap#5772]
### Feature Request description:

Looking to format day headers as single characters, which appears to be fairly common in a lot of datepicker designs.

However when the following configuration is set:

  $scope.dateOptions = {
        formatDayHeader: 'E',
        showWeeks: false
    };

The date headers are all formatted as a capital letter E.

I feel like it's a relevant and sensible addition, hope you feel the same.

Thanks! 
Marc.

### Version of Angular & UIBS

Angular: 1.5.3

UIBS: 1.3.1

**Comment by Marcmurray92** [comment]
EDIT: Clearer Title

**Comment by wesleycho** [comment]
We already have a `formatDayHeader` option - see http://angular-ui.github.io/bootstrap/#/datepicker

**Comment by Marcmurray92** [comment]
I'm aware of the option, what I'm referring to is the ability to format letter in a single character. For example, Monday being formatted as M. Tuesday as T etc.

**Comment by wesleycho** [comment]
That is not supported by the dateFilter, therefore we will not support it.

However, if one wants it, one can use a custom template to achieve this.

**Comment by Marcmurray92** [comment]
Fair enough, thanks for the quick response!
