### ISSUE TITLE
Popover doesn't show on load

### ISSUE THREAD

**Issue by nadyav** [angular-ui/bootstrap#5773]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
This is a reference to the issue described on https://github.com/angular-ui/bootstrap/issues/4264#issuecomment-206366624. It was closed, but there is no working plunker in the thread. I was asked to create a new plunker with the latest Angular UI version, but cannot get popover working at all with Angular UI 1.3.1, so using 0.13.3, as it was in the original thread. 

I'm trying to show a popover on page load only. I'm setting $scope.openPopoverOnLoad = true in the controller, and using popover-is-open="{{openPopoverOnLoad}}" in the view, so true is a boolean and not a string. Should I create a trigger in the controller as well, if I add popover-trigger="none"?

It's said on https://angular-ui.github.io/bootstrap/ ", for any non-supported value, the trigger will be used to both show and hide the popover. Using the 'none' trigger will disable the internal trigger(s), one can then use the popover-is-open attribute exclusively to show and hide the popover.", but adding popover-trigger="none" to the above code doesn't help as well. Popover just doesn't get displayed at all.

Thank you!

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.5

UIBS: 0.13.3

Bootstrap: 3.1.1

**Comment by RobJacobs** [comment]
Works for me in this [plunk](http://plnkr.co/edit/g5aaRBwvc8quLW5SFXCO?p=preview).

**Comment by nadyav** [comment]
Thanks, @RobJacobs. Looks like I need to upgrade my UI Bootstrap.

**Comment by nadyav** [comment]
Question to @RobJacobs - why is it uib-popover="text" vs popover="text"? I didn't see in the documentation uib-popover. Thanks.

**Comment by icfantv** [comment]
@nadyav, because we added the `uib-` prefix to all of our directives back in one of the 0.14.x versions due to namespace clashes (we should have done this originally, but c'est la vie).

**Comment by sbyron15** [comment]
I've run into a similar issue when the element with the popover attached to it is conditionally shown/hidden using `ng-if`.

See: http://plnkr.co/edit/5fUqQ4A02eTrZ0QRd5H3?p=preview

When I click the button, I would expect the `<span>` to appear with a popover. However, I have to click the button three times (show/hide/show) in order to get the expected behavior.

Any ideas?
