### ISSUE TITLE
Popover not showing with only text

### ISSUE THREAD

**Issue by rickerd** [angular-ui/bootstrap#5775]
When i have a popover with text only it doesn't show up..
But....

When i place a template to it, they both show up.

<div uib-popover="test" popover-is-open="true" popover-toggle="true"></div>

<div uib-popover-template="'appointment/views/_partials/popover.html'" uib-popover="test" popover-is-open="true" popover-toggle="true"></div>

Am i doing something wrong or is the code broken?

**Comment by abides** [comment]
simple plunker could be good idea to see if you are doing wrong or not.

**Comment by rickerd** [comment]
Okay, i know rwhat it is now.
When i put the tag in a ng-include, the whole shabam isn't working. But when i click on the text... the popover shows up suddenly.

**Comment by wesleycho** [comment]
Please post a reproduction in Plunker - this was listed in the issue template for a reason. This is not a support tracker, but one for posting verified bugs or feature requests.

**Comment by rickerd** [comment]
It was caused by ng-if. I will close the issue
