### ISSUE TITLE
Carousel does not support server-rendered slides

### ISSUE THREAD

**Issue by eddiejhong** [angular-ui/bootstrap#5781]
### Bug description:
Before angular-ui-bootstrap v1.0, server-rendered slides for the carousel was supported. This was nice because the initial slide loaded before angular was done loading, and it was also unnecessary to pass data to the angular module. I'm curious as to why this feature is no longer supported in your newer versions of angular-ui-bootstrap.

### Link to minimally-working plunker that reproduces the issue:
angular-ui-bootstrap v0.13.4 (supports server-rendered slides, not compatible with angular 1.5+): http://plnkr.co/edit/IA599TmL9tPFueEfle7N?p=preview
angular-ui-bootstrap v1.3.1 (does not support server-rendered slides): http://plnkr.co/edit/bKcIQWv7ICO0TO7h50kN?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.1

Bootstrap: 3.1.1

**Comment by eddiejhong** [comment]
@deeg Any progress made on this issue? Thanks!

**Comment by deeg** [comment]
@eddiejhong, I believe an investigation still needs to be done.

I believe @wesleycho or @Foxandxss will have to chime in, as I don't know much history about this component.

**Comment by wesleycho** [comment]
This appears to work - it seems you missed an API change. See [here](http://plnkr.co/edit/YVOaZRKkQ1qLXG7CncQn?p=preview) for working Plunker.
