### ISSUE TITLE
uib-dropdown breaks tab order

### ISSUE THREAD

**Issue by jesspam** [angular-ui/bootstrap#5782]
### Bug description:

If you open the list and make a selection the tab order is reset and hitting tab after the list closes moves the focus to the top of the page.  This can be seen in the demo page: https://angular-ui.github.io/bootstrap/  Opening and closing the list without clicking a list item does not interrupt the tab order.

### Link to minimally-working plunker that reproduces the issue: 
the behavior is seen on https://angular-ui.github.io/bootstrap/

### Version of Angular, UIBS, and Bootstrap 
Angular:1.5.3

UIBS:1.3.1

Bootstrap:3.3.6

**Comment by icfantv** [comment]
@jesspam, i'm not seeing this, can you please provide exact steps to duplicate, including which dropdown on which you're trying this on?  also, it may be better to try and isolate this in a stand-alone plunker.  you can create one easily by clicking the applicable button below the demo.

**Comment by jesspam** [comment]
I just verified that I see the issue on firefox and chrome.  To reproduce, go to the demo URL indicated:
click "Dropdown on Body" in the dropdown section, but don't choose any item from the list
click "Dropdown on Body" again to close the list
press Tab key to tab to the next few controls, this should work fine

now, click "Dropdown on Body" again, but this time choose an item
the list will close.  Now when you press the Tab key, you'll tab to the top of the page rather than the next control as before.

**Comment by jesspam** [comment]
@icfantv  Was that helpful?

**Comment by icfantv** [comment]
@jesspam please understand that we are unpaid volunteers on this OSS project and that we will get to the issues when we are able to allocate the appropriate amount of time.  continued pings are not necessary and considered rude.  please exercise some patience.

to answer your question, yes, that was helpful.  we will need to research what is involved here.  it may not be as simple as returning the focus to the dropdown when closed because the dropdown may no longer exist (e.g., if the dropdown selection results in a route change).

**Comment by jesspam** [comment]
@icfantv I just wanted to be sure you didn't need any more from me.  Thanks for your attention and good luck!

**Comment by wesleycho** [comment]
That's an interesting bug. On close, we should probably focus the dropdown element.

This could potentially have side-effects, but I think it's an ok change assuming no problems.

**Comment by stumblingmages** [comment]
@jesspam Not sure if it will help or not but some of my problems with unwanted navigation got better when I changed the anchor tags in my drop down menu to `<a href="javascript:void(0)">` rather than `<a href="#">`.
