### ISSUE TITLE
tooltip use in the table th cell and th use position:relative;tooltip can't work well.

### ISSUE THREAD

**Issue by 1203460788** [angular-ui/bootstrap#5792]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:1.5.3

UIBS:1.3.1

Bootstrap:3.3.6

**Comment by RobJacobs** [comment]
Use tooltip-append-to-body="true"

**Comment by 1203460788** [comment]
thanks a lot. I try it,then  work perfect !
