### ISSUE TITLE
Accordion is-open does not work as expected when using "$scope.accordion"

### ISSUE THREAD

**Issue by karlr42** [angular-ui/bootstrap#5798]
### Bug description:
If you have an accordion with `close-groups=false` and you are using an object `$scope.accordion` to control multiple groups, the groups do not follow the values of the object properties as expected. Only if the variable is called `accordion`.

I guess it's an issue with inheritance or something, since `$scope.accordion` seems to be an object that uib is using. Fix might just be to say not to use that name in the docs.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/4cItCuNWEsHrVLFv03yL?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:  1.5.3

UIBS: 1.3.1

Bootstrap: 3.3.6

**Comment by deeg** [comment]
I think it might be because of [calling the controller accordion](https://github.com/angular-ui/bootstrap/blob/master/src%2Faccordion%2Faccordion.js#L48) with controllerAs.

@wesleycho, thoughts on this? Should we just document it?

**Comment by wesleycho** [comment]
Yep, you're probably right - this is an unfortunate side effect of the implementation of controllerAs in Angular.

**Comment by deeg** [comment]
Alright, then I will assume the resolution is to just document this behavior rather than changing the controllerAs to some obscure name.

PRs welcome!

**Comment by wesleycho** [comment]
If we do decide to document, we need to do it for every component with controllerAs.

I'm not sure whether it's worth doing so though.

**Comment by deeg** [comment]
@wesleycho, sounds good.

@karlr42, thanks for reporting, but after talking with the team, we are not going to make any changes at this time. As Wes stated, this is an unfortunate side effect of controllerAs usage, and is something we have to live with for now.
