### ISSUE TITLE
Position of the uib-dropdown-menu isn't recalculated on scroll.

### ISSUE THREAD

**Issue by asurinov** [angular-ui/bootstrap#5799]
### Bug description:

Position of the appended to body dropdownMenu isn't recalculated on scroll.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/JluW5N1f1gjnT2bHs4qS?p=preview
(toggle central dropdown and then scroll container)

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.7+

UIBS: 1.1.1+

Bootstrap: 3

**Comment by deeg** [comment]
I believe this comes down to the same issue as [noted here](https://github.com/angular-ui/bootstrap/issues/5639) (#5639).

While that one is with typeahead it is essentially the same problem with append-to-body.

My guess is the resolution will be the same as well.

Thoughts @wesleycho, @RobJacobs?

**Comment by RobJacobs** [comment]
Looks like the same issue to me, we need to be careful about adding scroll and window resize events to trigger repositions as it can get expensive and add bloat.

**Comment by deeg** [comment]
@RobJacobs, yes I agree. We closed the last issue without making any changes as something we cannot support.

**Comment by wesleycho** [comment]
Closing as per comments
