### ISSUE TITLE
tooltip/popover on table cells interferes with table layout

### ISSUE THREAD

**Issue by jssebastian** [angular-ui/bootstrap#580]
Putting a ui-bootstrap tooltip or popover on a table cell (`<td>`) does not work properly: when the tooltip is shown, the cells next to it are pushed aside. Here is a plunkr showing the issue:

http://plnkr.co/edit/Ma1WjgHLWkxYCcMjLcqf?p=preview

**Comment by SanjayGautam** [comment]
This seems to be not fixed completely , it looks like that if you use ng-repeat and if you have any tooltips between it .. it will again fail to show the tool tip . 

<tr ng-repeat="name in names" >
<td><a  href="#" data-toggle="tooltip" title="{{name.firstName}}"  >{{name.firstName}}</a></td>
</tr>

above will not work , no tool tip is displayed

**Comment by willianribeiro** [comment]
@SanjayGautam I don't know if I am answering your question, but you need to use the angular-ui directives, this way:

```
<tr ng-repeat="name in names" >
     <td>
           <a href="#" tooltip="{{ name.firstName }}" tooltip-append-to-body="true">{{ name.firstName }}</a>
     </td>
</tr>
```

It works to me! 
Thank you @jssebastian and @pkozlowski-opensource

**Comment by varunrao88** [comment]
:+1:

**Comment by icechenfei** [comment]
`tooltip-append-to-body="true"` 
it's work.very thanks
