### ISSUE TITLE
Incorrect bahaviour of uib-typeahead(typeahead-editable="false" and required)

### ISSUE THREAD

**Issue by dragonkhan** [angular-ui/bootstrap#5801]
I have a typeahead with typeahead-editable="false" and required attribute.
The problem is following:
When i type some incorrect value(not in the list) and click outside the input, the value of input is reset to empty, but field is marked as correct.
Should be incorrect as required attribute is set and field is empty.

**Comment by dragonkhan** [comment]
`<input class="col-xs-6 form-control-inline" type="text" required
                                           typeahead-editable="false"
                                           uib-typeahead="currency for currency in ['USD','EUR']"
                                           ng-model="localCurrencyCode">`
Just type "aaa" and press Tab button

**Comment by deeg** [comment]
Please take the time to post a plunker reproducing the issue so we can better take a look at identifying and fixing the bug.

Also please follow the issue template and give info about what version of different libraries you are using.

**Comment by dragonkhan** [comment]
angular 1.4.10
UIB 1.2.5
bootstrap 3.3.6

will add plunkr later

**Comment by icfantv** [comment]
@dragonkhan, just a note that this is an all volunteer project - we do not have the time or resources to chase/investigate everything, especially in a case where the reporter is unwilling or unable to do themselves.  please remember this for the future.  thanks.

**Comment by dragonkhan** [comment]
Yeah, was in a hurry, so haven't seen the rules for issue description. Here is the plunkr: https://plnkr.co/edit/gfOCgTY1hHZ8bSQpfFR6?p=preview
Thanks.

**Comment by Zwerge** [comment]
@dragonkhan I just ran into this problem, try using ng-required="true" - this worked for me....

**Comment by dragonkhan** [comment]
@Zwerge didn't work for me. Could you check your idea in plunkr?

**Comment by vladrusu04** [comment]
I have somehow a similar problem and from what I see in the code:
```javascript
if (!isEditable && modelCtrl.$error.editable) {
    modelCtrl.$viewValue = '';
    // Reset validity as we are clearing
    modelCtrl.$setValidity('editable', true);
    modelCtrl.$setValidity('parse', true);
    element.val('');
}
```
there is a ``` modelCtrl.$viewValue = ''" ``` that will not stage for committing. Maybe there should be a ```modelCtrl.$setViewValue('')```

**Comment by wesleycho** [comment]
This looks fixed in the latest release, as seen [here](https://plnkr.co/edit/itvExPWdUH1UW22jKV4r?p=preview).

In fact, I came across this block in the current code:
```js
if (!isEditable && modelCtrl.$error.editable) {
  modelCtrl.$setViewValue();
  // Reset validity as we are clearing
  modelCtrl.$setValidity('editable', true);
  modelCtrl.$setValidity('parse', true);
  element.val('');
}
```
so it should fire the whole validation process.

Closing as fixed.
