### ISSUE TITLE
Dateparser problems with milliseconds format (sss)

### ISSUE THREAD

**Issue by superole** [angular-ui/bootstrap#5802]
### Bug description:
Dateparser seems to confuse seconds-format with milliseconds-format when they are used together.

### Link to minimally-working plunker that reproduces the issue:
http://angular-ui.github.io/bootstrap/#/dateparser

Enter "ss,sss" or "yyyy/MM/dd HH:mm:ss,sss" in the format input-field.
Expected output in result-field is "36,678" and "2016/04/14 13:46:36,678"
Actual output: "ss,s36678" and "2016/04/14 13:46:ss,s36678"

### Version of Angular, UIBS, and Bootstrap
Angular:
1.5.3
UIBS:
1.3.1
Bootstrap:
3.3.6

**Comment by RobJacobs** [comment]
Commas in in the millisecond field are not supported as far as I know:

https://docs.angularjs.org/api/ng/filter/date
http://www.w3.org/TR/NOTE-datetime

**Comment by icfantv** [comment]
I don't know that we should be supporting milliseconds at all.  This may just be a doc update...

**Comment by wesleycho** [comment]
We do support milliseconds - this sounds like a bug, but we should investigate a little further.

This is sort of low priority to me though, since it seems pointless to display milliseconds in a datepicker popup with them (although perhaps the user is trying to use the service for something else, which would be fair).

**Comment by superole** [comment]
I agree that it may be low priority. I just wanted to let you know about the issue, even if it is a corner-case.

@RobJacobs the issue is not related to the comma. It is easily reproducible without the comma: just choose any string containing two groups of s'es where one of them should represent milliseconds(sss) and the other seconds(s or ss). The angular date-filter supports this just fine(testable from the first link you presented).
