### ISSUE TITLE
Modal directive freezes the page for a while once closed

### ISSUE THREAD

**Issue by roibeart** [angular-ui/bootstrap#5803]
### Bug description:
I'm experiencing an annoying bug with the modal directive: after calling the `close()` or `dismiss()` method, on Chrome the page freezes, and inspecting the source of the page I see that the modal is still there but somehow without opacity. After some time (say one minute), the modal code disappears and I can again interact with the page.
I tried on firefox and this thing doesn't happen.

### Example
It happens also on the examples of the documentation:
https://angular-ui.github.io/bootstrap/#/modal

### Version of Angular, UIBS, Bootstrap and Chrome

Angular: 1.5.3

UIBS: 1.3.1

Bootstrap: 3.3.6

Chrome: 50.0.2661.75 (the latest at the time of writing)

**Comment by pkozlowski-opensource** [comment]
I'm not seeing it on the demo page with Chrome 51.0.2700.0. Are you sure that you don't have Chrome extensions installed that would interfere? Try in the incognito mode / on another machine.

**Comment by roibeart** [comment]
I tried it on different machines: on two of them (an iMac and a MacBookPro) the issue appears even in incognito mode, on the other two (an iMac and a PC) all worked well.
If I get the confirm that no one experiences it I can stop worrying about that.
Very strange thing, anyway

**Comment by roibeart** [comment]
I rebooted one of the machines that showed the issue and now all seems to work well.
I'm sorry, I forgot to apply the first rule of the problem solver...
Anyway, thank you for the support

**Comment by jongunter** [comment]
I'm experiencing this, too, on 2.5.0, Angular 1.5.8, and Chrome 58.0.3029.110. Except the page is locked up indefinitely and never yields control back to the user. It's in a complex app, so I'm getting to get a simplified plunker available, with which I will follow up shortly. If anyone has any ideas in the meantime, let me know.

**Comment by jongunter** [comment]
I looks like the `uib-modal-window` and `ui-modal-backdrop` `<div>`s are never being taken out of/hidden from the DOM. If I open developer tools and remove them, the page goes back to normal.
