### ISSUE TITLE
tooltips should be able to open and close with unrelated events

### ISSUE THREAD

**Issue by synthecypher** [angular-ui/bootstrap#5804]
For instance if I'm working on a *Copy to clipboard* button.

I need to be able to trigger the tooltip on a `click` event and close it on a `mouseleave` event.

Currently I can only set the open trigger to `click`, which will cause the tooltip to remain open until the button is clicked again.

**Comment by deeg** [comment]
I am not sure if this an enhancement the team will want to add to the library.

I'm not certain, but I think you should be able to accomplish this yourself. I believe you could use the tooltip-is-open attribute to control when it is open/closed yourself by adding the appropriate event handlers.

**Comment by RobJacobs** [comment]
Typically this is handled with tooltip-trigger attribute which the docs describe how to implement [here](http://angular-ui.github.io/bootstrap/#/tooltip)  I think we could do better with how the open and close triggers are defined by using an object with open and close properties that can hold multiple triggers:

    var triggers = {
       open: 'focus click',
       close: 'blur click'
    }

**Comment by deeg** [comment]
@RobJacobs, yeah that sounds like a good solution.

Any one opposed to that? Should ask for PRs implementing that?

@wesleycho, @Foxandxss?

**Comment by wesleycho** [comment]
I thought we already have support for this?

**Comment by RobJacobs** [comment]
I think it only allows you to set triggers that will show and hide, not define which triggers show and which triggers hide.  I'll do some testing to make sure...

**Comment by wesleycho** [comment]
If one wants custom events, one needs to define them in `$uibTooltipProvider`, as documented [here](http://angular-ui.github.io/bootstrap/#/tooltip)

**Comment by wesleycho** [comment]
Seeing as this is already documented as linked above, I am going to close this issue as already supported.

If there is a bug in that not working, then we can revisit this, but I believe this is already in the library.

**Comment by beans9** [comment]
@synthecypher 
example code : http://plnkr.co/edit/3CieGvygxFqhsCwDrKgN?p=preview
