### ISSUE TITLE
Modal dialog closes when mouse button is pressed over the dialog window but released outside the window

### ISSUE THREAD

**Issue by maximusk** [angular-ui/bootstrap#5806]
### Bug description:
STR:
1) Hover over the modal dialog
2) Press left mouse button down
3) Move mouse outside the modal window
4) Release the button

ER:
Modal dialog is closed

AR:
Modal dialog should not be closed since click actually occurred on the dialog. Closing of the dialog especially annoying when selecting a text on the dialog and accidentally move the mouse outside of the dialog

### Link to minimally-working plunker that reproduces the issue:
http://angular-ui.github.io/bootstrap/
section Modal (ui.bootstrap.modal) -> click on the `Open me` button

### Version of Angular, UIBS, and Bootstrap
1.5.3

UIBS:
1.3.2

Bootstrap:
3.3.6

**Comment by wesleycho** [comment]
This is not a bug - the backdrop also will close on click. If one doesn't want it to close, one needs to use `backdrop: 'static'`.

See [here](http://plnkr.co/edit/Zmoa5hGlORHvnpuTKvmZ?p=preview) for it in practice.

**Comment by maximusk** [comment]
I am sorry, can you please elaborate? This is clearly a bug. I want dialog to close on backdrop click, but don't want it to close when click is initiated on dialog. There is a simple fix for that, I have crested a pull request already
