### ISSUE TITLE
Add $resolve to uibModal scope

### ISSUE THREAD

**Issue by radarfox** [angular-ui/bootstrap#5808]
Hello,

it would be super, if modal plugin would support new `$resolve` property same as angular-route does.

See example here (search for "$resolve") https://docs.angularjs.org/api/ngRoute/service/$route

It makes usage with components much easier, because there is no need for "modal controller", just the "component controller":

```
$uibModal.open({
	template: '<my-component data-foo="$resolve.bar"></my-component>',
	resolve: {
		bar: 'Hello world!'
	}
});
```

Then in component just add bindings, and everything is set:

```
var myComponent = {
	template: '<p data-ng-bind="$ctrl.foo"><p>',
	bindings: {foo: '<'}
};
```

All I had to do, was to add 2 new lines in your source:

```
var modalScope = providedScope.$new();
modalScope.$close = modalInstance.close;
modalScope.$dismiss = modalInstance.dismiss;
modalScope.$resolve = tplAndVars[1]; // here
```

and

```
if (modalOptions.bindToController) {
  ctrlInstance.$close = modalScope.$close;
  ctrlInstance.$dismiss = modalScope.$dismiss;
  ctrlInstance.$resolve = modalScope.$resolve; // here
  angular.extend(ctrlInstance, providedScope);
}
```

Plunker http://plnkr.co/edit/UtTBUZoztzVS8A5jcoQq

Example in angular-route https://docs.angularjs.org/guide/component#components-as-route-templates

**Comment by deeg** [comment]
@radarfox, are you planning to fill out the issue description or was this created by mistake?

**Comment by icfantv** [comment]
closing due to lack of content.

**Comment by radarfox** [comment]
Sorry, i accidentaly pressed enter before entering description.

You is too fast for me :)

Now is all set, could you reopen?

**Comment by icfantv** [comment]
@radarfox, i'm not seeing a $resolve property in the docs page you linked. regardless, if this is an angular 1.5.x thing, we are not yet ready to require angular 1.5+.

**Comment by deeg** [comment]
@radarfox, is this somehow different than the scope property you can pass into open?

> scope (Type: $scope) - The parent scope instance to be used for the modal's content. Defaults to $rootScope.

**Comment by radarfox** [comment]
@icfantv It is located near the end of page - Properties -> current

Well it is not 100% Angular 1.5. It is just adding resolved object to modal scope. It is not requiring any 1.5 functionality.

**Comment by radarfox** [comment]
@deeg no, it should be bound to modal scope - child scope of scope passed in options. It is the same scope where $close and $dismiss is bound to.

**Comment by icfantv** [comment]
@radarfox do you mean `resolveAs`?

**Comment by deeg** [comment]
> @deeg no, it should be bound to modal scope - child scope of scope passed in options. It is the same scope where $close and $dismiss is bound to.

I guess I'm still confused on the difference between scope and resolve options your propose. Could you maybe set up a plunker with how you want resolve to work so we can better understand?

**Comment by radarfox** [comment]
@icfantv well `resolveAs` is just another enhancement for this use-case. It lets you choose `$resolve` property name. So if you dont like `modalScope.$resolve` you can change it to `modalScope.myResolve` by passing `resolveAs: "myResolve"` in options.

**Comment by radarfox** [comment]
@deeg here it is http://plnkr.co/edit/UtTBUZoztzVS8A5jcoQq

If support for `$resolve` would be added, then there would be no need for $uibModal.open controller and you can pass data to component very fast without extra code for each modal.

**Comment by radarfox** [comment]
Also ui-router implemented support for this - https://github.com/angular-ui/ui-router/releases/tag/1.0.0-alpha.1 (see the first paragraph of "Route to component")

And i found more detailed info on angular-route https://docs.angularjs.org/guide/component#components-as-route-templates

@deeg is this enought info for you?

**Comment by deeg** [comment]
@radarfox, is there a reason [something like this](http://plnkr.co/edit/KSBkLgaXskQJw20HnmXG?p=preview) wouldn't work?

That uses the already in place scope option instead of the newly created resolve option.

Sorry if I'm missing something completely.

**Comment by radarfox** [comment]
@deeg no, because that would not work with promises, like resolving does.

**Comment by wesleycho** [comment]
I can't say I love this suggestion, but I know ngRoute and UI Router have both went this route.

For parity, it may be better for us to just support this.

**Comment by deeg** [comment]
@radarfox, I see. None of the examples you provided showed promises that is why I was confused.

Agree with you now though!

**Comment by radarfox** [comment]
I hope it is clear that this is 100% backwards compatible enhancement, which takes only 2 lines of code to implement.

I see no performance or compatibility problems.

As a result you save a lot of code, when using component aproach with multiple modals.

**Comment by deeg** [comment]
@radarfox, yes that is clear. Feel free to open a PR and we can review it and merge it in.

**Comment by wesleycho** [comment]
It actually has a bit of negative perf implications, since the dirty checking loop becomes longer, but it seems that those concerns are fairly weak, or weak enough that this was not a strong point of consideration for both the Angular and UI Router teams.

**Comment by pcalouche** [comment]
Am I understanding this change wrong?  I've updated @radarfox plunk here but getting a console error saying 'Hello world' is an unknown provider.  Thanks in advance.

http://plnkr.co/edit/RWjPKsYRa4x9VcrJ2PUd?p=preview

**Comment by wesleycho** [comment]
@pcalouche there were multiple things wrong with your Plunker - see [here](http://plnkr.co/edit/pcd2GC39p0PqpkcQxyVe?p=preview). In the future, please do not open issues/pollute existing issues for what are support issues.

**Comment by radarfox** [comment]
@wesleycho Thanks for implementation and release.

The only disadvantage is that you also need `controller`, so I end up with dummy `controller: angular.noop`.

Why did you implement it differently from how `$close` and `$dismiss` already work?

**Comment by radarfox** [comment]
@wesleycho also angular-route does not require `controller` to be present.
