### ISSUE TITLE
Update npm package: bower has v1.3.2, npm has 0.12.2

### ISSUE THREAD

**Issue by stasberkov** [angular-ui/bootstrap#5815]
### Bug description:
Obsolete npm package version, much older than bower has

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by wesleycho** [comment]
As per the [README](https://github.com/angular-ui/bootstrap/blob/master/README.md), the package we publish is `angular-ui-bootstrap`.
