### ISSUE TITLE
Multiple datepickers all opening at once

### ISSUE THREAD

**Issue by enjareyes** [angular-ui/bootstrap#5816]
My datepickers are in an ng-repeat so I have many of them and when I click one they all open. They have unique id's but currently share the same model. I can't manually create a model for each one so what's the best way to handle this?

**Comment by icfantv** [comment]
@enjareyes hi there.  i responded to your previous post in #1853.  and just a polite reminder that the issues forum is not for support requests (per the template).  you may ping us on slack, gitter, or freenode (or stackoverflow).  cheers.

**Comment by morteza-gho** [comment]
I had the same problem. I solved the problem here
[http://stackoverflow.com/questions/19613510/how-to-have-at-least-two-datepickers-of-ui-bootstrap-on-a-single-page/37293256#37293256]
