### ISSUE TITLE
how to save data from modal when the modal has been closed or hide not submit

### ISSUE THREAD

**Issue by jason5149** [angular-ui/bootstrap#5817]
I'm using modal to get data from user, now I have an issue that is when user click out of the modal window I want to save which user has already put in the modal, and when user open modal again I can put this data which has written in the modal box!

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by icfantv** [comment]
@jason5149, In the future, please be respectful of our time by adhering to the issue template and actually reading it (and our documentation) before summarily removing its contents.  Had you read it, you would have noticed that the very first sentence indicates that the issues forum is not for support requests.  The linked documentation indicates how to get help.
