### ISSUE TITLE
Timepicker: JS Date object starts at 01h

### ISSUE THREAD

**Issue by christophermh44** [angular-ui/bootstrap#5819]
Hello,

I use your time picker as a "duration picker". So, if an item from my lists lasts 4 minutes, "01:04:00" is displayed inside the time picker. It matches the timestamp "240" which is represented, in JS like 240 seconds after January 1st, 1970 at 1am (=1970/01/01 01:04:00).

How can I tell to timepicker that I want to display 0 in the hour field?

Thanks for your answer!

### Link to minimally-working plunker that reproduces the issue:

== JS ==
```javascript
$scope.duration = new Date(240 * 1000); // in ms.
```

== HTML ==
```html
<uib-timepicker ng-model="duration"></uib-timepicker>
```

### Version of Angular, UIBS, and Bootstrap
Angular - 1.5.3
UIBS - 1.3.2
Bootstrap - no bootstrap

**Comment by christophermh44** [comment]
For now, I hid the hour field in CSS, but I can still press ↑ when I'm at (01:)59:59 to get (02:)00:00 and it distorts the calculations (I can press ↓ when I'm at (01:)00:00 to get (00:)59:59 and it's not better).

**Comment by icfantv** [comment]
@christophermh44, per the issue template, the issues forum is not for support-related requests.  Please read our project documentation for how to properly ask for, and receive, assistance.

To answer your question, the time picker is not meant to be used for duration.  You would be better off making your own widget to handle this.
