### ISSUE TITLE
uibCarousel not working / rendering in 1.3.2

### ISSUE THREAD

**Issue by stevie-p** [angular-ui/bootstrap#5822]
Apologies if I'm missing something obvious, but the `uibCarousel` directive is not working / rendering / animating for me in v1.3.2. It may be a recurrence of #1273 (or has that not been resolved)?

[Working Plnkr @1.1.2, fails in all later versions ](https://plnkr.co/edit/5qismWugt9guRhuTHArz?p=preview)

Angular: 1.5.3
UIBS: 1.3.2 (`ui-bootstrap-tpls.js` via `bower install angular-bootstrap`)
Bootstrap: 3.3.4

**Comment by icfantv** [comment]
@stevie-p, this is working correctly on our demo site.  can you please try recreating from the plunker there?

**Comment by stevie-p** [comment]
Here you go:
[Failing plunkr](http://plnkr.co/edit/VgJuN1qjXJCMBEhUnBGy?p=preview)
Perhaps an issue with hard-coded (rather than ng-repeated) `uib-slides`, scopes or transclusion?

**Comment by stevie-p** [comment]
Solved
`index` attribute is required on `uib-slide`. Perhaps worth mentioning that in the docs? Or perhaps it should be optional?
[Working plnkr with 1.3.2](http://plnkr.co/edit/CL2HlnpXnHbhueCBmEn7?p=preview)

**Comment by icfantv** [comment]
@stevie-p.  it is in [the docs](http://angular-ui.github.io/bootstrap/#/carousel).

**Comment by stevie-p** [comment]
Sorry if I'm being stupid @icfantv , but I can't see anywhere where it says `index` is required. In fact, it says "Default: none" which would lead me to believe it's optional. Could be clearer - all I'm saying! :-)

**Comment by icfantv** [comment]
I originally understood you to be saying that was not present.  I think what you're saying is that we should indicate that it is required?

**Comment by stevie-p** [comment]
Yes - exactly - Mark it as required, assuming that it is. 
However, I think index *should* be optional (as it was back in 1.1.2); not sure why / how it became required since 1.2.

**Comment by DDroll** [comment]
I think, problem is deeper. This not marked as "required" in docs, because is shouldn't be required. Maybe, something gone wrong while updating directive? It was optional in previos versions, and that was convinient, i don't see any reasons to make api worse. Looks like as accidental error.
