### ISSUE TITLE
[pagination] App-wide default settings override

### ISSUE THREAD

**Issue by carlosafonso** [angular-ui/bootstrap#5823]
Hi,

The pagination directive takes its default values from the `uibPaginationConfig` constant. These values can be later overridden using the directive's attributes.

If I have several components of my app using this directive and I decide to show 15 items per page instead of 10, I need to set the `items-per-page` attribute on each part using the directive.

Could these default values be defined in a provider/service so that my app can override any of them during config time in a single place? If so, I can give it a try and submit a PR.

Thank you!

**Comment by wesleycho** [comment]
One could override it just by doing
```js
$provide.constant('uibPaginationConfig', {
  ...
});
```

**Comment by icfantv** [comment]
@carlosafonso, if that solution works for you, i'm going to close this.  please confirm.  thanks.

**Comment by carlosafonso** [comment]
Of course, this should work!

Thank you both.
