### ISSUE TITLE
Displaying uib-dropdown-menu items when uib-dropdown-toggle not toggled

### ISSUE THREAD

**Issue by bman61** [angular-ui/bootstrap#5824]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.2

Bootstrap:3.3.6

**Comment by icfantv** [comment]
@bman61 this is working just fine on our demo page.  please us that plunker as a starting point and debug your code.

one thing i noticed is that you're using the uib-dropdown-menu as a class.  that was removed.  it is only supported as an attribute.

you would do well to read the changelog from 0.14.3 to 1.3.2 and pay special attention to the breaking changes sections.
