### ISSUE TITLE
Example usage of accordion's custom template doesn't support transcluded header

### ISSUE THREAD

**Issue by michal-filip** [angular-ui/bootstrap#5829]
Current online docs show example usage of custom template for accordion group. This custom template doesn't support transcluded heading. Although it's just an example, I suspect that most people will copy-paste this into their code as a starter. Therefore I'd suggest updating this template by including the "uib-accordion-header" directive in this template.

Plunker:
http://plnkr.co/edit/dFbSQ1CNFvVofSlkPLbr

Angular: 1.5.3
UIBS: 1.3.2

**Comment by wesleycho** [comment]
Funnily enough, I just ran into this at work yesterday - PRs welcome for this.
