### ISSUE TITLE
Datepicker year buttons change minDate in datepickerOptions

### ISSUE THREAD

**Issue by rbfinch** [angular-ui/bootstrap#5832]
Besides changing the selected year, the datepicker previous/next year buttons also change `minDate` in `datepickerOptions`.  This causes a problem with datepickerPopup when the user pops up the datepicker, changes the year, closes and pops up the datepicker again. At that point, the original `minDate` passed in datepickerOptions has been changed by the datepicker so the user may not be able to choose dates that should be choosable.

http://plnkr.co/edit/C3u8azKq31zmLa26UuHX

To demonstrate the issue:

* Note `minDate` should be current date
* Click popup button to display datepicker
* Click next year button
* Note `minDate` has changed
* Click a month to select a date, this should update the selected date and close the popup
* Click the popup button to display datepicker
* Note that you can no longer select months in the current year

After playing with the plunkr a bit more, it appears that `minDate` changes only if the previous/next year buttons are the first thing clicked after the first datepicker popup.  If something else is done, then it works correctly.

Angular: 1.5.5

UIBS: 1.3.2

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
This is an interesting bug - it seems to keep track properly what should be disabled in the UI, except it updates the model incorrectly. This suggests something potentially wrong in the popup layer.

**Comment by wesleycho** [comment]
This is not a bug - this is due to using the same date object for the init date and min date. See [here](http://plnkr.co/edit/SgKwZLZgAFVn0MT8gler?p=preview) for solution.
