### ISSUE TITLE
[Datepicker]: Option "showButtonBar" is missing

### ISSUE THREAD

**Issue by softsimon** [angular-ui/bootstrap#5833]
### Bug description:
I just upgraded from 1.1 -> 1.3 and "showButtonBar" has been removed from the code and API doc so I cannot hide the bottom bar anymore.

Is this a bug or a feature?

**Comment by deeg** [comment]
It does still seem to be an option on datepicker-popup.

[Here is a working plunker](http://plnkr.co/edit/FSrxqWETf5ObGrQ8nRKd?p=preview). Check out the first datepicker.

If I'm not mistaking the datepicker does not have the buttons built into it, and that is why that option is not needed. I will let @icfantv or @wesleycho speak to that better.

**Comment by RobJacobs** [comment]
@deeg You are correct, the button bar is not part of the datepicker directive, just the datepicker-popup directive.
