### ISSUE TITLE
Accordion custom template does not work with data-uib-accordion-heading

### ISSUE THREAD

**Issue by bstoney** [angular-ui/bootstrap#5834]
A custom accordion template does not correctly transclude a heading when used with `data-` prefix, i.e. `data-uib-accordion-header` instead of `uib-accordion-header`

    <div data-uib-accordion>
        <div data-uib-accordion-group data-template-url="custom-template.html">
            <div data-uib-accordion-heading>
                Heading <small>Sub heading</small>
            </div>
            <table class="table table-condensed table-striped">
                <thead>
                <tr>
                    <th>Name</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>A name</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <script type="text/ng-template" id="custom-template.html">
        <div class="panel panel-default">
            <div class="panel-heading pointer" data-ng-click="toggleOpen()">
                <h4 class="panel-title">
                    <a href data-uib-accordion-transclude="heading"><span uib-accordion-header data-ng-class="{'text-muted': isDisabled}">{{heading}}</span></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" data-uib-collapse="!isOpen">
                <div data-ng-transclude></div>
            </div>
        </div>
    </script>

Changing the template to use the `uib-accordion-header ` does work:

    <a href data-uib-accordion-transclude="heading"><span uib-accordion-header data-ng-class="{'text-muted': isDisabled}">{{heading}}</span></a>

**Comment by deeg** [comment]
Please take the time to follow the issue template and supply version numbers of the libraries you are using along with a plunkr reproducing the issue so we can look into identifying and fixing any bugs.

**Comment by RobJacobs** [comment]
The querySelector [here](https://github.com/angular-ui/bootstrap/blob/master/src/accordion/accordion.js#L127) is looking for the attribute uib-accordion-header.

**Comment by wesleycho** [comment]
I wish we didn't support this prefix :( .

PRs welcome.

**Comment by bstoney** [comment]
Thanks all, I appreciate the fix. I've read the issue template for future reference, also will do a PR next time :)
