### ISSUE TITLE
Popover directive attribute to assign custom class 

### ISSUE THREAD

**Issue by jmvalencia** [angular-ui/bootstrap#5836]
### Feature request description:

When you use the popover directive and append it to the body it would be nice to have the option of adding a new class to override styles without mess with the globals (this may break the default functionality).

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.2

UIBS: 1.1.2

Bootstrap: 3.3.5

**Comment by icfantv** [comment]
@jmvalencia you can do this by overriding the popover template.

**Comment by bennettatoms** [comment]
For anyone else who comes across this thread running into a similar issue, it's not currently listed in the documentation, but you can use the attribute `popover-class` to add a custom class to the popover instance that is appended to the document body, and thereby avoid overwriting CSS for `.popover` globally.

**Comment by theyuv** [comment]
@bennettatoms This doesn't seem to work for me. I have Bootstrap version 3.3.6. Any suggestions?

**Comment by ronilitman** [comment]
@bennettatoms Is there an option to not use the class .popover but to use a different class name? Because using the popover together with bootstrap totally destroys my styling, because bootstrap adds default styling with .popover
