### ISSUE TITLE
carousel - can't leave default for attributes "active" and also "index" for uib-slide 

### ISSUE THREAD

**Issue by jojosati** [angular-ui/bootstrap#5837]
### Bug description:
I've just upgrade from 0.14.x and found that since 1.x.x if omit the attribute "active" for the Carousel and "index" for the ui-slide will make it not work. 

* without "active" attribute the javascript throw error

```Error: [$compile:nonassign] Expression 'undefined' in attribute 'active' used with directive 'uibCarousel' is non-assignable!```

* without "index" the slide show nothing although the img is there.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/lfIkAN2XR4CgnqnfkcoS?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.4

UIBS: 1.3.2

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@jojosati, this is the expected behavior.  You are responsible for reading through the changelog and paying attention to the breaking changes sections for each release between your old one and your new one.  In the future, please be respectful of our time by first doing your due diligence.  Thanks.
