### ISSUE TITLE
datepickerPopup not show string datetime property

### ISSUE THREAD

**Issue by jeremyyang824** [angular-ui/bootstrap#5840]
When I use datepickerPopup, and pass a json object, which has a string datetime property. It will render empty in the input field.
So I think it should add a code fragement such as：
`if (angular.isString($scope.date)) {
            $scope.date = parseDateString($scope.date);
        }`
in the `UibDatepickerPopupController`. at "popup.js" line 141. 

Version: 1.3.2 - 2016-04-14

**Comment by icfantv** [comment]
@jeremyyang824 please be respectful of our time by adhering to the issue template.  additionally, it is not totally clear what you are asking for in your issue.  i will say that it sounds like you want us to support string objects for our date picker and if so, the answer to that is no and is thoroughly documented across many closed issues as to why we removed that support.

if this interpretation is not correct, please fix your issue and we will consider reopening.  thanks.
