### ISSUE TITLE
`uib-dropdown-toggle` doesn't work on first half of split button

### ISSUE THREAD

**Issue by david-mohr** [angular-ui/bootstrap#5841]
### Bug description:

`uib-dropdown-toggle` doesn't work on first half of split button.

I have a split button which I would like to toggle using both halves of the split button.  If I add `uib-dropdown-toggle` to the first button in a `btn-group` (using the 'split button' example given here: https://angular-ui.github.io/bootstrap/#/dropdown), the menu will not open, however chrome devtools does indicate that aria-expanded is being altered although it remains set to false.

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/oo4zk5gd0vPJlBX6px9s?p=preview

There are three buttons on this plnkr that all trigger dropdowns. The first demonstrates the problem (clicking 'Action' will not open the menu, clicking the caret will). The second demonstrates a workaround (clicking 'Action' will open the menu). The third is a standard button with a dropdown.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.9
Bootstrap: 3.3.6
UIBS: 1.3.2

**Comment by icfantv** [comment]
@david-mohr marking this as needing investigation, but just a head's up that your `id` attributes are not unique - but that is not why this isn't working...

**Comment by david-mohr** [comment]
Thanks @icfantv, I've updated the `id` attributes.

**Comment by wesleycho** [comment]
The library only supports one uib-dropdown-toggle is the reason this does not work. I don't see a particular compelling reason why we should support more than 1, given that it will complicate the internal logic around checking the toggle elements and that this seems like an edge case.

I would recommend using the is-open binding to solve your problem.

**Comment by david-mohr** [comment]
Thanks @wesleycho, I'll stick with the is-open work around.
