### ISSUE TITLE
Modal Scope Question

### ISSUE THREAD

**Issue by kyse** [angular-ui/bootstrap#5842]
I'm noticing some weirdness with the scope being used in the modal template.  Hoping someone can help me understand the reasoning.

I'm opening a modal with a custom template, and passing along another template for the content.  The end result I'm not getting is why the template for the modal (modalTemplate.html) is getting a different scope than the containing modal directive div and the final uib-modal-transcluded modal body content.

If you look at the scope for the 'myDirective' directive, you'll see both myDirectiveCtrl and appModal controllerAs vm's with rootscope as the parent.  But in the modal template div's, the scope is a sub of the modal scope.  Causing me to have to use '{{$parent.myDirectiveCtrl.label}}' to bind the modal title text to something on my controller vm.

I was under the impression scope inheritance allowed me to use '{{myDirectiveCtrl.label}}' and it would propogate down the scope tree to find the proper value, but this isn't happening.  Am I just ignorant of angular scope inheritance, or is this something specific to the uib modal directive I'm not grasping?

Thanks!

Plunker: https://plnkr.co/YrXAfTkWkfvAjC3yxM4v

Angular: 1.5.3
UIBS: 1.3.2
Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@kyse the issues forum is not for support requests.  please be respectful of our time by adhering to that.

two problems I notice right off the bat with your plunker.  you have the `scope` property on your directive capitalized and secondly it's an isolate scope.  isolate scope directives don't inherit anything unspecified from the parent.

**Comment by kyse** [comment]
The question is more about the modal template scope not inheriting from the main scope, not the directive scope.  But OK.  Thanks for your time and reply.

**Comment by icfantv** [comment]
ahhh, gotcha.  i misunderstood the question.  take a gander at [our docs](http://angular-ui.github.io/bootstrap/#/modal), you'll see a `scope` option in there for `$uibModal`.  just pass the right scope there and you should be good to go.  just a warning on the perils of storing primitives on scope:  values are copied and not referenced so they will not change if they're modified in other, hierarchical, scopes.
