### ISSUE TITLE
animation flicker when opening modal

### ISSUE THREAD

**Issue by dcrouch79** [angular-ui/bootstrap#5844]
### Bug description:
If the 'animation' parameter is set to false and there are any elements with ng-show="false" these elements are very briefly shown before being hidden. Adding ng-cloak directive does not help as suggested [here](https://docs.angularjs.org/api/ng/directive/ngCloak). Neither does the fix suggested under issue [#5183](https://github.com/angular-ui/bootstrap/issues/5183). Only way to avoid flicker is to set the 'animation' parameter to true.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/u75Qt0PLevcgQ1DQVoHa?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.5

UIBS:1.3.2

Bootstrap:3.3.6

**Comment by icfantv** [comment]
@wesleycho, this issue sounds familiar and i thought we'd addressed it either with code or with an explanation.  do recall which?

**Comment by RobJacobs** [comment]
Use ng-if.

**Comment by icfantv** [comment]
Works for me.  Thanks @robjacobs.
