### ISSUE TITLE
Popover is-open not working with trigger Outsideclick

### ISSUE THREAD

**Issue by sebfie** [angular-ui/bootstrap#5846]
### Bug description:

Hello, I need the Outsideclick trigger for my popup, but I also need to open it when clicking on an other button in my ui. In fact I can not, because when I click on this button, It closes the popup.

I fixed it using $timeout({},0), but I think the is-open attribute should work event with Outsideclick ?

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/SptThtx8h7LpGdwOoUHo?p=preview

**Comment by icfantv** [comment]
@sebfie please be respectful of our time and follow the instructions in the issue template.  the issues forum is not for support-related requests.  thanks.

the `is-open` attribute was added to give you full control over when the popover is open or not.  as indicated in the documentation, it was not meant to work in conjunction with existing triggers.  it's an either-or use case.

closing as a support issue.
