### ISSUE TITLE
typeahead expects li in template

### ISSUE THREAD

**Issue by frfancha** [angular-ui/bootstrap#5848]
The code: 
          target = popUpEl.find('li')[scope.activeIdx];
          target.parentNode.scrollTop = target.offsetTop;
in typeahead.js in master fails (target is undefined) if the template doesn't contains -li- (we use -tr- instead of -li- and -table- instead of -ul- by typeahead-popup-template-url).

When the developper tool is not opened in the browser everything runs fine despite the error.

If using -li- is officialy required in custom templates, then this is a feature request to allow other html elements, and if -li- is already allowed today then it is to report the bug.

**Comment by icfantv** [comment]
@frfancha, please be respectful of our time by adhering to our issue template.

additionally, please use MD formatting to make your issue text more readable.

**Comment by pkozlowski-opensource** [comment]
This is a valid issue. We shouldn't be doing DOM querying like this as it limits possibilities for template swapping.

**Comment by pkozlowski-opensource** [comment]
Offensive code is here: https://github.com/angular-ui/bootstrap/blob/f88067a04f8647f25e3bb987e3ea13993a146147/src/typeahead/typeahead.js#L409-L415

**Comment by wesleycho** [comment]
We probably should change it to query for a class instead of a tag.

**Comment by RobJacobs** [comment]
Was looking at creating a PR for this, was wondering if using:

    [role="option"]

for the query selector would work.
