### ISSUE TITLE
datepicker-popup is-open not working with <a> element

### ISSUE THREAD

**Issue by sibeliusseraphini** [angular-ui/bootstrap#5849]
### Bug description:

I was using a UIBS 0.x version, and the `datepicker-popup` works fine with `<a>` element.
I've upgrade to UIBS 1.3.2, and the is-open let my variable always false when using the `uib-datepicker-popup` with `<a>` element.

I know that the datepicker-popup is meant to be used with input element but I need to use if an `<a>` element

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.7

UIBS: 1.3.2

Bootstrap: 3.3.2

**Comment by wesleycho** [comment]
Why not just embed an inline datepicker and using the popover component then?

**Comment by sibeliusseraphini** [comment]
do u have an example of this?

**Comment by wesleycho** [comment]
Read the docs for the popover - this should be pretty straightforward for you to implement, and should capture your needs better.
