### ISSUE TITLE
Select box doesn't work in modal and in IE11

### ISSUE THREAD

**Issue by elutz** [angular-ui/bootstrap#5850]
##### Bug description:
If you place a select element in a modal dialog (opened with the help of $modal) it works in all browsers I tested on Windows 8 and 8.1 except IE11.
Using these browsers the plunker below works well:
- Firefox ESR 38.7.1
- IE10 
- Chrome 50.0.2661.87 m

In IE11 it isn't happened anything, the select box doesn't respond on any event (mouse-over, click ...)

##### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/hDYTAIfkczkYdwuz9ljo?p=preview
Click the button to open the modal and choose a color in the select box.

##### Version of Angular, UIBS, and Bootstrap
Angular: 1.5.3
UIBS: 0.13.3
Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
Are you sure this is a UI Bootstrap issue and not an Angular one proper?

**Comment by elutz** [comment]
Not really sure, but i wasn't able to reproduce it without an UI Bootstrap Modal directive.

**Comment by elutz** [comment]
I updated the plnkr to angular-bootstrap 1.3.2 
(Unfortunately plnkr offers old versions only in its libraries function)
Using this up-to-date version seems to fix the problem in IE11.
Look at http://plnkr.co/edit/hDYTAIfkczkYdwuz9ljo?p=preview again.

**Comment by icfantv** [comment]
@elutz in the future, you can use our Edit in Plunker links from our demo page to get you started.  Those are typically the latest versions of everything.
