### ISSUE TITLE
$uibModal can't close after $http post success

### ISSUE THREAD

**Issue by vincenthan13** [angular-ui/bootstrap#5853]
Hi. I am wondering how can I close or dismiss an uibModal upon $http post on success inside angularjs service.

If you could give me a little preview in jsFiddle or plunker, it will be really a great help for me. Thankyou.

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by icfantv** [comment]
@vincenthan13, in the future, please be respectful of our time by reading the issue template.  had you done so, you would have noticed that the first line states that the issues forum is not for support requests, which this clearly is.  additionally, we give you a link on how to properly ask for help - avenues where we (and others) are able to help you without making more work for our project.
