### ISSUE TITLE
Reload pagination after ajax request

### ISSUE THREAD

**Issue by Oviglo** [angular-ui/bootstrap#5855]
Hi,
I have a problem with Pagination module, I have a ajax popup wich show a list of data but the pagination don't works after ajax request.
Can you give me a way to fix this ?

Regards.

**Comment by icfantv** [comment]
@Oviglo, per the issue template you deleted, the issues forum is not for support requests.  please be respectful of our time and our processes by following the project documentation.  There is a link in the issue template that instructs you on how to get help.  Thanks.
