### ISSUE TITLE
TimePicker: ng-disabled is in docs but TimePicker is not affected.

### ISSUE THREAD

**Issue by lucasmaj** [angular-ui/bootstrap#5856]
ng-disabled does not appear to have any effect on TimePicker. 

Fix or remove from documentation please

**Comment by wesleycho** [comment]
Please post a reproduction - this issue also does not follow the issue template, please follow it in the future and save everyone some time.

**Comment by icfantv** [comment]
Closing as per [this plunker](http://plnkr.co/edit/vS1KavF66jkKgIuPV7Rs) it is working correctly.

As @wesleycho noted, in the future, please be respectful of our time and processes by adhering to the template.  It is there for everyone's benefit.
