### ISSUE TITLE
two features I think it maybe useful

### ISSUE THREAD

**Issue by lihongming** [angular-ui/bootstrap#5860]
I am thinking to add new feature to DatePicker. 

How about we add two things.

1. Before refreshView, fire a event to tell parent controller, we are going to refresh the calendar, sometimes we need to load some data from Restful API, to make the disableDate works as we want.

2. listen to an event, if the event fires, then refresh the view. For example the data about the disableDate is changed. we can update the calendar as soon as possible.

**Comment by wesleycho** [comment]
We are highly likely not to introduce any eventing to the library. This sounds like incorrect app api design to me.

**Comment by pkozlowski-opensource** [comment]
Agree with @wesleycho - we should not have event-based APIs unless there are _very_ good use cases.

**Comment by icfantv** [comment]
Agreed with @wesleycho and @pkozlowski-opensource.  Closing this as won't support.
