### ISSUE TITLE
Demo site "Dropdown in Container" dropdown has incorrect menu positioning

### ISSUE THREAD

**Issue by skmasq** [angular-ui/bootstrap#5864]
### Bug description:
Dropdown menu is incorrectly position

### Link to minimally-working plunker that reproduces the issue:
http://angular-ui.github.io/bootstrap/#/dropdown
![image](https://cloud.githubusercontent.com/assets/3149408/14915083/c2f3e94e-0e07-11e6-87e1-eaf41fabc92f.png)

### Version of Angular, UIBS, and Bootstrap

Demo site settings for current version (1.3.2)

### Browsers afftected:

- **Chrome**: 50.0.2661.94 m
- **IE**: 11.0.9600.18282
- **FF**: 46.0

**Comment by deeg** [comment]
@skmasq, which button are you clicking on to open the dropdown? The second button (the first blue one) on the top row?

What browser are you seeing this in? I am not seeing this behavior with the current live demo.

**Comment by icfantv** [comment]
@skmasq, this is by design as the demo is showing you how you can bind the dropdown to a specific element and not necessarily the button itself.  please be respectful of our time by performing some initial research on your end before entering anything as dealing with issues can be very time consuming.

**Comment by skmasq** [comment]
Hi @icfantv,

I am sorry that I have wasted your time in any way.

Where I am coming from, the docs say:

`dropdown-append-to` `$` (Default: null) - Appends the inner dropdown-menu to an arbitrary DOM element.
`dropdown-append-to-body` `B` (Default: false) - Appends the inner dropdown-menu to the body element.

What I understood is:
- `dropdown-append-to` instead of being appended to the body element, it would be appended to a specified element while keeping the drop down relative to the button, where the actual drop down would react to the parent elements scroll instead of body elements scroll.

I was not trying to be disrespectful of your time in any way, I just understood the doc that way, my apologies.
