### ISSUE TITLE
Allow Slide content to control Carousel

### ISSUE THREAD

**Issue by ricksmt** [angular-ui/bootstrap#5866]
Feature request for carousel control functions to be accessible in uibSlide content. I just finished hacking a workaround where I passed the functions I needed through the `actual` parameter.

**Comment by icfantv** [comment]
@ricksmt, what functions?  Did you try using `contrillerAs` syntax?

**Comment by wesleycho** [comment]
Can you explain your use case?

**Comment by ricksmt** [comment]
I used the UI Bootstrap modal to pop up a process for sharing some data. There's three pages involved. The first page is a brief explanation of what they're sharing; the second allows them to select who to share it with; the third allows them to add a custom message. The UI was a bit bloated having it all in one page, so I split it into these three parts and used the carousel for rotating between them.

Depending on context, they also have the option of being popped straight to the last page with the option of going back one. Normally they'd start with the first and funnel through or abandon the process/modal.

I wan't the access in the Slide control because then I can style the previous and next buttons and use text to specify where they'll go. I admit it's very different from the traditional use of the carousel. I've already got my workaround, and I suppose I can share that if anyone else happens to have the same use case. I assume this would be a low-priority feature request.

**Comment by icfantv** [comment]
If you want to restyle the controls, then you need to override the template.  From within the template HTML, you have access to any exposed controller functions via controllerAs.  You can select a given slide via the `active` attribute on the `uib-carousel` directive.

I'd like to see, specifically, what you want in order to consider this request as all I'm hearing right now is stuff that you can do using the API.

**Comment by wesleycho** [comment]
This sounds like you're overloading the component - couldn't you have logic in the parent controller that handles the paging without requiring any new functionality from the carousel itself?

It sounds like you have a sufficient workaround that doesn't require api bloat on the library's side. I'm hesitant to add additional support in the library itself for this use case, as it seems like it potentially adds mixed concerns.

**Comment by ricksmt** [comment]
I suppose I could push the paging out to the parent, but I really like each slide handling the quirks on which controls display and what they say.

I'll try to put together a demo, and then you can advise me on a simpler approach, or you'll better understand what I'm requesting.

**Comment by icfantv** [comment]
Closing due to lack of response.
