### ISSUE TITLE
Use notifyCallback in typeahead so results can be dynamically updated

### ISSUE THREAD

**Issue by kingcheez** [angular-ui/bootstrap#5868]
Hi,

This is a feature request along with a patch example against the combined JS to see if it is worth pursuing (I probably won't be able to do it but I wanted to show what I did in case the team decides it's worth doing).

Quite often, I need to search multiple sources, some slow, some quick and combine the results. The user experience I'd like to see is results as soon as they start typing  with progressive refinement until the final results are in.

To accomplish this, I simply used the resolve callback as the notify callback and it seemed to work for my test case.

Here is the patch (against the combined release 0.13.4):
```
@@ -5089,7 +5089,8 @@ angular.module('ui.bootstrap.typeahead', ['ui.bootstrap.position'])
           var locals = {$viewValue: inputValue};
           isLoadingSetter(originalScope, true);
           isNoResultsSetter(originalScope, false);
-          $q.when(parserResult.source(originalScope, locals)).then(function(matches) {
+
+          var callback = function(matches) {
             //it might happen that several async queries were in progress if a user were typing fast
             //but we are interested only in responses that correspond to the current view value
             var onCurrentRequest = (inputValue === modelCtrl.$viewValue);
@@ -5130,11 +5131,16 @@ angular.module('ui.bootstrap.typeahead', ['ui.bootstrap.position'])
             if (onCurrentRequest) {
               isLoadingSetter(originalScope, false);
             }
-          }, function() {
-            resetMatches();
-            isLoadingSetter(originalScope, false);
-            isNoResultsSetter(originalScope, true);
-          });
+          };
+
+          $q.when(parserResult.source(originalScope, locals)).then(
+            callback,
+            function() {
+              resetMatches();
+              isLoadingSetter(originalScope, false);
+              isNoResultsSetter(originalScope, true);
+            },
+            callback);
         };
 
         // bind events only if appendToBody params exist - performance feature
```

**Comment by wesleycho** [comment]
I'm not convinced that this is a good approach - that notification callback is considered an antipattern and should be avoided at all costs, in part due to the poor mechanism for appending the ability to notify progress to a promise, which is non-standard and breaks the promise contract.

I'm going to reject this as for what you are wishing, this should be handled on the user's side with the aggregation of data.

**Comment by kingcheez** [comment]
Thanks for your comment.

Unfortunately, there is no way to force the typeahead to update otherwise. Even if the data is retrieved and the results updated in scope, the typeahead results do not change. Perhaps an extra watch is a better solution? I don't know the codebase well enough to suggest an option.
