### ISSUE TITLE
The case of the first letter of the month changes the parsed result

### ISSUE THREAD

**Issue by mjhamm75** [angular-ui/bootstrap#5869]
I am trying to format my date to `DD MMM YYYY`

If I type `03 Mar 2016`, then it is parsed correctly.

If I enter `03 mar 2016` and it parses as `02 May 2016`.  I would think that the case should not matter when the date is being parsed.

The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by icfantv** [comment]
@mjhamm75 please be respectful of our time and processes by adhering to the issue template.  it is there to allow us to address bugs in a timely manner.  I'm going to close this until you fill in the template and can show this is a bug.
