### ISSUE TITLE
TypeError: date.getTimezoneOffset is not a function

### ISSUE THREAD

**Issue by mebibou** [angular-ui/bootstrap#5871]
### Bug description:

`ng-model` as numeric does not work properly when using `datepicker-popup`. By looking at [this line](https://github.com/angular-ui/bootstrap/blob/bba3f27e3dd9f95463743bf36a15636a746ea3ec/src/datepickerPopup/popup.js#L136) from the source code, I would say that the check for numeric value should be done before and not after, i.e.:
````
$scope.date = dateParser.fromTimezone(value, timezone);

if (angular.isNumber($scope.date)) {
  $scope.date = new Date($scope.date);
}
````
Should be instead:
````
if (angular.isNumber(value)) {
  value = new Date(value);
}

$scope.date = dateParser.fromTimezone(value, timezone);
````
Because `dateParser.fromTimezone` expects a `Date` and not a `Number`, the error `TypeError: date.getTimezoneOffset is not a function` is thrown.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.5
UIBS: 1.3.2
Bootstrap: 3.3.5

**Comment by icfantv** [comment]
I'm on my phone, but at first glance this looks legit.  @wesleycho?

**Comment by wesleycho** [comment]
This sounds legit too, but our intention is to officially remove support for non-date objects for the datepicker.

Feel free to file a PR.
