### ISSUE TITLE
Datepicker popup parsing string issue in input

### ISSUE THREAD

**Issue by HarelM** [angular-ui/bootstrap#5879]
Please see the below plunker generated from the datepicker popup documentation button:
http://plnkr.co/edit/uu2pU2XrwEd0sWLmFjRr?p=preview
Issue description:
I'm getting a date as a string from my server in a json object (the object is large and I can't looks for dates in it).
I bind the object property to the input.
The datepicker popup has the right date inside but the input itself is empty.
after selection from the datepicker the input is working as expected.
am I doing something wrong or is this a bug?
is there a workaround?

**Comment by icfantv** [comment]
As with the datepicker, the model must be a date object.

**Comment by HarelM** [comment]
Thanks for the input.
It is possible some how to add to the documentation the following code which converts dates iso8601 string to date object in angular http.
```js
app.config(["$httpProvider", function($httpProvider) {
        $httpProvider.defaults.transformResponse.push(function(responseData) {
            function convertDateStringsToDates(input) {
                var regexIso8601 = /^(\d{4}|\+\d{6})(?:-(\d{2})(?:-(\d{2})(?:T(\d{2}):(\d{2}):(\d{2})\.(\d{1,})(Z|([\-+])(\d{2}):(\d{2}))?)?)?)?$/;
                // Ignore things that aren't objects.
                if (typeof input !== "object") return input;

                for (var key in input) {
                    if (!input.hasOwnProperty(key)) continue;

                    var value = input[key];
                    var match;
                    // Check for string properties which look like dates.
                    if (typeof value === "string" && (match = value.match(regexIso8601))) {
                        var milliseconds = Date.parse(match[0]);
                        if (!isNaN(milliseconds)) {
                            input[key] = new Date(milliseconds);
                        }
                    } else if (typeof value === "object") {
                        // Recurse into object
                        convertDateStringsToDates(value);
                    }
                }
            }
            convertDateStringsToDates(responseData);
            return responseData;
        });
    }]);
```

**Comment by icfantv** [comment]
I'm guessing you didn't see our `uibDateParser` service which does this for you?

I will update the documentation for the popup to include `ng-model` and will mention the use of our parser service, but adding to an interceptor is beyond the scope of this library as some may not want this behavior.

**Comment by HarelM** [comment]
Actually I did see ```uibDateParser```, but as far as I can understand it's not meant to be used like regexp in order to make sure the string is a date. the ```Date.parse(...)``` in the method above is somewhat closer, but when getting to this place I already know it's a date and the JS parser is sufficient.
I'm not saying this library should support an interceptor, but a reference to a good one in the documentation would help other like me to solve this issue faster, when I tried this lib and angularstrap about a year ago this was one of the reasons I decided to adopt angularstrap, now that I use typescript a lot it gives this library a formidable benifit, this issue almost got me regretting this decision :-/...
Thanks for all the help any way, keep up the good work with this library!

**Comment by icfantv** [comment]
@HarelM, You are correct in that the uibDateParser requires that you know the format of the date.  I've submitted a PR for the documentation update.

On a softer note, having been on your end of things, I understand completely.  Please understand that anything we put in our library or on our site we then have to maintain and support.  We are all _unpaid_ volunteers and as such simply do not have the luxury of giving our users everything they want or think is a good idea.  We have to draw the line somewhere or the library will suffer.

While we of course want you to use our library, you should absolutely use the library that gives you the most benefit (while also being well-maintained).  Thank's for the support.
