### ISSUE TITLE
Tooltip on SVG-element in positioned element is placed incorrectly

### ISSUE THREAD

**Issue by JaZo** [angular-ui/bootstrap#5882]
### Bug description:
Using a tooltip on a SVG-element placed in a positioned element, results in the tooltip being placed incorrectly. I think this bug is present because offsetParent is not available on SVG-elements ([http://stackoverflow.com/questions/5996005/how-to-use-element-offsetparent-with-html-svg-elements](http://stackoverflow.com/questions/5996005/how-to-use-element-offsetparent-with-html-svg-elements)), but that is just an educated guess.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/QSke1BChbF0VO09wvclW?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.3

UIBS:
1.3.2

Bootstrap:
3.3.6

**Comment by RobJacobs** [comment]
You can wrap your svg in another element and place the tooltip on that, demo [plunk](http://plnkr.co/edit/nXiLTKCfcrnHelYbD24M?p=preview)

**Comment by icfantv** [comment]
closing as a support issue w/ resolution.
