### ISSUE TITLE
popover width keeps shrinking

### ISSUE THREAD

**Issue by vincentcialdella** [angular-ui/bootstrap#5884]
Hi,
I've migrated from 1.0.3 to 1.3.2 and popover has now a strange behaviour when it is visible: its width keeps shrinking each second (approximatively).

This occurs in $uibTooltip provider and especially here : 

    `var positionTooltip = function() {
              // check if tooltip exists and is not empty
              if (!tooltip || !tooltip.html()) { return; }

              if (!positionTimeout) {
                positionTimeout = $timeout(function() {
                  var ttPosition = $position.positionElements(element, tooltip, ttScope.placement, appendToBody);
                  tooltip.css({ top: ttPosition.top + 'px', left: ttPosition.left + 'px' });

                  if (!tooltip.hasClass(ttPosition.placement.split('-')[0])) {
                    tooltip.removeClass(lastPlacement.split('-')[0]);
                    tooltip.addClass(ttPosition.placement.split('-')[0]);
                  }

                  if (!tooltip.hasClass(options.placementClassPrefix + ttPosition.placement)) {
                    tooltip.removeClass(options.placementClassPrefix + lastPlacement);
                    tooltip.addClass(options.placementClassPrefix + ttPosition.placement);
                  }

                  // first time through tt element will have the
                  // uib-position-measure class or if the placement
                  // has changed we need to position the arrow.
                  if (tooltip.hasClass('uib-position-measure')) {
                    $position.positionArrow(tooltip, ttPosition.placement);
                    tooltip.removeClass('uib-position-measure');
                  } else if (lastPlacement !== ttPosition.placement) {
                    $position.positionArrow(tooltip, ttPosition.placement);
                  }
                  lastPlacement = ttPosition.placement;

                  positionTimeout = null;
                }, 0, false);
              }
            };`
The code that changes the width is this one 
`tooltip.css({ top: ttPosition.top + 'px', left: ttPosition.left + 'px' });`

ttPosition.left keeps increasing and therefore the width is shrinling.

I have seen that this method keeps being called by this code 
`observers.push(
                  tooltipLinkedScope.$watch(function() { 
                    if (!repositionScheduled) { 
                      repositionScheduled = true; 
                      tooltipLinkedScope.$$postDigest(function() { 
                        repositionScheduled = false; 
                        if (ttScope && ttScope.isOpen) { 
                          positionTooltip(); 
                        } 
                      }); 
                    } 
                  }) 
                );` 

Thanks for your help.

[EDIT]
Actually I found the source of the bug: it is because I'm settinf a max-width css rule on .popover class. How to properly fiw the width of a popover ?

**Comment by icfantv** [comment]
@vincentcialdella, the issues forum is not for support requests.  if you think you've found a bug, you need to adhere to the template so that we may more quickly help you.  We simply do not have the time to create reproducible plunkers from pasted code.  I'm going to close this until you can show that this is a bug in our library.  Thanks.

We are overriding the max width in our project and I don't see any issues.  We are still on 1.1.2, however.
