### ISSUE TITLE
How can I set the ui-tabset breakpoint to xs?

### ISSUE THREAD

**Issue by jamesla** [angular-ui/bootstrap#5885]
I have looked through the documentation and have searched through the issues tab and am unable to find an answer.

How can I set the ui-tabset directive to break at the xs breakpoint?

(just to confirm this is when the tab headings break (and stack vertically) not the content itself).

```
<div class="container-fluid">
      <uib-tabset justified="true">
        <uib-tab heading="tab1">
           .....
        </uib-tab>
        <uib-tab heading="tab2">
          .....
        </uib-tab>
      </uib-tabset>
    </div>
  </div>
```

**Comment by icfantv** [comment]
@jamesla, please be respectful of our time and our process by adhering to the issue template, the first line of which indicated that the issues forum is not to be used for support requests.  Thanks.  As this is clearly a support request, I am closing this.

Additionally, it is not at all clear what you mean by "xs" breakpoint.
