### ISSUE TITLE
uibTabset scope's active property is useless

### ISSUE THREAD

**Issue by e-cloud** [angular-ui/bootstrap#5888]
#### Version of Angular, UIBS, and Bootstrap
UIBS: latest-v1.3.2

After i read through the `tabs.js`, there is no other usage of `scope.acitve` in `uibTabset` directive

**Comment by RobJacobs** [comment]
The active property is most definitely used.  If you can create a plunk where it's not working as you expect I will re-open this issue.

**Comment by icfantv** [comment]
@e-cloud, the active property defines the index of the active tab.  It is how you can programmatically select tabs and you can determine the index of the actively selected tab.  It is also how we, internally, determine which tab is active and we use that to control the state of the selected tab (which is used for CSS purposes).

As documented in our code a few lines up from your highlighted section, you'll note that he `uibTabset` directive has a controller `UibTabsetController` and if you read that controller, you'll see that the `active` property features quite prominently.

In the future, please be respectful of our time and do your due diligence before entering issues.  Additionally, please become familiar with our [Code of Conduct](https://github.com/angular-ui/bootstrap/blob/master/CODE_OF_CONDUCT.md) and refrain from using such flippant remarks in your issue reports.  Thank you.

**Comment by e-cloud** [comment]
did you read my description? what i referred to is `scope.active`, not `active` attribute binded to the controller...

**Comment by e-cloud** [comment]
those lines of code are just like deadzone, there is no other logic concerning about that

**Comment by RobJacobs** [comment]
The active scope property is used by the templates:

https://github.com/angular-ui/bootstrap/blob/master/template/tabs/tab.html#L1

https://github.com/angular-ui/bootstrap/blob/master/template/tabs/tabset.html#L6

**Comment by e-cloud** [comment]
nope, `tabset.active` has no connection with `scope.active`
and, the `active` of `tab` directive has its own management, also no connection with `scope.active`

However, this kind of argument urges me to understand the tab source better.

**Comment by RobJacobs** [comment]
@e-cloud You are correct, sorry for the misunderstanding.  I will create a PR shortly and remove the code, thanks for reporting this.
