### ISSUE TITLE
uib-datepicker-popup in uib-accordion does not fire $scope.$watch bindings

### ISSUE THREAD

**Issue by dalibor983** [angular-ui/bootstrap#5892]
### Bug description:
When you have `uib-datepicker-popup` in `uib-accordion` and if you attach function with `$scope.$watch` to scope property that is bound to `uib-datepicker-popup` with `ng-model` attirbute watch function is called only once (before `uib-accordion` is rendered) and scope property is unbound from `uib-datepicker-popup`.

### Link to minimally-working plunker that reproduces the issue:
[Date picker in accordion](http://plnkr.co/edit/WAB5Fzog260tkc0mKLjs)

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.5

UIBS: 1.3.2

Bootstrap: 3.3.6

**Comment by RobJacobs** [comment]
Please see this [article](https://github.com/angular-ui/bootstrap/wiki/FAQ) for working with scope in an accordion.  If you find there is still an issue after implementing the datepicker inside of the accordion as suggested, let me know and I will re-open this issue.

**Comment by dalibor983** [comment]
I put `$parent` scope prefix in `ng-model` and it is not working but when I use `someObj.` it is working.
This is working sample [Date picker in accordion with someObj](http://plnkr.co/edit/X4YFWbEzaitLI5PQZAeF?p=preview)
