### ISSUE TITLE
Tooltip is getting cut with the left placement if the text is long.

### ISSUE THREAD

**Issue by smnth90** [angular-ui/bootstrap#5893]
For the tooltip example code of 'angular ui bootstrap' documentation, I have added some extra (long) text to the "uib-tooltip" attribute of the tooltip top button which is on the top and left side of the page. Now, when I hover on the tooltip top button, some part of the tooltip to the left is getting cut. 

The plnkr link is "http://plnkr.co/edit/NJppfHltSrhiSzpdpUPn?p=preview"

### Version of Angular, UIBS, and Bootstrap
Used existing code from the 'angular ui bootstrap' documentation.
Angular: 1.5.3

**Comment by RobJacobs** [comment]
That's why the 'auto' placement is available, changing the code to:

    <button tooltip-placement="auto + {{placement.selected}}" uib-tooltip="On the {{placement.selected}} If the text is long, tooltip is getting cut for the left placement " type="button" class="btn btn-default">Tooltip {{placement.selected}}</button>

will keep the tooltip from rendering off the page.  We don't want to force folks into that behavior if they would rather have complete control over the placement.

**Comment by smnth90** [comment]
Oh! That's great. Thank you @RobJacobs
