### ISSUE TITLE
Popover/tooltip positioning with text overflow container

### ISSUE THREAD

**Issue by peterreisz** [angular-ui/bootstrap#5894]
In html tables if you want to add a tooltip/popover for a long cell (with overflow: hidden option) the UIB using the whole content for positioning the tooltip/popover. The result is the tooltip/popover seems to be on a different cell or not in the middle of the actual cell of the html table.

![image](https://cloud.githubusercontent.com/assets/11595433/15215263/e4f552ea-1851-11e6-83b1-cb9e2ab06a1d.png)

See the example here: http://plnkr.co/edit/UUyCbS2EfN62Z1QsLhXO?p=preview
Hover on the first cell.

Versions:

Angular: 1.5.5
UIBS: 1.3.2
Bootstrap: 3.3.6

I've needed a fast runtime patch for my project, so I used the following decorator, it might be useful.

```js
$provide.decorator('$uibPosition', function($delegate) {
	
	var orgPositionElements = $delegate.positionElements;
	
	$delegate.positionElements = function(hostElem, targetElem, placement, appendToBody) {
		var originalPosition = orgPositionElements.call($delegate, hostElem, targetElem, placement, appendToBody);
		var parent = hostElem.parent()[0];
		if ((hostElem.attr('uib-popover') || hostElem.attr('uib-tooltip'))
				&& hostElem.parent()[0].tagName == 'TD' && parent.scrollWidth > parent.clientWidth) {
			var newPosition = orgPositionElements.call($delegate, hostElem.parent(), targetElem, placement, appendToBody);
			newPosition.top = originalPosition.top;
			
			return newPosition;
		}
		
		return originalPosition;
	}
	
	return $delegate;
})
```

**Comment by icfantv** [comment]
@peterreisz i'm sorry.  is this a bug?

**Comment by peterreisz** [comment]
It might be.

You can see my issue better if the text is very long in the cell:

![image](https://cloud.githubusercontent.com/assets/11595433/15221577/4b64e7f6-186c-11e6-9d2b-9053fc4587ac.png)

I'd expect this:
![image](https://cloud.githubusercontent.com/assets/11595433/15221671/bc46da2e-186c-11e6-9f96-09f7188abf5d.png)


Now I can achieve only similar with tooltip on the td and append-to-body:

![image](https://cloud.githubusercontent.com/assets/11595433/15221942/d6fdca20-186d-11e6-8144-60bfeef72f64.png)


If you don't want to support situations for positioning only for the visible part, then close this issue.

**Comment by icfantv** [comment]
@RobJacobs you have a thought on this?

**Comment by wesleycho** [comment]
This looks like a user issue - with a slight modification, I was able to get this to work [here](http://plnkr.co/edit/yDp59UiKYoHxJDEZ2VTD?p=preview).

Closing as a non-issue.
