### ISSUE TITLE
datePickerPopup datepicker-options two way binding problem with start Mode

### ISSUE THREAD

**Issue by v4l3r10** [angular-ui/bootstrap#5895]
Hi!

I have a problem with datepickerPopup and datepicker-options.
In my page there are n datepickers generated by ng-repeat:

```
<div class="datepicker datepicker-popup">
	<input class="form-control" readonly="" type="text" 
	name="date[$index]"
	show-button-bar="false" 
	ng-change="scope.datePickerChange($index)" 
	uib-datepicker-popup="{{scope.datePicker.format}}" 
	ng-click="scope.openDatePicker($index)" 
	ng-model="scope.bs.pax[$index].birthday" 
	is-open="scope.datePicker.open[$index]" 
	datepicker-options="scope.datePicker.dateOptions" 
</div>
```

this is my datepickerOptions:

```
    //Init date picker
    scope.datePicker = {
      format : 'dd/MM/yyyy',
      dateOptions : {
        startingDay : 1,
        showWeeks : false,
        yearRows : 4,
        yearColumns : 5,
	maxDate : new Date(),
        initDate : new Date('67,12,07'),
	datepickerMode : 'year'
      },
      open : []
    };
```

When  i select from first "date picker" it start in YEAR mode and all works fine.
After if i click on another one "datepicker" in page, bound to same datepickerOption
 it start from the last mode of datepicker used previously 
I have checked code and i have seen that datepickerOptions is two way binding:

```
 scope: {
            datepickerOptions: "=?",
            isOpen: "=?",
            currentText: "@",
            clearText: "@",
            closeText: "@"
        },
```
so everytime that the mode is changed inside the datepicker it propagates to datepickerOption in scope.

you can test this bug in (http://angular-ui.github.io/bootstrap/#/datepickerPopup)  official page.
Select in first datepicker a Year  and open the other datepicker. It get same "datepickerMode"

Angular: 1.4.5

UIBS: 1.3.2

Bootstrap: 3.3.5

**Comment by icfantv** [comment]
I would argue that this is not a bug and is intended behavior.  @wesleycho, thoughts?  I'm inclined to reject this.

**Comment by wesleycho** [comment]
This is not a bug - if one does not desire it doing that, one can simply watch the `is-open` property and reset the state.

But the question does remain, is this desired? If we were to reset this on the datepicker side, how do we know what the default should be? I posit there isn't a good way to do so on the library side that isn't restrictive, and thus should not be supported in the library itself as the default.

Going to close as per determination.
