### ISSUE TITLE
Modal's new resolve feature won't work with route query method

### ISSUE THREAD

**Issue by PartyArk** [angular-ui/bootstrap#5897]
This is a neat feature, but it's broken with query.

The reason is that query returns a weird hybrid of array and object. It's an Array (because that's the result it's expecting) but it also has the single $promise property. Resolve sees it's an array and thinks it's an array of promises; but it's just a single promise of the type array.

I will try to do a plunker, but I'm not sure how to mock the query method.

**Comment by wesleycho** [comment]
Can you post an example block of code or a Plunker with what you mean? This is confusing as written.

**Comment by wesleycho** [comment]
Closing due to lack of actionable information.
