### ISSUE TITLE
tabs and forms setPristine issue

### ISSUE THREAD

**Issue by kukac7** [angular-ui/bootstrap#5898]
### Bug description:
I have a form. After submitting I want to call `$setPristine()`.
Error message: `Cannot read property '$setPristine' of undefined`

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/cr9KWYT2i3VIuANJt2Uj?p=preview
The `submitForm()` reset the model and call `$setPristine()`.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.2

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@kukac7, the bug is in your code.  you are trying to reference the form from the wrong scope.
