### ISSUE TITLE
[popover/tooltip] Support Programmatic Triggers

### ISSUE THREAD

**Issue by joshdmiller** [angular-ui/bootstrap#590]
The upstream JavaScript version supports `trigger="manual"` to allow for programmatic triggering.

**Comment by christopherthielen** [comment]
@asafdav @marian2js Thanks for your code.  I had a problem where the toggle functionality was becoming confused whether or not the tooltip should be shown, when the tooltips had a popup delay.  

This was due to `toggleTooltipBind` being used.  `ttScope.isOpen` is not set to true until `show()` function executes, which happens after the delay timeout.  Thus:

- the expression becomes truthy
- it invokes `toggleTooltipBind`
- delays (for 1 second, let's say)
- the expression becomes falsey before `show()` is called
- `toggleTooltipBind` is invoked again
- ttScope.isOpen is still false, so it invokes `showTooltipBind()` again

I fixed this by registering a custom event *pair* and invoking the proper one based on truthy/falsey.

See this gist: 
https://gist.github.com/christopherthielen/4980c9117f3185906627

**Comment by sdasun** [comment]
@asafdav  @marian2js  @christopherthielen Why these examples only work with old angular-js none of these examples working with angular-js 1.3.9

**Comment by christopherthielen** [comment]
@sdasun FYI I'm using (a modified version of) my gist on angular 1.3.4 and ui-bootstrap 0.12.0

**Comment by christopherthielen** [comment]
@sdasun yeah it works fine for me:
http://plnkr.co/edit/yaENfy8Tbmxz6hcRNsY1?p=preview

**Comment by sdasun** [comment]
@christopherthielen  Thanks for Plnk r:+1: , I think something in my app interfering the event trigger.

**Comment by sdasun** [comment]
@christopherthielen worked after updating my ui-bootstrap from 0.11.0v to 0.12.0 :+1:

**Comment by ingshtrom** [comment]
1. I tried @luthur's fix by loading 0.12.1 of ui.bootstrap, but couldn't get it to work. I followed the examples given in this thread but nothing worked.  I am using angular 1.2.28 and it looked like it was compatible with that version. What exactly do I need to do to get it working?
2. Alternatively, I tried the plunkr given by @christopherthielen, but had to modify it to get it to work. The `closeTrigger` wasn't working for me.  Every time I sent the `openTrigger` event, it toggled the tooltip, so I modified his code to work for me. Any ideas why I would have such a different experience?

``` javascript
'use strict';

angular.module('ngen.shared')
    .directive('popPopup', function () {
        return {
            restrict: 'EA',
            replace: true,
            scope: { title: '@', content: '@', placement: '@', animation: '&', isOpen: '&' },
            templateUrl: 'template/tooltip/tooltip-popup.html'
        };
    })

    .directive('pop', function($tooltip, $timeout) {
        // Create a tooltop directive with the ui-bootstrap $tooltip service
        var tooltip = $tooltip('pop', 'pop', 'customTrigger'),
            compile = angular.copy(tooltip.compile),
            isFirstTime = true;

        // register a custom compile function on our directive which decorates the stock compile fn
        tooltip.compile = function customCompile(element, attrs) {
            // Invoke the parent compile function to receive the parent linkFn
            var parentLinkFn = compile(element, attrs);

            return function popLinkFn (scope, element, attrs) {
                // it doesn't matter what the value is, as long as it is changing.
                attrs.$observe('popShow', function () {
                    $timeout(function () {
                        // only trigger on subsequent calls
                        // the first call always happens when
                        // we load the app for the first time
                        if (isFirstTime) {
                            isFirstTime = false;
                            return;
                        }
                        element.triggerHandler('customTrigger');
                    });
                });

                // invoke the parent link fn
                parentLinkFn(scope, element, attrs);
            };
        };

        return tooltip;
    });
```

**Comment by lmk123** [comment]
@danludwig I use your solution and it works well for me, thanks!

**Comment by ognus** [comment]
I've found that using a simple custom directive worked best for my use case. I just want to be able to close the popover from within the popover template.

The directive exposes `scope.toggle` method that user custom trigger to open and close popover. I'm then using this method in the popover template.

# JS
```javascript
'use strict';

angular.module('main.directives')

.config(function($tooltipProvider) {
  $tooltipProvider.setTriggers({'open': 'close'});
})

.directive('popoverToggle', function($timeout) {
  return {
    scope: true,
    link: function(scope, element, attrs) {
      scope.toggle = function() {
        $timeout(function() {
          element.triggerHandler(scope.openned ? 'close' : 'open');
          scope.openned = !scope.openned;
        });
      };
      return element.on('click', scope.toggle);
    }
  };
});
```
# Example
### remove_popover_templ.html
```html
<p>Are you sure you want to remove this item?</p>
<a href='' ng-click='remove(item)'>Yes</a> 
<a href='' ng-click='toggle()'>No</a>
```

### list_of_items.html
```html
<div ng-repeat='item in items'>
  {{item.name}} 
  <a
      href=''
      popover-toggle
      popover-template="'remove_popover_templ.html'"
      popover-trigger='open'>
    Remove</a>
</div>
```

**Comment by DumboJetEngine** [comment]
+1

> Thinking about dialogs / tooltips / popovers - maybe it would be a good idea to have a $tooltip / $popover service (as we've got the $dialog one) so people can trigger popovers / tooltips as they like. Basically give people a way to control popovers / tooltips programatically. WDYT?

I am all for it. :)
That `$modal` service of your is the best angular thing I have laid my hands on.
Now I need a `$popover` service that works similarly, but apparently it doesn't exist yet. :(

**Comment by rodrigosaling** [comment]
@ognus thank you for your code. I was having a lot of trouble trying to add a simple close button in my popover, and you solved it perfectly!

**Comment by ognus** [comment]
@rodrigosaling great, glad it helped :)
@pkozlowski-opensource +1 for $popover service

**Comment by solispauwels** [comment]
$scope.$emit('$locationChangeSuccess'); This will close all tooltip or popovers

**Comment by windmaomao** [comment]
thank you very much ognus, works really really well.

**Comment by johanhenrikssn** [comment]
@ognus Thanks! Your solution worked great.

**Comment by stl-winniechan** [comment]
@ognus Thank you!

**Comment by ognus** [comment]
@WilliamRandol @johanhenrikssn @stl-winniechan no problem

**Comment by johanhenrikssn** [comment]
@ognus Trying to use controller as instead of scope in my application. How would I modify that directive to use controller as instead of scope?

**Comment by basco-johnkevin** [comment]
+1

**Comment by yaring** [comment]
Thanks @ognus !

+1

**Comment by ognus** [comment]
@johanhenrikssn just create a controller and move toggle method there instead exposing it to the scope. See http://plnkr.co/edit/iiP0t8 for working example.

**Comment by krnlde** [comment]
@ognus Your example works great for `popover-template` so far. Thanks for that! However it doesn't work when using normal `popover`. I overwrote the template by just adding a close button there.

```js
angular.module("template/popover/popover.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("template/popover/popover.html",
    "<div class=\"popover\"\n" +
    "  tooltip-animation-class=\"fade\"\n" +
    "  tooltip-classes\n" +
    "  ng-class=\"{ in: isOpen() }\">\n" +
    "  <div class=\"arrow\"></div>\n" +
    "\n" +
    "  <div class=\"popover-inner\">\n" +
    "      <h3 class=\"popover-title\" ng-if=\"title\">{{title}} <button type=\"button\" class=\"close\" ng-click=\"popoverCtrl.toggle()\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button></h3>\n" +
    "      <div class=\"popover-content\" ng-bind=\"content\"></div>\n" +
    "  </div>\n" +
    "</div>\n" +
    "");
}]);
```

Do you have a suggestion why this doesn't work? Is "isolated scope" a catchphrase here?

**Comment by krnlde** [comment]
Bump

**Comment by Elijen** [comment]
This seems to be very demanded feature. Can you guys @pkozlowski-opensource @ProLoser let us know how should this be solved so somebody can create a PR?

I am not sure what happened with @luthur's original PR.

**Comment by Elijen** [comment]
Meanwhile I created a Bower package including `popoverToggle` directive, if anyone is interested:
https://github.com/Elijen/angular-popover-toggle

**Comment by krnlde** [comment]
Thank you for your effort @Elijen! Unfortunately this doesn't really help since I (we) really want to use the original [repo](/angular-ui/bootstrap) and not implement every module of bootstrap seperately from different repos just because the main repo has a slow to no progress. One week and nothing happend on this topic - sadly the maintainers do not really feel responsible to answer here.

**Comment by Elijen** [comment]
@krnlde That's strange, I think it should work with both `popover` and `popover-template` directives. I will check out tomorrow.

**Comment by Elijen** [comment]
@krnlde Seems to work: http://plnkr.co/edit/QeQqqEJAu1dCuDtSvomD?p=preview

**Comment by krnlde** [comment]
Ah I see. What I mean it is not working when putting the close trigger in the template for the popover itself - like we need this closing cross inside the `.popover-title`:

```js
angular.module("template/popover/popover.html", []).run(["$templateCache", function($templateCache) {
  $templateCache.put("template/popover/popover.html",
    "<div class=\"popover\"\n" +
    "  tooltip-animation-class=\"fade\"\n" +
    "  tooltip-classes\n" +
    "  ng-class=\"{ in: isOpen() }\">\n" +
    "  <div class=\"arrow\"></div>\n" +
    "\n" +
    "  <div class=\"popover-inner\">\n" +
    "      <h3 class=\"popover-title\" ng-if=\"title\">{{title}} <button type=\"button\" class=\"close\" ng-click=\"isOpen != isOpen\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button></h3>\n" +
    "      <div class=\"popover-content\" ng-bind=\"content\"></div>\n" +
    "  </div>\n" +
    "</div>\n" +
    "");
}]);
```

This is because the scope of the template is another than the one you put the toggle in and they don't inherit from each other.

**Comment by Elijen** [comment]
@krnlde You should be to use `$parent.isPopoverOpen` (or what ever you named the $scope variable) from within the template.

Here is a plunkr: http://plnkr.co/edit/wIgZzH1Dw1Bm7QtZvZMn?p=preview

**Comment by krnlde** [comment]
Thanks for your plunkr, but it achieved a goal I'm not looking for. I want to add the close button inside the `.popover-title` which means the *original popover template* provided by bootstrap, not from my angular stuff. Here is your plunkr updated with my requirements (and not working):
http://plnkr.co/edit/5XTTgnnQlnlpcFiAS5IU?p=preview

**Comment by krnlde** [comment]
Do you guys have any news on that?

**Comment by aug-riedinger** [comment]
:+1: here. I don't understand why this is not already available ...

**Comment by mudassir0909** [comment]
@Elijen Pretty neat! :+1:

**Comment by aug-riedinger** [comment]
Sweat! Thanks!

**Comment by aug-riedinger** [comment]
I can't make it work though. :(

I have cloned the repo and built it with Grunt (AFAIK [official releases](https://github.com/angular-ui/bootstrap/tree/gh-pages#build-files) don't include the commit yet). It generated a `0.13.4-SNAPSHOT` version.

But if I have

```
<div tooltip="Hello" tooltip-is-open="true"></div>
```

it doesn't work. Did I miss something?

**Comment by RobJacobs** [comment]
@aug-riedinger It's meant to bind to a property in your controller.

**Comment by aug-riedinger** [comment]
Correct me if I'm wrong, but having `$scope.showTooltip = true` in the controller and `<div tooltip="Hello" tooltip-is-open="showToolip"></div>` is the same as `<div tooltip="Hello" tooltip-is-open="true"></div>`

At least that's how it works for every other directive I use.

Do you maybe have a working example available?

**Comment by aug-riedinger** [comment]
Cool it works!

I get an error message though:

```
TypeError: isOpenExp.assign is not a function
    at show (http://localhost:3000/assets/vendor/ui-bootstrap-tpls-0.13.4.js?body=1:3345:27)
    at showTooltipBind (http://localhost:3000/assets/vendor/ui-bootstrap-tpls-0.13.4.js?body=1:3308:17)
    at toggleTooltipBind (http://localhost:3000/assets/vendor/ui-bootstrap-tpls-0.13.4.js?body=1:3286:17)
    at Object.<anonymous> (http://localhost:3000/assets/vendor/ui-bootstrap-tpls-0.13.4.js?body=1:3481:19)
    at Object.scopePrototype.$watch.arguments.(anonymous function) [as fn] (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1905:36)
    at Scope.$get.Scope.$digest (http://localhost:3000/assets/vendor/angular.js?body=1:14244:29)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1924:23)
    at Scope.$get.Scope.$apply (http://localhost:3000/assets/vendor/angular.js?body=1:14507:24)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1987:22)
    at onUpdateTime (http://localhost:3000/assets/vendor/videogular.js?body=1:195:14)(anonymous function) @ angular.js?body=1:11608$get @ angular.js?body=1:8558$get.Scope.$digest @ angular.js?body=1:14262scopePrototype.$digest @ hint.js:1924$get.Scope.$apply @ angular.js?body=1:14507scopePrototype.$apply @ hint.js:1987onUpdateTime @ videogular.js?body=1:195onLoadMetaData @ videogular.js?body=1:173
```

**Comment by icfantv** [comment]
@aug-riedinger requests for support should go through the official, documented channels.  Comments on closed issues are very easily lost.

Here's your example:  http://plnkr.co/edit/DMqpDWJyRgDRPRbYr1Mx.

**Comment by dozed** [comment]
This means one cant use arbitrary expressions as value for `is-open`, e.g. `signinForm.$isValidated && signinForm.loginEmail.$invalid` ?

**Comment by RobJacobs** [comment]
@dozed Expression support was added under PR #4380 and is merged into the master branch.

**Comment by dozed** [comment]
@RobJacobs thanks! :)
