### ISSUE TITLE
Does popover/tooltip need to have slider if the content is too long that created dom cannot be totally placed in window

### ISSUE THREAD

**Issue by ruiann** [angular-ui/bootstrap#5901]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:1.5.5

UIBS:1.3.2

Bootstrap:

**Comment by RobJacobs** [comment]
Use the 'auto' placement feature to keep your tooltips/popovers within the bounds of the window.

**Comment by ruiann** [comment]
@RobJacobs i know the auto placement, but what if i don't want the auto to change the layout position but want the popover absolutely in the top?
