### ISSUE TITLE
Datepicker Popup restore value problem

### ISSUE THREAD

**Issue by taudienkk** [angular-ui/bootstrap#5902]
Hi,
I have an issue with the datepicker popup. In the version 0.13.0, the ng-model accepted the variable as string
`<input type="text" class="form-control" datepicker-popup="yyyy-MM-dd" ng-model="dt" is-open="opened" datepicker-options="dateOptions" ng-required="true" close-text="Close" /`

`$scope.dt = '2011-05-25'`
[http://plnkr.co/edit/GkwxGzMce2ZiRNuKWetK?p=preview](url)

I have updated to use latest version 1.3.2, the ng-model need to be initiated as Date object to make the value restore in the input, otherwise the input is empty.
` <input type="text" class="form-control" uib-datepicker-popup="yyyy-MM-dd" ng-model="dt" is-open="opened" ng-required="true" close-text="Close" />`
[http://plnkr.co/edit/1VJzkK0HMdLn4yPxzSNx?p=preview](url)

Is there anyway to make the datepicker work with the string value as input?

**Comment by wesleycho** [comment]
We do not support strings anymore because there are timezone issues that manifest that are unfixable, and increase the complexity of the internals tremendously.

I would recommend instantiating it as a date before binding to the view.
