### ISSUE TITLE
Find Bug ! 

### ISSUE THREAD

**Issue by anilreddy100** [angular-ui/bootstrap#5904]
### Bug description: Internet explorer any version not supporting icons such as <i class >..!

1.<a>ccc<i class = "icon-eye-open icon-large icon-white"></i></a>
2.<a data-ng-click="" data-popover="View Statement" data-popover-trigger="mouseenter"><i class = "icon-eye-open icon-large icon-white"></i></a>
please inform why its not came is it versions problem or other else .
 

### Version of Angular 1.2.18 , UIBS, and Bootstrap

Angular:1.2.18

UIBS: 0.6.0

Bootstrap:0.6.0

**Comment by icfantv** [comment]
@anilreddy100, if the versions you've specified are to be believed, I would encourage you in the absolute _strongest_ of terms to consider upgrading to the latest.  I apologize, but there is simply no way we are going to be able to support a version that is several years old.

Secondly, please be respectful of our time and our processes by taking a _little_ more time to complete the issue template properly.  Thanks.
