### ISSUE TITLE
Possible bug with Tooltip when used in a Button that opens a Modal

### ISSUE THREAD

**Issue by gslender** [angular-ui/bootstrap#5910]
### Bug description: 
When you add a Tooltip to a Button that opens a Modal, the MouseEnter event will show the tooltip correctly, but when you click the button (which opens a Modal), the z-index of the Tooltip is above that of the Modal and the Tooltip stays visible. 

Essentially the bug is that I don't believe there is a way (at least not simple or obvious) to close/hide the tooltip on button click, and perhaps a method can be added to solve this?

### Version of Angular, UIBS, and Bootstrap
Angular: v1.5.3
UIBS: v1.3.2 
Bootstrap: v3.3.6

**Comment by gslender** [comment]
I appreciate there is probably a range of overly complex ways to manage this, but surely a Tooltip on a button that performs an action should automatically close/hide the Tooltip - at least that seems like a fairly common requirement that should be easily performed without a stub of extra code for each button.

**Comment by icfantv** [comment]
Hi, this is exactly why we added the `is-open` attribute, so you can control it yourself.  Please make sure you select the appropriate trigger.

**Comment by gslender** [comment]
I'm not convinced using the is-open attribute is an efficient or effective method. Doing so has added a lot of complexity and additional scope variables that aren't making the use of tooltips very effective.

As such, I'm now looking for an alternative or simply not using tooltips - the solution you've provided doesn't work as gracefully as would be expected.

If I go to the trouble to put together a sample demo, will you take the time to recommend a solution or alternatively update the implementation of tooltip to be more effective?
