### ISSUE TITLE
Nested tabs: problem with activation on second level

### ISSUE THREAD

**Issue by spinjam** [angular-ui/bootstrap#5912]
**Bug description:**
I use "uib-tabset" with 2 level of tabs generated dynamically.
When I select a tab from the first level, the first tab on the second level should activate but this does not happen. 
Moreover the var used to track 2nd level index (is.lev2) is empty.

**Plunker:**
http://plnkr.co/edit/YmMNqA99XGCSoZzkDj5T?p=preview

Angular: 1.5
UIBS: 1.2.5
Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@spinjam, while I won't say that this is a bug, IMO, using nested tabs is an absolutely _horrible_ UX and as such I can't recommend to the team that we support this use case.  @wesleycho, thoughts?

**Comment by spinjam** [comment]
I agree that nested tabs are a terrible solution, but the project I'm working on is born that way.
I fixed the behaviour with a $watch on the variable that tracks the first level active tab (just updated the plunker with this workaround). Thanks.
