### ISSUE TITLE
Indeterminant tooltip position with element near screen edge

### ISSUE THREAD

**Issue by Jefftopia** [angular-ui/bootstrap#5914]
### Bug description:

UIB tooltip alternates between bad position and desired position. Specifically, with elements near the edge of the screen. In this case, a float-right anchor. The tooltip has default position (top).

You'll notice that changing the element tag has no affect, and neither does changing the positioning to, for example, absolute with right: 0. The same result: an indeterminant tooltip position. I think it must therefore be related to the screen edge.

I explored whether this was a caching issue. I do not believe so. I am precaching locally and it does not resolve the issue. In the plunkr, I cache the template, and have verified it is in my chrome cache by inspecting `chrome://cache`.

### Link to minimally-working plunker that reproduces the issue:

Plunker is [here](http://plnkr.co/edit/eMulLM04mYtyr7yhAhl6?p=preview).

### Version Info
Angular: 1.5.3

UIBS: 1.3.2

Bootstrap: 3.3.6

**Comment by RobJacobs** [comment]
This is because the text is wrapping in the tooltip causing the tooltip container to grow.  I believe the TWBS exhibits the same problem.

**Comment by wesleycho** [comment]
I think this can be solvable if we modify the `$uibPosition.positionElement` method to insert the element into the DOM to properly calculate the height and then calculate proper positioning I think @RobJacobs .

**Comment by wesleycho** [comment]
I should note that since this is a breaking change, this will be fixed upon major version release, so 2.0.0 at earliest (after our 1.3.3 release, we are likely to start work on it).

**Comment by Jefftopia** [comment]
@RobJacobs  @wesleycho Thanks for the responses. I'll be sure to keep an eye on this ticket.

**Comment by wesleycho** [comment]
Going to close as tracked by #5918
