### ISSUE TITLE
Clicks handled by button release, not push. App feels laggy

### ISSUE THREAD

**Issue by mStirner** [angular-ui/bootstrap#5915]
### Bug description:
Clicks handled by release not by push.
The app feels laggy, and not smooth

### Link to minimally-working plunker that reproduces the issue:
All demos

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.5

UIBS: 1.3.2

Bootstrap: 3

**Comment by wesleycho** [comment]
This needs to be a lot more descriptive.

**Comment by mStirner** [comment]
As example go to: http://angular-ui.github.io/bootstrap/#/tabs
Click on a Tab and hold the mouse key down, the tab is not switching content.
If you release the key, the new tab content is showing.

This make a "laggy" feeling.
But i am not sure if this came from ui bootstrap or from the Angular core.

When i click on other <a> elements, i have the same problem.

**Comment by icfantv** [comment]
I'm pretty sure this is because a click is defined as a mouse down and a mouse up.  I would argue that well defined UX (in most cases) dictates that a selection is done with a mouse click and not a mouse down.

**Comment by mStirner** [comment]
Is it possible to change that global in an AngularJS App ?

**Comment by icfantv** [comment]
I think you may be missing my point.  Why would you want to?  If well-defined UX for selection is a full click, and everyone is used to it, why would you change that?  That would be like changing double-click behavior for an OS.

**Comment by wesleycho** [comment]
Going to close this as won't support - this suggestion completely breaks the UX of the web, especially with regards to buttons and links.
