### ISSUE TITLE
Angular ui-tab not refreshing after hiding

### ISSUE THREAD

**Issue by mnaouali** [angular-ui/bootstrap#5916]
I'm looking to hide tabs and then display them, but I'm facing a refreshing problem. In fact if I select one chart then click on the hide botton to display the grid, it hides the other tabs but it displays always the nvD3 charts instead of the ui-grid. even in the charts tab, if I select tab 2 then I click on the hide button, then show button it will activate the first tab but with the second chart selected not the first one.
here is a [plunker ](http://plnkr.co/edit/VgfJsJpSPogkXyo5QJY9?p=preview)for the example that I'm trying

**Comment by wesleycho** [comment]
You need to use ng-if, not ng-hide. ng-hide won't remove the tab component, which will cause its state to still be tracked - see [here](http://plnkr.co/edit/KiO7ItjotuVKyLrF15RY?p=preview) for the fix.
