### ISSUE TITLE
Modify positionElement to account for height/width

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#5918]
`$uibPosition.positionElement` needs a refactor to account for height/width of an element through insertion in the DOM, which affects proper positioning. There are $timeout/$$postDigest hacks present to attempt to position properly, but some edge bugs appear due to this.

**Comment by doug-wood** [comment]
so where is the fix for this ?

**Comment by wesleycho** [comment]
Closing this, as after doing an analysis, the original intent of this issue is satisfied by #5983.
