### ISSUE TITLE
(Request): expose itemsPerPage inside uibPaging

### ISSUE THREAD

**Issue by paulflo150** [angular-ui/bootstrap#5921]
Hello,
would it be possible to add itemsPerPage to the scope, so that it can be used inside a pager template?

My use case is I need to be able to display the pager as follows: "Previous 30 of 100 Next"

Thanks!

**Comment by wesleycho** [comment]
It is already available on the controller - wouldn't that be enough, since the pager component is using controllerAs?

**Comment by wesleycho** [comment]
Looks like this is already possible - see [here](http://plnkr.co/edit/V3ucCAD0zeL0GiuD8kfv?p=preview)

**Comment by paulflo150** [comment]
Sorry I missed your previous comment. You are absolutely correct, it is already supported. Thanks!
