### ISSUE TITLE
Active property of tabs not working in 1.2.x and 1.3.x

### ISSUE THREAD

**Issue by pjlasl** [angular-ui/bootstrap#5923]
### Bug description:
We are looking to upgrade from 0.14.3 to 1.3.3 and found that using 

setting the .active = true of a tab in a controller is not working (nothing happens). We reverted back to 0.14.3 and the functionality returned.

Html code
`<uib-tabset class="hidden-print"  style="padding: 10px;" type="pills">                    
                    <uib-tab heading={{::stage[0].heading}} style="text-align: center;" ng-click="getQuotes(0,true)" active="stage[0].active" disable="stage[0].disabled"></uib-tab>
                    <uib-tab heading={{::stage[2].heading}} style="text-align: center;" ng-click="getQuotes(2,true)" active="stage[2].active" disable="stage[2].disabled"></uib-tab>                      
                </uib-tabset>`

in our controller we have a $scope variable stage where things are set/get. 

In a function we have the following call:
`$scope.stage[stageId].active = true;`

Here are all the version I tested where the expected behaviour is occuring:
0.14.3, 1.1.0, 1.1.1, 1.1.2

All version from 1.2.x and 1.3.x are not working properly

### Version of Angular and Bootstrap
Angular:
1.5.5
Bootstrap:
3.3.6

**Comment by RobJacobs** [comment]
See the breaking change section for the 1.2.0 release [here](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md)  The active tab is now managed on the tabSet directive by index attributes on the tab elements.  In the future, please search closed issues: #5774

**Comment by pjlasl** [comment]
I appreciate this. I looked, but apparently not thoroughly enough.

**Comment by icfantv** [comment]
@pjlasl yea, you need to read through the CHANGELOG between EVERY version from the one you're at to the one to which you want to move.
