### ISSUE TITLE
How to know whether the tooltip handler is already attached to an element or not

### ISSUE THREAD

**Issue by smnth90** [angular-ui/bootstrap#5928]
Before attaching a tooltip to an element, I would like to check whether tooltip is attached to the element or not. So can any one help me in finding the way to know whether the element is already attached with the tooltip handler.

Angular: Latest

Bootstrap: Latest

**Comment by icfantv** [comment]
@smnth90 please be respectful of our time and our processes by reading and adhering to the issue template.  The issues forum is not for support requests.  Please navigate to the link specified in the template you deleted to find out the proper way to receive help.  Thanks.
