### ISSUE TITLE
uib-tooltip-html doesn't reflect changes after an update of his content

### ISSUE THREAD

**Issue by Nalia** [angular-ui/bootstrap#5931]
### Bug description:

When the content expression of uib-tooltip-html is updated, the tooltip content isn't updated.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/szMs2KBy7fbwrGykDJU5?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.3

Bootstrap: 3.0.3

**Comment by icfantv** [comment]
@Nalia for performance reasons it does not make sense to watch and recompile the template every time it changes.  If you want dynamic behavior, the correct solution is to use the `uib-tooltip-template` option.

Add the following to your plunker and it will work:
```
<script type="text/ng-template" id="tpl.html">
  <div>
    Content of the template: {{ tooltipContent }}.
  </div>
</script>
```
and
```
<button class="btn btn-default"
        uib-tooltip-template="'tpl.html'"
        tooltip-placement="auto"
        tooltip-append-to-body="true">Tooltip-Template</button>
```

Closing as a support issue.

**Comment by gnehapk** [comment]
@icfantv I am also facing the same issue. Is the fixed available now?

Using - 
"angular": "1.5.8",
"angular-ui-bootstrap": "2.2.0",
 "bootstrap": "3.3.7",
