### ISSUE TITLE
Popover open and close callbacks

### ISSUE THREAD

**Issue by MikiSoft** [angular-ui/bootstrap#5939]
Title says it all. I need the feature where I would specify that particular functions in a controller need to be called/triggered once a desired popover is opened, or closed. So, attributes like `popover-on-open` and `popover-on-close` would be useful.

**Comment by MikiSoft** [comment]
Solution: http://stackoverflow.com/a/33609420/6062096

**Comment by jamespsterling** [comment]
Would love to see this built into the lib
