### ISSUE TITLE
Render html for each tab when tab is active

### ISSUE THREAD

**Issue by Alirz** [angular-ui/bootstrap#5940]
Hi,
How can I render html in tab when it was activating by user ? 
Is there a attribute or should I render it by my self?

Angular: 1.5.5

UIBS: 0.10.0

Bootstrap: 3.1.0

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
