### ISSUE TITLE
Results won't filter with typeahead-editable set to false.

### ISSUE THREAD

**Issue by dudeletslive** [angular-ui/bootstrap#5947]
### Bug description

Have an input, trying to filter the results and restrict the values. Filtering works fine, restricting values works fine, but when I try to combine these, the filtering stops working. No console errors.

### Link to minimally-working plunker that reproduces the issue

Can provide if necessary, but otherwise don't really have the time, as I've already spent too much trying to debug this.

### Version of Angular, UIBS, and Bootstrap

Angular: ~1.5.0

UIBS: ^1.3.2

Bootstrap: N/A

### Relevant Code

The HTML (Jade / Pug) of my element is as follows, 

```
input.pull-left(type="search",
        placeholder="Filter projects by researcher..."
        ng-model="$fltr.filterValue",
        uib-typeahead="key as key.name for key in users | filter: $fltr.filterValue | limitTo: 8",
        typeahead-editable="false",
        ng-disabled="!$fltr.filterKey",
        ng-show="$fltr.filterKey === 'researcher'")
```

Changing $fltr.filterValue to $viewValue re-enables filtering, but disables the typeahead-editable option.

**Comment by wesleycho** [comment]
This is not helpful, as the details given are not sufficient without wasting exorbitant time - please post a reproduction.

**Comment by icfantv** [comment]
Closing due to lack of response.
