### ISSUE TITLE
rating not working correctly with collection-repeat

### ISSUE THREAD

**Issue by vitaly87** [angular-ui/bootstrap#5951]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
when doing collection-repeat with ionic the rating component not working when you have rating more than 2.
### Version of Angular, UIBS, and Bootstrap

Angular:1.5 +ionic

UIBS:

Bootstrap:
1.3.3

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
