### ISSUE TITLE
ng-repeat don't work on mobile phone

### ISSUE THREAD

**Issue by TotooriaHyperion** [angular-ui/bootstrap#5952]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:1.5.6

UIBS:

Bootstrap:3.3.6

Device:Redmi Note 3 / Sony Xperia Z2 tablet(with mobile Chrome browser)

It's about a Carousel
the button of prev and next loaded successfully,
but the carousel-indicators and carousel-inners didn't.
their innerHTMLs are vacant.

Same code works fine on Chrome and Chrome's mobile phone simulator of iPhone6s plus,ipad etc.
And it's also don't work on mobile Chrome of Sony Xperia Z2 tablet.

These are ui-view's innerHTML on mobile phone.

`		<div class="slider-wrap ng-scope" ng-controller="CarouselDemoCtrl"
			  ng-class="change==1?&#39;bg0&#39;:&#39;bg1&#39;;">
			<div class="slider">
				<div ng-mouseenter="pause()" ng-mouseleave="play()" class="carousel" ng-swipe-right="prev()"
					  ng-swipe-left="next()" active="active" interval="myInterval" no-wrap="noWrapSlides">
					<div class="carousel-inner" ng-transclude=""></div>
					<a role="button" href="" class="left carousel-control" ng-click="prev()"
						ng-class="{ disabled: isPrevDisabled() }" ng-show="slides.length &gt; 1">
						<span aria-hidden="true" class="glyphicon glyphicon-chevron-left"></span>
						<span class="sr-only">previous</span>
					</a>
					<a role="button" href="" class="right carousel-control" ng-click="next()"
						ng-class="{ disabled: isNextDisabled() }" ng-show="slides.length &gt; 1">
						<span aria-hidden="true" class="glyphicon glyphicon-chevron-right"></span>
						<span class="sr-only">next</span>
					</a>
					<ol class="carousel-indicators" ng-show="slides.length &gt; 1">
						
					</ol>
				</div>
			</div>
		</div>`

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by icfantv** [comment]
@TotooriaHyperion, please be respectful of our time and our processes by adhering to the issue template.  We are all volunteers on this project and simply do not have the time to chase down and/or investigate incorrectly entered issues - it is there to allow us to help you, the community, faster.

I'm going to close this until you are able to comply and then will be happy to reopen.  Thanks.
