### ISSUE TITLE
Modal tabs into background when last tabbable's tabindex="-1"

### ISSUE THREAD

**Issue by antman888** [angular-ui/bootstrap#5955]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by antman888** [comment]
A possible solution is to filter elements with a tabindex="-1" attribute.

```
var tabbableSelector = 'a[href], area[href], input:not([disabled]):not([tabindex=\'-1\']), ' +
        'button:not([disabled]):not([tabindex=\'-1\']),select:not([disabled]):not([tabindex=\'-1\']), textarea:not([disabled]):not([tabindex=\'-1\']), ' +
        'iframe, object, embed, *[tabindex]:not([tabindex=\'-1\']), *[contenteditable=true]';
```

**Comment by wesleycho** [comment]
Sounds legitimate - feel free to file a PR
