### ISSUE TITLE
$promise with typeahead  - Duplicated on second try and error raised

### ISSUE THREAD

**Issue by lchabert** [angular-ui/bootstrap#5956]
Hello,

I have some trouble with your lib when i use a typeahead and async server side loading.
Server return a list of object (please see format below), with an id and a prefix.

```json
[
    {
        "id": 7057,
        "lcr_id": 1,
        "prefix": "+1201",
        "from_uri": "",
        "request_uri": "",
        "stopper": true,
        "enabled": false,
        "description": "Etats Unis - Fixes",
        "creation_date": "2016-05-31T10:18:43.882009Z",
        "update_date": "2016-05-31T15:23:11.082442Z",
        "group": 11
    },
    {
        "id": 7428,
        "lcr_id": 1,
        "prefix": "+1201555",
        "from_uri": "",
        "request_uri": "",
        "stopper": true,
        "enabled": true,
        "description": "Etats Unis - Services spéciaux",
        "creation_date": "2016-05-31T10:18:43.989139Z",
        "update_date": "2016-05-31T15:23:11.084030Z",
        "group": 11
    },
```

I have a resource to get my data, and return $promise to typeahead. No problem with this.
```javascript
$scope.getPrefixes = function(val) {
    return Prefix.query({'search':val, 'offset':0, 'limit':8}).$promise;
};
```

When i insert my first char in input form, no problem, items are rendered. If i add another char in input form, an error has been raised.
```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed.
```

Any reasons, when i insert only one char, no error, and on the next char, errors have been raised ? Why this error ?
If i enter more and more char, search will be more precise, so more restricted results. There is a high probability of same object will be returned by server on the next request, but why internal items aren't cleared by typeahead?

Thanks.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.5

UIBS: 1.3.3

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@lchabert, please be respectful of our time and our processes by reading the issue template before entering anything.  This is a support request and per the issue template the issues forum is not the place for these.
