### ISSUE TITLE
Setting hour and minutes empty creates inconsistencies in the value

### ISSUE THREAD

**Issue by Sudhirmiglani** [angular-ui/bootstrap#5960]
### Bug description:
Make hour and minutes editable. clear both the values, enter hours and then enter minutes.
Hours reset to previous saved model value.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/zuZZ1en2Ls6Wx3vvVDPK?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:1.4.8

UIBS:0.14.3

Bootstrap:3.3.6

**Comment by icfantv** [comment]
@Sudhirmiglani, we do not issue patches for previous releases.  Can you please test this using the latest versions of both angular and our library and see if the issue is still present?  Thanks.

**Comment by Sudhirmiglani** [comment]
Working for latest version @icfantv . Thanks man !

**Comment by icfantv** [comment]
Cool!  Glad to hear it.  If you're upgrading, please be sure to read the changelog for each version from your current to the latest paying special attention to the breaking changes sections for each release.

**Comment by Sudhirmiglani** [comment]
Sure. Thanks for your help
