### ISSUE TITLE
'Today' button in uib-datepicker-popup show be disabled, if min-date > current date, provided in datepicker-options="{minDate: nextday}"

### ISSUE THREAD

**Issue by dimylik** [angular-ui/bootstrap#5961]
Hi,

don't know if that issue is not fixed in latest release

'Today' button in uib-datepicker-popup show be disabled, if min-date > current date, provided in datepicker-options="{minDate: some_day_in_the_future}"

**Comment by icfantv** [comment]
@dimylk, please be respectful or our time and processes by adhering to the issue template.  It is there to allow us to quickly assess the issue and determine the right path forward.  We are all volunteers and simply do not have the time to chase issues that do not conform.  I am going to close this until you correct it and am happy to reopen at that time.  Thanks.
