### ISSUE TITLE
The performance of datepicker seems poor

### ISSUE THREAD

**Issue by e-cloud** [angular-ui/bootstrap#5964]
plunkr: http://embed.plnkr.co/zeQzQgF1UKb2G66yoSRI/
Angular: 1.5.5
UIBS: 1.3.3

In my usage, i combine the datepicker and the timepicker. When i just upgrade to UIBS 1.3 form UIBS 0.13, i just find that as i change the timepicker, the corresponding changes of datepicker are slow. 

Then i make a test. It turns out whenever i change the ng-model of datepicker, it will reconstruct the whole datepicker which can be concluded from **43** `$destroy` event.(see the console of the plukr if you change the date)

**Comment by icfantv** [comment]
@e-cloud, we actually strongly recommend NOT using the same model object for both the datepicker and timepicker.

I'm closing this as something that is not going to be very high on our priority list.

**Comment by e-cloud** [comment]
In fact, the combination is not the point. It's all about datepicker's performance.
And there is no combination in the demo plunkr.

**Comment by RobJacobs** [comment]
@e-cloud When changing the date bound to the ng-model, the day calendar needs to be rebuilt to correctly reflect the 'selected' date as it may be in a different month/year.  So what would you suggest?

**Comment by e-cloud** [comment]
such as keep the child scopes undestroyed, just update their value or so?
That's what it does in the old version.

But for maintainability, the profit may be minor.

**Comment by RobJacobs** [comment]
The day calendar is built with nested ng-repeats:

https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/day.html#L14
https://github.com/angular-ui/bootstrap/blob/master/template/datepicker/day.html#L16

Which I assume is destroying the day button scopes when the rows collection changes.
