### ISSUE TITLE
Dropdown keyboard-nav doesn't work with dropdown-append-to-body

### ISSUE THREAD

**Issue by cantacell** [angular-ui/bootstrap#5965]
Keyboard navigation, with dropdown-append-to-body,  works only for first element of the list.
http://plnkr.co/edit/sU8airzOxy9mhUg7l8Rk?p=preview

Version: 1.3.3
Angular: 1.5.3
Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
I forgot to put this issue down in the commit, but this is addressed by 6038403
