### ISSUE TITLE
Alert type "warning" not displaying the alert

### ISSUE THREAD

**Issue by SandeepThomas** [angular-ui/bootstrap#5966]
Setting alert type to warning is not showing the alert at all. 

The error is present in the plunker shown in the main page.

http://plnkr.co/edit/TIVrKSg9swQ14u2oYTl4?p=preview

Just changed the type to warning and the alert disappears!

**Comment by icfantv** [comment]
@SandeepThomas, the middle alert is of type `warning` which can easily be seen by the yellow nature of the alert and also by the JSON data in the javascript file indicating that the type is `warning`.

I'm going to close this until you can show that this is an issue with the library.
