### ISSUE TITLE
Parse error when using variables in typeahead-editable

### ISSUE THREAD

**Issue by Fossil01** [angular-ui/bootstrap#5970]
### Bug description:

My Angular tags are <% and %>. Which works fine everywhere.

Whenever I do the following:

```html 
<input ng-model="flight.number" name="number" type="text"  uib-typeahead="flight for flight in
flightnumbers | filter:$viewValue | limitTo:16" typeahead-editable="<% isTypeaheadEditable %>"
typeahead-select-on-blur="true" typeahead-select-on-exact="true"
typeahead-on-select="onSelect($item, $model, $label)" placeholder="KL0000"
class="form-control input-md" ng-minlength="4" ng-required="true">
```

I get this error message in the console:
https://docs.angularjs.org/error/$parse/syntax?p0=%3C&p1=not%20a%20primary%20expression&p2=1&p3=%3C%25%20isTypeaheadEditable%20%25%3E&p4=%3C%25%20isTypeaheadEditable%20%25%3E

Whenever I use the typeahead-editable="<% isTypeaheadEditable %>"  on any other HTML element it works fine. I can echo the value true or false using just <% isTypeaheadEditable %> in a <span> element for example.

The code in the controller which does true/false:

```js
	$scope.isTypeaheadEditable = false;
  	$scope.activeButton = function() {
    	$scope.isTypeaheadEditable = !$scope.isTypeaheadEditable;
  } 
```

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.7 (Also tried latest)
UIBS: 0.4.12 (Also tried latest)
Bootstrap: 3.3.4

**Comment by pkozlowski-opensource** [comment]
According to docs (http://angular-ui.github.io/bootstrap/#/typeahead) `typeahead-editable` takes an expression and not interpolation. So you shouldn't be doing `typeahead-editable="<% isTypeaheadEditable %>"` but `typeahead-editable="isTypeaheadEditable"` instead.

**Comment by Fossil01** [comment]
@pkozlowski-opensource Tried that too, does not change anything. When viewing the DOM with Chrome Inspector I cannot see the typeahead-editable attribute change. It just shows:

```<input ng-model="flight.number" name="number" type="text" uib-typeahead="flight for flight in flightnumbers | filter:$viewValue | limitTo:16" typeahead-editable="isTypeaheadEditable" typeahead-select-on-blur="true" typeahead-select-on-exact="true" typeahead-on-select="onSelect($item, $model, $label)" placeholder="KL0000" class="form-control input-md ng-pristine ng-valid-editable ng-invalid ng-invalid-required ng-valid-minlength ng-touched" ng-minlength="4" ng-required="true" aria-autocomplete="list" aria-expanded="false" aria-owns="typeahead-32-5466" required="required">

**Comment by pkozlowski-opensource** [comment]
> Tried that too, does not change anything

Then you need to provide more context - most importantly a live reproduce scenario with plunker (which btw we are asking for in a template for GH issues:  https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by Fossil01** [comment]
@pkozlowski-opensource 

Here you go: http://plnkr.co/edit/XHZRtJLfYNoZ4tJ2Og1z?p=preview

**Comment by pkozlowski-opensource** [comment]
Seems to "work" for me (not getting errors at least) when doing [suggested changes](https://github.com/angular-ui/bootstrap/issues/5970#issuecomment-224264992): http://plnkr.co/edit/wXkDktl1ywsU4WON6F9c?p=preview

Could you please update your plunker to the latest version of this library and clearly describe what is the problem? Once again, I'm not getting parse errors after doing what I've been suggesting.

**Comment by Fossil01** [comment]
@pkozlowski-opensource Check the source when clicking the toggle button. The Editable? false changes to true but the typeahead-editable= does not change to true or false.

**Comment by pkozlowski-opensource** [comment]
> but the typeahead-editable= does not change to true or fals

Huh? It never will! You shouldn't be checking HTML it will be always `typeahead-editable="isTypeaheadEditable"`. What matters is model, not attributes. Those attributes are meant to provide expressions to the Angular machinery. They will _not_ reflect values of expressions.

This starts to sound more and more like a support question so I'm going to close this one for now.

**Comment by Fossil01** [comment]
It's not a support question. Try the plnkr again.

Type in KL and select a flightnumber. There's no warning about an invalid flight.
Now type in: KL8129     This number is not in the JSON file so it shouldnt be allowed. There is now a warning.

Whenever you click the Toggle button it should allow manual input. But if you then enter KL8129 the error is still there. If I manually set typeahead-editable="true" then this error is not shown.

**Comment by wesleycho** [comment]
This looks fixed for the latest released version of UI Bootstrap [here](http://plnkr.co/edit/R3JEMZAhvIN1ge5Ce7PG?p=preview).

**Comment by Fossil01** [comment]
Yes, looks like it. Thanks :-)

I already tried that version before but apparently I was doing something wrong...
