### ISSUE TITLE
Animation doesn't work in first time opening modal which use templateUrl

### ISSUE THREAD

**Issue by moshfeu** [angular-ui/bootstrap#5973]
### Bug description: 

First time I open a modal using `$uibModal.open` with external file template (using `templateUrl` the `animtion` is not working and the popup just showup. From the second time and after the animation works. My guess it's becuase the ajax call for the template.

**The code I'm using to show the modal:**

    $uibModal.open({
      animation: true,
      templateUrl: '/kucibo',
      controller: ['$scope', '$uibModalInstance', function ($scope, $uibModalInstance) {
        
      }]
    });

### Link to minimally-working plunker that reproduces the issue:

http://output.jsbin.com/winatav

http://jsbin.com/winatav/edit?html,js

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.9

UIBS: 1.3.3

Bootstrap: Integrative with UIBS

Thanks!

**Comment by wesleycho** [comment]
It is strongly recommended that you bundle your template in $templateCache, even if using `templateUrl` - this is a result of how Angular works. Otherwise you come across this issue, for which there is no way for the library to adequately work around.
