### ISSUE TITLE
datepicker-options maxDate & minDate don't support timezone.

### ISSUE THREAD

**Issue by vkozubal** [angular-ui/bootstrap#5974]
### Bug description:
The datepicker-options maxDate and MinDate doesn't reflect the timezone offset. 

On the provided example both maxDate is set to new Date() plus one hour. Expected result that I can select current date.
Model value was set to new Date(). The timezone specified - '+14:00'

Please select the day before and then try to select current day again. You can't select current day again because it is disabled.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/6m2N2Lzf9Vw5rHHCsjwp?p=preview

### Version of Angular, UIBS, and Bootstrap
latest bootstrap version 1.3.3
Angular:
1.5.3

**Comment by wesleycho** [comment]
This looks legit, but it also looks like the root issue at play here is fixed in `master` with a breaking change to come in 2.0 to fix the timezone issue - see [here](http://plnkr.co/edit/71MeD4yENGZAkiREAO80?p=preview) for fix in action.

Closing as fixed, to be released when we release 2.0 :)
