### ISSUE TITLE
Tooltip not evaluating date expression

### ISSUE THREAD

**Issue by shyamal890** [angular-ui/bootstrap#5975]
`uib-tooltip="{{ctrl.date | date:"d MMM, h:mm:ss a"}}"`

The above is rendered as `{{ctrl.date | date:"d MMM, h:mm:ss a"}}` and not evaluated.

**Comment by pkozlowski-opensource** [comment]
According to http://angular-ui.github.io/bootstrap/#/tooltip the `uib-tooltip` attribute takes _text_ and not an expression. If you need an expression use `uib-tooltip-html`.

Please ask support questions on a dedicated support channel: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
