### ISSUE TITLE
ui tabs ngMessage doesn't work in the first tab

### ISSUE THREAD

**Issue by whisher** [angular-ui/bootstrap#5976]
Hi,
sorry to bother you but I dont
know which way to turn.
ngMessage validation doesn't work on the
the first tab (it work fine in all the others)
Can you help me ?
Thanks in advance.

http://codepen.io/whisher/pen/QEyyzz

**Comment by wesleycho** [comment]
It works just fine - see [here](http://plnkr.co/edit/ifjqGmBHX7wKb3sszSv6?p=preview).

In the future, please do not open issues like this on GitHub - the issues are meant for legitimate issues and/or well-thought feature requests, not for support tickets.
