### ISSUE TITLE
Add functionality : tooltip-popup-duration

### ISSUE THREAD

**Issue by ShakurOo** [angular-ui/bootstrap#5980]
That might be very usefull to add another functionality which allow users to control the duration of popup's visibility.

The user setting a time (in millisecondes) in a html attribute and then, from the core of the ui-bootstrap library :

1. Listen when the popup is opened
2. Start the countdown through the `tooltip-popup-duration`.
3. When the countdown is over, close automaticly the popin

Why this feature ? The default trigger is "hover" event. In some case, specialy when the directive is attached on text fields or any other elements which can be "focused", the mouse cursor stay above that fields because the user "click" on it for writing something. And the popup stay visible too. This is strange behavior... 

I know its possible to declare our own events and create a custom directive. But I think this make more complexe the angular app for an little functionnality which can be implemanting easily.

**Comment by pkozlowski-opensource** [comment]
You can easily do this in the user-land by setting `tooltip-trigger="none"` and opening / closing tooltips "manually" using `tooltip-is-open`. I'm not sure it is common enough to pay for additional bytes in the core (not to mention that crazy corner cases it creates).

-1 from me for now to ready to be convinced

**Comment by ShakurOo** [comment]
Hum, but by that way, I have to create a directive which listen when the tooltip popup opens, for changer `tooltip-trigger="none"` to false. It is right ? 

I'm sûre in a lot of case, this little functionality could be use. :/

**Comment by wesleycho** [comment]
This can easily be done within one's popup/tooltip template by adding a timeout in the component that uses the tooltip/popover - I don't see any value add in the library itself with this, and it isn't a feature I see being widely used.

**Comment by icfantv** [comment]
Agreed with @wesleycho and @pkozlowski-opensource here.  This can easily be handled on the user's end.

**Comment by wesleycho** [comment]
Closing this as won't support, should be easy to create a wrapper if one desires such a functionality.
