### ISSUE TITLE
uib-datepicker-popup  => ng-model does not work initially

### ISSUE THREAD

**Issue by squarewave24** [angular-ui/bootstrap#5981]
### Bug description:
after upgrading to later version of ui-bootstrap 1.3.2 and 1.3.3, the initial model value does not get loaded. 

{{ctrl.startDate}}
<input type="text" uib-datepicker-popup="d-MMM-yyyy" ng-model="ctrl.startDate" show-weeks="false">

no errors, the first line with one way binding does show correct date. 

any ideas on how to troubleshoot this would be great! 

### Version of Angular, UIBS, and Bootstrap
angular: 1.4.8
ui-bootstrap tested with 1.3.2 and 1.3.3

**Comment by wesleycho** [comment]
Please post a Plunker reproduction.

**Comment by squarewave24** [comment]
it's actually part of a big .net+Angular application so this would be tricky to extract. I am sure that if i just create a new example from scratch in plunkr it will work. I was hoping maybe you could share some ideas on how to troubleshoot this? I could post a resolution once I figure it out.

**Comment by wesleycho** [comment]
The issue queue is not for technical support. This is for verified library issues. One can ask in venues such IRC or Slack, but this isn't the place for them as it costs time reading, digesting, then responding to issues that aren't issues with the library itself.

Closing as a support issue.

**Comment by squarewave24** [comment]
understood, but this worked before upgrading, so just because there is no plunkr doesn't mean there is no issue with the library.

**Comment by wesleycho** [comment]
While that may be true, we don't have the resources to chase after vague issues - many times they turned out to be pure user error, and this project is community run while all members are working full time jobs.

**Comment by squarewave24** [comment]
Understand, thanks for quick response! 

I'll try reproducing it
