### ISSUE TITLE
Add `dblclick` trigger for $uibTooltipe

### ISSUE THREAD

**Issue by fedyk** [angular-ui/bootstrap#6000]
### Feature description:

We have a list of triggest for tooltip `mouseenter`, `click`, `outsideClick`, `focus`, `none`. If you need to add `dblclick` trigger you have to use `none` and write some wrapper which mostly already written in tooltip service, but you cannot reuse it because is hidden in service scope. With the current implementation of `$uibTooltip` service, it can be easily added.
Is it makes sense to have such trigger like `dblclick` build in uiBootstrap?

**Comment by icfantv** [comment]
I would argue that triggering a tooltip or popover via a double click is poor UX because it is a very _uncommon_ user action for a double click.  Think about what one uses the double click for:  opening folders, files is the only thing that comes to mind...

**Comment by wesleycho** [comment]
I agree, this sounds like poor UX - if one really wants this, one can implement the triggers locally.

Given that there is an adequate & simple workaround, going to close this as something we don't want to add additional code for in the library itself.
