### ISSUE TITLE
switch tabs using url param or controller

### ISSUE THREAD

**Issue by imiten** [angular-ui/bootstrap#6001]
Hi,

It seems tab switching is not working very well based on my sample plunk you can see what I mean.  

https://plnkr.co/edit/Bw3gQG9QZubW89U7gvfO?p=preview

not sure how to jump to tab like if I have page with tabs and I want to load page and also switch to second tab (using url preferrably) or using back button from some page go to previous page with tab. example on the plunk I have dummy data. you see first page has two tabs. go to second tab backup list and choose edit. Now use broswer back button or Back button. Desired would be to take to backup list tab of previous page but does not. I have tried even using url params and also using function like doBack.

**Comment by icfantv** [comment]
@imiten, per the issue template you deleted, the issues forum is not for support requests.  How-to questions are best served by and for the community as documented in the link provided in the issue template.
