### ISSUE TITLE
uibDropdownConfig should be a .value() instead of a .constant() to allow decorating

### ISSUE THREAD

**Issue by onlywei** [angular-ui/bootstrap#6004]
I think it's pretty useful to allow people to customize this object via `angular.module().decorator()`, because maybe they want to use their own CSS classes. It should be an easy change, as I don't see `uibDropdownConfig` being injected anywhere other than a controller.

**Comment by wesleycho** [comment]
One can use `$provide.value` to override it, but I'm actually not sure why they are `.constant`s.

PRs welcome!
