### ISSUE TITLE
Accordian Group Inside Custom Directive Bug: Two-way binding not working

### ISSUE THREAD

**Issue by Nick-t-go** [angular-ui/bootstrap#6021]
Small Bug description: I have an accordion group wrapped in a directive, inside the accordion is an input element with a reset button. Reset button has function to clear input box. However, it doesn't work. $scope is unresponsive.

Extra description: In my project(not found in minimal-working plunker example), I have several elements that seem to not be working as the two-way binding seems to be unresponsive at times.

Link to minimally-working plunker that reproduces the issue:  http://plnkr.co/edit/ZN0NUoJB7cqVkuzaL3ZS?p=preview

Angular:
     angular.js 1.5.3
Angular Animate:
    angular-animate 1.5.3   
UIBS:
   ui-bootstrap-tpls-1.3.3
Bootstrap:
  bootstrap 3.3.6

Question: Is it wrong to wrap the ui-accordian-group element in another directive? Since I have so many that I am using it makes it much neater for me. I also noticed though that this is causing weird issues with trying to dynamically style the elements based on being child elements or even using type of selectors.

**Comment by wesleycho** [comment]
In general when dealing with tightly coupled directives like the accordion and accordion group, one should not split them up - it decreases readability, but also cause major problems when combined with how directives work with Angular.

This is considered a user error - one should either only use directives inside the accordion group, or outside the whole accordion.

**Comment by Nick-t-go** [comment]
> This is considered a user error - one should either only use directives inside the accordion group, or outside the whole accordion.

Excellent this is the info I needed which my findings obviously supported just wanted to check that this was the case. @wesleycho Perhaps adding this to the "Known Issues" section of the Accordion directive would help other AngularUI noobs like myself avoid this mistake.

Regardless thanks for the clarification and help.
