### ISSUE TITLE
uibModalTransclude is not animatable

### ISSUE THREAD

**Issue by cleavera** [angular-ui/bootstrap#6023]
### Description:
Within the modal, the uibModalTransclusion directive does not trigger ng-enter and ng-enter-active classes when the modal is appended. This is because in the transclusion function it calls
```js
element.append(clone);
```
If this is replaced with
```js
$animate.enter(clone, element);
```
Then it will trigger the animation cycle and allow them to be hooked into.

### Version of Angular, UIBS, and Bootstrap

Angular: Any

UIBS: 1.3.3

Bootstrap: Any

**Comment by wesleycho** [comment]
Up for filing a PR?
