### ISSUE TITLE
append-to-elementid

### ISSUE THREAD

**Issue by dasaanudeep** [angular-ui/bootstrap#6028]
Hi All,

I tried typeahead-append-to="appendToElement" using below way but it doesn't seem to work.
$scope.appendToElement = window.document.querySelector('elementid');

`<input` uib-typeahead="val for val in vals" typeahead-append-to="appendToElement" />

**Comment by icfantv** [comment]
@dasaanudeep, please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.
