### ISSUE TITLE
Modal opens in IE11 with animation and disappears immediately when used with bounceInDown class as the windowClass

### ISSUE THREAD

**Issue by shihamsam** [angular-ui/bootstrap#6031]
I am using AngularJS 1.5.3 with Anjular UI Modal and animate.css for displaying animated modal windows.
When I use the 'animated bounceInDown' css classes in IE 11, the modal disappears after rendering. Check out the plunk for the issue in IE11. It looks like the issue is when the css animation has transform: translateY/  transform: translateX

This works fine in FF and Chrome

http://plnkr.co/edit/rOBpErIanq2i7h7noGZe?p=preview

Angular:1.5.3

UIBS:1.3.3

Bootstrap:3.3.6

**Comment by icfantv** [comment]
@shihamsam our library was written against Bootstrap CSS and while it should be extensible in most regards, we haven't tested it against third-party CSS libraries like the animation one you've linked.  As such, I don't really feel it's our responsibility to debug this for you, but please feel free to convince me otherwise.

We're all volunteers here and simply do not have the time to investigate things like this.

**Comment by shihamsam** [comment]
@icfantv Really appreciate the response. It is not the issue in the animation library as such the animation works fine in IE11 when applied to the modal markup itself(Without using the angular-ui). But the issue exists only when the animation class is attached through windowClass OR windowTopClass properties of the modal component. Something within the Modal code causes it to disappear the modal after the animation. That is the reason for reporting this bug here. I did enough search with no possible answers in SO. My feel is the fix need to be done somewhere inside the Modal code. Again this works fine in FF and Chrome.

**Comment by icfantv** [comment]
@shihamsam, we appreciate the research you've done thus far, but I'm afraid we simply do not have the bandwidth or resources to investigate this further.

**Comment by icfantv** [comment]
Closing as the issue appears to only happen when a third-party CSS library is used.
