### ISSUE TITLE
UI Bootstrap progress bar type is not working with Anglular UI grid cell template

### ISSUE THREAD

**Issue by dotnetjalps** [angular-ui/bootstrap#6034]
### Bug description:

When I use the ui.bootstrap.progressbar directive as cell template for angular ui grid(version 3.1.1) like following.

` {
                 name: "Study Staus",
                 cellTemplate: "<uib-progressbar value=\"row.entity.Percentage\" type=\"row.entity.BarType\"></uib-progressbar>",
                 enableSorting: false
 }`

Here the percentage and type both are coming from the server side. The percentage is working fine but the type is not working properly. It renders following div

`<div class="progress ng-isolate-scope" value="row.entity.Percentage" type="row.entity.BarType">
  <div class="progress-bar progress-bar-row.entity.BarType" ng-class="type &amp;&amp; 'progress-bar-' + type" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" ng-style="{width: (percent < 100 ? percent : 100) + '%'}" aria-valuetext="100%" aria-labelledby="progressbar" ng-transclude="" style="width: 100%;"></div>
</div>`

The percentage works fine but row.enityt.BarType is not working. I have double check that BarType value is coming.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5

UIBS:1.3.3

Bootstrap:3.0

**Comment by icfantv** [comment]
@dotnetjalps, please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.

**Comment by dotnetjalps** [comment]
Okay I will provide plunkr

**Comment by dotnetjalps** [comment]
Sorry for being late: Here is the plunkr for that - 
http://plnkr.co/edit/j3naoAEcAuiNlNTBPJip?p=info

**Comment by dotnetjalps** [comment]
@icfantv - Can you please reopen this issue.
