### ISSUE TITLE
UI Bootstrap Site - Modal scrollbar removal feature impact/side effects on navbar

### ISSUE THREAD

**Issue by nazrhyn** [angular-ui/bootstrap#6035]
### Bug description:
From the searching I've done, this is apparently ["the issue that never dies"](https://github.com/angular-ui/bootstrap/issues/5789#issuecomment-208963720). I did read your guidelines, but I'm not providing you with a plunkr, as it's happening on your site (watch the navbar title text):

![bootstrap-modal-shift](https://cloud.githubusercontent.com/assets/1672405/16197413/ff4983cc-36cf-11e6-8398-d16b43b31f3a.gif)

From what it looks like, the container gets the padding added, but the scrollbar is also affecting the navbar's contents, which does not receive padding modifications, so the contents of the navbar shift to the right.

I'm investigating a similar issue in our code that is also related to the scrollbar padding system; in our case, I am pretty sure it's related to how we arrange our containers, but if I find anything that I can reproduce for you, there, I'll make a plunkr. I thought I'd submit this one first as, if you fix this, it might fix our issue.

I will understand if you close this for not providing code, but I didn't want to manually duplicate the layout of your site to let you know what was going on when I could just point my finger :grinning:.

Thanks for such an awesome library; we love it.

**Comment by icfantv** [comment]
@RobJacobs, i could have sworn this was addressed?  Or is this a different issue?  Thanks.

**Comment by RobJacobs** [comment]
See my comment in #5749

**Comment by icfantv** [comment]
@RobJacobs sweet, thanks!  @nazrhyn, please look at the linked Issue above to see if it helps you with your issue.  I'm going to close this in the interim but will reopen if it can be shown it's a different issue.

**Comment by nazrhyn** [comment]
@icfantv Thanks for the pointer. I assume the main site is just not following this advice yet?

**Comment by icfantv** [comment]
@nazrhyn, ummmmmmmmmmm........that would probably be a safe assumption..... :-(

**Comment by nazrhyn** [comment]
Haha. :innocent:

I figured out the minimal case on my issue with one of our UI developers and opened the real issue, anyway. Hopefully I don't waste your time again!
