### ISSUE TITLE
Datetime picker on modal resolve not working

### ISSUE THREAD

**Issue by lxhelili** [angular-ui/bootstrap#6036]
Check out: http://plnkr.co/edit/f6eZ3HjBqnSarH4LGg5y

**Comment by icfantv** [comment]
@lxhelili, while this appears to be self-explanatory, please adhere to our issue template.  it's there to save us time.  thanks.

**Comment by icfantv** [comment]
@lxhelili, actually, this plunker is using VERY old code.  please recreate with the latest versions of our library, angular, and bootstrap.  Also, I should point out, had you used our template, I wouldn't have had to look at your plunker.

**Comment by icfantv** [comment]
Closing due to lack of response.
