### ISSUE TITLE
auto-close doesn't work without [uib-dropdown-toggle]

### ISSUE THREAD

**Issue by alexey-sh** [angular-ui/bootstrap#6038]
### Bug description:
auto-close doesn't work without [uib-dropdown-toggle]

From documentation:
>uib-dropdown-toggle which allows the dropdown to be toggled via click. **_This directive is optional._**
>`auto-close` (Default: `always`) - Controls the behavior of the menu when clicked.
>`always` - Automatically closes the dropdown when any of its elements is clicked.

Ok so lets remove `uib-dropdown-toggle` attribute and setup opening via `is-open` attribute..

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/T4jsdmfH9hz7wvb8BtHB?p=preview

 1. click on 'Click me for a dropdown, yo!' label
 2. click on outside space

Expected: closed dropdown
Actually: nothing happened

### Version of Angular, UIBS, and Bootstrap

Angular:1.5.3

UIBS:1.3.3

Bootstrap:3.3.6

**Comment by icfantv** [comment]
At first glance, this sounds like an issue.  We'll need to look into further.

**Comment by RobJacobs** [comment]
This is because the click event from the span that set the isOpen value is propagating down to the document click event here:
https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L13
https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L49

Using:

    ng-click="isOpen = !isOpen; $event.stopPropagation();"

will work.

**Comment by icfantv** [comment]
@RobJacobs, cool, thanks.  Closing as resolved.

**Comment by alexey-sh** [comment]
Could you please add this hacky behaviour into documentation?
Thanks

**Comment by icfantv** [comment]
@alexey-sh maybe i'm missing something, so please enlighten me.  does adding `uib-dropdown-toggle` cause something to not work or add additional, unwanted features such that you _can't_ use it?

**Comment by alexey-sh** [comment]
`ng-click="isOpen = !isOpen; $event.stopPropagation();"`
this is not obvious usage because the note about ` $event.stopPropagation()` doesn't exists in documentation. 

![Image of using $event.stopPropagation();]
(http://2.bp.blogspot.com/-UjQJV05vLuo/UAwEONhDulI/AAAAAAAAA0w/Hw7pcMHybYU/s1600/%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE+%D0%BD%D0%B0+%D0%BF%D0%BE%D0%B4%D0%BF%D0%BE%D1%80%D0%BA%D0%B5.jpg)

**Comment by icfantv** [comment]
You haven't answered my question, what happens when you add the missing directive?  What is the unwanted/undesired behavior?

**Comment by alexey-sh** [comment]
I don't know anything about what happens with the missing directive. I just want know is it possible to add  a few notes about `ng-click="isOpen = !isOpen; $event.stopPropagation();"`. If you can't add this please don't ask me a weird questions which are not related with my answer.
Thanks

**Comment by icfantv** [comment]
@alexey-sh, you filed the bug and I'm gathering more information.  If you are going to display an attitude, I should remind you that we are all unpaid volunteers and if you would like your request to be taken seriously, you would be wise to treat us with the same level of respect that we treat you.

I am trying to determine if we still moly need a doc update to indicate that the attribute is not optional or or if requiring it yields undesirable behavior.  As you seem to be intimately familiar with this particular issue, I am deferring to your experience.  But again, if all you are going to do is cop an attitude, it makes it makes it that much harder to decide on the proper fix.

**Comment by chillyistkult** [comment]
@icfantv Adding uib-dropdown-toggle directive inside uib-dropdown-menu breaks auto-close="outsideClick". Also it needs two clicks to close the dropdown for uib-dropdown-toggles inside menu.

**Comment by icfantv** [comment]
@chillyistkult, thanks for this.  trying to refresh my memory here, but it is starting to sound like this is really just a documentation update, then.  @wesleycho or @RobJacobs if you have a second, can you please confirm that this is the correct approach (the doc update)?  Thanks.

**Comment by wesleycho** [comment]
The documentation update we need is to mention that `auto-close` requires `uib-dropdown-toggle` to be used.

**Comment by chillyistkult** [comment]
It's not just a documentation update: As I mentioned if you use `uib-dropdown-toggle` inside `uib-dropdown-menu` it breaks auto-close and on top it is not working as I would expect. This is a very common scenario because for example you may need a close button for your dropdown. Currently the way to go is to use is-open and setting the variable as you need it, but honestly `uib-dropdown-toggle` should work from anywhere inside `uib-dropdown`.

**Comment by GLoganDR** [comment]
I agree with @chillyistkult. It's counter-intuitive to have to use the is-open stuff to close a dropdown from a button inside of the dropdown. uib-dropdown-toggle should work anywhere inside of a dropdown instead of needing to double-click. What's up with that?

**Comment by alexey-sh** [comment]
[it is](https://coub.com/view/9n109)
