### ISSUE TITLE
Clicking open model buttonand and simultaneously pressing enter key is leading to opening of 2 pop ups

### ISSUE THREAD

**Issue by LokeshBoran** [angular-ui/bootstrap#6039]
This issue occurs on http://angular-ui.github.io/bootstrap/versioned-docs/0.12.0/#modal
official site also.
When you click on "Large Modal" or "Small Modal" or "Open me!" by mouse and with that simultaneously  press "Enter" key from keyboard.
It opens two popups.

Please fix it.

Angular: 1.2.26

UIBS: 0.12.1

Bootstrap:3.2.0

**Comment by icfantv** [comment]
@LokeshBoran, please recreate with the latest versions of the libraries.  The versions you mention are two years old, which is several lifetimes in OSS.  We do not issue patches for prior releases.  I'm going to close until this is done and it can be shown this is an issue in the latest version.

**Comment by LokeshBoran** [comment]
@icfantv This issue is also occurs on https://angular-ui.github.io/bootstrap/#/modal this link and also in current version of the library. There is no check for similar instances in the library.

**Comment by RobJacobs** [comment]
I'm not seeing this behavior with a mouse click and enter key.  Regardless, hitting enter (or space) when a button has focus fires a click event.  You will notice, if you get the timing just right, hitting enter and space at the same time reproduces the reported behavior.  I'm not sure we want to bother with this one...

**Comment by icfantv** [comment]
I'm having trouble reproducing this as well.  I'm also inclined to not spend time addressing this as this particular use case.  @wesleycho?

**Comment by LokeshBoran** [comment]
@RobJacobs It still occurs with Mouse Click + Space Bar and Mouse Click + Enter key press.
It Depends on timing, you first mouse click after that just in moment press either Enter or Space Bar. You will get this error.
