### ISSUE TITLE
datepicker cannot validate using the W3C validator (339 validation errors)

### ISSUE THREAD

**Issue by moanrose** [angular-ui/bootstrap#6040]
### Bug description:

The angular-ui datepicker does not validate very well, because no data- prefix is appended to to the ng or uib attributes.  I get a total of 339 validation errors on the datepicker alone, but i suspect that this is a general problem to angular-ui. 

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/RFAxI1kaF1k8TfSSuMgM?p=preview

(Click the validate button)

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.6
UIBS: 1.3.3
Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
Closing as won't support - the W3C validator is not something most frontend developers cares about, it does some meaningless checks such as the `data-` prefix.
