### ISSUE TITLE
Typeahead options don't escape '<'

### ISSUE THREAD

**Issue by psgels** [angular-ui/bootstrap#6043]
In the uib-typeahead directive, if any of the options contains a '<', it is not escaped and treated as an HTML-tag, leaving the row blank. 

Especially since uib-typeahead works with html-tags itself I think it's wise to html escape its options, or at least provide an easy way to show '<'-characters if needed.

**Comment by wesleycho** [comment]
That sounds much more like a user responsibility to convert `<` into `&lt;`.

**Comment by psgels** [comment]
True, however the current way Typeahead is set up it makes this very difficult to actually do that, due to very inconsistent behavior: the entry sometimes shows correctly, and sometimes it doesn't. And when you select it with the < converted into &lt;, it shows up in its unconverted state. Converting it back does work, but then it messes with the filtering of the actual list, and I feel like it would be much more elegant if this were resolved withing ui-bootstrap itself.

**Comment by wesleycho** [comment]
And also potentially bloating up the library significantly for an edge case that the library is designed to allow users the control to handle.

Without a strong argument as to why it should be the library's responsibility, I am inclined to reject this request.

**Comment by wesleycho** [comment]
Closing due to lack of response & there being a strong argument against adding sanitization logic in the library itself.
