### ISSUE TITLE
Tooltip sometimes not working after upgrading from UIBS 0.13 to 1.3

### ISSUE THREAD

**Issue by nevcos** [angular-ui/bootstrap#6047]
### Bug description:

Tooltips randomly not showing when using **angular-timer**, after upgrading from UIBS 0.13 to 1.3.

### Link to minimally-working plunker that reproduces the issue:

Working with UIBS 0.13.0:
https://plnkr.co/edit/ba5RKLV8iE26nMjUGSRp?p=preview

Not working with UIBS 1.3.3:
https://plnkr.co/edit/5zqITvTfQGzfgAb0Fv1u?p=preview

### Tested versions

Angular: 1.5.7
Angular-timer: 1.3.4
Bootstrap: 3.3.6
UIBS: 1.3.3 and 2.2.0

### More debug details

On the following code of UIBS, when the tooltip don't work, the `interpolateFnWatchAction` is **only**  called on mouse leave. When it works, the function is executed **only** on mouse enter: 

``` javascript
($$observers[name] || ($$observers[name] = [])).$$inter = true;
(attr.$$observers && attr.$$observers[name].$$scope || scope).
  $watch(interpolateFn, function interpolateFnWatchAction(newValue, oldValue) {
    //special case for class attribute addition + removal
    //so that class changes can tap into the animation
    //hooks provided by the $animate service. Be sure to
    //skip animations when the first digest occurs (when
    //both the new and the old values are the same) since
    //the CSS classes are the non-interpolated values
    if (name === 'class' && newValue != oldValue) {
      attr.$updateClass(newValue, oldValue);
    } else {
      attr.$set(name, newValue);
    }
  });
```

One example of one of the tooltips that works on some routes and not in others, but this applies to all tooltips.

``` html
<li id="recent-calls-footer" class="footer-btn" uib-tooltip="Recent Calls">
    <a href="/search/recentCalls" style="display: block;" analytics-on="click" analytics-event="Recent Calls" analytics-category="Navigation" tpn-route="">
        <i class="icon-phone footer-icon" style="top:-3px; left:4px"></i>
        <span class="footer-icon-text ng-binding">3</span>
    </a>
</li>
```

Also noticed that when tooltips don't work, the tooltip element is created but without content, without attributes interpolation and without the "in" class:

``` html
<div class="tooltip ng-isolate-scope top fade" tooltip-animation-class="fade" uib-tooltip-classes="" ng-class="{ in: isOpen() }" uib-tooltip-popup="" uib-title="{{title}}" content="{{content}}" placement="{{placement}}" popup-class="{{popupClass}}" animation="animation" is-open="isOpen" origin-scope="origScope" style="top: 342px; left: 19px;">
  <div class="tooltip-arrow"></div>
  <div class="tooltip-inner ng-binding" ng-bind="content"></div>
</div>
```

With this scope:
![image](https://cloud.githubusercontent.com/assets/656065/16310842/140acd00-3966-11e6-97ac-77b306e42cc6.png)

And when it works (after retrying some more times), the element is:

``` html
<div class="tooltip ng-isolate-scope top fade in" tooltip-animation-class="fade" uib-tooltip-classes="" ng-class="{ in: isOpen() }" uib-tooltip-popup="" uib-title="" content="Recent Calls" placement="top" popup-class="" animation="animation" is-open="isOpen" origin-scope="origScope" style="top: 330px; left: -11px;">
  <div class="tooltip-arrow"></div>
  <div class="tooltip-inner ng-binding" ng-bind="content">Recent Calls</div>
</div>
```

With this scope:
![image](https://cloud.githubusercontent.com/assets/656065/16310874/324a16b8-3966-11e6-8673-51cf6b753487.png)

**Comment by icfantv** [comment]
@nevcos - it's not clear if you're unable to reproduce the issue in an isolated plunker or you haven't attempted to do so.  Can you please clarify?

Second:  That upgrade is a very large jump in versions.  Did you read through the [CHANGELOG](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md) for each version paying special attention to the BREAKING CHANGES sections?

Third:  We are all _unpaid_ volunteers and simply do not have the time to chase down issues written up like this without at least a minimal plunker that shows the issue.  We are not here to find implementation bugs in your code as the issues forum is not for support requests.  There was a link the issue template for how to get support help.

Please let us know how you would like to proceed.

**Comment by nevcos** [comment]
@icfantv The problem seems to occur in a very specific context. While trying isolating it, I was unable to reproduce it in a plunker, that's why I've added here as much information as possible.

Din't read the Changelog, only added the prefixes. But after reading, I think there's nothing more to do (we didn't use angular-ui extensively).

I will try to add more information and will retry to create a plunker.

Thanks

**Comment by icfantv** [comment]
@nevcos, ok, sounds good.

**Comment by nevcos** [comment]
@icfantv Sorry for the huge delay, I was able to test it better now and have updated the issue description with working and not plunker.
The issue seems related with `angular-timer`

Thanks!

**Comment by icfantv** [comment]
@nevcos no worries.  sounds like we can close this then?

**Comment by nevcos** [comment]
@cfantv You we can close it, at least while nobody else has the same problem 😄!
Thanks!
