### ISSUE TITLE
uib-dropdown not working

### ISSUE THREAD

**Issue by raman15071991** [angular-ui/bootstrap#6049]
i used uib dropdown but its not working properly the problem is its opening the li option without opening the dropdown selects the first option 
here is my code

`<div class="btn-group information" uib-dropdown is-open="status.isopen2" data-toggle="tooltip" data-placement="bottom" title="You can create, edit or update"> <p id="default-button" class="test save-dropdown" type="button" uib-dropdown-toggle ng-disabled="disabled" style="border: 1px solid #c5c5c5;padding: 5px;background:#fff;cursor:pointer"></p> <ul class="dropdown-menu dropdown-lead03" uib-dropdown-menu-right role="menu" aria-labelledby="single-button"> <li role="menuitem"> <a herf="" class="btn dropdown-option" ng-click="saveView()" id="btn_SaveView"> <i class="fa fa-eye" aria-hidden="true"></i> Save View </a></li> <li role="menuitem"> <a herf="" class="btn dropdown-option" ng-click="editView()" id="btn_editView" style="text-align: left;"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a></li> <li role="menuitem"> <a herf="" class="btn dropdown-option" ng-click="deleteView()" id="btn_deleteView" style="text-align: left;"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a></li> </ul> </div>`

please help me

**Comment by icfantv** [comment]
@raman15071991, please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete or poorly-written issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.

**Comment by raman15071991** [comment]
ok i will write it in a proper manner , I apologize for that
