### ISSUE TITLE
Datepicker is case sensitive on the month

### ISSUE THREAD

**Issue by mjhamm75** [angular-ui/bootstrap#6053]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
The date has to be entered with the first letter capitalized or the model is `undefined`.  For example `01 Jun 2015` parses fine, but `01 jun 2015` is `undefined`.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/4O4RzBh0hXoyfCg6y0HN?p=preview

### Version of Angular, UIBS, and Bootstrap
Angular:
angular 1.5
UIBS:
uibs 1.3.3
Bootstrap:
bootstrap 3.3.6

**Comment by wesleycho** [comment]
This could potentially be complex - we make use of information from $locale here, i.e. https://github.com/angular/angular.js/blob/master/src/ngLocale/angular-locale_en-us.js#L69-L82 . We would have to verify that toLowerCase() does not have ramifications across multiple languages.

I am inclined to reject this request as a consequence, as I do not believe this adds much for UX (users typically don't keep month names as lowercase unless if lazy).

**Comment by mjhamm75** [comment]
My users use the widget to input lots it data and capitalizing the first letter slows them down.  I would expect them to input the month and the first letter to automatically capitalize to have consitency with the other 3 letter inputs

**Comment by wesleycho** [comment]
Why not make use of the fact that there is a yearpicker then if that is a concern? One can also use an input `type="date"` to be more restrictive too.

**Comment by mjhamm75** [comment]
In an app that is all about data input, staying away from dropdown's
greatly speeds up the user.  The same way that we as programmers don't like
to move our hands off the keyboard to use our mouse unless we absolutely
have to.  This is an app where the user will type in hundreds of dates a
day.  It saves lots of clicks to be able to just type in the format that
they are already accustomed to, instead of having to click on a dropdown
and then click on the year that they need.

**Comment by wesleycho** [comment]
Problem is, if we were to add this feature, it would undoubtedly be easy to add support for English. However, we are extremely likely to break the display & validation for other languages, and that is why I am extremely loathe to add support - we definitely have users who use this datepicker with i18n support.

**Comment by mjhamm75** [comment]
That completely makes sense.  Obviously I was trying to stay away from
forking and doing a 1 off, but the overall community is obviously most
important.  If there is a way it can be done, excellent, if not keep up the
good work and I will definitely keep using the excellent stuff you guys are
making/maintaining.

**Comment by wesleycho** [comment]
In this case, you don't need to fork the library - you could take the dateparser service from current master and make the appropriate modification to the regex. It should be a one line modification to the MMM format object in formatCodeToRegex to add another copy with all lowercase months

**Comment by wesleycho** [comment]
Going to close this as there is a sufficient workaround for your use case that is non-intrusive (overriding the service).

**Comment by jessicabyrne** [comment]
I also need this capability, but for my users, I need them to be able to add the month in all capitals 10MAY16 and 10MAY2016

I am out of my depth changing the source code as is suggested here. I found formatCodeToRegex but can't figure out what to change. Could I get a little guidance on how to do this please?

**Comment by wesleycho** [comment]
@jessicabyrne try taking a look [here](https://github.com/angular-ui/bootstrap/blob/d846e2d788020c8d4c270ae7d90066bb092f1a16/src/dateparser/dateparser.js#L68) - that constructs the regex as a string. One approach would be to add lowercase versions, but that won't catch all scenarios. Another approach is adding the `i` flag (case insensitive) as the second argument to `new RegExp` [here](https://github.com/angular-ui/bootstrap/blob/d846e2d788020c8d4c270ae7d90066bb092f1a16/src/dateparser/dateparser.js#L293).

**Comment by jessicabyrne** [comment]
Would it be easier to do some kind of parser in an Angular controller instead?

**Comment by mjhamm75** [comment]
@jessicabyrne - Did you ever get this working in your app?
