### ISSUE TITLE
Timepicker flickers inside a modal

### ISSUE THREAD

**Issue by rizoom** [angular-ui/bootstrap#6065]
### Bug description:
The UIBS timepicker widget is included in a UIBS modal with show-spinners and show-meridians set to false. The widget flickers during the rendering. It does not happens for timepicker widgets outside the modals.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/vMa5BnTGVIwcOhmoLHHT?p=preview
In order to easily see the flickering, I inserted 10 timepickers, which seems to increase the effect.
The are 10 timepickers without flickering on the main page, and 10 inside the modal with the flickering.

It is also visible with spinners and meridian, it still affect the "seconds" input, as shown in this plunker:
http://plnkr.co/edit/4rTePkeBKp1M5sNDO0qC?p=preview

### Version of Angular, UIBS, and Bootstrap
Angular: 1.5.3
UIBS: 1.3.3
Bootstrap: 3.3.6
Tested with Chrome 51

**Comment by rizoom** [comment]
In fact, it might not be related to the timepicker but to ng-hide/show in modals.
See this plunker where 10 paragraphs are hidden in the modal:
http://plnkr.co/edit/lrjJdiudabgnHe6mefgv?p=preview

The flickering is less visible in this case (because the content of the modal is obviously quickier to process for Angular I guess)

**Comment by icfantv** [comment]
Closing in favor of #5957 as this will result in a complete rewrite of the widget, addressing all the outstanding issues.
