### ISSUE TITLE
uib-alert stays hidden when ng-cloak is used

### ISSUE THREAD

**Issue by nguillaumin** [angular-ui/bootstrap#6066]
### Bug description:

When I use `class="ng-cloak"` with a `<uib-alert />`, the alert stays hidden even after Angular has been initialised.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/e0phVsRYwl5jBhGniV5m?p=preview

It's a copy of the doco plunker where I added `class="ng-cloak` on the last alert, as well as a `<p class="ng-cloak">` above it to demonstrate the `<p>` is shown.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0
UIBS: 1.3.3
Bootstrap: 3.3.0

**Comment by wesleycho** [comment]
This is actually fixed in `master` already - see [here](http://plnkr.co/edit/PcYwSlSJKY2F8fPxfbW1?p=preview) for fix in action. The reason this occurs is because we use `replace: true`, and that is being removed for 2.0.

**Comment by huyph** [comment]
@wesleycho any idea when 2.0 will be released?

Should we have 1.3.4 for this bug fix and other fixes in the master?

**Comment by icfantv** [comment]
@huyph, no.  we do not release back-release patches.  we are all volunteers and simply do not have the time or resources to support multiple release branches.

@wesleycho and I are having a discussion about 2.0 and should know more soon, but we simply cannot commit to a hard date.

Please feel free to pull the latest from `master` and do a local build if you desire this code now and simply cannot wait.

**Comment by huyph** [comment]
Yeah that is fair. I was just wondering 😅 

Sounds good. Thanks for your contribution 👍

**Comment by nguillaumin** [comment]
Thanks guys!
