### ISSUE TITLE
Datepicker inputfield isn't refreshed after model change

### ISSUE THREAD

**Issue by chokdee** [angular-ui/bootstrap#6070]
### Bug description:
After doing a REST call the model isn't refreshed and the datepicker  The popup shows the correct value but the input field not.

### Link to minimally-working plunker that reproduces the issue:
don't have,
but see detailed description here:
http://stackoverflow.com/questions/38167986/initial-value-of-datepicker-angular-ui-isnt-shown

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.5

UIBS:
1.3.3

Bootstrap:
3.2.0

**Comment by chokdee** [comment]
Got it after many hours.
The REST Service got back a Date as String.
No error in comversion and the datepicker pop accept it but the input field not.

Maybe better to fix this.

**Comment by wesleycho** [comment]
We explicitly mention in the documentation that it should be a date object - see [here](https://angular-ui.github.io/bootstrap/#/datepicker). The reason is that there are state issues that arises when the model is a string/number, as well as timezone issues that are difficult to control.

**Comment by chokdee** [comment]
Not a good idea not to fix it.
