### ISSUE TITLE
Pagination with rel=“next” and rel=“prev”

### ISSUE THREAD

**Issue by harm-less** [angular-ui/bootstrap#6072]
According to Google they make use of pagination in a certain way for SEO purposes:
https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html

It is possible to also apply this to the pagination directive or does this conflict with the fact that the native Bootstrap component doesn't support this too?

**Comment by icfantv** [comment]
@harm-less, if this is just an HTML change, then you can override the template as to your liking.  That said, if this is indeed the case, I'm not opposed to having this in the core library.

**Comment by icfantv** [comment]
@wesleycho?

**Comment by wesleycho** [comment]
This looks like it's for adding links to the `head` tag via `link` tag. This is actually something that doesn't need any library changing to support, it is wholly up to the user to apply this.

**Comment by harm-less** [comment]
You're completely right wesley. I'm sorry for bringing this up, but thanks for the comments.
