### ISSUE TITLE
r

### ISSUE THREAD

**Issue by samwarnick** [angular-ui/bootstrap#6073]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by icfantv** [comment]
closing due to lack of content....or title.
