### ISSUE TITLE
Any way to support closing the nested accordions once the parent is closed?

### ISSUE THREAD

**Issue by MarkoIvanetic** [angular-ui/bootstrap#6074]
I was thinking about temporary solution by having "is-open" attribute on nested accordion to be "isOpen && $parent.$parent.$parent.isOpen".

But it doesn't seem to work.

**Comment by wesleycho** [comment]
This is up to the user to control - the accordion exposes everything necessary to do this, and any additional support does not make sense to add into the library itself.
