### ISSUE TITLE
How to setup responsove navbar like in bootstrap3?

### ISSUE THREAD

**Issue by kolkov** [angular-ui/bootstrap#6075]
I need a detailed guide to properly setup one responsive menu in navbar that work on desktops and on mobiles.
http://getbootstrap.com/
I want to menu mobile version was closed when selecting the menu item.
I want to menu items are highlighted.

ui-bootstrap-tpls-1.3.3.js
angular-ui-router.js

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

**Comment by kolkov** [comment]
Thanks!
I'll just leave it here.
http://stackoverflow.com/questions/38004168/navbar-dropdown-with-angular-and-ui-router-wont-work
