### ISSUE TITLE
uib-alert close button not rendered when using ng-bind

### ISSUE THREAD

**Issue by stevie-p** [angular-ui/bootstrap#6081]
Hello ui-bootstrappers

This isn't a major bug, but it had me confused for a while, so might be worth investigating or documenting.

### Bug description:
When using `ng-bind` (or similar) to set the the inner content of a `uib-alert`, the close button does not get rendered. For instance:

`<uib-alert ng-repeat="alert in alerts" type="{{alert.type}}" close="closeAlert($index)" ng-bind="alert.msg"></uib-alert>`

http://plnkr.co/edit/DrZzUoAqvDKu4a7NGDI5?p=preview

Angular: 1.5.3
UIBS: 1.3.2
Bootstrap: 3.3.5

**Comment by icfantv** [comment]
@stevie-p, this is because we're using `transclude` on our template.  if you want to play with this to see if there's a way around it, go ahead.  be mindful of creating unnecessary extra watches.

if you don't care, i'm just going to close this as won't fix.

**Comment by stevie-p** [comment]
Thanks @icfantv - let's close the issue.
I might have a look at the source and think about it when I have time...
