### ISSUE TITLE
uib-tabset breaks directive binding to controller outside uib-tabset

### ISSUE THREAD

**Issue by xenobytezero** [angular-ui/bootstrap#6084]
### Bug description:

When using a custom directive with an isolate scope inside a `uib-tabset`, where the directive is bound to data outside the `uib-tabset`, changing the data value inside the `uib-tabset` will break the watch 

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/pnL6mAyo8J6SyxQmV8LO

To show the bug, follow the steps below

1. Click the "Change from Controller" button a few times. The value in the controller changes, as it does in all of the directives bound to the data
2. Click the **FIRST** `Change From Directive` button a few times. The value in the directive changes, which permeates to the controller and the other bound directives.
3. Click the **SECOND** `Change From Directive` button a few times. The value in the directives inside the `uib-tabset` will change as expected, however the controller and directive outside the `uib-tabset` will not change.
4. Click the "Change from Controller" button a few times. This shows that the binding between the controller and the directives inside the `uib-tabset` is now completely broken

### Version of Angular, UIBS, and Bootstrap
Tested with
* Angular: 1.5.3
* UIBS: 1.3.3
* Bootstrap: 3.1.1

* Angular: 1.4.5
* UIBS: 1.1.2
* Bootswatch: 3.3.4+1

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive

**Comment by xenobytezero** [comment]
Looks like I still have more Angular to learn.

Thanks for the quick response, apologies for the noise.
