### ISSUE TITLE
JavaScript Response Issue :   When editing an issue the date saved is the date selected - 1 day   

### ISSUE THREAD

**Issue by walipun** [angular-ui/bootstrap#6085]
​E.g. To set the date for Issue ID 227 "Reporting process failure due to error “Cannot format given Object as a Date” to 2016-07-01 I had to select 2016-07-02 pn the pop up calendar.
 

JavaScript

**Comment by pkozlowski-opensource** [comment]
We can't help with issues without a proper reproduce scenario, see: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug
