### ISSUE TITLE
Can't use 'outsideClick' as a hide trigger.

### ISSUE THREAD

**Issue by synthecypher** [angular-ui/bootstrap#6086]
I've configured a trigger, to show the popover when the custom event `popoverShow` is detected.

I also want the hide event of this custom trigger to be `outsideClick`.

If I configure it like so it will not hide on `outsideClick`.

```javascript
$uibTooltipProvider.setTriggers({
  'popoverShow': 'outsideClick'
});
```

Reproduced here.

http://plnkr.co/edit/QEv4i6iMMAw65IOfAuSh?p=preview

I basically need to have the popover appear after completing some async behaviour, so I have my own click handler which does the async behaviour then if applicable triggers the `popoverShow` event for the handler.

**Comment by synthecypher** [comment]
Fixed the problem see this pull request.

https://github.com/angular-ui/bootstrap/pull/6087

**Comment by icfantv** [comment]
closing per comments in #6087.

**Comment by heavymanners** [comment]
The comment in #6087 doesn't address the core need, which is to have the outsideClick functionality for hide triggers. The comment says that the functionality is covered by 'click,' but it isn't, as click requires the user to click on the element itself, while outsideClick handles clicks outside of the element.

**Comment by panxq5** [comment]
+1 this is helpful
