### ISSUE TITLE
Timepicker form validation is wrong when min or max timepicker attribute is used

### ISSUE THREAD

**Issue by reinisp** [angular-ui/bootstrap#6088]
### Bug description: When updating invalid time with timpicker arrow buttons form is marked as valid even timepicker min time is greater than timepicker ng-model value.
 **Steps to reproduce:** 
1. Open plunker demo
2. Check that arrow to decrease minutes are disabled as current timepicker model equals min time
3. Manually set timepicker minutes to e.g. 25
4. Check that form is marked as invalid
5. Use timepicker arrow button to increase minute value. 

**Observed** Timepicker is marked as valid
**Expected** Timepicker is still invalid as min time is greater than timepicker model time

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.3

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
Closing in favor of #5957 as this will result in a complete rewrite of the widget, addressing all the outstanding issues.
