### ISSUE TITLE
Suggestion list disappears on scrolling when react autosuggest is used in angular ui bootstrap modal 

### ISSUE THREAD

**Issue by shreyabharadwaj** [angular-ui/bootstrap#6089]
The suggestion list rendered by the react autosuggest component disappears on scrolling the suggestion list using the mouse left click when the autosuggest component is used in a angular ui bootstrap modal popup. This issue is replicated in Chrome, Firefox as well as IE11.

React autosuggest component used is:
https://github.com/moroshko/react-autosuggest

**Comment by icfantv** [comment]
@shreyabharadwaj, pretty sure this isn't the right forum for your issue.
