### ISSUE TITLE
Select element in ui-bootstrap modal body doesn't allow modal-footer to render

### ISSUE THREAD

**Issue by navalsharma** [angular-ui/bootstrap#6090]
### When I use Select element in modal body then it doesn't show footer where I have OK and Cancel buttons. If i replace select element with input then it works perfectly fine. I don't know how to handle this issue.
`<div class="modal-body">
      div class="form-group">
	   
            <select class="form-control"/>
	</div>
</div>`

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.7

UIBS: 1.3.3

Bootstrap: 3.3.4

**Comment by icfantv** [comment]
Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.

**Comment by navalsharma** [comment]
I have managed to resolve this problem. I was using inline select which was creating problem in template.
It should be closed with separate statement.
<select> </select>

Though it works if I use input tag in inline style and that was confusing me.

Anyways thanks for the help.
