### ISSUE TITLE
Issue with carousel navigation controls not working when inside a modal

### ISSUE THREAD

**Issue by GenYCoder** [angular-ui/bootstrap#6092]
I've been at this for hours and still can't figure out why when a carousel is inside a modal, the navigation will work once but will stop moving. The index will be stuck at that same number without going to the next index. Maybe you guys can shed some light with the issue with the nav controls not working inside a modal

**Comment by GenYCoder** [comment]
![screen shot 2016-07-15 at 5 15 50 pm](https://cloud.githubusercontent.com/assets/4743914/16888652/76f6719e-4aaf-11e6-88c6-4d7b5b252370.png)

**Comment by icfantv** [comment]
@GenYCoder, please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.
