### ISSUE TITLE
Timepicker form validation is marked as invalid after clearing input field values

### ISSUE THREAD

**Issue by reinisp** [angular-ui/bootstrap#6099]
### Bug description: Timepicker form validation is marked as invalid, if user manually clears timepicker input field values.

Steps to reproduce: 
1. Open plunker demo
2. Clear timepicker input fields
3. Click outside timepicker (offocus)

Observed Timepicker is marked as invalid
Expected Timepicker is marked as valid

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/Bo50jUyF4xtpXmHkDQj0?p=preview
### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.3

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
Closing in favor of #5957 as this will result in a complete rewrite of the widget, addressing all the outstanding issues.
