### ISSUE TITLE
Datepicker Ng model format to view format

### ISSUE THREAD

**Issue by julienperrault** [angular-ui/bootstrap#6101]
I use Datepicker in a directive to pick a date with "dd/MM/yyyy" format (with uib-datepicker-popup="dd/MM/yyyy"). It sends to the ngModel a ISO formatted date ("date_db": "2016-06-15T22:00:00.000Z").
I save that value in a DB. After a reload of the page, the API is called to get all saved values so that all input are filled with their values.

But the Datepicker is not filled with the ISO value due to the format (the input format expected is "dd/MM/yyyy").

In simple words : 
The format conversion view value (input - dd/MM/yyyy) to ngModel (ISO) works
The format conversion ngModel (ISO) to view value (input - dd/MM/yyyy) doesn't work.

**Comment by icfantv** [comment]
@julienperrault, please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.
