### ISSUE TITLE
2.0.0 breaks keyboard-nav on uib-dropdown

### ISSUE THREAD

**Issue by mattlewis92** [angular-ui/bootstrap#6102]
### Bug description:
`keyboard-nav` on the `uib-dropdown` menu is broken in `2.0.0`. It looks like it was this commit that broke it: https://github.com/angular-ui/bootstrap/commit/603840317915e9c749ed5e9320714689e33dea77

If you add the event listener on the `$document` instead of the [dropdown menu element](https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L264) then it works, I'd send a PR but I'm assuming there is a reason why the event listener is bound to the dropdown menu instead of the document.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/AmmUCB7iidPBKVw6r1Ne?p=preview

(Hit the up and down arrows after opening the dropdown - this was just copied from the demo)

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.x
UIBS:
2.0.0
Bootstrap:
3.3.6

**Comment by icfantv** [comment]
@wesleycho, thoughts?

**Comment by wesleycho** [comment]
So as mentioned in the commit that changed this, the reason for the change is #5965 - in particular, this change is mandatory when appending/destroying the dropdown menu on toggle for the append-to option.

We need to look at this carefully.

**Comment by mattlewis92** [comment]
Even with `dropdown-append-to-body` added to the plunker, keyboard navigation doesn't seem to work, could binding the event listener to the `$document` instead handle all instances?

**Comment by wesleycho** [comment]
`document` is not the right solution - this would break some rules of accessibility, since the user could be focused elsewhere and it would still force navigation on the dropdown. Also if two dropdowns are open, it would navigate on both.

**Comment by mattlewis92** [comment]
OK what about binding the keydown to the document and then checking if the trigger element or the dropdown menu contains the `$event.target` element of the keydown event? Something like:
```
this.keybindFilter = function(evt) {
    var dropdownElementTargeted = dropdownElement && dropdownElement[0].contains(evt.target);
    var toggleElementTargeted = toggleElement && toggleElement[0].contains(evt.target);
    ... if (... (dropdownElementTargeted || toggleElementTargeted)) {
      evt.preventDefault();
      evt.stopPropagation();
      openScope.focusDropdownEntry(evt.which);
    }
  };
```

**Comment by mattlewis92** [comment]
@wesleycho any more thoughts on my proposed solution to this? Happy to work on a PR for it unless you can think of any potential issues with it?

**Comment by wesleycho** [comment]
I am not able to evaluate any issues deeply for at least another week - I am currently on vacation in Europe (have been for the past two weeks).

**Comment by mattlewis92** [comment]
Ah no worries, enjoy your holiday! 😄

**Comment by wesleycho** [comment]
Reading your proposed solution, I think this might be how we have to handle this - would you be interested in filing a PR? Adding a test for this situation also would help guard us from breaking this accessibility related issue in the future.

**Comment by mattlewis92** [comment]
Sure thing, I'll try and get to it over the next day or so
