### ISSUE TITLE
2.0.0 Nested modal not working correctly, backdrop in front and not closable

### ISSUE THREAD

**Issue by bisswanger** [angular-ui/bootstrap#6103]
### Bug description:

Calling $uibModal.open from within an open modal dialog causes the new dialog being shown in the back of the active dialog. The screen front is covered by the related backdrop which makes the site unusable.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/9cTZmaD0Veriujy9n7iE?p=preview
Click on "Open Me" and then any of the shown list items.
(Increase the size of the preview to see that the "lg" dialog is behind the active one)

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.x
UIBS:
2.0.0
Bootstrap:
3.3.6

**Comment by mavrick** [comment]
Thanks for submitting this @bisswanger - I was going to put together a bug report this morning but saw yours first :+1:

**Comment by rajucp** [comment]
Well. looks like this issue hasn't been resolved. Am I missing something. The same plunker above changed to 2.1.3 version and still not working.

http://plnkr.co/edit/QJpwzXpILPpOp67CXa1b?p=preview
