### ISSUE TITLE
Tooltip/Popover close on escape broken

### ISSUE THREAD

**Issue by stuartforster** [angular-ui/bootstrap#6108]
There is an issue with Chrome and potentially other browsers with capturing 'escape' for a 'keypress' event. 

This is preventing the ui-bootstrap tooltip (and popovers) from closing on press of escape key.

This should be changed to keydown or keyup here: https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L74

I will submit a PR with a fix shortly.

**Comment by icfantv** [comment]
@stuartforster, i can confirm that the event is not fired when `keypress` is used.  i will also confirm that changing to `keyup` or `keydown` does not cause the tooltip/popover to be closed.

what trigger do you expect this to work with?  also, please note that any code change will require tests.

**Comment by stuartforster** [comment]
Thanks @icfantv, trigger could be keyup or keydown, I think keyup probably makes most sense.

I'll investigate why the popover still doesn't close even when the event is firing.

I will include tests with any PR I submit.

**Comment by icfantv** [comment]
@stuartforster, after a thorough investigation, it appears the tooltip reference inside the close handling sequence is not defined meaning when the actual close route is executed, nothing happens and the tooltip stays open.

[Here's a plunker](http://plnkr.co/edit/WVTd5prw08Mj7tF6vEI4?p=info) to get you started.  I've already set the event to `keyup`.  Set a breakpoint at line 4724 and trace through and you'll see that ultimately the reference to `tooltip` is not defined which results in 4988 not being executed.
