### ISSUE TITLE
2.0.0 Modal content shift to right with container and scrollbar

### ISSUE THREAD

**Issue by Megaboot** [angular-ui/bootstrap#6109]
### Bug description:
Hello since the version 2.0.0, when i have a container with enough content to display a scrollbar and i click on a button to open a modal the content is shift to the right.
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/9QQME0SJOiJ24v4I7dYk
### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.5

UIBS: 2.0.0

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@Megaboot, please be respectful of our time and processes by searching both open and closed issues prior to entering any new issue.  This issue has been addressed a myriad of times and is most likely a CSS issue on your end.

**Comment by Megaboot** [comment]
@icfantv I'm sorry i can't find an issue related to me, i found https://github.com/angular-ui/bootstrap/issues/5749 which is similar to mine but with a fixed navbar. But we can also reproduce the issue with the plunk that @RobJacobs gave in is last comment if you update ui bootstrap to 2.0.0, because in the navbar it contains a container class.

I can't either find a documentation that speak about this breaking change because it was working fine in 1.3.3.
