### ISSUE TITLE
tabset, active property on tab - undefined is not a function

### ISSUE THREAD

**Issue by MannyC** [angular-ui/bootstrap#611]
I get this when I try to use the active property on a tab, example: 

``` html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="bootstrap.min.css">
        <script src="angular.js">  </script>
        <script src="ui-bootstrap-tpls-0.4.0.js"> </script>
        <script src="angular-test.js"> </script >
    </head>
    <body ng-app="angular-test">
        <div ng-controller="AngularTestController">
            <tabset>
                <tab heading="Tab 1" active="true"> test 1 </tab>
                <tab heading="Tab 2"> test 2 </tab>
            </tabset>
        </div>
    </body>
</html>
```

angular-test.js:

``` javascript
angular.module('angular-test', ['ui.bootstrap']);
function AngularTestController($scope) {
  //nothing yet
}
```

Stack trace:
TypeError: undefined is not a function
    at postLink (file:///C:/proj/angular-test/ui-bootstrap-tpls-0.4.0.js:2374:11)
    at nodeLinkFn (file:///C:/proj/angular-test/angular.js:4406:13)
    at delayedNodeLinkFn (file:///C:/proj/angular-test/angular.js:4559:11)
    at compositeLinkFn (file:///C:/proj/angular-test/angular.js:4003:15)
    at publicLinkFn (file:///C:/proj/angular-test/angular.js:3920:30)
    at file:///C:/proj/angular-test/angular.js:4009:30
    at new ngDirective.controller (file:///C:/proj/angular-test/angular.js:14046:5)
    at invoke (file:///C:/proj/angular-test/angular.js:2902:28)
    at Object.instantiate (file:///C:/proj/angular-test/angular.js:2914:23)
    at file:///C:/proj/angular-test/angular.js:4805:24 <li ng-class="{active: active, disabled: disabled}" heading="Tab 1" active="true" class="ng-scope">

**Comment by gilluminate** [comment]
This is the solution I use and is less cumbersome than adding/removing true/false from each tab:

````html
<button class="btn" ng-click="activateTab('search')">Search</button>
<button class="btn" ng-click="activateTab('preview')">Preview</button>
<button class="btn" ng-click="activateTab('edit')">Edit</button>

<tab heading="Search" active="active.search">...</tab>
<tab heading="Preview" active="active.preview">...</tab>
<tab heading="Edit" active="active.edit">...</tab>
````

then set up your default tab like so:

````javascript
$scope.active = {
  search: true
};
````

and the isActive() function:
````javascript
$scope.activateTab = function(tab) {
  $scope.active = {}; //reset
  $scope.active[tab] = true;
}
````

**Comment by Sampath-Lokuge** [comment]
+5 @gilluminate it works.Thanks a lot :)

**Comment by TigerSoaring** [comment]
@gilluminate
+10086
^_^

**Comment by diosney** [comment]
bump

**Comment by diosney** [comment]
Thanks @gilluminate, worked for me too.

**Comment by czegarram** [comment]
Thanks x 1000!

**Comment by saeidzebardast** [comment]
@gilluminate
Thanks. You really saved my day!

**Comment by sgentile** [comment]
@gilluminate   +1

**Comment by KarunaSirpa** [comment]
@gilluminate  Thank you.

**Comment by becoder** [comment]
@gilluminate thanks a lot, works like charm!

**Comment by kirakishin** [comment]
@gilluminate  +10 thanks a lot

**Comment by Lujaw** [comment]
@gilluminate Thanks

**Comment by icfantv** [comment]
Just to let you guys all know that the API for this attribute has changed such that the `active` attribute on the `uib-tab` directive is not longer supported in the latest versions of the library.  Rather, it serves ONLY for CSS purposes and is no longer documented in `master` as being for API users use.

**Comment by ultrarunner** [comment]
Just saw your comment @icfantv and noticed that the active property is listed in both sections of the documentation under ui-tab-settings. Will it be removed from the top one? If yes, how can we programmatically select a tab from now on? Thank you.

**Comment by icfantv** [comment]
@ultrarunner, the docs are incorrect (but have been fixed in `master`).  The `active` property on the `uib-tabset` element is the correct one to use now.  You can use it by setting it to the numerical index of the tab you would like to make active.  There is an outstanding PR (#5577) to support a string, but it is missing tests and documentation.  That said, the committer did respond saying they would rectify soon.

**Comment by ultrarunner** [comment]
@icfantv, thank you very much. Makes sense now.

**Comment by volkanx** [comment]
@icfantv 

Hi Adam, I'm having a strange problem with dynamically created tabs. I'm trying to set the last added tab active by setting its index on uib-tabset.active. It works on odd number of tabs (when there are 1,3,5 of them) and doesn't set the active one on even numbers.

I asked it on StackOverflow here: http://stackoverflow.com/questions/36420035/setting-active-tab-on-dynamically-created-tabs-with-angular-ui-bootstrap

One person suggested to use $timeout where I set the index and it works but I have no idea why!

Here's the link for the Plunk that demonstrates the issue: https://plnkr.co/edit/TX6ek4R62AfM2zUXcoC3?p=preview

This thread looked similar that's why I commend on this instead of starting a new one but I can do so if that's the proper way. 

I'd appreciate any feedback.

Thanks.

**Comment by icfantv** [comment]
@volkanx we've had several threads going that I will link to below indicating that we will not be supporting dynamic tabs.  but, if memory serves, the $timeout solution worked for someone else.

See issues:  #5654, #5656, and #5725.

**Comment by volkanx** [comment]
@icfantv Thanks for the info. I'll go with timeout and leave it that then. Thanks.

**Comment by renu-th** [comment]
<button ng-click="facAdd.selectTab()">Select Tab</button>

					<uib-tabset justified="true" active="facAdd.activeTab"> 
					<uib-tab
						index=1> <uib-tab-heading>
					Facility Information </uib-tab-heading>
					<form name="facUpd1">
					
					</form>
					</uib-tab> 
					<uib-tab index=2 > <uib-tab-heading>
					Addresses </uib-tab-heading> 
					<form name="facUpd2">
					
					</form>
					</uib-tab>
					<uib-tab index=3> <uib-tab-heading> Point of
					Contacts </uib-tab-heading> 
					<form name="facUpd3">
					
					</form>
					</uib-tab>
				
					<uib-tab index=4 > <uib-tab-heading>
					Verification/Inspection</uib-tab-heading>
					<form name="facUpd4">
					<div></div>
					</form>
					</uib-tab>
					</uib-tabset>


**Controller**
vm.selectTab= function()
		{
			vm.activeTab=4;
			vm.ind=3;
		}
For some reason this does not work for me in my application. Can anyone please help me out?

**Comment by MannyC** [comment]
@renu-th I suggest putting it in a plunkr or similar

**Comment by renu-th** [comment]
@MannyC : I did a sample on Plnkr it works fine, but it isn't working fine in my application.
