### ISSUE TITLE
multiple modals are not shown properly

### ISSUE THREAD

**Issue by jessehart** [angular-ui/bootstrap#6114]
when triggering a modal from within a modal the z-index is not properly set on the new modal. this results in the second modal showing below the first and the backdrop covering both.

http://plnkr.co/edit/go9iUrVN7pcbRpOUbv2u?p=preview

Angular: 1.5.8
UIBS: 2.0.0
Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@jessehart, please be respectful of our time by searching both open and closed issues before entering a new one.  Not only was this reported in the last few days but a PR fix was already submitted and accepted.
