### ISSUE TITLE
Tabs $scope.active do not work.

### ISSUE THREAD

**Issue by witoldszpur** [angular-ui/bootstrap#6115]
### Bug description:
Hello,

I have a bug in ```Tabs```

All my tabs is switched by outside buttons. After when you remove ```replace: true``` and make ```ng-isolate-scope``` is have a weird behaviour. Sometimes ```$scope.active``` in child is not updated, when I change it on parent. 

I see that:

```<div active="active" class="ng-isolate-scope">```  pass it through, but somehow is not updated. 

I tried also do:

``` 
   $scope.$evalAsync(
         function( $scope ) {
              $scope.active = number;
            }
   );
```  
or directed update child scope.

this is my function which I use to switch tabs:

```
    function switchTab(number, name) {
       $location.hash(name);
       $scope.active = number;
    }
```

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 2.0.0

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@witoldszpur, please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.
