### ISSUE TITLE
$uibModal not showing up. ui-bootstrap-tpls used still doesn't work. It works on Safari but doesn't for Chrome

### ISSUE THREAD

**Issue by IamGabrielWu** [angular-ui/bootstrap#6117]
Hi  i have a issue regarding angular-ui-bootstrap. I'm not sure if it's a bug because it works at Safari but not Chrome and it's on Stackoverflow for a week, no one help answer my doubt. Could you please help take a look please ?

http://stackoverflow.com/questions/38522423/uibmodal-not-showing-up-ui-bootstrap-tpls-used-still-doesnt-work-it-works-on

**Comment by icfantv** [comment]
Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.

**Comment by icfantv** [comment]
Our demo site is working.  Without a minimally-working plunker that reproduces the issue, there is nothing we can do.
