### ISSUE TITLE
Datepicker Popup Bug on Min / Max Date

### ISSUE THREAD

**Issue by mkoutroupis** [angular-ui/bootstrap#6118]
### Bug description: 
Min and Max Date in Datepicker Popup doesn't work either by defining min-date / max-date attribute or by setting datepicker-options

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/y1DvReVwFxFTk1UVR1yJ

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.7

UIBS: 1.3.3

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
Please extend us the courtesy of searching big open and closed issues prior to entering a new one as this is a duplicate.

**Comment by mkoutroupis** [comment]
Still not working
http://codepen.io/Koutroupis/pen/YGQZOw
