### ISSUE TITLE
bug(datepicker): doesn't fire ng-change events

### ISSUE THREAD

**Issue by ostronom** [angular-ui/bootstrap#612]
I have an issue with ng-change and datepicker directive. In this piece of code:

```
<...ng-repeat="p in props"...>
   <div datepicker ng-model="p.value" ng-change="myScopeFunction()"></div>
<...>
```

`myScopeFunction` is never called.

**Comment by dev-mjoy** [comment]
@johntom I nearly went through 7 hrs searching and finally got this small magic :+1:  ,Thanks a Lot!

**Comment by kris8889** [comment]
Hi,
I have tried this solution 

html
ng-change="selectDate(dt)"

js
$scope.selectDate = function(dt) {
console.log(dt);
}
but still not able to hit the event . Can anyone please post a plunkr link of this ?

Thanks in advance.

**Comment by dev-mjoy** [comment]
@kris8889 here is the link-- http://plnkr.co/edit/rbB3nf?p=preview  
[i have used moment js for parsing data.]

**Comment by blacksmoke26** [comment]
@johntom Thank you, solved my problem too.

**Comment by hmudassir** [comment]
I am facing on ng-change issue. I am using dynamic datetime-picker. date is showing in ng-model but ng-change not firing. Please help.........
