### ISSUE TITLE
Tooltip doesn't show up when svg's <foreignObject> elements with <body> are used on the page

### ISSUE THREAD

**Issue by maximusk** [angular-ui/bootstrap#6120]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
If there are svg elements with `body` tag on the page, tooltip doesn't show up

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by wesleycho** [comment]
Closing due to lack of response.
