### ISSUE TITLE
Popover with UTF8 characters

### ISSUE THREAD

**Issue by molerat619** [angular-ui/bootstrap#6121]
### Bug description:
That's what I am doing:

      `<i class="fa fa-question-circle help-icon" popover-html="{{ 'book.popover.airport.text' | translate }}"></i>`

The `'book.popover.airport.text'`to be translated contains simple HTML (like `<br>`) and UTF8 characters e.g. `ü`. I get following error on hover (I've set mouseenter as my trigger in config).

`angular.js:68 Uncaught Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 22-22 [ü] in expression [An welchem Flughafen dürfen wir ...].`

angular 1.4.0
boostrap 3.1.1
angular-bootstrap 0.13.0

**Comment by icfantv** [comment]
Please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.

First and foremost, you are lacking a working plunker that demonstrates the issue.  Secondly, you're using a very old version of UIBS.  If you would like us to look into this issue, please create a minimally working plunker using the latest versions of Angular, Bootstrap, and UIBS that shows this issue.  You may use the Edit in Plunker link [for the tooltip demo](http://angular-ui.github.io/bootstrap/#/tooltip) on our demo page to get you started quickly.
