### ISSUE TITLE
Could not update active tab index on view after adding some tabs or deleting some tabs.Please help  me in this issue

### ISSUE THREAD

**Issue by roshankarwalkar1** [angular-ui/bootstrap#6122]
### Bug description:
The actual situation is I am using uib-tabs for tab structure in which my requirement is to add new tabs if user wants to add new tab(so need to activate newly added tab)  and if user wants to edit item then add that tab but condition is if its already opened then just activate the tab(same structure like we edit files in IDE).this is working fine but when adding and deleting tabs for long time makes it unstable and its active index becomes null.  
### My code in view is
 `<scrollable-tabset api="tabManager.scrlTabsApi" show-drop-down="false">
    <uib-tabset active="tabManager.activeTabIndex">
      <uib-tab  class="component-tab" ng-repeat="tab in tabManager.tabs"   ng-init="tabManager.activeTabIndex = $index" >
        <uib-tab-heading>
          {{tab.ShortName}}{{tabManager.activeTabIndex}}
          <a ng-click="tabManager.closeTab($index)" href=''>
            <i class="fa fa-times" aria-hidden="true"></i></a>
        </uib-tab-heading>
        <div class="tabContent">
          <ng-include src="tab.TemplatePath"/>
          <h3>   {{tab.active}}</h3>
        </div>
      </uib-tab>
    </uib-tabset>
  </scrollable-tabset>`

### Version of Angular, UIBS, and Bootstrap
I am using latest versions of all three components.
Angular:
my controller code is:
     `$scope.tabManager =new Object();
        $scope.tabManager.scrlTabsApi = {};
        $scope.tabManager.activeTabIndex = 0;
        $scope.tabManager.tabIndex=0;
        $scope.tabManager.tabs =[
            {
                ShortName:"Getting Started",
                TemplatePath:"views/globalresources/gettingstarted.html",
                tabIndex:$scope.tabManager.tabIndex,
                content:null
            }
        ];
        $scope.tabManager.reCalcScroll = function() {
            if($scope.tabManager.scrlTabsApi.doRecalculate) {
                $scope.tabManager.scrlTabsApi.doRecalculate();
            }
        };
        $scope.tabManager.scrollIntoView = function(arg) {
            if($scope.tabManager.scrlTabsApi.scrollTabIntoView) {
                $scope.tabManager.scrlTabsApi.scrollTabIntoView(arg)
            }
        };
        $scope.tabManager.closeTab = function(index){
            $scope.tabManager.tabs.splice(index, 1);
            console.log($scope.tabManager.tabs);
          //  $scope.tabManager.reCalcScroll();
        };
        $scope.hasSubResources = function (resource) {
            if(resource.subResources.length){
                return true;
            }
            return false;
        };
        $scope.addNewResource=function (resourceTitle,content) {
            var isNew=content? false:true;
            var tabIndex;
            isNew ? tabIndex =null: tabIndex=$scope.IsTabOpened(content);
             if(tabIndex){
                 console.log("found"+tabIndex);
                     $scope.tabManager.activeTabIndex = tabIndex;
                 $scope.tabManager.reCalcScroll();
                 $scope.tabManager.scrollIntoView();
                 return;
            }
            //verify that tab is already opened and set active tab index to the tab specific index
            //if tab is not opened already
            $scope.tabManager.tabIndex++;
            $scope.tabManager.tabs.push(
                {
                    ShortName:content? content.ShortName:'New '+resourceTitle,
                    TemplatePath:'views/globalresources/'+ angular.lowercase(resourceTitle)+'.html',
                    tabIndex:$scope.tabManager.tabIndex,
                    content:content
                }
            );
                console.log("created new one "+$scope.tabManager.activeTabIndex);
             //$scope.tabManager.activeTabIndex = $scope.tabManager.tabs.length;
            $scope.tabManager.reCalcScroll();
            $scope.tabManager.scrollIntoView();

        };
        $scope.IsTabOpened=function (resource) {
            for(var key in $scope.tabManager.tabs){
                if($scope.tabManager.tabs[key].content){
                    if(!$scope.tabManager.tabs[key].content.Id || !$scope.tabManager.tabs[key].content.ShortName){

                    }
                    if($scope.tabManager.tabs[key].content.Id===resource.Id && $scope.tabManager.tabs[key].content.ShortName===resource.ShortName){
                      return $scope.tabManager.tabs[key].tabIndex;
                    }
                }
            }
            return  null;
        };
        `

**Comment by bolemeus** [comment]
I think this is related to #6077

**Comment by icfantv** [comment]
Please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.
