### ISSUE TITLE
uibDatepickerPopup directive doesn't set init value

### ISSUE THREAD

**Issue by chatii2412** [angular-ui/bootstrap#6123]
### Bug description:
The initial value is not set if the element is like `input[type='button']` because uibDatepickerPopup only set value when date is selected: [popup.js#L215](https://github.com/angular-ui/bootstrap/blob/master/src/datepickerPopup/popup.js#L215)

[Plunker](https://plnkr.co/edit/gsPj6jiXDgKHQQqXpUfL?p=preview)

workaround 1: add `ngValue` diredtive [Plunker](https://plnkr.co/edit/kwknBc9PBb1QZvHrRQl9?p=preview)

workaround 2: create a custom directive [Plunker](https://plnkr.co/edit/mnGUqlgoDu3CBaHkXm9i?p=preview)
``` js
app.directive('uibDatepickerPopup', ($timeout) => {
  return {
    restrict: 'A',
    require: 'ngModel',
    link: (scope, element, attrs, ngModelController) => {
      if (attrs.type !== 'button') {
        return;
      }

      $timeout(() => {
        element.val(ngModelController.$viewValue);
      });
    }
  };
});
```

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/gsPj6jiXDgKHQQqXpUfL?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8 or lower

UIBS: 2.0.0 or lower

Bootstrap: 3.3.7 or lower

**Comment by wesleycho** [comment]
Why is it being used as an input type button? Is this to avoid allowing keyboard modification of the date? On first impression, this does not seem like a great usage of the datepicker.

**Comment by charms9** [comment]
I cannot seem to set the init-date dynamically, which had been working for us previously. Now if I try to set the init date to something like
// HTML
<uib-datepicker(ng-model="dateObj", init-date="initDate"...>

// and in the JS for my directive
$scope.initDate = new Date($scope.minDate.getTime()); // say the selected minDate is Nov 12, 2016

In this example, it loads the calendar to November, but the month change buttons don't respond unless you click on a date or click the month name button first. I'm not sure why this just started happening, as it had been working as I had it for many months, and we had not updated the app in quite a while.

**Comment by wesleycho** [comment]
I did an investigation, and the reason it does not render is because Angular does not set an `ngModelCtrl.$render` function for inputs with type `button`. See [here](https://plnkr.co/edit/U2nysdD81qEOOf4hseLB?p=preview) for the right way to get this to work.
