### ISSUE TITLE
Pagination ellipsis is not symmetric

### ISSUE THREAD

**Issue by macias** [angular-ui/bootstrap#6126]
### Bug description:

The look of the pagination should be symmetric from two perspectives -- counting from beginning, and from the end. This does not happen -- consider such code:

```
<ul uib-pagination total-items="6" ng-model="currentPage" 
  boundary-link-numbers="true" items-per-page="1" rotate="false"
  max-size="5"></ul>
```

Hit "1" and you will get:

Previous | 1 | 2 | 3 | 4 | 5 | 6 | Next

Now hit "6":

Previous | 1 | ... | 6 | Next

(a bit strange, because the cut is too deep).

My point is, I am not telling if it is OK to show range 1-6, or just 1 and 6, I am saying the look should be consistent (symmetric) in both cases. 

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/ur7YPA7XXPjOCKn2ZYOL?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.5

UIBS:
2.0.0

Bootstrap:
3.3.6

**Comment by icfantv** [comment]
@macias this doesn't sound like a bug, rather it sounds like a feature request:  namely, either some automatic way of the ability to control how many "cuts" are made.

**Comment by macias** [comment]
@icfantv , no, this is not the subject of my report. I am not asking to add extra customization, I am pointing out that current behaviour is inconsistent, because there is no symmetry.

Please, look this way, you have some pages, you are at the first page.

Then, you have the same pages, you are the the first page. Do you expect, that the widget all of the sudden will start making changes? Probably no, you expect the same look.

Me too :-). Just add "counting from the end" to the second scenario.

**Comment by icfantv** [comment]
I have no idea what you're proposing.  Define "symmetry" please.

**Comment by macias** [comment]
@icfantv , Symmetry -- you stand on some page, you see pages backward and forward, there is an ellipsis and so on. Now you turn the axis around ("<--") and if you select the page counting from the last you should get exactly the same setup.

It is comparison when you are iterating from 1 to N page, and from N page to 1 (backward). The pagination should behave in the same way, symmetric one.

Consider this (in the first line the first page is selected, in the second the last). In the first line we are iterating forward, in the second -- backward.

Prev | *1 | 2 | 3 | ... | 5 | Next
Prev | 1 | ... | 3 | 4 | *5 | Next

In the first line, we have 2 pages ahead, ellipsis, the last page.
In the second line (the axis is reversed) we have also 2 pages ahead, ellipsis, and the last page.

Thus we have correct, symmetric look -- no matter if you are iterating from 1 to 5, or from 5 to 1, the pagination behaves the same.

And consider this case (as before, in the first line 1 is selected, in the second 5 is):

Prev | *1 | 2 | 3 | ... | 5 | Next
Prev | 1 | 2 | 3 | 4 | *5 | Next

First line -- 2 pages ahead, ellipsis, last page.
Second line -- 3 pages ahead, no ellipsis, last page.

You see different descriptions because the behaviour is not symmetric.

More examples -- symmetric looks:
Prev | *1 | ... | 5 | Next
Prev | 1 | ... | *5 | Next

Prev | *1 | 2 | ... | 4 | 5 | Next
Prev | 1 | 2 | ... | 4 | *5 | Next

Prev | *1 | 2 | 3 | 4 | 5 | Next
Prev | 1 | 2 | 3 | 4 | *5 | Next

Prev | *1 | 2 | 3 | ... | 5 | Next
Prev | 1 | ... | 3 | 4 | *5 | Next

Those are NOT symmetric looks:
Prev | *1 | 2 | 3 | 4 | 5 | Next
Prev | 1 | ... | *5 | Next

Prev | *1 | 2 | 3 | ... | 5 | Next
Prev | 1 | 2 | 3 | 4 | *5 | Next

I hope it is clear now :-)

**Comment by wesleycho** [comment]
On first look, this looks like it is not intended - we should look into this and come up with a good solution. In this case, it probably shouldn't use the ellipses, but this seems to suggest that when the numbers are too big, an undesired application of the ellipses happens.

**Comment by wesleycho** [comment]
I did a further investigation and found this actually is a user error - see [here](http://plnkr.co/edit/0keMnabmhjJsOMwoJ3pi?p=preview). What was happening is that rotate expects a binding, not a string of the boolean.

**Comment by macias** [comment]
Ah, sorry and thank you at the same time! :-)
