### ISSUE TITLE
AngularJS: scrollable typeahead input field

### ISSUE THREAD

**Issue by elieobeid7** [angular-ui/bootstrap#6127]
My HTML

    <div class="form-group">
        <label class='control-label col-md-4' for='id_paymentCurrency'>{{'PAYMENT_CURRENCY' | translate}}</label>
        <div class='col-md-4'> 
            <div id="scrollable-dropdown-menu">
            <input type="text" class="form-control" data-trim-value="false" ng-trim="false" id ='id_paymentCurrency' ng-model="vm.data.paymentCurrency"  typeahead-append-to-body="true" required
            typeahead-editable="false"
            uib-typeahead="currency.code for currency in vm.getCurrencies($viewValue)"ng-disabled="disabled" />
        </div>   
      </div>  
    </div>  

My CSS

    #scrollable-dropdown-menu .tt-menu {
       max-height: 150px;
       overflow-y: auto;
     }

I'm using angular 1.x and typeahead that comes with angular-bootsrap, I can't make the scrollbar to appear.

**Comment by icfantv** [comment]
Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.

**Comment by elieobeid7** [comment]
@icfantv  I read the template and it says that if I have to prove that it is a bug, I need to reproduce the issue and give you a link so you can see it.

http://fiddle.jshell.net/H7LA4/46/

This is definitely a bug, either in the code, because a scrollable bar isn't shown, or in the documentation.

**Comment by elieobeid7** [comment]
@icfantv i was using the wrong css selector here's a working demo

http://fiddle.jshell.net/93w5dvh3/

and here's the question on stackoverflow, those guys helped me fix it

http://stackoverflow.com/questions/38636183/angularjs-scrollable-typeahead-input-field

You have a bug in the documentation.

https://twitter.github.io/typeahead.js/examples/

following the example won't work, the documentation needs to be fixed.

**Comment by icfantv** [comment]
That's not our documentation.  We use Twitter bootstrap CSS only, not the JS.  Our documentation is located [here](http://angular-ui.github.io/bootstrap).

**Comment by elieobeid7** [comment]
I read your documentation, didn't find anything about the scrolling bar so I assumed that I should do what I read on twitter's doc.  Should report that issue to someone or not?

**Comment by icfantv** [comment]
@elieobeid7 scrolling is nearly purely a CSS thing.  you need to look at the template used to format the typeahead dropdown and see how one might take care of scrolling if it's not already done for you.
