### ISSUE TITLE
uibDatePicker popup size

### ISSUE THREAD

**Issue by ctysingh** [angular-ui/bootstrap#6128]
The default size of the date popup is too larger. Is there a way to customize the popup size.
I am using angualr 1.5 & UI bottstrap version 1.3.2

**Comment by pkozlowski-opensource** [comment]
> Is there a way to customize the popup size.

Sure. You can override our default templates: http://stackoverflow.com/a/17677437/1418796

**Comment by ctysingh** [comment]
I do not see any reference to datePicker in the link above. Will that solution work for datepicker popup too

**Comment by icfantv** [comment]
@ctysingh you need to override the template used for the date picker.  This is done by essentially overriding the property key for the date picker in the `$templateCache`.  And _this_ is done by specifying the `template-url` property on [the date picker component](http://angular-ui.github.io/bootstrap/#/datepicker).
