### ISSUE TITLE
uib-popover does not trigger popover on mouse enter but before it used to work

### ISSUE THREAD

**Issue by iberodev** [angular-ui/bootstrap#6129]
### Bug description:
On mouse enter does not trigger the popup and before it was working. Currently trying to find out whether there is a conflict with the latest angular 1.5.8

### Link to minimally-working plunker that reproduces the issue:
I am using it in a standard way like this:
        
                       <span uib-popover="{{consignments.filterSelected.helpText}}"
                              popover-title="{{consignments.filterSelected.helpTitle}}"
                              popover-trigger="mouseenter" 
                              popover-append-to-body="true">
                            <i class="fa fa-question-circle fa-sm"> </i>
                        </span>

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: ??

Bootstrap: 2.0.0

**Comment by iberodev** [comment]
I have noticed that in the sample the popover-trigger has single quote. so after replacing my `popover-trigger="mouseenter" ` with popover-trigger="`mouseenter`"  it works fine.

Last week (still don't know what I have upgraded since then) the very same `popover-trigger="mousenter"` was working fine. But anyway, this is not a bug :)

**Comment by GutoMuniz** [comment]
llklçklklçk
