### ISSUE TITLE
SVGs in pagination buttons causing Javascript error in IE/Edge

### ISSUE THREAD

**Issue by jon64digital** [angular-ui/bootstrap#6130]
### Bug description:

In Microsoft browsers, using an svg inside an element that calls selectPage() in the pagination control causes the following error when the svg is clicked

TypeError: Object doesn't support property or method 'blur'

The reson for this is that SVGs don't have a blur() function in microsoft browsers and the following lines of code in the pagination directive are calling it....

233:    if (evt && evt.target) {
234:        evt.target.blur();
235:    }

line 233 should probably check that evt.target has a blur function before calling it?

I'm sorry, I would create a pull request but my Github skills are shockingly bad and it's very late here.

### Link to minimally-working plunker that reproduces the issue:

Hopefully this is too simple to require plunkr

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.7

UIBS: 1.3.2

Bootstrap: n/a

**Comment by icfantv** [comment]
Not sure how I feel about this.  I'm going to need to talk to the other team members first.

**Comment by wesleycho** [comment]
This would require checking for whether the element is an svg element and cache the presence of `SVGElement.prototype.blur`...this seems like a case where IE/Edge is in the wrong.

I am not sure how I feel about this either.

What were you using SVG for, the arrows?

**Comment by jon64digital** [comment]
Hi Guys,

Yes we use SVG for all of our icons and we were using an arrow icon on the next button.

I don't think you would need to check for SVG specifically, I think you just need to check to see whether event.target has a blur function before calling the blur function. Maybe like this....

```
if (evt && evt.target && evt.target.prototype.blur !== 'undefined') {
    evt.target.blur();
}
```

I actually solved this in my application without needing angular-ui to change, by doing this in my main angular file...

```
if (typeof SVGElement.prototype.blur == 'undefined') {
    SVGElement.prototype.blur = function(){};
}
```

**Comment by icfantv** [comment]
I'm ok with that as a workaround as opposed to putting something in our library.  Tbh, I don't recall anyone mentioning this issue before.

I think we can safely close this.
