### ISSUE TITLE
datepicker popup when min-date restrict to tomorrow onwards, if click today button it selects todays date.

### ISSUE THREAD

**Issue by vardhamanpatil** [angular-ui/bootstrap#6131]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.3.13

UIBS: 0.13.0

Bootstrap:  v3.3.4

**Comment by icfantv** [comment]
Please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.

You need a minimally working plunker.

**Comment by icfantv** [comment]
You also need to be using the most recent version of the library.  That version is really old.
