### ISSUE TITLE
Modal over Modal z-index error

### ISSUE THREAD

**Issue by rsantosdev** [angular-ui/bootstrap#6136]
### Bug description:
When simple opening modal over another modal, the z-index is not being resolved. I've manually resolved the z-index for now.

### Link to minimally-working plunker that reproduces the issue:
Click on `Open Me` then `Open another`
http://plnkr.co/edit/gDdUqc0rMcC1ackqyHAk?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8
UIBS: 2.0.0
Bootstrap: 3.3.6

**Comment by icfantv** [comment]
Please be respectful of our time by searching both open and closed issues before opening new issues as this is a duplicate.  We've released 2.0.1 which has a fix.

**Comment by rsantosdev** [comment]
@icfantv sorry for my mistake. I had searched yesterday and couldn't find any issue related to that. The only issue I found was a discussion regarding the option to override the base z-index that the code uses. Could you please refer the original issue for me?

And sorry again!

**Comment by sandcastle** [comment]
This is still an issue 😢
