### ISSUE TITLE
dateparser: baseDate is not a valid date in the Date Picker

### ISSUE THREAD

**Issue by rcholic** [angular-ui/bootstrap#6137]
### Bug description:

The versions of the relevant libraries are stated below, and I am running into the warning `dateparser: baseDate is not a valid date` when trying to display saved date retrieved from backend, and the date does *NOT* show up in the date picker input field. The format of the date are iso date string like  `2016-08-02T15:24:52.061Z` and I created a `Date` object by `new Date(2016-08-02T15:24:52.061Z)`, which is fed to the date picker.

My understanding is that the `baseDate` should be a `Date` object, but why do I still see such warning when the date is converted to `Date` type? 

**HTML for the date picker:**
```
<input type="text"
  uib-datepicker-popup="{{dateFormat}}" show-weeks="false"
  ng-model="expiration_date" is-open="opened_expiration"
  datepicker-options="dateOptions"
  ng-required="false" close-text="Close"
  ng-disabled="org._destroy"
  ng-click="openCalendar($event)" />
```
So what might be wrong and how do I fix it?

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.9

UIBS: 2.0.0

Bootstrap: 3.3.4

**Comment by icfantv** [comment]
Please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.

Without a minimally working plunker we cannot determine if this is a bug or you are requesting support.

**Comment by grindking** [comment]
Is there already an approach for this issue? Thank you

**Comment by sri-sankl** [comment]
Parse the response date string to date and update the model. 
`uibDateParser.parse(responseDateStr, dateformat);`
