### ISSUE TITLE
datepicker resets the timezone offset internally

### ISSUE THREAD

**Issue by weblets** [angular-ui/bootstrap#6138]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

Hello i have a bug which was triggered because I tried to let the date picker show and accept dates from a different timezone. With a decorator and a timezone set to GMT+2 and i was able to pull this off, however one last issue remained. The today day was always marked as local timezone day not the one from the different timezone.

The problem was following code in the date picker:

 ` 
  // popup element used to display calendar
    popupEl = angular.element('<div uib-datepicker-popup-wrap><div uib-datepicker></div></div>');
    if (ngModelOptions) {
      timezone = ngModelOptions.timezone;
      $scope.ngModelOptions = angular.copy(ngModelOptions);
     //problematic code
      $scope.ngModelOptions.timezone = null;
      if ($scope.ngModelOptions.updateOnDefault === true) {
        $scope.ngModelOptions.updateOn = $scope.ngModelOptions.updateOn ?
          $scope.ngModelOptions.updateOn + ' default' : 'default';
      }`

If I remove the offending **$scope.ngModelOptions.timezone = null;** things start to work for me, the date is displayed correctly for the other timezone (aka 3th 11pm new york time defaults to a 4th being displayed as today for the target GMT+2)

However this = null must be there with a reason, so I am not sure if something is broken by removing that line. $scope.ngModelOptions.timezone however is used in the today calculation later so it should be enabled at that stage.

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by icfantv** [comment]
Please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.

You need a minimally working plunker for us to investigate this.
