### ISSUE TITLE
bug(typeahead): ignores maxlength on select

### ISSUE THREAD

**Issue by thnk2wn** [angular-ui/bootstrap#614]
If a typeahead has a maxLength, selecting the item in the list allows the maxLength to be bypassed. I tried both maxLength and ng-maxlength individually and together.

I made a quick and dirty workaround for our use case inside the typeahead directive of ui-bootstrap-tpls-0.3.0.js marked with a // CUSTOM comment as below but there's probably a cleaner way to do this going forward. I'd like to request some way to instruct the typeahead directive to truncate any suggestions/matches at maxlength characters upon selecting an item.

    scope.select = function (activeIdx) {
          //called from within the $digest() cycle
        var locals = {};
        var model, item;
        
        // CUSTOM - maxLength:
        var el = element[0];
        var value = scope.matches[activeIdx].model;
        if (el && el.maxLength && value && value.length > el.maxLength) {
            value = value.substr(0, el.maxLength);
        }
        locals[parserResult.itemName] = item = selected = value;
 
        model = parserResult.modelMapper(scope, locals);
 
        modelCtrl.$setViewValue(model);
        modelCtrl.$render();
 
        onSelectCallback(scope, {
            $item: item,
            $model: model,
            $label: parserResult.viewMapper(scope, locals)
        });
      };

More details here:
https://groups.google.com/forum/#!msg/angular-ui/ZZQug6nRLwQ/biLV1gFWDxUJ

**Comment by Foxandxss** [comment]
This issue is over two years. If you feel like this is still relevant, please create a new issue with a plunker using latest version.

Thanks.
