### ISSUE TITLE
controllerAs: "vm"

### ISSUE THREAD

**Issue by coscallis** [angular-ui/bootstrap#6141]
Given that $scope is now considered a bad (or at least 'less than good') practice...how about revising your examples to use the controllerAs:"vm" syntax... 

yes, mostly it is easy to figure...but sometimes it can be deceptive as to how to adapt...particularly if you are just adopting the controllerAs practice.

**Comment by icfantv** [comment]
@coscallis in a perfect world we would do a lot of things but the primary issue is that we are all volunteers and we simply don't have the time to do everything.

Feel free to submit a PR if you feel this is worth doing.
