### ISSUE TITLE
Template for directive 'uibTabset' must have exactly one root element.

### ISSUE THREAD

**Issue by Zeshan316** [angular-ui/bootstrap#6148]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I am using angular.min.js(1.5.3), ui bootstrap(1.3.3) with angular-ui-router(0.2.10) and when i go from one link to another i used to clear cache using "template cache" service of angular so then this error triggers, i searched a lot over net but nothing special i found that solve my problem can you help to resolve.

"Error: [$compile:tplrt] Template for directive 'uibTabset' must have exactly one root element. uib/template/tabs/tabset.html"
### Version of Angular, UIBS, and Bootstrap

Angular:1.5.3

UIBS:

Bootstrap:1.3.3

**Comment by pkozlowski-opensource** [comment]
Please provide a plunker with a reproduce scenario as requested in https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by matthiasdailey-ccri** [comment]
Does your template have more than one root element?

**Comment by Zeshan316** [comment]
@matthiasdailey-ccri my template uses uib-tabset directive it returns some kind of html which will replace that html in my template so i think its not on my end but on ui bootstrap.
I have also tested template cache on those pages which do not have uibtabset directive and those working fine.

**Comment by pkozlowski-opensource** [comment]
> so i think its not on my end but on ui bootstrap.

Please prove it with a plunker, otherwise it is not actionable and will be closed. See the link I've provided for more details on why we require minimal reproduce scenarios for every issue report.

**Comment by Zeshan316** [comment]
@pkozlowski-opensource ok i will debug again my code(already did it), if show same result i will add plunker, its little bit difficult to create plunker because app using lot of files angular,angular bootstrap,jquery and some others.

**Comment by icfantv** [comment]
@zeshan316, just a note that OSS maintainers aren't really receptive to that line, "I can't create a plunker because..."  If you cannot make time to create a minimally reproducible plunker, how can you expect us to be able to put forth the time and effort to debug someone vague?  We are all volunteers and simply cannot chase everything down.

**Comment by mrbacay** [comment]
I'm getting the same issue using a custom template for accordion groups, and I noticed that `accordion-group.html` has two root elements. I was just wondering why that's allowed, and mine isn't.

**Comment by Zeshan316** [comment]
This solution worked on
$templateCache.remove('url of the partial/view');
