### ISSUE TITLE
Radio buttons does not work with ng-repeat

### ISSUE THREAD

**Issue by vkrizan** [angular-ui/bootstrap#6150]
### Bug description:

Radio buttons rendered using `ng-repeat` does not work properly.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/V0HEvxXlhw3fvsL94x7U?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.5

UIBS: N/A

Bootstrap: 3.3.6

Thank you!

**Comment by icfantv** [comment]
I'm not going to say this is not a bug, but something definitely doesn't feel right with your plunker.  I just can't put my finger on it.

**Comment by pkozlowski-opensource** [comment]
It is a scoping issue. Keep in mind that `ngRepeat` is creating a new scope. Potential "fix": http://plnkr.co/edit/Kixp5OtZbo07xyzWEwIH?p=preview

**Comment by vkrizan** [comment]
Thank you @pkozlowski-opensource. It is certainly a scoping issue. It also works well with controller bound variable.
