### ISSUE TITLE
angular ui bootstrap 

### ISSUE THREAD

**Issue by pablobvch** [angular-ui/bootstrap#6155]
Hello Everyone,,
We have any problems with the version angular-ui bootstrap.
In the version 1.6.6. our app is working well, but when we use the new - 2.0.1- the paginator uib paginator, get hidden.
Any idea?
Thanks in advance,
Pablo

**Comment by wesleycho** [comment]
We cannot help without a reproduction - see https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md .

**Comment by RobHudson72** [comment]
I checked the documentation, and it looks like the markup for the tag has changed from `<uib-pagination></uib-pagination` to `<ul uib-pagination></ul>`

Changing the tags worked for me.

**Comment by pablobvch** [comment]
Thank you RobHudson72. It works very well.
