### ISSUE TITLE
Initializing model with date string fails to display viewValue

### ISSUE THREAD

**Issue by neilsoult** [angular-ui/bootstrap#6156]
### Bug description:
if ngModel value is initiated with date string (say, from a DB), input viewValue fails to display default value when using `ng-model-options="{ timezone: 'UTC' }"` this is because the `convertTimezoneToLocal` method in dateparser does not make sure the first parameter (`date`) is a valid date string. This could easily be solved by setting parameter value to `new Date()`, such as
```
function convertTimezoneToLocal(date, timezone, reverse) {
    date = new Date(date); // this is the code addition
    reverse = reverse ? -1 : 1;
    var dateTimezoneOffset = date.getTimezoneOffset();
    var timezoneOffset = timezoneToOffset(timezone, dateTimezoneOffset);
    return addDateMinutes(date, reverse * (timezoneOffset - dateTimezoneOffset));
  }
```
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/g2Pjtvq0Z531SHDwXI6l?p=preview
### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.6
UIBS:
1.3.3
Bootstrap:
3.1.1

**Comment by neilsoult** [comment]
here is the same plunkr with the `ng-model-options` removed: http://plnkr.co/edit/wSVVpNpFeQ0F5LdZtUsF?p=preview

**Comment by wesleycho** [comment]
We officially do not support using the string as the model - I highly recommend it be converted to a date object beforehand.

**Comment by icfantv** [comment]
@neilsoult, this is documented and has been discussed previously in an insanely large number of issues.  Per the issue template and our project documentation, please be respectful of our time by adhering to said information.  Thanks.

**Comment by neilsoult** [comment]
Yea, maybe you failed to see me closing the issue. Sorry to be an insane waste of your time and energy.
