### ISSUE TITLE
Tooltip example plunkr bug (fixed plunkr provided)

### ISSUE THREAD

**Issue by speyou** [angular-ui/bootstrap#6157]
Hello,

The plunkr example for tooltip is off when it comes to uib-tooltip-html with a string.

`<a href="#" uib-tooltip-html="'static. {{dynamicTooltipText}}. <b>bold.</b>'">inline string</a>`

The plunkr doesn't provide safe html or sanitizing so we have the following error: 
` [$sce:unsafe] Attempting to use an unsafe value in a safe context.`

I have fixed the issue in this plunkr: http://plnkr.co/edit/V6xyTmtGhQI5md7x8OQA?p=preview
by adding ngSanitize to the example.

Thanks for the library and have a nice day!

**Comment by wesleycho** [comment]
Thanks for this catch - I'll take a look at fixing this shortly, looks like the location to change is not obvious.
