### ISSUE TITLE
Default template for typeahead dropdown

### ISSUE THREAD

**Issue by jfain189** [angular-ui/bootstrap#6158]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
Hi,

I was just wondering what the default template for the typeahead dropdown menu is.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 2.0.1

Bootstrap:

**Comment by icfantv** [comment]
@jfain189 all the templates are located in in the top-level `template` directory for this project.  In the case for typeahead, that would be [here](https://github.com/angular-ui/bootstrap/tree/master/template/typeahead).

**Comment by icfantv** [comment]
And to override the template, just specify the `typeahead-template-url` property on the `uib-typeahead` element directive.
