### ISSUE TITLE
Collspan - width: "inherit" breaks grid column width

### ISSUE THREAD

**Issue by zucker-rdrg** [angular-ui/bootstrap#6163]
Commit https://github.com/angular-ui/bootstrap/commit/1ec0997 add `width: 'inherit',` to element but it breaks bootstrap grid columns width in case like this:

issue - angular-ui-bootstrap (2.0.2): http://plnkr.co/edit/C6i9Fz0KokJzTKxrNQHG?p=preview
no issue - angular-ui-bootstrap (1.3.2): http://plnkr.co/edit/BbIYvSaWbMxBzyuESeEH?p=preview

**Comment by wesleycho** [comment]
Hmm, as far as I can tell, the inherit part shouldn't even be necessary. Indeed, removing that area fixes this, as seen [here](http://plnkr.co/edit/4lEUVeXkyYrLtBlCc3kL?p=preview).

Will file a PR shortly.
