### ISSUE TITLE
Why restrict A?

### ISSUE THREAD

**Issue by kollors** [angular-ui/bootstrap#6167]
Why are you using the directive as an attribute? I think the same uibPager it would be logical to make the component or component directive, and its parameters of its attributes. And would like to see @ngdoc=) Thanks.

**Comment by icfantv** [comment]
@kollors because that's how it was developed.  we are targeting 3.0 for forcing angular 1.5+ support and can talk about conversion to components then (and then restricting to elements).

**Comment by icfantv** [comment]
I should mention that we would do this for ALL UIBS components, not just pager....if it wasn't clear before.

**Comment by wesleycho** [comment]
The reason it is restrict 'A' is to avoid potentially larger breaking changes due to the prior usage of `replace: true`. `restrict: 'A'` allows parity to be maintained, but `restrict: 'E'` adds an extra DOM element, which affects CSS.

**Comment by kollors** [comment]
Thanks
