### ISSUE TITLE
datepickerPopup popup-placement attribute not positioning as expected

### ISSUE THREAD

**Issue by jpmitche11** [angular-ui/bootstrap#6168]
The default popup is positioned as  left:0.   I would expect to be able to set right: 0 as an option.

Tried the new popup-placement attribute set to "auto bottom-right", but this position the element as I would expect. Calculates a new left position instead of simply setting right: 0.

Plunker: https://plnkr.co/edit/jiIRnQ4tcVyo59mxx2B4?p=preview

Screenshot - notice how the picker is not aligned with the edge of the input group:

![image](https://cloud.githubusercontent.com/assets/701676/17752983/48d0c8bc-649c-11e6-9851-57a893602e6c.png)

Angular:
1.5.5
UIBS:
2.0.2
Bootstrap:
3.3.6

**Comment by icfantv** [comment]
@jpmitche11 this is working fine [on our demo site](http://angular-ui.github.io/bootstrap/#/datepickerPopup).  without investigating further, i suspect you have a CSS issue in your plunker.

**Comment by jpmitche11** [comment]
Does the demo have any examples that use the popup-placement attribute?  My plunker is just a modified/trimmed down copy of the demo.  The issue is that the picker is aligned with the right side of the input element, instead of the right side of the toggle button.

**Comment by icfantv** [comment]
Ahhhh.  I understand.  I'm on my phone at the moment, so can't check, but what happens if you remove the BS form group stuff?  I suspect we don't account for the addon because we have no way of knowing if it's there.  @robjacobs, does this sound reasonable?

**Comment by wesleycho** [comment]
The problem here isn't with the library - it is properly aligning to the right. What is happening in the Plunker is that the button is not absolutely positioned over the input, but to the right of the input.
