### ISSUE TITLE
$uibModal works only once

### ISSUE THREAD

**Issue by HaakonL** [angular-ui/bootstrap#6172]
I have created a minimalistic plunker that shows the problem. But in short words, using ui-bootstrap to show a modal works only once. To reproduce: 

1) show a modal using ui-sref on a div and $uibModal.open()
2) close the modal
3) click the same div again.

Expected: Modal should open again.
Actual: Nothing happens

http://plnkr.co/edit/DC89llU7G8VWqUVxdD5a?p=info

**Comment by wesleycho** [comment]
There is a mistake in your code - see the `finally` block after the `$uibModal.open` call [here](http://plnkr.co/edit/LNfKzxrzQgtxWy7IIwQs?p=preview) for the correct usage.

**Comment by HaakonL** [comment]
Jeez and omg and all that. Sorry. And thank you!
