### ISSUE TITLE
close popover programmatically & only one popover open at the time

### ISSUE THREAD

**Issue by fxck** [angular-ui/bootstrap#618]
is there any way to do these? I would like to have a "x" button inside the popover to close it and I would want all other popover to be closed when I open a new one..

**Comment by jesselpalmer** [comment]
+1

**Comment by smilelizy** [comment]
@vchatterji  
Thanks for the hacks there.

$('body').on('click', function (e) {
   $('*[popover]').each(function () {
                //Only do this for all popovers other than the current one that cause this event
                if (!($(this).is(e.target) || $(this).has(e.target).length > 0) 
                     && $(this).siblings('.popover').length !== 0 
                     && $(this).siblings('.popover').has(e.target).length === 0)                  
                {
                     //Remove the popover element from the DOM          
                     $(this).siblings('.popover').remove();
                     //Set the state of the popover in the scope to reflect this          
                     angular.element(this).scope().tt_isOpen = false;
                }
    });
});

In your solution here, I found everything works fine, except that : angular.element(this).scope().tt_isOpen = false; 
does not see to do anything.

when I tracing the scope(), there is no property called tt_isOpen, not sure if it because something has changed over the last year.

Now if your set trigger map as : click -> click,  you open the popover by clicking, and click somewhere else on the screen does close it (removing it from the DOM I believe) , however the state of of popover remain : isOpen = true. This results that next time you'd click twice to make the popover appear again. 

I'm not able to figure how to fix this.
for now I just can think of configuring the trigger as : click -> never 

Hope there is a better way of doing this.

**Comment by thetaylor82** [comment]
Infuriating problem that should have been fixed long ago. On 0.12.1 I'm completely stuck as I have no access to tt_isOpen (or isOpen). Why can't I just trigger a close on the elements?

**Comment by tmundt** [comment]
+1

2015-04-23 11:46 GMT+02:00 thetaylor82 <notifications@github.com>:

**Comment by tompi** [comment]
tt_isOpen was removed, they use an "isOpen" attribute and I believe it's not in the same scope as before, anyway, lot's of trial and error leed us to this code which works unless you use the "append to body" attribute... (call hidePopovers  from your global click-handler))

var hidePopover = function(element) {
    //Set the state of the popover in the scope to reflect this
    var elementScope = angular.element($(element).siblings('.popover')).scope().$parent;
    elementScope.isOpen = false;
    elementScope.$apply();
    //Remove the popover element from the DOM
    $(element).siblings('.popover').remove();
};
var hidePopovers = function(e) {
    $('*[popover]').each(function() {
        //Only do this for all popovers other than the current one that cause this event,
        if (!($(this).is(e.target) || $(this).has(e.target).length > 0) && $(this).siblings('.popover').length !==
            0 && $(this).siblings('.popover').has(e.target).length === 0) {
            hidePopover(this);
        }
    });
};

**Comment by lpsBetty** [comment]
hmm I am using the new ``popover-template`` directive, how can I achieve this, my current code:

````
  $('body').on('click', function (e) {
    $('*[popover-template]').each(function () {
      var $this = angular.element(this);
      //Only do this for all popovers other than the current one that cause this event
      if (!($this.is(e.target) || $this.has(e.target).length > 0) && $this.siblings('.popover').length !== 0 && $this.siblings('.popover').has(e.target).length === 0) {
        //Set the state of the popover in the scope to reflect this
        console.log($this.scope()); // => undefined
        console.log($this.siblings('.popover')).scope()); // => undefined
        // var elementScope = angular.element($this.siblings('.popover')).scope().$parent;
        // elementScope.isOpen = false;
        // elementScope.$apply();
        //Remove the popover element from the DOM
        $this.siblings('.popover').remove();
      }
    });
  });
````

**Comment by bgold0** [comment]
Any fixes if I use append to body? None of these seems to be working for me.

**Comment by windmaomao** [comment]
will this work ? http://stackoverflow.com/questions/20939754/good-way-to-dynamically-open-close-a-popover-or-tooltip-using-angular-based

**Comment by bitflower** [comment]
@windmaomao it works like a charm. Unless you want to use a template. I'm investigating here right now.

**Comment by basco-johnkevin** [comment]
+1

**Comment by mattdisipio** [comment]
+1

**Comment by Elijen** [comment]
As need for more control over popovers is quite common and there seem to be no progress on adding it to angular-ui repo I created a mini directive that can be used to open/close popovers programmatically: https://github.com/Elijen/angular-popover-toggle

Suggestions are welcome :)

**Comment by billyshena** [comment]
Hello guys, any news about closing popovers on clicking outside?
Code examples do not seems to work using popover-template.
@IpsBetty: did you find any solution to make it work with popover-template?


Best,

**Comment by Elijen** [comment]
@billyshena Closing on clicking outside is little bit more complicated as you will most likely need to add `ng-click` on the body element and do `$event.stopPropagation` where you don't want to hide the popover (e.g. use clicks inside).

Here is a plunkr: http://plnkr.co/edit/kU9D8Av0fJI76wT8YlHa?p=preview

**Comment by lpsBetty** [comment]
@billyshena sorry, I use the same code as I pasted above, It just works for the first time, but not for the second time ... :/

**Comment by billyshena** [comment]
@Elijen: I've used your plunkr as an example and it seems to work (even tho it's kind of tricky). Thanks for your code sample !
@IpsBetty: Yeah I had the same issue aswell

Are there gonna be any updates on this repo about implementing additional features to the popover?
Best,

**Comment by Elijen** [comment]
@billyshena The issue #590 is without any response from angular-ui team for 1 year and half. So I doubt there will be any progress on this. That's why I created the bower package.

**Comment by mikuatapex** [comment]
it is solved by adding  data-trigger="focus"

**Comment by billyshena** [comment]
@Elijen : Mhh I see, thanks again then !
@mikuatapex : I need to be able to click inside the opened popup, which won't work using your solution I think.

**Comment by ruslan40** [comment]
@Elijen Wow. You are an absolute genius! Thanks so much for this.

I spend like two days on this issue (having built the rest of my app in 5). It is mind-blowing how something this trivial could be so ridiculously complicated.

**Comment by dnshah1991** [comment]
yes this is possible 
just add this code

$(".popover").each(function(index){
        		
        		 $(this).not('#' + $(Element).attr('id')).popover('hide'); 
// Element is current element on which  popover will open.
        		
        	});

**Comment by tkalfigo** [comment]
This might be of help: https://github.com/Elijen/angular-popover-toggle

**Comment by Hrafnkellos** [comment]
Here is another implementation of Elijen's directive, ng-click on body was not working well for me so i had to change it a little.

﻿(function (angular) {
        'use strict';

        var POPOVER_SHOW = 'popoverToggleShow';
        var POPOVER_HIDE = 'popoverToggleHide';

        var module = angular.module('popoverToggle', ['ui.bootstrap']);

        module.config(['$tooltipProvider', function ($tooltipProvider) {
            var triggers = {};
            triggers[POPOVER_SHOW] = POPOVER_HIDE;

            $tooltipProvider.setTriggers(triggers);
        }]);

        module.directive('popoverToggle', ['$rootScope', '$timeout', '$window', function ($rootScope, $timeout, $window) {
            return {
                restrict: 'A',
                link: link
            };

            function link($scope, $element, $attrs) {
                $attrs.popoverTrigger = POPOVER_SHOW;

                // To check if we are clicking an element with a popover class
                // http://stackoverflow.com/questions/16863917/check-if-class-exists-somewhere-in-parent-vanilla-js
                var hasSomeParentTheClass = function hasSomeParentTheClass(element, classname) {
                    if (element.className && element.className.split(' ').indexOf(classname) >= 0) return true;
                    return element.parentNode && hasSomeParentTheClass(element.parentNode, classname);
                }

                // To hide the popover and initialise values again.
                var hidePopover = function hidePopover() {
                    $scope.open = false;
                    if ($window.onclick) {
                        $window.onclick = null;
                    }
                    $element.triggerHandler(POPOVER_HIDE);
                    $scope.$apply(); //--> trigger digest cycle and make angular aware. 
                }

                $scope.$watch('open', function (newValue) {
                    $timeout(function () {
                        if (newValue) {
                            $element.triggerHandler(POPOVER_SHOW);

                            $window.onclick = function ($event) {
                                var clickedElement = $event.target;
                                if (!clickedElement) return; // Element exists

                                var clickedOnTheElement = hasSomeParentTheClass(clickedElement, 'popover'); // Element parent has popover class

                                if (!clickedOnTheElement) {
                                    hidePopover();
                                    return;
                                }
                            };

                        } else {
                            hidePopover();
                        }
                    });
                })
            }
        }]);

    })(angular);

**Comment by tobiasmuecksch** [comment]
+1

**Comment by icfantv** [comment]
Please do not +1 issues. It doesn't add anything to the discussion and clutters the thread. Thank you.

**Comment by smohamali** [comment]
{% gist d84d95dfd09fde410be1 %}

**Comment by smohamali** [comment]
My one liner solution: https://gist.github.com/smohamali/d84d95dfd09fde410be1

**Comment by icfantv** [comment]
@smohamali, we have the `*-is-open` properties now.  Instructions are in the docs.

**Comment by smohamali** [comment]
@icfantv Nope, I missed that in the documentation. Even easier. Thanks for the tip :+1:

**Comment by icfantv** [comment]
No worries.  It's always a good idea to carefully check both that and the changelog to see what's present and what's changed.  Especially in two years.  That's an eternity in OSS.

**Comment by danielimatics** [comment]
To open only one popover at a time: ` popover-trigger="outsideClick"`

**Comment by MikhailRoot** [comment]
currently popover-trigger is expression so `popover-trigger="'outsideClick'"` this is working with current version.

**Comment by r3wt** [comment]
@MikhailRoot thank you for that.

**Comment by ak868308** [comment]
somehow i created one example for my need. i used this code:
$('.btn').popover();

$('.btn').on('click', function (e) {
    $('.btn').not(this).popover('hide');
});

**Comment by SebSob** [comment]
To programatically close the popover you can use this dirty hack:

`angular.element(document.querySelector('body')).click();`

**Comment by IshanFx** [comment]
What I did was I set the tooltip-trigger="'none'" and change the tooltip-is-open="true" value based on the click.
