### ISSUE TITLE
Error when datepicker-popup is opened

### ISSUE THREAD

**Issue by bhaskar-fealti** [angular-ui/bootstrap#6184]
There is an exception when $locale.DATETIME_FORMATS.FIRSTDAYOFWEEK is not defined. I saw the following error in datepicker-popup when I expanded the popup and the week numbers are not rendered due to the following error.
```
TypeError: Cannot read property 'date' of undefined
    at _refreshView (ui-bootstrap-tpls-2.1.0.js:1847:66)
```
The root cause is the following line at 1520 which causes the value to be set to NaN:
`self.startingDay = ($locale.DATETIME_FORMATS.FIRSTDAYOFWEEK + 8) % 7;
`

I believe it should be something like this:
`          self.startingDay = $locale.DATETIME_FORMATS.FIRSTDAYOFWEEK == null ? 0
                                    : ($locale.DATETIME_FORMATS.FIRSTDAYOFWEEK + 8) % 7;
`

**Comment by pkozlowski-opensource** [comment]
> There is an exception when $locale.DATETIME_FORMATS.FIRSTDAYOFWEEK is not defined.

But this should never be the case, unless you are using a _very_ old Angular version. Please provide a reproduce scenario, see: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by bhaskar-fealti** [comment]
Opps!!! You are right. Though I am using angular 1.5.7, I had a reference to an old angular-locale_en.js that I did not notice and was causing the conflict. 

Sorry about that.
