### ISSUE TITLE
Datepicker 1.3.3 validation issue

### ISSUE THREAD

**Issue by elieobeid7** [angular-ui/bootstrap#6185]
I'm using datepicker from angular ui 1.3.3 from [maven repo] (https://mvnrepository.com/artifact/org.webjars/angular-ui-bootstrap/1.3.3), And AngularJs 1.x. if the user enters a wrong or invalid input, no error is displayed, the field is not cleared and nothing happens. Of course the the input won't be accepted when the user submits the form but there's no message or anything.

Is it by default? Should I use ng-messages? Is it a bug? Is it fixed by later releases? I see on github it's now 2.1.0 while I'm still using 1.3.3 from maven repos.

**Comment by wesleycho** [comment]
Please post a reproduction - you can grab a Plunker template from the homepage.

**Comment by elieobeid7** [comment]
that issue was solved a long time ago, you can close it if you want.

https://stackoverflow.com/questions/39053632/angular-ui-bootstrap-datepicket-input-validation
