### ISSUE TITLE
Accordion animation stopped working

### ISSUE THREAD

**Issue by zavital** [angular-ui/bootstrap#6194]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

just upgraded from 0.14.3 to  2.1.1.

on 0.14.3 when  i clicked an accordion group it would slide nicely down. now it is just hang for a second, and instantly opens (without animation). this happens also on the demo  page - https://angular-ui.github.io/bootstrap/#/accordion

### Link to minimally-working plunker that reproduces the issue:
just putting the demo plunker... 

https://plnkr.co/edit/exfn8D6swHm1zJY63Ier?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:1.5.8

UIBS:2.1.1

Bootstrap:3.3.7

**Comment by wesleycho** [comment]
Yep, looks like there's a regression here - will investigate what happened here.

**Comment by zavital** [comment]
thanks :)
