### ISSUE TITLE
Pagination example doesn't change the page URL

### ISSUE THREAD

**Issue by tobireif** [angular-ui/bootstrap#620]
When I go to http://angular-ui.github.io/bootstrap/#/pagination and open the Plunkr example, then view the content of the frame (in order to view the demo page itself), the URL of the page (eg http://run.plnkr.co/sfpGiAuFnlMXxoMJ/ ) doesn't get updated with each pagination step.

**Comment by phuyem** [comment]
here is my clumsy code:
 
   .controller(    'BlabalCtrl',
            ..........
            function getPageFromHashString(hash){
                if (!hash){
                    return 1;
                }else if (hash.indexOf('page=') <0){
                    return 1;
                }else{
                    return hash.substring(5, hash.length);
                }

            }
 
            

            $scope.pageChanged = function (currentPage) {
                $scope.currentPage = currentPage;
                $scope.loadItems(currentPage);
                $location.hash('page='+currentPage);
            };


            $scope.$on('$locationChangeSuccess', function (e, newUrl, oldUrl) {
                if (newUrl== null || oldUrl == null || newUrl==oldUrl)
                        return;
                var page = getPageFromHashString($location.hash());
                if (page == $scope.currentPage)
                    return;
                else{
                    $scope.pageChanged(page);
                }
            });

            $scope.currentPage = getPageFromHashString($location.hash());


It supports browser's back/forward.

**Comment by neminsuksen** [comment]
Thanks KieranDotCo, It work for me.

**Comment by mmileon** [comment]
hi KieranDotCo, Thanks :) its for me

**Comment by JoeyKo** [comment]
With ui-router, using $stateParams instead of $routeParams
