### ISSUE TITLE
uibModal Component feature initiates twice

### ISSUE THREAD

**Issue by AlDrag** [angular-ui/bootstrap#6201]
The new component feature for uibModal initiates twice. I modified a version of your uibModal Example plunkr to demonstrate it. For the Component Modal, the alert will popup twice.
https://plnkr.co/edit/QW9288

**Comment by navarroaxel** [comment]
Hey @wesleycho, since this issue beaks some features, please release the version 2.1.3 as soon as you can

i.e. I experienced the bug using the filterFilter in a ngOptions directive.

Thanks in advance!

**Comment by wesleycho** [comment]
Sure, I will release shortly.
