### ISSUE TITLE
2.1.2 popover-trigger is ignored

### ISSUE THREAD

**Issue by Rendrik** [angular-ui/bootstrap#6204]
### Bug description:
After upgrading to 2.1.2, all popover-triggers ceased to work (they default to click).
See the example below where the trigger mouseenter no longer works, unless you revert to an older version.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/xin76XxBWIIoVbi446d9?p=info

**Comment by wesleycho** [comment]
This works - see [here](http://plnkr.co/edit/GtIoG1jhxfdDOibUiT0y?p=preview)
