### ISSUE TITLE
How to Remove HH MM PlaceHolder. Or add 00 00 on time-picker 

### ISSUE THREAD

**Issue by amitjain24524** [angular-ui/bootstrap#6207]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

How to remove placeholder (HH MM). I want to empty box without change template lib file.

**Comment by wesleycho** [comment]
You can override the timepicker template if you want to use a different placeholder.

Closing as a support issue.
