### ISSUE TITLE
Progress bar not rendering with dynamic values which coming from api response

### ISSUE THREAD

**Issue by xsandips** [angular-ui/bootstrap#6211]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug
