### ISSUE TITLE
outsideClick trigger does not hide popover when clicked outside

### ISSUE THREAD

**Issue by bukharov** [angular-ui/bootstrap#6212]
### Bug description:

After updating from 1.3.3 to 2.0.1 I noticed that outsideClick trigger does not hide the popover anymore when clicked on something outside of it. 

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/GW18A5P9Rm3aNvIgzQ5C

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8
UIBS: 2.1.3
Bootstrap: 3.3.6

**Comment by thnt** [comment]
You should change `popover-trigger="outsideClick"` to `popover-trigger="'outsideClick'"`

**Comment by bukharov** [comment]
Oops, thank you very much.

**Comment by chrismbarr** [comment]
That solution works, but that is really lame.  It's not clear at all from the docs that a literal string needs to be passed in.

**Comment by arajay** [comment]
i think this is because you can declare multiple triggers, i.e. `tooltip-trigger=" 'mouseenter' 'outsideClick' "`
