### ISSUE TITLE
Limit Angular UI-Bootstrap Typeahead to on-select and object property

### ISSUE THREAD

**Issue by kira510** [angular-ui/bootstrap#6222]
@pkozlowski-opensource 

Please see the code snippet below. 

`<input type="text" class="topic_select" id="selectTopic" ng-model="topicsPopulate" uib-typeahead="topic as topic.name for topic in topics|filter:{name:$viewValue}:startsWith" typeahead-show-hint="true" typeahead-min-length="0" placeholder="Select a Topic" typeahead-on-select="TopicChanged(topicsPopulate)">`

The startsWith function basically filters based on the starting letters of each topic . But i have a small problem here, i am still able to type characters even after selecting a topic, how do i stop this from happening? Meaning to say that, i should not be able to type any other characters apart from the filtered names and i should not be able to add new character after onselect but i am able to remove the topic and type for another topic. 
Plus i must be able to type only those letters present in topic name, for ex: when i type EC, the dropdown shows eclipse as an option, and i must not be able to type ECG, instead i have to limit my typing to the letters present in that topic name. I have posted this on Stackoverflow, http://stackoverflow.com/questions/39342584/limit-angular-ui-bootstrap-typeahead-to-on-select-and-object-property

**Comment by pkozlowski-opensource** [comment]
>  I have posted this on Stackoverflow, http://stackoverflow.com/questions/39342584/limit-angular-ui-bootstrap-typeahead-to-on-select-and-object-property

This is the right forum for those types of questions, no need to cross-post here.

**Comment by kira510** [comment]
Hello @pkozlowski-opensource 
I don't see any update on http://stackoverflow.com/questions/39342584/limit-angular-ui-bootstrap-typeahead-to-on-select-and-object-property
