### ISSUE TITLE
popover-trigger="'mouseenter'" working only with quote

### ISSUE THREAD

**Issue by infrarosso78** [angular-ui/bootstrap#6223]
In the documentation you suggest to use popover-trigger="'mouseenter'" with quote AND single quote. After a lot of troubleshooting I realized in my code it worked only without inner single quote:
popover-trigger="mouseenter"

`<button uib-popover="Click to add the {{tag}} tag to the body text" popover-trigger="mouseenter" class="btn btn-primary btn-xs" ng-click="someFunction()" type="button">{{tag}}</button>`

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 1.3.3 

Bootstrap:v3.3.7

**Comment by Ludevik** [comment]
Are you showing docs for the version you are using? The popover trigger changed in current major version. 
If you want to display docs for 1.3.3 you can choose the correct version in the combobox, or just visit http://angular-ui.github.io/bootstrap/versioned-docs/1.3.3/

**Comment by infrarosso78** [comment]
my bad. Sorry.
