### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by coxrichuk** [angular-ui/bootstrap#6224]
This may not be the best place to ask .... but 

With this announcement yesterday (https://github.com/twbs/bootstrap/issues/20631) that support for bootstrap 3 will be coming to an end, are there any plans in place to move angular-ui over to bootstrap 4?

**Comment by wesleycho** [comment]
Closing, as we have already addressed this question in #4234. We don't have the bandwidth to work this in in this library, most of our efforts is focused on the ng2 version, which does support Bootstrap 4.
