### ISSUE TITLE
TypeError: Cannot read property '$apply' of null when dropdown is closed

### ISSUE THREAD

**Issue by yiwenliuable** [angular-ui/bootstrap#6225]
### Bug description:
When dropdown is open and set auto-close to outsideClick, I am expecting the dropdown to close when I click on other elements outside of dropdown, which works for most of the case, except for clicking on "textbox"(input/textarea). It shows Uncaught TypeError: Cannot read property '$apply' of null. I have attached an example in plunker.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/YpIV2bw1kUUGs5w2yU9d?p=preview
Steps to reproduce: open dropdown -> click on textbox -> textbox is not focused and receive the error in console
### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.8
UIBS:
2.1.3
Bootstrap:
3.3.7

**Comment by wesleycho** [comment]
This looks like a bug, although this doesn't really affect behavior.

https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L55 should probably be changed to $rootScope.$digest().

**Comment by nherzing** [comment]
@yiwenliuable @wesleycho  I posted PR to fix this. I'm not a huge fan of the solution but the code is pretty difficult to edit without introducing other issues/accidentally changing behavior. Would love to get this (or a comparable fix) merged because we're seeing this error 10+ times a day.
