### ISSUE TITLE
Popover and trigger "outsideClick"

### ISSUE THREAD

**Issue by luntegg** [angular-ui/bootstrap#6228]
Page with angular-ui version 1.2.5
http://plnkr.co/edit/VTpIXdyYHzecyVhBKlQG?p=preview

Page with angular-ui version 2.1.3 (last)
http://plnkr.co/edit/o1x8fsocKEYAjhdoge6f?p=preview

When we click on different popovers buttons - trigger on blur does not work.

**Comment by neonxz** [comment]
Yeah seeing this too. Need to stay on 1.3.3 until this is fixed :(

**Comment by wallacemaxters** [comment]
The documentation must be updated, because this information still is over there
https://angular-ui.github.io/bootstrap/#/triggers

**Comment by wallacemaxters** [comment]
Oh! this solved my problem:

https://github.com/angular-ui/bootstrap/issues/6212

**Comment by wesleycho** [comment]
As noted in the docs, it must have quotes around the value - see [here](http://plnkr.co/edit/hu65yZsXN7RkVGxPOLpw?p=preview) for fix in action.
