### ISSUE TITLE
tooltip inside ng-repeat causes ALL values to be re-evaluated when only one is activated

### ISSUE THREAD

**Issue by eepstein** [angular-ui/bootstrap#623]
I'm using a tooltip (actually a popover) for cells in a table.  The table is built via nested ng-repeat statements and the popover displays a value that is computed from $scope parameters, including the values from those ng-repeat statements.  

The side-effect of this is that when the user mousesover a single cell in the table, the underlying function is called FOR EVERY cell in the table.  This was most unexpected.

Seems to be some over-eager applying of the context in this case.

**Comment by teodor-marian** [comment]
I used ng-init on the ng-repeat tag to set-up my model, like this it will only be called once and you can use it in {{}} without performance issues
<any ng-repeat="item in item" ng-init="item.data = getData(item.id)"
     {{item.data.tooltip}}
