### ISSUE TITLE
Timepicker - Validation issue

### ISSUE THREAD

**Issue by bifodus** [angular-ui/bootstrap#6230]
### Bug description:

When a bad value is entered in the timepicker, the input displays as invalid (that is, the class `has-error` is applied to the parent `<td>`, with which it can be styled as an error), but the class `ng-invalid` isn't applied to the input element itself (it will remain as `ng-valid`).

There may be other problems with this, but in my use case this conflicts with ngAria.  ngAria will add the attribute `aria-invalid` to the element and set it to `true` or `false` based on the presence of the `ng-valid` or `ng-invalid` classes.

### Reproduce the issue:

1. View the Timepicker on the demo page
2. Enter the value 'z' into the Hours input in the Start Time
3. Inspect this input and notice the presence of `ng-valid`

### Version of Angular, UIBS, and Bootstrap:

Angular: 1.5.2
UIBS: 2.0.2
Bootstrap: 3.3.1

**Comment by david-kirkland** [comment]
+1 #
