### ISSUE TITLE
Carousel not working with latest angular?

### ISSUE THREAD

**Issue by fabn** [angular-ui/bootstrap#6232]
I already saw #6112 and I'm experiencing a very similar issue, i.e. carousel not showing and images shown as blocks and I get no errors in console.

[Linked plunker](http://plnkr.co/edit/YXMBHI6AqcF2EAUCud40?p=preview) is working on my computer and I can see the carousel working using that code.

Here are my dependencies

```
├── angular@1.5.8
├── angular-animate@1.5.8
├── angular-mocks@1.5.8
├── angular-ui-bootstrap@2.1.3
├─┬ bootstrap-loader@1.2.0-beta.1
├── bootstrap-sass@3.3.7
```

I want to use it in a angular + ES6 project based on NG6Starter template. Here is a minimal reproducible case: https://github.com/fabn/NG6-starter/tree/carousel and here's [the commit](https://github.com/fabn/NG6-starter/commit/f60d45f75b8d8d818a31168e7a2d363cea1fd512) that implement carousel in the starter app.

Here's the result of that code

![ng6 starter by angularclass](https://cloud.githubusercontent.com/assets/324213/18419803/a249a7d0-7863-11e6-8994-bf6b7f98509d.png)

Is there any known issue with carousel or did I miss some integration step?

**Comment by kimras** [comment]
Hi
I had the same.. The Directive has changed.. 
You need the Causel group to be a DIV 
Also I had to add Indexes on the groups. and a Active variable in the base Div.
Here is a snipit of what my code ended up with:
```
  <div uib-carousel interval="5000"  active="active">
            <div uib-slide index="0">
                <img ng-src="/img/zzzzz.png">
                <div class="carousel-caption">
                    <p>
                        Txt here 
                    <p />
                </div>
            </div>
            <div uib-slide index="1">
                <img ng-src="/img/xxxxx.png" />
                <div class="carousel-caption">
                    <p>
                        some text
                    </p>
                </div>
            </div>
    <div>

```

**Comment by pziegler** [comment]
this is how I have it and it works fine:
````
<div uib-carousel active="0" interval="5000">
     <div uib-slide ng-repeat="slide in $ctrl.slides track by slide.id" index="slide.id">
         <img ng-src="{{slide.url}}" ng-click="$ctrl.view(slide)" style="margin:auto; max-height:305px">
         <div class="carousel-caption">
               <p>{{slide.label}}</p>
         </div>
     </div>
</div>

**Comment by fabn** [comment]
The code is right, the plunker is working as intended. I've just found out that if I add to header of my page bootstrap css from CDN the code is working:

```html
<link href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
```

So there must be some incompatibility in `bootstrap-sass` and/or `bootstrap-loader`. I'll try to understand what is happening.

**Comment by fabn** [comment]
Ok, it was my fault. I've found that in my code carousel css was not properly loaded because I had `false` in [this line](https://github.com/shakacode/bootstrap-loader/blob/master/.bootstraprc-3-default#L97) of bootstrap configuration.

I'm closing this because it's not an issue with angular-ui.

**Comment by tucq88** [comment]
@pkishino I used same code as yours and also use ng6-starter, but I got this trouble and don't understand why. Have you faced it before ?
![image](https://i.gyazo.com/1b24f1fd42b8fe84520e806d2dcd556c.png)

**Comment by tucq88** [comment]
Ok it's my fool . 
```
<div uib-carousel active="0" interval="5000">
     <div uib-slide ng-repeat="slide in $ctrl.slides track by slide.id" index="slide.id">
...
```
In my $ctrl.slides object, I don't have any id = 0, so the carousel itself doesn't understand. `active` attribute stands with `index` attribute.

**Comment by Prashantko** [comment]
@kimras,thanks man it works for me

**Comment by harryshah6393** [comment]
Put script and css link like this. 

<head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-animate.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-sanitize.js"></script>
    <script src="https://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.1.2.js"></script>
    <script src="example.js"></script>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  </head>
