### ISSUE TITLE
Change note to emphersise on Directive changes

### ISSUE THREAD

**Issue by kimras** [angular-ui/bootstrap#6233]
I love your library, it works grate, but I have experienced that you change major directives who any clear notice. Then one I ran into this time was : Accordion, Carousel and Alert.

I have got them working but I had to run an emergency update as I expected no major changes..

So I would like to request some sort of Alert/highlighted message on the Directive changes. Or if it already exists, buease let me know whee I normally should look..

**Comment by wesleycho** [comment]
This was in the 2.0 release. That was the first semver release. All of the changes are detailed in the [changelog.md](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md) file, so they are already documented.

Considering such, I am going to close this as already present.
