### ISSUE TITLE
Can't Animate Dropdown With JavaScript

### ISSUE THREAD

**Issue by kmccullough** [angular-ui/bootstrap#6237]
### Bug description:

**_Dropdown_** directive cannot be animated using a JavaScript animation.

I was surprised to see that the element doesn't get removed from the DOM, but just _display: none_ inline on the element. Seems like this would best be handled by _$animate.enter()_/_$animate.leave()_.

### Link to minimally-working plunker that reproduces the issue:

Note, the slide-down/up animation intermittently fails.

http://plnkr.co/edit/8peFvGZ4UGSlx14n3RSq?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:1.5.3

UIBS: 2.1.3

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
Why are you using jQuery to animate? This is an anti-pattern when using libraries that are using $animate. In particular, UI Bootstrap uses $animate.addClass/$animate.removeClass to handle animations via CSS, so your best approach would be to hook into the ngAnimate animation lifecycle.

Going to close this as not an issue.

**Comment by kmccullough** [comment]
Can you show me how to do the slide-down animation using pure CSS? As far as I can tell, it cannot be done well.  I think the fact that I use jQuery for my animation is irrelevant; angular supports JavaScript animations and I'm trying to activate one. My slide-down directive also has a class animation using module.animation. The problem is, that doesn't work either, because $animate.addClass is called on the parent element, not the actual element that should be animated (e.g. if I append to body, it is the body element which $animate.addClass is called on). So, please offer an example of how to hook into your call to $animate.addClass to animate the drop-down menu using a JavaScript animation.

**Comment by kmccullough** [comment]
If you cannot provide such an example, please reopen this issue.

**Comment by kmccullough** [comment]
Still waiting on a response here. If you can tell me how $animate.addClass on BODY is helpful to me, I'll use it gladly.

**Comment by wesleycho** [comment]
GitHub is not the place to ask for support questions like this. Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md before posting/commenting on GitHub on any repository when the file is present.

In addition, it is the developer's responsibility to understand how ngAnimate works and how to hook into it - there is a lot out of material out there on how to use it, including the Angular documentation [here](https://docs.angularjs.org/api/ngAnimate). I don't have the time to educate on how to use ngAnimate, please invest the time to solve your problem before demanding that time of others.

**Comment by kmccullough** [comment]
I don't really need an explanation if you are asserting that it can be done.  Are you confirming that the call in  dropdown to $animate.addClass( BODY ) ... is correct, and usable?

**Comment by kmccullough** [comment]
Here is a look at the code in question:
```
    var openContainer = appendTo ? appendTo : $element;
    var hasOpenClass = openContainer.hasClass(appendTo ? appendToOpenClass : openClass);

    if (hasOpenClass === !isOpen) {
      $animate[isOpen ? 'addClass' : 'removeClass'](openContainer, appendTo ? appendToOpenClass : openClass).then(function() {
        if (angular.isDefined(isOpen) && isOpen !== wasOpen) {
          toggleInvoker($scope, { open: !!isOpen });
        }
      });
    }
```

Note openContainer is either the _uib-dropdown_ container or whatever element was appended to (in my case BODY).  $animate.addClass is therefore called on the PARENT to the actual element that should be animated, rather than the actual menu element that should be animated. If this code is correct, I apologize, but I cannot find any documentation on how to use an $animate class hook on a parent element. Now, I suppose I could hook into the class added to the body and then from there use a selector to find the actual menu to animate, but I feel like I shouldn't need to use a selection,  it should just animate the actual element, in which case I'd have actual direct reference to it in the handler.

My expected response here is for you to tell me the above code was intended to work like this, and I should just deal... or that it looks wrong to you as well. Keep in mind I am not asking for a tutorial, I'm asking you to verify\-- by looking at the code\--that this functionality is intended to work like this.
