### ISSUE TITLE
Disabled multiple specific date 

### ISSUE THREAD

**Issue by DRAKUN** [angular-ui/bootstrap#6241]
I can't to disable all date in this arrays Holidays
someone can help

$scope.holidays = [
        new Date(today.getFullYear(),today.getMonth(),14),
        new Date(today.getFullYear(),today.getMonth(),15),
        new Date(today.getFullYear(),today.getMonth(),16),
        new Date(2016, 9, 12),
    ];

**Comment by wesleycho** [comment]
Check the `dateDisabled` options as listed in the documentation [here](http://angular-ui.github.io/bootstrap/#/datepicker).

Please note that the issues are not for support - check out https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and read the documentation carefully before opening an issue.

**Comment by DRAKUN** [comment]
can u see that [https://github.com/DRAKUN/customDatePicker](url)
