### ISSUE TITLE
TypeError: null is not an object (evaluating 'openScope.$apply') on closeDropdown

### ISSUE THREAD

**Issue by nstuyvesant** [angular-ui/bootstrap#6242]
### Bug description: Error logged to console when opening a uib-modal from a uib-dropdown-menu on **Safari 9.1.3** on MacOS 10.11.6 and **Safari 10** on MacOS 10.12.

> TypeError: null is not an object (evaluating 'openScope.$apply') on closeDropdown (ui-bootstrap-tpls.js:3225)

Line 3222 of ui-bootstrap-tpls.js...
`openScope.focusToggleElement();`
causes openScope to become null. This leads to the error on line 3225.

If the modal is opened with a normal anchor outside of the uib-menu, there's no problem. If I use the latest version of Chrome or FireFox on MacOS, there's no error.

I should note that despite the error, the modal dialog still opens and the dropdown closes so the functionality is not impaired.

### Version of Angular, UIBS, and Bootstrap
Angular: 1.5.8
UIBS: 2.1.3
Bootstrap: 3.3.7

**Comment by wesleycho** [comment]
I think this is addressed by 08ee30a91e0fe669f81263fcdf37aaa589d55fe2

**Comment by nstuyvesant** [comment]
After upgrading to 2.1.4, the issue no longer occurs. Thanks!
