### ISSUE TITLE
Replace modal content/template after it's opened?

### ISSUE THREAD

**Issue by Fossil01** [angular-ui/bootstrap#6248]
Hi,

Could someone explain how I can replace the content inside a modal once it's opened? I'm opening a modal when a specific websocket event is fired.

After that event I get status updates and I want to replace the modal content with those statuses.

My code to open a modal:

```javascript
var modalInstance = $uibModal.open({
	animation: true,
	template: r.message.description,
	windowTemplateUrl: 'modal.html',
	controller: 'ModalController',
	backdrop: true,
	size: 'lg',
	resolve: {}
});
```

```html

<script type="text/ng-template" id="modal.html">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Document Reader</h4>
      </div>
      <div class="modal-body" uib-modal-transclude>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</script>
```

`r.message.description` is a string I get from the websocket. That's what I need to replace inside the modal.

Cheers,

Bento

**Comment by wesleycho** [comment]
Why not create a component wrapping what you need to replace, or use resolves?

In any case, this appears to be a support question, so closing as the incorrect place to open such an issue.
