### ISSUE TITLE
Not able to set tab via code after selecting tab from UI side. 

### ISSUE THREAD

**Issue by narendrasinghrathore** [angular-ui/bootstrap#6250]
#I am trying to set tab via controller which works fine. But after selecting tab manually from UI side, the code in controller stop working, no error nothing.

### UIBS: Version: 1.2.5 - 2016-03-20

HTML:

`<uib-tabset active="activeTab">

    <uib-tab  heading="Zero">
         <div ng-include="Zero.tpl.html"></div>
    </uib-tab>

    <uib-tab  heading="One" >
        <div ng-include="'One.tpl.html"></div>
    </uib-tab>

    <uib-tab  heading="two">
        <div ng-include="two.tpl.html"></div>
    </uib-tab>
    <uib-tab  heading="three">
        <div ng-include="three.tpl.html"></div>
    </uib-tab>
    <div>
        <button ng-click="changeTab(0)">0</button>
        <button ng-click="changeTab(1)">1</button>
        <button ng-click="changeTab(2)">2</button>
        <button ng-click="changeTab(3)">3</button>
    </div>
</uib-tabset>`

Controller:

`$scope.changeTab = function(tab)
                {
                  $scope.activeTab = tab;
                  //console.log('$scope.activeTab: ' + $scope.activeTab);
                };`

@icfantv

**Comment by narendrasinghrathore** [comment]
@icfantv Any help?

**Comment by icfantv** [comment]
@narendrasinghrathore Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.

**Comment by narendrasinghrathore** [comment]
@icfantv  I had posted this on stackoverflow, hope i get help from angular-ui-bootstrap team and from you soon.
Thanks

[http://stackoverflow.com/q/39643942/1936186](url)
