### ISSUE TITLE
AngularJS tooltip is not destroying in mobile device on scrolling other elements.

### ISSUE THREAD

**Issue by piyush-dholariya** [angular-ui/bootstrap#6266]
## Bug Description:
AngularJS tooltip is not destroying in mobile device on scrolling other elements.
So Want to destroy tooltip if grid, dropdown or any other scrollable elements is scrolled up/down.

## Version of Angular, UIBS, and Bootstrap
Angular: 1.5.8
UIBS: 2.1.4
Bootstrap: 3.3.7

**Comment by icfantv** [comment]
@piyush-dholariya we do not support tooltips or popovers on mobile devices.  The UX is horrible and does not make sense since there is no pointing device.
