### ISSUE TITLE
Carousel swipe is not working in v2.1.4

### ISSUE THREAD

**Issue by sangharsh** [angular-ui/bootstrap#6277]
Swipe is not working in Carousel in ui-bootstrap v2.1.4 (or any v2.x.x) whereas it is working fine with v1.3.3

Plunker: https://plnkr.co/edit/odlDYR?p=preview

Angular: v1.5.8
UIBS: v2.1.4
Bootstrap: v3.3.7

PS: For ease of swiping, plunker can be opened on mobile with QR code.

**Comment by wesleycho** [comment]
This was actually an intentional change, due to the deprecation of ngTouch - feel free to override the template and add the attributes if you're using it.

**Comment by sangharsh** [comment]
Okay. Checked it on changelog as well.

Does carousel have supporting swipe on roadmap?

Meanwhile, docs should be updated as they mention swiping is supported in carousel.
I'll raise a PR.

**Comment by splanard** [comment]
Same problem. I agree : the documentation should be updated.

**Comment by thefewminutes** [comment]
could documentation be updated please?
