### ISSUE TITLE
ui-sref does not trigger dropdown close

### ISSUE THREAD

**Issue by enkhi77** [angular-ui/bootstrap#6279]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
When clicking an anchor tag using the ui-sref to link to a new state, the dropdown does not close.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/Rz3AbgnYnWI34DjuByY6?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 2.1.3

Bootstrap: 3.3.6

UI-Router: 1.0.0-beta.2

**Comment by enkhi77** [comment]
found out it was an issue with UI Router, closing

**Comment by skeymeulen** [comment]
@enkhi77 Could you please elaborate what the UI Router issue was? I'm having the same problem.
