### ISSUE TITLE
Autofocus is not working in modals

### ISSUE THREAD

**Issue by suvjunmd** [angular-ui/bootstrap#6289]
### Bug description:

Autofocus is not working in modals. The problem appeared in version 2.2.0, and is missing in 2.1.3.
### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/lnaWCwMQoD0qamWyEhD2?p=preview
### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8
UIBS: 2.2.0
Bootstrap: 3.3.7

**Comment by motohead400** [comment]
I'm experiencing the same issue

**Comment by motohead400** [comment]
Can confirm.  Changed to 2.1.3 and autofocus now works.

**Comment by nstuyvesant** [comment]
Same here.

**Comment by nstuyvesant** [comment]
Sorry - just a clarification... I went back to 2.1.4 (not 2.1.3) from 2.2.0 to resolve the issue.

**Comment by brion-fuller** [comment]
I have noticed and issue which probably relatives to this.  But notice in 2.2.0 the modal automatically focuses on the first tab-able element. This did not occur in 2.1.4.

**Comment by nstuyvesant** [comment]
Seems that the focus goes to the close button (which probably is the first tab-able element). Perhaps this was related to the change to make the dialogs more accessible? See the change on https://github.com/angular-ui/bootstrap/commit/f9f7e02 - src/modal/modal.js line 649 (newly added).

**Comment by sman591** [comment]
Seeing a similar issue - it selects the first link, which for me happens to be in the modal body. Looking at the changes in https://github.com/angular-ui/bootstrap/commit/f9f7e02 it seems like that's definitely the cause - it didn't exist before then.

**Comment by dgsmith2** [comment]
It appears this was fixed in #6295

**Comment by suvjunmd** [comment]
Fixed in 2.3.1
