### ISSUE TITLE
In document 'https://angular-ui.github.io/bootstrap/' in the markup/javascript tabs, the Javascript does not include dependencies

### ISSUE THREAD

**Issue by vvaradarajan** [angular-ui/bootstrap#6290]
### Bug description:
In document 'https://angular-ui.github.io/bootstrap/' in the markup/javascript tabs, the Javascript does not include dependencies.
This is not a big issue since the plunker uses a different file 'example.js' which has the dependency.
However I just copied the markup and javascript and that did not work, since the dependency ['ui.bootstrap'] was missing.
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/HgoARzWfKlR47kQt2u1R?p=preview
### Version of Angular, UIBS, and Bootstrap
This is a documentation issue (versions are below, but not relevant to this issue)
Angular: 1.5.8

UIBS: 2.2.0

Bootstrap: 3.3.7

**Comment by wesleycho** [comment]
This is an extremely minor issue, if one at all. This is not going to change, as there is a lot of code generation going on here - each of the demo.js files for each component is being appended to the app, and in addition, each one is also being read as a raw string, slightly modified, and sent when users click to edit in Plunkr.

As a result, going to close this as something we are not going to address, as the benefits are not worth the effort here given the limited bandwidth of the team & the prioritizing ng-bootstrap.

**Comment by vvaradarajan** [comment]
Agree and Thank you.
