### ISSUE TITLE
'uibAccordionHeading', can't be found

### ISSUE THREAD

**Issue by nrsedat** [angular-ui/bootstrap#6293]
### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 2.2.0

Bootstrap: 3.3.7

**Comment by pkozlowski-opensource** [comment]
`uib-accordion-group` can only be used as an attribute and not as an element: https://github.com/angular-ui/bootstrap/blob/997813f0eba41971c948d0ea4c9c9c21542bccd7/src/accordion/accordion.js#L61

**Comment by nrsedat** [comment]
yes, I saw this. I think this would need me to change every place I use accordion. Is there any reason why element support was removed?

**Comment by pkozlowski-opensource** [comment]
>  Is there any reason why element support was removed?

3819bbe8fafe9117d3c9033ef3156803b9a57247

**Comment by nrsedat** [comment]
Closing this issue as per the above comments
