### ISSUE TITLE
uib-tabset Active property not working in 1.3.3

### ISSUE THREAD

**Issue by pjlasl** [angular-ui/bootstrap#6294]
### Bug description:

The active property is not selecting the proper tab when set via the controller. 

I am seeing the value change between clicks, but the tabs themselves are not showing as active.

### Link to minimally-working plunker that reproduces the issue:

`<uib-tabset style="padding: 10px;" active="stage.active">
                        <uib-tab index="$index" ng-repeat="prop in stage.properties" heading="{{prop.heading}}" ng-click="getQuotes($index,true)">                    
                    </uib-tabset>`

In my controller i have:

`$scope.stage.active = 1`

I would expect it to set the second tab active, but it doesn't...

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.8
UIBS:
1.3.3
Bootstrap:
3.3.6

**Comment by varunkumarm** [comment]
@pjlasl It looks like I'm also facing the same issue. Can you please provide the rationale behind closing this issue? If you have found a way to make this work, please put a comment here. Many thanks!!

**Comment by pjlasl** [comment]
My issue wasn't code related, but rather version related...My code was written for 1.3.3 of angular-ui, but my bower had not properly updated from 0.14.3. Once I moved to the proper version, everything worked. It was move of a oops on my part for not double checking the angular-ui version after my update...

**Comment by Vnthf** [comment]
uib-tab made by ng-repeat is not contained in active index. I tested it and It is bug.
