### ISSUE TITLE
Modal:  error in ChildModalFilterController (child for MainModalController) with  ControllerAs syntax

### ISSUE THREAD

**Issue by miukki** [angular-ui/bootstrap#6296]
Hi!

i m using angular-bootstrap version 0.13.4, angular version: AngularJS v1.5.8:

in Modal (with its own controller , lets say 'MainModalController as main') by using ng-include i load template with child controller ChildModalFilterController  as filter.

when in template i m  trying access   something like 
{{filter.degreeType}}

it doesn't work for Model.
i can only access parent scope e.g: 
{{main.order.product_line.location}}

options for modal open : 

```
function showModal (size, templateUrl, context, controller, controllerAs) {

    modalInstance = $modal.open({
      animation: true,
      templateUrl: templateUrl,
      controller: controller,
      controllerAs: controllerAs || 'modal',
      bindToController: true,
      size: size,
      resolve: context
      //scope: $scope
    });
 return modalInstance;

}

```

**Comment by wesleycho** [comment]
0.13.4 is quite an old version - have you tried a more recent version? Ideally also a reproduction with the most recent version would be preferred as well, as it is inefficient for us to chase and guess at problems.

**Comment by miukki** [comment]
i ahve updated angular-bootstrap to version 2.2.0 / problem is still exist

**Comment by miukki** [comment]
what is interesting string type for childController is possible access
{{filter.someString}}

but not for array.

**Comment by wesleycho** [comment]
Please post a reproduction with Plunker.
