### ISSUE TITLE
 I use yeoman+angular to create webapp,but a problem I understand

### ISSUE THREAD

**Issue by fairyly** [angular-ui/bootstrap#6299]
yeoman +angular is ok, use grunt server is ok,too. http://localhost:9000 is ok.

I  want to use 'ui-bootstrap.min.js' and 'ui-bootstrap-tpls.min.js' in index.html
then Install with Bower
$ bower install angular-bootstrap

index.html:
<script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="bower_components/angular-animate/angular-animate.js"></script>
    <script src="bower_components/angular-cookies/angular-cookies.js"></script>
    <script src="bower_components/angular-resource/angular-resource.js"></script>
    <script src="bower_components/angular-route/angular-route.js"></script>
    <script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
    <script src="bower_components/angular-touch/angular-touch.js"></script>
    <script src="bower_components/angular-bootstrap/ui-bootstrap.min.js"></script> //  I write here
    <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js "></script>//  I write here

But when I use 'grunt serve ' ,I write that was Disappeared;  why?

**Comment by fairyly** [comment]
bower.json:
{
  "name": "angular-yeoman",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.4.0",
    "bootstrap": "^3.2.0",
    "angular-animate": "^1.4.0",
    "angular-cookies": "^1.4.0",
    "angular-resource": "^1.4.0",
    "angular-route": "^1.4.0",
    "angular-sanitize": "^1.4.0",
    "angular-touch": "^1.4.0"
  },
  "devDependencies": {
    "angular-mocks": "^1.4.0",
    "angular-bootstrap": "^2.2.0"
  },
  "appPath": "app",
  "moduleName": "angularYeomanApp",
  "overrides": {
    "bootstrap": {
      "main": [
        "less/bootstrap.less",
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js"
      ]
    }
  }
}

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
