### ISSUE TITLE
typeahead-is-open option not working

### ISSUE THREAD

**Issue by victorhazbun** [angular-ui/bootstrap#6304]
### Bug description:

The option typeahead-is-open is not showing the list of elements when the value assigned is true.
As you can see in the plunker the option typeahead-is-open has assigned a variable "isOpen" and the value is true, however the list of elements are not shown. Is this a bug? or What is suppose to be the function of the option typeahead-is-open ?
### Link to minimally-working plunker that reproduces the issue:

https://embed.plnkr.co/lO130v63G4qCCw7JKKNL/
### Version of Angular, UIBS, and Bootstrap

Angular: "1.5.8"

UIBS: "2.2.0"

Bootstrap: "3.3.7"

**Comment by icfantv** [comment]
We are parsing this value and evaluating it against the scope.  Also, you're lacking specific steps in your issue for us to reproduce the issue in your plunker.  Closing until fixed.
