### ISSUE TITLE
[$injector:unpr] Unknown provider: $uibModalInstanceProvider <- $uibModalInstance when injecting $uibModalInstance

### ISSUE THREAD

**Issue by asadsahi** [angular-ui/bootstrap#6305]
### Bug description:

Getting below error, when trying to inject $uibModalInstance in the controller of an angular Component to close/dismiss the modal window. I am using uibModal as a ui router state using onEnter hook of router.

![image](https://cloud.githubusercontent.com/assets/3470892/19836227/8949114a-9e91-11e6-81ec-5df6a506a997.png)

Tried calling $close/$dismiss methods on $scope as described [here](http://stackoverflow.com/questions/33930325/angular-ui-bootstrap-modal-injectorunpr-unknown-provider-uibmodalinstance), but these methods aren't available on scope.

Something mentioned here (http://angular-ui.github.io/bootstrap/#/modal) in javascript source which states:

> // Please note that $uibModalInstance represents a modal window (instance) dependency.
> // It is not the same as the $uibModal service used above.

Note: If I am using template with controller (i.e not using component), I can inject $uibModalInstance into controller without error.

Is there any way to close/dismiss modal window without having modalInstance we have as a result of calling $modal.open method when using component?
### Version of Angular, UIBS, and Bootstrap

Angular:
    "angular": "1.5.8",
UIBS:
    "angular-ui-bootstrap": "2.2.0",
Bootstrap:
    "bootstrap": "3.3.7",

**Comment by wesleycho** [comment]
`$uibModalInstance` is a local, not a normal injectable.

Please reproduce this in Plunker - this is highly likely a user error.

**Comment by asadsahi** [comment]
Sorry wasn't able to provide example as I was still figuring out the meaning of:

> $uibModalInstance is a local, not a normal injectable.

Also, when I modiefied the modal example from ui website > [only modal dialog](https://plnkr.co/edit/8qdeWf40SpIMOHng99EP?p=preview)

I found this hidden Gem:

> // Please note that the close and dismiss bindings are from $uibModalInstance.

And that works for me as my whole application is tree of components and using the same in modal makes sense.

Thanks @wesleycho

**Comment by sdudnic** [comment]
> `$uibModalInstance` is a local, not a normal injectable.
What does it mean, @wesleycho and what should we do in that case ?
