### ISSUE TITLE
Conditional expression inside custom template in order to make the particular list item unselectable

### ISSUE THREAD

**Issue by sabhsingh26** [angular-ui/bootstrap#6309]
Hi All,

I am using uib-typeahead to show nested structure (flattening it to array). In this I wanted to make all the parent with child as non selectable and should be skipped when navigating from keyboard. And all children can be selectable so did put inside tag. In order to achieve this functionality, I put around ng-if statement on a tag and check whether it has children flag set or not. If it does have children property set, then skip the tag and go into div tag and check property. Now the tree structure is defined, uib-typeahead-ediatble is set to false, ui-typeahead-on-select it also set. But navigation using keyboard is weird as it does not skip all element list defined through DIV tag. And if I remove ng-if statements on and DIV tag, all list items are populated twice but keyboard navigation works only for element defined through tag.
Wanted to understand, whether this is a feature desgined or missing feature ? I tried using typeahead-group header class but that will also involve conditions on a tag which again does not work.

**Comment by sabhsingh26** [comment]
Hi All,

I am using uib-typeahead to show nested structure (flattening it to array). In this I wanted to make all the parent with child as non selectable and should be skipped when navigating from keyboard. And all children can be selectable so did put inside <a> tag. In order to achieve this functionality, I put around ng-if statement on a tag and check whether it has children flag set or not. If it does have children property set, then skip the tag and go into div tag and check property. Now the tree structure is defined, uib-typeahead-ediatble is set to false, ui-typeahead-on-select it also set. But navigation using keyboard is weird as it does not skip all element list defined through DIV tag. And if I remove ng-if statements on <a> and DIV tag, all list items are populated twice but keyboard navigation works only for element defined through <a> tag.
Wanted to understand, whether this is a feature desgined or missing feature ? I tried using typeahead-group header class but that will also involve conditions on a tag which again does not work.

**Comment by icfantv** [comment]
Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.
