### ISSUE TITLE
Timepicker marks valid hours/minutes as invalid

### ISSUE THREAD

**Issue by kevcenteno** [angular-ui/bootstrap#6312]
### Bug description:

1. Enter `99` for the hour
2. Enter `99` for the minute
3. Enter `11` for **one of** hour or minute

_Expected_
Hour/minute is marked as valid

_Actual_
Hour/minute is marked as invalid

### Link to minimally-working plunker that reproduces the issue:

https://angular-ui.github.io/bootstrap/#/timepicker

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.13

UIBS: 2.2.0

Bootstrap: 3.3.7

**Comment by icfantv** [comment]
@kevcenteno it's a time picker.  not a duration picker.

**Comment by kevcenteno** [comment]
@icfantv I hear you.  I just think that the timepicker should be validating the hour and minute field independently, which it isn't.
