### ISSUE TITLE
No Minified Version on npm

### ISSUE THREAD

**Issue by trisys3** [angular-ui/bootstrap#6317]
There is no minified version of bootstrap when installed with npm. To see what I mean, run `npm install angular-ui-bootstrap` in any empty directory, then inspect `node_modules/angular-ui-bootstrap/dist`, which holds the files built for the repository. You will see that there is a `ui-bootstrap-tpls.js` and a `ui-bootstrap.js`, but no `ui-bootstrap-tpls.min.js` or `ui-bootstrap.min.js`.

However, on bower, if you do the same thing (run `bower install angular-bootstrap` in an empty directory, then inspect `bower_components/angular-bootstrap/`), you will note that there *are* minified JavaScript files. Specifically, there is a `ui-bootstrap-tpls.min.js` and a `ui-bootstrap.min.js`. I tried with version 2.2.0 for both npm and bower.

First of all, was this intentional, or an oversight? Are we expected to minify the npm version as part of the build? If so, is there an npm script in this repository that can be hooked into, or at least a sample script, or will just a simple `uglify` build work fine?

**Comment by wesleycho** [comment]
This was intentional, the idea being that when using the npm version, a build process is used and smarter strategies are used to only require/import what is needed. This has been discussed in a prior issue, and will not be supported.

**Comment by trisys3** [comment]
OK, thanks. I did not see the earlier issue, could this be put into the README or somewhere? Thanks.
