### ISSUE TITLE
uib-dropdown-toggle <input> re-focusing on outside click

### ISSUE THREAD

**Issue by GAndriyS** [angular-ui/bootstrap#6321]
### Bug description:
uib-dropdown-toggle <input> re-focusing on outside click (e.g. another common, non-dropdown-toggle input)

#### Steps to reproduce
1) Click <input> to toggle dropdown menu
2) Click on common input or outside of dropdown

#### Observed
Hide dropdown menu , focus returns to uib-dropdown-toggle <input>

#### Expected
Hide dropdown menu, set focus to clicked element

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/sxREBmeGwoFBQ4ZnOLIV?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: v1.5.8

UIBS: Version: 2.2.0 - 2016-10-10

Bootstrap: v3.3.7

**Comment by svisamsetty** [comment]
@GAndriyS I am facing the same issue. Do you have any solution yet?

**Comment by GAndriyS** [comment]
@svisamsetty not yet, I'm waiting for developer's answer.

**Comment by kwiateusz** [comment]
On 2.3 that error is still present, and it's very annoying

**Comment by neehouse** [comment]
Having the same problem.. Resolved the refocusing issue by commenting out the focus call on the toggleElement.

`  scope.focusToggleElement = function() {
    if (self.toggleElement) {
      //self.toggleElement[0].focus();
    }
  };`

Not sure of any impact, but this gave back the ability to focus the items correctly.

The Angular-UI example, if you toggle a dropdown menu, and the scroll away and click, the same thing of the menu being re-focused occurs.

**Comment by usos0k** [comment]
Same issue. However, I face the issue only when I build the code as production mode. In my development mode, it works fine. Please anyone help!

**Comment by alex88** [comment]
Same issue here, clicking everywhere focuses on the toggle element and scrolls the page making inputs not working

**Comment by nikasioMel** [comment]
Same here.
No matter what I do, everything works as expected before a dropdown-menu is clicked. After that, the last dropdown clicked will get focus no matter where I click

**Comment by lukehutton** [comment]
I did the following to fix for myself, https://github.com/angular-ui/bootstrap/pull/6353/commits/e07f9fd9fc8b63501cab45d3a38a00d6cb0233ad I updated an existing PR to support something else so obviously better to have separate PR for it

**Comment by petedavis** [comment]
+1 Thanks @neehouse for the suggested temp fix.

**Comment by Gusi** [comment]
+1

**Comment by dougludlow** [comment]
@lukehutton e07f9fd works great for me! Thank you!

**Comment by GAndriyS** [comment]
neither [e07f9fd](https://github.com/angular-ui/bootstrap/commit/e07f9fd9fc8b63501cab45d3a38a00d6cb0233ad) or [955848c](https://github.com/angular-ui/bootstrap/commit/955848c3b125ff24ce749a42283763dc16668ef0) don't works for me, described bug still can be reproduced in version 2.5.0

http://plnkr.co/edit/zanydRnj0ghWiEdvt4Cg?p=preview

**Comment by rzawar** [comment]
facing same issue. I cannot focus on input in different controller or even in same directive. But I can focus on different dropdown.

**Comment by oriamd** [comment]
I struggled with the same problem and used this workaround :
`<div uib-dropdown-toggle ><input on-focus="toggleDropDown(true)" /></div>`
