### ISSUE TITLE
isOpen doesn't work properly 

### ISSUE THREAD

**Issue by xskif** [angular-ui/bootstrap#6322]
### Bug description:
I can't manually assign isOpen for dropdown, the same issue with tooltips and popovers.
It seems it has been broken after major release (1.x -> 2.x) because before that everything had worked fine.

I have this code in my directive
```
$scope.isOpen = false;

            function onSelectorToggle(open) {
                console.warn(open, $scope.isOpen);
            }
```

and this one in my .slim file
```
div uib-dropdown="" auto-close="outsideClick" is-open="isOpen" on-toggle="onSelectorToggle(open)"
```

Each toggle action fires in the console (true|false) for the 'open' attribute and false always for the '$scope.isOpen'

Angular: 1.5.6

UIBS: 2.2.1

Bootstrap: none

**Comment by xskif** [comment]
Looks like it's 'dot issue'

**Comment by jlf123** [comment]
dot issue??

**Comment by xskif** [comment]
Yes. Use $ctrl.isOpen or vm.isOpen, never use $scope directly
