### ISSUE TITLE
uib-tabset: Not able to use strings as indexes

### ISSUE THREAD

**Issue by jarinwhite** [angular-ui/bootstrap#6324]
### Bug description:

When using strings as tab indexes, the tabs do not behave as expected. All tabs are visible at all times, and choosing a different tab than the "active" tab causes multiple tabs buttons/pills to appear active.

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/7epQE2ltiTW4mox1TdhR?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 2.2.0

Bootstrap: 3.3.6

**Comment by phazei** [comment]
I'm also experiencing this issue.  It works just fine if the indexes are numbers, but if they're strings, then it just doesn't work

**Comment by RobJacobs** [comment]
You need to enclose your index values in single quotes so angular will interpret them as strings instead of a model property.

**Comment by jarinwhite** [comment]
Thanks, you are right, that was the solution. Not sure how I glossed over that. Closing this issue.
