### ISSUE TITLE
uib-pagination not working with ui-bootstrap-tpls-2.2.0.js

### ISSUE THREAD

**Issue by shermax** [angular-ui/bootstrap#6327]
uib-pagination not working with ui-bootstrap-tpls-2.2.0.js. 

If I test with ui-bootstrap-tpls-0.14.3.min.js it is working fine.

Tested using html:
`<uib-pagination boundary-links="true" total-items="pagination.total" ng-model="pagination.currentPage" ng-change="loadList()" max-size="7" rotate="false"
                                            previous-text="&lsaquo;" next-text="&rsaquo;" first-text="&laquo;" last-text="&raquo;"></uib-pagination>`

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

**Comment by agray** [comment]
This is happening for me too. We upgraded from v1.2.5 to v2.2.0.

**Comment by connectmobile** [comment]
Attribute works: `<ul uib-pagination>`
Element does not work: `<uib-pagination>`

[https://plnkr.co/edit/3bkfNHZWNSimNC8zuiVG?p=preview](https://plnkr.co/edit/3bkfNHZWNSimNC8zuiVG?p=preview)

**Comment by wesleycho** [comment]
This was a breaking change listed in the changelog for 2.0.0 and documented usage in the docs.

**Comment by jeffward01-umpg** [comment]
@wesleycho They should add this to the docs.  
@connectmobile 

**Attribute works:**` <ul uib-pagination>`
**Element does not work:** `<uib-pagination>`

**Comment by i-am-rem** [comment]
WOW!! this is so helpful!!
