### ISSUE TITLE
Some code is dead

### ISSUE THREAD

**Issue by NickHeiner** [angular-ui/bootstrap#6332]
In angular-ui-bootstrap@2.2.0, it appears that there is some dead code. When running it through the Webpack UglifyJS plugin, I got the following warnings:

```
Dropping unused function getSlideByIndex [./~/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js:620,0]
Dropping unused variable lastActivated [./~/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js:1345,0]
Dropping unused variable dataPerTracked [./~/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js:1337,0]
Dropping unused function cameltoDash [./~/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js:3001,0]
Dropping unused variable cache [./~/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js:2726,0]
Dropping unused variable selectedOption [./~/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js:3263,0]
```

Manually spot-checking some of these in the file does indeed suggest that the code is unused.

The short-term fix is to remove the dead code. The longer-term fix is to add `no-undef` to the `.eslintrc`, so these errors can be caught. I'm happy to do either if you express interest in such a PR :smile:.

**Comment by icfantv** [comment]
We allow the user to override our templates.  If you chose to do that, you have access to controller methods contained therein.  The one in slides, e.g., is there for utility.  Even if you specify your own template, you don't have access to the controller.

At this point, it would be a breaking change to remove at least one of them.  I'm going to close unless there's a compelling reason to rectify.
