### ISSUE TITLE
dropdowns won't close when parent stops event propagation

### ISSUE THREAD

**Issue by shooby83** [angular-ui/bootstrap#6334]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I got a wrapper that stops event propagation. In that wrapper I got several directives with UI Bootstrap dropdowns. 

The problem is, that these dropdowns doesn't close on any click. Only by clicking another dropdown.

Seems UI dropdown watches body or something to force closing.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/bHHrpipM4MlxLNfOE2pt?p=preview

### Version of Angular, UIBS, and Bootstrap
Angular:
1.5.3
UIBS:
1.3.3
Bootstrap:
1.3.3

**Comment by wesleycho** [comment]
The listener is on `document`, as seen [here](https://github.com/angular-ui/bootstrap/blob/14384fc40fab96fe1dcb6afcdbb5eec4ad4b2772/src/dropdown/dropdown.js#L13) - this is not likely to be changed, as this is important for the closing functionality when the click is outside the dropdown.

**Comment by wesleycho** [comment]
Going to close this as won't fix - one can use the `is-open` binding to work around this issue.
