### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by alippai** [angular-ui/bootstrap#6336]
The current versions are not secure: https://david-dm.org/angular-ui/bootstrap?type=dev
Except the karma upgrade nothing should break the build/test.

**Comment by wesleycho** [comment]
The lack of security is marked, the Markdown parser - this is not something we can do much about given the way the demo is set up.

This library is not seeing much active development currently, so if you'd like to put in the effort to try to upgrade the libraries, we'd more than be happy to accept PRs.

**Comment by wesleycho** [comment]
Going to close, as I have investigated upgrading deps prior and there are other issues at play - the insecure marking is not a library issue itself.
