### ISSUE TITLE
timePicker - minDate and maxDate difference of behaviour 

### ISSUE THREAD

**Issue by MGouaillier** [angular-ui/bootstrap#6337]
Hi !
I noticed a bug (not sure it's a bug) while using this picker (which is great by the way :D)
If you set a minDate and maxDate, when the picker reach this limit it doesn't have the same behaviour.

Let me explain this with some pictures

minDate is reached
![image](https://cloud.githubusercontent.com/assets/19687884/20717750/d67f0f50-b656-11e6-92d7-e8b3e785538e.png)

There's a red ribbon around the time selection but you can still edit the time

maxDate is reached
![image](https://cloud.githubusercontent.com/assets/19687884/20717758/df1cffaa-b656-11e6-943e-ebce400101fd.png)

The time input is disabled

This is quite annoying when you're using the picker without the little arrows that allow you to change the time, beacause you can't adjust the time in the maxDate case

**Comment by MGouaillier** [comment]
I managed to everride the template with this code

![image](https://cloud.githubusercontent.com/assets/19687884/20790366/583862f0-b7b8-11e6-8774-d7b156fed66d.png)

(Couldn't put code directly, indent wasn't great)

**Comment by MarkVanPeteghem** [comment]
I found a workaround for this problem using angular. I guess it can be adapted for code that doesn't use angular. Define this function:

`        function removeDisabled() {
          $timeout(function () {
            var inputs = $document.find('.uib-time input');
            for (var i=0; i<inputs.length; ++i) {
              var input = angular.element(inputs[i]);
              if (input.attr('disabled')) {
                input.removeAttr('disabled');
              }
            }
          }, 0);
        }
`
and call it whenever the timepicker value or its maximum changes.
