### ISSUE TITLE
Accordion closing after model update

### ISSUE THREAD

**Issue by ctysingh** [angular-ui/bootstrap#6338]
The accordion get closed once model is updated. How can i prevent the accordion getting closed.
I assume this is default behavior but is their a way to override this. 

Angular: 1.5
UIBS: 2.2.0
Bootstrap:3.3.7

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
