### ISSUE TITLE
use $uibtooltipprovider.option in pop over template

### ISSUE THREAD

**Issue by diptee** [angular-ui/bootstrap#6341]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by wesleycho** [comment]
Closing due to no actionable/respondable content
