### ISSUE TITLE
Datepicker Time

### ISSUE THREAD

**Issue by danielflippance** [angular-ui/bootstrap#6346]
### Bug description:
There appears to be no way to set the time of day for the datepicker. I use two date pickers for startDate and endDate where the user picks only the date, not the time, but I want the start date time in the model to be 00:00:00 and the end date time in the model to be 23:59:59

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 2.0.2

Bootstrap: 3.1.1

**Comment by wesleycho** [comment]
The only way to set it is through explicit setting of a date object in the model.

**Comment by wesleycho** [comment]
Going to close this as already doable through other means.
