### ISSUE TITLE
ng-accordion is not working

### ISSUE THREAD

**Issue by AbhiInfy** [angular-ui/bootstrap#6347]
### Bug description:
We are facing issue when trying to highlight the entity name which is getting rendered on accordion header. To make it working we need to set one attribute (searchon=”true”) to identify the element where we want highlighting functionality. Following are the problems we are facing .

If we talk about the header that’s been constructed by ng-accordian which is third party. So if we want to set the attribute we need to find the element in life cycle hook of the component using DOM manipulations.
If we manage to fix the point 1 above then we will lose the click function of the heading (if clicked on the entity name). This click function is also not controlled by us, it’s been handled by ng-accordian internally.
Note:- entity name is the only property binding to the UI of entry screen, we are filtering on the other properties (fund name, product name etc.) but not visible on UI as per current design, So highlighting will only available on entity name if above issue is resolved somehow.

I'm using ng2-accordion from below link:
https://www.npmjs.com/package/ng2-accordion

`<section class="widget-header">
    <div class="row">
        <div class="col-xs-6">
            <h1 class="widget-title">{{title}}</h1>
        </div>
        <div class="col-xs-6">
            <ul class="list-inline pull-right">
                <li>
                    <button class="btn btn-sm btn-link action-bar-toggle" (click)="isSearchBarActive = !isSearchBarActive" 
                            [ngClass]="{active: isSearchBarActive}"><i class="fa fa-search" ></i></button>
                </li>
            </ul>
        </div>
    </div>
</section>
<div class="action-bar document-search-bar row" [ngClass]="{active: isSearchBarActive}">
    <div class="col-xs-6">
        <input class="form-control input-sm document-search-form" [(ngModel)]="searchText" placeholder="Search&hellip;" (keyup)="search($event)">
    </div>
    <div class="col-xs-6">
    </div>
</div>
<div class="data-source-list" [word-highlighter]="searchText">
    <data-source-list-detail [selectedWorkItemGroup]="selectedWorkItemGroup"></data-source-list-detail>
    <div *ngIf="selectedWorkItemGroup?.workItemEntities.length !== 0" class="scrollable" >
        <accordion *ngFor="let workItemEntity of selectedWorkItemGroup.workItemEntities; let workItemEntityIndex=index" [showArrows]="true"  >
            <accordion-group heading="{{workItemEntity.entityName}}" [isOpened]="accordianGroupStats[workItemEntityIndex]"  >
                <div id="accordian-index-{{workItemEntityIndex}}" class="panel-body">
                    <form #datapoint="ngForm">
                        <div *ngFor="let workItem of workItemEntity.workItems; let workItemIndex=index">

                            <div *ngIf="workItem?.dataPointName==='Holding Performance'">
                                        <holding-performance [workItem]="workItem" [highlightPriority]="highlightPriorities[currentWorkItemIndex][priorityindex]" 
                                                    (formSubmitted)="childFormSubmitted($event)"  [loadedFirstTime]="priorityindex" [accordionGroupStats]="accordionCopy"
                                                    [processStageName]="selectedWorkItemGroup?.processStageName" [workItemIndex]="workItemEntityIndex" [currentWorkItemIndex]="currentWorkItemIndex"
                                                    name="holdingPerformance" [ngModel]="workItem">
                                        </holding-performance>
                            </div>

                            </div>
                    </form>
                     <div class="panel-footer m-t-3">
                    <div class="row">
                        <div  class="col-sm-12">
                            <button class="btn btn-sm btn-outline-primary pull-right" type="submit"  (click)="submit($event,workItemEntity,workItemEntityIndex)" [disabled]="!accordianGroupStats[workItemEntityIndex] || !datapoint.valid">Submit</button>
                            <button *ngIf="selectedWorkItemGroup?.processStageName==='Entry'" class="btn btn-sm btn-outline-defaultt" id="clearAll{{workItemEntityIndex}}" [disabled]="!accordianGroupStats[workItemEntityIndex]" (click)="clearDatapoints(workItemEntity?.workItems)">Clear</button>
                            <button *ngIf="selectedWorkItemGroup?.processStageName==='Entry'" class="btn btn-sm btn-outline-default" [disabled]="!accordianGroupStats[workItemEntityIndex] || !datapoint.valid" id="save{{workItemEntityIndex}}" (click)="save()">Save</button>
                        </div>
                    </div>
                </div>
                 
                </div>
            </accordion-group>       
        </accordion>
    </div>
</div>`

Angular:2

**Comment by pkozlowski-opensource** [comment]
> I'm using ng2-accordion from below link: https://www.npmjs.com/package/ng2-accordion

The mentioned project has _nothing_ to do with https://github.com/angular-ui/bootstrap (this repo). 

If you are looking for accordion / bootstrap widgets for Angular 2 then use https://ng-bootstrap.github.io
