### ISSUE TITLE
Error: b.DATETIME_FORMATS.STANDALONEMONTH is undefined

### ISSUE THREAD

**Issue by Mr-Anonymous** [angular-ui/bootstrap#6349]
### Bug description:
I keep getting the error `Error: b.DATETIME_FORMATS.STANDALONEMONTH is undefined` when I use the datepicker. I stripped everything out of my directive and even the bare minimum of the datepicker code like below throws this error when its loaded. Tried it from Mac:
```
return {
              restrict: 'A',
              replace: true,
              template: '<p>' +
                            '<input type="text" name="dob" class="form-control" placeholder="Date of Birth" uib-datepicker-popup />' +
                        '</p>',
          }
```
### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.8

UIBS: 2.3.0

Bootstrap: 3.3.7

**Comment by Mr-Anonymous** [comment]
The error only seems to happen with Angular 1.4.x version. The error did not show after updating Angular from 1.4.8 to 1.5.9.

**Comment by wesleycho** [comment]
The documentation mentions that it is only usable with Angular 1.5 - are you trying to use this feature with Angular 1.4, or is it erroring regardless?

**Comment by wesleycho** [comment]
Figured out exactly why this failed, will push up fix shortly & cut a release.
