### ISSUE TITLE
Error: $compile:multidir Multiple Directive Resource Contention while useng popover

### ISSUE THREAD

**Issue by ssyz1988** [angular-ui/bootstrap#6354]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
<span popover="xxx">123</span>,i just wrote this line, and it throws an error as title showed.
### Version of Angular, UIBS, and Bootstrap

Angular:
1.2.6
UIBS:

Bootstrap:
0.11.2

**Comment by ssyz1988** [comment]
<span popover="xxx">123</span> 
just one line..

**Comment by wesleycho** [comment]
Please post a Plunker - you can grab a Plunker template through the docs.

**Comment by wesleycho** [comment]
Actually, going to close as these are old versions of Angular and UI Bootstrap that we do not support
