### ISSUE TITLE
Dropdown stays selected forever

### ISSUE THREAD

**Issue by alanziberi** [angular-ui/bootstrap#6357]
### Bug description:

Dropdown stays selected and will not deselect until page is refreshed.

### Link to minimally-working plunker that reproduces the issue:

The bug can be seen on the UI Bootstrap demo page. Click any of the dropdown and then attempt to click elsewhere. You will not be able to select any other elements such as input boxes until page is refreshed.
https://angular-ui.github.io/bootstrap/

This does not happen with the previous version of UI Bootstrap (2.3.0 or 2.20).
http://angular-ui.github.io/bootstrap/versioned-docs/2.3.0/
http://angular-ui.github.io/bootstrap/versioned-docs/2.2.0/

### Version of Angular, UIBS, and Bootstrap

Angular: 1.6.0

UIBS: 2.3.1

Bootstrap: 3.3.7

**Comment by avaneerd** [comment]
I also have this problem using the same version stated as above.

**Comment by kinitawowi** [comment]
Same problem here, with UIB-2.3.1  renders any page practically useless once a drop-down has been used.. :(

Angular 1.4.14
Bootstrap 3.3.7

**Comment by Master-Inspire** [comment]
same problem here.
angular 1.5.9
Bootstrap 3.3.7
ui-bootstrap 2.3.1

**Comment by charlesdg** [comment]
Same problem

angular 1.5.9
ui-bootstrap 2.3.1

Need to rollback to 2.3.0 for the moment.

**Comment by adybionka** [comment]
Please check my comment to this issue https://github.com/angular-ui/bootstrap/issues/6364#issuecomment-267033714 . I think this is the same problem.

**Comment by cdauth** [comment]
I am running into this issue also with ui-bootstrap 2.1.4 (angular 1.5.8).
