### ISSUE TITLE
ui bootstrap context menu not working on ios

### ISSUE THREAD

**Issue by karishma2** [angular-ui/bootstrap#6359]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description: I am working on ui-grid. And added a functionality to open a context menu on long press over any column. It is working fine on android and windows devices but not working on iphone(ios). 
This is an open issue - "https://github.com/Templarian/ui.bootstrap.contextMenu/issues/9" but with no definite solution .Any help on the same would be appreciated.

### Version of Angular, UIBS, and Bootstrap

Angular:1.5

UIBS: NA

Bootstrap: 2.0

**Comment by icfantv** [comment]
Pretty sure this is a ui-grid issue as the context menu is working fine by itself on iOS.  Closing until you are able to prove this is a UIBS-specific library issue.

**Comment by icfantv** [comment]
Please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.
