### ISSUE TITLE
Is it possible use typeahead with $q.all?

### ISSUE THREAD

**Issue by prochafilho** [angular-ui/bootstrap#6361]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
The typeahead directive works great when binding the results to a single promise to be resolved. Is it possible to bind the results to a the return value of calling a promise with $q.all?
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/7pVvfp1SSeOBkMKnU9Fv?p=preview
### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.9
UIBS:
2.3.0
Bootstrap:
3.0.0

**Comment by wesleycho** [comment]
As to how Typeahead works, it requires a promise - the function can return a $q.all promise if you want, it has no real opinions other than it needs a single promise.
