### ISSUE TITLE
Bug in ui.bootstrap.modal

### ISSUE THREAD

**Issue by Zadvornyi** [angular-ui/bootstrap#6368]
Hello everyone, first of all I want to apologize for my English
I had project on Angular:1.5.7, UIBS:0.13.3, Bootstrap:3.3.6 , but after I had updated UIBS to 1.3.3. I had the bug with ui.bootstrap.modal. My code change default position for modal window. The bug is connected with modal window display, as after update the “callbacks $uibModal.open().rendered” function is fired after the template is displayed on the page. I also got blinking effect, which I did not have  with version 0.13.3.
before: 
![image](https://cloud.githubusercontent.com/assets/10829855/21181844/7f971e5e-c208-11e6-98c1-8a6857dac849.png)
- https://plnkr.co/edit/9FsLDyi0STRzlyXxRQF8?p=preview
- open console
- run code
after:
![image](https://cloud.githubusercontent.com/assets/10829855/21181645/8e688edc-c207-11e6-9f41-db06f2d00afa.png)
- https://plnkr.co/edit/l0tDbf3CGcxN1HWmbxQn?p=preview
- open console
- run code

#### Possible solutions
I investigated the code of both versions and I think I can offer possible solution. If I comment this row $q.when(animationPromise).then(function() { , it can resolve this problem

cc @wesleycho, @christopherthielen

**Comment by icfantv** [comment]
Closing per comments in rejected PR.

Your upgrade is quite a big jump.  Did you work through the breaking changes sections in ALL the versions from your old one to your new one?
