### ISSUE TITLE
Feature Request: modal component

### ISSUE THREAD

**Issue by graingert** [angular-ui/bootstrap#6374]
### Bug description: $uibModal makes it very difficult to do component architecture with a callback hierarchy 

I'd like a component:

```html
<uib-modal open="$ctrl.modalOpen" onClose="$ctrl.modalOpen = false">
  <uib-modal-header>...</uib-modal-header>
  <uib-modal-body>...</uib-modal-body>
</uib-modal>
```

**Comment by wesleycho** [comment]
This is not intended to be supported, as a declarative component is not flexible enough from a library perspective. One can already create a component that wraps the modal api provided by the library, so there should not be anything more added to the library itself, which creates api confusion & library bloat.
