### ISSUE TITLE
Unable to compile the angular-ui-boostrap typings

### ISSUE THREAD

**Issue by HackPoint** [angular-ui/bootstrap#6375]
# Attempted to compile "angular-ui-bootstrap" as a global module, but it looks like an external module. You'll need to remove the global option to continue.

Definition
"angular-ui-bootstrap": "registry:dt/angular-ui-bootstrap#0.13.3+20161212233252"##

typings -v : 1.4
typescript -v: 1.8.1

Can you explain why?

**Comment by wesleycho** [comment]
We do not maintain the typings - one would need to file the issue in the DefinitelyTyped project.
