### ISSUE TITLE
Tooltip to appear only on truncated text

### ISSUE THREAD

**Issue by seminolas** [angular-ui/bootstrap#6377]
### Bug description:

See plunker - when the width of the html pane is reduced to force ellipsis truncation, the tooltip doesn't appear on first hover, but does on second.

I realise this is may not be a bug, but my clunky use of angular. If so, I'd appreciate any clues for resolving this. Many thanks!

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/aqZq0ySiHhssy9l9ggTB?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 1.3.0

Bootstrap: 3.3.6

**Comment by adgoncal** [comment]
Try this: https://plnkr.co/edit/py8QQb?p=preview

**Comment by seminolas** [comment]
That works, thanks! Unfortunately, I'm currently stuck at an older version -it didn't work quite so well, so I went the manual route for now. Nevertheless, I think/hope someone will find this useful :-)

**Comment by Totemika** [comment]
Hi there,
I implemented this with a similar approach but I'm facing the issue that tooltip is usually center aligned so I get this effect for longer texts:

![truncated-tooltip](https://cloud.githubusercontent.com/assets/4906291/23064549/f3ba0306-f510-11e6-905f-f59468aaafb4.gif)

Have you find a workaround for this or just ignored this case?

Thanks

**Comment by Totemika** [comment]
Hi,
I used a similar approach to solve this but I am facing the issue of having the tooltip placement way too far from the text when the text is much longer than its container. 

I could reproduce this using [a fork](https://plnkr.co/edit/OHDqkm?p=preview) of @adgoncal 's Plunkr

![tooltip-issue](https://cloud.githubusercontent.com/assets/4906291/23068491/3097d45c-f524-11e6-867a-6628b4eb5df2.gif)

**Comment by adgoncal** [comment]
@Totemika 
You have `min-width: 150px` on `.truncate`
Try changing that to a smaller value.

**Comment by Totemika** [comment]
Thanks!
