### ISSUE TITLE
In iOS (iPad, iPhone) underlying page of a modal is scrollable.

### ISSUE THREAD

**Issue by menocomp** [angular-ui/bootstrap#6379]
No plunker is needed, the issue is replicated easily in the documentation. open this link [http://angular-ui.github.io/bootstrap/#/modal](url) in iPad (portrait or landscape) and click any buttons to open modal window and then try scrolling the underlying window will scroll.
This is not the case when you open it in desktop (Safari, Chrome, IE, FF) or even chrome in Android.
**Notes:**
Not reproducible in desktop Safari.
Reproducible in iOS in both Safari and Chrome.
The problem becomes even worse when the modal is really big and has its own scroll now you end up by having only one scroll that scroll two different things the modal and the underlying window.

**Comment by wesleycho** [comment]
This is not something that the library can offer any more to solve with - one must use appropriate CSS to solve this in tandem with the options to add classes in the modal service, most notably appropriate usage of `overflow: hidden` when the modal is open.
