### ISSUE TITLE
Modal does not hold focus on a textarea element

### ISSUE THREAD

**Issue by golkir** [angular-ui/bootstrap#6381]
When I click on textarea inside the modal, the focus is lost immediately. As a result, I cannot focus on textarea at all. I do not set or unset focus attribute in my code, so it is strange.

I use Angular 1.6.0, Angular UI Boostrap 2.3.1, and Bootstrap CSS 3.3.6 and Jquery 2.2.4. Together with this I have possibly unhandled rejection error from JQuery when cancel the modal.

**Comment by sandcastle** [comment]
See #6364

**Comment by golkir** [comment]
Thanks, but i don't use uib-dropdown in the modal window. I only use it when opening modal like this:
```
<div ng-if="is('client') || is('admin')" class="btn-group pull-right v-top" uib-dropdown is-open="status.isopen"
         ng-controller="ActionsCtrl">
        <button type="button" class="btn btn-primary btn-lg" uib-dropdown-toggle ng-disabled="disabled">
            Order Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li ng-if="ifCanPutOnRevision()"> <a 
            ng-click="openRevisionModal('md')">Put on revision</a></li>
            <li><a href="#deadline">Extend Deadline</a></li>
            <li> <a ng-show="order.status.completed" ng-click="leaveFeedbackModal('md')">
            Leave Feedback
            </a></li>
            <li> <a ng-click="openRefundModal('md')">
            Request Refund 
            </a></li>
            <li> <a ng-click="openCancelModal('md')">
            Cancel Order 
            </a></li>
        </ul>
    </div>
```

**Comment by wesleycho** [comment]
The only modal commit in that time frame is https://github.com/angular-ui/bootstrap/commit/8a4f625ef6cc9846f975c58f01eed32a75e85ebe, which shouldn't affect this.

If you are using a dropdown to open the modal, this is likely the regression described in #6364, which should be fixed in the freshly released 2.3.2 - let me know if this fixes the issue so we can close this out.

**Comment by MaxKorz** [comment]
2.3.2 fixed same issue for me

**Comment by wesleycho** [comment]
Closing this out as per comments/analysis - feel free to open a new issue if this isn't fixed.
