### ISSUE TITLE
ui datepicker events, on selection of a date

### ISSUE THREAD

**Issue by joshuawoodward** [angular-ui/bootstrap#639]
can we add some functionality to the scope.select, like an attribute date-select="onSelect()"

I would to perform an action when a date is selected

**Comment by mjoyce91** [comment]
I was hoping for a similar attribute out of the box to run a callback on date change. A simple solution I discovered was the following:

```
<div uib-datepicker
        ng-model="selected_date"
        ng-change="go(selected_date)">
</div>
```

Others may require some more complex, but this was enough for me.
