### ISSUE TITLE
Typeahead pre-selection index

### ISSUE THREAD

**Issue by Mathiiilde** [angular-ui/bootstrap#6390]
### Bug description:

Hi !
I face to a problem.
Using uib-typeahead directive, I would like to be able to pre-select the 2nd element of the list when I begin to type instead of the first.
I did not find out if it was possible to do that..
Thanks

**Comment by icfantv** [comment]
Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.
