### ISSUE TITLE
UI Bootsrap Datepicker - Different value for View and Model

### ISSUE THREAD

**Issue by Anu13sree** [angular-ui/bootstrap#6391]
Can you guys help me in figuring out how to assign different value for view and model. I have tried to use parser and formatters but the value is not getting assigned.

For Eg: View :- dd-MMM-yy and ng-model :- mm-dd-yyyy

Thanks in advance.

http://angular-ui.github.io/bootstrap/versioned-docs/0.13.3/#/datepicker

**Comment by icfantv** [comment]
Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.
