### ISSUE TITLE
Date Range Picker - Cannot select today date

### ISSUE THREAD

**Issue by crysthofferattier** [angular-ui/bootstrap#6395]
i'm using the last version, and my issue is i cannot select today date in my date range picker, when i select yesterday or another value then i can select today. This is normal?

**Comment by icfantv** [comment]
We do not have a date range picker in this library.

**Comment by icfantv** [comment]
Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.

**Comment by hongjanh** [comment]
of course ,this is normal. today.yesterday or anotherday.is sigle select. i think.
