### ISSUE TITLE
select function runs always.

### ISSUE THREAD

**Issue by sh977218** [angular-ui/bootstrap#6399]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
select function got called every time click tab, even if the tab is already selected.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/1kZXAhrwdftVNdR1098i?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.8

UIBS: 2.4

Bootstrap: 3.3.7

**Comment by icfantv** [comment]
This is by design and not a bug due to user requests.  You may feel free to ignore the event if your tab is already selected.
