### ISSUE TITLE
CArousel image behavior

### ISSUE THREAD

**Issue by banellaa** [angular-ui/bootstrap#6400]
### Bug description: im a beginner and the problem is that the carousel works fine except when i click the prev. control,instead of having a smooth slide, the image has some sort of a transition. i dont know how to fox this, can you please help me. here are my codes.
`
![2](https://cloud.githubusercontent.com/assets/25014621/21779200/778a1264-d6e1-11e6-82ae-89306df189d1.png)
![1](https://cloud.githubusercontent.com/assets/25014621/21779201/778dd46c-d6e1-11e6-9b6d-05e9f9ae2514.png)

`

Bootstrap:version 4

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem

Also Bootstrap 4 is not supported in this project.
