### ISSUE TITLE
Tooltip Memory Leak

### ISSUE THREAD

**Issue by matthiasdailey-ccri** [angular-ui/bootstrap#6405]
I think I've identified the cause of a memory leak in my company's app. The tooltip directive registers a keypress listener on an event, and does not remove it.

https://github.com/angular-ui/bootstrap/blob/78559761dcbd3cb20cbd458b0e27a64de516c148/src/tooltip/tooltip.js#L547-L551

This creates a jquery cache entry, which retains the scope through the context. 
For all the other listeners registered in `prepTriggers()`, they are deregistered in `unregisterListeners()`. Seems to me that the keypress listener should get deregistered too.

Before I go through the trouble of creating a plunkr, would you agree that the leak is obvious enough? The fix would be to make the keypress listener function into a named function, and deregister it at the end of the unregisterListeners function.

Thanks

**Comment by wesleycho** [comment]
This looks correct - feel free to open a PR.

**Comment by matthiasdailey-ccri** [comment]
Alright, here's a PR: https://github.com/angular-ui/bootstrap/pull/6423

Thanks!
