### ISSUE TITLE
test runs much slower from 1.3.3 to 2.0.0

### ISSUE THREAD

**Issue by sh977218** [angular-ui/bootstrap#6407]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
We use selenium to run integration test. Whole test takes about 24 minute as use version 1.1.0. After I upgrade angular-bootstrap to latest 2.4.0, whole test takes about 37 minutes to finish. I notice this and try several version to figure out which version did this. I figured out 1.3.3 is 24 minutes and 2.0.0 is 37 minutes. There are a lot changes in 2.0.0 change log. I couldn't figure out which one could be the cause of this. Is there any one having the same problem as me?

### Link to minimally-working plunker that reproduces the issue:

I cannot reproduce this issue.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 2.4.0

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.
