### ISSUE TITLE
ngCsp and datepicker-popup

### ISSUE THREAD

**Issue by EssyTech** [angular-ui/bootstrap#6419]
### Bug description:

If I include ngCsp directive the datepicker popup wont display.  If I remove the ngCsp directive the datepicker popup displays.

### Link to minimally-working plunker that reproduces the issue:

I will get a working plunker if needed.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.6.1

UIBS: 2.4.0

Bootstrap: 3.3.7

**Comment by wesleycho** [comment]
If you use ng-csp, you must include the stylesheet. You can include the specific style by requiring https://github.com/angular-ui/bootstrap/blob/master/src/datepickerPopup/popup.css or you could include ui-bootstrap.css, which is bundled with the distribution.
