### ISSUE TITLE
common bootstrap components to angular components

### ISSUE THREAD

**Issue by lcrossan** [angular-ui/bootstrap#6422]
would y'all be interested in a PR to component-ize some common bootstrap things? i'm thinking buttons, alerts, panels, and wells. 

instead of writing `<button class='btn btn-primary'>something</button>` it would be a nice convenience to have an angular component that just wraps that, so you could just say `<btn-primary></btn-primary>`. thoughts?

**Comment by jfinci1** [comment]
To me, seems like an unnecessary level of abstraction.  

Does `<btn-primary (click)="myClickHandler()>Handle Me<btn-primary>"` really save you much over  `<button class='btn btn-primary'(click)="myClickHandler()>Handle Me</button>`

**Comment by pkozlowski-opensource** [comment]
Agree with @jfinci1 - it doesn't save much typing but would limit flexibility and incur performance tax. Thnx for the suggestion but we are going to skip this one.
