### ISSUE TITLE
Timepicker - leading zero is erased in hours during input, when pad-hours is set to true

### ISSUE THREAD

**Issue by enchained** [angular-ui/bootstrap#6430]
Leading zero disappears, and then comes back after you clicked anywhere else. Try input '09' to my plunkr for example. Should it behave that way, or is it a bug? I'm having trouble using ui-mask because of this - it fails to detect 2 digits during input, and shows placeholder until I click anywhere else, and it looks confusing. 

See the default and ui-mask timepickers here: https://plnkr.co/edit/iURaci7K3sHK8J9HzN49?p=preview

[Here on the template update](https://github.com/angular-ui/bootstrap/blob/master/src/timepicker/timepicker.js#L475) it doesn't pad the hours while you're editing the hours (when keyboardChange === 'h' ), no matter what pad-hours value is:
` $scope.hours = keyboardChange === 'h' ? hours : pad(hours, !padHours);`

Is it on purpose, and why, or should it be fixed?

**Comment by icfantv** [comment]
Per the issue template, the issues forum is not for support requests.  Please read the link contained therein for how to ask for, and receive, assistance.  Thanks.
