### ISSUE TITLE
ui-datepicker loading issue firefox

### ISSUE THREAD

**Issue by raghuxseed** [angular-ui/bootstrap#6433]
ui-datepicker taking more time to load calender after clicking on icon (which initiates popup to open).This issue is found only in firefox.

**Comment by icfantv** [comment]
Please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.
