### ISSUE TITLE
"UibDateParser" in Migration guide for prefixes

### ISSUE THREAD

**Issue by nvbn** [angular-ui/bootstrap#6435]
There's a typo in Migration guide for prefixes.

"Change: dateParser for **U**ibDateParser." should be changed to "Change: dateParser for **u**ibDateParser."

**Comment by icfantv** [comment]
@nvbn please feel free to file a PR.  Thanks.

**Comment by nvbn** [comment]
I can't make pull request to wiki. The problem is in this page - https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes

**Comment by icfantv** [comment]
apologies.  fixed.
