### ISSUE TITLE
Parsing Date using timezone from ngModelOptions

### ISSUE THREAD

**Issue by ksiwak2e** [angular-ui/bootstrap#6436]
I found problem after upgrade version of anngular from 1.5.8 to 1.6.
They change structure of ngModelOptions. Now we get the option by getter.

In datepickerPopup/popup.js we have line:
`return dateParser.toTimezone(date, ngModelOptions.timezone);`
but `ngModelOptions.timezone` is undefined. In version 1.6 of angular we should use:
`ngModelOptions.options.timezone` or use getter `ngModelOptions.getOption('timezone')`.

Tha problem in gui is that date is parse valid and sometimes date in datePicker is different that this in model object.

Best regards.

**Comment by icfantv** [comment]
Please be respectful of our time and processes by adhering to the issue template.  As we are all volunteers, we simply do not have the time to chase every incomplete issue entered by users.  As such, I apologize, but I am going to close this until you comply.  Thanks.
