### ISSUE TITLE
Dropdown still uses element.bind()

### ISSUE THREAD

**Issue by sbaechler** [angular-ui/bootstrap#6444]
### Bug description:

Ui-Bootstrap Dropdown throws an exception if an app imports jQuery.slim. That version of jQuery does not have an `element.bind()` property anymore.

You could simply replace `bind` with `on`.

### Steps to reproduce the issue:

- Import jQuery.slim instead of jQuery.
- Create an angular app that uses UI-Dropdown

### Version of Angular, UIBS, and Bootstrap
- Angular: 1.5
- UI-Bootstrap: 2.5.0
- jQuery slim: 3.1

**Comment by edmorley** [comment]
This looks like it was fixed in 2.3.0?
https://github.com/angular-ui/bootstrap/commit/08b50ccb1c2daa2c8b6bf7460d310aa5638197ee

Are you sure the STR above was definitely using 2.5.0?

**Comment by edmorley** [comment]
Also that fix was missing from the 2.3.0 changelog entry:
https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md#230-2016-11-26

Would someone mind adding a "Fixed jQuery.fn.bind() deprecation warning under jquery 3" to the changelog?
