### ISSUE TITLE
Cannot select string date from datepicker popup template

### ISSUE THREAD

**Issue by mbursill** [angular-ui/bootstrap#6460]
### Bug description:
Cannot select a string date from a datepicker popup template.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/I7nTVnaDRMmcbeFEEzw7?p=preview

### Steps to reproduce the issue:
Create a custom datepicker popup template and from within it try to call `select('9999-01-01', $event)` 

### Version of Angular, UIBS, and Bootstrap
Angular: 1.6.1
UIBS: 2.5
Bootstrap: 3.3.7

**Comment by wesleycho** [comment]
String dates are not supported - see documentation [here](http://angular-ui.github.io/bootstrap/#!#datepicker)
