### ISSUE TITLE
SyntaxError: Unexpected token ' in JSON at position 0

### ISSUE THREAD

**Issue by fhqdgv** [angular-ui/bootstrap#6462]
`$ npm run demo

> angular-ui-bootstrap@2.5.1-SNAPSHOT demo C:\nodeProject\test\bootstrap
> grunt after-test && static dist -a 0.0.0.0 -H '{"Cache-Control": "no-cache, mu                                                                                                                                                             st-revalidate"}'

Running "build" task
File dist/ui-bootstrap-2.5.1-SNAPSHOT-csp.css created

Running "concat:dist" (concat) task

Running "concat:dist_tpls" (concat) task

Running "uglify:dist" (uglify) task
File dist/ui-bootstrap-2.5.1-SNAPSHOT.min.js created: 248.88 kB → 103.55 kB
>> 1 file created.

Running "uglify:dist_tpls" (uglify) task
File dist/ui-bootstrap-tpls-2.5.1-SNAPSHOT.min.js created: 250.04 kB → 104.71 kB
>> 1 file created.

Running "makeModuleMappingFile" task
File dist/assets/module-mapping.json created.

Running "makeRawFilesJs" task
File dist/assets/raw-files.json created.

Running "makeVersionsMappingFile" task
File dist/versions-mapping.json created.

Running "copy:demohtml" (copy) task
Copied 1 file

Running "copy:demoassets" (copy) task
Created 2 directories, copied 15 files

Done, without errors.
undefined:1
'{Cache-Control:
^

SyntaxError: Unexpected token ' in JSON at position 0
    at Object.parse (native)
    at Object.<anonymous> (C:\nodeProject\test\bootstrap\node_modules\.0.7.9@nod                                                                                                                                                             e-static\bin\cli.js:91:46)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\A                                                                                                                                                             ppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "demo"
npm ERR! node v6.2.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! angular-ui-bootstrap@2.5.1-SNAPSHOT demo: `grunt after-test && static d                                                                                                                                                             ist -a 0.0.0.0 -H '{"Cache-Control": "no-cache, must-revalidate"}'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-ui-bootstrap@2.5.1-SNAPSHOT demo script 'grunt af                                                                                                                                                             ter-test && static dist -a 0.0.0.0 -H '{"Cache-Control": "no-cache, must-revalid  `

The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular:

UIBS:

Bootstrap:

**Comment by wesleycho** [comment]
This appears to be a bug not in this library but in a dependency - please file the issue with the appropriate project.
