### ISSUE TITLE
problem with bootstarp3

### ISSUE THREAD

**Issue by BehnamAbdy** [angular-ui/bootstrap#6469]
hi
i've been working with n2-bootstrap since couple of months ago,every things worked well,just after updating to "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.20" the problem appeared with modal and timepicker components ,non of them open then related modal, for 90 % im sure the problem is with bootstap version because my web template is based on bootstrap 4,
is there any backword compatibility? or any other solution?

**Comment by wesleycho** [comment]
Closing as this appears to have been opened in the wrong project - I think you meant to open in https://github.com/ng-bootstrap/ng-bootstrap .
