### ISSUE TITLE
[ngbAccordion] Data loss on panel change

### ISSUE THREAD

**Issue by vinothinivenkatesan** [angular-ui/bootstrap#6474]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Link to minimally-working plunker that reproduces the issue:

```
<ngb-accordion #acc="ngbAccordion" activeIds="ngb-panel-0">
  <ngb-panel title="first">
    <template ngbPanelContent>
<`form`>
      <div class="col-md-6">
            <div class="form-group row">
                <label for="inputEmail3" class="col-md-4 form-control-label">First Name</label>
                <div class="col-md-8">
                    <input class="form-control" name="firstname" placeholder="Enter Here" type="text">
                </div>
            </div>
        </div>
</form>
</template>
 </ngb-panel>
<ngb-panel title="second">
    <template ngbPanelContent>
<form>
      <div class="col-md-6">
            <div class="form-group row">
                <label for="inputEmail3" class="col-md-4 form-control-label">Second Name</label>
                <div class="col-md-8">
                    <input class="form-control" name="secondname" placeholder="Enter Here" type="text">
                </div>
            </div>
        </div>
</form>
</template>
 </ngb-panel>
</ngb-accordion>

```
### Steps to reproduce the issue:

1. Implement accordion component from ng-bootstrap.
2. add a form with input field in each panel.
3. enter value in input field in first panel and open second panel again open first panel.
4. you can find the entered data missing in the input field

### Version of Angular, UIBS, and Bootstrap

Angular: 2.4

UIBS:

Bootstrap: 4.0.0

**Comment by WVWillHall** [comment]
https://github.com/ng-bootstrap/ng-bootstrap

**Comment by gbevan** [comment]
+1

**Comment by wesleycho** [comment]
Closing as opened in the wrong repository as @WVWillHall pointed out.

One thing that might help though is that you should be using `ngModel` on the inputs - this is most likely a usage issue.
