### ISSUE TITLE
unix timestamp from server and back also as timestamp

### ISSUE THREAD

**Issue by peckomingo** [angular-ui/bootstrap#6477]
If get a timestamp from the server and then want to display the date for the user in "yy-mm-dd" format also when he changes the date. However, when he sends the form the date should ge send as timestamp again. 

I tried to accomplish this with $parsers and my code looks something like this.
`var parseDate = function(value) {

    if(value instanceof Date) {
        var timestamp = value.getTime();
        return timestamp;
    } else return "";
};
ngModel.$parsers.push(parseDate);`

But the date gets send as something like `2017-02-19T23:00:00.000Z` in the network tab.

Is there anything wrong with the plugin and handling timestamps?

**Comment by wesleycho** [comment]
This library does not support strings for the model - please convert it to a date object as per docs for datepicker.
