### ISSUE TITLE
uib-typeahead doesn't close on blur on Safari iPhone/iPad

### ISSUE THREAD

**Issue by carolineBda** [angular-ui/bootstrap#6478]
### Bug description:
When typeahead is opened on a iPhone (safari) you can click any where on the page it doesn't closed.

### Link to minimally-working plunker that reproduces the issue:
https://jsfiddle.net/carolineBda/rc88cb48/2/

### Steps to reproduce the issue:

- Open the jsfiddle on an iPhone 6 in Safari
- type anything in the field
- click elsewhere: the dropdown stay opened

### Version of Angular, UIBS, and Bootstrap

Angular: 1.6.1

UIBS: 2.5.0

**Comment by LCousot** [comment]
I have the same issue. Could anybody help ? Thank you

**Comment by carolineBda** [comment]
Hello,

I've noticed that it is working on the demo website (dropdown close when clicking elsewhere on an iPhone):
https://angular-ui.github.io/bootstrap/#!#typeahead

Would you know why it is not behaving the same on the jsfiddle ?

**Comment by carolineBda** [comment]
I found a fix for my problem which solve the closing of the dropdown and also the tooltips on iPhone and iPad. 

I've just added on mobile devices the css rule:
`body { cursor: pointer; }`

That's it!
