### ISSUE TITLE
uib-pagination not work in uibModal

### ISSUE THREAD

**Issue by xiyuyizhi** [angular-ui/bootstrap#6488]
i am use uib-pagination in an modal that use uibModal,but the pagination can only show 1,total-items are not work

**Comment by roger2hk** [comment]
Need help using UI Bootstrap?

-  Live help in the IRC (`#angularjs` channel at the `freenode` network). Use this [webchat](https://webchat.freenode.net/) or your own IRC client.
- Ask a question in [StackOverflow](http://stackoverflow.com/) under the [angular-ui-bootstrap](http://stackoverflow.com/questions/tagged/angular-ui-bootstrap) tag.

**Please do not create new issues in this repository to ask questions about using UI Bootstrap**
