### ISSUE TITLE
bs-options is not showing the complete suggestion list

### ISSUE THREAD

**Issue by singhreetesh** [angular-ui/bootstrap#6514]
I am using bs-typhead and bs-options to bind a collection of string having around 400 values.
I typeahead is showing just 5 to 6 string from the above suggestion list.

Please help!

Angular: v1.5.6

Bootstrap: bootstrap.js v3.0.0

angular-strap @version v2.3.9 - 2016-06-10

**Comment by pkozlowski-opensource** [comment]
Wrong repo
