### ISSUE TITLE
Bootstrap 3?

### ISSUE THREAD

**Issue by im1dermike** [angular-ui/bootstrap#6522]
There is AngularUI for Angular 1.x and ngBootstrap for Angular 2.x and Bootstrap 4, but no support for Angular 2.x and Bootstrap 3?  Bootstrap 4 is still in alpha.

**Comment by pkozlowski-opensource** [comment]
@im1dermike please see our thinking on Bootstrap 3 for Angular 2: https://github.com/ng-bootstrap/ng-bootstrap/wiki/Why-Bootstrap-4-only%3F
