### ISSUE TITLE
Bootstrap pagination does not work with angular-ui-bootstrap/2.5.0/ui-bootstrap-tpls.js

### ISSUE THREAD

**Issue by chengtie** [angular-ui/bootstrap#6527]
Because of [this thread](http://stackoverflow.com/a/43568412/702977), I need to use a high version of `ui-bootstrap-tpls.js`. However, I realise that this disabled `bootstrap pagination`, which works with a lower version of `ui-bootstrap-tpls.js`.

For example, [this pagination works](http://plnkr.co/edit/J2DzS6YHvu1LRKSEvRLv?p=preview) with `https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.0/ui-bootstrap-tpls.js`, whereas `https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/2.5.0/ui-bootstrap-tpls.js` [does not work](http://plnkr.co/edit/wPwBgatEivCvnqun8Z93?p=preview).

Does anyone know what I could do?

**Comment by jeffcarey** [comment]
See the docs at https://angular-ui.github.io/bootstrap/, the tag changed since 0.11. You need to replace <pagination> with <ul uib-pagination>.

**Comment by chengtie** [comment]
It works, thank you...
