### ISSUE TITLE
UI Boostrap for Bootstrap 4

### ISSUE THREAD

**Issue by matheusggds** [angular-ui/bootstrap#6535]
Is there a support for Bootstrap 4 using Angular 1.x ?

**Comment by pkozlowski-opensource** [comment]
No, but there is Bootstrap 4 version for Angular 2+: https://ng-bootstrap.github.io/#/home

**Comment by kukac7** [comment]
@matheusggds topic: https://github.com/angular-ui/bootstrap/issues/4234

**Comment by pkozlowski-opensource** [comment]
Yeh, this is direct duplicate of #4234
