### ISSUE TITLE
$uibModal does not work on Chrome(Android)

### ISSUE THREAD

**Issue by emrealparslan93** [angular-ui/bootstrap#6537]
I'm trying to display a modal. It works on computer browsers such as Safari, Chrome, Firefox... But same modal does not work on Chrome Android. Nothing happens when I click trigger button. Here is my codes.

     $scope.openModalDetail = function(ticket) {
        var modalInstance = $uibModal.open({
            animation: true,
            templateUrl: 'modalDetail.html',
            controller: 'ModalControllerDetail',
            size: 'lg',
            windowClass: 'center-modal',
            resolve: {
                shop: function() {
                    return $scope.shop;
                },
                ticket: function() {
                    return ticket;
                }
            }
        });
     };

    angular.module('MetronicApp').controller('ModalControllerDetail', function($scope,    $uibModalInstance, ticket, shop, SweetAlert, TicketService, NgTableParams) {

    $scope.shop = shop;
    $scope.ticket = ticket;
    $scope.shopid = $scope.shop._id;
    $scope.defaultLanguage = $scope.shop.defaultLanguage;

    $scope.tableParams = new NgTableParams({
        sorting: {
            sent_at: "desc"
        }
    }, {
        dataset: $scope.ticket.items
    });

    $scope.ok = function() {
        $uibModalInstance.dismiss('cancel');
    };

    $scope.cancel = function() {
        $uibModalInstance.dismiss('cancel');
    };
    });

    <script type="text/ng-template" id="modalDetail.html">
    <div class="modal-header" style="padding: 0px;">
        <div class="btn-group btn-group btn-group-justified">
            
            <a ng-click="setStatus(false)" class="btn btn-lg grey-mint" ng-if="ticket.open" translate> Close Ticket </a>
            <a ng-click="setStatus(true)" class="btn btn-lg blue" ng-if="!ticket.open" translate> Open Ticket </a>
            <a ng-click="delete()" class="btn btn-lg red" translate> Delete Ticket </a>
        </div>
    </div>
    <div class="modal-body">
    </div>
    </script>

Angular: ^1.5.3

UIBS: ^1.3.3

Bootstrap: ~3.3.2

**Comment by wesleycho** [comment]
Please post a minimal Plunker that demonstrates the issue.

**Comment by emrealparslan93** [comment]
I figured out what causes to this problem. Sorry for confusion. @wesleycho
