### ISSUE TITLE
UIB-popover displays incorrectly when pointing to an element in a UIB-accordion

### ISSUE THREAD

**Issue by Nokel81** [angular-ui/bootstrap#6539]
### Bug description:
When placing a uib-popover tag on an a table cell element within a uib-accordian-group the popover gets does not display incline to where the text is rendered.

### Link to minimally-working plunker that reproduces the issue:
Code: 
```html
<uib-accordion close-others="true">
    <div uib-accordion-group class="panel-default" ng-repeat="grouping in groupings track by $index" heading="{{grouping.parent}}" is-open="grouping.isOpen">
        <table>
            <tr ng-repeat="group in grouping.children">
                <td>
                    <div class="clickable unselectable" href="#" ng-click="setCurrentFigure(group)" uib-popover="{{definitons[group]}}" popover-trigger="'mouseenter'" popover-placement="right">{{group}}</div>
                    <hr class="fancy">
                </td>
            </tr>
        </table>
    </div>
</uib-accordion>
```

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 2.5.0

Bootstrap: 3.3.7

Gif showing example:
![capture](https://cloud.githubusercontent.com/assets/8225332/25821843/a838ad78-3404-11e7-8750-80462f4361a8.gif)

**Comment by WVWillHall** [comment]
You didn't provide a plnkr so I can;t confirm this, but usually the solve for these issues is popover-append-to-body
