### ISSUE TITLE
Datepicker not opening on pre-populated date

### ISSUE THREAD

**Issue by DeanWilliamMills** [angular-ui/bootstrap#6556]
If the ng-model has a value (populated from the database) and you open the datepicker it opens on today's date and not on the ng-model date. When you close the datepicker and open it again then it opens on the pre-populated date. So it only happens the first time you open the datepicker

**Comment by WVWillHall** [comment]
Sounds like a race condition to me. 

You try adding an ng-init and explicitly setting the model yet?

**Comment by DeanWilliamMills** [comment]
@WVWillHall 
Thanks for the reply.
I also tried adding ng-init, but still doesn't work.

Here is my code snippet:

Controller:
`$scope.testDate = new Date($scope.date.getFullYear() - 10, $scope.date.getMonth(), 1);`

HTML:
`<input ng-model="testDate" type="text" readonly class="form-control" uib-datepicker-popup="{{datepickerOptions.format}}" is-open="datepickerToggle" />`

**Comment by WVWillHall** [comment]
working for me.

https://plnkr.co/edit/e5zD5MlP7GvVFCRASjNv?p=preview

**Comment by DeanWilliamMills** [comment]
@WVWillHall thanks for your help. I realized I was not on the latest version. After updating to the latest version the issue was resolved.
