### ISSUE TITLE
min-date and max-date not working in v2.5

### ISSUE THREAD

**Issue by philwronski** [angular-ui/bootstrap#6562]
Hi,

I have a problem with min-date and max-date, when i try to make a daterange.
`
 <input
                                            type="text"
                                            class="form-control"
                                            uib-datepicker-popup="MM/yyyy"
                                            ng-model="projectForm.project.start_date"
                                            is-open="projectForm.datepicker.start_date.opened"
                                            max-date="projectForm.project.end_date"
                                            datepicker-options="projectForm.datepicker.start_date.options"
                                            ng-required="true"
                                            close-text="Close" />
        
                                    <input
                                            type="text"
                                            class="form-control"
                                            uib-datepicker-popup="MM/yyyy"
                                            ng-model="projectForm.project.end_date"
                                            is-open="projectForm.datepicker.end_date.opened"
                                            min-date="projectForm.project.start_date"
                                            datepicker-options="projectForm.datepicker.start_date.options"
                                            ng-required="true"
                                            close-text="Close" />
`
This bug with angular 1.6.4 and ui-bootstrap 2.5
Sorry for my english.

Thanks

**Comment by WVWillHall** [comment]
>Apart from the previous settings, to configure the uib-datepicker you need to create an object in Javascript with all the options and use it on the datepicker-options attribute:

**Comment by philwronski** [comment]
Thanks for your reply.
I understand but when i want one datepicker (min-date) depends on another (selected date) nothing work.

<input
                                        type="text"
                                        class="form-control"
                                        uib-datepicker-popup="MM/yyyy"
                                        ng-model="projectForm.project.start_date"
                                        is-open="projectForm.datepicker.start_date.opened"
                                        datepicker-options="projectForm.datepicker.start_date.options"
                                        ng-required="true"
                                        close-text="Close" />

<input
                                        type="text"
                                        class="form-control"
                                        uib-datepicker-popup="MM/yyyy"
                                        ng-model="projectForm.project.end_date"
                                        is-open="projectForm.datepicker.end_date.opened"
                                        min-date="projectForm.project.start_date"
                                        datepicker-options="projectForm.datepicker.end_date.options"
                                        ng-required="true"
                                        close-text="Close" />

**Comment by philwronski** [comment]
I solve my problem.
I think there is a problem between angular 1.6.4 and ui-boostrap 2.5.0 with attribute min-date or with datepicker-options.

For 2 datepicker with dt1.maxDate depends on dt2.selectedDate:
`
<input
                                            type="text"
                                            class="form-control"
                                            name="start_date"
                                            uib-datepicker-popup="MM/yyyy"
                                            ng-model="projectForm.project.start_date"
                                            is-open="projectForm.datepicker.start_date.opened"
                                            datepicker-options="{'minMode': 'month', 'maxDate': projectForm.project.end_date}"
                                            ng-required="true"
                                            close-text="Close" />
`
`
<input
                                            type="text"
                                            class="form-control"
                                            uib-datepicker-popup="MM/yyyy"
                                            ng-model="projectForm.project.end_date"
                                            is-open="projectForm.datepicker.end_date.opened"
                                            datepicker-options="{'minMode': 'month', 'minDate': projectForm.project.start_date}"
                                            ng-required="true"
                                            close-text="Close" />`

It is necessary to pass the options in attribute datepicker-options directly. Not with variable or attribute (ex min-date)
