### ISSUE TITLE
Angularjs ui draggable not working when js order changes

### ISSUE THREAD

**Issue by VenkatShoreGroup** [angular-ui/bootstrap#6614]
Hi ,
a.Working scenario of order js files
1.Angularjs
2.Jquery

b.Not working scenario of order js files
1.Jquery
2.Angularjs

Please suggest in both scenarios it is workable.please send the code also ASAP.
@Netflix
Thanks,
Venkat

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#got-a-question-or-problem
