### ISSUE TITLE
uibModal issue: mask layer could not cover content below 

### ISSUE THREAD

**Issue by JoeyLi-1** [angular-ui/bootstrap#6644]
Hi There,

I met a wired issue, this issue occurred on some PC, but others works fine(even same browsers).
This issue only occurred on Chrome. The most wired thing is some pages have such issue but some others don`t. All those pages have almost the same code.
I don`t know why, so hope someone could give me some suggestions. Thank you very much!

First, I have a workaround to solve this issue by add these styles:
`.modal-body,
.modal-footer,
.modal-header {
    background-color: white;
}

.modal-backdrop{
    background-color: rgba(0, 0, 0, .99);
}
`
This is a screenshot of what happened:
![image](https://user-images.githubusercontent.com/20162464/30962393-2316cf56-a47c-11e7-8ab1-63cf4179c2b2.png)

### Version of Angular, UIBS, and Bootstrap
Angular:1.5.9

UIBS:1.3.3

Bootstrap:3.3.5

**Comment by cmartin81** [comment]
Did you find a solution for this?

**Comment by JoeyLi-1** [comment]
Hi @icfantv, 
Could you please review this issue? Thank you!

**Comment by icfantv** [comment]
@JoeyLi-1 apologies, but this project is no longer being maintained.

**Comment by JoeyLi-1** [comment]
Ooops! Okay, I will close this issue and just treat the workaround as solution. Anyway, thank you!
