### ISSUE TITLE
Datepickerpopup with ng-model not set from input on first open 

### ISSUE THREAD

**Issue by ElijahAdams** [angular-ui/bootstrap#6647]
With bare minimum set up. The ng-model value is not reflecting in the datepickerpopup calendar after the first pass when a date is keyed into the input field. 
Plunker: http://plnkr.co/edit/8lFSEwGZSiQCrON8Xuus?p=preview
Steps to recreate
1. Input date with the input field. Format is YYYY-MM-DD
2. Blur off the input field.
3. Use Open button to view the calendar. 
4. Observe the date is incorrect.**************************
5. close the calendar and re-open, Observe the date of the calendar popup is now correct. 

For some reason this issue does not occur with other versions of ui-bootstrap like 2.5.0. 
However I am using 0.14.3.

**Comment by icfantv** [comment]
closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
