### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by neemanjabu** [angular-ui/bootstrap#6648]
Tooltip function `showTooltipBind` checks for enabled exp prior showing tooltip and cancels show if tooltip is not enabled. `hideTooltipBind` function does not check this exp, therefore triggers unnecessary rootscope digest even though tooltip is not shown.
showTooltipBind
https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L222
hideTooltipBind
https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L241

**Comment by icfantv** [comment]
closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
