### ISSUE TITLE
Travis-CI build failed because it automatically routed the builds to Ubuntu Trusty

### ISSUE THREAD

**Issue by angelina999990** [angular-ui/bootstrap#6649]
Travis-ci build failed because it automatically routed the builds to Ubuntu Trusty, which is the Ubuntu distribution used by default now.  However, the builds is supposed to work in Ubuntu Precise which has reached the end of life.

check following
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming

related Issue
https://github.com/angular-ui/bootstrap/pull/6624

**Comment by icfantv** [comment]
Looking into this.  Thanks.

**Comment by icfantv** [comment]
That's not why the build failed.  I'm pretty sure it's this:  https://github.com/jasmine/jasmine/issues/1327

**Comment by icfantv** [comment]
Ok, I've played around with this for an hour and I'm calling it.  I don't have time to debug this.  If you want to, please feel free.  I've tried both `precise` and `trusty` as well as the timeout/retry settings in the issue above and pinning `jasmine-core` at `2.5.2`, none of which works.  Maybe there's a magic combination that gets it passing, and maybe there's not.  This project is EOL'd and there was a 9 month span between the last successful build and the first failed one.
