### ISSUE TITLE
Viewport height suggestion

### ISSUE THREAD

**Issue by Igcorreia** [angular-ui/bootstrap#6651]
I have been using this for a while and would like to share as a suggestion:

`
 .vh-100{
    min-height:100vh;
  }
  .vh-90{
    min-height:90vh;
  }
  .vh-80{
    min-height:80vh;
  }
  .vh-70{
    min-height:70vh;
  }
  .vh-60{
    min-height:60vh;
  }
  .vh-50{
    min-height:50vh;
  }
  .vh-40{
    min-height:40vh;
  }
  .vh-30{
    min-height:30vh;
  }
  .vh-20{
    min-height:20vh;
  }
  .vh-10{
    min-height:10vh;
  }
  @media (min-width: 576px){
    .vh-sm-100{
      min-height:100vh;
    }
    .vh-sm-90{
      min-height:90vh;
    }
    .vh-sm-80{
      min-height:80vh;
    }
    .vh-sm-70{
      min-height:70vh;
    }
    .vh-sm-60{
      min-height:60vh;
    }
    .vh-sm-50{
      min-height:50vh;
    }
    .vh-sm-40{
      min-height:40vh;
    }
    .vh-sm-30{
      min-height:30vh;
    }
    .vh-sm-20{
      min-height:20vh;
    }
    .vh-sm-10{
      min-height:10vh;
    }
  }
  @media (min-width: 768px){
    .vh-md-100{
      min-height:100vh;
    }
    .vh-md-90{
      min-height:90vh;
    }
    .vh-md-80{
      min-height:80vh;
    }
    .vh-md-70{
      min-height:70vh;
    }
    .vh-md-60{
      min-height:60vh;
    }
    .vh-md-50{
      min-height:50vh;
    }
    .vh-md-40{
      min-height:40vh;
    }
    .vh-md-30{
      min-height:30vh;
    }
    .vh-md-20{
      min-height:20vh;
    }
    .vh-md-10{
      min-height:10vh;
    }
  }
  @media (min-width: 992px){
   .vh-lg-100{
      min-height:100vh;
    }
    .vh-lg-90{
      min-height:90vh;
    }
    .vh-lg-80{
      min-height:80vh;
    }
    .vh-lg-70{
      min-height:70vh;
    }
    .vh-lg-60{
      min-height:60vh;
    }
    .vh-lg-50{
      min-height:50vh;
    }
    .vh-lg-40{
      min-height:40vh;
    }
    .vh-lg-30{
      min-height:30vh;
    }
    .vh-lg-20{
      min-height:20vh;
    }
    .vh-lg-10{
      min-height:10vh;
    }
  }
  @media (min-width: 1140px){
    .vh-xl-100{
      min-height:100vh;
    }
    .vh-xl-90{
      min-height:90vh;
    }
    .vh-xl-80{
      min-height:80vh;
    }
    .vh-xl-70{
      min-height:70vh;
    }
    .vh-xl-60{
      min-height:60vh;
    }
    .vh-xl-50{
      min-height:50vh;
    }
    .vh-xl-40{
      min-height:40vh;
    }
    .vh-xl-30{
      min-height:30vh;
    }
    .vh-xl-20{
      min-height:20vh;
    }
    .vh-xl-10{
      min-height:10vh;
    }

  
`

**Comment by icfantv** [comment]
@Igcorreia closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
