### ISSUE TITLE
Release 2.5.3 in Npm Build with Error

### ISSUE THREAD

**Issue by frekele** [angular-ui/bootstrap#6654]
angular-ui-bootstrap release 2.5.3 version is break.

The 'dist' directory contains snapshot version:
node_modules/angular-ui-bootstrap/dist/ui-bootstrap-2.0.0-SNAPSHOT.js
node_modules/angular-ui-bootstrap/dist/ui-bootstrap-2.0.0-SNAPSHOT.min.js
node_modules/angular-ui-bootstrap/dist/ui-bootstrap-2.0.0-SNAPSHOT.min.js
node_modules/angular-ui-bootstrap/dist/ui-bootstrap-2.0.0-SNAPSHOT-csp.css
node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls-2.0.0-SNAPSHOT.js
node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls-2.0.0-SNAPSHOT.min.js

No exist stable release builds.

After update my project, this is breaking my build.

I hope I have helped.

**Comment by frekele** [comment]
@icfantv

**Comment by icfantv** [comment]
I'm on it.  Sorry about that.  We just wanted to get the new README/project status out there.

**Comment by DenisDremkov** [comment]
change temporarily until an error is fixed

require('./dist/ui-bootstrap-tpls');
module.exports = 'ui.bootstrap';

=>

require('./dist/ui-bootstrap-tpls-2.5.4');
module.exports = 'ui.bootstrap';

**Comment by icfantv** [comment]
I think this should be fixed.  This is why everyone should have precise build/release instructions....which we did not.  :-o
