### ISSUE TITLE
How to disable closing popover/tooltip when escape key pressed

### ISSUE THREAD

**Issue by fiftin** [angular-ui/bootstrap#6657]
I found hard coded listener for escape key event:
```javascript
    function keypressListener(e) {
      if (e.which === 27) {
        var last = openedTooltips.top();
        if (last) {
          last.value.close();
          last = null;
        }
      }
    }
```
Is there a way to prevent closing popover/tooltip when escape key pressed?

Now I simply commented this listener in angular-ui source code because not found other solution.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.

**Comment by fiftin** [comment]
May be anybody continuous his own branch? I can join to develop. This is very useful library. We use it in our product.
