### ISSUE TITLE
Multiple tabs have the "active" class set when using UI Router and Bootstrap

### ISSUE THREAD

**Issue by jeremy-jameson** [angular-ui/bootstrap#6662]
I encountered an issue where multiple tabs appear selected when using UI Router's **ui-sref-active** directive with UI Bootstrap tabs. It seems to be related to the use of nested states and nested views.

Here's a Plunk that reproduces the unexpected behavior:

[http://plnkr.co/edit/Xm213M?p=preview](http://plnkr.co/edit/Xm213M?p=preview)

Here's another Plunk that does not use UI Bootstrap and consequently demonstrates the expected behavior:

[http://plnkr.co/edit/XXsM8h?p=preview](http://plnkr.co/edit/XXsM8h?p=preview)

I've attempted a considerable amount of debugging -- including setting a breakpoint on the `<li`> attributes modification -- but all I've been able to determine thus far is that the "active" class on the first tab is mistakenly added during the digest cycle (it does not appear to be set in the first pass through the **uiSrefActive** directive).

Any assistance (with a workaround or a fix) would be greatly appreciated.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.

**Comment by jeremy-jameson** [comment]
Yeah...I saw the notice, but when I subsequently looked at the Releases in GitHub, I noticed some recent versions. Upon further inspection, I see those Releases are probably "junk" (meaning not really intended for people to use).

Oh well, it was worth a shot. Our project is currently being upgraded to Angular 4 -- so hopefully I can find a temporary workaround to "limp by on" in the meantime.
