### ISSUE TITLE
angular-ui bootstrap second modal will trigger white ghost block in Chrome

### ISSUE THREAD

**Issue by frankpolkm** [angular-ui/bootstrap#6663]
Can anyone help with the issue?  https://stackoverflow.com/questions/46896843/angular-ui-bootstrap-second-modal-will-trigger-white-ghost-block-in-chrome

So sad to notice the project is discontinued. : (

Thanks,
Frank

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
