### ISSUE TITLE
Allocation of CSS ID to modal window

### ISSUE THREAD

**Issue by gauravbhusare** [angular-ui/bootstrap#6665]
I am unable to provide css id to modal window. I want id to be get allocated to following div
`<div id="addD" modal-render="true" tabindex="-1" role="dialog" class="modal fade ng-isolate-scope in" uib-modal-animation-class="fade" modal-in-class="in" ng-style="{'z-index': 1050 + index*10, display: 'block'}" uib-modal-window="modal-window" index="0" animate="animate" modal-animation="true" style="z-index: 1050; display: block;">`

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
