### ISSUE TITLE
popover does not position itself correctly

### ISSUE THREAD

**Issue by Peter-Optiway** [angular-ui/bootstrap#6667]
```html
<div class="container">
  <div class="row">
    <div class="col-xs-offset-1 col-xs-1">
      <button uib-popover="text wont fit on one line" popover-placement="top" type="button" class="btn btn-default">Inside</button>
      </div>
  </div>
</div>
```

This worked correctly in a older version of ui-bootstrap.
(Tested in IE, Edge, Chrome)
https://plnkr.co/edit/SDBsPANUYPydQxaL5UqU?p=preview
![image](https://user-images.githubusercontent.com/29247423/32719378-768b3426-c860-11e7-9d02-28dc225a4b1e.png)

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
