### ISSUE TITLE
Add support for popover-append-to

### ISSUE THREAD

**Issue by Peter-Optiway** [angular-ui/bootstrap#6668]
Just like `dropdown` has `dropdown-append-to` it would be nice if the `popover` had the same attribute.

Lets say you add a `popover` to a element that's inside a "col-xs-1" then the popover won't grow bigger than the parent container.

If i add `popover-append-to-body` then it can grow, but if there is a scrollbar inside some parent container that's not the body tag, then the popover does not follow with the scroll.
If we had `popover-append-to=".row"` then it should scroll correctly and allow it to dynamically adjust its width based on the content.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
