### ISSUE TITLE
uib-datepicker-popup and timezone doesn't work for minDate and currentDate

### ISSUE THREAD

**Issue by dk8996** [angular-ui/bootstrap#6671]
It seems like minDate + timezone for uib-datepicker-popup doesn't work correctly.  It works correctly for the inline version of datepicker.

Here are the examples, Works best when your browser is in EST timezone.

[plnkr example](https://plnkr.co/edit/CHcXCITbIJeB7XKp3Ckw?p=preview)

**Version of Angular, UIBS, and Bootstrap**

Angular: 1.6.x

UIBS: 2.5.0

Bootstrap: 3.x

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.

**Comment by noullet** [comment]
Thanks for your example @dk8996 , I think I found and solved the issue. If you are interested, you will find all the information in: https://github.com/angular-ui/bootstrap/issues/6235#issuecomment-378989429
