### ISSUE TITLE
how to add our custom icon(.svg image) to <p-tabPanel> of ngprime in leftIcon attribute

### ISSUE THREAD

**Issue by sridhark158** [angular-ui/bootstrap#6673]
# PLEASE READ

As per the [README](https://github.com/angular-ui/bootstrap/blob/master/README.md), this project is no longer being maintained.  Any issues entered will remain uninvestigated and unresolved.

We thank you for your contributions over the years.  This library would not have been successful without them.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
