### ISSUE TITLE
In<p-multiSelect > of prime ng throws error while selecting  checkbox from the dropdown in google chrome

### ISSUE THREAD

**Issue by sridhark158** [angular-ui/bootstrap#6674]
![bug](https://user-images.githubusercontent.com/32831520/33765214-cd09abde-dc3d-11e7-8a77-d9b1d6d9cfae.jpg)

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
