### ISSUE TITLE
fix for popover-trigger not firing on mouseenter

### ISSUE THREAD

**Issue by titocr** [angular-ui/bootstrap#6675]
Hopefully this will help someone on this now-orphaned project...

We realized that popover-trigger="mouseenter" was no longer working. Ultimately the fix is to wrap the attribute inside of single-quotes and then in double-quotes, so it ends up like this: popover-trigger="'mouseenter'"

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
