### ISSUE TITLE
preventing tab from opening

### ISSUE THREAD

**Issue by amitdangwal** [angular-ui/bootstrap#6676]
Hi Team,

angularjs version 1.6.6
angular ui version: 2.5.0
jquery:2.2.4
concern:
I have scenario where I have uibtabset with 4 tabs in it. Every tab has some data and if user modifies any tab data then he/she should be shown a message to save tab before opening other tab. This message(through uibmodal) should come when user click on other tab. If user does not save the changes then he/she should not be allowed to move to other tab. Problem is UIBModal with message to save changes appear when user click on the other tab but the tab also gets changed(to the one user selected) while modal window is shown to user. This should not happen as user focus is moved to other tab. 
 
I need inputs on this. It seem to be already discussed on this platform before but still issue seem to exist or probably I am not able to understand how to use it. Here below threads I have read.
https://github.com/angular-ui/bootstrap/issues/2715
https://github.com/angular-ui/bootstrap/issues/5720

Here below things I have tried (stopPropagation(), preventDefault(), defaultPrevented()) in following
ng-click 
deselect
select

Nothing worked and other tab still opening.

So is this bug ? It is mentioned that this functionality is added in #5720,#5723

I also tried to implement solution by "larvanitis" in issue #2715 but that is also not working correctly.

Please see if anyone can share some input. I have gone through examples of tabs, stackoverflow etc.

Amit

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.

**Comment by amitdangwal** [comment]
Sincere apology as I did not read the project status. I thought this is an active version. I am using this library. Still if you can give me some pointer on the issue then it will be of great help. If my response has again open the ticket then I sincerely apologize and I will not comment back. Thank you for your efforts Adam.
