### ISSUE TITLE
Modal stack until click in somewhere on the screen

### ISSUE THREAD

**Issue by johnico** [angular-ui/bootstrap#6677]
I am using $uibmodal , with 2 buttons close and cancel(in the component). the problem is that when the popup is triggered while refreshing the page or other triggered. I need to resize the window or click on somewhere in the page. only then the button are being clickable

```
function opentestmodal()
    {
        $rootScope.testmodal = $uibModal.open( {
            animation: true,
            backdrop:'static',
            component: 'testmodalComponent',
            windowClass: "testmodalPopupClass",
            windowTopClass: "toptestmodalPopupClass",
        });

        $rootScope.testmodal.result.then(function () {

        }, function () {
        });
    }
```
it release the buttons even if I click on the chrome address bar

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
