### ISSUE TITLE
Open new suggestion list in typeahead

### ISSUE THREAD

**Issue by EngMyWorld** [angular-ui/bootstrap#6679]
In uib-typeahead, I am fetching list of suggestions for typeahead drop down from a service call. On selection of an option by the user, I need to to display a second list of options attached to same text box as the previous one. I can keep a flag and update the list to be returned from the function call returned to the typeahead attribute by setting/resetting the flag in the function against typeahead-on-select.

Please suggest, how can I force the drop down options to open/display again when the user selects the option from first suggestion list?

`<input class="form-control" id="typeAhead" type="text" placeholder="Type an address" ng-model="$ctrl.selectedItem" uib-typeahead="items as items.FormattedString for items in $ctrl.querySearch($viewValue)" typeahead-on-select="$ctrl.onSelect($item, $model, $label)">
`

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
