### ISSUE TITLE
uibModal overlays the entire body. How to overlay just the appended div?

### ISSUE THREAD

**Issue by akcasoy** [angular-ui/bootstrap#6681]
My modal dialog html is appended to an element. But the style of modal and overlay is exactly same as before, the overlay covers entire body. How can i define my uibModal (or style the css) so that the dialog and overlay just fits in the div of my element?

Thanks a lot in advance!

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
