### ISSUE TITLE
uib date picker popup to be displayed in full screen width for mobile screen

### ISSUE THREAD

**Issue by technocraze** [angular-ui/bootstrap#6685]
Hi,

In desktop browser, the uib datepicker popup is displayed as configured. (either bottom top etc).

But in mobile screen, i want the popup to be displayed as full width.

current display
![datepicker popup](https://user-images.githubusercontent.com/1130869/35742807-aa69a908-0861-11e8-98cc-2c63d64360f6.png)

what i wanted..
![datepicker new](https://user-images.githubusercontent.com/1130869/35742822-ba4d13be-0861-11e8-8430-8610e3eded95.png)

i tried modifying the CSS, but its not positioning properly.

Can any one please help?

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
