### ISSUE TITLE
Slider are not showing it is coming in a single list

### ISSUE THREAD

**Issue by tanmay9dutta** [angular-ui/bootstrap#6686]
My app.module.

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { routes } from './app.routing';
import { HeaderComponent } from './shared/header/header.component';
import { FooterComponent } from './shared/footer/footer.component';
import { enableProdMode } from '@angular/core';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
debugger;
enableProdMode();
@NgModule({
    imports: [BrowserModule, NgbModule.forRoot(), FormsModule, RouterModule.forRoot(routes)],
    declarations: [AppComponent, FooterComponent, HeaderComponent],
    bootstrap: [AppComponent],
    providers: [NgbModule]
})
export class AppModule {
    constructor(config: NgbModule) {
        // customize default values of carousels used by this component tree
       
    }
}  

app.component.html
<header-cmp></header-cmp>
<ngb-carousel>
    <ng-template ngbSlide>
        <img src="https://lorempixel.com/900/500?r=1" alt="Random first slide">
        <div class="carousel-caption">
            <h3>First slide label</h3>
            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
    </ng-template>
    <ng-template ngbSlide>
        <img src="https://lorempixel.com/900/500?r=2" alt="Random second slide">
        <div class="carousel-caption">
            <h3>Second slide label</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
    </ng-template>
    <ng-template ngbSlide>
        <img src="https://lorempixel.com/900/500?r=3" alt="Random third slide">
        <div class="carousel-caption">
            <h3>Third slide label</h3>
            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
    </ng-template>
</ngb-carousel>
<router-outlet></router-outlet>
<footer-cmp></footer-cmp>

app.component.ts

import { Component } from '@angular/core';
import { OnInit } from '@angular/core';

@Component({
    selector: 'app-initializer',
    templateUrl: './app.component.html'
})

export class AppComponent {
    title = 'abc';

}

index.html

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Abc</title>
  <base href="/src/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
    <link href="assets/css/customStyle.css" rel="stylesheet" />

    <script src="/node_modules/core-js/client/shim.min.js"></script>
    <script src="/node_modules/zone.js/dist/zone.js"></script>
    
    <script src="/node_modules/systemjs/dist/system.src.js"></script>
    
    <script src="systemjs.config.js"></script>
    <script>
        System.import('main.js').catch(function (err) { console.error(err); });

    </script>
</head>
<body>
  <app-initializer></app-initializer>
</body>
</html>

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
