### ISSUE TITLE
Custom datepicker popup button

### ISSUE THREAD

**Issue by vondwater** [angular-ui/bootstrap#6687]
I'm trying to have a datepicker popup with an extra button. I can add the extra button with a custom template. That part works, but now i want to select a date when I click on the button. I already tried to use select('2018-03-15', $event) but that does not work. 
I think the select needs a real date object but how can I achieve that without needing to edit the directive code?

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
