### ISSUE TITLE
typeahead focus will re-trigger in some time. 

### ISSUE THREAD

**Issue by simssims** [angular-ui/bootstrap#6688]
Hi,
When I select a value from typeahead and click the next field, typeahead field is re-focusing again automatically (cursor jumping) due to timeout functionality. When I check the codes, timeout function can be removed from focus-out functions because "$rootScope:inprog" issue is not raised if timeout is removed. Appreciate for your help. 

      //return focus to the input element if a match was selected via a mouse click event
      // use timeout to avoid $rootScope:inprog error
      if (scope.$eval(attrs.typeaheadFocusOnSelect) !== false) {
        $timeout(function() { element[0].focus(); }, 0, false);
      }

I just use "element[0].focus();" and it works with no issue.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
