### ISSUE TITLE
unable to get multi-select uib-dropdown to work

### ISSUE THREAD

**Issue by robeverett** [angular-ui/bootstrap#6690]
# PLEASE READ

As per the [README](https://github.com/angular-ui/bootstrap/blob/master/README.md), this project is no longer being maintained.  Any issues entered will remain uninvestigated and unresolved.

We thank you for your contributions over the years.  This library would not have been successful without them.

**Comment by robeverett** [comment]
I am unable to find a complete example on the internet which matches my use case.

I am almost there with it, but I need the controller logic (event handling) and the css styling that shows that multiple items are selected.

```
<div class="btn-group"
     uib-dropdown
     auto-close="outsideClick"
     on-toggle="toggled(open)"
     keyboard-nav>
  <button ng-disabled=thisDisabled
          id="simple-btn-keyboard-nav"
          type="button"
          class="btn btn-xs btn-default ssDropdown_button"
          uib-dropdown-toggle>
    {{thisSelectedValue}} <span class="caret"></span>
  </button>
  <ul class="dropdown-menu status-select"
      style="overflow-y:auto;height:200px;"
      uib-dropdown-menu
      role="menu"
      aria-labelledby="simple-btn-keyboard-nav">
    <li class="ssDropdown_li"
        ng-repeat='row in vm.plannedEmployees | orderBy: row.employeeName'>
      <div ng-click="vm.employeeSelectClick(row, $event)"
           style="white-space: nowrap;">
        {{row}}
      </div>
    </li>
  </ul>
</div>
```
...in my controller:

```
vm.employeeSelectClick = function(emp, $event) { 

....

};
```

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
