### ISSUE TITLE
Uirating default view big

### ISSUE THREAD

**Issue by mota57** [angular-ui/bootstrap#6692]
# PLEASE READ

This is how it looks it suppose to look like in the website. Take a look at the plunker. I tried to use $("svg").attr("width", 30) to handle this but when you hover it, it goes back to this big giant start. 
https://embed.plnkr.co/7uAxPx9SsSJFldAvej4u/

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
