### ISSUE TITLE
angular1-ui-bootstrap4 popover is missing arrow

### ISSUE THREAD

**Issue by mindej** [angular-ui/bootstrap#6694]
Hi in angular1-ui-bootstrap4
popover template is wrong as it is missing `<div class="arrow" style="top: 34px;"></div>` div in template.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.

**Comment by icfantv** [comment]
Also, you have the wrong project.
