### ISSUE TITLE
Can comment/css class directives be safely disabled in an app which uses angular-ui/bootstrap?

### ISSUE THREAD

**Issue by lukaszprus** [angular-ui/bootstrap#6695]
I need to find answer to this question:

https://stackoverflow.com/questions/48888310/do-angularjs-and-and-angular-ui-bootstrap-have-their-own-comment-css-class-direc

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
