### ISSUE TITLE
$rootScope:inprog: $apply already in progress

### ISSUE THREAD

**Issue by rukhsarneyaz** [angular-ui/bootstrap#6696]
I am getting $apply already in progress error using uib-typeahead. I have a input field in my project with uib-typeahead. If I search for something and the typeahead suggestion popover is open and then I click on another div outside which has a ui-sref - then I get this error on console. 

When I saw the line which produces error in the `ui-bootstrap-tpls.js:7170` - $apply is used on blur without $timeout and that is causing the issue. ui-sref calls for another $apply and blur function calls for $apply. 

![screen shot 2018-03-13 at 4 25 35 pm](https://user-images.githubusercontent.com/37352489/37375049-32c45f9a-26db-11e8-995e-fd5ff7484569.png)

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
