### ISSUE TITLE
Doesn't work in Bootstrap 4.0.0

### ISSUE THREAD

**Issue by pengleichen** [angular-ui/bootstrap#6697]
For modal, the ui bootstrap doesn't work for the Bootstrap V4.0.0.
V3.3.7 
.fade {...} .fade.in{}
V4.0.0
.fade{} .fade.show{}, Don't use the class 'in'
 Could you please fix it, thanks very much!

**Comment by OlympicLarry** [comment]
This project is finished.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
