### ISSUE TITLE
Add $destroy for keydown events

### ISSUE THREAD

**Issue by scott56gps** [angular-ui/bootstrap#6701]
I have multiple dropdowns in one container using `keyboard-nav`.  When I click on one dropdown, the keyboard navigation works fine.  When I click on another dropdown while the first dropdown is open, It skips elements in the dropdown when using the keyboard.  I think this may be due to a scope.on $destroy function not being supplied for `keydown` events.

**Comment by scott56gps** [comment]
#6314
44ab0a8

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
