### ISSUE TITLE
Angular uib-tabset/uib-tab wrong ActiveTab index if tabs are created dynamically

### ISSUE THREAD

**Issue by PoornimaK02** [angular-ui/bootstrap#6710]
Hi All,

   Please help us with one of the major issue of active tab index in tabset. Below is our requirement, and active tab index is used works fine if the tab created are later the current index.

   There is a list of array with Name,Sortorder which is used to bind the tab here with order according to Sortorder column. This array is dynamic and sortorder is preset already. 

   In DB
Name Sortorder
A        1
B        2
C        3
D        4

   From the application user can add any name at any point of time. Like D first then B then C. so on every add completion, the array list is appended and ordered with sortorder column and keep the current active index as intact as the same tab should be open eventhough other tabnames are added. Everything works fine untill we add names like B first, C then , D later. But if the sequence followed is different, the active tab index generated goes wrong somehow(it always take +1 of the current scope ) with which to show current active tab as open is not working for us.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
