### ISSUE TITLE
Typeahead result set to uppercase

### ISSUE THREAD

**Issue by BMK91** [angular-ui/bootstrap#6711]
Hi guyz,

How do I set uib-typeahed result to uppercase from HTML view only. I don't care of any result from controller, but on the view it should be in uppercase.

I'm not able to do the given search result to uppercase.
Here is [attached](https://plnkr.co/edit/gT0hoQIM2rlnXFWCGysf?p=preview) plunker.

**Comment by mendeza** [comment]
Please ask such questions in the appropriate place: https://stackoverflow.com/questions/tagged/ng-bootstrap

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
