### ISSUE TITLE
Typeahead won't allow non-search result values

### ISSUE THREAD

**Issue by robeverett** [angular-ui/bootstrap#6712]
I can only enter a value which matches one of the search results.

How do I allow the user to enter their own text (and not just select from the results ?)
How do I prevent the "No Matching Records" popping up, is there an event I can handle for that ?

formatMatches = (value: any) => value.EmployeeName;
        engageIDs = (value: any) => value.EngageID;

        searchEmployee = (text$: Observable<string>) =>
          text$.pipe(
            debounceTime(200),
            distinctUntilChanged(),
            tap(() => this.searching = true),
            switchMap(term => 
              this.engageService.search(term).pipe(
                tap(() => this.searchFailed = false),
                catchError(() => {
                  this.searchFailed = true;
                  return of([]);
                }))
              ),
              tap(() => this.searching = false)        
          )

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
