### ISSUE TITLE
Pagination UI Bootstrap 4 for AngularJS and JSON.

### ISSUE THREAD

**Issue by dsagredo** [angular-ui/bootstrap#6714]
Hello

I have a problem can you help me?,  using Angular filter with pagination ui bootstrap 4.
This works fine and filters the items perfectly.The problem arises because I am using displayItems with a uib-pagination element. The pagination uses totalItems instead of displayItems.

Obviously I need to somehow apply the filter on the total-items, then create the displayItems, and put the filteredItems in the uib-pagination.

I'm not sure how to do this. Any thoughts? All help much appreciated...
https://next.plnkr.co/edit/sq5JBcPgh6Nr7ZNU?preview

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
