### ISSUE TITLE
Controller 'uibTabset', required by directive 'uibTabContentTransclude', can't be found!

### ISSUE THREAD

**Issue by baj84** [angular-ui/bootstrap#6715]
Hi,

I'm using angular 1.7 with redux and a component architecture.

I have a component which is using ui-tabs and is then included in another view via it's component name.
e.g. `<my-tab-component></my-tab-component>`

It works fine, until on state change it throws this error.
_Controller 'uibTabset', required by directive 'uibTabContentTransclude', can't be found!_

I believe this issue is related to [#5350](https://github.com/angular-ui/bootstrap/issues/5350)

But since the post angularjs has introduced components, so i'm hoping someone has got it working with them?

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
