### ISSUE TITLE
Collapsible panel with multiple tiles

### ISSUE THREAD

**Issue by kopreshk37** [angular-ui/bootstrap#6718]
I want to achieve something like this. Is this possible..?? if yes.. can you please tell me which library i can use and a similar example / demo would be great.

Thanks
![capture](https://user-images.githubusercontent.com/10919947/47765115-7058e000-dcee-11e8-83ac-08cf6bdc6db2.JPG)

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
