### ISSUE TITLE
How to use the Angular Bootstrap Popover in AngularUi calendar?

### ISSUE THREAD

**Issue by nitingupta220** [angular-ui/bootstrap#6723]
In my application, I'm using AngularUi calendar to show my events. 
I want to show a popover when someone clicks with the event details in it.
I can't find any solution where someone is using Angular Bootstrap popover with AngularUi calendar.

Everyone is using Popover on button click but I want to use it with AngularUI calendar from my JS code.

Any suggestions on how to do it?

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
