### ISSUE TITLE
how to focus textarea everytime I open modal 

### ISSUE THREAD

**Issue by webosmotic-developer** [angular-ui/bootstrap#6725]
# PLEASE READ

As per the [README](https://github.com/angular-ui/bootstrap/blob/master/README.md), this project is no longer being maintained.  Any issues entered will remain uninvestigated and unresolved.

We thank you for your contributions over the years.  This library would not have been successful without them.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.
