### ISSUE TITLE
tooltip: "tooltip-trigger" to use for Mobile sites?

### ISSUE THREAD

**Issue by montlebalm** [angular-ui/bootstrap#679]
I'm having trouble figuring out which tooltip trigger I should use for a mobile site. Here's what I've tried so far:
- "click" works, but you have tap on the element again to make it disappear.
- "blur" doesn't work at all.
- "mouseenter" makes the tooltip appear, but I don't see any way to make it disappear.

I hope I'm missing something simple, but so far it has eluded me.

Thanks.

**Comment by johannesjo** [comment]
For everyone who is wondering why closing on iOS doesn't work, you need to set the css property `cursor` to `pointer` for an element to have click interaction (in this case the body). Have a look here:
http://stackoverflow.com/questions/3705937/document-click-not-working-correctly-on-iphone-jquery
