### ISSUE TITLE
Tooltip does not work inside repeat with dynamic value

### ISSUE THREAD

**Issue by chriscantu** [angular-ui/bootstrap#69]
Hello...

When I try the following, the column value (user.firstName) never displays.  When I remove the tooltip directive, it reappears.  I also tried displaying a hard coded value and the tooltip reappears although it was not displayed in the correct location.  (This may be due to the fact, that I am rendering a template).  

```
<tr ng-repeat="user in users | filter:myFilter | orderBy:predicate:reverse">
    <td>....</td>
    <td><a><span tooltip-placement="right" tooltip="Some Text">{{user.firstName}}</span></a></td>
</tr>
```

Please let me know if made a mistake.  
Thanks!

Chris

**Comment by eeerrrttty** [comment]
Same issue here... I remove the "ng-repeat", then it works, i put it again, it stop working, it works, then it stop working....

**Comment by adriangordon1231** [comment]
@eeerrrttty try putting the dynamic value in curly braces .
uib=tooltip= "{{ data.value }}
