### ISSUE TITLE
Google place autocomplete does not work inside modal

### ISSUE THREAD

**Issue by srour** [angular-ui/bootstrap#693]
The google places autocomplete input box works great in angular. However, when the input box is inside an angular ui bootstrap modal it stops working. 

The workaround is to use $(#modaldiv).show() on the modal.

**Comment by wisewins** [comment]
http://plnkr.co/edit/irQiP6waYf5kE6B4NCBe?p=preview

Put out a plunker. Reason for autocomplete not working is becuase of Z-index. Latest version of bootstrap addresses this issue

**Comment by bencochrane1** [comment]
This fixed is for me:

**Comment by pwharff** [comment]
@bencochrane1 Thank you sooooo much, this was exactly the fix I needed.

**Comment by sankeeta** [comment]
@bencochrane1 Thank you very much 💯

**Comment by unicorn-in-training** [comment]
Thank you so much!! Worked perfectly for me too. Who knows how long I otherwise would've spent trying to troubleshoot this otherwise!

**Comment by augustplaninsek** [comment]
@bencochrane1 Thank you... I've been working on this problem for few hours. Thank you very much

**Comment by Sachin124** [comment]
> This fixed it for me:
> 
> `.pac-container { z-index: 100000; }`
> 
> http://stackoverflow.com/questions/27005608/angularjs-ui-bootstrap-modal-with-google-places

Thank You So much it's working like magic.
