### ISSUE TITLE
bug(tooltip): strange behaviour with table row hover.

### ISSUE THREAD

**Issue by michaelhunziker** [angular-ui/bootstrap#712]
Hi all!

I'm using tooltips and dropdown menus in a table. I wrote a directive that displays a "settings" icon on the left side of the table row once the user hovers over the row. There's also an info-icon left of it, which provides additional infos within a tooltip:

http://jsfiddle.net/akA6H/39

You'll notice that when you hover over the info-icon of row 2 (middle), the tooltip will show up. But, if you quickly hover over the tooltip you get a strange behaviour (the icons in row 2 won't disappear...). The problem occurs with Chrome. IE 10 seems to work fine. When I don't use tooltips, everything works fine in Chrome! 

I'd really appreciate some thoughts on my solution. Maybe I've done it completely wrong. Or is there maybe an issue with the tooltip-directive?

This is the directive i wrote (see also jsfiddle above):

```
.directive('showOnRowHover',

function () {
    return {
        link: function (scope, element, attrs) {

            element.closest('tr').bind('mouseenter', function () {
                element.show();
            });
            element.closest('tr').bind('mouseleave', function () {
                element.hide();
                var contextmenu = element.find('#contextmenu');
                contextmenu.click();

                element.parent().removeClass('open');
            });
        }
    };
})
```

This is how i use it (notice: the tooltip, which obviously causes the trouble is also in there!):

```
<td> 
    <div show-on-row-hover style="display:none;">
        <i tooltip-popup-delay="0"
            tooltip-placement="top"
            tooltip="Some tooltip text"
            class="icon-info-sign"></i>
    </div>
    <div show-on-row-hover style="display:none">
        <ul show-on-row-hover style="display:none;" class="nav">
            <li id="contextmenu" class="dropdown pull-right">
                <a class="btn-link dropdown-toggle">
                ....
```

Any ideas how I could work around this? I really need these tooltips...

Cheers
Michael

**Comment by samuelcastro** [comment]
@pkozlowski-opensource Thanks, fixed here. +1

**Comment by jitendersandhu** [comment]
@pkozlowski-opensource tooltip-append-to-body="true" works for me too. i was facing the same issue with row hover not working when there is tooltip. On mouseleave, the row was still remaining highlighted, when there was a tooltip on one of the row elements. Thanks for the suggestion!
