### ISSUE TITLE
Trigger typeahead manually? Is that possible?

### ISSUE THREAD

**Issue by artworkad** [angular-ui/bootstrap#759]
In my app the user may send a request for his position. When the position information is retrieved the data is populated to an input field which has the typeahead directive

```
document.getElementById('city').value = input;
```

But I want the typeahead to start and to search if the city is available in the typeahead resource. Is this possible?

**Comment by segevofer** [comment]
focus event was a overhead for me, and i used click event - because focus occurred also after selection.. 
(i also overloaded the 'typeahead' directive itself)

app.directive('typeahead', function () {
    return {
        require: 'ngModel',
        link: function (scope, element, attr, ctrl) {
            element.bind('click', function () {
                ctrl.$setViewValue();
            });
        }
    };
});

**Comment by segevofer** [comment]
focus event was a overhead for me, and i used click event - because focus occurred also after selection.. 
(i also overloaded the 'typeahead' directive itself)

```javascript
app.directive('typeahead', function () {
    return {
        require: 'ngModel',
        link: function (scope, element, attr, ctrl) {
            element.bind('click', function () {
                ctrl.$setViewValue();
            });
        }
    };
});
```

**Comment by jbmyid** [comment]
I tried above but could not make it work

**Comment by robbse** [comment]
For everyone having the same issue, the following example works for me.

```javascript
angular.module('app').directive('typeahead', typeaheadWatchChanges);

  typeaheadWatchChanges.$inject = ["$timeout"];

  function typeaheadWatchChanges($timeout) {
    return {
      require: "ngModel",
      link: function (scope, element, attr, controller) {
        scope.$watch('vm.model', function (value) {
          if (value) {
            element.focus();
            var old = controller.$viewValue;
            controller.$setViewValue('');
            $timeout(function () {
              controller.$setViewValue(old);
            });
          }
        });
      }
    };
  }
```

**Comment by jusopi** [comment]
I finally got this working after quite a bit of hassle with the aforementioned proposed solutions.  These were the scenarios that I had to have this working for:

- user clicks inside input to trigger opening of dropdown for:
  - existing values on model
  - when model is undefined/blank
  - when existing model value is a number

Sorry this is in Coffeescript.... should be self explanatory however.

```
.directive 'typeaheadClickOpen', ($parse, $timeout)->
    dir =
        restrict: 'A'
        require: 'ngModel'
        link: ($scope, elem, attrs)->

            triggerFunc = (evt)->
                ctrl = elem.controller 'ngModel'
                prev = ctrl.$modelValue || ''
                ctrl.$setViewValue if prev then '' else ' '
                if prev then $timeout -> ctrl.$setViewValue "#{prev}"

            elem.bind 'click', triggerFunc
```

In order to trigger the dropdown when the value was blank/undefined I set to an empty space `' '` as the UI renders blank/undefined as `''` already.  It's not ideal because `' ' != ''` and not sure how that would present in validation cases.  

Another thing to note is for those model values that were numbers, I had to cast the `prev` values as a string ergo the `"#{prev}"` bit on the timeout. 

It's disappointing to see such a huge need for exposing an API of sorts to trigger the dropdown and after nearly 2 years there is still no library solution.

**Comment by jbmyid** [comment]
@jusopi thanks worked for me :+1:

**Comment by kennethlynne** [comment]
@jusopi thanks for sharing!

And you know, this is open-source, and when people like you do not send a pull request with a proposed solution, then there won't be no library solution :dancer:

**Comment by irsick** [comment]
Here is decaffeinated directive by @jusopi just in case.
Tested on Angular 1.4.3 / UI Bootstrap 0.13.0

```javascript
  .directive('typeaheadClickOpen', function($parse, $timeout) {
      return {
          restrict: 'A',
          require: 'ngModel',
          link: function($scope, elem, attrs) {
              triggerFunc = function(evt) {
                  var ctrl = elem.controller('ngModel'),
                      prev = ctrl.$modelValue || '';
                  if (prev) {
                      ctrl.$setViewValue('');
                      $timeout(function() {
                          ctrl.$setViewValue(prev);
                      });
                  } else {
                      ctrl.$setViewValue(' ');
                  }
              }
              elem.bind('click', triggerFunc);
          }
      }
  })
```

**Comment by jusopi** [comment]
@kennethlynne I didn't consider sending a pull request because the issue is closed as of Aug 5th 2013.  That and the fact that there are a few other similar feature requests that have been largely ignored by the project owner(s), didn't figure it worth the effort.

**Comment by superxp1412** [comment]
@kazeno Thank you.
Your solution saved my time.

**Comment by knitevision1** [comment]
@kazeno thanks, nice solution. I'd also add this to the condition `element.val().length && !element.is(':focus')` so that if the input is already focused the fetch won't happen again.

**Comment by jbmyid** [comment]
@jusopi  Got one issue in IE, when used above directive, its being opened but when clicked on the item its doesnt select anything.

**Comment by jusopi** [comment]
@jbmyid the project I developed my solution for does not support IE at all.  We're targeting Chrome and FF exclusively.  Sorry.

**Comment by jbmyid** [comment]
@jusopi np Thanks, we were also not supporting just started now so got the issue :)

**Comment by piyush-dholariya** [comment]
Hi All,
I want to use Typeahead functionality to get ajax call on time interval but I do not want to show list of items's pop up. How can I prevent to show that popup?

**Comment by jusopi** [comment]
@piyush-dholariya this is something you should ask on stackoverflow, not in the repo's issues.

**Comment by stefansandulescu** [comment]
Having http://stackoverflow.com/questions/24764802/angular-js-automatically-focus-input-and-show-typeahead-dropdown-ui-bootstra as a source of inspiration I created the following directive:
`
function typeaheadShowOnFocus() {
        return {
          require: 'ngModel',
          link: function($scope, element, attrs, ctrl) {
            element.bind('focus', function() {
              ctrl.$setViewValue();
              $(element).trigger('input');
              $(element).trigger('change');
            });
            ctrl.$parsers.unshift(function(inputValue) {
              var value = (inputValue ? inputValue : '');
              ctrl.$viewValue = value;

              return value;
            });
            ctrl.$parsers.push(function(inputValue) {
              return inputValue === '' ? '' : inputValue;
            });
          }
        };
      }
`
I hope it helps someone

**Comment by dasaanudeep** [comment]
@jusopi Thanks for the directive, it works for me.

**Comment by wujunbin** [comment]
@robbse Thx for your code, it works for me.

**Comment by denesreyes** [comment]
The following works fine:
// Notice $element and $timeout is injected.
function promptTypeAhead(id, value) {
    var element = document.getElementById(id);
    $timeout(function () {
        var control = $element.find(element).controller('ngModel');
        control.$setViewValue(''); // Replicate an on change event
        control.$setViewValue(value);
        control.$render();
    }, 0);
}

Credit: @kennethlynne

**Comment by bikrantsharma** [comment]
Hi - so i am using this to open the typeahead on click of a button (latest angular bootstrap ui)

Here's my Test Scenario:

1. select a value from drop down
2. Click on the button
3. Typehead opens up with the filtered value.

Problem is that to focus on dropdown..we are resetting the selected value to '' in setviewvalue..and that removed the selected value. is there a way around it? 

Also, if we set the value to 'prev' the dropdown applies the filter and only show the selected value in dropdown.. Is there a way to get away from filter when the button is clicked?

but when the dropdown opens up it applies the currently selected 

.directive('typeaheadClickOpen', function($parse, $timeout) {
      return {
          restrict: 'A',
          require: 'ngModel',
          link: function($scope, elem, attrs) {
              triggerFunc = function(evt) {
                  var ctrl = elem.controller('ngModel'),
                      prev = ctrl.$modelValue || '';
                  if (prev) {
                      ctrl.$setViewValue('');
                      $timeout(function() {
                          ctrl.$setViewValue(prev);
                      });
                  } else {
                      ctrl.$setViewValue(' ');
                  }
       angular.element('#inputId').trigger('focus');
              }
              elem.bind('click', triggerFunc);
          }
      }
  })
