### ISSUE TITLE
Proposition for typeahead : Open suggestion view on focus

### ISSUE THREAD

**Issue by jdecool** [angular-ui/bootstrap#764]
It could be interresting to automatically open the suggestion view when the input field has focus.

It will allow user to see choices it can make when a filter is used and the list is not editable.

What do you think about ?

**Comment by Hotell** [comment]
I've created this custom combobox directive as a workaround. check it out.
works with latest ui-bootstrap 0.12 and angular 1.3.x
http://embed.plnkr.co/ZtuoTVgPLuMWDT2ejULW/preview

**Comment by javiermarinros** [comment]
Any news on this?

**Comment by andrewboni** [comment]
+1 for getting this in

**Comment by callicles** [comment]
+1

**Comment by sheymann** [comment]
+1, it's really useful on short list of options

**Comment by piernik** [comment]
+1

**Comment by cristifilip** [comment]
+1

**Comment by scottrogers** [comment]
+1

**Comment by mattvague** [comment]
+!

**Comment by rvanbaalen** [comment]
**No more +1 comments please** 

That way we can be notified about comments that actually need attention instead of being flooded with +1's

**Comment by Enykey** [comment]
Can you update Angular-UI doc to reflex the fact that typeahead-min-data cannot be 0 and should be 1 or more, please?

**Comment by icfantv** [comment]
@Enykey please feel free to fork the repo and submit a PR.

**Comment by shyamal890** [comment]
This seems to be one of the most sought after feature yet there is no one who's working on it. WHY?!

**Comment by wesleycho** [comment]
@shyamal890 please exercise patience/professionalism - maintaining a large open source project is difficult, and we have many issues that we have to manage with limited resources. Showing impatience will not get us to consider this faster, and only adds noise since instead of working through the backlog of issues, we are being distracted improperly - we are doing the best we can to get through our backlog of issues and systematically address them, and adding noise will only slow down the project more.

**Comment by thesalami** [comment]
Thank you @chenyuzhcy for answering a 2 year waited question with < 10 lines of code!
We all look forward to the next release.

**Comment by gandaldf** [comment]
@chenyuzhcy is there a way to open it programmatically?
for example... if I set focus like this: `element.find('input').focus();` it doesn't popup.

**Comment by Kuroky360** [comment]
+1

**Comment by gandaldf** [comment]
I created a directive that embeds the Typeahead directive and mimics the functionality of a combobox/select:

    .directive('combobox', ['$compile', '$timeout', function($compile, $timeout) {
    var directive = {
        restrict: 'E',
        scope: {
            model: "=",
            item: "@",
            items: "=i",
            onSelect: "&",
            onBlur: "&"
        },
        compile: compile
    };

    return directive;

    function compile(element, attrs) {
        return function(scope, element, attrs) {
            scope.focusing = false;
            scope.first = null;

            scope.open = function() {
                var ctrl = element.find('input').controller('ngModel');

                var temp = scope.model;

                ctrl.$setViewValue(' ');

                $timeout(function() {
                    ctrl.$setViewValue('');
                    scope.model = temp;
                });
            };

            scope.select = function(item, model, label) {
                scope.focusing = true;
                scope.onSelect({item: item, model: model, label: label});
            };

            scope.blur = function() {
                scope.focusing = false;
                scope.onBlur();
            };

            scope.focus = function() {
                if (scope.focusing === false) {
                    scope.focusing = true;
                    element.find('input')[0].focus();
                    scope.first = scope.model;
                    scope.open();
                }
            };

            scope.keyup = function(key) {
                if (key === 27) {
                    scope.model = scope.first;
                    scope.open();
                }
            };

            var template = '<div class="combo combo-static">' +
                           '    <input ng-model="model"' +
                           '           uib-typeahead="' + attrs.item + '"' +
                           '           typeahead-focus-first="false"' +
                           '           typeahead-min-length="0"' +
                           '           typeahead-editable="false"' +
                           '           typeahead-on-select="select($item, $model, $label)"' +
                           '           ng-focus="focus()"' +
                           '           ng-blur="blur()"' +
                           '           ng-keyup="keyup($event.keyCode)"' +
                           '           placeholder="' + attrs.placeholder + '"' +
                           '           type="text"' +
                           '           class="' + attrs.class + '">' +
                           '    <div class="combo-label" ng-click="focus()" ng-hide="focusing">' +
                           '        <span>{{model || "' + attrs.placeholder + '"}}</span>' +
                           '        <i class="fa fa-caret-down"></i>' +
                           '    </div>' +
                           '</div>';
                                    
            element.html(template);
            element.removeClass(attrs.class);
            
            $compile(element.contents())(scope);
        };
    }
    }]);

Here is my plunk: http://plnkr.co/edit/zWN950IxOndlYQHBXdY9?p=preview
Hope it could help someone.

**Comment by santosh-k1** [comment]
Its Easy to add only  $scope.selected = ' '; in your controller.. i have checked with ui-bootstrap-tpls-0.10.0.js and its working fine.

**Comment by icfantv** [comment]
@santosh-k1, I think you may have gotten that version number wrong.  We're currently at version 1.1.1.

**Comment by lin-credible** [comment]
+1

**Comment by icfantv** [comment]
@lin-credible, please do not just add a `+1` to issues.  It adds no intrinsic value to the discussion and serves to only clutter up the thread.  Thanks.

**Comment by mrdulin** [comment]
@santosh-k1 work for me ! Thanks!

**Comment by copiali** [comment]
Any update for this feature? Need it when we need to always show a default option on focus before trigger any search......

**Comment by santosh-k1** [comment]
@copiali below code will help you to resolve the issue.. it has open the value on text box focus:
 `  <input type="text" focus-me="opened" ng-focus="onFocus($event)" ng-show="opened" ng-trim="false" ng-model="selected" empty-typeahead typeahead="state for state in states | filter:$viewValue:stateComparator" class="form-control" />`
```

(function () {
  var secretEmptyKey = '[$empty$]'
  
  angular.module('plunker', ['ui.bootstrap'])
    .directive('focusMe', function($timeout, $parse) {
      return {
          //scope: true,   // optionally create a child scope
          link: function(scope, element, attrs) {
              var model = $parse(attrs.focusMe);
              scope.$watch(model, function(value) {
                  if(value === true) { 
                      $timeout(function() {
                          element[0].focus();
                      });
                  }
              });
          }
      };
    })
    .directive('emptyTypeahead', function () {
      return {
        require: 'ngModel',
        link: function (scope, element, attrs, modelCtrl) {
          // this parser run before typeahead's parser
          modelCtrl.$parsers.unshift(function (inputValue) {
            var value = (inputValue ? inputValue : secretEmptyKey); // replace empty string with secretEmptyKey to bypass typeahead-min-length check
            modelCtrl.$viewValue = value; // this $viewValue must match the inputValue pass to typehead directive
            return value;
          });
          
          // this parser run after typeahead's parser
          modelCtrl.$parsers.push(function (inputValue) {
            return inputValue === secretEmptyKey ? '' : inputValue; // set the secretEmptyKey back to empty string
          });
        }
      }
    })
    .controller('TypeaheadCtrl', function($scope, $http, $timeout) {
      $scope.selected = undefined;
      $scope.states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Dakota', 'North Carolina', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'];
      $scope.opened = true;
      
      $scope.stateComparator = function (state, viewValue) {
        return viewValue === secretEmptyKey || (''+state).toLowerCase().indexOf((''+viewValue).toLowerCase()) > -1;
      };
      
      $scope.onFocus = function (e) {
        $timeout(function () {
          $(e.target).trigger('input');
        });
      };
      
      $scope.open = function() {
        $scope.opened = true;
      }
      $scope.close = function() {
        $scope.opened = false;
      }
    });
}());
```
    
Working Demo Link : Demo http://plnkr.co/edit/bZMEOx0Qwo6VzW7oSuEE?p=preview

**Comment by Ablablab** [comment]
+1
