### ISSUE TITLE
Add i18n to Datepicker

### ISSUE THREAD

**Issue by rsvalerio** [angular-ui/bootstrap#777]
Or, in the meantime, is it possible to translate?

**Comment by vladei** [comment]
@ThCC can you tell us if the angular-translate works in conjunction with the datepicker?

**Comment by rbaarsma** [comment]
It works for the names of days and months, but not the texts Today / Clear / Done

Is there a way to translate this?
I see something in the angular-bootstrap-tpls.js about those texts being constants, so I guess I'm going to figure out how to override them for now.
