### ISSUE TITLE
Datepicker , disable dynamically dates.

### ISSUE THREAD

**Issue by Ostro** [angular-ui/bootstrap#779]
hi, 

i need to disable specific dates into the datepicker.
The problem is that the list date to disable is dynamic and directly depends on user action. 

In my scenario i'm working on a room reservation app, the user chose a room and then i  receive a list of 'already booked date' tha i need to disable in the datepicker.

the disabled date only appears if i change the month (that force the datepicker to rcall adin the disalbing function). Is it possible to manually trigger the datepicker to check again dates ?

**Comment by algil** [comment]
+1 datepicker-popup solution.

**Comment by arjunasuresh3** [comment]
+1

**Comment by vyacheslav-lonschakov** [comment]
still actual

**Comment by AndyDiazValdiviezo** [comment]
+1 datepicker-popup

**Comment by icfantv** [comment]
Please do not only add `+1` to issues without adding anything further to the discussion.  All that does is serve to clutter up the thread.  Thanks.

**Comment by awrico** [comment]
Here is my solution (I had to enable/disable holidays selection + colouring depending on checkbox state):

1. add $scope.$watch() to watch variable bound to checkbox
2. in $watch function write:

  $scope.date = angular.copy( $scope.date ); // $scope.date is ng-model variable of datepicker

In this way the datepicker is forced to re-render itself.
