### ISSUE TITLE
ng-model on datepicker does not work

### ISSUE THREAD

**Issue by garethdjames** [angular-ui/bootstrap#784]
Using the ng-model attribute on the datepicker directive instead of the surrounding tag causes the datepicker to not bind to the model

I have created a plunkr where the the first datepicker has the ng-model attribute on the datepicker and the second where it has it on the surrounding div

http://plnkr.co/edit/EFYBUuDt23U3wHvsD2rG

Note that this issue does not occur in version 0.4.0

**Comment by pawanMindyourfleet** [comment]
I am using bootstrap timepicker in my code and setting value on page load using ng-model

<timepicker ng-model="data.dropTime" ></timepicker>

And loading some html on runtime. Its working fine for me when i set value on page

But when i try to update the value in ng-model it will not reflecting on view side but value is updated in ng-model

Can you help in this.

**Comment by ElanHasson** [comment]
It seems this issue has been resolved, i've updated the plunker from @garethdjames.

http://plnkr.co/edit/2hLMd4KLbAMWxp2EtHXI

**Comment by roshani4** [comment]
in a span class ng-model working or not .
