### ISSUE TITLE
Tabs don't show the pointer cursor

### ISSUE THREAD

**Issue by saua** [angular-ui/bootstrap#851]
When you compare the tabs here:
http://getbootstrap.com/2.3.2/components.html#navs
with the ones on the UI Bootstrap homepage:
http://angular-ui.github.io/bootstrap/#/tabs

You'll notice that the "original" Bootstrap ones show a pointer cursor on non-active, non-disabled tabs, while the UI Bootstrap ones don't.

The only relevant difference in markup that I found was the missing href attribute. And indeed, adding a href (of any value) "fixed" the tabs for me.

I don't know if adding an empty (or "#") href is the correct fix for this, but it worked for me.

**Comment by japharr** [comment]
@topeju Thanks
