### ISSUE TITLE
Templates cannot be loaded

### ISSUE THREAD

**Issue by artworkad** [angular-ui/bootstrap#852]
Hi,

I have a problem using angular-ui when templates are involved. I use symfony2 as my php framework and angularjs for frontend stuff. 

E.g. when I use the dialog I get:

```
mypage.com/template/dialog/message.html 404 not found
```

The problem obviously is that angular ui performs a get request for the template. This request seems to be routed to php and fails because there is no such template in the project file system. I use ui-bootstrap-tpls-0.5.0.min.js.

Any ideas how to deal with this problem?

**Comment by LalitPatadiya** [comment]
I also faced the problem with tpls file and it give me error  "Failed to load template: template/carousel/carousel.html (HTTP status: {1} {2})" 

can you please let me know if you are having any idea why it give me error see below code which i used.

carousel slider :

<carousel interval="myIntervals">
                                <slide ng-repeat="(key, recentinfo) in profilemyrecentgiving" active="slide.active">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class='col-md-5 col-xs-5'>
                                                <div ng-if='recentinfo.contribution_story_id != 0'>
                                                    <img class="cart-story-image" src='[[recentinfo.project_squ_image]]'>
                                                    <img class="cart-storyproject-image" src='[[recentinfo.giving_story_image]]'>
                                                </div>
                                                <div ng-if='recentinfo.contribution_story_id == 0'>
                                                    <img class="impact-history-image" src='[[recentinfo.project_rect_image]]'>
                                                </div>
                                            </div>
                                            <div class='col-md-7 col-xs-7 align-left'>
                                                [[recentinfo.project_title]]
                                            </div>
                                        </div>
                                    </div>
                                </slide>
                            </carousel>

Also added the js file " ui-bootstrap-tpls-0.11.0.min.js " 

can you just look over it and please let me know if you have any idea for the same.

**Comment by icfantv** [comment]
@LalitPatadiya, in general, it's a bad idea to comment on closed issues that are this old as more than likely they'll get missed.  The best thing to do when seeking help is to follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  Please note that when asking for help, it's best to show that you've attempted to solve the problem yourself and also post a minimally working plunker showing the issue.
