### ISSUE TITLE
'Alert' charset UTF-8 - ui.bootstrap.alert

### ISSUE THREAD

**Issue by henriquezago** [angular-ui/bootstrap#860]
I'm having an charset issue. When I put a message like this "Campo [Nome] inválido!", i get this "Campo [E-mail] inv�lido!" on the ui.bootstrap.alert

**Comment by dietergeerts** [comment]
This still is the case.... My text show correctly on other sections of my page, but in the alert I see for example : gecre&#235;erd
![untitled](https://cloud.githubusercontent.com/assets/7393706/9976875/0ecc153c-5ef2-11e5-8a2b-0ee50e7100d1.png)
