### ISSUE TITLE
custom css class in $modal template

### ISSUE THREAD

**Issue by fxck** [angular-ui/bootstrap#892]
I did read this https://github.com/angular-ui/bootstrap/pull/441#issuecomment-23027814 and it never really came to a satisfying conclusion.

The thing is, you won't be changing `template/modal/window.html` 99% of time, what you might need to change quite often is its class.

You might have 3 sets of modals for different cases, all with a different width. And since width is defined on the parent(`.modal`), how could do it?

The `dialogClass` option as it was in the old $dialog made imho perfect sense.

**Comment by shashikantj** [comment]
@vanslly there is a size option for modal
```javascript
$modal.open({
  controller : 'myModalController',
  size : 'lg',
  ...
})
```
