### ISSUE TITLE
typeahead list - don't auto select / highlight first item

### ISSUE THREAD

**Issue by thnk2wn** [angular-ui/bootstrap#908]
Need a way to be able to not auto "select" / highlight the first match in the typeahead list. There are workarounds for direct use of bootstrap such as below. We can make custom changes in our copy of angular ui bootstrap typeahead but then we can't easily upgrade later.

http://stackoverflow.com/questions/9564977/bootstrap-typeahead-dont-autoselect-first-item

http://bibwild.wordpress.com/2013/04/04/overriding-bootstrap-typeahead-to-not-initially-select/

**Comment by ionox0** [comment]
+11

**Comment by icfantv** [comment]
@ionox0, please do not simply add `+1` to issues without additional information that would benefit the conversation.  only adding the `+1` adds no intrinsic value and only serves to clutter up the thread.

**Comment by MaddyMastering** [comment]
+1

**Comment by Artistan** [comment]
+1 shows that there is additional people that would use the same solution if it was provided, how is this a bad thing. 

To be specific, I would use it to allow for our search to just jump to the advanced search vs. having an autocomplete jumping to a page or other filtered advanced search based on the selected value (click on, not Enter). Enter would just "do a search"

**Comment by Artistan** [comment]
https://codepen.io/Artistan/pen/LywrXj

This makes a dataset based on the current input query be the first option.
