### ISSUE TITLE
Typeahead changes input display value with model (array of objects) 

### ISSUE THREAD

**Issue by destegabry** [angular-ui/bootstrap#981]
I have an array of id-value objects, I want my typeahead to let the user to select a value while having its id in the model (as I can do in select directive with the 'select as label for value in array' expression).
The typeahead displays values correctly while I'm typing, but when I select one from the dropdown list I get its id in the input box:
http://plnkr.co/edit/AMV7OaRMaYkq4UIhL7cP?p=preview

Any help?

**Comment by pkarikh** [comment]
@pkozlowski-opensource am I right that because of this bug there is no way to use ng-model-options getterSetter something like that?
`<input type="text" class="form-control" 
                id="elem-{$ $id $}" ng-model="value.value"
                ng-model-options="{ getterSetter: true }"
                typeahead="option for option in value.getOptions()">`

**Comment by pkarikh** [comment]
Also, may be this bug is related: https://github.com/angular-ui/bootstrap/issues/3258

**Comment by MuraliM** [comment]
@pkozlowski-opensource  could you please give an update on using typeahead-input-formatter with ajax based results? I too have the similar problem mentioned by @krimhorn 

Your inputs are highly appreciated! Thanks in advance

**Comment by lokeshjainRL** [comment]
We have workaround for this issue, hope this will help someone.

```javascript
Category //service
.getAllSubCategories()
.then(function categoryResolve(data) {
        vm.options.allSubCategories = data;
        return data;
 }) //First get all the data requited to make typeahead options and then trigger the model change
.then(function (data) {
        var temp = $scope.model;
        $scope.model = null;
        $timeout(function () { //Needed to notify about the change.
          $scope.model = temp;
     });
});
```
Till then waiting it to get resolved.

**Comment by pkarikh** [comment]
@lokeshjainRL maybe there is another fix for it, jfyi. https://github.com/angular-ui/bootstrap/pull/3865

**Comment by lokeshjainRL** [comment]
Thanks, this looks nice and simple approach.

On Wed, Aug 19, 2015 at 7:20 PM, Paul <notifications@github.com> wrote:

> @lokeshjainRL <https://github.com/lokeshjainRL> maybe there is another
> fix for it, jfyi. #3865
> <https://github.com/angular-ui/bootstrap/pull/3865>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/bootstrap/issues/981#issuecomment-132605356>
> .
>



-- 
Lokesh kumar Jain
*ReachLocal Services Pvt. Ltd.*
5-B | Express Zone Towers  |  Patel Vanika |  Western Express Highway |
Goregaon (E) | Mumbai – 400097
www.reachlocal.com | www.reachservices.co.in

**Comment by mgibas** [comment]
the simplest workaround for that is to use ```typeahead-input-formatter``` and ```typeahead-on-select``` combined:

````html
<input  typeahead="obj.id as obj.name for schema in vm.getMatches($viewValue)"  
typeahead-on-select="vm.onSelectedCallback($item, $model, $label)" 
typeahead-input-formatter="vm.formatLabel($model)"/>
````
```javascript
vm.onSelectedCallback = function ($item, $model, $label) {
    vm.selectedItem = $item;
}
vm.formatLabel = function () {
    return vm.selectedItem.name;
};
```

Maybe its also something promising for a fix :)

**Comment by marcodpt** [comment]
Working with an array of objects with a schema like this {id: 45, value: 'Test'}. I would like to see value on the screen and id on the model.... Ok, everyone wants this... So if you use correct input-formatter you can achieve this IF YOUR DATA ARRAY IS ALREADY LOADED... I mean that if your data is async default values wouldn't work correctly... and this is a real problem for me... So after a long series of tries i found a solution and I thought would be nice to share with others.... 

Solution: Use ng-if on typeahead element and while the array is empty switch the element for a simple text input.. this remove typeahead from dom and only when your array is loaded it calls input-formatter.

**Comment by krimhorn** [comment]
I've used that "hack" on a couple of other similar issues regarding async GETs and initialization. Didn't think to apply it to the typeahead though. Thanks for the verification that it will work there too. Much better than doing a temp value and forcing a $digest cycle.

**Comment by shyamal890** [comment]
@mgibas Your solution works. However, there is one problem, this would not work if the user entered the value manually or pasted the value.

**Comment by wesleycho** [comment]
Closing, as this should be addressed with the `ng-model-options="{getterSetter: true}"` support, already in the past couple of releases.

**Comment by pcalves** [comment]
@wesleycho Is there a working example anywhere of the `ng-model-options="{getterSetter: true}"` support mentioned in your last comment?

**Comment by DevSom** [comment]
Hello Everyone ,

I have a response data of country  in CountrylistResponse and based on the selection of country I have to update the Code value in other json which is ProjectdataRepsonse 
CountrylistResponse :  {"name": "Australia", "code": "AU"}, {"name": "Austria", "code": "AT"},{"name": "Azerbaijan", "code": "AZ"}
ProjectdataRepsonse:{ "Country": "","CountryCode": ""}.
 
input tag has following code
                       <input  type="text"  typeahead-on-select="onCountrySelect($item)" placeholder="enter a country"  ng-model="data.CountryCode" typeahead="countrydemo.code as countrydemo.name for countrydemo in countrydata  | filter:$viewValue | limitTo:8" typeahead-input-formatter="formatCountryLabel($model)">

$scope.formatCountryLabel = function(model) {
                for (var i = 0; i < $scope.countrydata.length; i++) {
                    if (model === $scope.countrydata[i].code) {
                        return $scope.countrydata[i].name;
                    }  }  }

I am able to update the CountryCode value based on the selection . After updating the CountryCode data is sent to database , but when I am fetching the data back I am not able to show correct value in input box because my ng-model refer to data.CountryCode but while showing the data I have to show value in data.Country. 

Please let me know how we can solve this issue.
